CenterForOpenScience/osf.io

framework/auth/views.py
website/landing_pages.py
website/routes.py
website/templates/public/login.mako
website/templates/public/login_landing.mako
website/templates/public/pages/getting_started.mako
website/templates/public/pages/help/addons.mako
website/templates/public/pages/help/user_profile.mako
website/templates/public/pages/help/view_only.mako

This PR is in support of a marketing email that is scheduled to be sent on Wednesday, so I've made it a hotfix.

[hotfix] Email landing pages

---

website/static/js/privateLinkTable.js

Fix SWF include path for ZeroClipboard.

---

website/addons/dataverse/views/crud.py

hotfix: Detect file extension in Dataverse file renderer.

---

scripts/populate_conferences.py

Add APS and ICPS conferences; see #1467 for details.
@sloria: need to run `populate_conferences` for changes to take effect.
Resolves #1467.

Add APS and ICPS conferences.

---

scripts/populate_conferences.py

hotfix/Add MPA2015 conference.

---

website/templates/project/register.mako

Fix for https://trello.com/c/TXyquW1V/129-attempt-to-register-project-gives-unable-to-resolve-error

Fix registration asset path.

---

webpack.prod.config.js

Fix uglify config for conference page (again).

[feature fix ] Fix uglify ignore regex.

---

main.py
website/settings/defaults.py
website/util/__init__.py

Restart the Flask app when `webpack-assets.json` changes. Not urgent--will just make local development a little easier.
h/t @brianjgeiger

Restart Flask app when asset hashes change.

---

website/templates/public/pages/meeting.mako

Resolves #1471; see issue for details.

Hide submission info for inactive conferences.

---

scripts/populate_conferences.py

Added the NC Cognition Conference. Would love it if this got added swiftly.

[Presentation Service]: NC Cognition Conference

---

website/static/js/fangorn.js

Fixes this trello card: https://trello.com/c/tEB0O367
Changed the pointer icon on project overview page to link icon
None.

Fix pointer icon in project overview

---

website/static/css/site.css

Minor but very visible issue when the active component would get the grey style momentarily.
Added the focus mode to the background style for uniformity
Since this change has high specificity there shouldn't be any.

Fix ui navbar css on focus

---

website/addons/github/static/githubFangornConfig.js

Purpose
-----------
Fixes a typo in the dialog box for deleting files in a file grid
Changes
------------
Fixes a typo in the dialog box for deleting files in a file grid (irreversible instead of irreversable)
Side effects
If there are, I will be very sad.
Fixes https://trello.com/c/rEH15pGs

0.24.0/irreversible file deletion dialog

---

website/static/js/crossOrigin.js

Disable xhook if not MSIE.

---

website/templates/public/pages/faq.mako

Purpose
------------
Fix extra line break in the FAQ page
Change
----------
Removed a closing p tag
Side effects
Probably famine in Illinois. 
Fixes https://trello.com/c/7vwVwMuS

0.24.0/faq line break

---

framework/mongo/handlers.py
website/addons/osfstorage/model.py
website/addons/osfstorage/tests/test_models.py
website/addons/osfstorage/views.py
website/static/js/fangorn.js

Resolve race condition on concurrent uploads to OSF Storage. Needs to be tested on staging before merge.

Feature fix/osfstorage race condition

---

website/addons/osfstorage/static/storageRevisions.js
website/addons/osfstorage/utils.py
website/addons/osfstorage/views.py

Fixes https://trello.com/c/vl47pGrC
Fixes https://trello.com/c/SOo9KYdy
Fixes regression that broke deleting OSF Storage files from file detail page

Feature fix/download counts

---

website/static/js/fangorn.js
website/static/js/pages/project-dashboard-page.js

Adds github branch selector (or any other addon's customization) to project dashboard.

[feature] project dashboard github branch selector

---

website/static/js/pages/project-dashboard-page.js

Show sorting icons on the file grid at project overview page. 
Fixes trello card: https://trello.com/c/CYeT87nl   Checkbox item 1. 
Turned the sorting option from false to true
None. 
Tested it in Chrome, Safari and Firefox.

Show sorting on project overview pages

---

website/static/js/fangorn.js

Fixes https://trello.com/c/sTVziRai/219-upload-files-to-registration-upload-pending.

Hide delete and upload UI on registrations.

---

website/addons/figshare/templates/figshare_view_file.mako
website/addons/figshare/views/crud.py
website/addons/osfstorage/static/storageRevisions.js

Note: contains another fix that has its own PR I messed up the branching but the contained fix is good to go.

When deleting a file in osf storage show just the name not the full path

---

website/static/js/projectorganizer.js

Fix a minor error reported in this Trello card: https://trello.com/c/8DpojqoR
Change tooltip text to what is on production
None.

Change PO tooltip "go to project" text to "go to page"

---

website/static/js/fangorn.js

No longer increment download counts in fangorn. Refresh the page for the real count.
Fixes https://trello.com/c/TN3AVKJg

[Feature] Fangorn download counts

---

website/static/css/onboarding.css

Purpose
-----------
Make the onboarder line up with the project organizer action bar
Changes
------------
Adjusted the bottom margin of the tab bar
Side effects
Slightly increased solar activity offset by increase in solar-blocking gasses in the atmosphere. Overall a wash.
Fixes https://trello.com/c/dWAq8Y2U

0.24.0/fix-onboarder-spacing

---

website/static/css/fangorn.css
website/static/js/fangorn.js

Change delete button cursor to pointer
Change CSS that applies to this button only, or all delete button within the rows
None.

Fix delete button cursor change to pointer

---

website/addons/dataverse/static/dataverseFangornConfig.js
website/static/js/fangorn.js

Resolves https://trello.com/c/yIvXdUlt/260-dataverse-no-delete-confirmation-modal.

Show prompt before deleting Dataverse files.

---

website/static/js/fangorn.js

Fix casing.

---

requirements.txt

Fixes https://trello.com/c/xxy9ahyo

Use the latest version of furl for unicode support

---

website/util/rubeus.py

Unescape ampersands for niceness until mako html safe

---

website/static/js/crossOrigin.js

[feature] ie 10 uploads fix

---

website/addons/osfstorage/views.py

Fixes rendering PDFs, PDBs in IE.

Bypass what seems to be a bug in WaterButler CORS.

---

website/addons/figshare/static/figshareFangornConfig.js
website/addons/github/static/githubFangornConfig.js
website/static/js/fangorn.js

IE does not support uploads, nicely handle that and inform the user

[Feature] Handle IE 9 uploads

---

website/addons/dataverse/static/dataverseFangornConfig.js
website/static/js/fangorn.js

Fixes https://trello.com/c/3gDcKvHW/339-dataverse-uploading-a-file-to-released-should-be-disabled
Fixes https://trello.com/c/ZS0xFuss/338-dataverse-no-download-button-from-file-overview

Feature fix/fix dataverse ui

---

website/addons/figshare/static/figshareFangornConfig.js

Fix typo in Figshare permissions check.

---

website/addons/dataverse/static/dataverseFangornConfig.js

Fixes https://trello.com/c/yIvXdUlt/260-dataverse-no-delete-confirmation-modal

Check Dataverse parent for released state.

---

website/search/elastic_search.py

Fixes #1422
Just a simple replace when return search results.
@lyndsysimon should know that this exists.

[Hotfix] Search ampersand

---

website/addons/dataverse/static/dataverseFangornConfig.js

Fixes issue #1694 
Removed unnecessary btn-group from dataverseFangornConfig.js
Dataverse files do not have multiple actions so there is no need for button group. Does not have side effects.

[Hotfix] Fixes dataverse download buttons showing as button group

---

scripts/analytics/tabulate_emails.py
scripts/analytics/tabulate_logs.py
scripts/analytics/utils.py

Fix typo and miscellaneous cleanups to metrics scripts.
* Fix typo in method name
* Remove unused `nchar` variables
None expected

Fix method name; remove unused variables.

---

.gitmodules
README.md
framework/auth/core.py
requirements.txt
scripts/parse_citation_styles.py
tasks.py
tests/test_citations.py
tests/test_features.py
website/citations/__init__.py
website/citations/models.py
website/citations/utils.py
website/citations/views.py
website/models.py
website/project/model.py
website/routes.py
website/settings/defaults.py
website/static/css/citations.css
website/static/css/site.css
website/static/js/citations.js
website/static/js/pages/project-dashboard-page.js
website/static/js/project.js
website/templates/project/project.mako

This PR is the first in a series that will include richer citations for projects, as well as implement addons for Zotero and Mendeley.
This PR adds CSL-formatted citations. The user must enter the format used to display the citation each time for now, but this choice will be persistent in a forthcoming PR.

[feature] Add rich citations widget

---

website/settings/local-dist.py

Remove lines from local-dist.py that shouldn't be there.
Negligible.

(fixes to develop)Lines shouldn't be in local-dist.py

---

scripts/migrate_cloudfiles_container.py
scripts/osfstorage/settings/defaults.py

Add migration to ensure that all files live in correct container
* Add migration script
* Add necessary settings to defaults.py
None expected

Add migration script to ensure all files are in correct container.

---

package.json
website/addons/wiki/shareServer.js

This fixes many of the issues seen when putting the sharejs server under heavy load.

[feature] error handling for sharejs server

---

website/templates/public/pages/help/user_profile.mako

I added a video over here too.

[Getting Started Videos] Added one new video

---

framework/render/exceptions.py
framework/render/tasks.py
tests/framework_tests/test_render.py
tests/test_addons.py
website/addons/figshare/exceptions.py
website/addons/figshare/model.py
website/addons/github/exceptions.py
website/addons/github/model.py
website/templates/project/view_file.mako

Adds handling for github files that are too large, dropbox dmca takedowns, delete button fix, and some tests.

[Feature] fileview page fixes

---

scripts/osfstorage/files_audit.py
scripts/osfstorage/settings/defaults.py
scripts/osfstorage/utils.py

Add script to ensure that all OSF Storage files are backed up in Glacier and have parity files
* Add script
* Copy parity file utils from WaterButler
None expected
Written with @icereval

Add script to verify that files are properly archived.

---

tasks.py
website/addons/wiki/shareServer.js

Purpose
---
Correct possible crash when `userMeta` is unavailable.
Lock down default CORS configuration and allow for settings override.
Cause
---
Incorrect default cors allow origin, no ability to configure.
Disconnect while database is offline could cause server to crash since `userMeta` was unavailable.
Side effects
---
None

[feature] collab wiki cors and logging

---

website/addons/base/__init__.py
website/addons/figshare/tests/test_models.py

[Feature] Figshare again

---

website/addons/dropbox/model.py

More unique dropbox cache names for when switching folders

[Feature] Dropbox wierdness

---

website/addons/github/exceptions.py

No download or delete button for github files are too large

[Feature Fix]Github crud

---

website/templates/public/pages/help/addons.mako

Added some explanatory copy, got rid of most of the repetitive videos. Added new video

Add-On Page reconfiguration.

---

website/templates/public/pages/getting_started.mako

Files, Forks, registrations, Links, Privacy, commenting, citations,  statistics, and Projects

Added Some Updated Videos. Added Templates

---

website/project/views/node.py

Assuming there is not a good reason for having this method -- removing an unfinished and unused method from the node views.
n/a
n/a

[dev][cleanup]rename_folder() was unfinished and unused

---

website/conferences/views.py

Remove leftover osf storage url

[Hotfix] Conferences

---

scripts/osfstorage/files_audit.py

Fix minor typos in audit script.

Fix imports and return values.

---

website/static/js/fileRevisions.js

Fixes #1816
Make a metadata request to waterbutler to see if we're are viewing a draft or not
When viewing a figshare file another request will be sent to waterbutler

[Hotfix] Figshare delete button

---

scripts/osfstorage/files_audit.py
scripts/utils.py

Add hash ring to speed up file audit script

Add hash ring for files audit.

---

scripts/migrate_names_cleanup.py
tests/test_views.py
website/profile/views.py
website/static/js/koHelpers.js
website/static/js/profile.js

Purpose
---
Citations do not consistently render. e.g.
Included is a migration script to cleanup any users with spaces in all name fields as well as knockout and backend checks to verify views trim as necessary.
Cause
---
User names contain erroneous spaces.
Side effects
---
None

[hotfix] citations not rendering, trim inputs on profile editor, migration

---

website/addons/base/views.py
website/addons/dataverse/views/config.py
website/addons/dataverse/views/crud.py
website/addons/dataverse/views/widget.py
website/addons/figshare/model.py
website/addons/github/views/widget.py
website/addons/osffiles/views.py
website/addons/zotero/views.py
website/conferences/views.py
website/profile/views.py
website/search/views.py

Standardize return variable names within website views
Easier to read code
n/a

[dev][cleanup]Code clean up within website views

---

scripts/analytics/tabulate_emails.py
scripts/analytics/tabulate_files_usage.py
scripts/analytics/tabulate_logs.py
scripts/analytics/utils.py

Add script to tabulate file usage by space per user
* Add files usage script
* Minor refactor to csv creation helper
None expected
Note: this script isn't being added to the daily reports, since we probably don't need these numbers every day. @sloria, let's run this manually and send results to @saradbowman and @JeffSpies.

Add script to summarize file usage.

---

website/templates/public/pages/getting_started.mako

Forks, Registrations, Statistics, Privacy

Getting Started Changes

---

scripts/populate_conferences.py

Add: Virginia Piedmont Regional Science Fair

---

bower.json

Update markdown-it-toc to lastest version in bower.json

---

website/static/js/fangorn.js

Show icons for Google Docs files in file grid
* Look up file extension icons in object
* Alias gdoc, gsheet to docx, xlsx
None expected

Show appropriate icons next to Google Docs files.

---

website/templates/project/addon/citations_widget.mako

Restore citation style pickers
* Fix CSS selector for binding selector
None expected

Bring back citation style picker.

---

framework/addons/__init__.py
website/addons/base/__init__.py
website/oauth/views.py

Yes, this is a dirty hack.
Yes, I intend to fix it in the very near future.
Yes, I'd like to merge it into develop anyhow.
No, it's not necessary for you to remove my name from the commit... though, if you do, I won't complain...
:innocent:

Fix bug where removing an external account could fail

---

website/addons/box/templates/box_node_settings.mako
website/addons/dropbox/templates/dropbox_node_settings.mako
website/addons/figshare/templates/figshare_node_settings.mako
website/addons/googledrive/templates/googledrive_node_settings.mako
website/addons/mendeley/templates/mendeley_node_settings.mako

reorder status message and submit float

[feature] addon submit button overlap

---

website/static/js/citationGrid.js

Fix text to fit on one line
^
none

Changing load error message to fit on one line

---

website/addons/box/model.py

Fix tyops.

---

website/addons/box/tests/test_models.py
website/addons/box/tests/test_views.py

Fix failing Box tests.

---

website/addons/box/model.py

Handle error on reload.

---

website/addons/box/model.py

Fix reload error again.

---

website/static/js/pages/notifications-config-page.js
website/static/js/project-settings-treebeard.js

Problems: Corrects issue with folder picker calling expandOnLoad infinitly on mithril redraw

[feature] notifications treebeard lazy load

---

tests/test_notifications.py
website/notifications/emails.py

Submitted on behalf of @samanehsan

[Feature] Notifications

---

website/static/css/site.css
website/static/js/notificationsTreebeard.js

Fixes this Trello card : https://trello.com/c/CtDerFKa
- CSS only changes on padding
- Treebeard option for height of row changed
None.

Fix padding on notifications treebeard box

---

website/templates/public/login.mako

Re-submit of PR #1946 (had to re-fork).

Add password tooltip

---

website/templates/emails/comment_replies.html.mako
website/templates/emails/comments.html.mako
website/templates/emails/digest.html.mako
website/templates/emails/transactional.html.mako

Feature/notifications develop: Inline CSS in templates 

---

website/addons/figshare/settings/defaults.py
website/addons/figshare/settings/local-dist.py

Change figshare settings structure to match other addons
Adds a local-dist.py to figshare, and removes oauth credentials from defaults.py
None

Add a local-dist.py to figshare settings and remove oauth settings from defaults.py

---

website/templates/public/pages/faq.mako

Update FAQs to include common questions received on the help desk.

hotfix: Additional FAQs

---

website/templates/public/pages/getting_started.mako

Updated getting started page with video and text about Notifications

Hotfix: Update getting started- notifications

---

website/settings/local

local had been added accidently in previous commit

File was added accidently

---

scripts/analytics/tabulate_emails.py

Update daily users added script to be consistent with active user count.
Slight improvement in quality of life for @saradbowman 
[Resolves #1768]

Make user metric criteria consistent.

---

website/addons/base/__init__.py
website/oauth/models/__init__.py

This changes no code at all, but adds additional documentation to the OAuth models, and to the new OAuth-aware base classes for addon settings.

[feature] Add documentation for OAuth objects

---

framework/analytics/piwik.py
framework/analytics/tasks.py
framework/auth/core.py

Move creation of Piwik users into Celery task that is deferred until request complete
* Add Celery task for Piwik user creation
None expected
@lyndsysimon can you take a look? @sloria sorry about the inline imports--would be good to sort this out sometime.

Queue creation of Piwik users.

---

scripts/analytics/benchmarks.py

Add user log counts by month, week, and day
* Update benchmarks script with extra logging windows
None expected
[Resolves #2066]

Add extra log count windows.

---

scripts/populate_conferences.py

[Presentation Service] Added ASB2015

---

scripts/populate_conferences.py

Actually Adding the TeaP Conference

---

scripts/populate_conferences.py

Updated so instructions show properly.

Fix Conference site for TeaP

---

website/static/js/conference.js

This issue #1761 requested all columns in presentations to be sortable. The PR adds sorting to category to finalize this. 
- Make cateogry column sortable in Treebeard options
None.

Add sorting option to category column of presentations

---

website/templates/footer.mako

Rather than collaborator network

update footer: Explore links to public activity

---

scripts/annotate_rsvps.py

Add script to annotate conference RSVP spreadsheets with user information. Requested by @lbanner.
* Add annotation script.
None

Add script to annotate conference RSVP spreadsheets.

---

website/addons/wiki/templates/edit.mako

Fix issue: #2167 
Revert becomes red, save becomes green.
None

Change wiki edit button classes to change colors

---

website/templates/public/pages/meeting_landing.mako

rather than submission service. As per today's community meeting.

Change title to Presentation Sharing Service

---

website/templates/public/pages/getting_started.mako
website/templates/public/pages/help/addons.mako

Box, Google, Drive, Zotero, Mendeley, Wiki

 [Getting Started Videos] Add Ons + Videos 

---

website/templates/profile/addon_permissions.mako

A stray character in the user addon settings template was breaking the render
Delete stray >
None

Remove stray > from addon user settings template

---

website/templates/public/two_factor.mako

Stop the 2FA input box from auto-completing previous codes.
More usage of HTML5
N/A

[Feature] Two Factor input field shouldn't autocomplete

---

website/templates/public/pages/help/addons.mako

1) Added bold formatting to the first sentence of each page.
2) Made the Citation Manager video come after Mendeley so that the anchor is in the right place for the scroll bar. 
3) Fixed issues with spacing between words.

[Getting Started Page] Formatting on the Add-Ons Page

---

website/templates/public/pages/getting_started.mako

1) Added bold text to the beginning of each section.
2) Fixed some spacing issues.

[Getting Started Page] Fixed Some Formatting Issues

---

website/addons/googledrive/README.md

Updates callback URL in Readme of Google Drive.

[skip ci] updates google drive Readme

---

website/addons/dropbox/model.py
website/addons/dropbox/tests/test_models.py
website/addons/figshare/model.py
website/addons/figshare/tests/test_models.py
website/addons/googledrive/model.py
website/addons/googledrive/tests/test_models.py

See commit messages for details.

[Feature] guid file addon reference fix

---

framework/auth/__init__.py

Re-add the session login code that was removed somehow

[featuire] Actual credential section was somehow removed

---

website/static/js/paginator.js

<b>Purpose</b>
Don't use ES6
<b>Changes</b>
^
<b>Side Effects</b>
None

convert paginator.es6.js to paginator.js

---

tests/webtest_tests.py

Existing tests failed to catch a serious regression fault. This covers that area and should prevent uncaught future regression failures.
One more web_test
Wider test coverage

[feature] Added test to catch future 2FA regression faults

---

website/addons/base/views.py
website/addons/dataverse/views/crud.py

[hotfix] file render bypass cache

---

README.md
requirements/dev.txt
tasks.py
webpack.common.config.js
webpack.dev.config.js
webpack.prod.config.js
website/util/paths.py

Adds support for LiveReload: browser will automatically refresh when a code change is made.
In order to use livereload, devs should run `inv requirements --dev` to get up to get their development requirements up to date.
Note: This PR depends on #2275

[feature] Livereload support

---

website/static/js/formViewModel.js

Follow up for PR #2140 
Conform to OSF coding standards. 
Move docstring to the correct location
n/a

Docstring was in the wrong location

---

website/static/js/growlBox.js
website/static/js/osfHelpers.js

<b>Purpose</b>
change the groulbox.es6.js to es5

change the growlbox.es6.js to es5 style

---

scripts/populate_conferences.py

Adding VSSEF per request

---

.travis.yml
tasks.py

[feature] travis container build

---

website/static/js/share/results.js

Changes:
Updated some bad js that broke the More button
Sideeffects:
None

Fix the load more button

---

website/addons/wiki/templates/edit.mako

Fixes Trello bug: https://trello.com/c/R7oLKh8h
- Fix the typo in bata-bind" to data0bind="
None

Fix typing error in View display

---

website/static/css/site.css
website/templates/public/forgot_password.mako
website/templates/public/login.mako
website/templates/public/two_factor.mako

Add OSF Branding to the OSF page
Addition of OSF navigation bar and footer to the `/login/` page
n/a
Closes-Issue: #2358

[hotfix] OSF Branding was requested for log in page

---

website/static/js/comment.js

Used two different places, one as an observable, the other not. Made not an observable.

Make modified not an observable

---

website/templates/project/contributors.mako

<b>Purpose</b>
Clarify the language that user click on remove contributor. solve issue https://github.com/CenterForOpenScience/osf.io/issues/2312
<b>Changes</b>
before changes:
after changes:

fix the remove contributor language

---

website/notifications/views.py

Minor fix for log messages. (as discussed with @sloria)

Fix format string bug: should be method, not parameter.

---

website/addons/figshare/api.py
website/addons/figshare/views/config.py
website/addons/forward/__init__.py
website/static/css/addon_folderpicker.css
website/static/js/addonNodeConfig.js
website/static/js/folderPickerNodeConfig.js
website/templates/project/addon/node_settings_default.mako

QA found a couple folderpicker bugs:
- https://trello.com/c/xuFlssfx/50-submit-button-for-figshare-gives-no-success-message
- https://trello.com/c/dsRLWpTS/68-external-link-configuration-is-incorrect
- https://trello.com/c/uiBl4UW3/57-staging-folder-highlighted
This PR fixes those
- Fix fixshare folder serialization
- Fix forward addon templates path
- Override treebeard CSS and prevent multiselect/dragging
None

[Ready for Review] Feature/folderpicker errors

---

website/addons/figshare/tests/test_views.py
website/addons/figshare/views/config.py

Changes to figshare folder serialization/deserialization broke figshare_config_put, and corresponding tests. This fixes those issues.
- Update folder serialization/deserialization
- Update test to reflect this
None

Update figshare deserialization of submitted values, and update tests

---

scripts/populate_conferences.py

Change 'name' field to spell out the name of several conferences

Change 'name' field

---

website/static/js/contribAdder.js

<b>Purpose</b>
fix https://trello.com/c/Ti2daUCU/121-import-contributors-add-all-function. Fix the add All and remove All button on add contributor modal

fix the add_all, remove_all for contributor add modal

---

website/static/css/fangorn.css
website/static/js/fangorn.js

https://trello.com/c/WeLGlh16/151-incorrect-cursor-for-delete-folder-icon-button
Add cursor: pointer to fg-hover-hide class
None

Update fangorn css to have pointer on delete buttons

---

tests/test_share.py
website/search/search.py
website/search/share_search.py
website/search/views.py
website/static/js/search.js
website/static/js/share/stats.js
website/static/js/share/utils.js

And filter out raw fields.
Can't be merged until the same changes have been made on scrapi. Probably post-.31

[hold] Update SHARE frontent to request old versions of the metadata

---

website/templates/public/login.mako

this complements #2292 
cc @GaryKriebel

change another placeholder from username to email

---

website/static/js/tests/projectorganizer/test_projectorganizer.html
website/templates/base.mako

this is what grep could find
@lyndsysimon please review

typo in jquery local path

---

scripts/populate_conferences.py

replace with presentations@osf account

[hotfix] remove personal accounts from admin list

---

website/settings/defaults.py

[feature] google drive session overwritten by api calls/transactions

---

website/addons/googledrive/templates/log_templates.mako

<b>Purpose</b>
Follow up fix. Fix the problem that when choose whole google drive folder. it will display as "//" in log.

fix the log part for choosing whole googledrive folder

---

website/addons/box/templates/log_templates.mako
website/addons/googledrive/templates/log_templates.mako

Adds the log-folder class to google drive folder creation logs
Remove the single quotes from box file deletion logs.

[Feature-Fix] addon log css

---

website/addons/osfstorage/views.py

Update folder naming conflict error message
Note: This is mostly for consistency with waterbutler

[Feature-Fix]Ambiguous error messages for folder naming conflicts

---

package.json
website/addons/osfstorage/views.py
website/addons/s3/templates/log_templates.mako
website/static/js/fangorn.js

* Updates to the latest version of treebeard
* Adds bucket to S3 logs
* Fixes an issue with double submitting folder creation
* Fixes an issue with the onchange event in FireFox

[Feature-Fix]Folder UI

---

website/static/css/site.css
website/static/js/signUp.js
website/templates/index.mako

Properly display validation messages on sign up form

---

website/static/js/accountSettings.js

<b>Purpose</b>
Add check confirm box for remove emails. Solve https://github.com/CenterForOpenScience/osf.io/issues/2496
<b>Change</b>

confirm box added for remove emails

---

scripts/migrate_manual_merged_user.py
scripts/tests/test_migrate_manual_merged_user.py
tests/factories.py

<b>Purpose</b>
Add migrate script to migrate manually merged user. Fix issue https://github.com/CenterForOpenScience/osf.io/issues/2470

migrate_manual_merged_user

---

tests/test_views.py
tests/webtest_tests.py
website/profile/views.py
website/static/js/pages/dashboard-page.js
website/views.py

<b>Purpose</b>
Ultimate fix for https://trello.com/c/iuQqlj9Z/88-making-email-primary-while-logged-in-as-another-user-sends-confirmation-email-to-an-already-confirmed-user.

add user check for account merging

---

website/static/js/pages/dashboard-page.js
website/views.py

<b>Purpose</b>
Fix the problem that can't update user local timezone. Solves https://github.com/CenterForOpenScience/osf.io/issues/2543

fix the can't update local timezone problem on dashboard-page

---

website/static/js/contribManager.js

Displays full permission text even when user isn't admin.
Thanks to @huangginny for the code, I just brought it into osf.io repo.
Close #1101

Permission Display Full

---

README.md

updated README.md with commands to create virtualenv

updated README.md with commands to create virtualenv

---

website/static/js/project.js

<b>Purpose</b>
Fix the node recent activity logs. Solves https://github.com/CenterForOpenScience/osf.io/issues/2514.
<b>Changes</b>
Before fix:
after fix:

fix the recent_activity log

---

website/addons/base/views.py

<b>Purpose</b>
Remove the delete button from file view page when disk saving is true

remove the delete button from file view page when disk saving is true

---

api/users/serializers.py

Add fields to `UserSerializer` according to API V2 specs.

[feature] API V2 DRF: Add fields to user serializer

---

website/templates/project/modal_generate_private_link.mako

<b>Purpose</b>
Update the anonymous link warning message. fix https://github.com/CenterForOpenScience/osf.io/issues/2562
<b>Change</b>
before change:
after change:

modify the warning language

---

website/static/js/fangorn.js

<b>Purpose</b>
Improve the warning message for uploading file error. Partially solves https://github.com/CenterForOpenScience/osf.io/issues/2480.

improve the warning message

---

tests/test_models.py
website/project/model.py
website/search/elastic_search.py
website/search/search.py
website/templates/search.mako

- cyclic structures in Node trees created infinite recursion in #get_descendants_recursive
- updating Node category created two ES entries
- Break recursion on pointers in #get_descendants_recursive
- Delete ES entry when updating category
None

[Ready for Review] PO Recursion / Search

---

tests/test_models.py
website/static/js/fileRevisions.js

<b>Purpose</b>
Fix https://trello.com/c/hjv4iD0O/52-dataverse-version-table-misaligned

fix the fail test on develop also fix the dataverse version table

---

website/static/js/registerNode.js
website/templates/project/project_base.mako

<b>Purpose</b>
add warning for project registration. Solves https://github.com/CenterForOpenScience/osf.io/issues/2627
<b>Changes</b>
Now when you register a parent project, you will see

Add warning message for project registration

---

tests/test_models.py
website/addons/box/templates/log_templates.mako
website/project/model.py
website/static/js/logFeed.js
website/static/js/osfHelpers.js
website/static/js/pages/project-base-page.js
website/static/js/projectorganizer.js
website/templates/components/dashboard_templates.mako
website/templates/log_templates.mako
website/templates/project/project_base.mako
website/templates/project/settings.mako
website/views.py

- prevent category selection from OB
- let update logs show changes
- fix breaking test
- use correct URL in PO search for existing projects
- Fix: https://trello.com/c/95ZMue06/92-read-only-child-of-private-project-is-not-listed-in-project-organizer
None

Still more noderefactor

---

website/static/js/fileRevisions.js
website/templates/project/view_file.mako

<b>Purpose</B>
Fix https://trello.com/c/hjv4iD0O/52-dataverse-version-table-misaligned.
<b>Changes</b>
after this fix:

remove the date column if the file is from dataverse

---

website/util/rubeus.py

This should fix the infinite recursion with cyclic links in projectorganizer.

Another Attempt to stop PO recursion

---

website/static/css/site.css
website/templates/project/view_file.mako

<b>Purpose</b>
fix the dataverse version table.

fix the problem that dataverse version table not display correctly

---

website/static/css/site.css

<b>Purpose</b>
Fix the problem that 
after this fix:

fix the scroll bar apart from table

---

framework/auth/core.py
framework/auth/exceptions.py
framework/auth/views.py
tests/base.py
tests/factories.py
tests/models/test_addon_settings.py
tests/models/test_user.py
tests/test_addons_oauth.py
website/addons/base/__init__.py
website/language.py
website/templates/error.mako

Ready for review.
Note that the additions to `language.py` should be reviewed and probably edited.

[feature] User account merging

---

website/templates/log_templates.mako

@nicipfeiffer suggested a change to our log language for updating Nodes.
to -> for
- get less awkward 
- :goat:

Node update logs: change to -> for

---

website/templates/public/pages/help/components.mako

remove statement saying components are like folders for clarity
Quick language review @bnosek @JeffSpies @sloria

Hotfix: Getting started; components

---

website/templates/public/pages/help/files.mako

Requesting quick language review @bnosek @JeffSpies @sloria

HOTFIX: getting started; adding folders

---

package.json

Fixes Trello bug: https://trello.com/c/HmjNFBml
Updated treebeard sha since the notify height class setting change was done in Treebeard
None.

[Fix] Update treebeard to fix notify height 

---

package.json
website/static/css/fangorn.css
website/static/js/fangorn.js

Resolve several trello cards following QA
https://trello.com/c/wnvyiE1j
https://trello.com/c/HmjNFBml
https://trello.com/c/bobyOtgY
https://trello.com/c/Yl0CAqms
https://trello.com/c/j7esgCWk
https://trello.com/c/sebqZcUF
- Update to treebeard commit number ro resolve cancel upload isUploading state properly
- Changes to text and labels
- Cancel Upload style changes
None

[Fixes] to several Trello cards related to cancel upload an messages 

---

website/static/js/fangorn.js

Fixes Trello bug: https://trello.com/c/5Tt8pA6g
If a user can't delete any of the selected files due to permission the delete multiple button will not appear on the toolbar in files page. 
Add code to check if user has permission to delete any of the files
None.

[Fix] Add a check to see if  Delete Multiple button shows

---

website/static/js/fangorn.js
website/static/js/projectorganizer.js

Fixes Trello bug: https://trello.com/c/dhVaPo4m
Also adds Open button.
None.

[Fix] Add back missing remove multiple button in PO

---

website/static/js/fileViewTreebeard.js

Make the file being viewed selected on load be selected
Add selected class to row
None.

[Fix] Add back broken selected class for selected file 

---

website/addons/dataverse/static/dataverseFangornConfig.js
website/addons/figshare/static/figshareFangornConfig.js
website/addons/github/static/githubFangornConfig.js
website/static/css/fangorn.css
website/static/js/fangorn.js
website/static/js/pages/project-dashboard-page.js
website/static/js/projectorganizer.js

Fixes following:
- Remove all button appearing for single item selected in PO
- Remove XS for hidden for better narrow window buttons
- Fix jumpin on select in PO
- Change button style
These pertinent Trello issues:
https://trello.com/c/lsMJQgj3
https://trello.com/c/oLACbxdv
https://trello.com/c/dhVaPo4m

[Fix] Combined minor fixes from Trello and other for toolbar

---

website/static/js/fangorn.js
website/static/js/projectorganizer.js

Fix for this trello card: https://trello.com/c/sDdCYN7S
Also fixing this: https://trello.com/c/x4It9Uci

[Fix]  search not clearing properly [skip ci]

---

website/templates/project/settings.mako

<b>Purpose</b>
Add clarification for notification settings. Solves https://github.com/CenterForOpenScience/osf.io/issues/2725
<b>Changes</b>
before change:
after change:

add notification clarify

---

website/addons/box/templates/log_templates.mako
website/addons/dropbox/templates/log_templates.mako
website/addons/googledrive/templates/log_templates.mako
website/addons/osfstorage/templates/log_templates.mako
website/addons/s3/templates/log_templates.mako
website/static/js/logFeed.js

<b>Purpose</b>
Remove the '/' before file name. Fix https://github.com/CenterForOpenScience/osf.io/issues/2695.
<b>Changes</b>
before change:
after change:

remove the '/' before the file name in log

---

website/project/views/contributor.py

Needs better exception, but basic concept is ready for review

[wip][hotfix] claim user w/o email address

---

website/static/js/conference.js

Adds natural scrolling option to presentations page.
This was overlooked in .36 release but is required here as well.

[Fix] Add Treebeard natural scroll to presentations page

---

website/templates/public/pages/help/files.mako
website/templates/public/pages/help/organizer.mako

hotfix/ getting started updates

---

website/templates/public/pages/faq.mako

To update "How do I make folders?" answer, now that there are folders.

HOTFIX: fix FAQs

---

website/templates/project/project.mako

<b>Purpose</b>
Fix the language inconsistent of component. Solves https://github.com/CenterForOpenScience/osf.io/issues/2691
<b>Changes</b>
before change:
after change:

change the language to fit the node type

---

website/project/model.py
website/project/views/node.py
website/static/js/nodeControl.js
website/templates/project/project.mako
website/templates/util/render_nodes.mako

Closes #1654.
Ready to merge upon CI completion and review.

[hotfix] Broken "forks" page for project

---

website/templates/dashboard.mako

Fixed button layout for Create Project.  Tested on all but IE.

---

website/static/js/fangorn.js

Fixes:
* Having "undefined" in modals
* Handle renaming a file to another file that already exists
* Not trimming files when they are replaced.

0.37.0 bug fixes

---

scripts/populate_conferences.py

Reid 2015 would like to be able to upload more presentations. Changed 'active' from 'False' to 'True'

Reid 2015 conference change 'active' to True

---

scripts/metrics.py

file tree has been deprecated for a long time now, check deleted files as well.

[Hotfix] Metrics

---

website/static/robots.txt

Disallowing bot access to piwik. Not much to be gained there, and there's a lot of branches to crawl.

Update robots.txt to disallow /piwik/

---

website/static/css/site.css
website/templates/profile.mako

Purpose
-----------
These fixes close #2781, #2773, and #2260.  Prior to these fixes, certain elements were not centered in the navbar and the navbar was also wider than it should be on the "Profile" page when on mobile.  Also, the name header on the "Profile page" for mobile was getting obscured/overlapping links previously and this addresses that.  This PR cleans up these misaligned UI elements to create a smoother user experience.
Changes
-----------
* Adjusted line height of the text next to the logo/gravatar to make sure that it was centered with the image
* Adjusted the padding/margins on the images so that they vertically center
* Changed the size of the font and the margins of the name header on the "Profile" page so that the name fits better.
* Removed a class from the table on …

[Feature Fix] UI fixes

---

website/static/css/fangorn.css
website/static/js/fangorn.js
website/static/js/projectorganizer.js

Fixes a couple of issues with Treebeard related to recent changes.
- Bug with toolbar not clearing when deleting multiple items from folder is fixed
- Modal buttons are made smaller to better accomodate height and widht limitations
- Added icons to uploading temporary rows per @icereval 's request.
- Removed left over tooltip for rename button
None.

[Ready for Review] [Fixes] Misc Treebeard related fixes

---

framework/auth/views.py

Immediate short-term fix to scrub malicious HTML from user names upon registration. Will send further details of fix to @lbanner , @GaryKriebel , or @JeffSpies by email and discuss in-person as needed.

Sanitize user name upon account creation

---

framework/auth/views.py
tests/test_views.py

This PR (to `master`) covers changes already submitted to `develop`: 
- #2904 (merged): Fix for code injection
- #2918 (under review): Regression test for data sanitizing
Thanks, @icereval .

[hotfix][master] Sanitize username upon account creation

---

website/templates/public/pages/faq.mako

Update FAQ about moving files, now that moving files is possible. Remove question "Do registrations have to be public?" - until embargo period is settled.

hotfix/ update faqs

---

website/profile/views.py
website/routes.py

<b>Purpose</b>
Remove the old route which is out of date. Closes https://github.com/CenterForOpenScience/osf.io/issues/2939.
<b>Change</b>
Remove the unnecessary routes.

remove old route

---

website/addons/dataverse/views/hgrid.py

If dataverse happens to throw an SSLError return a skeleton folder so the page loads correctly

Hotfix Dataverse SSL

---

website/static/js/nodeControl.js

Update registration action message to ensure accuracy
Adjusted new registrations action message to reflect 0.39.0 release changes
n/a

[hotfix] Registration action message was not accurate

---

website/static/js/nodeControl.js

Adds extra warning text when making project public. closes Issue #3007

Adds extra warning text 

---

tests/test_models.py
website/project/model.py

<b>Purpose</b>
Prevent project's deleted component to be forked.
<b>Changes</b>
Before change:
After change:
The deleted component will no longer be forked.

prevent fork deleted component

---

website/static/css/site.css
website/static/js/osfHelpers.js
website/static/js/projectSettings.js
website/static/js/tests/osfHelpers.test.js

This is a minor change, moving the "no, really, are you *sure* you want to do that?" prompt to osfHelpers.js

[feature] Add $osf.confirmDangerousAction() to osf helpers; moved from project js.

---

website/static/js/filepage/index.js
website/templates/project/view_file.mako

* Add a View toggle button to the file view page.
*e.g. logged out, user can toggle `Revisions`*

[hotfix] file view toggle

---

scripts/analytics.sh
scripts/cron.py

[hotfix] standardize cron #2

---

.gitignore
framework/guid/model.py
scripts/add_blacklist_guids.py
scripts/tests/test_add_blacklist_guids.py
website/models.py

Purpose
------------
Since we randomly generate GUIDs, there is a chance that we can get some that look like offensive or bad words. 
Changes
------------
Check randomly generated GUIDs against the BlacklistGuid database collection - if it's a blacklisted guid, a new one is generated. 
Side Effects
-----------------
Removed optimistic creation of guids so that the id can be checked before the Guid object is saved.

Feature: Check for blacklisted guids

---

website/templates/nav.mako

Remove beta descriptor from nav.mako

---

website/templates/footer.mako

<h1>Purpose</h1>
adds donate link to footer. Implements changes suggested in Issue #3017.
<h1>Changes</h1>
Just minor changes to html tags. Implemented exactly as suggested in #3017.
<h1>Side Effects</h1>

Adds donate link to footer.

---

website/static/js/projectorganizer.js

Conflict arose in 2e218c51ee990873fa1f3298430f383b982c1b9c.

Revert merge conflict in projectorganizer.js

---

website/static/js/registerNode.js

Make registration modal language more clear and concise.
Adjust language for the new registration modal.
None.
Closes-issue: https://trello.com/c/6n9pRBuc/43-improve-message-to-user-about-registrations

[feature] Improve registration modal message

---

website/templates/public/pages/help/forks.mako

**Purpose**
fix bad grammar, close issue #3090
**Changes**
changed static html
None

fixed weird grammar.

---

website/static/js/citationsNodeConfig.js

[feature] Fix bug in OAuth addon access token import

---

tests/test_registration_retractions.py
website/project/model.py

Ensure pending embargoes can be retracted.
1. Fixed broken conditional.
2. Fix bad comment in test.
None.

[feature fix] Pending embargoes should be retractable

---

website/static/js/fangorn.js

Fixing tiny bits of grammar just cuz

Remove one comma splice

---

website/templates/log_templates.mako

Bind to html rather than to text in knockout as we send back presanitized data

[Hotfix]Move and copy logs

---

website/templates/emails/forward_invite.txt.mako
website/templates/emails/forward_invite_registered.txt.mako
website/templates/emails/invite.txt.mako

This is a repackaging of #3179, which is a repackaging of #3175 :)
All I did here was pull the most recent `develop`, then cherry-pick @jlcohoon's commits from her previous PR.

[feature] revise unregistered contributor emails

---

website/templates/emails/conference_submitted.txt.mako

Include more add-ons in the list rather than just GitHub. at the request of @TimErrington

update conference success email

---

website/static/js/projectCreator.js
website/templates/components/dashboard_templates.mako

This PR is to resolve the side effect from #2858 . In #2858 PR, I deleted a Id and didn't realize it  was used in other place.
Add an new unique id and replace the old one in JS file
None.

[Feature Fix] Add Id for input dom to get the correct input value

---

tests/test_models.py

Adjust test to match new logging behavior in `Node#set_privacy`

[feature fix] Fix broken test

---

scripts/cron.py

Need to set minute; otherwise script will be called every minute
of the hour. h/t @icereval

Fix retraction/embargo cron tasks

---

scripts/migrate_registration_and_fork_log.py
scripts/tests/test_migrate_registration_and_fork_log.py

<b>Purpose</b>
Fix the problem that a lot registration and fork projects don't have logs. Closes https://github.com/CenterForOpenScience/osf.io/issues/3230

fix the 0 logs fork and registration

---

website/static/js/nodeControl.js

It makes it impossible to increase or decrease watch count multiple time in a row. 
Resolved the bug -- #3201
Because the reason for the issue is that it is still open to increase the count when the update is in progress. So normally the change should be only made when there is no updating in progress. The problem's logic is similar as the #3203. 
1) Add status variable -- `watchUpdateInProgress`
2) Add conditional judge before updating watch counts
3) Update the status variable when the watch update is done or started.
None.

[Feature Fix] Fix  watch count to show impossible numbers

---

website/static/css/front-page.css
website/templates/index.mako

Fixes minor issues
- Text and content changes
- Vertically align copyright text

[Fix] Wording fixes for new frontpage 

---

tests/test_views.py
tests/test_watch.py
website/project/views/log.py
website/static/js/contribAdder.js
website/static/js/logFeed.js
website/static/js/paginator.js
website/static/js/tests/paginator.test.js
website/views.py

<b>Purpose</b>
Fix the problem that the paginator page number may go beyond limit. Closes #3299.

[feature] paginator page limit

---

website/static/js/pointers.js

<b>Purpose</b>
Fix the add link modal paginator not working on staging and locally. Close https://trello.com/c/EBSti5LJ/52-pagination-not-working-for-add-links-modal

[feature fix] fix the paginator for add link modal

---

website/addons/twofactor/models.py
website/project/views/register.py
website/static/js/nodeControl.js
website/static/js/registerNode.js

Clean up old, outdated comments that are no longer relevant and shouldn't be in the code base.

[feature] Remove outdated/superfluous comments

---

website/templates/public/pages/help/addons.mako

Fixed typo

---

website/project/views/log.py
website/project/views/node.py
website/search/elastic_search.py
website/views.py

<b>Purpose</b>
Add backend error handle for invalid page num for paginator on add link search result and add contributor search result.

add error hanlder for invalid page number for paginator

---

website/templates/public/pages/faq.mako

Fixes very minor Trello issue: https://trello.com/c/1FZHkKSX

Fixes one heading font weight

---

website/static/css/pages/profile-page.css

Fixes Trello issue: https://trello.com/c/c9WfGF8E

Fix long name pushing plus button down

---

website/static/vendor/citeproc-js/citeproc.js

Fixes Trello issue: https://trello.com/c/bCtXMmxI

Fix mendeley and zotero text in TB view

---

website/addons/wiki/templates/add_wiki_page.mako
website/addons/wiki/templates/delete_wiki_page.mako
website/addons/wiki/templates/edit.mako
website/templates/components/dashboard_templates.mako
website/templates/profile/modal_change_avatar.mako
website/templates/project/modal_add_component.mako
website/templates/project/modal_add_contributor.mako
website/templates/project/modal_add_pointer.mako
website/templates/project/modal_show_links.mako
website/templates/public/login_landing.mako

Change modal txt and button color to follow the style guide
Search `modal-footer` class and change the button or text that doesn't follow modal defined the style guideline 
None

[Feature Fix][Staging] Change modal txt and button color to follow the style guide

---

website/static/css/pages/wiki-page.css

[feature fix] Add padding to wiki select to fix Firefox UI

---

website/templates/public/pages/faq.mako

Purpose
=======
Closes https://github.com/CenterForOpenScience/osf.io/issues/3350
h/t @jinluyuan for writing up the overview of additions/fixes
Changes
=======
FAQ Page updated
* Side nav-bar added
* UI Improved
* Questions added / fixed
Side Effects
==========
Fewer helpdesk emails maybe?

[Feature] Improve look and quality of FAQ

---

website/addons/badges/templates/badges_user_settings.mako
website/addons/badges/templates/dashboard_badges.mako
website/addons/dataverse/templates/dataverse_credentials_modal.mako
website/addons/googledrive/model.py
website/addons/s3/templates/s3_node_settings.mako
website/addons/s3/templates/s3_user_settings.mako
website/language.py
website/static/js/filepage/index.js
website/static/js/privateLinkManager.js
website/templates/claim_account_registered_login.mako
website/templates/dashboard.mako
website/templates/include/profile/jobs.mako
website/templates/include/profile/names.mako
website/templates/include/profile/schools.mako
website/templates/include/profile/social.mako
website/templates/merge_accounts.mako
website/templates/metadata/register_1.mako
website/templates/profile/addons.mako
website/templates/profile/notifications.mako
website/templates/project/addon/node_settings.mako
website/templates/project/addon/user_settings.mako
website/templates/project/forks.mako
website/templates/project/modal_add_contributor.mako
website/templates/project/modal_generate_private_link.mako
website/templates/project/modal_show_links.mako
website/templates/project/project.mako
website/templates/project/registrations.mako
website/templates/public/forgot_password.mako
website/templates/public/login.mako

Search the keyword, 'btn-success' and based on style guide, standardize  button color and text across the site
1) Change submit to save or other meaningful verb
2) Change save button to green, and other action button to blue

[Feature Fix] Based on style guide,standardize button color and text

---

website/static/js/filepage/revisions.js

Resolved [Trell bug](https://trello.com/c/qO0qasX9/177-file-detail-page-revisions-table-extends-past-border)
Resolved #3152 
1) Delete margin of panel body
2) Add fixed layout for table

[Feature Fix] Fix table out of screen

---

website/templates/include/comment_template.mako

Resolve [Trello bug](https://trello.com/c/E0TinF4t/146-comments-widget-buttons-out-of-order)

[Feature Fix] Make comment panel button in right postion

---

website/addons/dataverse/templates/dataverse_node_settings.mako
website/addons/forward/templates/forward_node_settings.mako
website/addons/github/templates/github_node_settings.mako
website/addons/s3/templates/s3_node_settings.mako
website/addons/twofactor/templates/twofactor_user_settings.mako
website/templates/claim_account.mako
website/templates/claim_account_registered.mako
website/templates/include/comment_template.mako
website/templates/profile/account.mako
website/templates/profile/modal_change_avatar.mako
website/templates/profile/notifications.mako
website/templates/project/addon/node_settings_default.mako
website/templates/project/forks.mako
website/templates/project/modal_add_component.mako
website/templates/project/registrations.mako
website/templates/resend.mako

Second Round for button text and color fix
Resolve Trello bugs:
Button text and color:
1. https://trello.com/c/RMZVgNBR/168-user-profile-change-avatar-modal-says-save-instead-of-close
2 .https://trello.com/c/jM5Y20ty/147-save-should-be-used-instead-of-submit
3. https://trello.com/c/tPFghV0D/185-user-settings-buttons-have-different-colors-than-mentioned-in-the-style-guide
4. https://trello.com/c/jnnpX4SH/184-forks-page-new-fork-button-misaligned
5. https://trello.com/c/xvFWOB0E/219-cancel-should-be-used-instead-of-close

[Feature Fix] [Style Guide] Fix button and margin details

---

website/addons/dataverse/static/dataverseNodeConfig.js

<b>Purpose</b>
Fix the problem that cancel import author will give error warning. Close https://trello.com/c/6ZnBpm14/233-dataverse-error-when-cancel-import-access-token-for-multiple-linked-accounts

fix the problem that cancel import auther will give error warning

---

website/static/css/fangorn.css

Use the mp4 icon, which is just a play icon, for webms.

[Feature] Webm icon

---

website/static/css/pages/file-view-page.css
website/static/js/osfHelpers.js

a. prompt message has wrong box --  [Trello Bug](https://trello.com/c/Alk8GJ71/129-modals-should-have-bullet-text-for-add-on-behavior-not-boxes)
b. non-centered arrow -- [Trello Bug]( https://trello.com/c/7ywYhvgm/191-toggle-icon-on-file-view-page-file-tree-is-missing-css-styling) 
1) Bring old prompt message (in master branch) back 
2) Add addition margin for arrow (method in master branch )

[Feature Fix] Bring old prompt message UI back

---

website/addons/figshare/messages.py

**Purpose**
fix bad figshare error message. close issue #3535
**Changes**
Just singularization  of message strings.
None

Warning Language Change

---

website/static/css/pages/file-view-page.css
website/static/css/pages/project-page.css
website/static/css/pages/wiki-page.css
website/static/css/style.css
website/templates/alert.mako
website/templates/project/modal_duplicate.mako

This PR fixes the following Trello cards:
https://trello.com/c/0MC22ECs
https://trello.com/c/dS2FxSg1
https://trello.com/c/bSu9S4CO
https://trello.com/c/xJOEEdzX
https://trello.com/c/1CLDtqJe
https://trello.com/c/dzmXDvyS
https://trello.com/c/0L4jQkws

Misc. Style related fixes for .42

---

website/static/js/filepage/revisions.js
website/static/js/project.js

1) Refine the modal title 
2) Discuss with Caner and determine to delete the problematic table-layout change on revision table. We will think a new way to design revision table in future
Resolved some bugs Trello.
1. https://trello.com/c/5AgfZfMR/197-file-detail-page-download-button-in-revisions-table-is-not-centered
2. https://trello.com/c/EewV1U0W/200-file-details-page-added-space-in-revisions-table
3.

[Feature Fix] Refine modal title and revoke table-layout change on revision table

---

website/addons/dataverse/templates/dataverse_user_settings.mako
website/static/css/fangorn.css
website/static/css/front-page.css
website/static/css/pages/getting-started-page.css
website/static/css/pages/wiki-page.css
website/static/css/style.css
website/templates/profile/addons.mako
website/templates/public/pages/getting_started.mako
website/templates/public/pages/help/addons.mako
website/templates/public/pages/help/addons/mendeley.mako
website/templates/public/pages/help/citations.mako
website/templates/public/pages/help/components.mako

Fixes the following bugs:
- Dataverse table hover: https://trello.com/c/vdi6DApj
- Project setting select wraps : https://trello.com/c/GkIsBcQx
- Wiki panel boxes scrolling : https://trello.com/c/U6ueGeu8
- Getting started width differences : https://trello.com/c/weeOQNnC
- Getting started headers : https://trello.com/c/YrwyF4S8
- Youtube controls : https://trello.com/c/6ai7PMie
- Fix treebeard icon alignment : https://trello.com/c/UWOAkzYJ
- OSF Add on spacing : https://trello.com/c/faxDp82u
- Logout alert top spacing : https://trello.com/c/V913ExEn

Misc style fixes for 0.42 - more trello bugs

---

website/static/js/contribManager.js
website/static/js/pages/register_1-page.js
website/static/js/project.js
website/templates/project/settings.mako

Resolve Trello bugs:
1. https://trello.com/c/Alk8GJ71/129-modals-should-have-bullet-text-for-add-on-behavior-not-boxes
2. https://trello.com/c/xJOEEdzX/167-notifications-settings-updated-text-should-be-green-not-black
3. https://trello.com/c/72NucmJc/181-modal-has-title-text-that-is-too-large

[Feature Fix] [Style Guide] Refine Modal and text color

---

website/static/css/pages/project-page.css
website/static/css/style.css
website/static/js/project.js
website/templates/util/render_node.mako

Resolved Trello Bugs:
1. https://trello.com/c/ZiLuaNbu/236-project-and-component-titles-are-not-bolded
2. https://trello.com/c/PtkGLihD/279-add-links-modal-add-contributors-modal-etc-results-and-adding-text-should-be-headers
3. https://trello.com/c/72NucmJc/181-modal-has-title-text-that-is-too-large
4. https://trello.com/c/kJzhvkzD/280-add-links-modal-search-results-have-inconsistent-spacing

[Feature Fix] [Style Guide] Fix bugs on Trellos

---

website/templates/public/pages/active_nodes.mako

Purpose
=======
Closes https://github.com/CenterForOpenScience/osf.io/issues/3462
Changes
=======
```anchor``` class added to headings that required it.
Side Effects
=========
None

[feature] Anchor public activity links properly

---

website/addons/dataverse/static/dataverseUserConfig.js
website/addons/dataverse/templates/dataverse_credentials_modal.mako

<b>Purpose</b>
Fix the problem that dataverse error message persist even if you change the option selection. Closes https://trello.com/c/DB7jwnok/35-dataverse-error-message-persists-despite-choosing-a-new-selection

fix the problem that dataverse error message persist 

---

website/templates/public/pages/active_nodes.mako

Purpose
======
Fixes typo introduced in https://github.com/CenterForOpenScience/osf.io/pull/3564
Changes
=======
Quotation mark added
Side effects
=========
None

[feature] Fix typo in Public Activity

---

website/addons/dataverse/static/dataverseNodeConfig.js
website/static/js/citationsNodeConfig.js

<b>Purpose</b>
Fix the problem that access token states doesn't update immediately. Closes https://trello.com/c/zXYPxkjB/259-import-dataverse-access-token-modal-pops-up-after-creating-access-token-on-project-settings

fix the problem that token status doesn't update at once

---

website/addons/dataverse/static/dataverseFangornConfig.js
website/addons/figshare/static/figshareFangornConfig.js
website/addons/github/static/githubFangornConfig.js
website/addons/s3/templates/s3_node_settings.mako
website/static/css/addonsettings.css
website/static/js/fangorn.js
website/static/js/filepage/index.js
website/templates/project/addon/node_settings_default.mako
website/templates/project/modal_add_contributor.mako
website/templates/project/modal_add_pointer.mako

Resolved Trello Bugs:
1. https://trello.com/c/mAG4OHYd/31-project-settings-change-button
2. https://trello.com/c/PRYjAalf/11-file-detail-buttons-not-spaced-when-reduced-browser-window
3. https://trello.com/c/i5qYapLF/12-sharing-tab-add-new-contributors-modal-add-contributors-plus-button-not-centered-and-wrong-color
4.https://trello.com/c/57NrbXoz/17-files-widget-github-figshare-upload-buttons-should-be-blue-not-green

[Feature Fix] Deferred Trello Style Guide Bugs

---

website/templates/profile.mako
website/templates/profile/account.mako
website/templates/profile/notifications.mako

Resolve #3588
Delete unnecessary semicolon near link tag

[Hoxfix] Delete unnecessary semicolon on link style tag

---

website/templates/public/pages/help/registrations.mako

include Archiver in prep for sending next user email at the end of the week.

hotfix/ getting started - update registration

---

website/templates/public/pages/faq.mako

in preparation for next user email

hotfix/ update faq to include preservation fund

---

website/addons/wiki/templates/edit.mako
website/static/css/pages/contributor-page.css
website/static/css/style.css
website/static/js/fangorn.js
website/static/js/filepage/index.js
website/static/js/notificationsTreebeard.js
website/static/js/pages/project-dashboard-page.js
website/static/js/project.js
website/templates/project/contributors.mako
website/templates/project/modal_duplicate.mako
website/templates/project/view_file.mako
website/templates/public/pages/active_nodes.mako
website/templates/public/pages/getting_started.mako

Addresses several of the Trello cards for style for 0.43
https://trello.com/c/4RpR6p0R
https://trello.com/c/rYUHPucN
https://trello.com/c/jXBBCrNK
https://trello.com/c/UFPXbgIo
https://trello.com/c/UFPXbgIo
https://trello.com/c/srMVbQhO
https://trello.com/c/TDKtEJgy
https://trello.com/c/soe7QcTc
https://trello.com/c/Yz9cpXrV
https://trello.com/c/6QlNBF7M
https://trello.com/c/uQJ90lyK
https://trello.com/c/qMNdQm1g

[Style] [Ready] Deferred style cards misc fixes

---

website/addons/googledrive/templates/googledrive_user_settings.mako

Profile settings configure addon page typo fixed

Fix spelling of account in github addon

---

website/templates/public/pages/help/citations.mako
website/templates/public/pages/help/contributors.mako
website/templates/public/pages/help/view_only.mako

**Purpose**
Fix typos on Getting started. Close #3633.
**Changes**
Simple html changes.
None

Fixed Typos on Getting Started Page

---

website/templates/components/dashboard_templates.mako

Adds placeholder text to "Create Project' form. Close issue #3658.
Simple html change.
None.

 Gives "Create Project" form placeholder text.

---

bower.json
website/static/css/pages/getting-started-page.css
website/static/css/style.css
website/templates/include/profile/settings_navpanel.mako
website/templates/profile/account.mako
website/templates/project/modal_duplicate.mako
website/templates/public/pages/active_nodes.mako
website/templates/public/pages/faq.mako
website/templates/util/render_node.mako

Fixes the following Trello cards:
https://trello.com/c/4RpR6p0R
https://trello.com/c/dXX6OioD
https://trello.com/c/cSzGd1ya
https://trello.com/c/CWj6sY7R
https://trello.com/c/zNY34VaB
https://trello.com/c/t9y7mTVi
https://trello.com/c/imvv0JJs

[Ready] [Style] 0.43 Style issues bundle 

---

website/archiver/__init__.py
website/archiver/decorators.py
website/archiver/listeners.py
website/archiver/model.py
website/archiver/tasks.py
website/archiver/utils.py

Have code meet OSF style guidelines.
Some minor spacing and spelling changes. 
None.

[feature] Minor style guide related clean ups and spelling corrections

---

api/nodes/views.py

Changed 'pk' to 'node_id' in node mixin comment to bring up to date with previous pr

Changed comment variable name

---

website/static/css/addonsettings.css
website/static/css/style.css
website/templates/project/project.mako
website/templates/public/pages/faq.mako

Addresses the following Trello issues: 
https://trello.com/c/dXX6OioD
https://trello.com/c/t2hlx0AQ
https://trello.com/c/105Uv3xu
https://trello.com/c/SGqpBu7A

[Style] [Ready] Further fixes for deferred style bugs

---

website/addons/dataverse/templates/dataverse_node_settings.mako

<h2>Purpose</h2>
Remove excess row padding for Dataverse import access Token Line. Close #3626 . Generally make DV addon markup more consistent. 
<h2>Changes</h2>
Simple Html change.
<h2>Side Effects</h2>

Make Dataverse Addon Markup Consistent with Default. 

---

website/templates/search_bar_help_modal.mako

add a space between "the" and "Lucene"

fixes typo in search help modal

---

website/addons/box/views/auth.py
website/addons/dropbox/views/auth.py
website/addons/googledrive/static/googleDriveUserConfig.js
website/addons/googledrive/templates/googledrive_user_settings.mako
website/addons/googledrive/views/auth.py
website/static/js/osfLanguage.js

Purpose
-----------
Fixes: 
- https://trello.com/c/TlpVtEpJ/83-google-drive-disconnect-account-misspelling
- https://trello.com/c/TLgfzDzk/93-box-account-connection-should-not-have-a-success-alert-at-top-of-page
- https://trello.com/c/KXtP9yQH/101-dropbox-account-connection-should-not-have-a-success-alert-at-top-of-page
- https://trello.com/c/y7oobIw4/123-user-settings-strange-blue-alert-message-upon-disconnecting-google-drive
Changes
------------
- Remove green success alerts when authorizing Box, Dropbox and Google Drive to make this consistent with the OSF style guidelines
- Remove googledrive deauth success message and unused deauth messages 
- Fix a typo

[feature] Fix User Settings UI

---

website/addons/box/static/box.css
website/addons/dropbox/static/dropbox.css
website/templates/profile/addons.mako
website/templates/project/addon/node_settings_default.mako

Fixes these Trello issues:
https://trello.com/c/iwxYLgYG
https://trello.com/c/105Uv3xu
Minor layout and css fixes.
None. But add on folder change functionalities need to be checked.

[Style] [Ready] Last deferred style fixes

---

website/templates/public/pages/getting_started.mako

Fixes: https://github.com/CenterForOpenScience/osf.io/issues/3709
Add anchor classes for proper sizing with fixed headers. 
None.

Add anchor classes to the target headers in getting started

---

website/addons/dataverse/static/dataverseNodeConfig.js
website/addons/dataverse/templates/dataverse_node_settings.mako
website/addons/github/templates/github_node_settings.mako
website/addons/s3/static/s3NodeConfig.js
website/addons/s3/templates/s3_node_settings.mako
website/static/js/folderPickerNodeConfig.js
website/templates/project/addon/node_settings_default.mako

Purpose
-------------
Minor language changes for correctness and consistency
Changes
-----------
- Add-ons disconnected from project settings say "Disconnected" addon instead of "Disconnect"
- Lowercase "From" in "Import Account From Profile" 
- Change S3 to say "Import Account From Profile"

[feature-fix] user/project settings language fixes

---

website/static/js/project.js
website/templates/util/render_node.mako

Fixes issue: #3651 
Minor change of icons.
None.

Change plus icon to angle in render_node

---

website/templates/public/pages/help/view_only.mako

<h1> Purpose</h1>
fix spacing on Getting Started page. Close Trello card:
https://trello.com/c/is0rdWev/144-getting-started-page-remove-spaces-around-em-dashes
Simple html
None.

Fix Language on Getting Started Page

---

website/addons/box/static/boxNodeConfig.js
website/addons/dataverse/static/dataverseNodeConfig.js
website/addons/figshare/static/figshare-node-cfg.js
website/addons/github/static/github-node-cfg.js
website/addons/s3/static/s3NodeConfig.js
website/static/js/citationsNodeConfig.js
website/templates/emails/digest.html.mako
website/templates/emails/file_operation_failed.html.mako
website/templates/emails/file_operation_success.html.mako
website/templates/emails/transactional.html.mako

Resolve Trello bugs:
1. https://trello.com/c/O8Vs1EIJ/161-ok-still-being-used-in-button-of-account-selection-modal-for-dataverse-mendeley-and-zotero
2. https://trello.com/c/TM9hCt68/158-s3-deauthorize-button-in-modal-should-be-red
Resolve Github issue:
https://github.com/CenterForOpenScience/osf.io/issues/3699
In this PR, it deletes all top-margin for the recent activity heading in email template.  I can't test it all, but I still changed the code. Because they use the same structure, in which multiple margins are applied to heading.

[Feature Fix] Fix button style and email template extra margin

---

website/addons/dataverse/templates/dataverse_credentials_modal.mako

Makes drop-down text more specific, closes #3728.
simple html
None

Change Placeholder Text of Dataverse Repository Drop-down Menu

---

website/addons/box/static/boxUserConfig.js
website/addons/box/tests/test_views.py
website/addons/box/views/auth.py
website/addons/dataverse/static/dataverseNodeConfig.js
website/addons/dataverse/static/dataverseUserConfig.js
website/addons/dropbox/static/dropboxUserConfig.js
website/addons/dropbox/views/auth.py
website/addons/figshare/static/user-cfg.js
website/addons/figshare/views/auth.py
website/addons/github/static/github-node-cfg.js
website/addons/github/static/user-cfg.js
website/addons/googledrive/static/googleDriveUserConfig.js
website/addons/googledrive/tests/test_views.py
website/addons/googledrive/views/auth.py
website/addons/s3/static/s3NodeConfig.js
website/addons/s3/static/user-cfg.js
website/static/js/addonSettings.js
website/static/js/osfLanguage.js

- Make language on modals for deauthorizing add-ons consistent. 
- Remove alert messages that appear at the top of the project and user settings pages

[feature-fix] Language and style fixes for user and project addon settings

---

website/addons/dataverse/static/dataverseNodeConfig.js
website/addons/dataverse/static/dataverseUserConfig.js
website/static/css/share-search.css
website/util/rubeus.py

Resolved Github bugs:
1. Private Link in file tree should say "Private Link", not "Private Component"
https://github.com/CenterForOpenScience/osf.io/issues/3621
2. SHARE main page overflow on mobile
https://github.com/CenterForOpenScience/osf.io/issues/3681
3. Improve error message when connecting Dataverse account 
https://github.com/CenterForOpenScience/osf.io/issues/3723
1) Add selection content check inside sendauth method.
2) Add media css code for share and change two columns into one in mobile screen
3) Add if-conditional statement to check whether show "private component" or "private link"
None

[Feature Fix] Fix GitHub UI Bugs

---

website/project/views/node.py

Make case more consistent on alert message. Close #3623.
simple wording change.
None.

Change Case On Alert Message

---

website/templates/project/view_file.mako

Make view files cursors consistent for opening and closing tab. Close #3734.
Simple html.
<h1> Side Effects </h1> 
None.

Add Pointer Class Cursor to View Files Page

---

website/addons/dataverse/templates/dataverse_node_settings.mako

Make the Project Settings error message reflect the one on Dataverse's page. Close issue #3644.
Simple html change.
None.

Change Dataverse Message on Project Settings

---

website/templates/public/pages/getting_started.mako

fix spelling of collaboration
remove registration video

hotfix/ getting started corrections

---

website/search/elastic_search.py
website/static/js/search.js
website/templates/search.mako

<b>Purpose</b>
Fix the problem that files and wiki link doesn't show up on search. Closes https://github.com/CenterForOpenScience/osf.io/issues/3827.

fix the problem that files and wiki link doesn't show up on search 

---

website/addons/github/model.py

Add underline to make Github message more consistent. Close #3849.
Adds ```<u>``` tag to make consistent with others.

Add Underline to Github Message

---

website/templates/project/forks.mako

Simplify forks language. Close #3612.
Simple Html.

Change Language on Forks Tab

---

website/static/css/front-page.css
website/static/js/pages/home-page.js
website/templates/index.mako

This PR updates the front page with the latest version from the designers. It fixes the issues with the network animation
Replaced js in home-page.js with updated version
Replaced bits of css 
Most of the content is not changed so there shouldn't be any.

[Fix] [Ready] Updates front page to fix animation and minor layout

---

website/addons/s3/static/s3NodeConfig.js
website/addons/wiki/templates/add_wiki_page.mako
website/static/js/osfHelpers.js

Fix modal button style
Resolved #3879 
1. Change the button text 
2. Change the button color
None.

[Feature Fix] [Style guide] Fix modal button style

---

website/static/js/search.js
website/templates/search.mako

Allows users to distinguish registrations with the same name. Close #3615.
small js changes to format dates and html to display them.
None.

Registrations in Search Now Have Dates

---

website/addons/s3/static/settings.json

While Beijing is not currently a vaild bucket location, Sao Paulo is.

[featuer fix] Fix endpoint mismatch

---

website/addons/wiki/templates/edit.mako

Make the order of the wiki page toggle buttons and the file page toggle buttons consistent. Close  #3888.
<h1> Change </h1>
The divs have been switched.
<h1> Side effects </h1> 

Make Toggle Buttons Consistant

---

website/static/css/front-page.css
website/static/js/pages/home-page.js
website/templates/index.mako

Attempts to fix the following Trello cards:
Save button cut off: https://trello.com/c/qXifzjSj
Password help text cutoff : https://trello.com/c/DRdKB1jX
Larger margin: https://trello.com/c/4gGTdjBN
Kara Woo quote: https://trello.com/c/RAuhcUGK
Static network background opacity: https://trello.com/c/Lj46oE3U
Img alt text: https://trello.com/c/vYzH2mft
Animation off center: https://trello.com/c/YB2Uj0vz

[Ready] Front page fixes for 45

---

package.json
website/static/css/front-page.css

Fixes the following Trello cards:
Treebeard icon error: https://trello.com/c/fZ1qqhfP
Static network background: https://trello.com/c/Lj46oE3U
Includes a treebeard install update

[Ready] 0.45 Trello Fixes 2 

---

website/templates/emails/email_removed.txt.mako
website/templates/emails/primary_email_changed.txt.mako

<b>Purpose</b>
Improve remove email address email language. Closes https://github.com/CenterForOpenScience/osf.io/issues/3922.

improve the email language

---

website/static/css/pages/profile-page.css
website/static/js/fangorn.js

Fixes following Trello cards
- Impactstory, first column of social:  https://trello.com/c/lml78IVc
- Keep Both button: https://trello.com/c/Kec6XhNM

[Ready] 0.45 Trello Fixes - 3

---

website/addons/s3/static/s3NodeConfig.js

https://trello.com/c/vIlsQfHO/54-invalid-bucket-name-button-options-are-wrong
Use the confirm action correctly
None

[Feature Fix] Change button to correct action

---

website/static/js/projectorganizer.js

0.45 includes style fixes for Treebeard modals. One modal was overlooked in that change: deleting collections in project organizer. This PR brings that to the new style
The method of constructing the modal is updated to match new style
None

[Ready] Add missing modal adjustment

---

website/static/css/projectorganizer.css
website/static/css/style.css

Fixes issue #3948 
Override the x-index for tb-modal so that it's lower than the navigation 
None

[Ready] Fix treebeard modal covering navigation

---

website/static/js/search.js

<b>Purpose</b>
Fix the problem that share will have two tabs if enter got pressed twice. Closes https://github.com/CenterForOpenScience/osf.io/issues/3433

fix the problem that share will have two tabs if enter got pressed twice

---

website/static/js/privateLinkManager.js

<b>Purpose</b>
Refine language for generate private link modal. Closes https://github.com/CenterForOpenScience/osf.io/issues/3773.

improve the language for create private link modal

---

website/static/css/style.css

Fixes this trello issue:
https://trello.com/c/66kD4BY2
Changed the gradient initial color to white as well to avoid blue tint
Checked in Chrome and Firefox as well to make sure it works there too

[Ready] Change toggle gradient initial color

---

website/static/js/fangorn.js

Fixes Trello issue: https://trello.com/c/p7SGGRd8
There was code left over from the button style change that needed update. The button state was changed to default and disabled while showing "Deleting..." text.
None

[Ready] Apply style guide to delete button

---

website/static/css/typeahead.css
website/static/js/onboarder.js

Makes dates more visible when highlighted in typeahead drop down. Closes #3868.
Removes text-muted class from dates.

Typeahead Dates Now Change Color when Highlighted

---

tests/test_views.py
website/profile/utils.py
website/project/views/contributor.py

Improve email validation when adding unregistered contributors to project, as discussed with @sloria .

Improve email validation for unregistered contributors

---

website/static/js/fangorn.js

Fixes the main problem in issue #3386, with the file renaming bar acting weird on mouse clicks. 
Removes the onclick functionality of FGInput.

[Hotfix] File rename fix

---

website/addons/s3/static/s3NodeConfig.js
website/addons/s3/templates/s3_node_settings.mako

Follow the style guide -- change the button text when button action is executing. 
Resolved  #4032
Add knockout text binding for button text
None

[Feature Fix] Change save button text when saving

---

website/static/js/pointers.js
website/templates/project/modal_add_pointer.mako

<h1>Purpose</h1>
Add spinner to "Add Link" modal. Closes #3611.
<h1>Changes</h1>
Small changes to modal_add_pointers.mako and pointers.js.
<h1>Side Effects</h1>

Adds spinner to "Add Links" Modal.

---

bower.json
website/addons/wiki/templates/edit.mako
website/static/js/filepage/util.js
website/templates/log_list.mako
website/templates/profile/notifications.mako
website/templates/project/addon/citations_widget.mako
website/templates/project/files.mako
website/templates/project/project.mako
website/templates/project/settings.mako
website/templates/project/view_file.mako

Replace the new osf-loader whose image is created by data URI
1) Update OSF style guide version
2) Replace spinner with the new osf-loader
None

[Ehancement] Apply new style guide osf-loader

---

website/static/js/share/stats.js

Date on share was in a sensible format (DD/MM/YY), now it is 'fixed' to american format MM/DD/YY

FeatureFix Date on share in american format

---

package.json
scripts/analytics/addons.py
scripts/analytics/depth_users.py

updates analytics to include newest addons and adds depth user script for community

[hotfix] analytics addons & depth users

---

website/addons/osfstorage/model.py
website/addons/osfstorage/tests/test_models.py

Include contentType and date modified in OSFStorageFileNode.serialized

[Hotfix] OsfStorage metadata

---

website/templates/project/project_header.mako

Forgot to close the div tag...

[feature fix] Fix regression bug in registration template

---

website/project/model.py

Introduced a bug in https://github.com/CenterForOpenScience/osf.io/pull/4124 by removing user from the send_mail kwargs
Re-add user kwarg

Add user back to kwargs

---

website/templates/project/contributors.mako
website/templates/project/modal_add_pointer.mako
website/templates/project/settings.mako

Makes minor fixes for the three issues listed here: 
- Changing case in Add links spinner: https://github.com/CenterForOpenScience/osf.io/issues/4099
- Add period to settings page sentence: https://github.com/CenterForOpenScience/osf.io/issues/4104
- Sharing pahe title: https://github.com/CenterForOpenScience/osf.io/issues/4109
Text changes
None

[Hotfix] Minor text related fixes

---

scripts/populate_conferences.py

add SPSP 2016

---

scripts/tests/test_approve_registrations.py
scripts/tests/test_embargo_registrations.py

Ensure cron job scrip tests work

[feature fix] Tests were calling old class property names

---

framework/auth/views.py
framework/status/__init__.py
website/language.py
website/mails.py
website/templates/alert.mako
website/templates/emails/confirm.txt.mako
website/templates/emails/welcome.html.mako

Newly signed up users will now receive a new "confirm email" email.
The confirmation link now links to the user's dashboard rather than user settings.
Upon confirming their email users will receive a "welcome" email.
There is a new welcome message displayed on the user's dashboard.
Note: It appears that push status message does not currently work with fakecas locally.

[Feature]signup onboarding

---

website/templates/project/modal_add_contributor.mako

Easy change for button text
Resolve https://github.com/CenterForOpenScience/osf.io/issues/4138

[Feature Fix] Change button text from save to add

---

website/static/js/fangorn.js
website/util/rubeus.py

Don't allow addons that are having service issues to prevent file related pages from loading.

[Hotfix] Failed addons

---

website/project/model.py

Reverts CenterForOpenScience/osf.io#4188

Revert "Make parent pending registration private"

---

tests/test_models.py
website/project/model.py
website/templates/project/project.mako

Reverts CenterForOpenScience/osf.io#4184

Revert "Disallow making pending registrations public"

---

scripts/consistency/consistency_of_users_to_projects.py

<b>Purpose</b>
Add scripts to check the consistency of users to projects. Closes https://github.com/CenterForOpenScience/osf.io/issues/1255

add scripts to check the consistency of users to projects

---

tests/test_views.py
website/project/views/node.py
website/routes.py
website/templates/index.mako
website/templates/project/project_header.mako
website/templates/project/statistics.mako

<b>Purpose</b>
Add redirect and change url for analytics page. Closes https://github.com/CenterForOpenScience/osf.io/issues/4105

add url redirect for statistics page

---

website/static/js/addonPermissions.js
website/static/js/pages/profile-settings-addons-page.js
website/templates/profile/addon_permissions.mako

Fixes this Trello card: Expand/collapse UI missing for some add-ons in User Settings https://trello.com/c/c5hO4Spy
The initialization where the expand plugin was run did not happen when all addons were reliable loaded and existing in the DOM. This fix moves the code so that it runs after page is loaded. 
Needs testing with all add ons

Move addon auth table expand instantiation

---

website/addons/dataverse/static/dataverseUserConfig.js
website/addons/dataverse/templates/dataverse_user_settings.mako
website/static/js/addonPermissions.js
website/static/js/citationsNodeConfig.js
website/templates/profile/user_settings_default.mako

Add on to the fix for this Trello card: 
https://trello.com/c/c5hO4Spy
Completed some changed missing from the previous fix to apply to all add ons. 
None, and I tested locally to make sure the add ons work

Fix mendeley, zotero, dataverse toggleHeight

---

package.json

Fixes this Trello bug 
https://trello.com/c/yWV0hc60
Updates Treebeard
In treebeard the change was in this commit:
https://github.com/caneruguz/treebeard/commit/9f1458a9f5961460dcd84c833b5da0180219f253
None. I checked with other implementations of treebeard and sorting is working as usual there.

[Ready] Update treebeard version with better sorting

---

website/static/js/filepage/index.js

fixes trello, and small syntax fixes

Fix panel rendering without enableEditing()

---

website/addons/dataverse/static/dataverseUserConfig.js
website/static/js/citationsNodeConfig.js
website/static/js/pages/profile-settings-addons-page.js

Attempts to fix this: https://travis-ci.org/CenterForOpenScience/osf.io/builds/78100419
Added require to load js

[Ready] Fix build fail

---

framework/auth/views.py

Removes the cookie on user logout.

[feature] on logout delete the multi-domain cookie

---

framework/auth/cas.py

prevents failures on missing attributes from profile requests, standardize accessToken and accessTokenScope between endpoints
[#OSF-4336]

[feature] cas attributes & scope compatibility

---

website/templates/search.mako

<b>Purpose</b>
Identify component registration. Closes [#OSF-4259].
<b>Changes</b>
before change:
after change:

identify component if it is a registration

---

website/notifications/events/files.py

Fix bug preventing the logging of files with names containing unicode

---

tests/test_events.py
website/notifications/events/files.py

This fixes [#OSF-4342] and [#OSF-4441]
Adds a class to the event module so that rename events are handled correctly.

Fix file rename issue

---

framework/auth/views.py

Removes the cookie on user logout.

[hotfix] logout delete multi domain cookie

---

api/base/authentication/drf.py
tests/api_tests/users/test_views.py

Make get_user consistently return None
OSF-4459

[Feature] Basic Auth causing 500s

---

tests/api_tests/nodes/test_views.py

Continuation of #4291.
- add more assertions for log creation
- split some tests into separate cases when appropriate
None

[RfR] Log Audit pt. 2

---

website/notifications/events/files.py

Purpose
======
Update language for clarity. "The language is not really clear what is happening."
Changes
=======
Language updated for clarity.
Side Effects
=========
None
[#OSF-4413]

[Feature][Fix] Update file notification language for clarity

---

website/static/js/logFeed.js
website/templates/util/render_node.mako

<b>Purpose</b>
Reverse previous code change to fix the recent activity log render problem. Closes [OSF-4546]

fix the recent activity log

---

website/static/js/fangorn.js

Purpose
======
Fix bug from #4299 due to var naming verbosity
Changes
=======
Revert to uglier, functioning code
Add comment explaining special case 
Side Effects
=========
None

[Feature][Fix] Fix bug from Dataverse special casing

---

website/templates/profile/account.mako

Update language in account settings to match the discussion from PR #4295

Change text to explain merging of accounts

---

website/addons/dropbox/model.py
website/addons/dropbox/tests/test_models.py

Dropbox logs no longer prepend node_settings.folder to path

[Hotfix] Dropbox logs

---

framework/sessions/__init__.py

This code should be tested on staging first with all supported browsers, upon success immediately moved to production.
QA, contact me and I can help setup the required testing scenario on staging.

[hotfix] remove potential legacy cookie

---

api/base/utils.py
api/nodes/serializers.py
api/users/serializers.py
tests/api_tests/users/test_views.py
website/filters/__init__.py

https://openscience.atlassian.net/browse/OSF-4535
- move /data/attributes/profile_image_url to /data/links/profile_image
- add helper for adding dict items based on DEV_ONLY mode
None

[RfR] Move profile image to links

---

requirements/metrics.txt
tasks.py

[feature] docker deployment std. wheelhouse

---

tests/test_contributors_views.py
website/project/views/contributor.py
website/static/js/contribAdder.js

Now acts the same in child node as the search results.
Relates to #4301

Update import contributors

---

scripts/triggered_mails.py
tests/test_mails.py
website/mails/queued_mails.py

Fix queued-mails

---

website/static/js/filepage/index.js

Word change based on @jinluyuan's suggestion.

Fix embed wording change

---

website/addons/dataverse/static/dataverseFangornConfig.js

Change text of the Publish button to reduce width of the button.

OSF-4475 change text for Publish button

---

README.md

Added copy api settings string.

---

scripts/analytics/benchmarks.py
scripts/osfstorage/files_audit.py
scripts/osfstorage/glacier_audit.py
tests/test_addons.py
tests/test_websitefiles.py
website/addons/base/views.py
website/files/models/base.py
website/settings/__init__.py
website/settings/defaults.py

Use jwts for waterbutler credentials endpoint and remove restrict_waterbutler
OSF-4733

[Feature] jwts for waterbutler

---

website/templates/profile/account.mako

"To merge or... to log in" is the correct grammar

(small grammar fix) Added "to"

---

website/mails/presends.py
website/settings/defaults.py

@sloria, change 
``` WELCOME_OSF4M_WAIT_TIME_GRACE = timedelta(days=12) ```
to
``` WELCOME_OSF4M_WAIT_TIME_GRACE = timedelta(minutes=2) ```

Add a settings grace period

---

scripts/migration/migrate_date_last_login_for_current_users.py
scripts/migration/migrate_mailing_lists_to_mailchimp_field.py
website/conferences/views.py
website/mails/presends.py
website/mails/queued_mails.py

Add migration for date_last_login

Add date_last_login update migration

---

scripts/box/connect_external_accounts.py
website/addons/box/model.py

Purpose
======
Fixes bug from #2195

[feature][fix] Ensure proper oauth grants for Box

---

website/conferences/utils.py

Fixes (https://openscience.atlassian.net/browse/OSF-4919)

Add signal that user is confirmed

---

website/addons/dataverse/static/dataverseFangornConfig.js

Purpose: Change the button style and text for the modal.
Changed: button style changed from "primay" to "default". Text change from "okay" to "close"

OSF-4794 Changed button style and text

---

website/conferences/views.py

Make the query for conferences much faster
https://openscience.atlassian.net/browse/OSF-4756

[Hotfix] Conference page

---

requirements.txt

https://openscience.atlassian.net/browse/OSF-5033

[feature] pin certifi to version compatible with mailchimp

---

website/templates/include/profile/social.mako
website/templates/index.mako
website/templates/public/forgot_password.mako
website/templates/public/login.mako
website/templates/public/pages/help/user_profile.mako

<b>Purpose</b>
The purpose was to change capitalization in some places that weren't fixed by https://github.com/CenterForOpenScience/osf.io/pull/4436/files
<b>Changes</b>
The changes made were to user_profile.mako, social.mako, login.mako, and forgot_password.mako.

Changed capitalization for [OSF-4583]

---

website/templates/nav.mako

<b>Purpose</b>
The purpose is to change "Forgot Password?" to "Forgot password?"
<b>Changes</b>
"Forgot Password?" became "Forgot password?"

Changed forgot password [OSF-4583]

---

website/templates/include/profile/settings_navpanel.mako

OSF-4715 made all the panel headings, except Developer apps, sentence case

Make Developer apps sentence case

---

tasks.py

Makes it harder to destroy your database... or prod's database. *cough*
Second commit contains fixes for https://github.com/CenterForOpenScience/modular-odm/pull/125

[Hotfix] Transact shell

---

website/addons/wiki/static/WikiEditor.js
website/addons/wiki/templates/edit.mako
website/static/css/pages/wiki-page.css

DIsplayed line numbers by default in the Wiki Edit section
[#OSF-4467]

Changes made in Wiki Edit

---

website/templates/profile/account.mako

Add tooltip in profile settings to explain the merging of accounts

---

website/static/js/licenses.js

[RfR] Delete AFL3 license as it is unused

---

website/static/js/koHelpers.js
website/static/js/registrationUtils.js

Looks like the datepicker KO binding handler got removed during merge.
- Add it back.
- Don't show error messages on create new draft reg
- Warn user if the try to leave reg editor with unsaved changes

[RfR] Re-add datePicker KO binding

---

tasks.py
website/addons/wiki/settings/defaults.py
website/addons/wiki/shareServer.js
website/addons/wiki/utils.py

changes are backwards compatible w/ default settings
[OSF-5099](https://openscience.atlassian.net/browse/OSF-5099)

[feature] sharejs use mongodb connection string format

---

website/static/js/profile.js

Previously dates on the profile page would give error messages at weird times.
I went into the Date mixin and moved around some of the code and provided some new checks as well as editing some old ones to create a more intuitive experience that provides feedback to the user at the appropriate time.
[#OSF-4571]

[Feature] Fixed issues with creating dates

---

website/templates/index.mako

<b>Purpose</b>
The purpose of this change is to edit the homepage text to emphasize open source.
<b>Changes</b>
The change made was to replace "Free. Get started today." with "Free and Open Source. Start now."

Changed home page text to address ticket #OSF-4673

---

website/search/share_search.py
website/static/js/share/index.js
website/static/js/share/utils.js

Just a few updates to get all the routes pointing to the right place.
Plus a little hack with the return values that may allow us to avoid a migration. Yippee!

[Hotfix] Last steps to get the SHARE documents API up and running

---

tests/test_models.py
tests/test_views.py
website/project/model.py
website/project/signals.py

- Remove some dead code
- Let MetaSchemas be updated w/o dropping collections
- Some models tests updates

Update Draft Reg

---

framework/auth/core.py
website/util/__init__.py

https://github.com/CenterForOpenScience/osf.io/pull/4492

Disconnect signal through context_manager

---

website/project/views/drafts.py
website/static/js/registrationUtils.js
website/templates/project/registrations.mako

see: https://openscience.atlassian.net/browse/OSF-5228
Add loading screens and block UI when registrations page content is loading

[WIP] Draft Reg Loading

---

website/static/js/pages/registration-edit-page.js
website/static/js/registrationEditorExtensions.js
website/static/js/registrationUtils.js
website/templates/project/registrations.mako

- bug with "Page not found" when creating new draft registrations
- undefined variable in embargo end date validator (caused embargo modal to be broken)
- filePicker autoselection when addons are enabled

[WIP] Feature/prereg fixes

---

website/project/metadata/prereg-prize.json
website/static/js/components/autocomplete.js
website/static/js/registrationModal.js
website/static/js/registrationUtils.js
website/templates/project/register_draft.mako

- Fix cross-browser date comparison issues
- Use `dateInitiated` in autocomplete 
- Ensure correct validator order for embargo end date

More Prereg Fixes

---

website/addons/citations/provider.py
website/addons/mendeley/tests/test_views.py
website/addons/mendeley/views.py
website/addons/zotero/model.py
website/addons/zotero/tests/test_views.py
website/addons/zotero/views.py

Fixes several issues with testing and the client from #4657

Feature/zotero credentials error redux pt. 2

---

tasks.py

Hello,
sometimes during development we had to clean *.pyc files to get things working.
So I am adding this as a task =)
Hope you like.
Kind regards,
Daniel

this adds a clean task to remove *.pyc files

---

website/addons/dataverse/client.py
website/addons/dataverse/static/dataverseUserConfig.js

To address the problem of adding a non-dataverse account and change error messages.
Changes are made to the dataverseFangornConfig.js and client.py files.
In dataverseFangornConfig.js file, few conditionals were added to improve the error messages shown in the modal under different circumstances.
In client.py file, it is changed so that when _connect() returns an empty connection, a ConnectionError is raised.

OSF-4309 Improve validation and error messages

---

website/static/js/filesWidget.js
website/static/js/osfLanguage.js
website/static/js/pages/render-nodes.js
website/static/js/registrationEditorExtensions.js
website/static/js/registrationUtils.js
website/templates/project/edit_draft_registration.mako
website/templates/project/registration_editor_extensions.mako
website/templates/project/registrations.mako

- Make the filesWidget preload data so it is compatible with adding loading screens
- Add loading screens for RegistrationEditor filePickers
- Only show progress bars for drafts with at least one required question
- Some small JS cleanup and fixes

Some Prereg fixes

---

scripts/populate_conferences.py

*change URL
*add logo
*add admin
The administrator will be reviewing submissions to ensure there are no copyright violations. The group will make it readily apparent to its users that an administrator will be monitoring submissions and will be a contributor on their project.

updating psi chi repository

---

api/collections/views.py
api_tests/collections/test_views.py

Purpose
------------
Add the ability to do bulk requests to the /v2/collections/ set of endpoints. Closes https://openscience.atlassian.net/browse/OSF-5349
Changes
------------
Added mixins, methods, and variables to the appropriate views.
Added tests.
Side effects
None

Bulk Collections

---

tests/factories.py
tests/test_views.py
website/project/decorators.py
website/project/model.py
website/project/views/node.py

From https://openscience.atlassian.net/browse/OSF-5355

Blocks anonymous links from viewing registrations and forks

---

website/static/css/pages/project-page.css

Takes care of https://openscience.atlassian.net/browse/OSF-5342

Fix description lines

---

tests/test_registrations/test_models.py
website/project/metadata/prereg-prize.json
website/project/model.py
website/static/js/osfHelpers.js
website/templates/emails/prereg_challenge_rejected.html.mako

There are some important changes in samchrisinger:feature/admin-app-forms that should be merged into the release branch. This PR aggregates those changes. 
- let $osf.block apply to a specific DOM element
- add $osf.dialog
- change flags to snake case in Prereg Challenge schema
- don't delete DraftReg approval reference upon rejection
- let DraftReg flags get updated (but not overwritten) if the schema
- changes
- add setter for DraftReg flags
- add is_rejected property to DraftReg
- update DraftRegApproval to use a URL template rather than url_for

Admin App Forms: The Good Parts

---

admin/pre_reg/views.py

Passing kwargs to redirect doesn't work.
Manually append query string to URL in approve/reject redirect

Fix Prereg admin redirects

---

tasks.py

Make it an alias for `invoke --list`. Better than a traceback! :-)
**Before:**
```
[osf.io]$ invoke
Traceback (most recent call last):
File "/Users/whit537/workbench/cos/osf.io/env/bin/invoke", line 9, in <module>
load_entry_point('invoke==0.9.0', 'console_scripts', 'invoke')()
File "/Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/invoke/cli.py", line 304, in main
dispatch(sys.argv)
File "/Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/invoke/cli.py", line 297, in dispatch
return executor.execute(*tasks, dedupe=dedupe)
File "/Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/invoke/executor.py", line 71, in execute
tasks = self._normalize(tasks)
File "/Users/whit537/workbench/cos/osf.io/env/lib/python2.7/site-packages/invoke/executor …
```

[feature] Add a default invoke task

---

website/static/js/project.js

issue: https://openscience.atlassian.net/browse/OSF-5159

Add quotes around tag text to url opened when tag is clicked.

---

CHANGELOG
api/nodes/urls.py
website/templates/project/project.mako

and make citations endpoint dev-only.

Disable custom citations UI 

---

scripts/migration/migrate_date_modified_for_existing_nodes.py
tests/test_models.py
website/project/model.py
website/project/views/node.py

Issue: https://openscience.atlassian.net/browse/OSF-5173
NodeList is sorting by id and it thinks it's supposed to be sorting by date modified
Makes date_modified a field on the node.  When there is a change to the node log, date_modified is updated.  Since date_modified is now a field on the node rather than a property, node list can be sorted by date_modified.
- Serialized node list sorted by date_modified rather than id
- Field added on model

[Ready to Review] Feature/sort nodes by date modified

---

scripts/migration/migrate_date_modified_for_existing_nodes.py

Makes /migration/migrate_date_modified_for_existing_nodes.py resumable.  
From @slora, adds `Q('date_modified', 'eq', None)` to node query

[Ready] Make migration resumable

---

website/static/js/registrationUtils.js

Adding error handling to the project registrations page was a good idea. Unfortunately we need to check that the current user is and admin when trying to fetch drafts (otherwise we get 403s)
Check that the current user is an admin before trying to fetch drafts.

Only try to fetch drafts if the current user is an admin

---

website/templates/project/edit_draft_registration.mako

$root.check refers to a deleted method
Use $root.toPreview instead

Use toPreview instead of now-deleted check

---

bower.json
website/static/js/fileBrowser.js
website/static/js/tests/fileBrowser.test.js
website/templates/base.mako
website/templates/dashboard.mako

Fixes registration link
Adds the new font
This should get staging2 to work more reliably.

Dashboard redesign component 3 - registration link fixes

---

website/static/js/accountSettings.js

Resending PR to develop
[OSF-4883]

Check merge accounts

---

package.json
website/routes.py
website/static/css/file-browser.css
website/static/js/addProjectPlugin.js
website/static/js/fileBrowser.js
website/static/js/pages/dashboard-page.js
website/static/js/project-organizer.js
website/templates/dashboard.mako
website/templates/nav.mako

Adding missing features and stability.

Dashboard redesign component 3

---

website/project/model.py
website/static/js/components/legend.js
website/static/js/iconmap.js

Adds software to the component lists and uses the font awesome laptop icon.  
The two files affected are $OSFHOME/website/static/js/iconmap.js which adds the icon and $OSFHOME/website/project/model.py which adds software as an option in components
NA

Add 'Software' as a component option

---

website/templates/project/registration_editor_extensions.mako

See: https://openscience.atlassian.net/browse/OSF-5490
Use a different loader for hidden-by-default file pickers

Use a quieter loading indicator for hidden filepickers

---

framework/auth/core.py
website/static/js/profile.js
website/templates/include/profile/social.mako

Add ResearchGate field to user profile

---

website/static/js/citationGrid.js
website/static/js/citationWidget.js
website/templates/project/project.mako

Purpose
-
The previous language was unhelpful to a user who did not understand what this feature was for.
Changes
-
* Changed "More" (above the drop down in the citationWidget) to "Get more citations"
* Changed "Citation Style" to "Enter citation style"
Side Effects
-
None as this is just a language change
[#OSF-5427]

[Feature] Updated language for citationGrid and citationWidget

---

website/templates/project/settings.mako

Fix bug where users with read access see wiki enable button.

[Feature] Check for write access to allow wiki enable/disable

---

admin/templates/base.html
admin/templates/pre_reg/edit_draft_registration.html

Make the page resize better.
Moved the "next page" button to the bottom left. Moved the "last saved" to the top.
In response to https://openscience.atlassian.net/browse/ADM-51
Fixed a few other resizing issues at the same time. The text resize isn't perfect, but certainly better than before.

[Feature] Fix Button in Resizing

---

website/static/js/comment.js
website/templates/include/comment_template.mako

Purpose
-----------
Addresses https://openscience.atlassian.net/browse/OSF-4938?focusedCommentId=27506&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-27506
If a comment is not successfully created/edited, a "Cannot submit comment" error message appears and persists. 
Changes
------------
- Clear the error message after the user creates/edits a new comment successfully
- Use `text-danger` classes for error messages

Fix comment error messages

---

admin/pre_reg/serializers.py
admin/pre_reg/views.py
admin/templates/pre_reg/prereg.html

[Feature] Admin Prereg Embargo indication

---

website/static/js/comment.js

Purpose
-----------
Fix issue where non-anonymous view-only-links still anonymize user names.

Show commenter name in non-anonymized VOLs

---

website/templates/emails/pending_embargo_admin.txt.mako
website/templates/emails/pending_registration_admin.txt.mako

See: https://openscience.atlassian.net/browse/OSF-5521
see below ...

Update registration approval email language

---

website/static/js/fileBrowser.js

Quick fix for failing logic in stagin2

Fix attribute name error

---

website/static/js/fileBrowser.js

Another fix for the stagin2 bug

Check if contributors or tags exist for a project

---

website/routes.py
website/settings/defaults.py

Add noteworthy links node and make it available to mako templates

---

admin/pre_reg/serializers.py

Deal with missing registration_choice

---

scripts/dev_populate_conferences.py
scripts/populate_conferences.py

And allow for partial custom fields.

Add custom TESS field names for OSF4M

---

package.json
website/static/css/file-browser.css
website/static/js/fileBrowser.js
website/static/js/project-organizer.js

The second part makes code structure improvements and UI and interaction improvements. The look should be closer to final product and component structure much more solid.
- A large number of small and large view changes including improve design elements and improve narrow screen interactions and add new UI
- Modals are added for collection interactions, waiting for collections API
- Information panel is close to final form with placeholders for activity list
- Code structure makes improvements by using single link object and less complicated link generation
- m.component mounting is done with the mithril way without too many redraws
- Some data url information is hard coded, these will be changed when API end points are done
- Code quality for what is changed
- UI and interaction of …

Dashboard redesign component Part II

---

website/static/js/fangorn.js

in /files to 'Filter' (both button and placeholder text), and changed variables called SEARCH to FILTER to stay consistent with labeling
[OSF-5543]

Change 'Search' label

---

website/static/js/registrationUtils.js
website/templates/project/edit_draft_registration.mako

under 'Edit draft registration' to local time, matched format with 'Started' and 'Last updated' under 'Registrations'
[OSF-5551]

Change 'Last saved' time 

---

website/project/metadata/prereg-prize.json

Update content of prereg form

---

framework/mongo/handlers.py
tests/base.py
tests/test_conferences.py

PyMongo's built in pooling break toku as sockets are acquired per atomic operation, not thread/request.

Pool PyMongo clients

---

api/base/pagination.py
api/base/settings/defaults.py
api_tests/nodes/views/test_node_list.py

[#OSF-5317]
Purpose
======
1) Prevent page[size] from cascading down to embedded object lists
2) Limit page[size] to a maximum of 100 
Changes
=======
* Set `max_page_size` to 100
* Disable `page[size]` cascading for embeds
Side Effects
=========
None
Example Request & Response
-----------------------------------------
```
GET /v2/nodes/?page[size]=1000&embed=contributors
```
```
HTTP 200 OK
Content-Type: application/vnd.api+json
Vary: Accept
Allow: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS
{
"data": [
{
"id": "9j4kv",
"type": "nodes",
"title": "testproj",
"description": "",
"category": "project",
"date_created": "2016-01-26T21:40:37.961000",
"date_modified": "2016-01-28T15:55:07.406000",
"registration": false,
"fork": false,
"collection": false,
"dashboard": false, …
```

[Feature] Improve behavior for the undocumented page[size] qaram

---

website/templates/log_templates.mako

- Update contributor logs to display non-bibliographic/bibliographic instead of invisible/visible.
- [OSF-5331]

[feature] Bibliographic/Non-Bibliograpic Contributor Logs 

---

api/collections/views.py
api/institutions/views.py
api/nodes/views.py
api/registrations/views.py
framework/auth/core.py
scripts/migrate_registration_and_fork_log.py
website/search/views.py

This moves our list queries to eq queries so that they'll be faster.

Switch outstanding 'contains' queries to 'eq' queries

---

website/static/js/nodesPrivacy.js

This is a simple language change PR responding to a request from QA and Community for Jira ticket
https://openscience.atlassian.net/browse/OSF-4457
Before
---------
Now
------

[RFR] Change language if no nodes privacy settings are changed

---

website/templates/log_list.mako
website/templates/log_templates.mako

- Changes log language from visible/invisible to bibliographic/non-bibliographic.
- Adds custom log language for contributor visibility changes in anonymous view only links.
- Language changes made according to [OSF-5331].

[feature-fix] Bibliographic/Non-bibliographic Contributor Logs 

---

admin/base/settings/local-dist.py
admin/spam/serializers.py
admin/templates/spam/comment.html

Use furl to build from local.py
website.settings DOMAIN should match the actual running osf domain for the deployment

[Feature Fix] OSF links from admin

---

scripts/populate_conferences.py

Fixed the logo url to the new url.

Update logo url

---

api/base/exceptions.py
api/collections/serializers.py
api/collections/views.py
api_tests/collections/test_views.py

for https://openscience.atlassian.net/browse/OSF-5579
Tests follow JSON api specs:
If all of the specified resources can be added to, or are already present in, the relationship then the server MUST return a successful response.
If the client makes a DELETE request to a URL from a relationship link the server MUST delete the specified members from the relationship or return a 403 Forbidden response. If all of the specified resources are able to be removed from, or are already missing from, the relationship then the serverMUST return a successful response.

Add tests for delete non-linked node, and add exitint linked node

---

website/templates/log_templates.mako

- Adds custom log language for contributor visibility changes in anonymous view only links.
- [OSF-5331]

[feature-fix] Contributor Visibility Logs -- Anonymous VOLs 

---

website/static/js/oauthAddonNodeConfig.js

[Hotfix] Send request to import account iff user does not cancel.

---

website/static/js/conference.js
website/static/js/submissions.js

Based on the discussion with community, add date column for conference page
Resolve [OSF-4694]
None

[Enhancement] [OSF Meeting] Add date created column to conference page 

---

website/project/views/comment.py

Purpose:
-----------
When an osfstorage folder is moved from a project to a component's osfstorage, any commented files it contains do not retain those comments.
Fixes JIRA ticket SYNC-119
Changes:
------------
Recursively check folder contents to make sure any commented files are handled.

Hotfix: Handle file comments when moving osfstorage folder

---

api/base/serializers.py

From https://www.flowdock.com/app/cos/qa/threads/AW0vkitpwCNso2VAsyM7LDzgk92
@sloria

[Fix] User embedding in comment serialization

---

tests/test_views.py
website/profile/views.py
website/settings/defaults.py

<b>Purpose</b>
Fix the problem that add emails wipe all the emails and didn't pop confirmation.
Sovles https://openscience.atlassian.net/browse/OSF-5779

ensure emails list return after update user

---

admin/base/settings/defaults.py
api/base/settings/defaults.py
bower.json
framework/flask/__init__.py
framework/tasks/__init__.py
framework/tasks/utils.py
package.json
requirements.txt
website/settings/defaults.py
website/templates/base.mako

sentry client upgrade code for develop branch, already in branches 0.65.0-develop and feature/institution-autodeploy

[feature] sentry update

---

website/templates/emails/confirm.txt.mako

PR to amend #5019
Related to https://openscience.atlassian.net/browse/OSF-5697
(Not sure how this happened, sorry!!)
Builds off of already merged PR that somehow left out the essential language update... Pretty simple, and actually changes the language when it wasn't before. Oops!
Update confirm email template

Actually update confirm email language in template

---

admin/base/settings/defaults.py
api/base/middleware.py
api/base/settings/defaults.py
api_tests/base/test_middleware.py
framework/mongo/handlers.py
framework/tasks/handlers.py
framework/transactions/handlers.py

Standardize usage of framework middleware in both Flask and Django web frameworks

[hotfix] standardize middleware

---

admin/README.md

Add readme to admin
People who are assigned to review admin now have a decent explanation of how to actually get it running. Huzzah!

[Feature] Admin add readme

---

website/static/css/dashboard.css
website/static/js/addProjectPlugin.js
website/static/js/dashboard.js
website/static/js/nodesPrivacySettingsTreebeard.js
website/static/js/notificationsTreebeard.js
website/static/js/project-organizer.js
website/static/js/wikiSettingsTreebeard.js

Fixes multiple QA issues as logged in the Trello list 
https://trello.com/c/bFEyfmRt
https://trello.com/c/nHeE7qIQ
https://trello.com/c/Na1wkTZZ
https://trello.com/c/CK2HGzEN
https://trello.com/c/p3jZMlEH
https://trello.com/c/5F02gZg9
https://trello.com/c/bEuKTN9T
https://trello.com/c/Daxmi4rB
https://trello.com/c/yYYpsSTX
https://trello.com/c/ZRPH9o3f

[WIP] Feature/dashboard fixes 1

---

scripts/populate_conferences.py

NRAO workshop: Molecular Gas in Galactic Environments 2016

Add XGAL 2016 to OSF4M

---

website/static/css/dashboard.css
website/static/js/addProjectPlugin.js
website/static/js/dashboard.js

Further fixes:
https://trello.com/c/BY73npXV
https://trello.com/c/oxUuUdKL
https://trello.com/c/fVd0i9Lk
https://trello.com/c/eSKXvQtt
https://trello.com/c/2snusleW
https://trello.com/c/0anVtmS9
https://trello.com/c/8CLMmXhr
https://trello.com/c/v2y4DQZn
https://trello.com/c/BY73npXV

Feature/dashboard fixes 2 

---

website/static/css/dashboard.css
website/templates/dashboard.mako

Quick fix to padding of alerts on dashboard page

Fix alert spacing on my projects

---

website/static/js/filesWidget.js

<b>Purpose</b>
Fix the problem that on staging, the prereg form cannot go beyond the second page.
Partially fix the https://openscience.atlassian.net/browse/OSF-5855

paritally fix [#OSF-5855]

---

website/static/js/fangorn.js

- Allows rejected files to be cancelled.
- Adds failed uploads (files that exceed the maximum upload size) to the list of uploaded files that can be cancelled. 
- [OSF-5410]

[feature] Remove Large File Uploads

---

website/static/css/nav.css
website/static/css/pages/login-page.css
website/templates/nav.mako

Changes in response to QA.
1.  Change login screen back to avoid responsive design errors
2.  Make signup button stay green when clicking signin
3.  round all button corners

[RFR] Feature/signup button style changes

---

api/applications/serializers.py

This should fix the 500 errors in /v2/applications.

Add get_absolute_url() for application serializer

---

website/static/js/keen.js

Adds referrer url parsing in Keen IO uploads for better searching later on. Adds the pageview data on error for easier diagnostics.
None.

[Feature Fix] KeenIO Referrer Url parsing/Error fix

---

admin/templates/pre_reg/registration_editor_templates.html
website/project/model.py

Disable commenting on draft preregistration if approved.
[OSF-5445](https://openscience.atlassian.net/browse/OSF-5445)
Check if the registration is approved and remove some elements if it is.
None

Disable commenting on draft preregistration if approved

---

website/project/views/contributor.py
website/static/js/contribAdder.js

Jira ticket:  https://openscience.atlassian.net/browse/OSF-5054
Respond to QA bug where contributor is added twice, leading to double logs.
There is a small change to the logic preventing the parent from being added, and I also changed the variable name to the more accurate childrenToChange.

Change nodesToChange to childrenToChange

---

website/static/js/myProjects.js

https://trello.com/b/XQl8eq7J/my-projects

Change collection modal to match new project look

---

api/nodes/serializers.py
website/static/js/addProjectPlugin.js
website/static/js/home-page/quickProjectSearchPlugin.js
website/static/js/myProjects.js
website/static/js/pages/home-page.js

Addresses some of the QA issues as logged in the Trello list
https://trello.com/c/zJqcgOL8/75-my-projects-page-spelling-grammar-capitalization
https://trello.com/c/LmHzuIgk/70-resolve-the-repetition-of-my-projects-title-vs-page-in-the-home-page
https://trello.com/c/NRNMvpHc/77-homepage-language-changes
https://trello.com/c/ZAvyPoee/78-info-panel-does-not-show-line-breaks-for-project-description

[Ready to Review] Dashboard/MyProjects Fixes

---

website/static/js/myProjects.js
website/static/js/project-organizer.js

Have a separate list of flat list items load for the purpose of filtering

Load search items in parallel with projects

---

scripts/populate_institutions.py
tests/factories.py
website/institutions/model.py
website/project/model.py

Purpose
=======
`is_institution` is unnecessary: remove.
Changes
=======
* `is_institution` removed
* `id` is a reserved word in python, changed to `key` in `Insitution.load`
Side Effects
=========
None

[Feature] Remove is_instution field

---

website/static/js/projectSettings.js

to 'patch' to stop removing project tags when project description is edited
[OSF-5802]

Change 'put' request in updateAll

---

website/static/css/dashboard.css
website/static/js/myProjects.js
website/static/js/project-organizer.js
website/templates/dashboard.mako

Includes trello fixes
https://trello.com/c/jXvA8bcG

Dashboard fixes 6 

---

website/static/js/myProjects.js

Redraw so a click is not necessary.
:shipit:

[Fix] Force redraw on initial request completion

---

website/static/js/pages/home-page.js

https://trello.com/c/lNVCdLI6/118-the-dashboard-page-needs-a-title-suggestion-my-dashboard
@caneruguz gave UI approval

[Fix] Add title to "My Dashboard"

---

api/base/exceptions.py
api/base/serializers.py
api/base/utils.py
api/logs/permissions.py
api/users/serializers.py
api_tests/logs/views/test_log_contributors.py
api_tests/nodes/views/test_node_contributors_list.py
api_tests/users/views/test_user_detail.py
website/static/js/home-page/newAndNoteworthyPlugin.js
website/static/js/home-page/quickProjectSearchPlugin.js
website/static/js/logTextParser.js
website/static/js/myProjects.js
website/static/js/project-organizer.js

Trello https://trello.com/c/MzCIowv8/110-disabled-users-that-are-contributors-on-a-project-will-prevent-the-myprojects-and-home-page-from-loading
Disabled contributors are not being handled in the dashboard - causing loading to hang.  The issue is that the dash is trying to access disabled contributors names when we are returning a 410 Gone.
API change - if 410 Gone, returns disabled user names under meta/errors for use in logs and contributor related items.

[Ready to Review] Dashboard/inactive user handling

---

website/static/css/pages/home-page.css
website/static/js/home-page/quickProjectSearchPlugin.js
website/static/js/pages/home-page.js

I increased the size and contrast of a few elements of the new home page.
Old School
New School

Style changes to the homepage to increate contrast on some elements

---

website/static/css/pages/home-page.css
website/static/js/home-page/meetingsAndConferencesPlugin.js
website/static/js/pages/home-page.js

A couple of small button changes.
So 5 minutes ago
-
Fashion forward and case correct
-

Fixed a case, changed button color and weight

---

website/static/js/myProjects.js

https://trello.com/c/dIxjFwIN/134-retracted-registrations-should-not-appear-on-my-projects-page
https://trello.com/c/qSscVKea/136-pending-registrations-should-not-show-on-my-projects-page

[Fix] Filter out unwanted registrations

---

api/base/pagination.py
website/static/js/myProjects.js

Improve loading nodes from cache for my projects

---

api/base/filters.py
api/base/utils.py
api/registrations/serializers.py
website/static/js/myProjects.js

https://trello.com/c/CEn3YOYE/131-registrations-should-neither-have-a-create-component-button-nor-a-center-pane-error
https://trello.com/c/R2zneCEV/111-registrations-not-loading-top-level

[Fix] Registration errors on My Project

---

website/static/js/home-page/newAndNoteworthyPlugin.js

Prevents console errors with defensive coding for `contributorMapping` access

[Fix] Race condition on Dashboard

---

website/static/css/pages/meeting-landing-page.css
website/templates/public/pages/meeting_landing.mako

<h3>
Purpose
</h3>
Open new page in new tabs. Plus centering the logos.
<h3>
Changes
</h3>
Changes made to the meeting-landing-page.css to center the logos. Add vendor prefixes to support IE9+.

OSF-5265 Open new in new tabs and center logo (IE9+ compatible)

---

api/logs/serializers.py
website/static/js/logActionsList.json
website/static/js/logTextParser.js
website/static/js/myProjects.js
website/static/js/project-organizer.js

Fixes dashboard issues:
https://trello.com/c/o7dDOft2/140-logs-for-initiating-registration-instead-say-initiated-retraction-of-registration
https://trello.com/c/UZcW3zdd/137-logs-for-deleted-component-point-to-parent-project-instead
https://trello.com/c/tl0zBta4/98-nested-components-should-not-have-a-remove-from-collection-button
https://trello.com/c/ZTNOMIuQ/129-pressing-the-x-in-search-sets-the-current-list-to-all-my-projects-but-does-does-not-change-the-selection-in-the-left-pane

[Ready to Review] Dashboard fixes3

---

website/static/js/home-page/newAndNoteworthyPlugin.js

Dashboard Trello Issues:
https://trello.com/c/nxO32u0w/128-homepage-title-and-modified-sort-arrows-disappear-after-create-new-project-and-keep-working-here

[Ready to Review] Dashboard Fixes 4

---

website/static/js/logTextParser.js
website/static/js/myProjects.js

Fixing a couple of JS errors that occur when bad data is received from the api

---

website/static/js/addProjectPlugin.js
website/static/js/myProjects.js
website/templates/alert.mako

Fixes MyProjects issues:
https://trello.com/c/xQQ4WmER/152-dashboard-closing-welcome-banner-and-alerts-should-not-leave-white-space
Also makes a fix to templating.

[WIP] Dashboard/dashboard fixes 6

---

website/static/js/myProjects.js

Fix view issues related to contributor loading and project organizer not instantiating

[WIP] Fixes to dashboard 

---

website/files/models/figshare.py

- Fix broken figshare FAQ link.
- [OSF-5650](https://openscience.atlassian.net/browse/OSF-5650)

[feature] Figshare Publish FAQ Link

---

webpack.common.config.js
website/routes.py
website/static/css/dashboard.css
website/static/js/addProjectPlugin.js
website/static/js/home-page/quickProjectSearchPlugin.js
website/static/js/logTextParser.js
website/static/js/myProjects.js

QA issues in Dash: 
- Restores event tracking that has been mistakenly deleted as multiple people have been making edits to My Projects/Dashboard page.
- https://trello.com/c/spqIGAB4/158-issue-with-text-in-growl-box-when-navigating-to-bookmarks-other-collections
- https://trello.com/c/54E9pqat/138-deleting-component-produces-error-on-my-projects-page-when-clicking-the-parent-breaks-page
- https://trello.com/c/ENuMzTlQ/162-x-for-contributors-and-tags-filters-needs-to-be-standard-osf-x-and-to-have-a-pointer-cursor-upon-hover
- https://trello.com/c/WxWgHbqP/165-templates-should-specify-your-projects-so-user-knows-she-can-only-template-for-her-projects
- https://trello.com/c/bGjmek7h/99-display-private-components-consistently-between-the-my-projects-and-the-project-overview-page
- …

[Ready to Review] Dashboard/dashboard fixes 9

---

website/static/js/addProjectPlugin.js
website/static/js/myProjects.js

- Fix updating view when new projects and components are added
- Fix project list data passing to templates list for creating new projects

Refactor fixes

---

package.json
website/static/js/addProjectPlugin.js
website/static/js/myProjects.js
website/static/js/project-organizer.js

Fixes cards:
- https://trello.com/c/NlPAV21D
- https://trello.com/c/CNvNNNit
- https://trello.com/c/EGAifUQS
- https://trello.com/c/QKl3b3zk
- https://trello.com/c/RjPjh8wP

Batch fixes from Trello

---

api/collections/views.py
website/static/js/addProjectPlugin.js
website/static/js/myProjects.js

Fixing trello issues: 
- https://trello.com/c/NlPAV21D
- https://trello.com/c/g7RDuMno
- https://trello.com/c/oSCxkCNa

Another batch for 66

---

framework/transactions/handlers.py

Logging and returning correct error in case of transaction rollback failure

[RFR] Fix transaction rollback error overriding original exception.

---

website/static/js/myProjects.js
website/static/js/notificationsTreebeard.js
website/static/js/project-organizer.js
website/static/js/wikiSettingsTreebeard.js

Hopefully final PR before release

Fixes/0.66.0 Expandonload fix and date modified sorting feature 

---

website/static/js/myProjects.js
website/static/js/nodeSelectTreebeard.js
website/static/js/notificationsTreebeard.js
website/static/js/project-organizer.js
website/static/js/projectSettingsTreebeardBase.js
website/static/js/wikiSettingsTreebeard.js

Same fixes of this PR: with an additional change on nodeSelectTreebeard 
https://github.com/CenterForOpenScience/osf.io/pull/5347

Release/0.66.0 develop Fix expandonload 

---

website/static/js/myProjects.js

Fixes trello issue:
- https://trello.com/c/g7RDuMno
This  fixes add collection input, not yet the rename input

Remove input binding in mithril and refactor resetting add collection

---

website/static/js/nodesPrivacySettingsTreebeard.js

Code lost in: d08b649142834c3c3e3df873c86bfae761cb2f50
Fix JSHint/ Karma failure in CI- function is called, but code was lost in merge commit.

Fix JS tests- restore code lost during merge commit

---

website/static/css/pages/faq-page.css
website/static/js/addProjectPlugin.js
website/static/js/myProjects.js
website/static/js/project-organizer.js
website/templates/public/pages/faq.mako

This bug potentially breaks the entire page so we should review and push. 
Because the system did not have correct filterText value it failed in draws because the range of items to be shown did not update well. Only happens when you click on filters AFTER text filtering 
Trello card
- https://trello.com/c/8udeZ5Es

[Hotfix] Important bug with my projects with filter

---

website/project/views/contributor.py
website/static/js/contribRemover.js

cherry pick from #5368 against mater.
@saradbowman

[hotfix] fix multiple removals of self and redirect

---

admin/base/settings/defaults.py
api/base/settings/defaults.py
api/caching/tests/test_caching.py
tests/base.py
tests/factories.py

Move back to using Django's `Testcase` for admin app.

[Feature Fix] Fix failing admin tests

---

scripts/osfstorage/usage_audit.py
website/files/models/base.py

Speedup and reduce the memory consumption of the osfstorage usage audit script

[Hotfix] Osfstorage Usage audit

---

api/files/serializers.py

And now there will be file serialization through ESI

Add get_absolute_url method for FileSerializer

---

website/static/js/logTextParser.js
website/static/js/nodeControl.js
website/static/js/project-organizer.js
website/templates/project/project.mako

Fixes Trello bugs: 
- https://trello.com/c/3rIm6YU9
- https://trello.com/c/Z2wb9wEh
- https://trello.com/c/AysLF4Cn

[hotfix] dashboard hotfixes

---

website/static/css/pages/dashboard-page.css

Fixes Trello issue:
https://trello.com/c/xQQ4WmER

[hotfix] Add alert container class to dashboard page as well

---

scripts/indices.py
website/conferences/views.py
website/project/model.py

The in query will speed it up a little. There has to be a way to stop looping over all the conferences but I haven't been able to figure it out so far.

[feature] speedup conferences submission view

---

website/static/js/myProjects.js

Fixes Trello card: 
https://trello.com/c/92kut17O

[Hotfix] Fix filters not updating when closing from breadcrumbs

---

PULL_REQUEST_TEMPLATE.md

Adds a PR template to enforce consistency in PR descriptions.

Add PULL_REQUEST_TEMPLATE

---

package.json
webpack.common.config.js
website/static/js/home-page/newAndNoteworthyPlugin.js
website/static/js/myProjects.js

Getting 'TypeError Cannot read property 'contributors' of undefined'.  API not returning contributor information.
Also handles when user makes project stored in Discover Public Projects private.
Use lodash.get for dashboard null checking

[Ready to Review] hotfix/myprojects-null-checking

---

api/base/views.py
api/base/wsgi.py

Monkey patch out cached properties

---

website/static/js/registrationEditorExtensions.js
website/static/js/registrationUtils.js
website/static/js/tests/registrationUtils.test.js
website/templates/project/registration_editor_extensions.mako

Refs: https://openscience.atlassian.net/browse/OSF-5586
Allow users of the prereg form to add more than one file to an answer
In the form:
In the preview:

[RfM] Add ability to attach multiple files to the preregistration form [OSF-5586]

---

website/templates/project/settings.mako
website/templates/public/pages/faq.mako

- Removes remaining occurrences of retract/retraction discovered while testing [OSF-5542](https://openscience.atlassian.net/browse/OSF-5542)

[feature fix] Remaining Retraction Language

---

scripts/populate_conferences.py

Add L. Starling Reid UVA 2016 conference

---

framework/postcommit_tasks/handlers.py

This removes gevent from the situation when ENABLE_VARNISH is False.
I added an extra clause to an existing if block and moved an import from module level to local.
n/a

Pull all gevent action into ENABLE_VARNISH check

---

scripts/send_queued_mails.py
website/mails/queued_mails.py

improvements to QueuedMails
Add more dry-run info, and add __repr__ to QueuedMails
https://openscience.atlassian.net/browse/OSF-6088

Add more dry-run info, and add __repr__ to QueuedMails

---

website/addons/dataverse/static/dataverseNodeConfig.js

Improve display of special characters in dataverse string.
See JIRA ticket for testing notes.
https://openscience.atlassian.net/browse/OSF-6086

[hotfix] Improve display of dataset titles for dataverse [#OSF-6086]

---

scripts/get_duplicate_account.py
tests/test_conferences.py
website/conferences/message.py

Fix the conference service accept upper case email address. And write script to find out duplicate emails account in database.
https://openscience.atlassian.net/browse/OSF-5940

[#OSF-5940]. Repeated Sign Up Creates Multiple Inactive Accounts

---

website/templates/institution.mako

https://openscience.atlassian.net/browse/OSF-6114

use maxes over img-responsive
