CenterForOpenScience/osf.io

- scripts/sync_email.py
- tests/test_mailchimp.py
- tests/test_views.py
- website/mailchimp_utils.py
Adds a user's first and last name when subscribing them to a mailchimp list, so that it is included in their mailchimp profile.
> Hotfix: Add user's first and last name when subscribing to mailchimp

- tests/test_views.py
- website/profile/views.py
Since we enabled unsubscribe confirmations and the email gives users the option to re-subscribe to the mailing list, the OSF needs to catch these subscribe events and update user records in our database.
> Hotifx: Catch 'subscribe' events sent via mailchimp webhooks

- website/static/js/onboarder.js
Purpose
-----------
Make the dropzone on the onboarder page properly upload files.
Changes
------------
Uses the patched dropzone instead of the regular dropzone.
Side Effects
Shouldn't be any, though I can't really test this, because I don't have local osfstorage working. However, the change does cause it to use the proper REST verb (post, not put), and the new error is consistent with what I would expect, so it probably works. Still, you'll want to try it first, obviously.
Fixes (hopefully) https://trello.com/c/F6TuUnRd
> 0.23.0/onboarder dropzone

- website/static/js/osfHelpers.js
Purpose
-----------
Make knockout tooltips work again.
Changes
------------
The custom binding handler for tooltips was in site.js but didn't make it over to osfHelpers.js. This is corrected.
Side effects
Should be side-effect free.
Fixes https://trello.com/c/GKeUl5eH
> 0.23.0/knockout tooltip binding

- website/static/js/search.js
- website/templates/search.mako
Force the knockout value to update in IE when using enter to submit a search, fixes https://github.com/CenterForOpenScience/osf.io/issues/1448
IE doesn't update the value of the search field unless the focus is lost
Blur and then focus the field before submitting the search
I don't have access to an IE browser to test this but running the commands in saucelab's VM seemed to work.
> Hotfix IE search when submitting via enter

- scripts/populate_conferences.py
Add SPSP conference and disable old conferences.
See above
None expected
@sloria: The requested admin user for SPSP2015 didn't exist on production as of this morning, so @KatyCain526 did/will talk to her/him and confirm when the account exists. At that point, we can run `populate_conferences`.
Resolves #1444
Resolves #1456
> hotfix: Add SPSP 2015; disable old conferences.

- website/templates/profile/notifications.mako
Change description of OSF general mailing list in user settings to make it more informative: 
Discussed with @AndrewSallans and @KatyCain526. @JeffSpies do you have any suggestions on this language?
> Hotfix: Edit mailing list description

- website/project/views/register.py
- website/templates/metadata/register_1.mako
Fixes issue where data was not unserializing in the template for OSF Standard Pre-Data Collection Registration.
Make `window.contextVars.regPayload` a JSON object instead of leaving it as a string so that `MetaData.ViewModel.unserialize` does not throw an error.
> CommonJS-fix: Store registration template payload as JS object on contextVars

- website/static/js/nodeControl.js
- website/templates/project/project_header.mako
Adds a line for "Registration Date", per #1342.
Add placeholder text ("No description") for projects without descriptions, styled to align with how it appears for contributors.
> [feature] Minor changes to page header for registration

- scripts/populate_conferences.py
Changing it because the url does not lead to the correct place. We want the explanatory information to show up on the conference page.
> Remove conference homepages

- scripts/populate_conferences.py
Removing the URL should allow for the explanation to be displayed on the presentation service page.
> Removed the URL for the MPA2015 conference

- webpack.config.js
- website/static/js/notifications-config-page.js
- website/static/js/notificationsConfig.js
- website/templates/profile/notifications.mako
- Require dependencies in `notificationsConfig.js` and add a webpack entry point for the module
- Initialize `NotificationsViewModel` in separate init
file instead of in `notifications.mako`
> Make mailchimp settings page CommonJS compatible

- website/static/js/search.js
- website/templates/search.mako
Properly reference the main search bar
Previous was attempting to refernce by name but using the id selector
Now the searchbar has a longer/more unqiue id, not name.
> [Hotfix] IE Search bar (again) (should work this time)

- website/static/css/site.css
- website/static/js/pages/profile-page.js
- website/static/js/profile.js
- website/templates/include/profile/social.mako
- website/templates/profile.mako
Purpose
-----------
Force a user to go to user settings page in order to update a profile
Changes
------------
Users who change their name on their user profile page do not see that there is an additional step of updating the name parts, and this has caused confusion on multiple occasions such as when Lyndsy was demoing the citation modifications and didn't realize that the name needed changing in multiple ways. This eliminates the ability for a user to make profile modifications on the profile page, and instead takes them to the settings page for such changes.  I had to make some changes to the knockout which wasn't really expecting to have a situation where you would have a view-only version of the page even if the user had the capability to edit their own info. It was almost there, but …
> 0.23.0/no-editing-on-profile-page

- website/templates/profile.mako
Purpose
-----------
On the gravatar page, if you click on the gravatar, after dismissing the dialog box, you would get a highlight around the gravatar and a little more on the side (looks like a briefcase).
Change
----------
Remove the whitespace between the a tag and the img tag, thus removing the briefcase highlight
Side effects
The code doesn't look as pretty, but nothing functional.
Fixes one of the issues in https://trello.com/c/7DbaUxsZ/37-various-tooltips-broken
> Remove small highlight after clicking gravatar

- website/static/css/site.css
- website/templates/profile.mako
Purpose
-----------
On the gravatar page, if you click on the gravatar, after dismissing the dialog box, you would get a highlight around the gravatar and a little more on the side (looks like a briefcase).
Change
----------
Move the padding for the gravatar into a containing span rather than on the anchor element.
Side effects
None that I can think of. It still has a highlight, but not an oddly shaped highlight.
Fixes one of the issues in https://trello.com/c/7DbaUxsZ/37-various-tooltips-broken - hopefully properly this time.
> 0.23.0/remove briefcase highlight on profile gravatar

- website/static/js/profile.js
I stumbled upon this myself but realized it was already raised in #1470.
This one line fix corrects wrong base URL for researcher ID (it was lacking the "/rid/" suffix).
Otherwise, this line in malformed links from the social tab of the user's profile page.
I'm not sure of your policy for hotfixing bugs in production. I'm targeting the master branch now (because that's what I branched off) but am happy to redirect to whatever you like if the pull request looks good to the dev team.
> Add suffix to researcherID base URL object

- tests/test_conferences.py
- website/conferences/views.py
Ensure absolute URLs in conference emails; add regression tests.
> Use absolute URLs in conference emails.

- website/conferences/views.py
Fix bug reported by @KatyCain526: no download link or count is displayed in the conference table for nodes whose first file has been deleted. This patch shows the first non-deleted file in the conference table.
* Show the first non-deleted file rather than the first file
None expected
> Show first non-deleted file in conference table.

- tests/base.py
- tests/exceptions.py
- website/addons/dataverse/tests/test_views.py
- website/addons/github/tests/webtest_tests.py
Purpose
======
See https://github.com/CenterForOpenScience/osf.io/issues/1363
Changes
=======
Use "mock" library to patch the sending of http requests. Requests that would be sent now generate the exception "UnmockedError"
Side Effects
==========
Previously passing, improperly mocked tests now fail.
> Fail tests mocking incorrectly

- tests/test_conferences.py
- website/conferences/views.py
- website/mails.py
- website/templates/emails/conference_inactive.txt.mako
Send warning email on conference submissions to inactive endpoints. Adds feature requested in https://trello.com/c/iyTo3Ndo/15-presentation-service-new-osf-user.
* Add email template for warning message
* Send warning email on submission to inactive conference
None expected
> Send warning on submission to inactive conference.

- website/templates/public/pages/meeting_plain.mako
Fix 500 on plain conference view page reported by @KatyCain526 (e.g. https://osf.io/view/spsp2014/plain)
* Include assets from `base.mako` in plain conference view
None expected
@sloria `meeting_plain.mako` doesn't inherit from `base.mako`, so some assets are included manually for now, which is pretty brittle. Can you think of a better way to handle this?
> Add base scripts to plain conference view.

- website/static/js/projectorganizer.js
Purpose
-----------
Make the icons for registered projects and components show properly
Changes
------------
Previously, the code checking the type of icon it should use was exiting out before checking if it was a registration. This fixes that
Side effects
There should be no side effects
Fixes https://trello.com/c/UjHCsl52
> 0.24.0/make-registration-icons-grey

- website/templates/projectGridTemplates.html
A previosu fix broke the view for the template on what dashboard is showing. Trello issue: https://trello.com/c/KmV63Bo0
The template includes now a section only for dashboard that has Add Existing Project and Add Folder buttons. 
The logic added checks for whether the item is dashboard. If any it would have side effects on the dashboard toolbar displays.
> Fix dashboard row selection icons not working

- website/static/js/projectorganizer.js
Based on code review, to put the instantiation of templates at the top so they happen once. 
There are now global variables for the templates which get built once 
Since the templates get fed with data with handlebars there shouldn't be any side effects.
> Optimize templates used in project organizer to load once

- website/static/js/folderPicker.js
Fixes figshare view not updating on first load.
Trello card: https://trello.com/c/ul6PFxw1 
Added a utility hook to Treebeard for ondataload; when all data load and flattening is done.
Added rowHeight value to folderPicker which resolved the view height problem (it turns out this was the main issue) 
Do ```bower treebeard update``` to update treebeard
Should not be any since rowHeight is used in all TB instances and the hook is still optional.
> Fix figshare load

- website/static/css/site.css
Purpose
-----------
Keep firefox from cutting off most of the search bar text
Change
-----------
Remove 15px of padding from the search bar
Side effects
No readily apparent side effects
Fixes https://trello.com/c/pdDUUtrN
> Fix firefox search text

- website/static/css/projectorganizer.css
Fixes the problem of typeahead padding. Refer to this Trello card: https://trello.com/c/PGUBPXzB
CSS Adjustments that give proper padding to the elements involved.
I tested in Safar, Chrome and Firefox, and check if any other typeahead element on the page has problems. Also fixed one other typehead use on dashboard on onboarder, which is a desired fix.
> Fix Firefox padding on typeahead

- website/static/js/projectorganizer.js
An earlier fix introduced a bug where some items would load twice, doubling their content. This fix makes sure the appropriate logic is used in Project organizer.
Trello card: https://trello.com/c/O22fwTxe
The logic for when updateFolder runs was changed. 
There might be a very edge scenario where this update may break things but we tested with all scenarios that users may need in this page. 
Thanks to @brianjgeiger for his help on this.
> Fix Project organizer bug where some items would load contents twice

- website/addons/figshare/messages.py
Purpose
-----------
Ensure concatenated messages are properly spaced. Found by Jeff and/or Caner.
Changes
-----------
Figshare messages are sometimes concatenated. One of these was found with no period or space after it. I added a period and/or space to all the messages to make sure they can be concatenated in any order.
Side effects
Someone could be relying on bad formatting somewhere. It won't be worse than what we have now as a problem, and if it is reported, then this will be closer to a proper fix than what would be there.
> 0.24.0/Figshare-message-concatenation

- website/addons/dataverse/templates/dataverse_view_file.mako
Resolve #1475 by removing delete button from Dataverse file view page.
While it is currently possible to determine if a file is a draft version (editable/deletable) through a series of API calls, I do not believe it is worth the additional time required to perform those actions to conditionally add a delete button to the file page. This may change with Dataverse 4.0, and is worth re-evaluating at that point.
Draft files remain deletable from the "Files" page.
> Remove delete button from Dataverse file view page.

- website/static/css/projectorganizer.css
Fixes Trello issue: https://trello.com/c/ftClJtwf 
Where Firefox input padding for adding a new folder was restricting text height. 
The padding style was adjusted for the effected input
This was a general change for '.typeahead' class scoped within places that load projectorganizer.css. I checked that
- It didn't have adverse effects on other inputs in this page related to typeahead
- it didn't break chrome and safari views
> Fix add folder padding issue in Firefox

- website/routes.py
- website/static/js/waterbutler.js
- website/templates/project/project_base.mako
Allows waterbutler.js to use global context cookieName from website/settings, fixes IE9 subdomain issue.
local.py on staging will need to be updated to COOKIE_NAME = 'osf_staging'
> [Feature] cookieName made available to javascript for waterbutler integration

- website/static/js/fangorn.js
When a file was uploaded that already existed in the folder the view showed both. With this update the most recent one (just uploaded) will remain, other copies will be removed from view. 
Trello card: https://trello.com/c/R7htu5Em
Add a check to see if duplicates exist by name (which are not the currently uploaded item itself)
Unless there is a corruption in the data structure this should not have side effect. The current behavior will remove ALL duplicates by name, but name has to be exactly the same.
> Remove duplicates if same file is uploaded

- website/addons/dataverse/templates/dataverse_view_file.mako
- website/addons/dropbox/templates/dropbox_view_file.mako
- website/addons/figshare/templates/figshare_view_file.mako
- website/addons/github/templates/github_view_file.mako
- website/addons/s3/templates/s3_view_file.mako
Purpose
-----------
Make the file detail pages for all CRUD addons look correct and without a space above the delete/file revisions section.
Changes
------------
Removed the unused warning div that had already been replaced with growlbox functionality
Side effects
Shouldn't be any. Best to test both that the file detail page looks right for all addons and that the delete growlbox appears.
Fixes https://trello.com/c/kKF42Gz0
> 0.24.0/space above revisions

- website/addons/dropbox/model.py
- website/addons/dropbox/tests/test_utils.py
- website/addons/dropbox/utils.py
Otherwise, get_addon will return `None`, which leads to the
AttributeError that caused #1557.
[fix #1557]
> [hotfix] DropboxNodeLogger must account for deleted node settings records

- website/static/js/projectorganizer.js
Remove sorting toggle buttons from project organizer title column to bring it to same functionality as production
In TBoptions for project organizer remove the option to sort from titles column
None, this is limited to one location.
> Remove title sorting on project organizer

- tests/framework_tests/test_sentry.py
- tests/test_mailchimp.py
- website/mailchimp_utils.py
Mailchimp validates emails before subscribing to a mailing list, but the OSF does not. As a result, if a user registers with a fake-looking email their account confirmation will fail. 
Catch `mailchimp.ValidationError`
> Hotfix: catch mailchimp validation error

- GUIDELINES.md
Purpose
------------
Add the Guidelines for Contributing that @samanehsan and I made a long time ago to the OSF repo
Changes
------------
There's a new markdown file with the guidelines
Side effects
There'll be a new notice at the top of the repo for how to report issues. One day it may also explain the best way to submit code.
> Create guidelines for contributing, especially issue reports

- website/addons/figshare/static/figshareFangornConfig.js
A previous fix for tooltips deleted the figshare buttons based on the misunderstanding that they were the same as the fangorn code, but they have checks that are unique to figshare so they need to be replaced and have the proper tooltips applied.
Fixes this Trello card: https://trello.com/c/H69pGl31
Previous version of the figshareFangonConfig file was restored with changes that added tooltips to the buttons. 
Should not be any, this was existing working code and the logic applies here.
> Repair removed figshare checks for action buttons

- website/addons/osfstorage/tests/test_utils.py
- website/addons/osfstorage/tests/test_views.py
- website/addons/osfstorage/utils.py
- website/addons/osfstorage/views.py
Fixes https://trello.com/c/QqViXlNJ/228-unable-to-download-previous-versions-of-files.
> Fix view and render by version.

- website/addons/osfstorage/requirements.txt
- website/addons/osfstorage/tests/test_utils.py
- website/addons/osfstorage/tests/test_views.py
- website/addons/osfstorage/utils.py
Fixes https://trello.com/c/O0ECROCL/215-delete-fail-when-trying-to-delete-rtf-file-with-non-ascii-character-in-title.
Osfstorage was escaping file names when returning metadata but as we use mithril this is no longer an issue.
> Remove markup escaping from osfstorage

- website/static/js/fangorn.js
In files and project overview pages: 
Sort contents of a folder in alphabetical order at load time and maintain order after file uploads are completed. 
Trello card: https://trello.com/c/lldWFdTv
Added a new function to sort folders which may be called from anywhere that has access to item and treebeard. 
Added this function to run after lazyload and when uploads are completed. 
The redrawing of the rows while some notifications are still up could cause issues but it shouldn't because they use id numbers which will be stable.
> Sort folders after depth 1 on load and after file upload.

- website/static/css/projectorganizer.css
- website/templates/projectGridTemplates.html
Properly align the layouts of several views on the toolbar so that they fit the content and fit well as page is resized
Fixes Trello card: https://trello.com/c/19Ylw8Z3
Generally view related changes to existing div. Did not move divs around or change logic for view or hide. 
Should not be any since programming logic was not touched. Was tested in Safari, Firefox and Chrome
> Fix project organizer toolbar layouts

- website/addons/dataverse/templates/dataverse_widget.mako
- website/templates/project/addon/config_error.mako
Fixes the dataverse widget on the project organizer page. Discussed in this Trello card: https://trello.com/c/SKz0Otpi
- Added the widget mako generic template to the top to apply to dataverse
- Removed unnecessary h3 header 
- Added padding around error message
Specific to dataverse and does not seem to have any other side effects. Check in Chrome, Firefox, Safari
> Fix dataverse widget on project dashboard

- website/static/css/site.css
- website/templates/project/addon/view_file.mako
Adds breaking word when file name is too long on file view page. 
Trello card: https://trello.com/c/TUJXjBdb
Added the break work style to the header
CSS scope might be an issue if the exact class name 'break-word' is being used elsewhere. I did an OSF wide search, did not find it defined anywhere else.
> Break long file names on file view

- website/static/js/projectorganizer.js
Smartfolders in Project organizer should not accept any drops 
Fixes trello card: https://trello.com/c/QTlitNLR
Add the check for whether a drop target is smartfolder to droplogic
Since only smartfolders are going to be affected by this change it should not have any side effects.
> Fix project organizer items dropping to smart folders and causing growl

- website/addons/dataverse/static/dataverseFangornConfig.js
Thanks @caneruguz for pointing out the solution.
Fixes https://trello.com/c/yIvXdUlt/260-dataverse-no-delete-confirmation-modal again.
> Fix button handlers in Firefox and Safari.

- website/addons/figshare/static/figshareFangornConfig.js
Adds permissions check to show/hide delete button when user is logged out. 
Trello card: https://trello.com/c/H69pGl31
figshare fangorn Checks if user has edit permissions when deciding to show delete button
None.
> Fix figshare action buttons checking for permissions to show delete

- website/static/css/site.css
Fixes the overlap issues with XS size navigation and search bar, addressing scenarios for search page and other pages. 
Addresses Trello issue: https://trello.com/c/klj8mGMC
Added xs size specific css classes to address the issue of overlapping divs and location
These are all improvements, I don't think any regression will come out of this but location on window in more scenarios could show need for further improvements. Tested in IE11, Chrome, Firefox, Safari.
> Fixes the search bar appearance in XS views with different scenarios

- website/static/js/projectorganizer.js
Fixes this Trello card: https://trello.com/c/pe7OS5Ty; where starting drag clears multiselect hover class so the user doesn't know they are still selected. 
Remove code that removes multiselect hover class
None. Tested in Chrome, Safari, Firefox, IE 11
> Fixes multiselect hover class clearing when drag starts in PO

- website/static/js/projectorganizer.js
For clarity and continuity the smart folders that are selected show their name instead of placeholder text.
Pass the name of smart folder as message and add No Actions to the toolbar
None.
> Add the smart folder name to the toolbar when selected

- website/static/js/projectorganizer.js
Fixes the problem where multiselect original row was reset during shift selects. Originalrow is important for selecting multiple rows using shift key. 
Trello card:  https://trello.com/c/kWRti0nr
Projectorganizer.js was using treebeard.selected for the purpose of originalrow which is a problem because selected gets updated on every click on the row. Returned that value to be the first item in multiselect. 
This only runs if multiselect has more than 1 item so there will always be a multiselected[0] in this scenario. Should not have any side effects.
> Fix resetting of original row for multiselect

- website/static/js/fangorn.js
Long filenames need to break in the modal for deleting files.
Added break class to the title
Added only to the header and the only css added applies to breaking the word so no side effects. Tested in Chrome, Safari, Firefox. this css property is compatible down to IE 5.5
> Break long file name titles in the delete modal in files page

- framework/analytics/tasks.py
- framework/tasks/handlers.py
- tests/test_mailchimp.py
- website/mailchimp_utils.py
Fixes race condition on user confirmation in which Celery task can overwrite a user record with stale data.
* Add general `queued_task` decorator for Celery tasks to be used in a request context
* Wrap Mailchimp tasks with `queued_task`
* Fix tests
None expected
> hotfix/Fire Mailchimp Celery tasks after request.

- website/static/css/projectorganizer.css
Project organizer icons show lines around them when viewed in certain window widths. This is because the icon is on default background image wrapping. This hotfix fixes this issue. 
Add "background-repeat: no-repeat;" to all project organizer icons
There is no scenario where we want these icons to repeat so there is no side effect.
> [Hotfix] Fix Project organizer icon images repeating in certain views

- website/templates/log_list.mako
- website/templates/project/project.mako
Hide potentially misleading placeholders (e.g. "A user could not render log") while project log list is loading
* Pass `scripted` argument to `log_list.mako`
* Use `%page` tag to read `scripted` argument
None expected
> Correctly apply "scripted" class to log list.

- bower.json
Fixes the issue #1661 . Scrolling by dragging the scrollbar with mouse should not cause jitters
Replaces the commit sha reference for treebeard in bower.json so the treebeard changes can be installed. 
Does not effect scrolling otherwise. Tested in Chrome, Safari, Firefox and IE 11.  Safari has still a tiny jitter but that should not hold up the fix.
> Fix jittering in Treebeard with on scroll

- website/static/css/site.css
Fixes #1696 temporarily until bootstrap fixes come later. 
Added fixed positioning to modal-backdrop
Should not be any, but we need to revisit if Bootstrap updates happen. Tested with Firefox, Chrome, Safari and IE 10 in Win 7.
> [Hotfix] #1696 add links modal

- bower.json
- website/static/js/fangorn.js
Fixes #1598 and uses the new treebeard option to add depth to sorting. 
Major changes are in Treebeard. **needs a treebeard update** new commit SHA is in the bower.json file. Adds sorting depth level so folders below that level (parents) will not be sorted.
Default sort level is 0, so if it's not defined it will not harm the behavior of other sort instances. This treebeard update will bring the production to this commit including previous commits. No foreseable effect though.
> [Hotfix] Fixes #1598 Sorting depth not to include major folders in files page

- website/templates/log_list.mako
Fixes issue #1676 
Adds css class to break words
Shouldn't be any, I can't imagine a scenario where the word break should not be requested. Tested in IE 10 in Win 7 so future versions of IE should work, also tested in Chrome, Safari and Firefox for regression.
> [Hotfix] Fix long file names not breaking in Activity log dashboard page

- website/addons/wiki/templates/toc.mako
Fixes #1698 .
Changes the link icon to what project main page is using
None
> [Hotfix] #1698 Change the link icon in Wiki page

- website/templates/nav.mako
Fixes #1649 and other issues caused by long OSF name in navigation bar. 
Use the short version of OSF in all widths smaller than large
None.
> Use short version of OSF in navigation for mobile devices

- website/templates/projectGridTemplates.html
Fixes #1682 , and allows the project name to be wider and use more of the available space
- The condition where an item is next to only Remove from folder button was added so that their column placement can be individually adjusted
- Further minor changes were made to improve the responsiveness 
- The conditions for cases can potentially be touching undesired cases but I ran through some tests to make sure all file/folder combinations show the appropriate content and width. 
- Tested in Chrome, Firefox, Safari and IE 10 in Win 7
> Fix 1682, project name column uses more of the available width

- website/static/js/projectorganizer.js
Fixes #1679 and the other two cases where the inputs didn't get immediate focus and needed one more click. 
Adds the focus trigger to inputs when they become visible
None. Only applies to the inputs that are relevant and trigger focus does not leave any permanent UI changes.
> [Hotfix] #1679 - Add focus to project organizer input elements when pertinent

- .gitignore
- website/addons/osfstorage/settings/defaults.py
- website/addons/osfstorage/tests/test_views.py
- website/addons/osfstorage/utils.py
- website/addons/osfstorage/views.py
Purpose
====
Allow non-signed url's to be downloaded and rendered from osfstorage.
FileSystemProvider is now the default for WaterButler/OSF, this will allow for easier system setup on development machines.
Changes
===
When calling osfstorage's download_file check for a 301 or 302 status, if found send back the redirect location (current behavior), otherwise send the full request contents directly to the renderer or client browser.
Side effects
===
None
> [feature] osfstorage support for direct provider downloads and default to filesytemprovider

- website/addons/dropbox/tests/test_utils.py
- website/addons/dropbox/utils.py
**Problem**
If a user linked his dropbox ROOT folder to a project, his collaborators on this project could not view the dropbox files in the project. Instead, when the collaborators click the file to view details, they get "Forbidden" instead.
**Cause**
The function <code>is_subdir</code> is not handling the case where the parent directory to check is the root directory.
**Side effect**
To be added
> [hotfix] Fixes bug in method that checks dropbox subdirectory

- website/templates/project/modal_add_component.mako
Notify users of upcoming permissions change: project admins will automatically be granted read-only access to all child nodes (see #1725).
* Include message about behavior change in create component modal
* Clean up whitespace in modal ಠ_ಠ
None expected
Note: This message should be deleted after #1725 is merged.
@bnosek: Changes to language welcome. The notice currently reads: "Note: Beginning on 2014/02/20, project administrators will automatically be granted read-only access to all child components."
> Add warning about upcoming permissions change on create component.

- framework/auth/core.py
- scripts/admin_permission_email.py
- website/mails.py
- website/templates/emails/security_permissions_change.txt.mako
Add script to email users about upcoming change in admin permissions
* Add script
* Add `security_messages` field to `User` to track sent messages
* Add miscellaneous change to email utils
None expected
To test: `py.test scripts/admin_permission_email.py`
To dry run: `python -m scripts.admin_permission_email dry`
To run: `python -m scripts.admin_permission_email`
@JeffSpies: Which address should the message be sent from?
> Add script to email users about permission change.

- website/addons/base/views.py
- website/addons/osfstorage/tests/test_utils.py
- website/addons/osfstorage/utils.py
- website/static/js/waterbutler.js
Purpose:
Corrects view only link file downloads not working.
Resolves #1748
Cause:
View Only file links are not downloading.
Side Effects:
None
> [hotfix] fix for file render page download via view_only link

- website/static/js/folderPicker.js
@icereval Pointed out a bug where if folderpicker item has enough items to require scrolling and the user selects another folder, the selected folder select goes unchecked with mithril refresh. This is because mithril is redrawing based on its state. This change fixes this bug so that if the user selects another folder the view is consistent despite scrolling. 
Added a temporary item to treebeard option to show which item is selected and cleaned up the function. 
Should not break anything else, this also doesn't affect any saved state.
> [Hotfix] Fix select related bug in folderpicker

- website/addons/wiki/static/ace-markdown-snippets.js
Purpose
---
Adds a new line before snippet code where the snippet is required to start at the beginning of a line for proper formatting.
Cause
---
Selecting snippets like `blockquote` while in the middle of typing a sentence did not move to a separate line and would not render.
Side effects
---
None
> [feature] ace snippets inline formatting

- website/templates/project/modal_generate_private_link.mako
resolve #1413
<b><big>Purpose</big></b>
Clarify the warning message that user will see when they try to create a view-only link
<b><big>Changes</big></b>
The old warning message is 
Now it is changed to
<b><big>Side effects</big></b>
This change only add "wiki pages" into the warning message, but actually all user-created content may have a chance to contain identify information, for example, addons.
> clarify the warning info for view-only link

- framework/auth/core.py
- tests/test_models.py
- tests/test_views.py
<h5>Purpose</h5>
Knockout validation is used to check that the input for the year field is a four-digit integer, but this check is not done on the backend. 
<h5>Changes</h5>
Add this validation to `validate_history_item()`
> Add backend validation for years entered for profile jobs/schools

- website/static/css/fangorn.css
- website/static/js/fangorn.js
Fixes error reported in flowdock where when uploading a file with a long name in project overview page the file name wraps to other rows. 
Truncated the file name in project overview upload notification and added nowrap style so there is no wrapping in any case. 
This doesn't change the behavior in other upload situations or treebeard instances. Should not have any side effects.
> Fix issue where long filenames wrapping in project overview

- website/templates/project/addon/view_file.mako
Temporarily fixes #645 . By temporary I mean it is not a system wide solution to highlighting active fields but for this purpose it works well and is reliable. I suggest we use this until a much bigger change. 
Adds to view_file.mako some js that adds the active lcass to Files tab in Project Menu
None. Limited to view_file.mako file.
> Add active class to Files when individual file is viewed

- website/addons/wiki/shareServer.js
Properly set the sharejs server's debug environment flag.
> [hotfix] sharejs debug environment

- tests/test_auth.py
- tests/test_contributors_views.py
- tests/test_models.py
- tests/test_rubeus.py
- tests/test_views.py
- website/profile/utils.py
- website/project/decorators.py
- website/project/model.py
- website/project/views/node.py
- website/project/views/register.py
- website/static/js/contribManager.js
- website/static/js/pages/sharing-page.js
- website/static/js/project.js
- website/templates/project/contributors.mako
- website/templates/util/render_node.mako
Ensure that project administrators have at least read-only access on all child projects and components; allow administrators to register private child nodes on which they are not a contributor.
* Add `Node#is_admin_parent` method
* Change `Node#has_permission` such that parent admins always have at least `read` permission
* Add `Node#admin_contributors` property to get parent admins who aren't also contributors
* Update contributors table
* Allow admins to register all project children, even if not contributors
None expected
Resolves #438
> [hold] Feature/admin views

- website/static/js/pages/base-page.js
Stop footerSlideIn from showing up on pages where it doesn't need to be.
It won't show up on the landing page or forgotpassword page.
Users won't be annoyed by redundant messages.
Closes-issue: #1844
> [hotfix] footerSlideIn shouldn't show up on these pages

- website/search/share_search.py
Should fix source related graph rendering errors (for example, when you search ["source:pubmed OR source:figshare"](https://osf.io/share/?q=source:figshare%20OR%20source:pubmed))
Should not have any side effects.
> Fix error in graph caused by inconsistent data lengths for various providers

- website/static/js/conference.js
- website/templates/public/pages/meeting_plain.mako
Fix errors reported in email by Jeff and Brian on the plain version of the presentations mako page. 
- Change column widths so that in the narrow version that their iframe uses; the downloads column has more space
- Remove the extra "}" 
- Remove the extra search bar
- Change image being used to width:100% so that the image always fits the screen on different sizes. 
The changes should not bring any side effects. 
Someone should double check this section though, it's supposed to add a special link if the meeting is actve and there is a info_url. In this case (SPSP 2015), meeting[active] is True, meeting['info_url'] is None. Is the data or the logic here correct? There is no reason to assume it's not but good to double check. 
```mako
% if meeting['active'] and meeting['info_url']: …
```
> [Hotfix] Fix meetings plain page to match meetings.mako

- website/addons/googledrive/views/auth.py
Handle authorization requests instantiated by the user for the Google Drive addon that are cancelled before completion
Users are redirected to either their user settings page (if they were requesting access there) or to the project settings page (if they were request access there).
None
Closes-issue: https://trello.com/c/Owg4dARP/81-denying-access-via-google-yields-json-error
> [Fix] Google Drive oauth cancellation errors weren't handled

- website/addons/figshare/README.md
Add straightforward docs for developers needing to setup FigShare addon and/or access to the FigShare API for local development
None
Saved time for future developers
> [feature] Developer docs were missing

- website/static/js/pages/base-page.js
- website/templates/index.mako
The signup page has placeholders that do not work in MSIE 9 or less. The PR uses navigator.userAgent to see which browser the page is open on and if it claims to be MSIE 9, 8, 7, or 6 for good measure.
closes: #1703 and #1483
Ugly UI for IE9 or worse, UX much improved. 
Suggest using modernizr for future feature detects rather than browser detecting which is often spoofed.
> Browser check and labels, closes #1703 and closes #1483

- tests/test_elastic.py
- website/search/elastic_search.py
<b>Purpose</b>
Fix the problem that the ampersand is still being rendered as html in search results in some instances but not others (appears to be for component search results, but not project results in this case)
<b>Changes</b>
Now the ampersand is displayed as "&" in search results.
resolves 
https://github.com/CenterForOpenScience/osf.io/issues/1832
> fix the apmersand being rendered as html in search results

- website/static/css/citations_widget.css
Disable pointer-style mouse when inappropriate in citations widget
Overrides some Treebeard imposed styles for descendants of .citations-widget
None -- we may consider applying this to aspects of the files widget as well.
> Overrides some Treebeard style to disable pointer-style cursor

- website/addons/mendeley/model.py
Dramatically reduces API calls to Mendeley. In particular before we had to make 1 request per citation in a folder. Now we make only 2 requests.
Before me made an API call to fetch a list of citation ids. Citation attributes were then lazily evaluated (part of the mendeley-python-sdk), which required an API call. 
Now me make 2 requests: One to get the list of citation ids for a folder, and one to fetch the metadata for all of a user's citations. These results are filtered by the list of ids.
none
> Change implementation for fetching citations for Mendeley folder

- website/addons/wiki/static/WikiEditor.js
Changes
-------
- This corrects a miscommunication that results from the new "connected" display. Users on incompatible browsers will no longer go from "Connected" to "Unsupported".
- Status messages will only be throttled when attempting to reconnect.
> Improve sharejs status bar to correct default, update when relevant

- website/addons/figshare/tests/test_views.py
- website/addons/figshare/views/auth.py
Ensure redirects for user OAuth requests that are cancelled are handled correctly
Cancelled requests from a user's settings page will redirect to their /settings/addons/ and cancelled requests from a projects settings page will be redirected to the project's /settings/ page
None
Closes-Issue: #1844
>   [hotfix] FigShare OAuth canellations redirected incorrectly

- website/static/css/citations_widget.css
Prevent rows from turing red
Overrides Treebeard .tb-multiselect background color for descendants of .citation-widget
None
> Override more Treebeard styles in citations widget

- website/static/js/folderPicker.js
Fixes an issue with folderpicker where toggled folder that was out of view had it's toggle removed. 
Ties the toggle state to a property that is available in all possible folderpicker clients (dropbox, mendeley etc.)
Should not be any, only affects display, not any save related functionality.
> Change tempicked variable to id

- package.json
- website/addons/wiki/shareServer.js
- website/addons/wiki/static/ShareJSDoc.js
- website/addons/wiki/utils.py
Purpose
---
- Fixes issue where contributors viewing the edit page, when write permission was revoked, would be redirected to a Forbidden page rather than a read-only version of the wiki.
Changes
---
- Redirects users to default read-only wiki page when write permission is revoked. 
Side effects
---
- As a necessary consequence of migrating sharejs uuids, contributors who are on the page when permissions change will continue to undergo a forced page refresh, but their panel configuration will be preserved. This is the same as the current behavior
- The sharejs node.js server now requires the body-parser middleware
> Send contributor to read-only wiki page when removed from project

- website/addons/base/views.py
If an addon raises and AddonException, usually because of lack of auth or settings, catch and log the exception but return 400.
> Feature Fix Addons not configured

- website/static/js/folderPicker.js
User can't submit folderPicker selections in FF. This fixes that issue.
Modifies event binding to protect folderPicker selects' onchange event.
Hopefully none.
> Fix FF bug with non selectable selects in folderPicker

- bower.json
set zeroclipboard to 2.1.6, could not use in ie10
> [feature] bower zeroclipboard ie10 fix

- framework/transactions/commands.py
- framework/transactions/handlers.py
- tests/base.py
- tests/test_oauth.py
Addresses the problem @erinspace described in https://github.com/CenterForOpenScience/osf.io/pull/1943 . 
@lyndsysimon made a change recently that allowed the transaction `rollback` command to be run within a test request context without raising an error by checking allowing `OperationFailures` to pass when `settings.DEBUG_MODE` is `True`.  However, this means that we incorrectly get error logs here: https://github.com/CenterForOpenScience/osf.io/blob/f23bc005a30375af00b0314ba54ee3bc95770627/framework/transactions/handlers.py#L40-41 when in `DEBUG_MODE`.
This change only allows the OperationFailure to pass if `rollback` is called within a test.
> Only allow OperationFailure to pass if in testing mode

- website/static/js/fileRevisions.js
Purpose
=======
When viewing files within nested folders with google drive, the breadcrumb area displays the project name and the root folder, omits the subfolder(s), and the file name has a '/' separating each character.
Changes
=======
The breadcrumbs now display `{project} / {root} / {subfolder(/s)} / {filename.ext}` for GDrive
Side Effects
=========
Box will display `{project} / {root} / {file_id} / {filename.ext}`
> Fix GoogleDrive file naming bug

- website/addons/box/model.py
Temporary workaround to ensure that token checker has most current tokens from database.
> Ensure tokens not stale.

- website/addons/box/model.py
- website/addons/box/views/config.py
Previously had a combination of string and int IDs, which was breaking
the logging callback when uploading files to the Box root folder.
> Ensure Box folder IDs are strings.

- website/project/views/node.py
Mako was still attempting to render wiki widget even when wiki is disabled. This fixes that.
Adds a check in _should_show_wiki_widget to make sure the node has the wiki addon enabled.
None
> Don't show wiki widget when disabled

- website/search/search.py
- website/search/share_search.py
- website/search/views.py
Purpose
--------------
Allow people to access the raw, unprocessed elasticsearch results for the SHARE data.
Changes
Accept a ```?raw``` query parameter in the ```/api/v1/share``` route, which causes the raw elasticsearch results to be returned.
Side effects
-----------------
More data will be available from the elasticsearch route, yay!
@chrisseto  @erinspace
> Add option to get raw elasticsearch results from share endpoint (for aggregations and such)

- bower.json
Update markdown-it-toc, which had a bug with parsing tokens beginning with newlines.
^
Wiki's getting too cool for its own good.
> Update markdown-it-toc version

- tests/test_conferences.py
- website/conferences/views.py
Make conference lookups case-insensitive.
* Change `eq` operator to `iexact` as needed
* Add regression tests
None expected
> [hotfix] Ignore case in conference endpoints.

- website/static/css/site.css
Fixes this Trello card https://trello.com/c/TzitIkbk
Changes height related CSS that applied to Treebeard use for notifications, this css applies to both places notifications settings are changed. (Project Settings and Profile Settings)
None
> Make notifications-settings box fit to 500px then scroll

- bower.json
- website/static/js/conference.js
Add sorting to download column for presentations
This required a fix in treebeard, the fixed a bug related to number sorting. It's tested to work. Commit is here:
https://github.com/caneruguz/treebeard/commit/429317f7fefc5936e7dea9370622d01b6411f92b
The number sorting does not affect any existing treebeard instance in OSF (if it did, this bug would have come up earlier).
> [Hotfix] Add sorting to the download count column on presentations page

- .gitignore
- scripts/send_digest.py
Purpose
=======
Prevent scripts.send_digest.py from logging entirety of emails
Changes
========
Silence website.mails logger
Side Effects
==========
.gitignore logs/
> Quiet mail digest logging

- website/notifications/emails.py
- website/templates/emails/comments.html.mako
- website/templates/emails/comments.txt.mako
- website/templates/emails/digest.html.mako
- website/templates/emails/digest.txt.mako
- website/templates/emails/transactional.html.mako
- website/templates/emails/transactional.txt.mako
Makes changes to the email texts based on suggestions from community team
Based on Gary' email
Footer text:
- Change: "You received this email because you were subscribed to email notifications."
- To:         "You received this email because you are subscribed to email notifications."
Activity text:
- Remove "commented on your project" and/or "replied to you on your project"
so  "Gary A Safari commented on your project at ..."
becomes  "Gary A Safari at ..."
Time Format:
- Change: "Fri Feb 27 17:29:02 2015"
- To:          "5:29PM on Friday, February 27"
Final text would read (using the email image above):
Gary A Safari at 5:29PM on Friday, February 27: "Then 3"
**Individual Email Templates:**
Salutation:
- Change: "Hello First MiddleInitial Last, there has been recent activity on your …
> Make changes to the email text as suggested by community team

- website/templates/search.mako
Purpose
------------
Fix previous PR's issue of rendering registered and unregistered users identically
Changes
-------------
Unregistered contributors showing up in the search page as contributors to a project will no longer be rendered as links
Side effects
> search page no longer renders unregistered users as clickable

- website/static/js/notificationsTreebeard.js
Fix a regression bug where the toggle and retoggle of folder does not show all children. This was a regression bug caused by not setting height on load, so Treebeard was setting it's showTotal to be whatever the container happened to be at the time, in this case limiting it to 3 because that was all that could fit. 
In order to not have to roll back the height fix, what this change does is add another step towards checking the height of container after toggle because loading the items in fact does increase the height. 
The changes are limited to the notifications treebeard instance. There shouldn't be side effects but this is not an elegant solution for the long term, I'll look into how Treebeard is doing its redraws and maybe do a better fluid height solution for this. Although most …
> Add redraw based on height of container in notifications/treebeard

- website/addons/box/model.py
- website/addons/box/templates/log_templates.mako
Purpose
=======
Improve logging behavior for Box
Accompanies PR: https://github.com/CenterForOpenScience/waterbutler/pull/23
Changes
=======
Upload/update logs include human-readable path/link to file
Delete logs read: `{User} removed file '{filename}' from Box in project {project}`
Side Effects
=========
> Fix box logging

- requirements.txt
- tests/base.py
- website/addons/dropbox/tests/test_views.py
- website/addons/dropbox/views/config.py
Use HTTPretty instead of requests for mocking HTTP requests in tests.
* Switch from mock to HTTPretty
* Fix breaking Dropbox tests
None expected
Note: This uses my fork of HTTPretty for the moment, but we should be
able to switch back to the PyPI version once my patch gets merged.
> Use HTTPretty for test mocking.

- website/addons/figshare/static/figshareNodeConfig.js
- website/static/js/folderPicker.js
Some of the folderPicker code is oriented towards path-based addon configs (e.g. dropbox, github, box, gdrive) rather than name based (figshare, mendeley, zotero). In particular checks for pre-selecting selects when building the Treebeard rows are incompatible with figshare logic. This fixes the figshareNode config to prevent these checks from evaluating true when inappropriate.
Set figshare initialFolderPath to a string that is unlikely to be matched.
None
> Change check for pre-selecting folderPicker selects.

- website/templates/base.mako
Google Analytics objects should be mocked in the event that no GOOGLE_ANALYTICS_ID is set.
ga object is mocked if GOOGLE_ANALYTICS_ID is not set
Cleaner console error messages.
Closes-Issue: #2027
> [hotfix] ga object should be mocked if no ID present

- scripts/osfstorage/migrate_dates.py
- website/addons/osfstorage/model.py
After running this script last time, we changed which fields on the
`OsfStorageFileVersion` model were displayed to the user:
`date_created` now reflects the time the file was uploaded (which is
displayed to the user), and `date_modified` reflects the time the file
reached the backend (which does not always correspond to the upload
time, and is not displayed to the user). The original migration to OSF
Storage didn't copy creation time correctly; this updated migration
copies times from the `nodefile` collection to the `date_created` field
of `OsfStorageFileVersion`.
[Resolves #1885]
> Update migration to handle dates for pre-migration files.

- website/addons/wiki/templates/edit.mako
- website/static/css/site.css
This fix introduces flex display style to wiki panels so that their header does not scroll and the height is still equal despite header size differences. It also changes the compare panel header.
- Added flex style to view and compare panels
- Change compare header so that everything is in one line, works best across devices.
Shouldn't be any, the styles are compartmentalized. In IE9 the flex style will default to the stated height (500px) for those panel bodies.
> [Hotfix] Fixes wiki panel headers scrolling and use of space in devices

- website/static/css/commentpane.css
Fixes comment pane covering the project navigation links when they overlap. As reported in this issue: #1950 
- Z-index for the comment pane div is reduced
Solution provided by @sambrady3 
Doesn't seem to be any. Checked these scenarios
- XS size (because navigation changes significantly there), works correctly, opens above comment pane
- Search bar opening, works correctly opens above comment pane 
- Modals opening (work correctly, opens above comment pane)
> [Hotfix] #1950 comment covering project links

- website/static/css/site.css
This change is designed to fix this issue: #2017, without using css transform related hacks so that we have a more reliable solution.
Scrollbars specific to webkit (Chrome and Safari) were added to the treebeard body elements only with a generic looking grey design. 
There shouldn't be any, the scope is under control so it shouldn't apply to anything other than treebeard grids in webkit browser
- Tested in Chrome : shows custom bars as expected
- Tested in Safari: shows custom bars as expected
- Tested in Firefox: doesn't show custom bars as expected
- Tested in IE9, 10, 11: doesn't show custom bars as expected
Also tested fangorn, folderpicker and presentations, everything seems to work fine with the custom scrollbars.
> [Hotfix] Add webkit specific scrollbar css for treebeard

- framework/auth/forms.py
- tests/webtest_tests.py
- website/project/views/contributor.py
- website/templates/claim_account.mako
Addresses #1369 by removing text input field and replacing with text about what the E-mail is. This effectively disables the ability to change the E-mail without confirmation.
Users are unable to update E-mails via unregistered account claims.
This is merely a security plug and does not address the issue of the user wanting to change the E-mail.
Also this looks ugly and should probably be reformatted if it is going to be kept.
> Fixes #1369 unreg changing E-mails

- website/static/js/contribAdder.js
Fixes #1907 
Problem
------------------
In IE 9, the admin cannot add more contributors on hitting "submit" on the add contributor modal
Cause
-------------------
When the modal is dismissed, the javascript <code>clear</code> function is called, so all selections are cleared. Since the modal is dismissed prior to the selections are passed to python, python actually gets a list of 0 users to be added.
Fix
--------------------
Since the page is going to reload anyways if adding contributors is successful, now the modal is dismissed AFTER the selections are passed to python, a value is returned, and only when python fails to add a contributor.
Side effects
---------------------
None
And btw...
---------------------
I un-indented the js code for submit just for clarity...
ping @sloria …
> [hotfix] Fix for IE

- website/addons/wiki/templates/edit.mako
Additional fix for #2041 which takes care of the scenario where Menu panel also needs to scroll.
Added the flex classes to the menu panel as well. 
None.
> Add wiki menu panel to the flex layout so menu headers don't scroll.

- website/addons/box/settings/defaults.py
- website/addons/box/views/config.py
Currently clicking "Share on Box" from the folderpicker UI does nothing.This allows the folderpicker to work as expected.
- Add a share URL template to Box settings
- Add a share url to serialized Box settings
None
> Hotfix: Fix "Share on Box"

- website/addons/box/static/boxNodeConfig.js
- website/addons/box/templates/box_node_settings.mako
- website/addons/box/views/config.py
Cailey found some bugs in the first hotfix in particular when the Share button was being shown, and All Files getting prepended to folder names.
- Strip 'All files' from folder path
- Clean up logic for showing 'Share on Box'
None
> Clean up Box nodeSettings to consistently hide/show Share and correct

- website/addons/box/static/boxNodeConfig.js
'Share on Box' was still clickable when Box folder was unconfigured.
Fix logic to correct this.
None
> Fix logic for checking if Box folder not set

- framework/analytics/piwik.py
- website/discovery/views.py
- website/static/css/site.css
- website/templates/public/pages/active_nodes.mako
Changes:
* Returns more results from Piwik, extending the list of popular registrations (closes #2002)
* Changes the date range from the current week (Sunday-Saturday) to the previous week. This prevents displaying very few hits (or no active projects/registrations) early in the week.
* Removes some dead code filtering out projects with no contributors - that issue has long been fixed.
> [feature] Fixes for Public Activity page

- website/templates/nav.mako
Purpose
-----------
OSF is a registry. People do not understand this. Having a registry link is a quick first step to making that clear. 
Changes
------------
Adds a menu item to the Explore menu called Registry that takes the user to a Search page of all of the OSF registrations.
Side effects
Rearranged the Explore menu to put registry at the top and Collaborator Network, which becomes increasingly out of date, at the bottom.
Closes #1331
> Add "Registry" to the Explore menu

- website/static/css/site.css
As a result, users could scroll passed the nav menu and it wouldn't
correct itself until the user would hit the bottom of the page
and affix would become affix-bottom.
Hide sub nav elements (list items) until they become **active**.
None.
Closes-issue: #1843
> [feature] getting-started page scrollspy too big

- tests/test_addons.py
- website/addons/base/__init__.py
- website/addons/base/views.py
- website/addons/github/model.py
- website/addons/osfstorage/model.py
- website/addons/s3/model.py
Fixes #1819
In some cases when attempting to view a file that was no longer authorized an uncaught exception when attempting to retrieve the authorization from osf as `user_settings` was `None`.
Fixed by adding in a check of `has_auth` and adding `has_auth` to all addons that don't have it.
Side effects:
All waterbutler/Crud addons now need to implement `has_auth` ping @mfraezz @kushG
> [Hotfix] unauthed addon files

- website/addons/wiki/templates/wiki_widget.mako
**Purpose**
- Prevent long words and links from overflowing in the wiki widget.
- Resolves [#1373](https://github.com/CenterForOpenScience/osf.io/issues/1373)
**Changes**
- Add ```break-word``` class to wiki widget.
- ***Before***
- ***After***
- None.
> [hotfix] wiki widget text overflow

- website/static/css/site.css
- website/templates/project/modal_add_contributor.mako
This is an attempt at a different fix to issue #1778 compared to Nan's fix here: #2077 
Takes a CSS/HTML approach to fixing the width. 
- Adds table-fixed helper class for tables that need word wrapping done.
- Changes modal to a larger modal so more of the available window space is used.
- Adds widths to the table columns as percentages that work in different window sizes
- adds word-wrap to table cells
The effects are limited to the contributor adding table and seems to work fine in Chrome, Safari, Firefox. Didn't check Internet Explorer but the css property is has good cross-browser compatibility. 
- **Someone should check this with long username data from server, I changed names after page load. Since the css class still applies this shouldn't be an issue but better test it again.**
> Add proper word breaking to contributor cell in project contributors page

- bower.json
- webpack.common.config.js
- website/static/vendor/bootstrap-editable-custom/bootstrap-editable.js
Replaces bower-installed x-editable with a vendorized, stripped-down version. It removes many date-related inputs and plugins that we don't use, which drastically reduces the library's size; the minified vendor bundle size  was reduced by ~40 KB.
Note: If https://github.com/vitalets/x-editable/issues/277 is ever implemented, we probably won't need to use this any more.
> [feature] Use customized, stripped-down version of bootstrap editable

- website/static/css/fangorn.css
- website/static/js/fangorn.js
A solution to issue #1680; with suggestion from @brianjgeiger . This fix turns the img tag file icons into classes with backgrounds to avoid dragging of those files. I think this is a semantically correct way to handle this problem and it's less error prone. 
- Create file-extension class and file names classes starting with _
- Change fangorn.js ResolveIcon and related methods to generate proper classes instead of path
- Add md file extension to use .txt icon for the moment
- Minor adjustments to alt icon css
None. Only affects fangorn, (not project organizer or other uses of Treebeard since they don't actually have files). Tested in Chrome, Safari, Firefox. The css used here is very old so should be compatible with IE.
> Convert file icons in fangorn to classes with background images 

- website/static/js/share/searchBar.js
- website/static/js/share/stats.js
Once migration goes though, this number will match the one on the SHARE donut. Also, removed redundant variable setting in stats page.
> Hotfix to update hard-coded SHARE provider number in search bar

- website/static/js/pages/base-page.js
At the request of @saradbowman, I've modified the footer slide-in to appear only on pages that are part of a specific node (as opposed to blacklisting pages we don't want it to appear on)
> [feature] Make footer slide-in appear only on node pages

- requirements.txt
Resolves issue https://sentry.osf.io/osf/staging/group/2832/. We were
using the `json` parameter in `requests.Request`, which was added in
requests 2.4.2, but pinning to requests 2.4.1.
* Upgrade requests version
None expected
As it turns out, this was breaking on staging but not on production, since production is currently using a newer version of requests than the version in `requirements.txt`.
> Upgrade requests to latest version.

- website/templates/public/pages/meeting.mako
- website/templates/public/pages/meeting_body.mako
- website/templates/public/pages/meeting_plain.mako
Show external link to conference (if provided) as well as submission info
* Show external link if provided
* Move duplicated mako code into included file
None expected
Requested by / discussed with @saradbowman
> [hotfix] Show conference external link

- tests/factories.py
- tests/webtest_tests.py
- website/addons/wiki/templates/edit.mako
Purpose
------------
One of the requirements of the one-page wiki was that the mako contain the wiki content so we don't lose SEO. This happened on the project summary page, but that code was dropped from the edit page. This fixes that.
Changes
------------
* Add the mako code that shows the wiki content back into the page.
* Also add tests.
* When the tests don't work, have @jmcarp fix the wiki factory so the tests run.
Side effects
Our wiki factory didn't actually do anything by way of adding wiki pages, so that's been corrected. Wiki factories now produce wiki pages. Also, heh, a couple of tests we skipped in the update because we thought we couldn't do were actually tests we needed, so I got rid of the skips.
Closes #2135
> Hotfix/Wiki Initial State

- tests/test_notifications.py
- website/notifications/emails.py
Fixes https://trello.com/c/gydQs38q/40-replying-to-a-comment-sends-email-with-misleading-incorrect-information.
Whenever a comment is a reply to another comment, only use the email template for "replies to your comment" for the user who was responded to. For all other subscribers, use the "comments" email template.
> Feature fix: Use comment reply email templates only with direct replies

- website/search_migration/migrate.py
Purpose
--------------
This PR ensures that all active users are added to the search index when ```inv migrate_search``` is called.
Changes
--------------
There is some logging added to the end of the migration script, so that we can know how many users/nodes were iterated over and how many should be in the search index. I also iterate over all users and add them if they are active, rather than manually checking a few properties like the previous script did
Side-effects
--------------
Hopefully all users will show up in search after a migration. Other than that, none.
> Fix user migrations

- tests/test_notifications.py
- website/notifications/emails.py
Fixes https://trello.com/c/gydQs38q/40-replying-to-a-comment-sends-email-with-misleading-incorrect-information.
Extension of PR https://github.com/CenterForOpenScience/osf.io/pull/2130, that accounts for users who receive notifications on components that are set to the default "adopt settings from parent component."
> [feature fix] Fix notification message for comment replies on components

- website/addons/github/model.py
- website/addons/github/templates/github_node_settings.mako
- website/addons/github/tests/test_models.py
- website/addons/github/views/hgrid.py
- website/routes.py
Handle 401 errors from GitHub API in various points in the code, borrowing language from Dropbox addon.
* Add `valid_credentials` field to serialized GitHub settings
* Show appropriate error message on invalid credentials
* Catch other 401s and add regression tests
None expected
[Resolves #2103]
Note: Most of the frontend changes in this patch will be replaced by an
upcoming refactor of the GitHub UI by @harrismendell.
> Handle 401 errors from GitHub.

- bower.json
- website/static/js/fangorn.js
Fixes a critical issue where Projectorganizer dragging clone did not appear properly.
Main changes were in Treebeard. See commit: https://github.com/caneruguz/treebeard/commit/40af39cb35ac545732b184a3dddc20e37b85159f
For OSF
- Bower.json commit hash for Treebeard was changed to latest commit in Treebeard
- a minor option setting that defines the removeIcon (for modal that appears when deleting files) was added to comply with Treebeards new requirement. 
None, the Treebeard changes are minor and low impact.
> [Hotfix] Project organizer dragging does not display the clone

- tests/test_notifications.py
- website/notifications/emails.py
<h3> Purpose </h3>
When formatting datetimes by locale for the notification emails, the day and month are translated into the language specified in the locale tag and may cause a unicode encode error. 
Return a unicode string in `localize_timestamp`
> Feature: Handle unicode encode error in localized datetimes

- website/addons/github/model.py
- website/addons/github/tests/test_models.py
Steps (requires 2 users):
* User 1 creates a project,links a github repo, and adds User 2 as a admin
* User 2 authorizes github
* User 2 attempts to view the settings of User 1's project
The fix:
* Default `valid_creditials` to `False`
Side effects:
* The following snippet will no longer raise an error but just return that a user is unauthorized
```python
except GitHubError as error:
if error.code == http.UNAUTHORIZED:
repo_names = []
valid_credentials = False
```
> [Hotfix] GitHub nodesettings auth battle

- website/project/views/node.py
- website/templates/project/registrations.mako
Closes issue #1628 where the message "To register this component you must register the parent project" is currently shown to the public and to contributors who do not have permission to register the parent project.
Only show the message to users who are admin on the parent project, since they are able to register it. For everyone else, show the message, "There have been no registrations of the parent project ([parent project title])."
> Hotfix: Fix message shown when there are no registrations on a component

- website/addons/figshare/static/figshareFangornConfig.js
- website/static/js/fileRevisions.js
Hide the delete button on the file detail page for Figshare files until we know whether the file is editable or not.
* Default `editable` to `false` for Figshare files
None expected
[Resolves #2101]
> Set Figshare files to uneditable by default to avoid accidental deletes.

- website/addons/mendeley/tests/test_models.py
- website/addons/zotero/tests/test_models.py
Atm to_json is handled in the superclass and testing on a per-addon basis is
unnecessary. Also these test were failing and breaking builds on develop.
Remove test_to_json from Zendeley test_models
Broken builds should now pass. :beers:
> Remove test_to_json from Zendeley test_models.py

- website/static/js/growlBox.es6.js
- website/static/js/oop.js
- website/static/js/tests/oop.test.js
Addition of two JS functions to use when OOP is needed. 
We have encountered a number of use cases for OOP in the JS codebase (see, for example, the mixins and inheritance used in `profile.js`). We've thus far used Constructor/Prototype (see [COSDev](https://github.com/CenterForOpenScience/osf.io/pull/2134)) for encapsulation and `$.extend` for inheritance. While this pattern is valid, it can be overly verbose and difficult to understand for newcomers to JS.
One alternative is to use ES6 classes, as in https://github.com/CenterForOpenScience/osf.io/pull/2134 . However, the Babel transpiler only supports ES6 classes in IE>=10 (source: http://babeljs.io/docs/usage/caveats/). 
The functions in this PR provide a happy medium--clean type definitions and browser support back to Netscape …
> [feature] Add helpers for OOP

- tests/test_views.py
- website/static/js/forgotPassword.js
- website/static/js/pages/forgotpassword-page.js
- website/static/js/tests/forgotPassword.test.js
Currently, there is no stand alone page where users may request password resets. While this is not an issue if all logins are routed through /login/, it becomes an issue once logins become an option from the navbar in PR #1865. 
Users may now use a clean reset password module. Developers can use the viewmodel as either a child component within larger viewmodels or as a standalone.
webpack.common.config.js has one more line
Depends-on-PR: #1728, #1865
Build will fail until dependencies are merged.
Need review
> [feature] add forgot password page

- website/addons/mendeley/templates/mendeley_node_settings.mako
Obsolete references to validCredentials was breaking the KO template.
Remove binding to validCredentials.
Template doesn't break.
> [Ready for Review] Mendeley folderPicker bugfix

- bower.json
- package.json
markdown-it-toc was allowing special characters in anchor hrefs and ids. This broke javascript event binders. 
Strip special chars from hrefs and ids
none
> Upgrade markdown-it-toc and move to package.json

- website/static/js/projectorganizer.js
- website/views.py
When a project's modifiedBy field was empty, projectorganizer was showing a modified 'by undefined'. This PR omits the 'by {name}' string if this is the case.
- Use CSS alias
- Omit name string if empty
- Fix kwarg in website views
None
> [Rrready for Review] Feature/projectorganizer no last name

- website/addons/dropbox/tests/test_views.py
- website/addons/dropbox/views/auth.py
resolve issue https://github.com/CenterForOpenScience/osf.io/issues/2177
<b>Purpose</b>
Fix the problem that when cancel the authorization on dropdox while you author it will always return you to user settings page instead of node settings page
<b>Changes</b>
if now you authorization starts from node settings page. It will return you back to there instead of return you to user settings page.
> fix the redirecting issue

- website/addons/citations/provider.py
- website/addons/mendeley/model.py
- website/addons/mendeley/templates/log_templates.mako
- website/addons/mendeley/tests/test_models.py
- website/addons/mendeley/tests/test_views.py
- website/addons/mendeley/views.py
- website/addons/zotero/model.py
- website/addons/zotero/templates/log_templates.mako
- website/addons/zotero/tests/test_models.py
- website/addons/zotero/tests/test_views.py
- website/addons/zotero/views.py
- website/project/model.py
- website/static/js/citationsFolderPickerViewModel.js
Citation addons don't currently have logs for selecting a folder, but they should. This patch adds logs for folder selection for Mendeley and Zotero.
* Add logs on `set_target_folder`
* Add Mendeley and Zotero log templates
* Update tests
Side effects
None expected
Note: As discussed with @lyndsysimon, addon logging should be generalized, but this can happen in a future patch.
> Add logs on folder selection for citation addons.

- tests/test_addons.py
- website/addons/base/__init__.py
- website/addons/base/views.py
- website/addons/box/model.py
- website/addons/box/tests/test_models.py
- website/addons/dropbox/model.py
- website/addons/dropbox/tests/test_models.py
- website/addons/figshare/model.py
- website/addons/figshare/tests/test_models.py
- website/addons/github/model.py
- website/addons/github/tests/test_models.py
- website/addons/googledrive/model.py
- website/addons/googledrive/tests/test_models.py
- website/addons/osfstorage/model.py
- website/addons/osfstorage/tests/test_models.py
- website/addons/s3/model.py
- website/addons/s3/tests/test_model.py
* Give slightly better error message to users when attempting to view files that are no longer in scope of their project
* Check if addons are unconfigured when attempting to view files
* When attempting to view a file that's containing addon was unconfigured it would cause 500s.
* Adding the `complete` attribute to denote if an addon is completely configured and authorized
* all addons must now implement a complete property
* otherwise it will raise a `NotImplementedError` when it is called
* mendeley and zotero should not require `complete` currently as they should never be in a view function that requires that property
* Tests on the way
> [Feature] fix removed addon files

- framework/auth/core.py
- scripts/analytics/benchmarks.py
- scripts/analytics/folders.py
- scripts/migrate_was_invited.py
- scripts/tests/test_migrate_was_invited.py
- tasks.py
- tests/test_models.py
- website/project/model.py
We don't currently have a practical (i.e. using a single, tolerably fast query) way to figure out whether an active user was originally created as an unregistered user or not. This isn't ideal for metrics or provenance tracking. This patch adds an `is_invited` field to `User` to track user provenance, and adds a migration script to backfill the new field for existing users--thanks @lyndsysimon for suggesting the method for this.
* Add `is_invited` field to `User`
* Add migration to backfill `is_invited` for existing users
* Add indices on queried fields
None expected
> Track whether users were created as unregistered.

- website/static/js/pages/project-base-page.js
Fixes this bug reported in Trello: https://trello.com/c/Rcit6oVh. When browser goes back to files page "view file" tooltips do not clear
This issue is caused by backward/forward cache: https://developer.mozilla.org/en-US/docs/Using_Firefox_1.5_caching
Added a dummy unload event which doesn't do anything but existence of an unload event forces the browser to reload the page when it goes back in history, therefore not maintaining state. 
I added this to project base page so that it applies to other places this tooltip may appear with files, i.e. Files page, future single file view page or others as they may come up. Navigating to other project pages isn't causing any issues. 
* Tested in Chrome, Safari, Firefox, IE 11
> Add unload event to force browsers not to use bfcache

- website/util/rubeus.py
Projectorganizer was ommitting the person who last modified the project when their last name is empty or undefined. This lets that value fall back to the modifier's first name.
Let modifiedBy fall back to given_name
None
> [Ready for Review] Let modifiedBy fall back for user's first name

- website/addons/base/serializer.py
Under some circumstances user's were getting 500s when creating Mendeley credentials
Check to make sure user_settings is not None before attempting serialization
None
> [Ready for Review] Prevent Mendeley 500s

- tests/base.py
- tests/test_elastic.py
- website/search_migration/migrate.py
Purpose
-----------
Account for index numbers with multiple digits during migrations
Changes
------------
Now account for index numbers with multiple digits during migrations
Side Effects
Migrations made on indices with multi-digit version numbers will now not loop back to the second digit +1
TODO
---------
> Now account for index numbers with multiple digits

- tests/test_share.py
- website/search/share_search.py
- website/search/util.py
SHARE atom feed at http://osf.io/share/atom was displaying errors in chrome and firefox because of an illegal-for-xml unicode character that had gotten through the atom feed parser.  This fix screens any title, description, tags, or contributors for any more of the unicode characters that are illegal for XML, and replaces them with an empty string. 
Add a function to utils that scans for unicode chars illegal in XML. Fix found at https://maxharp3r.wordpress.com/2008/05/15/pythons-minidom-xml-and-illegal-unicode-characters/ . Use that function when generating the title, summary, tags and contributors for the atom feed in share_search.py
Shouldn't be any! Only used in a small part of the share atom feed. Possible that some titles will display strangely if the character that gets through is …
> Fix illegal-for-xml unicode chars in Atom feed

- .travis.yml
- README.md
- requirements.txt
- requirements/dev.txt
- requirements/metrics.txt
- requirements/release.txt
- tasks.py
- webpack.dev.config.js
Currently, OSF requirements and user metrics requirements are installed in separate virtuaenvs. If we forget to install metrics requirements after deploying a release, our user metrics scripts break. This PR makes it easier to install all deployment requirements into a single virtualenv.
- Put environment-specific requirements files in`requireements` directory
- Modify `requirements` invoke task for the following interface
```
inv requirements --dev
inv requirements --addons
inv requirements --release
```
- Add `req` alias to invoke task
- Don't install all mfr renderer dependencies on travis--they aren't necessary for the tests
- `inv assets -d` will *not* put you in watch mode. You must pass `-w` or `--watch`. This allows us to build dev assets on Travis
- To update dev environments, …
> [hotfix] Requirements install

- website/static/css/site.css
- website/static/js/comment.js
- website/templates/include/comment_template.mako
Resolves https://github.com/CenterForOpenScience/osf.io/issues/2267
- Renders comment content using the markdown-it renderer
- Adds an edit button which toggles comment input
The display element for the markdown content now uses the `html` rather than the `text` binding. We rely on `markdown-it-sanitizer` rather than Knockout to sanitize the comment content.
> [hotfix] Markdown  comments

- webpack.common.config.js
- webpack.dev.config.js
- webpack.prod.config.js
- website/util/paths.py
Prevent extra app reload every time assets are built during development.
- webpack will no longer append hashes to built files when in debug mode
- [assets-webpack-plugin](https://github.com/sporto/assets-webpack-plugin) is no longer used in dev environments
None. Devs can now safely remove old assets with `inv clean_assets` the rerun webpack with `inv assets -dw`.
> [feature] Don't cachebust webpack assets in DEBUG_MODE

- CONTRIBUTING.md
github doesn't auto-link issues in Markdown documents in the repository; fixed links by inserting appropriate markdown linkage fu.
> Fix "examples of good issue reporting" links in CONTRIBUTING.md

- website/templates/public/pages/faq.mako
Changes smart quotes to regular quotes to fix the malformed links in the FAQ.
Closes https://github.com/CenterForOpenScience/osf.io/issues/2284
> Fixes smart quotes

- CONTRIBUTING.md
Fix link for #382 to point to #382, not #384. Mistake introduced in #2286.
> Fix mistake in issue link introduced by previous fix.

- tests/test_share.py
- website/search/share_search.py
- website/search/util.py
- website/search/views.py
XML was letting html tags through in title, description and tags. This hotfix updates the already existing remove illegal unicode chars function to also strip out html tags from the fields that were already getting checked for inappropriate characters for the xml atom feed.
Also, the atom feed was cutting off the first result, because I was starting the feed based on "page" instead of "start." Thanks for catching that @fabianvf!
- add re to find elements enclosed in <> tags signifying html tags
- replace found tags with nothing in illegal unicode function that before just removed illegal unicode characters
- Rename illegal_unicode_replace to html_and_illegal_unicode_replace to reflect change
- In search_share_atom in search views, update query to be based on "start" instead of "page" - …
> [WIP] Update SHARE Atom Feed - html tags and cutting off first result

- website/templates/nav.mako
While the username is a user's email, the OSF signup refers to "Email" not "Username" as now specified in the placeholder in the nav bar.
This simply changes "Username" to "Email".
> Change the login placeholder from "Username" to "Email"

- website/templates/project/project.mako
- website/templates/project/project_header.mako
Fixes these two issues: 
#2184 
#2293 
- The icons and methods for a parent that is not a private project were the correct ones, these were not accurately transferred to the scenario where the parent is private. These have changed to have the same behaviors
- If there is no link to parent component the cursor is not a link and the tooltip says the parent is private. 
None, very tiny code change.
> [Hotfix] Issue fixes related to private top project icons

- website/addons/dropbox/static/dropboxNodeConfig.js
- website/addons/dropbox/static/dropboxUserConfig.js
- Clarifies the language in the dropbox authentication error message as described by @caileyfitz and @samanehsan in [#2201](https://github.com/CenterForOpenScience/osf.io/issues/2201)
- Only changes the text of the user-facing error message.
> dropbox authentication error message

- website/templates/nav.mako
- Allows the presentation service to be accessed by users directly from the OSF.
- Addresses [#1418](https://github.com/CenterForOpenScience/osf.io/issues/1418) and [#2115](https://github.com/CenterForOpenScience/osf.io/issues/2115#issuecomment-85587127)
- Adds the link to the presentation service to the Explore tab in the navbar.
> [feature] presentation service link

- website/addons/wiki/templates/edit.mako
Fixes this issue: https://trello.com/c/Vix4YLTL/31-single-page-wiki-does-not-have-page-scroll
Added back the flex css knockout binding for View wiki-panel-body
None
> Fix Trello issue with scroll not happening on single page.

- framework/analytics/__init__.py
- tests/framework_tests/test_analytics.py
Problem
------------------
Upload two files to the osf storage with file1 including underscores and file2 has the same name as file1 but changes all underscores to dots. Such as "ginny_huang.txt" and "ginny.huang.txt"
There download counts will synchronize. Downloading one of them will cause the other download count to increase too.
Cause
------------------
Before we have waterbutler, there are restrictions to filenames, so osf would change "ginny.huang.txt" into "ginny_huang.txt" when uploading that file. 60f430a9ae1f36ba0edd16879508e07bb2f1447f is commited for consistency.
Solution
-------------------
Since now we can have "ginny_huang.txt" and "ginny.huang.txt" in the osf storage together, we do not need that fix anymore.
Side effects
---------------------
If you have files with names …
> [hotfix] download count

- website/static/css/share-search.css
- website/static/js/share/index.js
- website/static/js/share/results.js
- website/static/js/share/searchBar.js
- website/static/js/share/sideBar.js
- website/static/js/share/stats.js
- website/static/js/share/utils.js
- website/static/js/tests/share/utils.test.js
Purposes
--------------
Update functionality and prettiness of SHARE UI
Changes
-------------
Side effects
> Add a sidebar to the share search page

- website/static/js/share/index.js
Changes
-----------
self.vm changed to self. in the viewmodel init
Side-effects
SHARE page shouldn't crash due to js errors.
> Fix typo from last commit for the SHARE UI changes

- bower.json
- package.json
Fixes https://trello.com/c/WoSjkJ9g/14-view-only-links-don-t-actually-copy-when-icon-is-clicked
> Move zeroclipboard to bower

- website/static/js/share/index.js
- website/static/js/share/utils.js
Changes
-----------
Add an extra check for state change, don't push a new state unless URL parameters have actually changed.
Side-effects
Will no longer spawn an infinite series of empty states when hitting the back button on the share page
> The back button now works when getting directed from the search page

- website/static/js/share/utils.js
Changes
-------------
Data is explicitly unloaded from the graph. The little sliver of data in the donut chart is gone. When there are no results, the time graph clears.
> fix some graph weirdness by explicitly unloading data

- website/search/elastic_search.py
- website/templates/search.mako
**Steps to reproduce**
1. Make sure you have a public project
2. Add an unregistered user to that project
3. Add a registered user to that project
4. Search for this project
In the search result, there is a link for the unregistered user, while there is no link for the registered user. If you click on the unregistered user, it takes you to the profile page of the registered user.
**Cause**
Calling <code>es.search</code> returns a formatted output that is specified in <code>website/search/elasticsearch.py:update_node</code>. That format stores contributor names and contributor urls in separate lists, which results in the bug.
**Fix**
Changes the format of the elasticsearch output to the following:
{
'contributors': [
{
'url': '/a1b2c',
'name': 'Ginny Huang'
},
{
'url': None,
'name': 'Ginny …
> [hotfix] Match contributors list in search with that on project overview

- package.json
SHARE graphs were experiencing a strange loading issue with sometimes partially loaded data. This issue was very similar to the recently closed c3 issue here - https://github.com/masayuki0812/c3/issues/975
Updating c3 to 0.4.10 should fix some of the strange graph behavior!
- change c3 version from 0.4.9 to 0.4.10 in package.json
WiIll need to update version of c3 by running ```npm install --update```
> Update c3 to 0.4.10 to fix partial loading issues on SHARE graphs

- website/addons/wiki/templates/edit.mako
- website/static/js/osfHelpers.js
Fixes Trello card: https://trello.com/c/mGfhI0ii
Was used wrong position offset information, for closed components used position rather than offset to correctly get parent element offset. 
None. Tested with regular projects as well.
> Fix wiki anchor scrolls not working in registration or private modes

- website/addons/citations/provider.py
Users were getting 500s when trying to load Mendeley or Zotero content
when not logged in.
We were making an explict call to user.get_addon(...) even when user is
possibly a None. This fix allows user to be None.
None
> Allow for user to be None when constructing addon_serializer.

- website/search/share_search.py
- website/static/js/share/stats.js
- website/static/js/share/utils.js
Update the SHARE search page graph, specifically fixing:
- Graph now differently redraws to 0 when there are no results
- Re-searching from the beginning no longer renders blank pie slices
- Time series tooltip no longer shows ALL providers, only one per data point
- Remove redraw from share utils, causing weird blank pie slices
- Make the tooltip no longer grouped, but individual
- Add columns with 0 results per provider for 0 search results
> Update SHARE search graph

- website/static/js/share/stats.js
Purpose
------------
When there are no results, nearly empty graphs are displayed (with a small sliver for all the sources with 0 results). This is confusing and ugly.
Changes
------------
Now, if your search yields no results, the graphs are hidden
Side-effects
-----------------
Possible performance issues? I would love if someone who had some experience with c3 could look at this change.
> Hide the graph if there are no results

- tests/test_share.py
- website/routes.py
- website/search/views.py
- website/static/js/search.js
- website/static/js/share/stats.js
- website/static/js/share/utils.js
Purpose
-----------
We are ensuring that all non-REST-ful search routes be easily recognizable via the suffix /search/
Changes
-------------
Move the /api/v1/share/ search route to /api/v1/share/search/
Side-effects
--------------
Hopefully none, so long as I successfully found every use of the route in the frontend (which I think I did).
> move /api/v1/share/ to /api/v1/share/search/

- framework/auth/views.py
Requests for password resets of email accounts that had not been registered were informing the requestee that they didn't exist. Generally these should fail silently so we don't inadvertently leak information to a malicious party.
Requester shall see the same status message informing them an email has been sent with reset information regarding the account in question regardless of whether that email is registered or not.
This could confuse legitimate users that type in the wrong email address and don't read the status message.
Closes-Issue: #2355
> [hotfix] forgot password should not give unnecessary info

- tasks.py
This is a fix for https://github.com/CenterForOpenScience/osf.io/issues/2309
Of course, now email logging doesn't work with `invoke server --live`, hence the WIP tag.
I don't really understand what's happening and I am not familiar with livereload, but maybe this can give some inspiration for a better fix.
> [WIP] import livereload class only in live mode

- website/addons/s3/templates/log_templates.mako
<b>Purpose</b>
Fix https://trello.com/c/xZzHugJO/79-s3-amazon-simple-storage-service-which-is-it-exactly.
<b>Changes</b>
Change all the names of Amazon S3 in log parts to Amazon S3
before change it's either called S3 or Amazon Simple Storage Service
after changes,
they are all called Amazon S3
> change all the Amazon S3 name display in logs to 'Amazon S3'

- website/templates/project/contributors.mako
- website/templates/project/modal_add_contributor.mako
- website/templates/project/modal_generate_private_link.mako
<b>Purpose</b>
Update all fa-question-sign to fa-question-circle according to the update from font-awesome 3.2 to font-awesome 4. fix issue https://github.com/CenterForOpenScience/osf.io/issues/2395
<b>Changes</b>
for public project's anonymous link in view-only link table in sharing page
before change
after
admin on parent project
before change
after change
add contributor permission
before change
after change
add view-only link
before change
after change
<b>Others</b>
Perhaps need someone to inspect any missing font-awesome icon missing upgrade from 3.2 to 4.0 throughout osf
> update all fa-question-sign to fa-question-circle 

- website/addons/box/model.py
- website/addons/box/templates/log_templates.mako
- website/addons/box/tests/test_models.py
- website/addons/box/utils.py
<b>Purpose</b>
fix the problem https://trello.com/c/1qyfOSRH/81-staging-box-add-on-linked-folder-logged-incorrectly.
<b>Changes</b>
Now the box folder name in log updated correctly.
> fix the folder_name of box addon in log

- website/addons/dataverse/static/dataverseNodeConfig.js
Users were always getting error messages when connecting a dataverse account (even with success).
Fix the typo that was causing this.
None
> Fix Dataverse error messages

- website/static/js/citationsNodeConfig.js
Addresses the issue defined here: https://trello.com/c/PrkBu8ww/51-cannot-change-user-account-for-mendeley-zotero
Before, if a user saw 'Create Access Token', we assumed they had 0 linked accounts (a fallacy). Now we force them to choose from their list of connected accounts every time.
None
> Force user to pick account even when 'Create Access Token'

- website/static/css/site.css
Fixes issue reported at : #2363 
- Added media tag for shortening the input element for signin form at certain intervals. 
- Adjusted spacing in XS to fix a horizontal scroll bar
- Adjusted padding in search bar in XS to fix apparent misalignment. 
None.
Tested in Chrome, Firefox, Safari
Checked other sign in forms, since this change is using id specificity it shouldn't effect other elements.
> Fix sign in form overlapping with search at certain width intervals

- website/static/js/accountSettings.js
<b>Purpose</b>
fix https://trello.com/c/v6C5qJqy/90-confirmed-emails-show-up-in-unconfirmed-emails-list
> fix the Confirmed emails show up in Unconfirmed emails list

- website/static/js/contribAdder.js
<b>Purpose</b>
fix https://github.com/CenterForOpenScience/osf.io/issues/2432. fix the problem that you can't import contributors from parent project.
> fix the can't import from parent

- website/static/js/folderPickerNodeConfig.js
- website/static/js/tests/addons/folderPickerNodeConfig.test.js
- website/templates/project/addon/node_settings_default.mako
Node config for addons was rendering 'None' inappropriately:
https://trello.com/c/LcxG8dAD/120-zotero-mendeley-folder-picker-none-option
Fix bugs in logic for checking whether no folder is linked.
None
> Bugfixes to folderName logic and tests

- framework/addons/data/addons.json
- tests/test_rubeus.py
- website/addons/s3/__init__.py
We've decided to always refer to Amazon Simple Storage Service as Amazon S3. Logs generated using AddonConfig#full_name were still using 'Amazon Simple Storage Service'.
Change S3 full_name to Amazon S3
Wondering if @lbanner and @GaryKriebel are aware of these changes, and those in:
https://github.com/CenterForOpenScience/osf.io/pull/2409
There's a good chance these changes affect our user docs.
> Change S3 full name to Amazon S3

- tests/test_share.py
- website/routes.py
- website/static/js/share/utils.js
Purpose
-----------
Make share search routes work again
(/api/v1/share/search changed to /api/v1/share for some reason)
Changes
------------
api/v1/share -> api/v1/share/search
> fix route regression 

- tests/test_notifications.py
- website/notifications/emails.py
The signature for check_parent was not updated along with the rest of emails.py. This fixes it.
Tests need to be fixed.
> check_parent fix

- tests/test_identifiers.py
- tests/webtest_tests.py
- website/identifiers/metadata.py
- website/project/views/register.py
Adds a function `datacite_metadata_for_node` for building the [datacite metadata XML](http://schema.datacite.org/meta/kernel-3/index.html) for a given node. Allows all contributors of a Node to be listed as a creator for the DOI.
> [wip] Feature: DOI metadata/multiple creators

- website/addons/googledrive/templates/log_templates.mako
Decode the folder name of google drive when linking new folders.
> Feature-Fix Google drive "Linked" logs

- website/addons/dataverse/requirements.txt
This fix reverts all backwards-incompatible changes from 4.0 by locking to an earlier commit.
> Pin dataverse client to compatible commit

- website/profile/views.py
- website/static/js/accountSettings.js
<b>Purpose</b>
fix https://trello.com/c/iuQqlj9Z/88-making-email-primary-while-logged-in-as-another-user-sends-confirmation-email-to-an-already-confirmed-user.
> [hotfix]multi_account_add_email

- tasks.py
Default action for exists during pip install.
Prevents the invoke requirements task from freezing w/o prompt while waiting on input during pip installs.
**Issue**
```bash
Installing requirements for dataverse
Obtaining dataverse from git+https://github.com/IQSS/dataverse-client-python.git@b6aec5bc3fd1cc3199e3c97ac9c71705b54c3d11#egg=dataverse (from -r /Users/michael/Projects/cos/osf/website/addons/dataverse/requirements.txt (line 1))
git clone in /Users/michael/.virtualenvs/osf/src/dataverse exists with URL https://github.com/rliebz/dvn-client-python.git
The plan is to install the git repository https://github.com/IQSS/dataverse-client-python.git
```
**Actual Problem**
```bash
Obtaining dataverse from git+https://github.com/IQSS/dataverse-client-python.git@b6aec5bc3fd1cc3199e3c97ac9c71705b …
```
> [feature] pip install exists-action wipe

- website/static/js/pages/base-page.js
- website/templates/base.mako
- website/templates/index.mako
- website/templates/public/forgot_password.mako
- website/templates/public/two_factor.mako
<b>Purpose</b>
fix the outdated redirect link in website. solves https://github.com/CenterForOpenScience/osf.io/issues/2467.
<b>Changs</b>
Sign up bottom on the main page now redirect you to the correct signup form
the bottom on the slide in footer should all work and redirect you to the right place
The back to osf link on two factor page and forget password page now redirect you to main page instead of log in page.
> fix redirect link over the website

- website/static/js/share/stats.js
Pubmed should instead be displayed as pubmed central. As we've never changed a provider name before, we still need to figure out the best way to do this. As a temporary fix to the front end of the graph, I've changed the text for pubmed to pubmed central using the c3 tooltip function. Once we've done a proper assessment and come up with a fix for this, this custom tooltip code can be removed.
Add custom tooltip formatting in c3 code for generating the donut and time graphs that changes the display "pubmed" to "pubmed central."
Should only effect tooltip of pubmed entries.
> SHARE: Change hovertext for pubmed to pubmed central

- website/templates/project/registrations.mako
<b>Purpose</b>
Fix the problem that the public project registration page's redirect link direct you to top of public activity page instead of newest public registration part. Solves https://github.com/CenterForOpenScience/osf.io/issues/2461.
<b>Changes</b>
Now the redirect link direct you to the Newest public registration part of the public activity instead of top of the public activity page.
> improve the public project registration page redirect

- website/templates/project/project.mako
- Resolves [#2211](https://github.com/CenterForOpenScience/osf.io/issues/2211)
- Changes the tooltip for the duplicate project button to match the tooltips displayed for the watch/unwatch button and add to/remove from dashboard button.
> [hotfix] duplicate project tooltip

- api/users/views.py
Change permissions of the UserList class to `IsAuthenticatedOrReadOnly` so that GET requests are still allowed for unauthenticated users.
> [feature] API V2 DRF: Make UserList class permission IsAuthenticatedOrReadOnly

- tests/test_mailchimp.py
- tests/test_notifications.py
Fix tests in `test_mailchimp.py` and `test_notifications.py` that pass in a user object instead of `user_id`.
> Fix incorrect tests

- tests/test_addons.py
- website/addons/base/views.py
- website/routes.py
by checking the existence of the requested path in the node's
file tree
Using legacy routes in https://github.com/CenterForOpenScience/osf.io/blob/77e84f6ba8a5f05d06384d735e5d3ed851a8aa0d/website/routes.py#L807-863 with invalid file paths should no longer generate invalid GUIDs.
> [hotfix] Prevent creation of invalid OsfStorageFileGuids

- website/templates/log_templates.mako
Purpose
Fix #2529. Remove the extra "and" in log.
> fix doi registration log

- website/static/js/fileViewTreebeard.js
Purpose
------------
With the addition of folders, the paths for osfstorage files are no longer the full path to the file. As a result, those files will not highlight in the files navigation panel on the file detail page. 
Fixes https://trello.com/c/gM5yd99b/33-osf-file-not-highlighted-in-file-tree
Changes
------------
Get file paths from `window.contextVars.file.extras.fullPath` instead of `window.contextVars.file.path` for highlighting osfstorage files. Also do this for box files, since the full path to the file is now available.
> Release 0.34: Fix osfstorage and box file highlighting

- api/base/filters.py
- api/nodes/views.py
- tests/api_tests/test_base.py
- tests/api_tests/test_nodes.py
Purpose
-----------
Filtering tests.
Also fix the problem where filters would ignore privacy settings (and also folders and deleted nodes).
Changes
------------
1) Added tests.
2) ANDing the query filter to the base query rather than replacing it.
3) Changed the node base query to check for folders rather than dashboards, as dashboards are a subset of folders, and you don't want either.
Side effects
> Feature/api v2 drf - Tests and privacy

- api/base/serializers.py
- api/nodes/serializers.py
- api/users/serializers.py
Purpose: 
Add counts to `NodeSerializer` links field
Changes: 
- Change `_url_val` to take strings as functions of the serializer instead of attributes of the object being serialized.
- Add serializer methods for getting counts for node children, contributors and registrations.
- Add counts in links dict passed to `LinksField`
> [feature] API v2 node serializer counts

- scripts/populate_conferences.py
image is no longer hosted on spsp site, removing it from presentation service
> Remove SPSP15 logo URL

- website/templates/project/registrations.mako
This ticket refers to an issue observed in testing the development branch for the upcoming 0.35 release. It does not occur in production.
Projects with known registrations display additional, irrelevant text on the registrations page (see screenshot).
This appears to be a vestige of commented-out code in the mako template:
```
#% elif node['node_type'] != 'project':
```
Changing this to the double-pound-sign comment syntax [recommended](http://docs.makotemplates.org/en/latest/syntax.html#comments) in the mako docs removes this extraneous text. An alternate and longer-term solution would be to remove the commented out block altogether.
> Fix extraneous text on registration page

- website/static/css/site.css
- website/static/js/pages/profile-settings-page.js
- website/static/js/pages/project-settings-page.js
- website/templates/project/settings.mako
Resolves two bugs related to the positioning of the project settings links: 
#2307 
#2314 
- Made affix adjustment on resize more robust
- Added proper css for positioning in XS mode
- Added proper css for positioning when scrolling below the overall footer of OSF
None. Checked in Chrome, Safari, Firefox.
> Fix project settings page sidebar link positioning

- website/mails.py
- website/profile/views.py
- website/routes.py
- website/settings/defaults.py
- website/static/js/accountSettings.js
- website/static/js/oop.js
- website/static/js/pages/profile-account-settings-page.js
- website/templates/emails/support_request.txt.mako
- website/templates/profile/account.mako
This stubs the UI for exporting and deactivating user accounts.
Be sure to check/revise the language used in `website/static/js/accountSettings.js`.
> [feature] Add UI for account export & deactivation

- website/addons/osfstorage/model.py
- website/project/views/node.py
- website/static/css/iconmap.css
- website/static/js/iconmap.js
- website/static/js/nodeControl.js
- website/static/js/projectorganizer.js
- website/static/js/registerNode.js
- website/templates/project/project.mako
- website/templates/project/registrations.mako
- Clean up some stylistic issues with iconography.
- Bugfix an issue when deleting subprojects
- Update PO icons to make registrations grayed-out versions (even for projects)
- Move icon from project title to next to category
- Make PO info icon smaller and have cursor: pointer
- Check if can_view parent before redirect when deleting
- Change registration language as per @lbanner's request
None
> [Ready for Review] More noderefactor cleanup

- website/static/js/projectorganizer.js
Andy found a bug with cyclic pointer auto-expansion in projectorganizer. This PR attempts to prevent that expansion front-end. 
Check for item.data.isPointer in _expandStateLoad
None
> Block pointer auto-expansion frontend

- website/static/js/projectorganizer.js
- website/util/rubeus.py
PO was not auto expanding due to both server side and JS bugs
Fix the bugs. 
If a node is a pointer, but a child of the dashboard node, use the saved expand state. 
In JS, don't check if is Pointer.
It works now :dancer:
> Fix issues with ProjectOrganizer not auto-expanding

- framework/auth/core.py
- framework/sessions/utils.py
- tests/factories.py
- tests/framework_tests/test_sessions.py
- tests/models/test_user.py
Fixes the following bugs discovered by the QA team:
* [Alternate email the same for two users](https://trello.com/c/SOjOgLuu/28-alternate-email-the-same-for-two-users) (h/t @caileyfitz)
* [Merged user remains logged in](https://trello.com/c/TcyWVySj/26-merged-user-remains-logged-in) (h/t @caileyfitz)
> [bugfix] Misc. bugfixes for user merging

- website/templates/project/contributors.mako
<b>Purpose</b>
Change the create view-only link button to make it consistent with add contributor button according to the usability review.
<b>Change</b>
before change
after change:
> change the create view-only link button

- tests/test_models.py
- website/project/model.py
<b>Purpose</b>
Fix the problem that read permission contributor can't comment on a project. Solves https://github.com/CenterForOpenScience/osf.io/issues/2684
> fix the read permission contributor can't comment

- website/templates/project/project.mako
At some point `date registered` was removed from the project templates. This lead to some confusion about if parent projects were affecting logs of child registrations (they don't). Changes attempt to resolve any potential confusion for users viewing registrations
Re-added `date registered` to template, made `date parent project created`
more explicit, and removed date_modified for registrations per discussion.
None
Closes-issue: #1342
> [hotfix] Fix confusing timestamps for registration templates

- website/addons/github/static/githubFangornConfig.js
Fixes minor bug where github shows branch name as undefined on load.
Checks if branch is set (this can be updated by user during use) if not uses default branch.
None.
> Fix branch name title in Github printing undefined 

- website/static/js/projectorganizer.js
Fixes a bug where rename input would not let user change the name
Added a method where the content of value is received from the input element in a roundabout binding way to get around mithril component redrawing. 
Involves all input related toolbar items in Fangorn/Project organizer implementations but should be working fine.
> Fix input binding to work with component

- website/addons/dataverse/static/dataverseFangornConfig.js
- website/addons/github/static/githubFangornConfig.js
- website/static/css/fangorn.css
- website/static/css/projectorganizer.css
- website/static/js/fangorn.js
- website/static/js/projectorganizer.js
Following from our community meeting these changes turn links into single clicks and Project Organizer links into actual a tag links; plus some housecleaning around these changes. 
@GaryKriebel these include the changes we talked about.
- Increase top bottom padding
- Add underline to file name and 
- Make any other than file name not a link (make it consistent across PO and Files) 
- Single click to go to file or project. 
- Single command click to go to file and project
- Change help text to reflect this change 
- Add borders to columns to denote resize grab location 
- Change cancel upload button color to red
None.
> [Fix] Changes link structure to use single clicks

- package.json
- website/static/js/fangorn.js
Runs normal scrolling instead of virtual scrolling in treebeard with less than 1000 elements. 
Treebeard commit had significant changes here:
Should be backwards compatible.
Tested with modals but other issues may come up. Needs QA
> Fixes treebeard scrolling with natural scroll option 

- website/addons/dataverse/static/dataverseFangornConfig.js
- website/addons/github/static/githubFangornConfig.js
- website/static/js/fileViewTreebeard.js
Fixes Trello card about add on not maintaining highlight in file detail view page. 
https://trello.com/c/hYinPmmF
Add the item to multipleselect to make sure redrawings would occur because of onscroll highlightmultiselect function
None
> Fix Addon highlighting current item in file view [skip ci]

- website/static/js/fangorn.js
Following scrolling changes the go to file was broken. This fixes to make sure single file view; detail page works. 
Remove unnecessary code from before scrollign changes
Doesn't seem to be any.
> [Fix] Fix for scrolling to file 

- website/static/js/fangorn.js
- website/util/rubeus.py
Fixes the Trello card : https://trello.com/c/BkwPYEsL
Added to rubeus ndoeType value
Check against this value in fangorn to see if delete multiple button should be shown.
None.
> [Fix] Add node type to rubeus to omit components from multi delete [skip ci]

- website/static/js/fangorn.js
- website/static/js/projectorganizer.js
Fixes this Trello issue: https://trello.com/c/WmZHjGcP
Only run resetfilter when toolbar is returning from Search
None.
> [Fix] Run reset filter only when returning from search [skip ci]

- website/project/views/node.py
- website/templates/project/settings.mako
<b>Purpose</b>
Give write permission contributor the power to change the category of a project. Also solves https://github.com/CenterForOpenScience/osf.io/issues/2665
<b>Change</b>
What a write permission contributor will see on the settings page:
> enable write permission contributor to change category of a project

- website/static/js/fileViewTreebeard.js
Fixes the regression bug reported in Trello: https://trello.com/c/sg9bu0Hx
Surround old showTotal code with check to see if natural scroll limit is on so that showTotal doesn't get set if Treebeard is using natural scroll.
None.
> [Hotfix] Fix unnecessary setting of showTotal with natural scrolling

- tests/test_views.py
- website/project/model.py
- website/project/views/log.py
<b>Purpose</b>
Fix the problem that logs on old private component will show up to ppl who doesn't have right to view that on parent project. Solves https://github.com/CenterForOpenScience/osf.io/issues/2745
> fix the problem that old private component logs shown up

- package.json
- website/static/js/fangorn.js
After the failure of the high number natural scroll it seemed worthwhile to try to fix actual virtual scrolling. It turns out this is related to wrong assignment of top margin in Treebeard. This PR updates OSF to use the latest TB commit and use it's default natural scroll limit number which is 50.
https://github.com/caneruguz/treebeard/commit/fdeb82d4937c4ecd72b85e10c361fadd33079713
Package.json version for TB is changed
NaturalScrollLimit option is removed from fangorn.
None. 
@sloria
> [Fix] [Treebeard] Smooth scrolling in TB

- website/static/js/nodeControl.js
- website/templates/project/project.mako
<b>Purpose</b>
Fix the problem that admin contributor on parent project can't watch the private component or add the private component to their project organizor. Solves https://github.com/CenterForOpenScience/osf.io/issues/2715.
<b>Changes</b>
After change:
> allow admin on parent project to watch the private component

- framework/auth/core.py
- tests/test_views.py
- website/project/model.py
- website/project/views/contributor.py
- website/static/js/accountClaimer.js
* store `claimer_email` separate from `email` when claiming accounts, `email` being provided explicitly by the `referrer`
* allow user account claiming from `view_only` links
* properly email claimers w/ a direct invitation/sign up link when they enter the same `claimer_email` the `referrer` entered
> [hotfix] claiming users

- website/static/css/fangorn.css
- website/static/js/fangorn.js
- website/static/js/pages/project-dashboard-page.js
As files are uploaded to OSF the existing feedback system had a few problems
- It's application state for uploads was not reliable (it was switching back to pending after success)
- The alignment was off between notification and native row drawing
- Placement of cancel buttons for upload was not on the right. 
This PR aims to bring a better UI to the upload experience by setting proper states, showing a progress bar and improving the cancel upload button while maintaining responsive design.
- Upload html is now native to the resolverow function, i.e. not using notification for upload. 
- Template for upload rows is separated to be reused so the code is not repeated
- upload state is set where it should be
- Progress bar is added
Project Dashboard is properly taken care of and upload is …
> [Feature] Improve upload row feedback

- tests/factories.py
- tests/models/test_addon_settings.py
- website/addons/base/__init__.py
This code is ugly, but it should do the trick for now.  Consider this as almost a hotfix - test it in QA, and if it works :shipit:.
I'll write tests for it, then refactor it early next week and have it ready for the next release.
> [feature] Fix bug in OAuth addon merging where credentials were not merged

- README.md
With @billyhunt , some proposed revisions to the installation docs:
1. Add a prerequisites section to separate out things that the setup script does not install. (like XCode command line tools)
2. Add a table of contents to make it easier to navigate
3. Better reflect our actual dev practices: add more information on usage of invoke, and remove some redundant steps (commands to run things that we normally handle with invoke)
4. In the run requirements, provide a little more separation between the everyday commands and requirements for special features.
Suggestions welcome. The goal was to tighten this up, removing some redundancy and providing a clearer path for those following the instructions in order. Things done frequently should be easy to find.
> Revisions to README.md install docs

- website/static/vendor/knockout-sortable/knockout-sortable.js
- website/templates/include/profile/jobs.mako
- website/templates/include/profile/schools.mako
This resolves issue #1506 . The last and first position reordering for the employment and education tag in Profile Information was non-functional.
The the default setting for tolerance of a sortable instance is intersect (elements must overlap more than 50%). That amount of overlap was not possible for the first and last items of the list. Set tolerance to pointer so that the overlap of elements is determined by where the mouse is located on the screen.
Reference: [jQuery UI API] (http://api.jqueryui.com/sortable/#option-tolerance)
The entries are reordered based off of any overlap of the pointer and another entry.
> [Feature Fix] Profile settings reorder fix

- website/static/vendor/knockout-sortable/knockout-sortable.js
This is related to PR #2811. The merge included a change to a third party file (knockout-sortable.js).
The addition to the third party file was removed.
There should be no side effects.
> Revert third party file to original (knockout-sortable.js)

- website/static/css/site.css
- website/templates/project/modal_add_pointer.mako
Closes #2778. Originally, if a project name was very long, the row that contained the name in the Added section would overflow and leave the modal. 
This change adds proper word breaking so that the rows always stay within their boundaries.
All words will be broken at arbitrary points, including author names. May need discussion about redesign of modal to accommodate readability.
> [Feature Fix]Add Link clipping over modal when Project name too long

- website/templates/nav.mako
This resolves issue #2517. 1Password was auto-filling the username and password into the wrong fields.
Added aria-label to the login username and login password field. 1Password uses labels to determine which fields to fill.
There are no anticipated side-effects.
> [Feature Fix] 1Password autofill fix

- scripts/analytics/benchmarks.py
<b>Purpose</b>
Update the daily user count script. Related to https://github.com/CenterForOpenScience/osf.io/issues/2853
<b>Change</b>
Add query to exclude disabled user and correct the query for merged user.
<b>Side Effect</b>
There are no side effect of this pr but it does not fix the main problem of https://github.com/CenterForOpenScience/osf.io/issues/2853. That need a elastic search index reset on production and might need to run migrate user on production as well.
> modify the querry to return the right number of user

- website/addons/github/static/github-node-cfg.js
In IE's default setting, `window.location.reload()` will load a new page and start at the top of the page. After users import token, they have to scroll down the page and then they could come back to the config setting part. In this fix, it will firstly set the scroll location with hash tag before reloading the page. 
Resolved #2690 
1) Set hash tag before reloading -- `window.location.hash = "#configureAddonsAnchor";`
2) Add IE browser recognition code. Only when user uses IE will hash tag be set.
None. Set hash and only limit to IE browser
Among those commits, I also tried to use cookie to record the scroll position before reloading. However, it is much more complicated and has potential security risk.  Hashtag is easier way and hopefully could be applied to solve the similar page jump …
> [ Feature Fix] Import token page jump

- package.json
- website/static/js/fangorn.js
Fangorn file sorting alphabetically was broken because of a change to TB and moving, renaming was causing irregular behavior. This PR fixes the sorting of files and makes it more consistent across different user behaviors. 
- Fixed the fangornorderFolder function and placed it in appropriate locations in the doItem function
- Fixed pertinent treebeard issues (for instance sort state was resetting at every redraw). Check the treebeard commits for details. 
Sorting is generally harmless and should not cause any other issues but this addition needs testing.
> [Fixes] Fangorn sorting fixes with move and rename

- website/static/js/fangorn.js
This resolves issue #2263 and issue #2761. The addon icons (i.e. dropbox logo) were able to be clicked on and dragged.
The fangorn.js returns a span instead of an img
The icons do not act like pictures.
> [feature fix] Fix draggable addon icons 

- website/project/metadata/brandt-prereg-1.json
Purpose
----------
Closes #2679.  The question was referencing another question by number but the questions were not numbered.
Changes
------------
Used http://www.sciencedirect.com/science/article/pii/S0022103113001819 as a reference to determine that, in addition to their being a number where there shouldn't be, it was referencing the wrong question.  This was remedied by changing the wording to say "the previous question" instead of using a number.
Side Effects
--------------
There should be no side effects from this since the only thing that changed was text.
> [hold] [Feature] Fixed wording in one of the pre-registration questions

- website/static/css/site.css
- website/static/js/navbarControl.js
- website/templates/search_bar.mako
**Purpose**
Currently, the search bar place holder in IE can't not be shown. Because the default setting for IE is that when input is focused, then it will clear all the place holder. Resolves the #2248 .
**Changes**
I consulted other mainstream websites and found most of them had the same problem. But dropbox's sign-in page doesn't have this issue because it doesn't use placeholder from HTML5. Instead, it uses label tag to achieve the same goal.
So borrowing the same idea, I apply label tag and add the corresponding javascript and css code. 
1. Add search-label-placeholder class into site.css
2. Add label tag at the end of search input tag and assign unique ids to search input and label tags.
3. Add control javascript at the end of search_bar.mako
The same placeholder …
> [Feature Fix] IE search bar placeholder not visible 

- website/templates/project/project_header.mako
Update project header template with correct permissions for who sees the settings page
All non-registrations should be viewable to any user with read access.
All non-retracted registrations should be viewable to any user with
admin access.
n/a
> Update who sees project Settings page

- website/static/css/site.css
- website/templates/project/project.mako
<b>Purpose</b>
Add a button on project overview page to let user know where to go to manage contributor.
<b>Changes</b>
After change:
> add a button to redirect user to sharing page

- website/static/js/onboarder.js
Purpose
-----------
When a user is on the dashboard and they decide to upload a file, it is easy to believe just dragging the file has uploaded it. In reality, the user must select a project and hit upload. If a user has started this process and tries to navigate away from the dashboard before completing it, a popup had been added to warn them that their changes will not be saved and gives them an option to stay on the page and finish.
Closes Issue CenterForOpenScience/openscienceframework.org#1518
Changes
------------
Adds a popup if the user tries to navigate away from the dashboard with an unfinished upload.
Side Effects
None
> [Feature Fix] Add user warning if navigate away after adding files for upload

- website/static/css/site.css
- website/templates/project/modal_add_pointer.mako
QA brought up Add Link's modal is breaking last names into single character lines if Project name is too long. This PR fixes this problem.
Took out break-word: break-all css in site.css. Added modal-lg to class to allow for more space in general.
There should be no side effects as this is a simple bug fix.
> [Feature Fix]Add link modal clipping names

- website/templates/project/project.mako
Very simple fix to hide empty component box when user does not have write permissions.
https://github.com/CenterForOpenScience/osf.io/issues/2892
Is this feature desired?
> Hide empty component box when user doesn't have write permissions

- website/static/js/fangorn.js
Fixes this bug on production: https://github.com/CenterForOpenScience/osf.io/issues/2845
The Treebeard default value of natural scroll is at 50 items. Fangorn did not override this. However if at some point the row count went below 50 (i.e. because folders were closed) the required scroll refresh was not taking place because the visible items were now below 50. 
Changed the natural scroll setting to 0 to make sure that scroll drawing will always occur. 
Should not be any. Now it relies completely on the virtual scrolling and it seems to be working well. 
@sloria @lbanner
> [Hotfix] [High Priority]  Reduce natural scroll to 0 to avoid side effects in fangorn

- website/profile/views.py
- website/project/views/node.py
- website/templates/util/render_node.mako
- website/templates/util/render_nodes.mako
- website/views.py
This PR replaces #2316, by @huangginny. Original text below:
----------
Purpose
--------------------
Closes #1249 
Often, components from different projects have the same title (e.g. "Study Materials" or "Data"). They are listed in your public profile without providing the project title for context, so components with the same name are indistinguishable from each other.
Changes
---------------------
- Before
- After
Side effects
----------------------
I refactored <code>get_public_components</code> in <code>website/profile/views.py</code> so that when this method is called, the summary of node that is rendered always have the path underneath.
> [Feature] Add breadcrumbs to public components in user profile

- tasks.py
The syntax checker in `tasks.py` was not running currently, because the boolean flag (`flake`) overwrote the function name (`flake`) in the function scope.
With this change, it is now possible to run syntax checks in both `inv test --syntax` and `inv test --all`. This should make it easier to catch errors that would otherwise only be noticed in Travis CI failures.
The `flake` flag is renamed to `syntax` for clarity. It can now be used without having to run all unit tests.
> [feature fix] Fix broken syntax checker in "invoke test_all"

- framework/addons/data/addons.json
Fixes https://github.com/CenterForOpenScience/osf.io/issues/2960
by replacing the permissions line in the modal:
with
Making an OSF project public or private is independent of making a Dataverse study public or private. The OSF allows you to release the latest draft version of a Dataverse dataset.
> Updating permissions text for Dataverse.

- scripts/embargo_registrations.py
- scripts/retract_registrations.py
- scripts/tests/test_embargo_registrations.py
- scripts/tests/test_retract_registrations.py
- tests/test_models.py
- tests/test_registration_embargoes.py
- tests/test_registration_retractions.py
- website/project/model.py
Previously, logs were added to a retraction or embargoes respective registration. A behavior change was requested to move the log up to the project the registration was created from. 
Logging was moved to the project level and updated tests accordingly.
`Node#set_privacy` was not logging actions, updated it and tests accordingly.
N/A
Currently, tests will fail due to a known caching error within Modular ODM. Michael and Lyndsy are aware.
> Move Retraction/Embargo logs to parent project

- website/static/js/osfHelpers.js
This PR is to solve the issue that on firefox it shows the wrong file modified date. 
Resolved #2972 
Different from all the other browsers, Firefox assumes  the input(`DateString`) of  `new Date(DateString)` is the date based on local time zone while all the other browsers treat the input based on UTC time zone. In our case, the input date string is UTC time-zone. Therefore, we need manually add offset  when displaying on firefox, by adding ''Z' at the end of date string. The letter Z ("Zulu") indicates  Coordinated Universal Time (see UTC±00:00).
So in summary, the PR code is to add 'Z' at the end of date time string. The action is only limited to Firefox. Since it changes the osfHelper.js, the solution will apply all the hidden date-shown problems on Firefox.
Reference material …
> [Feature Fix]  [Firefox] Fix the incorrect time shown on file version table 

- tests/test_elastic.py
- website/search/elastic_search.py
Currently, when adding a contributor to a project, searching for a name with special characters such as accents yields no results, and logs an error in the console. This PR resolves this issue causing searches to return the relevant users.
Given a query with special characters, normalizes each word in that query converting all characters to ascii prior to passing the query to elasticsearch.
Closes Issue https://github.com/CenterForOpenScience/osf.io/issues/2460(https://github.com/CenterForOpenScience/osf.io/issues/2460)
> [feature fix]Feature/allow special characters in contributor search

- website/search/share_search.py
Purpose
-----------
When a query is posted at the SHARE API that contains an aggregation and the url parameter ```count``` is set to True, we throw a 500 because aggregations aren't allowed in count queries.
Changes
------------
If a count query is being made, I remove aggregations from it so that the document count for that query can still be correctly returned.
Side-effects
I don't think any side-effects are really possible from this PR.
> Remove aggregations from count query before executing it

- website/static/js/fangorn.js
- website/static/js/pages/project-dashboard-page.js
- website/static/js/projectorganizer.js
This fixes issues created by PR #2871. The certificate and collection icons on the project organizer are incorrect. Private component icons appear on the file grid.
`resolveIconView` in *fangorn.js* is revamped to handle requests from the project organizer and the file grid. The change in `resolveIconView` eradicates the need for `_poResolveIcon` in *projectorganizer.js*. The project organizer now calls `resolveIconView` directly.
In the file grid, the private component icon is used. In the project organizer, the dashboard icon, 'all my registrations' and 'all my project icons' display properly.
Fix:
Problem:
> [Feature Fix] Fix resolve icon view

- tests/test_share.py
- website/search/share_search.py
Purpose
----------
I made a mistake with python truthiness, keys that need to be deleted that have falsey values are skipped.
Changes
-----------
Explicitly check that the values are not None
Side-effects
None
> Fix count query checks for SHARE 

- framework/auth/core.py
Using UserFactory to create a user with a name containing non-ascii characters would throw a UnicodeEncodeError.
User \__str\__ returns the user's name encoded as ascii with non-ascii characters replaced with '?'.
> [Feature Fix] Fix test_elastic error

- website/project/model.py
- website/static/js/osfHelpers.js
- website/templates/project/contributors.mako
This resolves issue #2971. The icons that are displayed on the sharing page under View-only Links are outdated.
This requires the custom binding called `getIcon` defined in *osfHelpers.js* from PR #2953. The category of the node is added to what is returned by `to_json` in *model.py*. This is necessary so that the category can be given to `getIcon` in *contributors.mako*. The old image code has been taken out of *model.py*.
Under View-only Links on the project sharing page, the updated icon is displayed next to the title of the component. There is an added field to what is returned by `to_json`.
Fix:
> [Feature Fix] Update to view link icons

- website/static/js/projectCreator.js
Solve the Bug found during the testing for pull request  #2969. It is to render the special characters correctly in template dropdown menu
Apply the decode method to the title before it display. Similar as #2969. 
* Before the change:
* After the change:
None
> [Feature Fix] Decode the title in template dropdown menu

- website/static/js/osfHelpers.js
- website/static/js/tests/osfHelpers.test.js
Per @sloria feedback in #3012, reworked JS `apiV2Url` helper function to use URI.js. This will encourage consistent URL construction across various OSF libraries.
Needed a small workaround to join paths with trailing + leading slashes (eg `http://osf.io/api/v2/` + `/users/4urxt`), as otherwise encountered double slashes in result. Open to feedback if there's a more elegant way.
> Rework apiv2url to use uri.js

- tests/test_elastic.py
- website/search/elastic_search.py
- website/search/util.py
- website/static/js/search.js
Currently searches do not place relevant projects at the top of the results. Projects with titles similar to a given query are not at the top of the results page. Also, search results for a query with a singular word are different if the query has a query with a plural word (ex 'Horse' has different results than 'Horses'). This PR improves the apparent relevance of search results, and fixes plural and singular words yielding different results. 
resolves https://github.com/CenterForOpenScience/osf.io/issues/2552
* Titles weight in relevance scoring increased to 2
* Descriptions weight in relevance scoring increased to 1.2
* Use phrase searching by default
* The 'english analyzer' is used for titles and descriptions which fixes the plural/singular issue
Use of english analyzer may affect …
> [Feature Fix]Improve relevance of search results

- website/templates/public/pages/help/addons/dataverse.mako
Studies are now called datasets
Remove reference to only public datasets as now drafts can be linked
> hotfix: update dataverse to reflect changes in 4.0

- website/static/js/projectCreator.js
- website/templates/components/dashboard_templates.mako
The change will make template selection shown on IE when creating project on dashboard.  Resolve #1504 .
The change is quit simple. It only replace id selector -`#createNodeTemplates` with class selector-`.select-template`.
The change is very small, but the reason is very subtle. 
The selection bar is based on JQuery Library -[Select2](https://select2.github.io/). It needs to select input DOM and insert a new div DOM above that input DOM. In our case, input DOM is defined in mako template file with the ID -`#createNodeTemplates`. In IE, it will search unique ID starting from template. So it will insert the new DOM in template, which will not be shown. However, the other browsers will search unique ID from the shown HTML and consequently the inserted DOM will be shown. 
In order to getting …
> [Feature Fix] IE template dropdown not shown 

- tests/test_models.py
- website/project/model.py
This allows admins to mass update permissions on child nodes for contributors they've readded to the parent node of.
Closes issue https://github.com/CenterForOpenScience/osf.io/issues/2675
Now when someone is added to a node they're already on there permission updates.
> Issue #2675 [staging & production] Can't mass-update permissions on child nodes

- website/static/js/fangorn.js
Makes sure 'download as zip' doesn't button appear when there are no files. Closes #3018.
Just adds condition to make sure OSF storage isn't empty.
<h1> Side effects </h1>
> Makes sure 'download as zip' doesn't button appear when there are no files.

- website/static/css/site.css
- website/static/js/citationGrid.js
Purpose
-
After PR https://github.com/CenterForOpenScience/osf.io/pull/2950, QA noted that citations were not working with italics.  I also noted that they were not displaying this way in the widget.  This PR seeks to address both of these issues.
Changes
-
Previously, we were requesting the citations from citeproc.js in 'text' format, hence them displaying with no styling.  Now we request in 'html' format to preserve styling.  This meant also updating the mithril call that renders the rows in order to print it as html as opposed to printing the html as text.  Lastly (for this part), CSS styling had to be added so that the returned div would have 'display: inline' or else it would not show up.
For the copying aspect, we were previously passing the third party system plain text to copy, …
> [Feature fix] Mendeley properly displays/copies italics

- website/static/js/fangorn.js
This fixes issues created by PR #2953 . The collection icons on the project organizer are incorrect -- they are displayed as project icons. 
Some logic was added to `resolveIconView` in *fangorn.js* so that collection icons are displayed on the project organizer.
In the project organizer, the collection icons appear correctly.
Fix:
Problem:
> [Feature Fix] Po collection icon fix

- website/language.py
- website/settings/defaults.py
- website/static/js/pages/register_1-page.js
- website/static/js/registerNode.js
- website/static/js/registrationEmbargo.js
- website/static/js/tests/registrationEmbargo.test.js
The community has requested that we increase the maximum date for an Embargo from one year to four years.
Change the default setting from one to four years, adjust tests, and update website language accordingly.
None.
Closes-issue: #3094
> [feature] Increase Embargo max date to four years

- website/static/js/citationGrid.js
Regression was introduced in 7d8e492c4838daca0e15ef082678ea62c407607f.
The assumption was made that all items in the returned dataset would
have an item[data][csl] value - but folders do not. To resolve, I've
added a conditional that first checks for the existence of the key, and
falls back to the previous method of action.
> [hotfix] Fix regression preventing subfolder expansion in citationgrids.

- scripts/migration/migrate_none_as_email_verification.py
- scripts/tests/test_migrate_none_as_email_verification.py
* Create a migration script so that users with email_verifications that are `None` are changed to an empty dict, as is the new default.
* Closes #3087 
* Add script to `scripts/migration/migrate_none_as_email_verification.py`
> Add migration script for users with None as email_verifications

- README.md
Add information on running CAS and fakeCAS to documentation.
Solves half of https://github.com/CenterForOpenScience/osf.io/issues/2929
> [documentation] Add running CAS to documentation

- website/addons/github/views/repos.py
Purpose
-----------
Fixes #2976 
Now when a user creates a new github repository through the OSF, it's initialized with a master branch that contains a readme.md file. This way, a user can upload files directly to the new repository without having to commit to it first. 
Changes
------------
Set auto_init=True when creating a new github repo.
> [hotfix] Initialize github repositories created through the OSF

- api/base/utils.py
- framework/auth/core.py
Addresses the first part of #3049.
Due to a circular import, some code in the `api.base.utils` and `website.util` modules had to be repeated.
This PR will:
1. Remove the circular dependency by moving one import
2. Bring helper functions up to spec with new helpers such as `api_v2_url`.
Close a circular import issue, enabling future use of website utils in api.
Modify the absolute_reverse function (used for API links) to apply the correct prefix in production.
This might bear some investigating in production- as discussed with @brianjgeiger , I'm a bit surprised that URLs look ok in production, even though this fix *should* offer improvements.
> [feature-fix] Circular import in api utils

- website/templates/project/retracted_registration.mako
Registration supplement data should not be accessible for retracted registrations.
Convert portion of template related to registration supplement from link to text.
None.
Closes-issue: https://trello.com/c/JKXdsj8G/50-retracted-registration-link-to-registration-supplement-information-gives-bad-request
> [feature fix] Registration supplement should not be link

- website/language.py
Update the user facing registration prompt.
Closes-issue: https://trello.com/c/VahVMTC4/61-incorrect-information-about-registrations-on-initial-registration-dropdown-page
> [feature fix] Registration prompt was out of date

- website/templates/project/project_header.mako
Make the pending embargo warning label more informative.
Closes-issue: https://trello.com/c/UvdsHEh0/58-pending-embargo-label-next-to-embargoed-registration-and-registration-is-publicly-viewable
> [feature fix] Update pending embargo label

- tests/test_registration_embargoes.py
- website/project/model.py
- website/project/views/register.py
Ensure that all pending embargoes are private rather than inherit privacy settings from the registrations parent project
An embargo or its descendants may have addons with set_privacy callbacks that can't be ignored. As a result, a logging parameter to `Node#set_privacy` , defaulting to `True`, but can be disabled for edge cases such as this.
Closes-issue: https://trello.com/c/2lLlJ76j/62-pending-embargoes-inherit-privacy-from-project-when-they-should-default-to-being-private
> [feature fix] Ensure public projects create private pending embargoes

- tests/test_registration_embargoes.py
- tests/test_registration_retractions.py
- website/archiver/listeners.py
- website/project/model.py
Unclaimed accounts can be given admin rights to projects and registrations. As a result, they were also being assigned approval/disapproval tokens for retractions and embargoes.
Unclaimed accounts are now ignored and will neither be assigned approval/disapproval tokens nor sent emails.
N/A
Closes-issue: https://trello.com/c/sXQJW73i/68-unconfirmed-contributors-receive-emails
> [feature fix] Unclaimed admin accounts should not get tokens

- website/templates/emails/pending_embargo_admin.txt.mako
- website/templates/emails/pending_embargo_non_admin.txt.mako
- website/templates/emails/pending_retraction_admin.txt.mako
- website/templates/emails/pending_retraction_non_admin.txt.mako
Fix typos in retraction and embargo emails.
Closes-issue: https://trello.com/c/FTISFUZZ/71-spelling-error-in-registration-pending-email-for-embargo
> [feature fix] Fix typos in embargo/retraction emails

- website/templates/public/pages/help/registrations.mako
Update `Registrations` section of the Getting Started page
1. Remove the outdated video.
2. Update language.
None.
Closes-issue: https://trello.com/c/hCSeRcgL/64-registrations-video-should-be-removed-from-getting-started-page
> [feature fix] Update `Regstrations` section of Getting Started page

- website/static/js/nodeControl.js
Update language to match new four year max embargo period.
Closes-issue: https://trello.com/c/dyXQKA8m/72-warning-modal-language-needs-to-change
> [feature fix] Fix typo in registration warning modal

- main.py
- tasks.py
- tests/test_models.py
- website/addons/osfstorage/model.py
- website/app.py
- website/project/model.py
- website/settings/defaults.py
- website/util/__init__.py
Run Flask in multithreaded mode when in debug mode to avoid having to run multiple osf servers for waterbutler
> [Feature] No more dual OSF servers

- tests/test_elastic.py
- website/search/elastic_search.py
- website/search/search.py
- website/search_migration/migrate.py
Currently tests involving search hit the 'website' index. This PR has the elastic search tests hit a test index. 
This closes issue  https://github.com/CenterForOpenScience/osf.io/issues/1228.
* test_elastic.py sets the default index to a test index.
* In functions where 'index' is an argument, moved assigning of default index from the function header to the function body.
> [Feature] Use test index when testing search.

- website/addons/dataverse/static/dataverseFangornConfig.js
Purpose: 
------------
Partially addresses #2369. The dataverse drop-down for selecting the study version is cut-off with long study names (or if the grid is narrow) because it is still in-line: 
Changes: 
------------
Move the dataverse version select box to the treebeard toolbar along with other action buttons. Also include the current version after the study title to remain consistent with github:
> [feature] Move Dataverse version select dropdown into action toolbar

- tests/test_archiver.py
- tests/test_models.py
- website/archiver/listeners.py
- website/archiver/model.py
- website/archiver/tasks.py
- website/project/model.py
- website/project/views/register.py
- only add registrations to search after archive success
- update ES when retracting registrations
resolves:
- https://trello.com/c/3F9kmNmk/85-no-distinction-of-retracted-registrations-in-search-results
- https://trello.com/c/2pc5ZT9S/91-registration-stuck-on-archiving-can-be-seen-via-the-search-bar
- https://trello.com/c/T4SORuwV/78-making-existing-private-registration-public-does-not-make-all-components-in-that-registration-public
> [RFR] Archiver fixes

- website/templates/project/project.mako
Solve the button jump when using tooltip. See gif below:
Add the body as container, then it will not be influenced by other.
> #### [Popovers in button groups and input groups require special setting](http://getbootstrap.com/javascript/#popovers)
> When using popovers on elements within a `.btn-group` or an `.input-group`, you'll have to specify the option `container: 'body'` (documented below) to avoid unwanted side effects (such as the element growing wider and/or losing its rounded corners when the popover is triggered).
More details see a github discussion -- [link](https://github.com/twbs/bootstrap/pull/6378)
After adding `data-container="body"` to the button with tooltip, see the gif below:
None. It only sets the container of the tooltip button. I already tested it in four major …
> disable button jump when tooltip

- website/addons/dataverse/static/dataverseFangornConfig.js
Purpose
-------------
Closes #3186 
The delete button for draft dataverse files was not showing in the files grid toolbar, even though it is possible to delete those files through the file detail page. 
Changes
------------
Replaced the outdated `item.data.state` with `item.data.version` so that the check for whether the file is in a draft dataverse is correct. 
The delete button now shows up in the files grid toolbar:
> [hotfix] Include delete button in files tab toolbar for draft dataverse files 

- website/static/js/fangorn.js
The file tree's information panel did not include how to copy files. This PR adds instructions for copying files to this information.
This closes https://github.com/CenterForOpenScience/osf.io/issues/3182.
Added instructions for coping files to the file tree's information panel.
> [Feature Fix] Include how to copy file in file organizer information

- website/static/js/fangorn.js
<b>Purpose</b>
To fix a typo in fangorn.js that was causing various problems, notably erring when trying to drag-move files from folder to folder. 
<b>Side Effects:</b>
None 
Before: 
After:
> Fix fangorn.js indexOf typo

- website/static/js/registrationRetraction.js
- website/static/js/tests/registrationRetraction.test.js
Fixes https://trello.com/c/0TufdPXI/101-html-characters-in-title-are-escaped-in-retractions-confirmation-modal
> HTML decode entities in project titles

- package.json
- tasks.py
Encourages local testers to run jshint per new Travis requirements in #3107, before pushing to github.
- Add jshint to the list of packages that node installs automatically.
- Add a call to jshint (as specified by `.travis.yml`) to the syntax checks called by `inv test --syntax`.
- Consolidated two highly redundant commands (`inv test` and `inv test_all`) into one command with a flag. This will probably inconvenience *someone*...
- Very trivial adjustments for PEP8.
> [feature] Add jshint as dependency and invoke task.

- website/static/js/share/footer.js
- website/static/js/share/utils.js
Purpose
-----------
When using SHARE, if you hide the footer by clicking it or performing a query, and then search with an empty bar, and then search with a real query again, the footer will be visible at the same time as the search bar. This looks really weird. Also, the webkit columns don't display properly on chrome and safari.
Changes
-------------
Hide the footer on query, and make the columns behave as they should.
> [hotfix] [SHARE] Prevents the footer from popping back up again as the query changes

- website/static/js/osfHelpers.js
- website/static/js/tests/osfHelpers.test.js
Fixes #3172 #3176 
Purpose
-----------
Make it so that osfHelpers.FormattableDate can accept ISO 8601 formatted date strings, rather than just date-time strings, in Firefox
Changes
------------
No longer append "Z" to the date/time string in Firefox
Side-effects
I'm not sure why that "Z" is appended (locally on my firefox, the behavior is the same with or without the "Z"), but if there was a good reason for adding that then other places that display datetimes may be broken. Will try to find them.
> [hotfix] [SHARE]ish remove the bit of code responsible for appending Z to date/times when using Firefox

- website/static/js/pages/profile-settings-addons-page.js
- website/static/js/pages/project-settings-page.js
In our project and profile add-on setting pages, only when users click submit button, will the changes be saved. In case that users forget to submit, a confirmation page should be added when detecting there are unsubmitted add-on setting changes. 
Issues resolve -- #2155 
The basic idea is to bind [beforeunload event](http://www.w3schools.com/jsref/event_onbeforeunload.asp). Before unloading, detect whether there are changed settings. If yes, return a static warning message.
In our current style guide, it doesn't define the modal panel for confirmation.  So it doesn't follow the guideline for general modal panel.
> [Staging & Production] Add-on Configuring Confirmation confirm

- website/static/js/metadata_1.js
Part of a [JS cleanup](https://github.com/CenterForOpenScience/osf.io/commit/d9f8353fa89fdaef636fddd3059e05463c7ba381) PR lead to regression bug preventing registration viewmodel from loading.
Closes-Issue: https://trello.com/c/cLeQHpN9/12-registrations-page-broken-page-not-being-populated-correctly.
It might be a good idea to have someone with a stronger JS background review other changes in that PR
> [feature fix] JS Cleanup PR regression broke metadata viewmodel

- website/templates/project/modal_add_contributor.mako
When adding a contributor to a project, the language prompting the user to choose components that should also be affected was misleading. 
This closes https://github.com/CenterForOpenScience/osf.io/issues/3166
Changed text of prompt to *"Select any other components that you would like to apply these settings to."* from *"Would you like to add these contributor(s) to any children of the current component?"*.
> Update language used for adding contributors.

- website/profile/views.py
- website/project/views/node.py
Purpose
-----------
Closes #896 
Figshare was listed last in the user and project settings page for configuring addons: 
Changes
--------------
Sort lowercased addon names on user and project settings pages so that they show up in alphabetical order regardless of capitalization:
> [feature] Fix add-on order of appearance 

- tests/test_models.py
- tests/test_registration_retractions.py
- website/exceptions.py
- website/project/model.py
- website/project/views/node.py
- website/project/views/register.py
- website/templates/project/settings.mako
Make invalid token messages more verbose. Prompts user to ensure that they are logged into the correct account.
Closes-issue: https://trello.com/c/VTHIzy1i/87-embargo-approval-disapproval-link-error-mislabeled
> [feature fix] Make invalid token message more verbose

- tests/test_models.py
- tests/test_registration_retractions.py
- website/project/model.py
- website/project/views/node.py
- website/project/views/register.py
- website/templates/project/settings.mako
Desired behavior allows for children components or subprojects to be retracted **only ** when the parent registration is retracted.
Checks in place at the model and view level to ensure children cannot be retracted. Updated settings page to inform user and provide link to root registration's settings page.
None.
Closes-issue: https://trello.com/c/FGxAqxPi/112-retracted-components-of-registrations-that-have-not-been-retracted-show-up-in-project-organizer
> [feature fix] Disallow individual retraction of nested registration nodes

- website/addons/osfstorage/views.py
<b>Purpose</b>
Fix the problem that user name is showing up in file version table of OSF storage files under anonymous link . Combine with @chrisseto 's fix in waterbulter https://github.com/CenterForOpenScience/waterbutler/commit/5ee3305cf608e02001c5db2c032240ce9df021d6. Close https://github.com/CenterForOpenScience/osf.io/issues/3253.
> fix the osf side for anony osf file version

- website/addons/figshare/tests/test_models.py
One failing test was merged in with 0.40.0
Patch the figshare node settings model's archive_errors method, which makes API calls during Node#register_node. 
None
> Patch archive_errors during testing to prevent API calls

- website/addons/figshare/static/figshareFangornConfig.js
Purpose
-----------
Fixes #2183 
The delete button was showing up in the files grid toolbar for public figshare files that cannot be deleted. 
Changes
------------
Ensure public figshare files in a project do not have the delete button in the files toolbar unless they are part of a dataset that has multiple files.
> [hotfix] Fix figshare deleting public files

- website/static/js/projectCreator.js
- website/templates/components/dashboard_templates.mako
The create project button could be clicked multiple times which result in creating duplicated projects. In this PR, it will disable the button once getting an effective clicking. 
Resolve #3187
1) Add id for project create button
2) Disable the button when getting an effective submit
3) Enable the button when submit is failure.
None.
> [Feature Fix] Fix multiple clicks on create project button creates many of same project

- package.json
Purpose
-----------
Fixes #2843
Users could only shift + select a range of files that were visible in the grid (they could not select a file and then scroll to another file out of the view to highlight all of the files in between). 
Changes
------------
Use latest treebeard commit with the fix for shift + selecting files outside of the current view.
> [feature] Use tb version with fix for shift-selecting files

- website/addons/box/templates/log_templates.mako
<b>Purpose</b>
Fix the problem that box addon log are not displaying. Close https://github.com/CenterForOpenScience/osf.io/issues/3233.
<b>Changes</b>
Before: 
After:
> update box log template

- website/static/js/nodeControl.js
- website/static/js/registerNode.js
- website/templates/project/project.mako
Update registration prompts and behaviors to match introduction of retractions/embargoes into production.
- Update the preregistration prompt.
- Update the post-registration `make public` prompt.
- Remove `make public` functionality for registrations *pending an embargo*
N/A
Closes-issue: #3286 and #3287
> [Hotfix] Update registration prompts

- website/project/model.py
<b>Purpose</b>
Fix the datetime display on view-only link table. Close https://github.com/CenterForOpenScience/osf.io/issues/3232.
<b>Changes</b>
Currently:
after fix:
> [hotfix] fix the view_only_link_tiime

- framework/addons/data/addons.json
fixes #3276
I simply changed the strings for both to reflect the correct facts, as well as making the status "none" so that both strings will appear in red to reflect that they will not be registered whatsoever.
> [hotfix] Change Mendeley and Zotero add-on terms

- api/base/middleware.py
- api/base/settings/defaults.py
Refs #3163 
Allow Sentry to track errors that happen in the Django app used by APIv2.
Adds raven middleware to Django. Raven is already listed as a requirement for flask, so no new user installation is needed.
Applies a fix to ensure that Sentry catches problems when used with other error handling middleware, as [suggested](http://raven.readthedocs.org/en/latest/integrations/django.html#error-handling-middleware) by the Sentry docs.
Not sure how to test this locally, since I don't have the SENTRY_DSN keys needed to send actual data to the server.
Feedback on more granular reporting options would also be welcome. It would be nice if we could filter API/django errors out from the OSF/flask errors in a clear way. @brianjgeiger ?
> [feature] Enable sentry logging for APIv2

- website/templates/emails/archive_success.html.mako
Bold project titles in registration success email. close issue #3304.
Puts `<b>` tag on project title.
None.
> [feature] Bold project title in registration success email

- tests/test_models.py
- website/project/model.py
- website/project/views/node.py
- website/static/js/nodeControl.js
- website/static/js/project.js
- website/templates/project/modal_add_component.mako
Purpose
-------------------------
Currently when making a new component on the osf a modal will pop up and allow you to enter a title as long as you wish, but if your title is longer than 200 characters, the component will not be created.
Closes Issue https://github.com/CenterForOpenScience/openscienceframework.org/issues/2993
Changes
------------------
I simply added a maxlength="200" into the field for component titles. Stopping users form being able to enter a title longer than 200 characters.
Edit: Because we want there to be consistency in title length, there were many changes in order to secure that title length remains around 200 throughout the system. Both front end and back end validations were added in order to enforce the 200 character limit on titles. You can no longer edit a …
> [feature] Limit length of component titles

- framework/auth/core.py
- framework/auth/signals.py
- tests/models/test_user.py
- tests/test_models.py
- website/mailchimp_utils.py
- website/profile/views.py
- website/signals.py
Purpose
-----------
Fixes #3289 
A user merged into another user account would get its `mailing_lists` field cleared on the OSF, but would not get unsubscribed on mailchimp.
Changes
------------
Send a `user_merged` signal from `user.merge_user` to `update_subscription`, which updates mailing list subscriptions on both the osf and mailchimp for a user.
Change `unsubscribe_mailchimp` to take a username as an optional parameter, so that the merged user (whose username gets deleted) can still get removed from the mailing list.
> [hotfix] Unsubscribe merged-in user from mailchimp mailing lists

- website/templates/public/pages/help/links.mako
Fixes #3315
Changes two strings:
1: "persons's" to "person's"
2: "created be" to "be created"
> [hotfix] Fix grammar in links description

- tests/test_models.py
- website/mailchimp_utils.py
Purpose
-----------
Fixes https://trello.com/c/zanyrsrX/11-merged-accounts-still-receive-emails-to-both-email-accounts
Changes
------------
Fix conditional for which username to use -- if a username is passed in to the function use that, otherwise use `user.username`. Also fix test to call `user.merge_user` instead of calling `unsubscribe_mailchimp` directly.
> [hotfix-fix] Fix unsubscribing merged-in user from mailchimp

- framework/auth/core.py
- tests/test_views.py
- website/mailchimp_utils.py
- website/profile/views.py
Purpose
-----------
From @GaryKriebel in #3311: 
> If I add a 2nd email to my account, then make that 2nd email primary, will that action remove the first email from the mailchimp subscription and then subscribe the newly tabbed primary email address?
Changes
------------
When a user changes their primary email address, unsubscribe the old primary email from any mailchimp mailing lists subscriptions and subscribe the new primary email address.
> [hotfix] Update mailchimp subscriptions when primary username is changed

- website/templates/log_templates.mako
As per request of issue #3297, this changes the wording for embargo initiated triggered logs.
The logs now say 'initiated an embargoed registration' instead of 'initiated embargo'
Should be none.
> [3297][Feature] Fix embargo wording on logs

- framework/auth/views.py
To prevent the email confirming the merge being sent to the email requesting the merge, rather than the email that is to be merged. Fixes #3346
Confirm email method now changes the to_addr based on whether there this is a merge request.
I do not believe there is any.
> [Hotfix] Fix merge email being sent to the account sending the request

- framework/auth/views.py
- website/templates/emails/confirm_merge.txt.mako
Merge email now displays correct name, fixing #3346. Also supersedes #3348, where I screwed up.
Template now pulls from merge_account for name rather than user.
Should be none
> [Feature-fix] Merge email displays mergee name #3346

- website/static/js/fangorn.js
- website/static/js/fileViewTreebeard.js
Fixes #3324, which was the problem that in file-view, the file tree was not sorted. As suggested by @lyndsysimon, this now also renames the methods being exported by Utils, removing underscores to maintain consistency in naming conventions.
This makes it so that if there are no Column titles, the file tree is sorted in 'asc' mode. 
Files will always be sorted in ascending fashion if there is no column titles for all fangorn derived file trees (if and only if the method Fangorn.Utils.orderFiles is called when there are no titles).
> [Feature-fix] [3324] Fix sort on file-view tree

- framework/sessions/__init__.py
- website/app.py
- website/oauth/models/__init__.py
This should resolve an issue where OAuth flows would not complete successfully, due to the state token not persisting across requests.
ref: https://trello.com/c/5zWI9LC3/12-unable-to-configure-google-drive-and-drop-box-with-new-access-tokens
> [feature/fix] Save session when generating an OAuth connection URL

- tests/test_archiver.py
An Archiver test was failing probabilistically.
Remove the test, it was obsolete.
None
> Remove obsolete archiver make_copy_request test

- package.json
- website/conferences/views.py
- website/static/js/conference.js
This PR resolves this issue: #2831 
- Treebeard has been updated to allow for including filtering on columsn that are not visible
- Tags are provided as a data point in the back end
- hiddenFilterRows option is added to conference
Because of the commit order issue with Treebeard to make sure this works it needs to go in AFTER this PR is merged: https://github.com/CenterForOpenScience/osf.io/pull/2852
Although this is not absolutely necessry (the changes in treebeard are not breaking changes) it's best to be safe with production code and not need to test things again. I will be more careful about order of commits for future fixes.
> [Enhancement] Allow conference search to use tags

- website/templates/project/project_header.mako
Purpose
----------
Fix #3380 --  the settings tab of a project  was viewable to anyone, regardless of permissions. 
Changes
------------
Ensure only users with at least read permissions (contributors and read-only admins) can
see the project settings tab.
> [hotfix] Ensure only users with read permissions see project settings tab

- website/templates/project/project.mako
Fixes #3249
Replaces #3256
The duplicate button in the top-right corner of the project dashboard page appeared active to all visitors, even non users for whom it would not work.
Made the duplicate button appear as disabled if the page is accessed by a non-user.
Added a tooltip to the watch/duplicate button group stating that only users can watch and duplicate; looks like this:
> [feature fix] Project buttons disabled for non-users

- website/static/js/filepage/index.js
From the user perspective, usually the revision info is not primary interest. So it is more reasonable to hidden it at the default setting.
Resolve #3371 
Change the initial value of  `self.revisions.selected` from `true` to `false`
None
> [Feature Fix] Make default toggle: view [ON], revisions [OFF]

- website/templates/project/forks.mako
- website/templates/project/registrations.mako
fixes #3278
I added a button to the forks page that allows new forks to be created easily with two clicks. In addition, I made the forks page as a whole look much more like the registrations page, as they both perform a similar function, just for different types of nodes.
> [Feature] Allow new forks to be created on the forks page of a project

- website/static/js/filepage/revisions.js
Purpose
------------
Fixes #3011 
If a user navigated to the current file version from the versions table and then made some edits to create a new version, the user was not taken to the new version. As a result, the user could create new versions by editing this now out-dated file version. 
Changes
------------
Remove url params for current file version.
> [hotfix] Prevent editing of previous file versions

- website/static/js/projectorganizer.js
Set the naturalScrollLimit as 0 and then no margin will be added
Resolved #3393 
As Caner introduced, in `fangorn.js`, it also sets `naturalScrollLimit` to 0 with the same purpose. The reason behind it is that in Treebear, the default value of  `naturalScrollLimit` is 50. It means if items to show is below this number (50), `onscroll` in Treebear should not be run.
Before searching, the number of items is larger than 50. But after searching, the number of rows decrease and mostly will be less than 50. In that case, it will not run `onscroll`  in Treebear. That's the reason why it leaves blank space behind. 
None.
> [Feature Fix] Fix search result has unnecessary margin 

- framework/auth/core.py
- tests/models/test_user.py
Code clean up.
- Remove unused `User.aka` field.
- Update tests accordingly.
N/A
> [feature] Remove unused User.aka field

- tests/test_views.py
- website/profile/views.py
Allow individuals to get automatically redirected to a user's Twitter account if one is associated with the respective user.
- Add a new endpoint `/@<uid>/` that will automatically redirect to the Twitter account associated with `uid` if the account **is active** and **has a Twitter handle** associated with it. 
- If either of these conditionals is not met, the user is prompted with a concise error message.
A new route was added with a respective view.
> [feature] Add Twitter redirect endpoint

- website/static/js/onboarder.js
Fixes an issue caught before QA where the Create project box tempalte list does not populate the existing user nodes.
Bug: 
The call to the existing nodes was not properly named after refactoring of this section
> [Fix] projects list not appearing in create project onboarder template

- website/static/js/search.js
Fix for #2481
Searches for and replaces ```/\s?NOT tags:/``` with correct one:
```/\sNOT tags:/```, also does this for AND. This should put the correct space between
previous symbols and the keywords NOT and AND.
If there is already a tag in a ```tags:("")``` structure that matches the tag clicked on, it shouldn't add it, but it will correct the spacing issue.
It will put spaces in front of NOT tags: and AND tags:, I believe these are specific enough not to cause issues. That being said it would be possible to mess up the search parameters, but then a normal search without this fix would possibly fail too.
> Apply regex fix for search params

- website/static/css/projectorganizer.css
- website/static/css/typeahead.css
Unify the focus border on dashboard.
Resolved [bug](https://trello.com/c/kBV30AgO/82-dashboard-go-to-my-project-and-select-a-project-search-boxes-do-not-match-osf-style) found in trello
Delete css for creating focus border on typehead. Instead, Bootstrap focus border will be applied.
Note: Find some duplicated css code and need to be cleaned up (`projectorganizer.css` and `typeahead.css`)
None.
> [Style Guide] Detele unconsistent focus border and use bootstrap default style

- tests/test_views.py
- website/profile/views.py
- website/routes.py
Reverse the direction of the Twitter redirect end point.
Instead of resolving a Twitter handle from a User's uid, we now resolve a User's uid, and respective profile url, from a Twitter handle.
None.
- If multiple OSF user accounts are associated with a Twitter handle, the user is redirected to a page where they can select the account whose profile they wish to view.
> [feature fix] Reverse direction of Twitter redirect

- website/static/css/pages/search-page.css
In staging, when clicking disabled page change button, it will still change the page.
Resolve the bug on  [trello](https://trello.com/c/iTYLyqOF/117-page-count-for-search-results-increase-decrease-beyond-the-total-results-available).
Add the disabled class in deleted `site.css` to `search.css`.
None. It is only applied to search page.
> [Hot Fix] Add disabled class to disable pointer-event on page change button

- api/base/api_globals.py
- api/base/middleware.py
- api/base/settings/defaults.py
- framework/mongo/__init__.py
- website/addons/box/model.py
Our original attempt to address caching issues created several unintended side effects (see #3376). This is because simply pushing a flask request context is a very leaky abstraction.
This is an alternate attempt to resolve #3058 / #3303 in a way that does not involve Flask. It is a proposal, and may or may not be merged. The code is a bit messy and could stand to be refined, but it does pass the test case defined in #3058 without creating as many of the side effects seen in #3376.
- Replace the definition of `framework.mongo.StoredObject` (née `FlaskStoredObject`) with a new model whose key function is more framework-agnostic. Involves duplicating code from `modularodm.ext.odmflask` with minor modifications
- Removes FlaskRequestMiddleware
- Adds `DjangoGlobalMiddleware` and a new …
> [feature-fix] Alternative solution to database caching issues in DRF

- website/addons/dataverse/views/config.py
<b>Purpose</b>
Fix dataverse import token error. Closes https://trello.com/c/x1nwc3bi/32-dataverse-confirmation-modal-ok-does-no-action. Replace https://github.com/CenterForOpenScience/osf.io/pull/3448.
> fix the import dataverse token doesn't enable addon_user_settings

- website/static/css/style.css
- website/static/js/comment.js
- website/templates/include/comment_template.mako
Resolved [Trello bug](https://trello.com/c/DEgVxq18/134-comments-widget-buttons-need-to-be-overhauled)
1) After finding the missing css for comment panel in old `site.css`, add that part of code to `style.css`
2) Change save button color from grey to blue
3) Change button text from save to comment
None
> [Feature FIx] Fix comment panel style

- website/templates/include/comment_template.mako
Make-up change for [old PR](https://github.com/CenterForOpenScience/osf.io/pull/3470)
1) Change comment button from blue to green
2) Change button text from save to comment
> [Feature Fix] Change button color and text on comment panel

- website/static/css/pages/profile-page.css
- website/static/css/style.css
In order to not allow the icons to be pushed down in list group, apply component-overflow to the whole site (Add the class to `style.css`)
Related to another [PR](https://github.com/CenterForOpenScience/osf.io/pull/3439)
Resolve [Trello bug](https://trello.com/c/ssIWdear/122-icon-in-registrations-is-pushed-down)
Apply component-overflow to the whole site (Add the class to `style.css`)
None
> [Feature Fix] Add component-overflow class to whole site(style.css)

- website/static/js/fangorn.js
Resolved [Trello bug](https://trello.com/c/tMwhsLdB/132-files-widget-search-and-information-buttons-are-raised-higher-than-others)
Add span tag to general buttons(search and information buttons)
None. I tried to delete the span tag in finalRowButtons. But in `mithril`, nested component views must return either a virtual element or another component. So thinking in the opposite way, I added span tag to  the rise buttons.
And also this is not the perfect way to do it. It is still strange to me that why it increase 1 px in search button, comparing with production.
> [Feature Fix] Fix button rise on file widget

- website/addons/forward/templates/forward_widget.mako
Resolved [Trello bug](https://trello.com/c/iGzDgfAP/158-external-link-buttons-out-of-order)
Before Change:
After Change:
The original color for cancel button is warning. Should we retain this, or just change to grey in order to follow the style guide? I suggest to follow the style guide.
> [Feature FIx] [Style guideline] Change button position and color for link redirect

- website/static/css/style.css
- website/static/js/comment.js
- website/templates/include/comment_template.mako
Resolve Trello Bugs about comment panel:
1. [Button size](https://trello.com/c/td4qBlTm/138-comments-widget-for-making-a-new-comment-or-replying-buttons-are-too-big)
2. [Button position](https://trello.com/c/E0TinF4t/146-comments-widget-buttons-out-of-order)
3. [Button color](https://trello.com/c/AMBfenGU/139-comments-widget-edit-comment-should-have-a-green-save-button-not-a-gray-button)
4. [Unnecessary Icons](https://trello.com/c/mkZcgQAh/136-comments-widget-buttons-should-not-have-icons)
5. Wrong icons
Changes:
Before Changes:
After Changes:
> [Feature Fix] Fix comment panel bug related to style guideline problem

- website/templates/public/pages/faq.mako
Purpose
======
Improve FAQ UI
Increase site consistency
Changes
=======
Use the same styling on the FAQ as is used on the Getting Started page
Side Effects
=========
None
> [Feature] Normalize FAQ styling with Getting Started page

- website/addons/googledrive/model.py
Fixes https://github.com/CenterForOpenScience/osf.io/issues/2610
`urllib` hates unicode
> [Hotfix] Google drive unicode folder names

- website/templates/project/project_header.mako
Update project header alert links to follow [the style guide](https://centerforopenscience.github.io/osf-style/style.html#links).
Change link classes.
None.
Closes-bug: https://trello.com/c/O4XYyrJQ/170-registration-overview-this-project-link-should-be-underlined
> [feature] Update alert href classes to use current style guide

- website/addons/dataverse/static/dataverseFangornConfig.js
- website/addons/figshare/static/figshareFangornConfig.js
- website/addons/github/static/githubFangornConfig.js
The view icons of addon files are wrong. In this PR, it replaces them with the correct one.
Resolved [Trello Bug](https://trello.com/c/0U0gRPaL/140-files-widget-view-button-is-improperly-styled-for-figshare-and-github-add-ons)
> [Feature Fix] Replace right icon for view button on addon

- website/static/js/filepage/revisions.js
- website/static/js/profile.js
- website/templates/include/profile/social.mako
Allow users to link their LinkedIn profile by either their LinkedIn UserID or ProfileID.
- Template and JS no longer assume the use of LinkedIn ProfileID.
- Allow user to add path to either UserID or ProfileID
None.
Closes-issue: #3401
> [hotfix] Allow full path for LinkedIn profile 

- website/static/css/pages/wiki-page.css
- website/static/css/style.css
- website/templates/project/settings.mako
Wiki has a style missing and panel misses clearfix class.
And also resolved [trello bug](https://trello.com/c/SQlHYxDs/161-text-misaligned-on-settings-page-of-registration-for-retraction)
Before Change:
After Change:
> [Feature FIx] Add missing style for wiki

- website/templates/index.mako
Viewing the /goodbye page generates a 500 internal server error on staging. (h/t @sloria). Fix that.
Applies changes previously made in base.mako/alert.mako to the almost identical overriding block in index.mako. This reflects new field of the `Status` namedtuple introduced in #2917.
Audited other OSF pages; did not see this block, or the `status` object in general, being overriden/used in other mako templates.
> Fix status messages in index.mako

- website/static/js/profile.js
- website/templates/include/profile/social.mako
Allow users to use their LinkedIn pub/ endpoints
- Update JS regex to handle full URLs
- Update placeholder
None.
Closes-issue: https://trello.com/c/Fwfsu1EA/188-can-input-either-linkedin-profile-id-or-user-id
> [hotfix] Allow LinkedIn pub/ profile links

- website/static/css/pages/wiki-page.css
This PR fixes wiki editor icons missing bug. In production, we process this img tag with webpack and create  data URI for img tag ([more info](https://css-tricks.com/data-uris/)). However, after I moved css code out of js file and load them statically, it will not be processed by webpack anymore. So data uri will not be created. In addition, the original image url is not  public. Then it can't be shown correctly.
The current solution is to use the public  image resource url which already exists. Another possible solution is to require the css code in js file. However, it will slow the page loading speed. So choose to apply the first solution. 
Resolved [Trello Bug](https://trello.com/c/SgmXjoyO/196-wiki-page-edit-tool-buttons-have-become-invisible)
Before Change:
After Change:
> [Feature Fix] [Staging] Fix Wiki icons aren't shown 

- website/language.py
Clearly state that only registrations being entered into an embargo will issue approval/disapproval emails to project admins.
Updated language
None.
Closes-issue: #3484
> [hotfix] Update register project warning

- website/addons/figshare/static/figshareFangornConfig.js
Fixes #3407
Figshare overrides the toolbar generation function and did not check that kind is a file.
None
> [Hotfix] Figshare can view folders

- website/static/js/fangorn.js
Fixes #3509 
If drop target is a file change the target to its parent.
> [Hotfix] Dragging a file or folder onto a file now uploads to its parent.

- website/addons/forward/model.py
Currently when the External Link add-on is disabled then re-enabled the url present before disabling the add-on is still present after the add-on re-enabled.
This PR causes the values in the external link after re-enabling are the defaults.
This closes issue https://github.com/CenterForOpenScience/osf.io/issues/3496.
Upon disabling the external link add-on it's url, label, redirect_bool, and redirect_secs are set to their default values.
> [Feature Fix] Reset values of external link add-on to default when deleted.

- website/addons/figshare/messages.py
**Purpose**
Adds links to public figshare projects. closes issue #3525.
**Changes**
Modifies the typical error message to include a custom link for the project.
> add link to error message.

- website/static/js/filepage/index.js
- website/templates/project/project.mako
- website/templates/util/render_node.mako
Resolve:
1.  Center the panel title
https://trello.com/c/q4GC7v9Y/211-project-overview-container-titles-not-centered
2. Add proper font to edit
https://trello.com/c/OQhuTDYQ/201-file-details-page-font-size-difference-between-edit-and-revisions-pane-headers
3. Bold component and project tile
https://trello.com/c/ZiLuaNbu/236-project-and-component-titles-are-not-bolded
> [Feature Fix] Fix three styleguide bugs on trello

- website/static/js/pointers.js
<b>Purpose</b>
Fix the problem that when search from different option the page num doesn't reset. Closes https://trello.com/c/jN6sHnR1/204-add-links-modal-clicking-past-last-page-and-through-internal-pages-of-search-results-sometimes-yields-invalid-value-for-page-mes and Closes https://github.com/CenterForOpenScience/osf.io/issues/3497
> fix add link modal search

- website/templates/project/settings.mako
Fixes the trello issue regarding breaking navbar in project settings: https://trello.com/c/cysFBshY
Removed the bottom offset to make the navbar not stick to bottom.
> Remove data-offset-bottom for navigation in project settings

- website/static/css/pages/project-page.css
- website/static/css/style.css
- website/templates/profile/account.mako
- website/templates/project/settings.mako
Fixes these Trello issues
- https://trello.com/c/1AppLiKD
- issue with breaking user names: https://trello.com/c/70apE9EO
- affix navbar in project settings: https://trello.com/c/cysFBshY
Remove the 100% style and add word-break rule to the td. 
Add project css to project settings with new affix-bottom rule
> Break emails in confirmation settings box

- website/templates/nav.mako
In our implementation of new front page the search icon for narrow pages was deleted by me and we missed this in review. This is quite urgent so I'm adding it back in. 
Reported in issue #3461 
Add back the html for the search bar. This will restore functionality.
> [Hotfix] Fix search bar icon in narrow view

- website/addons/wiki/static/pagedown-ace/Markdown.Editor.js
- website/static/css/pages/wiki-page.css
The wiki uses dialogs for adding link and adding image. This change brings the style of these dialog boxes to look like modals without using modal syntax but using the modal classes
Addresses issue: https://trello.com/c/YPSBca7A
The static vendor file in wiki/static/pagedown-ace/ was changed to use modal classes
This is a change in vendor library but it's not installed with package manager and I think it's stable enough but we need to keep an eye on this in case the markdown file is replaced.
> [Ready] [Style] wiki dialog style update

- website/static/css/style.css
There was a curious error where a class in style.css for panel heading was not applying. Turns out a style did not have closing bracket. 
Added the missing closing bracket
None
> [Fix] [Ready] Close missing bracket in style.css

- website/addons/dataverse/templates/dataverse_user_settings.mako
- website/templates/profile/account.mako
- website/templates/profile/user_settings_default.mako
- Fix "Security Settings" heading on user account settings
- In the linked accounts table for Dataverse, Mendeley and Zotero make "Delete Account" right-aligned and not bolded
> [feature-fix] fix user settings css

- website/addons/s3/views/config.py
Remove the decorator that requires the user to have the s3 addon enabled in order to connect an account because it may not exist at that point.
> [feature-fix] Fix user settings s3 config

- website/static/css/pages/project-page.css
- website/static/css/style.css
- website/templates/project/modal_add_contributor.mako
- website/templates/project/modal_add_pointer.mako
Make-up PR  for PR https://github.com/CenterForOpenScience/osf.io/pull/3609
1. The class is applied in multiple pages and it has to be in style.css
2. Change the class name from `icon-width-td` to `osf-icon-td`
> [Feature Fix] Refine Class name and put it to the right place

- website/addons/s3/tests/test_view.py
Regression test for issue fixed by #3606, where Amazon S3 could not be configured the first time a user tries to connect an account.
> Add regression test for s3 config

- website/static/js/fangorn.js
Components and projects should have links to their base page just like files have links for file pages, as per #3593.
Added function gotonode that opens the window with the node clicked, be it project or component. Also, made the row clickable like files.
All trees created with fangorn that use the method _fangornMakeRow to create its rows will have links for its projects and components.
> [Feature] Add links to the components and projects on file trees

- website/addons/wiki/static/pagedown-ace/Markdown.Editor.js
Purpose
======
Closes https://github.com/CenterForOpenScience/osf.io/issues/3518
Changes
=======
Line causing bug (from library ```pagedown-ace```) commented out. See [line 1527-1529](https://github.com/mfraezz/osf.io/blob/19d8a5cbf112a565055cc8b02706e71c26529b05/website/addons/wiki/static/pagedown-ace/Markdown.Editor.js#L1527-1529) for details from original author. 
Side Effects
=========
None locally observable. This line never worked in FF locally / on staging and production (generated ```TypeError: not a function```) without causing any actual problems, and without exhibiting the closed issue.
> [Feature] Prevent unintended wiki page-refresh

- website/templates/project/settings.mako
**Purpose**
Put "Configure Comments" and "Configure Notification" boxes together at bottom of page. Closes #3634.
**Changes**
Simple html changes
Having two small boxes at the bottom of the page can cause the nav sidebar highlighting to skip over second to last option, but otherwise works fine.
> Project Settings Page Rearrangement

- scripts/osfstorage/correct_moved_node_settings.py
- website/addons/osfstorage/model.py
- website/addons/osfstorage/tests/test_models.py
Correctly set node_settings when moving nested OsfStorageFileNodes
Upon moving a OsfStorageFileNode to another node the node being moved
would have its node_settings field updated but would not recurse down
to update its children.
OsfStorageFileNode._update_node_settings addresses this issue.
OsfStorageFileNode.move_under now calls _update_node_settings before
returning
The migration to fix this is located at
scripts/osfstorage/correct_moved_node_settings.py
> [Hotfix] Moved nested files

- website/static/js/accountSettings.js
Currently when an email confirmation is requested to be resent, the success message has the text after the email address emphasized. This PR prevents that behavior.
closes https://github.com/CenterForOpenScience/osf.io/issues/3652
Closed emphasis tags around emails in alert messages.
> [Feature-Fix] Fix emphasis in email conformation message.

- website/static/js/accountSettings.js
<h1>Purpose</h1>
Fix language in "Resend Email Confirmation" modal. Close #3650 .
simple html change
None
>  Fix language of "Resend Email Confirmation" Modal 

- website/addons/wiki/templates/edit.mako
Fixes [this](https://trello.com/c/ujpOZpSr/126-delete-button-should-not-be-in-menu-for-home-wiki-page) Trello bug.
> [feature fix] Remove 'Delete' from Home wiki pages

- website/templates/util/render_node.mako
Fixes #3646
Added parameter that the node must not be a registration in order to show the icons that were not working.
> [hotfix] Remove broken action icons from link boxes in registrations

- website/addons/wiki/views.py
Fix for [this](https://trello.com/c/KRzmK3bk/136-empty-wiki-components-folder-if-pages-have-no-content) Trello bug.
> [feature fix] Empty Component Wiki Pages

- website/addons/wiki/templates/edit.mako
- website/static/js/pages/wiki-edit-page.js
[Trello](https://trello.com/c/eJNsz1fG/137-issues-when-collapsing-wiki-menu-and-then-making-window-smaller) fix.
Screenshot of wiki menu on small screen:
> [feature fix] wiki menu on xs screens

- website/static/css/style.css
Fixes this issue: https://github.com/CenterForOpenScience/osf.io/issues/3696
Increase z-index to 9 so that it covers most things on the page but not the top fixed bars. 
Not sure, as with z-indexes other values might have different. Tested against navigation bars and modals.
> Increase z-index for slide in panel

- website/discovery/views.py
Stop displaying retracted registrations on the Public Activity page. Close #3671.
simple change to /discovery/views.py
<h1> Side Effects </h1> 
> Stop Displaying Retracted Registrations in Public Activity.

- website/addons/dataverse/model.py
Update dateverse to accept the new callback format
Dataverse would send "full_path" for a round trip to give users a
readable file name. Waterbutler now handles send back file names now.
> [Hotfix] Dataverse logs

- website/templates/log_list.mako
Get rid of excess padding on the logs widgets. Close #3636.
Simple html change.
None.
> Make Widget Spacing Consistant on Project Page

- website/addons/osfstorage/model.py
- website/addons/osfstorage/tests/test_models.py
- website/addons/osfstorage/tests/test_views.py
- website/addons/osfstorage/views.py
Detect existing glacier archives upon upload to avoid make dups
When the upload callback is hit a query is done look for any versions
with a matching sha256 and a vault and archive field. If found that
version's vault and archive will be copied to the new version.
An "archive" key is now included in the response indicating whether
or not the new version should be sent to glacier.
This is the sister PR of https://github.com/CenterForOpenScience/waterbutler/pull/62. Both are not breaking changes meaning they do not have to be merged at the same time but both must be merged to work.
> [Feature] Glacier Deduping

- website/addons/figshare/templates/figshare_user_settings.mako
- website/addons/github/templates/github_user_settings.mako
- website/addons/s3/templates/s3_user_settings.mako
- website/templates/profile/user_settings_default.mako
Purpose
-----------
Some of the add-on authorizer names on the user settings page link to their profile on the add-on, while others link to the user's OSF profile and some are greyed out: 
Changes
------------
Make all of the add-on authorizer names grey for consistency:
> [feature-fix] Make all add-on profile authorizer names grey

- website/addons/wiki/tests/test_wiki.py
- website/addons/wiki/views.py
- website/static/js/wikiMenu.js
[Trello](https://trello.com/c/36HLF5nG/154-links-on-projects-do-not-have-link-icons-in-wiki-menu) bug fix.
> [feature fix] component link icons in wiki menu

- website/addons/wiki/templates/edit.mako
Fixes icons in collapsed menu being cut off on small screens, referenced in [#3685](https://github.com/CenterForOpenScience/osf.io/issues/3685#issuecomment-123445327). 
Trello card [here](https://trello.com/c/Cqsbok0V/157-collapsed-wiki-menu-s-icons-are-centered-in-small-windows).
[![Gyazo](http://i.gyazo.com/a36be62f9728ba1ae67d30f4cdf1fbe7.gif)](http://gyazo.com/a36be62f9728ba1ae67d30f4cdf1fbe7)
> [feature fix] center icons on collapsed wiki menu

- website/addons/wiki/views.py
[Trello](https://trello.com/c/XIpfEKf7/156-can-view-component-wiki-pages-with-no-content-on-project-wiki-tab) bug fix.
Tests pass locally.
> [feature fix] component wiki pages displaying incorrectly

- tests/test_views.py
- website/project/views/contributor.py
- website/static/css/pages/project-page.css
- website/templates/util/render_user.mako
- website/templates/util/render_users_abbrev.mako
In this PR, it is to delete the unnecessary space before comma. And also it found and deleted the non-standardized code for displaying comma in abbreviation of contributor names. 
Although there is [previous PR](https://github.com/CenterForOpenScience/osf.io/pull/3713) to solve it,  it is not modular and complete method.
Related Trello Bug Card -- https://trello.com/c/2QIU8n4V/65-public-activity-page-extra-space-between-contributor-and
Related Github issue -- #3669
Related Stackoverflow [Question](http://stackoverflow.com/questions/31522458/how-to-set-correct-comma-position-in-html/31522492#31522492) 
The biggest change in this PR is to delete `render_user.mako` and puts its refactored code into `render_users_abbrev.mako`.   Other small changes are listed below.
1) Delete …
> [Feature] Fix unnecessary space before comma

- tests/test_addons.py
- website/addons/base/views.py
Current behavior always uses the user who initiated the registration to generate API tokens for Water Butler. As a result, if that admin was not an admin, or did not have write permissions, for the original addon/component, Water Butler would return a 403 after asking the OSF if the user has writes to `copyfrom` or `copyto` the component.
`addons.base.check_access` will now check for `write` permissions up the stack for all `copyto` and `copyfrom` requests.
Closes-issue: #3722
> [WIP][hotfix] Ensure Archiver always uses an admin to register addons/components

- README.md
#3680 README.md did not mention any information about the MFR.
There is now a section in README.md that describes the purpose/function of the MFR and links it to the MFR repository for instructions on how to install and run it.
> Mention MFR on README.md

- website/templates/project/settings.mako
Stops disabling buttons for non-top level projects. Trello Card:
https://trello.com/c/F0CZEBjK/163-cannot-change-category-for-component-categorized-as-project
Corrects this bad PR:
#3667
Removes bad condition.
> Fix Lockout of Change/Cancel Buttons

- package.json
- website/addons/box/static/boxFangornConfig.js
- website/addons/dataverse/static/dataverseFangornConfig.js
- website/addons/dropbox/static/dropboxFangornConfig.js
- website/addons/github/static/githubFangornConfig.js
- website/addons/googledrive/static/googleDriveFangornConfig.js
- website/static/css/fangorn.css
- website/static/js/fangorn.js
- website/static/js/pages/project-dashboard-page.js
Fixes this github issue with connection error message: https://github.com/CenterForOpenScience/osf.io/issues/3205
This PR attempts to do a comprehensive fix that changes the way the title column is shown and adds a refresh button. 
- Update of treebeard commit number (this change allows for refresh icon to switch back to plus icon) 
- remove notify from all addons
- Add a util function that gives a template for not connected
- Adjust addons so that the exact same format appears in all
Potentially significant, although nothing came up in my testing. Still needs QA
For each add on:
- Check loads properly when connected
- Check loads properly with error message when not connected
- Check that toolbar appears with normal load
- Check that toolbar does not appear with not connected load
- …
> [Fix] [Ready] Improve feedback when add ons are not loaded due to connectivity 

- website/addons/wiki/templates/edit.mako
- website/addons/wiki/tests/test_wiki.py
- website/addons/wiki/views.py
- website/static/js/pages/wiki-edit-page.js
Closes [#3764](https://github.com/CenterForOpenScience/osf.io/issues/3764)
- Adds error handling for the wiki menu, as shown below:
- Removes ```_serialize_wiki_toc``` and moves relevant logic (including fix for pointers) to ```serialize_component_wiki```.
> [hotfix] wiki menu error handling and pointers fix 

- website/addons/base/__init__.py
- website/addons/box/model.py
- website/addons/dataverse/model.py
- website/addons/dropbox/model.py
- website/addons/figshare/model.py
- website/addons/github/model.py
- website/addons/googledrive/model.py
- website/addons/s3/model.py
<h2>Purpose </h2>
Fix representative error message caused by forking unconfigured addons. Closes #3521.
<h2>Changes </h2>
Now all addons use same error reporting function which properly accounts for unconfigured addons.
<h2> Side Effects </h2>
Now all relavant addons use the same function before_fork from the superclass AddonNodeSettingsBase instead having separately defined, but functionally incidental functions.
> Create Fork Modal Message Incorrect

- api/nodes/serializers.py
- tests/api_tests/nodes/test_views.py
- https://github.com/CenterForOpenScience/osf.io/issues/3536 Fixes Swagger Doc issue that would create a pointer to itself. 
- Changed variable name in nodes/serializers.py from 'node_id' to 'target_node_id'. 
- Changed variable names in unit tests
- Added unit tests that attempt to return deleted pointers
None. 
Closes issue:
https://github.com/CenterForOpenScience/osf.io/issues/3536
> [feature fix] Pointer created by Swagger docs belongs to wrong node

- tests/test_archiver.py
- website/archiver/__init__.py
- website/archiver/tasks.py
Some users need to be able to manually override our system archive size restrictions. This PR makes that possible.
- add NO_ARCHIVE_SIZE constant
- add check in #archive_node to override size limits
- add unit test to confirm this behavior works
None
> Archiver size overrides

- website/templates/include/profile/social.mako
This PR is to fix the issue that gitHub input form have rounded corners. The reason behind it is because we use a btn-group inside a btn-group, which results in the border issues. I change it into use one btn-group.
Resolved https://github.com/CenterForOpenScience/osf.io/issues/3808
Before Change:
(https://cloud.githubusercontent.com/assets/8591162/8881207/195e6a58-320c-11e5-8c21-c8d83d0afde4.png)
After Change:
None
> [Feature Fix] Fix the btn-group usage for import github

- website/static/js/onboarder.js
- website/static/js/pages/dashboard-page.js
- website/templates/components/dashboard_templates.mako
Filter typeahead results for registration project search, so that those without admin privileges won't get a 'forbidden' error. Close #3738.
Added permissionsAllowed as a parameter to the ProjectSearchViewModel, used it to filter results and set to admin for registration search.
> Filter Typeahead Results for Registration Onboarder.

- website/static/js/comment.js
- website/templates/include/comment_template.mako
The hover-edit function has been disabled, but the hover effect is still shown. In this PR, it will clear the hover highlight code for comment.
Resolve issue: https://github.com/CenterForOpenScience/osf.io/issues/3780
Delete the hover light code in comment.js and comment_template.mako
None.
> [Hot fix] Clear hover light effect on comment panel

- website/static/css/style.css
- website/templates/emails/archive_copy_error_user.html.mako
- website/templates/emails/archive_size_exceeded_user.html.mako
- website/templates/emails/archive_success.html.mako
- website/templates/emails/archive_uncaught_error_user.html.mako
- website/templates/public/pages/getting_started.mako
Fix Github Bugs:
1. Fix navigation overlap with Footer on Getting Started Page
https://github.com/CenterForOpenScience/osf.io/issues/3481
2. Include link to project in issue registering project email
https://github.com/CenterForOpenScience/osf.io/issues/3589
3. Check growl boxes and alerts across site for overlapping text
https://github.com/CenterForOpenScience/osf.io/issues/3700
1. Add bottom offset for affax in navigation
2. Add a tag for project name on mail heading
3. Since growlbox doesn't support `.alert-dismissable`, manually add padding to box
For adding project link in email, I can't test them locally.
> [Feature Fix] Fix GitHub UI Bugs

- website/project/views/node.py
<b>Purpose</b>
Fix the redirect link in the successful component creation alert. Closeshttps://github.com/CenterForOpenScience/osf.io/issues/3799
> fix the create new component success alert redirect

- tests/api_tests/nodes/test_views.py
- tests/api_tests/users/test_views.py
- https://github.com/CenterForOpenScience/osf.io/issues/3314
- Removed unnecessary calls to Node.remove() in the test_views.py files and kept the ones that were necessary
None.
Closes issue:
https://github.com/CenterForOpenScience/osf.io/issues/3314
> [feature fix] API tests teardowns

- website/static/js/accountSettings.js
For cosmetic reasons, user-entered text should be correctly HTML-escaped in growl and bootbox messages.
Reported on Trello board.
Applies `$osf.htmlEscape` to email addresses used in growl and bootbox on the account settings page. (for email address registration)
Affects functionality on  `/settings/accounts`:
1. Initial registration of new email addresses (green message in corner)
2. Resend confirmation link (confirmation box + green message in corner)
3. Remove email address button (confirmation box + green message in corner)
4. Make primary  (green message in corner)
Sign up with an email address that contains certain [old-school](http://stackoverflow.com/a/15532395/1422268) escape sequences, eg `&amp_text@cos.io`. The address should display correctly.
#2933 
#3635 (addendum)
> [feature][markupsafe][review]Escape user-entered text inserted in growl and bootboxes

- website/static/js/profile.js
- website/static/js/tests/profile.test.js
Tied to #2933 / #3635 .
Fix a front-end error that occurs when entering a middle name with two consecutive spaces. (edge case, but was hindering some other QA work on that page)
- Only calculate initials from non-empty parts of a tokenized string.
- Add regression test to ensure function works as intended.
- Exposes the `initials` function in NameViewModel to allow for unit testing. Updates calls to this function to avoid breaking existing functionality.
> Fix profile page initials error for strange names

- website/addons/badges/templates/badges_user_settings.mako
- website/addons/badges/templates/dashboard_badges.mako
- website/addons/box/static/boxNodeConfig.js
- website/addons/wiki/static/pagedown-ace/Markdown.Editor.js
- website/addons/wiki/templates/add_wiki_page.mako
- website/addons/wiki/templates/delete_wiki_page.mako
- website/addons/wiki/templates/edit.mako
- website/static/js/citationsNodeConfig.js
- website/templates/project/modal_add_component.mako
Fix modal titles to be in accordance with new guidelines added in https://github.com/CenterForOpenScience/osf-style/pull/66.
These guidelines were chosen due to this discussion: https://github.com/CenterForOpenScience/osf-style/issues/61. If accepted, this will close the issue.
These changes only correct the modal titles that were easy to find. Others may not be in accordance with the new styling.
> Feature fix/modal titles

- tests/test_addons.py
- website/addons/base/views.py
- website/addons/figshare/model.py
- website/addons/figshare/static/figshareFangornConfig.js
- website/addons/github/model.py
- website/addons/github/static/githubFangornConfig.js
- website/addons/github/views/hgrid.py
- website/addons/googledrive/model.py
- website/static/css/fangorn.css
- website/static/js/fangorn.js
- website/static/js/filepage/index.js
- website/static/storageAddons.json
- website/templates/project/view_file.mako
- Replaces [#3154](https://github.com/CenterForOpenScience/osf.io/pull/3154)
- Adds a link to the file view page which links to the provider's external view of the file.
- Adds a "View on ..." button to the file tree which also links to the provider's external view. 
- Addresses [#2926](https://github.com/CenterForOpenScience/osf.io/issues/2926)
- Addons Supported:
- Screenshot:
- File detail page:
- File tree:
- Dependent on WaterButler PR [#65](https://github.com/CenterForOpenScience/waterbutler/pull/65)
> [feature] external file view

- website/static/js/filepage/index.js
When branch is not passed to waterbutler and the viewed file does not exist on the default branch errors are raised and revisions is displayed incorrectly.
> [Hotfix] Github file view

- tests/api_tests/users/test_views.py
Small test hygiene.
- Deletes a unit test that is 100% duplicated (including test name) See lines 250-253 vs lines 327-330.
- Clean up uses of `super` and delete unused variable
No side effects expected.
> Delete exact duplicate API unit test

- website/static/js/osfHelpers.js
With the recent change to wiki to allow full page containers the anchor scroll function was broken. This PR fixes that to restore full page anchor links.
Update the value that the height is using to make sure proper logic is run.
None.
> [Fix] [Ready] Fix broken TOC anchor links in Wiki 

- website/static/js/projectorganizer.js
As reported in error #3781 when the user clicked cmd + link on Project organize the event bubbles up to select the row which has side effects triggering multiselect and showing a red flash background. 
Added function to prevent bubbling when Project Organizer links are clicked
None
> [Fix] [Read] Prevent selection on link Project Organize click

- tests/test_rubeus.py
- website/util/rubeus.py
Display correct name for private project 
Resolved Issue https://github.com/CenterForOpenScience/osf.io/issues/3621
Delete the old code which only do simple if-statement judgement and replace it with a function to get the display name of project. 
It is not a general solution and only apply in rubeus.py. Currently, the similar code that deal with the same issue is used in render_node.mako.  It may be better to put into node.py. Because it will be very likely to be used in many other places in future.
Code in render_node.mako
%if summary['is_registration']:
Private Registration
%elif summary['is_fork']:
Private Fork
%elif not summary['primary']:
Private Link
%else:
Private Component
%endif
> [Feature Fix] Put correct private component name in file tree

- website/static/js/accountSettings.js
- website/static/js/fangorn.js
<b>Purpose</b>
Fix the language type of file can't load and add question mark for resend email modal. Closes https://github.com/CenterForOpenScience/osf.io/issues/3884 and https://github.com/CenterForOpenScience/osf.io/issues/3889
> fix the typo problem when file can't load

- tests/webtest_tests.py
Some web tests are randomly failing, when the fake strings generated contain HTML-escaped characters.
This is a side effect of #3635 (markupsafe profile/settings pages).
- Adds a helper (assert_in_html) to be used with pages that are rendered in markupsafe mode. It looks for the (markupsafe-rendered version of this string) in the result document. Chose this approach because it's probably faster than re-parsing the entire document.
- Converted profile-related unit tests to use new assertion when dealing with dynamic content. (eg a project title) Did not touch tests that look for static unaffected strings (eg heading text)
- Ties these tests to the specific `markupsafe` library. (which is what mako, jinja et al already use as a dependency)
- Unit tests will need to be individually updated …
> Fix profile/settings related webtest failures

- website/templates/project/project.mako
Make button grouping more consistent with the style guide. Close #3630.
Ungroups buttons and moves tooltip over both of them.
<h1> Old Look </h1>
<h1> New  Look </h1>
> Ungroup Watch and Duplicate Buttons

- website/templates/util/render_nodes.mako
Fixes issue #3892 "re-enable reordering of components".
For some reason not clear to me the items that need to be sortable were given a selector that no longer showed the correct component rows that needed to be sorted. It was ```> li``` and it needed to be ```#components > li```. 
This script is localized to this file only so there shouldn't be side effects.
> [Ready] Fix components widget not being sortable

- website/static/js/fangorn.js
There has been some inconsistencies with upload canceling, for instance single file canceling has not always been successful. This PR makes improvements to make cancel upload more stable. 
- the function called to get list of files being uploaded now includes both uploading and queued files
- the growl boxes are removed when the dropzone error is "Upload canceled." because a) this cancel is not an error, it's initiated by user, b) there was a single growl message for each file which was bad UI. 
The only side effect is the removal of upload canceled error message since this change does not take into account times when canceling uploading might be in fact an error but I can't think of any case where that scenario would happen. Open to input on that one.
> [Ready] [Fix] Use better list of files for canceling uploads

- website/addons/base/__init__.py
- website/addons/box/model.py
- website/addons/dataverse/model.py
- website/addons/dropbox/model.py
- website/addons/figshare/messages.py
- website/addons/github/model.py
- website/addons/googledrive/model.py
- website/addons/s3/model.py
- website/addons/twofactor/models.py
Add underlines to addon error messages. Close #3887.
Adds ```<u>```tag to addon message links.
> Add Underline to Addon Message Links

- website/static/css/style.css
Stop project titles from over lapping. Close issue #3625. This was not fixed by #3697 
Simple css.
> Stop Project Titles from Overlapping on Add Links Page

- website/project/views/comment.py
Currently when you attempt to restore a comment, there is no effect. This PR causes comments to properly be restored.
This closes https://github.com/CenterForOpenScience/osf.io/issues/3638
In the undelete_comment function use 'cid' keyword to get the comment id.
> [Feature-Fix] Fix restoring comments

- website/static/js/projectorganizer.js
This PR is mainly to solve #3341, which bring the original buttons back after canceling search. During the debugging, I also found and solved two other issues. 
1) As pointed in style guide, too short and obvious tooltip is unnecessary.
2) Unnecessary padding after clicking `Adding existing projects` button
1. Delete the code for clearing selection after opening the search
> ctrl.tb.clearMultiselect();
2. Add padding only when it gets warning messages
3. Delete the tooltips -- ` tooltip: 'Rename this item'`
None.
> [Feature Fix] Fix dashboard buttons fail to restore after canceling search

- website/static/js/osfHelpers.js
Fix issue where the width of the scroll spy would contract if it was refreshed by applying a selected addon in the middle of the page. Close #3872.
Resize function now applies to parent '.osf-affix' instead of three children '.affix, .affix-top, affix-bottom'.
> Fix Scroll Spy

- website/addons/mendeley/api.py
- website/addons/mendeley/tests/test_api.py
- website/addons/zotero/model.py
Purpose
======
Closes https://github.com/CenterForOpenScience/osf.io/issues/3157
Changes
=======
* Add `limit: 500` argument to outgoing Mendeley requests
* Set `limit=100` to Zotero's `client.collections()` call in `citations_list`
Side Effects
=========
Also sets the max for Zotero, not just Mendeley.
Note
====
Pagination would be a more perfect solution, but this has been a user issue for a while.
> [Feature] Set limit to max for citation_list requests

- website/profile/views.py
- website/static/js/accountSettings.js
- website/templates/profile/account.mako
<b>Purpose</b>
Change the error return from backend from 500 to 404 while adding an invalid unconfirmed email. Also improve the error message when the front end email validate is not supported(Safari). Closes https://github.com/CenterForOpenScience/osf.io/issues/3851.
<b>Changes</b>
In Safari, add an invalid unconfirmed email,
Used to be:
After the change:
> improve the error message on add unconfirmed invalid email

- website/templates/index.mako
The box background style on front page is missing on staging.  The cause is because `signup-help` was deleted in previous PR https://github.com/CenterForOpenScience/osf.io/pull/3890. 
Reported by @alexschiller  Good catch!
There are five usages case for `signup-help` See one example below.
Before Change:
After Change:
In production, it has radius (rounded boarder). However, our style guideline only offers non-radius box. This PR follow the guideline, but it will be inconsistent with other input fields on front page.
> [Staging] [Feature Fix] Fix the box background style missing in front page

- website/static/css/search-bar.css
- website/static/css/style.css
In this PR, it is to fix the hidden of search bar when expanding the menu at the same time.
Resovled #3881 
1) Since the menu's z-index is 1030, so I change search-bar's z-index from 1028 to 1030. Therefore, it will not be covered. 
2) Delete unnecessary z-index code in style.css for navbar
After clicking menu icon -- before Change:
After clicking menu icon -- After Change:
None.
> [Hotfix] Fix hidden search bar in mobile 

- framework/auth/core.py
- website/templates/emails/email_removed.txt.mako
<b>Purpose</b>
Fix the typo and improve the language part for remove email's email alert. Closes https://github.com/CenterForOpenScience/osf.io/issues/3857.
<b>Changes</b>
Originally, remove an email will send two of the same email to both the email got removed and the primary email.
After change:
<b>Email One: </b>
[website.mails]  DEBUG: Sending email...
[website.mails]  DEBUG: To: tianxia@test.com
From: openscienceframework-noreply@osf.io
Subject: Email address removed from your OSF account
Message: Hello tianxia,
I just wanted to let you know, the email address helloworld@test.com has been removed from your account. For security purposes, a copy of this message has also been sent to your account's alternative email address (helloworld@test.com).
If you did not request this action, let …
> improve remove email from account email alert

- website/addons/googledrive/model.py
- website/addons/googledrive/tests/test_views.py
- website/addons/googledrive/utils.py
Purpose
=======
Closes https://github.com/CenterForOpenScience/osf.io/issues/3748
Changes
=======
Added optional keyword argument to fetch_access_token() so that this addon will actually check if the credentials are valid when defining valid_credentials.
Side Effects
=========
Added 'settings' to urls for proper link to user addon settings (`/settings/addons/`), rather than `/settings/undefined`
> [Feature] Add force_refresh argument to fetch_access_token for credential verification

- website/templates/log_templates.mako
To complete complete the changes discussed in #3843, namely removing any special styling tags in the Log had. This should have been part of #3843, but I missed some of the tags in the log_templates.mako. Sorry!
Removes class='tag' tags from the log templates, so they appear as normal links.
> Remove Tag Styling from Activity Log

- website/templates/metadata/register_1.mako
Fix error reported by @NatashaRichter on Trello: registration templates were failing to render because one variable was not being markup-escaped.
Should be none.
Registration pages behave a bit oddly, so please keep me apprised of any other breakages. (it's worth checking a few different schemas as well due to [inconsistent](https://github.com/abought/osf.io/blob/fix/3910-registration-js_err/website/project/views/register.py#L356-356) separation of concerns)
> Fix broken registration pages

- website/templates/profile/addons.mako
- website/templates/project/project.mako
- website/templates/project/settings.mako
Reported on Trello by WillBanner in associated with #3910.
When enabling an addon on project pages, the "Addon terms" modal incorrectly displays as raw code (rather than being rendered). This PR exempts that string from markupsafe rendering.
Additionally, the modal text is completely removed from several pages where it does not appear to be used at all.
- Fixed website/templates/project/settings.mako
- Removed text from  website/templates/project/project.mako 
- Removed text from  website/templates/profile/addons.mako 
Hopefully none: this modal text was removed from profile settings.
We are not sure why the text was *ever* in project pages; click a variety of addon related things and report any bugs.
Modal (on project settings) should look like this one:
> Fix addon settings modal on project pages

- website/addons/dropbox/static/dropbox.css
<b>Purpose</b>
Remove the unnecessary css for the dropbox alert to keep consistent with other addons. Closes https://github.com/CenterForOpenScience/osf.io/issues/3924
<b>Changes</b>
Before change:
After change:
> remove the unnecessary css

- website/addons/s3/static/s3NodeConfig.js
- website/static/css/style.css
- website/static/js/osfHelpers.js
- website/static/js/projectSettings.js
Resolve Trello Card:
1. Delete Project modal button should say "delete"
https://trello.com/c/hKV9YuJM/58-delete-project-modal-button-should-say-delete
2. Invalid Bucket Name button options are wrong
https://trello.com/c/vIlsQfHO/54-invalid-bucket-name-button-options-are-wrong
1. Deep copy to override the button label
2. Correct the button color
None.
> [Feature Fix] Refine modal button text and word break

- bower.json
- framework/addons/templates/capabilities.mako
- website/static/css/pages/project-page.css
- website/static/css/style.css
Resolved Trello Cards:
1. Text overflow in add-on terms modals
https://trello.com/c/NH16HOUi/67-text-overflow-in-add-on-terms-modals
3. Tags overflow in Search if they are too long
https://trello.com/c/kQnwKTWa/63-tags-overflow-in-search-if-they-are-too-long
1) Delete word-break code in style.css and update style guide version ( Add word break there https://github.com/CenterForOpenScience/osf-style/pull/76)
Apply refined word break to `p, a, span, em, td ` and class `break-word`
word-break: break-word; /* Only WebKit/Blink browsers Support */
word-wrap: break-word; }
2) Disable `word-break:break-word` in the first column of add-on terms table 
Because the new word break will apply the whole site. So maybe there are also other special cases we need to deal with.
> [Feature Fix] Refine break word in whole site

- website/static/js/fangorn.js
Provide users with a generic error message.
- Add generic upload error message.
- Old message:
- New message:
None.
We should add provider specific information to the Water Butler exception handler to build more useful error messages with fangorn.
Closes-issue: https://trello.com/c/jegKrdQ5/75-improve-error-message-to-users-when-file-uploads-fail
> [feature fix] Update fangorn error upload message

- website/static/css/style.css
Fix problem created when long tags cause cursor to get stuck between tags. Relevant Trello card: https://trello.com/c/tSoW9G6c/65-tag-input-box-jumps-around-when-alternately-adding-short-and-long-tags
Change to .tagsinput div ensures cursor will always trail last tag.
> Fix Long Tags Jumping Past Cursor

- website/templates/log_list.mako
Empty watchlists show a sentence that reads "Click the watch icon icon on a..." This removes the extra "icon."
> Remove extra "icon"

- website/project/views/node.py
<h1>Purpose</h1>
Fix grammar in view-only link change
<h1>Changes</h1>
Current language when you try to anonymize a public project/component:
"Anonymized view-only links DO NOT anonymize contributors of public project or component."
Changed to:
"Anonymized view-only links DO NOT anonymize contributors of public projects or components."
> fix grammar in view only link language

- website/templates/include/profile/jobs.mako
- website/templates/include/profile/names.mako
- website/templates/include/profile/schools.mako
- website/templates/include/profile/settings_navpanel.mako
- website/templates/include/profile/social.mako
- website/templates/profile.mako
- website/templates/profile/account.mako
- website/templates/profile/addons.mako
- website/templates/profile/notifications.mako
- website/templates/profile/settings.mako
This PR makes minor edits to several settings pages to improve work flow and general use. 
- All Settings pages headers are changed to Settings instead of their actual names. This allows the user to have a better context about where she is and links well to the Settings link on the navigation bar which says "Settings" when hovered over. 
- The active class in the navigation is fixed so that the user knows which of the settings pages she is at, thus eliminating need for a separate title for those settings page.
- There is now a link at Profile Information edit page to take users back to the profile page.
- The Cancel buttons in profile edit where renamed to "Discard Changes" which is the same as what the modals say when that button is clicked. 
- Icons were added to View Profile and Edit …
> [Ready] Enhancements to profile settings pages 

- website/static/js/search.js
- website/templates/search.mako
<b>Purpose</b>
Fix the problem that share search thread can appear twice on search page. Closes https://trello.com/c/WTvShYqU/5-fix-in-search-results-page-share-displaying-twice-when-user-hits-enter-button-twice.
> fix the share search thread appear twice

- website/static/js/osfHelpers.js
The PR is to solve the issue that navigation bar on setting pages doesn't update responsively when user changes the size of screen.
Resolved #3908
Reduce the debounce time. 
Cost user's resource for updating the page
> [Feature Fix] Set proper debounce time for navbar update on setting pages

- website/addons/s3/static/s3NodeConfig.js
<b>Purpose</b>
Fix the problem that s3 create bucket error message doesn't work. Closes https://trello.com/c/ArmmahP3/10-no-error-message-when-clicking-create-with-blank-name-for-amazon-s3
> fix s3 bucket error message problem

- bower.json
Fixes this Trello issue: 
https://trello.com/c/vqwzwfpf
The osf-style repo was updated to fix a quirk. This PR updates the installation. 
break-word does not always apply and normal is the default so there shouldn't be any side effects
> [Ready] Update style guide version to fix input multiple issue

- website/addons/base/views.py
- website/templates/project/view_file.mako
Fix two bugs that were causing file views to fail after the conversion to markupsafe, per report by @jinluyuan on Trello. One issue was triggered by files in Github addon storage, and the other was caused by viewing a file detail page when not logged in.
1. Move JSON conversion to mako template for consistency (`addon_view_file` does not seem to be used anywhere other than this view)
2. Check that all variables in `window.contextVars` are subject to the `sjson, n` filter in the template (but not in other functions)
3. Handle a case where strings constructed in Python should handle a user id value of "None", resulting in a mako error when viewing page while logged out.
The method of dealing with `user['id']= None` is a bit of a kludge, because the function …
> Markupsafe-3 bugfixes for view file page

- website/static/js/onboarder.js
Removes additional ```/``` from registration URLs.
Closes [#3875](https://github.com/CenterForOpenScience/osf.io/issues/3875).
> [hotfix] Registration URL

- website/static/js/projectorganizer.js
When Treebear need to update the content in scroll bar. The selected item would flash. In this PR, I found the reason is that the selected item with class `fangorn-selected` was cleared  even though it doesn't need. Although `fangorn-selected` would be added again for selected item, it creates a time slot without `fangorn-selected`. Therefore, it leads to the blink in appearance.
Resolved #3365
And also during debugging process, another bug was found. When searching, it will add unnecessary margin space.
Clear `item.css` only when item is not selected.
None.
> [Feature Fix] Fix selection in project organizer blinks when the number of row is larger than 50

- website/templates/project/view_file.mako
Closes [#3983](https://github.com/CenterForOpenScience/osf.io/issues/3983).
> [hotfix] File Spinner Covers External Links

- website/static/css/fangorn.css
- website/static/js/fangorn.js
- website/static/js/fileViewTreebeard.js
- website/static/js/iconmap.js
- website/static/js/pages/project-dashboard-page.js
This PR addresses the concerns of issue #3619 and creates a uniform look for private items
- Removes links from private items so the names are not clickable
- changes the yellow folder icon to Font Awesome lock icon
- Adds lock icon to all items that are private
- Makes the private items look muted in text color
This only applies to OSF related items so no changes were made in addons. As far as I know this is correct but it would help to have confirmation
I checked in all instances of files, Files Page, project overview Page, File Detail Page. I checked Wiki to make sure nothing is broken. 
Because there are changes in view logic testing needs to validate that treebeard view works fine, i.e the rows load and the private items look like they should in this change and the change does not …
> [Ready] Icon and view consistency for private items in file browser 

- website/static/js/filepage/revisions.js
This PR is a temporary fix to the issue #3787 , it's temporary in the sense that a Proposal for revising this section will be sent. In the meantime the fix itself is standard across the web and not a hack. It follows Jeff's suggestion in the discussion. 
Force non-responsiveness on revision when table is in narrow window view. It maintains responsiveness in bigger windows. 
This will hide the download button from immediate view which is not ideal but otherwise it would be stretched outside the window anyway.
> [Ready] Fix for scrolling width of revisions table 

- website/routes.py
A one-off conversion of the public activity page to reflect recent changes introduced in markupsafe-3 (#3910).
Turn on markupsafe rendering for the public `/explore/activity` page.
Should be none. However, best practice advises a quick round of QA using the same project names and test strings as for markupsafe-3. (#3910)
> Convert public activity page to markupsafe rendering by default [markupsafe-extra]

- tests/test_views.py
- website/project/model.py
- website/project/views/contributor.py
Continuation of https://github.com/CenterForOpenScience/osf.io/pull/3385
Purpose
----------
If a project has a component with a sub-component, and a user is added to both the top-level project and the sub-component but not the component, the user would only receive one email about being added to the project. However, when viewing the project page, they will just see a private component and may not realize that they were also added to a sub-component in that private component.
Changes
------------
Notify contributors if they have been added to a component if the parent project is private. So in the example above, the user would receive two emails: one for the top-level project and another for the sub-component.
> [feature] Notify contributors when added to a component whose parent project is private

- website/addons/dataverse/templates/dataverse_user_settings.mako
- website/static/css/style.css
- website/templates/profile/user_settings_default.mako
Stops project titles from overflowing tables on user settings page addons and prevents the "Disconnect Account" link from becoming crowded in table heading. Closes #3804.
Simple CSS and moves link outside table.
None.
> Fix Word Wrap and Crowded "Disconnect Account" link

- website/static/js/fangorn.js
Purpose
=======
Fix https://trello.com/c/ObhQKy9w/36-project-settings-page-is-broken-for-add-on-and-notifications-configuration
The issue arised because two different types of `item` will be checked there: `object` and `event`. An `object` has associated `permissions`, an `event` does not.
Changes
=======
Check for `item.data.permissions` to avoid a regression-causing `TypeError`
Side Effects
=========
None
> [Feature] Fix permissions regression

- tests/test_models.py
- website/project/model.py
Fix bug where changing the first contributors visibility would raise unnecessary error. Close #3765.
set_visible now can accept a list of user dicts being modified and check against that to see whether an error should be raised.
> Fix Visible Contributor Swap Bug

- website/static/js/pages/project-settings-page.js
- website/static/js/projectSettings.js
- website/templates/project/settings.mako
Stop the change/cancel buttons on the project setting from briefly flashing during loading. Close #3649...Again.
This issue was a lot more problematic then expected, for some reason simply putting a ko containerless conditional statement around the buttons doesn't cut it, so this was the best I could come up with.
> Fix Flashing Change Cancel Buttons

- website/static/css/share-search.css
- website/static/js/share/footer.js
- website/static/js/share/results.js
Builds on #3500.
Addresses 3 Bugs:
- On very small screens, the results were all crammed together and the long provider names cut out the hr between results. Now, the hr is preserved on small screens.
- On very small screens, on the SHARE index page, the provider links were unclickable. This puts them into their own HTML row so that the row below them does not take over on small screens - they're clickable on mobile now!
- The provider list was wrapping in a strange way - as noted in https://trello.com/c/KJRO3CxU/52-share-providers-list-column-vertical-wrapping-is-cut-off. This PR removes the column-gap css property that was causing the strange wrapping in Chrome
- Updates footer to have provider list in their own row
- Adds hr to the result so that long  names don't overshaddow on mobile …
> Fixes to SHARE Search Update

- website/static/js/share/results.js
- website/static/js/share/sideBar.js
- website/static/js/share/stats.js
Thanks to @fabianvf for most of these fixes - 
QA Found a few bugs:
- Blank active filters is confusing on mobile
- Clicking "show more" tags jumps the user to the top of the page
- Tooltip labeling had rounding inconsistent with graph labels
- Remove the "Active Filters" heading when there are no active filters
- Remove href from tags to keep the user in place when clicking
- Add same rounding math to tooltip labels as graph labels
-  href was removed from tags, but now - when you click on a tag to filter results, and the resulting filtered results list is shorter, the page appears blank until you scroll back to the top of the new results list (as the page did not jump as a new filter)
> More SHARE search bugfixes

- website/static/js/osfHelpers.js
- website/static/js/pages/project-settings-page.js
- website/templates/project/settings.mako
In Safari, the updating message in addon setting will not show. It is because Safari will not update the style instantly. So In this PR, it adds delay before reloading the page. Therefore it will show the message.
Resolve https://github.com/CenterForOpenScience/osf.io/issues/4001
Another change is about the spinner in comment configuration. In this PR, it replaces the old spinner with the style guide spinner. 
1) Add helper function for checking Safari Browser
2) Add setout delay for safari before reloading the page in project setting page
3) Replace with the style guide spinner
Apply setout function in Safari and it will create 100 milliseconds delay.
> [Feature Fix] Fix update message disappear on safari

- website/static/js/onboarder.js
- website/templates/components/dashboard_templates.mako
Purpose
=======
Partial fix for https://github.com/CenterForOpenScience/osf.io/issues/1669
Adds click-to-upload functionality, does not add drag&drop functionality. There's something weird about IE's event system, preventing drag&drop related events from being registered. It may be due to an interaction with knockout, but I've found no evidence for or against that.
Changes
=======
* One `dropzoneOpts` key-value pair added
* Change the header above the dropzone (to `"Click below to select file"`) iff IE
Side Effects
=========
May fix similar issue for Safari 7.0.3 (untested). See https://github.com/CenterForOpenScience/osf.io/issues/1250
If so, header will not change in Safari.
> [Feature] Add click support for onboarder dropzone in IE

- website/static/css/legend.css
To make the icon display more readable
Before Change:
After Change:
None
> [Feature Fix] Refine icon info display

- website/static/js/contribManager.js
Stops unwarranted 'single visible contributor' alerts from piling up, like so:
This also fixes this trello card: https://trello.com/c/uSTPAeg5/61-sharing-tab-still-seeing-the-incorrect-error-while-rearranging-contributors
Simple JS change clears message observable.
> Stop Single Visible Contributor Alerts From Piling Up

- website/static/js/components/legend.js
- website/static/js/projectorganizer.js
Align the display with alphabetical order
The PR will resolve #3645 completely.
1) Add sorting function 
2) Align the text 
Before Change:
After Change:
I don't know why I pull the request from cos develop branch. But it doesn't have the legend heading like staging.
> [Feature Fix] Align the display with alphabetical order

- package.json
- website/static/js/projectorganizer.js
Fixes the issue #2154 where in certain cases the expand/collapse state was not reliably setting. 
- This includes treebeard change so installing assets is required. Treebeard had two invocations of the ontogglefolder function in certain cases which made the expand/collapse to be set twice. (https://github.com/caneruguz/treebeard/commit/c81b89ba6ed59e160ed5042c6208bc5fb1cc15aa)
- Existing expand/collapse state saved was wrong, although this does not really take effect for the page and is not relevant to the function but it's good to keep the server state and application state synchronizes in case we use them in the future. 
- Treebeard core was changed so all treebeard instances need to be tested to make sure they  **a) show content** and **b) toggle folders properly**
- Note that saving …
> [Ready] Fix project organizer saving expand/collapse state accurately

- website/templates/emails/contributor_added.txt.mako
Fixes https://trello.com/c/bfdUb6zf/73-contributor-notification-needs-a-comma-for-if-then-sentence
> [feature-fix] Add comma to contrib added email

- website/conferences/views.py
- On both staging and production, when downloading a talk or poster from an OSF Meeting, an extra ```/``` is included in the download URL. 
- Example: on production, the download URL for the most recent SPSP 2015 poster is ```https://osf.io/project/24rz6/files/osfstorage//553eacc28c5e4a21991b2a4e/?action=download```.
- This PR removes the additional ```/``` that is not currently stripped from the file path.
> [hotfix] Fix OSF Meeting Download URLs

- website/static/css/style.css
Makes fixes as suggested in issue #4019 to improve style of tags used. 
- hover backgrounds are lighter color for readability
- X icon in search tags has radial white backgound to fix this (https://github.com/CenterForOpenScience/osf.io/pull/3843#issuecomment-126772678) 
- input focus outline is styled but kept for accesibility
- border radius is set to 2px 
I tested in search and  project overview pages, I don't know if these apply anywhere else.
> [Ready] Tag style fixes 

- website/static/js/share/stats.js
Fix for trello issue: 
SHARE - Line graph's x-axis dates are in Month/Year format and repeat themselves
> [FeatureFix] Share charts with full date

- website/templates/dashboard.mako
- website/templates/log_list.mako
- website/templates/profile/notifications.mako
- website/templates/project/files.mako
- website/templates/project/project.mako
- website/templates/project/view_file.mako
Fixes the following Trello bugs related to size of spinner by overall reverting to lg size
- Project Logs: https://trello.com/c/5J3lhaJy
- File Detail page: https://trello.com/c/9d61XxA2
- Project overview file widget https://trello.com/c/Oa3YLzdj
- Configure Notification https://trello.com/c/BvPQBnkV
- Added loader to project organizer
It does not fix MFR rendered section. 
Spinner sizes were changed to logo-lg to fit their spaces and each other. These may be different than production, their relative size and fit in their white space is the check. 
- Added loader to project organizer, which was not decided on, but it seems to make sense.
> [Ready] Fix spinner problems for 0.46

- website/static/js/share/stats.js
X label was being cut off when date appeared on far right side. Padding in c3 setup added to fix.
> [FeatureFix] Added padding to share chart so full x label shows

- website/static/js/share/stats.js
Dates were off by +1 (i.e. 31 -> 32)
> [Hotfix] Share Date Chart: Date range now between 31-1

- website/addons/github/utils.py
Add move and copy to github messages to prevent moves and copies from creating extra logs.
The core issue was fixed via waterbutler 0.10.2
> [Hotfix] Github double logs (kinda)

- website/static/css/front-page.css
A CSS bug was causing the sign-in button to be hidden for certain window sizes.
Revert a12e7115276104193917767cda01b5fa60f92477
Spoke with @caneruguz, and this likely snuck in during a merge with the
design firm's latest updates.
None
> [Hotfix] Fix UI bug with hidden sign-in

- website/static/js/filepage/index.js
Purpose
=======
Closes https://github.com/CenterForOpenScience/osf.io/issues/3705
Changes
=======
Remove url param that disabled download count tracking
Side Effects
=========
None
> [Feature] Remove '&mode=render' to increment download count

- scripts/approve_registrations.py
- scripts/embargo_registrations.py
- website/archiver/utils.py
- website/exceptions.py
- website/project/model.py
If Archiver fails, the registration is deleted. However, the respective Sanction is untouched. This ensures that they are rejected either by the Archiver callback or by the scripts checking Sanctions.
- Updated Archiver failure callback to forcibly reject Sanctions
- Updated scripts to forcibly reject Sanctions for this case
> [feature fix] Handle Sanctions after Archiver failures

- bower.json
- website/static/css/front-page.css
- website/static/css/style.css
Fixes a regression error where the menu for login stayed at 300px in narrow screens. Makes sure this works in all pages and not just front-page. 
- Updated the style guide css to include narrow version of menuLogin width
- moved the css for sign in to more general style.css since the login window appears in all logged out situations. 
- Removed #formLogin, doesn't seem to be used anywhere. 
I checked different withds and pages, seems to be none.
> [Hotfix] Fix width of sign-up in narrows screens

- website/project/model.py
- website/templates/log_templates.mako
Inconsistent behavior of reg. initiated and reg. rejected logs
https://trello.com/c/Hnbt1RyW/45-project-title-does-not-link-to-resource-deleted-for-disapproval-logs
Always refer to the registration in the log params.
Also convert cancellation links to plain text (don't expose url of potentially archiving node) 
None
> Fix 'node' in registration cancelled log to point to deleted reg

- website/project/model.py
Resolve incomplete embargo emails missing approval links.
- Fix misnamed method
Closes-issue: https://trello.com/c/eRBnRPfa/32-no-link-to-approve-embargoed-registration
> [feature fix] Approval emails for embargoes were missing their approval links

- website/templates/emails/pending_registration_admin.txt.mako
The link to view registration for registration approval emails was blocked by mako's #endif.
Reformat so the link is included inline for both branches.
None
> Uncomment hidden approval link from registration initiated email

- website/templates/project/project_header.mako
Ensure that all registration templates have a `read-only` watermark
Closes-issue: https://trello.com/c/cERml4ao/39-no-greyed-out-read-only-on-pending-registration
> [feature fix] Add watermark to pending registration templates

- tests/test_sanctions.py
- website/mails.py
- website/project/model.py
All sanction confirmation emails were getting sent to sanction initiator
- Send emails to user rather than Sanction.initiated_by
- Add a regression test for the bug.
resolves https://trello.com/c/Ww5fUwir/37-the-admin-making-the-registration-gets-all-contributors-approval-emails
> Fix Sanction emails

- website/project/model.py
Adding registration_approval rejection logs was erroring out
Use node._id instead of node
> Use ._id rather than model instance

- website/project/model.py
Ensure retraction approval emails have the approval link.
- Fix misnamed method.
Closes-issue: https://trello.com/c/Wd7C9Zr1/49-no-email-sent-upon-retracting-registration
> [feature fix] Retraction approval emails were missing the approval inks

- tests/test_sanctions.py
- website/project/model.py
We were both using and testing the wrong usage of website.mails.send_mail. 
Pass send_mail to address as the first argument, and update tests to reflect this.
> Send mail takes to_addr as first arg

- website/templates/log_templates.mako
Links never got removed from embargo cancellation logs
Convert link to span
> Remove link from embargo cancellation log template

- website/project/model.py
- Registration completion logs were given an explicit log_data, causing logs to appear out of order.
- Remove log_date constructor from NodeLog constructor
> Don't provided explict log_date for registration success logs

- website/archiver/listeners.py
This decorator should have been removed but wasn't causing issues
before. Now, if an error gets raised in any of the Sanction#ask logic
two bad things happen:
- exception gets swallowed
- (possibly) two emails get sent to some admins; Sanction#ask loops
through a list of users. If one of those calls raises an Exception then
the registration initatior will get a second email telling them there
was an issue registering X.
Remove the decorator
> Remove fail_archive_on_error decorator from archiver callback

- tests/test_registration_retractions.py
- website/project/model.py
- website/templates/project/project_header.mako
- website/tokens/handlers.py
Disallow sanction token actions if the sanction has been approved
Check if a sanction has been approved in the handler, raise a 400 if so.
- https://trello.com/c/YZFj2bAk/55-users-can-cancel-embargo-registrations-retractions-after-they-are-already-approved
- https://trello.com/c/bd4b6MPQ/54-alert-at-top-of-screen-incorrectly-refers-to-a-component-as-a-project-for-immediately-public-registrations
> Prevent rejection for approved sanctions

- framework/auth/decorators.py
- tests/factories.py
- tests/test_tokens.py
- website/project/model.py
- website/tokens/handlers.py
Earlier the SHORT_NAME for registration approval got changed which broke the handler system for sanction tokens
Fix this and add test coverage for sanction handlers. 
https://trello.com/c/YZFj2bAk/55-users-can-cancel-embargo-registrations-retractions-after-they-are-already-approved
> Fix token handler messages and add tests to document behavior

- api/nodes/serializers.py
- api/nodes/views.py
- tests/api_tests/nodes/test_views.py
Prevent deleted children from showing in the `NodeChildrenList`
* Add a conditional in the list comprehension for the view to remove nodes that are deleted as well as tests in TestNodeChildrenList
* Addresses #4154
None
> [Fix] Do not show deleted children in node children

- website/project/model.py
- website/templates/emails/pending_embargo_admin.txt.mako
- website/templates/emails/pending_embargo_non_admin.txt.mako
- website/templates/emails/pending_registration_admin.txt.mako
- website/templates/emails/pending_registration_non_admin.txt.mako
- website/templates/emails/pending_retraction_admin.txt.mako
- website/templates/emails/pending_retraction_non_admin.txt.mako
The language in our registration/embargo/retraction emails varied unnecessarily. 
Standardize the language.
> [READY for REVIEW] Standardize langauge for registration/embargo/retraction emails

- website/static/js/pages/register_1-page.js
This PR is to unify non-standard modal heading and reduce unnecessary margin.
Resolve https://github.com/CenterForOpenScience/osf.io/issues/4140
1) Add `h4` for title
2) Delete `br` tag
None
> [Feature Fix] Refine modal and margin on registration page

- tests/test_models.py
- website/project/model.py
- website/templates/project/project.mako
see conversation here: 
https://trello.com/c/koNpA4L1/67-public-immediately-pending-registrations-are-private-until-approval
- prevent pending registrations from being made public
- add test to document this behavior
https://trello.com/c/koNpA4L1/67-public-immediately-pending-registrations-are-private-until-approval
> Disallow making pending registrations public

- tests/test_archiver.py
- tests/test_models.py
- tests/test_views.py
- website/addons/dataverse/tests/test_model.py
- website/addons/dropbox/tests/test_models.py
- website/addons/figshare/tests/test_models.py
- website/addons/github/tests/test_models.py
- website/addons/googledrive/tests/test_models.py
- website/addons/s3/tests/test_model.py
- website/archiver/listeners.py
- website/archiver/tasks.py
- website/project/model.py
Replacing https://github.com/CenterForOpenScience/osf.io/pull/4165, based on discussions:
- https://github.com/celery/celery/issues/2554
- https://github.com/celery/celery/issues/2554
- https://github.com/celery/celery/issues/2219
Some users have issues using the chord pattern. 
Update proposed fix to avoid celery.chord usage.
> Update syntax to avoid celery.chord usage

- website/static/js/signUp.js
Resolved https://trello.com/c/QJIJ15HB/63-more-padding-on-home-page-after-sign-up
Before:
After:
I don't know why the text-info class is added after timeout. But if we clear all the message, it is better to clear the text-info class. As a result, it will not influence the new update message
And also I tried to use css binding in knockout and put the padding class in html. But it will create visible bar. So I have to put `p-xs` in javascript and add them dynamically.
> [Feature Fix] Add more padding on home page after sign-up

- website/project/model.py
is_initiator was not being injected into the embargo admin email template context. This caused a conditional in that template to always follow the False branch.
Add is_initiator to embargo email context.
https://trello.com/c/B9JAJr4x/70-incorrect-wording-in-embargoed-registration-email
> Add is_initiator to embargo email context

- website/static/css/pages/search-page.css
- website/static/js/navbarControl.js
This PR will have the dropdown menu not hidden. The reason is because I changed z-index to solve the issue that search bar is hidden in small screen (Issue https://github.com/CenterForOpenScience/osf.io/issues/3881) . 
Before Change ---- Dropdown on search page -https://osf.io/search/
After Change  ---- Dropdown on search page
Before Change ---- Dropdown on other pages:
After Change ---- Dropdown on other pages -- For example -- -https://osf.io
Generally, Putting `!important;` is not a good practice. I am not sure put the code below is the best practice.
$('.navbar .dropdown').on('show.bs.dropdown', function () {
self.showSearch(false);
self.searchCSS('');
});
> [Feature Fix] Fix search bar occludes dropdown items

- website/static/js/fangorn.js
It adds margin to span tag. So when span tag is empty, it still has that margin. So we add if-statement for it. When span is empty, don't use that.
Resolve https://github.com/CenterForOpenScience/osf.io/issues/4137
Before Change:
After Change:
None
> [Feature Fix] Fix icons not centered for information and x buttons 

- website/templates/project/project.mako
Leave enough space for button group when it comes to small screen
Resolved https://github.com/CenterForOpenScience/osf.io/issues/4139
Change the column number in small screen.
Before Change:
After Change:
It may leave less space for project title. but it could be broken. So,it still looks OK.
> [Feature Fix] Add properate column number for sm

- website/static/js/search.js
- website/templates/search.mako
The UI for search tags was behaving badly. Clicking the little X on a tag did nothing.
This updates that UI to behave as expected, i.e.:
- when a tag is clicked, and it is not already part of the query, it is added (to the query string)
- when the little X on a tag is clicked, and it is part of the query, it is removed (from the query string)
- Update search code relevant to tagging to be more readable and predictable
None
> [HOTFIX] Fix search tags

- website/static/js/share/searchBar.js
- website/static/js/share/utils.js
- website/static/js/tests/share/utils.test.js
Purpose
-----------
When visiting the SHARE atom feed, even with a short query (like "cats"), the url that is generated is 1800+ characters long. Much of that is cruft that is either default values, or not used in the atom feed.
Changes
-------------
Change query building logic to only add fields when they are not set to the default value, and removes unused fields when generating the SHARE atom feed URL. Shortens the json dumped URL significantly.
Side-effects
Changed all of SHARE query building logic, so could affect any searches/tags. 
Should make Atom feed quite a bit faster.
Example
-------------
a query for cats, which currently produces:
https://osf.io/share/atom/?jsonQuery=%257B%2522query%2522%253A%257B%2522filtered%2522%253A%257B%2522query%2522%253A%257B%2522commo …
> [Hotfix] strip share query down

- website/project/model.py
Registration approvals did not behave like embargoes in the sense that the root node of registration hierarchies was not made private
Make the root node private
https://trello.com/c/koNpA4L1/67-public-immediately-pending-registrations-are-private-until-approval
> Make parent pending registration private

- website/static/js/search.js
A JS bug prevented users from removing tags when more than one tag filter is active
Allow matches to be null
https://trello.com/c/uk52BtZA/74-adding-removing-search-tags-works
> [Hotfix] more Search tags

- website/templates/emails/pending_registration_admin.txt.mako
- website/templates/emails/pending_retraction_admin.txt.mako
There is a mistake in the pending retraction email. Also the language in the pending registration email stood to be improved. 
Update retraction and pending registration emails
https://trello.com/c/CzphRlmk/94-retraction-email-has-incorrect-language
> [Hotfix] Sanction email language fixes

- website/static/css/pages/contributor-page.css
- website/static/js/addonPermissions.js
- website/static/js/osfToggleHeight.js
- website/static/js/privateLinkTable.js
- website/templates/profile/addon_permissions.mako
- website/templates/project/contributors.mako
Based on issue #3689 this PR replaces the expand/collapse functionality of two locations
- View Only Link table in Sharing page
- Addon active projects list in user settings page
closes #3689 
Removes existing expand collapse logic and markup from the two locations and replaces with the osfToggleHeight plugin. 
None
(see issue #3689 for originals)
> [Feature] [Ready for Code Review] Consolidate expand/collapse use in two locations

- tests/test_registration_retractions.py
- website/addons/s3/static/s3NodeConfig.js
- website/project/views/register.py
- website/static/js/registrationRetraction.js
Cailey aka The Mash Master, managed to POST the retractions form more than once before page reload. This overwrote the previous retraction for that registration. This means multiple emails got sent, only the last of which actually works.
- Prevent double form submission
- Disable retracting a pending retraction on the backend
- Add python test for this behavior
- https://trello.com/c/kCFNv2Ui/100-unable-to-resolve-when-clicking-retraction-approval-links
- https://trello.com/c/ZQlGVZ8l/99-duplicate-emalis-for-registration-retractions
> [Hotfix] retraction mash

- website/static/js/search.js
Purpose
=======
Closes https://github.com/CenterForOpenScience/osf.io/issues/1502
Changes
=======
Use regex to escape quotes when building the tag's querystring
Side Effects
=========
Escaped strings appear in search bar, may confuse user.
> [Feature][Fix][Ready for Review] Escape " in clicked tags with \" using regex

- webpack.common.config.js
- website/conferences/views.py
- website/static/js/meetings.js
- website/static/js/pages/meetings-page.js
- website/static/js/submissions.js
- website/templates/public/pages/meeting_landing.mako
- Per @JeffSpies' request, the main OSF Meetings page (```osf.io/meetings/```) will now use treebeard to display the list of meetings. 
- Additionally, a tabbed view of 'All Meetings' and 'All Submissions' has been added to the page so that users can toggle between a table of all meetings (ordered by highest number of submissions) and all submissions (ordered by the most recent submissions first). 
- 'All Meetings' View
- 'All Submissions' View
Also pinging @AndrewSallans and @saradbowman for any comments.
> [feature] Treebeard OSF Meetings

- tests/webtest_tests.py
- website/templates/project/contributors.mako
- website/templates/project/project_header.mako
<b>Purpose</b>
Rename "Sharing" tab to be "Contributors". Closes https://github.com/CenterForOpenScience/osf.io/issues/4204.
<b>Changes</b>
Before change:
After change:
> rename sharing page to be contributors

- package.json
Fixes the bug that was causing issues for Steve's RPP special case fix. With refactored flatten function from @chrisseto 
https://github.com/caneruguz/treebeard/commit/ab1fa6139282328fa93eade64032f407f70da9a3
This PR updates treebeard commit number. In treebeard the fix was to refactor flatten function.
This will impact all treebeard instances. Especially lazyloading folder opening needs to be tested with QA in these locations:
- Files Tab
- Project Overview
- Dashboard
- File Detail Page
- Notifications Settings pages in user settings and project settings
> Fix flatten related bug

- website/conferences/message.py
Mailgun will not include stripped-text if there is message body
> [Hotfix] Conferences

- tests/test_addons.py
- website/addons/base/views.py
Require node_addon to be a subclass of StorageAddonBase
Wiki node_settings would sometimes make it to this route causing 500s
as they do not implement find_or_create_file_guid.
> [Hotfix] Non-file addons in file endpoints

- framework/auth/forms.py
<b>Purpose</b>
Improve the language on reset  password page. Closes https://github.com/CenterForOpenScience/osf.io/issues/4098
<b>Changes</b>
Before change:
After change:
> improve the reset password language

- package.json
- website/static/js/submissions.js
Fixes the following Trello bug about problems with sorting of date and author. 
https://trello.com/c/SM19wSbr
Part of the sort problem (with Author was because of a wrong sort type which was changed to 'text'
The other part of the problem was due to Treebeard not having date sorting as a feature, but the developer used it anyway without testing if date sorting works (which could also stem from the fact that all test items have the same dates which makes it hard to test locally). 
This update includes an update to treebeard with the date sorting feature added.
Should not break anything else since the additions to treebeard kick in only if date sorting is used, and it's not used anywhere else on the OSF.
> [Ready] Meetings sorting fixes

- website/addons/dataverse/templates/dataverse_user_settings.mako
- website/templates/profile/user_settings_default.mako
Fixes Trello issue https://trello.com/c/c5hO4Spy
where expand/collapse feature does not apply to some add ons. Turns out this is because the mako file where the html is defined is not being used by all addons. 
Added the pertinent sections to the addons that were missing these files
None. Adding further html attributes should not have any side effects.
> [Ready] Add expand related attributes to addon files

- website/project/model.py
Turns out we weren't using the settings constants for Embargo expiration times. Also, RegistrationApproval was using some unnecessary manual timedelta -> num. hours conversion. 
Fix this
None
> [Hotfix] Approval consts

- framework/auth/views.py
This closes issue #3374, and rewords the status message when the "forgot password" link is clicked to match the solution discussed in the issue.
> Fix status message for 'forgot password' (issue #3374)

- website/templates/emails/welcome.html.mako
This closes issue [#OSF-4251] where the email link included too many words.
> Update contact us email link

- api/applications/serializers.py
- api/applications/views.py
- tests/api_tests/applications/test_views.py
- tests/test_models.py
- tests/test_views.py
- website/oauth/models/__init__.py
- website/profile/views.py
- website/static/js/apiApplication.js
- website/static/js/tests/apiApplication.test.js
Improvements to OAuth2 app registration functionality, including fixes to accommodate recent changes.
- Updates Knockout to work with JSONAPI formatted data (fix breakage due to recent change) [#OSF-4313]
- Rename `active` field on ApiOAuth2Application model to `is_active` (requested previously, possible due to recent CAS change) [#OSF-4317]
- Add front and backend validators for max field length: 200 characters for application name and 1k for application description. [#OSF-4282]
> [ready for review] Update OAuth app reg to work with recent API changes

- api/base/exceptions.py
- api/base/filters.py
- tests/api_tests/nodes/test_views.py
In APIv2, if the client passed an invalid filter in the querystring, e.g. `?filter[not-a-field]=foo`, the invalid input passed silently.
A 400 response with the message "Querystring contains an invalid filter." is returned to the client.
https://openscience.atlassian.net/browse/OSF-4325
> [feature] Return 400 if client passes an invalid filter

- website/static/js/logFeed.js
- website/templates/util/render_node.mako
<b>Purpose</b>
Change the recent activities field for retracted registration to be a warning instead of showing logs. Closes [#OSF-3969]
<b>Changes</b>
before:
after:
> change the recent activity log for retracted registration

- api/nodes/views.py
- tests/api_tests/nodes/test_views.py
- website/project/model.py
There were uncaught errors being raised when the client:
- Tries to DELETE a node that has components
- Tries to delete a pointer that doesn't belong to the requested node
Re-raise exceptions with correct DRF exception in order to return properly-formatted 400 responses to the client.
https://openscience.atlassian.net/browse/OSF-4322
https://openscience.atlassian.net/browse/OSF-4314
> [feature] API error handling when removing pointers and nodes

- website/addons/wiki/templates/edit.mako
This gives the 'can_edit_wiki_body' check to the preview view of the wiki page. Used to be only 'can_edit'.
There are a few more plain 'can_edit' checks in the mako template but they do not cover any of the functionality described in the ticket.
> [Feature] Wiki Collaboration Preview Permissions

- website/static/js/notificationsTreebeard.js
Fixes [#OSF-4335] where the notifications treebeard instance did not draw more than first 16 columns
Treebeard should get rid of the naturalScrollLimit setting, I'll add as an issue
> Fix limiting showed items by resetting natural scroll limit

- framework/auth/views.py
- website/routes.py
- website/static/js/pages/base-page.js
- website/templates/base.mako
rename auth_url to reauth_url
send reauth attempt through standard logout endpoint so cookie can be cleared, thus preventing authentication loop
> [hotfix] Potential OSF Authentication Loop

- tests/api_tests/nodes/test_views.py
Fixes #4086 and an update to #4132
Purpose
-------
Currently api_tests/nodes/test_views/test_writing_to_public_field has a commented out status code assertion.  That assertion is no longer needed as it is a feature of the django rest framework.
Also, in the same test, changes "public_field" (the mongo field) to "public" (the django rest framework field) 
Changes
------------
Remove commented out line 573 and 574 of test_views
change "public_field" to "public" twice in the test.
> check for 200 on PATCH of read field and fix public field

- framework/auth/core.py
- framework/mongo/validators.py
- tests/test_models.py
- website/oauth/models/__init__.py
- website/static/js/osfLanguage.js
Refs [#OSF-4430] and [#OSF-4433].
Addresses unclear or surprising behaviors when registering an OAuth2 Developer App on the OSF. This includes the case where an all-HTML name was blanked by the sanitizer, and the rare case where a user might want to deactivate a new OAuth2 application immediately.
- Move the `string_required` validator from `framework.auth.core` to a new centralized location, `framework.mongo.validators`
- Use the above validator in the `name` field of `ApiOAuth2Application`.
- Change the wording of the "deactivation failed" error message to specify that it may work if the user waits a few minutes 
New error message sample:
Cleaned up and reordered imports in `framework.auth.core`; auth exceptions were being imported in two different ways. I've separated the cleanup work …
> [ready for review] Fixes for OAuth2 application registration

- website/app.py
- website/settings/celeryconfig.py
Resolve an issue resulting in registrations getting stuck in the archiving process.
Something happened during the addition of Celery Beat and changing how we setup our Celery workers that caused a circular import with Archiver as well as stopped `website.archiver.tasks` from being imported into the the task pool.
- Remove import in `website.app` causing a circular import
- Add `website.archiver.tasks` to CELERY_IMPORTS
Resolves-issue: [#OSF-4378](https://openscience.atlassian.net/browse/OSF-4378)
> Fix broken archiver

- website/static/js/folderpicker.js
Fixes:  Jira issue OSF-4275 and OSF-4424
Purpose
-----------
In the latest version of the Chrome browser, any Add On that uses the Folder Picker (Box, Google Drive, Mendeley) will not allow a user to change folders.  The Save and Cancel button never appear.
Current:
After fix:
Changes
------------
1.  The onChange event was happening twice, and was being lost during the redraw of the page.  I have changed the onChange event to an onMouseOver when a folder is selected.
> [Hotfix] Restore Save and Cancel  in folderpicker on Chrome

- website/addons/figshare/static/figshareFangornConfig.js
Purpose
-----------
Fix issue in [#OSF-3202] where the file action buttons appear in the Fangorn toolbar.
Changes
------------
Do not show figshare file action buttons (Upload, Download, View, Delete and View on figshare) in the Fangorn toolbar on the file view page.
> [feature-fix] Only show search button in toolbar for figshare files

- website/addons/github/model.py
Allows the project/user settings mako template to render w/ error message.
> [hotfix] Catch GitHubError and display a generic OSF error

- website/static/js/projectorganizer.js
The highlight created by dragging will be removed. 
Resolve #3191 
In old code, it stores the result of `tb.select('.tb-row')`. However, at the beginning, it only has one row. What we need in mouseout event is to deal with all the rows after loading completely. So I replace the variable `rowDiv` with the selector. Therefore it will select all the rows again after they load completely.
None.
> [Feature Fix] Fix Dragging project or component in Dashboard to ineligible row causes highlight to persist

- website/addons/dataverse/static/dataverseUserConfig.js
- website/static/js/addonSettings.js
- website/static/js/citationsNodeConfig.js
- website/static/js/pages/profile-settings-addons-page.js
Fixes JIRA issue: OSF-4265
Where the application of the osfToggleHeight plugin to addon node list was unreliable. 
There are two types of data load methods for addons
1. Those that get added by backend and mako file addon_permissions.mako
-- For these the document.ready function was used to apply
2. Asyncronous loading with ajax after load 
-- For these the initialization was added where nodes have been applied 
None
> [Ready] Fixes the osfToggleHeight initialization in user settings 

- tests/test_registration_embargoes.py
- website/project/model.py
If an embargo is rejected, its registration along with its component
registrations should be deleted if they did not exist prior to the
request for the embargo.
- Call Node#delete_registration_tree upon Embargo#_on_reject
- Modify delete_registration_tree to not delete the root registration
if it existed prior to the embargo.
[#OSF-4316]
> [Fix] Ensure rejected embargoes children components are cleaned up

- website/search/elastic_search.py
<b>Purpose</b>
fix the problem that registered component are categorized as component rather than registration. Closes [#OSF-4259]
Need to run invoke migrate to fix the data in elastic search database after this pr is merged.
> Fix elastic search update_nodes

- website/addons/box/README.md
The instructions in the README.md for local development needs updating.  The most important change is updating the OAuth2 `redirect_uri`
> Update and clarify the instructions for running the Box Add-on 

- website/addons/dataverse/static/dataverseFangornConfig.js
Purpose
------------
Fixes [#OSF-4451]
In the files toolbar for dataverse, the version menu includes the option to select the "Published" version even if the study does not have a published version. Choosing that option causes the select box to disappear and an error message pops up:  
Changes
------------
Only provide "Published" as an option in the dataverse version select box if the connected dataverse study has a published version.
> Only show "published" option in dataverse fangorn toolbar when there is a published version

- api/nodes/views.py
There was some discussion of how to generalize the <user_id> = me shortcut across the API. This PR explores how to do this with the node contributor detail view as a first use case.
Apply UserMixin to NodeContributorDetail view, and use #get_user shortcut method. 
none
> [RfR] Generalize <user_id> = me across API

- website/static/js/fangorn.js
- When the user clicks on (but does not open) a closed folder that contains files it is expected that a "Download as zip" button should appear. 
-Change in fanghorn.js
Users will be able to download empty folders. This side effect was discussed with @erinmayhood and the resulting issue is addressed in a new JIRA ticket: https://openscience.atlassian.net/browse/OSF-4549
Closes: 
- https://github.com/CenterForOpenScience/osf.io/issues/3388
- JIRA ticket: https://openscience.atlassian.net/browse/OSF-3429
> [hotfix] Download as zip button does not appear for closed folders

- api/base/authentication/drf.py
- api/base/exceptions.py
- api/files/views.py
- api/nodes/views.py
- api/users/views.py
- tests/api_tests/base/test_views.py
- tests/api_tests/users/test_views.py
Replaces https://github.com/CenterForOpenScience/osf.io/pull/4322
References [#OSF-4563]
QA discovered unconfirmed and deactivated users could access the API using HTTP basic auth.
Also fixes invalid node permissions check on file version view
- Add UserIsConfirmed permissions class
- Add UserIsNotDeactivated permissions class
- Add OsfAPIViewMeta class to ensure ^ are added to all view class
- permissions
- Update and unit tests
- remove ContributorOrPublic from FileVersionsList
???
> Test that every view has a base set of permission classes

- framework/auth/oauth_scopes.py
- tests/api_tests/base/test_auth.py
- tests/test_addons.py
References [#OSF-4574]
Some OAuth tools have trouble dealing with proper encoding of scope names. This changes the + character (which has special meaning and requires encoding) to an underscore (which should pass through without problems)
- Rename all scopes (internal and public facing) to separate permissions from scope name using an underscore (instead of a plus sign).
- Fix the feature that pretty-prints a list of what views/ core scopes go with what publicly available/composed scope
- Updated all unit tests accordingly. Times like this that I wish I'd used named constants....
> [Ready for review] Rename scopes to use underscores, not plus signs

- website/static/js/fangorn.js
- website/static/js/filepage/index.js
Purpose
======
Hides buttons that will invariably return errors if pressed
Changes
=======
More ugly special cases for Dataverse added
Side Effects
=========
None
> [Feature] Hide delete button for published dataverse

- website/project/views/contributor.py
<b>Purpose</b>
Fix the logic for sending email to notify contributor added. Closes [#OSF-4573]
> fix the logic for sending email to notify contributor added. 

- tests/test_sanitize.py
- website/util/sanitize.py
Fixes a bug where `strip_html` turned non-string inputs into strings.
This is relevant to the API because we sanitize all user input here: https://github.com/CenterForOpenScience/osf.io/blob/84559c0f97084514b1de6f93cf199be79a7e2ffc/api/base/serializers.py#L306 . Using `_rapply` with `strip_html` resulted in boolean and other non-string inputs being stringified.
This is a blocker for https://openscience.atlassian.net/browse/OSF-4306 and any other API development that requires updating non-string fields.
https://openscience.atlassian.net/browse/OSF-4570
> [Ready for Review] strip_html correctly handles non-string input

- tests/test_serializers.py
- website/project/views/node.py
Fixes https://openscience.atlassian.net/browse/OSF-4618
For the list of nodes returned when adding a contributor to a project with components, instead of checking whether a user can edit a node, check that they have admin permissions on the node.
> [Hotfix] Fix check for add contributor permissions

- api/static/css/osf_screen.css
- https://github.com/CenterForOpenScience/osf.io/issues/3552 To disable having active swagger docs pages and just have them display the docs. 
- Changed 'display' value in osf_screen.css file that corresponds to the "try it out!" buttons
None.
Closes issue:
https://github.com/CenterForOpenScience/osf.io/issues/3552
> [HOLD] Change swagger docs from active to read-only

- api/base/parsers.py
- tests/api_tests/nodes/test_views.py
Issue OSF-4629, https://openscience.atlassian.net/browse/OSF-4629
New parser added to handle new JSON request formatting can only handle dictionary data.  If other type of data like a "list" or "string" is sent, there is an uncaught 500 exception because the code tries to call `.get` on a string, for example.
Raises ParseError if data is not a dictionary.
> [Ready to Review] Uncaught 500 error when request contains non-dictionary data

- api/nodes/views.py
- tests/api_tests/nodes/test_views.py
Use get_object_or_error for osfstorage. Path is no longer stored in mongodb
> Fix node files endpoint

- api/base/exceptions.py
- api/base/serializers.py
- api/nodes/serializers.py
- tests/api_tests/nodes/test_views.py
The Node Contributor view was incorrectly serializing it's 'self' link. I.e.
```   
"links": {
"self": "http://localhost:8000/v2/user/xbd6f/",
"html": "http://localhost:5000/xbd6f/"
}
```
Which should be: 
```
"links": {
"self": "http://localhost:8000/v2/nodes/26vq3/contributors/xbd6f/",
"html": "http://localhost:5000/xbd6f/"
}
```
Make the Links class 'self' link overridable  
profit ???
> [RfR] Feature/api/node serializer fixes

- api/base/serializers.py
- api/users/serializers.py
- tests/api_tests/users/test_views.py
Fixes bug #4203
Purpose
-----------
In the API, users that have not filled out the any social fields in their profile will not show social media fieldnames. There is just a blank dictionary labeled social_accounts.
To provide consistent user experience and to encourage users to fill out their profiles, we will now show all social fields even if they do not exist on the database.  
Changes
------------
User fields are shown on new users and ones without any social media information filled out.
Side Effects
All User social fields are stored at the top level of the JSON object, not one level down in the social_accounts dictionary.
> [Feature] API Show New User Profile Fields

- website/static/css/style.css
- website/static/js/osfHelpers.js
Fix the issue that on get-start page, FAQ page, and setting page, affix Nav bar box gets bigger when scrolled down. 
Resolved [#OSF-4550]
Add init for nav-bar width when page refreshes
**Before Change:**
**After Change:**
When refreshing the page, the change of width of nav box is still visible when loading the page. But user will not be unexpected change of nav box size when user do any actions. 
----Updates----
After commit --`Fix side effect width change visible`,  side effect is resolved.
But the solution here is to hidden all the osf-affix firstly, and then show all of them when the width is got based calculation of the screen.
> [Feature Fix] Affix Nav bar box gets bigger when scrolled down

- website/static/js/share/results.js
Resolves [#OSF-4466].
Add a constraint so that the familyName filter is added only if the length of familyName of a contributor > 0.
> [Hotfix] removing the empty familyName filter that prevents events from showing up

- api/nodes/serializers.py
- tests/api_tests/nodes/test_views.py
- tests/factories.py
- tests/test_models.py
- tests/test_registration_embargoes.py
- tests/test_tokens.py
- website/project/model.py
Allows nodes to be made public/private through the API.
A node can be made public with the following request:
```
http -a sloria1@gmail.com:password PATCH :8000/v2/nodes/nx9d8/  data:='{"id": "nx9d8", "type": "nodes", "attributes": {"public": true}}'
```
Multiple PATCH requests with the same privacy setting will do nothing (no extra logs).
https://openscience.atlassian.net/browse/OSF-4306
> [Ready for Review] Allow making nodes private/public

- website/addons/dataverse/client.py
- website/addons/dataverse/requirements.txt
- website/addons/dataverse/settings/defaults.py
- website/addons/dataverse/tests/test_client.py
- website/addons/dataverse/tests/utils.py
Dataverse client will need to be updated.
```
pip install --no-deps -e git+https://github.com/CenterForOpenScience/dataverse-client-python.git@master#egg=dataverse
```
> [hotfix] dataverse timeout

- website/addons/base/views.py
Bail out early when a move or a copy failes to avoid file_signal calls
> [Hotfix] Failed moves/copies file signals

- tests/test_oauth.py
- website/oauth/models/__init__.py
- website/oauth/views.py
- website/static/js/addonSettings.js
- website/static/js/folderPickerNodeConfig.js
- website/static/js/oauthAddonNodeConfig.js
- website/static/js/tests/addons/oauthAddonNodeConfig.test.js
Purpose
=======
Allow users to deny access after authorizing an addon without giving an error page.
Changes
=======
* `auth_callback`, called by `oauth_callback`, will now return True if it worked and False if it didn't work
* `oauth_callback` doesn't create things it shouldn't when `auth_callback` fails
* minor improvement to `ExternalProvider.__init__`
Side Effects
=========
Can create an authenticated `ExternalProvider` at initialization, but still defaults to unauthenticated
> [Feature][Fix] Improve OAuth Architecture

- api/base/filters.py
- api/nodes/serializers.py
Makes query fields for node contributors consistent with query fields for users
middle_name changed to middle_names, fullname changed to full_name, get field name properly for queryset in base filters
None known
> Fix node contributors querysets

- website/addons/wiki/templates/edit.mako
- website/addons/wiki/views.py
- website/static/css/pages/wiki-page.css
Purpose
=======
Give users more information regarding wiki version history
Changes
=======
* previously unused `date` formatted, exposed
* dropdown item format changed to:
* `([# or 'Current']) [Firstname Lastname]: [YYYY-MM-DD HH:mm] UTC`
Side Effects
=========
None
> [Feature][Ready for Review] Wiki version dropdowns with usernames and timestamps

- website/addons/wiki/templates/edit.mako
- website/static/css/pages/wiki-page.css
Jira ticket OSF-3830
The Wiki Menu was longer when collapsed than when expanded, which pushed the header down and created wasted space on the page.
This only required one change, which was to make the height set to auto when the panel is collapsed.
The collapsed menu will still be a different height from expanded when the page has no content.
> Wiki menu - Collapsed menu is taller than expanded menu

- website/templates/project/modal_add_contributor.mako
Move the tooltip into a wrapper that allows the tooltip to still function.
Repercussions: No more than original PR.
> Disable button for contributors

- api/base/serializers.py
Refs  [#OSF-4726]
Fix super call skipping parent method. Remove redundant code already present in parent call. Avoid treating kwarg as positional.
None expected; minor cleanup.
There are some other odd usages of super calls in the API code, but they don't actively break anything. Left aside to avoid rushing scope creep.
> Minor code cleanup for method call

- api/base/views.py
- api/files/views.py
- api/nodes/views.py
- api/users/views.py
This branch includes typo fixes caught by QA's proofreading, explanation of conflict behavior for the Create Subfolder and Upload File actions, and new docs for the Node privacy updates.
> [CR] typo fixes and feature updates to BAPI docs

- tests/test_events.py
- website/notifications/events/files.py
This is not a permanent solution, as it relies on the slash at the end of a file name. Otherwise there is not enough info.
Emails about file updates should now, mostly, identify files and folders correctly when deleting.
> [Feature] Differentiate between files and folders

- website/addons/base/views.py
##Purpose
Fix typo. Resolved issue -- [#OSF-4661]
Change `is not longer valid.` into `is no longer valid`
##Side Effect
None
> [Feature Fix] Fix typo on unvalidated link 

- framework/mongo/validators.py
- tests/framework_tests/test_mongo.py
Presently, modularODM does not provide a way to restrict a field to a particular set of choices. There are some one-off validation functions, but I was not able to find a single reusable solution.
This adds a validator that accepts an iterable of choices, and returns a callable. It supports multiple datatypes, and provides an option for case-insensitive comparisons. Example use-cases include `Node.category` field and `Sanction.state` (a field in a pending PR).
- Add validator to restrict modularODM field to a set of pre-defined choices
- Also added unit tests for this and one other recently added validator.
```
class Node(...):
category = fields.StringField(validate=validators.choice_in(CATEGORY_MAP.keys()), index=True)
```
Side task; need identified while reviewing prereg PR.
> Provide choice_in validator for ModularODM models

- api/nodes/serializers.py
- tests/api_tests/nodes/test_views.py
- tests/test_models.py
- website/project/model.py
- Fixes a bug in logging title and description updates
- Consolidates node updating logic in `Node#update`. 
- Adds named constants `Node.PUBLIC` and `Node.PRIVATE`.
- Sending a PUT or PATCH to update title or description with the same content will not generate multiple logs
https://openscience.atlassian.net/browse/OSF-4668
> [Ready for Review] Fix logging of title/description updates; improve Node.update

- api/base/serializers.py
- tests/api_tests/applications/test_views.py
Fix [#OSF-4725]
ID field is not always based on the _id attribute. Rely on what the user specifies instead of hard-coded assumption.
This PR is intended to fix issues with developer application registration, which uses `client_id` as the publicly facing identifier field.
- Allow ID field to respond to whatever the specified source is (rather than hardcoded `_id` field)
- Fix broken unit tests that were suppressing our ability to detect problems with developer app registration
Once this and #4383 are merged, developer applications registration (`/v2/applications/`) should again work via the front-end.
> Fix hard-coded source in APIv2 IDField

- website/static/js/apiApplication.js
- website/static/js/tests/apiApplication.test.js
Refs [#OSF-4720].
Fix an issue where recent JSONAPI format changes caused data to be rejected by the server. Ensure that data is correctly serialized so that developer apps can be registered and updated.
- Change serialization method in data model
- Update unit tests to check additional fields
This issue was not caught because there are not presently any integration tests between the frontend and APIv2. If this issue continues to crop up in the future, we may need to revisit that strategy.
Will require further testing once id field issue is resolved ([#OSF-4725]); difficult to fully test as that issue is blocking data submission to server. Candidate fix for review in #4392 .
> [blocked] Update developer app reg UI to work with JSONAPI formatting changes

- api/nodes/views.py
- tests/api_tests/nodes/test_views.py
- Make NodeFilesList filterable
- Use httpretty rather than mocking requests.get for finer-grained control over mocked HTTP requests
https://openscience.atlassian.net/browse/OSF-4780
> [RfR] APIv2: Filterable files

- api/nodes/serializers.py
- tests/api_tests/nodes/test_serializers.py
- tests/api_tests/nodes/test_views.py
- tests/utils.py
- website/project/model.py
- Add initial unit tests for serializers 
- Add a few missing links and attributes to NodeSerializer and NodeRegistrationSerializer (partially addresses OSF-4436)
- Change NodeSerializer.parent to a `related` link rather than a `self` link (verified with Dawn that this is correct).
https://openscience.atlassian.net/browse/OSF-4771
Partially addresses https://openscience.atlassian.net/browse/OSF-4436
> [RfR] Registration links; Serializer tests

- website/static/js/share/results.js
- website/static/js/share/utils.js
Clicking Share page filters caused duplication of the results. This PR fixes the duplication bug.
updateFilters in share/utils.js now accepts a list of strings of a single string. 
The problem was that names are sometimes split into a first and last name as separate filters. Clicking a name filter made two separate updateFilter calls, which was chained to a search call, which called updateVm (updateFilter -> search ->updateVm (data added here). When the second updateFilter was called it reran the chain adding the data a second time. 
Now clicking the name filter adds the filters to an array and updateFilter is called a single time with that array. 
It is possible that changing the way updateFilter works could break the other filters. I didn't see any problems, but it is worth checking …
> Share fix for filters duplicating results

- api/base/serializers.py
- api/nodes/serializers.py
- tests/api_tests/nodes/test_views.py
Issue https://openscience.atlassian.net/browse/OSF-4602
When creating/updating a node, a dictionary is allowed as input.  We need to enforce that the type is an array.
PUTting {"tags": {"foo":"bar", "baz":"quux"}} into /v2/nodes/$node_id results in the keys of the object ("foo", "baz") being used as the tags and the values being ignored. 
Creates new ListField which overrides to_internal_value, enforcing that the data type is a list. 
Try to create a node, fill in all required fields.  For tags, put a dictionary.  
Expected response:
And if tags are the correct format, a list, node will be created successfully with tags.
> [Ready to Review] Feature/tags should be an array

- api/files/permissions.py
- api/nodes/views.py
- tests/api_tests/nodes/test_views.py
The attached patches fix two separate issues with the files API.
1.) d181651 updates NodeFilesList to handle the new JSON-API conformant WaterButler responses.  Relevant: [#OSF-4667]
2.) d65c61d fixes a permissions bug for file checkouts.  It wasn't checking whether or not the request was safe and ergo declining all non-osfstorage files.  Relevant: [#OSF-4674]
The Jira ticket for this task is https://openscience.atlassian.net/browse/OSF-4674
> [CR] Two Files API-related fixes

- package.json
- website/static/js/submissions.js
Fixes JIRA ticket [#OSF-4262]  and [#OSF-4261] where sort comparisons for columns in treebeard were causing them to sort equals
Main changes are in Treebeard but include
- correcting a section where comparison fallbcack to id was using < instead of - 
- handling cases where null or non-text/number/date examples are pushed into the comparison (there was a use case where a true/false was being sorted as text in OSF.)
none 
P.S. Sorry for the git amend mixup.
> Fix column sorting for meetings 

- website/addons/box/model.py
- website/static/js/folderPickerNodeConfig.js
Purpose
=======
Ensure 'All Files' is not displayed to the user
Changes
=======
* `replace` 'All Files' with '/ (Full Box)'
* Make sure root folder is not automatically deselected in `folderPicker` if already selected
Side Effects
=========
None
> [Feature][Fix] Box - UI Fixes

- api/base/filters.py
Purpose
------------
When filtering a list view by a boolean or serializer method field, if the field name differs from the source, it results in an Operation Failure `command SON([('rollbackTransaction', 1)]) failed: exception: no transaction exists to be rolled back`
Changes
------------
In `ListFilterMixin.get_filtered_queryset` pass the field_name to `convert_value` instead of the field source.
> [API V2] Fix ListFilterMixin for serializer & boolean fields

- api/nodes/permissions.py
- api/nodes/serializers.py
- api/nodes/urls.py
- api/nodes/views.py
- tests/api_tests/nodes/test_views.py
Issue OSF-4630
The Node Link serialization isn't correct:
"self" link should point to the Node Link Detail URL, not the target node's URL.
The target node's url should go in /data/relationships/node/links/related/href
The DELETE behavior for NodeLinkDetail is also incorrect:
The user only needs permission to remove the node link; not edit permissions for the target node
Note: Node link endpoints are currently dev-only, but this is a blocker for the public stable release.
This PR 1) makes self link pointing to Node Link Detail URL 2) moves target node's url under relationships 3)  Changes permissions for deleting node-link 4) For now, makes target_node_id write-only.  
Separate PR https://openscience.atlassian.net/browse/OSF-4804 will change how node links are created.
> [Ready to Review] Incorrect permissions and links for node links 

- README.md
Add mention of the following topics currently left out:
- Authentication
- Need to install OpenSSL (starting with OS X 10.11 El Capitan) (h/t @cwisecarver )
- Collectstatic for APIv2
I have not yet upgraded to El Capitan, and for the commands to install OpenSSL, am relying on text pasted into flowdock. (the env variables in particular look a bit odd)
Chris, can you look this over and make sure we're giving people correct advice?
> Update install docs to cover common things left out

- README.md
Builds on #4485, refs [#OSF-4923].
Continue improving the OSF install docs.
Fix cryptography install instructions (commands should be on same line) and add link to reference; h/t chris.
Make optional services sound less optional, and promote them more at the start of the install section.
> Install instructions part II

- tests/api_tests/nodes/test_views.py
- tests/test_models.py
- website/project/model.py
Sending multiple `PATCH /v2/nodes/<nid>` requests with the same category generated multiple logs, which was inconsistent with the behavior for PATCHing title and description.
Modify `Node#update` to only create a log when a field has been changed.
https://openscience.atlassian.net/browse/OSF-4664
> [rfr] Calling Node#update with same data doesn't generate multiple logs

- website/static/js/fangorn.js
Edit text in file grid information modal to correct information for non-contributors, and clarify for users how to expand folders to download as zip.
[OSF-3878]
> Fix text in file grid info modal

- website/addons/box/model.py
Purpose
=======
...so incorrect logs / deauthorizations don't occur
Changes
========
- `on_delete` defined properly
- `after_delete` logic fixed
Side effects
=========
None
> [Feature][Fix] Fix Box Deauth

- framework/auth/core.py
Purpose
=======
Users created as 'confirmed' should have an email associated with their account, as they used it to 'confirm' their account.
Changes
=======
Email address used to confirm is added to newly created confirmed user.
Side Effects
=========
None
Notes
---------
To fix preexisting broken users, run 
`python -m scripts.migration.migrate_confirmed_user_emails` 
[#OSF-4876]
> Ensure users created as confirmed have populated 'emails' fields

- scripts/googledrive/migrate_to_external_account.py
- scripts/tests/test_googledrive_migrate_to_external_account.py
- website/addons/googledrive/model.py
Purpose
=======
Adds script to migrate `GoogleDriveOAuthSettings` objects to `ExternalAccount` objects.
Note
=====
Must go in and be migrated before #4261  
Migration Steps
============
* Ensure that the `user_settings` field of GoogleDriveNodeSettings has been changed to `foreign_user_settings`
```
python -m scripts.googledrive.migrate_to_external_account
```
* [Merge 4261]
* Again, ensure that the `user_settings` field of GoogleDriveNodeSettings has been changed to `foreign_user_settings`
```
python -m scripts.googledrive.connect_external_accounts
```
[#OSF-2272]
> [Feature][Ready for Review] Migration script: GoogleDriveOauthSettings -> ExternalAccounts

- tests/test_addons_oauth.py
- website/addons/base/__init__.py
- website/addons/box/tests/test_models.py
- website/oauth/views.py
Purpose
======
Iterate over all `[Provider]NodeSettings` objects and deauthorize when revoking access.
Changes
=======
deauth logic added 
Side Effects
=========
NodeLogs will be created when appropriate
[#OSF-4991]
> [Hotfix] Ensure oauth accounts are properly deauthorized when removed via user settings

- website/addons/base/__init__.py
- website/addons/mendeley/model.py
- website/addons/mendeley/templates/log_templates.mako
- website/addons/mendeley/tests/test_models.py
- website/addons/zotero/model.py
- website/addons/zotero/templates/log_templates.mako
- website/addons/zotero/tests/test_models.py
Purpose
=======
Fixes bug introduced in #4518 
Citations style addons didn't implement `[Addon]NodeSettings.deauthorize()`
Changes
=======
* `.deauthorize`, deauth logging added to citations addons
* Add basic `.deauthorize` to `website.addons.base.AddonOAuthNodeSettings`
* Add `.deauthorize` tests for citations addons
Side Effects
=========
None
[#OSF-5030]
> [Hotfix] Ensure proper oauth deauthorization for all new-oauth addons

- website/conferences/views.py
It is to show full name when user don't set family name. For some languages, such as Chinese and Japanese, people usually don't separate their family name and first name with space. In OSF, if there is no space within user name, it will assume there is no family name. 
Currently, OSF meeting only show author's family name. Therefore, for user who use those language, there is no name to be displayed (blank).
Resolve [OSF-4899]
The change is simple here. Just show full name if there is no family name filed.
None
> [Feature Fix] [OSF Meeting] Show full name when user don't set family name

- website/templates/footer.mako
OSF-4774 made TOP Guidelines sentence case, but this is incorrect since TOP Guidelines is a proper noun
> Capitalized TOP Guidelines

- tests/test_elastic.py
- tests/test_models.py
Some search tests were failing semi-randomly. I think this is because ES isn't updating fast enough for our assertions.
Skip problematic tests.
> Skip problematic search tests

- api/nodes/views.py
- api_tests/nodes/views/test_node_links_detail.py
Issue https://openscience.atlassian.net/browse/OSF-5003
Small bug - When attempting to delete a node link that doesn't belong to the current node, a 404 NotFound should be raised instead of a 400.
Returns 404 instead of 400
Create a `node A`, and then create a node link to `node B`, called `node link C`.
Create a separate `node D` and create a node link to `node E` called `node link D`.
Then send a DELETE request to /v2/nodes/{node_A_id}/node_links/{node_link_D_id}/
Although `node_link_D` exists, it is not a pointer on `node_A`.  You should get a 404 Not Found.
> [Ready to Review] Raise NotFound instead of ValidationError when deleting incorrect node link 

- website/static/js/pages/project-base-page.js
- website/static/js/pages/project-registrations-page.js
- website/static/js/registrationUtils.js
- website/templates/project/registrations.mako
registrations.mako got mangled at some point and the KO data-binding hierarchy was broken. This PR moves all components to their correct homes and makes the page work again.  
- Pass RegistrationManager an option create button to listen for clicks
on
- move components into the correct binding scope
> Fix data-binding heirarchy on registrations.mako

- website/search/search.py
Calling update_node_async while still in a transaction context caused issues with celery tasks getting a stale version of a Node's state. In particular when adjusting privacy `is_public` was still False in the database and the ES document was not being created.
Use `enqueue_task` to defer the celery task until after the transaction is committed.
None
> Use enqueue_task to run ES update_node_async

- website/search/elastic_search.py
- website/static/js/pages/file-page.js
` inv migrate_search ` needs to be run after this is merged, so that the mapping of tags for files can be updated.
This changes private parent nodes name to a not hyperlinked ` --private project-- `, and it adds NOT-ANALYZED to tags
> Make private parents not show name

- website/static/js/search.js
Due to a bug in the search tag removal logic, if a user tried to remove a tag that is was a substring of another currently active tag (e.g. 'bio' and 'biosphere'), clicking remove on the substring tag would remove the active tag. (Clicking X on 'bio' removes 'biosphere')
- use regexp capture group to check actual tag equiavalence rather than
just a substring match
[#OSF-5084]
> Update search tag removal logic.

- website/static/js/search.js
QA discovered that if a user navigates to page 2 or beyond of a search result, then clicks a license filter with less than one page of results, they get trapped on that later page without the ability to go back or forward a page.
Set currentPage = 1 when search license filter changes
> [RfR] Fix Search license filter pagination bug

- website/project/views/node.py
Since public projects can be anonymous, warning messages in both the Contributors page and the "make public" modal should be removed. See screen shots.
In the node.py file, lines to show these warning messages are deleted. See screen shots for results.
> OSF-4850 Removed warning messages in Contributors page and modal.

- tests/test_registration_embargoes.py
- website/project/views/register.py
Purpose
------------
Fixes [OSF-5094] - after finishing registration steps, page redirects to the last registered component
Changes
------------
Use a variable name other than `node` when iterating through node children so as to not reassign the node.
> [hotfix] Redirect to project registrations page after creating a new registration 

- framework/auth/core.py
- tests/test_mailchimp.py
- tests/test_models.py
- tests/test_views.py
- website/mailchimp_utils.py
- website/profile/views.py
Purpose
-----------
Fixes JIRA ticket [OSF-5031]
If User A merges with User B (who is subscribed to the OSF general mailing list), User A is subscribed if they are not already and User B is unsubscribed. However, User B receives the mailchimp unsubscribe email. 
Changes
------------
Set `send_goodbye` to `False` when unsubscribing due to merging user accounts to prevent the merged user from receiving an email.
> [Ready to Review] Do not send merged users mailchimp unsubscribe email

- website/static/js/osfHelpers.js
In moment.js, `utc()` can't process the date format created by [Dropbox API](https://www.dropbox.com/developers-v1/core/docs) in Safari and IE. It is something like -- `Sat, 21 Aug 2010 22:31:20 +0000`. Therefore, it is shown as invalidate and not displayed.
Resolve [OSF-4294]
After testing, I find  `moment()` is more stable to accept all kinds of string date, as it mentioned in docs, 
>When creating a moment from a string, we first check if the string matches known ISO 8601 formats, then fall back to new Date(string) if a known format is not found.
So I choose to use `moment()` to create date object firstly and then apply `utc()` to get UTC time object. 
Related Stackoverflow question (Asked by me) -- http://stackoverflow.com/questions/33508049/moment-utc-doesnt-work-in-ie-and-safari …
> [Feature Fix] Convert string into date with moment()

- api/nodes/serializers.py
Purpose
-----------
We are mixing in registrations to the nodes endpoint. We neglected to add the ability to filter those out. Add that ability back in. **Needed for OSF Offline**
Changes
------------
Add a line to the node serializers allowed filters
Side effects
None
> Filter by registration
