CenterForOpenScience/osf.io

- website/static/js/share/results.js
When loading data from the SHARE Postgres API, we use the document ID from the SHARE document to create a unique div ID, so that clicking show and hide, and switching between tabs, only affects the one shown tab. This changes that div ID to also escape and replace forward slashes
Include forward slashes in the list of characters to be replaced with dashes when generating unique div IDs for retrieved SHARE data
None anticipated, as it is only for generating div IDs for SHARE data
[#SHARE-204]
> on SHARE Search Page, also escape / for creating data divIDs

- website/addons/osfstorage/views.py
The OSF was sending a bogus version of -1 to WB for file metadata
requests, causing WB to respond with null for the file hashes.  If not
provided, the version should default to None.
> [hotfix] restore missing hashes to osfstorage file metadata

- requirements/release.txt
pyrax v1.9.5 corrects issue with python-novaclient import issue.
https://github.com/rackspace/pyrax/issues/575
> [feature] bump pyrax version to fix dependency

- website/static/js/search.js
Interestingly, the 'g' flag for JS regexp causes the RegExp instance to
yeild matches at every call of ReExp#exec. This works by incrementing an
internal lastIndex count. Using RegExp#test also increments this counter
even though it returns nothing. So in this code, calling test was
incrementing the RegExp's match counter, and was causing the subsequent
exec call to return null under some circumstances.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec#Finding_successive_matches
Use assignment as condition for the tag removal while loop.
> Update search tag removal (again)

- tests/test_conferences.py
- website/conferences/model.py
- website/conferences/views.py
- website/routes.py
- website/static/js/pages/meetings-page.js
- website/templates/public/pages/meeting_landing.mako
The meetings page was taking many seconds to load because all
submission records needed to be loaded before page loaded.
This patch adds an API endpoint for loading the data for the
All Submissions tab asynchronously. This improves the load time
~5x.
Also caches the number of submissions in Toku so they can be displayed
on the "All meetings" tab.
Partially addresses OSF-4989
> Vastly improve OSF4M load time

- api/files/serializers.py
- api/files/views.py
- api/nodes/views.py
- api_tests/files/views/test_file_detail.py
OSF Offline needs the hashes of files stored on osfstorage.  Add a new
'extra' object to the file serializer, with a 'hashes' object
containing them.  This mimics the response format of waterbutler.
Hashes are currently only provided for files stored on
osfstorage. Folders and other providers will return null.
[#OSF-5200]
> [CR] api: add md5, sha256 hashes to FileDetails

- website/static/css/pages/project-page.css
- There is different formatting of project description logged in versus logged out. It is expected that there should be no formatting associated with the description. 
-Changes in project-page.css
None
Closes: 
- https://github.com/CenterForOpenScience/osf.io/issues/4097
- JIRA ticket: https://openscience.atlassian.net/browse/OSF-4155
> [hotfix] Different formatting of project description logged in vs. logged out

- website/templates/project/register.mako
- website/templates/project/retracted_registration.mako
Draft Reg. changed the way Node.registered_meta and Node.registered_schema work, and consequently the mako templates for showing registration supplements was updated. The retraction mako templates duplicate this logic and were not updated.
Update the retraction template logic
[#OSF-5247]
> Update retraction template to account for new Node.registered_meta/schema format

- api/base/serializers.py
- api_tests/nodes/views/test_node_detail.py
Solves issue https://openscience.atlassian.net/browse/OSF-5249
Corrects bug caused by https://github.com/CenterForOpenScience/osf.io/pull/4629
Above PR raises SkipField in multiple places when URL is none.  However, this causes comments relationships link to disappear.  When going to fetch `get_unread_comments`, if there are 0 comments on a node, URL is none and SkipField is raised.  The comments relationships link disappears.
Small change to `def _url_val`. 
`if not url and url != 0:`  ==>  comment link is restored.
> JSON API valid URI's fix 

- api/base/requests.py
- api/base/views.py
- api/nodes/serializers.py
- api/nodes/views.py
- api_tests/collections/test_views.py
- api_tests/nodes/views/test_node_detail.py
- api_tests/nodes/views/test_node_links_detail.py
- api_tests/nodes/views/test_node_links_list.py
Issue https://openscience.atlassian.net/browse/OSF-5250 
- Auto-embeds should check to ensure that it's not auto-embedding a ListView 
- Only two resources auto embedded: contributors:user-detail and node-links:node-detail. 
- Auto-embeds should happen regardless of level.
Node Contributors > user and Node Links > target node will be automatically embedded. 
Nodes > contributors and nodes > node links will NOT be automatically embedded.  
Users embedded in contributors:
Target node embedded in node links:
Multiple levels of embeds:
`http://localhost:8000/v2/nodes/3fnkr/?embed=contributors`
> [Ready for Review] Change which resources are automatically embedded.

- website/notifications/utils.py
When uploading or modifying files with utf8 characters in their names,
some providers will encounter 500 errors when posting to the waterbutler
logs endpoint.  This occurs because the file events notifier prepends
the file name to the event, and the `to_subscription_key` method in
`website/notification/utils.py` expects ascii-only events.  This patch
updates `to_subscription_key` to support utf8 events.
> support utf8 subscription keys

- api/nodes/serializers.py
Issue https://openscience.atlassian.net/browse/OSF-5284
The self link had been removed in NodeContributorSerializer, so it used the default, obj.get_absolute_url() to formulate the self link. When embedding, this caused the embedded user and the contributor self links to be the same.
Restoring `'self': 'get_absolute_url'` to node contributors links will allow the self-link to be generated properly.
> [Ready to Review] Restore self link using get_absolute_url method.

- website/addons/citations/provider.py
- website/addons/mendeley/model.py
- website/addons/mendeley/tests/test_views.py
- website/addons/mendeley/views.py
- website/addons/zotero/model.py
- website/addons/zotero/tests/test_models.py
- website/addons/zotero/tests/test_views.py
- website/addons/zotero/views.py
- website/static/js/citationGrid.js
- website/static/js/citationsNodeConfig.js
- website/static/js/folderPickerNodeConfig.js
- website/templates/project/addon/node_settings_default.mako
Old fix had a bug during importing from account in project settings page. This fix checks for valid credentials upon creating of node settings and tells user to fix in settings if something is wrong while disabling importing/deactivating account from project settings page.
> [Bug Fix] Zotero/Mendeley credentials error redux

- website/templates/project/settings.mako
Purpose
-
As noted on the [Jira Ticket][1], the layout on the project settings page was messed up and one panel was wrapping all of the other panels.  This PR fixes this layout issue.
Changes
-
Added a missing </div> tag and slightly restructured the panel (it had two panel-body elements which created a bunch of dead white space) to make the top panel be separate from the others and to be aesthetically pleasing
Side Effects
-
Since this PR is so small there should be nothing.  The only one I can think of would be messing up the knockout binding but this should not be an issue as it just adds in two unbound elements to the existing binding.  These elements should not be messed up as a result of being bound however.
[1]: https://openscience.atlassian.net/browse/OSF-5192
> Fixed project settings layout

- api/logs/serializers.py
Purpose
-----------
When /v2/nodes/logs was added, we didn't go too crazy with the params serialization. But in that I missed the addons params. This adds those params in. Closes https://openscience.atlassian.net/browse/OSF-5347
Changes
-----------
New fields mostly. A couple parameters are accessed differently than before, such as dataset becoming data_set, github.user becoming github_user, and so on. Templated node is a relationship link rather than having serialized data.
Side effects
-------------
None
> Add missing node logs parameters

- package.json
- website/static/js/fangorn.js
https://openscience.atlassian.net/browse/OSF-4829
Provide a report of how many files were successfully uploaded, and why others weren't .
For this first iteration, the user will receive a modal showing which files uploaded successfully and which didn't if the total files uploaded exceeds 3. The modal is shown below.
1. The behavior is the same for all providers and will show the name of the file as it was uploaded, rather than potential rename (such as file.txt (1)). 
2. Files that fail will have an 'X' next to their names and a little 'i' that should show what caused the file to fail on tooltip when the icon is hovered. 
3. Files that succeed will have a check mark next to their names, and the name should be a hyperlink (blue) to the file detail page.
QA, I was unable to test for case …
> Large number of files upload 

- website/templates/project/project_header.mako
#OSF-4851
No longer show project header bar "Registrations" and "Forks" links for projects that are anonymized.
Add logic to check for anonymous links to project_header.mako
None known
Test:
Situation - Can Reg and Forks be seen on header bar?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Anonymous private link - No
Not-Anonymous private link - Yes
Normal link - Yes
> Do not show Registration and Fork links for anonymized projects

- website/templates/project/registrations.mako
see: https://openscience.atlassian.net/browse/OSF-5348
- only show "You can start a new registration..." text if user is a project admin
> [Hotfix] Registration Language

- api/base/filters.py
- api/comments/serializers.py
- api/comments/views.py
- api/nodes/views.py
- api_tests/nodes/views/test_node_comments_list.py
Purpose
-----------
Addresses JIRA [OSF-5330]
Add ability to filter by a relationship field's object id. This is required for incorporating the API v2 comments routes into the commenting feature in development. 
E.g. `/v2/nodes/node_id/comments/?filter[target]=target_id`
Changes
------------
- Update `filters.py` to handle `RelationshipField` and `TargetField` 
- Make comment `target` a filterable field
- Test that filtering by `target` works
I included comment filtering in this PR so that there could be something to test this filtering with. 
Note to QA: Right now, you can only filter by target=node_id, since the node comments endpoint only lists top-level comments on the node. With the commenting feature, this endpoint will return all comments and users will also be able to filter by …
> [Feature][Ready for Review] Filter by a relationship field's object id

- website/static/js/nodesPrivacy.js
I was failing out of bulk api calls, and I think it was causing some grief.  Now the fail method is at the end of all the requests.
> [feature] put fail at end of call for very large projects

- website/static/js/pages/sharing-page.js
Purpose
-
There was a bug in which the responsive table/cards didn't work if the user was not an admin
Changes
-
Previously the window load and resize functions called `privateLinkTable.viewModel.onWindowResize();`
however `privateLinkTable` is only defined if the user is an admin.  To fix this I wrapped the calls with 
`if (!!privateLinkTable)`
Side Effects
-
Should be none
> [Feature] Small bug fix for contrib page

- website/static/css/style.css
- website/templates/public/pages/help/licenses.mako
The anchor layer is helping the anchor links not hide headers so it's pushed up but this ends up covering the layers above which leads to links not being clickable. This was an overall problem and not related to licenses but the z-index organization fixed the layering issue. 
-Added z-index to anchor div css, this is the most unobtrusive method I can think of and should be a good long term solution
- Space was added between here: and link in licenses.mako
I checked to see that the other div arrangements also still work after the anchor css change and that menu divs still work (for licenses and others) and bring the user to the proper location. 
Fixes issue talked about in here: https://github.com/CenterForOpenScience/osf.io/pull/4697
> Fix anchor div blocking content and license spacing

- website/project/metadata/prereg-prize.json
- website/templates/project/registration_editor_templates.mako
resolves: https://openscience.atlassian.net/browse/OSF-5329
Explicitly mark questions as optional or required, and add tooltip to required questions.
> Add tooltip to '(required)' text on Prereg schema

- website/static/css/pages/contributor-page.css
- website/templates/project/contributors.mako
Purpose
-
There was a weird issue where the table borders were flickering on Safari.  This PR seeks to fix that.
Changes
-
Changed how the sortable-bars were implemented and got rid of some relative positioning.
Side Effects
-
Could result in small UI issues elsewhere but I haven't seen any effects so far.
> [Feature] Fixed contributors page for Safari (the flickering borders issue)

- scripts/analytics/depth_users.py
Purpose
-----------
Make depth_use statistics more accurate.
Closes https://openscience.atlassian.net/browse/OSF-5032
Changes
------------
In the analytics script, no longer count the creation of a dashboard collection towards the depth_use statistic if the dashboard creation is the user's first NodeLog, since all it really means is that the user logged in after some date in the Autumn of 2014. 
Running the script locally, before the change I had
```
fullname         email                logs
---------------  -----------------  ------
Brian J. Geiger  bgeiger@pobox.com      48
```
after the change
```
fullname         email                logs
---------------  -----------------  ------
Brian J. Geiger  bgeiger@pobox.com      47
```
Side effects
The user's activity points …
> Remove dashboard node creation from depth_use count

- tests/test_views.py
- website/project/model.py
- website/project/views/contributor.py
- website/templates/emails/contributor_added.txt.mako
Continuation of PR #4638
Description from @njantrania: 
>Purpose
>The purpose of this was to change the email sent to registered contributors when notifying them about being added to a project so that the email would say who added them.
>Changes
>The change made was to add the name of the author of the project to the email so that the recipient could tell who added them.
Note: A user should only get this email if a user added them to a project. However, `add_contributor(s)` gets called in many places where we want to add contributors to a project automatically (e.g. OSF for meetings) so it's good to have a default message in case these emails get sent when they're not supposed to.
> [Ready for Review] Feature: Update add contributor email

- website/static/js/filepage/index.js
When clicking view file on github, it will always lead user to the master file link. However, github has different branches, and therefore the file linked is not the one rendering in MFR.
In this PR, it will create the correct link url for file (with current branch).  
Firstly, get the url for the branch. And then use ajax and get file object from waterbulter. The ajax ur is something like -- `http://localhost:7777/data?path=%2Fmain.py&provider=github&nid=9j5hu&branch=redesign` 
In this object, we can get the webView url from file object.  Then assign it to  `window.contextVars.file.urls.external`
None. This is limited to github.
> [Feature Fix] GitHub show wrong branch file

- api/registrations/urls.py
- api/registrations/views.py
- api_tests/nodes/views/test_node_alternative_citation_list.py
- api_tests/nodes/views/test_node_alternative_citations.py
Purpose
------------
Update alternative citations to be consistent with #4728, which creates separate endpoints for registrations.
Changes
------------
Added routes for viewing list/detail for alternative citations on registrations and updated tests.
> Add alternative citation routes for registrations

- api/base/filters.py
- api/base/serializers.py
- api/base/views.py
- api/nodes/serializers.py
- api_tests/base/test_filters.py
- api_tests/nodes/views/test_node_list.py
Issue https://openscience.atlassian.net/browse/OSF-5041
Allows for the equivalent of a bulk GET request through filtering (for example, if I want to request two nodes, specifically).  The reason we are not doing bulk GET requests is that putting JSON in the request body of a GET request is discouraged.  So for bulk GET capacity, we are implementing filtering on multiple ids.
Allows return of multiple resources via a comma-separated list of values in the query_param.
For example, the following two node id's are requested in the following URL:
`/v2/nodes/?filter[id]=3z4tf,vatpw`
This turns into the query, `'_id', 'in', ['3z4tf, 'vatpw']`
The response will contain representations of the two nodes, `3z4tf` and `vatpw`.
**Example:**
url = `v2/nodes/?filter[id]=69wkq, y3mxq, aegu6,12345`
The …
> [Ready to Review] Bulk GET special case filtering on ID

- website/static/js/contribAdder.js
When using the ContribAdder in async mode the list of current contributors was not being updated, and consequently you could "add" a contributor more than once (if the page is not reloaded). 
Update the list of current contributors so newly added contributors appear added in the UI.
> Update contributors list if using ContribAdder in asnyc mode

- website/static/js/nodeControl.js
- website/static/js/pages/project-dashboard-page.js
- website/templates/project/project.mako
Database locking issues are causing APIv2 requests to fail.
Until these issues are resolved, the UI for making multiple projects
public/private will be commented out.
The nodesPrivacy JS module and the v1 route (/project/<pid>/tree/) are
untouched.
@billyhunt @brianjgeiger
> Revert public/private UI from #4487 for now

- website/static/js/project.js
To give a more obvious visual notification that a fork was successfully created 
* Add bootbox alert on a successful fork that redirects to the new fork after being closed or hitting 'OK'
* Addresses #4118
* User has to click before being redirected to their new fork
> [Fix] Success alert for forks

- website/static/css/pages/profile-page.css
- website/templates/include/profile/jobs.mako
- website/templates/include/profile/schools.mako
Purpose
-
Fixes [OSF-5416][1].  Also, it looked odd to have a max width of 75% for non-expandable card titles so this was fixed as well
Changes
-
Removed `word-break: break-all` from the card headers.  Removed `class="header-content"` from unexpandable cards.
Side Effects
-
Its possible that this could cause slight UI issues but I highly doubt it and have not seen any.
[1]: https://openscience.atlassian.net/browse/OSF-5416
> [Feature] Fixed line break issues on employment/education cards

- scripts/prereg/migrate_metadata_for_uploaders.py
- scripts/tests/test_migrate_metadata_for_uploaders.py
- tests/test_registrations/test_archiver.py
- tests/utils.py
- website/project/metadata/prereg-prize.json
Recent changes with the impl. of file uploaders in the Prereg registration schema require existing draft metadata to be supplemented. 
Additionally, some questions that did not previously have uploaders now have them, and consequently saved data for those questions needs to be updated.
> Add script to migrate metadata for Prereg submissions

- website/addons/wiki/static/dragNDrop.js
Purpose
-
I made a rookie mistake and had the wrong variable name in one place that resulted in some dead image links.
Changes
-
Renamed the variable probably
Side Effects
-
Hopefully no more dead image renders
> Fixed issue with some image links being dead

- tests/test_models.py
- tests/utils.py
- website/project/model.py
- website/templates/project/project.mako
Fixes: https://openscience.atlassian.net/browse/OSF-5429
- disable set_privacy UI in project.mako if Node is_registration
- raise NodeStateError in Node#set_privacy if Node
is_pending_registration
- Update mock_archive to support Emabargoes
- Add tests for Node#set_privacy behavior
> Make sure pending registrations cannot be made public

- website/prereg/__init__.py
- website/prereg/utils.py
- website/prereg/views.py
- website/project/model.py
- website/templates/emails/prereg_challenge_accepted.html.mako
Since Node.registered_schema became a list field some of the Prereg code had not been updated.
Also there was a non-acii character in the prereg_challenge_accepted email template.
> Fixes to DraftRegistrationApproval flow

- website/project/metadata/utils.py
- website/static/js/registrationUtils.js
Natasha noticed slowness when loading the project registrations pages, in particular with how long the "New Registration" button is disabled (this is done while the available MetaSchemas are loading). 
see: https://openscience.atlassian.net/browse/OSF-5466
- Enable the "New Registration" button as soon as the MetaSchemas are loaded (don't wait for drafts too)
- Simplify Draft initiator serialization (this was the slowest part of draft serialization)
> Faster draft loading

- website/static/js/osfLanguage.js
- website/static/js/registrationUtils.js
- website/templates/project/registrations.mako
The changes I made in https://github.com/CenterForOpenScience/osf.io/pull/4805 cause the loading spinner to disappear prematurely from the "Draft Registrations" tab. This fixes that.
Break loading into loadingSchemas and loadingDrafts to isolate the two states. Use loadingDrafts to control the visibility of the loading spinner. 
Also make the "New Registration" button text "Loading ..." while loading, and add fail callbacks to the requests to fetch DraftRegistrations and MetaSchemas
> Fix OSF loader for DraftRegistrations

- website/static/css/pages/project-page.css
- website/static/css/style.css
Purpose
-
There had been a previous PR to fix the project nav bar however the necessary CSS was only being applied on one page (and some of the CSS is now duplicated by base.css).  This PR fixes that.
Changes
-
Deleted redundant CSS and then moved the necessary CSS to style.css so that it is applied to each page that needs it.
Side effects
-
Potential to break this or other UI stuff.
[#OSF-5456]
> [Feature] Fixed issue with scroll bar and content not being pushed down

- website/project/model.py
- website/templates/emails/prereg_challenge_accepted.html.mako
- website/templates/emails/prereg_challenge_rejected.txt.mako
The Prereg email formatting was broken. Also a bug in the rejection logic caused rejection emails to go to the Prereg admin rather than the draft initiator
- fix email formatting
- send rejection email to draft initiator
We should restart the celery worker.
> Update Prereg Emails

- api/base/filters.py
- api_tests/base/test_filters.py
- api_tests/nodes/views/test_node_list.py
- api_tests/nodes/views/test_node_logs.py
Issue https://openscience.atlassian.net/browse/OSF-5469
Extends Sam's PR https://github.com/CenterForOpenScience/osf.io/pull/4246, to add 'not equal', `ne`, to list of comparison operators in filter.
Allows filtering on `not equal`.  For example: 
`/v2/nodes/3e5vn/logs/?filter[action][ne]=comment_added`.
This gives me all log actions on node `3e5vn` whose action does not equal `comment_added`.
> [Ready to Review] Feature/API filter on `not equal`

- website/static/js/contribAdder.js
The v1 call to get_contributors was omitting non-bibliographic contribs,
and consequently those users were appearing as addable in the UI.
see: https://openscience.atlassian.net/browse/OSF-5461
Use the v2 endpoint for fetching Node contributors.
> Use APIv2 to fetch current list of contributors in contribAdder

- api/files/serializers.py
- api/files/views.py
- api/nodes/views.py
- api_tests/files/views/test_file_detail.py
Purpose
----
This PR fixes four minor closely-related tickets for changes to the V2 FileSerializer.  Two new attributes, `materialized_path` and `date_created`, were added.  Two existing attributes, `date_modified` and `extra.hashes`, were being pulled from the file versions, which non-osfstorage providers lack.  For these, we can use the metadata history to get this information.
*If desired I can split these up into separate PRs, but they're all pretty small, so I figured they'd be better together.*
Changes
----
* added `materialized_path` attribute to show unix-style path for entity relative to provider root.
* added `date_created` attribute. For osfstorage, `date_created` is the timestamp when the file was first uploaded to osfstorage.  For other providers, `date_created` is the …
> [RfR] add fields to V2 file serializer, improve non-osfstorage support

- website/project/model.py
Purpose
-----------
NodeLogs is slower than it should be. One reason is because, whenever you get the aggregate logs for a node, it's doing an 'in' query on an unindexed field. This should fix that.  Functionality should be the same, but it should be faster. 
Changes
------------
Modified the NodeLogs model to include an extra index.
Side effects
If anything, it's *possible* that forking or registering large/complex projects will become slower.
> Add an index for the backref connecting NodeLogs to Nodes

- website/static/js/registrationUtils.js
- website/static/js/tests/registrationUtils.test.js
- website/templates/project/registration_editor_templates.mako
There was a general lack of user feedback when adding/saving comments.
- only add a comment to the UI once saved sucessfully
- block the commenting UI while a comment is saving
> Only append comments if actually saved

- api/base/serializers.py
- api/logs/serializers.py
- api/users/serializers.py
- api_tests/comments/views/test_comment_detail.py
- api_tests/nodes/views/test_view_only_query_parameter.py
@sloria this fixes the broken test on staging. https://openscience.atlassian.net/browse/OSF-5488
Purpose
-----------
Ensure all use of a relationship to user:user-detail and nodes:node-registrations are prevented from being exposed when anonymized.
Changes
------------
Replaces broken mixin with a blacklist feature.
Side effects
Shouldn't be any. There's a test to ensure when forks are added, if they are called 'forks', will need to be added to the blacklist.
> Fix anonymized comments

- website/templates/project/registrations.mako
Fix inconsistencies between New Registration button and New Fork button
- New Registration button stays in the top right on small screens
- New Registration button has btn-success like New Fork
Old:
New:
```python 
None 
```
[OSF-5178]
> [Ready for Review] Fix inconsistencies between New Registration button and New Fork button

- scripts/prereg/approve_draft_registrations.py
Changes to how we were queuing celery tasks apparently broken the 'approve_draft_registrations' script for Prereg testing.
Make sure celery_teardown_request gets called in DraftReg auto-approve script
> Fix approve_draft_registrations testing script

- website/addons/base/views.py
- website/templates/include/comment_template.mako
- website/templates/project/view_file.mako
Purpose
----------
Address remaining non-blocking code review comments from #4856
Changes
------------
- Removed tooltips for comment action icons (edit, reply, delete and report) 
- Removed `allow_comment` flag
- UI fixes to the toggle comment replies button
- Move "Comment deleted" text to the left and the "+" toggle to the right
- Make the "+" black 
- Make the cursor for the "+" a pointer
> File comment fixes

- website/static/js/comment.js
- website/templates/include/comment_template.mako
Purpose
-----------
Addresses https://github.com/CenterForOpenScience/osf.io/pull/4806#issuecomment-168773334 
Changes
------------
When a user clicks "Restore" for a deleted comment, remove the additional confirmation step.
> Remove restore comment confirmation

- tests/test_registrations/test_views.py
- website/project/views/drafts.py
Prereg challenge submissions that were approved but had failed registrations were not editable from the UI. 
Modify `check_draft_state` to ignore the approval state of drafts with deleted registrations.
> Let Failed Registration Drafts be editable again

- tests/test_conferences.py
- website/conferences/views.py
- website/routes.py
- website/static/js/pages/meetings-page.js
- website/templates/public/pages/meeting_landing.mako
The endpoint is too inefficient to be used in production at the
moment; requests for All Submissions are timing out. This removes
the UI and the route for viewing All Submissions
see OSF-4756
> [hotfix] OSF4M: Remove "All Submissions" for now

- api/base/serializers.py
- api/comments/serializers.py
- api_tests/nodes/views/test_node_comments_list.py
Purpose
-----------
Allow html tags supported by v1 for comments.
Changes
------------
Put sanitization in a method separate from `is_valid` (`sanitize_data`) and override in the comment serializer to use `bleach.clean` when sanitizing comment content (and `strip_html` for everything else).
ALLOWED_TAGS = [
'a',
'abbr',
'acronym',
'b',
'blockquote',
'code',
'em',
'i',
'li',
'ol',
'strong',
'ul',
]
> Sanitize comment content with bleach.clean

- website/static/js/comment.js
Purpose
------------
When unreporting a comment and immediately reporting it again, the request fails because the message is null. Also, the form re-appears after unreporting a comment when it should not.
Changes
-------------
Make `self.abuseText` default to an empty string in the request payload. Also, set `self.reporting` to false after successfully reporting a comment so that the form does not re-appear when clicking unreport.
> Fix reporting abuse error

- tests/test_registrations/test_views.py
- website/project/views/drafts.py
- website/static/js/osfLanguage.js
- website/static/js/registrationUtils.js
See: https://openscience.atlassian.net/browse/OSF-5520
Drafts with failed or rejected registrations could not be deleted. The server was giving a 403 response and the JS failed silently.
- Let drafts with failed or rejected registrations be deleted
- Add unit test for this behavior
- Add .fail handler to deleteDraft JS call
> Let Failed Registration Drafts be deleted

- tests/test_registrations/test_embargoes.py
- tests/test_registrations/test_registration_approvals.py
- tests/test_registrations/test_retractions.py
- website/project/model.py
If the initiator of a registration was not an admin on any of the
project's components, our registration approval script would fail due
to a permissions error.
With this patch, admins on components will be sent an email to
approve or disapprove registrations of the parent project.
paired with @samchrisinger
See OSF-5547
> [hotfix] Fix bug when approving registrations of projects with private components

- tests/test_addons.py
- website/addons/base/views.py
We allow Prereg admins to download files from projects with a
DraftRegistration using the Prereg Challenge schema. This check needs to
be expanded to allow downloading on those nodes, as well as any of their
descendant node.
- also check a node's parents when seeing if the node has an associated Prereg DraftRegistration
- add a test for the new behavior
> Check parent nodes when letting Prereg admin download files

- tests/factories.py
- tests/test_registrations/test_embargoes.py
- tests/test_registrations/test_registration_approvals.py
- tests/test_registrations/test_retractions.py
- tests/test_registrations/test_sanctions.py
- website/archiver/tasks.py
- website/project/model.py
- website/project/views/node.py
- website/project/views/register.py
- website/tokens/__init__.py
- website/tokens/handlers.py
- Approval links go to registered node
- Disapproval links go to original node
- Allow registered components to be made public when initiator
doesn't have access to private components (as long as component
admins approve)
paired with @samchrisinger
> [hotfix] Fix approval/disapproval links for component admins

- website/addons/osfstorage/tests/test_models.py
- website/files/models/base.py
- website/project/signals.py
- website/project/views/comment.py
- website/routes.py
- website/settings/defaults.py
- website/signals.py
- website/static/js/fangorn.js
When files move within or between external providers and/or between nodes, update the file comments so that they move with the file. Comments do not move when a file gets copied.
> Update comments on file move

- website/templates/public/pages/faq.mako
Move anchor tag in OSF FAQ page from div to span similar to use in OSF Getting Started page in order to make links on FAQ page work.
[OSF-5532]
> Fix links on FAQ page

- api/registrations/serializers.py
- api/registrations/urls.py
- api/registrations/views.py
- api_tests/nodes/serializers/test_serializers.py
Purpose
-----------
Fix registrations api v2 endpoint so new relationships point to registrations rather than nodes. This will make the new Dashboard work better.
Closes https://openscience.atlassian.net/browse/OSF-5556 
Changes
------------
* Point parent, logs, and root to their registrations urls instead of nodes urls
* Modify registration serializer test to try to catch these cases beforehand. The serializer test could stand to be upgraded to have a more complicated test registration, but it's a lot better than it was before. Currently it is a standalone registration, and something that is a child of a foked templated project would be better. Other variations would help as well. 
Side effects
None
> Point registration logs to registrations collection

- website/static/js/registrationUtils.js
see: https://openscience.atlassian.net/browse/OSF-5506
The "Unseen comments" badge on the Draft Registration list was not going away, even when a user viewed the comments. 
- Actually use the saved comment data to populate Comment.seenBy
- When viewing the comments on a given page, save the drafts if some previously unseen comments are seen.
> Fix Prereg "Unseen comments"

- api/base/utils.py
- api/base/views.py
- api/nodes/views.py
- api/registrations/views.py
- api/users/serializers.py
- api/users/views.py
Purpose
-----------
Ensures that the `/v2/users/{user}/nodes/` and `/v2/users/{user}/registrations/`include only the appropriate node types, especially to ensure that the nodes endpoint doesn't include registrations.
Closes https://openscience.atlassian.net/browse/OSF-5555
Changes
------------
* Made a common location for a standard nodes request, so if 'what a node is' changes, it will be updated both in the node list and the users node list.
* Added a /registrations/ link to the base view
* Ensured that the registrations/children view actually returned proper information
Side effects
List views for nodes and node-like things will not include components that a user sees only because they are the administrator on the node. They will still have access to the node, but won't …
> Remove registrations from nodes dashboard

- website/static/js/comment.js
Purpose
-----------
Addresses the issue reported in https://openscience.atlassian.net/browse/OSF-23. 
If a user is logged in and is viewing a project that they are a contributor on using an anonymous VOL, all of the commenters are anonymized. But when the user comments, their name and gravatar appear until refreshing the page.
Changes
-----------
If a contributor is logged in and is viewing his own project through an anonymous VOL, if the user leaves a comment, anonymize their name and do not show their gravatar.
> Do not show contributor gravatar when commenting with anonymous link

- tests/test_notifications.py
- website/notifications/emails.py
Purpose
------------
Fixes JIRA ticket 5558
"Comment reply" notification emails are not getting sent.
Changes
------------
In addition to checking subscribers for node-level subscriptions, check user-level subscriptions as well because "comment replies" is specific to the user, not the project.
> Fix comment reply notification emails

- tests/base.py
- website/project/views/comment.py
- website/routes.py
- website/static/js/fangorn.js
Purpose
-----------
- Refactor logic for updating comments on file move to use the `file_updated` signal sent when a waterbutler log is created on the OSF. 
- In addition to updating comments when a file moves, update comments when a file is renamed
- Update the `Node.commented_files` field with the new file id (fixes issue where comments on files that were moved could not be deleted)
> Use file_updated signal to update comments on file move and rename

- website/files/models/base.py
- website/project/model.py
Purpose
-------------
Adding error handling for local development
Changes
------------
When calling File.touch, if waterbutler is not running, catch the `ConnectionError` and `return None` so that waterbutler does not always need to be running in order to view projects on the OSF.
> Handle wb connection error

- tests/test_registrations/test_embargoes.py
- website/project/model.py
Setting an Embargo's state to COMPLETED would fail validation;
this adds COMPLETED as a valid value
> Allow Embargo.state to be COMPLETED

- api/base/pagination.py
- api/base/parsers.py
- api/base/serializers.py
- api/collections/serializers.py
- api/collections/urls.py
- api/collections/views.py
- api/nodes/permissions.py
- api_tests/collections/test_views.py
- website/project/model.py
Lay down the groundwork for relationship endpoints as per JSON API specs and, more specifically, add the ` /collections/<collection_id>/relationships/linked_nodes/ ` endpoint to allow the creation, retrieval, update and destruction if node links in a collection. This is done in this manner:
```
Method:        POST
URL:           /links/self
Query Params:  <none>
Body (JSON):   {
"data": [{
"type": "linked_nodes",   # required
"id": <node_id>   # required
}]
}
Success:       201
```
This requires both admin permission on the collection, and for the user that is
making the request to be able to read the nodes requested. Data can be contain any number of
node identifiers. This will create a node_link for all node_ids in the request that
do not currently have a corresponding node_link in this …
> Collection Linked Nodes Relationship endpoint and Relationship API groundwork

- tests/base.py
- website/project/views/comment.py
Remove updating comments on file move/rename due to inconsistencies with certain move/rename operations.
> Undo updating comments on file move/rename

- website/static/js/comment.js
Fixes issue where comment info was anonymized (viewing through anonymous link) but the project
was public.
> Only use VOL token if project is private

- website/addons/github/model.py
- website/addons/github/settings/defaults.py
[#OSF-5577]
Purpose
=======
GitHub appears to have had a recent breaking API change, making `events` a required parameter for hook creation. Because we create hooks when linking repos, this prevents users from changing their selected repository. We only log file operations type events (`added`, `modified`, or `removed` -- see [this function](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/addons/github/views/hooks.py#L66)), thus the only event we need to specify is a [PushEvent](https://developer.github.com/v3/activity/events/types/#pushevent).
Changes
=======
* Specify which event type(s) should trigger the hook
Side Effects
=========
May trivially conflict with #4853
> [Hotfix] Specify webhook event type when creating a hook

- website/project/model.py
- website/project/views/node.py
- website/templates/project/project_header.mako
Changes
-------------
- `find_n_unread` is never called with `check=True` so update `find_n_unread` to remove that unused code. 
- Take out calls to `find_n_unread` in `_view_project`. Getting `n_unread_files` requires a call to waterbutler for each commented file, which slows project loading times.
> Remove unread comment counts in project nav bar

- addons.json
- api/comments/serializers.py
- website/addons/base/views.py
- website/settings/defaults.py
- website/templates/project/view_file.mako
Only allow osfstorage file comments due to inconsistencies with making sure comments stay with addon files when they are moved or renamed.
> Only allow osfstorage file comments

- website/project/views/comment.py
When an osfstorage file is moved to another node, update the file's comments with the new node and update `node.commented_files`.
> Update comments when osf file moves nodes

- api/comments/serializers.py
Purpose:
Fixes issue where restoring a comment produced both "comment update" and "comment restored" logs.
Changes:
In the comment serializer update method, first check if the comment is being restored. Otherwise, update the comment.
> Fix restoring comments

- tests/test_conferences.py
- website/conferences/message.py
e.g.
"some name" <email@domain.tld>
some name <email@domain.tld>
email@domain.tld
> [hotfix] Conferences: Allow additional sender email & name formats

- api/registrations/views.py
Fixes 500 error on registrations with file comments where the RegistrationDetailView did not have get_unread_file_comments, because it was missing the WBMixin.
> Add WBMixin to RegistrationDetailView

- tests/test_models.py
- tests/test_registrations/test_sanctions.py
- website/archiver/tasks.py
- website/project/model.py
- website/project/views/register.py
[OSF-5592]
- Add `Node#get_active_contributors_recursive`
- Changes the signature of multiple methods, e.g. `ask`, `_email_context`,
etc. to receive the node of the user being notified
https://openscience.atlassian.net/browse/OSF-5592
> [hotfix] Notify non-admin contributors when a registration is initiated

- website/project/metadata/prereg-prize.json
- website/templates/project/registration_editor_templates.mako
On pre-reg form, under 'Sampling Plan" and 'Existing Data', add an 'i' tooltip to the end of each option to indicate that there is more info (instead of linking the tooltip to the option text which is the current behavior)
[OSF-5492]
> Add 'i' tooltips on existing data question

- .coveragerc
I don't find a way to run coverage reports on the `api` module from pytest without this configuration change. Coming from https://github.com/caneruguz/osf.io/pull/17#issuecomment-176989103.
> include api module in coverage reports

- website/static/js/accountSettings.js
Jira ticket: OSF-5535
Purpose
-----------
Update the users to inform them they should log out of the OSF before merging accounts.
Current
----------
Proposed
-------------
> [RFR] Update language to ask users to log out before merging

- tests/test_addons_oauth.py
- website/addons/base/__init__.py
- website/addons/box/model.py
- website/addons/box/settings/defaults.py
- website/addons/box/tests/test_models.py
- website/addons/box/tests/test_views.py
- website/addons/dropbox/model.py
- website/addons/dropbox/tests/test_models.py
- website/addons/dropbox/tests/test_views.py
[#OSF-5365]
Purpose
=======
Addons that follow the [OAuth RFC](http://tools.ietf.org/html/rfc6749) most closely provide an endpoint to revoke the oauth grant on their end, invalidating any access tokens that may have been discovered by a third-party. We should make use of this feature for addons with an API supporting it.
Changes
=======
* Method and call added to base class that will `pass` when tokens should be revoked.
* Above method overridden in addons that support token revocation (and have been migrated to the `ExternalAccount` architecture already.)
* #4853 has had this method preemptively overriden on the `GitHubUserSettings` model.
Side Effects
==========
None
> [Feature] Remove remote grant during deauthorization if possible

- website/project/model.py
This removes an index from Node.contributors that was causing MultiKey errors in tokumx
> [Feature Fix] Remove index from Node.contributors 

- scripts/cleanup_failed_registrations.py
- website/archiver/tasks.py
An uncaught non-20X response from the WB API when making a copy request in Archiver would allow failing copy requests to appear as successes. This in turn created registrations that were stuck 'archiving'. Later, when the `approve_registrations` script was run, it would auto-approve those registrations, creating approved (potentially public) registrations still stuck in archiving mode.
Catch and raise a HTTPError for non-20X response from WB.
> Archiver Fixes

- website/addons/base/views.py
When a file move via the file browser takes too long, we let the user get back to browsing and then send them a notification when it's done. The notification email was showing the `path` of the moved file, which
is an identifier, not a human-readable filename.  Ex. if a file was moved from osfstorage to another provider, the email would read `The folder "56b3816a594d90018653919b” has been successfully moved`
This PR updates `create_waterbutler_log` to pass the human-readable `materialized` property of the source and destination log payloads instead of the `path` property.
Fixes: [#OSF-5648]
> [hotfix] Update file move notification emails to show file name

- framework/auth/core.py
- Allows a user to be disabled even when they are not subscribed to MailChimp emails by handling MailChimp's ```ListNotSubscribedError```. 
- [OSF-5588]
> [feature] handle-disable-unsubscribed-account

- api/base/filters.py
- api_tests/nodes/views/test_node_files_list.py
Reopening #5003 without all those merge develop commits
Relates to https://openscience.atlassian.net/browse/OSF-5029
Filtering by filename in the API fails if you don't use the correct case.
As described on Jira by @brianjgeiger:
https://staging-api.osf.io/v2/nodes/ck8hm/files/s3/?filter[name]=Renamed will always fail, even if there's a file named Renamed, but https://staging-api.osf.io/v2/nodes/ck8hm/files/s3/?filter[name]=renamed will succeed. 
- When parsing the filter on a CharField, the API will make the query term lowercase
- Add test to make sure that a search of the incorrect case returns the desired results
If any API filtering was relying on exact case of search terms for a charField, this will break.
> Make API filtering on a charfield be case insensitive

- website/templates/public/pages/help/statistics.mako
The "Statistics" tab has been renamed to "Analytics." This is updating the language on the Getting Started page.
I am not updating the anchor on the page because I'm concerned links point here and I don't want them to break. The entire Support/Getting Started page will be changed soon and I think we should deal with that issue then.
> hotfix/Update Getting Started language: statistics to analytics

- website/static/js/nodesPrivacy.js
- website/templates/base.mako
- website/templates/project/nodes_privacy.mako
Allow me to reintroduce myself, my name is jQuery 3, which works when patching Internet Explorer.  This was accidentally removed, and we are putting it back in.  
Also, added logic to allow confirm to disappear when there are more then 100 nodes to change (the limit for bulk api)
> [RFR] Put IE fix back in for changing nodes privacy.

- website/static/js/nodesPrivacySettingsTreebeard.js
Treebeard was going out of sync when select all or select none were pressed when changing nodes privacy.  Basically, treebeard could update knockout, but not vice versa. . .  . . . 
UNTIL NOW!!!!!!!!!
> [RFR] update treebeard when select all or select none are clicked

- api/base/renderers.py
- api/base/settings/defaults.py
- api/base/views.py
This disables ESI in **all** cases except where the content-type is that of jsonapi. This can be forced for testing with ?format=jsonapi in the url or by passing the correct jsonapi vendor content type as a header.
> [Feature] fix esi for jsonapi

- website/files/models/base.py
Prevent full table scan when looking up parent storedfilenode items.
@sloria
> [hotfix] storedfilenode parent index

- api/base/serializers.py
This PR makes list views in the API use ESI. 
Instead of drawing out the full object in JSON the object is replaced by a varnish esi:include tag. This allows cache invalidation to work correctly because every part of the API now depends on a url for each individual object. 
```json
{
"data":[
<esi:include src="http://localhost:8000/v2/nodes/kxfsn/?format=jsonapi"/>,
<esi:include src="http://localhost:8000/v2/nodes/bnscw/?format=jsonapi"/>,
<esi:include src="http://localhost:8000/v2/nodes/r7myv/?format=jsonapi"/>
],
"links":{
"first":null,
"last":"http://localhost:8000/v2/nodes/?format=jsonapi&page=115&page%5Bsize%5D=3",
"prev":null,
"next":"http://localhost:8000/v2/nodes/?format=jsonapi&page=2&page%5Bsize%5D=3",
"meta":{"total":345,"per_page":3}}
}
```
- For list esi:include tags the …
> [WIP] Make api lists ESI-based

- admin/base/wsgi.py
- api/base/wsgi.py
- main.py
Patching via uwsgi.ini configuration was only patching full module imports.
https://uwsgi-docs.readthedocs.org/en/latest/Gevent.html#monkey-patching
> Monkey patching
> uWSGI uses native gevent api, so it does not need monkey patching. That said, your code may need it, so remember to call gevent.monkey.patch_all() at the start of your app. As of uWSGI 1.9, the convenience option --gevent-monkey-patch will do that for you. Please note that uWSGI does monkey patching before your application starts, not before your application loads. So if you are loading other modules while loading your application you may still need to call gevent.monkey.patch_all() yourself.
> 
> A common example is using psycopg2_gevent with django. Django will make a connection to postgres for each thread (storing it in …
> [hotfix] gevent wsgi patch

- api/base/serializers.py
- api_tests/registrations/views/test_registration_detail.py
Fixes edge case found by @sloria in https://openscience.atlassian.net/browse/OSF-5725
As of OSF-5725, you can request specific related counts instead of fetching related counts for all the fields.  For example, a response to `v2/registrations/?related_counts=children` will only return counts for the registrations' children, not other countable fields like `contributors` and `node_links`.  However, we hide the majority of the fields for retracted registrations.  So if a retraction is in a list of registrations, `children` is a hidden field in a retraction, and a 400 error would be thrown. 
Ignores related_counts for hidden fields.
> [WIP] Feature/retractions causing 400 error when requesting specific related counts

- framework/addons/__init__.py
- website/addons/base/__init__.py
Purpose
=======
Fix [a bug](https://openscience.atlassian.net/browse/OSF-5742) that occurs when a user disconnects their account by unchecking the box in `Select Addons` on a node settings page, then later tries to disconnect from the user settings page as well. 
Changes
=======
More thorough deauthorization is performed in both cases.
Side Effects
=========
None
[#OSF-5742]
> [Hotfix] Fix ExternalAccount Addon Disconnect

- framework/auth/views.py
- website/mails/mails.py
- website/templates/emails/initial_confirm.txt.mako
Addresses https://openscience.atlassian.net/browse/OSF-5697
Previous cherry-picked commit https://github.com/CenterForOpenScience/osf.io/commit/fee6ee687cd577de8dd2c5cafc2e0b39a76fc5ea modified the CONFIRM_EMAIL template to assume that you're confirming an email added to an existing account. @caileyfitz found that this email is also sent to new registratnt to the OSF. This PR adds a new category for email confirmation to be sent, that checks if this user is not active and sends a specific email then.
- New email template that is sent when a person first enters their email into the account signup form
- Calling that email template from ```mails.py```
- Checking if a user is active, sending the simple CONFIRM_EMAIL in that case, and sending them their first ever "you've made an account with …
> [Ready for Review ]Add template that differentiates between New Account makers and adding a new email to existing account

- api/base/serializers.py
- api_tests/registrations/views/test_registration_detail.py
Continued fix on  https://openscience.atlassian.net/browse/OSF-5725.
Related to PR https://github.com/CenterForOpenScience/osf.io/pull/5044
The changes to the last PR ^ that made countable fields more generic, made Retractions work, but not Registrations.
If we have a HideIfRetractionField or HideIfRegistrationField, for example, these fields wrap RelationshipFields.  So on a registration, no fields will be hidden, but there will be a limited subset of "countable_fields" because the RelationshipFields are wrapped.
When populating countable fields (so looking for fields that are relationship fields, not attributes, as indicated by `json_api_link` is true), check for json_api_link in nested fields like HideIfRetraction or HideIfRegistration as well.
> [Ready]Feature/Ensure hidden relationship fields are showing up in countable fields

- website/static/js/meetings.js
- website/static/js/submissions.js
Enable search in OSF meeting front page
Resolve [OSF-4994]
It is a simple change since treebeard has already implemented search. The thing we need to do is to config it. 
1) Set show filter as true
2) Select column that need to be searched
None
> [Enhancement][OSF Meeting] Enable Search on OSF Meeting  Front Page 

- api/comments/permissions.py
- api/comments/serializers.py
- api_tests/comments/views/test_comment_detail.py
Purpose:
------------
Fixes https://openscience.atlassian.net/browse/OSF-5681
If a project's comment level changes from public to private, non-contributors can still edit and delete any comments that they made while the comment level was public.
Changes:
------------
- The `can_edit` field on the CommentSerializer now checks if the user can comment on the project (not just if they are the author).
- The `CommentDetailPermissions.has_object_permission` also checks if the user can comment on the project.
> Feature: Fix comment edit/delete permissions

- api/base/serializers.py
- api/nodes/serializers.py
- api/registrations/serializers.py
This fixes the html api urls pointing to the api instead of osf.
> Add get_absolute_html_url method to base serializer and encourage usage

- .coveragerc
The `scripts` directory is a Python module, it turns out. It should be possible to run coverage reports against it (e.g., https://github.com/CenterForOpenScience/osf.io/pull/5033/files#r54173051).
cf. #4965
> add scripts/* to .coveragerc

- website/addons/base/__init__.py
- website/addons/box/model.py
- website/addons/googledrive/model.py
- website/addons/googledrive/tests/test_models.py
Purpose
=======
When forking a node with configured addons that support OAuth grants, the new node's grants should have the same metadata as the original grant. If this is not done, some functionality (e.g. viewing/downloading a file) can throw errors.
Changes
=======
* Preserve metadata
* Don't bother with `.complete` check, grant always needs to be updated on folder selection
Side Effects
=========
Duplicated code from #4949: stop clearing `folder_id` on `set_auth` for GDrive -- this is necessary for folder link to persist when forking.
[#OSF-5790]
> [Hotfix] Preserve OAuth grant metadata when forking

- website/static/js/contribAdder.js
- website/templates/project/modal_add_contributor.mako
Before, the user would see 'No results found' even if the search wasn't over. They should know that contributors are still being searched.
Add some extra logic to show 'Searching contributors...'
Had to stop it in the debugger to pull off a screenshot which is why it's dark:
It occasionally will "flash" locally (where I have about 4 users to search through) but it's not too bad.
[OSF-5654]
> Add loading indicator to contributor search

- framework/exceptions/__init__.py
- framework/tasks/__init__.py
- framework/tasks/handlers.py
Multiple threads were causing the tasks queue to be overwritten when a new request was created.
Though the queue was attached to a threading.local the attribute `queue` was attached directly to the module avoiding any use of the threading.local as it only works when the `__getattribute__` can provide the necessary scoping mechanism to evaluate the current thread and thus return the appropriate object.
Also HTTPError `__str__` now matches `__repr__`
> [hotfix] fix task queue race condition

- tests/test_node_licenses.py
- website/project/model.py
Since the license is inherited to all the components and nested components, the logs on those components should record the license actions.
`add_log` called for each primary descendant of the updated node; trickle down license-omics. 
None apparent 
[OSF-5083]
> [RfR] Component logs reflect inherited actions regarding license

- tests/test_views.py
- website/profile/views.py
<b>Purpose</b>
Fix resend confirmation for unconfirmed emails don't return emails list. Solves https://openscience.atlassian.net/browse/OSF-5779#add-comment.
> fix the resend emails not returning emails

- website/static/js/contribRemover.js
Related to #4799
This fixes a bug found by QA where if there are multiple nodes but the contributor is not on those nodes, then the multiple remove radio button is displayed.  It should not be.
Steps to Reproduce
---------------------------
1.  have a project with components
2.  add a contributor on the project and not on any of the children
3.  try and remove her
Before Fix
----------------------
After Fix
----------
you see this dialog
> [RFR] Check to see if there are multiple contributors to remove

- website/static/js/contribRemover.js
There was a bug found by @ajski Amanda Liscouski where users without admin privileges could attempt to remove a contributor.  Also, as per QA's suggestion, changed language from Delete Contributor to Remove Contributor keeping it in line with the rest of the site.
> Users without Admin Privileges Can't Remove Contributors

- website/static/js/contribRemover.js
This fixes a bug found by Todd Sacco.  The logic for the toggle to remove a contributor from one vs all nodes was removed at some point.  Now it's back, and this time. . . . . 
It's Personal.
> Allow single node deletion

- website/static/js/pages/base-page.js
PhantomJS is being tracked by KeenIO on staging. This is skewing analytics and we need to ignore these calls.
None
> Ignore PhantomJS traffic on KeenIO

- scripts/analytics/benchmarks.py
Purpose
=======
[Dropbox refactor](https://github.com/CenterForOpenScience/osf.io/pull/4658) in 0.60.0 caused the `analytics/benchmarks.py` script to incorrectly calculate metrics related to Dropbox.
Changes
=======
* Change counting methods based on model changes
* Don't use `len(<object lists>)` to count, just keep tally
Side Effects
=========
None
[#OSF-5481]
> [Hotfix] Update analytics script to count correctly for Dropbox metrics

- requirements/release.txt
This adds the requirement for New Relic to release.txt and also adds a pinned version of uWSGI. @icereval suggested moving uWSGI out of the docker build process into release.txt for the ease of updating.
This should have no effect other than upgrading uWSGI to the newest version. There are accompanying changes in other repos that enable the New Relic instrumenting on individual servers in different environments. Those deployments have a **hard** dependency on this being released prior **OR** @icereval just installing it by hand on the servers in question.
> [Feature] Add New Relic and pin uWSGI

- api/files/views.py
- api/nodes/views.py
The docs claimed that a file could be updated by issuing a PUT request
against the parent directory's endpoint with the query parameter `name`
set to the name of the file.  This is incorrect; files should be updated
by issuing a PUT against the file's endpoint.  The incorrect method may
have accidentally worked in the past, but this will be fixed in an
upcoming release of WaterButler.
*This is a doc-only fix.  No code changes.*
> fix incorrect file update api docs

- website/project/views/node.py
Jira Ticket:  https://openscience.atlassian.net/browse/OSF-5814
After creating a component, the OSF takes you into that component.  Usually this is not the preferred action, and leaves users confused.  Now users will stay on the project page they were originally working on.
> [RFR] Redirect to project instead of component when creating new component

- framework/auth/core.py
Reverts CenterForOpenScience/osf.io#5139 due to `OperationFailure: Cannot transition from not multi key to multi key in multi statement transaction` will add to indices.md
> Revert "Add indices to the user collection"

- website/templates/include/profile/jobs.mako
This JIRA Issue this corresponds to is : https://openscience.atlassian.net/browse/OFI-25
**Purpose** 
Currently on https://osf.io/settings/ in the employment tab the heading for where the user enters which department they are in merely says, "Department". However, simply having this term can be vague and hard to understand. Some clarification is necessary. 
**Changes**
Updated the employment tab so the heading for department now reads "Department / Institute". Attached is an image of how the employment tab will look with the updated heading.
As only one line of code for the heading was changed no side effects are anticipated.
> [Ready to Review] - Updated Employment Tab to say "Department / Institute"

- tests/test_rubeus.py
- website/util/rubeus.py
This feature removes "Project: " and "Component: " before the project or component name when listed on the project page. 
Jira ticket: https://openscience.atlassian.net/browse/OSF-5834
> [Feature] Remove Project String from Project Name

- api/base/settings/defaults.py
- api/base/views.py
- api/collections/views.py
- api/comments/views.py
- api/files/views.py
- api/institutions/views.py
- api/logs/views.py
- api/nodes/views.py
- api/registrations/views.py
- api/users/views.py
swagger thinks three or more dashes on their own line indicates the
beginning of a YAML document.  It then dies when the content after
isn't valid YAML.  Replace the dash strings we were using as ascii art
with equal strings to appease swagger.
Also add a note that the BAPI docs are the current preferred doc source.
> take out multidashes from BAPI docs to appease swagger

- api/logs/permissions.py
- api/logs/views.py
- api_tests/logs/views/test_log_detail.py
Issue https://openscience.atlassian.net/browse/OSF-5777
Accessing log detail `/v2/logs/{log_id}/` for a project's logs gives a 500.  
This issue blocks https://openscience.atlassian.net/browse/OSF-5471
Instead of using ContributorOrPublic method on log views (which was built for nodes), created a ContributorOrPublicForLogs method which then calls ContributorOrPublic for each of the nodes on the log's backref to see if the user has permission to access the log.
(Will be modified slightly when backrefs are eliminated between nodes and nodelogs).
Tests were already written for these endpoints and were now failing locally before this change.  Are these running on Travis?
> [Ready to Review] Feature/500 error when accessing log detail

- website/templates/project/project.mako
<b>Purpose</b>
Fix the error that the contributors are not showing correctly in project overview page when it is a public project visited under anonymous private link.
Before fix:
After fix:
Partially fix https://openscience.atlassian.net/browse/OSF-5824
> Fix the project overview page contributor error

- website/static/js/filepage/revisions.js
The purpose of this pull request is to implement a feature to allow users to understand what the MD5 and SHA2 features are of the Revisions. By having this feature, the user is capable of making file comparisons as well as fully understanding what is provided on nearly half of the screen.
Added a question-circle next to MD5 and SHA2. Hovering over the question-circle creates a hovering popup that shows the description of each. Implementation was done on revisions.js on lines 94-98 and 108-113.
Definitions/descriptions of MD5 and SHA2 must be taken into consideration.
> [hold]  [feature]Hover description for MD5 and SHA2 for file revision

- framework/transactions/handlers.py
Flask context is not guaranteed to exist, it might be running in a Django context.
https://sentry.cos.io/sentry/osf-j5/issues/915/
"RuntimeError: working outside of application context"
> [hotfix] rollback error handling to transaction middleware

- tests/test_addons.py
- website/addons/base/views.py
Purpose
-----------
When a folder is moved/renamed, the guids of all of the files are updated with the new StoredFileNode objects. However, there is no way to know whether the original StoredFileNode corresponds to a deleted addon file unless you make a request to waterbutler.
Changes
------------
- When a file is deleted, remove its StoredFileNode and create a TrashedFileNode.
- When resolving a file, if it no longer exists remove the StoredFileNode and create a TrashedFileNode (handles the case where a file is deleted through the addon)
> Feature: Create trashed addon file nodes

- website/templates/footer.mako
Currently when VoiceOver reads the social media icons in the footer of the OSF pages it just reads "link" for each of them. It has no idea what they are and to a blind or visually impaired person this could be a major problem. This PR allows VoiceOver to read what social media sites the icons represent and relay that information to the user.
Adds ARIA labels to the five icons listed under the header "Socialize" in the footer of the OSF. The labels simply state exactly what social media website the icon represents. For example, the icon for twitter has the ARIA label : "Twitter" . An attached image showcases what this looks like in VoiceOver. Additionally, as the label is an ARIA label it would not be visible to sighted users and would only become audible and visible to users using …
> Improvement onto icon images: Added ARIA labels to social media icons

- api/comments/views.py
- api/nodes/serializers.py
- api/nodes/views.py
- api_tests/nodes/views/test_node_detail.py
- tests/factories.py
- tests/test_comments.py
- tests/test_websitefiles.py
- website/files/models/base.py
- website/files/models/osfstorage.py
- website/project/model.py
- website/project/views/comment.py
Purpose
------------
The `commented_files` field is used to easily calculate the total unread file comments, but updating the field causes the Node to lock. Since the total unread file comments are not being displayed anywhere, this code can be removed for now. 
Changes
------------
- Remove all usages of `Node.commented_files`
- Simplify `Comment.find_n_unread`
- Address code review comments from #5059, mainly minor refactoring
> Feature: remove Node.commented_files

- website/addons/s3/static/s3NodeConfig.js
Jira ticket: https://openscience.atlassian.net/browse/OSF-5553
When users enter a name in the S3 create bucket modal, if they hit the "return" key, the modal is dismissed.  This is not the expected behavior.  According to @billyhunt, since this form should be refactored, and fixing the behavior in a timely manner is important, this fix should be put in first to correct the unintended behavior.
> [Feature] Prevents enter key from refreshing the page within the Create Bucket bootbox

- website/archiver/tasks.py
- Multiple approval emails were being sent to project admins and contributors after registering a parent project with components and files (i.e. when multiple celery worker threads were running to archive the files in multiple components). 
- This PR resolves the issue by marking a job as complete before the approval emails are sent, so that emails cannot be sent more than once. 
- [OSF-5820]
> [hotfix] Fix Multiple Registration Approval Emails 

- website/templates/index.mako
Currently when VoiceOver reads the YouTube link to the video "Getting Started With the Open Science Framework" it just reads "link" for it. It has no idea what that is and to a blind or visually impaired person this could be a major problem. This PR adds an ARIA label to the link so that a blind/visually impaired user would be able to access it easily. This link is found on the home page of the OSF. It is the link located on the screen shot of the OSF with the YouTube play button over it. This can more clearly be seen in the before and after images.
Adds an ARIA label to the YouTube link to "Getting Started With the Open Science Framework". This label shows up in the links menu of VoiceOver and reads out "OSF YouTube Video" when the user scrolls to it. This label is not visible to sighted …
> [#OSF-5856] Added ARIA Label for youtube link

- api/registrations/serializers.py
- api/registrations/views.py
The urls for registration contributors were pointing to /v2/node/{node_id}/contributors/{contributor_id}/ which did not resolve. This changes them to point to /v2/registrations/{registration_id}/contributors/{contributor_id}/.
In prod the only issue would be that links.self would have been pointing at the wrong place. In staging, with varnish esi enabled, the issue would be that registration contributors would have become `{"errors":[{"title":"Not Found"}]}`.
@caneruguz This should fix your problem.
> [Ready for Review] Resolves misspointed url for registration contributors

- website/static/js/pages/project-settings-page.js
- website/templates/project/settings.mako
On the project settings page, under the checkbox list of addons, there existed an 'Apply' button which was inconvenient for users. This feature removes the apply button and updates the page when the checkboxes are clicked.
Jira ticket: https://openscience.atlassian.net/browse/OSF-5854
> [Feature] Remove project settings addons apply button

- website/templates/project/modal_add_contributor.mako
JIRA Ticket: https://openscience.atlassian.net/browse/OSF-4722
Currently when editing one of the projects for which the user has admin permission. In the project's Contributor's page when you try to add a contributor the plus button has a larger width than the minus button does. This PR makes the size of the buttons the same. This is more easily visible in the before and after images.
Takes out the section in the plus button code where the width was fixed as the width of the minus button was not fixed. 
No side effects anticipated. 
The buttons are different sizes.
The buttons are now the same size.
> [#OSF-4722] [Ready to Review] Fixed Add Button and Check Button Sizes

- website/static/js/pages/project-settings-page.js
- website/templates/project/settings.mako
**Issue:** https://openscience.atlassian.net/browse/OSF-5104 
Currently, when a user makes changes to either their category, title, or description in the project settings page and then tries to navigate to another page, their savings won't automatically be made nor are they alerted that they have unsaved changes on the page. This PR will show a pop-up alert when the user is navigating to another page without having saved their changes.
Shows a pop-up window that tells the user they're leaving a page without having saved the changes made. There are two buttons on this pop-up, the first to 'stay on this page' with the implication that they can save their changes before navigating to another page, and the second to 'leave this page', anyways. This is only enacted if any or all of the …
> Pop-up added when navigating away from project settings page after editing title/description

- .gitignore
Since `celerybeat` uses `anydbm` (via `shelve`), its data file might have one of a number of file extensions. It's actually pretty hard to figure out what those file extensions might be, but it's easy enough to keep them out of git with a wildcard.
P.S. I don't know what the `celery_beat.py.db` file is about, so I'm not touching that.
Reticketed from https://github.com/zkraime/osf.io/commit/a6d27826a247615b5de4838d76bf27b714aa144f#commitcomment-16682405.
> Ignore more celerybeat-schedule files

- package.json
- webpack.common.config.js
- website/static/js/home-page/newAndNoteworthyPlugin.js
- website/static/js/home-page/quickProjectSearchPlugin.js
Issue https://openscience.atlassian.net/browse/OSF-5867
Currently, users must wait until all projects are loaded before they can begin to search.   This can be a long wait if the users have many projects.
Allows user to search for projects before all projects are loaded in the background.  As new search results are found, they will be added to the list.  Sorting is still prevented until all nodes are loaded.
Also, adds ball-scale, instead of spinner while loading.  Just an experiment - we need to reach an agreement on the loader.
> [Ready to Review] Dashboard/quick search while loading

- admin/README.md
- admin/base/migrations/0001_groups.py
- admin/common_auth/migrations/0001_initial.py
Add permission groups such as `prereg_group` through a migration script.
Should make it slightly easier to start a new server with permissions groups rather than having to add groups by hand. Also this will be a basis for several subsequent PRs that add in required login and group permissions for each view.
> [FEATURE]Add permission groups through migration

- website/static/js/myProjects.js
With the current text, the word component will be repeated 3 times, which, as I mentioned in the trello card, will invoke Beatlejuice.  No one wants that.  And its also redundant.  
Since the lack of components or projects is implied by the lack of components listed.  I propose we remove the text all together.
Before
---------
After
-------
> remove redundant node text

- package.json
- website/static/js/diffTool.js
<h3>
Purpose
</h3>
The original behavior of the compare function of project wiki was erratic in that it was not clear whether it was comparing texts word by word, line by line or otherwise. This PR make use of new features in diff 2.2.2 and compare wiki texts line by line.
<h3>
Changes
</h3>
Update the package.json file to use newest version of diff (2.2.2).
Change diffTool.js. Specifically, the custom wikiDiff object was deleted and make use of diffLines() in diff 2.2.2.
> OSF-5179 Strange wiki compare behavior.

- website/templates/base.mako
- website/templates/dashboard.mako
- website/templates/project/project_base.mako
Analytics always needs the current user id. Set it in base.mako so
it's available on all pages, including /.  Stop setting it
specifically in sub-templates.
> make currentUser.id globally available via base.mako

- website/static/js/osfHelpers.js
trello ticket: https://trello.com/c/bswdkmZw/66-growl-box-error-for-adding-project-to-collection-it-s-already-in-should-not-persist
Our implementation of growl in osfHelpers did not pass the timeout variable to growl.  Now it does!!!!
This allows control of the persistence of different types of growl messages.
> [WIP] Pass growl timeout variable

- website/addons/wiki/templates/edit.mako
- website/static/css/pages/wiki-page.css
- Adds `panel-height` CSS class and applies it to the wiki menu, edit, and view panel headers. 
- [OSF-3619](https://openscience.atlassian.net/browse/OSF-3619)
> [feature] Consistent Wiki Panel Header Heights 

- website/templates/emails/comment_replies.html.mako
- website/templates/emails/comment_replies.txt.mako
- website/templates/emails/comments.html.mako
- website/templates/emails/comments.txt.mako
Purpose
======
Remove quotes around `comment.content` in email templates, it looks bad with markdown rendering.
See https://trello.com/c/ssDXjC4y/32-notifications-format-of-comment-email
Changes
=======
Quotation remarks removed.
Alternative approaches considered:
* `string[3:-4]` indexing to ignore `<p>[...]</p>`    - Bad
* BeautifulSoup/Bleach to strip tags           - Slow/Greedy
Side Effects
=========
None
> [Feature][Fix] Markdown rendering in comment emails

- website/project/views/comment.py
When an OSF storage file is moved to another provider, it already gets moved to TrashedFileNode. Check to make sure `old_file` is not None before trying to check for a TrashedFileNode and deleting the file.
> Check that file exists before deleting

- website/templates/nav.mako
https://trello.com/c/sEDHCCna/119-when-a-user-navigates-away-from-the-dashboard-they-should-be-able-to-get-back-by-clicking-the-dashboard-link-the-nav-bar
> [Fix] Add nav button to "My Dashboard"

- api/registrations/serializers.py
- api/registrations/views.py
Create registration file serializer that overrides relationship fields (e.g. comments and files) that hard-coded node views to make them registrations views.
> Fix comments field for file serializer

- api/collections/serializers.py
Purpose
-----------
Make collections work properly when it goes to production.
Changes
-------------
Remove DevOnly from two fields
Side Effects
None. Shouldn't even notice it on staging or local development.
> Remove DevOnly from necessary collections fields

- website/routes.py
- website/templates/emails/conference_submitted.txt.mako
- website/views.py
- Add link to OSF4M success email which redirects to a Google Analytics link.
- [OSF-4998]
> [feature] OSF4M Analytics Links

- api/nodes/views.py
- api/registrations/views.py
- api/users/views.py
Refs https://openscience.atlassian.net/browse/OSF-5515
Updates docstrings for APIv2 endpoints that use `RegistrationSerializer` (or a subclass thereof). Adds all newly added fields, and clarifies some descriptions based on help text added to field definitions.
Excludes "collections" field of the parent "node" serializer, because this is a DevOnly attribute.
Routes affected
- `<api>/v2/nodes/<node_id>/registrations/`
- `<api>/v2/registrations/`
- `<api>/v2/registrations/<reg_id>`
> Update API docs for "registrations" type endpoints

- website/static/js/myProjects.js
Currently, if you add a component via breadcrumbs, it will pop a Add project dialog.  Not the oh so needed Add component dialog.  This should make that magic happen.
:(
-
:)
-
> toggle breadcrumbs to use use component or project modal

- website/project/views/comment.py
This should fix the bug with dataverse and figshare (among others) comment unread counts not updating. 
It would be nice if when we replaced the v1 route for updating the timestamps for unread comment counts it was related more directly to the object being commented upon instead of the user. The current setup causes many logic branches to handle the fact that the URL/object being modified is the user but the object we're expected to see change is the File, Node, etc.
@sloria @nicipfeiffer @samanehsan
> [Ready for review] Fix file comment banning

- framework/auth/core.py
- scripts/tests/test_update_comments.py
- scripts/update_comments.py
- tests/test_comments.py
- website/project/model.py
- website/project/views/comment.py
Purpose
-----------
Since `user.comments_viewed_timestamps` organizes timestamps under a `node_id` top-level key, when a file moves nodes the field needs to be updated and that locks the user. Instead, make the timestamps a dictionary of `{target_id: timestamp}`
Changes
------------
- Change structure of user.comments_viewed_timestamps from {'node_id': {'node': timestamp, 'files': {'file_id': timestamp}}} to {'node_id: timestamp, file_id: timestamp, ...}.
- Need to run `scripts.update_comments_viewed_timestamp`
> Feature: Change structure of User.comments_viewed_timestamps

- website/oauth/models/__init__.py
Refs https://openscience.atlassian.net/browse/OSF-5911
Clean up unused and unnecessary backref from `ApiOauth2Application` model.
- Remove the line that creates the backref with the ForeignField. Confirmed that after the change, mongo records still create a foreign field, but don't save the backref.
There should be no side effects. This backref was never used. It was only referenced once, and at that, in a unit test that was [removed](https://github.com/CenterForOpenScience/osf.io/pull/4813/files#diff-327b130c82fa4e83e97f6c1a50a0da1cL1073) several months ago.
Although some data will persist in the `_backrefs` section of the mongo user document, this should not affect other code and can reasonably be ignored.
[#OSF-5911]
> Remove unused backref from ApiOAuth2Application

- website/oauth/models/__init__.py
Refs https://openscience.atlassian.net/browse/OSF-5912
(same as #5282. If you give a mouse a cookie...) 
Clean up unused and unnecessary backref from `ApiOAuth2PersonalToken` model.
- Remove the line that creates the backref with the ForeignField. Confirmed that after the change, mongo records still create a foreign field, but don't save the backref.
Tested `<api>/v2/tokens` endpoint : create and edit personal access tokens from profile settings page on the OSF, and see list of tokens.
There should be no side effects. This backref was never used.
Although some data will persist in the `_backrefs` section of the mongo user record, this should be ignored by other code and can reasonably be ignored.
[#OSF-5912]
> Remove totally unused backref from ApiOAuth2PersonalToken

- framework/routing/__init__.py
Related to, and possible alternative to, #5292 
This fix is to master. Replaces #5295 
Improve application of the `strip_ko` filter. We can reasonably apply this to all templates, because it is separate from the markupsafe flag.
When testing the fix, try these steps to ensure that your mako cache is cleared and templates reflect the newest filters. Because this is a global  without help.
1. Pull code
2. Stop any running OSF server
3. Clear contents of `/tmp/mako_modules` directory
4. Restart server
I can walk you through in person.
> Improve application of text filters

- website/static/js/privateLinkTable.js
- website/templates/project/contributors.mako
- The OSF now supports anonymous VOLs on public projects, but the display of anonymous VOLs on public projects has not been updated to reflect this. This PR removes the strikethrough and tooltip that were associated with anonymous VOLs on public projects.
- [OSF-5860](https://openscience.atlassian.net/browse/OSF-5860)
- ![screen shot 2016-03-25 at 10 34 25 am](https://cloud.githubusercontent.com/assets/7913604/14046107/58df6c3e-f275-11e5-9ab1-ca02f3ebba51.png)
- ![screen shot 2016-03-25 at 10 34 08 am](https://cloud.githubusercontent.com/assets/7913604/14046109/5c447cac-f275-11e5-81b4-6d8a47cfef62.png)
> [feature] Fix Anonymous VOL Description on Public Projects

- website/static/js/myProjects.js
https://trello.com/c/qSscVKea/136-pending-and-retracted-registrations-should-not-show-on-my-projects-page
> [Fix] Only filter retractions and pending registrations on the 'All my registrations' page

- tests/test_views.py
- website/project/views/node.py
- website/templates/project/modal_add_component.mako
- Currently, when a r+w contributor creates a new component within a project, they are not given the option to 'add contributors from the parent project'. However, a r+w contributor will become an admin on a component they create, and therefore would be able to later add contributors anyways. 
- Add 'add contributors' checkbox in add component modal for a r+w contributor.
- Add tests for r+w contributors to add components with inherited contributors.
- If a r+w contributor creates a new component with inherited contributors, their permission will be set to admin on the new component, instead of being inherited as r+w. 
- [OSF-5887](https://openscience.atlassian.net/browse/OSF-5887)
> [feature] Allow Read + Write Contributors to Add Components with Inherited Contributors

- tests/test_registrations/test_embargoes.py
- tests/test_registrations/test_retractions.py
- website/addons/badges/model/badges.py
- website/addons/box/model.py
- website/addons/dataverse/model.py
- website/conferences/model.py
- website/notifications/model.py
- website/project/model.py
Refs various, general parent is https://openscience.atlassian.net/browse/OSF-5674 
We are attempting to reduce the number of unused backrefs on our models, as backrefs create side effects (record locking) that are not ideal.
This PR is intended to encompass the low-hanging fruit: backrefs that aren't used at all, in various places.
- Remove various unused backrefs (see diff)
Should be no side effects because these backrefs were unused. Migration probably unnecessary. Where relevant, below are notes on how to hit endpoints where these models are used.
- The `MailRecord` model is used to track email submissions to conferences (OSF For Meetings); I wasn't able to test this locally.
- Also try creating embargoed and retratcted registrations, as well as approving a registration when asked to …
> Remove misc unused backrefs

- api/base/serializers.py
- api/registrations/serializers.py
- api_tests/files/views/test_file_detail.py
- api_tests/nodes/views/test_node_embeds.py
- api_tests/registrations/views/test_registration_detail.py
Purpose
-----------
Fix [https://openscience.atlassian.net/browse/OSF-5373] in which embedding a parent field for a top-level resource would embed an error rather than skipping the field.
Changes
------------
1. Add a test for the problem case
2. Check for the field representation early and, if it doesn't have a representation, bail out early
3. Cache the representation and use it later on when necessary
4. Fix a problem test from the Files views
5. Modify the HideIfRegistration and HideIfRetraction functions to raise SkipField if it's a registration, because the logic isn't always catching None's anymore depending
6. Explicitly skip the registrations field on registrations so it doesn't get serialized incorrectly
Side effects
Checking to verify the representation is …
> Do not embed empty relationships

- .gitignore
- tasks/__init__.py
Purpose
-----------
Optionally generate a file that lists the most recent merge requests in an easy to read format, and place that file into the static directory. This will allow QA to go to baseurl/static/git_logs.txt and, with the default setup, see the last 100 merges. Sample output is
```
Merge pull request #5232 from caseyrollins/feature/client-side-profile-url-validation - [feature] Client Side Profile URL Validation
Merge pull request #5220 from brianjgeiger/feature/api/do_not_embed_empty_relationships - Do not embed empty relationships
Merge pull request #5287 from abought/feature/osf5674-backrefs - Remove misc unused backrefs
Merge pull request #5306 from caseyrollins/feature/add-contrib-checkbox - [feature] Allow Read + Write Contributors to Add Components with Inherited …
```
> Allow QA to see what's in the new build

- website/static/js/myProjects.js
This fixes bug where in narrow/mobile view the user couldn't open the menu for collections
> Fix click on menu item propagating to top level

- website/files/models/osfstorage.py
Fixes sentry error where the node & guid parameters were getting switched.
> Hotfix: Pass in named parameters to get_file_guid

- website/language.py
- website/search/elastic_search.py
- website/search/views.py
Refs https://openscience.atlassian.net/browse/OSF-4538
The search page was returning "unable to resolve" errors for certain kinds of malformed queries, when it should have said "bad search query". This was traced to a problem where elasticsearch returned the wrong error code (not 400) in certain cases.
- Capture ES failures  as a generic search exception (if specific cases not already handled)
- Show a more user-friendly error message
Should no longer get "unable to resolve" errors in a growl box. See sample strings in https://openscience.atlassian.net/browse/OSF-4538?focusedCommentId=30463&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-30463
Since the ES error code is less specific than it should be, users may get a less helpful error message than intended. …
> Fix search page "unresolved" error for malformed queries [OSF-4538]

- website/static/js/keen.js
The keen session cookie expiration date was being incorrectly set and silently ignored, leading to session inconsistencies in the logged data. This patch correctly sets the session time to 25min. It also explicitly logs to Sentry pageview events that Keen rejects, so that we can inspect them later.
> [hold][fix] Fix Keen session logic and error logging.

- api/base/serializers.py
- api/base/views.py
As far as I can tell, I'll look more in the morning, this fixes ESI embeds for DRF 3.3.3. It looks like the structure of related links changed in the way they were being passed to `to_esi_representation`. After a few key checks and digging deeper into the object I got the correct href and passed it to thing that generates the ESI url. The key checks don't seem very pythonic and I'll try to clean them up in the morning but I think this will fix it. The output on local matches the output on staging and the error I was getting on `/myprojects/` locally is gone.
The bit in `api/base/views.py` just solidifies that the API really is trying to serve JSON on this particular request instead of just checking the global allowed content types. h/t @chrisseto 
@icereval, @brianjgeiger, @Ghalko
> [rfr][fix] Fixing esi embeds for drf 3.3.3

- tests/test_views.py
- website/templates/util/render_node.mako
Refs: https://openscience.atlassian.net/browse/OSF-440
Allow read-write users to remove links to other projects. Should address an issue where no one, including the destination project owner, could delete a link to a private project.
Additionally, allow users with write access to delete links, *even if they don't know what the link is pointing at*. (see screenshot) This was deemed slightly preferable to an unremovable link owned by someone who is no longer a contributor.
Tested "private item deletion" with a private fork, and a private node, using two users (one admin, one with write access).
In the screenshots below: an admin user created 1 link to a public project, and a RW user created 1 link to a private project (that the admin wasn't a contributor on)
For the admin, BEFORE / AFTER …
> Allow read-write users to remove linked  [OSF-440]

- website/templates/public/pages/meeting.mako
hgrid was removed from bower.json by c07269d0f2 on Feb. 24.  We no
longer use or serve it and it 404s.
> [hotfix] remove unused hgrid css from meetings page

- website/static/js/comment.js
@felliott  noticed that production was throwing an error because the loadingComments ko observable was defined only on the ListCommentModel and not also on the CommentModel: https://sentry.cos.io/share/issue/31312e32393036/
This PR also adds it to the BaseModel to make sure it's good everywhere
- Add ```self.loadingComments = ko.observable(true);``` to the ```BasetModel``` in ```website/static/js/comment.js```
None I can think of!
> [hotfix] Move loadingComments ko observabale to BaseComment

- tests/test_models.py
@felliott pointed out that a test for roots had a blank assert statement - so was always returning true! This fixes it to make it actually check if the top level project has its own ID as its root
in ```test_models.py``` change ```test_top_level_project_has_own_root``` to ```assert_equals``` instead of ```assert```
> [fix] Change blank assert to assert_equal

- website/static/js/citationGrid.js
- website/static/js/filesWidget.js
- website/static/js/folderpicker.js
Purpose
=======
The treebeard constructor now returns controller; calls to `.tbController` return `undefined` and cause a errors
Changes
=======
* Remove calls to .tbController
Side Effects
=========
None
> [hotfix] Remove calls to .tbController

- website/static/js/nodeSelectTreebeard.js
Purpose
=======
The treebeard constructor now returns controller; calls to `.tbController` return `undefined` and cause a errors. Extension of hotfix #5413 
Changes
=======
* Remove call to .tbController
Side Effects
=========
None
> [fix] Remove call to .tbController

- website/addons/github/model.py
- website/addons/github/tests/factories.py
- website/addons/github/tests/test_models.py
- website/addons/github/tests/test_serializer.py
Original PR (against now-closed branch): #5330
Purpose
======
Fix registration failures on staging caused by the `getattr` in [archive_folder_name](https://github.com/CenterForOpenScience/osf.io/blob/release/0.66.0-develop/website/addons/base/__init__.py#L727). GH doesn't quite fit the `StorageAddon` generalization, but is close enough to me made to work, and `user/repo` is the closest approximation to `folder_name` that `GitHubNodeSettings` has.
Changes
=======
Make field used by archiver a property that returns the GitHub approximation of what that field should be: 
* `folder_name` <-- `user/repo`
* related fields (`folder_id`, `folder_path`) properties as well.
Side Effects
=========
None expected.
> [fix] Ensure Archiver-required field returns correct value for GH

- website/language.py
- website/static/js/registrationUtils.js
Refs, but does not completely fix, https://openscience.atlassian.net/browse/OSF-5809
Fixes https://openscience.atlassian.net/browse/OSF-5967
When a registration of a draft fails, the UI does not unblock, and the user is left without a course of action.
Instead, the UI should be unblocked correctly, and the user should be taken back to the registration page after dismissing the modal.
See the linked PR for an example test case of a failing registration. (you can fork that project if you don't directly have access). Be warned that the rare failure case in question takes ~1min of waiting before it fails.
For local machine code review purposes, you can force a failure much faster by modifying `projects.project.views.drafts.register_draft_registration` to return a 400 immediately.
> Do not block UI when registration fails [OSF-5967]

- tests/test_project_decorators.py
- tests/test_views.py
- website/project/decorators.py
https://openscience.atlassian.net/browse/OSF-5843
Right now, users can access a collection by visiting it's guid as if it were a normal project. This PR adds a check to the ```@must_be_valid_project``` decorator that checks to see if it's a collection, and throws a 404 error with relevant message if it is.
- Add check to ```@must_be_valid_project``` to see if guid being accessed is a collection
None I can think of
> Don't allow users to view Collections as Projects [OSF-5843]

- website/static/js/contribAdder.js
- website/templates/project/modal_add_contributor.mako
Cover the case where a user has searched for a contributor, selects that contributor, and then searches for a second contributor with a different name.
Make sure to reset `doneSearching` when a subsequent search happens.
https://openscience.atlassian.net/browse/OSF-5654
[OSF-5654]
> [RfR] [OSF-5654] Fix: Show 'loading contributors...' in more cases 

- package.json
Treebeard has been updated to fix a [javascript issue with dismissing
modals](https://github.com/caneruguz/treebeard/pull/95).  This commit
bumps the OSF treebeard dep to get the fix.
> [hotfix] bump treebeard dep to get modal dismiss js fix

- website/static/js/pages/project-settings-page.js
The settings page for registrations doesn't have either a #selectWikiForm
element or a projectSettingsVM object, so check before using those.
> [hotfix] don't run irrelevant JS on registrations settings

- api/institutions/views.py
https://openscience.atlassian.net/browse/OSF-5957
API Swagger docs were throwing a server error:
```
AssertionError: 'InstitutionAuth' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
```
Add a serializer (the most basic one I could think of, the ```JSONAPISerializer```) 
- None anticipated, unless the way that view was intended to be serialized is dramatically different
> [fix] Add serializer to InstitutionAuth to fix API Docs [OSF-5957]

- website/addons/base/views.py
When deleting a file node, pass in the user so that the `TrashedFileNode.deleted_by` gets set.
> [hotfix] Pass user to file delete

- api/files/serializers.py
This fixes [NotImplementedError exceptions for file version lists](https://sentry.cos.io/sentry/osf-iy/issues/479/).
> Add get_absolute_url method to FileVersionSerializer

- api/tokens/serializers.py
Fixes a NotImplementedError when using ESI and the TokenSerializer.
> Add get_absolute_url method to TokenSerializer

- api/nodes/serializers.py
- api_tests/base/test_serializers.py
This test checks that all serializers not based in `api_test` or `test` modules have a get_absolute_url method. 
I also had to add a get_absolute_url method to `NodeAlternativeCitationSerializer` that doesn't do anything, other than throw an exception, because AFAIK Node Alternative Citations don't have a url.
> Force all serializers to have a get_absolute_url method

- framework/auth/core.py
- tests/models/test_user.py
https://openscience.atlassian.net/browse/OSF-5338
```PUT``` and ```PATCH``` methods are very slow on the OSF API at the moment. @chrisseto noticed that was because the ```contributor_to``` and ```visible_contributor_to``` methods were list comprehensions relying on a previous property and not a faster ModularODM Query. This PR changes the ```contributor_to``` and and ```visible_contributor_to``` properties to return a ModularODM query with the appropriate nodes.
- Move the  ```contributed``` property to be closer to the others
- Update the ```contributor_to``` property to return a ModularODM queryset instead of relying on the ```contributed``` property
- Update the ```visible_contributor_to``` property to return a ModularODM queryset instead of relying on the ```contributed``` property
- …
> [fix] Speed up User PUT and PATCH Methods by modifying User properties [OSF-5338]

- api_tests/base/test_utils.py
- api_tests/nodes/views/test_node_detail.py
- framework/status/__init__.py
Purpose
-----------
Allow public projects with publicly editable wikis to be made private via the API.
Closes [OSF-5482]
Changes
------------
Check within push_status_message() to see if we're running inside a Flask context. If so, under most circumstances let the message go, unless it's an error, in which case raise a 400 and pass along the error message.
Also, test all that, including the case directly related to the purpose. h/t to @mfraezz for the mock code in the unit test.
Side effects
push_status_message() isn't actually supposed to be called from anything that the API can get to, but it's littered throughout the model. If it failed, it would 500 for sure, so this is almost certainly better, but we only have the one case right now. The worst would be if someone …
> Change privacy on project with publicly editable wiki [OSF-5482]

- api/institutions/views.py
- website/static/js/myProjects.js
small clean ups and fixes to landing page
* Ordering happens at the node list view, to allow for proper fetching of additional nodes without adding duplicates
* Prevent showing help text that implies that the user is looking at the my projects page (including the tooltips for collections and contributors)
* Current user should be a filter in institution's contributors if they are a contibutor to one of those institutions nodes
> Small fixes to landing page

- scripts/fix_materialized_paths.py
- scripts/tests/test_fix_materialized_paths.py
- website/project/views/comment.py
Fixes issue where the materialized paths returned from waterbutler when renaming a file in dropbox,
github, googledrive and s3 did not start with '`/'` and caused errors when renaming the file again.
Because the materialized path did not match the one used to look up the file, the files received new guids.
> [hotfix] Add missing '/' to start of materialized path

- package.json
- website/static/js/osfHelpers.js
- website/static/js/tests/osfHelpers.test.js
Our karma tests for FormattableDates had two consistent failures.  One was a bad test, the other was a bug in the underlying library.  Both tests happen to pass on Travis because the local timezone on their server is GMT.  These tests will fail in any other timezone.
The first error was caused by FormattableDate assuming that date-only input
represents midnight in local-time.  Our test was comparing the return
value to midnight in UTC, which means the test would fail anywhere but
in +0.  We should probably fix up FormattableDate to consistently return
midnight UTC, but that will require a lot more verification of our
consuming code.  For now, add a new test function that only verifies
the date component of the returned datetime.
The second bug was caused by moment.js not recognizing the …
> fix bugs in FormattableDate JS tests

- admin/pre_reg/views.py
To fix commenting on prereg submissions for admin users.
Removed `deepcopy` copy and used given data. `deepcopy` was not actually copying the dictionary correctly.
Commenting can actually happen
https://openscience.atlassian.net/browse/ADM-86
> Fix comments not saving

- bower.json
Upgrade MathJax and resolve https://openscience.atlassian.net/browse/OSF-5876
MathJax#2.5 -> MathJax2.6
Before (notice trailing |)
After
> Upgrade MathJax

- website/static/js/myProjects.js
Issue https://openscience.atlassian.net/browse/OSF-6016
Continuation of fix https://github.com/CenterForOpenScience/osf.io/pull/5454
**This PR removes retractions from registrations list in new dashboard.**
`Uncaught TypeError: Cannot read property 'contributors' of undefined` is still happening after some JS null-checking added to MyProjects page.
Looking into it more, retractions were still showing up in the registrations list because the API seems to have changed field names to 'withdrawn' instead of 'retracted'.
(On a side node, I do not know why retractions are not embedding for retractions.  They should be embedding.  Contributors are **not** a hidden field on retractions.  If you navigate directly to `http://localhost:8000/v2/registrations/{retraction_id}/?embed=contributors`, …
> [hotfix] Remove retractions from dashboard

- api/caching/listeners.py
- api/caching/tasks.py
- framework/postcommit_tasks/handlers.py
- website/project/views/comment.py
Limit the banning of each api v2 url to once per request. So if the Node xyz12 is saved 7,123 times during one request it will be banned from Varnish once.
- Remove passing fields_changed because as a list it's unhashable and it wasn't being used anyway
- Changed enqueue_postcommit_task to take a tuple comprised of a function and a tuple of arguments
- Changed the save listener to call enqueue_postcommit_task with a function and the instance of the object saved
- Could completely break decaching in varnish.
- I've functionally tested with a debugger attached in both the API and the OSF
> [RFR] Limit Varnish banning to once per url

- api/base/urls.py
Update API to use the recommended syntax for defining URLs; avoids django deprecation warnings.
Syntax should be compatible with 1.8+.
Update URL patterns to new recommended documentation. (see ticket for notes on version compatibility)
Should be none; all routes should load as expected.
https://openscience.atlassian.net/browse/OSF-6012
[#OSF-6012]
> Update API URL syntax to avoid deprecation warnings

- website/citations/providers.py
Fix ability to traverse Zotero's directory structure. The Zotero API *may* have had a "non-breaking" change over the past ~2 months, causing `'parent_list_id'` to be returned as `False` rather than `None`.
* Check for `not <attr>` instead of `<attr> is None`
None. Verified that Mendeley still works as expected.
Side effect of [\[OSF-5359\]](https://openscience.atlassian.net/browse/OSF-5369)
`'__'` is given for `<root_folder>['parent_list_id']` for both citation addons, it's only first-level children that have `<folder>['parent_list_id']` not provided.
> [hotfix] Fix citation listing for Zotero

- website/static/js/profile.js
Fix display of error messages on the education tab of profile page: show field-specific error messages when clicking "add another" while fields are invalid.
Previously, it showed the same message ("*Institution field is required.*") regardless of the actual errors.
Clicking the "add another button" should show/hide user messages in a consistent fashion, rather than hard-coding a different message.
Should be none.
This changes the behavior of a shared class (`ListViewModel`)- look for anomalies on the Jobs profile page, which uses shared code.
https://openscience.atlassian.net/browse/OSF-5175
[#OSF-5175]
> Fix error messages when adding institution

- api/nodes/views.py
- website/addons/base/__init__.py
- website/addons/base/testing/models.py
Fixes API bug where authorized storage addons without a selected folder were throwing `503`'s when links were followed
* Add `.configured` property to base classes
* Use `.configured` instead of `.complete` in API call
* Tests
None, although there may be other places where similar bugs exist. This only fixes a very specific case.
[\[OSF-6019\]](https://openscience.atlassian.net/browse/OSF-6019)
> [feature] Add .configured to <Addon>NodeSettings

- framework/addons/__init__.py
- tests/test_addons_oauth.py
- tests/test_auth.py
- tests/test_models.py
- tests/test_registrations/test_archiver.py
- website/addons/base/__init__.py
- website/addons/base/testing/models.py
- website/addons/twofactor/tests/test_models.py
- website/citations/models.py
Remove addon related backrefs
Things to test:
1. Previously configured addons still work and display properly
* on the user settings page
* on the node settings page
2. Connecting and listing new (and combinations of new/old) addons still works properly
* on the user settings page
* on the node settings page
Full addon regressions are probably unnecessary, though it is theoretically possible that a previously-connected model will be changed but not updated in memory. See Side Effect \# 1. 
* backrefs removed
* tests fixed
* `test_addons` call added to `test` invoke task
1) `.get_addons` or similar now no longer return the same object-in-memory (i.e. the same objects are at different locations on the stack). Objects accessed by a backref are cached due to the way MODM handles these things, …
> [feature] Remove Addon-related backrefs

- tests/test_models.py
- website/project/model.py
Fix [OSF-5942]
If a user deletes a component in a project, and then uses that project as a template to create a new project, the deleted component shows up in the new project's logs.  E.g. "Component 2" was deleted in the original project, but shows up in the logs for the new project: 
When templating a project with components, do not copy components that are deleted.
None.
https://openscience.atlassian.net/browse/OSF-5942
> Do not copy deleted nodes when templating project [OSF-5942]

- api/guids/views.py
- api_tests/base/test_views.py
DRF-Swagger throws and error because `GuidRedirect` does not define a `serializer_class`.
Override `get_serializer_class()` and have it return `None` because setting `serializer_class = None` directly is not allowed. Also add a test to ensure all views either define a `serializer_class` or override `get_serializer_class()`
None.
https://openscience.atlassian.net/browse/OSF-6003
> Override get_serializer_class() in GuidRedirect view [OSF-6003]

- api/base/filters.py
- api_tests/nodes/views/test_node_files_list.py
Certain APIv2 views exit with a 500 error when the filter has a different datatype than the field.
This was evident in the `/v2/nodes/<nid>/files/<provider>` endpoint, when filtering by `last_touched`: this fails for osfstorage, because that provider does not store a value for the field. (by design)
- When filtering fails due to a `TypeError`, Provide a JSONAPI-formatted error message and a 400 error, instead of returning an unhelpful 500.
```
{
"errors": [
{
"source": {
"parameter": "filter"
}, 
"meta": {}, 
"detail": "Could not apply filter to specified field"
}
]
}
```
Should be none, as this is merely handling a previously uncaught exception.
I can create a custom exception class if preferred.
https://openscience.atlassian.net/browse/OSF-4967
> Correctly catch errors when filter type does not match field type

- website/addons/github/static/githubFangornConfig.js
OSF-5732 [](https://openscience.atlassian.net/browse/OSF-5732)
Issue:
- No delete button was appearing for folders created in the root folder of a GitHub repo linked to an OSF account.
Fix:
- Add a line in githubFangornConfig that displays the Delete button in the UI if the user has the appropriate permissions
> Add "delete" button to file view for GitHub folders [OSF-5732]

- website/addons/dataverse/static/dataverseFangornConfig.js
OSF-4551 [](https://openscience.atlassian.net/browse/OSF-4551)
Issue:
- Delete button was erroneously showing up on the file page for a published Dataverse file if a user visited that file immediately after publishing
- The "latest-published" property on the dataverse file (versus the folder) seemed to only be updating after a route change
Fix:
- Add a line in dataverseFangornConfig to set datasetVersion to "latest-published" for the child files of a Dataverse folder
- This line is executed when a Dataverse folder is successfully published from the filetree
> Remove "delete" button from detail page of published Dataverse file [OSF-4551]

- tests/test_auth.py
- website/project/views/node.py
<h3>
Purpose
</h3>
Original PR is [here](https://github.com/CenterForOpenScience/osf.io/pull/5336). I closed that PR and created this one to reflect new changes to fix the bug of no forbidden error when accessing settings page.
<h3>
Changes
</h3>
Change permission of the settings page to make use of the decorator "must_have_permission(READ)".
Add lots of unit tests to test all three decorator functions.
> OSF-5199 No forbidden error when accessing settings page

- .gitignore
- requirements/dev.txt
- scripts/meta/gatherer.py
- tasks/__init__.py
- website/settings/defaults.py
- website/static/css/style.css
- website/static/js/devmodeHelper.js
- website/static/js/pages/base-page.js
- website/templates/base.mako
Purpose
-----------
The github 'Merge and Squash' command broke the git_logs task because. This fixes the problem and makes it a bit nicer for QA because they have clickable links to go to the github pr.
Changes
------------
1. Added a meta script module for gathering info such as this
2. Added a gatherer script to get the last 1000 commits from git and compare those to the last 100 PRs from github. Whatever overlaps there gets its json dumped into a json file. 
3. Added a GITHUB_API_TOKEN setting
4. Added a knockout script to get the json data that was created by the script and show it when you click on the 'Warning: dev mode' banner (and hide it again if you click again)
Side effects
--------------
- It seems to work fine out of dev mode. Well, it should. I tested the else branch of the …
> 0.67.0/fix qa info logging

- api_tests/institutions/views/test_institution_list.py
- tests/test_institution_model.py
- website/institutions/model.py
prevent deleted institutions from being accidently found.
added argument to .find on institution that by default adds ` Q('is_deleted', 'ne', True) `
To find a deleted inst, one would have to call `.find` with a deleted=True argument.
> make institution.find not get deleted_insts

- api/base/middleware.py
- api/base/settings/__init__.py
- api/base/settings/defaults.py
- api/base/wsgi.py
- api_tests/base/test_middleware.py
> ##Purpose
> 
> Third party sites using OAuth or personal access tokens will want to make authenticated requests to our APIv2. The current CORS policy makes this impossible, so this PR aims to allow cross-origin requests when:
> 
> - the client includes the Authorization header (auth still must be checked later in the middleware pipe) AND
> - the client is not sending cookies with the request
> 
> ##Changes
> 
> Slight refactor of the code for dynamically whitelisting Institutions. Given the nature of the CorsMiddleware source, I think origin_not_found_in_white_lists is an elegant place to add custom logic, but checking for cross-origin requests requires having the request in context. So there's a little hackery here to bind the request into that method of the class instance, but it …
> Sam's Original API-CORS PR

- website/static/js/registrationUtils.js
> Fix [Object object] representation of files in registration preview

- website/addons/wiki/templates/edit.mako
- website/templates/include/profile/jobs.mako
- website/templates/include/profile/schools.mako
Fix several issues on staging2 that prevent viewing or editing of pages.
KO punches was more tolerant of syntax errors; when it was removed, hyphenated JS object keys stopped working. The solution is to quote them properly.
I have also attempted to audit for any similar problems. The most effective regex we collectively came up with is below, and did not find any other usages along these lines.
`data\-bind="[^"]*?attr:\s*\{(?:[^:}]+|[^}]+,[^:}\-]+)\-`
`data\-bind="[^"]*?attr:\s*\{(?:[^:}]+|[^}]+,[^:}\-]*?)\-[^}]+\}[^"]*"` (h/t @felliott )
Affected pages include:
- Profile page (jobs and schools tabs
- Wiki edit links
None expected.
https://openscience.atlassian.net/browse/OSF-6075
> Fix ko-related JS errors that prevent loading various pages

- package.json
- website/static/css/style.css
- website/static/js/pages/profile-settings-personal-tokens-detail-page.js
- website/templates/profile/personal_tokens_detail.mako
When creating an access token on the OSF on your settings page, it's not clear that the first time the token is created is the last time you'll be able to view it. This PR adds a bolder warning to the first time the token is displayed, as well as a "copy to clipboard" button to help facilitate using the code later on in an actual application.
- Add clipboardjs to npm installable packages
- copies text to the clipboard without flash!
- Add warning text to first time token is displayed
- Move Cancel, Save, and Delete Buttons to above token display
- These buttons deal directly with any potential token changes, not with the new token that was just created. 
- Small CSS style changes
- Not sure about how well the copy to clipboard button will work on IE - tested locally as much as possible …
> Bold warning on access token creation [#OSF-6058]

- admin/base/settings/defaults.py
Allows the css for the django_admin interface to be used.
Remove essentially duplicate settings
Makes things better. Possibly if a server is cleaned this could lead to other issues that are currently hidden.
None
> [Fix] Remove static dir that isn't used

- api/base/filters.py
- api/institutions/views.py
- api_tests/institutions/views/test_institution_registrations_list.py
- website/project/views/node.py
- website/templates/institution.mako
- website/templates/project/project.mako
- website/templates/project/settings.mako
More institution work clean up
- move institution descriptions to bottom, allow html
- registration institution endpoints don't include retractions
- project settings page includes current institution info
- fix reverse sorting (ordering with a ` - `) of ` get_queryset ` returning a list
- Dont show the affiliated institutions link or the thing at all depending on situation:
- if node is not anonymous:
- if user is not admin or node is a registration:
- node has institution: show Affiliated Institution without a link to settings
- node doesnt have institution: show nothing
- if user is admin and node is not a registration:
- node has institution: show Affiliated Institution with a link to settings
- node doesnt have an institution but user does: show Affiliated Institution with a link to …
> Institution fixes/features 

- requirements.txt
- requirements/constraints.txt
- tasks/__init__.py
- tasks/utils.py
Speed up installation of python requirements, by implementing some basic dependency resolution.
- Pin dependencies for certain addons that are currently allowed to auto-upgrade to newest
- Remove dependency on personal repositories (Lyndsy, Josh, etc)
- Modernize very old dependencies (after thorough review)
- Add a constraints file. Dependency choices were based on analysis of logs without constraints. In general, we chose versions to match the version that was present after final installation- since each run of pip happens separately, the version in OSF base requirements "wins".
- Update all invoke tasks that use pip so that they recognize the constraints file
- Add a reminder into the base requirements file
In general, the final result WITH the constraints file should be the same set …
> Use constraints file to resolve dependency conflicts

- website/addons/dataverse/README.md
Dataverse's demo instance has changed.  We're still pointing to the old url.
Replace `http://dvn-demo.iq.harvard.edu/` with `https://demo.dataverse.org/` in README.md.
Nausea, vomiting, unwanted elbow sentience.
No ticket created for this minor docpatch.  Happy to create one if desired.
> [doc/hotfix] fix dataverse demo url in README.md

- scripts/remove_wiki_title_forward_slashes.py
- scripts/tests/test_remove_wiki_title_forward_slashes.py
There are several wiki pages on production with a "/" in the title and because those titles are invalid the wiki pages cannot be saved.
Remove the "/" from wiki page titles so that they can be handled by #5524 
Related to https://github.com/CenterForOpenScience/osf.io/pull/5524
> [hotfix] Remove forward slashes from wiki page names

- website/static/js/registrationEditorExtensions.js
- website/templates/project/edit_draft_registration.mako
- website/templates/project/registrations.mako
There were some errors with the prereg form on staging2 probably caused by some scoping changes with the removal of ko punches. This PR fixes them.
- Re-implement `toggleUploader`
- Use `.bind` to prevent losing $parent/$root to the current `this` value
> [RfR] Fix JS scoping error after ko punches removal

- tests/test_registrations/test_embargoes.py
- website/project/model.py
- website/static/js/nodesPrivacy.js
- website/templates/emails/pending_embargo_termination_admin.txt.mako
- website/templates/project/project.mako
Fixes for: https://openscience.atlassian.net/browse/OSF-5641
- Misc language changes 
- Disallow making components of embargoes public (frontend/backend)
- fix getNodesOriginal implementation: https://openscience.atlassian.net/browse/OSF-6126
> Embargo Termination Followup [#OSF-5641], [#OSF-6126]

- website/routes.py
- website/templates/emails/conference_submitted.txt.mako
- website/views.py
- Remove OSF4M analytics redirect.
- Also update help links in OSF4M email.
- [OSF-6127](https://openscience.atlassian.net/browse/OSF-6127)
> [feature] [OSF-6127] Remove OSF4M Analytics and Update Email Links

- website/addons/wiki/model.py
This fixes wiki comment decaching.
I added absolute_api_v2_url property to NodeWikiPage model. An unhandled AttributeError was being caused during the decaching process. This caused none of the objects modified during the request to be decached, including the comments URL.
In the future, if people use absolute_api_v2_url property for other things they may get back html instead of JSON since NodeWikiPage does not have a v2 url I just used it's absolute_url which returns HTML. Since varnish is only keeping track of v2 pages now it will be adding NodeWikiPage to it's banlist which will do nothing. If we eventually start caching non-v2 urls this cache invalidation will already be in place.
> Add absolute_api_v2_url property to NodeWikiPage

- website/static/js/nodesPrivacy.js
The PATCH to update the privacy of an embargo was including all the nodes in the tree; which was causing (appropriately) permissions errors for nodes with components. 
- only try to patch the privacy of the root of an embargoed tree
> Only change privacy for root node of embargo [#OSF-5641]

- framework/sessions/__init__.py
Set the `X-Frame-Options` header for all requests.
Set the `X-Frame-Options` header for all requests.
None
https://openscience.atlassian.net/browse/OSF-6113
https://openscience.atlassian.net/browse/SEC-15
> Set the X-Frame-Options header to disallow embedding into frames

- website/templates/emails/pending_registration_admin.txt.mako
The pending registration email says "Clicking the disapproval link will immediately cancel the pending embargo", but this email is for a non-embargoed registration. 
Change the email to say "pending registration" instead of "pending embargo."
None.
https://openscience.atlassian.net/browse/OSF-6007
> Fix language in pending registration email [OSF-6007]

- website/templates/include/profile/jobs.mako
- website/templates/include/profile/schools.mako
- website/templates/profile/account.mako
- website/templates/project/modal_add_contributor.mako
- website/templates/project/modal_add_pointer.mako
- website/templates/project/register_draft.mako
Fix various buttons that stopped working when KO punches was removed.
Bind the correct context to various buttons. For list of buttons affected and problem details, see [#OSF-6132]. Incorporates previous reg fixes by Eric.
This fixes several broken buttons so that they no longer give JS console errors. The results of clicking should now be consistent with the intended behavior.
This was a limited audit for one common failure case; there may be other broken buttons.
https://openscience.atlassian.net/browse/OSF-6132
> Fix KO click events broken by KO punches removal

- api/base/urls.py
- api_tests/base/test_root.py
Visiting https://api.osf.io/ return 404 File Not Found when it should redirect to https://api.osf.io/v2/.
Add url pattern to redirect to root if `/` route is visited.
None
https://openscience.atlassian.net/browse/OSF-6133
> [feature] redirect to root [OSF-6133]

- website/static/js/registrationEditorExtensions.js
- website/static/js/registrationUtils.js
- website/static/js/tests/registrationUtils.test.js
- website/templates/project/registration_editor_extensions.mako
Reverts #5280 because it requires a migration (https://github.com/CenterForOpenScience/osf.io/pull/5494) that is not yet complete. Removing this feature to unblock the release of 0.68.0
> Revert #5280

- tests/test_registrations/test_archiver.py
- website/archiver/tasks.py
- website/archiver/utils.py
- website/project/metadata/prereg-prize.json
- website/project/metadata/schemas.py
- website/project/metadata/veer-1.json
- website/project/model.py
- website/static/css/registrations.css
- website/static/js/registrationEditorExtensions.js
- website/static/js/registrationModal.js
- website/static/js/registrationUtils.js
- website/static/js/tests/registrationUtils.test.js
- website/templates/project/register.mako
- website/templates/project/registration_editor_extensions.mako
- website/templates/project/registration_editor_templates.mako
We had to pull the Veer schema from 0.68 due to a migration needed for https://github.com/CenterForOpenScience/osf.io/pull/5494. This adds it back in to develop.
Revert the commits that pulled out the Veer schema.
> Add back Veer schema

- tests/test_models.py
- website/project/model.py
If Contributor A views wiki comments and Contributor B edits the page, when Contributor A tries to comment there's an "Unable to Resolve" error
Update all contributor comments_viewed_timestamps, not just the user editing the wiki.
None.
https://openscience.atlassian.net/browse/OSF-6138
> Hotfix: Fix unread wiki comments [OSF-6138]

- website/mails/mails.py
I changed the wrong subject lines
- fix the non-admin pending-registration email subject
- fix the non-admin embargo-termination-pending email subject
> [Hotfix] Fix subject for non-admin registration emails

- tests/test_models.py
- website/addons/wiki/model.py
If a wiki has a page name with spaces in it (e.g. "Test Wiki"), it's absolute url is `http://osf.io/<project_id/wiki/Test Wiki`, which redirects to `http://osf.io/<project_id/wiki/Test` because of the space.
%encode the wiki page name so that spaces or special characters do not break the url.
None.
https://openscience.atlassian.net/browse/OSF-6141
> [Hotfix] Encode wiki page_name when creating absolute url [OSF-6141]

- website/addons/twofactor/static/twoFactorUserConfig.js
Two factor authentication code still exists after disabling and enabling. Fixed
In "twoFactorUserConfig.js", added a line so that it resets the field after disabling.
None. At least not that I may think of.
OSF-5239
https://openscience.atlassian.net/browse/OSF-5239
> OSF-5239 Two Factor Auth bug

- api/applications/views.py
- api/tokens/views.py
[With ESI enabled Application and Token API segments would return `""` for each application or token.](https://www.flowdock.com/app/cos/osf-dev/threads/fRTR6af6NTCnxThJApnh0CAm87i) This fixes that problem.
In order to disable the browseable API for these endpoints the list of renderers was specified on the view. The renderer specified didn't process the response, removing quotes from around ESI tags. I changed the renderers list to the two renderers that will remove those quotes.
I functionally tested the endpoints for applications and tokens using both the `?format=json` and the content-type request header. They both returned correct responses and the endpoints did not appear in the browseable API locally. My local setup runs through varnish. It's possible that something is amiss …
> [RFR] Fix ESI content negotiation for Applications and Tokens API segments

- website/templates/footer.mako
landing pages footer links were not properly linking to osf.io, instead remaining on the domain of the institution. This fixes that.
https://openscience.atlassian.net/browse/OSF-6164
> Make sure landing page links go to osf.io

- tests/test_views.py
- website/project/views/node.py
Ensure that project registrations are shown in order of registration date, most recent first.
Change the get_registrations endpoint to explicitly sort registrations by registered_date, instead of assuming they were already sorted and simply reversing the order.
Add a regression test therefor. 
None I can see.
https://openscience.atlassian.net/browse/OSF-6008
> [hotfix] Sort registrations by date, most recent first

- api/tokens/serializers.py
Fix ESI included token list. This resolves a bug that should have been fixed in #5544.
The absolute_url method returns the html version of the token, not the json version. I changed the get_absolute_url method on the token serializer to return the absolute_api_v2_url instead.
Anything using this method and expecting the html link would break but since I am the last committer in the file and my last commit was adding this method I don't believe anyway is expecting this behavior.
> Fix token serializer absolute url method

- api/base/settings/defaults.py
- requirements.txt
Eliminate documentation for routes we don't want documented in the V2 API (tokens and applications)
1. Upgrade django-rest-swagger
2. Add tokens and applications namespaces to the list of ignored namespaces
Shouldn't be. I manually tested the docs and they seem to work at least as well as they 
https://openscience.atlassian.net/browse/OSF-6171
> [Hotfix] Update rest swagger and remove routes that we don't want documented [OSF-6171]

- website/templates/profile/addon_permissions.mako
Fix 500 error when viewing the user addons config page while figshare addon is enabled.
Manually import filter not available to one-off `TemplateLookup` usage.
None expected.
https://openscience.atlassian.net/browse/OSF-6173
> [0.69] Fix 500 error when viewing addonSettings with figshare enabled [#OSF-6173]

- website/addons/dataverse/static/dataverseUserConfig.js
- website/addons/dataverse/templates/dataverse_user_settings.mako
- website/addons/s3/static/s3UserConfig.js
- website/addons/s3/templates/s3_node_settings.mako
- website/addons/s3/templates/s3_user_settings.mako
- website/templates/log_templates.mako
- website/templates/profile/user_settings_default.mako
Fix JS console errors that occurred after authorizing S3 addon on a project settings page. These errors prevented selection of a bucket to be associated with that project.
Also identified and fixed some related errors on user settings page when deauthorizing an addon for a specific node, as well as disconnecting an addon account for the user.
Thanks to Nici for the help getting S3 working locally.
- Fix s3 addon for node settings page
- Fix "Remove addon" modal dialogs on the user settings page; should now be able to remove an addon by clicking the red "x" next to a project name, without the "remove" button generating JS errors. Special cases addressed in this PR are noted as separate items:
- Dataverse
- S3
- Settings for other addons
- Fix "Disconnect account" links on the user settings …
> [0.69] Fix S3 addon selector and and deauth modals [#OSF-6156]

- website/static/js/registrationEditorExtensions.js
- website/static/js/registrationUtils.js
Looks like the HTML escaping introduced in:
https://github.com/CenterForOpenScience/osf.io/pull/5531/files#diff-c7726ca88c3b2e15d44ec996c513ec73R884
might have regressed the fix introduced in https://github.com/CenterForOpenScience/osf.io/pull/5500. 
Move the html escaping into the extensions preview method rather than trying to escape the whole return value. 
Also be more tolerant of question.extra that is now the expected type (non-array values can be ignored)
> [Rfr] Don't osf.htmlEscape question previews

- .travis.yml
@sloria @abought @icereval This should fix the tests for #5543. 
Ubuntu removed the version of libpcre we were manually installing from their server. This bumps it a couple of minor versions.
I changed the file name of the libpcre deb package.
I suppose varnish might not work with this version of libpcre but it's doubtful since it's a minor version change. It's also going to break again down the line. I assume our only choice is to install it manually and that apt-get isn't included in the travis image but it might be worth thinking about a long-term solution.
This was discovered because tests for #5543 were failing.
> Bumping libpcre version for travis/varnish build

- api/nodes/utils.py
- api_tests/nodes/views/test_node_files_list.py
Going to the API endpoint `/v2/node_id/files/<provider>/` for an addon that is not configured on the project throws a 503 service unavailable error.
Throw a 404 NotFound error.
None.
https://openscience.atlassian.net/browse/OSF-4947
> Throw API error if addon is not configured [OSF-4947]

- api/base/filters.py
- api_tests/base/test_filters.py
- api_tests/base/test_views.py
Enable reverse sorting based on user node attributes such as title and date_created
Issue:
https://openscience.atlassian.net/browse/OSF-5237
Removed fields.pop(0) and simply selected the first index via fields[0].
I then included a reverse sort for the case in which the first character in the field was a '-', thus indicating a reverse sort. To implement the reverse sort, I simply switched the places of the 1 and -1 from the original sort.
> Reverse sorting on /users/nodes/ by title gives 500 [OSF-5237]

- website/static/js/comment.js
QA noticed that comments deleted by others were just a little smaller than those deleted by the user. This ups the number of comments loaded at once to 30 -- even on the giant screen, 25 deleted comments by another user show up at once, solving this issue. 
- Change number from 20 to 30 loaded at once
-nope!
https://openscience.atlassian.net/browse/OSF-5891
[#OSF-5891]
> Add just a few more b/c of comments made by others

- api/logs/views.py
- api/nodes/views.py
Fix typos and add node authorization and deauthorization actions to API docs. Related to the `v2/nodes/<node_id>/logs` endpoint.
* biliography --> bibliography
* permissions_update --> permissions_updated
* added `node_authorized` and `node_deauthorized` to ticket
Note: `file_added`, `file_updated`, etc. were not changed to `addon_file_added` because the logs say the name of the addon that was added. So, if the user filters off of `addon_file_added` no results would appear because the actual logs say something like `github_file_added`.
None
https://openscience.atlassian.net/browse/OSF-5371
> [feature] fix typos and add node authorization and deauthorization actions [OSF-5371]

- tests/test_models.py
- website/templates/project/project.mako
Changes introduced in Early Embargo Terminations hid the Make Public button on legacy private registrations.
- Change the conditional to make the button visible again
- Add a unit test
> Make sure legacy private registrations can be made public [OSF-6276]

- website/templates/project/register.mako
Fix registration supplements showing double helper text.
`RegistrationEditor#unwrap` now appends the question description so we don't need it in the template. 
N/A 
https://openscience.atlassian.net/browse/OSF-6278
[OSF-6278]
> Fix: remove dupe description text [OSF-6278]

- api_tests/nodes/views/test_node_files_list.py
Related to https://github.com/CenterForOpenScience/osf.io/pull/5581/files
Addons need to be:
enabled on the node.
authorized on the node.
configured on the node.
Changed tests by adding a method to authenticate github for testing.
[*OSF-6280]
> configure github addon in tests

- website/static/js/fangorn.js
If I cancel a file upload right when its upload progress reaches 100%, a growlbox pops up saying that the upload was cancelled. But when I refresh the page the file is still there.
Only show the cancel upload button when upload progress is less than 100%
None.
https://openscience.atlassian.net/browse/OSF-5972
> Only show cancel file upload button while uploading [OSF-5972]

- website/static/js/pages/wiki-edit-page.js
The first line in the wiki editor doesn't wrap properly when the page first loads. The editor is initialized before the layout panels are fully laid out, so the editor thinks it's wider than it is until it's told otherwise.
After the panels are completely rendered, poke the editor in the resize()
None I can see.
https://openscience.atlassian.net/browse/OSF-6240
> [hotfix] Properly wrap first line in wiki editor [OSF-6240]

- api/base/permissions.py
- api/guids/views.py
- api_tests/base/test_auth.py
- framework/auth/oauth_scopes.py
Users get the error "The user has not authorized access to this view" when viewing the `/v2/guids/<guid>` API route if they are authenticated with a personal access token.
Create a `CoreScope` for the guids view and add it to `ComposedScopes.FULL_READ` instead of directly requiring `ComposedScope.FULL_READ`.
Also check to ensure that the required scopes are lists of `CoreScopes`, not `ComposedScopes`
None.
https://openscience.atlassian.net/browse/OSF-6148
> [Hotfix] Fix guid view scopes [OSF-6148]

- api/guids/views.py
- api_tests/guids/views/test_guid_redirect.py
The API guid redirect route throws an error when viewing a private project/file/etc. even if there is a view_only parameter included in the url.
Add the `view_only parameter` to the redirect url.
None.
https://openscience.atlassian.net/browse/OSF-6161
> [Hotfix] Pass VOL query param to redirect_url [OSF-6161]

- api/base/parsers.py
- api/nodes/permissions.py
- api/nodes/serializers.py
- api/nodes/urls.py
- api/nodes/views.py
- api/registrations/serializers.py
- api/registrations/urls.py
- api/registrations/views.py
- api_tests/nodes/views/test_node_forks_list.py
- api_tests/registrations/views/test_registration_forks.py
- framework/auth/oauth_scopes.py
- tests/factories.py
- website/project/model.py
JIRA https://openscience.atlassian.net/browse/OSF-3897
Adds ability for fork projects and get list of forks via the API v2.  
Functionality added: 
- GET /v2/nodes/{node_id}/forks/
- POST /v2/nodes/{node_id}/forks/
- GET /v2/registrations/{registration_id}/forks/
- POST /v2/registrations/{registration_id}/forks/
To create a fork, issue a POST request to the node forks or the registration forks list endpoint.  Request body should look like this:
```
{
"data": {
"type": "nodes", # MANDATORY
"title": "{insert_title}" # OPTIONAL
}
}
}
```
`forks` relationship link added to Node and Registration serializers.  Also, the title for the fork can be specified up-front, rather than having to edit the title.  If no title supplied, default is still 'Fork of ' + current node title.
> Feature/APIv2 Fork Functionality [OSF-3897]

- website/static/css/add-contributors.css
- website/static/js/contribAdder.js
- website/templates/project/modal_add_contributor.mako
The Add Contributors Modal is too large, and goes off the page on most screens.
Override css on the add contributors table from the default treebeard size.
It _might_ be too awesome.
> change add contributor modal height

- package.json
- website/static/js/apiPersonalToken.js
- website/static/js/koHelpers.js
- website/static/js/pages/profile-settings-personal-tokens-detail-page.js
- website/templates/profile/personal_tokens_detail.mako
A previous PR used clipboardjs to copy a token - this PR uses the already in place ZeroClipboard instead
- Remove clipboardjs dependency from ```package.json```
- Add instantiation of the copy-button client in ```apiPersonalToken.js```
- send correct data to button
More flash!
https://openscience.atlassian.net/browse/OSF-6058
> Copy token with ZeroClipboard instead of clipboardjs [#OSF-6058] [Part 2]

- website/templates/log_list.mako
Change the description of an empty 'Recent Activity' widget to be consistent with the fact that there is no longer a watch button/feature.
Change description of empty 'Recent Activity' widget from "No logs to show. Click the watch icon on a project's page to get activity updates here." to "No logs to show."
[OSF-6022]
> Change message under 'Recent Activity' when no logs to show

- website/addons/github/README.md
- website/addons/github/static/githubFangornConfig.js
"Delete Folder" button should not be available when root node/folder of a provider is selected.
- Hide delete folder if the root is selected.
- Update the docs for setting up GH because the settings page changed some.
Nothing, clicking delete on the root didn't do anything before. This just removes the button.
https://openscience.atlassian.net/browse/OSF-6139
[OSF-6139]
> Remove Delete Folder button when root is selected [OSF-6139]

- website/templates/project/registrations.mako
In the list of project draft registrations, non-preregistration challenge draft registrations have a disabled "Register" button. The button should be enabled because users are able to create those registrations without admin approval.
Always enable the "Register" button if the registration draft does not require approval.
Note: Another option is to make `DraftRegistration.is_approved` return True if the registration does not require approval but that might break other aspects of draft registrations: https://github.com/CenterForOpenScience/osf.io/blob/develop/website/project/model.py#L3868
None.
https://openscience.atlassian.net/browse/OSF-5924
> Enable "Register" button for non-prereg draft registrations [OSF-5924]

- scripts/populate_new_and_noteworthy_projects.py
- website/settings/defaults.py
Jira https://openscience.atlassian.net/browse/OSF-6049
Script to populate new and noteworthy needed some work.  It ran one time and then we turned it off until we could come up with a better way to populate the list.  I've been manually populating it for the last few weeks and came up with a list of items that I thought would help better pick the projects we should highlight.
The original script just pulled recently created nodes and ordered by highest # log actions.
This is what script is pulling:
- Highest number of unique log actions - people that are using a lot of features in the OSF
- Projects from the last month
- Top level projects (not components! not registrations!)
- Projects selected should not have common contributors
- Projects selected should not have "test", "photo", …
> Populate New and Noteworthy Round Two [OSF-6049] 

- website/static/js/keen.js
Keen is rejecting some of our logging payloads because of schema mismatches (e.g. bools being represented as ints).  We have have been posting the entire `currentUser` context var into Keen, but that's fragile since a single data type property mismatch will cause Keen to reject the event.  This PR strips down the user object to just a few bare whitelisted properties.
Once merged, we should stop seeing Keen errors in the sentry logs.
Instead of serializing the full user object, just send the `id`, `locale`, `timezone`, and `entryPoint`.
None expected.
@felliott will need to clean up the Staging collection after this is merged.
Original author: @GageGaskins   This PR was cherry-picked out of https://github.com/CenterForOpenScience/osf.io/pull/5273
[#OSF-6074]
> normalize user payload sent to keen

- website/static/js/pages/project-settings-page.js
Fix double escaped text in addon removal modals; name should not be rendered as `<li>figshare</li>`
Remove redundant use of `htmlEscape`.
None expected. Profile addon removal modals code is different. (there may be some dead code in the latter file, but outside scope of this PR). Shouldn't have any addon names that will introdsuce display artifacts.
https://openscience.atlassian.net/browse/OSF-6298
> [0.69-ish] Fix text in project addon removal modal

- api_tests/files/views/test_file_detail.py
- framework/auth/core.py
- framework/auth/signals.py
- tests/test_notifications.py
- website/addons/osfstorage/listeners.py
- website/notifications/utils.py
- website/project/model.py
- website/project/signals.py
- website/signals.py
De-duplicate the `contributor_removed` signal, put project-related signals in `website.project.signals`. 
Contributors that are removed individually (`remove_contributor()` instead of just `remove_contributors()`) will now have any checked-out files checked-in when removed.
* Remove duplicate `contributor_removed` from `framework.auth.signals`
* Put `node_deleted` signal in `website.project.signals` rather than `framework.auth.signals`
* Update senders, listeners, tests to use correct signals.
* Minor: `return all(<bool_list>)` when trying to determine if any items in `<bool_list>` are `False`
None
None that I know of ¯\\\_(ツ)_/¯ 
1) Have a write contributor check out a file
2) Remove the write contributor via Contributors page
3) Ensure file was checked back in.
A1) Make node, configure …
> [Hotfix] Logical signal placement, related check-in/out fix

- api/nodes/views.py
- framework/auth/oauth_scopes.py
JIRA https://openscience.atlassian.net/browse/OSF-6309
Logs and forks are not included in osf.full_write or osf.full_read scopes which means we can't access logs or fork endpoints in Ember OSF.
Adds log read/fork read to osf.full_read and fork write to osf.full_write.
> [Ready to Review] Add logs and forks scope [OSF-6309]

- framework/auth/oauth_scopes.py
Fix malformed list of scope permissions. Because the thing appended at the bottom was redundant with the rest of the list, this should not alter the list of views accessible for a token with any of the existing publicly available scopes. This PR resolves a badly formed list revealed during auditing.
Since the only affected scopes (osf.full_read/osf.full_write) are already covered by runscope tests, there is a good chance that QA will already have this covered: just check that runscope oauth tests involving nodes still pass after this is merged.
Run `python -m framework.auth.oauth_scopes` to verify.
Before, there was a tuple embedded at the end of a flat list.
```
'osf.full_read': ['collections.base_read',
'comments.data_read',
'guids.base_read',
'institutions_read',
'nodes.base_read', …
```
> Fix malformed list of scope permissions

- website/addons/dataverse/templates/log_templates.mako
- website/addons/osfstorage/templates/log_templates.mako
File/folder names are not being displayed for osfstorage file delete actions:
because the expected display string isn't being assigned to the `data-bind`'s `text` attribute.
Add `text: ` to `data-bind` in the osfstorage delete template and the dataverse study_linked template.
Nope.
No ticket.
> [featurefix] Fix missing file names in log templates

- website/templates/util/render_node.mako
Make the category icons show in the components widget of the project summary page. It looks like this was broken by the markup safe feature because whatever handled the wrapping of the item in quotes use the wrong style of quotes for the surrounding part of the tag.
Change single quotes to double quotes and vice versa. 
Not expected; it's pretty well localized.
https://openscience.atlassian.net/browse/OSF-6308
> Make category icon show again by fixing quotes [OSF-6308]

- api/caching/listeners.py
- framework/analytics/__init__.py
- framework/postcommit_tasks/handlers.py
- website/project/views/comment.py
Fix locking of mongo records in user_activity_counters caused by incrementing the same user's counter concurrently in different requests.
I refactored the postcommit handler to accept func, args, and kwargs. I created a decorator which allows limiting the number of times the enqueued function can be run per request. If DEBUG=True then the functions are NOT enqueued. Changing the task storage object to an OrderedDict should enable tasks to be run in the order that they were added to the queue.
It's possible that the hash created could not be unique enough. This would cause tasks to be lost. Suggestions are welcome. My initial effort tried pickling the `raw` list but I encountered things that were unable to be pickled (mongo collection passed in from the analytics tests). …
> [RFR] Eliminate record lock on log creation activity count

- website/static/css/citations_widget.css
Display citations with selected style.
Add `display: inline;` to make selected style visible.
Consider investigating whether or not upgrading `citeproc.js` would fix this.
[#OSF-5893](https://openscience.atlassian.net/browse/OSF-5893)
> [Hotfix] Apply Alt Citation Styles [OSF-5893]

- website/mails/listeners.py
Prevent ` folder has no download count ` error to be triggered in sending osf4m queued mails.
Makes the presend find the first file, rather than the first whatever under osfstorage root.
Create a new osf4m project by sending an email. Then, delete all the files in it, leaving only a folder. If the email is received anyways, this worked!
> hotfix: prevent osf4m queued mail from crashing by checking for files

- framework/auth/views.py
- website/templates/emails/contributor_added.txt.mako
- website/templates/emails/forward_invite.txt.mako
- website/templates/emails/forward_invite_registered.txt.mako
- website/templates/emails/invite.txt.mako
- website/templates/emails/new_public_project.html.mako
- website/templates/emails/no_addon.html.mako
- website/templates/emails/no_login.html.mako
- website/templates/emails/password_reset.txt.mako
- website/templates/emails/pending_invite.txt.mako
- website/templates/emails/pending_registered.txt.mako
- website/templates/emails/welcome_osf4m.html.mako
Use HTTPS in emails, especially when that email could contain keys (e.g. password resetting, user confirmation, registration approval)
* Hard-coded links updated
* Generation of `reset_link` updated
* Verified registration links use `settings.DOMAIN`
* Verified user confirmation, merge links use `settings.DOMAIN`
* Verified queued emails use `settings.DOMAIN`
None expected
To test, 
* request a password reset via https://osf.io/forgotpassword/
* ensure the reset link uses https and work properly.
* As footer links (to osf.io and cos.io) are not present in this email, generate a different email and verify that they both use https and work.
[OSF-6343](https://openscience.atlassian.net/browse/OSF-6343)
> [Hotfix] Use HTTPS in emails [#OSF-6343]

- website/static/js/pages/wiki-edit-page.js
Fixes regression where wiki comment view model was getting instantiated even if there was no wiki.
Only instantiate the wiki comment view model if `window.contextVars.wiki.wikiID !== null`.
None
https://openscience.atlassian.net/browse/OSF-6349
Fix [#OSF-6349]
> Fix checking for wikis with no ids

- scripts/tests/test_clone_wiki_pages.py
- scripts/tests/test_remove_wiki_title_forward_slashes.py
- tests/test_models.py
- website/addons/wiki/model.py
- website/addons/wiki/tests/test_wiki.py
- website/project/model.py
There is at least one project on prod, https://osf.io/ny23d/, whose home wiki page record has `is_current` field set to `False`, even though it only has one version. The side effect of this is that forks of the project do not contain the wiki content (see https://github.com/CenterForOpenScience/osf.io/blob/585dca524b374210c615d0e28edb47366466a8d6/website/addons/wiki/model.py#L306-L307). 
Removes the NodeWikiPage.is_current field and makes it a property so that there can be no inconsistency with `Node.wiki_pages_current`.
Will need to unset the `is_current` field for all `nodewikipage` records.
In mongo shell:
```
db.nodewikipage.update({}, {$unset: {is_current: ""}}, {multi: true})
```
https://openscience.atlassian.net/browse/OSF-6350
> [hold] [hotfix] Make sure wiki content is copied to forks; make is_current a property

- website/addons/base/views.py
- website/addons/osfstorage/views.py
Improve display of "this file has been deleted" error messages.
1. Start saving the deleting user for osfstorage.
2. Hide the 'view' and 'revision' action buttons when the file is deleted/missing.
3. If an osfstorage file doesn't have a `deleted_by` field, just show the date of deletion.
<None expected>
[#OSF-5883]
> Fixes for deleted/missing file error messages

- website/archiver/tasks.py
[OSF-5801](https://openscience.atlassian.net/browse/OSF-5801)
Fix failing Dataverse registrations
Update website/archiver/tasks.py to avoid duplicate copy calls (draft and published versions were stumbling over each other)
None
[#OSF-5801]
> [Hotfix]Registrations with Dataverse fail [OSF-5801]

- website/templates/project/project.mako
Fix regression introduced in #5617: ensure that non-editors can see project category and descriptions for public projects across the OSF. Hotfix to master: let me know what testing is needed.
This can be tested by looking at category and description of a public project when a user is logged out. Reported for: 
https://osf.io/e4rvz/
In my defense, the AJAX editor widgets were a nice improvement for the three people on earth who could see them. Smidge of a regression for the other 7 billion, though.
Add a default value (from mako) for people who can't see the editor controls.
- People who are not editors on a project should see the CATEGORY and DESCRIPTION fields displayed correctly, as static text
- People who are editors on a project should have interactive editor widgets to change the …
> [hotfix] Allow non-editors to see project category and description

- api/nodes/serializers.py
- api_tests/nodes/views/test_node_contributors_list.py
Ticket https://openscience.atlassian.net/browse/OSF-6376
ValueError not being handled properly.  Getting a 500 error when user attempts an update or bulk update request on contributors that causes there to be no bibliographic contributors. 
In example below, there are two contributors and I am attempting to make them both non-bibliographic, which isn't allowed.  Instead of handling the error properly, a server error is returned.
```
BULK PATCH /v2/nodes/<node_id>/contributors/
{
"data": [{
"id": "12345",
"type": "contributors",
"bibliographic": "False"
}
},
{
"id": "abcde",
"type": "contributors", 
"bibliographic": "False"
}
}]
}
```
Properly handles 500 error by throwing a validation error.
> Feature/APIv2 500 Error Update Contributors [OSF-6376]

- website/addons/github/static/githubFangornConfig.js
The purpose of this PR is to resolve [[OSF-6346]](https://openscience.atlassian.net/browse/OSF-6346): a style inconsistency stemming from the fact that the GitHub add-on uses a different fangorn helper than the other add-ons. The specific problem was had three parts:
1. A discrepancy in modal button style
2. Incorrect placement of the modal header content (placed in body instead of in header)
3. If a non-GitHub file foo.bar was deleted earlier in the same session, "Delete foo.bar?" would be in the modal header. Otherwise, the header would be empty.
1. To fix button style, I changed the classes of the buttons to align with what's in `fangorn.js`.
2. To fix the placement of the header content, I moved the header text to the modal .update() function, consistent with `fangorn.js`.
3. This …
> Make Github delete confirmation modal match standard delete confirmation modal [OSF-6346]

- website/static/js/profile.js
- website/templates/include/profile/jobs.mako
- website/templates/include/profile/names.mako
- website/templates/include/profile/schools.mako
- website/templates/include/profile/social.mako
The save button has no signifier while a profile save is taking place.  Users do not know that the save request is being made. 
Now, after clicking save, The save button will grey and change to "Saving" until the request is completed, then it will change back to save.
before request returns
after request returns
Also fixed a small bug in the social section of the profile where "Settings Updated" was on the same line as the save button.
https://openscience.atlassian.net/browse/OSF-3912
> add Saving state to save button on profile

- website/static/js/profile.js
Currently, in Profile Settings, a user is able to fill out a start and end date for either an institution or employment and click 'Save' without also filling out the required institution/employer fields. A green 'Settings updated' message appears, even though upon refresh, none of the fields were actually saved.
A user is now unable to click 'Save' when editing institutions or employment unless the required fields ('Institution' or 'Employer' respectively) are filled out. When a user tries to fill out just the start and end dates without entering the required fields and then click 'Save', a red error message appears like "Institution/employer required". This matches the current correct behavior for when a user tries to fill out a field like 'Job title' and click 'Save' without also …
> Change required fields [OSF-6059]

- website/project/model.py
- website/templates/log_templates.mako
The formatting of embargo end logs is inconsistent with other logs. This fixes the trailing period.
- ~~Added words to the log template to match other logs~~
- Removed the trailing period
- ~~Change node to `registered_from_id` (previously registration id)~~
None
[OSF-6341 "End embargo early" log has incorrect outdated language](https://openscience.atlassian.net/browse/OSF-6341)
> "End embargo early" log has incorrect outdated language [OSF-6341]

- website/static/js/pages/project-dashboard-page.js
To prevent mithril from breaking when looking for the instLogo div which is not existent if the node has no affiliated institutions.
Check if the node has institutions before looking for id `instLogo`
> Fix attempting to put logos on non-existing div breaking mithril

- scripts/migrate_regressed_registration_logs.py
- scripts/retract_registrations.py
- website/project/model.py
- website/project/sanctions.py
Ticket https://openscience.atlassian.net/browse/OSF-6409
Some registration logs have regressed.  Registration-related logs were supposed to have a params['node'] field and a params['registration'] field.  Now some logs do not have params['registration'] field and params['node'] field points to the registration. This means original_node is incorrect since it is supposed to be the same as params['node'].
Restores params['registration'] fields where missing.  Points params['node'] fields to node instead of registration where incorrect.  Original_node should be set to params['node'].
**params['registration'] may be missing and params['node'] and original_node incorrectly pointing to the registration for the following log actions:**
- embargo_approved
- embargo_cancelled
- embargo_terminated
- …
> Feature/fix regressed registration logs[OSF-6409]

- website/static/js/institutionProjectSettings.js
Prevent the use of windows.contextVars directly.
use the data that is already being passed to the module
https://openscience.atlassian.net/browse/OSF-6416
> Do not use window contextvars directly in institutionProjectSettings.js

- website/addons/dataverse/static/dataverseFangornConfig.js
- website/addons/dataverse/views.py
- website/static/js/fangorn.js
(These two tickets were so similar that the code changes were essentially the same... and thus the pull requests were also merged)
Previous to this change, the publish option for a dataset would only be available if the entire dataverse had not yet been published. If the user publishes their dataverse/dataset once, then the publish option would be removed. Further changes to the draft dataverse would not be able to be published through the Fangorn interface, and a user would have to go to the dataverse website to do this.
The behavior is implemented as follows:
Initially, with an unpublished dataverse/dataset, the publish option is available.
Once the dataset is published, the publish option is removed.
If the user uploads or deletes a file from the draft dataset, the publish option is …
> Updates to Dataverse Publishing flow and UI [OSF-6397]  [OSF-4553] 

- CHANGELOG
- website/addons/wiki/static/pagedown-ace/Markdown.Editor.js
- website/addons/wiki/templates/edit.mako
- website/addons/wiki/templates/wiki-bar-modal-help.mako
Addition of a question button to the wiki markup bar in order toi help users navigate to the page describing how markdown is done. When pressed it just pops-up with a modal box that users will see and get a link from.
Edited the Markdown.Editor.js to add the button and give it a data-target that points to the wiki-bar-modal-help.mako page which is what will popup, Also changed the edit.mako page to include the wiki-bar-modal-help.mako page when the page is loaded.
If the edit bar is used anywhere else in the code then the bar will pop up with a link to the wiki pop up markdown page. Talked to QA and they said the only place that the edit bar is used is the wiki so it should be fine.
https://openscience.atlassian.net/browse/OSF-2080
> Wiki help bar that adds syntax guidelines [OSF-2080]

- api/caching/listeners.py
- framework/analytics/__init__.py
- framework/postcommit_tasks/handlers.py
- website/notifications/utils.py
- website/project/views/comment.py
This should fix tasks locking user objects in mongo. 
It adds the ability for the postcommit handler decorator to make tasks run in celery instead of running postcommit, inside or after the request. It also decorates several tasks that were causing locks.
If celery is down or backed up some of the tasks may be delayed to the point that users may notice the discrepancy in their activity counters.
This is a second pass at fixing OSF-6294 without so many side effects.
https://openscience.atlassian.net/browse/OSF-6294
> [RFR] Feature/fix locking by moving tasks to celery [OSF-6294]

- website/static/js/profile.js
related to https://github.com/CenterForOpenScience/osf.io/pull/5714
QA caught a problem where the .always call is not "allllllwayyyys" (get it) working on Safari or Firefox to enable the save button after an AJAX request.  And by not always, I mean ever.  So I am calling the request in the handle success and handle error functions.
https://openscience.atlassian.net/browse/OSF-3912
> [RFR] Remove .always call and unsave button in function

- framework/auth/core.py
- tests/models/test_user.py
- website/profile/views.py
- website/templates/profile/account.mako
This prevents confusion when a user requests to deactivate their account then refreshes the page and sees that the deactivate button is still available.
By adding a requestedDeactivation to the User class, the page checks if the account is pending deactivation on load, and in the case that the user has requested deactivation, it displays a message informing the user rather than the button.
Before:
After:
N/A
https://openscience.atlassian.net/browse/OSF-2735
> [Feature] Hides account deactivation button upon refresh if user has requested to deactivate. [OSF-2735]

- api/base/middleware.py
- api/base/settings/defaults.py
- The APIv2's CORSMiddleware had a little extra code accidentally brought in during a merge. This removes the dead code.
- FF sends its `ACCESS_CONTROL_REQUEST_HEADERS` as a comma separated list with no spaces which broke the CORSMiddleware's check for whether or not to send CORS headers on options requests. This fixes that.
> CORSMiddleware cleanup/fixes

- website/routes.py
- website/static/css/pages/home-page.css
- website/static/js/components/institution.js
- website/static/js/components/utils.js
- website/static/js/home-page/institutionsPanelPlugin.js
- website/static/js/pages/home-page.js
- website/templates/base.mako
To aid affiliated users in discovering their affiliated institutions landing page.
Add institution logo links to Dashboard. Links go to OSF4I landing pages.
Unaffiliated institutions are muted.
The `InstitutionImg` mithril component added in this PR should be used to render logo images for other features, e.g. https://github.com/CenterForOpenScience/osf.io/pull/5754 . Ping @hmoco 
https://openscience.atlassian.net/browse/OSF-6311 .
> Add institution logo links to Dashboard page

- api/registrations/serializers.py
- api/registrations/views.py
Reopening #5761 as a hotfix instead
In the API, registration files were being redirected to ```/node/```  instead of ```/registrations/``` and were so causing an error. This adds a registration file provider serializer to send the correct information.
```/v2/registrations/3nb7j/files/``` should now have ```relationships>files>links>related``` be referring to ```registrations``` instead of ```nodes```
```
{
"data": [
{
"files": {
"links": {
"related": {
"href": "http://localhost:8000/v2/registrations/3nb7j/files/osfstorage/",
"meta": {}
}
}
}
}
]
}
```
- Add RegistrationProviderSerializer
- Use that serializer
- nope
https://openscience.atlassian.net/browse/OSF-6413
> hotfix/repair registrations files provider relationship [#OSF-6413]

- api/base/pagination.py
- api_tests/nodes/views/test_node_comments_list.py
When filtering by  node id, and using related counts, a non found node would throw a 500 error. This PR changes the filter function to check if a node being filtered on exists before trying to paginate.
- Add check for root_target to filter for pagination
- Add test to make sure that no results are found when filtering on a fake node id with related counts
- none anticipated
https://openscience.atlassian.net/browse/OSF-6427
> Hotfix/ Fix API referent error on get_paginated_response [#OSF-6427

- website/static/js/institutionProjectSettings.js
Related to https://github.com/CenterForOpenScience/osf.io/pull/5726
Users working on a project without components were not getting a warning if they were removing a non-affiliated institution.  Also
1.  A bug where an institution could sometimes show up in the add list even if it shouldn't. 
2.  A div was not properly closed, leading to a red text disaster!
https://openscience.atlassian.net/browse/OSF-6165
> [RFR] Give warning message to users with childless nodes

- website/static/js/fangorn.js
There was an inconsistency between the icon on the "rename" button when in the main menu vs. while entering a name. Also, low resolutions would reflow the text inside the buttons while entering a name, causing a malformed button. 
- Use pencil icon for rename in both instances
- Remove text from "rename" and "create" buttons that appear when entering text
None
https://openscience.atlassian.net/browse/OSF-6288
> Improve file widget "Rename" & "Create folder" buttons [OSF-6288]

- website/static/js/institutionProjectSettings.js
Related to #5726
QA correctly pointed out that sometimes the modal for adding to multiple shows when it is not necessary.  If adding an institution and all the children already have the institution for instance.  Or if there is no admin privileges on the children.
*  Do not send requests for nodes that the user does not have permission to change
*  Do not show modal if no child nodes will be changed (due to their current state or privileges)
https://openscience.atlassian.net/browse/OSF-6165
> [RFR] Add logic to only show modal when appropriate

- website/static/js/institutionProjectSettings.js
Related to #5726
QA found a bug where if you set and unset an institution, the single institution does not work.  I needed to reset modifyChildren after a request is made.
https://openscience.atlassian.net/browse/OSF-6165
> [rfr] reset modifyChildren after request

- api/institutions/views.py
- api_tests/institutions/views/test_institution_nodes_list.py
- api_tests/institutions/views/test_institution_registrations_list.py
- website/institutions/model.py
- website/institutions/views.py
- website/search/elastic_search.py
Allow for deletion of institutions using the `is_deleted` flag, and making sure deleted intitutions dont have a landing page and can't be found in search.
Institution now has is_deleted attribute. Update_search looks for that to delete the elastic doc.
Also this https://openscience.atlassian.net/browse/OSF-6453
> [hotfix]Allow deletion of Institutions;  don't show private nodes on OSF4I landing pages

- framework/auth/__init__.py
- framework/auth/core.py
- website/project/views/node.py
From https://github.com/CenterForOpenScience/osf.io/pull/5784
-------------
[OSF-6440](https://openscience.atlassian.net/browse/OSF-6440)
Update user's affiliated email domain institution before user gets queried to create initial project.
Update framework/auth/core.py add "def update_affiliated_institutions_by_email_domain" to "class User"
Update framework/auth/__init__.py update "def authenticate" to call User.update_affiliated_institutions_by_email_domain
Update  website/project/views/node.py  update def node_setting to call User.update_affiliated_institutions_by_email_domain
None
[#OSF-6440]
> Add check for affiliation by email domain at login

- api/caching/listeners.py
- framework/postcommit_tasks/handlers.py
- website/project/views/comment.py
This should fix the locking problem and analytics not updating.
Because I'm just calling delay on the celery tasks it could still create locking but the retries and the 60 second wait should mitigate that until I can get a PR in that fixes it for good. Because of the retries things put into celery could potentially run out of order.
> Hand-patching codes back in for celery tasks

- framework/auth/views.py
- tests/test_views.py
Related to PR 5000
Change login from login.mako to cas login.
https://openscience.atlassian.net/browse/OSF-4542
> change redirect url to cas

- website/addons/forward/templates/forward_widget.mako
- website/addons/forward/templates/log_templates.mako
- website/templates/include/profile/social.mako
- website/templates/public/pages/meeting_body.mako
- External links from the profile page, OSF for meetings pages, or forward widgets open tabs in a new window, which could lead to some undesirable effects (see tickets for more detail)
- Remove "_blank" target from link in forward widget on configured projects
- Remove "_blank" target from log link for changed forward URL
- Remove "_blank" target from link in external websites in the user profile
- Remove "_blank" target from external conference website URL
- None anticipated
https://openscience.atlassian.net/browse/OSF-6426
> Fix external sites opening in new tabs [#OSF-6426]

- framework/auth/__init__.py
- framework/auth/cas.py
- framework/auth/views.py
https://github.com/CenterForOpenScience/osf.io/pull/5000/
Ironically, auth_login is no longer used when logging in.  So cleaning up the old emails should happen in cas.py now.
https://openscience.atlassian.net/browse/OSF-5536
> move clean function to cas from auth_login

- website/templates/log_list.mako
Currently, the deactivated user's name is not shown in logs.
* Show the deactivated user's name in log
* Show "A deactivated user" in an anonymous view-only link log
None
https://openscience.atlassian.net/browse/OSF-6266
> [Feature] show deactivated user's name in logs [OSF-6266]

- scripts/meta/gatherer.py
- tests/base.py
- website/static/js/devModeControls.js
- website/static/js/pages/base-page.js
- website/templates/base.mako
Make the widget that shows commits to QA and other interested parties more useful
1. Get the name of the current branch from git 
2. Check the current branch versus master and only list the commits that are different
3. Find the commits that match the two PR types (normal merge and squashed merge) and pull out the PR name from that
4. Get the PR info from github
5. Show the branch name in the widget as well
1. It's not going to be able to show any useful information for local branches, only branches that are on centerforopenscience/osf.io
2. Will only work with git 1.7 or greater
No ticket
> Gather more accurate data about the commits

- website/static/js/pages/project-dashboard-page.js
- Currently, if you view a project that has an affiliated institution with an anonymous VOL, parts of the project dashboard will break due to a mithril error (attempting to render the ```institutionLogo``` mithril component into the [```#instLogo```](https://github.com/CenterForOpenScience/osf.io/blob/5441d3bffa89b99658d8dbd09e9e610963d6383d/website/templates/project/project.mako#L25) div, which doesn't exist). This PR fixes this by not rendering the ```institutionLogo``` mithril component when viewing a project through an anonymous VOL.
[OSF-6486](https://openscience.atlassian.net/browse/OSF-6486)
> [hotfix] Institution Logo w Anonymous VOL

- website/static/js/nodesPrivacy.js
Currently, the confirmation modal when making a project/component private is the same as the confirmation modal when making a project/component public.
* add check for whether the project is public or private
* add check for whether the node is a project or component
* add message for changing project/component to private
None
https://openscience.atlassian.net/browse/OSF-6480
> [Hotfix] change make private modal text [OSF-6480]

- api_tests/files/views/test_file_detail.py
- website/files/models/osfstorage.py
Fix for file checkin/checkout.  Via the API, if a file was checked in, you could send a request to check it in.  If a file was already checked out, you could send a request to check it out.  This also created a bunch of unnecessary logs.
So this request to `PATCH /v2/files/{file_id}/` for an already checked-in file, would check it in again.  So there would be two logs created, one for `file_tag_added`(correct) and one for `checked_in` (incorrect).
```
If already checked in, this request would result in another checkin.
{
"data": {
"id": "<file_id>",
"type": "files", 
"tags": ["hey"],
"checkout": null
}
}
}
```
```
If file checked out, this request would result in another checkout.
{
"data": {
"id": "<file_id>",
"type": "files", 
"tags": ["hey"],
"checkout": …
```
> Feature/File Checkin Checkout Fix [OSF-6487]

- website/static/js/fangorn.js
In the file widget or on the files page, If a user clicked on a file, clicked rename, and then clicked on a Storage heading or project title, it appeared as though they could edit the name and then save the changes. Submitting the changes resulted in an "unable to rename" error. The text box should never be presented to the user in the first place.
This PR changes the Add-on Storage titles or project titles back to the default toolbar if they're clicked after clicking the rename button.
- If a project title or addon name row is clicked, reset the toolbar to the default instead of staying on the Edit screen.
There might be a more complex project or storage heading action that this breaks, but I have not been able to find it yet. Apologies if it does! …
> Add check for project or addonroot onclick, return to default toolbar [#OSF-6437]

- website/static/js/_allLogTexts.js
- website/static/js/logTextParser.js
- website/static/js/registrationModal.js
- website/static/js/registrationUtils.js
- website/static/js/tests/registrationModal.test.js
When attempting to embargo a Registration, if the user attempts to pick a date 3 days away (as is required to Embargo) after 8pm, the system informs them that they must pick a date at least 3 days away, and won't let them pick that date (ie. On August 31st 8:36pm, the calendar does not recognize September 3rd as a valid date). The problem lied in the timezone difference between local time and UTC time. There is a four hour difference (hence why it had a problem starting at 8pm). So the valid date calculation needed to account for the time zone difference.
- Added the Timezone Offset when calculating the chosen end date in milliseconds
- Fixed some of formatting.
- The max length (4 years) might have a similar issue to this.
https://openscience.atlassian.net/browse/OSF-4304
> [Feature] Allow embargo registrations at 3 days out [OSF-4304]

- website/addons/base/views.py
- website/addons/wiki/model.py
- website/addons/wiki/shareServer.js
- website/addons/wiki/static/ShareJSDoc.js
[OSF-6300](https://openscience.atlassian.net/browse/OSF-6300)
Fix to get latest version in file editor panel
Add code to refresh active sharejs sessions. For future use in v2 API wiki updating
Update website/addons/base/views.py add version to key for file_guid_to_share_uuids
Update website/addons/wiki/model.py add def update_active_sharejs for use in future API updates
Update website/addons/wiki/shareServer.js add reload call
Update website/addons/wiki/static/ShareJSDoc.js add reload case
1. This code updates sharejs code and will require sharejs to be bounced.
2. If sharejs restart is deferred, any new shared editing sessions initiated from the file view after the code is updated will not share(js) with sessions initiated before the code is updated. This does not effect the wiki sharejs …
> [RFR][Feature][OSF-6300]File view pane, edit panel shows earlier version

- website/static/js/fangorn.js
Cancelling pending uploads to Dataverse and Github (those that require synchronous uploads) failed to cancel uploads. Instead, **fangorn** would attempt to upload a cancelled file, which would either succeed (undesired) or raise an error, stopping all uploads (also undesired). However, it would appear cancelled to the user because **fangorn** removes all uploads the user cancels, cancelled or not, from the UI. This was because uploads were removed from the UI regardless of whether they were found in `dropzone`.
In addition, when cancelling an upload in progress by a synchronous provider, the next upload that gets processed is not cancellable (even though the old code searched `dropzone.files`) due to `dropzone` not adding it to the `files` list.
- Add robust searching through …
> [feature fix] Uploads do not continue after Dataverse upload cancel [OSF-5459]

- website/static/js/myProjects.js
- website/static/js/pages/statistics-page.js
- website/static/js/project-organizer.js
I did an audit of the google analytics events in the Dashboard and My Projects pages.  There are a couple items that are triggering firing of two events.
1) There is an 'x' (close) button as well as a 'Cancel' button on the Add Collection modal on the My Projects page.   When the close button is clicked, the 'cancel' button event tracking was also fired.
2) There are a few items we track in the mobile view only.  If you click on the button with a horizontal ellipsis beside a project in the mobile view to open up the information panel, the event tracking for a single project being selected is also fired. 
Corrected firing of two events for these two actions.
Before the date that this gets merged in, event tracking will be incorrect. After this date, event tracking for these two items …
> Feature/Google Analytics Audit [OSF-6479]

- website/static/js/registrationUtils.js
If the window is narrow when looking at a preview of a registration, the formatting is strange.
* switch from col-md to col-xs
None
https://openscience.atlassian.net/browse/OSF-6464
> [Feature] fix registration preview style on narrow window [OSF-6464]

- website/search/elastic_search.py
- website/templates/search.mako
Currently, the user cannot tell if a file is attached to a retracted registration in search results. This PR adds "Withdrawn" before "Registration File" so that the results look similar to retracted registrations.
* Add `is_retracted` to elastic search file_doc
* Add "Withdrawn" text in search results if the file is attached to a retracted node
I had to run `inv rebuild_search` on my local but I'm not sure what that means for production.
https://openscience.atlassian.net/browse/OSF-6456
> [Feature] add withdrawn before retracted registration files in search [OSF-6456]

- website/addons/wiki/views.py
[OSF-6471](https://openscience.atlassian.net/browse/OSF-6471)
Fix "wiki not live updating before the first save"
Update website/addons/wiki/views.py move "version_settings = below "empty home page logic.
None
[#OSF-6471]
> [RFR][Hotfix][OSF-6471]wiki not live updating before the first save

- framework/celery_tasks/handlers.py
- framework/postcommit_tasks/handlers.py
- website/archiver/tasks.py
- website/settings/defaults.py
- website/settings/local-travis.py
Celery is breaking RabbitMQ because it's storing all completed tasks in it to the point it runs out of memory. [This makes it only store errors.](http://docs.celeryproject.org/en/latest/configuration.html#celery-ignore-result)
This one's for you @icereval!
Added two settings to defaults.py
It's possible that it will make Flower very confused about what's going on or potentially completely useless. I don't remember if it does or not. We can deploy it to staging and check, maybe? I would say visibility at the cost of rabbit dying every few days might not be worth it. An alternative solution would be to write a custom kombu task that runs in beat and empties out everything older than X or to switch the result backend to postgres or redis and setup the existing celery task to empty out old …
> Add setting to make celery ignore everything but errors

- tests/test_views.py
- website/routes.py
- website/views.py
- As of now, the osf.io/help/ page has not been made, and is a dead end
- Displays the /faq/ page on attempting to reach the /help/ page
- Added to a Rule in routes.py, where going to /help/ will display the /faq/ mako template.
- Added a test case that tests to make sure the page is reached in test_views.py
https://openscience.atlassian.net/browse/OSF-4039
> Have /help/ display the /faq/ page [#OSF-4039]

- api/base/serializers.py
- api/caching/tests/test_caching.py
- api_tests/base/test_serializers.py
Keep the relationship link when embedding the relationship
1. Pull the relationship link creation out of the else block in the serializer
2. Add a test
No
https://openscience.atlassian.net/browse/OSF-6488
> Include api relationships even if embedding [OSF-6488]

- api/comments/serializers.py
[OSF-6467](https://openscience.atlassian.net/browse/OSF-6467)
Allow PATCH call to "delete" comments
Update api/comments/serializers.py update "def update" to allow changing attribute "deleted" to true
None
[#OSF-6467]
> [RFR][Feature][OSF-6467]Enable Comments PATCH to update "deleted" attribute to true

- api/caching/listeners.py
- framework/analytics/__init__.py
- framework/analytics/migrate.py
- framework/analytics/piwik.py
- framework/analytics/tasks.py
- framework/postcommit_tasks/handlers.py
- tests/framework_tests/test_analytics.py
- website/project/model.py
- website/project/views/comment.py
**REPLACES #5809**
Currently, postcommit tasks could run in any order, asynchronously. This changes them to run as a celery chain: synchronously and in order.
There is a separate queue for celery specific postcommit tasks. This queue is run as a celery chain after the request's transaction is committed successfully.
Tasks decorated with run_postcommit could be delayed to the point where a user would notice.
> [RFR] Make Postcommit tasks marked as celery run as a chain

- website/static/js/fangorn.js
To fix a bug found in #5808 by the wonderful and thorough QA. Previously, storage providers and project titles would reset to default toolbar when clicked if in edit mode, but components would NOT switch back to default, causing a repeat of the "text box that should not be there" error. 
- Now also check for the "component" node type. And use NodeType to check for both projects and components onclick for better consistency.
None I can think of
https://openscience.atlassian.net/browse/OSF-6437
> Also return to default toolbar for Component clicks [#OSF-6437]

- api/base/serializers.py
- tests/test_rubeus.py
- website/addons/base/generic_views.py
- website/addons/dataverse/views.py
- website/addons/github/views.py
- website/util/__init__.py
- website/util/rubeus.py
Anonymous view only links that were connected to a github repo still showed their github username as a part of the connected repo storage heading - since usernames can lead to identification, they should be hidden if the files are being shown as part of a view only link. 
In fact, to anonymize a little more, no part of the file path should be shown at all on anonymous links - only the addon heading. 
- Add private_key kwarg that can be passed when building the addon root name for the hgrid file tree
- if that private_key kwarg is passed, and checks out as anonymous, remove the file path or folder or bucket name from the name of the heading for all addons
- refactor ```is_anonymized``` in ```api.base.serializers``` to facilitate reuse elsewhere
- use new …
> github usernames appearing in View Only links [#OSF-6449]

- website/static/js/fangorn.js
:bug: found by @felliott , related to renaming text box appearing where it shouldn't, was console errors that appeared when an item wasn't selected, but instead the expand contract button.
This PR checks for a selected item before trying to mess with its toolbar reset properties, thus getting rid of the console errors and keeping the rename bugfix intact.
- Check for selected item before assessing things about it
Hopefully none
https://openscience.atlassian.net/browse/OSF-6437
> Check for selected item before trying to reset toolbar [#OSF-6437]

- api/nodes/serializers.py
- api/nodes/views.py
- api/registrations/serializers.py
- api_tests/base/test_serializers.py
- framework/auth/oauth_scopes.py
Need to advertise draft registration relationship links under nodes so we can have the links in ember-osf.  Also need draft_read and draft_write in available scopes.
Adds draft registration relationship links to node serialization but not registration serialization.  Moves draft_read and draft_write to full_read and full_write scopes.
None
https://openscience.atlassian.net/browse/OSF-3087
> Feature/Return Draft Registration Relationship for Nodes [OSF-3087]

- website/static/js/addProjectPlugin.js
- website/static/js/home-page/newAndNoteworthyPlugin.js
Fixes two existing bugs associated with the `Create Project` button on the dashboard:
* Sometimes disabled in edge case associated with `Most Popular` nodes
* Hitting return multiple times creates multiple projects
* Avoid throwing `TypeErrors` when attempting to access possibly-undefined vars
* Add simple locking mechanism to only allow the creation of only one project at a time
None known
[OSF-6500](https://openscience.atlassian.net/browse/OSF-6500)
> [Hotfix] Dashboard Create Button Fixes [#OSF-6500]

- website/static/js/fangorn.js
Cancelling all uploads for an asynchronous provider (without any synchronous uploads) would not work, due to `syncFileCache` not being defined for async-only uploads.
- Check if `syncFileCache !== undefined` before checking synchronous providers
N/A
https://openscience.atlassian.net/browse/OSF-5459
> Uploads do not continue after Dataverse upload cancel [OSF-5459]

- scripts/populate_institutions.py
- website/notifications/exceptions.py
- website/notifications/listeners.py
- website/notifications/utils.py
[OSF-6504](https://openscience.atlassian.net/browse/OSF-6504)
Fix "populate_institutions.py no longer works"
Add  website/notifications/exceptions.py containing class InvalidSubscriptionError(NodeError)
Update website/notifications/listeners.py to try/except and catch InvalidSubscriptionError
Update website/notifications/utils.py "def subscribe_user_to_notifications" raise InvalidSubscriptionError for institutions/deleted nodes/collections targets
None
[#OSF-6504]
> [RFR][Feature][OSF-6504]Add exception handling for invalid subscription targets 

- tasks/__init__.py
- website/maintenance.py
- website/routes.py
- website/static/js/pages/base-page.js
- website/templates/base.mako
To put up a maintenance notice right now, we manually commit and uncommit code that adds a specified banner to the top of the page.  This adds instead a way to do this programmatically, either through an invoke task or by calling the maintenance module directly (future uses in the admin module!)
Examples:
```
invoke set_maintenance_state
invoke set_maintenance_state --start 2016-03-16T15:41:00-04:00
invoke set_maintenance_state --end 2016-03-16T15:41:00-04:00
```
- Add a maintenance module with a few options:
- **set_maintenance**:  make a new collection called 'maintenance' in the database that will have some info about what period to set the maintenance from. Either pass in a start and end date or have them be calculated for you. Dates default to UTC if no timezone info is specified.
- …
> Add ability to invoke automatic maintenance notice [#OSF-6482]

- scripts/migration/migrate_metadata_for_veer_pregistrations.py
- website/project/metadata/veer-1.json
ID missing from one of the nested questions in Veer Preregistration Schema which was making API requests to update registration metadata fail.  A jsonschema could not be created to validate metadata via the API due to the missing ID.   Also, the missing ID in the schema caused an undefined key in the registration metadata.  
Adds missing id to schema.  Adds migration script to fix drafts and registrations that have used this schema.
Requires small migration.
https://openscience.atlassian.net/browse/OSF-6510
> [migration] Hotfix/Veer Preregistration Schema Fix [OSF-6510]

- tests/base.py
- tests/test_models.py
- tests/test_notifications.py
- website/notifications/listeners.py
- website/notifications/utils.py
- website/notifications/views.py
- website/project/model.py
- website/project/views/contributor.py
Newly created components should automatically be set to "Adopt settings from parent project"
Currently on staging, new components are getting the defaults from User Settings, Notifications, and not inheriting the settings from the parent project.
* have created components default to `adopt_parent`
* only projects where the user has changed the settings appear in configured projects
Users have no subscription objects for components they create.
https://openscience.atlassian.net/browse/OSF-5748
> [Feature fix] global notification settings [OSF-5748]

- website/notifications/views.py
Fix 500s when changing default settings.
Check if the node exists before setting field.
None
https://openscience.atlassian.net/browse/OSF-5748
> [Feature fix] check if node exists before changing field value [OSF-5748]

- framework/auth/core.py
- tests/test_models.py
- tests/test_notifications.py
- website/notifications/utils.py
- website/notifications/views.py
- website/project/model.py
* Forks should be created with default settings
* Configured projects should be based on the user not the node
* Check if `_id` exists before sending contributor added 
* Use `dirty_dict` instead of `notification_settings_dirty`
None
https://openscience.atlassian.net/browse/OSF-5748
> [Feature fix] have forks default proper settings [OSF-5748]

- website/project/model.py
Add comment to explain why, when adding a fork, the contributor_added signal is deferred until after save.
* add comment
None
https://openscience.atlassian.net/browse/OSF-5748
> [Feature fix] add comment about sending signal after save [OSF-5748]

- api_tests/registrations/views/test_registration_list.py
- website/project/model.py
ValidationValueError on model when Embargo End Date is not far enough in the future should read "Embargo end date must be at least three days in the future." rather than "Embargo end date must be more than one day in the future'.
Error message changed. 
Now APIv2 error (which throws error model) when embargo end date is incorrect will match front end.
https://openscience.atlassian.net/browse/OSF-3087
> Feature/Error Message on Model upon Incorrect Embargo End Date [OSF-3087]

- website/addons/wiki/templates/edit.mako
- website/static/css/style.css
On the Wiki Edit pane, the setup of the Revert/Save buttons made the box have an overflow.  This was unnecessary for the interface, and didn't make it very user-friendly.  
The purpose of this PR is to remove the scrollbar on the Edit pane.  The scrollbar appeared by default on the pane when the page loaded.  
Currently when a user goes to the Edit pane on their Wiki page, the scrollbar will appear by default on the Edit pane.  All of the changes made for this PR involve fixing the styling on the Edit pane in order to remove the scrollbar.  
The main changes included getting rid of the fixed height and overflow properties for the Edit pane. 
Shouldn't be any
<a href="https://openscience.atlassian.net/browse/OSF-5970">https://openscience.atlassian.net/browse/OSF-5970</a>
> Remove overflow scrollbar on Wiki Edit pane [OSF-5970]

- website/static/js/components/carousel.js
- website/static/js/home-page/institutionsPanelPlugin.js
Currently the arrows on the carousel are not highly visible if there are more than six institutions displayed.
* reduce the amount of institutions displayed at a time to 5 if there are more than 6 institutions
* center institutions
More than six:
Six or less:
Depending on the `CAROUSEL_WIDTH`, the padding on the control arrows in `carousel.js` may have to be adjusted. The alignment of the arrows is correct for column widths of 2/carousel widths of 5 or 6.
https://openscience.atlassian.net/browse/OSF-6478
> [Feature] reduce number of institutions so arrows can be seen [OSF-6478]

- website/static/js/project.js
Remove the TypeError that is thrown when viewing user profiles.
Adding if statements to catch null objects that functions attempt to access. 
https://openscience.atlassian.net/browse/OSF-6303
> Type error on user profile

- website/addons/dataverse/static/dataverseFangornConfig.js
- website/addons/github/static/githubFangornConfig.js
- website/static/js/fangorn.js
- website/static/js/pages/project-dashboard-page.js
[OSF-5939](https://openscience.atlassian.net/browse/OSF-5939)
In project overview page and project file view page...
- Add last modified date to file info.
- Allow sorting by modified date
GitHub files now show their file size in project files view
Dataverse Raven logging should now work
Update website/addons/dataverse/static/dataverseFangornConfig.js
- Require raven-js to resolve unknown name
- Add columns size, downloads, and modified to allow for sorting by last modified date
Update website/addons/github/static/githubFangornConfig.js
- Minor clean up
- Add columns size, downloads, and modified to allow for sorting by last modified date
Update  website/static/js/fangorn.js 
- Require moment-js for handling date/time
- Add  function _fangornModifiedColumn to normalize modified date using …
> [RFR][Feature][OSF-5939]Sort files by Dates in project(overview) page and project files page

- website/addons/github/static/githubFangornConfig.js
- website/static/js/myProjects.js
Make the github rename icon the consistent with other addons.
Changes irregular "A" or fa-font icon to the fa-pencil icon, using a very simple js change.
Can confidently say there are none
https://openscience.atlassian.net/browse/OSF-6465
> Change github file widget rename icon to pencil [OSF-6465]

- website/templates/emails/invite.txt.mako
To allow a user visit a project they were just invited to, before registering.
modified email templates and send parameters, add comments to template explain template function
none that I know of.
https://openscience.atlassian.net/browse/OSF-3211
> Unregistered contributor email should have link to project that they are invited to [OSF-3211][redo]

- website/addons/dataverse/static/dataverseFangornConfig.js
- website/addons/github/static/githubFangornConfig.js
This PR is a fix for [PR#5817](https://github.com/CenterForOpenScience/osf.io/pull/5817/files)
[OSF-5939](https://openscience.atlassian.net/browse/OSF-5939)
Don't add modified column in fileview placement
Update website/addons/dataverse/static/dataverseFangornConfig.js
Don't add modified column in fileview placement
Update website/addons/github/static/githubFangornConfig.js
Don't add modified column in fileview placement
None
[#OSF-5939]
> [RFR][Fix][#OSF-5939]Don't add modified column in fileview placement

- website/templates/emails/invite.txt.mako
Made the language for invite email even clearer. 
Simple modification to the invite.txt.mako template.
https://openscience.atlassian.net/browse/OSF-3211
> Improve Invite email link language [OSF-3211]

- api/nodes/serializers.py
- api/registrations/serializers.py
- api_tests/nodes/views/test_node_detail.py
Support ember-osf comment functionality, by allowing project pages to fetch only project comments by default. (and exclude comments on other items owned by the node)
This makes nodes and registrations endpoints consistent with how the same links already work for files endpoints.
Appends `filter[target]=node_id` to the serialized relationship url for `/v2/nodes/<nid>` and `/v2/registrations/<rid>` endpoints (list and detail views).
None expected.
1. Make a comment on a node, and a file owned by OSF storage on that node. Ensure that the comment appears on the web.
2. Make a registration, and do the same
3. Visit the API endpoints for the node, and the registration (eg `http://localhost:8000/v2/nodes/f263w/` and `http://localhost:8000/v2/nodes/abc12/`); ensure that `filter[target]=<node_id>` …
> [ember-osf] Add node ID to apiv2 comment rel links [OSF-6533]

- api/files/serializers.py
- api_tests/files/views/test_file_detail.py
- api_tests/utils.py
Add a "guid" field to APIv2 file serializer.
This will support commenting in ember-osf. (which requires specifying file GUID as a target)
The field name is deliberately generic.
- Add serializer field
- Add unit tests
- Update files tests to support "file without a guid" scenario
None expected. This is a new field with a well-defined default fallback value.
https://openscience.atlassian.net/browse/OSF-6534
> [ember-osf] Add "GUID" field to apiv2 files serializer [OSF-6534]

- website/addons/osfstorage/tests/test_models.py
- website/files/models/base.py
- website/files/models/osfstorage.py
Moving a folder from osfstorage to an external provider reports an error, even though the move actually succeeds.  This is caused by the guid-preservation code not knowing how to look up the children of trashed osfstorage folders.  While fixing this, I also discovered that we weren't properly returning guids we did find, meaning they would still point to the old TrashedFileNode.
* Taught `website.files.models.osfstorage.get_file_guids` to handle trashed osfstorage folders.
* Removed pass-by-reference code from `get_file_guids`.  It was buggy, unnecessary, and unused.  Both `get_file_guids` implementations now just return lists of guids found.
* Added tests for `osfstorage.get_file_guids`
None expected.
[#OSF-6393] https://openscience.atlassian.net/browse/OSF-6393
> [hotfix] [OSF-6393] move folders from osfstorage

- website/static/js/devModeControls.js
Ensure that loading a page from a release branch doesn't try to get the git_branch text file used only on staging and development
Check for the existence of the selector that the knockout is being applied to, and don't create the viewmodel if the selector doesn't exist.
I am not set up to test outside of dev mode, so this would be good to check. I don't *think* it should cause any problems. Still works fine in dev mode, and it should just not do anything outside of dev mode, so should marginally increase page load speed.
https://openscience.atlassian.net/browse/OSF-6535
> Hotfix/no git branch 404 [OSF-6535]

- website/templates/base.mako
Removes the devModeControls div when not in master so the previous fix will apply
Removed the else branch on the mako template that added an empty div. Tested by manually removing all divs to ensure that nothing was loaded and removed the file to make sure file didn't 404 if the div didn't exist.
No, should be good.
https://openscience.atlassian.net/browse/OSF-6535
> Hotfix/Remove devModeControls when not in dev mode

- scripts/refresh_addon_tokens.py
- website/addons/base/exceptions.py
- website/addons/googledrive/serializer.py
- website/addons/googledrive/views.py
- website/addons/mendeley/model.py
- website/oauth/models/__init__.py
The cron script to refresh tokens for addons that have expiring tokens seems to have failed, and the logs are unhelpful.
* Improve error logging
* Limit the number of outgoing requests to 5/second
* `InvalidAuthError(AddonError)` removed, it was an unnecessary wrapper
None
[OSF-5853](https://openscience.atlassian.net/browse/OSF-5853)
> [Hotfix] Rate limit when refreshing OAuth token [OSF-5853]

- scripts/refresh_addon_tokens.py
- tests/factories.py
- tests/test_oauth.py
- website/addons/box/model.py
- website/addons/box/settings/defaults.py
- website/addons/googledrive/model.py
- website/addons/googledrive/settings/defaults.py
- website/addons/mendeley/model.py
- website/addons/mendeley/settings/defaults.py
- website/oauth/models/__init__.py
It's pointless to make 500+ failing requests each morning for tokens that have expired. This adds a mechanism to see, on a per-provider basis, whether or not tokens are passed the window of time that they can even be refreshed.
* Add `has_expired_credentials` property on authenticaed `ExternalProvider` instances for providers that support it (defaults to `False`)
* Update addons that this affects with `expiry_time`
* Update script to skip expired accounts
* Update text fixtures to support this
* Add tests for this behavior
* Improve error handling in script
None
[OSF-5853](https://openscience.atlassian.net/browse/OSF-5853)
> [Hotfix] Skip expired credentials in token refresh script [OSF-5853]

- api_tests/nodes/views/test_node_logs.py
- tests/base.py
- website/project/model.py
- website/static/js/myProjects.js
Prevent test from fail when time of exactly one second is parsed to the microsecond
Dates now parsed using the dateutils, which does not throw error.
I noticed small bug in assert_date_equals method which I fixed.
https://openscience.atlassian.net/browse/OSF-6414
> Fix zero microsecond testing bug [OSF-6414]

- website/static/js/fangorn.js
This PR is a fix for [PR#5817 OSF-5939](https://github.com/CenterForOpenScience/osf.io/pull/5817/files)
[OSF-6548](https://openscience.atlassian.net/browse/OSF-6548)
Fix incorrect sorting for non-iso formatted dates
Update website/static/js/fangorn.js
Update item.data.modified with iso formatted date instead of just pushing iso date to column. Treebeard sort funtion goes against item.data.modified not column data.
None
[#OSF-6548]
> [RFR][Fix][#OSF-6548]Fix sorting for non-iso date formats

- website/templates/public/pages/faq.mako
Clarify FAQ on registration size limits
Clarification the 5GB limit includes OSF Storage and Add-on Storage.
Fewer help desk emails
> hotfix/ clarify limit on storage on registrations

- api/files/views.py
- api/nodes/views.py
This adds documentation (explaining the new "guid" field for files api endpoints) to the long-form prose in the browseable API and swagger for endpoints, where applicable. This adds text, but not functionality.
Swagger docs will also continue to show the field-level help text that was already present.
Adds documentation for the API to swagger docs, and browseable docs, for these endpoints:
-  `v2/nodes/<nid>/files/osfstorage/`
- `/v2/files/{file_id}`
- `v2/docs`
This edits docstrings only. No side effects expected.
https://openscience.atlassian.net/browse/OSF-6536
> Add documentation for new GUID field on file endpoints [#OSF-6536]

- website/static/js/fangorn.js
This PR is a hotfix for [PR#5817 OSF-5939](https://github.com/CenterForOpenScience/osf.io/pull/5817/files)
[OSF-5939](https://openscience.atlassian.net/browse/OSF-5939)
Fix incorrect sorting for DropBox v1 API formatted dates
Update website/static/js/fangorn.js
Update item.data.modified with OSF formatted date instead of just pushing OSF date to column. Treebeard sort funtion goes against item.data.modified not column data.
None
[#OSF-5939]
> [RFR][Hotfix][#OSF-5939] Fix sorting for DropBox

- website/addons/dataverse/static/dataverseUserConfig.js
- website/addons/s3/static/s3UserConfig.js
- website/static/js/addonSettings.js
- website/static/js/pages/profile-settings-addons-page.js
Change how the collapse/expand caret (osfToggleHeight) is loaded.
Changed how the caret is loaded in dataverseUserConfig.js and s3UserConfig.js since Dataverse and S3 are the only two addons that are not loaded through OAuthAddonSettingsViewModel.
For the addons that are loaded through OAuthAddonSettingsViewModel, the caret is loaded for each addon. 
None that I can think of.
https://openscience.atlassian.net/browse/OSF-4265
> Fix how osfToggleHeight is loaded [OSF-4265]

- api/users/serializers.py
- api_tests/users/views/test_user_detail.py
API V2 keys were not correctly cased to be processed by ember-osf.
All "Social" keys changed to underscores or all lowercase, instead of camelCasing.
Should be no side effects.
https://openscience.atlassian.net/browse/OSF-6537
> Make User API Endpoint use Underscores/lowercase keys [OSF-6537]

- tests/test_views.py
- website/project/model.py
- website/project/views/node.py
- website/routes.py
- website/templates/project/project.mako
- website/util/rubeus.py
[OSF-2718](https://openscience.atlassian.net/browse/OSF-2718)
In project overview page and project file view page...
- Enable viewing components masked by unauthorized parent.
- Allow for breadcrumbs to to get back from masked components.
In project overview page
- Update components widget to match info in file tree widget.
Remove visibility of unauthorized components. "Private Component"
Updated tests/test_views.py
* Updated various for get_children now get_readable_descendants
* Fixed test_pointer_list_read_contributor_cannot_remove_public_component_entry now actually public
* Added def test_readable_descendants_masked_by_permissions
Updated website/project/model.py
* Added def find_readable_antecedent to find logical parent
* Added def find_readable_descendants to find logical children …
> [RFR][Feature][OSF-2718]Can't see all components when permission to one is denied

- api/base/serializers.py
- api/nodes/serializers.py
- api_tests/nodes/views/test_node_contributors_detail.py
- api_tests/nodes/views/test_node_contributors_list.py
- api_tests/nodes/views/test_node_embeds.py
- api_tests/nodes/views/test_node_list.py
- api_tests/nodes/views/test_view_only_query_parameter.py
- api_tests/registrations/views/test_registration_embeds.py
Replaces #5824 
--------------------
Contributors don't have guids, so it used the id of the user, beign unique for user per node. However that becomes a problem if you look for the ocntributor data universally, as missing the node information will lead to duplicate results (problems encountered in ember-osf). New ids for contributors are unique, and are concatenations of user and node ids.
Contributor ids are now a concatenation of node id and user id, separated by `-`
https://openscience.atlassian.net/browse/OSF-6490
> [feature] Concatenate contributor ids

- website/addons/dataverse/serializer.py
- website/addons/dataverse/views.py
- website/static/js/citationGrid.js
The DOI foundation has [stopped listing the `dx` resolver as "preferred", and started to support HTTPS](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). I hope I correctly understood your code to generate/display DOI links, not parse them.
I omitted the same change in `citeproc.js`, because [an upstream PR](https://bitbucket.org/fbennett/citeproc-js/pull-requests/8/generate-secure-doi-links/diff) is pending.
> secure DOIs

- website/addons/forward/static/forwardConfig.js
- website/addons/forward/templates/forward_node_settings.mako
On the project settings page, when "External Links" under "Select Add-ons" is enabled, the button is no longer disabled when the URL field is empty. A new error message consistent with other OSF pages now appears when the user clicks the button without entering anything into the URL field (previously, the default HTML5 form validation error appeared). 
Before:
After:
[OSF-3546]
> Button no longer disabled when URL field is empty on project settings page

- api/nodes/serializers.py
- api_tests/nodes/views/test_node_addons.py
Raise an exception with a useful error if a user specifies either `folder_id` or `folder_path` but not both for a `PUT`/`PATCH` to google drive, which requires both.
* Raise error
* Add tests
None
[OSF-6593](https://openscience.atlassian.net/browse/OSF-6593)
`PATCH` on authorized node: <img width="845" alt="screen shot 2016-07-05 at 10 40 41" src="https://cloud.githubusercontent.com/assets/5659262/16590590/39c839f8-42a6-11e6-8686-9ed8a360d922.png">
`PATCH` on authorized node: <img width="856" alt="screen shot 2016-07-05 at 10 44 43" src="https://cloud.githubusercontent.com/assets/5659262/16590589/39c62d52-42a6-11e6-82b8-88f64918d51f.png">
`PUT` on unauthorized node: <img width="845" alt="screen shot 2016-07-05 at 11 46 56" src="https://cloud.githubusercontent.com/assets/5659262/16590591/39 …
> [Hotfix] Raise error on bad GDrive folder select [OSF-6593]

- addons.json
- tests/test_registrations/test_archiver.py
- website/addons/forward/model.py
- website/addons/forward/tests/test_models.py
From ticket:
>Registrations should include external links. 
* Allow external links to be registered.
* Add test for registered external links.
None
[OSF-6518](https://openscience.atlassian.net/browse/OSF-6518)
> [Hotfix] Register External Links [OSF-6518]

- website/addons/wiki/templates/edit.mako
- website/static/css/pages/wiki-page.css
This PR edits the bootstrap styling of the view panel on the edit wiki page so that, on collapse, the buttons and labels stay within the container and aligned properly. 
- Changed small column to large column so that content collapses at an earlier breakpoint
-Adding more buttons in the panel may cause it to break yet again.
https://openscience.atlassian.net/browse/OSF-5966
> Resize Wiki Edit Page Error

- api/identifiers/urls.py
- api_tests/registrations/views/test_registration_embeds.py
Embedding identifiers on the api registrations endpoint leads to a 500 error. 
https://api.osf.io/v2/registrations/?embed=identifiers
- Add identifier list to the identifiers urls.py so that embeds can get the correct URL for self links in the reverse URL search
- Add a test to make sure the embed returns a desired status code
https://openscience.atlassian.net/browse/OSF-6628
> Hotfix - Fix 500 error when embedding identifiers on registration API view [#OSF-6628]

- website/static/js/myProjects.js
There was no help text for empty collections besides "All my projects" and "All my registrations," which left an empty box in the view. Turns out this text existed but did not show due to an oversight in using the ternary operator; adding the string to the boolean occurred first, which always returned true.
- Restored existing help text to working order
- Altered `nonLoadTemplate` logic
- Added specific help text for bookmarks
None.
https://openscience.atlassian.net/browse/OSF-6532
> Collections: when none show help text [OSF-6532]

- framework/auth/views.py
- tests/test_views.py
- tests/webtest_tests.py
Limit the rate of uses' attempt to resending confirmation email. This prevents unconfirmed user from being spammed.
- Add `throttle_period_expired()` check before `send_confirm_email()`
- Users will be notified if they make a second request too fast.
- Add related unit tests
No
https://openscience.atlassian.net/browse/OSF-6561
> [Fix] Add rate-limit to resending confirmation email [#OSF-6561]

- website/static/js/components/logFeed.js
Fix the paginator's current page is not in the middle when there are two clips on both sides.
Before changes:
After changes:
https://openscience.atlassian.net/browse/OSF-6587
> [#OSF-6587]Page numbers for logs

- api_tests/nodes/views/test_node_logs.py
- framework/addons/__init__.py
Fix bug where deleting an addon would create unnecessary log messages. 
Fixed code that checked if addon that was being deleted had attribute 'external_accounts' 
Wrote unit test that checks that deleting an addon does not make any unnecessary messages in the log. Test fails without change, passes with it. 
None
https://openscience.atlassian.net/browse/OSF-6011
> #OSF-6011 Fixed bug 'Extra logs when deauthorizing addons'

- tasks/__init__.py
The default test browser in `karma.conf.js` [is PhantomJS](https://github.com/CenterForOpenScience/osf.io/blob/ef98b0bf6eb5b520fff990306bc58ea3fcaca061/karma.conf.js#L6), not Chrome.
s/Chrome/PhantomJS
n/a
Noticed while working on [OSF-6447](https://openscience.atlassian.net/browse/OSF-6447).
> Fix `inv karma` docstring

- website/static/css/style.css
- website/static/js/passwordForms.js
- website/templates/claim_account.mako
- website/templates/landing.mako
- website/templates/profile/account.mako
- website/templates/public/login.mako
- website/templates/public/resetpassword.mako
Make minor ui changes and fix interaction bugs
- Password strength indicator text and progress bar colors changed to three bootstrap colors with overrides for landing page
- Layout changed so that progress bar and text is on the same row
- Fixed validation text appearing twice by removing the ko-validation automatic insertion 
- Other minor style changes
Most likely not. Someone should check that all possible locations where the password strength check appears are addressed. I think they are, based on global search of the code. I was able to test all instances, seems to be working fine. 
Partially fulfilling requirements of https://openscience.atlassian.net/browse/OSF-3457
> Password verification ui and functional changes [OSF-3457]

- website/addons/dataverse/static/dataverseNodeConfig.js
- website/addons/dataverse/static/dataverseUserConfig.js
Dataverse v4.4 was just released, changing the path the user must visit to fetch their api token.  The new v4.4 path is  `/dataverseuser.xhtml?selectTab=apiTokenTab`.  UVa's DV instance is v4.3 which uses the old path of `/account/apitoken`.  
This patch will use the old token path if the host is UVa, otherwise it will default to the new path. 
This will break the link for `apitest`, but `apitest` is due to be upgraded to v4.4 shortly and is currently broken for unrelated reasons.
The v4.4 url change also causes a minor user incovenience.  If a user clicks on the api token link while not yet logged in, they are taken to the DV login page.  The DV login page does not preserve the query parameter in the redirect target, so the user is then sent to their account page, where 'API Token' is …
> [hotfix] fix Dataverse api token url for DV v4.4 [OSF-6665]

- website/project/views/node.py
- website/static/js/pointers.js
- website/templates/project/modal_add_pointer.mako
The _Add Links_ modal does not distinguish between projects of the same name and author, which is particularly problematic for projects that have been registered multiple times (see screenshot).
Note that registrations have the same creation and modification date as their parent project, but have a separate registration date. This means that the "last modified" date could come before the registration date, which can be very confusing. Thus, only the registration date is shown for registrations.
Revision 1:
- Added tooltip conditionally displaying date created and date modified or date registered, depending on whether or not the node is a registration
- Added `dateCreated`, `dateModified`, `isRegistration`, and `dateRegistered` to `search_node` endpoint
- Removed tooltips on **+** and …
> [Feature] No way to distinguish between projects in Add Links modal [OSF-4046]

- website/static/js/iconmap.js
In the files tree, subprojects created as components didn't have a project icon next to them.
When you create a subproject, Fangorn labels it as technically a component. In Treebeard, `resolveIcon` looked for a component icon when it should have looked for the project icon. So, I added the project icon to the `componentIcons` array do let the subproject be read as a component, but still be given a project Icon. This seems to be an easier solution than changing how subprojects are read altogether.
I just added something to an icon array, so I don't think that would affect anything else.
[OSF-6545](https://openscience.atlassian.net/browse/OSF-6545)
> [OSF-6545]Eliminate Project Ambiguity

- website/static/js/components/logFeed.js
Fix the paginator when there are one eclipse at the beginning.
Before change:
After change:
https://openscience.atlassian.net/browse/OSF-6660
> Page number for logs with ellipsis on the left not showing [#OSF-6660]

- admin/templates/pre_reg/draft_detail.html
Allow ADM prereg users to comment on prereg drafts 
* Use correct cookie name.
None
[OSF-6674](https://openscience.atlassian.net/browse/OSF-6674)
> [Hotfix] ADM Prereg commenting [OSF-6674]

- README.md
The install instructions for Linux are pretty Ubuntu-centric 
Where we mention Ubuntu in the README, supply the same RHEL command to install. Fedora users will be able to substitute `dnf` for `yum` and have the instructions work.
> Update install instructions to include RHEL and CentOS

- website/static/js/myProjects.js
Fix bug where contributors are listed multiple times on the My Projects page and clicking on a contributor does not show all of the projects they contributed to, only the most recent.
Added code that made comparison between the contributors use the contributor's user id instead of the contributor id. Up until recently, those were the same, because the contributor id was incorrectly using the user's id. Now the contributor id is unique and the user's id is used instead.
None
https://openscience.atlassian.net/browse/OSF-6690
> Fix bug 'Contributors listed multiple times' [OSF-6690]

- framework/mongo/validators.py
- tests/test_comments.py
- website/project/model.py
- website/static/js/comment.js
- website/static/js/tests/comment.test.js
Update regex to handle the domain in the embedded link.
Note: the grouping is different in the python regexes
* Updated tests
* Updated regex
None
> Update regex to handle domain and update tests [OSF-5658]

- website/static/css/pages/statistics-page.css
- website/static/js/dateRangePicker.js
- website/static/js/pages/statistics-page.js
- website/static/js/statistics.js
- website/templates/project/statistics.mako
This PR addresses some, but not all, of the issues mentioned in [#OSF-6652].  I'm throwing this up here because the chart library was refactored muchly and will need a code re-review.  The remaining changes will be implemented in a follow-up PR, which should be much less invasive.
- Display spinners after clicking "Update date range"
- Make "Popular pages" bar graph horizontal to avoid wrapping issues
- Bump up font size of chart labels
- Renamed "Visits over past week" to "Unique visits"
- date range form: initial version is text, click update button to reveal form
- more spacing between "from" and "until" in date range updater
- We exclude analytics for today, should reflect that in the picker: can select today, but end date is exclusive.
- not-UI related but good: refactor …
> [CR] Keen UI updates [#OSF-6652]

- api/base/filters.py
- api/nodes/serializers.py
- api_tests/base/test_filters.py
Fix an APIv2 issue with 500 errors: could not filter on fields whose field name was different than the DB source field. (eg `filter[id]=<item_id>`. Affected multiple endpoints using ListFilterMixin; see JIRA ticket for list.
Changed `parse_query_params` to avoid losing information about the modified field name.
None expected. Filtering should work the same as before on all ODMFilter endpoints, but now should also work for ListFilterMixin endpoints.
https://openscience.atlassian.net/browse/OSF-6702
> Fix list filter issue when field name did not match source field name [#OSF-6702]

- website/notifications/emails.py
- website/notifications/listeners.py
- website/notifications/utils.py
Subscribe users to global notifications upon confirmation.
* check the proper users subscriptions
* add listener for `user_confirmed`
Users are subscribed to user subscriptions on confirmation.
> subscribe users to global notifications when confirmed [OSF-5658]

- scripts/refresh_addon_tokens.py
Negative sleep time will currently crash the script, preventing any further token updates. Too many requests can make third-party APIs impose a rate limit. Prevent either of these.
* Catch the correct error for `time.sleep( x < 0 )` for python 2.7
None
[OSF-5853](https://openscience.atlassian.net/browse/OSF-5853)
> [Hotfix] Catch correct error when refreshing tokens [OSF-5853]

- scripts/meta/gatherer.py
- tasks/__init__.py
Allow `invoke git_logs` to accept branch parameter and use that rather than requesting from git
1. Add branch parameter to invoke task
2. Have gatherer use the branch passed in if it exists, otherwise use existing implementation.
None
> Allow git_logs to accept branch parameter

- scripts/add_global_subscriptions.py
Subscribe all current users to default notifications.
* Added migration for global subscriptions
All users will have global notifications set to instantly unless they already have global notifications.
> add migration for global notification subscriptions [OSF-5658]

- webpack.common.config.js
- website/addons/wiki/templates/edit.mako
- website/static/js/dateRangePicker.js
- website/static/js/keen.js
- website/static/js/pages/statistics-page.js
- website/static/js/statistics.js
- website/templates/base.mako
- website/templates/project/contributors.mako
- website/templates/project/files.mako
- website/templates/project/forks.mako
- website/templates/project/project.mako
- website/templates/project/registrations.mako
- website/templates/project/settings.mako
- website/templates/project/statistics.mako
- website/templates/project/view_file.mako
Finish up UI updates for user-facing analytics.
* disallow startDate == endDate to avoid ugly error message
* show cos-spinner instead of keen-dataviz spinner
* reimplement popular pages to avoid entry duplication after project rename
* pages that can be logged into public pageviews must now set a contextVar to indicate it.
* nit: throw errors, not strings
None expected.
[#OSF-6652]
https://openscience.atlassian.net/browse/OSF-6652
> [CR] Final UI updates for user-facing analytics [#OSF-6652]

- website/static/css/style.css
- website/static/js/registrationUtils.js
Enable users to scroll to top of ERPC terms model when modal is long enough that there is overflow
Since the default CSS for modals is found in a 3rd party library, added jquery code that overrode default CSS and made the overflow for the modal scrollable. Also made overflow of the background (body) hidden so there is only one scroll bar
Before:
After: (Notice scrollbar)
None
https://openscience.atlassian.net/browse/OSF-6635
> Fix bug 'user cannot scroll to top ERPC terms modal' [OSF-6635]

- website/static/js/keen.js
Fix dashboard not loading because of bad code in keen.js.
Bad usage of lodash.get was causing JS errors on certain pages.
None expected.
No ticket. Issue reported directly by QA.
> [hotfix] fix keen js error that causes dashboard to not load

- website/static/js/project.js
Fixes the console error: _Uncaught TypeError: Cannot read property 'nodeType' of null_
when looking at a profile page
Added type checking conditions, so as to ensure variables 'e' and 'commentsLinkElm' are not undefined and/or null.
None.
https://openscience.atlassian.net/browse/OSF-6303
> fix Uncaught TypeError: Cannot read property 'nodeType' of null

- website/static/js/components/logFeed.js
- Fixes the log pagination so that the second to last log page is shown.
- Preserves all other log pagination functionality (shown in screenshots).
- [OSF-6682](https://openscience.atlassian.net/browse/OSF-6682)
- Pagination with ellipsis at the end:
- Pagination with ellipsis at the beginning (with second to last page displayed):
- Pagination with double ellipsis:
> [feature] Fix Log Pagination

- website/addons/github/static/githubFangornConfig.js
Fix the delete folder pop test for github is different from other addons.
When you try to delete a folder with content on github,
Before the change:
After the change:
https://openscience.atlassian.net/browse/OSF-6420
> [#OSF-6420]Fix modal message inconsistent for folder deletion

- api/nodes/serializers.py
- api/nodes/views.py
- api_tests/nodes/views/test_node_contributors_list.py
Make default contributor sort order a) a thing; and b) match what we use on the front-end.
1. Test
2. Add an index to allow us to know the order from the list structure
3. Sort by that list by default
Shouldn't be, although the index is currently read-only, so we'll need to do more work. Added to at-mentions because it's related to a problem they're having, but they may fix it another way so we could save this for an IR.
https://openscience.atlassian.net/browse/OSF-5948
https://openscience.atlassian.net/browse/OSF-6734
> Feature/at mentions contributor sorting [OSF-5948] [OSF-6734]

- website/static/js/comment.js
Remove sort param since contributor endpoint was updated.
* remove sort param
Contributors are originally displayed in the order they are cited. This results in the current user being first in the list.
> Remove sort param [OSF-5658]

- api/base/permissions.py
- api/base/utils.py
- api/base/views.py
- api_tests/base/test_root.py
- api_tests/tokens/views/test_token_list.py
We want to use the admin scope things, and we need to verify that it's as secure as we want it to be.
Resolves (some) blockers for [OSF-6727](https://openscience.atlassian.net/browse/OSF-6727) and [OSF-6724](https://openscience.atlassian.net/browse/OSF-6724) / #5942 
**TODO** (Someone with RS access after this goes in):
Until the admin scope is available outside of `DEV_MODE`, `RequestHasAdminScope` will only be useful for cookied requests.
[OSF-6725](https://openscience.atlassian.net/browse/OSF-6725)
> [Feature] Verify Admin Scope [OSF-6725]

- website/static/js/fangorn.js
- website/static/js/iconmap.js
- website/static/js/koHelpers.js
- website/static/js/nodeControl.js
- website/static/js/osfHelpers.js
- website/static/js/wikiMenu.js
- Fixes icon display for categorized projects in the files widget. 
- Combines project and component icons in ```iconmap.js```, as both projects and components can have categories. 
- I checked the pages/files that use ```iconmap.js``` but in addition to the files widget, the icons in the component list and wiki pages should be double checked.
- [OSF-6679](https://openscience.atlassian.net/browse/OSF-6679)
- Broken:
- Fixed:
> [feature] [OSF-6679] Project/Component Icons 

- website/static/js/contribAdder.js
- website/static/js/paginator.js
- website/templates/project/modal_add_contributor.mako
Fix bug where when importing contributors in a component from a parent node, the results do not paginate like a normal search, and there is some weird behavior where the results of an import from parent will appear on whatever page of the pagination from a normal search, and if you move to another page and then back to the page the import from parent appeared on, it is gone.
Since, unlike the normal search results, the import from parent does not have API support for pagination (normal search request to API includes the page number that is wanted), had to add frontend code that splits the results of an import from parent into the page requested, and added paginator for the import from parent results.
Also moved the import from parent button from above the results header to below the …
> Importing contributors from parent does not paginate [OSF-4762]

- package.json
- website/addons/wiki/static/ace-markdown-snippets.js
**Purpose**
Markdown-it-video has upgraded to a new version that has Vine support and bug fixes. The version used by the OSF did not have these changes, so an upgrade was necessary. After the upgrade was implemented, testing was done to ensure everything still works. Autocomplete for Vine and Prezi has also been added. 
**Changes**
Vine and Prezi can be embedded into the Wiki editor by using the same Markdown syntax used for Youtube and Vimeo. This was possible after updating the version number in package.json.
@[youtube](url)
@[vimeo](url)
@[vine](url)
@[prezi](url)
Adding snippets to ace-markdown-snippets.js for Vine and Prezi allowed for both websites to be autocompleted as well as Youtube and Vimeo. 
**Side effects**
N/A
**Ticket**
https://openscience.atlassian.net/browse/OSF-6130
> Upgrade markdown-it-video [OSF-6130]

- website/static/js/pages/files-page.js
- website/static/js/pages/project-dashboard-page.js
Addl Dev on [[OSF-3520] Registrations draggable](https://github.com/CenterForOpenScience/osf.io/pull/5975). Make registration files not able to drag and drop.
From the original PR, I simplified my code my removing the functions, and corrected the variable I was using to check if the node was a registration. `node.isRegistered` --> `node.isRegistration`
None that I can think of.
[OSF-3520](https://openscience.atlassian.net/browse/OSF-3520)
> [OSF-3520] Simplified code, changed variable

- website/static/js/addProjectPlugin.js
- website/templates/project/settings.mako
Purpose
======
Add more descriptive language when changing Category in components to clarify what Category means to the user.
Changes
======
Added "(for descriptive purposes)" when adding new component and under component settings.
**Before**
**After**
Side effects
=========
None
Ticket
=====
https://openscience.atlassian.net/browse/OSF-6627
> Update Language about Categories of Components/Projects [OSF-6627]

- website/templates/project/addon/widget.mako
Unconfigured add-ons show up in widgets to viewers that cannot edit add-ons. This provides redundant information to typical users.
Using an unconfigured add-on:
- Render widget only if add-on is configured or if the viewer has the ability to edit it.
None.
https://openscience.atlassian.net/browse/OSF-4161
> unconfigured add-ons display widget to non-contributors [OSF-4161]

- website/static/js/fangorn.js
Fixes bug where any error message shown when creating a folder persists through multiple create folder attempts and certain error messages sometimes take a while to display or may even never display at all
Fixes code to clear helpText whenever the dismiss toolbar button is hit and also whenever a create folder attempt is made
Also makes sure error messages appear using m.redraw() after helpText is filled with the error
None
https://openscience.atlassian.net/browse/OSF-5707
> Fix bug "new folder error persists through multiple 'create folder' attempts" [#OSF-5707]

- website/static/js/passwordForms.js
- website/templates/profile/account.mako
Two bugfixes and some stumbled on improvements to the new password strength checks:
- Disable submission for low strength password on password change form in settings - needs to be handled separately because the form's submit is not data-bound in knockout
- Frontend on signup with existing account showed incorrect error message
- Backend would error on password reset to same as old password - added that to frontend validation so that feedback happens quicker
- Add frontend validation for old password matching new password
- Move oldPassword to be used in password validation extender
- Remove catching of all 400s and changing the message - email as password checks are taking place separately and don't need a special override in submit any longer.
- Disable password reset in settings …
> hotfix/Password strength bugfixes [#OSF-6759]

- api/base/permissions.py
- api/users/serializers.py
- api/users/views.py
- api_tests/tokens/views/test_token_list.py
- api_tests/users/views/test_user_list.py
- framework/auth/core.py
- framework/auth/oauth_scopes.py
- tests/models/test_user.py
Allow (with limited availability) the creation of users through APIv2. This is required for several services currently in development.
* Create custom scope for `USERS_CREATE`, included in the admin scope
* Add tracking mechanism to User model to see who added each user (spam mitigation)
* Create UserCreateSerializer, conditionally used on `POST` requests to `/v2/users/`
* Create permissions class to allow *only* tokened requests for unsafe methods.
Uniqueness of users ensured by ignoring username case. This was previously a bug in one possible user-creation flow
`osf.users.create` scope will need to be exposed in `public_scopes` (with `public=False`) before this will work in production.
[OSF-6753](https://openscience.atlassian.net/browse/OSF-6753)
> [Feature] Create Unregistered Users via APIv2 [OSF-6753]

- api/base/serializers.py
- api/nodes/views.py
- api_tests/nodes/views/test_node_contributors_list.py
Replaces #6045 
- Contributor bulk updates in API v2 would not work with the new contributor identifier format (```node-id```-```user-id```). This PR updates the ```NodeContributorsList``` view in the API so that bulk updates with the new identifiers will succeed. Additionally, this PR updates the tests for bulk updates to use the new contributor identifier format in their request bodies. 
- Update tests to make bulk requests with new contributor identifiers.
- Override ```get_requested_resources()``` in ```BulkDestroyJSONAPIView```
- Update ```get_queryset()``` in ```NodeContributorsList``` to still look for User ID's. 
- None expected, as it doesn't appear that we are currently making bulk contributor updates via API v2 on the OSF.
- …
> [feature] [OSF-6745] Contributor Bulk Updates

- website/templates/project/statistics.mako
On small screens, the "no analytics" image wasn't scaling, and the pie chart was scaling too small, too fast.
* Add `.img-responsive` to the no analytics image.
* Remove inappropriate margins from chart rows, so that pie chart is sane down to 320x480.
Nope.
> [hotfix] responsiveness fixes for Keen

- scripts/migrate_piwik/transform_01.py
Don't overwrite already-transformed data if transform-01 is resumed.
> [hotfix] don't overwrite transformed piwik data

- website/static/js/components/socialshare.js
- website/static/js/filepage/index.js
(1) If a user has ad block turned on and tries to share a project via linked in, the user is not able to share the project and get no information as to why. I think we should improve this with a tooltip that informs the user that having ad blocked enabled may prevent successful sharing of their project.
(2) The link on the file detail page used in the share/embed popover is to the rendered file, which is fine, however with the social media sharing links the link should be to the file.
Added tooltip, changed share button file link.
NO
https://openscience.atlassian.net/browse/OSF-2052
> [OSF-2052] LinkedIn share button should warn about adblockers. Share button file url should be the OSF file page url.

- website/static/js/fangorn.js
- website/static/js/filepage/index.js
- website/templates/project/view_file.mako
Fixes for develop and the versioning. Since we are the only ones that keep track of versions and it seems that I can't get the hases of the versions for anything but the osfstorage without rewriting the underlying architecture, I decided to only show versions for the column that is from the osfstorage and leave the rest blank. This should also fix the display problem on the file revision page.
Special cased osfstorage to show versions
There should not be any.
https://openscience.atlassian.net/browse/OSF-6026
> [OSF-6026] feature/versions fixes for specific versioning

- website/static/js/components/socialshare.js
Due to browser differences, clicking on the "Share" button on a project page in Safari did nothing.
Use of onfocus and other events was changed to accommodate different browser behaviors.
N/A
https://openscience.atlassian.net/browse/OSF-2052
> [OSF-2052] Social share button should show up on Safari

- website/static/js/fangorn.js
Fix bug where new folder error persists if user clicks on OSF Storage immediately. Also fixed weird behavior where clicking inside the tb-tbody element but not on an actual file would deselect the currently selected file without dismissing the toolbar.
made sure that whenever a new folder is selected the error text clears. 
None
https://openscience.atlassian.net/browse/OSF-6778
> New Folder Error Message Persists [#OSF-6778]

- api/base/pagination.py
- api/institutions/views.py
- api/nodes/views.py
- api_tests/base/test_pagination.py
- api_tests/institutions/views/test_institution_list.py
- api_tests/nodes/views/test_node_addons.py
- website/static/js/folderPickerNodeConfig.js
- website/static/js/osfHelpers.js
List more than 10 folders for addons when using APIv2
* Page size set to 1k
* Opportunistic Fix: `InstitutionsList` page size set to 1k:
>I do see us going over 100 institutions but we will likely remain under 1k
\- @icereval 
This isn't pagination. Because [where this is being called in TreeBeard](https://github.com/CenterForOpenScience/treebeard/blob/develop/dist/treebeard.js#L1064) doesn't resolve promises, this flow is difficult to hook into.
Consider adding a JSONAPI-compliant pagination feature to TreeBeard.
[OSF-6830](https://openscience.atlassian.net/browse/OSF-6830)
> [Hotfix] List more than 10 Folders through API [OSF-6830]

- website/addons/zotero/model.py
Display all citations, not just the first 25 of every 100.
* Update query param: `size` -> `limit`
* See [Zotero docs](https://www.zotero.org/support/dev/web_api/v3/basics#sorting_and_pagination_parameters)
None
[OSF-6852](https://openscience.atlassian.net/browse/OSF-6852)
> [Hotfix] Update Zotero's Page Size Quaram [OSF-6852]

- website/project/views/node.py
Read access contributors to a private project should see the "Make public to get analytics" message when they visit the Analytics page.  Instead, we were showing a 403 Forbidden.
Remove some old (circa-2014) permissions code that was forbidding read-onlys.
None expected.
[#OSF-5885]
https://openscience.atlassian.net/browse/OSF-5885
> [hotfix][CR] read-access contributors should see analytics page [#OSF-5885]

- website/templates/profile/personal_tokens_detail.mako
Ensure that tooltips display correctly on "personal access tokens: create" page: http://localhost:5000/settings/tokens/create/
This fixes an issue where the quotation marks added around strings by `sjson` interfered with the quotation marks used to denote an attribute in HTML.
Replace the `sjson | n` filter (which trusted the string as given) with the `entity` filter. All possible strings for this field are plain text with no entities, apostrophes, or quotation marks.
None expected, but if a scope description ever adds an apostrophe, it will render oddly for reasons outlined below. No current descriptions are affected by this. Long term we plan to use a different system of tooltips in future frontend code.
Origin: This field is strange because it *looks* like a javascript context, but …
> [hotfix] Access token info icon fails to display because of extra quotation mark [#OSF-6321]

- website/project/model.py
Excluded deleted and private node from update search when try to save nodes for node_license update. Can be a solution to the problem of https://openscience.atlassian.net/browse/OSF-5389. Even if it does not solve this ticket, deleted nodes and private nodes shouldn't be included in updates for node_license search update. And we can still use https://github.com/CenterForOpenScience/osf.io/pull/6054 to add license to rpp as a ultimate solution.
… nodes for node_license update[#OSF-5389]
https://openscience.atlassian.net/browse/OSF-5389.
> License cannot be applied to the RPP project[#OSF-5389]

- website/project/views/register.py
- website/settings/defaults.py
[OSF-6526](https://openscience.atlassian.net/browse/OSF-6526)
Add facility for removing questions from anonymized VOL to registrations
Update  website/project/views/register.py add logic for removing questions from anon VOLs
Update website/settings/defaults.py add setting ANONYMIZED_TITLES list of titles to remove
Relies on list of titles being accurate and up to date.
[#OSF-6526]
> Anon-view only links show names in prereg registration schemas [OSF-6526]

- api/comments/serializers.py
- api/comments/views.py
- api/nodes/views.py
- api/registrations/views.py
- api_tests/comments/views/test_comment_detail.py
- api_tests/utils.py
[OSF-6551](https://openscience.atlassian.net/browse/OSF-6551)
Fix "node" and "replies" links for registration comments. Covers comments for nodes, wikis, and files.
Update api/comments/serializers.py make registration and node super classes of *CommentSerializer
Update api/comments/views.py add logic to differentiate between Node and Registration
Update api/nodes/views.py switch to NodeCommentSerializer
Update api/registrations/views.py switch to RegistrationCommentSerializer
Update api_tests/comments/views/test_comment_detail.py fix several tests and add three tests
Update api_tests/utils.py add "def urlparse_drop_netloc" for converting links to URIs for app.get
None
https://openscience.atlassian.net/browse/OSF-6551
> Fix registration comment related links [OSF-6551]

- website/static/js/registrationModal.js
- website/static/js/tests/registrationModal.test.js
#6025 &rarr;
[OSF-6477](https://openscience.atlassian.net/browse/OSF-6447) describes a bug that we're seeing intermittently during testing at Travis. This PR fixes it.
Root cause [identified](https://github.com/CenterForOpenScience/osf.io/pull/5977#issuecomment-232963579) and [analyzed](https://github.com/CenterForOpenScience/osf.io/pull/5977#issuecomment-236922483). Surrounding area [excavated](https://github.com/CenterForOpenScience/osf.io/pull/5977#issuecomment-233401612), and partially refactored (#6025, #6050). Fix [discovered](https://github.com/CenterForOpenScience/osf.io/pull/5977#issuecomment-235797811), and implemented on this PR. Ready for review! :)
See the [commit log](https://github.com/CenterForOpenScience/osf.io/pull/5977/commits).
Note for QA: verify that the embargo date …
> Fix heisenbug in test for 4 year limit on embargo dates

- api/base/generic_bulk_views.py
- api/nodes/views.py
- api_tests/nodes/views/test_node_list.py
The Google Cloud / Kubernetes load balancer does not allow DELETE requests with JSON bodies, and the initial spec for JSON API Bulk DELETEs has just this combination. So we have a new implementation of Bulk DELETEs that will use query parameters to perform the delete rather than JSON body. The JSON body is still acceptable for now, because it's used in places, but that will probably be phased out before we move all the servers over to the new load balancer.
A request would look like:
DELETE `https://api.osf.io/v2/nodes/?type=nodes&id=abcde,fgh4j,k8mn2`
You cannot use both the JSON body and the query parameters. if the id field is in the query parameters and there is a JSON body, the request will fail with a good error. If only the type field is in the query parameters, it will ignore the …
> Allow bulk DELETE with query parameters [OSF-6732]

- admin/meetings/forms.py
- admin/meetings/serializers.py
- admin/meetings/views.py
- tests/test_conferences.py
- website/conferences/model.py
- website/conferences/views.py
- website/static/js/pages/meetings-page.js
Adds functionality where it is possible to specify in the admin app when creating a meeting that the meeting should not show up on the meetings page. 
Also removes 2 already existing non-meetings meetings from the view on the meetings page
Added input in the create meeting form in the admin app that you deselect if the meeting is actually not a meeting
When editing and older meeting that does not have the attribute is_meeting because if has been added in this change) the check-box for 'Is A Meeting' defaults to unchecked and if not checked before submitting, the meeting will not display on the meetings page. 
https://openscience.atlassian.net/browse/OSF-5645
> Make flag for non-meetings Meetings in Admin app [#OSF-5645]

- website/static/js/project-organizer.js
Currently every project icon is a cube on the My Projects page, this properly makes them based on catagory
Before:
After:
Simple two line fix, uses iconmap.js to ensure proper icon is used.
https://openscience.atlassian.net/browse/OSF-6047
> My Projects page displays icons properly [OSF-6047]

- website/static/js/filepage/index.js
Removed Download/Delete/Check Out buttons from the viewing of an old version of a file.
Those buttons actually referred to the current version of the file, not the revision, so it could be misleading to the user
Made sure to check if in an old version view before rendering those specific buttons.
None
https://openscience.atlassian.net/browse/OSF-4544
> Remove Download/Delete/Check Out buttons from old version view [#OSF-4544]

- framework/auth/decorators.py
- tests/test_views.py
- website/profile/views.py
- Before, when an account was made but not yet confirmed, their page was still able to be accessed.  
- Makes it so when an unconfirmed user's profile page is attempted to be accessed, it displays the text "Account not yet confirmed.  The profile page could not be displayed as the user has not confirmed the account" and throws and HTTPerror.
- Added the decorator ``must_be_confirmed`` in ``decorators.py`` that checks if the user on the page being visited has activated their account.  If so, it returns normally.  If it is not activated, it raises the error and displays the message.
- Wrapped the function ``profile_view_id`` in ``profile/views.py`` that is accessed when a page is loaded up 
Here is a picture of the changes on a page of an unconfirmed user:
- …
> [OSF-4670] Do not show a profile page for an unconfirmed user

- website/static/js/addProjectPlugin.js
Based on feedback, it seems that many OSF users do not know that admins of parent projects have read access to children projects. The purpose of this fix is to clarify that by updating the language in the Create Component modal.
Used mithril to add italicized and bold text to Create Component modal in addProjectPlugin.js file.
N/A
https://openscience.atlassian.net/browse/OSF-6826
> On Create Component modal, Add language to indicate Admins have read access [OSF-6826]

- website/static/js/accountSettings.js
The original confirmation message when adding an email to merge accounts was ambiguous so it should be edited to be more detailed. 
Changed the text in accountSettings.js.
N/A
https://openscience.atlassian.net/browse/OSF-6721
> Made text improvement in merging accounts modal [OSF-6721]

- website/static/css/front-page.css
- website/templates/landing.mako
On mobile view, the Sign Up Free button overlaps with the section underneath it when the user submits the form without filling out any of the boxes. 
Adjusted the spacing in CSS by changing the height of the entire div and moving the sign up form up by 100px. 
N/A
https://openscience.atlassian.net/browse/OSF-4072
> Mobile: Password warning cut off on front page [OSF-4072]

- website/static/js/fangorn.js
Text inputs for renaming and folder adding didn't focus properly, this fixes that and makes them consistent.
one line fix makes all input fields focus properly
https://openscience.atlassian.net/browse/OSF-4481
> File widget textboxes have incorrect highlight [OSF-4481]

- website/static/css/style.css
Currently on account setting the side navbar won't be properly responsive and will slide under the panels on that page.
Simple change to media query.
https://openscience.atlassian.net/browse/OSF-5125
> Stop side navbar on account settings scrolls behind main text of page [OSF-5125]

- website/project/views/drafts.py
- website/static/js/registrationUtils.js
Sorted draft registrations in reverse chronological order by last updated date.
Added code to sort draft registrations by last updated date in API and removed code that was sorting draft registrations by created date on frontend
None
https://openscience.atlassian.net/browse/OSF-6243
> Draft registrations should be in reverse chronological order [#OSF-6243]

- framework/auth/core.py
Allow users of the Admin app to delete users who have unsubscribed to MailChimp emails.
1. The error being caught was EmailNotExistsError, so I caught that and ignored it.
I can't think of any. If the email doesn't exist for some other reason which would still allow them to get MailChimp emails (seems unlikely), then we would have a harder time unsubscribing them.
https://openscience.atlassian.net/browse/OSF-6867
> Allow users who have opted out of mailchimp emails to be disabled

- api/preprints/serializers.py
- api/preprints/views.py
- api_tests/preprints/views/test_preprint_list.py
- scripts/create_fakes.py
- tests/factories.py
Update serializer, add tests for preprint provider, add documentation
- Create preprint documentation in preprint detail docstring on API v2
- Add ability to specify provider in preprint factory
- Add provider in create_fakes script
- Tests for filtering by provider
- Documentation in preprint list and detail view
- Documentation on creating a new preprint by POST-ing to a node that exists
- Update subjects serializer to show both ID and text
> Specify provider in test factories, Documentation Improvements

- website/discovery/views.py
Keen doesn't limit how many entries it returns. Set a maximum limit to keep explore activity page at a reasonable size.
> [hotfix] limit number of popular projects to display

- admin/meetings/serializers.py
Make it so that old meetings' is_meeting field defaults to true so that when editing an older meeting you don't accidently submit the form without setting is_meeting to true
Changed serializer to set is_meeting to true is it is none
None
https://openscience.atlassian.net/browse/OSF-5645
> Old meetings' is_meeting field default to true [#OSF-5645]

- api/preprints/serializers.py
- api/preprints/views.py
- api_tests/preprints/views/test_preprint_detail.py
- api_tests/preprints/views/test_preprint_list.py
- tests/factories.py
- tests/test_models.py
- website/project/model.py
Add DOI field to the node model as well as preprint serializer (in plain and URL form) so that 
- `preprint_doi` field on node
- doi validation on node
- `doi` field in attributes and in links
- method to format DOI URL
- pass DOI in PreprintFactory
- tst for filtering by DOI
- test for update DOI via API v2
- Old generated preprints wont have DOIs to display on API
https://openscience.atlassian.net/browse/PREP-98
> Add preprint_doi field to Node and Preprints v2 view

- api/base/permissions.py
- api/users/views.py
- api_tests/users/views/test_user_list.py
Changes permissions under which a user can create an unregistered user via the API v2.  Previously, a user could only create another user if they had a properly scoped token (users-create).  Creating them with cookie auth was not allowed.  This allows you to create users if you have a cookie.
Needed to create unregistered contributors for preprints and will eventually be needed for OSF unreg contrib functionality as well. 
Removes RequiresScopedRequestOrReadOnly from permissions classes
https://openscience.atlassian.net/browse/OSF-6879
> Feature/Create Users Via Cookie Auth [OSF-6879]

- api/addons/views.py
- api/base/settings/defaults.py
- api/nodes/serializers.py
- api/nodes/views.py
- api_tests/nodes/views/test_node_addons.py
- api_tests/users/views/test_user_addons.py
- website/addons/forward/model.py
Allow users to configure forward via APIv2
* Refactored AddonNodeSettingsSerializer
* Added `url` and `label` as serializer fields for forward
* Tests
None expected
[OSF-6653](https://openscience.atlassian.net/browse/OSF-6653)
> [Feature] Configure External Link addon via APIv2 [OSF-6653]

- api/base/filters.py
- api_tests/base/test_filters.py
- api_tests/users/views/test_user_list.py
- Allows for multi-field filtering in the API, i.e. ```/v2/users/?filter[given_name, family_name]=roll``` will filter users whose ```given_name``` **OR** ```family_name``` contains 'roll'.
- Updated ```QUERY_PATTERN``` regex in the ```FilterMixin``` class (note: I'm not 100% confident in this regex). 
- Changes to ```parse_query_params()``` in ```FilterMixin``` and the format of the query dict that is returned. 
- The multiple fields included in the filter must be the same type, i.e. ```/v2/nodes/?filter[title, public]=science``` will give an error. 
- Multi-field filters can be combined with other multi-field or single-field filters.
- ```/v2/nodes/?filter[title,description]=music&filter[public]=true``` will filter by:
- ```(title contains 'music' OR description contains 'music') AND …
```
> API Multi Field Filtering [OSF-6851]

- website/static/js/filepage/index.js
- website/static/js/filepage/revisions.js
Fix the problem that "delete", "check out", and "download" buttons are missing from certain file types. Now those buttons will show up on all files on latest version and won't show up for any old version files.
Before changes:
After change:
for latest version of file cannot be edited on OSF, the delete, checkout, download button still show up
for previous version of file cannot be edited on OSF, the delete, checkout, download button will NOT show up
I think the download button should still be there but with changes to make it to download the current version instead of the most recent version. This can be another improvement ticket.
https://openscience.atlassian.net/browse/OSF-6892
> [#OSF-6892][Hotfix] Delete, Check Out, and Download buttons missing from certain file types

- api/nodes/serializers.py
Add 'node' relationship to contributor serialization. This is important for https://github.com/CenterForOpenScience/ember-osf/pull/117 to work-- Ember Data needs the node->contributor and contributor->node relationship to effectively manage state between the two when creating/deleting contributors.
> Add 'node' to contributor serialization

- website/templates/project/settings.mako
- Fixes a UI bug found when testing [OSF-6649](https://openscience.atlassian.net/browse/OSF-6649) where the horizontal table dividers did not have a consistent width.
- Before:
- After:
- [OSF-6649](https://openscience.atlassian.net/browse/OSF-6649)
> [feature fix] Affiliate Institution Table UI [OSF-6649]

- api/preprints/serializers.py
- api/preprints/views.py
- api/taxonomies/serializers.py
- api/taxonomies/urls.py
- api/taxonomies/views.py
- api/users/views.py
- api_tests/preprints/views/test_preprint_detail.py
- api_tests/preprints/views/test_preprint_list.py
- api_tests/taxonomies/views/test_taxonomy_list.py
- framework/auth/oauth_scopes.py
- scripts/update_taxonomies.py
- tests/factories.py
- website/project/model.py
- website/project/taxonomies/__init__.py
Update Preprints from points noticed during CR
* Add/correct OAuth scopes
* Maintain typical API conventions -- list endpoints creates, detail updates
* Improve efficiency of queries (prefer generators to optimize for pagination)
* Treat fields that point to models appropriately
*  Update docs
* Fix minor bugs
Minor changes required in `ember-preprints`:
* creating a preprints is now done through the list endpoint `/preprints/`  (`node_id` in json)
* Taxonomy `parent_ids` is now `parents`, still list of id's
@chrisseto may have already updated that side of things
Maybe something on the Preprints board? ¯\\\_(ツ)_/¯
> [Feature] Update Preprints models / API endpoints [PREP-????]

- api/preprints/serializers.py
- api/taxonomies/serializers.py
- api_tests/taxonomies/views/test_taxonomy_list.py
Fix bug introduced in #6178 
* Use (renamed) `TaxonomyField` to serialize `Subject`s in `.parents`
* Fix test to not be a noop
None expected
Logging removed:
```
~/D/osf.io ❯ DJANGO_SETTINGS_MODULE=api.base.settings nosetests api_tests/taxonomies/ api_tests/preprints/
.............................
----------------------------------------------------------------------
Ran 29 tests in 13.886s
OK
```
> [Fix] Taxonomy parent filtering

- api/base/filters.py
- api_tests/base/test_filters.py
- Using an invalid operator to filter a `RelationshipField` resulted in a 500 error because `get_valid_operators()` was returning `None`. 
- This PR changes `get_valid_operators()` to return `DEFAULT_OPERATORS` instead.
- [OSF-6483](https://openscience.atlassian.net/browse/OSF-6483)
> Fix Filter Operator Error [OSF-6483]

- api/taxonomies/serializers.py
- api_tests/taxonomies/views/test_taxonomy_list.py
Fix serialization for `TaxonomyField`
`[<subj.id>, ...]` -> `[{'id': <subj.id>, 'text': <subj.text>}, ...]` 
None expected
Preprint attributes:
```
"doi": "10.123/0",
"date_modified": "2016-08-21T13:35:07.960000",
"abstract": "Ambiparous cosmic habitat instance  monolith zone demonstrating salinity. Formations sedentary aspects of doldrums aquifer meridian formations. Range whitewater vista transfer rain forest aquifer ornithology precipitation.",
"title": "Dominant shard equation meiosis proton components incandescent metamorphosis.",
"subjects": [
{
"text": "Example Subject #0",
"id": "57b9ae09c2babb68c151ff7e"
}
],
"provider": "osf",
"date_created": "2016-08-21T13:35:05.779000",
"tags": [
"invisible",
"bacteria",
"realm",
"crepuscular",
"whitewater"
]
},
```
from …
> Fix serialization for TaxonomyField

- api/base/filters.py
- api/nodes/serializers.py
- api/nodes/views.py
- api_tests/base/test_serializers.py
- api_tests/nodes/views/test_node_list.py
Since preprints are normal nodes, `v2/nodes` shows all preprints as well, without the ability to filter. This poses a problem when selecting a node you'd like to convert to a preprint, as trying to convert an already existing preprint.
Now you can filter on `preprint` with `?filter[preprint]=true` or `?filter[preprint]=false`
- Add special case check in `filters.py` and convert to appropriate ODM query
- Preprint field on node serializer, added to filterable fields
- Node view documentation updates
None except the new ability to filter out preprints when needed from `v2/nodes/` with a filter. Any place we'd like to distinguish preprints from nodes is possible. 
None
> Add ability to filter to NodeList with `?filter[preprint]=true|false`

- api/base/serializers.py
- api_tests/users/views/test_user_list.py
Limit the "projects_in_common" meta only show when "show_projects_in_common=true" in query.
before change:
After change:
https://openscience.atlassian.net/browse/OSF-6893
> [#OSF-6893]Show "in common" users on contributor search if query parameter is passed

- website/static/js/home-page/preprintsPlugin.js
- website/static/js/pages/home-page.js
- website/templates/nav.mako
Add a link to Preprints in the Browse navbar, and as a bar on the homepage
- Add link to preprints in Browse menu in navbar
- Add bar at the bottom of the page with links to preprints, below meetings
> Add preprints links on the OSF

- api/preprints/serializers.py
Don't include the DOI link if there is no doi
Before: 
After: 
Return `None` if there's not a DOI to format
@chrisseto might have to update the SHARE harvester with a `Maybe` field for DOI harvesting preprints
> Properly exclude DOI url if DOI is none

- website/files/models/osfstorage.py
- website/project/views/node.py
- website/static/css/pages/file-view-page.css
- website/static/css/pages/project-page.css
- website/static/js/fangorn.js
- website/static/js/filepage/index.js
- website/templates/project/project.mako
- website/templates/project/project_base.mako
- website/templates/project/view_file.mako
Add various messages on the OSF for when users access the OSF Projects associated with Preprints.
Building on @caneruguz's work!
"Learn more" links will go to http://help.osf.io/m/preprints
Only shown to **admins** on the project
- On file delete from osfstorage, set `_is_preprint_orphan` if the file was the preprint's primary file
- Add banners about the preprint on the main project page, and the primary file page
- Add banner about preprint orphan to *project administrators*
- Make preprint properties and primary file information visible to templates and mithril
- Extra warning message when deleting a file that's a primary file
Extra node save on file delete if primary file is being deleted?
> Preprint messages on the OSF

- website/static/js/anonymousLogActionsList.json
- website/static/js/logActionsList.json
Preprint logs are registered as a valid `NodeLog.action`, adds language to them.
* Update public and anonymized log language
None
> [Feature] Preprints logs

- website/project/model.py
- website/static/js/fangorn.js
- website/static/js/filepage/index.js
- website/static/js/nodesPrivacy.js
Since a preprint is just a project on the OSF, users can make them private and perhaps not realize the concequences.
This adds at least a warning message to give a bit of a heads up
- Change to the model to make sure `is_preprint` also looks at Privacy of a node (`is_public=False > is_preprint=False)
- Add check in `nodesPrivacy.js` for when making private to add special preprints message.
- Small wording change from "your preprint" to "this preprint"
- Anywhere that uses the node's `is_preprint` property  will now accurately exclude former preprints that are now private (to match what the API does...)
> Message when making Preprint Private

- website/addons/github/model.py
WB will soon start returning the applicable branch name in all Github action metadata.  The current `create_waterbutler_log` implementation for GH cannot handle this, as it expects a commit sha if any extra metadata is returned at all.
Test directly for `extra.commit.sha` instead of just `extra`.
None expected.  This should have no visible effects.  It's purpose is to not break new functionality.
[OSF-6947]
https://openscience.atlassian.net/browse/OSF-6947
> [hotfix] make github wb logger less brittle [OSF-6947]

- tests/factories.py
Ever since adding the unique subject text requirement, new instances of `create_fakes` for preprints would fail with duplicate key errors. This PR searches for an existing key first for the SubjectFactory before making new ones
Now use `python -m scripts.create_fakes -u email@yay.io --nprojects 30 --preprint True --preprintprovider osf,engrxiv` with abandon! Woo!
- Query for existing subjects first and use those in subject factories
> make Subject factory try to use existing Subjects to avoid unique error

- framework/auth/views.py
- website/profile/views.py
- website/routes.py
- website/static/js/accountSettings.js
- website/static/js/pages/profile-account-settings-page.js
- website/templates/profile/account.mako
Allow users to revoke prior external authorizations
* `account` template updated
* v1 route/view added
* update `social` field on link
Additional V1 route to be destroyed. This isn't close to the final iteration of the "external service login" feature, so this is probably better than a v2 route that would need deprecating.
> [Feature] Add support for revoking ORCID login

- api_tests/nodes/views/test_node_contributors_list.py
- website/project/model.py
- When adding an unregistered contributor via the API, the visibility specified in the request was being ignored as it was not being passed to `add_unregistered_contributor`. It works now and tests have been updated.
- Add `visible` as a key word argument to `add_unregistered_contributor`. 
- Add and update tests.
- [OSF-6855](https://openscience.atlassian.net/browse/OSF-6855)
> [feature fix] Set Bibliographic for Unregistered Contributors via API [OSF-6855]

- website/templates/project/project.mako
- website/templates/project/view_file.mako
Links directly to preprints on ember preprints have changed from `/content/<guid>/` to just `/<guid>/` . This PR updates links on OSF Preprint projects to go to the right place.
- Update link on preprint project page
- Update link on preprint primary file view page
None
> Fix links to view preprint on project and file page

- api/preprints/parsers.py
Trying to create a new preprint via the API was breaking for me, with the following error:
````
parsed = parser.parse(stream, media_type, self.parser_context)
File "/Users/fitz/code/osf/osf.io/api/base/parsers.py", line 112, in parse
return self.flatten_data(data, parser_context, is_list=False)
File "/Users/fitz/code/osf/osf.io/api/base/parsers.py", line 84, in flatten_data
relationships = self.flatten_relationships(relationships)
File "/Users/fitz/code/osf/osf.io/api/preprints/parsers.py", line 16, in flatten_relationships
ret = super(PreprintsJSONAPIParser, self).flatten_relationships(relationships)
TypeError: super(type, obj): obj must be an instance or subtype of type
````
Pass the correct class to the `super()` call.
None expected.
No ticket.
> fix broken API preprint parser

- framework/auth/campaigns.py
- framework/auth/views.py
- website/mails/mails.py
- website/templates/emails/confirm_preprints_osf.txt.mako
- website/templates/public/login.mako
- website/util/metrics.py
Add a new campaign, so that users of the preprints service (through the OSF) will see a custom signup page and receive unique signup emails.
Sample URL: `http://staging.osf.io/login?campaign=osf-preprints`
If they click "use an existing account", then when they are done with the login process, they will be taken to `staging.osf.io/preprints` (the preprints landing page)
Upon confirming an account, they should be taken to the landing page for the campaign (eg `staging.osf.io/preprints`)
Add new `osf-preprints` campaign: custom signup page, and track users who came in this way via metrics.
None expected.
https://openscience.atlassian.net/browse/PREP-131
> [rfr][preprints] Add custom signup/ campaign page for OSF Preprints service

- website/static/js/filepage/index.js
Files in OSF Storage have a "Create preprint" button on them. Clicking on it just leads to a blank Add Preprint form asking you to upload a file. Since creating preprints from pre-existing project files is not part of the current functionality, the "Create preprint" button should be removed from files.
- remove create preprint button from files
none
https://trello.com/c/YVCh0mcO/17-create-preprint-button-on-osf-files-leads-to-blank-add-preprint-form
> Remove the create preprint button from files

- website/static/js/nodesPrivacy.js
"Circulation" is misspelled in the warning modal when a user attempts to make a project with a preprint file private.
Now it's better!
spell it right!
https://trello.com/c/3gjuXT55/18-make-project-private-modal-has-spelling-error
> Fix typo on modal

- website/static/js/fangorn.js
replaces https://github.com/CenterForOpenScience/osf.io/pull/6222
Preprints are normal nodes, so users can currently do anything to those nodes and files that one can do with normal nodes and files.
This is a fangorn update that warns a user when they try to move a file out of a preprint project, but then ultimately allows them to do it anyway if they really want to. If they move it, the preprint will become orphaned.
- Moving a preprint file out of a component should trigger a preprint warning
- Moving a preprint file into a folder should be OK
- Moving a preprint file into a component with a file that has the same name should trigger a move preprint warning modal, and then a same filename choice modal afterwards.
- Moving a file into the component should trigger a replace warning that …
> Warn users when moving or replacing a preprint file

- api/preprints/views.py
Docstring for the preprint detail view still contained old info about POSTing to create a new preprint, when that functionality has been moved to the Preprint List View. 
- preprint detail docstring 
nope
> Small update to preprint detail view about updating instead of creating

- website/static/js/projectSettings.js
Other node actions dealing with preprints have warnings when doing something destrictive to the preprint -- add a notice for deleting a project that represents a preprint as well
- add conditional message to delete confirmation dialog
-nope!
https://trello.com/c/w373G0FY/20-delete-project-modal-should-be-updated-for-preprints
> Update to getConfirmationCode to put in warning about deleting preprint

- website/templates/public/login.mako
Fix spacing to top and right of create account button on OSF login page create account form
Before:
After:
Columns should add to twelve, not 16. Add spacing around items.
Affects:
- Login page signup form for campaigns (eg preprints): `http://staging2.osf.io/login/?campaign=osf-preprints`
- Login page signup form for institutions, `http://staging2.osf.io/login/?campaign=institution`
None expected. Cosmetic/ display only.
Trello card: https://trello.com/c/gAqDGxBk/81-cosmetic-bug-for-campaign-signup-page
> [preprints] Fix appearance of campaign login page create account form

- api/files/serializers.py
- api/nodes/views.py
We wanted to display download counts from the current file using the waterbutler info we currently have for the time being!
So now the download count is under `extras > downloads` like it is in waterbutler:
- Add download count for the current File
I think this is in total, and not for the current version? Is that confusing to anything?
> Get download count from file object for file serializer

- website/project/model.py
Reordering contributors via the APIv2 was not updating the visible_contributor_ids which are used to populate the contributors on the project view page.  So reordering contributors on a preprint would have no effect on the order of contributors displayed on the project view page.
Saves the order of visible contributor ids.
Just passed save=save into update_visible_ids.  Cannot think of any issues.
https://trello.com/c/Du2ygimQ/108-order-of-authors-on-view-page-not-consistent-with-what-was-saved-and-what-appears-on-project
> Feature/Reordering Contributors via APIv2 was not updating visible_contributor_ids

- api/preprint_providers/views.py
- api/preprints/views.py
- api/taxonomies/serializers.py
- api/taxonomies/views.py
- scripts/update_taxonomies.py
- website/project/taxonomies/__init__.py
Updates #6237 
From parent PR:
>- add child count to the taxonomies serializer (added here in attributes instead of in extra for simplicity when reading from ember for speed sake)
- add child_count property to Subjects
- add children as foreign field to Subjects cause why not be proper
- use update_taxonomies script to also set the children
- update preprints realted views with caveat message
* minor update to model / script
>Must run update_taxonomies again to make sure all children are saved, orelse all children counts will be 0
An ember-osf PR will rely on this to get accurate carrts or not
> [Hotfix] Save children

- api/files/serializers.py
- api/preprints/serializers.py
- api_tests/nodes/views/test_node_files_list.py
- api_tests/preprints/views/test_preprint_detail.py
- api_tests/preprints/views/test_preprint_list.py
Fix bugs
* Tags for `preprints` are built the way they are with `nodes`
* Check `obj.kind` for `file` before calling `File`-specific method
Increased test coverage
https://trello.com/c/LZ6F68HO/121-keep-receiving-a-a-cannot-upload-folders-error-when-adding-files-to-the-preprint-project
> [Hotfix] Tags and Folders Bugs

- api/preprints/serializers.py
- api_tests/preprints/views/test_preprint_list.py
When a read-write user tries to POST to create a preprint that already exists, the API returned a 409 error before the 403 forbidden. While 409 is techncally correct, 403 is way more appropraite for the user because they'll never be able to make a node a preprint. 
- check permissions of auth user before 409 conflict
no?
https://trello.com/c/vc41eU5E/124-api-read-write-and-read-only-users-get-a-409-error-instead-of-a-403
> Non admins get 403 Forbidden instead of 409 Conflict when Wrongly POSTing to existing preprint

- api/base/parsers.py
- api_tests/nodes/views/test_node_comments_list.py
- api_tests/nodes/views/test_node_contributors_list.py
- api_tests/nodes/views/test_node_links_list.py
- Currently, there is no validation for the relationships resource key that is required in the request body when creating a relationship. This PR adds validation by requiring that the resource key matches the target type, which is followed by validation that the target type is correct.
- Added validation in `JSONAPIParser.flatten_relationships()` 
To verify this, just add a contributor via the v2 API (we should have tests already for that) and try adding a contributor with a user type of something incorrect to see it fail.
- [OSF-5268](https://openscience.atlassian.net/browse/OSF-5268)
> [feature] Validate Relationships Resource Key [OSF-5268]

- api/base/serializers.py
- api_tests/nodes/views/test_view_only_query_parameter.py
- Currently when a route is viewed on the API with a view only token, the view only token is not passed to the generated links of each relationship field. This PR adds the view only token to each relationship link, making the API browsable with a view only token. 
- `view_only` query parameter is retrieved and added to the relationship urls returned from `get_url()` in the `RelationshipField` class.
- [OSF-6733](https://openscience.atlassian.net/browse/OSF-6733)
> Append VOL to Relationship Links [OSF-6733]

- framework/auth/core.py
- framework/auth/forms.py
- tests/test_models.py
- tests/test_views.py
- website/static/js/passwordForms.js
- website/templates/landing.mako
[OSF-6780](https://openscience.atlassian.net/browse/OSF-6780)
Change minimum password length from 6 to 8
Change 6 to 8 for all of the following
Update framework/auth/core.py
Update framework/auth/forms.py
Update website/static/js/passwordForms.js
Update website/templates/landing.mako
None
[#OSF-6780]
> [RFR][Feature][OSF-6780]Raise minimum password length to 8 characters

- website/static/js/contribAdder.js
- website/static/js/tests/contributors.test.js
- website/templates/project/modal_add_contributor.mako
Inform users that they cannot add an email address as an unregistered user. Gives the user an error message if the regular expression matches the syntax of an email address.
Checks the regular expression of the query. If the input has the format of [text]@[text].[text], it registers it as an email address, informs the user with an error, and does NOT allow for that user to be added as an unregistered contributor.
n/a
https://openscience.atlassian.net/browse/OSF-5639
> [OSF-5639] Warn users they cannot search by email address

- admin/meetings/serializers.py
Fix the problem that admin for OSF for meetings cannot visit the second page.
Remove unconfirmed user from OSF for meetings admin serializer.
https://openscience.atlassian.net/browse/OSF-6475
> Unable to access all pages of Meetings in Admin App[#OSF-6475]

- admin/meetings/forms.py
- admin/meetings/serializers.py
Fix bug where even if a meeting has a homepage link text it does not show up in the form and you cannot submit the form without entering another one.
Fixed bug mentioned above so now if a meeting has a homepage link text it will appear in the field.
Also made it so that if you do not enter a homepage link text it will default to 'Conference homepage' so that field is no longer required to submit the form.
None that I can see 
https://openscience.atlassian.net/browse/OSF-6854
> Fix admin app meetings form 'Homepage link text' [#OSF-6854]

- api/addons/serializers.py
- api/addons/views.py
- api/base/views.py
- api/nodes/serializers.py
- api_tests/addons/test_addons_list.py
- api_tests/nodes/views/test_node_files_list.py
Add link to list of storage addons, accessible on node providers page
* Enable filtering addons by category
* Add link
* Add tests
Increased max page size of addons list.
[[#OSF-4681]](https://openscience.atlassian.net/browse/OSF-4681)
> [Feature] Storage Addon links / Filter by categories [#OSF-4681]

- bower.json
At.js was using our fork of the library until a fix for the `contenteditable` bugs was taken integrated. The changes were merged 🎉  so we don't need the fork anymore.
* point to upstream instead of fork
None
https://openscience.atlassian.net/browse/OSF-6948
> [Feature] Update At.js dependency to upstream [OSF-6948]

- framework/auth/views.py
Unregistered contributors should be searchable after registering, regardless of whether they set a password or signed in with ORCiD for the first time.
Ensure `user.is_active` when `user.register` calls `user.update_search`
None
[#OSF-6979](https://openscience.atlassian.net/browse/OSF-6979)
Verified with @icereval that only QA accounts were affected. They were manually migrated; no script is necessary.
> [Hotfix] Index ORCiD-registered unreg contribs [#OSF-6979]

- framework/auth/utils.py
- tests/test_conferences.py
Fix failing test
* Update error message in test
* Call `.lower` on possibly-spammy email domain when verifying
None
> [Hotfix] spam email test

- api/base/serializers.py
- api/base/utils.py
- api_tests/comments/views/test_comment_detail.py
- api_tests/files/views/test_file_detail.py
- api_tests/nodes/views/test_node_detail.py
- api_tests/nodes/views/test_view_only_query_parameter.py
- api_tests/wikis/views/test_wiki_detail.py
- Fixes incorrectly formatted comment relationship links by using `furl` to build relationship links with multiple query parameters (`view_only` and `filter`)
- Appends VOL key to generated `self` and `html` links.
- Adds generic `extend_querystring_if_key_exists` helper to `api.base.utils.py` to append the VOL key query parameter if present.
- [OSF-6733](https://openscience.atlassian.net/browse/OSF-6733)
> [feature fix] Append VOL Key to API Links [OSF-6733]

- tests/test_elastic.py
- website/project/model.py
- website/project/spam/__init__.py
Some search tests are failing because elasticsearch index got moved into a queued task. Running `celery_teardown_request` is needed to get all of the entries in ES.
> Fix failing search tests.

- scripts/analytics/institutions.py
Analytics gathering for getting user and node counts grouped by institutions.
Add a script to the analytics module.
1. If the environment doesn't have a private keen project or private keen write key set, the script should output the dictionary rather than trying to send the data to keen
2. I'm not entirely sure how the analytics are run, so a celery beat task or cron job may need to be updated somewhere?
https://openscience.atlassian.net/browse/OSF-6952
> Feature/quick institutions sales stats [OSF-6952]

- website/static/js/pages/base-page.js
Just ran into this; simple typo in user-facing string.
This worked great btw, you thought about everything 👍
> Fix typo in 'merge account' popup

- website/static/js/registrationModal.js
- website/static/js/registrationUtils.js
- website/static/js/tests/registrationModal.test.js
- website/static/templates/registration-modal.html
- website/templates/project/registration_utils.mako
&larr; #6025 ([diff](https://github.com/whit537/osf.io/compare/refactor-registration-modal...clean-up-knockout-validation-usage))
This PR cleans up our usage of Knockout-Validation in the registration modal. Non-idiomatic usage makes the logic harder to follow.
n/a
n/a
https://openscience.atlassian.net/browse/OSF-6837
> Clean up Knockout-Validation usage

- tasks/__init__.py
Causes `invoke setup` to install rabbitmq as a package the osf depends on.
Added an entry to the list of packages that are installed by brew
Probably not.
https://openscience.atlassian.net/browse/OSF-4222?orderby=priority+DESC%2C+updated+DESC
> Task / Install RabbitMQ in `invoke setup` [OSF-4222]

- tasks/__init__.py
- tests/test_metadata.py
- tests/test_node_licenses.py
- tests/test_registrations/test_archiver.py
- website/app.py
- website/project/licenses/__init__.py
- website/project/model.py
Our Varnish tests are occasionally failing at Travis, obscuring test results and adding drag to our development process. Let's fix 'em!
Switch `ensure_{licenses,schema}` from a "look before you leap" (LBYL) model to "easier to ask forgiveness than permission" (EAFP), so that each can safely be run concurrently with itself. See the [commit log](https://github.com/CenterForOpenScience/osf.io/pull/6104/commits) for details.
- A couple uniqueness constraints are now implemented in the database instead of in Python, such that violations now raise `KeyExistsException` instead of `ValueValidationError`.
- We now log process and thread ids on calls to `init_app`.
- The `apiserver` task sprouted an `autoreload` knob.
- `ensure_licenses` now returns a tuple (number inserted, number updated) instead …
> Fix Varnish tests

- website/addons/zotero/requirements.txt
The version of pyzotero we are using is GPL licensed. We are not compatible with GPL. So let's use the new version of Pyzotero which has a much more OSF-friendly license
1. Change our requirements to use the new version
Could break everything zotero related.
https://openscience.atlassian.net/browse/OSF-6983
> Upgrade version of Pyzotero to the MIT-licensed version [OSF-6983]

- requirements.txt
- tasks/__init__.py
- website/project/sanctions.py
*This is a tag-team PR!  @mfraezz has fixed a flake8 issue in current master that was making travis cry.  @felliott's code fixes dependency installation when wheels are involved.  By our powers combined!*
@emetsger encountered a problem when trying to build the OSF with JHU's custom Dockerfile.  All of the requirements were built as wheels, then `invoke req -q` was told to use those wheels.  `oauthlib` failed to install because v1.1.2 was required by the constraints file, but only v0.7.2 (required by Mendely) and v2.* (the latest) were available.
`pip wheel` accepts a constraints file just like `pip install` does.  This PR updates our `invoke wheel` task to pass the constraints to the wheelbuilder.  While investigating this, I also found that the OSF (without addons) is missing an …
> [hotfix] fix build: flake8 correction + fix invoke wheel to support constraints

- framework/exceptions/__init__.py
- framework/mongo/utils.py
- website/project/decorators.py
- website/project/views/register.py
- website/static/js/nodeControl.js
- website/static/js/tests/nodeControl.test.js
From ticket:
>Users should be able to create a DOI for Public Projects and Components. Much like for public registrations, DOIs should only be issued upon request (link click) from the Project/Component Overview page.
>
>If a public project has a DOI and then it is registered (or forked), the project DOI should not be copied over to the registration (or fork).
* Allow admin contributors to create DOI/ARKs on public projects
If a public project with a DOI becomes private again, anyone who follows that DOI but cannot view the project will be confused.
[OSF-6754](https://openscience.atlassian.net/browse/OSF-6754)
> [Feature] Allow DOI Creation on Public Projects [OSF-6754]

- website/static/js/myProjects.js
- This PR adds institution-specific help text when viewing an empty registrations collection. 
- h/t to @amyshi188 for starting work on this PR 
- [OSF-6825](https://openscience.atlassian.net/browse/OSF-6825)
- Before:
- After (institution view):
- After (user view):
> [feature] Add Institution Specific Text for Empty Collections [OSF-6825]

- website/templates/project/settings.mako
- Add text to explain to read-only contributors that they do not have the necessary permissions to affiliate their institution with a project.
- None
- [OSF-6651](https://openscience.atlassian.net/browse/OSF-6651)
- Admin/R+W Contributor View:
- Read-Only Contributor View:
> [feature] Read-Only Contributors Affiliation Help Text [OSF-6651]

- website/identifiers/metadata.py
Fix issue from #6028 -- public, non-registered nodes don't have a `registration_date`
* Get `year` from `registration_date` or `date_created`
None expected
[\[OSF-6754\]](https://openscience.atlassian.net/browse/OSF-6754)
> [Feature][Fix] Public project DOI/ARK creation [OSF-6754]

- website/templates/project/project.mako
Remove superfluous line break
* Remove superfluous line break
None
Relates to [OSF-6753](https://openscience.atlassian.net/browse/OSF-6754)
> [Feature][Fix]Remove line break before "Identifiers"

- tests/test_views.py
- website/project/views/contributor.py
This prevents an edge case by which a user sends a POST to
a claim URL before there is an associated email with the unclaimed
account.
> [hotfix] Prevent claiming account with no associated email

- api/base/views.py
- api_tests/nodes/views/test_node_contributors_detail.py
The list view for BaseContributors grabs the index, but the detail view didn't return it.
- assign the index in `get_object` method of `BaseContributorDetail`
- test to make sure index is there and it increments
- none anticipated
https://openscience.atlassian.net/browse/OSF-7028
> Include index on node contributor detail [#OSF-7028]

- website/static/js/pages/project-dashboard-page.js
Institution logos on the project page were being forced into  a circle, making the non circular logos look a little odd. Instead of using the circular versions of the logos, go ahead and let the logos not be circles if they aren't.
- remove the img-circle css class from project page institution images
Logos look a little larger next to project titles
https://openscience.atlassian.net/browse/OSF-7026
> Make logos on project page not a circle [#OSF-7026]

- website/addons/dataverse/static/dataverseFangornConfig.js
- website/addons/github/static/githubFangornConfig.js
- website/static/js/fangorn.js
The files view page didn't properly filter by file name, or allow sorting when Github or Dataverse were enabled.
- Add blank version rows for github and dataverse on file view page
- Disallow sorting on the version column for file page
https://openscience.atlassian.net/browse/OSF-6863
[#OSF-6863]
> File page name and date modified filter fix [#OSF-6863]

- api/base/serializers.py
- api/base/views.py
- api/collections/serializers.py
- api/collections/urls.py
- api/collections/views.py
- api/nodes/views.py
- api/registrations/views.py
- api_tests/collections/test_views.py
- website/project/model.py
- website/static/js/myProjects.js
- website/static/js/project-organizer.js
[OSF-6029](https://openscience.atlassian.net/browse/OSF-6029)
[My Projects] Registrations that aren't yours have blank contributor names and throw 404 error when expanded
Update  api/base/serializers.py
Add class LinkedRegistration
Update class LinkedNodesRelationshipSerializer do not return registrations
Add class LinkedRegistrationsRelationshipSerializer
Update api/base/views.py
Update class LinkedNodesRelationship do not return registrations
Add class LinkedRegistrationsRelationship
Add class BaseLinkedList
Update api/collections/serializers.py
Update class CollectionSerializer
Add attribute linked_registrations
Update def get_node_links_count do not return registrations
Add def get_registration_links_count
Update api/collections/urls.py
Add /linked_registrations/
Add …
> [feature]Allow for mixed projects and registrations in a collection [OSF-6029]

- website/static/js/pages/project-settings-page.js
- website/templates/project/project_base.mako
This stops the using from entering an the confirmation string before they get an error message telling them they can't delete a nested component.
Changes the project base mako so contextvars include info on wheater a node has children, then uses that info to pre-validate on clicking the delete button.
https://openscience.atlassian.net/browse/OSF-6840
> Alert that user cannot delete project on "Delete" click [OSF-6840]

- framework/analytics/__init__.py
- tests/framework_tests/test_analytics.py
- website/addons/osfstorage/utils.py
- website/addons/osfstorage/views.py
The download count for a file should increment every time any non-contributor downloads the file. This way, the download count is a measure of outside interest in the resource, not a measure of collaborators' downloads.
The main change is to the analytics ```update_counter``` method. This has been changed to check if the user performing the download is one of the project's contributors. If they are, the download count will not be incremented. 
Secondary changes were:
- Changing the signature of ```update_counter``` to accept a ```node_info``` dict that contains a list of contributors.
- Changing ```update_analytics``` to pass the contributors list via ```node_info``` to the ```update_counter``` method.
The ```osfstorage_download``` method had to also be modified to add the user's id to …
> Change download count to not include contributors' downloads [OSF-3628]

- bower.json
- website/static/css/pages/profile-page.css
- website/templates/include/profile/social.mako
This PR is an update and clean-up of [https://github.com/CenterForOpenScience/osf.io/pull/6107](https://github.com/CenterForOpenScience/osf.io/pull/6107).
The purpose of this PR is to add icons for the social links on the profile page. 
Changes include adding Academicons  (now via bower) to the OSF for academic icons, adding icons to the template, and adding formatting for the icons.
No side effects can be seen.
https://openscience.atlassian.net/browse/OSF-789
> Add social icons for social profile [OSF-789]

- website/addons/dataverse/requirements.txt
- Fix `data[fF]ile` key issue
- Prefer pinning to commits rather than branches
* Pin to commit 
None
[OSF-7039](https://openscience.atlassian.net/browse/OSF-7039)
> [Hotfix] Pin Dataverse client to commit

- scripts/populate_conferences.py
- website/project/metadata/prereg-prize.json
- website/templates/base.mako
- website/templates/copyright.mako
- website/templates/public/pages/faq.mako
A bad SSL certificate on https://centerforopenscience.org/ is breaking links from OSF to cos.io. This PR works around this problem by updating the links to point directly to https://cos.io/, which is the terminal redirect.
The main link to check is the one in the footer.
n/a
https://openscience.atlassian.net/browse/OSF-7043
> Update links to cos.io

- admin/meetings/serializers.py
Make Meetings editable via ADM
* Prevent `KeyError`, show default value if available.
None expected
[\[OSF-7047\]](https://openscience.atlassian.net/browse/OSF-7047)
> [Hotfix] Prevent KeyError for Meetings in ADM [OSF-7047]

- website/static/js/fangorn.js
The error message for not being able to upload a folder wasn't being called on treebeard instances until another action was complete such as successfully uploading a file. Make sure that the modal is triggered when there's just an error and not an error bundled along with a success
- make sure `queuecomplete` is called when an error has happened
Tested as best I could, but I hope that no errors cause other things not to upload - things in the file tree seem to happen the way they should!
https://openscience.atlassian.net/browse/OSF-6910
> Make sure "cannot upload folder" error is shown in a timely manor [#OSF-6910]

- website/static/js/logTextParser.js
Capitalize the "Home" wiki page in the recent activity log text to reflect the name of the Home page as it is shown to the user. The user sees "home" in the log text when they should see "Home". This PR fixes that issue.
In the ```logTextParser```, added a check for a ```wiki_update``` on the home page. When the check catches that event occurring, the ```source``` log text is capitalized (to "Home").
None, as the change is cosmetic and local to the ```logTextParser::returnTextParams``` function.
[https://openscience.atlassian.net/browse/OSF-6367](https://openscience.atlassian.net/browse/OSF-6367)
> Logs should capitalize wiki's home page [OSF-6367] 

- website/static/css/quick-project-search-plugin.css
After the arrow used to display more projects is clicked the bottom margin disappears.
Simple CSS fix.
https://openscience.atlassian.net/browse/OSF-6552
> [OSF-6552] Fix bottom margin for quick project search

- website/static/css/meetings-and-conferences.css
- website/static/css/pages/home-page.css
- website/static/js/home-page/preregPlugin.js
- website/static/js/pages/home-page.js
- Adds a banner for the Preregistration Challenge to the OSF dashboard page.
- Adds a background to the Preprints banner because it didn't have one. 
- Makes all of the banner buttons have the same fixed width.
- None.
- (with "Preregister" text on button as opposed to "Begin a Preregistration")
- @saradbowman, I chose the background for the Prereg banner just based on what I thought looked nice (repeating the three backgrounds that were already being used on the page), but I can change the background for this banner (and the others) to be whatever your ❤️  desires. Also, I can fit "Begin a Preregistration" on the button, but it does look a bit long compared to the other banners buttons (screenshots for both options shown below so you can which you prefer).
- …
> [feature] Add Prereg Banner to Dashboard [OSF-7009]

- requirements.txt
Our Modular-ODM dep was tracking `develop` instead of commits or releases.  To avoid pulling in untested versions of modm, pin the dep via the release tags to v0.4.0.
None expected.
[#OSF-7053] - [JIRA](https://openscience.atlassian.net/browse/OSF-7053)
> [feature] pin modm to current release (0.4.0) [OSF-7053]

- framework/auth/core.py
- framework/auth/forms.py
- website/static/js/passwordForms.js
- website/templates/landing.mako
Prevent issue when passwords are 256 characters.
Set `maxLength` to `255`
None expected
None known.
Exactly 256 characters:
> [Hotfix] Decrement maxLength for passwords

- website/static/css/meetings-and-conferences.css
- website/static/css/pages/home-page.css
- website/static/js/home-page/meetingsAndConferencesPlugin.js
- website/static/js/home-page/preprintsPlugin.js
- website/static/js/home-page/preregPlugin.js
- Adds `.banner` CSS class for fixed width, which is applied only to the banner buttons on the dashboard.
- Removes `.btn` class from `meetings-and-conferences.css` which caused the fixed width to be incorrectly applied to the "Create new project" button.
- [OSF-7009](https://openscience.atlassian.net/browse/OSF-7009)
> [feature fix] Fixed Width Banner Buttons on Dashboard [OSF-7009]

- framework/auth/cas.py
@sloria 
Django's `.object.get()` will throw `ObjectDoesNotExist` exception when query fails to find the object. It also throws `ValueError` exception if `cas_resp.user` cannot be converted to Integer as primary key, in the case for ORCiD login.
Please refer to the code.
User can now login or create/link accounts through ORCiD.
No Ticket
> [feature/django-osf] Handle `User.object.get(pk=cas_resp.user)` exceptions [Part of #7064]

- website/addons/dataverse/static/dataverseFangornConfig.js
- website/addons/dataverse/static/dataverseNodeConfig.js
- website/addons/dataverse/static/dataverseUserConfig.js
- website/addons/forward/static/forwardConfig.js
- website/addons/s3/static/s3NodeConfig.js
- website/addons/s3/static/s3UserConfig.js
- website/addons/twofactor/static/twoFactorUserConfig.js
- website/addons/wiki/static/WikiEditor.js
- website/addons/wiki/templates/add_wiki_page.mako
- website/static/js/comment.js
- website/static/js/contribAdder.js
- website/static/js/institutionProjectSettings.js
- website/static/js/nodesPrivacy.js
- website/static/js/pages/base-page.js
Fix a bunch of incorrect `Raven.captureMessage` calls that were passing log data at the wrong level.  Arbitrary log data should live under the `extra` key of the options argument.
None expected.
[#OSF-7054] - [JIRA](https://openscience.atlassian.net/browse/OSF-7054)
> [feature] fix incorrect Raven.captureMessage invocations [OSF-7054]

- website/addons/owncloud/static/owncloudNodeConfig.js
- website/addons/owncloud/static/owncloudUserConfig.js
- website/addons/owncloud/views.py
- website/addons/s3/static/s3NodeConfig.js
Fix minor bugs discovered with ownCloud addon
* Safari objected to the use of `const`, use `var` instead
* Fix scoping issues when calling `super` functions
* `strip` removes any character, not matching substrings. Prefer `replace`. (Consider `re.match`?)
None expected
> [Feature] ownCloud bug fixes

- framework/guid/model.py
Allow duplicate characters in the same GUID, thus expanding the set of possible GUIDs
`random.sample` effectively pops the selected item from the population when sampling. For example, `random.sample('12345', 5)` will output exclusively permutations of `'12345'`:
```
In [1]: import random
In [2]: random.sample('12345', 5)
Out[2]: ['1', '5', '2', '3', '4']
In [3]: random.sample('12345', 5)
Out[3]: ['1', '2', '3', '4', '5']
In [4]: random.sample('12345', 5)
Out[4]: ['3', '1', '2', '4', '5']
In [5]: random.sample('12345', 5)
Out[5]: ['4', '3', '2', '1', '5']
```
This causes GUIDs to not have multiple instances of the same character -- you'd never see an `_id` of `aabcd` even if it wasn't on the `BlackListGuid` list. Because it is, however, and because of how many other `BlackListGuid`s have …
> [Hotfix] Allow duplicate characters within the same GUID [OSF-7059]

- website/addons/owncloud/static/owncloudNodeConfig.js
- website/addons/s3/static/s3NodeConfig.js
- website/static/js/oauthAddonNodeConfig.js
Workaround for `oop.js` recursion bug
* Break the bulk of `constructor` out to `construct` so that the child class can call both `<grandparent>.constructor` and `<parent>.construct`
None expected
> Implement workaround for recursive scoping bug

- README.md
README.md specified an older version of invoke that did not work when installing the OSF locally on a clean install. ReadTheDocs specified a newer version which worked.
Update invoke specified version
None
None
> update specified invoke version

- requirements.txt
@sloria 
Django 1.9 no longer support `py-bcrypt==0.4`:
```python
...
File "/Users/longzechen/.virtualenvs/osf-postgres/lib/python2.7/site-packages/django/contrib/auth/hashers.py", line 289, in salt
return bcrypt.gensalt(rounds=self.rounds)
TypeError: gensalt() got an unexpected keyword argument 'rounds'
```
In addition, `py-bcrypt==0.40` inherits OpenBSD `u_int8_t` vulnerability.
Use `bcrypt==3.1.1` (latest version).
No
https://openscience.atlassian.net/browse/CAS-9
> [feature/django-osf] Fix BCrypt [#CAS-9]

- website/addons/wiki/static/wikiPage.js
- website/addons/wiki/templates/edit.mako
- website/addons/wiki/templates/wiki_widget.mako
- website/addons/wiki/tests/test_wiki.py
- website/addons/wiki/views.py
- website/static/js/markdown-it-pymarkdown-lists.js
- website/static/js/markdown.js
- website/static/js/pages/project-dashboard-page.js
- website/static/js/tests/oldMarkdownFormatting.test.js
While wikis nowadays are rendered in Javascript, wikis created before Febuary 12, 2015 we
- saved the wiki to the database as markdown
- rendered the markdown in Python
- saved the rendered markdown as html into the database for use later
If it was an old wiki, we were using that pre-rendered wiki html put that into the view pane and wiki widget instead of rendering the plain markdown with JS as we do with newer wikis.
We no longer want to trust html, and want to use JS to render all markdown from now on. **But** we want to keep the look of the old python markdown! Which has [some key differences from javascript markdown](http://pythonhosted.org/Markdown/#differences).  Of these differences, the most notable is list behavior.
For example! The following raw markdown:
1. first
2. second
* …
> Use JS rendering for all wiki markdown regardless of age [OSF-6412] [OSF-7038]

- api/logs/serializers.py
- api_tests/logs/views/test_log_detail.py
- Currently, when a file is moved from a private component to a component a user has access to, the title of the private component is exposed in the API via the `/v2/nodes/<node-id>/logs/` endpoint. This PR checks user permissions before serializing the titles of source nodes in a file move log. 
- Adds a serializer method field to determine if this user has permission to see the source node title for a file moved log. 
- `/v2/nodes/<node-id>/logs/`
- Before:
- `params['source']['node_title']` ("Just Me") should not be visible to this contributor:
- ![screen shot 2016-10-05 at 3 02 51 pm](https://cloud.githubusercontent.com/assets/7913604/19127418/d987ae2a-8b0c-11e6-8be7-1c2cdb29f47a.png)
- After 
- `params['source']['node_title']` has changed to "Private Component":
- …
> [feature] Check User Permissions When Serializing File Moved Log [OSF-6521]

- tests/test_views.py
- website/project/views/contributor.py
- In the workflow of adding unregistered contributors and claiming accounts, there is an uncovered condition of a logged-out user using an unregistered contributor claim link after they have created an account with the same email they claimed to be a contributor with. 
- Steps to reproduce:
- As an admin on a public project, add an unregistered contributor by just their name, not email. 
- As a logged-out user visiting said public project, click on the unregistered contributor name and enter an email to claim yourself. 
- Note that two emails are sent: one sent to the project admin who added the unregistered contributor (with a claim link), and one sent to the email of the logged-out user who just claimed themselves.
- *do not click the claim link yet* 
- As a logged-out user, sign up for …
> [feature] Handle Registered and Logged-out User Using Unregistered Claim Link [OSF-6857]

- website/static/js/registrationUtils.js
- Preserves line breaks that are entered while filling out a registration form.
- Adds back the `breaklines` class which was added [here](8b567fe564bc5550b47daa596016707bbd728b4c) and then somehow removed around [here](ceea8db61b8693a9ecdb5f5b884797a781c9223e).
- Registration form preview (before):
- Registration form preview (after):
- Admin review preview (before):
- Admin review preview (after):
- [OSF-7019](https://openscience.atlassian.net/browse/OSF-7019)
> [feature] Preserve New Lines in Registration Forms [OSF-7019]

- api/nodes/views.py
- api_tests/base/test_throttling.py
- Currently, the only throttle class applied to the `NodeContributorsList` view is the custom `AddContributorThrottle`. Applying this custom class overrides the default throttle classes we are using (`UserRateThrottle` and `NonCookieAuthThrottle`) so that the default rates are not being checked when this endpoint is accessed. 
- This PR adds the default throttle classes to the `NodeContributorsList` view, and adds a test to confirm all three rates are being applied.
- Add the default `UserRateThrottle` and `NonCookieAuthThrottle` classes to `NodeContributorsList` view.
- [OSF-7065](https://openscience.atlassian.net/browse/OSF-7065)
h/t @mfraezz for discovering this bug.
> Fix AddContributorThrottle [OSF-7065]

- tests/test_search/test_elastic.py
- website/search/elastic_search.py
- website/search/util.py
Allow search queries with dashes, periods, and underscores to be searchable. Specifically, files and nodes ares now searchable ignoring - _ and .
Previously the project named Bohemian_Rhapsody would only be found by searching the full name with the underscore. Now  Bohemian_Rhapsody can be found via searching Bohemian or Rhapsody. 
Add extra_search_terms elasticdoc and filedoc in elastic_search. extra_search_terms is just a version of the file name or node name with - _ and . replaced with spaces allowing all values to be indexed. If no - _ or . are in the file/node name then no extra search terms are added.
1. This change should only increase the number of search results and not remove any results.
2. It is possible that files and nodes with - _ and . will slightly increase in search …
> [Feature] Add extra search terms [OSF-7071]

- website/project/metadata/aspredicted.json
- website/project/metadata/brandt-postcomp-2.json
- website/project/metadata/brandt-prereg-2.json
- website/project/metadata/osf-open-ended-2.json
- website/project/metadata/osf-standard-2.json
- website/project/metadata/prereg-prize.json
- website/project/metadata/veer-1.json
- website/templates/project/modal_generate_private_link.mako
- website/templates/project/project.mako
- website/templates/project/retracted_registration.mako
- continuation of @amyshi188's work in #6150 
- Make user-facing registration terminology more consistent. 
- The registration form a user chooses when making a registration (e.g. "Open-ended Registration", "Preregistration Challenge", etc.) were referred to as forms, templates, and supplements. This PR makes the terminology consistent by using "registration form" throughout the OSF.
- [OSF-6289](https://openscience.atlassian.net/browse/OSF-6289)
- Registration form tooltips (before):
- Registration form tooltips (after):
- Registration overview (before):
- Registration overview (after):
- Add VOL modal (before):
- Add VOL modal (after):
> [feature] Make Registration Terminology Consistent [OSF-6289]

- website/templates/project/registration_editor_templates.mako
- Adds text to the comments section of a preregistration draft to clarify that preregistration comments are not registered.
- [OSF-7007](https://openscience.atlassian.net/browse/OSF-7007)
> [feature] Clarify Prereg Comments [OSF-7007]

- api/files/serializers.py
- api/files/views.py
- api/nodes/views.py
- api_tests/files/views/test_file_detail.py
The version of the primary file for the preprint needs to be exposed in the view preprint page.
Exposes current_version as a serializer field on file. Determined by the length of the history.
https://openscience.atlassian.net/browse/OSF-7067
Needed for https://openscience.atlassian.net/browse/PREP-144
> Feature/Make current_version a file serializer field [OSF-7067] [PREP-144]

- website/addons/dataverse/static/dataverseFangornConfig.js
- website/addons/github/static/githubFangornConfig.js
- website/static/js/fangorn.js
- website/static/js/filepage/revisions.js
- website/static/js/pages/file-page.js
- website/static/js/registrationEditorExtensions.js
- website/static/js/waterbutler.js
*Note:  This is a rebased and updated version of #5240.*
Update fangorn to use WaterButler v1 API, hopefully hastening the retirement of v0.
update website/addons/github/static/githubFangornConfig.js for WB v1 upload URL
update website/static/js/fangorn.js for URLS, and lazyLoadPreprocess
update website/static/js/waterbutler.js for WB v1 URLS
update website/static/js/filepage/revisions.js for lazyLoadPreprocess
remove unused waterbutler imports
remove obsolete delete url formatting for dataverse
None expected.
[#OSF-5847] - [JIRA](https://openscience.atlassian.net/browse/OSF-5847)
> [feature] Update fangorn to use WaterButler v1 API [OSF-5847]

- website/templates/project/project_header.mako
This PR rewords some of the project headers on registrations that specify what it is a registration of. 
This PR edits the wording of the registration decorator from 
"This project is a registration of **this project**; the content of the project has been frozen and cannot be edited"
To:
This registration is a frozen, non-editable version of this project. (With link to "this project")
This change trickles to all node types, which is intended. 
https://openscience.atlassian.net/browse/OSF-3518
> changing initial wording of registration header [OSF-3518]

- website/addons/s3/templates/s3_node_settings.mako
- website/static/js/folderPickerNodeConfig.js
- website/templates/project/addon/node_settings_default.mako
On the add-on settings page, when one presses the “Change” button to change folders, it toggles a folder change dialog. The same “Change” button then has to be used to close the folder change dialog, leading to confusion over what the button does. This fixes that by changing the button text after the button is pressed to “Close”. Thus, users will be able to tell that the button functions as a toggle for a panel.
`folderPickerNodeConfig.js`
- added button text as a knockout observable
- added logic to ```togglePicker``` function that toggles button text between “Change” and “Close”
`node_settings_default.mako` and ```s3_node_settings.mako`
- changed button to use `<span>` for button text that binds to the knockout observable (and thus changes the button text on click)
None; the change is …
```
> [Production& Staging] Add change folder toggle button [OSF-3655]

- tasks/__init__.py
Optionally disable the allocation of a pty when using `invoke` using the `--no-pty` flag.
Adds a `pty` argument which defaults to `True` to the `apiserver`, `adminserver`, and `wheelhouse` tasks.
None.  The new flag defaults to `True` which maintains existing behavior.  Supplying `--no-pty` is optional.
See https://github.com/CenterForOpenScience/waterbutler/pull/167
> Allow disabling of pty for 'wheelhouse', 'adminserver', and 'apiserver' tasks [OSF-7057]

- tests/base.py
- tests/test_metadata.py
- tests/test_test_utils.py
Our current testing infrastructure scopes database isolation to the test class level. Better practice is to scope isolation to the test-case level, to avoid interference between one test and another. This PR factors out a `DbIsolationMixin` implementing test-level isolation for use across multiple test classes.
No user-visible changes.
No side-effects.
https://openscience.atlassian.net/browse/OSF-7042
> Support test-level database isolation [OSF-7042]

- website/static/js/filepage/revisions.js
OwnCloud uses a date format that isn't parseable by `FormattableDate`, meaning that timestamps don't show up on the file revisions page.
Update the file revisions page to use the `modified_utc` field  in WB metadata responses.  This field translates the `modified` timestamps (which are returned in the provider's preferred format) to standard ISO8601 representation with a +00:00 offset (UTC).  This field was added to WB in v0.22.0 (released mid-August 2016).
None expected.
No ticket.
> Update file revisions page to use WB utc timestamp

- osf_models_tests/test_comment.py
- tests/test_comments.py
- tests/test_views.py
- website/app.py
- website/notifications/emails.py
- website/project/model.py
Move model tests from `tests/test_comments.py` into `osf_models_tests/test_comment.py`, and fix a few things along the way
- port tests
- move `test_find_unread_includes_edited_comments` into `tests/test_views.py`
- Add `NotificationDigest` to app.py
- Check for users to send to in `emails.py`, as [] does not have `.all()` method
- refactor `validate_contributor` method a bit to get user from GUID and check after the fact
https://github.com/CenterForOpenScience/osf-models/issues/132
> [WIP] Port comment tests for osf_models

- website/static/js/fangorn.js
Moving a file into the storage root of another project causes the move to fail and the file to be deleted.
The Fangorn to WBv1 conversion was indicating the node id of the target node with a property that exists for subfolders but not the storage root.  This PR updates the code to use a common property instead.
None expected.
Bugfix for [OSF-5847] [Link](https://openscience.atlassian.net/browse/OSF-5847), caught by QA during testing.
> [feature][fix] fangorn: send node id for x-node root folder moves [OSF-5847]

- website/static/js/myProjects.js
Adding All My Preprints broke the institutions My Projects view. This PR is attempting to fix that issue.
- Removed third systemCollection (All my preprints) from the logic where user provides their systemCollections. NOTE: the current implementation of this is fragile and probably only works for the institutions use case. It should rather loop through the passed in systemCollections. But I didn't change that because I don't want to fix beyond the need of the issue and create QA concerns. 
None, All my preprints for individual user still works as expected. 
https://openscience.atlassian.net/browse/OSF-7032
> Fix adding preprints breaking institutions [OSF-7032]

- api/base/urls.py
- api_tests/base/test_views.py
- Adding versioning (#6329) to the API resulted in broken swagger docs. Unfortunately, this [cannot be fixed](https://github.com/marcgibbons/django-rest-swagger/issues/344) without upgrading to django-rest-swagger 2.0 and DRF 3.4, which we aren't quite ready to do at the moment. 
- This PR temporarily redirects the docs route (`/v2/docs/`) to root (`/v2/`) until we decide to upgrade django-rest-swagger and DRF. 
- `/v2/docs/` -> `/v2/`
- [OSF-7106](https://openscience.atlassian.net/browse/OSF-7106)
> [feature] Redirect Swagger Docs to Root [OSF-7106]

- website/prereg/utils.py
Fix query for a user's nodes on which they are admins!
- Update node query for getting a user's nodes, then filter by admin
One query and a pairing down of results vs one modular ODM
https://trello.com/c/tA2FBEWb/16-prereg-splash-page-leads-to-unable-to-resolve
> Allow prereg splash page to load for django-osf

- osf/models/institution.py
`v2/institutions/` API routes were broken in new models -- also pass along the `version` kwarg to match old models for `api_v2_url`!
- Pass `version` kwarg for `api_v2_url` and `absolute_api_v2_url`
Nope!
https://trello.com/c/5j5UzvCk/22-institution-detail-route-in-api-no-worky
> Fix Institutions API routes for django-osf with version kwarg

- website/addons/dataverse/static/dataverseFangornConfig.js
Downloads from Dataverse were broken because DV's fangorn config was sending the path twice.
Stop sending the path twice.
None expected.
Bugfix for: [#OSF-5847] -- [Link](https://openscience.atlassian.net/browse/OSF-5847)
* WBv1 gets cranky if you try to set the file path in the url AND the
query param. So don't do that.
> [featurefix] Fix broken DV downloads with Fangorn+WBv1 [OSF-5847]

- .travis.yml
Exclude any branch that has django-osf in the branch name from TravisCI.
> Exclude any branch that has 'django-osf' in the name

- website/addons/base/views.py
`create_waterbutler_log` is using the wrong key to detect errors in WB responses. This means that we were signaling file updates at times when we shouldn't.  In some cases this could cause a recursive fetching of the addon contents, which is bogus.
`s/error/errors/`
None expected.
No ticket.
> fix typo that was signaling files on wb errors

- osf/models/node.py
- osf_tests/test_node.py
Fix broken behavior of Node.parent_node for forked components. Also unskip some valid tests.
All osf_tests passing locally.
> [djangosf] Fix parent_node behavior

- api_tests/base/test_auth.py
- osf/models/mixins.py
- osf/models/node.py
- osf_tests/test_node.py
- osf_tests/test_user.py
Various fixes for addon methods to make the behavior consistent with v1. Adds and unskips tests.
- Don't allow deletion of mandatory addons
- Fix signature of add_addon
- Unskip valid TFA tests
- Add test for Node addon methods
> [djangosf] Fix behavior of addon methods for consistency with v1

- framework/encryption/__init__.py
- scripts/encrypt_external_accounts_unicode.py
Fix issue with encrypting unicode
* `jwe` [wants bytes](https://github.com/chrisseto/pyjwe/blob/master/README.md), so give it `bytes`
`python -m scripts.encrypt_external_accounts_unicode --dry`
None expected.
None
```
In [4]: name = 'mfräezz'
In [5]: jwe.encrypt(name.encode('utf-8'), SENSITIVE_DATA_KEY)
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-5-ca1156250faa> in <module>()
----> 1 jwe.encrypt(name.encode('utf-8'), SENSITIVE_DATA_KEY)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```
```
In [6]: jwe.encrypt(bytes(name), SENSITIVE_DATA_KEY)
Out[6]: 'eyJhbGciOiAiZGlyIiwgImVuYyI6ICJBMjU2R0NNIn0.._6_kjjv7JIsqlcy_ZfRkqg. …
```
> [Hotfix] Encrypt unicode correctly

- api/base/pagination.py
- api_tests/nodes/views/test_node_comments_list.py
- api_tests/nodes/views/test_node_embeds.py
- https://staging-api.osf.io/v2/nodes/?version=2.1&embed=contributors currently gives a `502`, we do not like mysterious `502`s.
- This PR fixes the `NodeContributorPagination` and `CommentPagination` classes to no longer incorrectly look for pagination metadata in the old `2.0` location when version `2.1` is specified. 
- [OSF-6473](https://openscience.atlassian.net/browse/OSF-6473) (original versioning ticket)
> [feature] Fix v2.1 Pagination [OSF-6473]

- framework/auth/views.py
- osf/models/user.py
- tests/test_views.py
- website/project/views/contributor.py
- website/project/views/node.py
**note** A few views tests are still failing because the `osfstorage` addon is acting up -- which @sloria is currently workin on!
Make existing tests from `tests/test_views.py` pass!  Some changes to the tests (timezone assurances, generator/queryset fixes ) and a few updates to the views themselves to make sure they work with the new models and are passing along the right things!
- Make sure a few things are in UTC when tests failed because of not being able to compare aware and naive datetimes
- Some things are generators now, update checking methods
- A few methods have new signatures, fix those when called
- Use queries in replace of the old `User. find_by_email`
- Changes in `website/project/views/node.py`:
- Use a `Guid` object to get nodes, cause Guids are passed and not Node ids
- …
> Fix (most) failing views tests for django-osf

- framework/auth/campaigns.py
- framework/auth/views.py
CAS Institution Login (PR https://github.com/CenterForOpenScience/osf.io/pull/6082) was implemented with the vanilla Preprints at hand. However, this breaks auth logic for current ember Preprints which do not share OSF auth logic.
For example, when user try to login from the register page: `https://staging.osf.io/register/?campaign=osf-preprints`, she/he hits: `
https://staging-accounts.osf.io/login?service=https://staging.osf.io/preprints/`. After successful CAS authentication, the login fails the OSF-side service validation with no authenticated OSF session created, and user ends up on:`
https://staging.osf.io/preprints/?ticket=ST-774-ureywqBxppkdNEJ3yvrm-staging-accounts.osf.io`
To fix this issue, we add a `login/?next=` and `register/?next=` endpoint to handle OSF authentication. User …
> [Fix] Fix OSF Login and Register End Point [CAS-3]

- tests/framework_tests/test_routing.py
- website/routes.py
- website/settings/defaults.py
- website/static/js/pages/home-page.js
- website/templates/base.mako
- Hides institution logos from the dashboard institution carousel until there are at least 5 projects (non-registered, public, top-level nodes) affiliated with the institution.
- Replaces `all_institutions` global with `dashboard_institutions`
- Users may not know a given institution exists on the OSF until there are enough affiliated projects to display the logo. 
- [OSF-6980](https://openscience.atlassian.net/browse/OSF-6980)
> [feature] Hide Institution Logos with < 5 Affiliated Nodes [OSF-6980]

- website/static/js/filepage/index.js
[OSF-6670](https://openscience.atlassian.net/browse/OSF-6670)
Large text file are failing to renderer in a disorderly manner.
Limit them.
Update website/static/js/filepage/index.js update file size limit to 64k to match MFR CodePygmentRenderer limit.
This PR is lock step with MFR PR#217 limiting the size of text file that we'll allow to use the share editor. If these limits get out of sync, users may be confused.
[#OSF-6670]
> Limit sharejs/ace editor to 64k to match MFR PR#217 [OSF-6670]

- website/static/js/osfHelpers.js
- website/static/js/pages/registration-retraction-page.js
- website/static/js/registrationRetraction.js
- website/static/js/tests/registrationRetraction.test.js
- website/templates/project/retract_registration.mako
Project titles with smart quotes currently need to copy/pasted to withdraw a registration as they are not easily typeable.
Retooled to match project deletion script. Now requires typing of a scientists name. 
None known.
https://openscience.atlassian.net/browse/OSF-7082
1. Test that you can withdraw registrations with the new text.
2. Test that you can delete projects (this change touched a tiny portion of that code).
> [Feature] Handle smart quotes in registration withdraw form [OSF-7082]

- tests/test_search/test_elastic.py
- website/search/elastic_search.py
Files without guids in search lead to file not found page. This fixes the broken url.
Wraps the file_ object with .wrapper() to properly update the file_.path for OsfStorage files.
None known
```
invoke migrate_search
```
https://openscience.atlassian.net/browse/OSF-7078
1. Test that files found through search with and without guids lead to the file when clicked.
2. Test that files on OsfStorage and at least one other provider properly redirect.
> [Feature] Fix file seach result path [OSF-7078]

- api/nodes/views.py
- api/registrations/serializers.py
- api/registrations/views.py
- api/wikis/serializers.py
- api/wikis/views.py
- api_tests/nodes/views/test_node_wiki_list.py
- api_tests/wikis/views/test_wiki_detail.py
- Fixes the `node` and `comment` relationship links for registration wikis. 
- Separated current wiki serializers into a base `WikiSerializer`, `NodeWikiSerializer`, and `RegistrationWikiSerializer`.
- BEFORE `/v2/wikis/<wiki_id>/` (of a registration wiki)
- AFTER `/v2/wikis/<wiki_id>/` (of a registration wiki)
- BEFORE `/v2/registrations/<node_id>/wiki/`
- AFTER `/v2/registrations/<node_id>/wiki/`
- [OSF-7074](https://openscience.atlassian.net/browse/OSF-7074)
> [feature] Fix Wiki Serializer Relationships [OSF-7074]

- framework/auth/core.py
- tests/test_auth.py
- Currently, if you sign up for an OSF account multiple times without confirming your account after the first sign-up attempt you will receive multiple "confirm account" emails (good), but for each sign-up attempt after the first you will receive a "reset password" email (bad). 
- This PR makes it so that subsequent sign-up attempts will result only in "confirm account" emails, not "reset password" emails. 
- Only sends the "password reset" email if a password change occurs for a **confirmed** user. 
- Are there any cases where an unconfirmed user should be able to change their password? This change would prevent that.
- [OSF-7060](https://openscience.atlassian.net/browse/OSF-7060)
> [feature] Fix Password Reset Email Sent After Duplicate Sign-Up [OSF-7060]

- website/static/js/filepage/editor.js
Add skip logic to prevent fileEditor from downloading the file twice.
Checks for already loaded file data before making the call.
Without separating the reloadFile function from the fileEditor, there is still a small window in which the file could be accessed twice. Specifically, if the first ajax request has executed, but not finished, the call will be made again. In my testing I didn't experience this. 
https://openscience.atlassian.net/browse/OSF-6883
[#OSF-6883]
1. The file editor should work properly (edit, save, and revert)
2. The file should be loaded up only once (see jira ticket for how this is tested, I recommend doing so in Firefox as conditions that cause the bug occur most often there).
> [Feature] Stop file editor from being created twice [OSF-6883]

- website/static/js/fangorn.js
General fixes for the following file tree widget bugs:
Reported Bugs Fixed
1. OSF-6875 - When renaming files/folders, typing square closing brackets leads to odd behavior
2. OSF-5267 - When renaming files/folders, moving the mouse over a widget removes last entered values
Unreported Bugs Fixed
3. When creating a new folder, pressing the Enter key does not submit
4. When renaming a file/folder to a name that already exists, the help text lists the wrong file name to be replaced (needs to be tested on preprints as well).
5. When renaming a file/folder, clicking on a different file/folder allows you to modify that file/folder name (it should clear the toolbar).
6. When filtering and at least one letter is typed, clicking white space within the file picker removes the filtering but leaves the …
> [Feature] Fix File Tree Renaming [OSF-6875][OSF-5267]

- website/static/js/logTextParser.js
Continuation of [OSF-6367](https://openscience.atlassian.net/browse/OSF-6367). Capitalize home wiki page name in logs for comment actions.
Added a line to the log text generator for wiki comments that capitalizes the wiki name if it is the home wiki.
None, this change is purely cosmetic
[https://openscience.atlassian.net/browse/OSF-7079](https://openscience.atlassian.net/browse/OSF-7079)
> Capitalize home wiki page in comment action log texts [OSF-7079]

- api/comments/views.py
- api_tests/comments/views/test_comment_detail.py
comment_node did not always exist before comment_node.is_registration was checked. This error caused comment replies not to be deleted as it failed out.
Initialize comment_node to false and make sure comment_node exists.
None known.
https://openscience.atlassian.net/browse/OSF-7056
This might also solve: https://openscience.atlassian.net/browse/OSF-6994
[#OSF-7056]
> Ensure comment_node exists before trying to access is_registration [OSF-7056][OSF-6994]

- package.json
- website/static/js/fangorn.js
Previously, orderFolder always re-sorted on the first column (ascending or descending). This PR (and the corresponding treebeard PR) make orderFolder resort based on the users last sort method (defaulting to Alphabetically/Ascending). 
sortOrder checks sort column status and sorts based on that.
Update treebeard version
None known.
[#OSF-6570]
The following I believe trigger the resorting:
1. Initial loading of the page
2. Renaming a file
3. Adding a folder
4. Adding a file
If no sort order is selected, the default is Alphabetical, Ascending.
I have only tested this with Dropbox and OSF Storage. I do not expect there to be addon specific problems for this change.
> [Feature] Make orderFolder maintain previous sorting [OSF-6570]

- website/static/js/filepage/index.js
The MFR embed for PDF's was calculating the height incorrectly:
But we want it to be like this:
The dynamic MFR embed now starts with the following:
`<style>.embed-responsive{position:relative;height:100%;}.embed-responsive iframe  {position:absolute;height:100%;}</style>`
These styles are from Bootstrap and are required for the correct dynamic calculation of the embed's height. The OSF page already includes Bootstrap, so they are already present. But if the embed is on a page without Bootstrap, they have to be manually added, which we do here.
None
https://openscience.atlassian.net/browse/OSF-4770
> [OSF-4770]MFR Dynamic Embed should include dependent Bootstrap CSS styles

- website/addons/github/api.py
Pages do not load when github is down. This catches the error so the page at least loads.
Catch the error, let page load. 
Sometimes the github logo showed up saying it couldn't load and sometimes it just didn't appear at all. Since this should be a rare occurrence it may not be worth worrying about, but wanted to mention.
https://openscience.atlassian.net/browse/OSF-7142
[#OSF-7142]
> [Hotfix] fail gracefully when addons down [OSF-7142]

- website/static/js/filesWidget.js
- website/static/js/registrationEditorExtensions.js
The preregistration file picker is broken because it doesn't handle WBv1 responses.
Remove FilesWidget-specific Fangorn overrides to take advantage of its WB response unrolling.  Update manual response parsing to handle the new response structure.
No ticket.
* prereg was doing some custom overloading of fangorn and manual
response processing and therefore didn't missed out on the WBv1 API
conversion in Fagorn.
> [hotfix] update prereg files widget for WBv1

- website/static/js/filepage/index.js
The Fangorn WBv0 => WBv1 conversion didn't account for a query parameter that changed names. As a result, providers that can send a redirect to the file (osfstorage and s3) were failing their CORS check.
Update the file view page to pass `direct=` to WB instead of `accept_url=`.
None expected.
[#OSF-7144] -- [Link](https://openscience.atlassian.net/browse/OSF-7144)
* The WBv0 `accept_url` param has been renamed to `direct` in WBv1.
Update the file view page to follow.  This fixes CORS issues when
trying to download from osfstorage or s3.
> [hotfix] fix file editing [OSF-7144]

- website/addons/wiki/templates/wiki_widget.mako
The wiki preview size should be a fixed size and scrollable so that the preview isn't too long when many images are involved.
Added a CSS class to the preview div to make it fixed-size and scrollable.
None, this change is purely cosmetic.
[https://openscience.atlassian.net/browse/OSF-5781](https://openscience.atlassian.net/browse/OSF-5781)
> Truncate Wiki Preview [OSF-5781]

- website/static/js/fangorn.js
When a user renames a file to a name that already exists, the OSF asks if they want to keep both files or overwrite the existing one.  This is currently broken, because the `conflict` parameter that indicates the desired behavior is not being sent with the rename request.  In the absence of the `conflict` param, WB defaults to throwing a 409 Naming Conflict error.
Include the `conflict` parameter in the rename request body.
None expected.
[#OSF-7145] -- [Link](https://openscience.atlassian.net/browse/OSF-1234)
> [hotfix] fix rename conflicts [OSF-7145]

- website/static/js/tests/addons/folderPickerNodeConfig.test.js
- website/static/js/tests/contributors.test.js
- website/static/js/tests/forgotPassword.test.js
- website/static/js/tests/formModelView.test.js
- website/static/js/tests/licensePicker.test.js
- website/static/js/tests/nodeControl.test.js
- website/static/js/tests/oop.test.js
- website/static/js/tests/paginator.test.js
- website/static/js/tests/profile.test.js
- website/static/js/tests/saveManager.test.js
Make the Karma tests stop failing so often
Skip most of the tests that are likely to fail
Lower JS test coverage
https://openscience.atlassian.net/browse/OSF-7002
> Skip many of the javascript viewmodel tests for better reliability [OSF-7002]

- scripts/tests/test_populate_popular_projects_and_registrations.py
- tests/webtest_tests.py
- website/discovery/views.py
An addendum to https://github.com/CenterForOpenScience/osf.io/pull/6394 -- if `settings.NEW_AND_NOTEWORTHY_LINKS_NODE`, `settings.POPULAR_LINKS_NODE` or `settings.POPULAR_LINKS_REGISTRATIONS` weren't set properly, the page at `explore/activity/` wouldn't load at all.
Fix that!
- Catch errors that the nodes specified in settings did't work as planned
- Add tests for the missing settings
- Page should load on staging now...
https://openscience.atlassian.net/browse/OSF-7021
> Ensure discovery page loads with no popular node settings [#OSF-7021]

- tests/framework_tests/test_routing.py
- tests/test_views.py
- website/routes.py
- website/templates/base.mako
- website/templates/home.mako
- website/views.py
- Moves all of the logic from #6351 from `get_globals()` in routes.py to the dashboard view so that every request does not have to undergo the expensive query to find the institutions that should be displayed on the dashboard (as [pointed out](https://github.com/CenterForOpenScience/osf.io/pull/6351/files#r85000979) by @sloria).
- None expected, everything should still function as described in #6351 
- [OSF-6980](https://openscience.atlassian.net/browse/OSF-6980)
> [feature-fix] Move dashboard_institutions to Dashboard View [OSF-6980]

- scripts/populate_institutions.py
A quick fix of `logoutUrl` for UCSD on test environment. It should be "https://test.osf.io/goodbye" instead of "https://osf.io/goodbye".
```
'logout_url': SHIBBOLETH_SP_LOGOUT.format(encode_uri_component('https://test.osf.io/goodbye'))
```
No need to test for now.
No
No
> [Fix] Fix ucsd logout url on test environment [No Ticket]

- website/static/js/filepage/editor.js
Reworks my previous changes to [OSF-6883]
Instead of doing a check if created, this extracts the ajax call into a separate object. The FileEditor then checks for a previous call if reload=false, or simply reloads if reload=true;
None known.
https://openscience.atlassian.net/browse/OSF-6883
[#OSF-6883]
Since this change has more of a chance of breaking things, the basic functionality of the file editor should be checked to ensure editing/saving/reverting works properly.
> [Feature Fix] Use promise to stop Editor ajax double call [OSF-6883]

- website/addons/wiki/templates/wiki_widget.mako
Additional development for [https://openscience.atlassian.net/browse/OSF-5781](https://openscience.atlassian.net/browse/OSF-5781). Changed scrollbar to hide when not needed.
Before:
The scrollbar (circled in magenta) is visible when it doesn't need to be.
After:
The scrollbar is no longer visible when not needed.
Set ```overflow-y``` to ```auto```.
None visible.
[https://openscience.atlassian.net/browse/OSF-5781](https://openscience.atlassian.net/browse/OSF-5781)
> Update Wiki Preview Length [OSF-5781]

- scripts/populate_popular_projects_and_registrations.py
- website/project/utils.py
- website/settings/defaults.py
The previous code to grab popular nodes from keen for processing was limited by the fact that it was running every time the view was accessed, and so only grabbed a limited number of results from the recent keen results. It was also relying on a combination of unique views and total views, which we can leave out to make things simpler (since we're not displaying unique views for the time being). 
Since this script will now be run once a day, it can be a bit more intensive and actually sort through the keen results. 
- Get popular nodes and registrations from all keen results in last 7 days
- Only rely on unique view count for popularity
- Add a setting for number of registrations and projects to show
- Add better logging so you know if it isn't actually updating any node links.
- Script …
> Improve popular node gathering script [OSF-7021]

- api/base/settings/defaults.py
- framework/transactions/handlers.py
- tests/test_views.py
Make views atomic in the Flask app.
django.db.transaction.atomic() provides high-level interface for
starting, rolling back, and committing transactions. It can only
be used as either a decorator or context manager, so I call
__enter__ and __exit__
> [djangosf] Modify transaction handlers for djangosf compat

- api/files/permissions.py
- api/files/serializers.py
- api/files/views.py
- api_tests/users/views/test_user_nodes_list.py
- website/addons/osfstorage/tests/test_models.py
- website/addons/osfstorage/tests/test_views.py
- website/addons/osfstorage/views.py
- website/files/exceptions.py
- website/files/models/osfstorage.py
- website/static/js/fangorn.js
- website/static/js/filepage/index.js
- website/static/js/projectSettings.js
Prevent the deletion of preprints (or making it an orphan preprint) by not allowing the primary file of preprints to be deleted or moved to another folder, component or addon.
Remove all the preprint related file operation warnings. As a replacement, when such actions fail, a growl message informs the user that such action is prohibited due to preprint status.
Preprint files can no longer be moved into folders or deleted, from apiV2 or the OSF web client.
https://openscience.atlassian.net/browse/OSF-7156
> Block preprint file deletion or move, remove warnings [OSF-7156]

- addons/box/tests/test_client.py
- addons/box/tests/test_serializer.py
- addons/box/tests/test_views.py
- addons/box/tests/utils.py
Port Box's `test_(client|serializer|views).py` to Django OSF
None expected
> [djangosf] Add remaining Box tests

- addons/base/apps.py
- addons/osfstorage/apps.py
- api/nodes/permissions.py
- api_tests/nodes/views/test_node_addons.py
- api_tests/users/views/test_user_addons.py
- tests/base.py
Fix `test_(node|user)_addons` tests
* Fix bug causing OSFStorage to not be added to nodes
* Use correct models when checking permissions in the API
* Update tests
We should probably get the test suite running more quickly
```
~/D/osf.io ❯ DJANGO_SETTINGS_MODULE=api.base.settings py.test api_tests/nodes/views/test_node_addons.py api_tests/users/views/test_user_addons.py -s
.......................................................................................................................................................................................................................................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.sssss.ss.sssssss..ssssssssssssss.ssssssss.sssssss..ssssssssssssss.ssssssss.sssssss..ssss.sssssssss.sssss.ss.sssssss.. …
```
> [djangosf] Update addon API tests

- api/preprints/serializers.py
- api/preprints/views.py
- api_tests/preprints/views/test_preprint_detail.py
- website/preprints/model.py
You may no longer entirely change the primary file of a preprint, only update the version by directly dealing with the file stored on the node. Therefore, don't let the API change the primary file of the preprint either!
- Update preprint detail docstring
- Raise validation error in serializer if the preprint file is updated
- Update test
QA Automated runscope tests trying to update preprint files might fail if there are any!
https://openscience.atlassian.net/browse/OSF-7190
> Disallow changing primary preprint file after publishing [#OSF-7190]

- api/base/settings/defaults.py
- api/base/throttling.py
- Previously, **all** requests were contributing to the throttle counts of our custom throttle classes, not just the undesired ones. This PR overrides `allow_request` in each throttle class so that only the bad requests are processed further by `BaseThrottle.allow_request()` and added to the request history.  
- Also, the throttle rate for adding contributors somehow became 10 requests/hour (probably my bad), it's back to 10 requests/second now. 
- Better throttling. 
- [OSF-7189](https://openscience.atlassian.net/browse/OSF-7189)
> [hotfix] Fix Custom Throttle Classes [OSF-7189]

- website/static/js/filepage/index.js
- website/static/js/filepage/revisions.js
- Currently, when toggling between the `view` and `revisions` panels on the file view page, information about the `view_only` query parameter, if present, is lost. This PR retains the `view_only` query parameter when toggling so that if present, contributor names can be anonymized in the revisions table. 
- *note the URL changes and the contributor name in the revisions table, ignore the fact that I don't have MFR running*
- File View Page (w/o an anonymous VOL)
- File View Page (w/ an anoymous VOL) **BEFORE**
- File View Page (w/ an anoymous VOL) **AFTER**
- [OSF-7191](https://openscience.atlassian.net/browse/OSF-7191)
> [hotfix] Fix File Revisions Table w Anonymous VOL [OSF-7191]

- framework/auth/cas.py
- tests/test_cas_authentication.py
- Handle unicode names in CAS. 
- Makes [`fullname`](https://github.com/caseyrollins/osf.io/blob/c2814b34d4c608546ada118ddd7316f4f3ceb345/framework/auth/cas.py#L293) a unicode string.
- [OSF-7195](https://openscience.atlassian.net/browse/OSF-7195)
> [hotfix] Handle Unicode Names in CAS [OSF-7195]

- website/static/js/institutionProjectSettings.js
- website/static/js/osfHelpers.js
- website/static/js/tests/institutionsProjectSettings.test.js
- website/templates/project/project_base.mako
Currently only admins are given the dialogue option to add/remove affiliations to all nested components. This was a side effect of the data provided by the API V1 route used. Read/Write contributors are now given the add/remove all dialogue box.
1. Strip out api v1 functionality
2. Add 3 osf helper functions to get all paginated data, concat the data, and return all children of a node from a paginated response.
3. Using API v2 calls, allows read/write users to modify nested nodes.
The logic of when to show the modal (add/remove from node or node and all children) was simplified to avoid some fun/edgy cases (e.g., extremely edgy case if a node has more than 10 institutions) and generally reduce complexity. Now, so long as the node you are on has at least one child, the modal will appear. …
> [Feature] Allow read/write to modify all nested affiliations [OSF-7105]

- website/static/css/pages/contributor-page.css
- website/templates/project/contributors.mako
VOL view on the contributors page nests very poorly. This flattens the nesting.
Nodes no longer nest in the list of associated nodes. Set to a static 100px width, trims overflow and adds ellipsis. 
Before:
After:
None known.
https://openscience.atlassian.net/browse/OSF-5507
[#OSF-5507]
1. Should show a flat list
2. Long titles should be truncated.
3. The modal that used to create a VOL should still indent properly (related code)
> [Feature] Fix VOL nesting [OSF-5507]

- website/addons/s3/static/s3NodeConfig.js
- Updates the Amazon s3 "learn more" link to point to the OSF guides instead of an external Amazon URL. 
- [OSF-7121](https://openscience.atlassian.net/browse/OSF-7121)
> [feature] Update s3 "Learn More" Link [OSF-7121]

- website/static/js/fangorn.js
When clicking file widget lines, if the item has not already been clicked, the toolbar will sometimes drop down mid drag, causing the event.target (what is highlighted by fangorn) and where the dropzone thinks the target is to be different.
Runs a mithril redraw on initializing a drag, which should populate the toolbar and get them in sync 
None known. There is a chance a similar problem can theoretically occur on load events, but I've never been able to replicate it that way.
[#OSF-6319]
https://openscience.atlassian.net/browse/OSF-6319
Make sure you cannot get the mouse and the event target it out of sync. Happy to demo this behavior for you as it can be difficult to replicate.
> [Feature] Redraw on dragstart to get fangorn in sync [OSF-6319]

- website/addons/base/__init__.py
Prevent error when deauthorizing addons
* Except possible `AttributeError`
None expected
Check with @icereval that this works on staging after being deployed
[[#OSF-7202]](https://openscience.atlassian.net/browse/OSF-7202)
> Prevent error when deauthorizing addons [OSF-7202]

- api/base/serializers.py
- api_tests/base/test_serializers.py
- api_tests/comments/views/test_comment_detail.py
Filters added to the query params by the `RelationshipSeralizer` were using the normal way to add arguments, with `filter` as the name and the entire filter as the value: `filter=[field_name]=example`. This is done using the `extend_querystring_params` function which adds query string params with `furl`. So, pass the right thing to `extend_querystring_params`, and make sure it works with multiple filters!
- Update `format_filters` method so that it returns a list of dicts with checked filter params, instead of a string with all the checked filters bundled together
- Add each of those checked filters to the url via `extend_querystring_params`
- Test to make sure adding multiple filters via the `RelationshipSerializer` looks as we expect
Any use of `format_filters` (couldn't find any …
> Filter URL serialization in Relationship Field [#OSF-7194]

- scripts/refresh_addon_tokens.py
- website/addons/box/settings/defaults.py
- website/addons/googledrive/settings/defaults.py
- website/addons/mendeley/settings/defaults.py
- website/oauth/models/__init__.py
- website/settings/defaults.py
Apply this diff before the first run, as `date_last_refreshed` won't be populated initially:
```
diff --git a/scripts/refresh_addon_tokens.py b/scripts/refresh_addon_tokens.py
index 1c3bdc7..3c34ee8 100644
--- a/scripts/refresh_addon_tokens.py
+++ b/scripts/refresh_addon_tokens.py
@@ -36,7 +36,7 @@ def get_targets(delta, addon_short_name):
return ExternalAccount.find(
-        Q('date_last_refreshed', 'lt', datetime.datetime.utcnow() - delta) &
+        # Q('date_last_refreshed', 'lt', datetime.datetime.utcnow() - delta) &
Q('provider', 'eq', addon_short_name)
```
Then run, in a python shell:
```
In [1]: from scripts.refresh_addon_tokens import run_main
In [2]: run_main(addons={'box': 60, 'googledrive': 14, 'mendeley': 14}, dry_run=False)
``` …
> [Hotfix] Improve tracking of last refresh date

- tests/test_preprints.py
- website/preprints/tasks.py
Send bibliographic status to SHARE
* Send bibliographic status to SHARE
* Incidental: Fix `tags` bug
* Add test
To update existing SHARE data for preprints, run:
```
python -m scripts.migration.migrate_share_preprint_data
```
None expected
None known
> [Hotfix] Send bibliographic status to SHARE

- scripts/analytics/addon_snapshot.py
- scripts/analytics/base.py
- scripts/analytics/institution_summary.py
- scripts/analytics/node_summary.py
- scripts/analytics/run_keen_events.py
- scripts/analytics/user_domain_events.py
- scripts/analytics/user_summary.py
- scripts/tests/test_addon_snapshot.py
- scripts/tests/test_user_summary.py
- website/settings/defaults.py
We did a cool first round of sending stats to Keen, but let's make that more awesome by making it more closely match the other stats that we've been gathering regarding projects and nodes and addons and whatnot.
Here are what the new keen analytics events look like:
```
[
{
"date": "2016-11-13T09:21:13.988000+00:00",
"keen": {
"timestamp": "2016-11-13T09:21:13.988000+00:00"
},
"domain": "schuppe.com"
},
{
"date": "2016-11-13T09:21:13.988000+00:00",
"keen": {
"timestamp": "2016-11-13T09:21:13.988000+00:00"
},
"domain": "mail.com"
}
]
```
```
{
"users": {
"enabled": 5,
"authorized": 3,
"linked": 2
},
"nodes": {
"deleted": 0,
"total": 2,
"connected": 2,
"disconnected": 0
},
"provider": {
"name": "github"
}
}
```
```
{
"status": {
"active": 5,
"deactivated": 2,
"depth": 1,
"unconfirmed": 1
}, …
```
> Add more analytics to Keen! [OSF-7206]

- api/preprint_providers/views.py
- api/preprints/views.py
- Updates the API documentation for the `/preprints/` and `/preprint_providers/` endpoints to match their most recent implementation.
- Removes the "active development" warning for these endpoints. 
- [OSF-7203](https://openscience.atlassian.net/browse/OSF-7203)
> [feature] Update Preprint Documentation [OSF-7203]

- bower.json
- osf/models/institution.py
- scripts/populate_institutions.py
The banners for institutions were moved into a banners directory but those changes never made it into the Institution model in django-osf.
I added `'banners'` to a path and ran Django setup in the populate institutions script.
None expected.
https://trello.com/c/D0R7ZG8g/37-institutional-logos-not-rendering-loading-on-project-page
> Fix institution logo paths

- scripts/analytics/addon_snapshot.py
- scripts/tests/test_addon_snapshot.py
Staging was getting the following error when running the `addon_snapshot` analytics:
```
...
File "/code/scripts/analytics/run_keen_snapshots.py", line 18, in <module>
SnapshotHarness().main()
File "scripts/analytics/base.py", line 171, in main
events = class_instance.get_events()
File "scripts/analytics/addon_snapshot.py", line 85, in get_events
if not node_settings.owner.is_bookmark_collection:
AttributeError: 'NoneType' object has no attribute 'is_bookmark_collection'
```
So, check for an owner and also don't include those nodes if the owner doesn't exist
- Subtract from connected if there's no settings owner or if it's a bookmark collection
- Tests to make sure these scenarios work as expected
Nope
https://openscience.atlassian.net/browse/OSF-7206
> Update addon_snapshot analytics to handle no owner error [OSF-7206]

- website/project/model.py
Extends https://github.com/CenterForOpenScience/osf.io/commit/cf68848c0cba14288104186163d1f36d532b61b1
- Ensure permissions are checked whether adding a contrib or modifying perms for existing contrib
- Fix typo
None expected.
> [Hotfix] Check perms when changing contrib perms

- scripts/migration/migrate_meetings_preprints_to_preprintservices.py
Migrate submissions to "Tempory Homes" of preprint providers to `PreprintService` objects.
* Add mingration script
None expected.
[#PREP-100](https://openscience.atlassian.net/browse/PREP-100)
Should not require downtime.
```
python -m scripts.migration.migrate_meetings_preprints_to_preprintservices
```
As of 11/17, 656 of these nodes can be handled automatically with the `--auto [int (optional)]` arguments. 73 need to be specified manually with the `--targets [string]` argument. `[string]` is expected to be valid JSON is expected in the form
```
'{"data": [{"node_id": "asdfg", "file_id": "notarealfileid", "subjects":[["notarealsubjectid"]]}, {...}, ...]}'
```
* `--auto [int]` - Selects and migrates `[int]` number of (or all) targets that can be migrated automatically. 
* `--targets …
> OSF4M -> PreprintService Migration

- api_tests/preprints/views/test_preprint_detail.py
- website/project/licenses/__init__.py
- Removes the license year validation that was added in #6588. The `year` field on the `NodeLicense` model is a string field to allow for date ranges, but the additional date validation prevented that.
- Remove validation and related tests.
- Users will be able to enter any string as a license year. 
- [PREP-252](https://openscience.atlassian.net/browse/PREP-252)
> [feature-fix] Remove License Year Validation [PREP-252]

- api/preprints/serializers.py
- api_tests/preprints/views/test_preprint_list.py
- Prevent a preprint from being created if the node included in the request has been deleted.
- [OSF-7240](https://openscience.atlassian.net/browse/OSF-7240)
> Prevent Preprint Creation from Deleted Node [OSF-7240]

- website/static/js/pages/project-settings-page.js
- website/static/js/projectSettings.js
- Adds a warning when a user attempts to delete a node that contains a preprint.
- [OSF-7241](https://openscience.atlassian.net/browse/OSF-7241)
> [feature] Warn Users Before Deleting Node With Preprint [OSF-7241]

- tests/test_models.py
- tests/test_preprints.py
- website/preprints/model.py
- website/preprints/tasks.py
- website/project/tasks.py
- website/settings/defaults.py
* Update to use new SHARE format
* Move access_token from settings onto preprint providers
* PreprintProvider instances now require an access_token.
* Add SHARE API Key for Provider Services ( @chrisseto )
Took a couple tries:
```
[29/Nov/2016 21:17:45] "POST /api/v2/normalizeddata/ HTTP/1.1" 400 110
[29/Nov/2016 21:18:12] "POST /api/v2/normalizeddata/ HTTP/1.1" 400 251
[29/Nov/2016 21:20:44] "POST /api/v2/normalizeddata/ HTTP/1.1" 400 259
[29/Nov/2016 21:20:57] "POST /api/v2/normalizeddata/ HTTP/1.1" 400 249
[29/Nov/2016 21:21:13] "POST /api/v2/normalizeddata/ HTTP/1.1" 400 110
[29/Nov/2016 21:21:45] "POST /api/v2/normalizeddata/ HTTP/1.1" 400 256
[29/Nov/2016 21:22:11] "POST /api/v2/normalizeddata/ HTTP/1.1" 400 256
[29/Nov/2016 21:22:35] "POST /api/v2/normalizeddata/ HTTP/1.1" 400 110 …
```
> Update Preprint on save hooks [OSF-7242]

- api_tests/preprints/views/test_preprint_detail.py
- api_tests/preprints/views/test_preprint_list.py
- website/preprints/model.py
- website/static/js/logActionsList.json
- website/static/js/logTextParser.js
- Removes a broken (and duplicated) preprint log that was breaking both the "My Projects" page for users with a preprint, and the project overview page of projects with preprints. 
- Fixes the `preprint_license_updated` log to set correct log params.
- Removes the broken `preprint_initiated` log from `set_primary_file()` as it was being duplicated in `set_published()`
- [OSF-7245](https://openscience.atlassian.net/browse/OSF-7245)
> [feature] Fix Preprint Logs [OSF-7245]

- scripts/analytics/addon_snapshot.py
- scripts/analytics/base.py
- scripts/analytics/node_log_events.py
- scripts/analytics/run_keen_events.py
- scripts/analytics/run_keen_snapshots.py
- scripts/analytics/run_keen_summaries.py
- scripts/analytics/user_domain_events.py
- scripts/analytics/user_summary.py
On production, very large queries were making the summary keen statistics fail with mongo cursor errors. Also the celery tasks weren't functioning properly.
- Use pagination instead of direct queries for statistics
- Update main function of stats to be called via command line or celery task
- Pass in correct args to celery task
https://openscience.atlassian.net/browse/OSF-7234
> Keen analytics cursor error/fix celery tasks [OSF-7234]

- framework/auth/campaigns.py
Fix a bug introduced by [OSF-7217], where OSF preprints campaign url is incorrectly set to `/preprints/osf`. The correct one should be `/preprints/`.
No
No
https://openscience.atlassian.net/browse/OSF-7252
> [Fix] Fix OSF Preprints Campaign URL [OSF-7252]

- api/nodes/views.py
- api_tests/nodes/views/test_node_citations.py
- The node citations endpoints for private projects are accessible through unauthenticated requests, revealing the list of contributors for a private project. This PR fixes that, and adds tests for both endpoints which were previously untested.
- Permissions check and tests added to node citations endpoints:
- `NodeCitationDetail`, `/v2/nodes/<node_id>/citation/`
- `NodeCitationStyleDetail`, `/v2/nodes/<node_id>/citation/<style_id>/`
- [OSF-7254](https://openscience.atlassian.net/browse/OSF-7254)
> [fix] Check permissions for node citation endpoints [OSF-7254]

- scripts/migration/migrate_googledoc_paths.py
The upcoming WaterButler v0.29 release will include changes to the googledrive provider to start appending extensions to the paths of Google Doc files.  Current behavior is to save the path without an extension, meaning if a directory `foo` contains a GDoc and a GSheet that are both named `Survey`, the path `/foo/Survey` would apply to both.  This can cause registration failures.  The fix is to disambiguate this by appending an appropriate extension to each path e.g. `/foo/Survey.gdoc` & `/foo/Survey.gsheet`.
Existing StoredFileNodes and TrashedFileNodes will need to be updated to use this new convention, or else they will appear to be orphaned when doing metadata updates.  This script searches the `*FileNode`
collections and appends the appropriate extension when the most recent metadata …
> [CR] add migration script to correct gdoc paths [OSF-7247]

- website/addons/s3/static/settings.json
- website/addons/s3/tests/test_view.py
Relies on https://github.com/felliott/boto/pull/1 or something similar!
Ohio and Mumbai were new region options for amazon s3 buckets, but not available to select via creation on the OSF - a [PR to waterbutler](https://github.com/felliott/boto/pull/1) adds support for new regions with V4 Authentication, and so these regions should be available to create buckets in now. 
- Add ohio and mumbai to list of bucket locations
You should now be able to attach buckets created via the Amazon s3 console located in Ohio and Mumbai to an OSF project, and create a bucket located in Ohio or Mumbai via the OSF project settings page, but only after waterbutler has been updated with aboved linked PR!
https://openscience.atlassian.net/browse/OSF-7140 …
> Add Ohio and Mumbai to list of s3 buckets [OSF-7140]

- admin/metrics/urls.py
- admin/metrics/views.py
- admin/static/js/metrics/metrics.js
- admin/templates/base.html
- admin/templates/metrics/osf_metrics.html
- admin/webpack.admin.config.js
- admin_tests/metrics/test_utils.py
- scripts/analytics/base.py
Analytics in the OSF Admin have not been updating. Let's change that over to Keen!
- Remove old CSV rendering routes and views
- Now render results from keen collections in javascript
- Fix calling snapshot analytics from command line
Metrics added:
- Yesterday's Active Users
- Active Users Over Time
- Affiliated Public projects by Institution
- Affiliated Private projects by Institution
- Previous 7 days of user registrations by email domain
- Yesterday's Node logs by user
- Previous 7 days of users by status
- Previous 7 days of linked addon by addon name
- Correct keen API keys will need to be added in `local.py` if they're not there already
https://openscience.atlassian.net/browse/OSF-7085
> Add some Keen analytics in the OSF Admin! [OSF-7085]

- website/views.py
Sentry had been getting errors when someone attempted to access a guid url that was attached to an old `OsfStorageGuidFile` object. 
- Catch this particular `KeyError` and return 404 Not Found instead.
https://openscience.atlassian.net/browse/OSF-7146
> Catch key error for accessing old OSFStorageGuidFile objects [OSF-7146]

- scripts/analytics/user_summary.py
Piggy-backing off of #6562, this adds the number of users with edited profiles to the list of tracked items.
- Also include if a user has edited their profile in user summary counts
Old events gathered won't have it, but that's ok!
Adding final part of:
https://openscience.atlassian.net/browse/OSF-7085
> Add profile edited count to user summary script [OSF-7085]

- scripts/analytics/user_domain_events.py
Skip all the bad datas when we try to script from database for the analytics data since actually there should be no registered user without username in prod database.
Nothing to be tested by QA. After this fix, the bug report in the ticket when you run the script for analytic should be gone.
https://openscience.atlassian.net/browse/OSF-7244
> [#OSF-7244]Fix attribute error splitting username in None for analytics task

- scripts/analytics/migrate_analytics.py
- scripts/tests/test_addon_snapshot.py
- scripts/tests/test_migrate_analytics.py
Command line tool for Keen analytics that shouldn't need to be run very often, but can update Keen from the daily users spreadsheet, or smooth out event data from a given collection, or transfer between collections if they have the same schema.
Examples:
* Transfer all events from the 'institution_analytics' to the 'institution_summary' collection as a dry run:
- `python -m scripts.analytics.migrate_analytics -d -t -sc institution_analytics -dc institution_summary`
* Fill in the gaps in analytics for the 'addon_snapshot' collection between 2016-11-01 and 2016-11-15:
- `python -m scripts.analytics.migrate_analytics -sm -sc addon_snapshot -s 2016-11-01 -e 2016-11-15`
* Reverse the above action by adding -r:
-  `python -m scripts.analytics.migrate_analytics -sm -sc addon_snapshot -s …
> Script to Backfill, Smooth, or Transfer Keen Data [OSF-7223]

- api/preprint_providers/serializers.py
- scripts/populate_preprint_providers.py
- website/preprints/model.py
Adds links for the providers to a example for their particular brand
* Updates model and serializer for PreprintProvider
* Updates populate_preprint_providers script
N/A
https://openscience.atlassian.net/browse/PREP-284
Links will only work on prod. Please only verify that they're using the correct GUID.
Need to run populate_preprint_providers script after the the merge
> Add example links for Preprint Providers [PREP-284]

- api/logs/serializers.py
- api_tests/nodes/views/test_node_detail.py
- api_tests/preprints/views/test_preprint_detail.py
- scripts/remove_duplicate_preprint_logs.py
- website/preprints/model.py
- website/project/licenses/__init__.py
- website/project/model.py
- website/static/js/anonymousLogActionsList.json
- website/static/js/logActionsList.json
- website/static/js/logTextParser.js
- When editing a preprint, multiple PATCH requests are sent to the API, which results in duplicate `perprint_license_updated` logs being added to the preprint node.
- This PR prevents duplicate logs by checking that the update license record differs from the current license record before adding a log to the node. 
- Additionally, this PR updates the language of both node and preprint license logs to include the license that was applied (screenshots below).
- Adds a check to ensure a log is only added if the updated license record is different from the current license record. 
- Adds tests to ensure duplicate logs are not added.
- Adds a migration to remove the duplicate `preprint_license_updated` logs.
- Update `license_changed` and `preprint_license_updated` log language.
- Add `license` …
> [hotfix] Fix Duplicate Preprint Licensing Logs [OSF-7260]

- api/base/settings/defaults.py
- api_tests/base/test_middleware.py
- requirements.txt
- Upgrades [django-cors-headers](https://github.com/ottoyiu/django-cors-headers) (in hopes that it will resolve [OSF-7225](https://openscience.atlassian.net/browse/OSF-7225)).
- django-cors-headers version bumped from 1.1.0 to 1.3.1 (current)
- `CorsMiddleware` class moved up in defaults.py `MIDDLEWARE_CLASSES`
- Per https://github.com/ottoyiu/django-cors-headers#setup, "CorsMiddleware should be placed as high as possible, especially before any middleware that can generate responses such as Django's CommonMiddleware or Whitenoise's WhiteNoiseMiddleware. If it is not before, it will not be able to add the CORS headers to these responses."
- [OSF-7225](https://openscience.atlassian.net/browse/OSF-7225)
>  [feature] Upgrade django-cors-headers [OSF-7225]

- website/static/js/fangorn.js
- website/static/js/tests/fangorn.test.js
Files cannot be dragged-and-dropped from external providers to the Figshare root.  The reason is that there is old code that checks whether the root is public or private and is supposed to disallow drop if it's public.  However, the public/private flag was removed in the Figshare refactor.  It could be added back, but the Figshare V2 API now supports copying files to public projects.  Instead, remove the check altogether.
Removed the `isInvalidFigshareDrop` method from `fangorn.js` and `fangorn.test.js`
None expected.
[#OSF-7266] - [JIRA](https://openscience.atlassian.net/browse/OSF-7266)
> [CR] enable moving files into public Figshare in Fangorn [OSF-7266]
