api/base/filters.py, api/institutions/authentication.py, api/institutions/views.py, api_tests/institutions/views/test_institution_registrations_list.py, scripts/populate_institutions.py, website/institutions/model.py, website/mails/mails.py, website/project/model.py, website/project/views/node.py, website/search/elastic_search.py, website/search/search.py, website/templates/emails/new_public_project.html.mako, website/templates/emails/no_addon.html.mako, website/templates/emails/no_login.html.mako, website/templates/emails/welcome.html.mako, website/templates/emails/welcome_osf4i.html.mako, website/templates/emails/welcome_osf4m.html.mako, website/templates/institution.mako, website/templates/landing.mako, website/templates/project/project.mako, website/templates/project/settings.mako, website/templates/search.mako
Get OSF4I fixes from `release/0.68.0` into production for USC go-live
Combines the fixes from:
https://github.com/CenterForOpenScience/osf.io/pull/5501
https://github.com/CenterForOpenScience/osf.io/pull/5525
https://github.com/CenterForOpenScience/osf.io/pull/5540
https://github.com/CenterForOpenScience/osf.io/pull/5541
=> [hotfix] Institutions fixes cherry-picked from 0.68.0

website/addons/wiki/model.py
Reverts CenterForOpenScience/osf.io#5554
=> Revert "Add absolute_api_v2_url property to NodeWikiPage"

framework/auth/core.py, website/addons/base/__init__.py
`Q` faster when looking up Users by ExternalAccounts
* Index field
* Don't use regexes
None
=> [Hotfix] Faster User/ExternalAccount lookup [No Ticket]

website/static/js/logActionsList.json
To support the new log type in my Projects page
https://openscience.atlassian.net/browse/OSF-6147
=> Add prereg_registration_initiated log type to logActionList.json

website/static/js/nodeControl.js
https://openscience.atlassian.net/browse/OSF-6159
=> Remove bookmark from project page uses v2

admin/common_auth/views.py
Sorry not necessarily a hotfix. But for staging.
In place of #5612
=> [Fix] Correct redirect

website/static/js/comment.js, website/templates/include/comment_template.mako
https://openscience.atlassian.net/browse/OSF-5196
=> allow removed comments to be shown

website/addons/base/views.py, website/files/models/base.py
Fix the viewing of deleted files
Add missing keys to the file gone payload
=> Fix "Gone File" view

website/templates/base.mako
Hotfix for syntax error in keen tracking, that's breaking dashboard.
Added a comma.
Working dashboard.
no ticket, high priority issue reported in flowdock.
=> Fix JS syntax error in keen user tracking

website/static/js/signUp.js, website/templates/public/login.mako
Prevent registration of the same account multiple times.
Disable create account when the form is submitted
None
https://openscience.atlassian.net/browse/OSF-5816
[OSF-5816]
=> [RfR] Disable create account btn after submission [OSF-5816]

admin/common_auth/admin.py, admin/common_auth/models.py, admin/common_auth/views.py, admin_tests/common_auth/test_views.py, requirements.txt
To fix errors.
- Read-only field for `MyUser` admin.
- Replace new user registration form email with password reset form.
None
None.
=> [Feature] Admin fix MyUser & Registration

website/templates/include/profile/jobs.mako
Make language on employment page consistent
Department -> Department / Institute
None
https://openscience.atlassian.net/browse/OSF-5988
=> Make language on employment page consistent [OSF-5988]

scripts/migration/migrate_registration_extra.py, scripts/migration/migrate_registration_extra_drafts.py, scripts/tests/test_migrate_registration_extra.py, scripts/tests/test_migrate_registration_extra_drafts.py
Fix file representations that were causing errors with the prereg form.
Update migration script so that they fit the template.
Shouldn't be any
https://openscience.atlassian.net/browse/OSF-6305
=> [hotfix] Fix prereg form rendering files [OSF-6305]

website/archiver/utils.py
Improper indentation in the `find_question` util was breaking things.
Fix the indentation
=> Indentation matters

api/caching/listeners.py, framework/analytics/__init__.py, framework/postcommit_tasks/handlers.py, website/project/views/comment.py
@icereval and @cwisecarver noticed a `RuntimeError: Working outside of request context` errors in our server logs. The postcommit_handlers code is apparently running after Flask's request context is torn down.
Reverts #5652
=> [hotfix] Revert #5652

admin/README.md, admin/common_auth/views.py
Update the docs. And make sure it works.
- Update docs so they match the current prereg process
- Add `osf_user.save()` so that the above process actually updates `system_tags`
Better reading, better doing.
None
=> [Feature] Update admin prereg docs

website/static/css/pages/contributor-page.css, website/static/css/pages/profile-page.css, website/templates/include/profile/jobs.mako, website/templates/include/profile/schools.mako
make labels on profile Education and Employment cards bold
creates new css class
None
https://openscience.atlassian.net/browse/OSF-6302
=> bolds labels on profile page [OSF-6302]

website/static/css/pages/project-page.css, website/static/templates/license-picker.html
Fix for License text does not wrap in Firefox and Chrome
Added support for Chrome, Firefox and Opera.
None
https://openscience.atlassian.net/browse/OSF-6383
=> [OSF-6383] Fix for text wrapping

api/base/filters.py, api/base/urls.py, api/licenses/serializers.py, api/licenses/urls.py, api/licenses/views.py, api/nodes/serializers.py, api/nodes/views.py, api/registrations/serializers.py, api/registrations/views.py, api_tests/licenses/views/test_license_detail.py, api_tests/licenses/views/test_license_list.py, api_tests/nodes/views/test_node_detail.py, framework/auth/oauth_scopes.py, website/project/licenses/__init__.py
Allow users of the v2 API to access license information for a node and details about available licenses. (Read only)
1. Added `/v2/licenses/` and `/v2/licenses/[license-id]` routes to show the licenses available to the user
2. Added a license relationship to the node serializer that would link to the above licenses
3. Added node_license attribute to the node serializer that would give year and copyright holder information related to the attached license
4. Ensured that withdrawn registrations do not serialize license information
5. Ensure that the license relationship can be viewed with anonymized VOL but not the node_license data
6. Allow default query on ODM Filter Views to be `None`
7. Add license read scope
8. Documentation and tests …
=> Allow users to read license information on a node [OSF-6292]

website/templates/project/settings.mako
Prevent add institution from showing if the user does not have permission to do so.
https://openscience.atlassian.net/browse/OSF-6399
=> Fix 'Add institution' showing when user is not admin

website/static/js/pages/project-dashboard-page.js
Logo was a little too close to the title
=> add marginRight so that logo is not touchng the node's title

website/templates/search.mako
Prevent error from being thrown when affiliatedInstitutions is null
Checks if affiliated institutions exist before attempting to check their length ko side
=> Prevent error from being thrown when affiliatedInstitutions is null

scripts/populate_conferences.py
Add HEPA Annual Meeting 2016 to OSF4M.
=> Add HEPA Annual Meeting 2016

scripts/populate_conferences.py
Add a meeting for Open Global Health on OSF4M.
Added the info. for OGH.
None.
I have added a meeting. Thank you!
=> Add Open Global Health to OSF4M

scripts/populate_conferences.py
Change APS onference name on OSF4M to be consistent with past APS conference OSF4m pages
change 'name' field for APS2016
=> Update APS conference 'name' field

website/project/views/node.py, website/templates/project/project_header.mako
Allow all registrations to be cancelled including ones with an embargo.
- Added the button to the project header page
- Added the disapproval link to the project registration file
Before:
After:
N/A
https://openscience.atlassian.net/browse/OSF-6145
=> [Feature] Add cancel button for embargoed registrations. [OSF-6145]

scripts/populate_conferences.py
Add `dev` option to conferences so `python -m scripts.populate_conferences dev` can be run. This allows for a non-production environment to ignore non-existent emails.
Please run!
=> [Feature] Add  dev option to populate conferences

website/static/js/institutionProjectSettings.js
Related to https://github.com/CenterForOpenScience/osf.io/pull/5726
Modify the language to deal with childless node warnings and fix a typo.
https://openscience.atlassian.net/browse/OSF-6165
=> add language for childless nodes and fix typo

website/templates/public/pages/faq.mako
=> hotfix: update FAQ - encryption

website/static/js/addProjectPlugin.js, website/static/js/components/institution.js
=> Change check mark to opacity toggle on create node with institution

website/templates/public/pages/faq.mako
Add FAQ about how to report security issues
added new FAQ
none
https://openscience.atlassian.net/browse/OSF-6415
=> HOTFIX: Add FAQ about how to report security issues

website/static/js/myProjects.js
To give users instruction on how registrations work if they have not yet registered yet.
Added a hyperlink to the My Projects page for empty registrations.
On a local machine, the hyperlink takes the user to http://localhost:5000/myprojects/help.osf.io/#registrations rather than just help.osf.io/#registrations. I was not sure how to test this on my local machine; however, the hyperlink in the pull request is correct. 
https://openscience.atlassian.net/browse/OSF-6037
=> Added hyperlink to wiki page for creating registrations [OSF-6037]

framework/celery_tasks/handlers.py, framework/postcommit_tasks/handlers.py, tests/factories.py, tests/test_models.py, website/archiver/tasks.py, website/settings/defaults.py, website/settings/local-travis.py
Includes #5814 with test fixes.
=> [hotfix] Make celery ignore results

.dockerignore, Dockerfile, tasks/__init__.py, website/settings/__init__.py
Docker compatibility
N/A
N/A
N/A
=> Docker Build Nuances

website/addons/figshare/views/hgrid.py
Piggybacking off of #5827, this also adds the view_only kwarg to the hgrid builder for figshare (missed that one, oops)
- pass along ```private_key``` to figshare hgid builder
-nope
https://openscience.atlassian.net/browse/OSF-6449
=> Anon Only Link bugfix - also prevent folders shown in figshare [#OSF-6449]

website/templates/util/render_nodes.mako
- Fixes broken component sorting on the project overview page.
- [OSF-6424](https://openscience.atlassian.net/browse/OSF-6424)
=> [hotfix] Fix Reorder Components

website/static/js/registrationModal.js, website/static/js/tests/registrationModal.test.js
Fix on old bug. Now cannot make embargos in the past, if the user changes the time.
Checks the current date when the page is loaded and compares chosen time to the minimum date of the date when the registration was opened.
=> [OSF-4304]

website/static/js/myProjects.js
Update link to go to registrations page
Change wrong link to OSF registration help page.
https://openscience.atlassian.net/browse/OSF-6037
=> Update link to registrations page

package.json, website/static/js/comment.js
[OSF-598](https://openscience.atlassian.net/browse/OSF-598)
Update comments to automatically recognize URLs 
Update package.json to require linkifyjs
Update website/static/js/comment.js update var CommentModel to utilize linkifyjs for URL recognition.
None
[#OSF-598]
=> [RFR][Feature][OSF-598]Utilize linkifyjs for URLifying comments

website/static/js/contribAdder.js, website/static/js/contribManager.js, website/static/js/contribRemover.js, website/static/js/tests/contributors.test.js, website/templates/project/modal_add_contributor.mako, website/templates/project/modal_remove_contributor.mako
To remove a bug where asynchronous knockout.js data-bind processing is too slow and results in a broken modal being displayed.
This is a problem that has been encountered before, and I used the same solution that's employed across OSF: using the helper method osfHelpers.applyBindings() instead of the default ko.applyBindings(). As per the usual implementation, I updated the modal content divs to also include the "scripted" class with which the osfHelpers applyBindings method interacts. These changes, both in theory and in all observations thus far, have fixed the bug, and have updated the code to be consistent with the rest of OSF.
Though not specified in a ticket, I found the same issue in the code for the Add Contributors modal, and updated it to use the osfHelpers implementation of …
=> Fix broken "remove contributor" modal caused by knockout async problems [OSF-6109]

website/project/metadata/aspredicted.json, website/project/metadata/schemas.py
Add schema for specific registration, AsPredicted Preregistration.
- Added a json file: `aspredicted.json`
- Added necessary info to `schemas.py`
Need to run `ensure_schemas` if not normally run in order to get the schema on the database.
Populates API and New Registrations Modal
All registration associated functionality should work as well.
https://openscience.atlassian.net/browse/OSF-5755
=> [Feature] Add AsPredicted metaschema [OSF-5755]

website/templates/public/pages/faq.mako
update FAQ on registration size limits
1 gb -> 5gb
fewer help desk emails
=> hotfix/ correct limit on storage on registrations

website/addons/forward/static/forwardWidget.js, website/addons/forward/views/config.py
Fix the external link behavior on registration.
Before this change, the block page redirect panel will pop up on registrations. 
After this change, the page will not be blocked and the redirect panel will not pop up.
The redirect widget will remain on the project overview.
https://openscience.atlassian.net/browse/OSF-6518
=> [#OSF-6518]fix the external link on registration

website/static/js/pages/dashboard-page.js
Update timezone and locale for users when they visit the myProjects page.
Use the user profile endpoint to update locale and timezone if they are different than the user's once they visit the my projects page
more accurate timezone and locale for our users
https://openscience.atlassian.net/browse/OSF-6538
=> Update timezone on myProject page

website/static/css/log-feed.css
- Added CSS class to guarantee that baby gravatars are shown in the log feed.
=> [feature fix] Log Feed Gravatar Size [OSF-5980]

website/static/js/addProjectPlugin.js, website/static/js/mithrilHelpers.js, website/static/js/pages/project-dashboard-page.js, website/static/js/tests/mithrilHelpers.test.js, website/templates/project/project.mako
Fix the weird `Add Component` button.
* add `unwrap` to mithrilHelpers
* add disabled placeholder button
Disabled button shows until mithril renders the actual button.
https://openscience.atlassian.net/browse/OSF-6443
=> Feature/create component dialogs better button [OSF-6443]

package.json, webpack.common.config.js, website/static/js/pages/base-page.js, website/static/js/pages/statistics-page.js
Update code in response to the deprecation of jquery.cookie in favor of js-cookie
Replaced all jquery.cookie code with js-cookie code and updated package.json and webpack.common.config.js for dependency changes
https://openscience.atlassian.net/browse/OSF-6481
=> #OSF-6481 Replace jquery.cookie with js-cookie

website/addons/dataverse/static/dataverseUserConfig.js, website/addons/s3/static/s3UserConfig.js, website/static/js/addonSettings.js
Change threshold for loading the caret.
Change from 140px to 150px
None
https://openscience.atlassian.net/browse/OSF-4265
=> OSF4265 Fix height for osfToggleHeight

api_tests/nodes/views/test_node_detail.py, tests/test_auth.py, tests/test_models.py, tests/test_views.py, website/project/model.py, website/project/views/contributor.py
Fixes failing tests introduced from last hotfix
Where permissions are being lowered for a user, ensure that there is an admin contributor on the project under test.
=> [hotfix] Fix failing tests

website/static/js/tests/registrationModal.test.js
Log `moment().utcOffset()` to aid in debugging [OSF-6447](https://openscience.atlassian.net/browse/OSF-6447).
Adds a log line during testing.
n/a
https://openscience.atlassian.net/browse/OSF-6447
=> Log the UTC offset to help debug OSF-6447

website/static/js/tests/registrationModal.test.js
While @whit537 is working on a fix, skip JS test that fails randomly
* skip test
None
[OSF-6663](https://openscience.atlassian.net/browse/OSF-6663)
=> Skip randomly-failing JS test [OSF-6663]

admin_tests/meetings/test_forms.py
Fixes the fact that a field wasn't added to the dummy data for testing.
- Added field to testing data.
=> Add new field to form test

website/static/js/search.js
Fix the problem that hit enter multiple times causes doubling of search results.
https://openscience.atlassian.net/browse/OSF-6633
=> [#OSF-6633]Search on prod: hitting enter multiple times causes doubling of search results

website/static/js/comment.js
Get all contributors and account for pagination.
* make function recursive
* sort by `_id`
* increase page size to 50
None
=> get all pages of contributors [OSF-5658]

website/static/js/filepage/index.js
Provide at mention functionality on file page.
* add inputSelector to options
None
=> add input selector to file page comment options [OSF-5658]

website/templates/public/pages/faq.mako
Add FAQ about accessing the API and about contributing to the OSF source code
Moar FAQs
More informed users
=> hotfix: update faq

website/templates/footer.mako, website/templates/public/pages/support.mako
To make the API more obvious to users, add link to API docs in footer and a link the API docs in help/support.
changes the static html in the page footer reflect suggestions.
https://openscience.atlassian.net/browse/OSF-6710
=> Make API and Open source more obvious to users [OSF-6710]

website/addons/forward/static/forwardWidget.js
Fix bug where there is some weird behavior in which your mouse cursor continues to show a loading icon for as long as the external link pop-up on a project title page is open
Overwrode default CSS in blockUI when displaying external link popup
None
https://openscience.atlassian.net/browse/OSF-6520
=> Fix unnecessary loading icon on external link popup [#OSF-6520]

website/addons/figshare/static/user-cfg.js, website/addons/figshare/templates/figshare_user_settings.mako, website/templates/profile/addon_permissions.mako, website/templates/profile/user_settings_default.mako
Add expand/collapse caret to fishare in user settings. Also made some cosmetic changes.
A line is added to user-cfg.js for figshare to make use it load for figshare. Also changed some mako files.
None
https://openscience.atlassian.net/browse/OSF-6641
=> Add Expand/Collapse caret for Figshare [OSF-6641]

website/addons/wiki/static/wikiPage.js, website/addons/wiki/templates/edit.mako, website/addons/wiki/templates/wiki_widget.mako, website/static/css/pages/project-page.css, website/static/css/pages/wiki-page.css, website/static/js/pages/project-dashboard-page.js
Fix the unwanted unrendered markdown on the wiki and project page.
Added CSS so the unwanted unrendered markdown is not displayed until it is rendered.
None
https://openscience.atlassian.net/browse/OSF-6361
=> Fix the display of unrendered markdown on wiki and project page [OSF-6361]

scripts/migrate_piwik/extract.py, scripts/migrate_piwik/transform_01.py
* Make long-running transformation step of piwik migration resumable.
* Document fields that were missing from production piwik.
None.  Code may not be needed, but it would be good to have in the repo history.
=> [hotfix] resumable piwik migration

scripts/migrate_piwik/transform_01.py
Make transform-01 of piwik migration gobble less memory by caching to sqlite instead of memory
=> [hotfix] cache locations,users,nodes in piwik transform

admin/pre_reg/views.py, admin_tests/pre_reg/test_views.py
This fixes three issues from the previous PR:
- files not loading from misplaced guid
- generating a guid for older files
- and taking care of the special case of `q26` which is different from all of the rest.
- Add checking and different ways to handle file questions
- Add tests
https://openscience.atlassian.net/browse/OSF-6411
- Also add tests
=> [Feature] Fix guid issue and q26 [OSF-6411]

website/addons/github/static/githubFangornConfig.js
Fix the delete folder pop test for github is different from other addons.
https://openscience.atlassian.net/browse/OSF-6420
=> GitHub: modal message inconsistent for folder deletion[#OSF-6420]

website/templates/share_search.mako
Resolves https://github.com/CenterForOpenScience/SHARE/issues/338
=> [Hotfix] Add a note about SHARE v2

website/addons/github/static/githubFangornConfig.js
Dismiss the delete alert modal after hit delete for github folder and file deletion.
https://openscience.atlassian.net/browse/OSF-6420
=> [#OSF-6420]now delete folder will dismiss the delete alert correctly

admin/pre_reg/views.py, admin_tests/pre_reg/test_views.py
To make the errors useable by the admins.
Added question title to error message to facilitate communication with user who submitted file and has since changed it.
https://openscience.atlassian.net/browse/OSF-6411
=> [Feature] Add better error message for admin user [OSF-6411]

website/routes.py, website/settings/defaults.py, website/settings/local-dist.py
external ember app & configuration to support local development via simple reverse proxy
h/t @abought
=> [feature] external ember app [#PREP-87]

website/addons/base/views.py, website/static/js/filepage/index.js
Save when retrieving or creating guid.
=> [Feature] Attempt to fix prereg checkout by saving during api call [OSF-6411]

website/addons/base/views.py, website/static/js/filepage/index.js
Add in appropriate header to Ajax call.
=> [Feature] Attempt to fix checkout with better headers [OSF-6411]

website/addons/base/views.py
=> [Feature] Add file save [OSF-6411]

package.json
The treebeard source was changed to fix a bug where you couldn't shift-click and select multiple files if you scrolled.
Changed the treebeard version that was being imported. Simple.
The fact that this would not merge without a pull from develop is notable and could indicate an even newer version of treebeard.
https://openscience.atlassian.net/browse/OSF-6565
=> Treebeard update SHA [OSF-6565] 

tests/test_prereg.py, website/static/js/pages/login-page.js, website/static/js/passwordForms.js, website/static/js/registrationUtils.js, website/templates/erpc_landing_info.mako, website/templates/project/register_draft.mako, website/templates/public/login.mako
Fix bugs found during QA
* Update link
* Disable "Register" button if required fields are absent
"Register" button will be disabled if required fields are absent on Veer or AsPredicted preregistrations as well.
[#OSF-6578](https://openscience.atlassian.net/browse/OSF-6578)
=> [Hotfix] ERPC/Registration bugs [#OSF-6578]

admin/templates/pre_reg/draft_form.html
Disable the "Save" button after it is clicked to prevent multi click duplicate more than one pending registration. 
Now after the button clicked and if the respond is slow, you will see the button text changed to "Sending. Please wait" and the button is diabled
https://openscience.atlassian.net/browse/OSF-6845
=> Prereg admin should not be able to approve registrations more than once[#OSF-6845]

api/institutions/serializers.py, api/institutions/views.py, api/nodes/permissions.py, api/nodes/serializers.py, api/nodes/views.py, api_tests/institutions/views/test_institution_relationship_nodes.py, api_tests/nodes/views/test_node_relationship_institutions.py, website/templates/project/settings.mako
- This PR allows read + write contributors to add their affiliation to a project.
- R+W contributors can add and remove their own affiliations.
- R+W contributors cannot add or remove admin affiliations.
- Admins can remove, but not add, r+w contributor affiliations.
- Read only contributors can do nothing. 
- API
- Changed the ```/nodes/<node-id>/relationships/institutions/``` and ```/institutions/<inst-id>/relationships/nodes/``` routes to allow r+w contributors to appropriately create, edit, and delete node-institution relationships.
- Front-end
- Changed the ```project/settings.mako``` template to display add/remove buttons to r+w contributors for their affiliations.
- [OSF-6649](https://openscience.atlassian.net/browse/OSF-6649)
- Kanye West (admin affiliated with …
=> Allow R+W Contributors to Add Affiliations [OSF-6649]

api/base/exceptions.py, api/base/urls.py, api/nodes/permissions.py, api/nodes/serializers.py, api/nodes/urls.py, api/nodes/views.py, api/registrations/serializers.py, api/registrations/urls.py, api/registrations/views.py, api/view_only_links/serializers.py, api/view_only_links/urls.py, api/view_only_links/views.py, api_tests/nodes/views/test_node_view_only_links_detail.py, api_tests/nodes/views/test_node_view_only_links_list.py, api_tests/view_only_links/views/test_view_only_link_detail.py, api_tests/view_only_links/views/test_view_only_link_nodes.py, framework/auth/oauth_scopes.py
- Allows view only links to be managed through the API. VOLs can be created, updated, and deleted via the ```/nodes/<node-id>/view_only_links/``` and ```/nodes/<node-id>/view_only_links/<link-id>/``` endpoints. Additionally, VOLs can be viewed via the base endpoint ```view_only_links/<link-id>/```.
- The nodes associated with a VOL are managed via the ```/view_only_links/<link-id>/relationships/nodes/``` endpoint in a similar fashion to how node/institution relationships are managed.
- VOLs can be filtered by their ```name```, ```anonymous```, and ```date_created``` attributes.
- The nodes associated with a VOL must all be part of the same project, however it is *not* necessary for a component's parent to be associated with a VOL before it can be associated.
- Added routes:
- …
=> Manage VOLs via API [OSF-6738] 

package.json
Change the dropzone to be based on commits instead of branch.
Have a updated custome version of dropzone rdy to go in. This pr should be merged after https://github.com/CenterForOpenScience/dropzone/pull/2 is merged.
https://openscience.atlassian.net/browse/OSF-6351
=> [#OSF-6351]change the dropzone route

website/templates/erpc_landing_info.mako, website/templates/prereg_landing_info.mako, website/templates/prereg_landing_page.mako
=> ERPC Landing Page [OSF-6896]

api/nodes/views.py
- Fix varnish failure by banning the node url after deleting a VOL.
=> [feature fix] Varnish Failure w/ VOLs API

api/preprints/views.py
=> Remove unused import for flake8

api/preprint_providers/serializers.py
Add a relationship to preprints in preprint provider
=> Updates from @chrisseto to help ember data

api_tests/nodes/views/test_node_contributors_list.py
- Remove a test that will randomly fail because of a 0.1 second throttle limit. 
This does not require any testing.
=> [feature] remove throttle test that will randomly fail

CHANGELOG
=> Update changelog of 0.89.0

website/static/js/fangorn.js
Add JIRA ticke to @mfraezz 's TODO
- add https://openscience.atlassian.net/browse/PREP-132
naw
https://openscience.atlassian.net/browse/PREP-132
=> Add JIRA link to preprint about breaking logic when components can be preprints

website/search/elastic_search.py
Make components include their descriptions in ES results. 
One line change in JS.
https://openscience.atlassian.net/browse/OSF-6332
=> Make component give description in ES results [OSF-6332]

api/base/pagination.py, api/taxonomies/views.py
Add no max size for taxonomy list endpoint
=> Allow taxonomy endpoint to take in any page size

package.json
- Update Treebeard to most recent [commit](https://github.com/CenterForOpenScience/treebeard/commit/87eb491dbe4adec3802fb5c592579f0b2588cf8b) to resolve [OSF-5825](https://openscience.atlassian.net/browse/OSF-5825)
- [OSF-5825](https://openscience.atlassian.net/browse/OSF-5825)
=> [feature] Update Treebeard [OSF-5825]

api/base/parsers.py, api_tests/nodes/views/test_node_comments_list.py, api_tests/nodes/views/test_node_contributors_list.py, api_tests/nodes/views/test_node_links_list.py
Reverts CenterForOpenScience/osf.io#6189
=> Revert "[feature] Validate Relationships Resource Key [OSF-5268]"

framework/auth/views.py
Please refer to relevant ticket for detailed information.
No
https://openscience.atlassian.net/browse/OSF-6972
https://openscience.atlassian.net/browse/SEC-50
=> Hotfix/LoginNextUrl [OSF-6972]

framework/auth/views.py
Fixes bug introduced in #6260 
* Prevent spurious email from being sent
None expected
=> [Hotfix] Prevent spurious email from being sent

api_tests/preprints/views/test_preprint_detail.py
Increase test coverage, minimize chances of regression
* Add tests
None
=> [Hotfix] Additional Preprints tests

website/static/js/registrationModal.js, website/static/js/registrationUtils.js, website/static/js/tests/registrationModal.test.js, website/static/templates/registration-modal.html, website/templates/project/registration_utils.mako
&larr; #5977 ([diff](https://github.com/whit537/osf.io/compare/debug-OSF-6447...refactor-registration-modal)) — #6050 &rarr;
I refactored the registration modal while debugging #5977. This PR contains some of the safer refactors.
n/a
n/a
https://openscience.atlassian.net/browse/OSF-6751
=> Lightly refactor registration modal

api/base/settings/defaults.py, api/base/settings/local-travis.py, api/base/throttling.py, api/base/views.py, api_tests/base/test_throttling.py
- Adds a custom throttle class to the root API view with a higher throttle rate for non-authenticated requests.
=> [feature fix] Adjust Base Route Throttle

CHANGELOG
=> Add changelog for 0.93.0

requirements.txt
Remove software with licenses that don't align.
Remove from requirements, didn't see any obvious uses.
https://openscience.atlassian.net/browse/OSF-7015
=> [Feature] Remove crontab [OSF-7015]

Dockerfile
Fix deployments
* update build requirements
=> Update Dockerfile with ownCloud requirements

CHANGELOG, package.json
Update the changelog and package.json for the 0.94.0 release
=> Update changelog and version for 0.94.0

Dockerfile, website/addons/owncloud/templates/owncloud_credentials_modal.mako, website/security.py
Updates to ownCloud discovered from testing.
* Ensure encryption in prod
* Security recommendations in UI
* Fix docker build
None
=> [Feature] ownCloud addon updates

api/base/pagination.py, api/base/urls.py, api/search/serializers.py, api/search/urls.py, api/search/views.py, api_tests/search/serializers/test_serializers.py, api_tests/search/views/test_views.py, framework/auth/oauth_scopes.py, website/search/elastic_search.py, website/search/search.py
- Adds several search endpoints to API v2. Each endpoint can accept a search query via query parameters, e.g. `/v2/search/projects/?q=science` will search for projects with the word science in their title, description, tags, etc. 
- `/v2/search/`
- searches across files, projects, components, registrations, and users.
- all of the items returned from this search should be serialized appropriately in a single response (users serialized as users, registrations serialized as registrations, etc.)
- Additionally, this endpoint includes a `search_fields` dictionary in the response which contains the appropriate links and counts of results for each doc type. 
- `/v2/search/files/`
- searches across components -- query parameters will search within a file's name. 
- `/v2/search/projects/`
- …
=> [feature] API Search [OSF-4254]

website/static/js/anonymousLogActionsList.json, website/static/js/logActionsList.json
Change preprint logs to say 'made' instead of 'inititated'
https://openscience.atlassian.net/browse/OSF-7046
=> Update preprint logs with new language [OSF-7046]

framework/analytics/__init__.py
=> Disable import that is killing our deployment.

requirements.txt, requirements/dev.txt
=> Move django requirements into base

osf_models_tests/factories.py, osf_models_tests/test_comment.py, osf_models_tests/test_guid.py
This adjusts a few tests to work with the new guid model. @sloria
It's partner PR is https://github.com/CenterForOpenScience/osf-models/pull/144
=> [RFR] Fixing Guid Tests

api/nodes/serializers.py, api_tests/nodes/views/test_node_list.py, website/project/model.py, website/project/views/node.py
Fix the problem that when you have a unregistered contributor in parent node you cannot create a component and inherit contributor from parent project.
Before fix:
1. create a project and add an unconfirmed contributor to the project
2. add a component to that project and inherit contributor from the project
3. you will see an error and the component is not successfully created
After fix:
1. create a project and add an unconfirmed contributor to the project
2. add a component to that project and inherit contributor from the project
3. there will be a normal pop up to ask you if you want to stay on the project or go to the component created
4. go to the component created. You should see all contributors from the parent project being successfully inherited including the unregistered …
=> [hotifx]Inheriting unclaimed users in new component seems not to work	[#OSF-7072]

CHANGELOG, package.json
There's a new release. Let's make sure people know that it's new and what's in it
1. Entries added to CHANGELOG
2. Version number increased in package.json
That would be super-impressive, but no.
https://openscience.atlassian.net/browse/OSF-7045
=> Update metadate for the 0.95.0 release [OSF-7045]

website/static/js/myProjects.js, website/static/js/project-organizer.js
Fixes to a ticket in 0.97 release for showing my preprints in My Projects. 
- Make preprints collection not droppable like other system collections
- Add nodetype to preprint DOM so the dragging to collections works 
NA
https://openscience.atlassian.net/browse/OSF-7032
=> Fixes to My preprints collection in My Projects page [OSF-7032]

addons/box/migrations/0001_initial.py, addons/osfstorage/migrations/0001_initial.py, addons/twofactor/migrations/0001_initial.py
Stop sentry errors
Update migrations to point to things that actually exist.
Less sentry errors.
=> [RFR] Fix osf.utils.base import error.

osf/models/user.py
Fix https://sentry.cos.io/sentry/osf-back-end/issues/256416/
Update django-osf user model to support sending renewal emails.
=> [RFR] Update email methods to support renew functionality.

framework/auth/core.py, osf/management/commands/migratedata.py, osf/management/commands/migraterelations.py, osf/models/analytics.py, website/conferences/utils.py
Updates migrations to work with new table naming scheme and moves missing changes from osf_models to osf.io.
Updates migrations with correct table names, move NodeRelation migration from osf_models repo to osf.io. Add necessary fields to analytics models for migration.
=> [RFR] Fix migrations after repo merge

website/project/views/node.py
User could not add a node link from the project dashboard
- Consolidate the converted MODM query into using some django excludes instead when searching for nodes to add as links
- Use correct `fullname` field of an `OSFUser` object
Nope
https://trello.com/c/8rLceO5i/19-components-widget-add-links-button-broken
=> Fix up node query and call for firstAuthor data for Django-OSF

api_tests/files/views/test_file_detail.py, api_tests/files/views/test_file_list.py, api_tests/preprints/views/test_preprint_list.py, api_tests/users/views/test_user_addons.py, tests/base.py
**note** WIP because waiting on updates to `osfstorage` and addons for all tests to pass
Update API tests for django-osf!
- Import some factories from the new django ones
- A few django queryset method updates
- 
https://github.com/CenterForOpenScience/osf-models/issues/133
=> [WIP] Update API Tests for Django OSF

website/static/js/project-organizer.js
Responding to request in the ticket to change the icon for the preprints if they are in all my preprints 
Added check to see if the view is in "All my preprints", if so the link of the project is to preprint view and the icon is text icon. 
None
https://openscience.atlassian.net/browse/OSF-7032
=> Add conditional for showing preprint link and icons only if under All my preprints collection [OSF-7032]

website/static/js/myProjects.js
Make language change in MyProjects when there are no preprints for user.
Language changed to: "You have not made any preprints yet. Learn more about preprints in the OSF Guides or make one now."
None
https://openscience.atlassian.net/browse/OSF-7032
=> Change language for when there are no preprints for the user [OSF-7032]

website/citations/providers.py
Should cut down on the number of iterations in a loop.
Filter in sql.
=> [RFR] Limit filtering to only things by the correct provider

CHANGELOG
Quick change of a description in the changelog
=> Update changelog for better description

website/static/js/projectSettings.js, website/static/js/tests/projectSettings.test.js
Settings page uses IE incompatible patch function.
Replace IE incompatible patch with $3 patch.
None known.
https://openscience.atlassian.net/browse/OSF-6157
Also fixes: https://openscience.atlassian.net/browse/OSF-6765
[#OSF-6157]
1. Test to make sure you can update the title, description, and category from the settings page. 
2. Test IE and another browser to confirm no side effects, though none are expected as this fix is used elsewhere.
=> [Feature] Use IE compatible patch [OSF-6157]

package.json
Current karma setup breaks local phantom runs.
Update karma relevant versions.
None known, works locally.
https://openscience.atlassian.net/browse/OSF-7109
=> [Feature] Update karma dependencies [OSF-7109]

website/static/js/project.js
Make javascript call compatible with Internet Explorer
Replace .replace method with native js.
None known, functionality should be exactly the same, minus error messages.
https://openscience.atlassian.net/browse/OSF-7094
[#OSF-7094]
1. No more "Object doesn't support property or method 'remove'" errors on settings page in IE.
=> [Feature] Remove remove and replace with standard js [OSF-7094]

scripts/populate_institutions.py
@sloria 
Fix institution logout url for UCSD on test environment.
```
'logout_url': SHIBBOLETH_SP_LOGOUT.format(encode_uri_component('https://test.osf.io/goodbye'))
```
No
=> [Fix] Fix institution logout url for UCSD Test [No Ticket]

.jshintrc, api/collections/serializers.py, framework/auth/__init__.py, framework/sessions/__init__.py, osf/models/base.py, osf/models/user.py, osf/utils/datetime_aware_jsonfield.py, osf_tests/requirements.txt, requirements/dev.txt, setup.cfg, tasks/__init__.py, website/files/utils.py, website/project/__init__.py
- Use pytest for running tests
- Fix lint errors
=> [djangosf] Modify travis test tasks

CHANGELOG, package.json
Update changelog and package.json for release
https://openscience.atlassian.net/browse/OSF-7113
=> Changelog and package.json for 0.98.0 release [OSF-7113]

website/preprints/tasks.py
=> [Hotfix] Improve on_preprint_updated

website/preprints/tasks.py
=> [hotfix] Add omitted SHARE update fields

scripts/migration/migrate_node_preprints_to_preprintservices.py
Correct small issues with original script
* Upsert documents that might not be there
* `.reload` to prevent saving stale data
* set `date_modified`
None.
=> [Hotfix] Preprint script fixes

api/addons/views.py, api/nodes/views.py, api/users/views.py, api_tests/nodes/views/test_node_addons.py, api_tests/users/views/test_user_addons.py
Fix tests
* Fix tests
* Add permissions checking
None expected
None known
=> [djangosf] Addon API Tests (Part 2)

api/files/permissions.py
Permissions overly restrictive on preprints
This allows checkouts to work again.
None known
[OSF-7157]
https://openscience.atlassian.net/browse/OSF-7157
=> [Feature-fix] Enable checkouts on Preprints [OSF-7157]

addons/osfstorage/models.py, api_tests/comments/views/test_comment_detail.py, api_tests/comments/views/test_comment_report_detail.py, api_tests/comments/views/test_comment_report_list.py, osf/models/base.py, osf/models/node.py
api_tests/comments/views
- Fix some tests that were improperly using models in place of their id
- Change clone method to null out (G)FK values
- Unskip file tests
- Use pk instead of fully hydrated models for speed!
If people are expecting (G)FK fields to be cloned along with the cloned object ... they'll be wrong. This mimics the behavior of modm.
=> [RFR] Comment API Tests

website/addons/dataverse/templates/dataverse_user_settings.mako, website/addons/owncloud/templates/owncloud_user_settings.mako, website/addons/s3/templates/s3_user_settings.mako, website/templates/profile/user_settings_default.mako
Custom addon settings pages do not put all TR tags in.
Add all the TR tags to fill the empty cells.
None
https://openscience.atlassian.net/browse/OSF-7112
[#OSF-7112]
=> [Feature] Fix Addon Settings TR tags [OSF-7112]

scripts/migration/migrate_osfstorageguidfile_trashedfilenodes.py
Update old `OSFStorageGuidFile` `Guids` to point to the correct referent
* Adapt code from @chrisseto into a migration
None expected
None known
=> [Hotfix] OSFStorageGuidFile/TrashedFileNode Migration

api_tests/nodes/views/test_node_comments_list.py, api_tests/preprints/views/test_preprint_detail.py, tasks/__init__.py
@sloria This should be RFR
https://github.com/CenterForOpenScience/osf-models/issues/133
Updated tests and code to reference things correctly in a new Django world.
- Node == NodeRelation
- Node == Collection
- node == node_relation.child
=> [RFR] Make API tests pass

website/static/js/fangorn.js
Private preprints were not getting the fangorn preprint UI because they are not marked as preprints.
Use a different method to check if a file is a preprint
None known.
[#OSF-7204]
https://openscience.atlassian.net/browse/OSF-7204
=> Private preprint fangorn ui [OSF-7204]

website/preprints/tasks.py
=> [Hotfix] Fix typo from #6552

website/templates/project/modal_add_pointer.mako, website/templates/project/project.mako, website/templates/public/pages/help/links.mako
Add links confuses people.
Renames `Add Links` to `Project Links`
Less confusion.
https://openscience.atlassian.net/browse/OSF-7112
[#OSF-7112]
=> [Feature] Rename add links [OSF-7112]

website/static/js/fangorn.js
Fix the typo error of the fix in https://openscience.atlassian.net/browse/OSF-6432#add-comment.
https://openscience.atlassian.net/browse/OSF-6432#add-comment
=> [OSF-6432][IE] Unable to view files in a VOL

addons/osfstorage/apps.py
https://trello.com/c/rRi3ZPz5/34-osf-storage-is-written-as-osfstorage-in-files-widget
=> Fix OSF Storage name bug

website/static/css/pages/registries-landing-page.css
Removes white space between footer and bottom banner.
Fix margin.
None.
[#OSF-7222]
https://openscience.atlassian.net/browse/OSF-7222
=> [Feature Fix] Update Registries CSS [OSF-7222]

website/settings/defaults.py
Analytics scripts were not imported properly for use in keen -- oops!
Let's import them!
These same things are temporarily in `local.py` for staging, should they be removed?
=> Import analytics scripts for celery tasks

CHANGELOG, package.json
=> Update metadata for release 0.101.0

framework/routing/__init__.py, framework/transactions/utils.py, manage.py, osf/models/external.py, tests/framework_tests/test_modular_templates.py, website/addons/badges/routes.py, website/addons/dataverse/routes.py, website/addons/forward/routes.py, website/addons/wiki/routes.py, website/routes.py
=> Move OsfWebRenderer to framework.routing

website/search/elastic_search.py
Eager connection was preventing the CI Dockefile build.
e.g.
```
export DJANGO_SETTINGS_MODULE=api.base.settings && python manage.py collectstatic --noinput --no-init-app
```
=> [feature] cached, lazy elastic search connection

scripts/migration/migrate_meetings_preprints_to_preprintservices.py
Improve error message when default subjects are not found
* Improve error message when default subjects are not found
* Improve default subject building
None
=> Improve Failure for Missing Subjects

scripts/tests/test_refresh_addon_tokens.py, website/addons/dataverse/templates/dataverse_user_settings.mako, website/addons/figshare/templates/figshare_user_settings.mako, website/addons/owncloud/templates/owncloud_user_settings.mako, website/addons/s3/templates/s3_user_settings.mako, website/static/js/addonSettings.js, website/templates/profile/user_settings_default.mako
Allow users to reauthorize existing accounts with bad creds
* Update UI (backend already worked
* Update related script tests
None
[OSF-7237](https://openscience.atlassian.net/browse/OSF-7237)
=> [Hotfeature]  UI components for external account reauthorization

scripts/migration/migrate_subjects_from_plos_to_bepress.py
* Update mapping
* Allow over-completeness
=> Update Subject mapping

website/preprints/model.py
Avoids redirect for branded preprints
Small change to the preprint model
N/A
https://openscience.atlassian.net/browse/PREP-250
=> Update url for branded preprints, fixes [PREP-250]

CHANGELOG, package.json
New release, new changes
Updated CHANGELOG and package.json
Nope
=> Update metadata about release 0.102.0

.travis.yml, addons/box/models.py, addons/dataverse/models.py, addons/dropbox/models.py, addons/forward/models.py, addons/github/models.py, addons/googledrive/models.py, addons/mendeley/models.py, addons/osfstorage/models.py, addons/owncloud/models.py, addons/s3/models.py, addons/twofactor/models.py, addons/wiki/models.py, addons/zotero/models.py, framework/auth/core.py, osf/management/commands/migratedata.py, osf/management/commands/migraterelations.py, osf/models/base.py, osf/models/external.py, osf/models/nodelog.py, osf/models/user.py, osf/utils/datetime_aware_jsonfield.py, osf/utils/order_apps.py, startover-make.sh, startover.sh, tasks/__init__.py, tests/test_registrations/test_archiver.py, website/addons/osfstorage/settings/defaults.py, website/addons/osfstorage/settings/staging.py, website/project/model.py
=> [WIP] Make migrations great again.

tests/test_preprints.py, website/preprints/tasks.py
Ensure there are is a date and at least empty list of subjects in the preprint data going to share
- Default values
- Tests
No
https://openscience.atlassian.net/browse/OSF-7249
=> Handle None values [OSF-7249]

website/project/model.py
- Handle both `copyrightHolders` and `copyright_holders` casing for node license update.
- [OSF-7250](https://openscience.atlassian.net/browse/OSF-7250)
=> Fix Broken APIv1 License Updates [OSF-7250]

scripts/migration/migrate_meetings_preprints_to_preprintservices.py
* Disable logging
* Exclude deleted nodes and nodes tagged with multiple providers
* Unset SHARE_URL to prevent `on_preprint_updated`
=> Migration updates: Logs, Targets, Settings

scripts/migration/migrate_meetings_preprints_to_preprintservices.py
=> [Hotfix] Update OSF4M->PreprintService script

tests/test_preprints.py, website/preprints/tasks.py
* The tag `qatest` now marks preprints as deleted
* `node.is_deleted` now marks preprints as deleted
???
=> SHARE Preprint fixes

website/static/js/logActionsList.json
- Fix malformed preprint logs. 
- [OSF-7260](https://openscience.atlassian.net/browse/OSF-7260)
=> [hotfix] Preprint Licensing and File Updated Logs [OSF-7260]

api/base/views.py, api/preprint_providers/views.py
=> [Hotfix] Document possible API instability

scripts/figshare/migrate_folder_logs.py, website/addons/figshare/model.py, website/addons/figshare/static/figshareAnonymousLogActionList.json, website/addons/figshare/static/figshareLogActionList.json, website/addons/figshare/tests/test_models.py, website/addons/figshare/tests/test_views.py
Fix logging issue missed in #6167 
* Update log action on folder selection
* Update anonymous log action
None expected
[#OSF-6394](https://openscience.atlassian.net/browse/OSF-6394)
=> Fix Figshare log action [OSF-6394]

api/base/settings/defaults.py, api_tests/base/test_middleware.py, requirements.txt
Reverts CenterForOpenScience/osf.io#6642
=> Revert " [feature] Upgrade django-cors-headers [OSF-7225]"

scripts/populate_preprint_providers.py
See #6636
engrXiv GUID points to project page instead of Preprint
https://openscience.atlassian.net/browse/PREP-284
=> Update GUID for engrXiv [PREP-284]

website/preprints/tasks.py, website/project/tasks.py
=> Remove verify=False

website/templates/base.mako
Update Google Analytics Linker on osf.io
Nothing to be tested by QA. It will be changing the analytics we get from google analytic.
https://openscience.atlassian.net/browse/OSF-4909
=> [#OSF-4909]Update Google Analytics Linker on osf.io

tests/test_auth.py, tests/test_campaigns.py, tests/test_preprints.py, website/util/time.py
* Fix `tests/test_preprints.py`
* Fix `tests/test_auth.py`
=> [django-osf] Test fixes

api/base/middleware.py
- Resolve intermittent CORs errors described in [OSF-7225](https://openscience.atlassian.net/browse/OSF-7225)
- Override `process_response()` in `CorsMiddleware`
- [OSF-7225](https://openscience.atlassian.net/browse/OSF-7225)
=> [feature] Fix CorsMiddleware Class [OSF-7225]

osf/models/user.py, tests/test_notifications.py, website/notifications/emails.py, website/notifications/utils.py
=> [djangosf] Fix test_notifications

CHANGELOG, package.json
Update metadata for 0.103.0
* Add lines to changelog
* Update version in package.json
Nope
=> Update metadata for 0.103.0

osf/models/base.py, osf/models/files.py, osf_tests/settings.py, osf_tests/test_comment.py, osf_tests/test_user.py, tests/test_addons.py, tests/test_views.py, website/project/views/comment.py
Fix more tests
* Fix two test classes in `test_comment`
* Skip other test classes in `test_comment` that were skipped in develop
* Fix some warnings that pytest complains about
None expected
=> [djangosf] test_comment.py fixes/skips

api/base/middleware.py
=> [feature-fix] CorsMiddleware [OSF-7225]

scripts/email_users_with_invalidated_externalaccounts.py
```
python -m scripts.email_users_with_invalidated_externalaccounts --dry
```
=> [Hotfix] Email users with invalid credentials

api_tests/preprints/views/test_preprint_citations.py, docker-compose.yml, tasks/__init__.py
=> Update docker-compose file to mount local mfr and waterbutler.

website/templates/footer.mako
Purpose:
-replaced donate link with the current service
Changes:
-old was giving library
-new is crowdrise
Side effects:
-none
Ticket:
-none
=> Update Donate link

website/templates/copyright.mako
update year on copyright
updates the year on the copyright 
2016 -> 2017
none
=> hotfix/ update year

osf/models/base.py
=> Remove errant Q

docker-compose.override.yml, docker-compose.yml, docker-sync.yml, tasks/__init__.py
=> docker-sync

api/users/views.py, docker-compose.override.yml, osf_tests/settings.py
Fixes: https://sentry.cos.io/sentry/osf-back-end/issues/256022/
=> Fix api user filtering

api/nodes/serializers.py
Tags are a model now, not just a ListField. This updates the node serializer to allow creation and update of nodes in the v2 API with get_or_create of tags.
=> Update node serializer to accept tags.

README-docker-compose.md
To help with finding logs on containers running in the background!
To help with finding logs on containers running in the background!
Add missing `logs` to docker command
Nope
=> Fix small typo on README-docker-compose

tests/test_node_licenses.py
I broke the tests: https://github.com/CenterForOpenScience/osf.io/pull/6721
I fixed the tests.
@icereval will be happy?
=> Fix node license tests

api/nodes/serializers.py, api/preprint_providers/views.py, api/registrations/serializers.py, api_tests/base/test_serializers.py, osf/models/node.py
Preprints are broke on djangosf
1. Switch len to count
2. Wrap queryset
3. Fix href generation to get _id instead of pk
4. Fix failing test because of pk fix
None yet.
[#OSF-7326]
https://openscience.atlassian.net/browse/OSF-7326
=> Fix preprints [OSF-7326]

requirements.txt
Sentry was complaining that we're using an outdated version of raven. 
Upgraded raven to the newest version.
n/a
=> Upgrade raven

scripts/register_oauth_scopes.py
@sloria 
Update scripts to populate `ApiOAuth2Scope`.
This is part of https://openscience.atlassian.net/browse/OSF-7332.
=> [Fix] Fix Scripts for Populating OAuth Scopes [#OSF-7332]

api/base/authentication/drf.py
This issue is caused by CAS returns `username` instead of `GUID` for OSF during PAT authentication. 
This is the second (and the last) part of https://openscience.atlassian.net/browse/OSF-7332.
=> [Fix] Fix Personal Access Token Authentication [#OSF-7332]

website/addons/base/__init__.py
Fix broken build from #6737 
See https://travis-ci.org/mfraezz/osf.io/builds/193223990
=> Pass LookupError to fix TCI build

osf/models/analytics.py
Self-explanatory
Compare strings to strings, not complex objects.
None expected
[#OSF-7360](https://openscience.atlassian.net/browse/OSF-7360)
=> Exclude contribs when incrementing download count [#OSF-7360]

api/base/wsgi.py, main.py, requirements.txt
The database is locking while trying to create a guid for a file outside of osfstorage.
- Add psycogreen
- Patch psycopg with psycogreen
- Upgrade gevent
- Comment gevent hack/fix that was said to be fixed by 1.1 version
Much more greens.
=> Fix database locking

osf/models/user.py
Add missing property, left off from modm User.
Added property.
None known of.
Fixes https://travis-ci.org/CenterForOpenScience/osf.io/jobs/193915259#L1634 @icereval
=> Add missing user property

api/preprint_providers/views.py, api_tests/preprint_providers/views/test_preprint_provider_subjects_list.py
Taxonomy api is broken
Changes the query to work with django
None known
[#OSF-7352]
https://openscience.atlassian.net/browse/OSF-7352
=> Fix Preprints api taxonomy [OSF-7352]

addons/dataverse/models.py
Fix views for Dataverse files
* Correct a bad c/p
None expected
[#OSF-7377](https://openscience.atlassian.net/browse/OSF-7377)
=> Fix DataverseFile.update [OSF-7377]

scripts/analytics/addon_snapshot.py
Allow analytics to run
* Update syntax
None expected
[#OSF-7391](https://openscience.atlassian.net/browse/OSF-7391)
=> Update AppConfig model access syntax in analytics job [#OSF-7391]

addons/base/models.py
Self-explanatory
* Update syntax
None expected
None known
=> Prevent AttributeError when merging users addons

osf/models/node.py
Follow-up to #6781 with a RCTE that doesn't recurse to anything that could be cyclic
* Fix SQL query
None expected
[#OSF-7395](https://openscience.atlassian.net/browse/OSF-7395)
=> Exclude node_links in Recursive CTE [#OSF-7395]

scripts/register_oauth_scopes.py
@sloria 
I happened to wrote `Java` instead of `Python` when converting this script to Django-OSF.
=> [Fix] Fix `print()` in `scripts.register_oauth_scopes` [No Ticket]

addons/box/README.md, addons/dropbox/README.md, addons/figshare/README.md, addons/github/README.md, addons/googledrive/README.md, addons/mendeley/README.md, addons/zotero/README.md, website/addons/box/README.md, website/addons/dataverse/README.md, website/addons/dropbox/README.md, website/addons/figshare/README.md, website/addons/github/README.md, website/addons/googledrive/README.md, website/addons/mendeley/README.md, website/addons/owncloud/README.md, website/addons/zotero/README.md
[SVCS-242](https://openscience.atlassian.net/browse/SVCS-242)
Update addons doc for new addons location
Update  all website/addons/*/README.md with deprecation warning...
```
```
Update all ./addons/*README.md  replace ./website/addons with ./addons
None
[SVCS-242]
=> Update addons doc for new addons location

README-docker-compose.md
=> [Fix] Update Docs for Remote Debugging Using Docker [Not Ticket]

osf/models/node.py
This is a followup to #6790. The solution in that PR isn't complete because nodes can be returned out of order. This is a simpler solution that guarantees the correct order of nodes is returned.
- `get_nodes` will query on NodeRelations, ordered, and joined with AbstractNode, then return the ordered list of `AbstractNodes`.
https://openscience.atlassian.net/browse/OSF-7400 (see my comment on the ticket)
=> Fix ordering of nodes returned by get_nodes

website/profile/views.py
- Exclude registration on profile [OSF-7420]
- Prevent duplicates [OSF-7400] (see comment)
=> Don't show registrations and prevent duplicate nodes on profile

osf/models/base.py, osf/models/node.py, website/prereg/utils.py, website/prereg/views.py
Extends #6784 
* Override Django's `_for_write` to conditionally add or remove query annotations
* Ensure `GuidMixin` models have correct `_id` after cloning
* Add `.subselect` manager for subqueries that don't require annotation
None Expected
None known
=> [Feature] Optimize GUID queries

tests/test_preprints.py, website/project/views/contributor.py
Send emails when contributors are added to preprints
* Fix query
* Add test
None expected
[[#OSF-7425]](https://openscience.atlassian.net/browse/OSF-7425)
=> [Feature fix] Contributor-added emails for Preprints [#OSF-7425]

osf/models/node.py, osf_tests/test_node.py, scripts/README.md, tests/base.py, tests/test_metadata.py, tests/test_test_utils.py
- Remove duplication of logic for adding default addons (wiki and osfstorage)
- Update scripts README
- Remove DbIsolationMixin from tests
=> DjangoOSF chores

addons/box/README.md, addons/figshare/README.md, website/addons/figshare/README.md
[SVCS-242](https://openscience.atlassian.net/browse/SVCS-242)
Minor doc edits. Response to post merge CR.
None
[SVCS-242]
=> Minor doc edits. Response to post merge CR.

api/base/settings/defaults.py, osf/db/router.py
Prevent `OperationalError`
* Add db router 
¯\\\_(ツ)_/¯ 
[#OSF-7406](https://openscience.atlassian.net/browse/OSF-7406)
=> [Feature] PostgreSQL failover routing [#OSF-7406]

scripts/populate_preprint_providers.py
Add AgriXiv advisory board member
https://openscience.atlassian.net/browse/EOSF-238
=> [EOSF-238] Add AgriXiv advisory board member

scripts/populate_preprint_providers.py
Fixes non-django-y syntax breaking the populate providers script.
=> Re update populate script to support django syntax

scripts/populate_preprint_providers.py
Add agrixiv to prod.
Move script to master
=> Add Agrixiv to Prod, and updated script to master,

README-docker-compose.md
change name of postgres data volume container
=> Fix last example command to remove postgres data vol

osf/models/node.py, tests/test_views.py, website/project/views/node.py
Fix behavior around deleting Nodes with with NodeLinks or components
* Only `.load` actual models
* `.filter` correctly, if less efficiently
None expected
[[#OSF-7444]](https://openscience.atlassian.net/browse/OSF-7444)
[~~[#OSF-7492]~~](https://openscience.atlassian.net/browse/OSF-7492)
=> Fix Node deletion behavior wrt NodeLinks [OSF-7444]

api/users/views.py
* Return a QuerySet from `get_queryset`
None expected
[[OSF-7515]](https://openscience.atlassian.net/browse/OSF-7515)
=> Fix UserInstitutions View [OSF-7515]

osf/models/node.py
Prevent `AttributeError`
* Use Django's "bulk" `.update`
None expected
[[OSF-7514]](https://openscience.atlassian.net/browse/OSF-7514)
=> Use Django's "bulk" .update [#OSF-7514]

README-docker-compose.md
Add instructions for not committing docker-compose.override.yml and docker-sync.yml
=> How to skip modified files in git

osf/models/node.py
=> Filter with correct object types [OSF-7514]

tasks/__init__.py
=> Enables celery worker queues.

admin/meetings/forms.py
=> [Admin] Use URLField to validate URL [OSF-7521]

scripts/osfstorage/usage_audit.py
[[#OSF-7527]](https://openscience.atlassian.net/browse/OSF-7527)
=> Update usage_audit.py for Django [#OSF-7527]

osf/models/user.py
Reverts CenterForOpenScience/osf.io#6860
=> Revert "Update "Optimize guid queries (Update)" [OSF-7516]"

osf/models/base.py, osf/models/node.py
Reverts CenterForOpenScience/osf.io#6851
=> Revert "[Feature] Optimize guid queries (Update) [OSF-7462]"

osf/management/commands/migraterelations.py
See title.
Increment fk count for notification subscription fks.
nah
=> [RFR] Add counting to notification subscription fks

.gitignore, scripts/generate_sitemap.py, website/routes.py, website/settings/defaults.py
No osf sitemap.
Adds a sitemap generator and beat job.
None known
1. This requires beat and will require prod modifications to work.
2. This will also require a later PR to add a ping to google on prod when the sitemap is updated. 
3. After CR, I would like to add a few tests, but I want at least one pass of CR first in case things need to drastically change.
4. This will require some product changes to priorities (not currently generated) and changefreqs.
I will confirm that it is working, no normal QA at the moment.
[#OSF-7322]
https://openscience.atlassian.net/browse/OSF-7322
=> [Feature] Add sitemap generator [OSF-7322]

scripts/generate_sitemap.py, website/static/js/components/logFeed.js
Previous had no error handling.
Now catches all errors in xml serialization and logs them, throws sentry errors when too much is breaking.
NA
[#OSF-7322]
https://openscience.atlassian.net/browse/OSF-7322
##QA Notes
No QA, if it gets moved to QA put back in AD and send it back to me. I'll verify that everything is working with staging data.
=> [feature] Log errors in sitemap generator [OSF-7322]

osf/management/commands/verify.py, osf/models/base.py, osf/models/node.py, osf/models/user.py, osf_tests/test_guid_annotations.py, requirements/dev.txt
=> Add initial guid query optimizations

osf/models/mixins.py
* Sort AddonConfigs
None Expected
[[OSF-7534]](https://openscience.atlassian.net/browse/OSF-7534)
=> Sort AddonConfigs Alphabetically [OSF-7534]

osf/models/admin_log_entry.py, osf/models/admin_profile.py
=> Add primary_identifier_name to new admin models

scripts/generate_sitemap.py
No progress bar, some queries off/inefficient
Adds progress bar, fixes queries.
More awesome.
[#OSF-7322]
https://openscience.atlassian.net/browse/OSF-7322
=> [feature] Sitemap progress bar, better queries [OSF-7322]

addons/base/models.py
Allow addon deauthorization
* Fix bad copy from MODM method
None expected
[[OSF-7541]](https://openscience.atlassian.net/browse/OSF-7541)
=> Fix revoke_oauth_access [OSF-7541]

README-docker-compose.md
How to update with docker-compose
=> Add section for updating

framework/auth/core.py, osf/models/user.py, osf_tests/test_user.py, website/institutions/views.py, website/views.py
Add a few minor optimizations.
- Prevent redundant query for Institutions on user home page
- Prevent unnecessary Institution and User query on index page when not logged in
- Simplify implementation of `User.update_affiliated_institutions_by_email_domain`
No ticket, just found these inefficiencies while browsing New Relic.
=> Minor optimizations

api/base/middleware.py, api_tests/base/test_middleware.py, framework/transactions/context.py, website/mailchimp_utils.py
Make TokuTransactions ~behave as expected wrt the current DB~ raise an exception
* ~Conditionally use pre- or post-django code~
* Raise an exception
Any existing uses will error.
[[OSF-7543]](https://openscience.atlassian.net/browse/OSF-7543)
=> Deprecate TokuTransactions [OSF-7543]

scripts/retract_registrations.py, scripts/send_queued_mails.py, scripts/triggered_mails.py
[[OSF-7543]](https://openscience.atlassian.net/browse/OSF-7543)
=> Prefer django.db.transaction.atomic [OSF-7543]

addons/github/tests/test_models.py, api_tests/nodes/views/test_node_files_list.py, tests/test_addons.py
=> Fix tests broken by correct GH behavior [No Ticket]

scripts/populate_new_and_noteworthy_projects.py
Prevent UnicodeEncodeErrors
* Use `ensure_bytes`
None expected
[[OSF-7547]](https://openscience.atlassian.net/browse/OSF-7547)
=> [Hotfix] Prevent UnicodeEncodeErrors in New&Noteworthy script [OSF-7547]

api/base/filters.py, api/base/views.py, api/nodes/serializers.py, api/nodes/views.py, api_tests/nodes/views/test_node_contributors_list.py
Speedup dashboard page load by reducing number of queries needed for /user/me/nodes api requests.
Used SQL annotations to gather necessary data in one query.
Possible that the query is only working and the tests passing because there is a limited amount of data in the database during testing and the `SELECT CASE WHEN` `JOIN` could be working randomly.
=> [RFR] Refactor user/me/nodes to hold onto the queryset as long as possible

website/templates/prereg_landing_info.mako
Fix typo in n pre-reg landing page, close ticket OSF-7507.
minor language change.
None
https://openscience.atlassian.net/browse/OSF-7507
=> [Hot fix][OSF-7507] Fix typo in pre-reg landing

scripts/migration/ensure_bookmark_existence.py, website/project/__init__.py
=> [Hotfix] Ensure bookmark collection existence

api_tests/collections/test_views.py, api_tests/nodes/views/test_node_list.py, api_tests/registrations/views/test_registration_list.py, api_tests/users/views/test_user_detail.py, api_tests/users/views/test_user_nodes_list.py, api_tests/users/views/test_user_registrations_list.py, framework/auth/core.py, scripts/migration/ensure_bookmark_uniqueness.py, tests/factories.py, tests/models/test_user.py, tests/test_models.py, tests/test_search/test_views.py, tests/test_test_utils.py, tests/test_websitefiles.py, website/notifications/listeners.py, website/project/model.py, website/views.py
Reverts CenterForOpenScience/osf.io#6919
=> Revert "Revert Hotfix 104.43"

admin/users/views.py, osf/models/node.py
Tag spam users correctly
* Interact with MRM's correctly
* Opportunistic fixes for Admin module
None expected
[[OSF-7557]](https://openscience.atlassian.net/browse/OSF-7557)
=> Fix Spam tag addition [OSF-7557]

scripts/populate_preprint_providers.py
Update license and description of scielo
https://openscience.atlassian.net/browse/EOSF-238
=> [EOSF-238] Update license and description of scielo

osf/utils/datetime_aware_jsonfield.py, requirements.txt
dateutil.parser was 48% of the profile
Replace dateutil.parser with C library
Speed.
=> Use c lib for datetime parsing

osf/models/registrations.py, tasks/__init__.py, website/project/model.py, website/project/views/register.py
Retractions are broken and the retraction tests are not being run.
1. Adds proper root check (two model changes are for compat, but unused)
2. Add back in registration tests that all passed locally
Better test coverage.
[#OSF-7573]
https://openscience.atlassian.net/browse/OSF-7573
Simply withdraw a registration. If it works then 👍
=> [feature] Fix retractions root check [OSF-7573]

.travis.yml, api/base/settings/local-dist.py, api/base/settings/local-travis.py, api_tests/base/test_versioning.py, api_tests/conftest.py, framework/auth/campaigns.py, osf_tests/conftest.py, osf_tests/settings.py, requirements/dev.txt, scripts/osfstorage/settings/__init__.py, tasks/__init__.py, tests/base.py, tests/test_registrations/test_archiver.py, website/app.py, website/search/elastic_search.py, website/settings/defaults.py
Optimize tests for parallel runs with local (docker) and travis-ci.
=> [feature] parallel tests

api/applications/views.py, api/base/serializers.py, api/base/settings/defaults.py, api/base/utils.py, api/base/views.py, api/citations/views.py, api/collections/views.py, api/files/views.py, api/guids/views.py, api/identifiers/views.py, api/institutions/serializers.py, api/institutions/views.py, api/licenses/views.py, api/metaschemas/views.py, api/nodes/serializers.py, api/nodes/utils.py, api/nodes/views.py, api/preprints/views.py, api/registrations/views.py, api/taxonomies/views.py, api/tokens/views.py, api/users/serializers.py, api/users/views.py, api/view_only_links/serializers.py, osf/models/base.py, osf/models/files.py, osf/models/node.py, osf/models/user.py, osf_tests/test_eager_queryset.py
But Faster. 
- Pass data we already had to embeds so no extra queries.
- Add the ability to eagerly load fk and m2m fields passed to `.eager(['field', 'field1'])`
- Pycharm reformatted some things for me.
Nothing whatsoever could work.
=> [RFR] Make it more faster pls (API) v2

osf/models/node.py
Make abstractnode queries faster.
Added index_together on is_public, is_deleted, and type
Queries could be faster.
=> Add migration for index abstractnode is_public, is_deleted, and type

website/project/views/node.py
Don't try to show deleted forks
* Filter for non-deleted forks
None expected
[OSF-7609](https://openscience.atlassian.net/browse/OSF-7609)
=> Hide deleted forks [OSF-7609]

osf_tests/test_archiver.py
Continuation of #6939 
TODO:
* Follow-up PR for `test_models`
Note:`test_websitefiles` will be fixed separately after a refactor to file-related models
None expected.
[OSF-7574](https://openscience.atlassian.net/browse/OSF-7574)
=> Fix test_archiver [OSF-7574]

osf/models/institution.py
Fix login_url population during migration
changed auth -> login in migrate_from_modm for Institutions
I guess it could still not work.
=> [RFR] Change auth_url to login_url in Institution.migrate_from_modm

api/nodes/serializers.py
Count node children correctly
* Exclude deleted children
None expected
[[OSF-7618]](https://openscience.atlassian.net/browse/OSF-7618)
=> Count only non-deleted children [OSF-7618]

framework/auth/core.py, osf/models/user.py, website/search/elastic_search.py, website/search/search.py
Make `.save` calls faster for users with many nodes
* Update elastic with queued tasks
None expected
[[OSF-7643]](https://openscience.atlassian.net/browse/OSF-7643)
=> Asynchronize user-related elasticsearch updates [OSF-7643]

api/institutions/views.py, osf/models/node.py, osf_tests/test_node.py
=> Turn can_view into a sql query

api/base/settings/defaults.py, docker-compose.yml, osf/models/base.py, osf_tests/test_guid_annotations.py, requirements.txt
Pending further review and modifications to make it work
with ATOMIC_REQUESTS, among other things
=> Remove django-cacheops [OSF-7664]

api/nodes/views.py, api/preprint_providers/views.py, api/preprints/views.py, api_tests/nodes/views/test_node_preprints.py, api_tests/preprint_providers/views/test_preprint_provider_preprints_list.py, api_tests/preprints/filters/test_filters.py, api_tests/preprints/views/test_preprint_list.py
Api preprint filter routes are 503ing
Fixes the broken filters
None known
[#OSF-7584]
https://openscience.atlassian.net/browse/OSF-7584
test these routes:
https://staging-api.osf.io/v2/preprints/?filter[id]=<id>
https://staging-api.osf.io/v2/nodes/<node_id>/preprints/?filter[id]=<id>
https://staging-api.osf.io/v2/preprint_providers/preprints/?filter[id]=<id>
https://staging-api.osf.io/v2/nodes/<node_id>/preprints/?filter[provider]=<provider_id>
https://staging-api.osf.io/v2/preprint_providers/preprints/?filter[provider]=<provider_id>
=> [feature] Fix api post process [OSF-7584]

README-docker-compose.md
Update docs with more simple command
=> Use docker image prune command for cleanup

osf/models/base.py, osf/models/licenses.py, osf/models/metaschema.py, osf/models/node.py, osf/models/node_relation.py, osf/models/nodelog.py, osf/models/preprint_provider.py, osf/models/preprint_service.py, osf/models/subject.py, osf/models/user.py
[[OSF-7668]](https://openscience.atlassian.net/browse/OSF-7668)
=> Improve object reprs [OSF-7668]

osf/models/node.py
Optimize license property
Replace recursive python with recursive SQL
Haven't profiled, this could be slower in all but the edgiest of cases
None known
=> Optimize license property [No Ticket]

scripts/populate_institutions.py
VT
Attributes: `eppn`
https://openscience.atlassian.net/browse/CAS-49
=> [HotFix] [Institutions] Update VT [CAS-49]

addons/box/models.py, addons/dataverse/models.py, addons/dropbox/models.py, addons/figshare/models.py, addons/github/models.py, addons/googledrive/models.py, addons/osfstorage/models.py, addons/owncloud/models.py, addons/s3/models.py, osf/management/commands/migratedata.py, osf/management/commands/migraterelations.py, osf/models/files.py, scripts/delete_restored_trashedfilenodes.py, scripts/migration/ensure_bookmark_uniqueness_legacy.py
Make migrations work with new file models.
Updated migrations and added a migration to fix bookmarks.
=> Fix migrations to support new file models

api/nodes/serializers.py
[[OSF-7705]](https://openscience.atlassian.net/browse/OSF-7705)
=> Count only components, not links [OSF-7705]

osf/models/node.py
Make `parent` behavior mimic prod
* Remove erroneous conditional
None expected
[[OSF-7708]](https://openscience.atlassian.net/browse/OSF-7708)
=> Fix Fork Parent [OSF-7708]

scripts/migrate_duplicate_external_accounts.py
```
python -m scripts.migrate_duplicate_external_accounts --dry
```
=> [Hotfix] Duped ExternalAccounts

api_tests/nodes/views/test_view_only_query_parameter.py, osf/models/node.py, osf_tests/test_node.py
[[OSF-7707]](https://openscience.atlassian.net/browse/OSF-7707)
=> Optimize aggregate logs query [#OSF-7707]

addons/osfstorage/views.py
=> [OSF-7729] Default to an empty list

addons/osfstorage/tests/test_views.py, addons/osfstorage/views.py
=> [OSF-7729] Fetchone returns a tuple

addons/osfstorage/models.py
=> [Hotfix] Optimize materialized_path

admin/nodes/views.py
Viewing registration details is currently broken, as that happens through the nodes view and Node.load did not find them!
Also attempt to load Registrations on the node view
=> [hotfix] Also allow viewing registrations from node detail

scripts/analytics/addon_snapshot.py
Prevent error
* Define var before referencing it
=> [Hotfix] Fix addon snapshot script

api/base/middleware.py, api/base/serializers.py, api/base/views.py, requirements.txt
=> [OSF-7744] Fix memory leak. Move cache onto request

osf/models/base.py
Prevent duplicate joins from happening when calling `.load`.
In `GuidMixin.load`, re-annotate the queryset after filtering, so the join with `guid` can be re-used
(source: https://stackoverflow.com/questions/40663638/removing-a-superfluous-inner-join-from-a-django-query)
https://openscience.atlassian.net/browse/OSF-7739
=> [hotfix] [OSF-7739] Prevent duplicate join clause when calling .load

api/base/settings/defaults.py, osf/management/commands/osf_shell.py, requirements.txt, tasks/__init__.py
Updates and improves the `inv shell` (which is equivalent to `python manage.py osf_shell`.
This depends on a fork of `django-extensions` that has a modification to allow adding additional imports at runtime (https://github.com/django-extensions/django-extensions/pull/1039). This change has been merged upstream, so we can remove the fork when django-extensions cuts another release.
Devs will need to update their requirements: `docker-compose up requirements` and/or `pip install -r requirements.txt`
- I'm sending this as a hotfix so that the behavior of `inv shell` is consistent on master and develop. It's a low-risk PR, anyway.
- I had issues with garbage characters showing up when entering characters into IPython. Seems to be an issue with invoke<=0.13.0. Upgrading invoke locally (0.15.0) …
=> Update `inv shell` for Django

osf/models/node.py, osf_tests/test_node.py
Prevent `AttributeError`s when chaining additional filters on `<AbstractNodeQuerySet>.get_children`
* Add regression test
* Return `AbstractNode.objects.none()` instead of `[]`
* Remove unused kwarg
None expected
[[OSF-7778]](https://openscience.atlassian.net/browse/OSF-7778)
=> [Hotfix] Fix ANQS.get_children [OSF-7778]

framework/mongo/utils.py, website/search/elastic_search.py, website/search_migration/migrate.py
Speed up search indexing without refactoring the whole thing.
- Use django magic to filter in sql instead of filtering in python.
- Use values_list to only pull back data we're actually going to use.
- Make Nodes modified during the first pass of indexing be indexed again afterwards.
None expected.
https://openscience.atlassian.net/browse/OSF-7748
=> [RFR] Speed up search indexing [OSF-7748]

scripts/populate_preprint_providers.py
Preprint providers is missing django setup and doesn't work.
Add django setup
n/a
None
=> Add Django setup to Populate preprint providers [no-ticket]

tests/test_preprints.py, website/preprints/tasks.py
=> [Hotfix][WIP] Don't use DOIs as preprint identifiers

addons/base/models.py, addons/box/models.py, addons/dropbox/models.py, addons/googledrive/models.py, addons/s3/models.py
Fix the generic addon `_view_folder`
* Generalize `fetch_folder_name`
None expected
[[OSF-7816]](https://openscience.atlassian.net/browse/OSF-7816)
=> Generalize fetch_folder_name [OSF-7816]

website/search/elastic_search.py, website/search/search.py, website/static/js/search.js, website/templates/search.mako
Reverts CenterForOpenScience/osf.io#6524
=> Revert "[feature] Add Preprint Filter to OSF Search [OSF-6978]"

admin/README.md
Update instructions for getting the admin up and running locally
- README updates to work with new django configuration
None
https://openscience.atlassian.net/browse/OSF-7842
=> Update admin README for new docker instructions [OSF-7842]

admin/README.md
Two quick changes to admin docs.
Typo fix; use docker specific command
None
[#OSF-7842]
https://openscience.atlassian.net/browse/OSF-7842
=> [feature] Admin docs fix [OSF-7842]

website/static/js/pages/project-dashboard-page.js
Mithril mounts also mounts institution related things on retractions. Which throws a mithril error.
Stop mounting retractions.
Nah
https://openscience.atlassian.net/browse/OSF-7575
=> [feature] Fix institutions mounting failure too [OSF-7575]

addons/github/apps.py, addons/github/views.py
Github branches be broke.
Fixes the branches by using the custom function that existed.
None known.
[#OSF-7816]
https://openscience.atlassian.net/browse/OSF-7816
If branches works, this works 👍
=> [feature] Fix github root/branches [OSF-7816]

scripts/populate_institutions.py
Fix missing space in the description for FSU.
Need to run `scripts.populate_institutions <environment>`.
=> [HotFix] FSU Description [No Ticket]

docker-compose.ubuntu.yml
Update to Ubuntu docker file to stay up to date with override file.
None
=> Keeping up with the Joneses (docker-compose.override.yml)

api/files/views.py, api_tests/preprints/views/test_preprint_detail.py, api_tests/users/views/test_user_nodes_list.py, osf/models/files.py, osf_tests/test_elastic_search.py, scripts/migrate_file_guids.py, scripts/osfstorage/migrate_to_generic.py, website/files/models/base.py, website/files/utils.py
Remove deprecated `BaseFileNode.wrapped()`.
https://openscience.atlassian.net/browse/OSF-7773
=> [OSF-7773] Remove usage of deprecated BaseFileNode.wrapped()

scripts/populate_preprint_providers.py, website/templates/public/register.mako
1. Update the Steering committee section to have the title/heading of 'Legal Scholarship Advisory Board'
2. Remove the title 'Copyright Advisor'' after Kyle Courtney's name
3. lawarxiv added to list of prod preprint providers
4. remove gray background color on lawarxiv logo on register page
5. Remove  Architecture
Engineering
Life Sciences
Physical Sciences and Mathematics
https://openscience.atlassian.net/browse/OSF-7810
=> Hotfix/LawArXiv Steering Committee Changes [OSF-7810]

website/static/css/pages/home-page.css, website/static/css/quick-project-search-plugin.css, website/static/js/home-page/preregBannerPlugin.js, website/static/js/home-page/quickProjectSearchPlugin.js, website/static/js/pages/home-page.js, website/templates/home.mako
- Adds the prereg promo banner to the dashboard. 
- Reverts the work done in #7025 and #7046 
- Adds the banner as a plugin to the page (instead of hacking around it!) this time. 
- [OSF-7511](https://openscience.atlassian.net/browse/OSF-7751)
=> [feature] Prereg Banner Dashboard [OSF-7751]

website/templates/project/project.mako
Update Language when there are no components on a project
1. create a project with no component
2. go to the project's dashboard
Before change:
After change:
https://openscience.atlassian.net/browse/OSF-7438
=> [#OSF-7438]Update Language when there are no components on a project

addons/wiki/static/wikiPage.js, addons/wiki/templates/edit.mako, addons/wiki/templates/wiki_widget.mako, addons/wiki/tests/test_wiki.py, tests/test_webtests.py, website/static/js/pages/project-dashboard-page.js
Change Default Language on Wiki without Content
create a new project without any wiki
go to the project overview page and watch the wiki widget
before change:
after change:
https://openscience.atlassian.net/browse/OSF-7437
=> [#OSF-7437]Change Default Language on Wiki without Content

scripts/populate_preprint_providers.py
Change the LawArxiv example preprint to https://osf.io/preprints/lawarxiv/vk7yp
goes to lawarxiv at https://osf.io/preprints/lawarxiv
click on the link "see an example"
before change:
the link will redirect you to https://osf.io/khbvy/
after change: 
the link will redirect you to https://osf.io/preprints/lawarxiv/vk7yp
https://openscience.atlassian.net/browse/OSF-7937
=> [#OSF-7937]Update LawArxiv example preprint

CHANGELOG, package.json
=> Changelog for 0.108.0

scripts/analytics/run_keen_events.py, scripts/analytics/run_keen_snapshots.py, scripts/analytics/run_keen_summaries.py
Keen scripts don't run locally. This adds the proper django setup so they don't break.
Adds django setup to the three celery-run scripts. I tested that beat does not break when running them.
Would be nice to confirm that staging beat jobs still work.
https://openscience.atlassian.net/browse/OSF-7957
No QA needed, these are run on an as-needed basis.
=> [feature] Fix keen scripts [OSF-7957]

website/templates/footer.mako
Update Google+ Link on footer
The link on the current OSF footer links to the wrong Google+ account (https://plus.google.com/103557785986281627994)
Change it to the correct link to this account: https://plus.google.com/b/104751442909573665859
https://openscience.atlassian.net/browse/OSF-7161
=> [#OSF-7161]Update Google+ Link on footer

framework/auth/views.py, osf/models/user.py, osf_tests/test_user.py
https://openscience.atlassian.net/browse/OSF-7971
=> ORCID login

scripts/fix_keen_preprint_keys.py
Old preprint nodes are using the preprint guid to generate the keen id when it needs to be from the node guid. This is working properly inside of the osf now, but there is old broken data.
This script will clean up the broken ones.
NA
https://openscience.atlassian.net/browse/OSF-7408
Make sure analytics work on preprints after the script is run-- the script will output at least 10 guids that were updated for testing.
=> [hotfix] Add keen key fix script [OSF-7408]

.travis.yml
Fixes travis builds
* Specify valid binary package locations
None expected
None known
=> [Hotfix] Bump Travis dependency versions

admin/preprints/serializers.py
Dead import was left and missed because travis failed. 
Remove unneeded import.
na
na
=> [hotfix] Fix flake import [noticket]

admin/pre_reg/views.py
One missed file with FileNode changes borked admin.
Fixes that file
NA
NA
=> [noticket] Swap FileNode - BaseFileNode

osf/utils/datetime_aware_jsonfield.py
[#OSF-7874]
Since upgrading to Django 1.11, we can now modify DatetimeAwareJSONField to use a custom JSON encoder in the definitoin
Modify `DateTimeAwareJSONField` to accept a default encoder instead of using Json explicity to dump and load for encoding
https://openscience.atlassian.net/browse/OSF-7874
=> Use custom JSON encoder to implement DateTimeAwareJSONField [OSF-7874]

api/files/serializers.py
In a recent django rest framework update, they [changed the choices](https://github.com/encode/django-rest-framework/commit/f1a2eeb818366b11c44c86d2ccfa1d6822d216b9) for a field (in a model form) to be derived from the result of `get_representation` instead of just coercing the value to a string - this method for choices is called by [the base class for our browsable docs renderer](https://github.com/CenterForOpenScience/osf.io/blob/develop/api/base/renderers.py#L28) (even tho we don't really use it), and so needs to be changed to use a pk instead of the return value of `to_representation`, which is a dict due to our JSON API compliant API.
This was causing our file detail endpoint to error when instantiating the renderer for the browsable API docs, even tho we were removing those forms …
=> [hotfix] Override CheckoutField get_choices method to use pk  [OSF-7967]

osf/management/commands/populate_custom_taxonomies.py
Follow-up to #7163 
* Add `merge` key to `data` param
None expected
[[OSF-7788]](https://openscience.atlassian.net/browse/OSF-7788)
=> Allow custom taxonomy merge targets [#OSF-7788]

website/archiver/tasks.py
SEE https://github.com/CenterForOpenScience/osf.io/pull/7099
=> [hotfix] wbv1 archiver update [OSF-7284]

tasks/__init__.py
Run admin tests
* Run admin tests in `API1` job
None expected
None known
=> Run admin tests

scripts/generate_sitemap.py
gz in index breaks googlebots.
point to xml instead of gz
NA
No ticket
=> [hotfix] sitemap remove gz from index [no-ticket]

website/static/js/project.js, website/templates/project/project.mako
Fix the view forks button not working
Now the view fork button will redirect to fork page
https://openscience.atlassian.net/browse/OSF-7436
=> [#OSF-7436]Change icons on top right of Project Overview page to make them more universal	

CHANGELOG, package.json
Update standard release metadata for the new version
Changelog. Package.json.
No
n/a
=> Update changelog and package for 0.110.0

website/templates/project/project.mako
Change number on "forks" button sto be forks only
Change number on "forks" button sto be forks only
https://openscience.atlassian.net/browse/OSF-8054
https://openscience.atlassian.net/browse/OSF-7436
=> [#OSF-8054]Number on "forks" button should be forks only

osf/migrations/0032_unquote_gd_nodesettings_folder_path.py
Prevent errors from clean DB
* Use `state` to maybe get model
None expected
None
=> [Hotfix] Prevent errors from clean DB

website/static/js/fangorn.js
Checkouts got broke by id changes at some point
Add id check instead of checkout check
NA
https://openscience.atlassian.net/browse/OSF-7736
1. Make sure the facet is the correct color (person who checked vs person who didn't)
2. Make sure the button appears properly (checked versus person who didn't check)
3. Make sure the button actually works as intended
=> [feature] Fix fangorn checkouts [OSF-7736]

website/static/templates/registration-modal.html
Change button text in the final registration modal so the user is aware
it's the last step. 
Change button text from  "Continue"  to "Submit"
https://openscience.atlassian.net/browse/OSF-7830
=> [Improv] Change button text in reg choice modal [OSF-7830]

docker-compose.yml
[#SVCS-364]
Add local_bin volumes to wb/wb_requirements and mfr/mfr_requirements
None
[SVCS-364](https://openscience.atlassian.net/browse/SVCS-364)
=> Update docker-compose.yml for MFR/WB to include /usr/local/bin

website/static/js/fangorn.js
Update browser check and browser file API feature detection.
- Use osfHelper method for browser detection.
- Add better check for File API isDirectory feature.
https://openscience.atlassian.net/browse/OSF-7285
=> [Feature] Update fangorn dropzone error on folder upload [OSF-7285]

admin/templates/users/user.html
- Fixes 502 in admin app due to templating error.
- Iterate over emails that are already returned from the [user serializer](https://github.com/CenterForOpenScience/osf.io/blob/master/admin/users/serializers.py#L12) instead of directly accessing user emails in the template.
- https://sentry.cos.io/sentry/admin-yg/issues/279724/
=> [hotfix] Fix Admin User View 502 [No Ticket]

website/static/js/logTextParser.js
Fix one typo error in previous pr.https://github.com/CenterForOpenScience/osf.io/pull/7073/files#diff-9935e4b6316b40e4e97d56393d0d7f57R450
https://openscience.atlassian.net/browse/OSF-7684
=> [#OSF-7684]Moving files between components breaks links in logs

addons/osfstorage/tests/test_views.py
Nested folder checkouts were not fully added.
Add two more nested folder checks.
NA
https://openscience.atlassian.net/browse/OSF-7954
No QA, just tests
=> [feature] More checkout tests for nested folders [OSF-7954]

scripts/generate_sitemap.py
Osf preprints should be listed as /preprints/<guid>/ in sitemap.
Lists osf preprints as /preprints/<guid>/ in sitemap
BEFORE:
AFTER:
NA
https://openscience.atlassian.net/browse/OSF-7964
No QA needed, will be checked when script is run.
=> [hotfix] Sitemap preprints url update [OSF-7964]

osf/models/user.py
Fix links returned from API
* Add OSFUser.get_absolute_url
None expected
None known
=> [Hotfix] Fix OSFUser self links

api/institutions/views.py
- Fix institution node and registrations list queries.
- Make more fast. 
- [OSF-8085](https://openscience.atlassian.net/browse/OSF-8085)
=> [feature] Fix Institution Node/Registration Queries [OSF-8085]

website/static/js/addProjectPlugin.js
Reverts CenterForOpenScience/osf.io#7053
=> Revert "[OSF-7636] Add ability to inherit tags from parent node"

README-docker-compose.md
Update links to Linux specific configuration.
Update README-docker-compose.md
No associated ticket
=> Update links to Linux specific configuration.

osf/management/commands/force_archive.py
Extends #7312 
Allow other permissible addons to be specified
None expected. Use with caution
[[OSF-8185]](https://openscience.atlassian.net/browse/OSF-8185)
=> [Hotfix] Force other addons [OSF-8185]

osf/management/commands/force_archive.py
Improves #7351 
* LBYL for file collisions
* Granular archive job target completion
None expected
[[OSF-8185]](https://openscience.atlassian.net/browse/OSF-8185)
=> [Hotfix] Force other addons better [OSF-8185]

addons/s3/utils.py, docker-compose.override.yml, docker-compose.yml, docker-sync.yml
Update docker-compose and docker-sync files to use the latest versions
- Remove volumes_from and replace with volumes in dockercompose.override.yml
- Remove dest in docker-sync.yml
- Update docker-compose.yml to version 3
- Add named volume "code"
- Remove commented out code
May interfere with production deploy?
No Ticket
=> Use latest docker-sync, docker-compose version

scripts/github/tarchive.py
Add one-off script to handle rate-limiting edge case
* Add script
None expected
[[OSF-8185]](https://openscience.atlassian.net/browse/OSF-8185)
=> [Hotfix] TARchive [OSF-8185]

docker-compose.override.yml
Lines to run preprints with docker were incorrect/missing.
Add/fix preprints lines.
None
None
=> Fix lines for local use of preprints [No ticket]

osf/management/commands/force_archive.py
Extend functionality of `force_archive.py`
* Update script to be agnostic re. deletion status
None expected
[[OSF-8180]](https://openscience.atlassian.net/browse/OSF-8180)
=> [Hotfix] Allow archiving from deleted nodes [OSF-8180]

scripts/stuck_registration_audit.py
Update audit script to be more accurate
* Use `LOG_[WHITE|GREY]LIST` as defined in the `force_archive` script
* Use `verify` method from `force_archive` script
None expected
[[OSF-8159]](https://openscience.atlassian.net/browse/OSF-8159)
=> [Hotfix] Update stuck registration audit [OSF-8159]

admin/README.md
Admin does not say to commit changes made via shell.
Add a line to commit changes.
NA
NO TICKET
=> [feature] Update admin docs [no-ticket]

api/preprints/serializers.py, osf/models/preprint_service.py, tests/test_preprints.py, website/preprints/tasks.py, website/util/share.py
Reverts CenterForOpenScience/osf.io#7243
=> Revert "[HOLD] SHARE subject serialization [OSF-7788]"

website/templates/nav.mako
Fix space between OSF and service name
Add class to fix space between OSF and HOME (and MEETINGS)
NA
https://openscience.atlassian.net/browse/OSF-7562
=> [feature] Navbar add missing class [OSF-7562]

CHANGELOG, package.json
=> Update changelog and package.json for 0.116.0

admin/templates/base.html
Reverts CenterForOpenScience/osf.io#7420
=> Revert "[feature] Custom admin style when dev_mode off [OSF-8140]"

framework/sentry/__init__.py, website/views.py
Make sentry aggregate errors 
- Modify sentry (flask client)  config to take extra data as optional keyword arg
- Modify website view to call sentry with guid as extra data
https://openscience.atlassian.net/browse/OSF-7823
=> [Feature] Make sentry error less annoying [OSF-7823]

addons/base/views.py, website/static/js/filepage/index.js, website/templates/project/view_file.mako
Prereg checks out files when they are viewed. The files show whoever last viewed the prereg as the person who checked it out to the user without notifying the user as to why. Who is David Mellor and why is he in my project checking out my files?
Adds a special case to the banner for prereg checkouts
The prereg checkout banner will not show up if the prereg admin who checked out the file is a contributor on the project. The prereg banner will show up if a prereg admin was a contributor on a project that has a prereg draft and checked out a file before being removed as a contributor. That just might be the edgiest of edge cases. 
In other words, people with prereg (admin) view access might have some weird views, but they are weird anyway.
The original code appears to have a small chance of …
=> [feature] Special case checkout banner for preregistration checkouts [OSF-8071]

website/templates/public/pages/active_nodes.mako
Rename "Newest Public Projects" to "New and Noteworthy" on "new projects" tab
https://openscience.atlassian.net/browse/OSF-7325
=> [Feature] Rename newPublicProjects menu item [OSF-7325]

website/static/css/pages/profile-page.css, website/static/js/profile.js, website/templates/include/profile/social.mako
Fix social profile rendering of long urls
1) Make personal website url to span 2 table cols
2) Add css to fix long url wrapping issue on preexisting urls.
N/A
[OSF-6722](https://openscience.atlassian.net/browse/OSF-6722)
- With a user with long social profile urls such as [dhyac](https://osf.io/dhyac/), please check the responsiveness of this table across screen sizes and browsers; not very sure how it renders in IE.
=> [Feature] Fix social profile long url wrapping [OSF-6722]

framework/auth/views.py
Improve language for resend confirmation email alert.
https://openscience.atlassian.net/browse/OSF-7207
=> [Feature] Improve resend confirmation alert text [OSF-7207]

osf/management/commands/force_archive.py
Extend `force_archive` functionality
* Allow/revert `addon_file_moved` and `addon_file_renamed` for OSFS
* Improved logging
Script takes slightly longer to run
[[OSF-8182]](https://openscience.atlassian.net/browse/OSF-8182)
=> [Hotfix] Allow forcing additional file ops [#OSF-8182]

api/preprints/serializers.py, osf/models/preprint_service.py, tests/test_preprints.py, website/preprints/tasks.py, website/util/share.py
Reverts CenterForOpenScience/osf.io#7422
-----
In other words, restores #7243
Now that the SHARE side of this is ready, we can release the OSF side
=> Revert "Revert "[HOLD] SHARE subject serialization [OSF-7788]""

website/mailchimp_utils.py
- Handles MailChimp's `ListInvalidBounceMemberError` in `subscribe_mailchimp()`
- [OSF-8105](https://openscience.atlassian.net/browse/OSF-8105)
=> [hotfix] Handle MailChimp Error [OSF-8105]

api/preprints/serializers.py, osf/models/preprint_service.py, tests/test_preprints.py, website/preprints/tasks.py, website/util/share.py
Reverts CenterForOpenScience/osf.io#7243
=> Revert "SHARE subject serialization [OSF-8227]"

api/preprints/serializers.py, osf/models/preprint_service.py, tests/test_preprints.py, website/preprints/tasks.py, website/util/share.py
Reverts CenterForOpenScience/osf.io#7459
In effect: add back SHARE subject serialization.
=> Revert "Revert "SHARE subject serialization [OSF-8227]""

framework/auth/core.py, osf/models/__init__.py
Corrects high CPU utilization on DB server when performing OSFUser and Email filter.
Use a subquery to match on Email address.
None
None
=> [hotfix] Improve User Lookup Performance

api/base/serializers.py, api/users/serializers.py, api/users/views.py, api_tests/base/test_auth.py, framework/auth/oauth_scopes.py
- Use the correct string when checking request scopes... h/t @cwisecarver @icereval 
- None
=> [feature] Fix email_read Core Scope [No Ticket]

osf/models/user.py, osf_tests/test_user.py, tests/test_auth.py, tests/test_citations.py
Fix the test failure, and improve the user.cls_name logic
https://openscience.atlassian.net/browse/OSF-8272
=> [Hotfix][#OSF-8272]Probabilistic test failure -- CitationsUserTestCase.test_registered_user_csl

.gitignore, website/profile/views.py, website/project/views/node.py, website/settings/defaults.py, website/templates/profile.mako, website/templates/project/project.mako, website/templates/project/project_base.mako
Remove any lingering badges code. It has never been used, and no longer even exists in the addons/ directory.
- Remove code from templates
- Remove badges code from views
- Remove dead badges code from settings and .gitignore
https://openscience.atlassian.net/browse/OSF-8225
=> Remove dead badges code [#OSF-8225]

bower.json
Fix issue with travis builds
Bump academicons bower dependency to 1.8.0
=> [Feature] Bump academicons [No Ticket]

scripts/triggered_mails.py
- Fixes bad Django Q import in triggered_mails script.
=> [feature] Fix Django Q Import [No Ticket]

tests/test_identifiers.py, website/identifiers/metadata.py
Promotes https://github.com/CenterForOpenScience/osf.io/pull/7356 to a hotfix (see https://www.flowdock.com/app/cos/share-dev/threads/_Wi1QYkrR1MKKgWTRHwp-B-gs_7)
https://openscience.atlassian.net/browse/OSF-8131
=> [hotfix] Update Metadata Sent to EZID to include contributor GUID

osf/models/institution.py
Reverts CenterForOpenScience/osf.io#7540
=> Revert "[feature] Check saved_fields before updating institution in search [No ticket]"

api_tests/base/test_middleware.py
Fix TCI
* Rename duplicative test
* Use proper URL for validation
None expected
None known
=> [Hotfix] TCI

website/static/js/filepage/index.js
Fix UI issue
* Add special case
None expected
[[#OSF-8192]](https://openscience.atlassian.net/browse/OSF-8192)
=> [Feature] Hide `Force check in` for BitBucket [OSF-8192]

website/static/js/filepage/index.js
=> Fix JS Comparision

api/base/settings/__init__.py
Fix build, probable bug
* Construct `ORIGIN_WHITELIST`more carefully
None expected
None known
=> [Hotfix] Fix whitelist construction

website/static/css/nav.css, website/templates/nav.mako
Add donate to navbar.
Donate link added to navbar. Navigates to cos.io/donate.
None
https://openscience.atlassian.net/browse/OSF-8279
=> Feature/Add navbar donate link[OSF-8279]

tests/test_preprints.py, website/identifiers/metadata.py, website/util/share.py
=> Unify SHARE and datacite data export

docker-compose.linux.yml
[RFR] Update linux.override to match PR#7400
.docker-compose.linux.yml  Keeping up with the Jones'
None
[PR#7400](https://github.com/CenterForOpenScience/osf.io/pull/7400)
=> [RFR] Update linux.override to match PR#7400

docker-compose.override.yml
Update development docker-compose config for Ember apps.
1. Updated yarn link to use new NPM organization scoped name for ember-osf
2. Added registries-sync volume
N/A
N/A
=> Update docker-compose override for ember apps

website/templates/public/pages/support.mako
Update support email addresses from cos.io to osf.io on the support page
On https://osf.io/support/
before change:
After change:
https://openscience.atlassian.net/browse/OSF-7302
=> [#OSF-7302]Update support email addresses from cos.io to osf.io on the support page

api_tests/search/views/test_views.py
Fix issues with travis builds caused by api_tests/search (pytest) tests 
This issue is caused by multiple pytest (xdist) processes creating, searching, and deleting on same elastic_search db and index.
- Use per-test random uuid as elastic_search index (functional scope fixtures)
- Setup and teardown elastic_search index after each test
- Remove old cleanup and delete_all fixtures
There is still a very remote probability of [UUID collisions](https://softwareengineering.stackexchange.com/questions/130261/uuid-collisions)
[OSF-8390](https://openscience.atlassian.net/browse/OSF-8390)
=> [Feature] Fix elasticsearch issue in api_tests/search [OSF-8390]

website/static/js/osfHelpers.js
Some excess code got added to a pytest conversion (https://github.com/Nesiehr/osf.io/commit/f388d1e3501ac1c8fc19a67309c5218d0fa81830)
Revert those changes.
Fewer sentry errors.......
No Ticket
=> [no-ticket] Fix osfhelpers  bad merge

website/static/js/myProjects.js
I (unwittingly) used es6 style variable evaluation for key values. 
Cleans that up so karma tests don't break.
The S in ES6 stands for Sadness.
https://openscience.atlassian.net/browse/OSF-8084
=> [feature] Rework sparse fields in myProjects page [OSF-8084]

tests/test_registrations/test_embargoes.py, website/project/decorators.py
Reverts CenterForOpenScience/osf.io#7405
=> Revert "[feature] Embargoed Resources Custom Forbidden Page [OSF-5640]"

website/static/js/myProjects.js
Not enough fields being given causing names in components to get lost
Add bibliographic field and more name fields (to ensure consistency in name construction)
na
https://openscience.atlassian.net/browse/OSF-8084
=> [feature] My Project Page: Add more sparse fields to fix nested contributor names [OSF-8084]

api/preprints/serializers.py, api_tests/preprints/views/test_preprint_detail.py
Same as #7609 , but targeted for develop.
=> [Resend] Add title and contributors to preprint serialzier [OSF-8499]

CHANGELOG, package.json
0.120.0 changelog and package json
=> Update metadata for release

osf/management/commands/populate_custom_taxonomies.py
Make it easier to duplicate the entire BePress taxonomic tree for custom providers
* Add pargument
* Update control flow / validation logic
None expected
None known
=> Allow complete BePress duplication [No Ticket]

osf_tests/factories.py, osf_tests/test_archiver.py, scripts/analytics/addon_snapshot.py, scripts/analytics/institution_summary.py, scripts/analytics/node_log_events.py, scripts/analytics/node_summary.py, scripts/analytics/user_domain_events.py, scripts/analytics/user_summary.py, scripts/approve_embargo_terminations.py, scripts/approve_registrations.py, scripts/embargo_registrations.py, scripts/osfstorage/glacier_audit.py, scripts/populate_popular_projects_and_registrations.py, scripts/refresh_addon_tokens.py, scripts/retract_registrations.py, scripts/send_queued_mails.py, scripts/stuck_registration_audit.py, scripts/tests/test_addon_snapshot.py, scripts/tests/test_approve_embargo_terminations.py, scripts/tests/test_approve_registrations.py, scripts/tests/test_node_log_events.py, scripts/tests/test_node_summary.py, scripts/tests/test_populate_popular_projects_and_registrations.py, scripts/tests/test_send_queued_mails.py, scripts/tests/test_user_summary.py
Many of our regularly run scripts are using some modular odm queries - let's make things more consistent
- Move some Q queries to django Q queries
- Use django syntax where possible
- Fix unrun scripts tests for sanity checks on regularly run scripts
https://openscience.atlassian.net/browse/OSF-8313
=> Refactor scripts to use django queries [OSF-8313]

website/templates/util/render_addon_widget.mako
Buttons got lost in mod meta
Access the data properly
NA
https://openscience.atlassian.net/browse/OSF-8564
=> [hotfix] Fix broken wiki buttons [OSF-8564]

framework/status/__init__.py
Extends #7619 
* Save data change
None expected
[[OSF-8373]](https://openscience.atlassian.net/browse/OSF-8373)
=> Save deleted session status [#OSF-8373]

addons/base/views.py
Somehow missed some removals in #7529, here to fix that
- Remove Q queries
- replace MODM error checking
=> Convert addons base to django 

osf/management/commands/populate_custom_taxonomies.py
Simplify custom taxonomy creation process for providers with acceptable `subjects_acceptable`
* Update script
None expected
[[OSF-8558]](https://openscience.atlassian.net/browse/OSF-8558)
[[OSF-8563]](https://openscience.atlassian.net/browse/OSF-8563)
=> [Hotfix] Update custom taxonomy script [OSF-8558][OSF-8563]

tests/test_serializers.py, website/profile/utils.py, website/profile/views.py
Clean up
* Remove dead code
* Remove dead tests
None expected
[[OSF-8391]](https://openscience.atlassian.net/browse/OSF-8391)
=> Remove unused v1 user profile code [OSF-8391]

addons/owncloud/views.py
Fix bug
* Update possibly-changed fields
None expected
None known
=> [Hotfix] Update ownCloud account when updated

osf/management/commands/update_bepress_version.py
Keep our internal taxonomy up-to-date with BePress
* Add migration
None expected
[[OSF-8334]](https://openscience.atlassian.net/browse/OSF-8334)
[[OSF-8325]](https://openscience.atlassian.net/browse/OSF-8325)
=> [Hotfix] Update BePress version [OSF-8334][OSF-8325]

osf/management/commands/update_bepress_version.py
Improve script behavior
* Improve logic
* Improve logging
None expected
[[OSF-8334](https://openscience.atlassian.net/browse/OSF-8334)
=> [Hotfix] Update BePress update script

osf/management/commands/populate_custom_taxonomies.py
Allow automatic inclusion of used-but-missing subjects
* Add flag to automatically include used-but-missing subjects
None expected
[[OSF-8558]](https://openscience.atlassian.net/browse/OSF-8558)
=> [Hotfix] Update custom taxonomy script [OSF-8558]

osf/management/commands/update_bepress_version.py
Extends #7657
* Fix logic error
None expected
[[OSF-8334]](https://openscience.atlassian.net/browse/OSF-8334)
=> [Hotfix] Update BePress update script 2

website/templates/base.mako
Updates #7643 
* Conditionally use shim for IE, on the "My Projects" page
None expected
[[OSF-8381]](https://openscience.atlassian.net/browse/OSF-8381)
=> Use es6 shim iff IE [OSF-8381]

scripts/analytics/institution_summary.py
Institutions keen script did not like unicode.
Make it like unicode.
N/A
https://openscience.atlassian.net/browse/OSF-8609
No qa needed, just check that inst analytics work again.
=> [hotfix] Fix keen institutions unicode error [OSF-8609]

requirements.txt
Unblock #7662
http://docs.celeryproject.org/en/master/whatsnew-4.0.html#step-1-upgrade-to-celery-3-1-25
* Bump version
None expected
[[OSF-8619]](https://openscience.atlassian.net/browse/OSF-8619)
=> Upgrade celery to backwards/forwards-compatible version [OSF-8619]

osf_tests/test_search_views.py, website/project/views/node.py
- Return only projects which a user has access to from `api/v1/search/node/`
- Exclude public projects when `includesPublic=False` (i.e. when searching within "my projects" in the Add Links widget).
- Exclude quickfiles nodes.
- [OSF-8309](https://openscience.atlassian.net/browse/OSF-8309)
=> [feature] Exclude Public and QF Nodes in Search Node [OSF-8309]

docker-compose.linux.yml, docker-compose.override.yml
Bring docker-compose.linux.yml up to date with docker-compose.ovveride.yml
Fix fakeCAS entry in override.yml and linux.yml
None
None
=> [RFR] [No Ticket] Bring docker-compose.linux.yml up to date

website/static/js/citationList.js, website/static/js/citationWidget.js, website/static/js/pages/project-dashboard-page.js, website/templates/project/project.mako
Fix node dashboard's citation widget
* Revert JS file deletions from commit 8801d7a850fc5b28c31c5efd82603aece655991a.
* Remove unnecessary code
None expected
[[OSF-8623]](https://openscience.atlassian.net/browse/OSF-8623)
=> Partially revert "Remove AlternativeCitations" [#OSF-8623]

website/static/js/project.js
Templating a project was failing on staging 
<
- switch a `success` call to `done` to allow projects to be templated.
https://openscience.atlassian.net/browse/OSF-8643
=> Adjust beforeTemplate method to work with new jquery [OSF-8643]

website/project/views/drafts.py
- Return unique MetaSchemas and add back custom ordering.
- [OSF-8641](https://openscience.atlassian.net/browse/OSF-8641)
=> [feature] Fix MetaSchemas List on New Registration Page [OSF-8641]

addons/wiki/Dockerfile, addons/wiki/package.json
=> don't run sharejs as root

osf/management/commands/purge_test_node.py
Delete more better
* Only remove history / trashed data, retain current files / structure
None expected. Takes ~90 minutes to run on the offending node.
[[OSF-8616]](https://openscience.atlassian.net/browse/OSF-8616)
=> [Hotfix] Update purge command [OSF-8616]

api/base/filters.py
- Follow up fix to #7714 
- Don't overwrite queryset.query.distinct_fields, add to it instead ❤️ 
- I hope not.
=> [fix] Fix Ordering Filter distinct_fields 

framework/database/__init__.py
- Continuation of #7709 
- Check that request is within a transaction before using `select_for_update`
- [OSF-8297](https://openscience.atlassian.net/browse/OSF-8297)
=> [feature fix] Don't use select_for_update outside of a transaction [OSF-8297]

api/base/utils.py, framework/auth/core.py, framework/database/__init__.py, osf/utils/requests.py
- See #7720 
- Move request and transaction checks into a helper function.
- [OSF-8297](https://openscience.atlassian.net/browse/OSF-8297)
- [OSF-8683](https://openscience.atlassian.net/browse/OSF-8683)
=> [feature fix] select_for_update outside of atomic transactions [OSF-8297][OSF-8683]

addons/bitbucket/README.md, addons/box/README.md, addons/dataverse/README.md, addons/dropbox/README.md, addons/figshare/README.md, addons/github/README.md, addons/googledrive/README.md, addons/mendeley/README.md, addons/s3/README.md, addons/zotero/README.md
Update add-on documentation for local installation.
Updated documentation for bitbucket, box, dataverse, dropbox, figshare, github, googledrive, mendeley, s3, and zotero
Just a documentation change, should be none.
https://openscience.atlassian.net/browse/SVCS-473
=> Update Add-on local install documentation

website/templates/project/registrations.mako
- Fix registration schema selection in the create registration modal.
- Same as 600239034d3467e1d567e39502c28fe5c5a97db9: needed a colon 😑 
- [OSF-8641](https://openscience.atlassian.net/browse/OSF-8641)
=> [feature fix] Fix Registration Modal [OSF-8641]

addons/s3/views.py
Fix bug
* Update credentials when provided with new key for account
None expected
[[OSF-8733]](https://openscience.atlassian.net/browse/OSF-8733)
=> [Hotfix] Update S3 creds when updated [OSF-8733]

website/static/js/folderpicker.js
Empty buckets break things and look like they load forever.
Make empty buckets not error.
NA
https://openscience.atlassian.net/browse/OSF-8745
Check that setting up an S3 account with an empty bucket don't break things. I can give you credentials to my empty s3 buckets when you need em.
=> [hotfix] Fix s3 buckets import [OSF-8745]

website/templates/nav.mako
Add My Quick Files link to nav bar
Add My Quick Files link to nav bar mako template
None
https://openscience.atlassian.net/browse/EOSF-823
=> Added My Quick Files link to nav bar

osf/management/commands/migrate_file_view_counts_from_keen.py
Rename the file and fix the function call.
https://openscience.atlassian.net/browse/OSF-8174
=> [#OSF-8174]Make file view counts through OSF file storage available through the API

reviews/models/mixins.py
Fix celery issue.
Remove state machine property from preprint so it can be serialized.
https://openscience.atlassian.net/browse/MOD-127
=> [MOD-127][Fix] Remove machine property

website/templates/project/project_base.mako
Works some of the time, but not good enough
Introduced in #7784
=> Remove async attr from MathJax script

reviews/models/mixins.py
=> [Fix][MOD-128] Follow up PR for email notifications

CHANGELOG, package.json
=> Update changelog and version number for 0.122.0

website/templates/emails/reviews_submission_status.html.mako, website/templates/emails/reviews_submission_status.txt.mako
Include language about comment for pre-moderation too.
Check for comment for both pre-moderation and post-moderation.
None
https://openscience.atlassian.net/browse/MOD-153
=> [MOD-153][Fix] Update status change email so notify comment is always checked

scripts/generate_sitemap.py
First 10 sitemap errors are now logged to sentry for quick access (and as a fun canary in the coal mine for bad data in the db). However, the errors generated are not easily identifiable.
Prepend the sitemap errors with "Sitemap Error" to make them easily found
NA
https://openscience.atlassian.net/browse/OSF-8822
No QA needed
=> [hotfix] Prepend Sitemap Errors with "Sitemap Error" [OSF-8822]

website/templates/emails/reviews_resubmission_confirmation.html.mako, website/templates/emails/reviews_submission_confirmation.html.mako
Don't have conflicting wording in the emails.
* Don't say user will get email if no_future_emails
* Format emails
None
https://openscience.atlassian.net/browse/MOD-151
=> [MOD-151][Fix] Don't say user will get email if no_future_emails

website/templates/emails/reviews_submission_status.html.mako
Fix rejected wording.
pre-moderation is_rejected:
You may edit the preprint and resubmit," --> "Admins may edit the preprint and resubmit."
post-moderation is_rejected:
"Admins may edit the preprint and resubmit." --> "Admins may edit the preprint and contact the moderator at [email] to resubmit."
None
https://openscience.atlassian.net/browse/MOD-154
=> [MOD-154][Fix] Fix rejected wording

admin/preprint_providers/views.py, osf/management/commands/populate_custom_taxonomies.py
Fix Travis
* Populate global during `Command.handle`
* Update admin to use `call_command`
None expected
=> [TCI] Populate global during Command.handle [No Ticket]

osf/models/sanctions.py, tests/test_registrations/test_embargoes.py
Clicking the email link to stop an embargo from turning into a registration after an embargo time has ended (or manually cancelling it) can delete the registration.
Add a check for is_public to the token handling and throw error if the project is public when it occurs (it should not be public when the link is valid)
NA
https://openscience.atlassian.net/browse/OSF-8840
Make sure normal embargoes work
Make sure clicking the original emails link after the embargo is removed and the registration is public does not delete the registration.
=> [hotfix] Stop embargo reg deletions [OSF-8840]

yarn.lock
Update yarn.lock, fix travis failure
Generate new yarn.lock
=> [Feature] Update yarn.lock

Dockerfile
=> Use default home directory for user www-data

README-docker-compose.md
[NO-TICKET]
Update README replace tukumx reference with mongo
=> Udate README-docker-compose.md s/tukumx/mongo/

docker-compose.override.yml, website/settings/local-dist.py, website/settings/local-travis.py
Update the yml files for local dev env setups.
1. In `docker-compose.override.yml`, command for `emberosf`, `preprints` and `registries` are changed to make sure `node_modules` and `bower_components` folders are deleted upon restarting the container.
2. In `docker-sync.yml`, the name for local repo of preprints container is changed to reflect recent changes to the remote repo name.
None.
https://openscience.atlassian.net/browse/OSF-8848
=> [OSF-8848] Update docker and docker sync settings for ember

website/static/js/nodesDelete.js, website/templates/project/nodes_delete.mako, website/templates/project/project_base.mako
Change the language and redirection of deletion modal.
Conditionals are added to show the correct language for projects vs. components.
Redirection are change. Now it should redirect to parent's overview page if a component is deleted.
None.
https://openscience.atlassian.net/browse/OSF-8516
=> [OSF-8516] Change language and redirection for delete modal of nested projects and components.

website/static/js/fangorn.js
Allow (back) open same file in multiple tabs.
Removes front-end hotfix that prevents users from opening
same file in multiple tabs as the main issue was fixed in the backend.
[OSF-8780](https://openscience.atlassian.net/browse/OSF-8780)
=> [feature] Allow opening same file in multiple tabs [OSF-8780]

addons/googledrive/README.md
Update read me file for tip on increasing rate limit.
=> [RFR] Update addons/googledrive/README.md with rate limit tip

docker-compose.yml
Add wb_flower service to docker-compose.yml
For Celery troubleshooting
Listens at port 5556
None
[SVCS-335](https://openscience.atlassian.net/browse/SVCS-335)
=> [RFR] [#SVCS-335] Add wb_flower service to docker-compose.yml

docker-compose.linux.yml
[NO-TICKET]
Update linux override for several mac updates
=> Update linux override for several mac updates

.travis.yml
=> [hotfix] random traivs fix

website/templates/nav.mako
There are some elements unable to find on the navbar for selenium tests. Add id to them to make them more easier to be found.
Add unique id to navbar 'search', 'support' and 'donate' link.
https://openscience.atlassian.net/browse/OSF-8789
=> [#OSF-8789]SEL:Dashboard Page- Signed In--Top navigation bar

framework/celery_tasks/__init__.py, framework/celery_tasks/routers.py, website/settings/defaults.py, website/settings/local-dist.py, website/settings/local-travis.py
Configuration updates from #7662
* Moves [celery configuration into a class](http://docs.celeryproject.org/en/latest/userguide/application.html?highlight=config_from_object#configuration)
* Uses newer [lowercase names](http://docs.celeryproject.org/en/latest/userguide/configuration.html#new-lowercase-settings) for Celery >=4
* Requires changes to local.py in all environments
=> Celery Config Fixes

osf/models/node.py, osf_tests/test_node.py
Return the correct set of ids
* Return the correct set of ids
None expected
None known
=> [Hotfix] Correct Admin contributor ids [No Ticket]

api_tests/nodes/views/test_node_detail.py, osf/models/node.py, osf/models/preprint_service.py, reviews/models/mixins.py, website/identifiers/listeners.py, website/preprints/tasks.py
Fix preprint create / update
* Don't send complex objects to celery
None expected
None known
=> Send ids to celery tasks

addons/bitbucket/api.py
Show more repos to users when selecting one to link.
* Provide the [max pagination size](https://developer.atlassian.com/bitbucket/api/2/reference/meta/pagination)
None expected
[[OSF-8977]](https://openscience.atlassian.net/browse/OSF-8977)
=> [Hotfix] List more than 10 BitBucket Repos [#OSF-8977]

osf/models/node.py, osf_tests/test_node.py
Be better.
* Ensure `NodeRelation`s exist when they need to
None expected
[OSF-8993](https://openscience.atlassian.net/browse/OSF-8993)
=> [Hotfix] Fix roots for Forks/Templates [OSF-8993]

framework/postcommit_tasks/handlers.py
Celery was turning tasks in the postcommit celery queue into dictionaries when being passed in a chain, so we needed to de-serailze them into tasks again before they could be applied.
developed with @sloria!
- de-serailize tasks before applying the chain
https://openscience.atlassian.net/browse/OSF-8992
=> Deserialize signatures in postcommit_celery_queue [OSF-8992]

addons/gitlab/models.py, addons/gitlab/templates/gitlab_user_settings.mako, website/notifications/constants.py, website/static/js/fangorn.js
Make things better
* Fix "version caching" issue
* Fix bad settings link
* Fix file comments
* Fix fangorn drag&drop
None expected
[[OSF-8169]](https://openscience.atlassian.net/browse/OSF-8169)
=> [Feature] Fix GL bugs [OSF-8169]

website/preprints/tasks.py
Arg got lost in a merge a while back. Needs to be added.
Arg is  back. horray.
NA
https://openscience.atlassian.net/browse/OSF-8999
No QA, would require killing share to test and is low risk.
=> [hotfix] Fix async share retry [OSF-8999]

admin/templates/preprint_providers/enter_custom_taxonomy.html
[#OSF-8559]
Add a bit more clarity about when you need to include a stand-in custom mapping
one more line of documentation for the admin tool
nope
https://openscience.atlassian.net/browse/OSF-8559
=> Custom tax form - Add a note about non-included custom mappings [OSF-8559]

website/static/css/style.css, website/templates/include/comment_pane_template.mako, website/templates/project/project.mako, website/templates/project/project_header.mako
Fix the way project title and (make public) menu wrap.
Drop the menu below the project title for all screens
except large screen.
[OSF-8814](https://openscience.atlassian.net/browse/OSF-8814)
**after PD**
=> [feature] Fix wrapping [OSF-8814]

website/templates/emails/no_login.html.mako
Improve engagement with better email that links to COS help resources.
Adds static html links
<div style="margin: 40px;">
<br>
Hello ${fullname},
<br><br>
We’ve noticed it’s been a while since you used the Open Science Framework (OSF). We are constantly adding and improving features, so we thought it might be time to check in with you.
Most researchers begin using the OSF by creating a project to organize their files and notes. Projects are equipped with powerful features to help you manage your research:
<br>
<ul>
<li>You can keep your work private, or make it public and share it with others</li>
<li>You can use the wiki to live-edit content with your collaborators</li>
<li>You can connect to third-party services like Dropbox or Google Drive</li>
</ul>
To get started now, visit your …
=> [OSF-8268] Update language in engagement email

osf_tests/test_elastic_search.py, website/search/elastic_search.py, website/static/js/search.js, website/templates/project/modal_add_contributor.mako
Give user's profile information on search
before change:
after change:
https://openscience.atlassian.net/browse/OSF-8510
=> [#OSF-8510]Search by contributor's profile information

website/static/js/home-page/quickProjectSearchPlugin.js
Change the placeholder text
before change:
after change:
https://openscience.atlassian.net/browse/OSF-8728
=> [#OSF-8728]Change placeholder text in dashboard search box

website/templates/public/register.mako
Change the style of login through institution and fix the title for sign up page.
before change:
After change:
https://openscience.atlassian.net/browse/OSF-8849
https://openscience.atlassian.net/browse/OSF-8226
=> [#OSF-8849]Make institutional login more prominent

website/static/js/fangorn.js
People want to open multiple tabs from the the files page using Fangorn (me included.) This simple fix allows the users to open tabs by right clicking.
Simple js fix to Fangorn
https://openscience.atlassian.net/browse/OSF-7832
=> [OSF-7832] Make right click enable 'Open in New Tab' option in menu.

website/templates/emails/welcome.html.mako, website/templates/emails/welcome_osf4i.html.mako
Remove .com from box and ad owncloud
before change:
After change:
https://openscience.atlassian.net/browse/OSF-7792
=> [#OSF-7792]There should not be a link to Box.com in the Welcome to the OSF email

website/util/rubeus.py
=> Get rid of mutable default

website/util/rubeus.py
=> Fix test for rubeus

PULL_REQUEST_TEMPLATE.md
- To improve Amanda and Allison's quality of life.
=> Add "QA Notes" to Pull Request Template

website/templates/project/statistics.mako
WIth all the changes being made on the analytics page an extra </div> weaseled it's way into the changes, this removes it.
Removes superfluous tag and indentation.
Make sure to test with error banners and keen being populated with graphs.
https://openscience.atlassian.net/browse/OSF-8055
=> [OSF-8055] Fix HTML on analytics page.

website/templates/project/view_file.mako
h/t @alexschiller
Fix misnamed variable in view_file template
profile_image_url --> profile_image
Combine with testing for PR7629
None
[OSF-4338](https://openscience.atlassian.net/browse/OSF-4338)
=> Fix misnamed variable in view_file template

website/static/js/fangorn.js
Reverts CenterForOpenScience/osf.io#7395
=> Revert "[OSF-7832] Make right click enable 'Open in New Tab' option in menu."

website/project/views/node.py
Reverts CenterForOpenScience/osf.io#7975
=> Revert "[OSF-8056] Ensure Addon tab JS assets load properly "

website/project/views/node.py
Reverts CenterForOpenScience/osf.io#7973
=> Revert "Check if asset path exists for addons"

website/project/views/node.py
Reverts CenterForOpenScience/osf.io#7978
=> Revert "Revert "Check if asset path exists for addons""

website/templates/public/register.mako
Reverts CenterForOpenScience/osf.io#7867
=> Revert "[#OSF-8849]Make institutional login more prominent"

website/static/js/fangorn.js
Fix issue with renaming file caused by PR https://github.com/CenterForOpenScience/osf.io/pull/7723/
Add checks to make sure rename operation is not treated same way as
copy or move operation.
See main PR for this ticket at PR https://github.com/CenterForOpenScience/osf.io/pull/7723/
NA
[OSF-6466](https://openscience.atlassian.net/browse/OSF-6466)
=> [Feature] Fix fg issue with renaming files [OSF-6466]

osf_tests/test_registrations.py
Allowance for  registration test is too low and fails when travis is slow
up allowance from 3000 to 10000
NO QA, test fix only
NA
https://openscience.atlassian.net/browse/OSF-9050
=> [feature] Increase allowance for registered date [OSF-9050]

osf/migrations/0074_parse_citation_styles.py
Fix 'conflicts' arising from new use of recently-removed function
* Remove uses of `remove`
None
None expected.
None known
=> [DjangoLE] Fix TCI

website/templates/include/comment_pane_template.mako, website/templates/project/project_header.mako
Settings sometimes pulled right. Comments showed up at wrong time. 
1. Remove unneeded class
2. Stop comments button showing up when md, make comments icon show up on md
1. Check horizontal scaling on comments button.
2. Settings button shouldn't try and shift to the right anymore
NA
https://openscience.atlassian.net/browse/OSF-9056
=> [Feature] Fix navbar issues [OSF-9056]

osf/migrations/0074_parse_citation_styles.py
Reverts CenterForOpenScience/osf.io#8023
=> Revert "[REVERT][OSF-3622] Add migration file to automatically parse citations""

api/base/filters.py
Patch regression
* Use distinct
Check `/v2/preprints/` and ensure there are no dupes
None expected.
[[OSF-9058]](https://openscience.atlassian.net/browse/OSF-9058)
=> [Hotfix] Distinct preprints [OSF-9058]

api/nodes/views.py
- Fix duplicate files being returned from `NodeFilesList`
=> [hotfix] Fix Duplicate Files [No ticket]

api/base/filters.py, api_tests/institutions/views/test_institution_nodes_list.py, api_tests/nodes/filters/test_filters.py, website/static/js/pointers.js, website/templates/project/modal_add_pointer.mako
Follow up for https://github.com/CenterForOpenScience/osf.io/pull/7457
to address issues found in QA testing 
- Fix filtering when you have multiple filters
- Update tests
- Clear on modal exit or when user clicks `done`
- Clear errors and warnings upon successful linking
[OSF-5360](https://openscience.atlassian.net/browse/OSF-5360)
=> [feature] Fix multiple filtering, add tests, modal ui [OSF-5360]

osf/admin.py
groups and user_permissions disappeared on admin admin
Add em back
Make sure both user_permissions and groups can be modified on admin
NA
https://openscience.atlassian.net/browse/OSF-7784
=> [feature] Fix groups in adminadmin [OSF-7784]

scripts/populate_institutions.py
=> [HotFix] Update Banner Description for UA [No Ticket]

website/conferences/utils.py
Uploads are getting an extra leading slash which is causing problems.
Only add a slash if there isn't one already
Sufficient test plan already in place.
NA
https://openscience.atlassian.net/browse/OSF-8696
=> [feature] Add leading slash only if none exists [OSF-8696]

website/static/js/pages/project-dashboard-page.js
Adding of tags to registrations was enabled in this release, but there is JS to disable removing of tags on registrations. 
Remove that
Confirm that write contributors on a registration can delete tags. Confirm non-write contributors cannot delete tags.
https://openscience.atlassian.net/browse/OSF-8691
=> [feature] Allow deleting of tags on registrations [OSF-8691]

CHANGELOG, package.json
Update changelog and package.sjon
=> New version 0.126.0

addons/wiki/static/ShareJSDoc.js, website/static/js/pages/ShareJSDocFile.js
=> Fix jshint

scripts/fix_user_mailchimp.py
Add a script to sub users to OSF general mailchimp for whose users who created during the double-opt-in mailchimp error.
https://openscience.atlassian.net/browse/OSF-9101
=> [#OSF-9101]Error when subscribing to mailchimp: "Due to restrictions on your account, double opt-in is required for this list"

tests/test_mailchimp.py, tests/test_views.py, website/mailchimp_utils.py
Revert Double Opt In for OSF General List/MailChimp
https://openscience.atlassian.net/browse/OSF-9107
=> [#OSF-9107]Revert Double Opt In for OSF General List/MailChimp

osf_tests/test_archiver.py, osf_tests/test_queued_mail.py, osf_tests/test_remind_draft_preregistrations.py
=> [Hotfix] Skip some failing tests [OSF-9095]

README-docker-compose.md
Update README for Linux Preprint development. 
Update REAME-docker-compose.md
None
None. README update for Linux.
=> [RFR] [README] Add note for fs.inotify.max_user_watches in README for Linux installs

osf/exceptions.py, requirements.txt, tests/test_files/test_views.notarealfileextension
Remove MODM 
* Replace multi-inheritance exceptions with aliases
* Remove dependency
There are still other places where we reference Toku/MODM compat things unnecessarily (a quick grep through the code reveals about two dozen places). Consider follow-up ticket to clean those places up
None
None expected
[[OSF-9063]](https://openscience.atlassian.net/browse/OSF-9063)
=> [Feature] Remove modm [OSF-9063]

website/util/rubeus.py
Prevent infinite recursion for edge cases on the files page. 
h/t @mfraezz for discovering the exact edge case. 
Keep track of visited nodes in recursive function to break before infinite recursion occurs. 
Given the following project structure, make sure the files grid loads when logged out and that an error isn't sent to Sentry:
* Public parent project
* Private child component
* Private grandchild component 
* Public great-grandchild component
* Link to private child component
=> [hotfix] Fix Files Page Recursion [No ticket]

website/views.py
Wrapping at exactly 150 characters add the ... when it didn't need to. 
Add inclusive <= for the max length.
AFTER 150 Characters:
AFTER 151 Characters:
Retest ticket, just fixing edge case.
NA
https://openscience.atlassian.net/browse/PAT-267 -->
=> [PLAT-267] Fix description truncating at 150 chars

package.json, yarn.lock
Update to latest published version of osf-style (1.6.0)
`yarn upgrade @centerforopenscience/osf-style@1.6.0`
No QA, already tested
None
N/A
=> Update to osf-style@1.6.0

website/templates/prereg_landing_page.mako
Pregistration (definitely not a word) -> Preregistration (definitely a word)
https://openscience.atlassian.net/browse/PLAT-630
=> [feature] Fix Prereg Typo [PLAT-630]

website/project/metadata/ridie-complete.json, website/project/metadata/ridie-initiation.json, website/project/metadata/ridie.json, website/project/metadata/schemas.py
This PR mainly consists of two json files for RIDIE registration forms.
https://openscience.atlassian.net/browse/PLAT-367
=> [PLAT-367][OSF] RIDIE registration forms

website/templates/nav.mako
Avoids an unnecessary route transition in Ember, which speeds up loading.
Adds the `user_id` to the route for "My Quickfiles" in the navbar
=> Use user_id in quickfiles route

website/templates/emails/notify_base.mako
Fix digest emails
Digest email doesn't have node information which is reasonable as it can have multiple nodes actions happen in one digest email. Add the condition to check if node information is passed into the email template.
Now all transactional and digest email should work correctly.
No ticket
=> [no ticket] fix digest email

api/nodes/serializers.py, website/templates/project/retracted_registration.mako
Change the text on the retracted registration to be "Identifier: DOI <doi>"; "Identifiers: DOI <doi> | ARK <ark>"
https://openscience.atlassian.net/browse/PLAT-331
=> [#PLAT-331]Show DOIs on Withdrawn Registrations

addons/base/views.py, addons/osfstorage/models.py
Correct the naming of  the check for the right prereg permission.
https://openscience.atlassian.net/browse/PLAT-53
=> [PLAT-53]Prereg files remain checked out after user deletes their draft registration

website/notifications/tasks.py
This PR didn't pass the node into the Digest email template properly. This PR fixes that.
- minor python change.
Check the digest email, it should have the link now.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-627
=> [PLAT-627] Fix Update email prefs

addons/wiki/templates/edit.mako, website/routes.py, website/templates/project/project_base.mako
Include mfr.js for dynamic sizing.
- Includes mfr.js for dynamic sizing
- add mfr_url to view
https://openscience.atlassian.net/browse/PLAT-493
=> [PLAT-493] Includes mfr.js for dynamic sizing

framework/auth/campaigns.py, tests/test_campaigns.py, website/static/css/registration_landing.css, website/static/js/pages/reg-landing-page.js, website/templates/prereg_landing_page.mako, website/templates/public/register.mako, website/templates/registered_reports_landing.mako
There were a few responsive design and alignment problems found by QA and some "nice-to-have" validation and design fixes they wanted this PR addresses those.
- Makes alignment consistent for smaller windows.
- Marginalizes buttons at consistent height.
- make text align left properly inside lower boxes
- Visually disables create project button.
- Removes caret icons.
QA has detailed what they are looking for in the ticket.
https://openscience.atlassian.net/browse/PLAT-216
=> [PLAT-216] Fix onboarder alignment and more

addons/wiki/static/dragNDrop.js, addons/wiki/static/pagedown-ace/Markdown.Editor.js
Fix MFR from breaking when loading ace.js
- move statement to prevent drag and drop from having import side effects.
https://openscience.atlassian.net/browse/PLAT-493
=> [PLAT-493] Fix MFR from breaking when loading ace.js

addons/wiki/static/dragNDrop.js, addons/wiki/templates/edit.mako, website/static/css/pages/wiki-page.css, website/static/js/fangorn.js
Response to QA feedback
- changes fargorn growl language
- updates pulsers
check that:
- the replace language to fangorn is updated.
- The pulser are the right kind and pulse properly.
https://openscience.atlassian.net/browse/PLAT-486
=> [PLAT-486] Dnd editor fix pulsers and language.

framework/status/__init__.py, website/ember_osf_web/views.py
=> Make sure existing sessions statuses dont break

api_tests/wikis/views/test_wiki_detail.py
- Update permissions import in wiki tests.
- Fix release/next-platform build.
=> Fix permissions import

admin/templates/metrics/osf_metrics.html
- Adds chart notes and fixes a typo.
https://openscience.atlassian.net/browse/PLAT-773
=> [feature] Add chart notes and fix typos in admin metrics [PLAT-773]

website/profile/views.py
Make reset password token expired when user change their password in user's account settings.
Change the expire time of the reset password token to be the moment user changes their password.
1- Create a osf.io account
2- Confirm your email
3- Now request a password reset for your account.
4- Don’t use the password reset link that was sent to your email.
5- Login to your account, remember don’t use first the reset password link you requested in 3 step
6- Change your password in the Account Settings( url: https://osf.io/settings/account/
Step 5. After you changed your password inside your account, Check now the reset password link you requested in Step 3 in your email.
Step 6. Change your password using the reset password link you requested.
Before change:
You can still use the reset …
=> [#PLAT-656]Authentication Session Token Issue

osf_tests/test_elastic_search.py, website/search/elastic_search.py
Hide hierarchy on search results if parent is private
Before change:
After change:
1. Create a private project
2. Create a public component of that private project
3. go to search page and search for the public component
Before change:
After change:
https://openscience.atlassian.net/browse/PLAT-378
=> [#PLAT-378]Hide hierarchy on search results if parent is private
