CenterForOpenScience/osf.io

osf_tests/factories.py
tests/test_notifications.py
website/notifications/emails.py
website/notifications/tasks.py

This switches some map reduce mongo to SQL aggregations.
The user _id was being used for querying in mongo, I switched that to user instance because the other requires a join. I searched a bunch of different ways and only found two usages outside of tests. If I missed updating any of them they won't work.

Fix notification digest and it's tests

---

website/addons/figshare/client.py
website/addons/figshare/messages.py
website/addons/figshare/model.py

Prevent misleading `403`s and `404`'s.
* Ensure correct endpoints are hit
* Incidental: make messages reflect container type
None expected
https://openscience.atlassian.net/browse/OSF-7267

Fix Figshare Pageload Messages [OSF-7267]

---

api_tests/base/test_middleware.py
requirements.txt

- Upgrade django-cors-headers (will hopefully resolve [OSF-7225](https://openscience.atlassian.net/browse/OSF-7225)) 
- Bump version.
- Fix tests that should now be using a response object.
- [OSF-7225](https://openscience.atlassian.net/browse/OSF-7225)

[feature] Bump django-cors-headers Version [OSF-7225]

---

website/addons/figshare/model.py
website/addons/figshare/static/figshareAnonymousLogActionList.json
website/addons/figshare/static/figshareLogActionList.json
website/addons/figshare/tests/test_views.py

Fix figshare logging.
* Save `FigshareNodeSettings` object before `NodeLogger`'s call to `.get_addon` finds stale data
* Update log language
* Update test to ensure correct param is saved
The first `figshare_folder_selected` log added would have no folder-related params saved, causing the front-end to default to `a folder` for both `params.folder` and `params.folder_name`. Subsequent logs would have the params intended for the previous log.
Behavior is as expected.
[`[#OSF-6394]`](https://openscience.atlassian.net/browse/OSF-6394)

Fix figshare logging [OSF-6394]

---

scripts/analytics/base.py

Attribute error when calling analytics snapshots 
- Call analytics scripts directly from args instead of saving to variable 
- init_app without setting up URL routes

Change calling of entered scripts from args for analytics

---

framework/addons/data/addons.json
website/addons/figshare/static/figshareFangornConfig.js
website/addons/figshare/views.py
website/static/js/fangorn.js
website/static/js/tests/fangorn.test.js

The update to the Figshare v2 API means that a bunch of common fangorn features that weren't supportable before now work.
* Allow copying files and folders out of Figshare.
* Enable folder creation in Projects.
* Enable download button for all files & folders.
* Update Figshare delete logic. All private files and folders can be deleted.
* Update supported features modal.
None expected.
[#OSF-7272] - [JIRA](https://openscience.atlassian.net/browse/OSF-7272)

[CR] Figshare interface improvements [OSF-7272]

---

website/addons/figshare/static/figshareAnonymousLogActionList.json
website/addons/figshare/static/figshareLogActionList.json

Figshare is missing a log message for the create folder action. Add it.
Figshare's file_removed log message doesn't distinguish files and folders. Start doing so.
None expected.
No ticket.

figshare logs: add folder_created, correct file type

---

website/settings/defaults.py

This `TODO` should be a `TODONT`.
This comment was added in 2014 and is no longer accurate.  In fact, this setting is necessary, and GitLab stands a real chance of getting merged in the near future.  Let's not tempt anyone into doing something rash.
Remove comment from `website/settings/defaults.py`. No functional changes.
Future suffering may be reduced.
No ticket.

Delete inaccurate comment from default settings

---

api/base/middleware.py

h/t @chrisseto for this fix 
- Resolves [OSF-7225](https://openscience.atlassian.net/browse/OSF-7225)
- Remove `origin_not_found_in_white_lists()` inner function
- Store `request` on a local thread to be passed to `origin_not_found_in_white_lists()`
- [OSF-7225](https://openscience.atlassian.net/browse/OSF-7225)

Fix CorsMiddleware [OSF-7225]

---

scripts/migration/migrate_preprints_across_providers.py

Several preprints submitted to "Temporary Home of `<provider>`" were submitted to the wrong one. This fixes.
* Add script
None expected
None known

[hotfix] Add script to migrate preprints across providers

---

website/static/js/filepage/index.js

The file edit page displays 'Delete' and 'Edit' buttons for figshare.  Public files on figshare are not deletable, and no files are updatable.
* If the file is stored on figshare, don't initialize an editor instance.
* If the file is on figshare and is public, don't display the Delete button.
None expected.
[#OSF-5599] - [JIRA](https://openscience.atlassian.net/browse/OSF-5599)

no delete for public figshare files; no editing at all

---

api/files/serializers.py
api_tests/nodes/views/test_node_files_list.py

For APIv2 versions greater than 2.1, the `Node Files List` endpoint will 500 if there are files in the folder.
Bug fix on file serializer for date_created and date_modified fields. Only attempt to modify the date on versions > 2.1 if object is a file, not a folder.
https://openscience.atlassian.net/browse/OSF-7238

Feature/APIv2 500 Error on Node Provider [OSF-7238]

---

api/citations/utils.py
api/preprints/serializers.py
api/preprints/urls.py
api/preprints/views.py
api_tests/preprints/views/test_preprint_citations.py

- Adds citations to preprints. 
- Previously, citations only existed for a preprint's OSF node, which is not an accurate citation for the preprint as their GUIDs are different.
- Adds `/v2/preprints/<preprint_id>/citation/` endpoint
- Adds `PreprintCitationDetail` view
- Adds `PreprintCitationSerializer` class
- Adds `/v2/preprints/<preprint_id>/citation/<citation_style>/` endpoint
- Adds `PreprintCitationStyleDetail` view
- Utilizes the existing `NodeCitationStyleSerializer` class 
- Adds `citation` relationship field to `PreprintDetailSerializer` 
- Adds `preprint_csl()` and `display_absolute_url()` helpers to citation utils. 
- Adds preprint citations test file
- [OSF-7243](https://openscience.atlassian.net/browse/OSF-7243)

[feature] Preprint Citations [OSF-7243]

---

framework/mongo/utils.py
scripts/analytics/addon_snapshot.py
website/settings/defaults.py

The `run_keen_summaries` and `run_keen_snapshots` were having issues running. One was because of timing, the second because of a memory issue when paginating over too many nodes. This PR hopefully will fix those!
- Change `run_keen_summaries` to run at 1 am instead of 2am
- Modify the `paginate` util to check if a model is passed
- Iterate only using the `paginate` method instead of saving the results 
- Any use of `paginated` that is expected to fail if a valid model isn't passed will no longer fail....

Keen analytics improvements - addon snapshot memory use and celery task times

---

framework/mongo/utils.py
scripts/analytics/addon_snapshot.py

Not passing model to `paginated` should be a user error -- make better use of paginated instead by dealing with missing user and addon model settings
- paginated back how it was
- forward special cased counting
- check fr user and model settings

Put paginated back, instead deal with missing addon user and model settings

---

README.md
tasks/__init__.py

Elasticsearch is not pinned to the proper version. With recent update this broke search on machines with newer search installed.
Pins to 1.7, changes readme.
Might break people's previous install. 
Steps to fix:
1. brew uninstall elasticsearch
2. delete `/usr/local/bin/elasticsearch`
3. `brew install elasticsearch@1.7`
4. in osf venv `invoke rebuild_search`
[#OSF-7294]
https://openscience.atlassian.net/browse/OSF-7294

[feature] Pin elasticsearch version [OSF-7294]

---

website/static/js/search.js

The current URL for the number of share search results is deprecated and therefore always returns `0`. See ticket for screen shot.
Update the share search URL so that the count is accurate.
None
https://openscience.atlassian.net/browse/OSF-7262

[Hotfix] Update share search url [OSF-7262]

---

api/preprints/views.py

- Fix preprint citation 502s on staging.
- Remove `ContributorOrPublic` permissions class from preprint citation views as it expects a Node, Pointer, PreprintService, or AddonSettings object, not a dictionary describing a citation.
- Traceback causing the 502:
```
Traceback (most recent call last):
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
self.result = application(self.environ, self.start_response)
File "/Users/casey/.virtualenvs/osf/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
return self.application(environ, start_response)
File "/Users/casey/.virtualenvs/osf/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
response = …
```

[fix] Preprint Citations Permissions [OSF-7243]

---

api/preprint_providers/views.py

@sloria @cwisecarver 
There is no `is_deleted` field for `osf_preprints_provider`. Mongo does not complain in OSF but Postgres fails in Django-OSF.

[fix] [django-osf] Fix Default ODM Query for Preprint Provider [no ticket]

---

admin/static/css/keen-dashboards.css
admin/static/js/metrics/metrics.js
admin/static/js/pages/metrics-page.js
admin/templates/base.html
admin/templates/metrics/osf_metrics.html
admin/templates/sales_analytics/dashboard.html
admin/webpack.admin.config.js

OSF Admin Metrics changes, according to the needs and requests of the community team.  Redo the gathering of keen analytics in a new style and broken into new sections for clarity, speed, and usability.
- Revamp all calls to keen - now use the newer Keen dataviz  and analytics libraries
- Add a wide variety of new charts
- New chart organization
- add metrics-page that does the keen initializing and calls seperate analytics sections when a new tab is clicked
- All new layout, colors and organization.
- Removed link to old OSF Sales Analytics, as those charts aren't working at the moment.
Removed sidebar link to OSF Sales Analytics, so any documentation that says to look for that will be wrong. I left the page itself intact for now though. 
https://openscience.atlassian.net/browse/OSF-7253

Update Metrics on OSF Admin [OSF-7253]

---

scripts/analytics/node_summary.py

Right now Keen counts are including all collections - don't count those!!!
- don't include collections when querying for nodes
Numbers will jump down a lot! Will need to re-run node_summaries for these days!

Don't count OSF Collections while counting nodes and projects

---

website/static/js/filepage/index.js

The file page refuses to render text files larger than 64kb to avoid dumping masses of text into the user's browser.  There was a request to increase this limit to 200kb.  The corresponding setting in MFR has already been increased with the [v0.18.3 hotfix release](https://github.com/CenterForOpenScience/modular-file-renderer/commit/19afba382e7150659a9a0a43f031bacff692d36d).
Bump file view page render limit to 200kb.
None expected.
No ticket.

[hotfix] increase mfr render limit to 200kb

---

admin/templates/metrics/osf_metrics.html

Static assets not loading properly for the admin module metrics.js
Use `render_bundle` to load assets!

hotfix - use render_bundle to load metrics-page assets on admin metrics page

---

osf/models/licenses.py
website/project/licenses/__init__.py
website/search/elastic_search.py

Fix search for things with licenses.
Node serialization for ES was using `id` for licenses instead of `_id`. Now it uses `_id` and it works.
Search might work now. There could also be other bugs this doesn't cover.
https://trello.com/c/ikKIGc4t/95-search-results-empty

Fix licenses serialization for search

---

api/citations/views.py
osf/models/base.py

See title ^-^
Added an additional `elif` block to the BaseModel load method that forces lookups for basestring type queries to `_id`
It could break many things if primary keys are being sent in as basestring and django is automagically converting them to integers but I don't think it would do that because of blind faith.
https://trello.com/c/X4ztaboP/94-unable-to-get-details-for-citation-styles-on-staging3

Fix citation API endpoint lookup

---

addons/base/__init__.py
addons/base/apps.py
addons/box/__init__.py
addons/box/apps.py
addons/dataverse/__init__.py
addons/dataverse/apps.py
addons/dropbox/__init__.py
addons/dropbox/apps.py
addons/figshare/__init__.py
addons/figshare/apps.py
addons/forward/__init__.py
addons/forward/apps.py
addons/github/apps.py
addons/googledrive/apps.py
addons/mendeley/apps.py
addons/osfstorage/__init__.py
addons/osfstorage/apps.py
addons/owncloud/__init__.py
addons/owncloud/apps.py
addons/s3/__init__.py
addons/s3/apps.py
addons/twofactor/__init__.py
addons/twofactor/apps.py
addons/wiki/__init__.py
addons/wiki/apps.py
addons/zotero/__init__.py
addons/zotero/apps.py

Rename BaseAddonConfig to BaseAddonAppConfig well as rename subclasses of BaseAddonAppConfig.
This more clearly differentiates BaseAddonAppConfig from
website.addons.base.AddonConfig

Rename BaseAddonConfig -> BaseAddonAppConfig

---

addons/base/views.py
framework/transactions/context.py
scripts/README.md
scripts/approve_embargo_terminations.py
scripts/approve_registrations.py
scripts/embargo_registrations.py
scripts/populate_institutions.py
scripts/populate_new_and_noteworthy_projects.py
scripts/populate_popular_projects_and_registrations.py
scripts/populate_preprint_providers.py

In Django-land, we should use `django.db.transaction.atomic` rather than `TokuTransaction`.
- Change relevant usages of `with TokuTransaction()` to `with transaction.atomic()`.
- Modify `TokuTransaction` so that it behaves the same as `transaction.atomic` (just in case there are lingering usages in the legacy API)

Replace TokuTransaction with django.db.transaction.atomic

---

website/static/js/licensePicker.js

License picker does not stick around for non-admin users
Use saved license instead of selected license (which defaults to none?) and causes it to disappear.
None known
[#OSF-7331]
Try admin/write/read and not-logged in users to ensure proper viewing of license.

Stop license picker from disappearing [OSF-7331]

---

osf/tests.py
osf/utils/datetime_aware_jsonfield.py

https://sentry.cos.io/sentry/osf-back-end/issues/269425/
Switched from calling to_python which only runs when forms are used to using from_db_value which is called every time data is retrieved from the database.

Fix datetimeawarejsonfield decoding and add tests

---

website/static/js/myProjects.js
website/static/js/project-organizer.js

After the migration, guid routes changed for preprints. This PR fixes makes the preprints collection tab grab the working route to the preprint.
Pull in preprint data to the nodes that have a preprint. Populate the route with that data.
Not a direct side effect of this PR, but a possible further improvement/bug:
Currently each line of the my projects page is populated from a single node that has a preprint. This does not check if the node has multiple preprints (e.g., more than one provider that has a preprint file). This means that only the first preprint value will be displayed here. It seemed sufficiently out of scope of this ticket to attempt a fix at that.
[#OSF-7188]
https://openscience.atlassian.net/browse/OSF-7188
1. Make sure that the link created properly goes to the preprint …

[hotfix] Properly embed preprint url [OSF-7188]

---

api/logs/serializers.py

Prevent AttributeError from a `node.has_permission` check
* Handle unauthenticated users separately
None expected
No known Jira ticket. [Sentry error](https://sentry.cos.io/sentry/osf/issues/7948/)

[Hotfix] Avoid checking AnonymousUsers for _id

---

scripts/initialize_analytics.py

Fix `initialize_analytics` verification step
`'nin'` is not supported for CharFields, use multiple `'ne'`
None expected
None known

Prevent FieldError during key verification

---

api/base/views.py
api/registrations/serializers.py
api_tests/registrations/views/test_registration_linked_nodes.py
website/discovery/views.py
website/project/model.py
website/project/utils.py

Fix `AttributeErrors` relating to how `class Pointer` changed
`nodes_pointer` now returns a queryset of nodes, rather than of pointers. Don't access fields that don't exist.
None expected
[#OSF-7372](https://openscience.atlassian.net/browse/OSF-7372)

Update uses of `nodes_pointer` ThroughRelation [#OSF-7372]

---

tests/test_notifications.py
website/notifications/utils.py

Fix https://sentry.cos.io/sentry/osf-back-end/issues/269410/
Check if possible Object/NoneType has attribute before accessing it.
None expected
None known

Prevent AttributeError in `users_to_remove`

---

addons/base/views.py

Display files that have tags without erroring
Evaluate the queryset returned by `.values_list` into an actual `list`
None expected
[#OSF-7389](https://openscience.atlassian.net/browse/OSF-7389)

Fix file tag serialization [#OSF-7389]

---

api/nodes/serializers.py
api/preprints/serializers.py
api_tests/nodes/views/test_node_detail.py
api_tests/preprints/views/test_preprint_detail.py

Hotfox of #6774
> 
> ## Purpose
> Provide a useful error when `PATCH` an invalid `license`
> 
> ## Changes
> * Improve error handling
> * Add regression tests
> 
> ## Side effects
> None expected
> 
> ## Ticket
> [#OSF-7383](https://openscience.atlassian.net/browse/OSF-7383)

[Hotfix] Handle user error when patching licenses [#OSF-7383]

---

addons/s3/apps.py

Display S3 on settings pages
* Set `categories` for S3
None expected. Consider follow-up during Phase 2 to increase strictness of `AppConfig` definitions
[#OSF-7390](https://openscience.atlassian.net/browse/OSF-7390)

Add forgotten field to S3's AppConfig [#OSF-7390]

---

api_tests/nodes/views/test_node_contributors_list.py
osf/models/node.py

- Attempting to add an inactive merged user as a contributor on staging3/djangosf results in a 500 with the following (shortened) traceback:
```
api/nodes/serializers.py:799: in create
permissions=permissions, bibliographic=bibliographic, index=index, save=True
osf/models/node.py:1189: in add_contributor_registered_or_not
contributor_obj = self.contributor_set.get(user=contributor)
../../miniconda/envs/osf/lib/python2.7/site-packages/django/db/models/manager.py:122: in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
../../miniconda/envs/osf/lib/python2.7/site-packages/django/db/models/query.py:387: in get
self.model._meta.object_name
E   DoesNotExist: Contributor matching query does not exist.
```
- This PR fixes things so that the active merged user will be …

[OSF-7381] Fix Add Merged User Contributor

---

osf/models/node.py
osf_tests/test_node.py

Instead of doing a recursive query/cte, we just traverse up
the tree in Python. Though this is less performant, it is
much less bug-prone. Fixes [OSF-7378].
NOTE: Though the @cached_property decorator is used on `root`,
cached results only persist as long as the Node instance exists,
so it probably will not produce much benefit. We may want to
come up with a way to cache `root` across requests (ping
@cwisecarver for thoughts), but that may be unnecessary and can
happen in a separate PR.

Simplify implementation of AbstractNode.root; Fix [OSF-7378]

---

osf/models/node.py
osf_tests/test_node.py

Make node.objects.get_children stop killing the postgres server.
Switch from recursive CTE to python.
Node links will not be followed or returned by this implementation. This was my understanding of the correct behavior. That makes it so that you can never create at circular loop that will run until maximum recursion depth.
Places where this is likely to affect:
- Anything in the API using node filters on root
- Probably the bulk change privacy for node and its children that was updated a year or so ago
- Showing orphaned children in the file viewer and component list
- Institution affiliation settings for projects
[#OSF-7395](https://openscience.atlassian.net/browse/OSF-7395)

Fix Node.objects.get_children [OSF-7395]

---

tests/test_views.py
website/project/views/node.py

Turns out we do use the get_pointed view for the "View Links"
modal
fixes https://sentry.cos.io/sentry/osf-back-end/issues/269645/

Fix "View Links" button and unskip get_pointed tests

---

docker-compose.yml

Due to `invoke`'s [default behavior](https://github.com/pyinvoke/invoke/blob/master/invoke/program.py#L57) to not write any pyc files this causes notable performance issues when restarting apps.
The application code is not necessarily an issue, testing indicates the `/usr/local/lib/python2.7` shared main library needed to be compiled (this won't change in docker envs).
_NOTE: be sure to copy files with timestamps `-p` or `*.pyc` files will not be considered valid, but rather simply ignored._
**Requires a full rebuild of the docker environment due to volume changes.**
e.g. 
- `docker-compose down -v`
- `docker-compose up requirements mfr_requirements wb_requirements`
- `docker-compose run --rm web python manage.py migrate`
- `...` other database population scripts
- `docker-compose up -d …

Docker Shared Requirements Optimize for Python Byte Code

---

addons/base/views.py

Resolve a [sentry error](https://sentry.cos.io/sentry/osf-back-end/issues/269323/)
* Use default values if unsaved
* Serialize lists to JSON instead of complex objects
None expected
None known.
* Upload a file to OSFS but **_do not_** navigate to it.
* Navigate to its "`info`" page in APIv2. This can be found at `http://<api_domain>/v2/nodes/<node_id>/files/osfstorage/` under `data['links']['info']`
* Delete file in UI
* Navigate to the "`html`" link from the APIv2 "`info`" page (e.g. http://localhost:5000/xzsur/files/osfstorage/588a951b701add011bbdd804?revision=1)

Prevent ValueErrors in rare edge cases

---

addons/wiki/tests/test_wiki.py
addons/wiki/utils.py
tests/test_notifications.py
tests/test_views.py
website/notifications/utils.py
website/project/views/node.py

Children of nodes are being accessed in ways that recurse FOREVER.
Use a different method to get children.
None known.
[#OSF-7396]
https://openscience.atlassian.net/browse/OSF-7396
Test:
See setup in jira ticket. Things that should work now:
1. Changing privacy settings (component and project)
2. Wiki settings (on project settings page)
3. Email Notification Settings (on project settings page)
4. Adding a contributor (select components modal)

Use Node.objects.get_children to get node children [OSF-7396]

---

framework/encryption/__init__.py
tests/framework_tests/test_encryption.py

Names on Dropbox and Google drive break when we try to encrypt them.
1. Add helper function to ensure incoming strings to be encoded are in the proper utf-8 format
2. Add tests for helper function and encryption in general since it was untested.
None known
https://openscience.atlassian.net/browse/OSF-7200
[#OSF-7200]
1. Test auth on at least 1 addon. I did dropbox locally and it worked. Per MattF if it works for one, there is no reason it shouldn't work for all of them. Worth testing at least one or two for a sanity check, but probably not worth checking all of them (especially if you can't easily change your name on the service).
2. Change your name on <addon> to contain unicode madness and try to authorize the addon on the osf
3. Ensure it also works with non-unicode madness

[hotfix] Handle unicode in encryption [OSF-7200]

---

admin/base/migrations/0002_groups.py
admin/base/utils.py
admin/meetings/views.py
admin/nodes/views.py
admin/pre_reg/views.py
admin/spam/views.py
admin/templates/base.html
admin/templates/meetings/list.html
admin/templates/nodes/node.html
admin/templates/pre_reg/draft_detail.html
admin/templates/pre_reg/draft_list.html
admin/templates/spam/detail.html
admin/templates/users/user.html
admin/users/views.py

Right now there is no way to grant access to the OSF Admin app without granting access to everything. This PR adds a few new groups and makes use of new permissions to instead grant a few layers of access:
basic - can log in and see OSF Metrics
read only - can view information about nodes, users, and meetings but cannot perform any actions
admin - can view and modify things
prereg - can view prereg submissions but not perform any actions
prereg_admin - can view and provide feedback on prereg submissions
superuser - has access to all groups and modifications
This will use a combination of groups and specific edit permissions for each user. The groups a user is in will define which pages they can visit, while if a user specifically is given the `auth.admin` or `auth.prereg_admin` permission …

[Hotfix] Update admin groups and permissions to allow more layers of access [OSF-7359]

---

api_tests/nodes/views/test_node_children_list.py
api_tests/nodes/views/test_node_list.py
api_tests/registrations/views/test_registration_forks.py
osf/models/node.py
osf_tests/test_node.py
tests/test_views.py

When a node is both a component of a project and linked to from
another project, the node would *sometimes* appear twice when
calling AbstractNode#get_nodes() on either the parent project or the
linking project.
This filters out duplicates in `AbstractNode.get_nodes()`, but does so in Python, because there
is no way to both (1) ensure uniqueness of returned nodes and
(2) maintain ordering by NodeRelation._order in the same query.
- `AbstractNode.get_nodes()` and `AbstractNode.nodes` now return a list rather than a QuerySet. I verified that no application code treats the return values as a QuerySet.
- This is an ugly solution--I tried many different queries to do the filtering in SQL rather than in Python, but none produced the desired behavior 😞 
- The test added here is not sufficient to …

[feature fix] Prevent duplicates from appearing in node lists [OSF-7400]

---

admin/templates/base.html

The view of prereg in the sidebar was included in the if statement checking if they could see nodes and users information, preventing those who can see prereg but not nodes and users from seeing the prereg link.
- Move the if statement end to the appropriate place in base.html
nope

[hotfix ]Allow Admin users who ONLY have access to prereg to see this on the sidebar

---

README-docker-compose.md
docker-compose.ubuntu.yml

[SVCS-237](https://openscience.atlassian.net/browse/SVCS-237)
Get TomB's docker/django development setup on Ubuntu. Update Docs.
Update  README-docker-compose.md 
- docker/docker-compose install
- loopback alias
- alternative to docker-sync
Add docker-compose.ubuntu.yml
- Used in place of docker-compose.override.yml
None
[#SVCS-237]

Update docker compose and documentation for developement on Ubuntu [SVCS-237]

---

api_tests/registrations/views/test_registration_forks.py
osf/models/node.py
osf/models/sanctions.py
website/project/views/register.py

Prevent logs from linked nodes from appearing. 
- Pass `primary_only=True` when querying for a node's logs
- Passing a function to get_descendants_recursive was removed.
This fixes a few calls to use the newer primary_only parameter
Comment in https://openscience.atlassian.net/browse/OSF-7378

[feature fix] Don't show logs from linked nodes [OSF-7378]

---

webpack.common.config.js
website/static/js/pages/base-page.js

Fixes this error in local dev environments:
Don't initialize `DevModeControls` unless `website/static/built/git_logs.txt` exists

Prevent initializing DevModeControls if git_log.json doesn't exist

---

osf/utils/fields.py
osf_tests/test_external_accounts.py

#6766, but for Django
h/t @alexschiller 
>   1. Add helper function to ensure incoming strings to be encoded are in the proper utf-8 format
>   1. Add tests for helper function and encryption in general since it was untested.
None expected
[#OSF-7200](https://openscience.atlassian.net/browse/OSF-7200)

[Feature] Encrypt unicode properly for EncryptedTextFields [#OSF-7200]

---

osf/models/comment.py
osf/models/node.py
tests/test_serializers.py
tests/test_views.py
website/project/views/node.py
website/templates/util/render_node.mako
website/templates/util/render_nodes.mako

Optimize the views for reordering nodes and reordering contributors.
- Simplify the request payload for the reorder_contributors v1 endpoint
- Fetch all `NodeRelations`/`Contributors` then sort them based on the request payload. This means doing one query rather than n queries
- Minor cleanup: Remove unnecessary `link_id` view kwarg and `node_reference` DOM attribute
https://openscience.atlassian.net/browse/OSF-7426

Reduce number of queries when reordering contributors and nodes [OSF-7426]

---

admin/common_auth/views.py

Addendum to #6802
Common auth views hadn't been fully updated to restrict permissions. Let's do that!
- Switch order of inherited items to ensure permissions checking works
- Raise an exception when accessed by unauthorized user
none antipated

Small update to restrict permissions for user creation view

---

framework/auth/views.py
tests/test_views.py

For a new OSF user login through ORCiD for the first time, a temporary user is created with an `usable` password pending email confirmation. During the confirmation process set the password `unusable`:
```python
if not user.is_registered:
user.set_unusable_password()
user.register(email)
```
However, this violates `.is_active` check:
```python
self.is_active = (
self.is_registered and
self.is_confirmed and
self.has_usable_password() and
not self.is_merged and
not self.is_disabled
)
```
First, for "Flask" OSF on `master`, the password is set to an "usable password"m a hash of a random string: https://github.com/CenterForOpenScience/osf.io/blob/master/framework/auth/views.py#L496. This explains why Prod OSF works.
```python
if not user.is_registered:
user.set_password(uuid.uuid4(), …
```

[Fix] Do not set unusable password for new ORCiD created users [CAS-33]

---

osf_tests/test_node.py

Prevent random failures in `test_fork_recursion`
* Use `get_nodes`
None
None

[fix] Prevent random test failure

---

osf/models/node.py

Improve load time of logs
* Use already-optimized `Node.objects.get_children` instead of `get_descendants_recursive(primary=True)`, which does the same thing.
Rough benchmarking indicated this cuts query time to ~30% of what it currently is. Further improvements are likely possible, but converting `can_view` permissions checking to a sub-clause in an RCTE is Gehennic. This is ~90% of the benefit for ~1% of the effort.
None expected
None known

[Feature] Optimize get_aggregate_logs_query [No Ticket]

---

api_tests/nodes/views/test_node_list.py

There was some question previously about being able to get all "types" of preprints using the API preprint filter. 
The general understanding was that Preprints can be in a few states (from the linked Jira ticket)
1. Valid - has a published preprint with a non-orphaned file
2. Orphaned - has a published preprint with an orphaned file
3. Abandoned - has a non-published preprint, file status irrelevant
4. None - Has no preprints of any kind associated
2, 3, and 4 should be included when ?filter[preprint]=false, 1 for true
This PR adds a few tests that better ensure that these conditions are met, specifically for double checking **orphaned** and **abandoned** preprints
- tests to check that orphaned preprints appear in `filter[preprint]=False` and NOT in `filter[preprint]=True`
- tests to …

Additional Tests to reinforce API filtering for Preprints [OSF-7418]

---

website/project/views/drafts.py

Prevent multiple submissions of the same draft registration
* Check for an existing `DraftRegistrationApproval`, fail if found
None expected
[#OSF-7431](https://openscience.atlassian.net/browse/OSF-7431)

[Hotfix] Prevent multiple submissions of the same draft registration [#OSF-7431]

---

README.md

The currently used addon settings are now in the addons toplevel directory instead of inside the website directory
Description was wrong in the readme and it confused me!
- update path to find addon settings that are used on develop
nope
none

Update README to reflect new path for addon settings

---

framework/auth/campaigns.py

As requested: `preprint_providers = PreprintProvider.find(Q('_id', 'ne', None))` is replaced by ~~`preprint_providers = PreprintProvider.find()`~~.
Further replaced by `PreprintProvider.objects.all()` for Django-OSF.
No
No
https://openscience.atlassian.net/browse/OSF-7265

[fix] Update query in campaign initialization [OSF-7265] 

---

website/project/views/node.py

Fix sentry bug trying to load logs of a node that doesn't exist.
add `.exists()` to `node.logs` check.
None obvious.
https://openscience.atlassian.net/browse/OSF-7487

[RFR] Add `.exists()` check before using logs [#OSF-7487]

---

api/base/authentication/drf.py
api/base/exceptions.py

Branded Preprints Phase 2 relies on CORS making API calls with OSF cookie for authentication. This ticket revisits `api/base/authentication/drf.py` in the following aspects:
- verify cookie based authentication for API
- update user status check
- use native Django model and query
- update comments and doc string
https://openscience.atlassian.net/browse/OSF-7434

[Feature] Improve API DRF Authentication [OSF-7434]

---

framework/auth/core.py
scripts/set_null_usernames_to_guid.py
tests/models/test_user.py

Ensure uniqueness on the `User.username` field.
Instead of setting username to None, set to the GUID to
ensure uniqueness. Add a migration to fix existing users
whose username equals None.
https://openscience.atlassian.net/browse/OSF-7481

[OSF-7481] Ensure usernames are unique when user is merged

---

osf/models/user.py
osf/utils/datetime_aware_jsonfield.py

Serialize `DateTimeAwareJSONFields` properly in forms
* Add `DateTimeAwareJSONFormField`
* Set default formfield for `DateTimeAwareJSONField`
Incidental:
* Received a `ValidationError` when saving a `Tag`-less user after altering only a `DateTimeAwareJsonField`. `Tag` now has `blank=True`
[OSF-7494](https://openscience.atlassian.net/browse/OSF-7494)

Add FormField for DateTimeAwareJsonFields [OSF-7494]

---

osf/models/base.py
osf/models/node.py

Updates #6842, #6803 
h/t @cwisecarver 
* Put annotations on in the managers
* Expose previously exposed (with `.as_manager` magick) queryset methods on manager
* Set `_default_manager` on (most) models to have the Mixins included in related fields' mro
`<Node>.forks`, `<Node>.logs`, etc. are still being inefficient. `AbstractNode` is a `TypedModel`, and overriding the `_default_manager` leads to `save` calls on untyped objects. Inheriting from `TypedModelManager` on `AbstractNodeManager` did not change this. To be fixed, along with `OSFUserManager`, in a follow-up PR.
[[OSF-7462]](https://openscience.atlassian.net/browse/OSF-7462)

[Feature] Optimize guid queries (Update) [OSF-7462]

---

.travis.yml

Noticed my local builds were [erroring almost immediately](https://travis-ci.org/mfraezz/osf.io/jobs/201985167#L195).
This was because the 9.5.5 Postgres image we were using has disappeared from the [download page](https://apt.postgresql.org/pub/repos/apt/pool/main/p/postgresql-9.5/):
```
~/D/osf.io ❯ curl -SLO http://apt.postgresql.org/pub/repos/apt/pool/main/p/postgresql-9.5/postgresql-9.5_9.5.5-1.pgdg12.4+1_amd64.deb
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   345  100   345    0     0   2328      0 --:--:-- --:--:-- --:--:--  2331
~/D/osf.io ❯ file postgresql-9.5_9.5.5-1.pgdg12.4+1_amd64.deb
postgresql-9.5_9.5.5-1.pgdg12.4+1_amd64.deb: XML 1.0 document text, ASCII text
~/D/osf.io ❯ cat …
```

[Fix] Update TCI postgres image [No Ticket]

---

osf/models/base.py

Fix forking and GUID generation
Remove usage of `guid_string` from guid generation.
https://openscience.atlassian.net/browse/OSF-7508

[OSF-7508] Remove incorrect GUID generation code

---

osf/models/user.py

Follow-up to #6851 
* Annotate `OSFUser` queries with guid information
* ~~Strip query annotations on `.count`~~
* ~~Use query-annotating managers on related fields pointing to `GuidMixin`'d objects.~~
None expected
[[OSF-7516]](https://openscience.atlassian.net/browse/OSF-7516)

Update "Optimize guid queries (Update)" [OSF-7516]

---

website/templates/public/register.mako

* add missing title
* ~~update logo background~~
Must be merged at the same time with https://github.com/CenterForOpenScience/cas-overlay/pull/46.
- login and sign up page for AgriXiv is customized
- "create account" on login page -> sign up page
- "already have an account" on sign up page -> login page
https://openscience.atlassian.net/browse/CAS-39

[HotFix] Update Sign Up Page for AgriXiv [CAS-39]

---

scripts/migration/migrate_share_registration_data.py
website/preprints/tasks.py
website/project/tasks.py
website/settings/local-dist.py
website/templates/nav.mako
website/util/share.py

Update SHAre with registrations to use in ember app
Add hook to send new registrations to SHARE 
Migration to send current registrations to SHARE.
https://openscience.atlassian.net/browse/OSF-7324
This is the hotfix version of https://github.com/CenterForOpenScience/osf.io/pull/6710
This should send newly created registrations, once made public, to SHARE. To test, send a post request to `https://staging-share.osf.io/api/v2/search/creativeworks/_search` with this (slightly modified) payload.
```
{  
"query":{  
"bool":{  
"must":{  
"query_string":{  
"query":"*"
}
},
"filter":[  
{  
"terms":{  
"type":[  
"registration"
]
}
},
{  
"terms":{  
"sources":[  
"OSF" ? (might be something else, this can also be ignored
]
}
},
{  
"terms":{  
"registration_type":[  
<INSERT NAME OF THE …
```

[OSF-7324] Registries Migration to SHARE and hook

---

scripts/populate_preprint_providers.py

Now that AgriXiv has been contributing content to their preprint server, they need the example project link updated to https://osf.io/preprints/agrixiv/8whkp/ instead of the current one from OSF.
Update the populate_preprint_providrs.py script. Change the example entry from empty to 8whkp.
https://openscience.atlassian.net/browse/EOSF-515

Update AgriXiv example project [EOSF-515]

---

osf/management/commands/migraterelations.py

JYznd is a cased node id and the permissions migration for contributors was failing on it.
Created a lowercased, unicode version of node permissions and visible contributor ids and used those to do lookups against for contributor migration.
Unlikely.

[RFR] Work around case sensitive node id

---

docker-sync.yml

The latest release of docker-sync requires a "version" key in `docker-sync.yml`.

Fix compatibility with docker-sync 0.2.0

---

tests/test_models.py
website/project/model.py

...so that prereg drafts can be resubmitted
Fix a corner case that prevents some preregistration drafts from being submitted. This will happen when:
1. A prereg draft is submitted
2. Prereg is approved
3. Archiving fails, or the user rejects the registration
Under these conditions, the prereg draft fails to submit due to [these lines](https://github.com/CenterForOpenScience/osf.io/blob/930c225fdcb1f8d78452628e12eb8dbc73facdb6/website/project/views/drafts.py#L134-L135).
When an archive fails or the user rejects the registration, set the draft registration's approval to `None`.

[hotfix ] When an archive fails, set the draft registrations' approval to None

---

scripts/migration/resolve_multi_referent_guid.py

Fix dupes
* Add script
* In the event that a dupe is found in `_backrefs`, it won't be updated. This should be okay, as backrefs are no longer used.
[OSF-7531](https://openscience.atlassian.net/browse/OSF-7531)
This script requires a carefully-crafted input. A database dump must be grepped for dupes, and the correct objects selected for modification. Input for the case described in the ticket has been created, but there may be others.

[Hotfix] Fix dupes [OSF-7531]

---

api/wikis/serializers.py

* `repr` no longer exposes `._id`, so use `._id`
None expected
[[OSF-7530]](https://openscience.atlassian.net/browse/OSF-7530)

Fix NodeWikiPage path serialization [#OSF-7530]

---

website/templates/public/register.mako

Add missing title on the sign up page for SciELO and BITSS preprints
- if the two preprints goes before Django-OSF release, use this PR
- if after, rebase this to develop
Verify that sign in and login page for SciELO and BITSS has branded content.
https://openscience.atlassian.net/browse/OSF-7536
https://openscience.atlassian.net/browse/CAS-40
https://openscience.atlassian.net/browse/CAS-41

[HotFix] Add Missing Title on Sign-up Page for SciELO and BITSS [OSF-7536]

---

api_tests/collections/test_views.py
api_tests/nodes/views/test_node_list.py
api_tests/registrations/views/test_registration_list.py
api_tests/users/views/test_user_detail.py
api_tests/users/views/test_user_nodes_list.py
api_tests/users/views/test_user_registrations_list.py
framework/auth/core.py
scripts/migration/ensure_bookmark_uniqueness.py
tests/factories.py
tests/models/test_user.py
tests/test_auth.py
tests/test_models.py
tests/test_search/test_views.py
tests/test_test_utils.py
tests/test_websitefiles.py
website/notifications/listeners.py
website/project/model.py
website/views.py

Ensure/Enforce a 1-1 relationship between Users and bookmark collection Nodes
* Add migration to fix data
* Create users bookmark collection only when user is created
* Add commented-out uniqueness constraint
Uniqueness won't be enforced until #6905 is merged.
[[OSF-7551]](https://openscience.atlassian.net/browse/OSF-7551)

[Hotfix] Bookmark collection uniqueness [OSF-7551]

---

scripts/migration/ensure_bookmark_uniqueness.py

To be merged/ran before #6914 so that the auto-deploy doesn't destroy staging
`python -m scripts.migration.ensure_bookmark_uniqueness`
[[OSF-7551]](https://openscience.atlassian.net/browse/OSF-7551)

Port uniqueness script to django [OSF-7551]

---

website/static/js/home-page/quickProjectSearchPlugin.js
website/static/js/myProjects.js
website/static/js/osfHelpers.js
website/static/js/project-organizer.js
website/static/js/tests/osfHelpers.test.js

& become &amp; on the Dashboard and Project Organizer.
The ideal solution to this would handle amps better on the backend. This is a cosmetic front end hack/fix to make amps show up properly. Where possible I caught the titles early, but a lot of the time.
This also now handles < and >
Replace &amp; with & on PO and Dashboard
This is a hack, so manually making the name contain &amp; will convert it to & in these displays.
[#OSF-6853]
https://openscience.atlassian.net/browse/OSF-6853
Test a project name that contains &
On the Dashboard project widget:
1. Make sure titles in the dashboard handle amps
2. Make sure each level of parent-grandparent handles amps (picture)
3. Make sure searching matches amp properly (e.g., title = cat&dog, quick search cat&d matches; cat&amp;dog will still match …

[hotfix] Handle amps in PO and dashboard [OSF-6853]

---

admin/common_auth/views.py
admin/desk/views.py
admin/nodes/views.py
admin/pre_reg/views.py
admin/spam/views.py
admin/templates/base.html
admin/templates/nodes/node.html
admin/templates/nodes/node_list.html
admin/templates/pre_reg/draft_detail.html
admin/templates/pre_reg/draft_list.html
admin/templates/spam/detail.html
admin/templates/users/user.html
admin/templates/users/user_list.html
admin/users/views.py

The `AdminProfile` model was moved from the admin app to the OSF app, so
the permissions checks throughout the admin app needed to be adjusted to
account for the move. Basically replace 'common_auth' with 'osf' and
'admin' with 'osf' in some cases.
- update permissions checks throughout to look for permissions under `osf` instead of `common_auth` or `admin`
https://openscience.atlassian.net/browse/OSF-7563

Update permissions checks to look in osf instead of admin [OSF-7563]

---

osf/models/node.py

Make user permission queries faster.
Replaced user permission query with more efficient version.
Everyone could have permissions to everything, but probably not.
h/t @chrisseto for the `not has_permission`, good catch. It was late.

Optimize permissions query in order for #winning

---

NOTICE
api/base/serializers.py
osf/models/base.py
osf/models/node.py
osf/utils/caching.py

Make less guid queries
Add custom cached_property decorator that supports setters. Implement on GuidMixin._id and Node.parent_node and Node.root.
Could cause setting guids on existing objects to not work good.

[RFR] Add custom caching decorator and implement on various properties

---

api/logs/serializers.py
api/nodes/views.py
api/users/views.py
osf/models/node.py
osf_tests/test_node.py

Make APIv2 logs/ endpoints faster.
* Fixes bug where forked nodes' `root` would be incorrect
* Simplify and optimize `AbstractNodeQuerySet.get_children` by using the the `descendants` related name rather than a recursive query
* Use `.values` in NodeLogParamsSerializer to avoid instantiation and select overhead
* Use `select_related` to eagerly select NodeLogSerializer's relationship fields
~2 second speedup for the `/v2/nodes/<nid>/logs/` endpoint
Before
After

API log list optimizations and .root fix

---

framework/auth/decorators.py
framework/auth/views.py
tests/test_views.py
website/project/views/contributor.py

@icereval 
FYI @brianjgeiger 
Security related issue. Please refer to the ticket.
https://openscience.atlassian.net/browse/OSF-7581

[HotFix] Fix BingPreview Issue [OSF-7581]

---

api/base/pagination.py
framework/mongo/utils.py

Default Django Pagination usages to `ORDER BY 'id'` if when an `order_by` has not been specified.
Avoids the case where paginated rows are returned more than once during a paginated request.
[Postgres does not order rows](https://www.postgresql.org/docs/9.1/static/queries-order.html)
> After a query has produced an output table (after the select list has been processed) it can optionally be sorted. **If sorting is not chosen, the rows will be returned in an unspecified order.** The actual order in that case will depend on the scan and join plan types and the order on disk, but it must not be relied on. A particular output ordering can only be guaranteed if the sort step is explicitly chosen.
https://docs.djangoproject.com/en/1.10/topics/pagination/#required-arguments
>A list, tuple, …

ensure pagination includes default pk order by [#OSF-7607]

---

website/static/js/project-organizer.js

Fixes collapse bug on my projects page with a project that has components. Seems to only surface in Django, possibly due to a race condition/promise resolution and latency.
Checks if item is open already and returns early instead of firing a network request
N/A
https://openscience.atlassian.net/browse/OSF-7614

[OSF-7614] Fix collapse problem by check if item is already open

---

README-docker-compose.md
docker-compose.yml

The `docker-compose logs` command crashes locally after 60 seconds with the following error:
```
HTTP request took too long to complete
```
This prevents this from happening by removing `tty: true` from docker-compose.yml. (see https://github.com/docker/compose/issues/3106).
- Remove `tty: true`
- Update docs re: ipdb breakpoints
This changes how devs will access ipdb breakpoints. They will need to run apps using `docker-compose run --service-ports web` ([source](https://github.com/pydanny/cookiecutter-django/blob/master/docs/developing-locally-docker.rst#debugging)). See the updated docs for details.

 Prevent "HTTP took to long to complete" when running 'docker-compose logs'

---

api/institutions/authentication.py
api_tests/institutions/views/test_institution_auth.py

- When signing up for an OSF account via institution login, the `fullname` field of the user is automatically populated, but the `given`/`middle`/`family` name fields are not. 
- These fields are guessed when the user is created, but the guessed name fields were being overwritten by the names provided by the institution (i.e. being overwritten with `None` when the institution didn't provide `given`/`middle`/`family` names).
- This PR changes things to use the institution provided names, if they are provided. Otherwise, the names that are guessed from the `fullname` will be used.
- [OSF-7212](https://openscience.atlassian.net/browse/OSF-7212)

[hotfix] Populate User Names From Institution Account Creation [OSF-7212]

---

scripts/populate_preprint_providers.py

engrXiv needs a quick update to their Steering Committee section
Update the affiliation for Douglas Van Bossuyt from “Colorado School of Mines” to “KTM Research”
Update populate_preprint_providers.py script file with the new affiliation.
Ticket Link: 
https://openscience.atlassian.net/browse/OSF-7376 
https://openscience.atlassian.net/browse/EOSF-464

Update engrXiv Steering Committee list [OSF-7376]

---

website/static/js/osfHelpers.js
website/static/js/tests/osfHelpers.test.js

Fix the problem that adding affiliations from components does not affiliate nested components (grandchildren)
What to test:
Create a project (1) and add a component (2)
Within the component, create a nested component (3)
Within 3, create another nested component (4), and then another within 4 (5), and another within 5 (6)
Go to Component 2 and go to Settings
Click to Add Affiliation and in the modal that appears, select to add the affiliation to 2 and every component within it
After affiliation has been added, check the components and nested components
Before change:
Only a few of components child nodes has the correct affiliation information. Usually it will be component 2, 3, 5 has but 4,6 doesn't
After change:
All child nodes of component 2 should have the correct affiliation …

[#OSF-7232]Adding affiliations from components does not affiliate nested components (grandchildren)

---

api/institutions/authentication.py
framework/auth/__init__.py
framework/auth/views.py
framework/sessions/__init__.py
osf/migrations/0040_ensure_root_field.py
osf/models/node.py
osf/models/user.py
website/conferences/views.py
website/project/views/comment.py
website/settings/defaults.py

Includes #6994
Prevents potential locking errors and unnecessary updates to User records.
Only update `date_last_login` after 60 seconds have elapsed after last update.
We used to do this for requests that used basic auth: https://github.com/CenterForOpenScience/osf.io/commit/c35b12f9de9cb209eb649234708adfb3199f997f , but we must have forgotten to add the throttle for cookie auth.

Add throttle for date_last_login

---

admin/users/views.py
api_tests/nodes/views/test_node_detail.py
osf/management/commands/migratedata.py
osf/management/commands/migraterelations.py
osf/models/mixins.py
osf/models/node.py
osf/models/tag.py
osf/models/user.py
osf_tests/conftest.py
osf_tests/test_node.py
osf_tests/test_user.py

System tags were being exposed through the v2 node detail endpoint.
- Override the default Manager for Tag, so that `node.tags` filters out system tags
- Add the `all_tags` manager for Tag. Usage: `Tag.all_tags.filter(osfuser=user, system=False)`
- Add the `all_tags` property to OSFUser and AbstractNode. 
When filtering tags, you must call `all_tags` if you want to include system tags, e.g. `node.all_tags.filter(name=name, system=True)`.
https://openscience.atlassian.net/browse/OSF-7662
In an attempt to address [OSF-7606](https://openscience.atlassian.net/browse/OSF-7606), I tried a couple optimizations on this branch, but neither of them improved performance or reduced the number of queries.
1. Making `tags` a SerializerMethodField in NodeSerializer
```python
tags = …
```

[OSF-7662] Filter out system tags when accessing Node.tags

---

website/profile/views.py
website/routes.py

No need to embed public projects and components in the `/api/v1/profile/` endpoint; it just slows things down on the Dashboard and Account Settings pages.
Don't embed nodes in the /api/v1/profile/ view.

Only embed public projects and components in the HTML view

---

website/static/js/filepage/index.js

Don't show `Edit` to users on checked-out files
* Block showing edit button until API request completes
* `redraw` mithril after request completes
None expected
[[OSF-7670]](https://openscience.atlassian.net/browse/OSF-7670)

Prevent "Edit" button race condition [OSF-7670]

---

website/static/js/components/logFeed.js
website/static/js/pages/render-nodes.js
website/static/js/project.js

Reduce load time of user profile
* Mount LogFeeds on first toggle, not pageload
* Allow individual log panes to draw independently of all the panes on the page
None expected
[[OSF-7676]](https://openscience.atlassian.net/browse/OSF-7676)

Load profile logs lazily [OSF-7676]

---

api/nodes/serializers.py
osf/models/node.py
website/project/views/node.py

The `Contributor` model was added in the rewrite, and a small edge case was missed. This fixes
* Fix bad merge from ~October
None expected
[[OSF-7697]](https://openscience.atlassian.net/browse/OSF-7697)

Allow unregistered contribs to be imported across components [OSF-7697]

---

scripts/migration/ensure_bookmark_existence.py
website/project/__init__.py
website/views.py

Fix bad data
* Use `creator` to distinguish valid bookmarks
~~It might be possible for this to break existing valid bookmark collections with links.~~
~~TODO: investigate if there are any~~
Update: not a problem. See ticket for details
```
python -m scripts.migration.ensure_bookmark_existence --dry
python -m scripts.migration.ensure_bookmark_uniqueness --dry 
```
[[OSF-7696]](https://openscience.atlassian.net/browse/OSF-7696)

[Hotfix] Use `creator` to distinguish valid bookmarks [OSF-7696]

---

admin/metrics/views.py

Permissions were changed to be under the OSF namespace in a previous PR, but this change slipped by by accident. This is to allow metrics only users to actually be able to view metrics
- Update permission required name

Admin - Update metrics permission required name

---

admin/common_auth/forms.py

A small update that makes the superuer's form for adding admin users a little nicer
- Specify a form widget on admin permissions update page

Add checkboxselectmultiple widget for admin form

---

website/static/css/pages/home-page.css
website/static/css/quick-project-search-plugin.css
website/static/js/home-page/quickProjectSearchPlugin.js
website/static/js/pages/home-page.js

- Adds a Prereg promo banner to the top of the dashboard page.
- Removes the exisiting Prereg section from the page.
- Prereg banner added to `quickProjectSearchPlugin.js`
- `preregPlugin.js` purposely not removed so that the old banner can be added back easily, if desired.
- [OSF-7644](https://openscience.atlassian.net/browse/OSF-7644)

[hotfix] Prereg Banner [OSF-7644]

---

addons/osfstorage/models.py
addons/osfstorage/utils.py
addons/osfstorage/views.py
osf/models/files.py

```python
In [38]: prod = requests.get('https://files.osf.io/v1/resources/ktehs/providers/osfstorage/?meta').json()['data']
In [39]: local = requests.get('http://localhost:7777/v1/resources/ktehs/providers/osfstorage/?meta').json()['data']
In [40]: local = [x['attributes'] for x in sorted(local, key=lambda y: y['id'])]
In [41]: prod = [x['attributes'] for x in sorted(prod, key=lambda y: y['id'])]
In [42]: _ = [x.pop('modified', None) for x in prod]
In [43]: _ = [x.pop('modified', None) for x in local]
In [44]: prod == local
Out[44]: True
```
Even better:
```python
In [47]:  prod = requests.get('https://files.osf.io/v1/resources/ktehs/providers/osfstorage/58b85106594d9001fbfeb37f/?meta').json()['data']
In [48]: %time  prod = requests.get('https://files.osf.io/v1/resources/ktehs/providers/os …
```

[OSF-7720] Move serialization logic into SQL

---

website/static/js/home-page/quickProjectSearchPlugin.js
website/templates/home.mako

- The button on the new prereg banner overlapped with the banner text on mobile screens, and also made the mobile dropdown menu disappear. Oops.
- Still good on large screens:
- Better on mobile screens:
- [OSF-7644](https://openscience.atlassian.net/browse/OSF-7644)

[hotfix] Fix Prereg Banner on Mobile [OSF-7644]

---

scripts/README.md
scripts/migration/ensure_bookmark_contributors.py
website/app.py

For some Bookmark collections (68 on prod), the creator is not a contributor. This
causes a 403 error when trying to access their bookmarks on the "My Projects" page
Add a script to ensure that all bookmark collections' creators are also contributors.
Any new one-off scripts in `scripts/` should use `setup_django()` rather than `init_app()` (pinging @mfraezz to be aware of this).
https://openscience.atlassian.net/browse/OSF-7710

Add script to fix bookmark collections for some users

---

api/base/views.py
api/collections/views.py
osf/models/node.py

Optimize. 
`c` is a collection with 15 links. Old way:
```
In [26]: %timeit -n 10 list(c.linked_nodes.filter(id__in=[e.id for e in c.linked_nodes.filter(is_deleted=False).exclude(type='osf.collection').order_by('-date_modified') if e.can_view(Auth(u))]))
[...]
10 loops, best of 3: 864 ms per loop
```
New way:
```
In [27]: %timeit -n 10 list(c.linked_nodes.filter(is_deleted=False).exclude(type='osf.collection').can_view(user=u, private_link=None).order_by('-date_modified'))
[...]
10 loops, best of 3: 261 ms per loop
```
* Use `AbstractNodeQuerySet.can_view`
* Incidental fix: use `.exclude` instead of python filtering
* Incidental fix: explicitly check view permissions in `AbstractNodeQuerySet.can_view`
None expected
[[OSF-7738]](https://openscience.atlassian.net/browse/OSF-7738)

[Hotfix] Optimize BaseLinkedList [OSF-7738]

---

requirements.txt

The latest version resolves some issues with garbage characters being printed when running IPython with ctx.run (see Notes in #7062).
Bump invoke
I reviewed invoke's changelog, and there should be no breaking changes that affect us.
Devs should update their requirements
```
docker-compose up requirements
```
and/or
```
pip install -r requirements.txt
```

Bump invoke to 0.15.0

---

website/profile/utils.py
website/project/views/node.py

Reduce number of queries required to view a project with lots of contributors
New:
```
In [7]: %timeit -n 10 utils.serialize_visible_contributors(included_n)
10 loops, best of 3: 25.6 ms per loop
```
Old:
```
In [8]: %timeit -n 10 utils.serialize_contributors(n.visible_contributors, node=n)
10 loops, best of 3: 14.9 s per loop
```
* `.include` related models
* Create new utils for this case
None expected
None known

[Hotfix] Optimize view project

---

website/static/js/logTextParser.js

- See ticket (especially Sara's comment) for better explanation. 
- TL;DR: file-related logs aren't being updated correctly when paginating through the log feed, resulting in linked file names leading to the wrong file. 
- Passes the correct logObject to the `returnLinkForPath` controller function. 
- From the Mithril docs:
> The controller function is called once when the component is rendered. Subsequently, the view function is called and will be called again anytime a redraw is required. 
- The logs widget on the project overview page redraws when a new page of logs is requested, so only the view function (with the logObject from the first page when the controller was called) was being called when viewing any logs page other than the first. 
- The logs widget on the My Projects page …

[hotfix] Fix Duplicate File Logs on Project Overview Page [OSF-7585]

---

tests/test_serializers.py
website/profile/utils.py
website/profile/views.py

Unnecessary count queries were being made on the `PUT /api/v1/profile/` endpoint, which gets called often (every time a user visits the dashboard).
Don't include the user's number of public projects and components.

[hotfix] Remove unnecessary count queries when sending PUT to /api/v1/profile

---

osf/models/registrations.py
osf_tests/test_registrations.py

DraftRegistration approval emails were sending emails with the full parent Node representation instead of just the GUID -- fix that!
- Construct the url for the draft registration with the _id instead
- Add test for proper URL formation
https://openscience.atlassian.net/browse/OSF-7759

[hotfix] Update prereg draft approval/rejection email [OSF-7759]

---

api/files/serializers.py
api_tests/files/views/test_file_detail.py

Files relationships were using node_id instead of node_.id, and thus gave the postgres table val instead of the guid.
Fix id; add test.
N/A
https://openscience.atlassian.net/browse/OSF-7758
Create a folder in a project. Navigate to the folder's file page (e.g., https://api.osf.io/v2/files/58e655786c613b0252fec572/ )
and confirm that the guid appears correctly in the relationships->files->links->related->href

[Hotfix] Fix folder relationship id [OSF-7758]

---

admin/preprints/views.py

Form to change preprint provider broken on production admin - this should fix it. 
- Add return super to post for processing change form
- correct definition of context object

[hotfix] Process preprintprovider change form

---

website/templates/project/project.mako

Editing preprints is changing from a query parameter to a route, but the OSF links to the query parameter version. We meed to link using the route.
Changed the Project template to do `/edit` instead of `?edit`
No.
https://openscience.atlassian.net/browse/OSF-7761

Use preprint edit route [OSF-7761]

---

osf/models/node.py
osf_tests/test_node.py

Optimize `get_root` to speed up profile, other pages.
Before:
```
In [4]: %timeit -n 3 get_public_projects(user=u)
3 loops, best of 3: 12.4 s per loop
```
After:
```
In [4]: %timeit -n 3 get_public_projects(user=u)
3 loops, best of 3: 8.51 s per loop
```
Note: most of the remaining 8.5s is contributor selects or nodelog counts. Also, `u` has ~250 projects, 149 public.
* Utilize `root_id` field
* Add test
None expected
[[OSF-7779]](https://openscience.atlassian.net/browse/OSF-7779)

[Hotfix] Optimize get_root [OSF-7779]

---

scripts/populate_new_and_noteworthy_projects.py

_guids isn't a real field. It's a byproduct of the guid annotations. It's the name of the field that's being added to the queryset. The underscore was supposed to show that it was private and people shouldn't use it. People used it.
Remove the _ and use the public guids___id field for filtering.
I checked to make sure there were no other occurrences of _guids filtering in the code base. People could still use it if they don't understand how it works.
Here's the sentry error: https://sentry.cos.io/sentry/osf/issues/277605/

[Hotfix] Replace incorrect _guids lookup.

---

api/base/pagination.py
api/search/serializers.py
api/search/urls.py
api/search/views.py
api_tests/search/views/test_views.py
osf/models/institution.py
website/search/elastic_search.py

Search results from the API were not equipped to deal with showing found Institutions matching the query search terms. Add the means for Institutions to show up in search results now without throwing a 500 error!
- Update search views, urls, and serializers to also show Institution information in results
- Add Institution results in the pagination view for search results
- Add key to `elastic_search.py`'s `DOC_TYPE_TO_MODEL`
- Update elastic search when an institution is saved
- Add tests
None internally, but external uses of the search endpoint of the URL will now have to account for another key, and another type of serialized search result.
https://openscience.atlassian.net/browse/OSF-7370

Add Institutions matching query to API search results [OSF-7370]

---

api/nodes/utils.py
osf/models/files.py
tests/test_addons.py

Waterbutler returns different metadata for a file when its accessed from its parent's endpoint or the file endpoint directly. Accessing the file endpoint directly (`/files/github/filename.txt`) includes "modified" information, and then editing and then going back to the parent (`/files/github/`) did not have the "modified" field for the new update. The OSF was breaking when trying to insert this edited entry with missing modified information into the file history.
As a fix, if there is no modified metadata available, append to the end of the history.
h/t to @felliott for much help and amazingly helpful github comments!
- Update URL for accessing Waterbutler file info to use the internal waterbutler URL
- If there is no modified information included in the metadata, append to the end of …

Handle incomplete metadata from WB when addon's parent directory accessed [OSF-7148]

---

api/files/serializers.py

Dates break on v2.2 api serializer when date is none.
I spent longer than I care to admit trying to get a working test, but to no avail. I couldn't find a way to set dates to null that stuck when pushing it through the serializer, because of datetime validation for most of the prebuild factories/file creator helpers. 
Stops trying to conform none dates to datetime spec and allow return of null
None known
See jira example. Just go to the api view of files/github with version tag. If no 500 error, all is well.
[#OSF-7316]
https://openscience.atlassian.net/browse/OSF-7316

[feature] Stop api breaking on v2.2 with null date [OSF-7316]

---

website/static/js/fangorn.js

Fangorn doesn't auto populate rename text due to an earlier bug. 
This fixes that and how folder creation naming works, since the previous version broke that.
None known
[#OSF-7151]
https://openscience.atlassian.net/browse/OSF-7151
Check that all fangorn inputs work properly (filter, rename, folder create)
Check that renaming works
Check that there were no regressions (] and " ' all work, etc)
Also check for regressions of the last letter disappearing bug on mouse out

[Feature] populate fangorn rename v9001 [OSF-7151]

---

osf/models/files.py
osf_tests/test_files.py

Updating folders was failing because the File.update method was brought over from modm but the Folder.update method was not.
Moved the BaseFileNode.update method to File. Added Folder.update method from modm. Added a test to make sure calling Folder.update calls Folder.update.
None expected.
https://openscience.atlassian.net/browse/OSF-7783?filter=17500

[RFR] Bring Folder.update back from the dead [OSF-7783]

---

admin/templates/base.html

View preprint permission named incorrectly in base template, so users can't see the sidebar for preprints
- Rename permission check to `view_preprintservice` in sidebar
Admin app will need to be refreshed after merge!

[hotfix] Name preprintservice permission correctly in base template

---

scripts/create_fakes.py

- Fix the create_fakes script.
- `NodeFactory` kwarg changed from `project` to `parent`.
- Avoids this error when creating a fake project with components:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/code/scripts/create_fakes.py", line 384, in <module>
main()
File "/code/scripts/create_fakes.py", line 377, in main
args.presentation_name, args.is_registration, args.is_preprint, args.preprint_provider)
File "/code/scripts/create_fakes.py", line 333, in create_fake_project
creator=creator)
File "/usr/local/lib/python2.7/site-packages/factory/base.py", line 67, in __call__
return …
```

[feature] Fix create_fakes [No Ticket]

---

website/search/elastic_search.py

Updating nodes that have a wiki name with a dot in them fails.
Replace '.' with ' ' when indexing wiki page names.
Must be merged before running `populate_instititions` on prod. Therefore, this should be merged before #7120
https://openscience.atlassian.net/browse/OSF-7828

[OSF-7828] Replace '.' with ' ' when indexing wiki page names

---

addons/wiki/models.py
addons/wiki/tests/test_models.py

An error was being raised by NodeWikiPage.absolute_url if the
NodeWikiPage's page_name contained special characters.
This error caused GUID resolution to fail for these NodeWikiPages.
Don't quote `absolute_url` and `url` properties. Allow the browser to do that.
https://openscience.atlassian.net/browse/OSF-7811

[hotfix] [OSF-7811] Don't quote page_name in absolute_url and url

---

docker-compose.yml

Don't start tokumx container unless sharejs container is explicitly started
Remove depend tokumx from admin, api, and web containers in docker-compose.yml.
It is assumed that the sharejs container is the only container directly communicating with tokumx.
https://openscience.atlassian.net/browse/OSF-7765

Remove tokumx depend from all containers other then sharejs [#OSF-7765]

---

addons/dataverse/client.py
addons/dataverse/static/dataverseFangornConfig.js
website/util/sanitize.py

- Fixes the display of custom dataverse publish text which may contain HTML.
- Strips the HTML received from dataverse (with the exception of `strong`, `li`, and `ul` tags)
- Use `m.trust()` to render the un-stripped tags.
- Before:
- After:
- [OSF-7211](https://openscience.atlassian.net/browse/OSF-7211)

[feature-fix] Render HTML in Dataverse Custom Publish Text [OSF-7211]

---

docker-compose.override.yml
docker-compose.ubuntu.yml
docker-compose.yml

This makes it easier to use local database dumps
The compose file version was bumped to 2.1 in order to add support
for ${VARIABLE:-default}
https://docs.docker.com/compose/compose-file/#variable-substitution

Allow postgres data volume to be overridden with an envvar

---

scripts/generate_sitemap.py

Sitemap index file incorrectly used 'datemod' instead of 'lastmod'
Change the tag to be 'lastmod'
Also changing dates to be YYYY-MM-DD instead of full ISO8601
https://openscience.atlassian.net/browse/OSF-7682

[feature] Switch sitemap datemod to lastmod [OSF-7682]

---

addons/figshare/README.md

There are special instructions required to use the Figshare addon locally. These instructions should be brought up to date with recent model changes, and we should confirm that the instructions work as written.
This is a developer facing change to docs, and should not affect user or site functionality.
None expected. This is my first PR with the new models, so worth verifying for accuracy. Worked when I ran locally in `shell_plus`.
https://openscience.atlassian.net/browse/OSF-7755

Update local figshare instructions to reflect model changes [#OSF-7755]

---

website/static/js/project.js

- #6558 broke registration forking functionality. Oops.
- Make the appropriate API request based on if the node is a project or registration.
- [OSF-7865](https://openscience.atlassian.net/browse/OSF-7865)

[hotfix] Fix Registration Forking [OSF-7865]

---

admin/nodes/serializers.py
admin/templates/nodes/node.html

Currently, admin app displays "Date Created" for Registrations. However, this date refers to the date the Project was created. This is a bit confusing and doesn't give enough information about the registration to Support staff (e.g., user emails about a registration that's pending, but Support doesn't know if the registration should be "out" of pending by now or not).
It would be helpful to see the date/time the registration was initiated in the admin app, so we can do better troubleshooting of private projects/registrations.
- Add registered_date to admin's node serializer
- Display the registered date in the node's Registration detail section
https://openscience.atlassian.net/browse/OSF-7230

Add Date Registration Initiated to Admin App [OSF-7230]

---

admin/nodes/serializers.py
admin/templates/nodes/node.html

Add link on project detail to registrations, add link on registration to `registered_from` node
- Updates to node seralizer to include registration and registered_from
- Update to node template view
https://openscience.atlassian.net/browse/OSF-6842

Add link between projects and registrations in admin [OSF-6842]

---

addons/osfstorage/views.py

As documented on the FileVersion model, date_modified is meant for
internal use and/or debugging only. date_created represents when the
version was created or the date_modified of the FILE supposing it is
the newest version.

[Fix] Return the correct dates for OSFstorage files at get_children

---

addons/base/views.py
osf_tests/test_guid.py
website/views.py

Redirect `/download` for files and preprints
Add special cases in `resolve_guid`
None expected
[[OSF-7835]](https://openscience.atlassian.net/browse/OSF-7835)

[Hotfix] Redirect `/download` [OSF-7835]

---

osf/utils/fields.py

Make it less annoying to work with a DB without having its `SENSITIVE_DATA_*` keys.
* Conditionally `except InvalidTag` iff `DEBUG_MODE`
None expected
None known

[Hotfix] Pass InvalidTag iff DEBUG_MODE [No Ticket]

---

api/nodes/views.py
api/preprint_providers/views.py
api/preprints/views.py
api/users/views.py

Api is duplicating returned values.
Adds distinct() to the queryset for the 4 api routes
None known
https://openscience.atlassian.net/browse/OSF-7903
!!!! Make sure you test both logged in and non logged in users!!!!
See https://staging-api.osf.io/v2/preprints/?filter[provider]=osf
If you look at the id values, note that some of them duplicate. There should not be duplicated preprint data.
This changes the 4 preprint api routes: users, preprints, preprint_providers, and nodes
Easiest way to find the issue is to filter by a specific preprint provider

[hotfix] Distinct preprints fix [OSF-7903]

---

osf_tests/test_archiver.py
tests/test_sanitize.py
website/archiver/utils.py
website/util/sanitize.py

- Fixes `ArchivedFileNotFound` error being incorrectly raised for files with <, >, and & characters in their name that have been attached to a registration schema.
- Unescape selected file names for comparison to file map in archival process.
- Adds regression test for file names with special characters.
- Adds failing test case for `different_file_names_same_shas` (mostly unrelated, just seemed like a good test to add).
- Allows additional safe characters to be passed to `unescape_entities()`.
- Adds test for `unescape_entities()` with additional characters.
- [OSF-7613](https://openscience.atlassian.net/browse/OSF-7613)

[feature] Fix Failing Registrations with &, <, > in File Names [OSF-7613]

---

website/static/js/myProjects.js

- Collapses the info panel/preview pane on the my projects page by default.
- Change the initialization value of the `showInfo` m.prop() from true to false.
- IMO, it's not obvious that the info panel even exists anymore, but ¯\\\_(ツ)_/¯ 
- [OSF-6777](https://openscience.atlassian.net/browse/OSF-6777)
- Before (expanded by default)
- After (collapsed by default)

[feature] Collapse Info Panel on My Projects Page by Default [OSF-6777]

---

website/templates/project/project.mako

The link to view the Registration Form at the moment is obscured underneath the title in a link, and people are having trouble locating the information. Move the link into a more visible button.
- If it's a normal project, show a plain old row with the license info
- If it's a registration, the row should also include the View Registration Form button
- Add note about only showing one registered schema, because this is different from the current implementation
This button, as it stands, only links to ONE registration form, as before it would show
multiple if there were multiple. However, in most cases there should only be one registration form per registration.
There are currently 12 registrations on production that have more than one registration schema. …

Make link to registered schemas a more prominent button  [OSF-7301]

---

website/static/js/fangorn.js

If you have display a 'operation taking to long' modal in fangorn the header of the previous modal you displayed is redisplayed as the  'operation taking to long' modal header
A couple lines of js overwrite old header replacing it with new one.
https://openscience.atlassian.net/browse/OSF-7428

[OSF-7428] Fix fangorn 'operation taking to long' modal header

---

website/static/js/pages/project-dashboard-page.js

This points out to the user they have no tags for their project by changing the text prompt for uses with no tags.
Changes to over override taginput.js's default text behavior.
https://openscience.atlassian.net/browse/OSF-7439

[OSF-7439] Change default text prompt for tags for users with no tags

---

website/static/js/licensePicker.js

Encourages users to add a license to licenseless projects 
swaps out button text "No license" for "Add a license"
https://openscience.atlassian.net/browse/OSF-7441

[OSF-7441] Change no license prompt text

---

website/templates/project/registrations.mako

- Updates the language displayed on the registrations tab when there are no registrations. 
- Adds language to make it clear that non-admins don't have permission to create a registration.
- [OSF-7577](https://openscience.atlassian.net/browse/OSF-7577)
- Before (same view for admins and non-admins)
- After (admin view)
- After (non-admin view)

[feature] Update Language on Registrations Tab [OSF-7577]

---

osf/models/user.py
website/static/js/profile.js
website/templates/include/profile/social.mako

- Updates ImpactStory base URL used for social links. 
- ImpactStory base URL changed everywhere from `https://impactstory.org/` to `https://impactstory.org/u/`
- [OSF-7580](https://openscience.atlassian.net/browse/OSF-7580)

[feature] Update ImpactStory Links [OSF-7580]

---

website/static/js/nodeControl.js

This change encourages users to add a description to their project by changing the prompt text from "No Description" to "'Add a brief description of your [node category]"
minor textual change to JS.
https://openscience.atlassian.net/browse/OSF-7440

[OSF-7440] Change Project Description Prompt text

---

api_tests/nodes/views/test_node_alternative_citations.py

Prevent the alternative citation test from breaking (every May).
Citeprocpy's MLA citation produces the month in an abbreviated format, with a `.` if the month actually gets abbreviated. Our test adds it at the end of the month as well, except it doesn't account for May, which doesn't get abbreviated and so doesn't get a `.`. This adds that exception for the unit test to work every month.
Tests will pass every month, instead of only passing 11 out of 12 times a year 🉑 :fire:

Fix alternative citation tests

---

addons/github/apps.py
addons/github/models.py

Don't needlessly send errors to sentry
* `except GitHubError`s in two places
None expected
[[OSF-7892]](https://openscience.atlassian.net/browse/OSF-7892)
[[OSF-7895]](https://openscience.atlassian.net/browse/OSF-7895)

Except bad GH creds [OSF-7892][OSF-7895]

---

osf/models/external.py
tests/test_oauth.py

Don't log superfluous errors to sentry
* Except possible expected errors
None expected
[[OSF-7894]](https://openscience.atlassian.net/browse/OSF-7894)

Except possible errors when refreshing tokens [OSF-7894]

---

admin/users/views.py
admin_tests/users/test_views.py

Addendum to #7070  -- now with more name search case insensitivity!
Search by name is now case insensitive!
Searching by "User name" or "USER NAME" or "UsEr NAmE" should yield the same results.
None antipated
https://openscience.atlassian.net/browse/OSF-6841

Admin Name search now case insensitive [#OSF-6841]

---

admin/pre_reg/views.py
admin/preprints/views.py
admin_tests/common_auth/test_logs.py
admin_tests/meetings/test_views.py
admin_tests/nodes/test_views.py
admin_tests/pre_reg/test_views.py
admin_tests/preprints/test_views.py
admin_tests/spam/test_extras.py
admin_tests/users/test_views.py
tests/base.py

Add tests that check permissions for user, node, meeting, preprnt, and prereg views
Also update all admin tests to actually pass when run locally
- node view tests
- user view tests
- prereg view tests
- meeting view tests
- Preprint view tests
- updates to other tests to run properly locally
https://openscience.atlassian.net/browse/OSF-7427

Add Permission tests for admin views

---

admin/templates/users/get_link.html
admin/templates/users/user.html
admin/users/serializers.py
admin/users/urls.py
admin/users/views.py
admin_tests/users/test_views.py

Addendum to https://github.com/CenterForOpenScience/osf.io/pull/7088
If a user is unclaimed, generate claim links for every node that they've been added as an unregistered contributor on
- urls for unclaimed user route
- view that parses unclaimed records and turns to links
- changes to structure of modal to show list of links if necesary
- add is_claimed to user serializer
- test for link generation from unclaimed user record
https://openscience.atlassian.net/browse/OSF-7123

Also generate links for Unclaimed users in admin [OSF-7123]

---

website/static/js/pages/file-page.js

This points out to the user they have no tags for their project by changing the text prompt for uses with no tags for the files page.
Changes to over override taginput.js's default text behavior for the file page tags.
https://openscience.atlassian.net/browse/OSF-7439

[OSF-7439] File page - Change default text prompt for tags for users with no tags 

---

website/archiver/tasks.py

Don't attempt to collect files that can't be accessed.
* LBYL
It's possible that registrations which would otherwise not archive will have an empty root folder for an addon that is enabled but not configured.
[[OSF-7922]](https://openscience.atlassian.net/browse/OSF-7922)

[Hotfix] Skip attempts to archive empty addons [OSF-7922]

---

README-docker-compose.md

Document process for creating/using local backups of the data in postgres. This can be helpful for developers with useful test data not covered by create_fakes.
Documentation only; should not affect users. Tested commands on Mac OS.
None expected. Should be beneficial to services team members who need to reset docker while preserving useful test data.
h/t @cwisecarver 
https://openscience.atlassian.net/browse/OSF-7899

Add PG backup/restore commands to documentation [#OSF-7899]

---

website/static/css/fangorn.css
website/static/js/fangorn.js

Make the text "unred" and "unbold"
create a project and go to the file widget
create a folder
upload a file to the project both inside the folder and outside the folder
drag the file of the project from outside the folder to inside the folder
Before the ticket:
After https://github.com/CenterForOpenScience/osf.io/pull/6836's fix:
After this fix:
https://openscience.atlassian.net/browse/OSF-7310

[#OSF-7310]Improve wording on move/replace file modal

---

addons/osfstorage/models.py
addons/osfstorage/tests/test_views.py
api_tests/nodes/views/test_node_list.py
api_tests/users/views/test_user_nodes_list.py
website/static/js/filepage/index.js

Code preventing preprints from being deleted did not get ported over when osfstorage was moved to addons. Currently only fangorn is preventing deletions of preprint files and bad moves, but fangorn has some known flaws (lazy loaded nested folders are supposed to be caught by the backend)
Add back in the code blocking bad preprint actions
None known; someone should check how many orphans were created.
https://openscience.atlassian.net/browse/OSF-7938
This is a regression of https://github.com/CenterForOpenScience/osf.io/pull/6525. However, all of the fangorn logic is still in place so the things that need thorough testing are the areas where fangorn is known to fail: when a preprint is inside a folder that has not been expanded. Test this situation thoroughly. A light regression of the …

[hotfix] stop preprint deletions [OSF-7938]

---

website/static/js/search.js
website/templates/search.mako

- Adds OSF style loading indicator to the search page.
- [OSF-7961](https://openscience.atlassian.net/browse/OSF-7961)
- You can only see the indicator flash for a brief moment here (since search isn't slow locally), but it should appear on initial search and when filtering between categories.

[hotfix] Add Loading Indicator to Search Page [OSF-7961]

---

addons/base/views.py
addons/osfstorage/tests/test_views.py
api/files/serializers.py
osf/models/files.py
osf/models/preprint_service.py
tests/test_preprints.py
website/preprints/model.py

`BaseFileNode.stored_object` is deprecated, and before was still in use via a property that just returned itself. So, get rid of references to `stored_object` for `BaseFileNode` objects, and remove the warning messages and placeholder methods as well.
- Remove references to `stored_object` for `BaseFileNode` objects
- Remove the helper method and warnings
- Fix  call to render wen embeding file checkout in the API - discovered while removing `stored_object` call
- The old `BaseFileNode` model was not updated, so will still be able to use `stored_object`
https://openscience.atlassian.net/browse/OSF-7853

Remove usages of and old methods for BaseFileNode.stored_object [OSF-7853]

---

website/static/js/addProjectPlugin.js

When making a new component, the license gets inherited from its immediate parent. Add a bit to the component creating modal to let the user know.
- Add "License" section to component creation modal that explains
- Add "learn more" link that leads to [OSF Help section on licenses](http://help.osf.io/m/sharing/l/524050-licenses?id=524050-licenses)
None anticipated!
https://openscience.atlassian.net/browse/OSF-7187
[#OSF-7187]

Add language for a component inheriting a license! [OSF-7187]

---

addons/dataverse/static/dataverseNodeConfig.js

"Other" dataverse URLs, particularly for UVA's dataverse, were being sent to the wrong place for API token retrieval
- Make the URL for API token retrieval uniform across all "other" dataverse sources
- Account for the fact that they may or may not include a / and the end of the URL they enter
##Notes for QA
The "request API Token" link for Harvard Dataverse is: `https://dataverse.harvard.edu/dataverseuser.xhtml?selectTab=apiTokenTab`. Make sure every "other" dataverse you enter takes you to `http://whateveryoutype/dataverseuser.xhtml?selectTab=apiTokenTab`
https://openscience.atlassian.net/browse/OSF-7213
[#OSF-7213]

Always make an other dataverse have the same URL to fetch API token [OSF-7213]

---

api/logs/serializers.py
osf/models/nodelog.py
osf_tests/test_private_link.py
tests/test_views.py
website/project/__init__.py
website/project/views/node.py
website/static/js/anonymousLogActionsList.json
website/static/js/logActionsList.json
website/static/js/logTextParser.js

Add logs whenever a view-only link is created on a project or component. Currently, a user could create a view-only link, share that with others, allowing them to access the project. The user could then remove the VOL and his collaborators would never know that the project's contents had been shared. 
Create new logs that say when a normal or an anonymous view only link is added or removed.
- Add `VIEW_ONLY_LINK_ADDED` and `VIEW_ONLY_LINK_REMOVED` to the `NodeLog` model
- Add `anonymous_link` to the NodeLog serializer
- Add log when node link is added or removed
- Tests to make sure logs are added
- Log text added to log actions list
- Log kwarg `anonymous_link` parsed in `LogTextParser.js`
https://openscience.atlassian.net/browse/OSF-7309

Add log when user adds or removes a private link [OSF-7309]

---

api/base/filters.py
api/nodes/views.py
api/preprint_providers/views.py
api/preprints/serializers.py
api/preprints/views.py
api/users/views.py
api_tests/preprints/filters/test_filters.py

To allow api filtering of preprints by the id of their subjects again. Additionally, allow filtering by text in the subject.
Make subjects a filterable field on preprints.
https://openscience.atlassian.net/browse/EOSF-339
Should be able to do two things:
`/v2/preprints/?filter[subjects]=<subject_id>`
`/v2/preprints/?filter[subjects]=<subject_text>`
and it should return all matching preprints.

[EOSF-339] Subject Filtering

---

admin/preprints/serializers.py
admin/preprints/views.py

Custom taxonomies broke preprints admin panel. 
Fairly convinced this would have been
Fix taxonomies serialization. No tests because this would have been caught by travis admin tests if they were running (tested and confirmed it failed)
NA
https://openscience.atlassian.net/browse/OSF-7972
1. Check that you can load up a preprint guid on the preprint view page.
2. Confirm that subjects appear accurately on the preprint detail page
3. Test this with a simple and complex hierarchy of subjects (single level of subject down to three-deep subjects)

[hotfix] Fix preprints subjects in admin panel [OSF-7972]

---

osf/models/node.py

- Update search when contributors are added and removed.
- Update search when an affiliated institution is added or removed.
- Add a few `update_search()` calls.
- For contributors, I considered adding `@contributor_added.connect` to `update_contributors_async` in search.py, but it seemed to overcomplicate things as that signal is already used to trigger a handful of other events (with different method signatures). See the [closed PR](https://github.com/CenterForOpenScience/osf.io/pull/7196) if you're curious. I could've added a new signal just for search, but that seemed a bit overkill as it would require adding signals for updating tags and institutions as well (if we were being consistent). 
- [OSF-7763](https://openscience.atlassian.net/browse/OSF-7763)

[feature] Search Fixes [OSF-7763]

---

scripts/populate_preprint_providers.py

- Script currently fails when attempting to set the `default_license` for a new preprint provider:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/code/scripts/populate_preprint_providers.py", line 1392, in <module>
main(env)
File "/code/scripts/populate_preprint_providers.py", line 1381, in main
update_or_create(PREPRINT_PROVIDERS[provider_id])
File "/code/scripts/populate_preprint_providers.py", line 68, in update_or_create
new_provider = PreprintProvider(**provider_data)
File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 553, in __init__
_setattr(self, field.name, …
```

[feature] Fix populate_preprint_providers Script [No Ticket]

---

addons/base/views.py
addons/osfstorage/tests/test_views.py
api/files/permissions.py
api/files/serializers.py
api/files/views.py
api/nodes/views.py
api/preprints/serializers.py
api/search/serializers.py
api/search/views.py
api_tests/wikis/views/test_wiki_content.py
osf/models/__init__.py
osf/models/files.py
osf/models/user.py
osf_tests/test_comment.py
scripts/osfstorage/usage_audit.py
tests/test_addons.py
tests/test_websitefiles.py
website/project/views/comment.py
website/search/elastic_search.py

Currently, StoredFileNode and FileNode are aliases of BaseFileNode, and they only exist for backwards compatibility.
- Remove aliases of `StoredFileNode` and `FileNode` from new OSF models
- Switch usages in tests, views, serializers, etc to use `BaseFileNode`
https://openscience.atlassian.net/browse/OSF-7854

Remove usages of StoredFileNode and FileNode [OSF-7854]

---

.docker-compose.env
.docker-compose.mfr.env
.docker-compose.wb.env
README-docker-compose.md

Some of the documentation surrounding debugging services in a docker environment were unclear or incomplete. This adds some notes about how to best debug with docker-sync.
Adds and reorganizes to README-docker-compose.md
None

Add docs for debugging services

---

osf/models/preprint_provider.py
osf/models/subject.py

Handle edge case when `subjects_acceptable` is `[]` and `self.subjects.exists()` is `False`
* Include only BePress Subjects
Could lead to weird behavior if there are no Subjects with `.provider` `'osf'`, but that should be handled by either a [migration](https://github.com/CenterForOpenScience/osf.io/blob/develop/osf/migrations/0024_migrate_subject_parents_to_parent.py#L57-L61) or the [`update_taxonomies` script](https://github.com/CenterForOpenScience/osf.io/blob/develop/scripts/update_taxonomies.py#L70)
[EOSF-668](https://openscience.atlassian.net/browse/EOSF-668)

Return correct subjects_acceptable [EOSF-668]

---

addons/figshare/models.py

Display correct error message for invalid Figshare credentials
* Except a `403` in `before_page_load`
None expected
[[OSF-8004]](https://openscience.atlassian.net/browse/OSF-8004)

[Hotfix] Display correct error message for invalid Figshare credentials [OSF-8004]

---

api_tests/nodes/views/test_node_contributors_list.py
osf/models/node.py

- Prevent deactivated users from being added as unregistered contributors through the API.
- Check if contributor is a deactivated user in `add_contributor()` 
- [OSF-7122](https://openscience.atlassian.net/browse/OSF-7122)

[feature-fix] Prevent Deactivated User Contributor Additions [OSF-7122]

---

addons/dataverse/static/dataverseUserConfig.js

Same fix as #6565, but applied to the user settings page as well. 
- [OSF-7213](https://openscience.atlassian.net/browse/OSF-7213)
- [OSF-7215](https://openscience.atlassian.net/browse/OSF-7215)

[feature] Fix UVA Dataverse API Token URL on User Settings Page [OSF-7215][OSF-7213]

---

website/templates/project/project.mako

Fix the bookmark button disappear from previous pr
The bookmark bottom should show correctly
https://openscience.atlassian.net/browse/OSF-7436

[#OSF-7436]Change icons on top right of Project Overview page to make them more universal

---

website/app.py
website/identifiers/listeners.py
website/identifiers/utils.py

[#OSF-7772]
When a node was deleted, the listener for updating metadat on EZID was not functioning properly, as the listener was not imported when the app was initiated. 
Move the function for listening for when a preprint's node is deleted to a separate listeners file, which can then be imported in `app.py`. This way, when the app starts up on staging, the listener to update EZID metadata when a node is deleted is properly imported along with other listeners!
- Move listener from `identifiers/utils.py` to new `identifiers/listeners.py` and import them in `website/app.py`
https://openscience.atlassian.net/browse/OSF-7772

Move listener for identifier update when node deleted [OSF-7772]

---

api/preprints/views.py
api_tests/preprints/views/test_preprint_detail.py

Deleted preprints can be seen through the api if you have the guid.
Preprints with deleted nodes 404 now; added a test of this
NA
https://openscience.atlassian.net/browse/OSF-8076
Test a preprint with a deleted node 404's and one that is not deleted does not 404.

[feature] Hide deleted preprint detail [OSF-8076]

---

api/nodes/serializers.py
api/registrations/serializers.py
api_tests/registrations/views/test_registration_files_list.py

the id for a registration is wrong in certain places
Uses _id instead of id; add a test, h/t @Nesiehr
Swapped two other places to _id (that currently worked) for consistency
https://openscience.atlassian.net/browse/OSF-8015
Test a registrations `https://api.osf.io/v2/registrations/b6psa/files/osfstorage/` route and make sure the guid is populated in the href (see ticket for an example)

[hotfix] registration files id [OSF-8015]

---

framework/auth/decorators.py

It seems some custom Outlook setups are prefetching or navigating to urls (possibly for security reasons). The user doing the fetching always seems to be IE9.
Block IE9 from viewing the secure pages to prevent autoclicking of routes. Throw a custom error message saying BingPreview and IE9 cannot view that page.
People using IE9 cannot see those pages. People using IE9 already can't use the osf (very well) so this shouldn't be a big problem. 
[#OSF-7665]
https://openscience.atlassian.net/browse/OSF-7665
This change affects emails for:
1. Resetting Passwords
2. External login email confirmations
3. Normal signup email confirmation
4. Unclaimed user project registration confirmations
The change should affect all of these equally, so checking each of those on a different browser should be …

[Hotfix] Outlook still sometimes breaks password links [OSF-7665]

---

api_tests/nodes/views/test_node_alternative_citations.py

- Continuation of #7173
- June and July will also break as they are not abbreviated in MLA format. See [modern-language-association.csl](https://github.com/citation-style-language/styles/blob/master/modern-language-association.csl#L46) for reference.

[hotfix] Fix MLA Citations Test [No ticket]

---

admin_tests/users/test_views.py

Fix TCI build
* Edit tests to conform with expected behavior based on [code](https://github.com/CenterForOpenScience/osf.io/blob/581683795ab27dff21b8e9f025214a15919757bd/admin/users/views.py#L373-L381)
Because I'm not certain "expected behavior based on code" equates to "expected behavior", two possible alternatives were considered:
```
diff --git a/admin/users/views.py b/admin/users/views.py
index 0d2dde4..b68d40a 100644
--- a/admin/users/views.py
+++ b/admin/users/views.py
@@ -372,13 +372,11 @@ class UserWorkshopFormView(PermissionRequiredMixin, FormView):
@staticmethod
def get_user_logs_since_workshop(user, workshop_date):
-        query_date = workshop_date + timedelta(days=1)
-        return NodeLog.objects.filter(user=user, date__gt=query_date)
+        return …
```

[Hotfix] Fix TCI build

---

admin_tests/users/test_views.py

Admin test that creates and destroys a CSV file would occasionally fail on travis, causing the whole build to fail
- Use mocking for `csv.read` instead of actually creating and parsing a test file
https://openscience.atlassian.net/browse/OSF-8081

Periodic test failure of TestUserWorkshopFormView tests [OSF-8081]

---

tests/test_utils.py
tests/test_views.py
website/profile/views.py
website/routes.py

The `current_user_gravatar` endpoint is unnecessary. It is used in website.routes.get_globals, but we can just use `website.profile.utils.get_gravatar` for that. Removing that call should also remove unnecessary queries for the currently logged-in user (made in the must_be_logged_in decorator).
- Remove routes that use methods
- Remove tests that called those routes
- Use `get_gravitar` method located in `website/profile/utils.py` for globals
- Add tests for profile util get_gravitar
https://openscience.atlassian.net/browse/OSF-7996

Remove usages of current_user_gravatar and get_gravitar route [OSF-7996]

---

website/conferences/views.py

- Updates the link to an author's profile page on a meetings submission to be correct in the case that the project creator removes themselves as a contributor (or makes someone else the project administrator).
- [OSF-7589](https://openscience.atlassian.net/browse/OSF-7589)

[feature] Fix Author Link on Meetings Submission [OSF-7589]

---

tests/test_registrations/test_embargoes.py
website/project/views/node.py

Deleting a node before a registration is approved/canceled makes it so that the registration cannot be cancelled. 
Changes the order of the decorators to allow the token to execute.
None known, permissions are checked via the token as well, so shouldn't cause any problems.
https://openscience.atlassian.net/browse/OSF-7768
Steps to reproduce:
1. Create Node
2. Create Draft Registration (but do not approve)
3. Open draft in a new tab for easy access (to not lose the link)
4. Delete Node
5. Go to draft and click note at top to delete draft
6. Draft should now delete (although it will send you to a resource not found page with a drop down saying draft registration was deleted).
Test:
1. Approving and Rejecting a registration with a deleted and intact node
2. Test the above with embargoes as …

[feature] Allow cancelling of draft reg with deleted node [OSF-7768]

---

osf/models/node.py
tests/test_preprints.py

It is possible for a preprint to have a deleted primary file but not show it is an orphan.
Add check to is_preprint_orphan for deleted file and return true if true
na
https://openscience.atlassian.net/browse/OSF-7939

[feature] Make deleted primary file orphan a preprint [OSF-7939]

---

tests/test_preprints.py
tests/test_views.py
website/project/views/contributor.py
website/templates/emails/contributor_added_preprints_branded.txt.mako
website/templates/emails/invite_preprints_branded.txt.mako

- Fixes malformed links and emails in preprint contributor added emails.
- Use preprint provider `_id` (instead of `name`) to format links and emails.
- [OSF-8037](https://openscience.atlassian.net/browse/OSF-8037)

[feature] Fix Preprint Contributor Added Emails [OSF-8037]

---

website/static/js/filepage/index.js
website/static/js/filepage/revisions.js

- Use short download URLs on the file view page. The download button in the toolbar and the download buttons in the revisions table have been changed.
- Use the new 'osf.io/<file_guid>/download` short URL instead of WaterButler download URLs on the file view page.
- Ensure that download counts aren't affected.
- Ensure the download URL can be copied by right clicking the buttons (as noted in the ticket). 
- [OSF-7834](https://openscience.atlassian.net/browse/OSF-7834)

[feature] File View Page Short Download URLs [OSF-7834]

---

addons/dataverse/static/dataverseFangornConfig.js

- Display custom publish text for all dataverses.
- Remove the check that only displays this text for UVA's dataverse.
- [OSF-7889](https://openscience.atlassian.net/browse/OSF-7889)

[feature] Display Publish Text for all Dataverses [OSF-7889]

---

api/nodes/permissions.py
api/nodes/views.py
api_tests/nodes/views/test_node_files_list.py

- Fix 502 when accessing NodeProviderDetail endpoints (`/v2/nodes/<node_id>/files/providers/<provider>/`)
- Handle `NodeProvider` object in `ContributorOrPublic` permissions class.
- [OSF-7904](https://openscience.atlassian.net/browse/OSF-7904)

[feature] Fix NodeProviderDetail 502 [OSF-7904]

---

website/templates/public/pages/support.mako

Correct github spelling on osf.io/support from 'Github' to 'GitHub'
https://openscience.atlassian.net/browse/OSF-7165

[Feature] Correct github spelling [OSF-7165]

---

api/base/filters.py
api/institutions/views.py
api/nodes/filters.py
api/nodes/views.py
api/registrations/views.py
api/users/views.py
api_tests/nodes/filters/test_filters.py
api_tests/registrations/filters/test_filters.py

- Fixes filtering by tags and contributors on user and institution node list views. 
- Replaces `NodeODMFilterMixin` and `NodesListFilterMixin` with `NodesFilterMixin` on all nodes list views.
- /v2/users/<user_id>/nodes/ 
- /v2/users/<user_id>/registrations/
- /v2/institutions/<inst_id>/nodes/
- /v2/institutions/<inst_id>/registrations/
- /v2/nodes/
- /v2/registrations/
- [OSF-8085](https://openscience.atlassian.net/browse/OSF-8085)

[feature] Use NodesFilterMixin in Nodes List Views [OSF-8085]

---

osf/management/commands/populate_fake_preprint_providers.py
scripts/update_taxonomies.py

- Fixes error when running `update_taxonomies`:
```
File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/code/scripts/update_taxonomies.py", line 74, in <module>
main()
File "/code/scripts/update_taxonomies.py", line 69, in main
update_taxonomies('bepress_taxonomy.json')
File "/code/scripts/update_taxonomies.py", line 30, in update_taxonomies
bepress_provider, _ = update_or_create(OSF_PROVIDER_DATA)
File "scripts/populate_preprint_providers.py", line 50, in update_or_create
provider_data['domain_redirect_enabled'] &= PREPRINT_PROVIDER_DOMAINS['enabled'] and bool(provider_data['domain'])
KeyError: 'domain_redirect_enabled'
```
- Add data …

[feature] Fix update_taxonomies and populate_fake_preprint_providers [No Ticket]

---

admin/base/utils.py
admin/preprint_providers/forms.py
admin_tests/preprint_providers/test_views.py

- Exclude custom taxonomies from subjects acceptable in admin app.
- Allow all subjects to be unchecked when creating a preprint provider (in order to set `subjects_acceptable = []` which represents the full bepress taxonomy/all subjects allowed).
- Filter `get_top_level_subjects`
- Don't require `subjects_chosen` and `top_level_subjects` fields in the preprint provider form.
- Becca doesn't get to check as many boxes.
- [OSF-8119](https://openscience.atlassian.net/browse/OSF-8119)
- [OSF-8125](https://openscience.atlassian.net/browse/OSF-8125)

[feature] Fix Admin App Setting Subjects for Preprint Providers [OSF-8119] [OSF-8125]

---

website/templates/public/pages/support.mako

Spell github correctly on osf.io/support page
Reapply changes made in https://github.com/CenterForOpenScience/osf.io/pull/7284
that got overwritten when fixing merge conflict.
https://openscience.atlassian.net/browse/OSF-7165

[Feature] Correct github spelling on support page [OSF-7165]

---

docker-sync.yml

When running docker-sync in daemon mode, it writes a pid file and log file to .docker-sync, which it then tries to sync. This results in writing to the log, syncing the log, ad infinitum.
Added .docker-sync to sync_excludes and watch_excludes for osf.io
N/A
N/A

Add .docker-sync to sync_excludes and watch_excludes for osf.io

---

admin/static/js/preprint_providers/preprintProviders.js
admin/templates/preprint_providers/update_preprint_provider_form.html

- Prevent admin app `502` when attempting to save a preprint provider after editing checkbox fields (`allow_submissions` or `domain_redirect_enabled`).
- Don't call `addSubject`/`removeSubject` when non-subject checkboxes are clicked (resulted in NaN values since `allow_submissions` and `domain_redirect_enabled` are boolean fields).
- [OSF-8146](https://openscience.atlassian.net/browse/OSF-8146)
- https://sentry.cos.io/sentry/admin-hl/issues/279945/

[feature] Fix Admin Handling of Checked Inputs [OSF-8146]

---

admin/static/js/preprint_providers/preprintProviders.js

- Fixes importing a preprint provider from JSON in the admin app.
- Add handling for all non-text fields when importing (boolean fields, tinymce fields, subjects, and licenses). Fix `subjects_acceptable` handling to only check subject checkboxes.
- Whenever a new field is added to the admin app for creating/updating a preprint provider, we need to make sure it imports and exports correctly. Especially if it's anything other than a simple text field.
- Broken fields included:
- subjects_acceptable
- licenses_acceptable
- description
- advisory_board
- footer_links
- domain_redirect_enabled
- allow_submissions 
- Please check that all of the above fields import correctly now. 
- Please test **all** fields to ensure everything imports and exports correctly.
- Pay special attention to how …

[feature] Fix Admin App Import Preprint Provider [OSF-8016]

---

tests/test_views.py
website/project/views/node.py
website/routes.py

[#OSF-8108]
Got a little over-zealous removing old api v1 endpoints -- turns out `add_pointer` is still used by the frontend!
- re-add `add_pointer` route, method, and tests
https://openscience.atlassian.net/browse/OSF-8108

Re-add API v1 routes for adding pointers to nodes [OSF-8108]

---

api/base/filters.py
api_tests/institutions/views/test_institution_nodes_list.py
api_tests/nodes/filters/test_filters.py
api_tests/nodes/views/test_node_list.py
api_tests/users/views/test_user_nodes_list.py

- Fix filtering nodes by date in the API.
- Add tests to check filtering nodes by dates.
- Handle lists of operations in `ListFilterMixin` as `filter[date][eq]=day` becomes `[filter[date][gt]=day-1, filter[date][lt]=day+1]`.
- [OSF-8155](https://openscience.atlassian.net/browse/OSF-8155)

[hotfix] Fix Filtering by Date [OSF-8155]

---

api/preprint_providers/serializers.py
api_tests/preprint_providers/serializers/test_serializers.py

- Un-versions preprint provider `email_support` field since ember-preprints displays this field on provider error pages.
- [OSF-8173](https://openscience.atlassian.net/browse/OSF-8173)

[hotfix] Return Preprint Provider `email_support` [OSF-8173]

---

tests/test_preprints.py
website/preprints/tasks.py

Defaulting to `False` for share updates causes other calls to this method to fail.
e.g. https://github.com/CenterForOpenScience/osf.io/blob/master/osf/models/preprint_service.py#L232
TODO: **Once released, manually resend all preprints starting June 10th.**
```python
from website.preprints.tasks import on_preprint_updated
preprint_ids = PreprintService.objects.filter(date_modified__gte=datetime.datetime(2017, 6, 9)).values_list('guids___id', flat=True)
for pid in preprint_ids:
print(pid)
on_preprint_updated(pid, update_share=True)
```

Send updated preprints to SHARE be default

---

tests/test_identifiers.py
tests/test_registrations/test_embargoes.py
tests/test_views.py
website/project/views/node.py
website/project/views/register.py
website/routes.py

It appears that the following endpoints are unused by the frontend and can therefore be removed:
- GET /api/v1/project/<<pid>>/forks/ (view is still used for mako endpoint, but API endpoint is unused)
- GET /api/v1/project/<<pid>>/register/<template>/ (view is still used for mako endpoint, but API endpoint is unused)
- PUT /api/v1/project/<<pid>>/
- DELETE /api/v/1/project/<<pid>>/
- GET /api/v1/project/<<pid>>/identifiers/
- GET /api/v1/project/<<pid>>/statistics/ (view is still used for mako endpoint, but API endpoint is unused)
- GET /api/v1/project/<<pid>>/files/
- GET /api/v1/project/<<pid>>/permissions/beforepublic/
- POST /api/v1/project/<<pid>>/permissions/<permissions>/
- Remove the specified API v1 routes and views where appropriate
- Remove references to the routes and views in …

Remove unused APIv1 project endpoints and views [OSF-8109]

---

api/preprints/serializers.py
osf/models/preprint_service.py
osf/models/subject.py
tests/test_preprints.py
website/preprints/tasks.py
website/util/share.py

OSF-side of https://github.com/CenterForOpenScience/SHARE/pull/653
* Update `Subject` serialization process
* Include information about deleted subjects when a `preprint.subjects` M2M relation changes
Tagged `[HOLD]` because this shouldn't go in until SHARE's ready for it.
Extension of [OSF-7788](https://openscience.atlassian.net/browse/OSF-7788)

[HOLD] SHARE subject serialization [OSF-7788]

---

addons/figshare/messages.py
addons/figshare/models.py

Display correct error message for internal Figshare errors, or other unexpected errors originating on their end.
Now when we catch errors from Figshare we always attribute them to Figshare.
Figshare errors can't be rethrown to as OSF errors.
https://openscience.atlassian.net/browse/OSF-8176

[hotfix][OSF-8176] Figshare errors locks user out of project 

---

admin/preprint_providers/forms.py
admin/templates/preprint_providers/update_preprint_provider_form.html

ember-preprints PR [#401](https://github.com/CenterForOpenScience/ember-preprints/pull/401) needed
- Adds the ability to create columns in the editor for the preprint provider advisory board field. 
- Adds the ability to directly edit HTML fields in the admin app (in case of emergencies). 
- Edit TinyMCE configs.
- [OSF-8145](https://openscience.atlassian.net/browse/OSF-8145)

[hotfix] Edit Admin Editors [OSF-8145]

---

osf/management/commands/force_archive.py

Extends #7351 and #7377 
* Don't mark registration as finished archiving until WB finishes copying
For non-OSFS addons, must be ran twice -- the second time after WB finishes copying, and with the `--skip-collisions` flag.
[[OSF-8185}}(https://openscience.atlassian.net/browse/OSF-8185)

[Hotfix] Handle archival edge case [OSF-8185]

---

api/preprint_providers/serializers.py

-  Fixes submit button not displaying on OSF Preprints landing page.
- Fixes https://osf.io/preprints/submit `404`ing.
- Remove `DevOnly` from preprint provider fields. Preprints app needs these fields from the API so everything isn't broken.

[hotfix] Remove DevOnly from Preprint Provider fields in API [No Ticket]

---

admin/preprint_providers/forms.py

- https://github.com/CenterForOpenScience/ember-preprints/pull/406
- Allows (minimal) styling of preprint provider HTML fields in the admin app.
- Adds `style` to the list of allowed attributes and `text-align` to the list of allowed styles for preprint provider HTML fields.
- [OSF-8206](https://openscience.atlassian.net/browse/OSF-8206)

[feature] Admin App Allow Styling in Preprint Provider HTML Fields [OSF-8206]

---

docker-compose.override.yml

Allow linking to emberosf-sync.
Emberosf-sync volume accidentally named ember-osf-sync  the docker-compose.override.yml. Fixing this.
None
None

Feature/fix name of emberosf-sync volume [No Ticket]

---

README-docker-compose.md

- The `populate_fake_preprint_providers` management command has replaced the `populate_preprint_providers` script for local development. This PR updates the README to reflect that change.

Update README with Preprint Provider Management Command [No Ticket]

---

website/static/js/navbarControl.js
website/templates/base.mako
website/templates/nav.mako
website/templates/public/pages/meeting.mako
website/templates/public/pages/meeting_landing.mako

Carries on from #7393 . Changes the `nav` from a `block` to `def` to avoid having to pass around functions. 
- Change nav from a `block` to a `def`
- Rename params
- Remove client-side logic (`currentService`)
https://openscience.atlassian.net/browse/OSF-7562

[OSF-7562] Render navbar server-side to avoid flashes of content

---

website/static/js/navbarControl.js
website/templates/base.mako
website/templates/nav.mako
website/templates/public/pages/meeting.mako
website/templates/public/pages/meeting_landing.mako

HOME and MEETINGS flash when loading. Also writes urls for HOME and MEETINGS backend side
No more flashy home 🔦 📸 💥 
na
https://openscience.atlassian.net/browse/OSF-7562
Check the home page, and various other pages to ensure the following data works properly
1. The text of title (HOME, MEETINGS)
2. Clicking HOME or MEETINGS goes to "/" or "/meetings/" respectively
3. The support button goes to the proper support location
Check both the base meetings page and a specific meeting page as these were modified separately

[feature] Use mako def for navbar [OSF-7562]

---

docker-compose.override.yml

Allow linking to emberosf-sync.
Emberosf-sync volume accidentally named ember-osf-sync  the docker-compose.override.yml. Fixing this.
None
None

Feature/fix name to emberosf-sync [No Ticket]

---

osf/models/preprint_service.py
scripts/generate_sitemap.py

- Make the sitemap generator more fast. 
- Use more Django magic (values, values_list, select_related, include).
- Remove `.iterator()` from loops.
- `preprint.primary_file.node._id` --> `preprint.node._id`
- Unsure if adding `IncludeManager` to `PreprintService` will have side effects... @sloria? 
- [OSF-8168](https://openscience.atlassian.net/browse/OSF-8168)
```
LOCAL
USERS=783; NODES=1021; PREP=352; TOTAL_URL_COUNT=2516;
OLD
time = [13.60890507698059, 13.498132944107056, 13.477915048599243, 13.3643319606781, 13.486894130706787]
queries (user) = 784
queries (node) = 1023
queries (prep) = 2113
NEW
time = [2.0950450897216797, 2.0373950004577637, 2.051614999771118, 1.997941017150879, 1.9991240501403809]
queries (user) = 1 
queries (node) = 1 
queries (prep) = 1 
```
```
STAGING
USERS=672; …
```

[hotfix] Optimize Sitemap Generator [OSF-8168]

---

api/base/serializers.py
api/users/serializers.py
api_tests/base/test_auth.py
framework/auth/oauth_scopes.py

- Adds private `osf.users.user_email` scope.
- Adds restricted `email` field to user serializer.
- Skip `email` field if USER_EMAIL scope is not present.
- Skip `email` field if requesting user != serialized user.
- Add `osf.users.user_email` scope tests.
- Confirm that the `osf.users.user_email` scope is not listed when creating a personal access token (osf.io/settings/tokens). 
- Add a runscope test (or add an assertion to an existing runscope test) to confirm that the `email` field never appears in a user response.
- [OSF-8148](https://openscience.atlassian.net/browse/OSF-8148)

[feature] Add USER_EMAIL Scope [OSF-8148]

---

admin/templates/base.html

Staging and Prod admin app have the same style and may be difficult to tell the difference.
Add custom style if dev_mode if off to make the style big and red for prod. Staging should stay the same.
BEFORE: 
AFTER:
N/A
https://openscience.atlassian.net/browse/OSF-8140
Confirm that admin looks the same on staging. Have someone confirm new color of admin on prod.

[feature] Custom admin style when dev_mode off [OSF-8140]

---

website/static/js/pages/project-dashboard-page.js

Prevent grey screen (modal backdrop) which occurs when the addComponent is clicked before the 
treebeard/fangorn filebrowser is fully added to the DOM.
Modifies the order in which Mithril draws mounted components by using
m.startComputation/m.endComputation to only allow one redraw. As a result,
the addCompnent button is not clickable till filebrowser is fully drawn.
https://openscience.atlassian.net/browse/OSF-8053

[Feature] Prevent redraw grey screen when add component is clicked quickly [OSF-8053]

---

website/static/js/filepage/revisions.js

Some addons do not have user data for revisions. Previously these were leaking information when viewed through anon vols, but this made it list anon user even if an addon did not have user data.
Only show anonymized user if addon shows users and has a user.
NA
https://openscience.atlassian.net/browse/OSF-7292
Test all addon revision pages both under normal conditions and through an anon VOL. "Anonymous User" should only show up for addons that show user info when viewed normally. The column width  weirdness (e.g., dataverse download header does not line up with the download button) matches how this was before things got broke'd. 
Note: Unpublished dataverses do not show up under VOLs, I made a ticket for this.

[feature] Remove file revision anonymous contributors if no user [OSF-7292]

---

api/nodes/serializers.py
api_tests/nodes/views/test_node_list.py
website/static/js/pages/project-dashboard-page.js

The feature to inherit tags from the parent node didn't account for tags that had just been added (tags which added on the backend, but not yet loaded in the frontend contextVars), this changes makes sure the contextVars always reflect reality.
On a successful Ajax request adding or removing tags, the contextVars are changed to reflect this.
https://openscience.atlassian.net/browse/OSF-7636

[OSF-7636] Fix bug in auto populating tags

---

api/base/settings/defaults.py
api/base/settings/local-dist.py
api/preprint_providers/serializers.py
api/preprint_providers/urls.py
api/preprint_providers/views.py

[#OSF-7948]
Preprint providers should not have subjects_acceptable in API response
Deprecated subjects_acceptable
New API version 2.5
Renamed PreprintProviderSubjectList to PreprintProviderTaxonomies as it is now only used by the taxonomies endpoint.
```
curl -s http://localhost:8000/v2/preprint_providers/agrixiv/ | jq '.data.attributes
' | jq keys
[
"additional_providers",
"advisory_board",
"allow_submissions",
"banner_path",
"description",
"domain",
"domain_redirect_enabled",
"email_contact",
"email_support",
"example",
"footer_links",
"header_text",
"logo_path",
"name",
"share_source",
"social_facebook",
"social_instagram",
"social_twitter",
"subjects_acceptable"
]
```
```
curl -s http://localhost:8000/v2/preprint_providers/agrixiv/?version=2.4 | jq '.data.attributes
' | jq keys
[ …
```

[RFR] [OSF-7948] Delete subjects_acceptable list from PreprintProviderSerializer

---

api_tests/nodes/views/test_node_contributors_list.py
osf/models/node.py

- Prevent unconfirmed users from being added as contributors via the API.
- Check `user.is_registered` in `node.add_contributors_registered_or_not`
- [OSF-7975](https://openscience.atlassian.net/browse/OSF-7975)

[feature] Prevent Unconfirmed User Contributor Additions (API) [OSF-7975]

---

admin/preprint_providers/views.py

Show acceptable licenses as formatted list
Modify admin preprintProviderDisplay view to show formatted list
of acceptable licenses.
https://openscience.atlassian.net/browse/OSF-8009

[Feature] Show licenses acceptable as formatted list [OSF-8009]

---

website/templates/prereg_landing_info.mako

Add COS eligible journal list link in the OSF preregistration challenge workflow steps
- Make 'eligible journals' a link pointing to COS eligible journals
https://openscience.atlassian.net/browse/OSF-7906

[Feature] Add link to cos prereg journals [OSF-7906]

---

website/static/js/profile.js

Use non-www impactstory link for profile (www alternative has no ssl cert). 
https://openscience.atlassian.net/browse/OSF-8095

[Feature] Fix impactStory profile url [OSF-8095]

---

webpack.common.config.js

Remove non-existant js module from webpack.common.config.js

[Feature] Remove non-existant js module from  webpack config [No ticket]

---

osf/models/node.py
osf/models/user.py
osf_tests/test_node.py
osf_tests/test_user.py
tests/test_auth.py
tests/test_citations.py

For some unregistered contributors, the API was showing the wrong name.  When there is a new unregistered contributor being added to a project, the API will automatically check if the email being used is already in use by another contributor.  If it is, it'll add the new unregistered contributor's name to a new field under the contributor that already exists.  
For citations it will get the first and last name fields of the contributor.  If the contributor is an unregistered contributor with an email that already exists, this can be an issue if the names aren't exactly the same.  
The changes include adding a conditional to the API's logic when making citations.  If the user isn't registered, it will get the unregistered_contributor field instead of the first/last name fields.  
For …

[OSF-8099] API citations show wrong names

---

api/addons/views.py
api/applications/views.py
api/base/views.py
api/citations/views.py
api/collections/views.py
api/comments/views.py
api/files/views.py
api/identifiers/views.py
api/institutions/views.py
api/metaschemas/views.py
api/nodes/views.py
api/preprint_providers/views.py
api/registrations/views.py
api/taxonomies/views.py
api/tokens/views.py
api/users/views.py
api/view_only_links/views.py
api_tests/taxonomies/views/test_taxonomy_list.py

Travis logs for API tests (and local tests with the `-s` flag added) were throwing quite a few `UnorderedObjectListWarning` errors, which clued us in to the problem that many API views are indeed unordered, and so could return inconsistent results when paginating through them.
Let's add ordering to API views!
- Add default `('-date_modified',)` ordering to many subclasses of`JSONAPIBaseView` 
- Add other orderings, mostly `('-id',)`, for other Views that aren't for a model with a `date_modified` field
- Update one taxonomies test to return results in the same way as the new view does for consistency
Pagination should now be consistent! So, none anticipated, but if anything was relying on inconsistent pagination (why would it?) this would go wonky. …

Add default API view ordering to get rid of UnorderedObjectListWarning [#OSF-8136]

---

addons/base/views.py
tests/test_addons.py

Send back a proper `302` response when a `HEAD` request is made to the file download endpoint.
e.g. `curl -O -v https://osf.io/87trm/download` is returning `HTTP 1/1 200 OK` w/ a `Location` header.
```
> HEAD /87trm/download HTTP/1.1
> Host: osf.io
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 07 Jul 2017 19:48:48 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Location: https://files.osf.io/v1/resources/pyvfg/providers/osfstorage/595e8a0f9ad5a1022c00ceb5?action=download&version=1&direct
< X-Frame-Options: SAMEORIGIN
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Expires: Mon, 01 Jan 1990 00:00:00 GMT
< Pragma: no-cache
< Strict-Transport-Security: max-age=16000000; preload;
```
This workaround was put in place during a …

[hotfix] redirect file head req

---

website/templates/util/render_node.mako

Prevent menu from showing on linked nodes (component and project)
Use `summary['primary']` for visibility check 
https://openscience.atlassian.net/browse/OSF-7442

[Feature] Do not show menu on linked nodes [OSF-7442]

---

scripts/triggered_mails.py

- Make `triggered_mails.py` less query intensive.
- MODM --> Django
- Possible that I've made a mistake and the the new queries aren't equivalent to the old ones? Tested against staging DB and got the same results for new and old queries though. See notes below.
- [OSF-8167](https://openscience.atlassian.net/browse/OSF-8167)
- **OLD**
```
In [14]: len(conn.queries)
Out[14]: 0
In [15]: inactive_users = User.find((MQ('date_last_login', 'lt', timezone.now() - osf_settings.NO_LOGIN_WAIT_TIME) & MQ('tags__name', 'ne', 'osf4m')) | (MQ('date_last_login', 'lt', timezone.now() - osf_settings.NO_LOGIN_OSF4M_WAIT_TIME) & MQ('tags__name', 'eq', 'osf4m')))
In [16]: inactive_emails = QueuedMail.find(MQ('email_type', 'eq', NO_LOGIN_TYPE))
In [17]: users_sent_id = [email.user._id for email in …
```

[feature] Reduce Number of Queries in Triggered Mails Script [OSF-8167]

---

api/nodes/serializers.py
api_tests/nodes/views/test_node_addons.py

- Fixes bug discovered while testing OSF-8058 (getting an error when saving redirect link with an empty label field).
- `allow_null` --> `allow_blank` in the forward settings serializer.
- From the DRF docs: http://www.django-rest-framework.org/api-guide/fields/#charfield
> The `allow_null` option is also available for string fields, although its usage is discouraged in favor of `allow_blank`. It is valid to set both `allow_blank=True` and `allow_null=True`, but doing so means that there will be two differing types of empty value permissible for string representations, which can lead to data inconsistencies and subtle application bugs.
- Sending `url=None` or `label=None` in a request payload used to be succesful, but will now fail with an appropriate error message.
- …

[feature] Fix Redirect Link Serializer [OSF-8058]

---

osf/models/user.py
osf_tests/test_search_views.py

Store user ssrn profile link in the database.
Currently, user ssrn profile link is not being stored to the database, hence does not
show social profile view and user search.
- Update osf user model to store ssn profile link.
https://openscience.atlassian.net/browse/OSF-7313

[Feature] Update osf user model to store ssrn profile url [OSF-7313]

---

website/templates/prereg_landing_info.mako

Use newer prereg eligible journals cos url
Use newer url `https://cos.io/our-services/prereg-more-information/` instead of ` https://cos.io/preregjournals` to prevent unnecessary redirect.
[OSF-7906](https://openscience.atlassian.net/browse/OSF-7906)

[Feature] Use newer prereg eligible journals url [OSF-7906]

---

admin/nodes/views.py
admin_tests/nodes/test_views.py

…dd test cases
Fix broken admin app routes (node/ flagged_spam, known_spam, known_ham)
One line fix to use order-by instead of sort in admin/nodes/views.py
Added response status code tests to make sure those routes don't break silently in the future
Before:
After:
None known.
Affected Admin Routes:
/nodes/flagged_spam
/nodes/known_spam
/nodes/known_ham
https://openscience.atlassian.net/browse/OSF-8249

[feature] Bug Fix: Fix Broken Admin Routes (Flagged Spam, Known Spam, Known Ham) [OSF-8249]

---

website/static/js/addProjectPlugin.js

In response to this this ticket: https://openscience.atlassian.net/browse/OSF-7636, the changes to fix this problem have already been merged here: https://github.com/CenterForOpenScience/osf.io/pull/7353, so we just have to revert the revert and will be at 100%.

Revert "Revert "[OSF-7636] Add ability to inherit tags from parent node""

---

website/templates/util/render_node.mako

Remove quick actions menu on registration (per product demo).
Use `summary['is_registration']` registration check 
[OSF-7442 ](https://openscience.atlassian.net/browse/OSF-7442)

[Feature] Do not show menu on regs at all [OSF-7442]

---

osf/management/commands/export_user_account.py
scripts/generate_sitemap.py
scripts/utils.py

- Adds a management command for exporting user accounts.
- Exports all of the projects, preprints, and registrations for which a user is a contributor. 
- For each node, wikis, files, and basic metadata will be exported.
- This could be horrendously slow, depending on how many nodes/files the user has.
- [OSF-8196](https://openscience.atlassian.net/browse/OSF-8196)

[hotfix] Export User Account [OSF-8196]

---

api/institutions/views.py
api_tests/institutions/views/test_institution_nodes_list.py

- Prevents registrations from being returned from /v2/institutions/<inst_id>/nodes/
- Remove aliasing of AbstractNode to Node.
- Add test.
- [OSF-8300](https://openscience.atlassian.net/browse/OSF-8300)

[hotfix] Remove AbstractNode to Node Aliasing in Institution View [OSF-8300]

---

website/conferences/views.py

- Display the correct category for meetings submissions. 
- Display the category of a meeting submission based on project tags, not system tags. The list of submissions for a meeting is already determined by project tags, not system tags.
- I *think* `system_tags` for OSF Meetings will be obsolete after this change, and we could consider removing them / not adding them when submission emails are processed.
- [OSF-7848](https://openscience.atlassian.net/browse/OSF-7848)

[hotfix] OSF Meetings Submission Tags [OSF-7848]

---

scripts/send_erpc_entrants_email.py
scripts/tests/test_send_erpc_entrants_email.py

The folks running ERPC want to contact the entrants to update them about the competition. They have given us email text to send to the entrants (anyone who has admin + read/write to a registration created with ERPC registration schema). We will send one email to them. The email includes a link to a Google form where the entrants can sign up to be contacted further.
- Script to gather all admin/write contributors to registrations using the ERPC MetaSchema. Then, if not used in dry mode, send an email to those participants.
https://openscience.atlassian.net/browse/OSF-8258

[hotfix] Script and test for sending email to ERPC participants [#OSF-8258]

---

osf/models/preprint_service.py
website/preprints/tasks.py

Previously, when the Preprint was loaded from the database, since it was
unsaved the first time around the incorrect information was being passed
along to SHARE on first pass didn't include the new identifier
information.
Use `preprint` in  `get_and_set_preprint_identifiers` instead of `preprint_id`
DOIs should get sent to SHARE the first time around now hopefully?
https://openscience.atlassian.net/browse/OSF-8321

Use Preprint object itself when initially requesting identifiers [OSF-8321]

---

api_tests/preprints/views/test_preprint_detail.py
api_tests/preprints/views/test_preprint_list.py
api_tests/preprints/views/test_preprint_list_mixin.py
osf/models/preprint_service.py
osf_tests/factories.py
tests/test_preprints.py

Celery tasks for minting a new DOI and then sending to SHARE were grouped so one was happening before the other was ready. 
- Chain the two tasks together so that one executes after the other!
https://openscience.atlassian.net/browse/OSF-8321

[hotfix] Chain tasks for preprint DOI minting and sending to SHARE [OSF-8321]

---

tests/test_identifiers.py
website/identifiers/metadata.py

We are now minting DOIs for Preprints. We're sending extra metadata to EZID for them to pass to DataCite. We are including ORCIDs for contributors in this metadata.
For proper disambiguation in SHARE, let's also include the OSF user's GUID in the EZID metadata
- Also include a user's OSF profile as a persistent identifier when sending preprint metadata to SHARE
- update preprint metadata format test
Older preprints will have inconsistent metadata, which shouldn't be a problem other than continuity. If they're updated at all, however, their EZID metadata should also be updated to include contributor's OSF urls. 
https://openscience.atlassian.net/browse/OSF-8131

Include OSF Urls for all contributors to preprints with EZID metadata [OSF-8131]

---

addons/osfstorage/models.py

[#OSF-7958]
On `OsfStorageFolder`, the properties `is_preprint_primary` and `is_checked_out` have a few recursive calls to see if a folder contains a preprint or checked out file. This can be optimized!
- optimize check for `is_preprint_primary`
- optimize check for `is_checked_out`
https://openscience.atlassian.net/browse/OSF-7958

Optimize checkout and is_preprint_primary checks for folders [OSF-7958]

---

osf/utils/migrations.py
osf_tests/test_utils.py

- Adds a context manager to prevent `auto_now` fields from being updated during migrations and scripts.
- Adds `disable_auto_now_fields` context manager and test in `test_utils.py`. 
- [OSF-8222](https://openscience.atlassian.net/browse/OSF-8222)

[feature] Add context manager for disabling auto_now updates [OSF-8222]

---

osf/models/institution.py
scripts/populate_institutions.py

- Optimizes `scripts.populate_institutions` 
- Removes the call to `update_node` for every affiliated node of every institution updated/created in the script. Instead, nodes will be updated in search if the institution is actually changed on save, i.e. if the name of an institution is changed in the populate script.
- Add `DirtyFieldsMixin` to `Institution` model. 
- Update `Insitution.save()` to check for changed fields before calling `update_node` for all affiliated nodes. 
- Whenever an Institution is saved (with a changed field, such as `name`), `update_node` will be called for every node affiliated with that institution. In theory, this shouldn't be a problem because `scripts.populate_institutions` is the only place where institutions are updated.
- …

[feature] Add DirtyFieldsMixin to Institution Model [OSF-8244]

---

.npmrc
Dockerfile

Updates Node.js to a maintained version
* Add .npmrc to ignore optional dependencies - would use yarn, but yarnpkg/yarn#2666 is needed before we can use it. `livedb`'s optional dependency, `hiredis` will not build on newer node.js versions.
* Update Dockerfile to use node.js version 8
* `npm cache clean` requires `--force` flag
* May affect the wiki / ShareJS, so we'll need to regression test that
* Assets should be unaffected, but again, something to watch out for
https://openscience.atlassian.net/browse/DEV-239

[DEV-239] Update to node.js version 8

---

osf/models/institution.py

- From [discussion with @sloria](https://github.com/CenterForOpenScience/osf.io/pull/7477#pullrequestreview-53857522): only update an institution in search if it has changed (i.e. check `saved_fields` first).

[feature] Check saved_fields before updating institution in search [No ticket]

---

osf/migrations/0044_basefilenode_uniqueness_index.py

Create a DB constraint preventing duplicate files
* Add migration
* Fewer than 5 minutes of downtime
* Next release from `develop` will require `makemigrations --merge` to be ran
[[OSF-8259]](https://openscience.atlassian.net/browse/OSF-8259)

[Hotfix] Fix duplicate files [OSF-8259]

---

admin/templates/base.html

[#OSF-8284]
Users with the view subject permission were still unable to see the subjects link in the sidebar because of a misspelled subject permission check -- it should not be plural.
- actually add correct permission in sidebar
I really really really need better proofreading skills
https://openscience.atlassian.net/browse/OSF-8284

Fix typo in Subject sidebar view [OSF-8284]

---

osf/models/preprint_service.py
scripts/generate_sitemap.py

sitemap urls point to non-redirected routes
Users custom domains for preprint providers that redirect
OLD:
NEW:
N/A
https://openscience.atlassian.net/browse/OSF-8282
Will be checked when MattC runs it, no QA needed
No tests; sitemap dun have any tests yet.

[wip][hotfix] Use custom domains for providers in sitemap [OSF-8282]

---

website/settings/defaults.py

Allow adding NUS users as contributors
Remove nus.edu.sg from blacklisted domains
[OSF-8198](https://openscience.atlassian.net/browse/OSF-8198)

[Hotfix] Allow nus users [OSF-8198]

---

admin/preprint_providers/urls.py
admin/preprint_providers/views.py
admin/templates/preprint_providers/update_preprint_provider_form.html
admin_tests/preprint_providers/test_views.py
osf/management/commands/populate_custom_taxonomies.py
website/static/test_bepress_taxonomy.json

Branded preprint provider taxonomies and licenses were not exporting/importing correctly between the staging and production admin app. 
This changes subjects and licenses so they are looked up by name rather than by ID.
Due to custom taxonomies (and how hard it would be to update them), when attempting to update a preprint provider, if subjects for that provider already exist, the subjects from the import json will be ignored.
https://openscience.atlassian.net/browse/OSF-8236

[feature fix] admin provider import export [OSF-8236]

---

api/nodes/views.py
api/users/views.py

`NodeAddonList` and `UserAddonList` don't currently have dates to be ordered by by default, switch those to `id` . 
Remove default ordering from addon folder list, as wasn't working with ODM filtering.
Worked on in conjuction with @TomBaxter !
- update ordering on `NodeAddonList`
- update ordering on `UserAddonList`
- remove default ordering from `NodeAddonFolderList`
https://openscience.atlassian.net/browse/OSF-8359
https://openscience.atlassian.net/browse/OSF-8347

Update default ordering for NodeAddonList and UserAddonList [OSF-8359] [OSF-8347]

---

admin/preprint_providers/views.py
admin_tests/preprint_providers/test_views.py

My [PR](https://github.com/CenterForOpenScience/osf.io/pull/7521/) for fixing preprint provider import export did not work correctly on staging. 
This PR removes taxonomy import/export and fixes some unicode and licenses problems. 
Importing/Exporting taxonomies will continue to not work.
Subjects should not change on import. A future ticket will fix this. If you are creating a new preprint provider it will assume the default - which is the full bepress taxonomy.
https://openscience.atlassian.net/browse/OSF-8236

feature/fixes to preprint provider import export[OSF-8236]

---

website/static/js/myProjects.js

There were many, many issues on the my projects page. This fixes a bunch of them. There are still more. 
Fixed issues:
1. Withdrawn Registrations and Pending Registrations no longer break Bookmarks, Collections, and All my Registrations
2. If a collection only has withdrawn/pending registrations in it, the empty banner will show up now.
3. Use Sparse fields to speed up some of the api calls (there is room for more of these still)
4. Fix typo that caused certain registrations related api requests to fail (I had this happen a few times but I couldn't isolate when it happened exactly, sorry).
5. Force refreshes to stop registrations from duplicating under certain circumstances (Todd had this happen and I had it occur locally). 
6. Stop the empty collection message from flashing when a …

[Feature] Fix MyProjects Page [OSF-8084]

---

osf/models/files.py
tests/test_addons.py

This PR complements [this PR](https://github.com/CenterForOpenScience/osf.io/pull/6835) as a fix for #6062 .
Suppose a github file name `README.md` exists for a repo connected to an OSF project, the `update()` method for this GithubFile would be called to update the file history when the following api v2 endpoints are called:
1. /nodes/<project_guid>/files/github
2. /nodes/<project_guid>/files/github/README.md
For the first endpoint, waterbutler would update the file history by passing a new entry (a dict whose value for key `modified` is `None`) to the `update()` method. For the second endpoint, however, waterbutler would do so with a dict whose value for `modified` is the actual time of modification.
Therefore, when `insort()` is called to insert the new data from waterbutler as a …

[OSF-8339] Fix API 502s when refreshing github metadata

---

website/static/js/components/logFeed.js
website/static/js/logTextParser.js
website/static/js/myProjects.js
website/static/js/tests/logTextParser.test.js

If many contributors are added at one, they make the log entry very long.
This changes the contributor added log text is created so that it only shows 3-4 contributors. If there are 4 it shows them all normally if there are 5 or more it shows 3 of the contributor names and then text that states "and 2 others."
I had to change the exports of `logTextParser` from a single export to a dictionary. This means that `LogText` will need to be grabbed by name any time it is used instead of just by importing `logTextParser`. The in most cases this change will look like this `LogText.LogText` instead of just `LogText` (depending on how the import is named).
Could easily make it so it always just says "and <#> other(s) added" but this seemed cleaner.
https://openscience.atlassian.net/browse/OSF-8346 …

Feature/shorten contributor logs [OSF-8346]

---

addons/base/views.py
addons/osfstorage/tests/test_views.py

When files are moved between providers the links in logs get broken. Instead of attempting to fix the links themselves, this PR redirects the url to the final destination by loading the deep url and constructing the proper link.
Redirect osfstorage links to new locations. Add tests.
NA
https://openscience.atlassian.net/browse/OSF-7684
For OSFStorage:
1. Test that links from logs in moved files redirect to the correct location
2. Test that moved and then deleted files do not redirect infinitely (note: they are not throwing a 410 resource deleted error, I'll make a ticket for that).
3. Test that valid log links work properly too.
4. Test that guid file links still work as intended.
Other providers:
Make sure unmoved links still work and broken links are still broken. This is important as …

[feature] Redirect bad osfstorage file urls [OSF-7684]

---

website/mails/mails.py
website/project/views/contributor.py
website/templates/emails/contributor_added_preprint_node_from_osf.txt.mako

Currently, when there is a preprint associated with a node and someone is added to that node as a contributor, there is no indication in the email that the node also contains a preprint. 
Added an email template to send when adding contributors to a node that contains a preprint.
All nodes with preprints will now receive this email instead of the default email when contributors are added. Both templates will need to be changed if the default template needs to be changed.
https://openscience.atlassian.net/browse/EOSF-412

Feature/Add email template for adding contributors to a preprint OSF node [EOSF-412]

---

osf_tests/test_generate_sitemap.py
scripts/generate_sitemap.py
scripts/tests/test_generate_sitemap.py

This PR aims to add unit tests to the sitemap generation script.
scripts/generate_sitemap.py is changed so that the url method for nodes and users are used to generate links.
test_generate_sitemap.py is added as unit tests.
https://openscience.atlassian.net/browse/OSF-8307

[OSF-8307] Add tests for sitemap generation.

---

website/static/js/profile.js

When users added '&' to their employment / education / social personal website link it resulted in being displayed as '&amp;'.
This replaces any '&amp;' with '&' in the personal website links and employment and education tabs on the profile page.
Modified profile.js to pick up on where '&amp;' was being displayed on the employment, education, and social tabs where applicable.
If a user were to have '&amp;' in their personal website social link it would likely break the link by replacing that with '&'
There may be other links under social where a user could put  an ampersand, so if that is the case this will need to be updated.
https://openscience.atlassian.net/browse/OSF-3945

[feature] Replace '&amp;' with '&' in Profile Tabs [OSF-3945]

---

website/templates/util/render_nodes.mako

Prevent users with write access from reordering registration's components
Add `is_registration` check to prevent users with write access to a registered node from
attempting to reorder components on a registration.
https://openscience.atlassian.net/browse/OSF-7688

[Feature] Prevent components reordering on a registration [OSF-7688]

---

tests/test_views.py
website/project/views/node.py
website/static/js/project.js

Fix issues with forking a pointer (node link) on the project
overview page, component list widget.
- Use json parameter, pointerId, as linked node id as opposed to a pointer/node-link id
- Rename parameter to avoid future confusion
- Update forkPointer tests
N/A
https://openscience.atlassian.net/browse/OSF-8062

[Feature] Fix forking a pointer [OSF-8062]

---

website/static/js/addProjectPlugin.js

Fix issue where a user submits empty (create component) 
form through enter key press.
- Prevent addProjectPlugin controller from sending request if project/component
title is not provided.
N/A
https://openscience.atlassian.net/browse/OSF-8162
##QA Considerations
- In add component form, try submitting empty form by pressing enter. The form should not submit, check the network tab in console to make sure no request is made.
- Type spaces in the component title and submit form with enter key press. The form should not submit
- Type spaces followed by letters say "      awesome title", should save and submit just fine. The spaces in the title will be trimmed, the title "awesome title".

[Feature] Prevent component create with empty title [OSF-8162]

---

api/institutions/views.py

Fix the problem registrations of institutions missing contrib names
Before change:
when you go to any institution page and click on all registration, you will see no contributors for registrations
After change:
Contributors will show up for all institution registrations.
https://openscience.atlassian.net/browse/OSF-8154

[#OSF-8154]Institutions pages: registrations missing contrib names

---

osf/management/commands/update_preprint_share_dates.py
osf/models/node.py
tests/test_preprints.py
website/preprints/tasks.py

SHARE is not actually updated when most preprint fields change. This is because it relies on the `date_modified` attribute of preprints, which currently only updates on preprint exclusive fields (those not on the node). When preprints are separated from nodes, this problem will disappear, but until then, we want to send SHARE a more realistic`date_modified` for preprints. 
This sends the greater of the node `date_modified` or the preprint `date_modified` to SHARE whenever a node associated with a preprint is updated.
There is also a management command that resends SHARE data for any node modified later than its associated preprint for all other preprints - this sends SHARE the later node `date_modified`.
Also, because it is hard to check when a primary file is updated, SHARE is updated …

Hotfix/update share preprint date modified[OSF-8388]

---

website/static/js/logTextParser.js
website/static/js/tests/logTextParser.test.js

When I shortened contributor logs (OSF-8346), I made a new function, getContributor list, which returned a list of contributors for the log to display. I forgot an `else` statement on one of the lines and unregistered contributors were being listed twice.
This fixes that mistake and adds unregistered contributors to my test.
None
https://openscience.atlassian.net/browse/OSF-8346

Feature/Make getContributorList handle unregistered contributors correctly [OSF-8346]

---

website/templates/project/settings.mako

[#OSF-8353]
Skip <script ... node-cfg.js> in project/settings.mako if registration
Updated website/templates/project/settings.mako
project/settings view growling about 404 for addon settings asregistrations have no addon settings. Surrounded offending call with "if not node.is_registration.
None
[OSF-8353](https://openscience.atlassian.net/browse/OSF-8353)

[OSF-8353] Registrations Settings Page is throwing 404 errors - Prod and Staging

---

admin/users/views.py
admin_tests/users/test_views.py
osf/models/user.py
osf_tests/test_tag.py

The syntax in the admin app for removing old system tags for users to indicate their spam status has been broken since Tag became a many-to-many relationship, and system tags were filtered out by default. Use the correct syntax to remove the relationship from the spam tags when appropriate
- Simplify `UserDeleteView` used by both `HamUserRestoreView` and `SpamUserDeleteView` for users
- Add tests for the admin "HamUserRestoreView"
- Add test for removing a system tag
- Remove old comment from user model
https://openscience.atlassian.net/browse/OSF-7760
To test this ticket, check the behavior of the "Disable Spam Account" and the "Re-enable Ham Account" buttons on a User's detail in the admin.
After clicking "Disable Spam Account":
- the system tag "spam_confirmed" should …

Remove system tags from user in admin when changing spam status [OSF-7760]

---

api/preprint_providers/serializers.py
api_tests/preprint_providers/serializers/test_serializers.py

[#OSF-7990]
Add attribute share_publish_type to PreprintProviderSerializer.
Add attribute share_publish_type to PreprintProviderSerializer.
Add test.
None
[OSF-7990](https://openscience.atlassian.net/browse/OSF-7990)

[RFR] [OSF-7990] Add attribute share_publish_type to PreprintProviderSerializer.

---

tests/test_views.py
website/templates/project/retracted_registration.mako

Mod meta change some things with the retractions template, and because of how it is imported (include iirc), the contributor_list needs a relative path. 
Add the proper relative path
NA
I attempted to add view tests. They passed (horray)... but I couldn't make them fail (boo). Stashed them for later. I think something about how Pytest is handling the view might handle the import properly. Any idea on how to get a failing test would be appreciated...
https://openscience.atlassian.net/browse/OSF-8517

[feature] Fix contributor_list import [OSF-8517]

---

api/files/serializers.py
api/files/views.py
api/users/serializers.py
api/users/urls.py
api/users/views.py
api_tests/users/views/test_user_detail.py
api_tests/users/views/test_user_files_list.py
osf/migrations/0053_add_quickfiles.py
osf/models/user.py
osf_tests/test_quickfiles.py
tests/test_quickfiles.py

QuickFiles needs a few improvements and a few additions to the file detail serializer when showing a detail page.
- Change API routes from `v2/users/files/` to `v2/users/quickfiles/` per product request
- Change user file relationship to quickfiles
- add `BaseFileSerializer` and split into two subclasses:
- normal `FileSerializer` for a standard file with the node relationship
- `QuickFilesFileDetailSerializer` that instead has the user relationship
- use `OsfStorageFile` over `BaseFileNode` where appropriate
- use  `QuickFilesNode._typedmodels_type` over `osf.quickfilesnode` where appropriate
https://openscience.atlassian.net/browse/OSF-8117

QuickFiles Improvements [OSF-8117]

---

osf/models/files.py
tests/test_addons.py

The [previous PR](https://github.com/CenterForOpenScience/osf.io/pull/7544) made a change to log to Sentry upon certain condition. However made the same mistake of failing to consider items with undefined 'modified' field. This PR fix this problem and adds a unit test checking for Sentry log.
Changes to logging condition to ignore when 'entry['modified']' is None. Added a new unit test.
None
https://openscience.atlassian.net/browse/OSF-8339

[OSF-8339]API 502 - Continued

---

website/static/js/logTextParser.js
website/static/js/tests/logTextParser.test.js

In shortening contrib logs, I ended up with an extra ', and' if maxShown == number of contributors.
Shown [here](https://openscience.atlassian.net/browse/OSF-8346?focusedCommentId=57030&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-57030).
I also realized that after adding the oxford comma, two contributors were added you would have an extra comma.
Remove this extra 'and'.
Remove the comma if there are only two contributors.
I also added/updated tests for these cases.
https://openscience.atlassian.net/browse/OSF-8346

feature/shorten contrib logs: Remove extra 'and' [OSF-8346]

---

osf/models/mixins.py
osf_tests/test_node.py
tests/test_views.py
website/project/views/node.py
website/static/js/project.js
website/templates/util/render_node.mako

**Addl. dev. for https://github.com/CenterForOpenScience/osf.io/pull/7368**
Forking a pointer should create a fork of the node the pointer/nodelink points to, leave the pointer
unchanged.
- Intended: forking a pointer should results in the pointer getting replaced by the fork of the node it points to. The fork should becomes a component of the parent node. 
- What's happening is that the pointer gets replaced by renamed pointer to the a fork of the project it points to.
- What's going to happen, we leave the pointer alone in its place as (non-primary) component, create and return a fork, prompt user to go to the (new) fork or keep working on current page.
- Prevent replacing pointer with renamed pointer to fork
- Fix fork-pointer tooltip
- Return fork and status code 
- Update tests …

[Feature] Fix issues with forking pointer [OSF-8062]

---

addons/osfstorage/views.py
framework/sessions/__init__.py

Prevent doing a db write every request unless necessary
* Remove unnecessary `Session` save in `after_request`
* Ensure session is saved when actually updating `auth_user_id`
None expected
[[OSF-8373]](https://openscience.atlassian.net/browse/OSF-8373)

Remove unnecessary Session save [#OSF-8373]

---

api/preprint_providers/serializers.py
api_tests/preprint_providers/views/test_preprint_provider_list.py

EOSF needs `allow_submissions` and `share_publish_type` filterable fields on preprint providers.
Add `allow_submissions` and `share_publish_type` filterable fields. 
I explored adding indices to the DB for the filters, but the table is small enough that it doesn't matter.
We now have preprint provider list view tests. Hooray.
https://openscience.atlassian.net/browse/OSF-8579
Test filtering on allow_submissions and share_publish type on preprint_providers:
api.osf.io/v2/preprint_providers/?filter[share_publish_type]=thesis
api.osf.io/v2/preprint_providers/?filter[allow_submissions]=preprints
api.osf.io/v2/preprint_providers/?filter[allow_submissions]=True
api.osf.io/v2/preprint_providers/?filter[allow_submissions]=False

[hotfix] Add Preprint provider filters [OSF-8579]

---

addons/base/views.py
website/templates/project/view_file.mako

Files that are not found lead to unable to resolve instead of nicely formatted not found pages (and are leading to a lot of sentry errors).
1. Fix mako template data to handle data that was not being formatted properly.
2. Use correct exception catch for oststorage files
NA
https://openscience.atlassian.net/browse/OSF-8570
1. Test non existent files on various addons (e.g., osf.io/<guid>/files/github/imnotarealfile/)
2. Try deleted addon files via guid
3. Try osfstorage files that don't exist (e.g., osf.io/<guid>/files/imnotarealfile)
In all the above cases, you should get a properly formatted error message and not an "unable to resolve" error

[hotfix] Fix error handling and mako template data [OSF-8570]

---

website/templates/base.mako

Speed up page loads
* Remove shim
The commit adding this didn't say why it was added, so the front-end might break in unexpected ways. It is believed that this was intended to fix a search issue on the "My Projects"/"Dashboard" page, but they appear to function properly without it. 
[[OSF-8381]](https://openscience.atlassian.net/browse/OSF-8381)

Remove shim [#OSF-8381]

---

api/base/filters.py
api/licenses/views.py
api/users/views.py

- Fix filtering by `id` on non-Guid objects.
- Determine filter `source_field_name` based on either `self.model_class.primary_identifier_name` or `issubclass(self.model_class, GuidMixin)`.
- None

[feature] Fix `id` Filtering

---

website/mails/mails.py
website/project/views/contributor.py
website/templates/emails/confirm_preprints_branded.txt.mako
website/templates/emails/contributor_added_preprints_branded.txt.mako
website/templates/emails/invite_preprints_branded.txt.mako

To change the wording in emails sent by branded preprint sites.
Change three email templates to make use of `preprint_word_singular` and `preprint_word_plural` fields. Add a migration file.
The change only works if the `preprint_word_singular` and `preprint_word_plural` fields for each PreprintProvider instances are set on prod/staging.
https://openscience.atlassian.net/browse/OSF-8421

[OSF-8421] Change "preprint" text to "thesis," etc in emails

---

osf_tests/test_search_views.py
website/project/views/node.py

- Fixes bad query introduced in #7527 
- Adds a basic test for the search_node view.
- [OSF-8309](https://openscience.atlassian.net/browse/OSF-8309)

[feature] Fix Node Query [OSF-8309]

---

api/base/utils.py
api/nodes/views.py
api/registrations/views.py
api/users/views.py
requirements.txt

- #7493 introduced a bug where the API returned duplicate registrations (and likely duplicate nodes as well). This PR fixes that. 
- Use subqueries in `default_node_permissions_queryset()` util to prevent duplicate nodes from being returned without having to use `.distinct()` everywhere. 
- Make `default_node_list_queryset` and `default_node_permissions_queryset` generalizable to nodes and registrations.
```
In [33]: qs = Registration.objects.filter(is_deleted=False) & Registration.objects.filter(Q(is_public=True) | Q(_contributors=me))
In [34]: qs.count()
Out[34]: 10454
```
vs.
```
In [3]: me = OSFUser.objects.get(username='casey@cos.io')
In [4]: sqs = Contributor.objects.filter(node=OuterRef('pk'), user__id=me.id, read=True)
In [5]: contrib_qs = …
```

[feature] Use Subqueries to Prevent Duplicate Records [OSF-8310]

---

api/base/filters.py
api_tests/nodes/views/test_node_list.py

- Fixes a bug that resulted in incorrect results being returned when filtering on multiple fields, if any of the filter fields were also used in creating the default queryset (i.e. filtering nodes by both `public` and `title`). 
- Slight modification to `ListFilterMixin`
- Mega test added.
- [OSF-8310](https://openscience.atlassian.net/browse/OSF-8310)

[feature] Fix Multiple Field Filtering [OSF-8310]

---

addons/osfstorage/models.py
addons/osfstorage/tests/test_views.py
addons/osfstorage/views.py
website/files/exceptions.py

[#OSF-8117]
The backend should also prevent moving and copying files in a Quick Files Node, so you can't be sneaky and use the API instead of the frontend. 
- Add quickfiles check to move and copy hooks
- add quickfiles exception to make things super clear (and to match checkout and preprint file handling)
- add tests to make sure they're caught properly 
https://openscience.atlassian.net/browse/OSF-8117

[feature] Prevent moving and copying quickfiles on the backend [OSF-8117]

---

docker-compose.yml

Use pre-built quay image for docker-compose (like other services)
build → image in docker-compose.yaml
N/A
N/A, QA not required

Change build to quay image for sharejs in docker-compose settings

---

addons/osfstorage/models.py
addons/osfstorage/tests/test_views.py

Allow a rename of a file via API - which turns out is the same as move!
- Check for moving within the same node for a quickfiles file and allow if so!
https://openscience.atlassian.net/browse/OSF-8117

Allow renames for quickfile files [OSF-8117]

---

osf/models/base.py

Optimize any API response for `GuidMixin`'d models
* Override default `count` behavior
None expected
[[OSF-8497]](https://openscience.atlassian.net/browse/OSF-8497)

Exclude included related fields when counting [#OSF-8497]

---

osf/management/commands/populate_custom_taxonomies.py

Require one less step in the admin module when populating custom taxonomies
* Add `--share-title` flag to script, required under certain conditions, ignored under all others
None expected
[[OSF-8633]](https://openscience.atlassian.net/browse/OSF-8633)

Set `share_title` in `populate_custom_taxonomies` [#OSF-8633]

---

api/identifiers/views.py
api/preprints/views.py
api_tests/identifiers/views/test_identifier_list.py

After the modm removal, the identifiers endpoint for preprints was returning too many identifiers!
-Update preprint identifier list, remove old override
- change default queryset for IdentifierList to return identifiers for that object
- make preprint identifier list test a bit more robust
https://openscience.atlassian.net/browse/OSF-8640

Preprint identifier list only return identifiers for that preprint [OSF-8640]

---

api/preprints/serializers.py
api/preprints/urls.py
api/preprints/views.py
api_tests/preprints/views/test_preprint_detail.py
api_tests/preprints/views/test_preprint_list.py

We soon want to move away from the node - preprint entanglement, now that using django and postgres has made that possibility way more convenient. This is the first step in that process, that will "fake" the change first in the API, now making it possible to `POST`  to `/v2/preprints/` and `PATCH`es to `/v2/preprints/<preprint_id>/ `to create and update *all* formerly node related attributes including `title`, `description`, and `contributors`.
**Current workflow (assuming creating a new node)**
1. `POST` to `/v2/nodes/` to create the node
2. Upload the file to the node's wb upload link via `PUT`
3. `POST` to `/v2/preprints/` to create the preprint with provider and relationship to node
4. `PATCH` to `/v2/preprints/<prerprint_id>/` to add subjects to the preprint
5. `PATCH` to …

[feature] Backwards-compatible API changes for preprint/node divorce [OSF-8488]

---

admin/users/views.py
admin_tests/users/test_views.py

Naive data time when workshop date is read in lead to failure of branches pushed after 8pm (till the next day).
Add time zone awareness to the read in date. I confirmed with Courtney that this should be okay. Most dates confirm to the UTC date, so this should not be a problem for their metrics. 
Refactored and simplified a few tests. Some where retesting the same thing in ways that was not adding value. Added 3 time-specific regression tests that should be able to catch failures with daylight savings and such. 
https://openscience.atlassian.net/browse/OSF-8089
No QA, no user facing changes that are easily testable.
Three regression tests were added. Two of those fail when the primary change (in the views) is reverted, so can confirm that they are working as intended. 
Other tests were …

[feature] Fix workshop test failures (that occur after 8pm EST) [OSF-8089]

---

api/base/filters.py
api_tests/nodes/views/test_node_list.py

- #7682 broke the ability to sort API endpoints that use `DISTINCT` by any non-default-ordering field, i.e. https://staging-api.osf.io/v2/nodes/?sort=-date_created 502'd.
- If a request contains ordering fields and the existing queryset contains distinct fields, add the ordering fields to the queryset's distinct fields.
- [OSF-8656](https://openscience.atlassian.net/browse/OSF-8656)

[feature] Fix API Sorting [OSF-8656]

---

osf_tests/test_search_views.py

`test_search_pagination_default_page_2` was failing probabilistically. 
All search tests in `test_search_views` were consolidated except for `test_search_projects_by_title`.
Should speed up tests
https://openscience.atlassian.net/secure/RapidBoard.jspa?rapidView=107&selectedIssue=OSF-8626

Feature/probabilistic test failure - pagination[OSF-8626]

---

framework/auth/views.py
tests/test_webtests.py

inactive users can reset passwords. They shouldn't be able to get in but it ain't great. 
Use is_active to determine if a user can receive emails for password resets instead. Do not show error message if attempting to reset passwords for an unconfirmed user. 
N/A
https://openscience.atlassian.net/browse/OSF-8652
1. confirm disabled users, unconfirmed users, spam users, don't get emails (and don't show the error message when trying to reset passwords). 
2. Confirm that normal password resets work.

[hotfix] Fix is_active password reset [Osf-8652]

---

website/static/js/components/logFeed.js
website/static/js/pages/project-dashboard-page.js

To solve an issue described in https://github.com/CenterForOpenScience/osf.io/pull/7277,
logs and tb filebrowser mounts where put in same mithril redraw.
Use `m.request` with `background : true` to prevent mithril redraws upon promise return, while
keeping part of solution in https://github.com/CenterForOpenScience/osf.io/pull/7277
- Have logFeed use with `m.request` with `background : true`
- Remove `m.startComputation/m.endComputation` pair
- Test this with a project that has lots of files, folders, and maybe several addons enabled. The point is to make the filebrowser take long to load. This fix should make it so the logs load independently and depending on the complexity/size of the files/folder/addons, logs may finish loading earlier.
- Check if the 'new component' button is only …

[Hotfix] fix mithril redraws [OSF-8587]

---

scripts/tests/test_populate_new_and_noteworthy.py
website/project/utils.py

Fix django query in util for getting popular projects and registrations -- Also fix unrelated tests discovered in testing this ticket
- update call in `website/project/utils.py` to filter by `guids___id` instead of `guid`
- fix tests in `test_populate_new_and_noteworthy.py`
https://openscience.atlassian.net/browse/OSF-8675

Fix call to find popular projects and registrations [OSF-8675]

---

scripts/analytics/institution_summary.py

Metrics is using the wrong contributors method so data is not being passed
Use the correct user count
NA
There are no tests for institutions metrics (but there is a ticket to add them)
https://openscience.atlassian.net/browse/OSF-8693
After this is run the plot on the institutions tab on metrics should pop back up to normal numbers:

[feature fix] Fix institution user count in nightly metrics [OSF-8693]

---

api/base/settings/defaults.py
api/preprints/views.py
api_tests/nodes/views/test_node_detail.py
api_tests/users/views/test_user_detail.py
framework/auth/views.py
osf/models/user.py
osf/utils/requests.py
osf_tests/test_user.py
tests/test_views.py

- Confirm `select_for_update` is used when user accounts are merged.
- Allow `select_for_update` to be easily disabled.
- Update `check_select_for_update` helper.
- Update tests. 
- [OSF-8297](https://openscience.atlassian.net/browse/OSF-8297)

[feature] select_for_update in merge_user [OSF-8297]

---

website/project/views/contributor.py

CAS login tokens expect a certain URL when logging in, and the
redirected url (/project/guid) does not match the URL that CAS is
expecting (/guid/).
Thanks @cslzchen for helping figure this one out!
- redirect directly to guid resolve project URL so that CAS can match the URL that the token was generated for
https://openscience.atlassian.net/browse/OSF-8714

Use resolve_guid route after confirming unregistered contrib [OSF-8714]

---

website/static/js/myProjects.js

Public was missing from the fields selected for the my projects page.
Add public so things can be displayed as public again.
PUBLIC BEFORE:
PUBLIC AFTER:
More awesomeness.
https://openscience.atlassian.net/browse/OSF-8721

[hotfix] Add public to node sparse fields [OSF-8721]

---

README-docker-compose.md

Add `docker` and `docker-compose` guide for runtime privilege configuration.
Update the file `README-docker-compose.md` .
No
No Ticket

[Feature] Add Guide for Docker Compose Runtime Privilege [No Ticket]

---

website/static/js/components/logFeed.js
website/static/js/pages/project-dashboard-page.js

Fix bug introduced in #7721
* Ensure UI redraws after log request completes
None expected. Tested to verify logs and files still load independently.
[[OSF-8713]](https://openscience.atlassian.net/browse/OSF-8713)

[Hotfix] Load logs [OSF-8713]

---

admin/pre_reg/views.py
admin_tests/pre_reg/test_views.py

Draft registrations were showing up in the order that the draft was initiated, not the order in which they were submitted for approval. Fix that!
- change ordering to `datetime_updated` over `datetime_initated`
- add a test to make sure this stays fixed
none anticipated!
https://openscience.atlassian.net/browse/OSF-8740

[hotfix] Order prereg submissions by datetime_updated [OSF-8740]

---

api/nodes/filters.py
api_tests/nodes/views/test_node_list.py

When making API calls with two or more filters including `parent=[null]`, filters after the parent null filter were being skipped
- Add special case filter to queryset in `NodesFilterMixin` that can then be returned to Super
This might make filtering a lot slower cause of the copy -- *is there a better way?!?*
https://openscience.atlassian.net/browse/OSF-8744

[hotfix] Other filtering ignored with filter[parent]=null [OSF-8744]

---

api/preprints/serializers.py
api_tests/preprints/views/test_preprint_detail.py

[#OSF-8734]
As another step in the node preprint divorce, add a few more fields to the Preprint serializer so that the frontend can pretend that Preprint is its own thing!
- add files to the preprint serializer
- add tags to the preprint serialzier
- add special case to update tags in preprint serializer since same is done in node serializer
- tests for updating tags
https://openscience.atlassian.net/browse/OSF-8734

[hotfix] Add files and tags to preprint serializer for node-preprint divorce [OSF-8734]

---

scripts/generate_sitemap.py

Right now the logs for the sitemap are only stored in the osf logs, which requires prod access to get into. The sitemap should send the first 10 errors it receives to sentry in addition to logging.
Simple python change logs the first 10 errors.
Tested it in the shell.
https://openscience.atlassian.net/browse/OSF-8385

[OSF-8385] Sentry log first 10 sitemap generation errors.

---

website/templates/public/register.mako

Now that we've added Thesis Commons, adding preprints to the names of all the preprint providers for the register pages no longer works.
The word preprints has been completely removed from the headings on the preprint register pages.
While the ticket said to simply remove the word 'preprints' from the Thesis Commons register page, after discussing this with @brianjgeiger he suggested removing the word 'preprints' from all of the preprint register pages as it is not necessary for understanding (a similar change was recently made to emails). 
None: Word change
https://openscience.atlassian.net/browse/OSF-8549

Feature/Remove 'preprints' from register pages [OSF-8549]

---

api/base/serializers.py
api/nodes/utils.py
api_tests/nodes/views/test_node_files_list.py

[#OSF-7927]
View only link API requests to api.nodes.views.NodeFilesList are failing because 'view_only' kwarg s not being passed.
Add 'view_only' kwarg to WB request, if present in OSF request.
Update api/nodes/views.py class NodeFilesList
Check for 'view_only' in request.query_params and pass to waterbutler_api_url_for if found.
Added test api_tests/nodes/views/test_node_files_list.py::TestNodeFilesList::test_vol_node_files_list
None
[OSF-7927](https://openscience.atlassian.net/browse/OSF-7927)

[OSF-7927] View-only link returns 403 for add-on files

---

package.json

keen/keen-tracking.js@9bbc71e8b2a0e301aab51ab677877172e8cc0dd2 causes the site to break
Pins the version of keen-tracking in package.json
We should switch to yarn and use `--frozen-lockfile` or `--pure-lockfile` flags to solve this problem.
N/A
Fixes the staging3 navbar problem
https://openscience.atlassian.net/browse/OSF-8760
cc @CenterForOpenScience/reviews

[OSF-8760] Pin keen-tracking

---

api/registrations/serializers.py
api/registrations/views.py
api_tests/registrations/views/test_registration_list.py
website/static/js/nodesPrivacy.js

Embargos are trying to terminate using then /nodes/ route which previously worked because of AbstractNode. Since it was changed to just Node, registrations can no longer bulk update privacy. 
1. Add Bulk updating to the registration api
2. Modify the privacy function to accept a `type` of node or registration
3. Add a boat load of tests for bulk updates
None known
https://openscience.atlassian.net/browse/OSF-8751
1. Confirm that you can still make projects (and their components) public/private (both by making the parent public and the nested components)
2. Ensure that making an embargo'd registration public works as expected

[hotfix] Add bulk registration update to allow embargos to be terminated early [OSF-8751]

---

osf/models/node.py

`get_root` is called after node creation. When registering a node with multiple components, it's called once per created registration, and is slow.
`get_children` is called when listing logs, and is slow for non-root nodes.
* Filter while recursing, reducing row count of built CTs
* Build CT for `get_children` in the logical direction (top-down)
None expected
[[OSF-8616]](https://openscience.atlassian.net/browse/OSF-8616)

[Hotfix] Improve RCTE's [OSF-8616]

---

website/static/css/log-feed.css
website/static/css/new-and-noteworthy-plugin.css
website/static/css/pages/profile-page.css
website/static/js/components/logFeed.js
website/templates/include/profile/jobs.mako
website/templates/include/profile/schools.mako
website/templates/include/profile/social.mako
website/templates/project/settings.mako

There are various places on the OSF that have strange wrapping. 
- Make authors with long names wrap instead of overflowing box in 'New and Noteworthy'.
https://openscience.atlassian.net/browse/OSF-7358
- Stop job titles and institutions from overflowing box on employment section of profile page.
- Fix overflow of 'enable wiki' section of project settings page.
- Fix overflow of 'personal websites' in the social section of the profile page.
(Also add icon to the personal websites section to balance out table.)
https://openscience.atlassian.net/browse/OSF-7477
https://openscience.atlassian.net/browse/OSF-7608
- Stop long usernames from being out of line with their gravitar.
(Even if a username is long enough to warrant its own line, keep it in line with gravitar.)
None
None: HTML/CSS …

Feature/fix wrapping[OSF-6788]

---

admin/pre_reg/views.py
admin_tests/pre_reg/test_views.py

[#OSF-8740]
In the admin, actually sort by the datetime that the approval was created, not the last time the draft registration was last updated.
- sort by approval creation date
- modify test
https://openscience.atlassian.net/browse/OSF-8740

[hotfix] Sort pre-reg submission by the date the approval was created

---

scripts/remove_after_use/send_2nd_erpc_email.py
scripts/remove_after_use/test_send_2nd_erpc_email.py

Send a second email to ERPC participants with a survey!
After the removal of all old/temporary scripts, figured it'd be best to add a new place in the OSF scripts directory for these temporary scripts and tests so that they're easier to identify and remove after they have been executed.
Here's a preview of the sent email as received by gmail:
- add a new `remove_after_use` directory inside the scripts directory
- Add a script to send email to ERPC participants with survey
- Add a test to ensure it is send to the right people
https://openscience.atlassian.net/browse/OSF-8726

[hotfix] Add temporary scripts directory and second email to ERPC participants [OSF-8726]

---

reviews/models/mixins.py
website/templates/emails/reviews_submission_confirmation.html.mako
website/templates/emails/reviews_submission_status.html.mako
website/templates/emails/reviews_update_comment.html.mako

Update HTML templates for update comments and status change notifications. 
Remove inheritance from notify_base.mako which has the base template (contains header and footer).  
Those two types of notifications are stored into the notification digest and later use the digest.html.mako, which already has both the header and footer, causing duplication in content. 
New submission notification is not stored in the notification digest (not using the digest.html.mako) template, therefore the inheritance from notify_base.mako is kept.
https://jsfiddle.net/sherifvt/yvhpx9d3/
https://jsfiddle.net/sherifvt/3b4rap7y/
https://openscience.atlassian.net/browse/MOD-132

[Improvement][MOD-132] Update email html templates

---

.travis.yml

* Removes node_modules directory (need to remove that later after travis cache problem is fixed)
* Waits for elasticsearch to come up to avoid non-deterministic failures h/t @icereval 
* Eliminates `rm -Rf` commands on treebeard and dropzone in node_modules (causes problems with yarn)

Don't delete pinned node modules

---

api/preprints/serializers.py
api/users/views.py
api_tests/preprints/filters/test_filters.py
api_tests/reviews/mixins/filter_mixins.py
api_tests/users/views/test_user_actions.py

Allow excluding preprints with private nodes from the reviews UI.
Allow filtering with `filter[node_is_public]=true` on all preprint list endpoints.
Exclude actions on preprints with private nodes from `/users/me/actions/`
None
https://openscience.atlassian.net/browse/MOD-110

[MOD-110][Fix] Allow filtering preprints by the node's is_public

---

api/base/filters.py
api/preprints/permissions.py
api_tests/nodes/views/test_node_preprints.py
api_tests/preprint_providers/views/test_preprint_provider_preprints_list.py
api_tests/preprints/views/test_preprint_detail.py
api_tests/preprints/views/test_preprint_list.py
api_tests/preprints/views/test_preprint_list_mixin.py
api_tests/users/views/test_user_preprints_list.py
osf_tests/factories.py

Allow contributors to see unpublished preprints in the review process.
* Contributors can see the preprint detail if provider uses reviews and the preprint is not in the initial state.
* Contributors can see preprint in preprint list if provider uses reviews and the preprint is not in the initial state. h/t @alexschiller
* Add tests
https://openscience.atlassian.net/browse/MOD-138

[MOD-138][Improvement] Allow contributors to see unpublished preprints

---

README-docker-compose.md
docker-sync.yml

`native_osx` is the new default strategy in docker-sync. It's quicker and more reliable than using unison on macOS: https://github.com/EugenMayer/docker-sync/wiki/8.-Strategies
- Change strategy to native_osx
- Update docs
Devs should be up to date with the latest docker-sync and restart their docker-sync containers
```
gem update docker-sync
docker-sync stop
docker-sync clean
docker-sync start
```

Use native_osx strategy for docker-sync

---

reviews/models/mixins.py

Don't say that the user will receive notifications for future emails if their default settings is "never".
Include no_future_emails in submission confirmation email
None
https://openscience.atlassian.net/browse/MOD-151

[MOD-151][Fix] Include no_future_emails in submission confirmation email

---

website/templates/project/edit_draft_registration.mako

Make primary action button on the "Edit draft registration" page more obvious.
As a user, it is unclear which button I am expected to click.
Change button text and color
None
None

Fix button styling and text

---

website/static/js/filepage/index.js

Various users have had trouble finding how to download a file ([flowdock thread](https://www.flowdock.com/app/cos/osf-love/threads/VchTXUUhylTmg-36RMl0tVXH7LB)). 
Change button styling and order to make "Download" the primary action.

[hotfix] Make download button more easily discoverable

---

addons/osfstorage/models.py
addons/osfstorage/tests/test_views.py
addons/osfstorage/views.py
website/files/exceptions.py

[#OSF-8841]
This reverts commit 45faea194b1c39243ecb17508f1cfc4a77e3879f.
Allow moving and copying of quickfiles into a project, reverse #7691 
- Remove checks and exceptions raised when attempting to move or copy a quickfile
- Reverse tests to make sure that they can be moved and copied
https://openscience.atlassian.net/browse/OSF-8841

Allow quickfiles to be copied and moved to a project [OSF-8841]

---

addons/dataverse/models.py
addons/figshare/models.py
api/base/views.py
api/nodes/views.py
api_tests/nodes/views/test_node_files_list.py
osf/models/files.py

External providers are super duper slow when there are lots of files. It scales linearly with the number of files because we update ALL files every time we hit a list endpoint. This PR makes it at least faster than it was before.
1. Use bulk_update to save everything at one time
2. Use bulk_create to create all new objects at one time
3. Remove permission check on every file (permissions are already checked earlier)
None Known
https://openscience.atlassian.net/browse/OSF-8794
1. It is important to test files that have never been viewed and those that have been viewed once. I'll detail an example of how to test below. I'm most concerned about dataverse and figshare, since they had a small change special casing that I did not test locally.
2. Testing the speed improvements is not 100% …

[hotfix] External storage speed fix [OSF-8794]

---

admin/static/js/metrics/metrics.es6.js
admin/templates/metrics/osf_metrics.html

Stickiness did not have needed context to be useful. Used previous month instead of last 30 days.
1. Use yesterday/previous 30 days now
2. Add stickiness for same day last week, month, year
Old:
New:
Note the change in % in the screenshots. Previously it was grabbing the previous month and comparing it to yesterday. So  yesterday's DAU / July Users  versus yesterdays DAU / yesterday + 29 more days DAU
https://openscience.atlassian.net/browse/OSF-7687
No tests, all front end JS changes that don't have tests.
Make sure everything renders, not much to it. Hard to verify the numbers exactly.

[feature] Change stickiness to use previous 30 days; add more stickiness metrics [OSF-7687]

---

admin/preprint_providers/views.py
admin_tests/preprint_providers/test_views.py

Now that all taxonomies are custom taxonomies, we can easily import taxonomies from staging.
I removed taxonomies from the excluded fields when importing a preprint provider.
https://openscience.atlassian.net/browse/OSF-8392

Feature/Add custom taxonomy import/export [OSF-8392]

---

api/institutions/serializers.py
api/institutions/urls.py
api/institutions/views.py
api_tests/institutions/views/test_institution_relationship_nodes.py
osf/models/institution.py
website/static/js/institutionProjectSettings.js
website/templates/project/project_header.mako
website/templates/project/settings.mako

Users should be able to update institutional affiliations on registrations.
This PR adds the ability to update institutional affiliations for registrations in two ways:
1. It adds the 'Project Affiliation / Branding' section to the settings page of a registration.
2. It adds an API endpoint at `/v2/institutions/<institution>/relationships/registrations/` that allows one to add/delete/view institutional registration relationships (this also supports the section added to settings).
3. Settings are now visible for all write contributors of a registration.
Also, `/v2/institutions/<institution>/relationships/nodes/` previously could add relationships for any AbstractNodes. This was a bug and was removed.
This PR also moves the 'Project Affiliation / Branding' section to the bottom of the …

Feature/add affiliation to registration [OSF-8514]

---

api/base/generic_bulk_views.py
api_tests/nodes/views/test_node_list.py
website/static/js/nodesDelete.js
website/static/js/nodesDeleteTreebeard.js
website/static/js/pages/project-settings-page.js
website/static/js/projectSettings.js
website/templates/project/nodes_delete.mako
website/templates/project/settings.mako

This PR aims to improve the deletion process of projects with components by adding a helper modal to the front-end, enabling site users to choose delete all the components when deleting a project.
There are two parts to this PR. 
The first part is a fix for the bulk deletion API. As of now, bulk deletion of a project and its components would fail even if all the components of the project are specified in postorder in the XHR request. The reason is that a database query to get all node instances does not preserve such order, resulting in error upon deleting nodes with undeleted child nodes.
Changes made:
1. In `api/base/generic_bulk_views.py`, `resource_object_list` is sorted according to the order specified in the request before returning.
The second part is a series of front end assets …

[OSF-8516] Add a modal for deleting projects with components.

---

osf/models/node.py
osf/models/registrations.py
osf_tests/test_node.py
osf_tests/test_registrations.py
scripts/fix_registration_unclaimed_records.py
scripts/tests/test_fix_registration_unclaimed_records.py

Registrations don't get unclaimed records. Fix that. 
1. When nodes are registered, copy over the unclaimed records
2. Script to fix old data
Fix deletion of unclaimed records when contributors are removed. Currently they stick around because of a missing save. Test for that was passing because data wasn't being refreshed from the DB.  Humorously this missing deletion oversight makes the script much more efficient to run and with less data loss.
https://openscience.atlassian.net/browse/OSF-8624
- Currently unclaimed users on registrations are not claimable via the registration. After the script is run these should work.
- Test creating a new registration with unclaimed contributors allows those contributors to be claimed via the registration.
- Test that creating a registration with …

[feature] Fix unregistered contributors registration records [OSF-8624]

---

admin/preprint_providers/views.py
admin_tests/preprint_providers/test_views.py

Currently if an admin tries to import JSON from an old preprint provider to create a new preprint with different fields they will be treated to an 502. This PR fixes that.
Single line python fix makes sure only fields in the current PreprintProvider model are included.
Any new fields added are automatically set to there default settings in the Preprint create detail.
Includes unit test.
https://openscience.atlassian.net/browse/OSF-8493

[OSF-8493] Admin import for preprints should be fault tolerant for new fields

---

website/static/js/nodesDeleteTreebeard.js

Fix treebeard grid issue where tb.treeData is unavailable because http requests have not returned.
See [Fix treebeards](https://github.com/CenterForOpenScience/osf.io/pull/7694/commits/09c5c21696299ba577d9466a11fdec315109bb32)
Use `ondataload` callback in `tbOptions`
[OSF-8516](https://openscience.atlassian.net/browse/OSF-8516)

[Feature] Use ondataload callback [OSF-8516]

---

api/base/views.py
api/nodes/serializers.py
api_tests/files/views/test_file_detail.py

Allow embedding of the quickfile's node's owner's information, aka user in the serializer, in a quickfiles detail page
- Use the `get_serializer` method when checking for fields that might have embeds instead of calling the property directly
- add tests
https://openscience.atlassian.net/browse/OSF-8874

[hotfix] embedding users on quickfile detail page [OSF-8874]

---

website/static/js/search.js

Fix js error on search results page which makes loading appear infinite.
The main issue occurs because elastic search returns (depending on the query)
`AFL3` as part of the license aggregates. `AFL3` is removed from licenses gathered
from license list. https://github.com/CenterForOpenScience/osf.io/blob/45451c06bbd22cb64c139a8e2590ecce9925c99f/website/static/js/licenses.js#L4
With no `AFL3` key in the initial `licenseCounts` list (built from licenses list), the filter returns empty array which upon indexing causes error and the `loading` binding to stay `true`.
https://github.com/CenterForOpenScience/osf.io/blob/45451c06bbd22cb64c139a8e2590ecce9925c99f/website/static/js/search.js#L395-L402
For now, just prevent JS error from happening using a simpler loop. …

[hotfix] Fix license lookup [OSF-8856]

---

scripts/analytics/institution_summary.py
scripts/analytics/node_summary.py
scripts/analytics/preprint_summary.py
scripts/populate_new_and_noteworthy_projects.py

Fixes for Node, Institution, and Preprint metric analytics.
Fixes to new and noteworthy root project query.
Node, Institution and Preprint metrics need to be re-indexed to keen.io for all historical dates.

[hotfix] preprint es query, get roots for metrics and noteworthy

---

scripts/fix_registration_unclaimed_records.py

Deleted registrations break the fix registration unclaimed records script. When a registration is deleted the connection back to the originating node is severed, which breaks the script. This PR removes deleted reg from the queryset of registrations to update. Note this is different than a retraction, deletions occur when a registration is canceled.
Don't update deleted registrations.
any registration that is un-deleted may need to be updated, but unlikely.
https://openscience.atlassian.net/browse/OSF-8624

[feature/fix] Stop script from updating deleted registrations [OSF-8624]

---

website/templates/emails/prereg_challenge_accepted.html.mako

Additional development for OSF-8548. Add address to end of email.
Add address
None
https://openscience.atlassian.net/browse/OSF-8548

feature/Add address to end of Prereg email [OSF-8548]

---

scripts/osfstorage/glacier_audit.py

- The glacier audit script makes references to a `FileVersion` field that doesn't exist (and which doesn't exist on the [develop-backup](https://github.com/CenterForOpenScience/osf.io/blob/develop-backup/website/files/models/base.py#L798) branch...)
- Remove the invalid reference.
- None.
- [OSF-8891](https://openscience.atlassian.net/browse/OSF-8891)

[hotfix] Fix Glacier Audit Script [OSF-8891]

---

api/preprints/permissions.py
api_tests/preprints/views/test_preprint_detail.py

Allow contributors to see private preprints for unmoderated services.
Use the same permissions for moderated and unmoderated providers.
Contributors can now see preprints that were submitted to an unmoderated service and then made private.
https://openscience.atlassian.net/browse/MOD-172

[MOD-172][Hotfix] Allow contributors to see private preprints for unmoderated services

---

scripts/approve_registrations.py
website/static/js/nodesPrivacy.js

Allow admins to make private/embargoed registrations public.
* Don't `forcibly_reject` non-deleted registrations stuck in archiving
* `PATCH` `/v2/registrations/<registration_id>/` instead of `/v2/nodes/<registration_id>/`
None expected
[[#OSF-8899]](https://openscience.atlassian.net/browse/OSF-8899)

[Hotfix] Handle edge case when making registration public [#OSF-8899]

---

website/static/js/contribAdder.js
website/templates/project/modal_add_contributor.mako

There are a couple problems with the current import contributors feature.
- It doesn't import non-bibliographic contributors
- It doesn't import the contributors permissions
- You can't modify a contributors the bibliographic status before you add them, only their permissions.
This fix will set the permissions and bibliographic status on import so you can import everyone in one click.
Changed the get_contributors_from_parent/ endpoint to get more info about the contributors permissions and bibliographic status, then modified the .mako and .js to display the new info without crowding the screen
Modified some of the wrapping in that dialog, so make sure that works in a sane way with long names.
Nothing special
https://openscience.atlassian.net/browse/OSF-8477

[OSF-8477] Import contributors in one click - fix pagination

---

api/base/serializers.py
api/logs/serializers.py
api_tests/nodes/views/test_node_logs.py
website/static/js/components/logFeed.js
website/static/js/logTextParser.js
website/static/js/myProjects.js

Follow-up to modify how registrations work. The `linked_node` field on logs did not return any data for registrations, which was further causing issues with how logs were being presented. 
1. Add conditional to linked_nodes and linked_registrations so that they only show up if the pointer is a node or registration. This means data for registrations is now accessible and won't be `not found` like it is right now.
2. Add a bunch of permissions tests for the registrations and confirm that the proper linked_* shows up.
3. Add linked_registrations to the myprojects page node logs, so those logs render the same
BEFORE nodes/{guid}/logs/ linked_node for a registration
NOTE: the nodes/qams8/ link goes to `Not Found`
AFTER nodes/{guid}/logs linked_node becomes `linked_registration`
NOTE: the …

[feature fix] Fix pointer logs for embargos and registrations [OSF-8607]

---

website/search/elastic_search.py
website/settings/defaults.py

Needed for TLS/SSL connection for staging
Add ELASTIC_KWARGS dictionary to defaults.py and use it in the elasticsearch client
N/A
No user-facing changes

Add ability to specify elasticsearch kwargs for SSL certs

---

osf/models/user.py
osf_tests/test_user.py

Currently it is possible to merge a user into itself which removes the user from all of their projects
This adds a check to see if they are the same user and stops it. This is not a 100% confirmed fix, but all roads point to it being one route through which the main bug occurs.
NA
https://openscience.atlassian.net/browse/OSF-8852
Just quickly make sure merges still work as expected, no testing of the actual functionality

[Hotfix] Stop self merges [OSF-8852]

---

requirements.txt
website/search/elastic_search.py
website/settings/defaults.py

Make elastic work with SSL/TLS (for real this time)
* Updates elasticsearch-py dependency to 2.4.0 (from 1.3.0) to match what we're using
* Fix typo in settings
Related:
* https://github.com/elastic/elasticsearch-py/blob/2.4.0/elasticsearch/connection/http_urllib3.py
* floragunncom/search-guard#401
* http://urllib3.readthedocs.io/en/latest/reference/urllib3.contrib.html#module-urllib3.contrib.pyopenssl
N/A

elasticsearch-py SSL/TLS update and fix

---

api/base/settings/defaults.py
framework/celery_tasks/__init__.py
requirements.txt
website/settings/defaults.py
website/settings/local-dist.py
website/settings/local-travis.py

Store beat schedule on database
* Use `django-celery-beat`
* Update default settings
* Update requirements
* Verified schedule mechanism works:
```
beat_1              | [2017-09-06 17:17:24,488: DEBUG/MainProcess] Current schedule:
beat_1              | <ScheduleEntry: embargo_registrations scripts.embargo_registrations(dry_run=False) <crontab: 0 0 * * * (m/h/d/dM/MY)>
beat_1              | <ScheduleEntry: retract_registrations scripts.retract_registrations(dry_run=False) <crontab: 0 0 * * * (m/h/d/dM/MY)>
beat_1              | <ScheduleEntry: daily-emails website.notifications.tasks.send_users_email('email_digest') <crontab: 0 0 * * * (m/h/d/dM/MY)>
beat_1              | <ScheduleEntry: new-and-noteworthy scripts.populate_new_and_noteworthy_projects(dry_run=False) <crontab: 0 2 6 * * …
```

[Feature] Add django_celery_beat [OSF-8605]

---

osf/models/node.py

- Make registrations a bit faster and less expensive.
- Remove unnecessary recursion in `register_node`.
- Deleted outdated comments.
- [OSF-8889](https://openscience.atlassian.net/browse/OSF-8889)

[feature] Remove unnecessary recursion in register_node [OSF-8889]

---

website/project/views/node.py

Fixes https://travis-ci.org/CenterForOpenScience/osf.io/jobs/302083572
```
flake8 .
./website/project/views/node.py:40:1: F811 redefinition of unused 'Node' from line 19
```
`Node` is imported on LL19 and LL40

Remove duped Node import

---

website/static/js/home-page/quickProjectSearchPlugin.js

**New hotfix**
Fix "create project" button on mobile.
When a user has no project, the "create button" was not clickable.
Fix bootstrap grid usage 
[OSF-8858](https://openscience.atlassian.net/browse/OSF-8858)

[hotfix] Fix unclickable button on mobile [OSF-8858]

---

osf/models/user.py
osf_tests/test_user.py
scripts/fix_merged_user_quickfiles.py

Merging users moves the quickfiles node. The files are moved properly away from the old quickfiles node, but the node itself also is moved. 
Stop moving quickfiles nodes when transferring node contributor-ship. Add script to run to fix merged users.
Stop potential bad things/weird things in the future.
Run the `fix_merged_user_quickfiles` script in --dry mode first to confirm everything works properly.
https://openscience.atlassian.net/browse/OSF-8911
Just merge a user and make sure everything works properly. I'll confirm that things are working properly on the backend.

[Hotfix] Stop quickfiles from moving with merges [OSF-8911]

---

api_tests/nodes/views/test_node_detail.py
api_tests/preprints/views/test_preprint_detail.py
api_tests/preprints/views/test_preprint_list_mixin.py
osf/models/node.py
website/identifiers/listeners.py

When a DOI is created on a node, it's status in EZID should change to "unavailable" if that node is made private, or is deleted.
- Add call to identifiers listener to also update a node's identifier on node delete, not just its preprint's identifiers
- Add call to `update_ezid_metadata_on_change` to update any existing DOIs on privacy change
- Modify tests for preprints to specifically check that `update_ezid_metadata_on_change` is being called
- Add new tests to check for that call when node privacy is updated or node is deleted
Shouldn't affect any existing tests, since none seem to create "doi" identifiers. If one is created in the future, one will have to mock the actual sending of EZID data in the tests
To test:
1. Create a public project
2. Create a DOI/ARK for that project
3. Check …

[hotfix] Update node identifiers when privacy changes or is deleted [#OSF-7229]

---

.docker-compose.mfr.env

[#SVCS-336] B
SVCS-336 adds functionality to override DOCKER_LOCAL_HOST in certain
situations required for some file types(pdf, pdb, and video) to render.
This addendum PR makes that behavior the default in our docker development
setup.
None
[SVCS-336](https://openscience.atlassian.net/browse/SVCS-336)

[RFR] [SVCS-336] Add env variable required for some file types to render in docker

---

website/search/elastic_search.py
website/search_migration/migrate.py

Query syntax errors from elasticsearch are raising an exception with 'search_phase_execution_exception' that is not caught properly. This is a hack-ish fix to get our builds passing and present a better error message via the api. Currently it is pasting the raw exception data on prod (which is enormous).
Catch `search_phase_execution_exception` and reraise as a MalformedQueryException.
Fix issue with variable name ordering (h/t @mfraezz)
https://github.com/elastic/elasticsearch-py/blob/1.3.0/elasticsearch/client/indices.py#L352
https://github.com/elastic/elasticsearch-py/blob/2.4.1/elasticsearch/client/indices.py#L337
Slightly less detail on error since the failed query is not passed back when this error is caught.
https://openscience.atlassian.net/browse/OSF-8944

[feature] Handle search_phase_execution_exception [OSF-8944]

---

admin/templates/preprints/preprint.html

Deleted preprints be broke on admin. 
There was a bit of django html gore that needed cleaning. 
na
https://openscience.atlassian.net/browse/OSF-8951
1. View a preprint with a deleted node and test the restore node button.
2. View a private preprint

[Hotfix] Make preprints with deleted nodes viewable via admin [OSF-8951]

---

api/files/views.py
api_tests/files/views/test_file_detail.py

Currently, looking up a deleted file via api file detail endpoint with **guid** returns 200 and the file object. 
Add check for `is_deleted` on the returned file object
[OSF-8963](https://openscience.atlassian.net/browse/OSF-8963)

[hotfix] Return 410 for a deleted file [OSF-8963]

---

api_tests/nodes/views/test_node_citations.py
osf/models/user.py
tests/test_citations.py

Any node with a disabled user will break citations on that node and any associated preprints
1. Allow disabled users to use fullname instead of defaulting to checking for unclaimed records (e.g., acting like an unregistered contributor)
2. Add citations tests to confirm that this works properly
Fewer sentry errors, the best side effect:
https://openscience.atlassian.net/browse/OSF-8831
Create a preprint with a user, Disable that user account and then confirm that the citations on the node and preprint work
Citations for unregistered contributors should also work (related but unlikely to break).

[hotfix] Fix citations for nodes with disabled users [OSF-8831] 

---

api/caching/listeners.py

- Fixes a caching issue that was causing forks and registrations to not work properly.
- Remove signal calling `ban_object_from_cache` 
- None expected, `ban_object_from_cache` was never called prior to #7801 
- Alternatively, this file could've been deleted, decided with @sloria to leave it in just in case. 
- [OSF-8941](https://openscience.atlassian.net/browse/OSF-8941)

[feature] Fix Failing Forks and Registrations [OSF-8941]

---

api_tests/users/views/test_user_detail.py
requirements.txt

Our attempt to upgrade djangorestframework to version 3.6.4 revealed some breaking changes in that particular release, that were also noted by the django-rest-framework-gis team [in the PR for the change](https://github.com/encode/django-rest-framework/pull/5259), namely that while trying to filter for HiddenFields in the form renderers (which we don't actually use, and are filtered out after the forms are created),  filtering in the browsable API assumes that the keys in `serializer.data` will correspond to fields on the serializer, which they don't in our case.
That same team later [created a PR to fix it](https://github.com/encode/django-rest-framework/pull/5499) , that was merged for the [3.7.1 release](https://github.com/encode/django-rest-framework/milestone/58?closed=1) of drf. …

Downgrade drf to 3.6.3 for now to fix breaking Browsable API changes [OSF-8966]

---

scripts/premigrate_created_modified.py
website/settings/defaults.py

Hotfix version of #7499 
> ## Purpose
> Allow data to be migrated slowly to prevent downtime
> 
> ## Changes
> * Add script
> 
> ## Side effects
> `website/settings` needs to be updated after script is ran with `--start`. See note in script
> 
> ## Deployment Notes
> 1. Run `python -m scripts.premigrate_created_modified --start`. This creates empty columns in the larger tables.
> 2. Add the following to `CELERYBEAT_SCHEDULE` in `website/settings`:
> ```
>    '1-minute-incremental-migrations':{
>       'task': 'scripts.premigrate_created_modified',
>        'schedule': crontab(minute='*/1'),
>    },
> ```
> 3. Wait about a week (until the new columns are populated), and merge `release/next-djangole`
> 
> 4. The deployment has been simplified; the "auto"-migrations will check settings and …

[Hotfix] Premigrate created/modified fields [#OSF-7986]

---

osf_tests/test_archiver.py
website/archiver/tasks.py

Celery trying to pickle an `AggregateStatResult` object when passing to the `archive_addon` archiver task was causing celery to freak out, as it wasn't JSON serializable. Turns out `archive_addon` doens't even use that result sooooo
- Remove the arg for `stat_result` from the `archive_addon` signature
- Don't pass the arg in the tests either
https://openscience.atlassian.net/browse/OSF-8987

Remove unused arg for archive_addon celery task [OSF-8987]

---

tests/test_views.py
website/views.py

When a Quick File has been deleted, the OSF should return a page not found rather than routing to Ember.
Add a condition to check if a Quick File is deleted and raise GONE if it is.
None
https://openscience.atlassian.net/browse/EOSF-933

[EOSF-933] Raise GONE for deleted quick files view

---

website/util/rubeus.py

- Fixes a bug where the files page only serialized components within two levels of `node.root` instead of `node` (i.e. if you were on a component page, you wouldn't see two levels of children).  
- Compares the given node to a `grid_root` (the node whose file page you're on) instead of the ultimate root (`node.root`)
- Adds a bit of documentation since this isn't the clearest thing in the world.
- [OSF-8677](https://openscience.atlassian.net/browse/OSF-8677)

[feature] Files Page Fix Components [OSF-8677]

---

website/archiver/__init__.py
website/archiver/tasks.py

Take 2!
These are used in celery tasks, which serialize things to JSON. Before, we were passing around the raw objects, which was breaking in the upgraded celery - hence making them JSON serializable by subclassing dict!
- change access of serialized objects to dict access after passing around by tasks
- make StatResult and AggregateStatResult subclassses of dict
hope not 
https://openscience.atlassian.net/browse/OSF-8987

fix serialization for  StatResult and AggregateStatResult [OSF-8987]

---

website/project/views/node.py

- Fixes a bug where public components that a user is not a contributor on were being listed as "Private Project" in the add contributor modal. 
- Check `is_public` as well as permissions when determining read access.
- None
- [OSF-8536](https://openscience.atlassian.net/browse/OSF-8536)

[feature] Fix private project when adding contributors [OSF-8536]

---

tasks/__init__.py
tests/test_notifications.py
website/notifications/emails.py
website/notifications/tasks.py

Don't send notification emails to disabled users. This seems like an obvious thing, but was an edge case that we didn't encounter for a long time. 
Rather than setting the user to receive `'none'` notifications upon disably, this keeps their old settings in case they are later restored, and checks to make sure that any user about to receive a notification email does not.
* Ignore disabled users when calculating notifications
* Add test
Also fixes upstream flake8 error
[[OSF-8998]](https://openscience.atlassian.net/browse/OSF-8998)

[Hotfix] Disable notifications for disabled users [OSF-8998]

---

admin/preprint_providers/forms.py
admin/preprint_providers/views.py
admin/static/js/preprint_providers/preprintProviders.js
admin/templates/preprint_providers/enter_custom_taxonomy.html
osf/management/commands/populate_custom_taxonomies.py

The custom taxonomy script changed just a bit since this was written - let's fix it!
- be sure to set `BEPRESS_PROVIDER` in the `validate` method as well, which is called seperately to check input
- add the `merge` form fields while we're at it, why not
- Parse out the error messages from the script into strings so that they can be rendered nicer
- Only show Bepress subjects in the dropdowns to make things faster
nope
https://openscience.atlassian.net/browse/OSF-8559

Fix custom taxonomy form in admin [OSF-8558]

---

website/project/views/node.py

- Fixes a bug where component names were not displayed to the administrator on a parent project.
- Removes  `can_read` permission checks in `node_child_tree`. It is guaranteed that the given user has admin permission on the given node, so checking for read permission on each child isn't necessary.
- Added some docstrings because who doesn't love additional documentation of old/complicated v1 routes.
- Faster! Removing some of the `.has_permission('read')` checks will give a slight performance boost.
- Otherwise, none expected. I confirmed that `node_child_tree` is only used when admin permission is required (adding contributors, removing contributors, deleting projects, changing project privacy). 
- [OSF-8536](https://openscience.atlassian.net/browse/OSF-8536)
h/t to @laurenrevere for …

[feature] Fix component name display on contrib page [OSF-8536]

---

website/search/elastic_search.py
website/static/js/components/publicNodes.js
website/static/js/logTextParser.js
website/static/js/myProjects.js
website/static/js/nodeControl.js

Stop ampersands from showing up as &amp; in project descriptions, in titles on the profile page, and activity logs.
Decode project descriptions on project, institutions dashboard, and search pages. (Am I missing other locations?)
Decode project titles on public projects and components user profile pages.
Decode project titles in activity logs.
Descriptions were not showing up on the my projects page because they were not included in `sparseNodeFields`. This PR also fixes that.
Not a side effect, but to keep this fix consistent, any time the project description is used people will need to make sure to decode the ampersands.
None needed. Only changes ampersand visualization.
https://openscience.atlassian.net/browse/OSF-8865

Feature/fix ampersands in project description (and then some) [OSF-8865]

---

website/static/js/keen.js

Keen fails when adblock is on and sends an error EVERY TIME.
Check if google analytics iframe exists, if it does, no adblock and can send the error. If there is a useful error message also send it.
None Known. Fewer sentry errors that are useless?
https://openscience.atlassian.net/browse/OSF-8935
Check adblock on and off to see if sentry is still sending errors to staging. I can help you check if desirable.

[feature] Stop sending Adblock Keen errors to sentry [OSF-8935]

---

api/base/serializers.py
api_tests/nodes/views/test_node_files_list.py

Add view_only param to node files list api endpoint
Modify api.base.serializers to check for vol in params 
and add vol param to wb action links. 
[OSF-8820](https://openscience.atlassian.net/browse/OSF-8820)

[feature] vol url param [OSF-8820]

---

website/templates/public/pages/support.mako

Currently, it takes two clicks to actually get to frequently asked questions.
Update "Visit FAQ" button  to link to actual questions.
None
None needed: just link change.
https://openscience.atlassian.net/browse/OSF-8920

Feature/update FAQ link [OSF-8920]

---

website/static/js/registrationUtils.js

Decode HTML in project -> "View Registration Form"
Registration Form data is HTML encoded before storing in postgres.
This PR HTML decodes data before presentation. Specifically &amp; , &gt; and, &lt;
Best effort has been made, but this PR should be reviewed with an eye towards javascript injection.
[OSF-8522](https://openscience.atlassian.net/browse/OSF-8522)

[RFR][OSF-8522] Special characters do not render on registration forms

---

website/static/js/pages/file-page.js
website/templates/project/view_file.mako

This PR makes file title editable in file detail page.
In `file-page.js`, the file title element is made editable by using the bootstrap-editable library. 
None
https://openscience.atlassian.net/browse/OSF-8710

[OSF-8710] File title is made editable in file detail page

---

website/static/js/profile.js
website/templates/include/profile/names.mako

Enable citation preview on user profile setting page when only full name is specified.
Originally, the "impute" api v1 endpoint would only be called whenever the user hits "Auto-fill" button to auto-fill the specific names. However, if we want to show citation preview using only the full name information, we have to impute the full name upon page load and on changes and then get the corresponding MLA/APA citation previews.
Therefore, in `profile.js`, four more knockout observables are added. The `impute` function is changed to be invoked on page load and subsequent changes and store the imputed names to the added observables. An `autoFill` function is added to set the specific name fields from imputed name observables when user click the button. `citeMla` and `citeApa` is changed to user …

[OSF-8237] citation preview available even if individual fields are not filled

---

admin/preprint_providers/views.py
admin/templates/preprint_providers/detail.html
admin/templates/preprint_providers/list.html

The logo links for preprint providers were broken in the admin app.
Removed the provider logos from the preprint provider list view.
Fixed the link for the preprint provider detail view.
None
None needed, purely frontend.
https://openscience.atlassian.net/browse/OSF-8704

feature/fix admin preprint provider logos [OSF-8704]

---

api/users/serializers.py
website/templates/include/profile/names.mako
website/templates/public/register.mako

It is possible to send us really large names through our profile settings page. This is possibly a security risk.
Put character limits on the frontend inputs where name fields exist (profile settings and registration).
Put a character limit of 200 characters for fullnames in the api.
Note: Most of the fields were limited at 255 characters (the maxlength specified on the user model), but `fullname` was limited to 200 characters. It turns out quickfile nodes are named after the user's full name and stops the user from being able to create a full name that is longer than 200 characters.
Not a side effect of _this_ ticket, but fullnames can no longer be more than 200 characters.
None needed because most purely frontend and the one api change is small. …

Feature/add name limits[OSF-8729]

---

website/templates/footer.mako

Remove 'Explore' and replace with 'Status' in footer
before change:
after change:
This pr doesn't remove or adjust the https://osf.io/activity/, even though it is not displaying properly and not something used recently. This page is still used in other places in osf:
https://github.com/CenterForOpenScience/osf.io/blob/develop/website/templates/landing.mako#L260
https://github.com/CenterForOpenScience/osf.io/blob/develop/website/templates/project/registrations.mako#L36
https://github.com/CenterForOpenScience/osf.io/blob/develop/website/language.py#L16
Unless there are some decisions made about the design and language change for those, cannot remove the code for the activity page.
https://openscience.atlassian.net/browse/OSF-8747

[#OSF-8747]Add links to status page

---

website/templates/public/pages/active_nodes.mako

Prevent newly private projects from showing in activity tabs. 
As the data for activity tabs (popular public, new and noteworthy)  are generated
by script (not on per-request basis), newly private may show with permissions errors.
Add extra frontend check to make sure newly private projects do not show in activity
tabs.
[OSF-7647](https://openscience.atlassian.net/browse/OSF-7647)

[Feature] Add extra check for newly private projects [OSF-7647]

---

admin/static/css/base.css
admin/templates/users/user.html
admin/users/serializers.py
website/profile/views.py
website/routes.py
website/static/js/accountSettings.js
website/templates/profile/account.mako

Currently if a user tries to deactivate your account they send a deactivation request to an admin who will review it and get back to them, so if they click it (and confirm it with a confirmation modal) by accident they can't rescind their request. This PR allows them to cancel their deactivation request.
Adds route for canceling request and minor front-end changes to call that route and display reinvent info about account status. 
I checked for pre-existing relevant tests and there weren't any. It would be beneficial to write some simple tests, but it should probably be done as a separate ticket. It just seems illogical to include tests for canceling a deactivation request when there are none for making a deactivation request. …

[OSF-6477] Allow the user to cancel the deactivation request for their account.

---

addons/github/static/githubFangornConfig.js

We flat out forgot to put a "Download As Zip" button in the GitHub Fangorn interface... Until now.
The Download as zip is put in the GitHub Fangorn interface.
https://openscience.atlassian.net/browse/OSF-7619

[OSF-7619] Add Download-as-zip button to GitHub Fangorn interface

---

addons/github/static/githubFangornConfig.js

The "Open" button in for GitHub in fangorn always takes you to to the page for the default branch regardless of what branch you've selected in the dropdown menu. This PR sends you to the right page.
Simple js one-line change updates repo url.
https://openscience.atlassian.net/browse/OSF-7620

[OSF-7620] In Fangorn, Github's [Open] button only points to the default branch

---

admin/nodes/views.py
admin_tests/nodes/test_views.py

Currently if a admin tries to mark a registration as Ham the process fails, this fix ensures the registration is marked correctly.
Simple one line python change.
There are no existing unit tests for the existing group of "mark as Ham/Spam" views, I didn't think it was appropriate write a test to cover this single case without expanding the ticket to cover other methods and views.
https://openscience.atlassian.net/browse/OSF-7831

[OSF-7831] Allow nodes AND registrations to be marked as Ham

---

admin/static/js/preprint_providers/preprintProviders.js
admin/templates/preprint_providers/update_preprint_provider_form.html

When modifying preprint info on the admin page there's no way of discarding your changes, even if you restart the page everything is cached and your likely to forget your initial configuration. This fix gives the user a hard refresh in the form of a Discard button.
Add a new discard buttom with a js prompt that restarts the page without a cache.
https://openscience.atlassian.net/browse/OSF-8007

[OSF-8007] Cancel changes button on admin preprint config

---

tests/test_registrations/test_views.py
website/project/views/drafts.py

Currently if a user has two versions of a draft open (like in two tabs) they can submit one for review and submit the other without review and this leads to some confusing behavior. This fix stops the user from being able to do this.
Add line for submit_for_review function which rejects already registered nodes.
There was a test associated with this behavior, but it was bad and would produce a false positive every time. I fixed it, possibly there are other false positives in that test class.
https://openscience.atlassian.net/browse/OSF-8051

[OSF-8051] Prevent submitting an already registered draft for review.

---

addons/osfstorage/models.py
api/logs/serializers.py
api_tests/logs/views/test_log_detail.py
tests/test_addons.py

Currently when you create a folder in osfstorage, and go to the `logs` view of its node in the api you will see urls ('view' and 'download') for the folder. These folder links are incorrect and should be removed.
1. Stop new osf_storage folder links from being added to logs when new logs are created. 
2. Remove osf_storage folder links from api serialization (this stops the api from showing the old urls that already exist in the database).
There will be an inconsistency in the information osf_storage_folder_created `nodelog`s have. Newer osf_storage_folder_created logs will have no urls, while older logs will still have the incorrect urls (we just won't show them).
https://openscience.atlassian.net/browse/OSF-8121
If you find a node with existing folders and go to …

feature/remove folder urls from logs [OSF-8121]

---

admin/nodes/serializers.py
admin/nodes/urls.py
admin/nodes/views.py
admin/templates/nodes/node.html
admin/templates/nodes/node_logs.html

Allows admins to view the logs of private projects.
Simple changes to the admin node.html page and and serializers.py to expose log info.
https://openscience.atlassian.net/browse/OSF-8319

[OSF-8319] Add logs to admin app on node detail page

---

api_tests/preprints/views/test_preprint_list.py
osf/models/external.py
requirements/dev.txt
website/util/sanitize.py

When it comes to Python using dicts as default args there's some weird behavior. The dict used as a default arg is used every time that method is called, potentially growing and retaining old information, here's an example.
```
In [1]: def dict_leaks(label, attrs={}):
attrs[label] = "alive!"
print('{}'.format(attrs))
In [2]:  dict_leaks("dog")
{'dog': 'alive!'}
In [3]: dict_leaks("cat")
{'dog': 'alive!', 'cat': 'alive!'}
```
So pretty sneaky and bad.
I removed the instances of default dict arguments and changed the code so dicts are freshly instantiated. 
Would be nice if we could test for this but it would have to apply to all python code on the site to be meaningful.
https://openscience.atlassian.net/browse/OSF-8357

[OSF-8357] Remove dict as default args

---

addons/wiki/tests/test_views.py
website/project/views/node.py

Fix the problem that trigger for wiki widget "Read More" does not match display field length
before change:
after change:
https://openscience.atlassian.net/browse/OSF-8584

[#OSF-8584]Trigger for wiki widget "Read More" does not match display field length

---

addons/figshare/models.py

If you have unicode in your figshare username you currently can't connect to you account to osf, this fix stops the error and allows the accounts to be connected.
Simple one line fix stops python from throwing Unicode error.
It would be pretty involved to mock up a test for this and the behavior is largely dependent on FIgshare's client.
https://openscience.atlassian.net/browse/OSF-7423

[OSF-7423] Allow Figshare to work properly with unicode usernames

---

addons/dataverse/static/dataverseNodeConfig.js

When attempting to connect to a Dataset in Dataverse, when you receive a 500 it's always displayed as an "illegal character error". This fix makes sure the error is properly displayed.
One line fix of simple code typo
Can't think of any relevant tests.
https://openscience.atlassian.net/browse/OSF-8323

[OSF-8323] Incorrect error message is shown for Dataverse 500 error

---

website/static/js/filepage/revisions.js

Currently clicking the download link for the most recent revision of a file using the box provider send you to the a file detail page which tells you the file can't be found. This fix cause that button to download the file.
Simple one line js fix ensures current version is downloaded without revision parameter.
https://openscience.atlassian.net/browse/OSF-8127

[OSF-8127] Download URLs 404 for Box file revisions

---

admin/static/js/preprint_providers/preprintProviders.js

Currently admins adding or modifying preprint provider information can submit a preprint form with a blank domain, this causes bad redirects which the admins don't intend. This fix beefs up the validation to require the domain when the preprint provider has domain redirect enabled.
Smallish Jquery fix, I tried many different implementations (probably too many) using server side changes, but this Jquery fix was the best I came up with.
Know that I know of.
I couldn't think of any relevant tests. 
https://openscience.atlassian.net/browse/OSF-8195

[OSF-8195] Stop admins from redirecting to blank domain

---

addons/dataverse/static/dataverseNodeConfig.js
addons/dataverse/static/dataverseUserConfig.js
addons/dataverse/templates/dataverse_credentials_modal.mako

Show loader when user sends post request to authorize Dataverse.
- Add loaders to modal view
- Add loader state to modal controller
- Loaders disappear upon request return (failure/success)
- Disable save button while authorizing
N/A
[OSF-8602](https://openscience.atlassian.net/browse/OSF-8602)
**user settings**
**node settings**

[Feature] Show loaders when authorizing dataverse [OSF-8602]

---

website/static/css/log-feed.css
website/static/js/components/logFeed.js

Gravatar has a bit too much freedom.
Imprison the gravatar.
Before (My Projects Page):
After (My Projects Page):
None
https://openscience.atlassian.net/browse/OSF-8897
Check both the logs on the project overview page and the my projects page. The issue was some extra CSS added to the project overview page, which now should only be applied there.

[feature] Fix my projects page gravatar in logs [OSF-8897]

---

bower.json

Pin to latest commit at https://github.com/CenterForOpenScience/styles
Point to latest commit in bower.json instead of master.
[OSF-9009](https://openscience.atlassian.net/browse/OSF-9009)

[hotfix] pin to latest commit [OSF-9009]

---

website/static/css/pages/project-page.css
website/static/css/search-bar.css
website/static/js/pages/base-page.js
website/static/js/pages/project-base-page.js
website/static/js/pages/search-page.js
website/templates/base.mako
website/templates/nav.mako
website/templates/project/project_header.mako

Currently, the maintenance banner does not show up on all of the OSF pages. It also shows up slightly differently on the pages that it does show up on.
The maintenance banner functionality was added to the navbar instead of being added to individual pages. This makes it easy for the maintenance banner to work well on most OSF pages (as it can be a normal bootstrap row). 
Unfortunately, the maintenance banner does not work as seamlessly on pages that have elements  fixed directly below the navbar (such as the project navbar). On the search page and the project pages, the maintenance banner was moved to be below those elements instead of directly below the navbar.
The maintenance banner will now appear nicely on any page with normally placed elements, but if anything is placed in a `fixed` …

Feature/add maintenance alerts to all pages [OSF-7841]

---

website/profile/utils.py

PR 7629 resulted in bad URL for user profile image in nav bar.
This fixes it.
Remove trailing comma
Combine with testing for PR7629
None
[OSF-4338](https://openscience.atlassian.net/browse/OSF-4338)

Fix PR7629 OSF-4338 - remove trailing comma

---

website/profile/utils.py

user_profile image was medium in nav bar. Should have been small.
Resize user_profile_image
Combine with testing for PR7629
None
[OSF-4338](https://openscience.atlassian.net/browse/OSF-4338)

Resize user_profile_image OSF-4338

---

website/project/views/node.py

Fixes bug where addon's page will fail to resolve because of missing assets.
Adds check to so non-exsistent osfstorage/node-cfg isn't looked for.
If addon page loaded, this worked
https://openscience.atlassian.net/browse/OSF-8056

Check if asset path exists for addons

---

website/project/views/node.py

Previous checks only allowed certain assets which were not in the base addon directory to load, this fix checks correctly for all assets and removes the unsightly empty panel created by the absences of the default provider osfstorage.
Checks proper directory of assets in settings.BASE_ASSETS and stops default provider js from rendering,
All providers should enable properly and show there logo and connect account link, except osfstorage which should be totally gone from the bottom panel.
https://openscience.atlassian.net/browse/OSF-8056

[OSF-8056] Ensure Addon tab JS assets load properly 

---

.travis.yml
tasks/__init__.py

The "osf" job has recently been timing out. Have each job run in about the same amount of time by balancing the number of tests per job. From a recent build:
```
osf: ========= 2454 passed, 32 skipped, 1 pytest-warnings in 2082.91 seconds =========
else: ======== 1295 passed, 17 skipped, 1 pytest-warnings in 1417.41 seconds =========
api1_and_js: = 1171 passed, 61 skipped, 1 pytest-warnings in 1526.10 seconds =========
api2: ============== 1127 passed, 1 pytest-warnings in 1279.63 seconds ===============
api3: ========== 515 passed, 8 skipped, 1 pytest-warnings in 564.43 seconds ==========
```
* Move about 1k tests from job `osf` to `api3`
* Rename jobs appropriately
* `osf`->`addons`
* `api3`-> `api3_and_osf`
None required
None expected
None known

[Hotfix] Balance TCI jobs [No Ticket]

---

addons/gitlab/views.py

Fix bug
* Retain changes to auth tokens if an account's token changes
1. Connect GL account, confirm works. 
2. Revoke token through GL UI
3. Confirm doesn't work
4. Create new token, "connect or reauthorize" with it.
5. Confirm works
None expected
None known

[Hotfix] Update GL tokens [No ticket]

---

osf/utils/migrations.py
osf_tests/test_utils.py

The `disable_auto_now_fields` used in the `add_preprint_doi_created` migration was correctly disabling the auto_now fields, but not putting them back the way it found them. 
- Keep track of updated auto_now add fields and only reset the ones you changed
- Add a test to check for this in the future
This ticket does not need to be tested, as it's only for tests running on travis!
none
none

[hotfix] Fix auto_now context manager used in migrations [no ticket]

---

api/base/authentication/drf.py

Don't throw `500`s unnecessarily
* `try`/`except` cookie unsigning
If still experiencing white screen of death:
* Don't, hopefully
If not:
* None
[[OSF-9033]](https://openscience.atlassian.net/browse/OSF-9033)

[Hotfix] Ignore stale cookies [OSF-9033]

---

website/static/js/pages/file-page.js

Currently on staging, renaming a file on file detail page fails because of CORS issue. This PR should fix the issue.
add `crossOrigin: true`.
This should fix the issue discovered during QA testing.
https://openscience.atlassian.net/browse/OSF-8710

[OSF-8710] Rename file on file detail page: Fix for cross origin.

---

website/util/rubeus.py

- Fixes incorrect icons on the files page.
- Fix linked node subquery so that only linked nodes are annotated as linked nodes, instead of every child being annotated as a linked node if a single linked node child exists.
- Cross browser not needed. 
- Confirm that what you see matches the "after" image below for links v. components.
- [OSF-9038](https://openscience.atlassian.net/browse/OSF-9038)

[hotfix] Fix Files Page Icons [OSF-9038]

---

website/static/js/profile.js

Current on staging, auto fill button for profile citations are not working because jQuery 3 removed .success(). This fix the issue.
.success() is changed to .done().
None.
https://openscience.atlassian.net/browse/OSF-8237

[OSF-8237] Change to use .done() for jQuery 3.

---

addons/gitlab/api.py

Display all GL repos, not just the default page size
* Use client helpers to avoid front-end pagination
1. Own more than 20
2. Make sure they all show up
In the case where a user has far too many repos, loading them might take several extra seconds.
None known

[Hotfix] Display all GL repos [No Ticket]

---

website/static/js/fangorn.js
website/templates/project/modal_add_contributor.mako

Add the ability that when click on the profile info icon on add_contributor_modal will open a new tab instead of redirect the current tab. And fix a typo error for support email extract.
https://openscience.atlassian.net/browse/OSF-8510

[#OSF-8510]Search by contributor's profile information

---

website/templates/include/comment_pane_template.mako
website/templates/include/comment_template.mako

Fix the issue where submit/save button are greyed out
after maxlength hit but can still be clicked. 
Follow up PR https://github.com/CenterForOpenScience/osf.io/pull/7889
The cause: apply the tooltip binding on the same element that has
'disabled' binding sets 'pointer-events' to 'auto' which re-enables pointer-events. 
Apply the binding to wrapping span element
Test both three modes: edit, reply, comment. in all these place
make sure you cannot click after maxlength hit and that button is greyed out
and has the info tooltip.
[OSF-8870](https://openscience.atlassian.net/browse/OSF-8870)

[Feature] Disable click after maxlength hit [OSF-8870]

---

website/templates/project/forks.mako

Currently a bad relative link on the forks page send you a 404 if you come from the directly from the project overview. This fixes make the link absolute preventing the problem.
Changed link to use node url instead of relative link.
Go to the project overview page and click the fork icon, click View Forks then click Back to analytics, if you're now on the analytics page this fix worked. 
https://openscience.atlassian.net/browse/OSF-8055

[OSF-8055] Fix relative link from forks to analyltics page

---

website/project/views/node.py
website/templates/project/project_header.mako

Add-ons and settings have some problems on then navbar
1. Revert 'Settings' menu item to previous state
2. Stop 'Add-ons' from showing up on registrations, public nodes, and read contrib
3. Stop addons route from being accessible on registrations (it doesn't show anything)
4. Stop addons route from being accessible for read contrib (it breaks)
1. Make sure settings shows up how it should (on reg only for admin, on nodes for all contrib, not for non-contrib or not logged in)
2. Make sure addons shows up when it should
3. Make sure the addons route works only for those who can modify it properly.
NA
https://openscience.atlassian.net/browse/OSF-9045

[feature] Fix settings and add-on nav [OSF-9045]

---

osf/migrations/0074_parse_citation_styles.py

This is a follow up to [this PR](https://github.com/CenterForOpenScience/osf.io/pull/7595). Currently, `scripts/parse_citation_styles.py` has to be run to populate the CitationStyle instances for OSF. Discussed with Steve and he thinks it is better to add a migration to do so. This PR port the script so that the styles are automatically parsed upon migration.
`0074_parse_citation_styles.py` is added.
Make sure citation widget is working properly after this PR.
None.
https://openscience.atlassian.net/browse/OSF-3622

[OSF-3622] Add migration file to automatically parse citations

---

api/users/serializers.py
website/templates/include/profile/names.mako
website/templates/public/register.mako

I didn't realize that quickfiles add " 's quickfiles" to the end of a user's `fullname` when creating the quickfiles node. Since currently nodes can only have titles 200 characters in length, fullnames can only be 186 max. 
This will be fixed in [OSF-8994](https://openscience.atlassian.net/browse/OSF-8994?jql=text%20~%20%22node%20title%20limit%22) because node title limit will be increased. At that point, the limit for fullnames can go back to 256.
Change limits from the erroneous 200 to 184.
Make sure that changing fullname to have 186 characters does not fail on profile settings page. Make sure to wait to see the green "Settings updated"
Make sure creating a user with a 186 character name works
None
https://openscience.atlassian.net/browse/OSF-8729

Feature/Change full name length to 186 to account for quickfiles [OSF-8729]

---

admin/preprint_providers/views.py
admin_tests/preprint_providers/test_views.py

[#OSF-9046]
subjects_acceptable is less and less relevant now, and is causing all sorts of errors when importing into a new preprint provider without a custom taxonomy, as it uses _ids which don't match when moving between environments.
A quick thing is to just not export them, and instead rely on the actual Subjects (hopefully) set in the provider being exported. 
- don't export subjects_acceptable, because the import is optimized for subject relationships (that really should exist anyhow before export)
- also don't export `_id` so that you can go back and change it later but still get all the same settings as another provider
To test!
- Export a preprint provider with a custom taxonomy
- Import in the create section
- Make sure that the form imports correctly (it will be *very* slow as …

[hotfix] No subjects_acceptable or _id when exporting preprint providers [OSF-9046]

---

api/base/serializers.py
api_tests/nodes/views/test_node_files_list.py
osf/models/files.py

Add view_only url parameter to 'info' link for files endpoint
Follow up PR https://github.com/CenterForOpenScience/osf.io/pull/7871
- Add vol url param to info link
- Update tests
This is an API change. When looking up file detail say v2/nodes/jc3vf/files/github/?view_only=82b06ecfb70c448b95449c437a68ca0e Make sure the info has the view-only parameter as well.
[OSF-8820](https://openscience.atlassian.net/browse/OSF-8820)

[Feature] Add vol param to 'info' link [OSF-8820]

---

api/nodes/views.py
api_tests/nodes/views/test_node_forks_list.py
website/mails/mails.py
website/static/js/project.js
website/templates/emails/fork_completed.html.mako
website/templates/emails/fork_failed.html.mako

Forking emails and error messages have bad, casing, grammar and language. This fixes that.
Language and textual changes.
- Fork completed email should have the node title rather than the fork title;
- The line that says that they can opt-out of this type of email;
- Changed to sentence case from title case on the subject of the email;
- Used suggested wording for forking notification;
- Adjusted wording of body of success email based on suggestion and made it more compact;
- On failure email, re-worded so user sees that they can visit the original project, not the failed fork.
This should now match the language described in the original ticket.
Please verify that at least one other HTML email still gives the unsubscribe option. …

[OSF-8247] Fix Fork completion failure email language 

---

addons/wiki/tests/test_wiki.py
addons/wiki/utils.py
website/templates/project/settings.mako

The wiki disable button got lost in the shuffle of changing view attributes, this fix restores it and makes disabled wikis appear in the wiki configure panel.
HTML changes to make button visible and JS changes to allow disabled wiki nodes to still appear (This needed because their children may be configurable, even though they are not.)
Try complex branching hierarchies with both enabled and disabled wikis.
https://openscience.atlassian.net/browse/OSF-8269

[OSF-8269] Changes to allow for enabling/disabling of wikis.

---

website/static/css/pages/statistics-page.css
website/templates/project/statistics.mako

Responsiveness for the newly added panels on the analytics tab is not very good, this fix addresses that and improves their padding.
CSS changes to add better responsiveness and padding for the analytics panels.
Chrome and Firefox look the same. 
There are still still issues with Safari that are documented in the ticket and will likely be resolved later.
https://openscience.atlassian.net/browse/OSF-8055

[OSF-8055] Fix padding and responsiveness for analytics page metrics.

---

admin/nodes/serializers.py
admin/nodes/views.py
admin_tests/nodes/test_views.py

Currently the logs in the admin app only show information strictly dealing with the node being observed and not it's children, this is a bit different then the public node logs which show some info like component creation which only is associated with the child, but not the parent.
This fix makes the queries for the normal osf.io node logs and the private admin app logs match.
- Changes query for the admin app private logs to match the logs on the node overview page.
- Adds unit tests for the admin node log view. 
- Create some components and see if they're logged in the admin logs.
- The node overview logs should now match the admin logs entry-for-entry.
https://openscience.atlassian.net/browse/OSF-8319

[OSF-8319] Fix admin app logs to show information about components

---

website/templates/project/forks.mako

After some changes were made on the forks page to accommodate changes to the analytics page things were a bit funky. The "Back to Analytics" button had no top padding and the "New Forks" button was out on alignment.
- Added some margin to the "back to analytics" link button.
- Brings the "New Forks" button back into alignment with forks panel.
Check for responsiveness on multiple browsers.
https://openscience.atlassian.net/browse/OSF-8055

[OSF-8055] Clean up forks page

---

website/templates/emails/fork_completed.html.mako
website/templates/emails/fork_failed.html.mako

Currently the fork sucess/failure emails use text labels on links instead of raw links, this fix makes things more consistent other emails by using the raw links.
- Fork success email now uses a raw link (osf.io/...) instead of label text ("here.")
- Fork failure email now uses a raw link (osf.io/...) instead of label text ("here.")
- You should know be able to see the full text of a link instead of the label, "here."
https://openscience.atlassian.net/browse/OSF-8247

[OSF-8247] Change fork emails to use raw link instead of text

---

website/static/js/wikiSettingsTreebeard.js

When you try configure a private wiki it gives you the message "This feature disabled for wikis of private project/components", this should be "This feature **is** disabled for wikis of private project/components"
- Changes text to read "This feature is disabled for wikis of private project/components"
Create a project and go to configure the wiki, if it is private and enabled you should see the message, "This feature is disabled for wikis of private project/components"
https://openscience.atlassian.net/browse/OSF-8269

[OSF-8269] Fix typo in wiki config

---

addons/dataverse/models.py
addons/figshare/models.py

Store metadata about touched addon files
* Use `super` to update `_history` and `last_touched`
Test that looking at Figshare/Dataverse files still work
None expected
[[OSF-8762]](https://openscience.atlassian.net/browse/OSF-8762)
[[OSF-8636]](https://openscience.atlassian.net/browse/OSF-8636)

[Feature] Improve metadata retention [OSF-8762][OSF-8636]

---

addons/base/views.py

Service Ticket: https://openscience.atlassian.net/browse/SVCS-488
MFR PR: https://github.com/CenterForOpenScience/modular-file-renderer/pull/304
Let OSF expose whether a file is public to WB and MFR. For MFR can use an external rendering service provided by Microsoft to render public `.docx` files.
Add `publice_file = node.is_public` as query parameter to the `download_url`,
which is a query parameter for the  `render_url`,
which is returned by `addon_view_file()`,
which is called by route `addon_view_or_download_file()`.
This change is based on the discussion with @sloria and @AddisonSchiller a while ago.
No
Please refer to the [Service Ticket](https://openscience.atlassian.net/browse/SVCS-488) or the [Service PR](https://github.com/CenterForOpenScience/modular-file-renderer/pull/304). …

[SVCS-488] Improve docx rendering - OSF Part

---

tests/test_rubeus.py
website/util/rubeus.py

Fixes a few bugs introduced by [OSF-8677](https://openscience.atlassian.net/browse/OSF-8677) (PR #7824)
- Component ordering wasn't being respected by the files grid.
- Private components were being serialized in the files grid as an unclickable "Private Component" row. Prior to the 0.125.0 release, private components were simply omitted from the files grid. 
- Note: this bug made it so that a public component nested within a private component wasn't accessible from the files grid.
- Makes use of `find_readable_descendants` so that nested private components will be serialized.
- Removes the `_get_node_name` method (after confirming it isn't used anywhere else) because non-viewable components are never serialized.
- Removes related tests. 
- Adds tests to confirm nested projects (with …

[hotfix] Files Page Fixes [OSF-9003]

---

api/nodes/views.py
api_tests/nodes/views/test_node_forks_list.py

Forks list in the UI does not include registrations of forks, but the api does. 
Remove registrations of forks from the nodes/<guid>/forks endpoint
Check that the nodes/[guid]/forks/ endpoint does not include registrations of forks.
NA
https://openscience.atlassian.net/browse/OSF-8422

[feature] Remove registrations of forks from forks endpoint [OSF-8422]

---

website/project/views/node.py
website/static/js/project.js

Add language change when the templated node is a registration.
After change: 
when the node is a project,
when the node is a registration,
https://openscience.atlassian.net/browse/OSF-7955

[#OSF-7955]Templating a registration breaks and creates a malformed registration

---

addons/base/views.py

Escape string, not object
* `escape` string.
* Use `getattr` due to possible Nonetype object
None required
None expected
None known

[Hotfix] Escape fullname rather than complex object

---

tests/test_addons.py
website/project/views/node.py
website/static/js/pages/project-addons-page.js
website/templates/project/addons.mako

Currently Github/Gitlab panel allow a user to connect their node to Github/Gitlab, but when the page refreshes the "Connect Account" button is still present and the account appears to the user as unconnected. This fix passes more information to the Github/Gitlab templates that allow them to recognize they'd been connected and allow the user to configure.
Also the addon name filter was filtering by short name. Noticeably "Amazon S3" was being sorted as "s3", now addons will be filtered properly by their full name.
- Reinstates the addon instances .to_json method, previously we had relied only on the AddonAppConfig's .to_json method. This allows Github/Gitlab to be used normally.
- The addon name filter now filters by the addons full name.
- Adds unit tests to ensure github/gitlab data is …

[OSF-8056] Fix Github/Gitlab on Add-ons Tab and improve filter

---

website/static/js/registrationUtils.js

Add a prompt to alert users about tagging for registrations.
In `registrationUtils.js`, a new message is appended to `preRegisterPrompts`.
For OSF-8691, there are two things to note:
1. Refresh the page after adding/removing tags in the tag widget to make sure the addition/deletion of tags persists.
2. Make sure the message "Tags on a registration can be modified at any time to enhance discoverability." appears in the modal when user click the submit button to register.
None
https://openscience.atlassian.net/browse/OSF-8691

[OSF-8691] Add alert for registration tags

---

website/templates/emails/fork_failed.html.mako

There's an extra row with some information in the fork failure email, this fix removes it.
Remove the "View the fork here" row from the fork failure email.
- Check the email, the line "View the fork here" should be gone.
https://openscience.atlassian.net/browse/OSF-8247

[OSF-8247] Remove unnecessary row from fork failure email

---

admin/templates/nodes/node.html

Be better
* Conditionally avoid a reverse lookup if it will fail
Viewing registrations in the admin app should fail less often
None expected
None known
Discovered while investigating [[OSF-8968]](https://openscience.atlassian.net/browse/OSF-8968)

[Hotfix] Avoid 502-generating NoReverseMatch errors [No ticket]

---

website/templates/project/project_header.mako

Write users can modify affiliations on registrations so actually should be able to see the settings page. In the past the only thing on the settings page was the withdraw button. 
Show affiliations for write users on reg
Check that settings shows up for write contrib.
NA
https://openscience.atlassian.net/browse/OSF-9045

[feature] Show settings for write users on registrations [OSF-9045]

---

addons/github/static/githubFangornConfig.js

Currently Github's Download-as-zip button only appears when the user is a contributor to that project. This fix makes the button visible and usable for all users.
Changed js condition to apply more broadly to all folders.
Look at a public project which has a Github addon, all folders in that addon should be downloadable as zip. Try as a contributor and non-contributor. 
https://openscience.atlassian.net/browse/OSF-7619

[OSF-7619] Make download as zip button visible to non-contribs

---

admin/static/js/nodes/registrations.js
admin/templates/nodes/node.html

When updating an embargo in the admin app, when you hit "Update embargo," a confirmation modal pops up. Currently, clicking that "Update embargo" button is submitting the form. The form should not be submitted until the user confirms using the modal.
Form is now submitted on the "Confirm" button of the "Are you sure you want to update this embargo?" modal.
Wait a couple of seconds before hitting "Confirm" to be sure that it is not submitting from clicking "Update embargo".
I also noticed that the "update embargo" button was disabled, but still clickable when validation failed. This also fixes that.
https://openscience.atlassian.net/browse/OSF-7846

Feature/Fix admin embargo update  [OSF-7846]

---

addons/base/models.py
osf_tests/test_archiver.py
tests/test_conferences.py
website/conferences/utils.py

Fixes conference uploads and archiving
Remove leading slash completely for file uploads
Remove size check for recursive folder stuff.
1. Check conference uploads, they should work now
2. Check archiving of a project with only a folder at the top level and containing a file. This is the broken edge case. 
NA
https://openscience.atlassian.net/browse/OSF-8696

[feature] Fix wbv0 uploads and archiving [OSF-8696]

---

website/static/js/pages/project-addons-page.js
website/templates/project/addon/page.mako
website/templates/project/addon/widget.mako
website/templates/project/addons.mako
website/templates/util/render_addon_widget.mako

On the Add-ons Tab the scroll spy (the navigation bar on the left hand side) is taking to use to the wrong elements of clicked and not highlighting correctly. This fixes that.
Also the "This addon is not configured properly" widgets on the node overview are still pointing to the settings page. This changes them the addon page.
**"This addon is not configured properly" pictured:** 
Also there are several user facing refferences to "Addons" instead of "Add-ons", so I have changed to use the agreed upon spelling.
- Scroll spy fixed
- "This addon is not configured properly" widget links changed
- "addons" spelling corrected to "Add-ons
- Check the the scroll spy takes you the right part of the page and observe that it highlights when the correct part of the page is scrolled over.
- Note that …

[OSF-8056] Fix language links and scrollspy for addons tab.

---

addons/gitlab/utils.py

Prevent errors when linking a repo as a group owner / master / developer. 
* Check for `group_access` in addition to `project_access`
None expected
[[OSF-9077]](https://openscience.atlassian.net/browse/OSF-9077)

[Hotfix] Respect GitLab group permissions [#OSF-9077]

---

admin/users/views.py
admin_tests/users/test_views.py

The implementation of OSF-6477 has uncovered a small bug in user reactivation, if a user requests deactivation, is deactivated and then reactivated, their deactivation request still stands. This is more apparent now that the user can see if their deactivation request is pending. This PR clears any deactivation request when the account is reactivated.
- One line change turns requested_deactivation to false when reactivated via view. 
- Corresponding change to unit tests
1. Have a user request deactivation 
2. Deactivate them as an admin
3. Reactivate them as an admin
4. Log back in as the reactivated user.
5. Observe the red "Request Deactivation" button, showing that the user no long has a deactivation request pending.
https://openscience.atlassian.net/browse/OSF-6477

[OSF-6477] Reset user's requested_deactivation status if they are reactivated

---

website/static/js/pages/project-addons-page.js
website/templates/project/addons.mako

There were some things about the add-on tab which didn't make sense:
- There was an "Enable Add-on" modal that was made redundant by the the "Add-on Capabilities" modal, this fixes removes it so you go directly to "Add-on Capabilities" to confirm the add-on.
- The links for enabling/disabling the add-ons were labeled connect/disconnect, this relabels them enable/disable.
- Changed link labels and styling
- Removed "Enable Add-on" modal, so it flows right into "Add-on Capabilities" modal.
- Observe the link buttons in the "Select Add-ons" panel say "Enable/Disable" instead of "connect/disconnect"
- Enable an add-on and see that the "Add-on Capabilities" modal comes up immediately.
https://openscience.atlassian.net/browse/OSF-8056

[OSF-8056] Improve Add-on tab with new product considerations

---

website/static/js/fangorn.js

Prior to any conflicts, the queue resolved to undefined. After conflicts it resolves to false. 
Fun fact: 
`undefined && true` returns undefined not false.
`false && true` returns false
Remove typeof check to just existence. 
Previously, if no conflict had occurred yet, moving a file from one folder to another would not show a modal. After a conflict the same file movement would show a modal. After a conflict, moving two files (one that has a conflict and one that does not) would initially show the conflict dialogue, but then immediately show the inaccurate moved modal. I can demo if this is confusing.
None Known
https://openscience.atlassian.net/browse/OSF-6466

[feature] Fix fangorn conflicts queue check [OSF-6466]

---

website/static/js/pages/file-page.js

Fix support for IE. Add GitLab and OneDrive as read only providers.
1. Change `includes()` to `indexOf()` to support IE 11.
2. Add two more read only providers.
None
None
https://openscience.atlassian.net/browse/OSF-8710

[OSF-8710] IE fix for file rename on detail page.

---

website/static/js/pages/project-dashboard-page.js

Data was being duplicated in the contextVar.node.tags because a second variable was referencing the same list. 
1. Remove this other variable and only use contextVar.node.tags.
2. Switch permissions for deletion on reload 
1. test deletion of immediately created tags and then refresh page to see if they stay deleted.
2. Test delete of newly created tags after refresh
Error handling is already pretty bad, this... doesn't make it worse... but really doesn't make it better.
https://openscience.atlassian.net/browse/OSF-8691

[feature] Fix bad data in tags deletion and permissions [OSF-8691]

---

addons/wiki/static/ShareJSDoc.js
addons/wiki/templates/edit.mako
website/static/js/filepage/editor.js
website/static/js/pages/ShareJSDocFile.js

Gravatars on wiki editing and file editing were accidentally kill.
Add them back.
**FILE EDITING**:
BEFORE:
AFTER:
**WIKI EDITING**:
BEFORE:
AFTER:
1. Confirm editing wiki collaboratively shows the gravatars
2. Confirm that editing files collaboratively shows the gravatars
NA
https://openscience.atlassian.net/browse/OSF-4338

[feature] Fix ShareJS gravatar passing [OSF-4338]

---

osf_tests/test_queued_mail.py
osf_tests/test_remind_draft_preregistrations.py
scripts/remind_draft_preregistrations.py
website/mails/presends.py

In my prereg reminder emails I was checking if the preregistrations had been submitted for review to check they were no longer drafts. Because you can start a preregistration challenge registration and register it without review, this was not an effective way of checking if the registrations were submitted.
I now check if `registered_node` exists for a draft registration. This is what I should have been doing all along because this is the way to check if a registration draft has been submitted.
One should go through the preregistration process and then "Register without review". If you wait 2 weeks (or about an hour on staging). You should not receive a prereg reminder email.
The same should continue to be true for registrations submitted for approval in the prereg challenge. You should …

Feature/Exclude prereg submitted without review from prereg reminder emails [OSF-8546]

---

osf/models/external.py
osf/models/user.py
requirements.txt
website/util/rubeus.py
website/util/sanitize.py

Related to travis-ci/travis-ci#8897 and psycopg/psycopg2#594
The new image that travis is using upgrades to Postgres 10.1, which psycopg2 version 2.6.1 does not like -- upgrade to latest 2.7.3 to fix this issue
- upgrade psycopg2 to 2.7.3
- update a method to run validation and raise errors for null emails earlier before attempting a query
- also fix unrelated flake8 errors on master
This change should not require QA, as it is solely backend dependency related!
no ticket, gone rogue

[hotfix] Bump psycopg2 version to 2.7.3 [no ticket]

---

package.json

Fix line height for project navbar.
This points to the version of osf-style that has this fix.
None
Hopefully none
None

Feature/upgrade osf-style version to 1.5.2

---

website/static/js/pages/file-page.js

Currently, file detail page would reload upon successful rename, resulting in some other unintended problem. This PR remove the reload but add a growl box message instead.
Remove reload and add growl box message that reads:
"Your file was successfully renamed. To view the new filename in the file tree below, refresh the page."
So........ Now it should not reload after successful renaming, but shows a growl message that reads:
"Your file was successfully renamed. To view the new filename in the file tree below, refresh the page."
None.
https://openscience.atlassian.net/browse/OSF-8710

[OSF-8710] Add growl message, remove reloading

---

api/users/serializers.py
api_tests/users/views/test_user_files_list.py

When files are uploaded, they are automatically given a move link through waterbutler.  However, when files are loaded they are missing this link.  This adds a move link to the quick file serializer.
- Add move link to the quick files serializer
Before this fix, users were only able to move files that had just been uploaded.  With these changes, users should be able to have pre-uploaded files that can now be moved.  To test:
1. Upload a file
2. Move to project or component
3. Test that it works
4. Upload another file
5. Refresh the page
6. Move file to project or component
7. Test that it works 
https://openscience.atlassian.net/browse/EOSF-878

[EOSF-878] Add 'move' link to quickfiles

---

website/static/js/fangorn.js

Some issues with copy/conflict.
1. Rework conflict queue logic to properly clear out the queue when empty and to know when the queue is complete. 
2. Force dismiss modal on click actions to stop mashing
3. Change wording of 'Replaced old version' to 'Moved or replaced old version' to better match reality.
number 1: Make sure copy/moves don't lock up the modal indefinitely. 
number 2: Make sure the button cannot be mashed. It May in theory be possible to hit multiple times, but it should be really, really hard to do now.
number 3: Moves without conflicts were showing the "replaced" text even though it was just a move. The logic is a bit weird, so I just changed the language for now. A followup ticket may be created to separate these properly.
NA …

[hotfix] Fix copy/conflict file tree [OSF-9071]

---

addons/gitlab/utils.py

Slight tweak to permissions checks for gitlab.
Permissions are returned something like `{u'group_access': {u'notification_level': 3, u'access_level': 50}, u'project_access': None}`, or vice-versa.  Since the `project_access` and `group_access` keys are present but set to `None` if there aren't any, `.get(item, default)` will still return `None` instead of the default, as the key is there. Why, python?
Part 2 of #8048
- slight permissions dict get tweak
To test!
- create a gitlab group
- create a new project inside that group
- add a file to that project
- connect that project to an OSF project
- ensure that the file tree for that project renders correctly
Also might make sense to doublecheck gitlab repos *not* in groups still connect/render (though this shouldn't touch that at all)
none …

[hotfix] Slightly change permissions checks for permissions format [OSF-9088]

---

addons/osfstorage/views.py

Leverage select_for_update when performing metadata updates of osfstorage version objects.

[hotfix] osfstorage txn metadata

---

tests/test_mailchimp.py
tests/test_views.py
website/mailchimp_utils.py

Fix the mailchimp double opt-in flag.
https://openscience.atlassian.net/browse/OSF-9101

[HOTFIX][#OSF-9101]Error when subscribing to mailchimp: "Due to restrictions on your account, double opt-in is required for this list"

---

osf_tests/test_queued_mail.py
osf_tests/test_remind_draft_preregistrations.py

Two test classes were skipped due to a hanging test. 
The tests were hanging due to archiver calls that were not mocked. These tests pass when run outside of docker, but fail inside docker (and subsequently on Travis). 
No QA
N/A
https://openscience.atlassian.net/browse/OSF-9095

[hotfix] Fix skipped queued mail tests [OSF-9095] 

---

scripts/generate_prereg_csv.py

Emails of the prereg challenge csv have not been sending. This is due to the change in the variable for support emails from SUPPORT_EMAIL to OSF_SUPPORT_EMAIL made in [OSF-8700](https://openscience.atlassian.net/browse/OSF-8700).
Change the obsolete 'SUPPORT_EMAIL' to OSF_SUPPORT_EMAIL.
The help desk should get an email every sunday with a csv of the preregistration data attached.
None
https://openscience.atlassian.net/browse/OSF-8926

Hotfix/change SUPPORT_EMAIL to OSF_SUPPORT_EMAIL due to #7828 [OSF-8926]

---

osf/migrations/0069_auto_20171127_1119.py

Fix migration so that it will run when there are existing Preprints with `preprint_doi_created == null`
Do the query for preprint DOI manually using the migration models rather than attempting to use get_identifier from IdentifierMixin.
No QA needed
None
N/A

Fix preprint doi query in migration

---

osf_tests/test_elastic_search.py
tasks/__init__.py
website/search/elastic_search.py
website/search_migration/__init__.py
website/search_migration/migrate.py

Optimize `migrate_search` and `rebuild_search`
* Use SQL to construct ES updates / deletes
Before: took some indeterminately large amount of time (10+ hours)
After: `rebuild` takes ~15 minutes
```
[website.search_migration.migrate]  INFO: 53188 nodes migrated
[website.search_migration.migrate]  INFO: 1170014 files migrated
[website.search_migration.migrate]  INFO: 74833 users migrated
inv rebuild_search  119.07s user 4.71s system 13% cpu 15:11.86 total
```
And `migrate` takes ~23
```
[website.search_migration.migrate]  INFO: 53188 nodes migrated
[website.search_migration.migrate]  INFO: 434963 nodes marked deleted
[website.search_migration.migrate]  INFO: 1170014 files migrated
[website.search_migration.migrate]  INFO: 2577084 files marked deleted
[website.search_migration.migrate]  INFO: …
```

[Feature] Optimize search migration [#OSF-9037]

---

website/search_migration/__init__.py

Exclude the correct set of QA nodes from the ES search migration
* Fix `WHERE`s
Should exclude nodes with titles `Bulk Stress 2018[...]`, `OSF API Registration Test 9001`, etc
None expected
[[OSF-9037]](https://openscience.atlassian.net/browse/OSF-9037)

Use "icontains" for QA node filtering [OSF-9037]

---

website/app.py
website/reviews/listeners.py

Ensure review submission/acception/rejection emails get sent
* Import listeners before app initialization
1) Do a thing to trigger an email
2) Make sure email is sent
None expected
[[MOD-204]](https://openscience.atlassian.net/browse/MOD-204)

Connect reviews listeners [#MOD-204]

---

api/base/pagination.py
api/preprint_providers/views.py
api_tests/preprint_providers/views/test_preprint_provider_subjects_list.py

- Increases the max page size for `/v2/preprint_providers/<provider_id>/taxonomies/` endpoint to 1000. 
- The preprints app used to make requests to the `/v2/taxonomies/` endpoint which has the `NoMaxSizePagination` class (see #6245), but a similar pagination class was never added to the preprint providers taxonomies endpoint.
- Add an `IncreasedPageSizePagination` class that sets `max_page_size` for a given view to 1000.
- Adds the `IncreasedPageSizePagination` class to the `PreprintProviderTaxonomies` list view.
- Noted on ticket.
- [OSF-9158](https://openscience.atlassian.net/browse/OSF-9158)

[hotfix] Increase max page size for preprint provider taxonomies [OSF-9158]

---

admin/preprint_providers/views.py
admin_tests/preprint_providers/test_views.py

When you export a preprint providers settings JSON as it doesn't include the _id attribute, this is less then desirable so we're putting the _id in the JSON.
Changes config to stop blocking the _id and reinstates old test statement to test for it.
In the Admin app export any preprint provider as JSON, do a quick ctrl-f to ensure "_id" is in the text of the file.
https://openscience.atlassian.net/browse/PLAT-471

[PLAT-471] Preprint provider export should include _id

---

scripts/generate_prereg_csv.py
website/settings/defaults.py

Mistakenly was sending prereg csv emails to 'support@osf.io' - should have been sending them to 'prereg@cos.io'.
Change them to send to 'prereg@cos.io'
None
None
https://openscience.atlassian.net/browse/PLAT-633

feature/make prereg csvs send to prereg email [PLAT-633]

---

api/base/settings/defaults.py
api/base/settings/local-dist.py

Every once in awhile, a too-long n+1 log prevents travis from showing what tests have failed - so let's only enable it locally when on debug, not on travis (like django debug toolbar!)
- move settings for adding N+1 to local-dist
None needed!
no ticket

Don't enable n+1 logging on travis [no ticket]

---

addons/base/views.py
tests/test_addons.py

We want Waterbutler to be able to send download information to `create_waterbutler_log` without raising an error or actually creating log data.
This allows `create_waterbutler_log` to accept `download_file` and `download_zip` actions. Currently it just ignores them (This allows waterbutler to send us the data without returning 400s. We will use this data in OSF-8786 to tally downloads).
When a preprint is downloaded, nothing should be added to its node log.
None expected
https://openscience.atlassian.net/browse/OSF-8785

Feature/Ignore download_file and download_zip log actions [OSF-8785]

---

osf/management/commands/populate_custom_taxonomies.py

Since this is essentially a command line tool, in order to use subject text whose name includes a ' (such as Children's and Young Adult Literature or Women's Studies), we need a way to translate between bash/zsh escaped quotes (`\''`) and JSON loads escaped quotes (`\'`).
As far as I can tell, this is the only way I could get the quotes all the way through the pipeline:
in command line : `\''` (two single quotes) ` ("Women\''s Studies")`
in python, as a string, pre-json loads: `\\\'`  `("Women\\\'s Studies")`
- add the `--escape-quotes` argument that let's you enter subjects with ' in their name if you escape it with a backslash and two single quotes
no qa needed
none
no direct ticket, but related to https://openscience.atlassian.net/browse/PLAT-521

[hotfix] Process command line single quotes for custom taxonomy [no ticket]

---

osf_tests/factories.py
osf_tests/test_analytics.py
osf_tests/test_comment.py
osf_tests/test_files.py
osf_tests/test_guid_auto_include.py
osf_tests/test_institution.py
osf_tests/test_node.py
osf_tests/test_oauth_application.py
osf_tests/test_preprint_summary.py
osf_tests/test_registrations.py
osf_tests/test_remind_draft_preregistrations.py
osf_tests/test_sanctions.py
osf_tests/test_search_views.py
osf_tests/test_user.py
setup.cfg

Flake doesn't check the osf_test directory, it should. Now it does.
-  Changes setup.cfg to not exclude the osf_test
-  Removes double quotes, whitespace etc 
-  Removes dupe test `test_skips_no_settings`
Travis should take care of this.
https://openscience.atlassian.net/browse/PLAT-247

[PLAT-247] Don't exclude osf_tests from flake8

---

website/project/views/contributor.py

Fix the problem that add an unregistered contributor to non top level project sending the wrong email.
Fix the logic to check contributor.is_registered as a priority
1. create a project A
2. create a project B which is a component of A
3. Add an unregistered contributor with email to project B and check the email you get
before change:
You get an email with no way to set your password.
after change:
You get an email with a link to set your password.
https://openscience.atlassian.net/browse/PLAT-67

[#PLAT-67]Add an unregister contributor to a not top-level component send wrong email

---

addons/base/views.py
website/routes.py
website/static/js/components/quickFiles.js

Fix profile links
Reintroduce `/quickfiles/path` route, which creates a guid for the file and reroutes to their /guid file detail page
Change logic in the profile page to resolve quickfiles with guids to their file-detail page directly. 
https://openscience.atlassian.net/browse/EMB-111

[EMB-111] Fix profile links and add ability to resolve quickfiles path -> guid

---

api/users/views.py
api_tests/users/views/test_user_nodes_list.py

User nodes endpoint need to be able to be sorted.
Remove hardcoding of user-node sort endpoint and add tests
Attempt sorting of the user-nodes endpoint.

[EMB-16] Allow user-nodes to be sorted

---

osf/management/commands/populate_custom_taxonomies.py

For the purpose of validating a custom taxonomy, we should keep track of what subjects were previously excluded -- without this change, excluding a subject and then trying to add a custom subject with the same name results in an error.
When validating excludes, persist the exclusion of the excluded subjects in `included_subjects`
Should not need QA!
No ticket

Persist excluded subjects when error checking for custom [no ticket]

---

api/institutions/views.py
osf/models/node.py

According to NewRelic, the `InstitutionNodeList.get` endpoint has one of the slowest average response times.  Add query optimizations to speed this up. This will cut queries from ~66 to ~39 (or ~89 to ~51 depending on cacheing)
- add include and select_related to `InstitutionNodeList` queryset
- Try removing a `#TODO` and using filter in the `parent_node` property, seems to work now?
Should not need QA!
https://openscience.atlassian.net/browse/PLAT-548

Add includes and select related to optimize get.InstitutionNodeList [PLAT-548]

---

bower.json
package.json
webpack.common.config.js
website/templates/base.mako
yarn.lock

These commits remove the bower bootstrap import in the base mako template, and add bootstrap to webpack. The purpose of this PR is to remove the need for bootstrap to load independently from the rest of the webpacked CSS, hopefully reducing page load time.
* Installed bootstrap via yarn
* Added bootstrap CSS to webpack config
* Changed reference to bootstrap JS from bower copy to yarn copy
* Removed bower bootstrap import from base mako template
N/A
None that I can think of.
[https://openscience.atlassian.net/browse/PLAT-510](https://openscience.atlassian.net/browse/PLAT-510)

Use yarn bootstrap instead of bower bootstrap [PLAT-510]

---

osf/migrations/0077_add_noderequest_model.py
osf/models/node.py

The `0077_add_noderequest_model` locks the abstractnode table for a long time: 1.5min locally before crashing.
The vast majority of the time is spent adding the `access_requests_enabled` field because it has a default value and therefore results in a a table rewrite:
```
ALTER TABLE "osf_abstractnode" ADD COLUMN "access_requests_enabled" boolean DEFAULT true NOT NULL;
```
Prevent a table rewrite by breaking it down into multiple steps:
- Add the field as nullable with no defaults
- Add the field default
For reference: https://pankrat.github.io/2015/django-migrations-without-downtimes/
https://openscience.atlassian.net/browse/PLAT-554

[PLAT-554] Prevent a table rewrite when adding access_requests_enabled field

---

addons/wiki/templates/edit.mako
website/static/css/style.css
website/static/js/components/logFeed.js
website/static/js/filepage/util.js
website/static/js/pages/file-page.js
website/static/js/pages/project-dashboard-page.js
website/static/js/pages/statistics-page.js
website/templates/profile/notifications.mako
website/templates/project/addon/citations_widget.mako
website/templates/project/modal_add_contributor.mako
website/templates/project/nodes_delete.mako
website/templates/project/nodes_privacy.mako
website/templates/project/project.mako
website/templates/project/registration_editor_extensions.mako
website/templates/project/registrations.mako
website/templates/project/settings.mako
website/templates/project/statistics.mako
website/templates/project/view_file.mako
website/templates/public/pages/meeting_landing.mako
website/templates/util/render_addon_widget.mako
website/templates/util/render_node.mako

Replace the old OSF logo spinners with the new pulsing/scaling loading icons as per updated OSF-style guidelines.
* Replace inline loading spinners with pulsing loading icons.
* Replace all other loading spinners with scaling loading icons.
* Include `span`s in `.ball-scale-blue` css rule, along with the already-included `div`s to simplify inline loading icons.
* Fix minor capitalization issue in tags form
It should be confirmed that the loaders for the dates on the analytics page do in fact appear, and that they appear in-line. Analytics isn't loading at all for me.
None that I can think of.
[https://openscience.atlassian.net/browse/PLAT-327](https://openscience.atlassian.net/browse/PLAT-327)

Update loading icons to ball-scale and ball-pulse [PLAT-327]

---

addons/base/utils.py
addons/base/views.py
addons/bitbucket/models.py
addons/box/models.py
addons/dataverse/models.py
addons/dropbox/models.py
addons/figshare/models.py
addons/github/models.py
addons/gitlab/models.py
addons/googledrive/models.py
addons/onedrive/models.py
addons/osfstorage/models.py
addons/owncloud/models.py
addons/s3/models.py
osf/models/files.py

Expose the last known metadata for missing files to users that should be able to know it.
* Conditionally extend pre-existing error message for this case
* Add base class methods to pre-parse some metadata
* Implement provider-specific hash hooks
To test:
1. Connect addon and view file
2. Delete file through addon UI
3. Try to view file on OSF at same url
4. Confirm message includes more metadata
None expected
[[#OSF-8636]](https://openscience.atlassian.net/browse/OSF-8636)
[[#OSF-8762]](https://openscience.atlassian.net/browse/OSF-8762)

[Feature] Expose metadata for missing files[PLAT-498]

---

website/static/js/pages/project-addons-page.js
website/templates/project/addons.mako

Zotero users with existing keys who wish to use zotero group libraries will need to reauthenticate to get a key with correct permissions.
If zotero configured, on the Project Addons tab, add a dismissable warning similar to our maintenance alerts.   Uses cookies to track whether user has dismissed alert.  Appearance similar to https://github.com/CenterForOpenScience/osf.io/pull/7749.
- Banner should appear beneath zotero section on Project Addons tab.
- Check that links are correct.
- Check that once the banner is dismissed it doesn't reappear unless cookies are cleared.
https://openscience.atlassian.net/browse/PLAT-496

Feature/Add One-Off Dismissable Alert for Zotero Group Libraries [PLAT-496]

---

api/citations/utils.py

Show preprint DOI in the citation if there is no user-specified DOI.
In `utils.py`, the `preprint_csl` method is modified to use `preprint_doi`.
Basically, the peer-reviewed DOI should always be included in the citation, and it would fall back to using self-generated DOI if peer-reviewed DOI is not provided by the user.
For moderated preprint services, if the preprint is not yet approved, it would not use the self-generated DOI if peer-reviewed DOI is not provided. However, the peer-reviewed DOI should show in citation even if the preprint is not yet approved.
None.
https://openscience.atlassian.net/browse/IN-94

[IN-94][OSF] Show preprint doi in citation

---

osf/models/sanctions.py
scripts/embargo_registrations.py

Embargoes were getting stuck because their parent registrations were getting deleted. This fix identifies deleted embargoes and filters them out where they're not needed.
- Add is_deleted property to embargo model
- adds to conditionals so scripts recognize deleted  embargoes
Not a lot we can do QA wise this really only effects a script which runs each night.
https://openscience.atlassian.net/browse/PLAT-637

[PLAT-637] Give embargos an is_deleted property

---

scripts/remove_after_use/add_eartharxiv_subjects.py

Add a couple subjects for eartharxiv!
Add new subjects underneath Physical Sciences and Mathematics, consisting of "Planetary Science" and a bunch of children! See ticket for list of children!
This is pretty simple so I'm not sure it needs QA but just in case:
- The new subjects show up on the side search bar under the hierarchy Physical Sciences and Mathematics > Planetary Science > all the children
- You can choose the subjects when creating the a new eartharxiv preprint
nope
https://openscience.atlassian.net/browse/PLAT-718

Script to add eartharxiv subjects under Planetary Sciences [PLAT-718]

---

admin/users/views.py
admin_tests/users/test_views.py

- Fixes the exported user workshop CSV to return user guids, not pks.
- `user.pk` --> `user._id`
- `len()` --> `.count()` (should speed this up a bit)
- No QA needed. Courtney can test on prod when this is up.
- None.
- [PLAT-700](https://openscience.atlassian.net/browse/PLAT-700)

[hotfix] Fix user workshop CSV [PLAT-700]

---

addons/base/views.py

Not every file has versions (if it is not an OSFStorage file). Persistent file downloads would break if there weren't file versions. I also didn't need to set the latest version as the default download because downloading the latest version also happens by default.
Removed adding latest file version to query params. Latest version is already downloaded by default. 
All storage providers and versioning for them should work.
None expected.
https://openscience.atlassian.net/browse/OSF-8982

Feature/Persistent download links: allow storage providers without versions to work [OSF-8982]

---

website/static/css/style.css
website/static/js/pages/statistics-page.js
website/templates/project/statistics.mako

Fix a QA issue regarding 2 inline loading icons being too large for their respective text.
Add a CSS class for smaller (8px instead of 15px) pulse balls, and apply that class to 2 relevant loading icons.
Check the inline loaders for the dates at the top of the analytics dashboard and make sure they load and are smaller than the other pulse balls on the screen.
None
https://openscience.atlassian.net/browse/PLAT-327

Shrink inline loading icons on analytics dashboard [PLAT-327]

---

api/base/parsers.py
api/base/serializers.py
api/nodes/serializers.py
api/nodes/views.py
api_tests/base/test_serializers.py
api_tests/nodes/views/test_node_detail.py
api_tests/nodes/views/test_node_list.py
api_tests/nodes/views/test_view_only_query_parameter.py

In EmberOSF, we have some terrible hacks in to handle updating relationships that go to many relationships. In particular, the affiliated_institutions relationship on nodes. The reason is that the preferred method of updating that information, by including it in the relationship field of the POST or PATCH request, only worked with 1 to 1 relationships, such as Preprint->Node or Node->License. This generalizes everything to allow that to work with toMany relationships, and in particular adds support for Node->affiliated_institutions.
1. Update parsers to handle lists
2. Update affiliated_institutions field to be writeable, not be required, and have "many"
3. Update base serializer to handle where everything broke when "many" was activated (mostly related to not realizing that fields also …

[EMB-171] Handle toMany relationships for create/update in v2 api

---

api/base/serializers.py
api_tests/nodes/views/test_node_list.py

Fix serialization of affiliated_institution relationships so that they won't think that the node's `id` is the institution's `id`
1. Add a test for the condition
2. Dereference the child_relation field some more in the to_representation method of the base serializer so it's serializing the right info and not the parent field's info
We could glance at some other relationship field link serializations to make sure nothing else broke.
This should only affect fields with a child_relationship, so it should be limited to the affiliated_institutions relationship
https://openscience.atlassian.net/browse/EMB-171

[EMB-171] Fix bad serialization of node id in affiliated_institution urls

---

website/registries/views.py

Register Reports Landing Page is breaking this unbreaks it.
- Adds back in placeholder view for registries.
Falls under normal testing for Register Reports landing page.
None

Fix Register Reports Landing Page

---

addons/wiki/static/dragNDrop.js
website/static/js/fangorn.js

There was a bug caused by dropping multiple 409ing files causing the wiki links not to draw properly, this fixes that.
While testing that I notice there was another bug preventing the user from deleting multiple files in the Wiki images folder, this fixes that too.
- Reorders API requests so we check for duplicate names before upload
- Handle special delete warnings differently.
Upload multiple 409ing and non-409ing files and delete multiples from the files page.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-486

[PLAT-486] Fix Drag and drop bugs

---

addons/wiki/static/dragNDrop.js

ES2015 syntax was cause Jenkins to fail this fixes that.
- Small syntax change
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-486

[PLAT-486] Get rid of bad JS syntax for DND

---

osf_tests/test_generate_sitemap.py
scripts/generate_sitemap.py

Improve sitemap script.
- Make sure unconfirmed users are excluded (not sure how this is happening anyways, because previously only active users are included), but added a filter just in case
- Change preprint download link
No testing required.
https://openscience.atlassian.net/browse/PLAT-675

Feature/Sitemap Improvements [PLAT-675]

---

api/preprint_providers/views.py
api_tests/preprint_providers/views/test_preprint_provider_moderator_list.py

Frontend needs consistent ordering
* `order_by` `fullname`
* Add a test
Low need. To test, ensure that the list of mods for any given PreprintProvider is ordered alphabetically
None expected
[[IN-210]](https://openscience.atlassian.net/browse/IN=210)

[IN-210] Order moderators by fullname

---

package.json
website/templates/nav.mako
yarn.lock

osf-style is now adding `flexbox` to the navbar styles from [this PR](https://github.com/CenterForOpenScience/osf-style/pull/111).  The current osf.io navbar should change in order to reflect these new styles.
- Move navbar collapsed button to the right of the other elements within its container
- Add `secondary-nav-dropdown` class to user details dropdown
This should be tested with https://github.com/CenterForOpenScience/osf-style/pull/111 which adds the styles to the navbar
https://openscience.atlassian.net/browse/IN-95
Relies on https://github.com/CenterForOpenScience/osf-style/pull/111 to actually see the desired changes
Will need to update to the latest osf-style after other PR is merged

[IN-95][OSF] Change navbar to take in new osf-style navbar styles

---

addons/osfstorage/tests/test_views.py
framework/auth/core.py

With the addition of the new shiny persistent file download route (#8107), users couldn't provide an oauth token as they used to in order to authenticate for download requests. Let's fix that!
- add check in `_get_current_user` method to look for token. This is eventually called from the `@collect_auth` decorator
- test for getting with token in header
I do believe that @TimErrington was the one who reported this bug because of a script he runs regularly, so perhaps this would be best tested by him!
Any route using the `get_user` method from `core.py` can now pass a token in the header, which is nice!
https://openscience.atlassian.net/browse/PLAT-741

Check for header auth token on persistent file download

---

addons/wiki/static/dragNDrop.js
addons/wiki/templates/edit.mako
website/static/js/fangorn.js

Follow up on QA catches for DnD.
- Change loading indicator 
- Fix show permissions messages shows
- Make sure  loading indicators go away right when links are being drawn
- Fix delete wiki language when deleting a single file
- Upload a bunch of files and make sure the loading indicators disappear right before the links are drawn.
- Delete a single file in the wiki images folder and make sure the sentences have spaces after the period.
- upload something to a public wiki without permission.
- Make sure we have a single pulsing ball.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-486

[PLAT-486] More dnd fixes

---

website/static/js/registrationUtils.js
website/templates/registered_reports_landing.mako

If a user creates a registration from the /rr page this opens a rr draft immediately. 
- JS changes to send you to a new draft right after a click the registration.
Create a registration from the /rr page after some loading you should directly into a draft.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-216

[PLAT-216] fix onboarder redirect

---

addons/osfstorage/tests/test_views.py
framework/auth/core.py

Follow up to #8239
Previous hotfix only worked for personal access tokens, make it work for authenticated CAS requests as well!
- update method to authenticate thru cas 
- update test for cas
This might be best tested by our partners with applications that use access tokens for the download URLS -- see https://github.com/CenterForOpenScience/waterbutler/issues/328 and https://github.com/dschreij/QOpenScienceFramework/issues/13
https://openscience.atlassian.net/browse/PLAT-741

Take 2: persistent file download URL accept token: CAS edition! [#PLAT-741]

---

addons/wiki/static/dragNDrop.js

If you drag and drop multiple file types and one is invalid the loading indicator goes away prematurely, this fix ensures it sticks around until all files have been dealt with.
- Stop editor from being prematurely re-enabled.
Upload a bunch of valid images, then include a bad one, check that the loading indicator doesn't leave prematurely.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-486

[PLAT-486] Loading indicator dnd fix

---

api/waffle/views.py
api_tests/waffle/views/test_waffle_list.py

Currently, visiting page 2 of the waffle endpoints results in an error: https://staging-api.osf.io/v2/_waffle/?page=2
A proposed solution to this on the tickets is that the waffle endpoint doens't really need pagination, and so a similarly un-restricted pagination (like the Institution list) should be used instead.
- Use `MaxSizePagination` as the `pagination_class` for the waffle list API route (same `pagination_class` as the `InstitutionList`
Should not need QA, but a quick check of https://staging-api.osf.io/v2/_waffle/ and or  https://api.osf.io/v2/_waffle/ should show ` "per_page": 1000,` at the bottom in the `meta` section, along with `null` for last, previous, and next pages.
https://openscience.atlassian.net/browse/PLAT-744

[hotfix] Use max page_size for waffle API endpoint [PLAT-744]

---

addons/base/views.py
tests/test_addons.py

Fix bug where loading a file with an all upper case extension caused the file not to be downloaded properly.
- downcases the extension comparison.
There are test files and good instructions attached on the ticket.
Not really necessary as a hotfix.
https://openscience.atlassian.net/browse/PLAT-768

[PLAT-768][hotfix] Fix case so downloading file by guid works better

---

docker-compose.yml

Update docker-compose.yml to fix docx rendering and use newer WaterButler images for local development.
Two minor updates for the Services projects in docker-compose.yml:
* LibreOffice in the unoconv container has been upgraded to 6.0.  The `command` stanza in docker-compose.yml needs to be updated for docx rendering to work in local development
* The `wb` service was updated to use the newer WaterButler images, but `wb_requirements`, `wb_worker`, and `wb_flower` are still pointing to the old one.  Update those to match.
No QA needed, this only affects local development.
None.
No ticket.

Docker updates for Services

---

api/nodes/serializers.py
api_tests/base/test_serializers.py
api_tests/nodes/views/test_node_detail.py
website/views.py

Add needed work for ember_osf_web to show a subset of ember pages, such as the registrations page
- Added `current_user_is_contributor` attr to node's serializer: checks if user making the request is a contributor
- Added check for ember page flags on waffle, when reaching a node guid, to see which app should render the subpage.
https://openscience.atlassian.net/browse/EMB-162
https://openscience.atlassian.net/browse/EMB-189

[EMB-162][EMB-189] Add support for ember node subpages

---

api/nodes/views.py
api/wikis/permissions.py
api/wikis/serializers.py
api/wikis/views.py
api_tests/nodes/views/test_node_wiki_list.py
api_tests/wikis/views/test_wiki_detail.py
api_tests/wikis/views/test_wiki_versions_list.py

- Adds handling for disabled wikis and publicly editable wikis.
- Added check for disabled wikis in WikiMixin and NodeWikiList.
- Added `is_publicly_editable` permission check.
- Added tests.
- Attempting to access **any** wiki endpoint should fail if the wiki is disabled (404).
- Editing a publicly editable wiki (POST to /v2/wikis/<id>/versions/) as a non-contributor should succeed (201). 
- Attempting to create, delete, or rename a wiki page as a non-contributor, even if the wiki is publicly editable, should fail (403). 
- I'll update https://github.com/CenterForOpenScience/developer.osf.io/pull/8 when I merge.
- [PLAT-543](https://openscience.atlassian.net/browse/PLAT-543)
- [PLAT-771](https://openscience.atlassian.net/browse/PLAT-771)

[feature] Handle disabled and public wikis [PLAT-543][PLAT-771]

---

api/guids/serializers.py
api_tests/guids/views/test_guid_detail.py

The GUID serializer for previewing a referent with `?resolve=false` was showing a `nodes` related href and type instead of `registrations` 
- Update `get_type` to return `registrations` for a registration Record
- ... while still using `node_id` for the view_kwarg
- Test to check for proper type and related URL
Pretty simple!
- Visit the GUID endpoint of a registration with the `?resolve=false` query param
- eg: `http://staging-api.osf.io/v2/guids/<registration_id>/?resolve=false`
- Ensure the relationships referent data type is  `registrations`
- Ensure the relationships links href leads to the registration 
https://openscience.atlassian.net/browse/PLAT-714

Fix unresolved registration GUIDs that think they point to a node [PLAT-714]

---

addons/dropbox/models.py
addons/dropbox/requirements.txt

Old dropbox client is going to be depreciated, this upgrades to 8.7.1 to avoid problems arising from that.
- bumps version number
- slightly reshuffle imports to accomdate changes.
Connect/disconnect to the Dropbox addon. There should be no user facing changes.
https://openscience.atlassian.net/browse/PLAT-695

[PLAT-695] Upgrade Dropbox client version to use v2 auth endpoints

---

website/conferences/views.py

The serialization of meetings pages (`/view/<meeting>/` route) is incredibly slow and expensive. 
Replaces the meetings serialization with sql.
https://openscience.atlassian.net/browse/PLAT-657

Feature/Optimize Meetings Page Serialization with SQL [PLAT-657]

---

website/conferences/views.py

Tweaks for meetings page serialization in SQL
- Add default sort order on created - recently created first
- Do a better job of figuring out what meeting category is.   Now looks in array of tag names on meeting to see if certain tag is present. 
- For example, meeting with tags ["SPSP2016", "poster", "science"] would be categorized as a poster.
- In previous version, was searching through concatenated list of strings "SPSP2016 poster science" for the word "poster".  So a project tagged as "imposter" would show up as a poster. Silly me.
https://openscience.atlassian.net/browse/PLAT-657

Fix/Category and Default Sort - Meetings Page Serialization [PLAT-657]

---

website/templates/project/project.mako

Makes view-only link feature more visible.
Add a "Create view-only link" link to the More Actions meatball menu on the project overview page.
- Links to the view-only links section of the project settings page
- Only visible if user is an admin contributor and the node is not a registration.
Verify that "Create view-only link" visible in the More Actions menu, under the same scenarios that the "Create view only link" section is visible on the project settings page.
- Create a project
- As admin contributor verify "Create view-only link" visible in More Actions menu
- Add a read/write contributor. Login as read-write contributor. Verify "Create view-only link" *not* visible
- Create a registration of the project.  Login as admin contributor.  Verify "Create view-only link" *not* visible
- …

Feature/Add a "Create view-only link" link on Project Page [PLAT-374]

---

api/nodes/views.py
api_tests/nodes/views/test_node_forks_list.py

`/v2/nodes/<guid>/forks` doesn't hide deleted forks
Make sure, like the v1 view, the NodeForksList view excludes deleted forks.
1. Create a node
2. Fork the node
3. Delete the fork
4. Go to /v2/nodes/<guid>/forks
the deleted fork should not be listed.
https://openscience.atlassian.net/browse/EMB-221

[EMB-221] Hide deleted forks on a node's forks list view

---

addons/wiki/tests/test_wiki.py
addons/wiki/views.py

Navigating to a *public* project's wiki with edit params (`localhost:5000/fs5ql/wiki/home/?edit&view&menu`) as a logged-out user returns a 403.  Instead, the public wiki should be displayed, and the edit parameter removed.
- 2-line change: If `edit param present, user does not have permission to edit, but has permission to view, redirect to the wiki but remove the edit parameter.
- Have this logic occur after check for whether wiki is publicly editable because we still want the user to be prompted to login.
1. create a project
2. make the project public
3. add content to the wiki and click `save`
4. once the page is refreshed, click the 'edit' button on the wiki page
5. copy the url with url parameters
5. open a new incognito browser
6. paste in the url
7. confirm that url works, and edit …

Feature/ Handle wiki `edit` URL param [PLAT-99]

---

website/templates/project/project.mako

When looking on staging3, noticed that the "Request Access" option was appearing on registrations. 
Make sure that "Request Access" does not appear on registrations frontend
Ensure that Request Access isn't in the dropdown [...] button on registrations! Goes along with request access QA in general!
The strangest thing is this isn't happening locally, but in particular saw it on this registration:
https://staging3.osf.io/kjm4r/
None

[no ticket] Make sure request access button does not show on registrations

---

addons/box/models.py
addons/box/requirements.txt
addons/box/serializer.py
addons/box/tests/test_views.py
addons/box/tests/utils.py
api_tests/nodes/views/test_node_addons.py
requirements.txt
requirements/dev.txt
website/routes.py
website/util/rubeus.py

We have dependencies preventing us from upgrading to Python 3.
Certain dependencies were updated/replaced to ensure they are python-3 compatible
- **fake-factory** (renamed to faker; latest version supports py3: https://github.com/joke2k/faker)
- **python-geoip-geolite2** ~~(no new updates but has a py3 fork)~~  Using [maxminddb-geolite2](https://pypi.python.org/pypi/maxminddb-geolite2) instead which has py3 compatibility
-  **hurry.filesize** ~~(no new updates, but there are py3 alternatives such as https://github.com/tbielawa/bitmath).~~ Removed this dependency. It appears to be unused.
- **box.py** (no new updates, but official sdk supports py3: https://github.com/box/box-python-sdk)
- I would test Box addon thoroughly; making sure there are no changes.  Whatever typical regression …

Feature/Update or Replace Dependencies for Python3 [PLAT-726]

---

website/static/js/citationGrid.js

Currently the Zotero clipboard button is broken this fixes it.
- Changes the selector a bit so it accepts zotero ids which contain a slash.
Connect to Zoterro and click the copy button to the right of the citation label, the label should be highlighted and you should be able to paste the text of the label.
Simple bug fix shouldn't need any docs.
https://openscience.atlassian.net/browse/PLAT-738

[PLAT-738] Fix Zotero clipboard button 

---

api_tests/requests/views/test_request_list_create.py
osf/utils/machines.py
website/mails/mails.py
website/project/decorators.py
website/templates/emails/access_request_submitted.html.mako
website/templates/emails/contributor_added_access_request.html.mako
website/templates/request_access.mako

A round of pre-official-QA adjustments to the request access feature!
- Remove periods from request access email subject lines
- Add inline links to HTML emails for request access notifications
- Ensure that emails are only sent to project admins, not admins on parent projects
- Use `auth_logout` with `?next=<node_url>` instead of reauth, which was re-logging back in right away!
QA notes are included in original frontend PR #8192
see above!
https://openscience.atlassian.net/browse/PLAT-462

Access Request Adjustments [PLAT-462]

---

website/static/vendor/ace-plugins/spellcheck_ace.js

There are JS errors `"ace.edit can't find div #editor"` when visiting a Registration's wiki.
It looks like where `('../../vendor/ace-plugins/spellcheck_ace.js');` is being required on the `wiki-edit-page`, *ace.edit('editor')* is being called to spell check Ace editor contents.    Using jquery in both the enable_spellcheck() and spell_check functions, check if `#editor` exists on the page before attempting to call ace.edit('editor').
1. Create a registration
2. Visit its wiki
3. Confirm there are no longer JS errors in the console regarding the ace editor.  Also visit the registration's project and confirm spellcheck is still enabled.  Type jibberish in the wiki editor and confirm it is underlined with red dots.
https://openscience.atlassian.net/browse/PLAT-825

Hotfix/JS Errors Registration Wikis [PLAT-825]

---

api_tests/requests/views/test_request_list_create.py
framework/auth/oauth_scopes.py
osf/models/node.py
website/static/js/pages/project-settings-page.js
website/templates/emails/access_request_rejected.html.mako
website/templates/emails/access_request_submitted.html.mako
website/templates/emails/contributor_added_access_request.html.mako
website/templates/project/contributors.mako
website/templates/project/private_links_table.mako

Fixing up some things caught by the extremely thorough and wonderful QA team!
- Change "Wiki enabled/disabled" and "Access requests enabled/disabled" to sentence case
- Change [x Remove] button icon on View Only Link in mobile mode to x instead of -
- If requests are disabled on the project, former requests for access are no longer shown
- they come back if requests are re-enabled on the node
- If a user requests access and then is added as a contributor, they should no longer show up on the requests for access list
- Access capitalized for consistency with other headers
- Instances of "the Open Science Framework" changed to "OSF" in 3 emails
- A period inside the " for the email to the admin about a user requesting access
- `NODE_REQUESTS_READ`, `NODE_REQUESTS_READ` added to …

More Request Access Improvements! [PLAT-462]

---

api/base/serializers.py
api/base/settings/defaults.py
api/nodes/serializers.py
api_tests/nodes/views/test_node_detail.py

Ember needs to know when wikis are disabled via the api.
As per @brianjgeiger suggestion, do not show the wiki relationship if the wiki is disabled.
links.relationships.wiki should be present/absent on node list and node details based on whether the wiki is disabled.
No tix

Don't show wiki relationship when wiki is disabled

---

website/routes.py
website/settings/defaults.py
website/static/css/style.css
website/templates/base.mako
website/templates/footer.mako

Make the footer better.
This should not be merged/deployed until the Embosf version of this ticket (https://github.com/CenterForOpenScience/ember-osf-web/pull/190) is deployed with ember-osf-web 0.3.0.
1. Move relevant parts of copyright footer into the footer
2. Remove most of the footer
3. Change the colors so that they are more accessible
4. Adjust the style in other ways
5. Merge the strings into the footer
Before:
After:
This is all pretty simple; all static links and the like. The copyright date range should still be accurate. We aren't going to do the analytics tracking on the legacy OSF; when pages are embosfed, they'll get more analytics tracking on the footer links.
No docs necessary
I hope not.
https://openscience.atlassian.net/browse/EMB-174

[EMB-174] [Hotfix] Match footer to Embosf styling

---

addons/base/models.py

The warning when you have to re-authorize an addon when removing a contributor with an addon authorized is incorrect, this fix corrects it.
- Simple HTML changes
1. User A, create a project
2. Add User B with admin or write permissions
3. User B, configure an addon
4. User A, remove User B as a contrib
You should see a message with a link click the link and see that it goes to the addons page.
https://openscience.atlassian.net/browse/PLAT-187

[PLAT-187] Fix addon re-authorization link

---

website/static/js/meetings.js
website/static/js/submissions.js

Currently both meetings and the projects within them open in new tabs when clicked on OSF for Meetings. Would be great for it to all stay in the same browser window.  Internal links aren't usually expected to open in new tabs (confirmed this with Product)
- Meeting links open in same browser window.
- Submission links open in same browser window.
- Submission author links open in same browser window (went ahead and added, so links would behave same as above item)
- Verify changes listed above.
https://openscience.atlassian.net/browse/PLAT-792

Feature/Meetings Open Same Tab [PLAT-792]

---

website/views.py

`ember-osf-web` does not yet support custom domains (nor even institutions), so we shouldn't send them to it.
Separate the custom domain handling from the legacy home page and only decorate the legacy home page func.
Make sure this works for custom domains, e.g. https://staging-osf-nd.cos.io
n/a
n/a
n/a

[Hotfix] never send custom domains to Ember

---

website/preprints/tasks.py

A bad merge conflict fix (my fault) caused calls to share to dupe if the first call raised a 500 error. 
The removed part was moved to a function but got resurrected. 
Excise dupe code.
Not really testable. If we really want to test it, share needs to raise a 500, then check to make sure the call for that preprint only showed up once. IMHO not worth worrying about.
No
None known
https://openscience.atlassian.net/browse/IN-296

Cleanup extra call from bad merge

---

scripts/add_missing_identifiers_to_preprints.py
website/settings/defaults.py

Some preprints fail to ever get DOIs. There is a script that should already fix them, but it never runs because celery doesn't import it.
* Update celery imports
* Update script QS
N/A
N/A
None expected
[IN-295](https://openscience.atlassian.net/browse/IN-295)

[Hotifx][IN-295] Actually add missing identifiers

---

framework/auth/views.py
osf/exceptions.py
osf/models/user.py
osf/models/validators.py
osf_tests/test_user.py
tests/test_conferences.py
website/language.py
website/profile/views.py

Before, the `validate_email` method would return a `ValidationError`, which made it hard to distinguish from other errors that inhereted from `ValidationError` such as `ValidationValueError`, which would raise the incorrect message with the "already registered" wording in the `register_user` api v1 route.
- Change the error raised to a specific `BlacklistedEmailError` so that it can be caught uniquely and a full error message shown.
- Also throw/catch this exception when attempting to enter an alternate email on the profile settings page from the blacklisted domains list.
- Update tests to look for this specific exception
To test this:
1. Try to sign up for the OSF with an email from [any of the blacklisted domains](https://github.com/CenterForOpenScience/osf.io/blob/1bda6e975c466d8cd4eabe …

Show better error message when a user tries to use a blacklisted domain [PLAT-785]

---

addons/github/api.py
addons/github/models.py
addons/github/routes.py
addons/github/serializer.py
addons/github/templates/github_node_settings.mako
addons/github/tests/test_models.py
addons/github/tests/test_serializer.py
addons/github/tests/test_views.py
addons/github/views.py
api/addons/serializers.py
api_tests/nodes/views/test_node_addons.py
tests/test_addons.py

Embosf wants to access the providers folder info via the API, lets oblige them.
- Move folder listing function to model
- Add new test for model
- Minor change to addon config template, to keep UI working.
- Let serializer know Github is a top level only provider.
* Check configuring GH repos (code that populates the dropdown of repos was changed here)
* You're going to have to create Github account with a few repos and connect to it. Check the appropriate API endpoint, it should look like this:
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-434

[PLAT-434] Refactor github so repo listing is available to v2

---

addons/wiki/models.py

Before 0.138, wiki spam cwas checked in Node.on_update, which
checks `if user` before calling `check_spam`.
WikiVersion.check_spam does NOT check `if user`, so the
`check_spam` call raises an error.
This is preventing some users' submissions to OSF4M.
Don't call `WikiVersion.check_spam` unless a user can be loaded from the request.
Quick regression test to make sure OSF4M submission still works.
This may not be the best long-term solution, but it's low-risk, and
this will at least allow prod users to submit to OSF4M. In the future, we may want to allow `check_spam` to work without a user.
Sentry: https://sentry2.cos.io/cos/osf-back-end/issues/2892/
(no JIRA ticket)

[hotfix] Don't call check_spam if user cannot be loaded from request

---

website/views.py

We fixed waffle flags for non-project pages, but that didn't transfer to projects. This applies that fix to project pages.
Update the website view to get the current user or a mock user and inject that onto the request object.
If the project_forks flag works with everybody turned to unknown, then this should be good.
No more than we'll have for other flags, which is to say that I'm pretty sure that other Waffle features won't work on these pages (like waffling for different languages or anything like that). Any new waffle features we might want to try, which currently we have no plans for, will need to be tested before we can expect them to work.
https://openscience.atlassian.net/browse/EMB-281

[EMB-281] Fix node-based waffle flags

---

api/providers/serializers.py
api_tests/providers/preprints/views/test_preprint_provider_moderator_list.py
osf/models/node.py
osf/models/provider.py
osf/models/user.py
osf_tests/test_user.py
tests/test_citations.py
tests/test_views.py
website/project/views/contributor.py
website/templates/emails/confirm_moderation.html.mako

Allow unregistered moderators to set password from invite email
- Generalize `add_unclaimed_record` method to handle both unregistered `contributor` and `moderator`
- Generalize `claim_user_form` to allow/handle redirects to provider's reviews or node pages.
[[IN-297]](https://openscience.atlassian.net/browse/IN-297)

[IN-297][OSF] Allow unregistered moderators to set password from invite email

---

addons/osfstorage/models.py

Send saved storage region to WB as part of stored auth request.
Pulling waterbutler_settings and waterbutler_credentials off of associated Region object, rather than settings. 
https://openscience.atlassian.net/browse/PLAT-685

Feature/Send Storage Regions [PLAT-685]

---

scripts/populate_institutions.py

Ferris State University have decided to abandon CAS protocol and use SAML2 for institution login. For now, disable institution login for Ferris until they are ready.
Set `delegation_protocol` to the empty string `''` so that CAS no longer pulls Ferris from the database.
NotQATeam
No
CAS PR: https://github.com/CenterForOpenScience/cas-overlay/pull/106
https://openscience.atlassian.net/browse/SVCS-812

[SVCS-812] Disable Institution Login for Ferris State University

---

tests/test_notifications.py
website/notifications/emails.py
website/templates/emails/reviews_submission_status.html.mako

Fix reviews status update emails
- Make template a keyword arguments.
- Use preprint/submission url.
[[IN-48]](https://openscience.atlassian.net/browse/IN-48)

[IN-148][OSF] Fix reviews status update emails

---

osf/models/preprint_service.py
website/project/views/contributor.py
website/settings/defaults.py
website/templates/emails/file_operation_failed.html.mako
website/templates/emails/file_operation_success.html.mako
website/templates/emails/notify_base.mako

- Follow-up fixes to #8187 
- Fix branded preprint provider logos not appearing in HTML emails. 
- Retrieve assets from the master branch of osf-assets instead of a specific commit. 
- https://openscience.atlassian.net/browse/PLAT-338

[feature fix] Fix branded preprint logos in emails [PLAT-338]

---

addons/zotero/tests/utils.py

An earlier Zotero PR https://github.com/CenterForOpenScience/osf.io/pull/8219 added a test and then a later PR https://github.com/CenterForOpenScience/osf.io/pull/8230 started accessing a different key from data returned from pyzotero.
Mock test data from PR https://github.com/CenterForOpenScience/osf.io/pull/8219 needs to be expanded to include this new key.
Fix test failure on release/next-platform.  
https://travis-ci.org/CenterForOpenScience/osf.io/jobs/380280400

Fix/Mock Zotero Data [PLAT-730] 

---

website/project/views/contributor.py

Fix issue where in "adding unreg moderator" workflow the user
just created a password, is redirected to preprints provider home but appears not logged in.
h/t @cslzchen 
Navigate to osf login then redirect to preprints home
[[IN-297]](https://openscience.atlassian.net/browse/IN-297)

[IN-297][OSF] Redirect to preprints provider home after authentication through osf

---

api/caching/tasks.py
api_tests/actions/views/test_action_list.py
api_tests/preprint_providers/views/test_preprint_provider_preprints_list.py
api_tests/preprints/views/test_preprint_detail.py
api_tests/preprints/views/test_preprint_list.py
api_tests/users/views/test_user_actions.py
framework/postcommit_tasks/handlers.py
osf/models/preprint_service.py
osf/utils/machines.py
osf_tests/factories.py
osf_tests/test_reviewable.py
tests/test_preprints.py
website/preprints/tasks.py

* Upgrading to celery v4.2.0rc2 in 7081d5d7b2e09cc9084c392a9be2aaeb09111c2e resulted in some tasks failing due to a `RuntimeError` (see https://sentry2.cos.io/cos/osf-back-end/issues/3147/#). 
* `RuntimeError` raised by celery: https://github.com/celery/celery/blob/d02d260a192f8923dfa331ae2b503af57534654a/celery/result.py#L41
* Addition in v4.2.0rc2 that results in the above `RuntimeError` being raised for synchronous subtasks: https://github.com/celery/celery/blob/d02d260a192f8923dfa331ae2b503af57534654a/celery/result.py#L940
* Remove synchronous subtask calls in `postcommit_celery_task_wrapper` in favor of asynchronous calls in `postcommit_after_request`.
* Directly call `get_and_set_preprint_identifiers` in `on_preprint_updated` (instead of as a synchronous task). 
- …

[hotfix] Make synchronous tasks asynchronous [PLAT-857]

---

addons/base/views.py
addons/osfstorage/views.py
tests/test_addons.py

These were using the WB log callback to mark versions as seen
and tally preprint views, respectively. This approach won't
work outside of local development due to MFR's cached renders.
Fitz is working on adding an MFR callback that we will
use instead. Once that's ready, we can revert this commit.
Remove the code that marks file versions as seen and updates file view analytics in the waterbutler log callback.
https://openscience.atlassian.net/browse/PLAT-639
https://openscience.atlassian.net/browse/PLAT-218

Disable PLAT-639 (Track Unseen Versions) and PLAT-218 (tally preprint views)

---

scripts/analytics/file_summary.py
scripts/analytics/run_keen_summaries.py

We need to include the number of files/number of public files on the OSF in the daily summaries we send to Keen.
Added file_summary script, similar to node_summary, that calculates
- total # of files in OSFStorage (includes quickfiles)
- total # of public files in OSFStorage, (includes quickfiles)
- total # of private files in OSFStorage
- total # of files added today in OSFStorage (includes quickfiles)
- total # of public added today in OSFStorage, (includes quickfiles)
- Total # of private files added today
No QA testing needed
None
https://openscience.atlassian.net/browse/PLAT-725

Feature/Report on number of files, public files in OSFS [PLAT-725]

---

api/base/views.py

Eliminate the need to also do a request to `/v2/_waffle/` every time someone launches an embosfed page
Add a meta attribute to the root endpoint to include active waffle flag names. See `meta.active_flags` below:
```
{
"meta": {
"version": "2.8",
"current_user": {
"data": {
"quickfiles": {
"links": {
"download": {
"href": "http://localhost:7777/v1/resources/cw6uj4b279/providers/osfstorage/?zip=",
"meta": {}
},
"upload": {
"href": "http://localhost:7777/v1/resources/cw6uj4b279/providers/osfstorage/",
"meta": {}
},
"related": {
"href": "http://localhost:8000/v2/users/g3mq5/quickfiles/",
"meta": {}
}
}
},
"nodes": {
"links": {
"related": {
"href": "http://localhost:8000/v2/users/g3mq5/nodes/",
"meta": {}
}
}
},
"institutions": {
"links": {
"self": {
"href": …
```

[EMB-299] Active waffle flags in /v2/ root

---

osf/migrations/0099_add_default_storage_region.py

Directly importing user and osfstorage models was causing some trouble when running migrations locally. Also, make sure to specify the dependency to another app's migrations.
- update add_default_storage_region migration to import correctly
none necessary!
none needed
no ticket

Make sure migration to add default regions imports models correctly [no ticket]

---

website/static/css/pages/wiki-page.css

Very wide Wiki tables get cut off in the view pane, this fix allows them to scroll.
- Simple CSS fix
This fix only pertains the Wiki page when the view pane is the only one visible. Markdown for adding a table is view able here.
https://openscience.atlassian.net/browse/PLAT-735

[PLAT-735] Make wiki tables scrollable

---

tests/test_views.py
website/project/views/contributor.py

Currently adding an unregistered contributor with an email address that is already being used shows an error message that the user is already in the database, forcing the user to go back and search again.
Quick fix, remove check that user is already registered. Just go ahead and add the user as a r/w contributor. 
- No advance prep needed.
- Go to your Add contributors page on a project
- Search for a contributor that already exists.
- Ignore search results, instead click on " add user as an unregistered contributor."
- Enter in name, and known email in the Add Unregistered Contributor form, email should belong to a registered user
- Confirm that user is selected to be added to project as r/w contributor instead of an error being thrown.
Not needed. …

Feature/Adding Registered Contributor through Unregistered Contributor Form [PLAT-54]

---

api/base/views.py
api/metaschemas/serializers.py
api/metaschemas/urls.py
api/metaschemas/views.py
api/nodes/serializers.py
api/registrations/serializers.py
api_tests/metaschemas/views/test_registration_metaschemas_detail.py
api_tests/metaschemas/views/test_registration_metaschemas_list.py
osf/models/metaschema.py

To allow for `metaschemas/files`, metaschemas endpoint needs to be generalized for different types of metaschemas. Move /v2/metaschemas/ to /v2/metaschemas/registrations/.
❗️ Relies on feature in release/next-interfaces, so pointed to this branch for now.
- ADD /v2/metaschemas/registrations/
- ADD /v2/metaschemas/registrations/<metaschema_id>
- DEPRECATE /v2/metaschemas/<metaschema_id>/ (Behaves exactly the same as before, except the response includes a warning in /meta/warnings/)
- DEPRECATE /v2/metaschemas/ ( Behaves exactly the same as before, except the response includes a warning in /meta/warnings)
- Update relationship links that point to metaschemas
Don't know if there are any automated tests that need to be updated... `/metaschemas` has moved to `/metaschemas/registrations`, and …

Feature/Generalize Metaschemas API [PLAT-816]

---

osf_tests/test_remind_draft_preregistrations.py
scripts/remind_draft_preregistrations.py

Currently if you create a preregistration draft, but don't finish it you get a reminder email prompting you to complete it. The problem is if you delete the project in the mean time, you still get the reminder email. This fix removes the email from the queue if you delete the project.
- Dequeues emails from deleted projects
- Adds tests
The ideal way to test this would be to create a prereg draft, delete it's project and wait 2 week to see if you get a reminder email, but obviously that isn't practical. Devs who want to test this should be able to in the shell or can just run the unit tests.
Bug fix not necessary.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-822

[Hotfix][PLAT-822] Stop sending prereg reminder emails on deleted projects

---

api/citations/utils.py
api_tests/preprints/views/test_preprint_citations.py
framework/auth/utils.py

We use cite-proc.py to format our citations for APIv2 which are used in preprints.  We use a different library for formatting citations on projects.  Cite-proc is missing some things, so we do some post-processing, and sometimes our overrides need more tweaking.
- MLA was looking for the word "Open" in the citation to split it, but this doesn't exist for other preprint providers.  Don't split the citation on the word open to get rid of the duplicated citation.
- When someone has two middle names, both initials need to show up in all three citations
- Extra periods stripped from the end of preprint titles.
- Extra period after the right quotation mark dropped.
- With two authors for MLA/Chicago, no space between authors and no period at the end.
- APA citations more than 8 contributors, …

Fix/More Preprints API Citations [PLAT-827]

---

api/files/views.py
api_tests/files/views/test_file_detail.py
api_tests/users/views/test_user_files_list.py

Stop users from being able to access a disabled users quickfiles from the file detail page.
- adds check for FileDetail class and two new tests
1. create a user
2. upload files to their quickfiles node.
3. save the file detail urls for those files
4. disable/deactivate the user (you can do this via the admin or shell).
5. visit the urls again, you should see this:
Bug fix, no docs necessary. 
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-783

[PLAT-783] Prevent accessing a deactivated users quickfiles ...again

---

addons/base/views.py
tests/test_addons.py

WB will start sending auth callbacks with  'render' and 'export' as actions if the download requests originated from MFR.
Doing so will allow us to track unseen file versions and preprint views (which were disabled in #8387) in the auth callback.
Handle `render` and `export` action. Both actions require read access.
None
None
https://openscience.atlassian.net/browse/SVCS-674

[SVCS-674] Account for 'render' and 'export' actions in auth endpoint

---

api/collections/permissions.py
api_tests/collections/test_views.py

Allow admins to remove their submissions from collections
- Extend `DELETE` update handling with a check for `admin` on referent
- Update test
Recommend API testing as we wait for the collection frontend.
Endpoint to test : `/{}collections/{}/collected_metadata/{}/'.format(API_BASE, collection._id, cgm._id)`
for instaance.
1) default contributor permissions ('read', 'write'), 
1.1) expect `403` should be returned as the contributor does not have `admin`
2) Try with same steps with same user as admin and make sure the submissions get removed from the collection.
[[IN-276]](https://openscience.atlassian.net/browse/IN-276)

[IN-276][OSF] Allow admins to remove their submissions from collections

---

tests/base.py
website/search/elastic_search.py

We often get probabilistic test failures due to Elasticsearch connection errors.
This change is both (1) an attempt to fix the errors and (2) a way to diagnose the errors more easily.
- Make ES connection error messages more verbose
- Use UUID1 instead of UUID4 when generating random ES index names for each test (UUID4 is prone to collisions when using PRNGs)

[hotfix] Attempt to fix probabilistic ES errors on Travis

---

website/routes.py
website/settings/local-dist.py

Allow `ember-osf-web` assets to be served from `/assets/` and add simple way to add extra routes.
(assets served from `/ember_osf_web/assets/` will continue to work)
* Refactor flask routing to automatically add routes for Ember asset prefixes when `ember_osf_web` external ember app is defined.
* Add optional `routes` config key to list extra routes for `ember_osf_web`.
Should only affect development environments.
Not at this time.
n/a
n/a

Refactor ember-osf-web asset routing

---

Dockerfile

Docker builds are currently failing because the python2.7-slim
no longer has gnupg2 installed
Install gnupg2 in the docker image.

[no ticket] Fix docker image

---

api_tests/preprints/views/test_preprint_citations.py

Modify date comparisons in citations tests. Tests introduced in https://github.com/CenterForOpenScience/osf.io/pull/8329

Feature/Modify formatting of dates in APA, MLA, and Chicago citation tests [PLAT-827]

---

api/nodes/views.py
api_tests/nodes/views/test_node_list.py

* Allow projects with linked nodes to be bulk deleted. 
* Properly exclude linked nodes from bulk delete check.
* Steps to reproduce in ticket.
* None expected.
* https://openscience.atlassian.net/browse/PLAT-889
```
(osf)~/d/osf.io ❯❯❯ py.test api_tests/nodes/views/test_node_list.py -k test_bulk_delete_project_with_linked_node
=================================================================== test session starts ====================================================================
platform darwin -- Python 2.7.13, pytest-3.0.3, py-1.5.3, pluggy-0.4.0
Django settings: api.base.settings (from environment variable)
rootdir: /Users/caseyrollins/develop/osf.io, inifile: pytest.ini
plugins: xdist-1.15.0, django-3.2.1, celery-4.2.0rc2
collected 78 items
api_tests/nodes/views/test_node_list.py F …
```

[hotfix] Fix node bulk delete with linked node [PLAT-889]

---

api/users/serializers.py
api_tests/users/serializers/test_serializers.py

Embosf needs more user fields to complete the contributors page.
- Return jobs and schools when serializing a user in V2
- Adds small user serializer test
Add school/employment info to users on settings page, verify these show in the API.
Attributes specifically stated to not need documentation.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-817

Feature/Return User Profile Info in the API [PLAT-817]

---

website/templates/emails/reviews_submission_confirmation.html.mako
website/templates/emails/reviews_submission_status.html.mako

* In python < 3.x ''.format with a unicode object breaks
* Sentry obscures stack frames that are not in the osf folder.
Select 'Full', to the right of 'App Only', to see the full trace.

[IN-318] Use unicode .format strings in email templates

---

website/static/js/koHelpers.js

Fix issue where enter keypress on input field result in new line.
This change should not affect enter keypress on `textarea` inputs using
the `editableHtml` ko helper.
`preventDefault` on enter keypress.
Make sure the pressing enter while confirming the delete does not do anything.
These changes modifies a helper also used in comments, but it should modify the behavior on enter keypress. Check and see if comments still work just fine.
[IN-243](https://openscience.atlassian.net/browse/IN-243)

[IN-243][OSF] Fix handling enter keypress on editable html input

---

website/static/js/alertsManager.js
website/templates/project/addons.mako

Fix weird UI interactions btn github and zotero dismissible alerts
- Fix unclosed divs
- Remove `.dismissible-alerts` from zotero alert to allow
dismissing gh alerts when zotero is enabled.
http://recordit.co/tyaValuPqD
[IN-242](https://openscience.atlassian.net/browse/IN-242)

[IN-242][OSF] Fix weird interactions btn github and zotero dismissible alerts

---

api/preprints/serializers.py

When we embed a `primary_file` in a preprint we 502, this makes us not do that.
- remove lookup_url_kwarg we can't actually use lookup
`v2/preprints/?embed=primary_file` and `v2/preprints/<preprint_guid>/?embed=primary_file` should work and display an embedded primary_file.
🐞 fix, no new docs.
https://openscience.atlassian.net/browse/PLAT-155

[PLAT-155][Hotfix] Embedding primary_file on preprints 502s

---

website/settings/defaults.py
website/templates/footer.mako

* Remove google plus link/icon from the footer. 
* https://openscience.atlassian.net/browse/PLAT-909

[hotfix] Remove google plus from the footer [PLAT-909]

---

osf/utils/machines.py
website/templates/emails/reviews_submission_status.html.mako

Some providers report that users aren't reading their comments after submission -- including them in emails may lead to increased user involvement.
* Add comments to reviews emails when appropriate
1. Submit preprint to a moderated service that doesn't have `reviews_comments_private` set to `True`
2. Moderate it and include a comment.
3. Ensure submitting user gets the comment in their notification email.
None expected
[[IN-260]](https://openscience.atlassian.net/browse/IN-260)

[IN-260] Add Comments to Reviews Emails

---

admin/static/css/banners.css
website/static/css/scheduled-banner.css

Center banner image in admin (banner preview) and legacy frontends
- Fix banner styles
- Center the banner image
Make sure the banner is centered.
Please try different sizes heights to make sure larger banners display right.
[IN-334](https://openscience.atlassian.net/browse/IN-334)
**Meetings**
**Admin**

[IN-334][OSF] Center banner image

---

docker-compose.yml

Allow development docker builds of ember-osf-web to work with osf.io@master
Set environment variable `ASSETS_PREFIX=/ember_osf_web/` in docker-compose.yml section for ember_osf_web.
No QA.
n/a
n/a
n/a

Set ASSETS_PREFIX to /ember_osf_web/ in docker-compose

---

tests/identifiers/test_crossref.py
website/identifiers/clients/crossref.py
website/templates/emails/crossref_doi_error.html.mako

Crossref has some rules with names that I didn't anticipate until actual testing began! Namely (hahah get it):
- If there is just one name, has to be a family name
- There can't be numbers or ? in a given name
Also make the error emails easier to read while we're at it.
- Use close to the same logic to figure out how to use the name as the API citation util
- Get rid of numbers and ? in a given name
- Tests for these things
- Make the helpdesk error email better formatted and not just a blob
- Should now not completely freak out and refuse to mint a DOI if you have a number in your first name
- Should now be able to make DOIs with just a firstname set
Not for this no but I did add a few docstrings!!

Crossref name parsing plus a bit of email [PLAT-802]

---

admin/preprints/serializers.py
admin/preprints/urls.py
admin/preprints/views.py
admin/templates/base.html
admin/templates/preprints/confirm_ham.html
admin/templates/preprints/confirm_spam.html
admin/templates/preprints/flagged_spam_list.html
admin/templates/preprints/known_spam_list.html
admin/templates/preprints/preprint.html
admin/templates/preprints/preprint_list.html
admin_tests/preprints/test_views.py
osf/models/preprint_service.py

Add preprint spam handling in Admin
- Add `known-spam`, `known-ham`, `confirm-ham`, `confirm-spam` views
- Add spam fields to preprint detail view
- Add tests
In preparation for testing: it would help to have some flagged preprints.
In Admin, preprints, go to flagged preprints. Make sure you see ll flagged preprints.
Select a few flagged preprints and confirm them as spam.
Go to known spam and make sure all of them are listed.
Go spam preprint node pages and make sure the associated node are now private.
Go to detail page of confirmed spam preprint:
With the 'confirm not spam' button, make some spammy preprints 'HAM'.
Go to the known HAM and make sure the new changed preprints are listed.
Make sure that spam fields show up in the preprint detail page. …

[IN-281][OSF] Add preprint spam handling in Admin

---

osf/models/node.py
osf_tests/test_node.py
website/project/tasks.py

Updating contributors or licenses on a project should trigger changes to the datacite metadata
- move a call to on_node_updated that got nested incorrectly on merging 
- add call to update on_node_updated task when a license is changed
- test to make sure that call is created correctly when a license is changed
Now, changing a license or contributors should trigger a version change. Changing two contributors should create just one new version!
https://openscience.atlassian.net/browse/PLAT-806

Make sure updating contributors and licenses trigger changes in datacite metadata

---

osf/models/node.py
osf_tests/test_node.py
tests/test_views.py

See: https://www.flowdock.com/app/cos/archiver/threads/6Az9BWQBQPlk_HELqquwhMwEJ9b
User is unable to add an unregistered contributor whose email address is associated with a registered user.
The get_user call was not correctly handling when a user tries to
add an unregistered user using an email that's a secondary email address
of a registered user. With this change, we get the registered user associated
with the email address rather than using `get_user`.
Steps:
* Register email A
* Add email B as a confirmed, secondary email
* Create a preprint, inviting email B as an unregistered contributor
Expected:
The registered user (with username A) is added as a contributor to the
preprint/node.
Actual:
There is an unregistered contributor with email B as the username, even
though email B is a …

[PLAT-915] Fix corner case for adding a contributor with a registered, secondary email

---

tests/identifiers/test_crossref.py
website/identifiers/clients/crossref.py

* Adds user ORCIDs (when verified) to the metadata we send to CrossRef for preprint DOIs.
* See https://support.crossref.org/hc/en-us/articles/214567746-Authors-and-editors
* Explicitly delete license information from CrossRef metadata when a preprint license is changed to "None"
* See https://support.crossref.org/hc/en-us/articles/115003564483
* See above.
* When a preprint license is updated to "None", license information should be cleared from the DOI metadata.
* If a preprint contributor has a **verified** ORCID (i.e., they've logged in to the OSF via ORCID, not just added it to their profile), their ORCID should be part of the DOI metadata. 
* https://openscience.atlassian.net/browse/PLAT-802

[feature] Send ORCIDs and update licenses in CrossRef metadata [PLAT-802]

---

website/static/css/add-project-plugin.css

On mobile devices clicking/touching the dropdown menus for forks or request access to projects doesn't work this makes it work
- Simple CSS fix for bootstrap bug.
Using a mobile device or Chrome's responsive mode, click the anything forks dropdown menu to see if it works.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-772

[PLAT-772][Hotfix] Fix responsive button for forks and request access

---

tests/identifiers/test_crossref.py
website/identifiers/clients/crossref.py

Don't combine the suffix with the surname, let it be seperate as crossref allows this
- undo combining surname and suffix
- test
- suffix should now appear in its own field and not repeated in surname
<person_name contributor_role="author" sequence="first">
<given_name>Erin Leonor</given_name>
<surname>Braswell</surname>
<suffix>I</suffix>
</person_name>

[PLAT-802] Make sure suffix is indeed separate from surname

---

api/citations/utils.py

As things stand, tests for chicago citation would fail on travis the 20th of every month.
Update reformat method to split on first occurrence of `20`. The `20` is part of the year, so this test should work till year 3000 😆 😆  
Please check the chicago citation on preprints and make sure there is no extra space between month and day.
No ticket.

[hotfix][OSF] Fix chicago citation reformat

---

api/crossref/views.py
scripts/remove_after_use/register_preprint_dois_with_crossref.py
scripts/remove_after_use/send_preprint_doi_csv.py
website/identifiers/clients/crossref.py
website/templates/emails/crossref_doi_error.html.mako

Makes the legacy DOI script faster and fixes a few small bugs with building Crossref metadata.
- Modify Crossref error email to include batch ID instead of assuming that a single preprint is updated/created
- Remove control characters from title and description when building metadata
- Separate legacy DOI migration script from CSV generation script. This make the DOI migration script more fault-tolerant.

[PLAT-802] Crossref fixes

---

api/citations/utils.py
api_tests/preprints/views/test_preprint_citations.py
website/static/bluebook.csl

Use "OSF Preprints" in citations
- Update `bluebook` citation styles
- Update other citations to use "OSF Preprints"
Please make sure that preprint citations are using the "OSF Preprints" instead of "Open Science Framework". Try bluebook citations as well.
[[IN-255]](https://openscience.atlassian.net/browse/IN-255)

[IN-255][OSF] Use "OSF Preprints" in citations

---

addons/wiki/static/wikiPage.js
website/static/js/pages/project-dashboard-page.js

Currently a wiki this no content will prompt the user to add content even if they don't have the permissions to add content. This PR changes the language to be appropriate.
- Simple fixes to new and old wiki renders.
The phrase, "No wiki content" should appear for wikis with no content for users that can't edit the wikis, otherwise behavior should be unchanged.
🐞  fix, no docs
https://openscience.atlassian.net/browse/PLAT-875

[PLAT-875] Incorrect wiki prompt for non-write users

---

api/crossref/permissions.py
api/crossref/views.py
api/preprints/serializers.py
api_tests/crossref/views/test_crossref_email_response.py
api_tests/nodes/views/test_node_detail.py
api_tests/preprints/views/test_preprint_detail.py
api_tests/preprints/views/test_preprint_list.py
api_tests/preprints/views/test_preprint_list_mixin.py
api_tests/providers/preprints/views/test_preprint_provider_preprints_list.py
framework/postcommit_tasks/handlers.py
osf/models/node.py
osf/models/preprint_service.py
osf_tests/factories.py
osf_tests/test_reviewable.py
tests/test_preprints.py
website/preprints/tasks.py

Updating a preprint's metadata was causing lots of POSTs to crossref, as the call to update metadata is triggered from preprint's save method. Combine calls to the task on_preprint_updated to ensure it's just called once if that task is already in the postcommit queue. 
Also, make sure to set the DOI for real only when we receive confirmation from crossref.  Set the doi URL from the client's build_doi method if it doesn't have a real identifier set yet.
Fix the tests to look for this change in the way `on_preprint_updated` is called.
- add update_or_enqueue_on_preprint_updated method that uses new get_task_from_postcommit_queue to check for the task in the postcommit queue
- also call this in the preprint save method
- Remove the `get_and_set_preprint_identifiers` method as that's …

Preprint DOI improvements to metadata and DOI setting [PLAT-802] [PLAT-921]

---

api/crossref/views.py
tests/identifiers/test_crossref.py
website/identifiers/clients/crossref.py

Add an addendum to the crossref view that will retry to send the data again without the relation included.
Crossref does validation on DOIs in the `related_item` section to see if they resolve, whereas we do not when asking for a published DOI. If crossref rejects the preprint because of it, resend the metadata without the relation included (the failure will still be collected in an error CSV later on)
- add kwarg to build metadata without relation
- resend metadata wihout relation on fauilure
- test to make sure relation conditionally isn't included
Not directly, but this should mean that preprints that have a "fake" preprint article DOI will eventually get issued DOIs, but the relation won't show up in crossref's metadata.

Resend metadata without relation if crossref rejects for bad relation DOI [PLAT-802]

---

osf/utils/machines.py
osf_tests/factories.py
website/templates/emails/reviews_update_comment.html.mako

Include comment in "edit-comment" email
* Include comment in "edit-comment" email
* Fix flake upstream
Ensure comment included in "edit-comment" email
None expected
[[IN-260]](https://openscience.atlassian.net/browse/IN-260)

[IN-260] Include comment in "edit-comment" email

---

api/preprints/serializers.py

Don't show the pre-built DOI if it has't yet been given for pre-moderation preprints
- update serializer to check for pre-moderation status if there's no DOI yet.
- PRe moderation preprints  that haven't been approved shouldn't have that message any longer
https://openscience.atlassian.net/browse/PLAT-921

If a preprint's provider has pre-moderation, don't return preprint URL [PLAT-821]

---

scripts/remove_after_use/register_preprint_dois_with_crossref.py
tests/identifiers/test_crossref.py
website/identifiers/clients/crossref.py

Truncate and process names a bit more so that crossref will accept contributor names for preprints found on production.
- Don't build metadata for an empty object list when sending existing preprints to crossref
- Truncate surnames and given_names to 60 chars
- Truncate suffixes to 10 chars
- If a name cannot be parsed as a given_name and surname, return "anonymous"
This is different than what we had before -- now, names should be actively truncated at 60 chars for Given + middle, 60 for surname, and 10 for suffix.

Process names for CrossRef contributors [PLAT-802]

---

api/requests/serializers.py
api_tests/requests/views/test_request_list_create.py

Filter field on NodeRequestSerializer was out of date, change it to match fields on the `NodeRequest` model and allow filtering on `machine_state`
- Update name in `filterable_fields`
- Add test for `?filter[machine_state]=pending`
- This change is API only, and so most likely won't need any QA testing. As it's a hotfix and specifically for a feature that's being worked on, I imagine that'll be the testing!
Doesn't seem as though the requests part of the API is documented on developer.osf.io yet, so no doc changes needed
https://openscience.atlassian.net/browse/PLAT-854

[hotfix] Update filterable_fields on NodeRequestSerializer for machine_state [PLAT-854]

---

docker-compose.yml
website/routes.py

https://github.com/CenterForOpenScience/osf.io/pull/8371/files#diff-758f58f82207e3674b3105d2b3d4ce7aR1679 created a route conflict so serving ember-osf-web assets from `/assets` is no longer an option. Instead, we have set up the ember app so that its assets can always be served from `/ember_osf_web`, regardless of whether served through flask or directly from the ember-cli express server. This PR removes the special assets routes for ember-osf-web and the setting of ASSETS_PREFIX=/ember_osf_web/, which is no longer necessary, as this is now the default.
* Remove ember-osf-web asset routing
* Remove setting of ASSETS_PREFIX for ember_osf_web
No QA needed. This only affects local development.
n/a
n/a
n/a

Remove ember-osf-web assets routes

---

api/base/serializers.py
api/nodes/serializers.py
api/nodes/views.py
api/registrations/serializers.py
api/registrations/views.py
api_tests/base/test_serializers.py
api_tests/nodes/serializers/test_serializers.py
api_tests/registrations/views/test_registration_detail.py

Support the embosf'd analytics page. Previous changes worked for nodes but not registrations.
- Add default ordering to "linked by" relationship views
- Fix 502 error at `/v2/registrations/?related_counts=1` (missing `get_view_only_links_count` method)
- Add count to registrations' `forks` relationship
- Add `templated_by_count` to registration detail meta (to match node detail)
- Replace `ShowIfAdminScope` with `ShowIfAdminScopeOrAnonymous`, so our apps get the same information whether or not the user is logged in.
`/v2/registrations/?related_counts=1` should no longer error, and should include counts in each registration's `forks` relationship. 
A registration's detail view (`/v2/registrations/<guid>/?related_counts=1`) should have the `forks` count, plus `templated_by_count` in the …

[EMB-277] Registration related_counts, add missing ordering

---

api/crossref/views.py

On Crossref's latest test server, minting a DOI that has a possible match with a title and first author of a preprint already on their server now returns 2 success messages, which looks something like:
```
<record_diagnostic status="Success">
<doi>10.31235/osf.io/bemhx</doi>
<msg>Possible preprint/VoR pair, Vor DOI: 10.1017/S0140525X17001893</msg>
</record_diagnostic>
<record_diagnostic status="Success">
<doi>10.31235/osf.io/bemhx</doi>
<msg>Successfully added</msg>
</record_diagnostic>
```
- Don't update the DOI for those successes, but still count it when deciding how many DOIs were processed successfully
Should not have any impact on the way things are currently working!
None needed
None anticipated 

Account for new duplicate success message about possible pairs in crossref [PLAT-802]

---

api/registrations/views.py
api_tests/registrations/views/test_registrations_childrens_list.py
osf/models/node.py

If you're not logged in (or in incognito mode) and you visit a registration children endpoint, like https://api.osf.io/v2/registrations/5k7hu/children/ the result will 502, that ain't right! This PR fixes that.
- Changes the get queryset method for the RegistrationList view to get the auth properly instead of just taking it off the request object.
Open an incognito window and go to a registrations endpoint, if you get any 200 response you are good to go.
🐞  fix no docs.
* https://openscience.atlassian.net/browse/PLAT-934
* Sentry: https://sentry2.cos.io/cos/osf-back-end/issues/213/

[PLAT-934][Hotfix] Registrations children list 502s when not logged in

---

scripts/remove_after_use/send_preprint_user_email.py
website/mails/mails.py
website/templates/emails/preprint_doi_change.html.mako

Email all users who are active and a contributor of a published preprint that a change is happening. 
Note: updated line-height to 1.5:
- One-time use script to email all active users on published preprints once
- The email to send
- If your user has more than one published preprint, they should only get one email
- A user who only has an unpublished preprint (never completed or not approved by a moderator) should not receive an email
- A user who *only* has a preprint that was since "made private" by making the node private should **still** get an email
- A user who *only* has a preprint that has a node that was deleted should **not** get an email
None required
https://openscience.atlassian.net/browse/PLAT-938

[hotfix] Notify preprint contributors of DOI platform change [PLAT-938]

---

api/nodes/views.py
api_tests/nodes/views/test_node_view_only_links_detail.py
website/project/views/comment.py

if you try to delete a view only link through our v2 API it crashes, this fixes that.
- Comments out unused code that was causing problems
Issue a delete request to v2/<node_id>/view_only_links/<link_id>/, if you receive a 204 with deleted link  you're good.
🐞 fix no docs.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-923

[PLAT-923][Hotfix] Attempting to delete a VOL 502s

---

api/crossref/views.py

It appears that if two metadata updates come too quickly to crossref with duplicate metadata. These errors are expected and mostly caused by how calls to update preprint metadata are triggered, as lots of unrelated node updates will cause a connected preprint to update in crossref.
After the node/preprint divorce, this will get a lot better as updates to things like tags, files, and the wiki won't automatically trigger updates on the connected preprint.
Here's a ticket (also now referenced in the code) that can be used to address this once that happens: https://openscience.atlassian.net/browse/PLAT-944
- Ignore expected duplicate metadata errors
Probably best QAed by Becca -- errors from crossref should virtually disappear!
none needed
Kind of …

If we get a crossref error that's caused by double metadata posts, don't email the helpdesk

---

framework/auth/cas.py
framework/auth/forms.py
framework/auth/views.py
tests/test_cas_authentication.py
website/templates/external_login_email.mako

If ORCID doesn't provide us with a name, we still want one to use and display when people log in via ORCID. This provides a form field so we can collect it.
- adds name field is only required if you don't provide a name.
It shouldn't be difficult to test this for QA using a live ORCID service on staging, but for a dev using fakecas it's very difficult to test.
I choose to simulate a ORCID response by fudging the Session object so it would appear to come from ORCID.
in the framework/sessions/__init__.py file I modified the `get_session` method to the following:
```python
def get_session():
Session = apps.get_model('osf.Session')
user_session = sessions.get(request._get_current_object())
if not user_session:
user_session = Session()
user_session.data['auth_user_external_first_login'] = True …
```

[PLAT-850] Ask Users for Name if ORCID Doesn't Provide It

---

addons/github/models.py
addons/github/templates/github_node_settings.mako

In order for the currently selected github repo to be shown to admins as the selected option in the dropdown, make a change to how `github_repo_full_name` is serialized (removing the spaces between the use and the repo names) to match how the repo name is returned in `repo_name['path']`
- Remove spaces between username and repo name for `github_repo_full_name` in `to_json` method of github node settings
- Compare `repo_name['path']` to `github_repo_full_name` to determine which option should be selected
- Clean up logic when rendering `<option>` tags
- Authorize the github addon
- Connect a repo to the project and save
- Refresh the page
- Make sure the previously selected repo name is still selected in the dropdown
None necessary …

[hotfix] Display currently selected github repo on addons page [PLAT-911]

---

tests/test_conferences.py
website/conferences/utils.py
website/conferences/views.py

Previously, the OSF Meetings hook was looking for a project of the same name and same creator as the submitter - let's update that to always create a new project when making a conference submission from email.
- always create a new node when getting a conference email
- add test to ensure that a new project is created when a project with the same name exists
To test:
- Choose an existing project
- Submit a paper or talk to an existing meeting endpoint with that same project title
- Ensure the submission appears in that conference
- You should now have two projects with that title, one with the conference tag and one without
- Double checked our [help section for creating meeting submissions](http://help.osf.io/m/meetings/l/546443-submit-to-a-meeting), there doesn't seem to be anything …

[hotfix] Allow Meeting submission when user has project with same title [PLAT-927]

---

website/static/js/pages/project-addons-page.js
website/templates/project/addons.mako

The Zotero library message a has served it duty and now it's time for this old soldier to fade away.
- Simple HTML and JS changes
Enable Zotero, there shouldn't be a message, you should try this in an incognito window because old cookies might prevent this message from being displays.
No docs necessary.
https://openscience.atlassian.net/browse/PLAT-912

[PLAT-912][hotfix] Remove Zotero library message

---

osf_tests/test_elastic_search.py
scripts/remove_after_use/reindex_quickfiles.py
website/search/elastic_search.py

Links to a user's quickfiles node in search were incorrect, using the quickfiles guid instead of `/<user_id>/quickfiles`
- update `node_url` if the search result file is in a quickfiles node
- script to reindex all quickfiles
After the script is run, all search results for files in quickfiles nodes should link directly to that user's quickfiles page at `/<user_id>/quickfiles/`
- Search for a quickfile on the search page
- Click the link for "User Name's QuickFiles" under the file result
None required
https://openscience.atlassian.net/browse/PLAT-932

[hotfix] Reindex files in quickfiles nodes so their project links are correct [PLAT-932]

---

api/base/parsers.py
api/search/permissions.py
api/search/views.py
api_tests/base/test_views.py
api_tests/search/views/test_views.py

Improve consistency with other search paradigms, simplify things for the front-end.
* Add `SearchParser` to parse an ES query out of `POST` bodies
* Tweak permissions to treat `POST`s as `SAFE_METHODS` for search views
* Make `POST` behave like a `GET` for search views
* Add test
Nothing front-end yet. If desired, could use PostMan to test filtering behavior, but that's duplicative of TCI
This only works for `v2/search/collections`. POSTing to a non-collection search endpoint (e.g. `v2/search/nodes`) will now raise a `501 Not Implemented` rather than a `405 Method Not Allowed`.
[[IN-354]](https://openscience.atlassian.net/browse/IN-354)

[IN-354] POST v2/search to search

---

api/base/settings/local-dist.py
api/base/urls.py
requirements/dev.txt

Paired with: @pattisdr 
Integrate [django-silk](https://github.com/jazzband/django-silk) for profiling requests and code blocks.
* Add django-silk settings to local-dist.py
* Add route for accessing the Silk GUI `http://localhost:8000/silk/`
None
https://www.notion.so/cos/Using-django-silk-for-Profiling-ab212fe4017b484783fb878e344c1b1f
https://openscience.atlassian.net/browse/PLAT-880

[PLAT-880] Integrate django-silk for profiling

---

api/taxonomies/utils.py
api_tests/providers/mixins.py
api_tests/providers/preprints/views/test_preprint_provider_subjects_list.py
api_tests/taxonomies/views/test_taxonomy_list.py

Show subjects starting with "Other" at the end of all lists. This sort could be done on the front-end, but it's less costly to do so on the backend.
* Annotate and sort `optimize_subject_queryset`
* Add tests
Ensure "Other" subjects are at the end of lists in the front-end
None expected, at present.
`startswith` (uses a bitmap heap scan) was used over `istartswith` (sequence scan) for optimization purposes. Currently, all subjects starting with `r'[oO]ther'` are capitalized, but this may become a problem if any start with a lowercase `'other'` (unlikely).
[[IN-208]](https://openscience.atlassian.net/browse/IN-208)

[IN-208] Order "Other" subjects last

---

osf_tests/test_guid.py
website/project/decorators.py
website/views.py

Allow superuser to download unpublished preprint
Modify permissions check to include superuser perms check.
Essentially these changes allow superuser to download unpublished
preprints. But it also ensures submitter, moderator, and admin can download unpublished preprints
on branded and non-branded preprint providers.
Please check and make sure users can download their own unpublished preprints from custom domains. https://openscience.atlassian.net/browse/IN-214
[[IN-214]](https://openscience.atlassian.net/browse/IN-214)

[IN-214][OSF] Allow superuser to download unpublished preprint

---

api/base/serializers.py
api/base/utils.py
api/preprints/serializers.py

Currently, for withdrawn preprints, API V2 would hide some of its relationship fields, creating problems for the frontend app to properly update such relationships. This PR fix the problems by serializing a `null` relationship instead of simply hiding them.
- A new `NoneIfWithdrawal` class (subclassing `ConditionalField`) is implemented to determine whether a certain field should be serialized.
- Change preprint serializers to make use of the newly added class for the fields that previously used `HideIfWithdrawal`.
- Modify the `JSONAPISerializer` class so that we will serialize a `null` relationship for RelationshipField. (Currently, `JSONAPISerializer` would serialize a null RelatioshipField as a null attribute, which, needless to say, is not good.)
- Modify `decompose_field()` to add …

[IN-339][OSF] Properly nullify relationships of withdrawn preprint instead of hiding them.

---

website/project/views/node.py
website/templates/project/project.mako

Add logos to project overview page for collected projects.
Add new entry to the dict returned by `serialize_collections`.
There is currently no UI to add stuff to collections. So there are two ways to go about this ticket. The first is to defer until collection fronted UI is there. The second is to use osf shell on staging to add project to collections.
None.
https://openscience.atlassian.net/browse/IN-313

[IN-313][OSF] Add logos to project overview page for collected projects

---

api_tests/registrations/views/test_registration_list.py

When we search factory made nodes by title we often accidentally through random chance make a title that contains terms we don't want to find. This fixes that issue.
- Stops title from being random.
- No QA for travis issue
Not user facing.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-946

[PLAT-946][hotfix] Fix Probabistic Travis fail

---

website/static/css/style.css
website/static/js/pages/base-page.js
website/templates/base.mako

Add a banner to alert non-logged in users that the OSF uses cookies. This is dismissible and shouldn't show up for logged-in users.
Note: Appears over the slide-in banner that asks non-logged in users to join the OSF.
- add HTML and CSS for banner
- javascript that adds a cookie when accepted and hides the banner
This banner:
- Is for legacy OSF frontend
- Should only appear for non-logged-in users who haven't previously clicked Accept
- Clicking Accept sets a cookie that will hide the banner as long as that cookie is set
- The cookie banner should appear over the pre-existing "Join the OSF" banner that slides in
- both alerts are separately dismissible.
None necessary
https://openscience.atlassian.net/browse/PLAT-902

[hotfix] Add cookie banner to legacy OSF frontend [PLAT-902]

---

website/search/elastic_search.py

Allow searching by direct matching controlled server-side language
* Update mapping
No UI yet
None expected.
Requires `invoke migrate_search --no-delete` to be ran before [mappings will be updated](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/mapping.html#_updating_existing_mappings). Tested locally, worked with a production-sized dataset in ~16 minutes. 
Shouldn't require downtime, as it's only making `SELECT`s, but would certainly run faster with it.
Additionally, if it's not ran, nothing will be any more broken than it currently is. Search will just continue not behaving as required for `collectionSubmission` docs
None

[No Ticket] Update ES mapping for collectionSubmission docs

---

osf/models/preprint_service.py
tests/test_preprints.py

Update crossref status from `public` to `unavailable` upon preprint withdrawal
h/t to @erinspace for all the work on crossref and helping out.
- Modify `verified_publishable` to return false when preprint is withdrawn.
- Add tests
- Create a preprint and make sure it gets crossref doi, checking at `test.crossref.org` the status should be 'public'
- Create a withdrawal request  and approve it, make sure that  (may take a while) the status gets updated to `unavailable` at `test.crossref.org`
[[IN-282]](https://openscience.atlassian.net/browse/IN-282)

 [IN-282][OSF] Update crossref status upon preprint withdrawal

---

website/static/js/myProjects.js

We need a way to link to the preprints/registrations sections of the my projects page to add a "My Registrations" and "My Preprints" links to the respective apps.
Standard anchors aren't a great option here (not just scrolling to a page section), so I added two somewhat hacky functions:
1.  Splits the href and sets the filter on init 
2. Sets the page history to include the pseudo anchor
New Things:
1. Going to `myprojects/#preprints` or `myprojects/#registrations` goes to the respective section of the myprojects page. 
2. Going to `myprojects/` will not add an anchor to the url and will load projects.
3. The anchors are case insensitive (`#pRePriNtS` will reset it to `#preprints`)
4. Clicking registrations or preprints will add the appropriate anchor to the url
5. Clicking projects, …

[IN-352][OSF] Add pseudo anchors for filters on My Projects Page

---

osf_tests/test_node.py
website/project/views/node.py
website/static/css/style.css
website/templates/project/project.mako

Add collected subjects to project overview
- Update tests to make sure subjects show
- Update template to show collected subjects
- Make sure to have lots of subjects (say 15), test the responsiveness of the subjects list
- Make sure the list only shows if you are the collector, right permissions.
N/A
**Lots of subjects:** See http://recordit.co/IFLgNxIJH7
**Few subjects:**
[[IN-231]](https://openscience.atlassian.net/browse/IN-231)

[IN-231][OSF] Add collected subjects to project overview

---

api/base/settings/defaults.py

The default for Django is 'America/Chicago'. This should be updated to 'UTC,' as we store all dates and datetimes as UTC anyhow.  This wasn't set in the past to fix a failing test, which no longer seems to be a part of the codebase.
- set `TIME_ZONE = UTC`
No user facing changes, nothing should be different
None necessary
This may have been causing some strange bugs as this setting will affect any datetime queries. All datetime queries should now be using `UTC`, which should hopefully make things more consistent in general.
https://openscience.atlassian.net/browse/PLAT-954

Set TIME_ZONE = UTC in settings [PLAT-954]

---

api/base/authentication/drf.py
api_tests/base/test_auth.py

Since we're using a custom `OSFSessionAuthentication` class, we need to add in some csrf checks that are similar to [django's SessionAuthentication class](https://github.com/encode/django-rest-framework/blob/master/rest_framework/authentication.py#L111), while still doing our same session cookie processing.
- add `enforce_csrf` method to session authentication
- tests to make sure requests made with session auth also have the proper CSRF tokens set to succeed
No QA necessary!
Session auth doesn't seem to be mentioned in our docs, so no updates necessary there. 
Any API requests currently being made with session auth that don't include CSRF validation either in the POST body or in the headers as `X-CSRFToken` will be rejected. I don't think this applies to any of our services, and I don't …

Enforce CSRF on OSFSessionAuthentication [PLAT-986]

---

addons/gitlab/tests/test_views.py
addons/gitlab/tests/utils.py
addons/gitlab/utils.py

This fixes the issue where once you pick a gitlab repo, OSF storage for that project no longer loads. It just spins indefinitely. 
- Changes to make the branch selector not break everything 
- Fix tests to accommodate new behavior 
Doing basic activities in Gitlab should work well.
🐞 fix
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-913

[PLAT-913][Hotfix] Update API endpoints for GitLab

---

website/settings/local-travis.py
website/views.py

Route the base `osf.io/<guid>` detail view for registrations to Registries
* Add waffle-flagged special case to `resolve_guid`
No UI changes yet
None expected
[[IN-359]](https://openscience.atlassian.net/browse/IN-359)

[IN-359] Add special-case for Registries to resolve_guid

---

addons/gitlab/tests/test_views.py

Fix mocking for Gitlab to prevent tests from failing
- change the mocks from return values to primative datatypes
Only effects travis.
None

[Hotfix] Fix mocking for gitlab

---

api/base/settings/defaults.py
api/base/settings/local-dist.py
api/base/settings/local-travis.py
api/base/throttling.py
api/users/serializers.py
api/users/urls.py
api/users/views.py
api_tests/users/views/test_user_settings.py
framework/auth/oauth_scopes.py

Embosf will need this functionality to implement the account settings page.
- Add a /v2/users/<uid>/settings/export/ endpoint.
Type is `user-account-export-form`
POST to this endpoint should email the help desk (as clicking the button currently does)
Reponse should be `204 No Content`
- Add a /v2/users/<uid>/settings/deactivate/ endpoint.
Type is `user-account-deactivate-form`
POST to this endpoint should email the help desk (as clicking the button currently does)
Reponse should be `204 No Content`
None needed, can be tested on front end when finished.
None needed. Don't need excessive help desk emails.
https://openscience.atlassian.net/browse/PLAT-929

Feature/Account Export and Deactivation Requests in APIv2 [PLAT-929]

---

admin/nodes/views.py
admin_tests/nodes/test_views.py

This allows stuck registrations with addons to be remove via the admin.
See https://github.com/CenterForOpenScience/osf.io/pull/8444/files#r205158303
* Fix check for stuck registrations
* Some cleanup
https://openscience.atlassian.net/browse/PLAT-999

[PLAT-999] Allow removing stuck registrations with addons

---

docker-compose.yml

Fix OSF Requirements Install Using `docker-compose`
Use `--all` instead of `--quick`.
No
No
No
No

[No ticket] Fix OSF Requirements Install Using `docker-compose`

---

api/base/authentication/drf.py

Set the CSRF cookie so our front end can pass CSRF enforcement.
Whenever a request uses session auth and doesn't have a CSRF cookie, set a CSRF cookie.
- enable `enforce_csrf` switch (might take a while for the waffle cache to notice)
- go to the embosf dashboard page
- create a new project
- watch it not fail
Limitation: Ember apps will need to make a GET request (which will set the CSRF cookie in the response) before they can POST. This will probably always happen anyway, but might be a confusing thing someday.

Ensure CSRF cookie for all session-auth requests

---

api/nodes/serializers.py
api_tests/nodes/views/test_node_contributors_list.py

We don't want to show the email for contributors that have just been added.
- makes email write-only
- adds test
If you add a contributor you should see the contributor's email in the response.
Not a user facing change,
https://openscience.atlassian.net/browse/PLAT-1014

[Hotfix][PLAT-1014] Fix email write only
