CenterForOpenScience/osf.io

- website/templates/public/pages/meeting_landing.mako
Update OSF Meeting registration process
Before change:
After change:
1. go to osf.io/meetings/
2. in the section 'For Conference Organizers', click the green button 'Register'
3. There is a pop up which should display 'To request poster and talk hosting for a conference:
Submit this set-up form'
4. click the set-up form, it should redirect you to https://docs.google.com/forms/d/e/1FAIpQLSeBq4CfC5CjTBz49TP2dO9ZIsQc6QAAJFUoUbkS767Le9twLw/viewform
https://openscience.atlassian.net/browse/PLAT-681
> [#PLAT-681]Update OSF Meeting registration process

- addons/bitbucket/apps.py
- addons/bitbucket/models.py
- addons/bitbucket/tests/test_models.py
Handle deleted BitBucket repos
Before change:
You will get to "Unable to resolve" page and cannot access the project.
After change:
1. Create a project
2. Connect a Bitbucket repo to the project
3. Sign in to Bitbucket, and delete the repo
4. Navigate to your project
Before change:
You will get to "Unable to resolve" page and cannot access the project.
After change:
https://openscience.atlassian.net/browse/PLAT-697
> [#PLAT-697]Handle deleted BitBucket repos

- README-docker-compose.md
> Update readme for ipdb debugging

- api/licenses/views.py
- api/preprint_providers/views.py
- api_tests/licenses/views/test_license_list.py
- osf/models/licenses.py
- osf_tests/test_node_license.py
- website/static/js/licenses.js
https://github.com/CenterForOpenScience/osf.io/pull/8229 adds two new CC-licenses as options for both OSF projects and preprints - CC-BY-NC-ND and CC-BY-SA 4.0.  This PR removes them as options for projects, while still allowing them to be used on preprints.  Also removes these licenses from the APIv2 LicenseList endpoint.
- Remove latest two CC-licenses from project page dropdown
- Remove latest two CC-licenses from LicenseList endpoint
- Still allow the CC-licenses to be returned under PreprintProviderLicenseList if in licenses_acceptable or no licenses_acceptable specified.
- Still allow the new CC-licenses to be selected for a PreprintProvider in the admin app
- Still allow accessing new CC-licenses under LicenseDetail APIv2
https://openscience.atlassian.net/browse/PLAT-722
> Exclude Latest Two CC-licenses from Projects [PLAT-722]

- osf/migrations/0096_ensure_schemas.py
- website/project/metadata/ridie-complete.json
- website/project/metadata/ridie-initiation.json
- website/templates/project/registration_editor_templates.mako
Update ridie registration schema.
Requirements list:
https://docs.google.com/document/d/1nRXnDwP025bIYnkvhaMxMc9YAqrQq7ZM-FmSczvRRU8/edit
https://openscience.atlassian.net/browse/PLAT-367
> [#PLAT-367]Updates to RIDIE Registration form - Study Initiation

- website/templates/public/pages/meeting_body.mako
Add a loader that is present until treebeard loads. We do something similar [in other places 
](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/templates/profile/notifications.mako#L57).  
https://openscience.atlassian.net/browse/PLAT-657
> Feature/Loader for Meeting Submissions [PLAT-657]

- addons/base/views.py
- addons/osfstorage/utils.py
- addons/osfstorage/views.py
- osf/models/analytics.py
- osf/models/files.py
- tests/test_addons.py
Reverts CenterForOpenScience/osf.io#8184 because I merged it into the wrong branch.
> Revert "[PLAT-218][Needs WB PR] Use WB download action callbacks to tally preprint views"

- docker-compose-dist.override.yml
- docker-compose.yml
- docker-sync.yml
- website/collections/views.py
- website/routes.py
- website/settings/local-dist.py
- website/templates/public/pages/collections_landing.mako
Add collections docker stuff.
* Add collections to `docker-compose.yml` and `docker-sync.yml`.
* Add collections route and dummy landing page
Doesn't need QA
N/A
None
> [IN-277][osf.io] Add collections docker-compose and docker-sync configs

- api_tests/actions/views/test_action_list.py
- api_tests/users/views/test_user_actions.py
- osf_tests/factories.py
- requirements/dev.txt
Upgrades faker and factory-boy.
This avoids a dependency conflict that results in an ImportError
when running tests
* Replace fake-factory (deprecated) with faker
* Update factory-boy
* Remove an invalid usage in creating a PreprintFactory.
This failed silently in older versions of factory-boy but
raises an error in newer versions
Nothing to test
Nah
No--just a dep upgrade
No ticket
> Update factory-boy and change fake-factory->faker

- website/templates/footer.mako
Use title case in footer links.
Use title case in footer links.
As requested by QA
n/a
n/a
https://openscience.atlassian.net/browse/EMB-174
> [Hotfix][EMB-174] Use title case in footer links

- website/static/css/style.css
Stop the footer from being so clingy
Add a 20px margin to the top
I sure hope not
https://openscience.atlassian.net/browse/EMB-174
> [EMB-174] footer margin

- scripts/populate_institutions.py
As requested by the institution, update the contact link in the description.
"GW Data Services Librarian" should now direct to this page: https://libguides.gwu.edu/prf.php?account_id=151788
**NotQATeam**
No
No
https://openscience.atlassian.net/browse/SVCS-716
> [SVCS-716] [OSF Institutions] Update Description for GWU

- framework/auth/campaigns.py
- website/project/views/contributor.py
- website/templates/emails/password_reset.html.mako
* Follow-up fixes for #8187 
* Fix preprints and registries logos.
* Fix branded provider asset paths.
* Add OSF contact email to reset_password template.
- https://openscience.atlassian.net/browse/PLAT-338
> [feature fix] HTML email fixes [PLAT-338]

- website/static/css/style.css
- website/templates/project/project.mako
Fix responsiveness for collection list
- Replace dl list with ul
- Remove css
Please see QA notes at https://github.com/CenterForOpenScience/osf.io/pull/8266
[[IN-147]](https://openscience.atlassian.net/browse/IN-147)
> [IN-147][OSF] Fix responsiveness for collection list

- addons/base/views.py
It seems like there are 2 requests to create_waterbutler_log, and only the one by MFR includes the version. Default to marking the most recent version seen if there is no version passed in the original URL query parameter.
If version isn't included in `request_meta` from waterbutler, assume the latest version in `mark_file_version_as_seen`
This should hopefully fix things!
https://openscience.atlassian.net/browse/PLAT-639
> Don't rely on the latest version when determining unseen files [#PLAT-639]

- .travis.yml
Make builds faster by caching pip dependencies in Travis
Enable pip caching in Travis. See https://docs.travis-ci.com/user/caching
No ticket
> [no ticket] Cache pip deps in travis

- framework/auth/campaigns.py
- Fix logo for branded preprint account confirmation emails.
- https://openscience.atlassian.net/browse/PLAT-338
> [feature] Fix branded preprint invite email [PLAT-338]

- website/reviews/listeners.py
Add missing import
Import settings in reviews_submit_notification
N/A
N/A
Should fix some errors.
N/A
> [osf.io] Import settings in reviews_submit_notification

- addons/zotero/tests/utils.py
- tests/test_auth.py
* Fix failing tests on feature/storage-i18n
> [feature] Fix feature/storage-i18n tests

- osf/migrations/0106_auto_20180601_1341.py
- website/templates/emails/prereg_challenge_accepted.html.mako
* Add migration to update prereg challenge language. 
* Update prereg challenge email.
https://openscience.atlassian.net/browse/PLAT-818
> [feature] Update prereg language [PLAT-818]

- addons/osfstorage/tests/test_models.py
- osf/models/files.py
> Only clear comments for files with GUIDs

- api/base/serializers.py
> [Hotfix] Don't load all addons for every node

- website/templates/base.mako
GDPR Compliance
https://support.google.com/analytics/answer/2763052?hl=en
N/A
N/A
N/A
None
> [PLAT-917][Hotfix]  Anonymize Google Analytics IPs

- api/preprints/serializers.py
Check for workflows value and not the enum. Also simplify logic in the serializer.
- check for value
- logic a little cleaner
- Should actually not show the DOI value for non-approved preprints!
https://openscience.atlassian.net/browse/PLAT-921
> Check for pre-moderation VALUE to decide weather or not to show "predicted" DOI [PLAT-921]

- api/preprints/serializers.py
Misunderstood the requirements, pre-moderation preprints just don't publish the preprint until it's been confirmed. This is way better.
- Change the serializer check to pre-make the DOIs to see if the preprint has  been published or not
Ok hopefully this should be the one! <3
https://openscience.atlassian.net/browse/PLAT-921
> If a preprint is *not published* don't show the potential DOI [PLAT-921]

- CHANGELOG
- package.json
Update changelog and version for release
> Update changelog and version for 0.145.0

- api/crossref/views.py
[#PLAT-802]
Only send crossref error emails to the helpdesk when we encounter an error we're not expecting (i.e. something that isn't "Relation target DOI does not exist")
- Only send an email if we find an error that we weren't expecting, that isn't handled already
https://openscience.atlassian.net/browse/PLAT-512
> Only send error emails to helpdesk with unexpected failures [#PLAT-802]

- tests/identifiers/fixtures/datacite_post_metadata_response.xml
- tests/identifiers/test_datacite.py
- website/identifiers/clients/datacite.py
This matches what we used to send to datacite
https://openscience.atlassian.net/browse/PLAT-806
> Change resourceType to Project, and resourceTypeGeneral to Text

- .coveragerc
- .travis.yml
- README.md
- api/base/settings/defaults.py
- requirements/dev.txt
- tasks/__init__.py
Add Coveralls code coverage to tests runs.
e.g. @ https://coveralls.io/github/CenterForOpenScience/osf.io
Added dependencies for coverage and coveralls.
We will need to add additional exceptions to the `.coveragerc` `[omit]` section as needed.
N/A
N/A
Better tests.
N/A
> [Feature] Add code coverage to tests and coveralls badge

- scripts/analytics/file_summary.py
- scripts/osfstorage/usage_audit.py
* Fix nightly scripts
* Update file queries in scripts to be FOA compatible. 
* Remove unused `query_datetime` variable in file_summary.py
* No QA. I'll make a note to check sentry the day after this is merged to see if the scripts failed. 
* https://openscience.atlassian.net/browse/PLAT-964
> [feature] Fix scripts [PLAT-964]

- website/search/elastic_search.py
* Fixes operations that would update a file in search. 
* Check file `target` instead of `node` 
* Check file editing and renaming (on a public file).
* Check changing a project with files from private to public.
https://openscience.atlassian.net/browse/PLAT-968
> [feature] Fix update_file in search [PLAT-968]

- website/static/js/pages/file-page.js
* Fix adding/removing tags
* Update url for tags widget to match new route in #7875 
* Check adding and removing tags on a file
* https://openscience.atlassian.net/browse/PLAT-969
> [feature] Fix tags [PLAT-969]

- website/templates/project/project.mako
Fix sizing for logo in case the uploaded image is large.
Specify height = width = 16
https://openscience.atlassian.net/browse/IN-313
> [IN-313] Fix sizing for logo

- scripts/remove_after_use/remove_duped_subject.py
Remove duplicate psyarxiv custom subject (" Social and Personality Psychology" and "Social and Personality Psychology" both currently exist).
* Remove from existing preprints.
* Replace with correct subject on new preprints.
> [hotfix] Remove duplicate PsyArxiv subject

- scripts/remove_after_use/fix_psyarxiv_mapping.py
Fix prior migration
* Map from a controlled 1-1 list
None expected
[[PALT-987]](https://openscience.atlassian.net/browse/PLAT-987)
> [Hotfix][PLAT-987] Fix Psyarxiv mapping

- tasks/__init__.py
--quick is a misnomer because it installs all requirements
and is therefore the opposite of quick.
Before: `inv req --quick`
After: `inv req --all`
No ticket: just noticed this while developing.
> Rename --quick to --all for invoke requirements

- .travis.yml
Clean up Travis config.
* Remove unnecessary PROJECT_DIR envvar
* Remove varnish stuff
> Minor travis cleanup

- api/base/filters.py
- api/preprints/permissions.py
- api/preprints/views.py
- api_tests/preprints/views/test_preprint_detail.py
- api_tests/preprints/views/test_preprint_list.py
Let moderators see withdrawn, never public preprints
* Add perms class
* Update test
No UI yet
None expected
None
> [No Ticket] Add Moderator/Withdrawn permissions class

- scripts/populate_institutions.py
UGENT has requested a call with us to test institution login between their development environment and our test server.
@sloria please run the institution scripts on the test server, thanks
https://openscience.atlassian.net/browse/SVCS-855
> [OSF Institutions] Update Test Environment for UGENT [SVCS-855]

- addons/base/views.py
Addendum to #8643
When checking for a version to get the region, verify it's an osfstorage file
https://openscience.atlassian.net/browse/PLAT-1053
> When checking for a version to get the region, verify it's an osfstorage file

- api/base/filters.py
- api/base/serializers.py
- api/collections/views.py
- api/nodes/serializers.py
- api/nodes/utils.py
- api/nodes/views.py
- api/users/views.py
- osf/models/node.py
Serializing lists of nodes are slow - causing issues with collections endpoint on MyProjects page (which embeds LinkedNode), and issues with UserNodes.
Reducing n+1 queries on the following locations on the NodeSerializer:
- tags field
- ~node_license field~ **
- analytics_key field
- current_user_can_comment field
- current_user_permissions field
- ~license~ **
- wikis relationship
- parent relationship
- root relationship
- subjects field
** n+1 query problem still exists on licenses (because we have to fetch license recursively).  However, number of license queries has been halved. License is fetched once per node and put on serializer context for the other license field to use, credit @sloria 
Improvements made by annotating node queryset or using `prefetch_related`. Consolidated in …
> Feature/Optimize Node List Serialization [PLAT-981]

- addons/base/views.py
Yet another addendum to #8643
- Use OsfStorageFileNode (cuz BaseFileNode overrides path) 
- If path turns out to be a folder and a version is still there, don't error just don't do anything with the folder 
https://openscience.atlassian.net/browse/PLAT-1053
> Account for folders without relying on querying BaseFileNode for path [#PLAT-1053]

- addons/base/views.py
> Remove breaking select_related query

- addons/base/views.py
> Change fileversion query to filter to use select_related

- tasks/__init__.py
* Run the tests in the `api_tests/regions` directory.
> Run regions api tests

- addons/osfstorage/models.py
Travis wasn't happy, as sometimes a fileversion is not there for real!
Check if the fileversion exists before checking the region on that fileversion
> Adjust move_under to only update region if fileversion exists

- scripts/remove_after_use/fix_bookmark_permissions.py
A small set of users had their permissions revoked for Bookmark collections, due to a bug in the admin app. Said bug has since been fixed, this script grants admin permissions back to those users for their Bookmarks
Add script
Some affected staging users, other notes documented on ticket
None expected
[[IN-462]](https://openscience.atlassian.net/browse/IN-462)
> [Hotfix] Fix bookmark perms [IN-462]

- api/institutions/authentication.py
- framework/auth/views.py
- tests/test_auth.py
- website/ember_osf_web/decorators.py
- website/profile/utils.py
- website/profile/views.py
- website/project/views/node.py
- website/static/js/addProjectPlugin.js
- website/templates/emails/welcome.html.mako
- website/templates/emails/welcome_osf4i.html.mako
- website/templates/my_projects.mako
- website/templates/profile/account.mako
- website/templates/project/project.mako
- website/templates/project/settings.mako
- website/views.py
Disables storage-i18n frontend components on the user settings page, project settings page, add project/component modal, and welcome emails if waffle flag is not enabled. 
https://openscience.atlassian.net/browse/PLAT-1107
> [hotfix] Disable storage-i18n selectors

- website/templates/prereg_landing_page.mako
Closes [https://openscience.atlassian.net/browse/PLAT-1096]
Changes words so people still use the form. 
Add words
non
none
none
https://openscience.atlassian.net/browse/PLAT-1096
> Change wording

- osf/metadata/schemas/user_entered_datacite.json
- osf/metadata/serializers.py
- osf/metadata/utils.py
- osf/migrations/0124_add_file_metadata_models.py
- osf/models/metadata.py
- osf/models/nodelog.py
- osf_tests/test_file_metadata.py
- website/files/utils.py
Keep on going
- more validation
- move methods around
- even more tests
https://openscience.atlassian.net/browse/PLAT-983
> Some more updates for file metadata process! [#PLAT-983]

- website/templates/project/project.mako
Need a link on the project page to edit in a collection
Adds edit link for project admins to update the node in the collection
None
> Add edit link for collections

- framework/status/__init__.py
- requirements.txt
Upgrade Flask to 0.12.4
- update for catching "Out of context" error message better.
Not user facing, No QA.
Not user facing, No Docs.
https://openscience.atlassian.net/browse/PLAT-1102
> [PLAT-1102] Upgrade Flask

- website/views.py
Remove unused imports from website/views
Remove unused imports from website/views
n/a
n/a
n/a
n/a
> Remove unused imports from website/views

- admin/base/utils.py
- admin/collection_providers/forms.py
- admin/collection_providers/views.py
- admin/preprint_providers/forms.py
- admin/registration_providers/forms.py
Improve `*Provider` creation process
* Make it obvious that `id` is the url slug
* Fix CollectionProvider JSON export/import
Feel free to test provider creation/import/export on the `test` environment
None expected.
None.
> [Hotfix] Provider Admin Improvements [No Ticket]

- website/settings/defaults.py
Clean up unused settings to avoid confusion.
Looked through website/settings/defaults and website/settings/local-dist for unused settings
None needed
https://openscience.atlassian.net/browse/PLAT-1088
> Feature/Remove Unused Settings [PLAT-1088]

- framework/auth/views.py
- tests/test_views.py
Revert #8769 because it breaks ORCID login.
> [Hotfix] Revert #8769

- framework/auth/views.py
Resolves https://sentry2.cos.io/cos/osf-back-end/issues/9113/
Resolves https://staging-sentry.cos.io/cos/osf-back-end-pc/issues/4298/
Passes necessary `domain` argument to `welcome.html.mako`
https://openscience.atlassian.net/browse/PLAT-1210
> [hotfix] Add domain to external welcome email [PLAT-1210] 

- api/registrations/serializers.py
- api_tests/nodes/views/test_node_draft_registration_detail.py
- api_tests/nodes/views/test_node_draft_registration_list.py
- osf/models/node.py
- website/project/metadata/utils.py
Draft registrations with multiselect options are failing this PR makes sure they validate properly.
- fix multiselect options
- uncomment metadata validation
You should be able to make a new prereg challenge draft and submit it.
https://openscience.atlassian.net/browse/PLAT-1215
> [Hotfix][PLAT-1215] Partial registration fixes

- osf/migrations/0139_rename_aspredicted_schema.py
Fix migration
* Use model from app state when migrating
None expected
None
> [Hotfix] Migrate with model from app state

- scripts/remove_after_use/end_prereg_challenge.py
Improves logging for end prereg challenge script
- more logging statements for end prereg challenge script
No QA
No docs
https://github.com/CenterForOpenScience/osf.io/pull/8831
> [PLAT-1177] better logging for end prereg challenge script

- website/project/decorators.py
- website/views.py
* Avoid AttributeError
* Relocate permission check to include file guids
None expected
[PLAT-1274](https://openscience.atlassian.net/browse/PLAT-1274)
> [Hotfix][PLAT-1274] Preprint Download edge case

- admin/nodes/serializers.py
- api/nodes/filters.py
- api/nodes/serializers.py
- api_tests/nodes/views/test_node_detail.py
- api_tests/nodes/views/test_node_list.py
- api_tests/users/views/test_user_nodes_list.py
- osf/models/node.py
- osf/models/osf_group.py
- osf_tests/test_osfgroup.py
- Fixes for UserNodesFilter on current_user_permissions
- Simplify get_node_count query
> Feature/Guardian Polishing [PLAT-1268]

- api/nodes/serializers.py
- api/nodes/views.py
- api/osf_groups/permissions.py
- api/osf_groups/serializers.py
- api/osf_groups/views.py
- api/preprints/serializers.py
- api/users/views.py
- api_tests/nodes/views/test_node_linked_registrations.py
- api_tests/nodes/views/test_node_list.py
- api_tests/preprints/views/test_preprint_contributors_detail.py
- api_tests/preprints/views/test_preprint_contributors_list.py
- osf/admin.py
- osf/models/mixins.py
- osf/models/node.py
- osf/models/osf_group.py
- osf/models/preprint.py
- osf/models/user.py
- osf/utils/permissions.py
- osf_tests/test_node.py
- osf_tests/test_osfgroup.py
- osf_tests/test_user.py
- tests/test_preprints.py
- tests/test_views.py
- website/notifications/utils.py
- website/project/views/node.py
- website/search_migration/__init__.py
- website/util/rubeus.py
> Feature/Groups-Guardian Polishing IV [PLAT-1268]

- osf/metrics.py
Make Impact metric queries faster.
Only request relevant from relevant indices when querying impact metrics.
None. I will self-QA this.
This implementation relies on our use of yearly indexes. Implementation will need to change if we move to monthly or daily indexes. 
https://openscience.atlassian.net/browse/PLAT-1291
> [PLAT-1291] Only request relevant ES indexes

- admin/preprint_providers/forms.py
Disallow choosing type in preprint set up
Exclude type
none
none
none
https://openscience.atlassian.net/browse/DEV-296
> [DEV-296] exclude type from preprint admin set up

- osf/metrics.py
**Purpose**
PR #8882 introduced a bug where an uncaught `NotFoundError` would
be raised if `_get_relevant_indices` returned any indices that
don't exist in ES
**Changes**
Fall back to an unoptimized query if a `NotFoundError` is raised
during search.
**QA Notes**
Will self-QA this fix
**Ticket**
https://openscience.atlassian.net/browse/PLAT-1291
> Prevent error when index doesn't exist

- addons/base/views.py
Extend #8928 to actually work, whoops u_u
`data['version'] = None` is a thing
https://openscience.atlassian.net/browse/PLAT-639
> Actually handle None for version in data

- api/applications/serializers.py
- api/base/exceptions.py
- api/tokens/serializers.py
- api_tests/applications/views/test_application_detail.py
- api_tests/applications/views/test_application_list.py
- api_tests/tokens/views/test_token_detail.py
- api_tests/tokens/views/test_token_list.py
Validation errors that happened when calling `instance.save()` for creating and updating tokens and applications via V2 weren't being caught and re-raised properly as helpful errors.
- Method in a central place that formats these specific validation errors
- Catch them in create and update methods of token and application serializers
- Tests for create and update for tokens and serializers
This is entirely API related!
To test:
- Make an API request to create a token. Here's what the POST/PATCH data should look like, to `/v2/tokens/`
```
{
"data": {
"name": "aoeuaoeuaoeuaoeuaoeuaoeuaoeuaoeuao euaoeuaoeuaoeuaoeuaoeuaoeuaoeuaoeuaoeuaoeua oeuaoeuaoeuaoeuaoeuaoeuaoeuaoeuaoeuaoeuaoeu",
"scopes": "osf.full_read"
},
"type": "tokens"
}
}
```
- This should return a 400 response …
> Raise Validation errors for application and token create/update [PLAT-1089]

- osf/external/chronos.py
- website/settings/defaults.py
Turn off SSL cert verification if `DEV_MODE=True`
https://openscience.atlassian.net/browse/EMB-515
> [EMB-515][Chronos]verify=false if DEV_MODE is true

- osf/migrations/0147_blacklistedemaildomain.py
> .all() before .delete()

- addons/osfstorage/tests/test_views.py
- api/base/settings/defaults.py
- api/caching/tasks.py
- api/caching/utils.py
- osf/migrations/0156_create_cache_table.py
- osf/models/node.py
Too much throttle info in db.
- default cache no longer db.
Should cause improved performance site wide.
🐞 fix no docs.
https://openscience.atlassian.net/browse/PLAT-1355
> [Hotfix] Fix storage usage throttling [PLAT-1355]

- scripts/populate_institutions.py
cc @mfraezz 
- CWRU has revised the institution description again.
- More on the login issue.
It turns out that the issue is on our side since CWRU does release required attributes to us and login is successful locally. It must be either missing mapping in Shibboleth `attribute-map.xml` or a typo/mistake in CAS `institutions-auth.xsl`.
```bash
2019-05-07 16:17:55 INFO Shibboleth-TRANSACTION [5]: Cached the following attributes with session (ID: _9ad26498f9bc156d034c157eb3bceac2) for (applicationId: default) {
2019-05-07 16:17:55 INFO Shibboleth-TRANSACTION [5]:    uid (1 values)
2019-05-07 16:17:55 INFO Shibboleth-TRANSACTION [5]:    mail (1 values)
2019-05-07 16:17:55 INFO Shibboleth-TRANSACTION [5]:    displayName (1 values)
2019-05-07 16:17:55 INFO Shibboleth-TRANSACTION [5]: …
```
> [OSF Institutions] Update CWRU Description and Fix Login [ENG-342]

- osf_tests/test_comment.py
- website/project/model.py
Improve validation for finding new mentions and replace old legacy code.
- removes `validate_contributor` for @mentions and consolidates function
technical task, no docs.
https://openscience.atlassian.net/browse/PLAT-552
> [PLAT-552] Improve method that checks for @mentions

- api/meetings/serializers.py
- api_tests/meetings/views/test_meetings_detail.py
Add related count to related submission link's meta.
> [No Ticket ] Add related count to related link meta

- website/templates/registered_reports_landing.mako
Update language on the Registered Reports workflow landing pages
words
n/a
n/a
n/a
https://openscience.atlassian.net/browse/ENG-469
> [ENG-469] update language

- website/project/views/node.py
Additional sanitation for &amp;. This time in the components modal dialog
Added sanitation to the title line in website/project/views/node.py
https://openscience.atlassian.net/browse/ENG-53
*See comments for specific change
> [ENG-53] Adding ampersand sanitation to the components modal dialog

- osf/external/chronos.py
Send license info to Chronos.
Change error message for duplicate submissions to the same journal.
Send license name if the license is not `No license`. Send `NL` if the license name is `No license`.
Change the error message of duplicate submissions.
https://openscience.atlassian.net/browse/ENG-656
> [ENG-655][ENG-656] Send license info to Chronos

- website/views.py
Fix dead link
* Update URL
Ensure osf.io/faq/ doesn't throw a 404
None Expected
None
> [Hotfix] Update FAQ link

- tests/test_ember_osf_web.py
Hunt down and fix import mocking bug that was fooling with travis.
- Stop mocking imports
should pass travis
🐞 fix, no docs
Non that I know of.
> Get waffle cookies working... again!

- README-docker-compose.md
- tasks/__init__.py
- tasks/local-dist.py
add clause that checks for local tasks and creates a local-dist.py with example task
Developer happiness
> [LUP] Add local tasks!

- package.json
- yarn.lock
Upgrading Bower Version to 1.8.8.
Updating yarn.lock. Keep in mind this is not manual, but was done by running `yarn upgrade bower`
The goal of this PR is to not cause any issues at all. This should not add new functionality nor break anything. Bower is a legacy package manager used on any non-emberized pages, so any non-emberized pages need to be tested for brokenness.
https://openscience.atlassian.net/browse/ENG-678
> [ENG-678] Upgrading bower version to 1.8.8

- api/registrations/serializers.py
Don't include prereg challenge comments with `registered_meta` -- they are unnecessary
Strip out `comments` in the registration serializer.
Viewing registrations should work just as before.
n/a
n/a
n/a
> [fix] Prereg challenge comments

- scripts/EGAP/files_to_import_structure.py
- scripts/tests/test_files_to_import_structure.py
Take the 52 pick-up that is the EGAP data dump and make it into the freshly minted deck of our file import structure.
1. Given a directory of files (a.ka. files_dir), a directory of metadata generated from the egap spreadsheets (a.k.a. metadata_dir), and an optional list of project ids, copy the appropriate files from the files directory into the appropriate locations in the directory of metadata generated from the egap spreadsheets.
* The location to copy to (a.k.a. destination_dir) is "<metadata_dir>/<project_id>/data/"
* Do not copy the files if they do not start with the project id
* If the files contain the word "anonymous" (case insensitive), copy to a "<destination_dir>/anonymous" directory
* If the files contain the phrase "PAP_anon" (case insensitive), copy to the …
> [ENG-1108] Add script for importing files into EGAP file structure

- osf/external/chronos.py
All the remaining author should be `Author` instead of `submittingAuthor`.
> [No ticket] Change 'submittingAuthor' to 'Author'

- api/registrations/serializers.py
Remove input format constraint for embargo_end_date field.
> [No ticket]Fix datetime format

- scripts/EGAP/files_to_import_structure.py
Some unnecessary double quotes stuck in there, let's remove them.
- " -> '
Non-necessary
N/A
None
> fix double quotes for travis

- api/base/serializers.py
- api/schemas/serializers.py
> Add 'schema' relationship to RegistrationSchemaBlockSerializer

- osf/management/commands/import_EGAP.py
Make sure ingestor can ingest zipped files properly
- add to scripts
No additional QA
No that I know of 
None
> Fix ingestor2

- osf/management/commands/import_EGAP.py
Adds error handling for registration metadata for EGAP Registrations
* Adds checks for what should be the `egap_registration_date` and the `egap_embargo_public_date` on the import_EGAP script
> Adds error checking for import_EGAP registration_metadata

- api/base/serializers.py
Add `data` to `target` field on files endpoint.
> Modify TargetField

- website/project/metadata/registered-report-3.json
To change the `title` and `description` text in `registered-report` to match new wording.
Update the `registered-report` schema
Should be tested to make sure wording is accurate against the new changes.
`N/A`
`N/A`
`N/A`
> [Feature] Update registered-report schema

- website/project/metadata/osf-open-ended-3.json
Add question label to file upload on Open-ended Registration
Add `description` to file upload on Open-ended Registration schema
`n/a`
`n/a`
`n/a`
> Open-ended registration: Add question label to file upload

- osf/utils/migrations.py
avoid duplicate headings/labels in registration schema blocks
when migrating to schema blocks:
if a "parent" question has text and its first "child" question does not, skip the `section-heading` block and move the text to the child
> deduplicate schema headings

- scripts/stuck_registration_audit.py
Resolve Sentry Error: https://sentry2.cos.io/cos/osf-back-end/issues/22889/
Minor byte-string conversion issue
Dev test only
None
> [Hotfix] Fix stuck registrations audit for py3

- website/project/metadata/egap-registration.json
EGAP files are not functioning properly on registration pages
Added a config line to the EGAP schema, ensuring that archiver will properly archive the files.
Ensure file links are working now
N/A
Shouldn't be
https://openscience.atlassian.net/browse/ENG-1375
> [ENG-1375] Adding in a config section to the EGAP schema

- osf/management/commands/import_EGAP.py
Reverts CenterForOpenScience/osf.io#9260
> Revert "Feature/egap fix part 2"

- api/draft_registrations/views.py
- api/nodes/views.py
https://openscience.atlassian.net/browse/ENG-1353
> [ENG-1353] raise Gone if the draft has been registered

- website/templates/emails/preprint_withdrawal_request_declined.html.mako
Update email language to instruct users to signin and visit their preprint to see reason declined, because users are missing this
Update email language to instruct users to signin and visit their preprint to see reason declined
Just email language change
https://openscience.atlassian.net/browse/ENG-1174
> [ENG-1174] Update email language for withdrawal declined

- osf/management/commands/data_storage_usage.py
- osf/management/commands/registration_schema_metrics.py
We had some still someone mysterious byte/str encoding issues that were causing this script to fail.
- hack fixes bytes to strings while iterating rows.
Hotfix should be dev tested watch out for bad data on prod.
Not user facing no new docs.
https://openscience.atlassian.net/browse/ENG-1442
> [ENG-1442][Hotfix] Fix data usage script for Python 3

- .travis.yml
- requirements/constraints.txt
Clean up travis issues that were causing failures.
- add six==1.14.0 to constraints.txt to resolve conflict
- clean-up travis depreciation warnings
Should just cause travis to pass.
🐞  fix, no new docs.
Hotfox, no ticket.
> [Hotfix] Fix sick travis

- api/base/views.py
- osf/models/preprint.py
Fix up docstrings
-  makes docstring accurately represent the datatype
Not reverent to QA 
not user facing, no docs.
https://openscience.atlassian.net/browse/ENG-1642
> [ENG-1642] Sloan cleanup

- .travis.yml
- api_tests/conftest.py
- api_tests/sloan/test_sloan_metrics.py
- osf/metrics.py
- pytest.ini
Oh with the excitement of it all we ding-dang forgot to actually map the new sloan attributes to the PreprintView/Download templates, this adds them in and adds tests to make sure we never forget.
- adds sloan fields to Preprint metrics model
- adds tests and travis changes.
Devtest and Courtney test only.
🐞 fix, no new docs.
https://openscience.atlassian.net/browse/ENG-1650
> [ENG-1650] Sloan querying attributes fix

- osf/management/commands/update_institution_project_counts.py
- osf/metrics.py
Creates a management command to update institutional and institutional-user public and private project counts in Impact
* Creation of `update_institution_project_counts` management command which records public and private project counts for institutions and institution-users.
* Creation of `UserInstitutionProjectCounts` and `InstitutionProjectCounts` metrics classes with functions to write and retrieve records from Impact. 
These changes do not require data migrations and is an additive change. Testing for this ticket may have to be dev testing (outside of what I've already tested locally) by running the script and modifying the Impact indices in elasticsearch6. 
No external documentation needs to be updated.
Possible side effects include increased load on servers at the time of day the …
> Institutional Metrics for Impact Script [ENG-1477]

- osf/management/commands/reindex_es6.py
- osf_tests/management_commands/test_reindex_es6.py
Extends #9323 
- Prevent closing active indices
- Rename command
N/A
N/A
None expected
[[ENG-1650]](https://openscience.atlassian.net/browse/ENG-1650)
[ENG-1650]: https://openscience.atlassian.net/browse/ENG-1650
> [ENG-1650] Prevent closing of active indices

- addons/base/views.py
Fix fields still not matching their mappings.
- one string manipulation line
Wait until passes dev-test
🐞 fix no docs.
https://openscience.atlassian.net/browse/ENG-1688
> [ENG-1688] Fix cookie names again

- api/institutions/serializers.py
- api/institutions/urls.py
- api/institutions/views.py
- api_tests/institutions/views/test_institution_department_list.py
- api_tests/institutions/views/test_institution_detail.py
- api_tests/institutions/views/test_institution_summary_metrics.py
- api_tests/institutions/views/test_institution_user_metric_list.py
- api_tests/sloan/test_sloan_metrics.py
This adds the metrics relationship links to the institution detail.
- simple changes to the institution serializer and adds some testing.
Dev test only, QA will able to see if this works on the front-end.
Sample json:
```json
{
"data": {
"id": "cos",
"type": "institutions",
"name": "Center For Open Science [Stage]",
"description": "Center for Open Science [Stage]",
"assets": {
"logo": "/static/img/institutions/shields/cos-shield.png",
"logo_rounded": "/static/img/institutions/shields-rounded-corners/cos-shield-rounded-corners.png"
}
},
"nodes": {
"links": {
"related": {
"href": "http://localhost:8000/v2/institutions/cos/nodes/",
"meta": {}
}
}
},
"registrations": {
"links": {
"related": {
"href": …
```
> [ENG-1554] Institutional relationships endpoints

- api/base/middleware.py
- framework/auth/views.py
fix problem where logging in wouldn't update the logged in flags.
- Adds Sloan id to custom id function 
Sloan id should be registered on impact for custom domains.
🐞 fix no docs.
https://openscience.atlassian.net/browse/ENG-1739
> [ENG-1739] Set Sloan ids to custom domains

- api/base/utils.py
- api/institutions/views.py
To fix the impact ES pagination.
No migrations, low risk, test 
This is actually loading more results, which is necessary for preserve ordering.
https://openscience.atlassian.net/browse/ENG-1764
> [ENG-1764] Fix pagination for impact dashboard

- api/institutions/serializers.py
- api/institutions/views.py
- api_tests/institutions/views/test_institution_department_list.py
Making department id unique on the department api endpoint by adding institution ID
Changing the institution views and serializer to use a custom ID for department
No
minimal
no
Additive
Through API
N/A
Institutional dashboard
n/a
-->
N/A
Shouldn't be.
https://openscience.atlassian.net/browse/ENG-1821
> [ENG-1821] Adding institutional ID to departments.

- website/institutions/views.py
- website/routes.py
Serve the ember institutional dashboard
Adding route to ember, adding return ember app to institution views.
No
minimal
No
Additive
UI
N/A
Institutional Dashboard
N/A
-->
N/A
N/A
https://openscience.atlassian.net/browse/ENG-1823
> Adding route for institutional dashboard [ENG-1823]

- osf_tests/test_sanctions.py
Beefing up tests for ending embargo early for registrations with multiple contributors
Adding tests to osf_tests/test_sanctions.py
No
None. Adding tests
no
Additive
N/A
N/A
N/A
N/A
-->
N/A
N/A
https://openscience.atlassian.net/browse/ENG-1920
> Adding additional tests for ending embargo early [ENG-1920]

- api_tests/institutions/views/test_institution_summary_metrics.py
- api_tests/institutions/views/test_institution_user_metric_list.py
Some tests were failing randomly. Some needed institution as an arg. also increased time.sleep
See Purpose
No
None
No
Modification to tests
N/A
N/A
N/A
Might slow tests a tad
-->
N/A
N/A
N/A
> Institutional metrics test enhancements

- api_tests/institutions/views/test_institution_user_metric_list.py
- api_tests/registrations/views/test_registration_list.py
Some tests were failing randomly. Some needed institution as an arg. also increased time.sleep
See Purpose
No
None
No
Modification to tests
N/A
N/A
N/A
Might slow tests a tad
-->
N/A
N/A
N/A
> Further test enhancement

- admin/preprint_providers/views.py
- admin/registration_providers/views.py
- admin/templates/registration_providers/detail.html
- osf/models/provider.py
This fixes the admin app so it displays exceptions created by the SHARE source function properly.
- catch and displays error messages for providers
- fix redirects 🤦 
No
Low
No
Other
AdminApp, look at ticket description
None
No
🐞  fix no docs
https://openscience.atlassian.net/browse/ENG-2092
> [ENG-2092] Fix share source validation and exception handling

- admin/templates/base.html
- osf/migrations/__init__.py
Fix typo so brands can be displayed.
- fix simple typo
- no migration
- low risk
- verifiy via admin app
bug fix, no docs 
https://openscience.atlassian.net/browse/ENG-2084
https://openscience.atlassian.net/browse/ENG-2084
> [ENG-2084] Fix typo in view brands

- osf/migrations/__init__.py
Fix typo so brands can be displayed.
- just adds brand write permissions for everyone.
- no migration
- low risk
- verifiy via admin app
bug fix, no docs 
https://openscience.atlassian.net/browse/ENG-2143
> [ENG-2143] Migrate brand write permission to `osf_admin`

- PULL_REQUEST_TEMPLATE.md
Update the QA notes section of the Pull Request Template to be more streamlined and modern
-->
> Update qa notes

- addons/zotero/requirements.txt
Keep zotero from breaking our builds.
Update zotero requirements.
- Only changes the version of the zotero library we're using
What are the areas of risk? We'll want to regression test the zotero addon.
Certainly possible
N/A
> Update zotero requirements

- website/project/metadata/qualitative-research.json
- website/project/metadata/real-world-evidence.json
Fix problems with the RWE registration and the Qualitative registration forms
1. Change 'description' blocks to 'help' blocks
2. Fix Q7 to match what the spreadsheet had
3. Add newlines to various places in the forms where they were called for
4. Update qualitative form based on feedback [ENG-2353]
- Examples show up below the help text
- Formatting is better on questions that have newlines
https://openscience.atlassian.net/browse/ENG-2351
https://openscience.atlassian.net/browse/ENG-2353
[ENG-2353]: https://openscience.atlassian.net/browse/ENG-2353
> [ENG-2351][ENG-2353] Fix RWE registration form

- .travis.yml
- osf_tests/factories.py
- website/project/metadata/schemas.py
Fix travis fails on develop and master
- add new schema to ordering
- Verify travis passes this PR
Low risk
🐞 fix, no docs
https://openscience.atlassian.net/browse/ENG-2360
> [ENG-2360] Fix travis

- api/actions/serializers.py
This will make the types correct for ember
- simple change to type string
- Verify the type for registration actions is `review-actions`
🐞 fix, no docs
https://openscience.atlassian.net/browse/ENG-2382
> [ENG-2382] Change registration-actions type to review actions

- website/project/metadata/real-world-evidence.json
Makes additional modifications to the RWE schema
* Adjusts help/example text on the Real World Evidence schema
N/A
N/A
N/A
[JIRA Ticket](https://openscience.atlassian.net/browse/ENG-2375)
> [ENG-2375][Hotfix] RWE Schema Tweaks

- .travis.yml
- tasks/__init__.py
Reverts CenterForOpenScience/osf.io#9546
> Revert "[WIP] Fix testmon"

- osf/models/sanctions.py
- website/notifications/tasks.py
- website/templates/emails/digest_reviews_moderators.html.mako
- website/templates/emails/pending_embargo_admin.html.mako
Fix sporadic sentry errors from badly formatted emails.
- pass user to moderator digest emails
- add colon to email template conditional
- Verify emails are sent correctly via registries moderation
https://openscience.atlassian.net/browse/ENG-2450
> [ENG-2450] Fix email formatting problems

- .github/actions/build-es/action.yml
- .github/actions/build-es6/action.yml
- .github/actions/start-build/action.yml
- .github/workflows/test-build.yml
- README.md
- admin_tests/spam/test_views.py
- api/base/settings/local-travis.py
- api/requests/views.py
- tasks/__init__.py
- website/settings/local-travis.py
Migrate off of TCI. 
h/t @corbinSanders for the bulk of the initial work.
- GHActions yaml
- Update README badges
- add `order_by` to `PreprintRequestActionList`
- ignore ordering in `test_get_spam`
- tweak CI settings
N/A
None Expected
[ENG-2614](https://openscience.atlassian.net/browse/ENG-2614)
> [Hotfix] Add GitHub Actions build yml [ENG-2614]

- website/templates/search_bar.mako
Search icon is clickable, but not visible. The CSS needs a small update to fix issue. 
Modified search_bar.mako 
- Verify search icon appears. 
- N/A
- N/A
- N/A
- N/A
https://openscience.atlassian.net/browse/ENG-2228
> [ENG-2228] Fix search bar icon

- osf/management/commands/find_spammy_files.py
- website/mails/mails.py
- website/settings/defaults.py
- website/templates/emails/spam_files_detected.html.mako
Mitigate abuse
Add configurable async script to auto-detect spam
Add dict with necessary info to `CeleryConfig.beat_schedule`
None expected
> [Hotfix] File Sniffer

- .github/workflows/test-build.yml
The install lxml job is failing on the main workflow.
Adding `sudo apt-get update` to the install xml job run script. 
- Verify N/A dev test
- Verify
N/A
N/A 
N/A
> Fixing lxml install on the workflow [hotfix]

- osf/migrations/0227_add_secondary_data.py
- website/project/metadata/schemas.py
- website/project/metadata/secondary-data.json
A new registration schema needs to be added for secondary studies
Adding the new schema, a migration to add the schema to the db
- Verify the new schema is not visible, however request it is made visible on staging for testing purposes
- Verify
N/A
N/A
https://openscience.atlassian.net/browse/ENG-2652
> Adding secondary schema [ENG-2652]

- addons/osfstorage/models.py
- api_tests/institutions/views/test_institution_registrations_list.py
- api_tests/registrations/views/test_withdrawn_registrations.py
- osf/management/commands/delete_withdrawn_or_failed_registration_files.py
- osf/models/files.py
- osf/models/registrations.py
- osf/models/sanctions.py
- osf_tests/factories.py
- osf_tests/management_commands/test_delete_withdrawn_or_failed_registration_files.py
- website/search/elastic_search.py
- website/settings/defaults.py
- website/settings/local-travis.py
Expands on PR purging files for withdrawn registrations to include failed registrations as well
- adds periodic tasks to mark files as deleted and purge them, with tests.
- Verify failed registrations are purged, check with dev-ops to ensure files are purged properly.
new tech task, no docs.
https://openscience.atlassian.net/browse/ENG-2108
> [ENG-2108][ENG-2107] Purge archive fails

- osf/models/draft_node.py
- osf/models/sanctions.py
- osf_tests/test_sanctions.py
- website/mails/mails.py
- website/project/views/contributor.py
- website/templates/emails/contributor_added_draft_registration.html.mako
- website/templates/emails/invite_draft_registration.html.mako
- website/templates/emails/password_reset.html.mako
- website/templates/emails/pending_embargo_admin.html.mako
- website/templates/emails/pending_embargo_non_admin.html.mako
- website/templates/emails/pending_embargo_termination_admin.html.mako
- website/templates/emails/pending_embargo_termination_non_admin.html.mako
- website/templates/emails/pending_registration_admin.html.mako
- website/templates/emails/pending_registration_non_admin.html.mako
- website/templates/emails/pending_retraction_admin.html.mako
- website/templates/emails/pending_retraction_non_admin.html.mako
Update the emails for Registrations to
a) Reference the My Registrations page in emails to new draft contributors
b) Give more correct information to unregistered contributors added to draft registrations
c) Reference the created project in relevant sanctions emails for no-project registrations
d) Improve clarity
* Updated language in`contributor_added_draft_registration`
* Updated language in all emails about pending sanctions
* Added a new template for unregistered contributors on draft registrations
* Stopped emailing contributors when a DraftNode gets converted to a Node (since this is now in the embargo/approval email)
- Verify
- Verify
Any …
> [ENG-2752] Update registration emails

- api/users/views.py
- api_tests/users/views/test_user_list.py
This removes bad versioning that created an error when merged contributors were added in the draft registration workflow.
- remove bad versioning conditional
- Verify merged users don't appear in search
- Verify
https://openscience.atlassian.net/browse/ENG-2694
> [ENG-2694] Remove merged contributors from search

- admin/templates/users/user.html
- osf/models/mixins.py
Minor improvements to spam exclusions and Admin functionality
-Allow any un-hammed user to be marked as ham
-Prevent auto-spamming of moderated objects -- preprints and registrations
None expected
None known
> [Hotfix] Spam Tweaks [No Ticket]

- admin/users/views.py
Fix bug from #9688 
- Add conditional to bypass superclass disabling control flow when user is not disabled.
None expected
None
> [Hotfix] Ham Confirmation [No Ticket]

- website/project/metadata/character-lab-fully-powered-study.json
- website/project/metadata/character-lab-pilot-study.json
Updating character lab schemas per their request
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-2880
> Hotfix/character lab schema [ENG-2880] [SCHEMA] [HOTFIX]

- website/project/metadata/schemas.py
Ensure that the character lab schemas will be found by the management command.
Add the schemas to the schemas.py file
As long as `update_registration_schemas` finds the schemas, this should be fine.
No
N/A
> Find character lab schemas

- api/guids/serializers.py
- api/search/views.py
- website/search/elastic_search.py
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-2928
> [ENG-2928] Add ability to search on new collection metadata facets

- website/search/elastic_search.py
Prevent private or deleted objects from appearing in search.
- Allow deletes to occur
- DRY up code
None expected
[ENG-2630](https://openscience.atlassian.net/browse/ENG-2630)
> [Hotfix] Allow CollectionSubmission deletion from search [ENG-2630]

- website/project/metadata/real-world-evidence.json
Removing a question from RWE schema.
https://openscience.atlassian.net/browse/ENG-3113
> [ENG-3113] Hotfix/rwe schema fix

- website/registrations/utils.py
Add a CSV parser for bulk registration upload
- Add parser utility class
*usage*
```python
from website.registrations.utils import BulkRegistrationUpload
file_upload = open('upload_example.csv')
upload = BulkRegistrationUpload(file, 'osf')
upload.validate() # parse and validates each row
upload.errors # all validation errors
upload.get_parsed() # get parser output
```
TODO
TBD
- Verify
- Verify
N/A
N/A
> [ENG-3104] Add bulk upload csv parser

- website/registrations/utils.py
Use schema blocks to build validations
Tested as part of the project
N/A
N/A
> [ENG-3104] Use schema blocks to build validations

- api/base/urls.py
- api/providers/views.py
- scripts/prepare_for_registration_bulk_creation.py
- website/registrations/utils.py
> [No ticket] Some modifications to the parser

- api/providers/tasks.py
- api/providers/views.py
- website/registrations/utils.py
- website/settings/defaults.py
> Move task locations and some parser fixes.

- website/project/metadata/character-lab-long-form-registration.json
- website/project/metadata/character-lab-short-form-registration.json
- website/project/metadata/schemas.py
Latest updates to the Character Lab schemas, using atomic schema format.
Most work done by @Johnetordoff as part of https://github.com/CenterForOpenScience/osf.io/pull/9754
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3205
> [ENG-3205] Updated CL Schemas (as atomic schemas)

- website/registrations/utils.py
> Update to 'get_raw_value' method

- website/registrations/utils.py
Handle badly formatted contributor name and email
- Handle case where entry does not match expected format (e.g Jane Doe\<jane.doe@email.com\>)
N/A
N/A
> [ENG-3104] Catch contributor format errors

- api/providers/views.py
- website/registrations/utils.py
> fix subjects; provide meaningful err msg for invalid/missing columns

- website/registrations/utils.py
Make 'bibliographic contributors' required
- Make 'bibliographic contributors' required
- Add new errors
N/A
N/A
> [ENG-3104] Require bibliographic contributors; add new error types

- website/registrations/utils.py
Remove `global STORE`
- Use `BulkRegistrationUpload` instance variable instead of `global`.
N/A
> [ENG-3104] Remove global store

- api/providers/views.py
- osf/registrations/utils.py
Respond to code review https://github.com/CenterForOpenScience/osf.io/pull/9782
- Move parser class to `osf/registrations/`
- Optimize `get_schema_questions_validations`
N/A
N/A
> [ENG-3104] Bulk upload parser improvements

- api/providers/views.py
- website/registrations/utils.py
> Fix permission checks + some nitpicks.

- website/templates/include/profile/social.mako
- website/templates/project/modal_add_contributor.mako
Improve coverage to check all user profile links.
- simple config change
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3125
> [ENG-3125] Improve Indexing of social links

- osf/models/registrations.py
- osf/models/schema_response.py
- osf_tests/test_pigeon.py
> add schema response update behavior to pigeon

- osf/models/schema_response.py
- osf_tests/test_schema_responses.py
- website/mails/mails.py
- website/templates/emails/updates_approved.html.mako
- website/templates/emails/updates_initiated.html.mako
- website/templates/emails/updates_pending_approval.html.mako
- website/templates/emails/updates_rejected.html.mako
Bring the emails in line with the language from product
* Update the language in the mako templates
* Update context when sending emails to support template changes
* Send emails to contributors when update is submitted for moderation
- Verify
- Verify
> Updated email language for Registration Update

- osf/models/schema_response.py
- osf_tests/test_schema_responses.py
- website/notifications/tasks.py
- website/templates/emails/digest_reviews_moderators.html.mako
- website/templates/emails/updates_approved.html.mako
- website/templates/emails/updates_pending_approval.html.mako
- website/templates/emails/updates_rejected.html.mako
* Fix language in the emails for registration update
* Fix test that wasn't checking the rendering of certain emails
* Fix the absolute URL for non-APPROVED SchemaResponses to point to the revision route instead of the registration + query param
* Fix bad links and link rendering in moderator digest emails
- Verify
- Verify
> Fixes for reg update emails

- api/providers/tasks.py
- api_tests/providers/tasks/test_bulk_upload.py
- osf/registrations/utils.py
- osf_tests/test_registrations.py
- website/notifications/tasks.py
CR response to https://github.com/CenterForOpenScience/osf.io/pull/9841
* Fix registration provider submissions URL 
* Improve subjects parsing logic
* Finer-grained try-except
* Remove unnecessary and improve existing info level logs
* Add/update tests
* Fix minor style issues
See **Purposes**
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-3262
> [ENG-3262] Bulk upload: more improvements and bug fixes

- api/providers/tasks.py
- api_tests/providers/tasks/test_bulk_upload.py
- osf/registrations/utils.py
- osf_tests/test_registrations.py
- website/notifications/tasks.py
CR response to https://github.com/CenterForOpenScience/osf.io/pull/9841; Carbon copy of https://github.com/CenterForOpenScience/osf.io/pull/9854.
* Fix registration provider submissions URL 
* Improve subjects parsing logic
* Finer-grained try-except
* Remove unnecessary and improve existing info level logs
* Add/update tests
* Fix minor style issues
See **Purposes**
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-3262
> [ENG-3262] Bulk Upload Improvements - Pre-release Fixes

- website/static/js/filepage/editor.js
- website/static/js/filepage/index.js
Adds some additional tags for better metrics.
- minor js changes
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3497
> [Hotfix][ENG-3497] Google Analytics for collaborative editing. 

- admin/templates/collection_providers/update_collection_provider_form.html
- admin/templates/preprint_providers/create_or_update_preprint_provider_form.html
- admin/templates/registration_providers/update_registration_provider_form.html
remove unnecessary admin code
remove the unused tinymce-fontawesome plugin
n/a
- Verify
- Verify
n/a
none worth mentioning
n/a
> [hotfix] drop unused plugin

- requirements.txt
Explicitly specify the version of `cryptography` to install, since `pyjwe` requires it and will grab a version we cannot support (anything >3.4 needs rust to build, and our Alpine version does not support rust)
- Verify
- Verify
> Explicit cryptography version

- scripts/populate_institutions.py
Add University of Manchester (`uom`) to production OSF
N/A
* Add the following to `institutions-auth.xsl` in `prod` CAS .
```xml
<xsl:when test="$idp='https://shib.manchester.ac.uk/shibboleth'">
<id>uom</id>
<user>
<username><xsl:value-of select="//attribute[@name='mail']/@value"/></username>
<isSelectiveSso>true</isSelectiveSso>
<selectiveSsoFilter><xsl:value-of select="//attribute[@name='selectivessofilter']/@value"/></selectiveSsoFilter>
<fullname><xsl:value-of select="//attribute[@name='displayname']/@value"/></fullname>
<familyName><xsl:value-of select="//attribute[@name='sn']/@value"/></familyName>
<givenName><xsl:value-of select="//attribute[@name='givenname']/@value"/></givenName>
<middleNames/>
<suffix/>
</user>
</xsl:when>
```
*  It should be under the section `<xsl:when …
> [ENG-3342] University of Manchester - Prod

- website/project/metadata/hypothesis-testing-studies-using-youth-data.json
- website/project/metadata/other-studies-using-youth-data.json
> New Youth Schema

- api/base/serializers.py
The Files Page redesign is on the horizon, so we wanted to fix some fringe issues with our files embedding, specifically embedding registration files. This PR fixes that by updating the `TargetField` for registrations.
- Small changes to serializer field to allow or registrations. 
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3641
> [ENG-3641] Fix target field embedding for Registrations

- api/files/serializers.py
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3665
> [ENG-3665] Allow guids to be returned as id for files

- api/registrations/views.py
Enable sorting by name and modified date for RegistrationFilesList view
- Verify
- Verify
> Specify ordering_fields for RegistrationFilesList

- package.json
- yarn.lock
Fix weird modal behavior
Pin `mithril` strictly to `0.2.0`.
- Verify
- Verify
> Fix weird modal behavior

- admin/management/views.py
- admin/templates/management/commands.html
- scripts/find_spammy_content.py
Optimize an admin function
- Add `fast` execution option
None expected.
Unknown
> [Hotfix] Add `fast` option to script

- scripts/populate_institutions.py
Configure new institution `nesta`  for `prod` server.
Most work has been done in https://github.com/CenterForOpenScience/osf.io/pull/9893 and this PR only updates the description.
* After deployment, run the institution population script for `prod`.
```
python3 -m scripts.populate_institutions -e prod -i nesta
```
* (Optional) You can also run the script for the `test` server to update the description, which can also be done via the admin app.
**`prod` settings are different from `test` settings since the IdP servers are different.**
* Before deployment, add the following to `institutions-auth.xsl` under SAML institutions.
```xml
<xsl:when test="$idp='http://www.okta.com/exkum8enx4nlKaJR50x7'">
<id>nesta</id>
<user>
<username><xsl:value-of …
```
> [ENG-3634] OSF4I - Nesta Prod

- api/nodes/serializers.py
- api_tests/draft_nodes/views/test_draft_node_files_lists.py
- api_tests/nodes/views/test_node_files_list.py
- api_tests/preprints/views/test_preprint_files_list.py
Adds a target link to node provider storage view.
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3780
> Add target link to node provider storage serialization

- osf/metadata/utils.py
- website/identifiers/clients/crossref.py
Crosseref specifies that there must be at least one institution if the `affiliations` tag is used. We are appending an empty list of in the case of no affiliations.
Only append affiliations element if there are institutions to append
- Verify
- Verify
> [HOTFIX] Don't send empty affiliations list to Datacite or Crossref

- addons/dataverse/models.py
A long time ago we anonymized fields on the for DataverseFiles by setting the fields to empty strings in the `update` method, this PR removes that special casing.
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3831
> [ENG-3831] Remove special casing from DV permissions

- osf/migrations/0136_preprint_node_divorce.py
- osf/migrations/0137_transfer_preprint_service_permissions.py
- osf/migrations/0162_post_migrate.py
- osf/migrations/0199_draft_node_permissions.py
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3821
> [ENG-3821] Remove post-migrate signals from migration stream

- osf/management/commands/update_institution_sso_email_domain.py
Support institutions that have requested a institutional wide email domain change.
N/A
* How to run the script
```
-h, --help         show this help message and exit
-i ID, --id ID     the institution of which affiliated users' eligible email
is to be updated
-s SRC, --src SRC  the email domain that are eligible for update
-d DST, --dst DST  the email domain that is to be added
```
```
docker-compose run --rm web python3 -m  -i <instn_id> -s <src_domain> -d <dst_domain>
```
* Example local logs for adding `<username>@test.osf.io` to `cos` users who has `<username>@osf.io`.
```
[__main__]  INFO: Action aborted since email [longze@test.osf.io] exists for a different user user [wbg6v]!
[framework.auth.core]  ERROR: OSFUser matching query does not exist.
[__main__]  INFO: Successfully added …
```
> [ENG-3834] Institution SSO Email Domain Update Script

- admin/package.json
- admin/yarn.lock
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3795
> [ENG-3795] Fix Banner Bug

- api/resources/serializers.py
- api_tests/registrations/views/test_registration_resource_list.py
Make Resources filterable by type (and dates)
Add `filterable_fields` to the ResourceSerializer
Add test (plus some cleanup around existing tests)
- Verify
- Verify
> Make Resources filterable by type (and dates)

- scripts/populate_institutions.py
Update the description for `nationalmaglab` as requested.
OSF side update only (i.e. no CAS or Shib). Run the institution population script on both `test` and `prod` after deployment.
```
python3 -m scripts.populate_institutions -e <`prod` or `test`> -i nationalmaglab
```
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-3654
> [ENG-3654] OSFI: update description for `nationalmaglab`

- osf/management/commands/sync_doi_metadata.py
- website/settings/defaults.py
Can't pass model instance to celery task. Pass ID and load instance
- Verify
- Verify
> [Hotfix] DOI sync again

- osf/management/commands/cumulative_plos_metrics.py
- website/settings/defaults.py
Add cron command for gathering requested metric data
- Add `osf.management.commands.cumulative_plos_metrics`
- Update CeleryConfig
N/A
- Add `cumulative_plos_metrics` to `beat_schedule` dict
None Expected
[ENG-3707](https://openscience.atlassian.net/browse/ENG-3707)
> [Hotfix][ENG-3707] PLOS Metrics

- api/base/utils.py
- api/files/annotations.py
- api_tests/nodes/views/test_node_contributors_list.py
- api_tests/preprints/views/test_preprint_contributors_list.py
- api_tests/registrations/views/test_registration_detail.py
- api_tests/users/views/test_user_settings_detail.py
- osf/utils/datetime_aware_jsonfield.py
- osf/utils/fields.py
- osf_tests/test_external_accounts.py
Replaces https://github.com/CenterForOpenScience/osf.io/pull/10038
Part of https://openscience.atlassian.net/browse/ENG-3948
> [Django Upgrade] [ENG-3948] JSONField Change & DRF Updates

- addons/osfstorage/views.py
- api/actions/views.py
- api/base/views.py
- api/draft_registrations/views.py
- api/institutions/views.py
- api/nodes/views.py
- api/preprints/views.py
- api/registrations/views.py
- api/users/views.py
- framework/database/__init__.py
- osf/management/commands/backfill_date_retracted.py
- osf/migrations/0001_initial.py
- osf/models/action.py
- osf/models/base.py
- osf/models/collection.py
- osf/models/contributor.py
- osf/models/files.py
- osf/models/mixins.py
- osf/models/node.py
- osf/models/nodelog.py
- osf/models/osf_grouplog.py
- osf/models/preprint.py
- osf/models/preprintlog.py
- osf/models/request.py
- osf/models/subject.py
- osf_tests/test_include_queryset.py
- requirements.txt
- website/profile/utils.py
- website/project/views/node.py
- website/views.py
Queries compared:
- https://gist.github.com/Johnetordoff/299b621272f5b341d4d15e8737a9d7df
- Verify
- Verify
> [Django Upgrade] [ENG-3948] Replace `django-include` with `prefetch`

- api/base/middleware.py
- api/base/settings/__init__.py
- api_tests/base/test_middleware.py
[https://pypi.org/project/django-cors-headers/](https://pypi.org/project/django-cors-headers/)
- Updates Cors for Django 3 compatibility
- changes requirement.txt to update CORS
- refactors tests and settings
- minor formating changes to provide CORS domains
- Verify
- Verify
> [Django Upgrade] [ENG-3948] More CORS Update

- osf/external/spam/tasks.py
- osf/migrations/0250_add_notabledomain_domainreference.py
- osf/models/__init__.py
- osf/models/notable_domain.py
> [ENG-4038] Add celery task to reclassify resources upon NotableDomain updates

- osf/models/spam.py
- osf_tests/test_notable_domains.py
> De-dupe spam data domain list

- osf/external/spam/tasks.py
- osf/models/notable_domain.py
> Make sure reclassification happens

- website/search/elastic_search.py
Prevent duplicate contribs
- Update queries, serialization
None expected
None known
> [Hotfix] Fix search contributor serialization

- api/collections/serializers.py
- api/search/views.py
> refactor search view's type for FE

- osf/external/spam/tasks.py
- osf_tests/test_notable_domains.py
Improve our domain extraction by fixing the regex and cutting down on false negatives
* Adjust the DOMAIN_REGEX to handle subdomains and urls surrounded by special characters
* Request the http headers for any identified domain as a way to avoid storing non-domains
* Getting just the headers and no body should avoid exposing us to malicious behavior
* This also allows us to check/store redirects from things like link shorteners
- Verify
- Verify
> Improve Domain Extraction

- api/guids/serializers.py
> Fix collections moderation preprint issue

- osf/admin.py
Allow sorting by number of references in the admin app.
- Verify
- Verify
> Sort by num of references

- osf/models/node.py
- osf_tests/test_notable_domains.py
Check Wiki content for Spammy domains when making a Project public (or when `saved_fields` is unspecified, i.e. the management command)
* Modify how `get_spam_fields` handles fields for addons and add support for the Wiki addon
* Tests
- Verify
- Verify
> Extract wiki domains

- api/collections/views.py
- osf/models/collection_submission.py
- osf/models/node.py
- osf/utils/workflows.py
- osf_tests/test_collection_submission.py
…removals due to privacy changes
- Verify
- Verify
> Clean up bugs resubmit behvior for collections submissions etc

- api/collections/permissions.py
- framework/auth/oauth_scopes.py
Improve some edge cases for bugs found during integration testing.
- Verify
- Verify
> Integration Testing bugs

- api/collections/serializers.py
- osf/models/brand.py
- osf/models/node.py
- website/templates/emails/collection_submission_accepted.html.mako
- website/templates/emails/collection_submission_rejected.html.mako
- website/templates/emails/collection_submission_removed_admin.html.mako
- website/templates/emails/collection_submission_removed_moderator.html.mako
- website/templates/emails/collection_submission_removed_private.html.mako
- website/templates/emails/collection_submission_submitted.html.mako
> Clean up collected metadata more

- api/base/urls.py
- api/collections/serializers.py
> add more serializer fields

- api/base/urls.py
- api/collections/serializers.py
> add more serializer fields, fix url namespace duplication

- api/collection_submissions_actions/serializers.py
- api_tests/collection_submissions_actions/views/test_collection_submissions_actions_list.py
> fix collection submission action typo_

- api/providers/serializers.py
- api/providers/urls.py
- api/providers/views.py
- api_tests/providers/collections/views/test_collections_provider_moderator_list.py
- osf_tests/test_schema_responses.py
- osf_tests/utils.py
- Verify
- Verify
https://openscience.atlassian.net/jira/software/c/projects/ENG/issues/ENG-4182
> [ENG-4182] Add moderator collection moderation endpoints

- website/templates/project/project.mako
> fix broken link

- website/project/views/node.py
- website/templates/project/project.mako
> fix more linking behavior and permissions blocking

- website/templates/project/project.mako
> fix project overview page collection submissions indicatior

- website/templates/project/project.mako
> fix project overview page history text

- website/templates/project/project.mako
> fix another broken link for collection submissions

- website/project/views/node.py
> fix broken comments

- osf/models/collection.py
- osf/models/collection_submission.py
- osf/models/provider.py
- osf/utils/notifications.py
- osf_tests/test_collection.py
- osf_tests/test_collection_submission.py
- osf_tests/utils.py
- website/mails/mails.py
- website/reviews/listeners.py
- website/templates/emails/collection_submission_rejected.html.mako
- website/templates/emails/collection_submission_removed_admin.html.mako
> Clean up email

- api/base/serializers.py
> fix serializer typo

- osf/models/collection_submission.py
- osf/utils/notifications.py
> fix email for providerless submissions

- website/search/elastic_search.py
- website/templates/emails/collection_submission_removed_moderator.html.mako
> fix search indexing for collection submission

- osf/migrations/0006_collections_moderation.py
- osf/models/collection_submission.py
- osf/utils/workflows.py
- osf_tests/test_collection_submission.py
- website/notifications/tasks.py
- website/search/elastic_search.py
- website/templates/emails/collection_submission_submitted.html.mako
> Fix collection moderation notifications

- website/templates/emails/collection_submission_submitted.html.mako
- website/templates/project/project.mako
> fix collection count and email template

- osf/models/node.py
> improve spamibility of collections

- osf/models/collection_submission.py
> fix claim link email template behavior for collection submissions

- osf/management/commands/sync_collection_provider_indices.py
> fix management command syncing collection provider indexes

- api/nodes/serializers.py
- api/providers/serializers.py
> fix moderator behavior fpr collection submissions

- osf/external/spam/tasks.py
- osf_tests/test_notable_domains.py
> Follow redirects

- api/actions/views.py
> fix action detail behavior

- api/collections/permissions.py
- osf/models/collection.py
- osf/models/collection_submission.py
> remove granular moderator permissions

- api/collections/permissions.py
> clean-up views code

- api/actions/views.py
- api/collections/permissions.py
- api/nodes/serializers.py
- osf/models/collection_submission.py
> clean up for flake and tests

- api/base/filters.py
- api/search/views.py
- osf/models/node.py
- website/search/elastic_search.py
> add auto-remove state for user triggered privacy change

- osf/models/collection_submission.py
> fix claim link for email

- website/static/js/nodesPrivacy.js
- website/templates/project/project.mako
> update node privacy warning from collections

- website/templates/project/project.mako
> fix project overview page problems

- website/templates/project/project.mako
> fix project collection submission counts

- website/static/js/nodesPrivacy.js
- website/templates/emails/collection_submission_removed_moderator.html.mako
- website/templates/project/project.mako
> fix emails and add to node privacy statement

- website/templates/project/project.mako
> fix project overview page logic

- website/static/js/pages/project-dashboard-page.js
- website/templates/project/project.mako
> clean -up pencil behavior for collection submission status indicator

- osf/utils/workflows.py
> add email submission behavior

- osf/utils/workflows.py
> fix resubmit notifications

- website/static/js/pages/project-dashboard-page.js
> Fix caret flipping

- osf/models/collection_submission.py
- website/templates/emails/collection_submission_accepted.html.mako
- website/templates/emails/collection_submission_rejected.html.mako
- website/templates/emails/collection_submission_removed_admin.html.mako
- website/templates/emails/collection_submission_removed_moderator.html.mako
- website/templates/emails/collection_submission_removed_private.html.mako
- website/templates/emails/collection_submission_submitted.html.mako
> update email templates

- api/providers/serializers.py
> serialize reviews_workflow for collection provider

- osf/models/collection_submission.py
- website/mails/mails.py
> clean up implicit removal behavior

- website/project/views/node.py
- website/static/js/pages/project-dashboard-page.js
- website/templates/project/project.mako
> add auto-resubmit button for collections submissions

- osf/models/node.py
- osf_tests/test_elastic_search.py
- osf_tests/test_node.py
- website/project/tasks.py
- website/project/views/node.py
- website/reviews/listeners.py
- website/static/js/nodesPrivacy.js
> Do code review, add new privacy language

- osf/models/collection_submission.py
- osf/utils/workflows.py
> Collection submissions public

- website/templates/emails/collection_submission_submitted.html.mako
> clean-up email template

- admin/static/js/pages/collection-provider-page.js
> fix collection provider admin app bug

- api/collection_submission_actions/serializers.py
- api_tests/collection_submission_actions/views/test_collection_submissions_actions_list.py
- osf/models/collection_submission.py
- osf/utils/workflows.py
- website/mails/mails.py
- website/templates/emails/collection_submission_cancel.html.mako
> add cancel behavior for collection submissions

- osf/models/node.py
> add implict cancelation for collection submissions

- website/templates/emails/collection_submission_removed_private.html.mako
> Collections moderation email templates

- website/templates/base.mako
- website/templates/nav.mako
- website/templates/project/nodes_privacy.mako
> add fixes for project overview accessibility

- admin/templates/base.html
- website/templates/footer.mako
> Collection moderation ally fixes

- admin/templates/base.html
- website/static/css/style.css
> fix footer for accessibility for collections moderation

- website/static/js/pages/project-dashboard-page.js
- website/templates/project/project.mako
> add cancel button to project overview page

- website/search/elastic_search.py
> fix bug where canceling led to being added to ES

- osf/models/institution.py
> Return placeholder images

- api/providers/serializers.py
- api/providers/urls.py
- api/subscriptions/views.py
> add subscription provider relationship

- api/subscriptions/serializers.py
- api/subscriptions/views.py
> Add type to subscription serializer

- admin/institutions/views.py
- admin/templates/institutions/detail.html
- admin/templates/institutions/list.html
- admin/templates/osf/assetfile_list.html
- osf_tests/test_institution.py
Fix two bugs found during QA testing, for details see:
* https://www.notion.so/cos/Admin-App-Institution-Asset-Files-Page-Filter-Dropdown-at-the-Top-of-the-Page-Does-Not-Work-03b241604d6a457b88c7ff1a4e4dfb5c
* https://www.notion.so/cos/Admin-App-Institutions-List-Page-Still-uses-old-static-logo-files-instead-of-newly-uploaded-Inst-1724da30bffe4c81bf09ec05a1e17812
> [Institution Rework] Fix admin asset and institution filter

- admin/institutions/forms.py
- admin/templates/institutions/node_list.html
Exclude banner_name and logo_name from form fields when creating/updating institutions.
- Verify
- Verify
> [Institution Rework] Exclude banner_name and logo_name from form fields

- osf/management/commands/migrate_user_institution_affiliation.py
- osf/models/user.py
Fix and improve the migration script/command
* Fix the dry-run option
* Fix conflicts for existing affiliations
* Add number of skipped users to output
Follow-up for https://openscience.atlassian.net/browse/ENG-4198
> [Institution Rework] [ENG-4198] Fix/Improve Migration Command

- api/collections/serializers.py
- api/collections/views.py
Allow collection submissions to be sorted by date-modified and name
- ensures serializers fields are annotated in the queryset
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-4238
> [ENG-4238] Allow collection submissions to be sorted by date-modified and name

- api/custom_metadata/serializers.py
- api_tests/metadata_records/test_custom_item_metadata.py
- api_tests/metadata_records/utils.py
- osf/models/metadata.py
- osf_tests/test_registrations.py
- tasks/__init__.py
fix bugs found by QA
- add test for `GuidMetadataRecordManager.copy` and fix it
- fixes "Can’t register a project with metadata"
- add more thorough tests for the `funders` field, fix unexpected validation errors
- allow blank sub-fields
- discard unrecognized sub-fields (normal DRF behavior)
- quietly remove `funders` entries with all-blank validated sub-fields
- fixes "Trying to add a funder with a blank field results in a 400 error stating that the field cannot be blank."
- fixes "Bad key on Funder causes 502 instead of 400"
- Verify
- Verify
> [ENG-4056] fixes: guid metadata bugs

- api/institutions/authentication.py
- api_tests/institutions/views/test_institution_auth.py
Minor tweak SSO exceptions for CAS
Supports: https://github.com/CenterForOpenScience/osf-cas/pull/76
Local Dev QA 
https://openscience.atlassian.net/browse/ENG-4204
> [Institution Rework] [ENG-4204] Part 2: Minor tweak SSO exceptions for CAS

- api/base/serializers.py
- api/subscriptions/serializers.py
> add provider relationship to collection provider subscription

- api/subscriptions/views.py
> Update Collection subscriptions

- api/base/serializers.py
- api/subscriptions/views.py
> make subscription lists provider specific

- api/base/urls.py
- api/collection_subscriptions/urls.py
- api/subscriptions/views.py
> Add top level subscription endpoint

- api/institutions/authentication.py
- website/mails/mails.py
- website/templates/emails/add_sso_email_osf4i.html.mako
- website/templates/emails/duplicate_accounts_sso_osf4i.html.mako
Add email templates and update API `institution/auth`.
N/A
N/A
N/A
N/A
Follow-up for https://openscience.atlassian.net/browse/ENG-4202
> [Institution Rework] [ENG-4202] Follow-up: Add email templates

- website/mails/mails.py
- website/templates/emails/add_sso_email_osf4i.html.mako
- website/templates/emails/duplicate_accounts_sso_osf4i.html.mako
Fix/Improve email templates
Previous PR: https://github.com/CenterForOpenScience/osf.io/pull/10308
Follow-up for https://openscience.atlassian.net/browse/ENG-4202
> [Institution Rework] [ENG-4202] Another follow-up: Fix/Improve email templates

- api/subscriptions/serializers.py
> make self links point to top level domain

- api/custom_metadata/views.py
- framework/auth/oauth_scopes.py
set required scopes for guid-metadata api views, include them in `full_read` and `full_write` composed scopes, as appropriate
- Verify
- Verify
> [fix] set guid-metadata required scopes

- api/actions/serializers.py
- api/base/filters.py
- api/base/serializers.py
- api/base/utils.py
- api/chronos/serializers.py
- api/collections/serializers.py
- api/collections_providers/fields.py
- api/draft_registrations/serializers.py
- api/logs/serializers.py
- api/meetings/serializers.py
- api/nodes/serializers.py
- api/preprints/serializers.py
- api/registrations/serializers.py
- api/requests/serializers.py
- api/sparse/serializers.py
- api/taxonomies/serializers.py
- api/tokens/serializers.py
- api/users/serializers.py
- api_tests/base/test_filters.py
- api_tests/base/test_serializers.py
- api_tests/files/views/test_file_detail.py
in some cases, `api.base.serializers.RelationshipField` requires that the serializer field have the same name as the corresponding model field, which is a problematic entanglement of the api and data layers.
(encountered/fixed while working on #10273  )
digging to fix this bug led to a broader cleanup:
- since `RelationshipField` overrides all meaningful logic in `HyperlinkedIdentityField` (with some extra logic to counteract it), change to simply extend `Field`.
- extending `Field` removes an implicit `source='*'`, which is good because RelationshipField subclasses with `to_internal_value` don't always have to know the name they're bound to on the serializer.
- update `FilterMixin` to:
- remove unnecessary `parse_sparse_fields` call, which allows us to
- use bound serializer fields …
> fix: less surprising RelationshipField

- osf/models/notifications.py
> add fix for notification subscription full clean issue

- api/base/views.py
> correct sorting for user instead of node

- addons/osfstorage/utils.py
- framework/auth/__init__.py
- framework/auth/core.py
- framework/routing/__init__.py
- framework/sessions/__init__.py
- osf/models/external.py
- website/project/views/contributor.py
Follow-up PR, see https://github.com/CenterForOpenScience/osf.io/pull/10358 for why we need to use `get_session()` instead of `LocalProxy(get_session)`.
See diff
N/A
N/A
N/A
N/A
> [Refactor Sessions] Change session usage

- framework/auth/views.py
- framework/sessions/__init__.py
Verify and fix bugs when using realCAS for the following tasks
* See comments in diff.
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4400
> [Refactor Sessions] [ENG-4400] Bug Fixes - realCAS related

- website/static/js/fangorn.js
- website/templates/emails/storage_cap_exceeded_announcement.html.mako
- website/templates/project/addons.mako
- website/templates/project/project.mako
- website/views.py
Replace out-of-date help links for Storage Caps, Github Reauthorization, and the FAQ page
- Verify
- Verify
> Replace out-of-date help links

- addons/osfstorage/views.py
- framework/sessions/__init__.py
- framework/status/__init__.py
- website/app.py
- website/language.py
- website/project/views/contributor.py
- website/routes.py
* Fix the issue where an extra anonymous session with a status message is created when claiming a user.
* In addition, removed the status message which is no longer used.
* Add a new handler using `flask.g` to get/set/use session within request context.
* Remove unused / deprecated code/hooks
See  **Purpose**
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4316
This PR also covers a few local testing ticket
* https://openscience.atlassian.net/browse/ENG-4478
* https://openscience.atlassian.net/browse/ENG-4433
* https://openscience.atlassian.net/browse/ENG-4401
* https://openscience.atlassian.net/browse/ENG-4430
* https://openscience.atlassian.net/browse/ENG-4432
> [Refactor Sessions] [ENG-4316] Final bug fixes (local)

- osf/models/analytics.py
> Only save session in update_counter when the session is not anonymous

- framework/sessions/__init__.py
> Fix view only links

- api/base/settings/defaults.py
> increase maximum number of connections in connection pool

- api/base/utils.py
Avoid extra session query by reusing request-global `request.session`.
- Verify
- Verify
> Use request.session in has_admin_scope

- osf/models/user.py
Fix session/cookie for WB/archiving
See https://centerforopenscience.slack.com/archives/C04KLR892GL/p1681926121439639 for details
* Add `None` check for `UserSessionMap`
* Remove redundant `.save()` by updating session data before `.create()`
Create registration
* No project: upload file during creation
* From project: make sure project has file
After submission, check you email to see that registration is created successfully (i.e no archiving errors)
N/A
N/A
Bug fixes for for https://openscience.atlassian.net/browse/ENG-4316
> [Refactor Sessions] Fix getting cookie from session for waterbutler and archiving

- api/institutions/authentication.py
- api_tests/institutions/views/test_institution_auth.py
- osf/models/institution.py
Selective SSO for YLS
* Tweaked the criteria action to support both Shared SSO and Selective SSO
* Tweaked Selective SSO to handle different criteria
* Added config for YLS
N/A (Will be verified by institution partners on our test server.)
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4434
> [ENG-4434] Selective SSO for YLS (Test Server Only)

- website/project/views/node.py
fix json-ld osfnode metadata -- serialize as double-quoted json (rather than single-quoted python dict)
use the correct osf.metadata tool
- Verify the html of the node dashboard page (`https://osf.example/blarg`) includes a `<script type="application/ld+json">` tag that contains valid json -- in particular: `"` (double quotes) around strings, not `'` (single quote)
- Verify with a glance that the contents of said json are coherent with the info on the web page
> hotfix: serialize json-ld as json

- tests/test_addons.py
- tests/test_preprints.py
> fix some tests

- api/providers/serializers.py
> [ENG-4569] Serialize brand info for preprint provider

- addons/s3/utils.py
> make get bucket names use the correct calling format

- api/addons/serializers.py
- api_tests/nodes/views/test_node_addons.py
> [S3 Improvements] clean-up and revert old changes

- api/addons/serializers.py
> clean-up and revert old changes

- osf/models/metadata.py
Update DOI metadata on GMR update
- Update DOI metadata on GMR update
None expected
None known
> [Hotfix] Update DOI metadata on GMR update

- admin_tests/nodes/test_views.py
- admin_tests/preprints/test_views.py
- api/share/utils.py
- api_tests/providers/test_reindex_provider.py
- api_tests/share/_utils.py
- osf/models/mixins.py
- osf/models/registrations.py
- osf/utils/fields.py
- osf_tests/management_commands/test_recatalog_metadata.py
- osf_tests/metadata/test_osf_gathering.py
- osf_tests/test_elastic_search.py
- osf_tests/test_tag.py
- tests/test_registrations/test_retractions.py
- website/search/elastic_search.py
get tests passing on `feature/search-improvements-2023` branch
- Verify
- Verify
> [fixes] search improvement tests

- addons/s3/utils.py
- osf/management/commands/add_colon_delim_to_s3_buckets.py
- osf_tests/test_s3_folder_migration.py
> S3 move utils

- osf/metadata/osf_gathering.py
- osf_tests/metadata/test_osf_gathering.py
fix error gathering metadata for bookmarked items
exclude bookmark, deleted, and provider-less collections when gathering collection membership
- Verify bookmarked items can show in search
- Verify
> fix: skip bookmarks while gathering metadata

- api/base/serializers.py
Make registrations load properly with ember-osf-web's `basket/barium` release.
Serialize the citation relationship with the proper `type`.
When this and https://github.com/CenterForOpenScience/ember-osf-web/pull/1928 are merged, you should be able to navigate directly to a registration.
https://openscience.atlassian.net/browse/ENG-4627
> [ENG-4627] Fix the citation relationship data

- osf/management/commands/backfill_domain_references.py
Skip objects that don't require inspection
- Ignore QA Nodes/Registrations
- Optionally ignore known spam
- Randomize ordering, to avoid hitting all previously-encountered unprocessable content each run
None expected
> [Hotfix] Spam backfill improvements

- api/share/utils.py
- api_tests/share/_utils.py
- api_tests/share/test_share_node.py
- api_tests/share/test_share_preprint.py
- osf/metadata/osf_gathering.py
- osf/metadata/serializers/turtle.py
- osf_tests/metadata/_utils.py
- osf_tests/metadata/test_osf_gathering.py
- osf_tests/metadata/test_serialized_metadata.py
- guarantee institutional affiliations are filterable/facetable in iri-centric search
- support multi-paragraph text fields in metadata
- ensure back-compatibility for legacy search, in parallel with "new" search
- if there's no ROR or specific institution iri, fall back to the osf institution page url to identify an institution (instead of using a blank node)
- remove buggy `_stabilize_turtle` function (which outputs broken turtle when there's multi-paragraph text)
- update tests to handle unstable turtle
- TODO: better stable rdf serialization (maybe no-context jsonld?)
- restore legacy "sharev2 push", so metadata updates are pushed two ways until we're ready to abandon the old ways
- Verify
- Verify …
> [fix] lil bundle of search/metadata fixes

- api/share/utils.py
- osf/features.yaml
- osf/management/commands/recatalog_metadata.py
- osf/metadata/osf_gathering.py
- osf/metadata/rdfutils.py
- osf/metadata/serializers/datacite/datacite_tree_walker.py
- osf_tests/management_commands/test_recatalog_metadata.py
- osf_tests/metadata/expected_metadata_files/file_basic.datacite.json
- osf_tests/metadata/expected_metadata_files/file_basic.datacite.xml
- osf_tests/metadata/expected_metadata_files/file_full.datacite.json
- osf_tests/metadata/expected_metadata_files/file_full.datacite.xml
- osf_tests/metadata/expected_metadata_files/preprint_basic.datacite.json
- osf_tests/metadata/expected_metadata_files/preprint_basic.datacite.xml
- osf_tests/metadata/expected_metadata_files/preprint_basic.turtle
- osf_tests/metadata/expected_metadata_files/preprint_full.datacite.json
- osf_tests/metadata/expected_metadata_files/preprint_full.datacite.xml
- osf_tests/metadata/expected_metadata_files/preprint_full.turtle
- osf_tests/metadata/expected_metadata_files/project_basic.datacite.json
- osf_tests/metadata/expected_metadata_files/project_basic.datacite.xml
- osf_tests/metadata/expected_metadata_files/project_basic.turtle
- osf_tests/metadata/expected_metadata_files/project_full.datacite.json
- osf_tests/metadata/expected_metadata_files/project_full.datacite.xml
- osf_tests/metadata/expected_metadata_files/project_full.turtle
- osf_tests/metadata/expected_metadata_files/registration_basic.datacite.json
- osf_tests/metadata/expected_metadata_files/registration_basic.datacite.xml
- osf_tests/metadata/expected_metadata_files/registration_basic.turtle
- osf_tests/metadata/expected_metadata_files/registration_full.datacite.json
- osf_tests/metadata/expected_metadata_files/registration_full.datacite.xml
- osf_tests/metadata/expected_metadata_files/registration_full.turtle
- osf_tests/metadata/test_osf_gathering.py
show license and registration template/schema for RegistrationComponent objects in search
if license (`dcterms:rights`) is missing on a node, inherit from parent (recursively)
registration components inherit their registration template/schema
(`dcterms:conformsTo`) from the root (where responses are stored)
- Verify
- Verify
> [fix] missing registration component metadata

- osf/metadata/osf_gathering.py
- osf/metadata/serializers/datacite/datacite_tree_walker.py
- osf_tests/metadata/_utils.py
- osf_tests/metadata/expected_metadata_files/preprint_basic.datacite.json
- osf_tests/metadata/expected_metadata_files/preprint_basic.datacite.xml
- osf_tests/metadata/expected_metadata_files/preprint_basic.turtle
- osf_tests/metadata/expected_metadata_files/preprint_full.datacite.json
- osf_tests/metadata/expected_metadata_files/preprint_full.datacite.xml
- osf_tests/metadata/expected_metadata_files/preprint_full.turtle
- osf_tests/metadata/test_osf_gathering.py
- osf_tests/metadata/test_serialized_metadata.py
avoid errors with how subjects in custom taxonomies are expressed in metadata 
correct a wrong assumption that custom subjects mapped to separate bepress subjects -- include both custom subjects and bepress subjects as separate `skos:Concept`s (instead of combining them into one with the custom name as `skos:altLabel`), and reference the provider as the name of custom subjects' `skos:ConceptScheme`
- Verify
- Verify
> [hotfix] fix custom subject metadata gathering

- osf/metadata/osf_gathering.py
- osf_tests/metadata/expected_metadata_files/preprint_basic.turtle
- osf_tests/metadata/expected_metadata_files/preprint_full.turtle
- osf_tests/metadata/test_osf_gathering.py
avoid duplicate subjects in the search interface and useless information in the metadata record
if a subject from a custom taxonomy has the same name as its bepress synonym, do not include both as distinct subjects (just the bepress one)
- Verify
- Verify
> [hotfix] exclude non-custom custom subjects

- osf/metadata/osf_gathering.py
- osf/metadata/rdfutils.py
- osf/metadata/serializers/datacite/datacite_tree_walker.py
- osf/models/metaschema.py
- osf_tests/metadata/expected_metadata_files/file_full.turtle
- osf_tests/metadata/expected_metadata_files/preprint_full.turtle
- osf_tests/metadata/expected_metadata_files/project_full.turtle
- osf_tests/metadata/expected_metadata_files/registration_full.turtle
- osf_tests/metadata/test_osf_gathering.py
- avoid duplicate registration templates on the search page
- better align metadata with osfmap
- identify registration templates by their earliest version (so all versions are considered equivalent)
- get preprint withdrawal metadata from the preprint's latest accepted withdrawal request (when available)
- for datacite metadata serialization, infer `funderIdentifierType` from the identifier iri
- Verify
- Verify
to be reflected in search, will require running `recatalog_metadata` for registrations -- or (to be more surgical) calling `update_search` on registrations with non-earliest schema
[ENG-4654]
[ENG-4384] …
> [ENG-4654][ENG-4384] metadata-gathering updates

- osf/models/registrations.py
- scripts/approve_registrations.py
- scripts/embargo_registrations.py
- scripts/retract_registrations.py
Add a full rollback partially updated states in Sanctions approval code.
- Change exception handling for sanctions scripts to rollback transactions
- use guids for logging statements.
- add Sentry reporting 
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-4510
> [ENG-4510] Improve exception handling for sanction approvals

- api_tests/files/views/test_file_list.py
fix failing tests
in the api's node file list, files with duplicate `materialized_path` (which is expected in the current `dataverse` addon implementation) may be returned in any order -- update tests to accept that lack of order (instead of failing unpredictably)
- Verify
- Verify
> [hotfix] assume less in dataverse test

- osf/management/commands/recatalog_metadata.py
- osf_tests/management_commands/test_recatalog_metadata.py
allow running `recatalog_metadata` without congesting the "high priority" task queue
update `recatalog_metadata` to specify `queue="low"`
- Verify
- Verify
> [fix/nicety] decongested recatalog

- website/templates/project/project_header.mako
Make it so the files tab opens in a new page.
-minor html change
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3969
> [ENG-3969] Files should open in new tab from project overview page

- addons/boa/static/boaUserConfig.js
- api/base/settings/defaults.py
- website/static/js/fangorn.js
- website/static/js/pages/project-dashboard-page.js
- website/util/rubeus.py
This is a PR from @felliott , cherry-picked from https://github.com/felliott/osf.io/tree/feature/boa-addon
Project overview page needs to know if Boa has been enabled AND configured, so that Fangorn can know whether or not to show the Boa button. 
* Only show button if boa active
* Don't hardcode API url
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4882
> [ENG-4882] Boa button fix and more

- addons/boa/tasks.py
- website/templates/emails/addons_boa_job_complete.html.mako
- website/templates/emails/addons_boa_job_failure.html.mako
Provide file's full path in email notifications
* Provide file's full path in email notifications
* In addition, update signature for `handle_error`
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4895
> [ENG-4895] Provide file's full path in email notifications

- website/static/js/fangorn.js
Fix error toast message on legacy page
* Fix error toast message on legacy page
N/A
N/A
N/A
Legacy part for https://openscience.atlassian.net/browse/ENG-4936
> [ENG-4936] Fix error toast message on legacy page

- addons/boa/tasks.py
Fix URL encoding for output file upload URL
Sentry error: https://staging-sentry.cos.io/cos/osf-back-end-vu/issues/18050/
* Fix URL encoding for output file upload URL
* Catch missed exceptions
N/A
N/A
N/A
N/A
> [ENG-4642] Boa add-on: QA bug fixes - must encode output file name

- addons/base/generic_views.py
- addons/boa/boa_error_code.py
- addons/boa/settings/defaults.py
- addons/boa/tasks.py
- addons/boa/views.py
- website/static/js/fangorn.js
- website/templates/emails/addons_boa_job_failure.html.mako
* Fix bugs revealed by QA testing: [QA Bug Board](https://www.notion.so/cos/bdd75fbff02245939324a0024133c76a?v=f62f5942253f4f688f39452763c8b1c9)
* Partially respond to CR for https://github.com/CenterForOpenScience/osf.io/pull/10469
* Bugs
* CR response
- ~~Unit test~~: lots of unit tests to fix and add, which will come as a separate PR
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4642
> [ENG-4642] Boa Add-on Bug Fixes and Improvement

- addons/boa/tasks.py
- addons/boa/tests/test_tasks.py
- addons/boa/tests/test_views.py
Fix unit tests from https://github.com/CenterForOpenScience/osf.io/pull/10481
> [ENG-4642] Boa Add-on Bug Fixes and Improvement - Unit Tests

- addons/boa/tasks.py
Boa HotFix: Put try/except block to debug a sentry bug in boa tasks
> [Boa HotFix] Put try/except block to debug a sentry bug in boa tasks

- osf/external/cedar/client.py
- website/settings/defaults.py
- website/settings/local-dist.py
Create a python client to make API requests to the CEDAR API to fetch CEDAR Metadata Templates.
See **_Purpose_**
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4850
> [ENG-4850] Cedar client

- api/base/urls.py
- api/cedar_metadata_templates/serializers.py
- api/cedar_metadata_templates/urls.py
- api/cedar_metadata_templates/views.py
Create a new read-only endpoint to return CEDAR schemas to the FE
* Serializer
* URL config
* List view
* Detail view
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4852
> [ENG-4852] Add read-only endpoint for cedar templates

- osf/external/cedar/client.py
- osf/external/cedar/exceptions.py
- osf/management/commands/fetch_cedar_metadata_templates.py
Add error handling to models, client and management command
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-5079
> [ENG-5079] Add error handling to models, client and management command

- admin/base/urls.py
- admin/cedar/forms.py
- admin/cedar/urls.py
- admin/cedar/views.py
- admin/templates/base.html
- admin/templates/cedar/detail.html
- admin/templates/cedar/list.html
- osf/migrations/__init__.py
Cedar template admin configuration feature
* List cedar metadata templates
* View cedar metadata template
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4855
> [ENG-4855] Cedar template admin configuration feature

- api/nodes/serializers.py
- api/subjects/urls.py
- api/subjects/views.py
- api_tests/base/test_serializers.py
add `NodeSerializer.allowed_subjects` relationship, to power the front-end subject picker for resources without providers
- Verify
- Verify
[ENG-4335]
[ENG-4335]: https://openscience.atlassian.net/browse/ENG-4335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-4335] subjects on projects

- Dockerfile
Fixed issue with Python installation.
Updated docker file step.
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5208
> [ENG-5208]: Fix python bootstrapping in docker build

- README-docker-compose.md
Error during command run.
Updated the instructions to add a new command in case of an error during 'Populate preprint, registration, and collection providers' step.
- Verify
- Verify
https://openscience.atlassian.net/jira/software/c/projects/ENG/boards/145?selectedIssue=ENG-5208
>  [ENG 5208]: Updated the instructions in 'Populate preprint, registration, and collection providers' step. 

- admin/management/urls.py
- admin/management/views.py
- admin/templates/management/commands.html
- osf/management/commands/fetch_cedar_metadata_templates.py
- website/settings/defaults.py
Add button for ingesting cedar templates from CEDAR workbench
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4855
> [ENG-4855] Add button for ingesting cedar templates from CEDAR workbench

- api/base/serializers.py
- api/cedar_metadata_records/serializers.py
- api_tests/base/test_serializers.py
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-5224
> [ENG-5224] Cedar Backend Unit Tests - Part 1

- osf/metadata/osf_gathering.py
- osf/models/cedar_metadata.py
- osf_tests/factories.py
- osf_tests/metadata/test_osf_gathering.py
> [ENG-4854] Gather cedar template

- admin/templates/cedar/list.html
> Add cedar template version number to admin app list view

- api/files/serializers.py
- api/files/urls.py
- api/files/views.py
Fix file cedar metadata records relationship, which address this [bug](https://www.notion.so/cos/Link-for-the-cedar_metadata_records-relationship-on-a-file-returns-no-cedar-records-966560ab47ac42cfa5c8bf9e6d4db9be).
N/A
N/A
N/A
N/A
N/A
> [Cedar] Fix file cedar metadata records relationship

- api/cedar_metadata_records/permissions.py
- api/cedar_metadata_records/serializers.py
- api/cedar_metadata_records/utils.py
- api/cedar_metadata_records/views.py
- osf/models/cedar_metadata.py
Fix Permission, here is the [bug notion](https://www.notion.so/cos/Permission-Issue-Backend-a6c9546a9174412bb191f1d5d37d3bbc)
Cherry-picked from https://github.com/CenterForOpenScience/osf.io/pull/10534/commits/2fed8d5d2ead5e794d2813699828ad251279e285, https://github.com/CenterForOpenScience/osf.io/pull/10534/commits/28be6a16701ff37eb78b2da4da35471b1e9be2bb and https://github.com/CenterForOpenScience/osf.io/pull/10534/commits/386043279e459c3472b7d045140f9e22997acbdc in https://github.com/CenterForOpenScience/osf.io/pull/10534
N/A
N/A
N/A
N/A
> [Cedar] Bug-fix: Fix Permission

- website/views.py
> Add some more rules to route `<registration_guid>/metadata/*` and `<node_guid>/metadata/*` to the ember app.

- .github/actions/start-build/action.yml
- .travis.yml
- addons/owncloud/models.py
- addons/zotero/provider.py
- api_tests/registrations/views/test_registration_list.py
- scripts/remove_qa_test_items_from_elastic_and_share.py
- scripts/tests/test_user_system_tag_normalization.py
- website/citations/providers.py
Get rid of all syntax errors when upgrading to python 3.10
Fixed syntax errors
[ENG-5214](https://openscience.atlassian.net/browse/ENG-5214)
[ENG-5214]: https://openscience.atlassian.net/browse/ENG-5214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5214] Update core OSF syntax for py3.10

- addons/wiki/models.py
- addons/wiki/settings/defaults.py
- requirements.txt
- tests/test_oauth.py
Update python-dateutil
replaced datetime.utcfromtimestamp
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5367
> [ENG-5367] Dep-group: datetime

- api/metrics/urls.py
- api/metrics/views.py
- api_tests/base/test_views.py
- osf/metrics/README.md
- osf/metrics/openapi.py
- requirements.txt
document `osf.metrics` api and data models
- add `osf/metrics/README.md` (for reading coders)
- add `/_/metrics/openapi.json` (for api users -- can feed into postman, redoc, etc)
- see [example json response](https://github.com/CenterForOpenScience/osf.io/files/14453603/local_osfmetrics_openapi.json)
- Verify
- Verify
NOTE: added `dataclasses` as dependency, because i wrote a bunch of code using dataclasses before i realized osf is still on a pre-dataclasses version of python
[ENG-5282]
[ENG-5282]: https://openscience.atlassian.net/browse/ENG-5282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> [ENG-5282] metrics api docs

- addons/wiki/models.py
- admin/collection_providers/forms.py
- admin/preprint_providers/forms.py
- admin/registration_providers/forms.py
- api/comments/serializers.py
- framework/forms/utils.py
- framework/utils.py
- osf/utils/sanitize.py
- requirements.txt
- website/archiver/utils.py
- website/search/views.py
- website/settings/defaults.py
- website/util/sanitize.py
Bump bleach  and Markupsafe to the newest version
Specified Markupsafe in requirements.txt, fixed bleach usages to work with newest 
Css sanitization may be broken
[ENG-5335](https://openscience.atlassian.net/browse/ENG-5335)
[ENG-5335]: https://openscience.atlassian.net/browse/ENG-5335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5335] Dep-group: html sanitization

- admin/base/settings/defaults.py
- admin/base/settings/local-dist.py
- framework/email/tasks.py
- requirements.txt
Bumped dependency group - email (sendgrid and mailchimp3)
Update mail related dependencies
Adapted code which involved sendgrid to new library version, adapted django settings to django-sendgrid-v5
[ENG-5338](https://openscience.atlassian.net/browse/ENG-5338)
[ENG-5338]: https://openscience.atlassian.net/browse/ENG-5338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5338 ] Bumped dependency group - email

- addons/base/utils.py
- addons/bitbucket/models.py
- addons/figshare/models.py
- admin_tests/mixins/providers.py
- framework/auth/decorators.py
- framework/auth/forms.py
- framework/auth/views.py
- framework/database/__init__.py
- framework/flask/__init__.py
- framework/forms/__init__.py
- framework/routing/__init__.py
- osf/utils/tokens/handlers.py
- requirements.txt
- tests/base.py
- tests/framework_tests/test_routing.py
- tests/test_auth.py
- tests/test_metadata.py
- tests/test_tokens.py
- tests/test_webtests.py
- website/app.py
- website/notifications/events/files.py
- website/project/forms.py
- website/routes.py
- website/static/css/my-projects.css
To upgrade Flask, enforce PEP8 compliance, and resolve TestApp issues.
- Updated Flask;
- Formatting according to Pep8;
- Fixed errors with TestApp;
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5331
> [ENG-5331] Dep-group: Flask / Werkzeug / Mako / Jinja

- osf/metadata/gather/focus.py
- requirements.txt
- requirements/dev.txt
Python libs upgrade
bumped formatting deps 
[ENG-5366](https://openscience.atlassian.net/browse/ENG-5366)
[ENG-5366]: https://openscience.atlassian.net/browse/ENG-5366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5366] Dep-group: formatting

- osf/models/identifiers.py
- tests/test_preprints.py
- website/preprints/tasks.py
Fix issues where DOI creation isn't automatic on Preprint publication.
- removes check on stopping `request_identifier_update` from not creating new DOIs
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5449
> [Hotfix][ENG-5449] Fix Crossref DOIS

- api/base/views.py
- osf/management/commands/migrate_registration_responses.py
- osf/management/commands/restore_deleted_root_folders.py
- osf/models/node.py
- requirements.txt
- requirements/dev.txt
- Сhanges purposed to update Django and related modules, with updates to django-bulk-update, django-celery-beat, and djangorestframework-csv;
- Updated the django-bulk-update module by replacing  bulk_update module with a built-in .bulk_update;
- Updated the versions of two modules django-celery-beat and djangorestframework-csv in requirements.txt;
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5330
> [ENG-5330] Dep-group: Django-*

- addons/base/tests/serializers.py
- addons/gitlab/api.py
- addons/osfstorage/tests/test_views.py
- addons/wiki/tests/test_wiki.py
- admin/base/settings/local-dist.py
- admin_tests/meetings/test_views.py
- framework/flask/__init__.py
- osf/utils/tokens/handlers.py
- requirements/dev.txt
- tests/base.py
- tests/framework_tests/test_routing.py
- tests/test_auth.py
- tests/test_utils.py
- tests/test_views.py
Python dependencies and libs upgrade
Bumped dev dependencies
- Verify
- Verify
[ENG-5336](https://openscience.atlassian.net/browse/ENG-5336)
[ENG-5336]: https://openscience.atlassian.net/browse/ENG-5336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG 5336] Dep-group: dev modules (flake, etc)

- admin/collection_providers/forms.py
- admin/preprint_providers/forms.py
- admin/registration_providers/forms.py
Fix Styling for Advisory Board section across Admin App interfaces
Modified HTML sanitization in registration, collection, and preprint provider forms to allow color styles, ensuring styling appears as expected when published.
https://openscience.atlassian.net/browse/ENG-5429
> ENG 5429 Fix Styling for Advisory Board Section Across Admin App Interfaces

- framework/auth/utils.py
- framework/routing/__init__.py
- osf/utils/names.py
- requirements.txt
- tests/test_utils.py
- website/conferences/message.py
- website/routes.py
These changes update dependencies for better performance and add new features for enhanced geolocation and image processing.
- **Removed** python-magic
- **Replaced** maxminddb-geolite2 with geoip2
- **Switched** from Pystache to Mako for better template rendering performance
- **Added** a new parameter in the nameparser module for specifying string encoding, enhancing data handling flexibility
- **Updated** the transitions module to its latest version for access to new features and improvements
- **Added** new dependencies: Pillow for image processing and geoip2 for enhanced geolocation capabilities
- Verify
- Verify
Any concerns/considerations/questions that development …
> [ENG-5340] Dep-group: catchall

- addons/github/requirements.txt
- framework/celery_tasks/handlers.py
- framework/postcommit_tasks/handlers.py
- framework/transactions/handlers.py
- osf_tests/conftest.py
- requirements/dev.txt
- tests/base.py
- tests/identifiers/conftest.py
Fix import of non existing attribute from flask
Replaced `_app_ctx_stack` and `_request_ctx_stack` with modern alternatives
- Verify
- Verify
[ENG-5456](https://openscience.atlassian.net/browse/ENG-5456)
[ENG-5456]: https://openscience.atlassian.net/browse/ENG-5456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5456] Fix flask import issue

- addons/base/views.py
- addons/dropbox/tests/test_views.py
- addons/owncloud/views.py
- admin/users/views.py
- admin_tests/users/test_views.py
- api/base/serializers.py
- api/base/utils.py
- api/files/serializers.py
- api/guids/views.py
- api_tests/draft_nodes/views/test_draft_node_files_lists.py
- api_tests/nodes/views/test_node_files_list.py
- api_tests/wikis/views/test_wiki_detail.py
- api_tests/wikis/views/test_wiki_version_detail.py
- framework/auth/campaigns.py
- framework/auth/cas.py
- framework/auth/views.py
- framework/flask/__init__.py
- framework/sessions/__init__.py
- requirements.txt
- tests/test_addons.py
- tests/test_cas_authentication.py
- tests/test_conferences.py
- tests/test_preprints.py
- website/identifiers/clients/crossref.py
- website/notifications/events/files.py
- website/util/client.py
- website/views.py
Python and libs upgrade
Updated furl usage to be more modern
- Verify
- Verify
[ENG-5332](https://openscience.atlassian.net/browse/ENG-5332)
[ENG-5332]: https://openscience.atlassian.net/browse/ENG-5332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5332] Dep-group: url encoding

- osf/features.yaml
- website/profile/views.py
- website/project/views/node.py
Allows us to feature flag the new addon's changes by creating waffle flags.
- Add `ENABLE_GV` flag to `features.yaml` switched off.
- Make `ENABLE_GV` responsible for users settings addon page and node settings addon page.
- TODO: FIles widget flipping?
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5144
> [WIP][ENG-5144] Add Waffling for GV

- addons/wiki/requirements.txt
- addons/wiki/utils.py
- admin/base/settings/defaults.py
- api/base/middleware.py
- api/base/settings/defaults.py
- conftest.py
- framework/celery_tasks/__init__.py
- framework/celery_tasks/utils.py
- framework/sentry/__init__.py
- requirements.txt
- requirements/release.txt
- tests/base.py
- website/project/utils.py
- website/search_migration/migrate.py
- **Update** dependencies for security and bug fixes.
- **Upgrade** modules for compatibility and new features.
Improve readability.
- **remove** ssl_cert_reqs and add tlsAllowInvalidCertificates;
- **bump** versions modules in requirements.txt;
- **replace** the elasticsearch2 module with elasticsearch;
- **replace** the raven module with sentry_sdk;
- **remove** raven from the requirements.txt; 
-  **add** modules: elasticsearch_dsl, newrelic, google-auth to the requireme…
…nts.txt; 
- **add** space;
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5368
> [ENG-5368]  Dep-group: services

- api/caching/tasks.py
- requirements.txt
- requirements/dev.txt
- tasks/__init__.py
Python and dependencies upgrade
Bumped celery, kombu and their helper libs 
- Verify
- Verify
[ENG-5329](https://openscience.atlassian.net/browse/ENG-5329)
[ENG-5329]: https://openscience.atlassian.net/browse/ENG-5329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5329] Phase 2: Dep-group: Celery / Kombu

- osf/management/commands/migrate_registration_responses.py
- osf/metadata/serializers/turtle.py
- osf/models/node.py
- osf/utils/sanitize.py
- osf_tests/factories.py
- osf_tests/test_node_license.py
- osf_tests/test_registration_bulk_upload_parser.py
- osf_tests/test_session.py
- requirements/dev.txt
- tasks/__init__.py
- tests/base.py
- website/settings/defaults.py
- website/settings/local-travis.py
Python and libraries upgrade
Upgraded test dependencies, got tests to launch, fixed small amount of tests
- Verify
- Verify
[ENG-5327](https://openscience.atlassian.net/browse/ENG-5327)
[ENG-5327]: https://openscience.atlassian.net/browse/ENG-5327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5327] bump test dependencies

- addons/base/tests/views.py
- website/oauth/views.py
- website/settings/defaults.py
- website/settings/local-dist.py
> [ENG-5141] Conditionally rerouting oauth callback to gravyvalet

- addons/github/tests/utils.py
- api/base/middleware.py
- framework/auth/core.py
- framework/auth/views.py
- osf/metrics/openapi.py
- osf/models/external.py
- osf_tests/metadata/test_osf_gathering.py
- osf_tests/metadata/test_serialized_metadata.py
Fix infinite recursion when working with transitions in the beginning, but in fact - fix everything that slipped through rebase
Fixed datetime.UTC usage and other minor fixes
- Verify
- Verify
[ENG-5522](https://openscience.atlassian.net/browse/ENG-5522)
[ENG-5522]: https://openscience.atlassian.net/browse/ENG-5522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Eng-5522] Infinite recursion when working with transitions

- api_tests/share/test_share_node.py
Fix share interaction issues
Skipped tests which raised that issue, as of chages with celery 5.0, and because they are more of integration tests
- Verify
- Verify
[ENG-5526](https://openscience.atlassian.net/browse/ENG-5526)
[ENG-5526]: https://openscience.atlassian.net/browse/ENG-5526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5526] Phase 3: Share interaction errors

- osf_tests/test_search_views.py
Fix TestSearchViewsfailing with ambiguous results
Fixed tests in CI, maked them to speak locally as for some reason local environment setup for this test is broken even for old version of project
- Verify
- Verify
[ENG-5527](https://openscience.atlassian.net/browse/ENG-5527)
[ENG-5527]: https://openscience.atlassian.net/browse/ENG-5527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5527] Phase 3: TestSearchViews Ambiguous results

- addons/osfstorage/tests/test_views.py
- framework/sessions/__init__.py
- tests/test_addons.py
- tests/test_views.py
Fixed tests: `test_external_login_confirm_email_get_duped_id, test_external_login_confirm_email_get_duping_id, test_download_file_with_token, test_download_file_with_token, test_external_login_confirm_email_get_link
`
- **fix** errors for test_external_login_confirm_email_get_duped_id and test_external_login_confirm_email_get_duping_id tests;
- **fix** errors for test_download_file_with_token and test_download_file_with_token;
- **fix** status code error for test_external_login_confirm_email_get_link test;
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5553 …
> [ENG-5553][ENG-5589] Fix redirect issue from email link and mock_get_client error

- tests/test_addons.py
Fix `test_auth_bad_bearer_token`
Changed status code in test to pre python upgrade one
- Verify
- Verify
[ENG-5604](https://openscience.atlassian.net/browse/ENG-5604)
[ENG-5604]: https://openscience.atlassian.net/browse/ENG-5604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5604] Phase 3: Fix test_auth_bad_bearer_token

- api/preprints/serializers.py
- api/preprints/urls.py
- api/preprints/views.py
> [WIP] Add self link and view for preprint subjects relationship

- addons/base/views.py
Fix Draft registration problems on staging.
- Verify
- Verify
https://staging-sentry.cos.io/cos/osf-back-end-vu/issues/19547/
> add DraftRegistration file permission test

- api/base/utils.py
- api_tests/users/views/test_user_settings_detail.py
- **fixing** tests that had an error with an incorrect status code after upgrading Django to a higher version;
- **add** a commas; 
- **add** space according to pep8; 
- **rewrote** the is_truthy and is_falsy functions;
- **fix** test_update_two_factor_enabled test;
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-5637
https://openscience.atlassian.net/browse/ENG-5638
> [ENG-5637][ENG-5638] Fix invalid status codes

- docker-compose.yml
Fix devenv on python 3.12
Fixed requirements container in `docker-compose.yml`
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5748
> [ENG-5748] Broken devenv on python3.12

- admin_tests/users/test_views.py
- api_tests/providers/test_reindex_provider.py
- osf_tests/test_archiver.py
- tests/test_tokens.py
- tests/test_views.py
Investigate and fix pre-upgrade broken/incorrect unit tests revealed by Python 3.12 upgrade
Fixed tests broken by python 3.12 upgrade
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-5696
> [ENG-5696] Investigate pre-upgrade broken/incorrect unit tests revealed by Python 3.12 upgrade

- osf_tests/test_archiver.py
Fix osf_tests/test_archiver.py::TestArchiverTasks.test_archive_addon
Fixed osf_tests/test_archiver.py::TestArchiverTasks.test_archive_addon according to new behaviour
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5739
> [ENG-5739] Phase 4: Fix osf_tests/test_archiver.py::TestArchiverTasks.test_archive_addon

- tests/test_registrations/test_embargoes.py
Fix test_GET_approve_with_valid_token_redirects
- Fixed LegacyRegistrationEmbargoApprovalDisapprovalViewsTestCase.test_GET_approve_with_valid_token_redirects: by asserting that there weren't any redirects 
- Fixed RegistrationEmbargoApprovalDisapprovalViewsTestCase.test_GET_approve_with_valid_token_redirects by changing patch of redirect and fixing assert value.
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5746
> [ENG-5746] Phase 4: Fix RegistrationEmbargoApprovalDisapprovalViewsTestCase.test_GET_approve_with_valid_token_redirects

- addons/s3/utils.py
- osf/models/external.py
Fix Box addon setup
Forced passing `client_id` to `fetch_token` request of `OAuth2Session`
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5796
> [Eng-5796] Fixed Box addon setup

- api/nodes/serializers.py
- api/nodes/views.py
- api_tests/draft_registrations/views/test_draft_registration_relationship_institutions.py
- api_tests/nodes/views/test_node_relationship_institutions.py
To resolve the bug in the create new project modal that incorrectly raises an exception.
Removed the unneeded exception.
<https://openscience.atlassian.net/browse/ENG-4080>
> Fix RelationshipPostMakesNoChanges exception in project creation

- api/metrics/serializers.py
- osf/metrics/counted_usage.py
Fix project metrics not working
Passed `PageViewInfo` object when creating `CountedAuthUsage` record instead of dict with attributes
- Verify
- Verify
[ENG-5772](https://openscience.atlassian.net/browse/ENG-5772)
[ENG-5772]: https://openscience.atlassian.net/browse/ENG-5772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-5772] Phase 4: Project metrics not working

- addons/base/models.py
- api/nodes/views.py
- osf/external/gravy_valet/translations.py
- tests/base.py
Make StorageProvidersList play nice with EphemeralNodeSettings
* Replace existing `NodeStorageProvider` object with a dataclass that knows how to populate its fields from a NodeSettings object (if provided)
* Add `display_name` property to legacy `BaseNodeSettings` to support GV behavior of distinguishing addon name from provider name
* Update `Ephemeral[Node|User]Settings` to receive the `gv_data` as an init param and to grab information from that data
*  Add required properties to `Ephemeral[Node|User]Settings` to support existing workflows.
- Verify
- Verify
> Gv integration fixes

- framework/celery_tasks/__init__.py
Dummy PR to trigger CI
- Verify
- Verify
> [WIP] Feature/celery config

- admin/preprints/views.py
So reason state change can't happen.
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5848
> [ENG-5848] Add button to admin to move preprint from initial to pending

- Dockerfile
- addons/dataverse/requirements.txt
- addons/mendeley/requirements.txt
- api/ia/views.py
- docker-compose-dist-arm64.override.yml
- docker-compose-dist.override.yml
- docker-compose.yml
- osf/metrics/reports.py
- poetry.lock
- pyproject.toml
- requirements.txt
Bring feature branch up-to-date with recent release fixes - 2/?
https://openscience.atlassian.net/browse/ENG-6067
> [ENG-6067] Update feature/preprints-affiliations

- api/preprints/serializers.py
- api_tests/preprints/views/test_preprint_detail.py
- api_tests/preprints/views/test_preprint_list.py
> Fix Self Link for Preprint Affiliated Institutions

- framework/auth/views.py
Stage3 Testing Resend Confirmation Email
Revert resend confirmation to synchronous version
> Revert resend confirmation to synchronous version

- framework/auth/views.py
- framework/postcommit_tasks/handlers.py
Reverts CenterForOpenScience/osf.io#10724
> Revert "Add logging to post-commit handlers"

- osf/metrics/reporters/institution_summary_monthly.py
Currently the `get_active_monthly_user_count` method of the summary reporting is a bottleneck that causes large institutions with many users to crash in the middle of reporting. This PR aims to improve the performance of that query by using subqueries instead of joining logs.
- The `get_active_monthly_user_count` now works differently by checking the Outter id of the user in two subqueries.
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6124
> [ENG-6124] Improve monthly active query

- admin/management/views.py
This adds for more validation for Monthly Reporters Go, button on the admin app to prevent users from creating monthly reports in current/incomplete/future months. This will alert the user they made a mistake 
- adds more conditions to admin view `MonthlyReportersGo`
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6324
> [ENG-6324] Fix Admin behavior for creating monthly reports

- osf/management/commands/migrate_preprint_affiliation.py
- osf_tests/management_commands/test_migrate_preprint_affiliations.py
After conducting our opt-out survey we now have our list of users to exclude from Preprint affilation, now we can migrate the affiliations for the rest of them.
- add migrate preprint affiliation management command 
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6364
> [ENG-6364] Migrate Preprint Affilations

- osf/metrics/reporters/private_spam_metrics.py
- osf/metrics/reports.py
Follow-up to #10783 
- Add corresponding MetricsReport
None Expected
The `sync_metrics` management command will need to be ran.
Link to JIRA ticket, if applicable e.g. https://openscience.atlassian.net/browse/ENG-4438
> [ENG-4438] Add PrivateSpamMetricsReport

- osf/management/commands/change_node_region.py
Allow for the changing of storage region on Nodes, Registrations on a limited basis.
- Add `change_node_region` script
- Manually verified nodes, registrations, with multiple versions, and multiple files attached to schemaresponses, on staging2
None expected
https://openscience.atlassian.net/browse/ENG-5242
> [ENG-5242] Add script to change a Node's Region 

- osf/external/gravy_valet/request_helpers.py
- osf/external/gravy_valet/translations.py
Fix forking after GV is being enabled
added before_fork and after_fork to EphemeralNodeSettings
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6543
> [ENG-6543] Fix forking

- api_tests/metrics/test_counted_usage.py
- osf/metrics/counted_usage.py
prevent counted-usages with different `action_labels` from overwriting each other
deduplicate only when `action_labels` match exactly
- Verify
- Verify
> [ENG-6506] fix: counted-usage clobbers

- addons/base/views.py
> [ENG-6540] Check and see if the provider is osfstorage

- osf/external/gravy_valet/request_helpers.py
- osf/external/gravy_valet/translations.py
- osf_tests/external/gravy_valet/gv_fakes.py
Fix removing contributors
- Verify
- Verify
[ENG-6552](https://openscience.atlassian.net/browse/ENG-6552)
[ENG-6552]: https://openscience.atlassian.net/browse/ENG-6552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6552] Fix removing contributors

- osf/management/commands/check_crossref_dois.py
As Celery task for creating DOIs could not be executed properly and crushes on local environment, there is a need to create a function to bypass sending data to CrossRef and create DOIs locally.
Thats why created a helper method to create DOIs locally. 
See above
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6443
> [ENG-6443] Created method for saving DOI locally bypassing CrossRef check

- osf/external/gravy_valet/translations.py
Fix creating registrations
added after_regiter hook for 
- Verify
- Verify
> [ENG-6539] fixed EphemeralNodeSettings to have after_register hook

- api/preprints/views.py
- osf/models/base.py
- osf/models/preprint.py
Versioned GUID routing update
Fix guid version check error
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6649
> [ENG-6649] Versioned GUID routing update

- api/preprints/serializers.py
- osf/models/preprint.py
* Added field is_latest_version to PreprintSerializer
* Created a method to check if the preprint version is the latest one
See **_Purpose_**
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6467
> [ENG-6467] Added property is_latest_version and created a method to check latest version

- api/preprints/views.py
- osf/external/spam/tasks.py
- osf/models/__init__.py
- osf/models/base.py
- osf/models/spam.py
Reject preprint update for old versions
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6458
> [ENG-6458] Reject preprint update for old versions

- osf/models/preprint.py
- Update the _is_rejected_ field in the GuidVersionsThrough model after a preprint has been rejected
- Make a GUID link to the latest published preprints (including withdrawn)
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6644
https://openscience.atlassian.net/browse/ENG-6680
> [ENG-6644][ENG-6680] Rejected version number and GUID referent

- addons/osfstorage/decorators.py
- osf_tests/factories.py
- osf_tests/test_guid.py
- website/views.py
Fix failed tests for new Versioned GUID change - Part 1
Add new factories
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6558
> [ENG-6558] Fix failed tests for new Versioned GUID change - Part 1

- api/preprints/serializers.py
- scripts/generate_sitemap.py
Changed how sitemap generator work so include latest version
Changed how sitemap generator work so include latest version
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6477
> [ENG-6477] Feature/update sitemap generator

- osf/external/gravy_valet/translations.py
> Fix citation addons

- api/institutions/serializers.py
- api_tests/institutions/views/test_institution_summary_metrics.py
- api_tests/institutions/views/test_institution_user_metric_list.py
Follow-up bug-fixes for the Dashboard project
- Add `report_yearmonth` to Institutional Metrics Serializers
None expected
> [Feature] Dashboard B&I

- osf/external/gravy_valet/request_helpers.py
- website/citations/views.py
> Invoke list_collection_items if there is a list_id

- api/preprints/views.py
Fix PreprintOldVersionsImmutableMixin
TBD
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6720
> [ENG-6720] Fixed PreprintOldVersionsImmutableMixin

- addons/osfstorage/listeners.py
Fix new `website` test failures
Fix new `website` tests
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6727
> [ENG-6727] Fix new `website` test failures

- osf_tests/factories.py
- tests/identifiers/test_crossref.py
Add test for versioned DOI and crossref_metadata
Add test for versioned DOI and crossref_metadata
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6620
Part of https://openscience.atlassian.net/browse/ENG-6732
> [ENG-6620] [ENG-6732] Added tests for versioned DOI and CrossRef metadata + Update Preprint Factory

- website/project/views/node.py
> [ENG-6728] Fix root folder

- framework/email/tasks.py
Unfortunately we got two sentry messages with our sendgrid user messaging feature
1. For Node Requests when the email works, it sends a 202 and our sentry doesn't like that: https://staging-sentry2.cos.io/organizations/cos/issues/1778/?query=is%3Aunresolved&referrer=issue-stream&stream_index=3 small problem.
2. https://staging-sentry2.cos.io/organizations/cos/issues/1782/?query=is%3Aunresolved&referrer=issue-stream&stream_index=0 The payload sent to sendgrid 400s persumalble because the Mail object isn't set up correctly.
- add 202 to acceptable response codes
- change sendgrid email object formulation.
- Verify
- Verify
Any concerns/considerations/questions that development …
> [BUG][WIP] Fix sendgrid email 400s and 202s reporting to sentry

- osf_tests/test_preprint_factory.py
Add tests to check if PreprintFactory work properly
Create new file test_preprint_factory.py
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6701
> [ENG-6701] - Add tests for Preprint factory 

- osf/models/preprint.py
Fixed preprint version creation due to recent merge/refactor
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6767
> [ENG-6767] Fixed preprint version creation

- api/preprints/serializers.py
- api/preprints/views.py
- osf/models/base.py
- osf/models/preprint.py
Added sentry logs to critical pieces
N/A
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6703
> [ENG-6703] Add sentry logs to critical pieces

- addons/osfstorage/views.py
- api/preprints/views.py
- api/share/utils.py
- osf/models/base.py
SHARE surfaces only the most recent DOI version.
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6478
> [ENG-6478] SHARE update for versioned preprints

- api/base/filters.py
Update `FilterMixin` for versioned guid (a.k.a "Check and fix api_2 tests")
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6646
> [ENG-6646] Update FilterMixin for versioned guid

- api/base/filters.py
- api/nodes/views.py
- website/project/views/node.py
Include only latest preprint version in project`s supplements
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6761
> [ENG-6761] Include only latest preprint version to project`s supplements

- api_tests/share/_utils.py
Merge https://github.com/CenterForOpenScience/osf.io/pull/10864 first
Fix SHARE tests
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6722
> [ENG-6722] Updated SHARE tests according to the SHARE update 

- api/collections/views.py
Add only the latest preprint version to collections
N/A
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6765
> [ENG-6765] Latest version of preprint in collections

- osf/models/preprint.py
Fix preprint subjects
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6791
> [ENG-6791] Fixed preprint subjects 

- api/base/filters.py
- api/collections/views.py
- api_tests/nodes/views/test_node_preprints.py
- api_tests/preprints/views/test_preprint_list_mixin.py
To fix existing tests after projects/collection fix
N/A
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6787
> [ENG-6787] Fixed tests, fixed issues

- website/views.py
> [ENG-6343] Direct all files page request to the ember app

- osf/external/gravy_valet/request_helpers.py
Fixed forking for citation adddons
- Verify
- Verify
[ENG-6798](https://openscience.atlassian.net/browse/ENG-6798)
[ENG-6798]: https://openscience.atlassian.net/browse/ENG-6798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-6798] BE: Citation Addons: Forking the project doesn't transfer authorization to forked project

- api/nodes/views.py
Converted all node id's in NodeAddonList to str to fix the view
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6580
> [ENG-6580] BE/Platform: Projects Settings Page: Unable to retrieve redirect link settings

- addons/base/views.py
- addons/osfstorage/utils.py
Fix preprints related metrics
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6764
> [ENG-6764] Fix preprints related metrics

- osf_tests/factories.py
- tests/test_preprints.py
Add new tests for preprint moderation states
https://openscience.atlassian.net/browse/ENG-6693?atlOrigin=eyJpIjoiOTBhN2U1MTg5M2U0NGI1YjgxNGRkZTYwYTUzYTMxOWYiLCJwIjoiaiJ9
> [ENG-6693] Add new tests for preprint moderation states

- api/base/utils.py
- api/preprints/permissions.py
- api/preprints/urls.py
- osf/models/base.py
- osf/models/preprint.py
Add Docstrings & comments
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6783
> [ENG-6783] Add Docstrings & comments - 1st pass

- addons/forward/static/node-cfg.js
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6819
> [ENG-6819] Fix redirect link settings not appearing 

- tests/framework_tests/test_email.py
Clean-up mock for new behavior, improve sendgrid mocking methods.
- Changes mocks and behavior for two tests of sendgrid
- Verify
- Verify
N/A
> add fix to email mocking, test for catagories

- osf/external/gravy_valet/request_helpers.py
- osf/external/gravy_valet/translations.py
- osf_tests/external/gravy_valet/gv_fakes.py
- osf_tests/test_gv_utils.py
- website/project/views/node.py
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6831
> [ENG-6831] Remove _LegacyConfigsForWBKey from osf.io

- website/templates/emails/digest.html.mako
Update digest notification template 
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6870
> [ENG-6870] Fix digest notification template 

- osf/models/preprint.py
Fix the “create version” failure by bypassing the node permission requirement ONLY during version creation.
Added bypass for the node permission requirement during version creation
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6886
> [ENG-6886] Bypass for the node permission requirement during version creation

- tests/identifiers/test_crossref.py
Update tests for recent CrossRef Metadata upload fix
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6988
> [ENG-6988] Update tests for recent CrossRef Metadata upload fix

- osf/models/preprint.py
Bug-fix follow-up: orphaned (unfinished) version shows up in the version list drop down
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-7005
> [ENG-7005] Bug-fix follow-up: orphaned (unfinished) version shows up in the version list drop down

- tests/identifiers/test_crossref.py
- website/identifiers/clients/crossref.py
Follow-up fix for DOI CrossRef metadata upload failure
N/A
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-7008
> [ENG-7008] Follow-up fix for DOI CrossRef metadata upload failure

- api/base/utils.py
- api_tests/nodes/views/test_node_preprints.py
Project PR CR
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6706
> [ENG-6706] Project PR CR Response

- osf/models/preprint.py
- website/identifiers/clients/crossref.py
Don`t include rejected preprints to CrossRef metadata
N/A
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6989
> [ENG-6989] Don`t include rejected preprints to CrossRef metadata

- tests/test_preprints.py
> Fix import

- osf/metrics/preprint_metrics.py
Fix to enable API serializer to combine preprint metrics for Versioned GUID and Base GUID
Changed the logic of the method for searching metrics.
TBD
TBD
TBD
https://openscience.atlassian.net/browse/ENG-7086
> fix for metrics

- api/requests/serializers.py
- api_tests/requests/views/test_node_request_institutional_access.py
Fix issue where admin with `rejected` or `pending` pre-existing non-inst node requests was causing 500s where updating request at that node.
- fix logic and add test
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6998
> [ENG-6998] Catch Noderequests edge case

- api_tests/institutions/views/test_institution_relationship_nodes.py
- api_tests/nodes/views/test_node_relationship_institutions.py
- osf/models/mixins.py
- website/templates/emails/project_affiliation_changed.html.mako
The more dynamic templating options just produced too much awkward language, so we decided to use a simpler email template. 
- removes most of the custom language from the template,
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7004
> [ENG-7004] Alert admins of changed affillations

- api/requests/serializers.py
- api_tests/requests/views/test_node_request_institutional_access.py
- osf/models/mixins.py
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6998
> [ENG-6998] Catch another edge case where the user has multiple approvals

- api/requests/serializers.py
- api_tests/requests/views/test_node_request_institutional_access.py
- api_tests/requests/views/test_node_request_institutional_access_resubmit.py
- api_tests/requests/views/test_node_request_list.py
Catch cases where users have multiple access request that have been accepted.
- tweak logic and add test
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6998
> [ENG-6998] Infinite resubmits for iac

- website/templates/project/project_header.mako
- website/views.py
add components tab on legacy view
- Verify
- Verify
> [ENG-6840] Add Backend Support for Components Tab in Ember Project View

- admin/preprints/urls.py
- admin/preprints/views.py
- admin/templates/preprints/make_published.html
- admin/templates/preprints/preprint.html
Admin should be able to make a preprint published via admin app on a preprint page
Created a template and an appropriate view
https://openscience.atlassian.net/browse/ENG-6880
> [ENG-6880] Added an ability to make preprints published via admin app

- .github/actions/start-build/action.yml
- .github/workflows/test-build.yml
Test if updating CI works
- update the soon to be obsolete cachev2 with v4
- Verify
- Verify
> update cachev2 to v4

- osf/external/gravy_valet/translations.py
For dataverse, [the original Dataverse NodeSettings model override the `_get_fileobj_child_metadata` to return an empty list in case of 404 not found errors](https://github.com/CenterForOpenScience/osf.io/blob/develop/addons/dataverse/models.py#L165). We would need to emulate that in EphemeralNodeSettings.
- Verify
- Verify
> Add _get_fileobj_child_metadata to EphemeralNodeSettings

- osf/external/gravy_valet/translations.py
- osf/metadata/osf_gathering.py
- osf_tests/metadata/expected_metadata_files/preprint_basic.turtle
- osf_tests/metadata/expected_metadata_files/preprint_full.turtle
- osf_tests/metadata/expected_metadata_files/project_basic.turtle
- osf_tests/metadata/expected_metadata_files/project_full.turtle
- osf_tests/metadata/expected_metadata_files/registration_basic.turtle
- osf_tests/metadata/expected_metadata_files/registration_full.turtle
- osf_tests/metadata/test_osf_gathering.py
- website/project/views/contributor.py
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5137
> [ENG-5137] Preprint and project author on search cards does not reflect author order on preprint or project

- admin/users/views.py
- framework/auth/views.py
- tests/test_auth_views.py
- website/settings/defaults.py
- website/templates/emails/forgot_password.html.mako
- website/templates/emails/forgot_password_institution.html.mako
> [ENG-7276] Create way for users to reset password without the need for emailing a password reset link

- admin/templates/nodes/node.html
- admin/templates/nodes/resync_datacite.html
- admin/templates/preprints/resync_crossref.html
- osf/models/identifiers.py
- osf/models/preprint.py
This button was shown for all registrations, but not for projects. Also it should be displayed for public nodes only
Edited template if statements
https://openscience.atlassian.net/browse/ENG-6418
> [ENG-6418] Resync with Datacite button is displayed for only public projects and registrations

- api/preprints/serializers.py
- api_tests/preprints/views/test_preprint_detail.py
An unexpected error was raised because incorrect Publication DOI was passed
If possible try to strip redundant data and save the correct format
https://openscience.atlassian.net/browse/ENG-7283
> [ENG-7283] fixed publication doi related error

- osf/management/commands/force_archive.py
> Add cookie header to fix force archive

- osf/models/collection_submission.py
Fix Unhandled 'user'
Access dictionary with no exception
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-4255?focusedCommentId=83517
> ENG-4255-fix-not-proper-dictionary-item-access fix not proper dictionary access

- osf/models/collection_submission.py
- osf/models/user.py
Handle exceptions for subscribe_on_confirm and unsubscribe_mailchimp
add additional exceptions with sentry logging (It may be just temporary changings it may be redandunt)
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-4255?focusedCommentId=83544
> ENG-4255 add additional exceptions for subscribe_on_confirm and unsubscribe_mailchimp with sentry logging

- api/nodes/views.py
> [ENG-7317] FIx improper merge causing fix to fail

- tests/test_conferences.py
- website/conferences/utils.py
> Fixed meeting submissions failing with gv enabled

- api_tests/nodes/views/test_node_contributors_detail.py
fix TestNodeContributorDetail
See diff
N/A
N/A
N/A
N/A
> fix TestNodeContributorDetail

- addons/base/views.py
- docker-compose.yml
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7474
> [ENG-7474] Off-Addons-Release: File details page not working with view only links

- admin/templates/nodes/embargo.html
- admin/templates/nodes/node.html
Extend admin functionality to enable putting a registration into embargo
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7236
> [ENG-7236] Extend admin functionality to enable putting a registration into embargo

- admin/preprints/views.py
- admin_tests/preprints/test_views.py
test unwithdraw functionality when moderation is on/off
https://openscience.atlassian.net/browse/ENG-7563
> [ENG-7563] test unwithdraw functionality when moderation is on/off

- addons/base/views.py
Fix not graceful handling of fetching unconfigured providers during `get_auth` handler
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7256
> [ENG-7256] AddOns: Handle `get_auth` failures more gracefully

- framework/celery_tasks/utils.py
- framework/sentry/__init__.py
- osf/management/commands/delete_legacy_quickfiles_nodes.py
- osf/management/commands/force_archive.py
- website/archiver/tasks.py
Increase logging when archiving registrations
- Added general log message with some debug info when archiving is failed
- All raised exception in archiving celery tasks are expected to be logged with `logged`  decorator from `celery_utils.py` file, so I just made some updates to make it work as expected
- Added log statement to `force_archive()` function
- Deleted some sentry legacy code from `celery_utils.py` because it was used in only one place of the code
https://openscience.atlassian.net/browse/ENG-7457
> [ENG-7457] Increase Logging to Diagnose Registration Archiving Failures

- api/users/serializers.py
- api/users/urls.py
- api/users/views.py
- api_tests/base/test_views.py
- api_tests/users/views/test_user_confirm_external_login.py
Upgrade User Confirmation to V2
Added User Confirmation API endpoint
Added unit tests for User Confirmation API endpoint
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-7334
> [ENG-7334] Upgrade User Confirmation to V2

- admin/nodes/views.py
- admin/static/js/nodes/update_embargo.js
- admin/templates/nodes/embargo.html
fix embargo updating on admin page
1. Remove pre-validation request (date is validated inside of the `change_embargo_date()` function, so no need to make two separate requests)
2. Show error under input when request is failed
3. Minor UI improvements (remove form overlaping, increase size of the input field)
https://openscience.atlassian.net/browse/ENG-7679
> [ENG-7679] The date selection field (white square) next to the "Update Embargo" button is not informative.

- website/templates/project/project_header.mako
- website/views.py
Recent activity button should redirect to ember app
Added button with url that is handled by Flask and redirects user's request to ember
https://openscience.atlassian.net/jira/software/c/projects/ENG/boards/145?assignee=712020%3A7c7368dc-40cb-475f-bae8-b07a8bd2dd6c&selectedIssue=ENG-7706
> [ENG-7706] Added redirect to ember for Recent Activity tab

- admin/management/urls.py
- admin/management/views.py
- admin/templates/management/commands.html
- osf/management/commands/sync_doi_metadata.py
Possible updates mentioned in the ticket
https://github.com/CenterForOpenScience/osf.io/pull/11014#pullrequestreview-2705866778
Taking a look at the PRs on implementation
https://github.com/CenterForOpenScience/osf.io/pull/10979/files#diff-782af18f0182394607e13838b8a0b02651f3ab7a8a576cd5e5a854cafd44a21cR730-R731
https://github.com/CenterForOpenScience/osf.io/pull/10991/files
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7296
> [ENG-7296] feature/ENG-7296--v2 resyncing empty metadata dataarchive registration with Datacite

- osf/migrations/__init__.py
> Add view_registrationschema permission

- api/users/serializers.py
- api/users/urls.py
- api/users/views.py
- api_tests/base/test_views.py
- api_tests/users/views/test_user_external_login.py
Upgrade external_login_email.mako to V2
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-7327
> [ENG-7327] Upgrade external_login_email.mako to V2

- osf/management/commands/log_table.py
> [ENG-6422] added management command to log all write actions to given table

- api/preprints/views.py
Fix issue with resubmit rejected perepint version
TBD
TBD
TBD
TBD
https://openscience.atlassian.net/browse/ENG-7472
> [ENG-7472] Fix issue with resubmit rejected perepint version

- api/comments/views.py
- api/nodes/views.py
- api_tests/comments/views/test_comment_detail.py
- api_tests/nodes/views/test_node_comments_list.py
- osf/features.yaml
Implement the “Turn off Comments” flag
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-7339
> [ENG-7339] Implement the “Turn off Comments” flag

- osf/management/commands/sync_doi_metadata.py
Use retry method to simplify try..except
Use retry method instead of sleep
https://openscience.atlassian.net/jira/software/c/projects/ENG/boards/145?selectedIssue=ENG-7741
> [ENG-7714] Use retry instead of sleep

- .github/actions/start-build/action.yml
- .github/workflows/test-build.yml
> upgrade cache and ubuntu versions to avoid GHA brownouts

- website/static/js/accessRequestManager.js
- website/templates/project/contributors.mako
Fix contributor permissions when accepting access requests
Update .mako template for project contributor
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7698?atlOrigin=eyJpIjoiNjdlNGZkZTY4ZjM1NGFkNzhkOWJkMjlhZTIzNTcwZjgiLCJwIjoiaiJ9
> [ENG-7698] Fix permission for contributor, when accepting access request

- osf/utils/machines.py
- osf_tests/test_institutional_admin_contributors.py
Fix issues with addeding contributors who are requested. 
- makes selected permission override requested.
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7698
> [ENG-7698] Fix permission for contributor, when accepting access request #2

- framework/auth/__init__.py
> [ENG-7755]Set user_reference_uri upon authentication

- osf/__init__.py
- osf/tasks.py
- website/settings/defaults.py
> [ENG-7310] [ENG-7756] Implemnted communication from GV to OSF and addon action logging

- api/crossref/views.py
- website/identifiers/clients/crossref.py
- website/preprints/tasks.py
Mint preprint doi if all previous versions have minted doi
Build doi for previous versions when build doi for the newest one
Improved logs, created a new celery task to have the ability to retry task asynchronously
https://openscience.atlassian.net/browse/ENG-7728
> [HOTFIX-7728] Mint preprint doi if all versions have minted doi

- .docker-compose.gv.env
- addons/base/views.py
- docker-compose.yml
> [ENG-7703]-related Fix/gv local setup

- api_tests/base/test_utils.py
- osf/models/base.py
`Preprint` inherits from `VersionedGuidMixin` that inherits from `GuidMixin` thus `coerce_guid` tries to fetch guid from `guids` attribute instead of `versioned_guids`
Added if statement
https://openscience.atlassian.net/jira/software/c/projects/ENG/boards/145?selectedIssue=ENG-7791
> [ENG-7798] Parse versioned guid

- admin/preprints/urls.py
- admin/preprints/views.py
- admin/templates/preprints/fix_editing.html
- admin/templates/preprints/preprint.html
- osf/management/commands/fix_preprints_has_data_links_and_why_no_data.py
- osf_tests/management_commands/test_fix_preprints_has_data_links_and_why_no_data.py
Fix preprint updating
Add a manage command to fix why_no_data and has_data_links for broken preprints due to an unknown bug on FE (Futa described it in the comments to the ticket)
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7503?atlOrigin=eyJpIjoiZWYyNDhjYjBiMWY5NDhjNGEyODdiOTgwMmE1YzlhNTciLCJwIjoiaiJ9
> [ENG-7503] Fix/eng 7503

- api/share/utils.py
- api_tests/share/_utils.py
- api_tests/share/test_share_node.py
- osf/external/gravy_valet/exceptions.py
- osf/external/gravy_valet/request_helpers.py
- osf/external/gravy_valet/translations.py
- osf/metadata/osf_gathering.py
- osf/models/node.py
- osf_tests/metadata/expected_metadata_files/project_basic.turtle
- osf_tests/metadata/expected_metadata_files/project_full.turtle
- osf_tests/metadata/test_serialized_metadata.py
* Added verified links retrieval from GV to OSF
* Update SHARE with node's verified links
See diff
N/A
N/A
N/A
* Analysis: https://openscience.atlassian.net/browse/ENG-7769
* Implementation: https://openscience.atlassian.net/browse/ENG-7770
> [ENG-7769] [ENG-7770] Added verified links retrieval from GV to OSF + update SHARE with node's verified links

- api/preprints/views.py
- api_tests/preprints/views/test_preprint_versions.py
fix preprint visibility for admin reviewer
https://openscience.atlassian.net/browse/ENG-7811
> [ENG-7811] Reviews Dashboard not displaying contributors for preprint provider moderators

- admin/users/forms.py
- admin/users/views.py
- admin_tests/users/test_views.py
Add search by ORCID field to users search admin page
https://openscience.atlassian.net/browse/ENG-4673
> [ENG-4673] Add search by ORCID functionality to admin

- framework/auth/views.py
Revert async function that causes 502
> revert async email sending

- api/nodes/serializers.py
support related_counts for view_only_links
https://openscience.atlassian.net/browse/ENG-8051
> [ENG-8051] Update to /nodes/<node-id>/ api

- framework/celery_tasks/routers.py
- website/settings/defaults.py
Add external low/high modules and fix routing check
Add external low/high modules and fix routing check
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-8239
> [ENG-8239] Add external low/high modules and fix routing check

- osf_tests/test_gv_addon_logs.py
- osf_tests/test_gv_session_optimization.py
- osf_tests/test_gv_url_helpers.py
- osf_tests/test_gv_verified_links.py
- tests/identifiers/test_datacite_verified_links.py
- tests/identifiers/test_tasks.py
- website/identifiers/tasks.py
VRL - Unit tests for BE
Combines #11142  and #11178 from @Vlad0n20
N/A
- Verify
- Verify
N/A
N/A
https://openscience.atlassian.net/browse/ENG-7860
https://openscience.atlassian.net/browse/ENG-8025
https://openscience.atlassian.net/browse/ENG-8142
> [ENG-7860] [ENG-8025] [ENG-8142] VRL - Unit tests for BE

- osf/models/node.py
Reverts CenterForOpenScience/osf.io#11192
> Revert "[ENG-8048_2] fixed None issue during iteration"

- admin/templates/nodes/embargo.html
- admin/templates/nodes/embargo_termination_approval.html
- admin/templates/nodes/registration_approval.html
- admin/templates/nodes/retraction.html
Admins feel discomfort while looking for tokens in stashed urls and approval state fields on a registration page in admin
Format fields in a json-like way
https://openscience.atlassian.net/browse/ENG-6614?atlOrigin=eyJpIjoiMTdkMTM0YzBmNjljNDcxYTkxNjYzZDRjYTY3NjEyODMiLCJwIjoiaiJ9
> [ENG-6614] Improved formatting of stashed urls and approval state for registrations in admin

- website/identifiers/tasks.py
Fix AttributeError: 'NoneType' object has no attribute 'referent'
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-8314?atlOrigin=eyJpIjoiZjVmMmM4YzgwOTRmNDQ5NzlmZThjMTQxMWU1Njg5MjQiLCJwIjoiaiJ9
> [ENG-8314] Fix AttributeError: 'NoneType' object has no attribute 'referent'

- api_tests/users/views/sanction_response/test_user_sanction_response_embargo_termination.py
- api_tests/users/views/sanction_response/test_user_sanction_response_registration_approval.py
- api_tests/users/views/sanction_response/test_user_sanction_response_retraction.py
- tests/test_tokens.py
Fix failed test after merging upstream/develop branch
Fix failed test after merging upstream/develop branch
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-8329
> [ENG-8329] fix failed tests

- framework/auth/oauth_scopes.py
Allow token users to access collections related endpoints
- Update FULL_READ AND FULL_WRITE scopes to include collections specific scopes
- Verify
- Verify
> [ENG-8397] Collections scopes

- docker-compose.yml
Fix docker-compose for MFR
N/A
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-8398
> [ENG-8398] Fix docker-compose for MFR

- osf/management/commands/force_archive.py
- osf_tests/management_commands/test_force_archive.py
Fix name collisions issue and generic fallback.
See https://github.com/CenterForOpenScience/osf.io/pull/11194
https://openscience.atlassian.net/browse/ENG-8192
> [Reopen] [ENG-8192] Ability to force archive registrations when OSF Folders have changed

- api_tests/users/views/test_user_settings.py
clear throttle cache to make tests independent
https://openscience.atlassian.net/browse/ENG-8656
> [ENG-8656] Clean up password reset throttle error 

- api_tests/preprints/views/test_preprint_list.py
fix TestPreprintCreate
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-8758
> [ENG-8758] fix TestPreprintCreate

- api_tests/mailhog/provider/test_reviewable.py
- api_tests/preprints/views/test_preprint_versions.py
- api_tests/registries_moderation/test_submissions.py
- api_tests/users/views/test_user_actions.py
- notifications.yaml
- osf/utils/machines.py
- osf/utils/notifications.py
- osf_tests/test_registrations.py
- osf_tests/test_reviewable.py
- osf_tests/test_sanctions.py
- tests/test_preprints.py
- tests/test_registrations/test_review_flows.py
- tests/utils.py
- website/reviews/listeners.py
Add moderation emails
restored deleted reviews signals
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-8851
https://openscience.atlassian.net/browse/ENG-8852
> [ENG-8851][ENG-8852] Preprint Moderator Reject: No emails sent when moderator rejects preprint submission
