addons/base/views.py, addons/dataverse/models.py
Just a few little things to address the most recent round of QA.
dataverse:
- dataverse files node > target
- check write permissions directly for editing
deleted file metadata:
- update addon_deleted_file to take target
- return only node specific metadata when target is a node
Viewing dataverse files and deleted file metadata should work now!
https://openscience.atlassian.net/browse/PLAT-578
=> Render Dataverse Files, Deleted File metadata [PLAT-578]

scripts/analytics/file_summary.py
[#PLAT-1021]
The former query for counting total public files was hanging unexpectedly - simplify the query to make it run much faster. Perhaps related to the files-on-anything release.
- combine public node counts and quickfile counts after querying instead of the former OR query
None needed really, all the analytics should run normally though after this!
None necessary
https://openscience.atlassian.net/browse/PLAT-1021
=> Modify public file query to prevent Postgres hanging [PLAT-1021]

osf/models/mixins.py
Use `ReviewsStates` instead of `DefaultStates` for review counts.
- Changed `DefaultStates` to `ReviewsStates`
No front-end changes.
N/A
N/A
=> [OSF] Change provider counts to use ReviewsStates instead of DefaultStates

scripts/analytics/base.py, scripts/analytics/preprint_summary.py, scripts/analytics/run_keen_events.py, scripts/analytics/run_keen_snapshots.py, scripts/analytics/run_keen_summaries.py, scripts/analytics/user_summary.py
Figuring out what was actually done when running Keen analytics after the fact is hard as there was no file logger – add one and use it to log all keen analytic script logs to a file!
- change file logger in `scripts/analysis/base.py` to be for all analysis scripts
- add file logger that will log all child loggers in `scripts/analysis`
- small script improvements discovered with local testing
No QA needed!
None necessary
https://openscience.atlassian.net/browse/PLAT-1023
=> Add logging to keen analysis scripts [PLAT-1023]

addons/gitlab/api.py, addons/gitlab/exceptions.py, addons/gitlab/settings/defaults.py, addons/gitlab/static/gitlabNodeConfig.js, addons/gitlab/static/gitlabUserConfig.js
http:// schemes are add to Gitlab hosts too much this removes them. Like so:
- removes the excessive schemes strings.
- changes default http://gitlib.com
- better a catch the TOS error.
- Add suggestion to reconnect to error message.
Connect to a Gitlab instance and see that the link takes you to the right page.
None needed.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-913
=> [PLAT-913] Fixes for gitlab

api/base/serializers.py, api/base/urls.py, api/base/versioning.py, api/chronos/permissions.py, api/chronos/serializers.py, api/chronos/urls.py, api/chronos/views.py, api_tests/chronos/views/test_chronos_journal_detail.py, api_tests/chronos/views/test_chronos_journal_list.py, api_tests/chronos/views/test_chronos_submission_detail.py, api_tests/chronos/views/test_chronos_submission_list.py, framework/auth/oauth_scopes.py, osf/external/chronos.py, osf_tests/factories.py, tasks/__init__.py
Add endpoints for interacting with Chronos
1) Endpoints for:
- getting journal options for preprint provider
- `_/chronos/journals` `GET`
- Returns list of ChronosJournal objects (no outgoing calls)
- creating new submission
- `_/chronos/<preprint_id>/submissions/` `POST` (req: `journal` relationship)
- Triggers `submit_manuscript` and returns submission (outgoing call)
- link to finish submission on Chronos in serialized object
- updating an existing submission
- `_/chronos/<preprint_id>/submissions/<submission_id>` `PATCH` (empty)
- triggers `update_manuscript` and returns resulting submission (outgoing call)
- getting submission status(es) for a preprint
- Note: A preprint may have multiple submissions at any time, one per journal
- `_/chronos/<preprint_id>/submissions/` `GET`
- …
=> [IN-366] Chronos API wrapper

pytest.ini, requirements/dev.txt, tests/test_addons.py
We don't want to make external HTTP requests during Travis tests. This ensures we don't and fixes a few cases where we do.
- implements pytest plugin pytest_socket to block HTTP requests
- fixes the mocks for three addon tests that were making external calls
No QA, should have no visible effects on testing.
Not user-facing, none needed.
Pytest must be upgraded to work with current version.
https://openscience.atlassian.net/browse/PLAT-901
=> [PLAT-901][Hotfix] Block outgoing requests

api/metaschemas/views.py, api/schemas/serializers.py
[#PLAT-978]
Even though the `/metaschemas/` route will be deprecated, old requests should still work unchanged. 
- Add a serializer that allows `metaschemas` type for old requests
None needed
Nope
https://openscience.atlassian.net/browse/PLAT-978
=> Requests to old /metaschemas/ routes can still use metaschemas type [PLAT-978]

.jshintignore, .pre-commit-config.yaml, README.md, requirements/dev.txt, tasks/__init__.py
**Purpose**
Prevent formatting and syntax errors from ever making it to
Travis.
**Changes**
* Use [pre-commit](https://pre-commit.com/) to run flake8 and jshint
on git staged files
* Added a .jshintignore so that only website/static/js gets linted
(same behavior that `invoke jshint` had)
* Added `invoke syntax` which runs all hooks on all files. This
replaces both `invoke flake8` and `invoke jshint`
**Side effects**
Devs should install the pre-commit hook with
```
pip install pre-commit
pre-commit install --allow-missing-config
```
**Documentation**
Added a small blurb in the README about how to install the
pre-commit hook.
**Notes**
The pre-commit config was purposefully kept minimal to reduce
the size of this PR's diff.
I'd like to follow up this up with a PR to add more formatting …
=> Use pre-commit for formatting and linting

addons/s3/settings/__init__.py
Allow config settings defined in `addons/s3/settings/defaults.py` to be overridden in `addons/s3/settings/local.py`.
Add a local-loading stanza to `addons/s3/settings/__init__.py`.
Dev will QA
No documentation updates needed.
None expected.
Doesn't have its own ticket, but extends work done in [PLAT-977](https://openscience.atlassian.net/browse/PLAT-977).
=> [PLAT-977] let s3 default settings be overridden by local.py

api/metaschemas/views.py, api/schemas/serializers.py
While #8614 reverted the type for `/metaschemas` it did not for `/metascheas/registrations`. 
Registries relies on this to be correct: https://osf.io/registries/discover
* add `DeprecatedRegistrationMetaSchemaSerializer`, which sets type to `registration_metaschemas`
* use `DeprecatedRegistrationMetaSchemaSerializer` for `DeprecatedRegistrationMetaSchemaList` and `DeprecatedRegistrationMetaSchemaDetail` views.
* make sure resources returned by `/v2/metaschemas/registrations` are of type `registration_metaschemas`.
* make sure registries discover page doesn't display an error
Don't think so?
Registries works again.
N/A
=> [hotfix] Also revert /metaschemas/registrations type

scripts/analytics/file_summary.py
With files on anything, this script was refactored for new targets, which accidentally excluded Registrations.
Turns out the `ContentType` for `Node`, `Registration` and `QuickFilesNode` is all the content type for the base class `AbstractNode` anyhow. 
Simplify the query to be for all `AbstractNode` targets, which include QuickFiles and Registrations. 
This makes the public and private totals match the total files once again.
```
{'private': 265828, 'total': 558372, 'public': 292544}
```
Sara and those looking at file analytics on keen should see this change reflected.
https://openscience.atlassian.net/browse/PLAT-1024
=> [hotfix] Adjust count to be fore all AbstractNode targets [PLAT-1024]

osf/models/user.py, osf_tests/test_quickfiles.py
[PLAT-1026]
This will ensure that the root folder is also updated and not just the target, as the API endpoint relies on getting the children of the root folder.
- Get the destination quickfiles root folder, and instead of manually updating the file's target, move it under the destination root folder instead. 
- Update the test to not only check the file's target, but the file's parent's target (which was not getting updated properly)
Merging users quickfiles should now work as expected!
None necessary
https://openscience.atlassian.net/browse/PLAT-1026
=> [hotfix] Update parent as well as target for user quick files merges [PLAT-1026]

scripts/populate_institutions.py
Add CMU to production OSF server
Fyi, `[skip ci]` added to commit
https://openscience.atlassian.net/browse/SVCS-845
=> [OSF Institutions] Add CMU to prod server [SVCS-845]

webpack.common.config.js
Simple typo in "image/png" in the webpack.config for url-loader
image/ng -> image/png
=> typo in image/png for url-loader

api/preprints/serializers.py, api_tests/preprints/views/test_preprint_detail.py, osf_tests/test_node.py, tests/test_preprints.py, website/preprints/tasks.py, website/settings/defaults.py, website/static/vendor/citeproc-js/citeproc.js
Same as #5436: Updating code that generates DOI links to use the preferred resolver, see √https://www.doi.org/doi_handbook/3_Resolution.html#3.8
See above.
I'm not sure whether the change to `citeproc.js` should be included here. My PR against their source is "open": https://bitbucket.org/fbennett/citeproc-js/pull-requests/8/
Also, instead of updating [the test](https://github.com/CenterForOpenScience/osf.io/compare/develop...katrinleinweber:resolve-DOIs-securely#diff-ff12d43019bc9d10aba358d19ec9bbe6), maybe duplicating it with both URL variants makes more sense?
=> Hyperlink DOIs against preferred resolver

osf/models/identifiers.py, website/identifiers/clients/crossref.py, website/identifiers/tasks.py
Fix issue where updating preprint DOI metadata
upon withdrawal, deletion, etc. fail
Pass `status` down to `request_identifier_update` instead of
doing a db query. We suspect a stale data somehow where preprint doi status is still
public (`verified_publishable`) after  withdrawal, deletion
Create a preprint and make sure it gets crossref doi, checking at `test.crossref.org` using the preprint doi to retrieve the submission xml. The status should be 'resolved' and you should be able to see the following fields `item_number`, `title`, `description`, `description`, etc elements in the submission xml file.
Create a withdrawal request and approve it, make sure that (may take a while) the fields mentioned above don't show in the submission xml file. …
=> [IN-282][OSF] Fix issue with updating preprint DOI metadata

api/base/utils.py, api/base/versioning.py, api/base/views.py, api/taxonomies/views.py, api_tests/base/test_utils.py
Use standard library distutils to compare versions instead of relying on string comparisons (where 2.9 > 2.10)
- Wrap version numbers to be compared in `StrictVersion`
- Update tests for version comparison utils
No QA needed, this was just to prevent future confusion as our API is just about to reach version 2.10
Nope!
https://openscience.atlassian.net/browse/PLAT-1015
=> [hotfix] DeprecatedView for versions higher than x.9 [PLAT-1015]

api/institutions/authentication.py, framework/auth/views.py, osf_tests/test_queued_mail.py, tests/test_auth.py, website/mails/listeners.py, website/templates/emails/welcome.html.mako, website/templates/emails/welcome_osf4i.html.mako, website/templates/project/settings.mako
To fix email links and improve language for setting page.
- pass current domain to email templates
- change language about being unable to change node regions.
Click and new welcome email link and check out new text on settings page.
None
https://openscience.atlassian.net/browse/PLAT-851
=> [PLAT-851] Storage Internationalization UI Fixes

website/project/views/node.py, website/templates/project/settings.mako
There is the same code in two places: in 'addons/forward/templates/forward_node_settings' and in 'website/templates/project/settings.mako' (where it was copy-pasted!). 
I added a new dict 'addons_settings' for addons that have configurations in the project settings page. This dict is returned from the 'node_setting' function of website.project.views.node. I filled this dict with neccesary data of the 'forward' addon. I also added the 'render_node_settings' def in project settings.mako that renders settings templates of addons from the mentioned dict. Finally I replaced copy-pasted code with 'render_node_settings' call.
The only page to test is the project settings page.
=> Render forward_node_settings.mako in project settings

osf/models/user.py, tests/test_views.py, website/profile/views.py
❗️ Needs to be accompanied by https://github.com/CenterForOpenScience/cas-overlay/pull/128
Password changes are not invalidating your other sessions in other browsers.  
The solution maybe issue a logout request on password reset and redirect to login with verification key and username automatically.
Needs to accompany Longze's CAS-side fix. On my side, logout the user when they reset their password, and then log them in automatically with a verification key and username. Longze's CAS piece will make a logout from the OSF make all CAS sessions invalid.
1.  Log in in two browsers as the same user.
2. Change your user's password in one browser.
3. Confirm you see a green "password changed" indication at the top
4. In the other browser, refresh or hit sign in, and confirm that you are logged …
=> Hotfix/Password Change Invalidate Sessions [PLAT-1052]

osf_tests/test_node.py, website/project/tasks.py
Whenever a registration is submitted, the parent-child relationship isn't being sent if it exists.
- Pass through parent-child relationship
- Add test
No front-end changes
N/A
N/A
https://openscience.atlassian.net/browse/IN-32
https://openscience.atlassian.net/browse/IN-425
=> [IN-425][IN-32][OSF] Add hierarchies to registries

api/preprints/serializers.py
We need to see the `reviews_state` of withdrawn preprints for the reviews app to work with withdrawals.
- Removed `NoneIfWithdrawal` check from `reviews_state`
No front end changes
`N/A`
https://openscience.atlassian.net/browse/IN-421
=> [IN-421][OSF] Remove NoneIfWithdrawal on reviews_state

api/users/permissions.py, api/users/urls.py, api/users/views.py, api_tests/base/test_views.py, api_tests/users/views/test_user_claim.py, api_tests/utils.py, website/project/views/contributor.py
Allow Ember apps to let unregistered users be claimed
* Add endpoint
* Add tests
No UI components, API testing would duplicate TCI
None expected
[[IN-417]](https://openscience.atlassian.net/browse/IN-417)
=> [IN-417] V2 Claim Unregistered User Endpoint

addons/gitlab/api.py, addons/gitlab/models.py, addons/gitlab/views.py
Currently If a user hasn't agreed to the TOS the user is locked out of their account. This fixes that.
- refactor `.code` to `.response_code` to catch exception better
- add descriptive messages to catch error.
I tested this by inserting an error into the repo method like so:
```python
def repo(self, repo_id):
"""Get a single GitLab repo's info.
https://docs.gitlab.com/ce/api/projects.html#get-single-project
:param str repo_id: GitLab repository id
:return: gitlab.Project a object representing the repo
"""
try:
raise gitlab.GitlabGetError('You (@latifn2) must accept the Terms of Service in order to perform this action. Please access GitLab from a web browser to accept these terms.', response_code=403)
return gitlab.Project(self.gitlab, repo_id)
except gitlab.GitlabGetError as exc:
if …
```
=> [PLAT-1069][Hotfix] Catch Gitlab TOS Error

admin/common_auth/views.py, api/users/serializers.py, api_tests/users/views/test_user_can_review.py
Fix permissions check in user serializer
* Use the right kind of `GroupObjectPermission` sub-class
* Fix lookup in Admin module
This should affect whether or not non-superusers can view the reviews app, and also allow additional users to be added to reviews groups through the admin module
None
None expected
None
=> [Hotfix][No Ticket] User can_view_reviews

api/nodes/serializers.py, api/registrations/serializers.py
Add `archiving` property to registrations serializer and `draft_registrations` count to node serializer.
* serialize `archiving` property of registrations
* add ability to get related count for `draft_registrations` to node serializer
Will be QAed along with front-end.
**developer.osf.io PR needed to document new attribute for registrations!!!**
https://openscience.atlassian.net/browse/EMB-186
=> [EMB-186] registrations archiving and node draft registrations count

website/settings/local-dist.py
**Purpose**
Use celery in local development for better
dev-prod parity.
We used to disable celery for local dev in the
pre-Docker days so that devs didn't have to install
rabbitmq and run celery.
Nowadays, running celery is as easy as `docker-compose up -d worker`,
so no need to disable it.
See @icereval's comment in https://github.com/CenterForOpenScience/osf.io/pull/8666#issuecomment-418939103
**Changes**
* Don't override `USE_CELERY` in local-dist.py
=> Enable celery in local development

addons/osfstorage/models.py, addons/osfstorage/tests/test_models.py
When you fork a project and its components, the storage regions of the fork are the same as the original. They should instead be stored under the user's default region.
Fork region changed and test added.
It looks like to me that a node's NodeSettings should point to the creator's UserSettings.  Currently forks are getting the same UserSettings as the original user.  I may be misunderstanding what this is for.
https://openscience.atlassian.net/browse/PLAT-1033
=> Feature/Forked Projects take User Default Region [PLAT-1033]

docker-compose-dist.override.yml
`ember-osf-web` does not consume `ember-osf`
Remove commented out config for linked `ember-osf` development from `ember_osf_web` section of `docker-compose-dist.override.yml`.
n/a
n/a
n/a
n/a
=> [no ticket] Remove ember-osf linked config for ember_osf_web

docker-compose-dist.override.yml
Remove ember_osf_web from docker-compose-dist.override (since we don't use it)
Remove ember_osf_web from docker-compose-dist.override.yml
n/a
n/a
n/a
n/a
=> [no ticket] Remove ember_osf_web from docker-compose-dist.override

api/base/settings/defaults.py, requirements.txt, website/settings/defaults.py
Use `django-celery-results` and configure the `django-db` as the storage source for the Celery task results backend.
The `amqp` backend we're using is no longer supported by celery.
This should reduce some of the high load on rabbitmq we've been seeing on production lately.
Configures the backend PostgreSQL database for results storage.
Double check to ensure registrations archive.
To test locally you'll need to ensure `USE_CELERY = true` is set in the `website/settings/local.py` settings file.
DevOps will need to monitor both the database size, and ensure the `celery.task.backend_cleanup` task is running nightly (currently is) via the beat scheduler.
N/A
=> [hotfix] django-celery-results

framework/logging/__init__.py, website/settings/defaults.py
**Purpose**
DEBUG is too chatty, even for local dev. My flask server logs are full of junk like this:
There's no need to implicitly set the logging level to DEBUG
when DEBUG_MODE is one. This can be set explicitly in local.py
if needed.
**Changes**
The log level for the flask app will always be whatever
`settings.LOG_LEVEL` is set to, even if `DEBUG_MODE = True`
**Side effects**
DEBUG logs will no longer show by default in local dev.
If you need these, set `LOG_LEVEL = logging.DEBUG` in
`website/settings/local.py`.
**QA**
No QA--this only affects local dev
=> Always respect logging level set in website.settings

addons/osfstorage/models.py
When moving a file, update the file's most recent version's region to match the destination region, if it's different. The region metadata for a move is already updated waterbutler side on an inter-region move, so we should update this end as well!
- On an inter-region move, update the most recent version of the file being moved to match the destination's region
This is for that side use case we talked about! This should fix the case in which a file is moved regions and then a new version of that file is updated.
None needed
https://openscience.atlassian.net/browse/PLAT-1053
=> When moving a file, update the most recent version's region if needbe [PLAT-1053]

docker-compose-dist.override.yml
Similar to 7b1aed6305d07dbcc38ec9812e6cb90b073fa192, default to using
`:cached` mode on mounted volumes in
`docker-compose-dist.override.yml` to avoid high CPU usage on
Docker4Mac.  See [1], [2].  If you've already created a
`docker-compose.override.yml`, manual append `:cached` to all volumes
except those under `emberosf` and `rabbitmq`.
[1] https://docs.docker.com/docker-for-mac/osxfs-caching/#cached
[2] https://github.com/docker/for-mac/issues/1759#issuecomment-366632793
=> Add `:cached` to override bind mounts

website/files/utils.py
When a file is copied from one region to another, none of its versions followed and it was simply treated as a new node. Now, let's bring along all the other regions for the move and just update the most recent version to be the same as the destination node's region, leaving the other versions in their original region.
- in `copy_files`, copy over all the old versions and then update the most recent one to be in the destination node's region
This is the OSF side of being able to copy all the versions of a file across regions! For a super through test the most recent version of a file would be stored on the destination nodes region, and all the other versions of the node would be on the origin node's region.
None needed
https://openscience.atlassian.net/browse/PLAT-1100
=>  [PLAT-1100] Update the most recent fileversions region for copied files across regions

tasks/__init__.py
* Add missing api_test directories to invoke tasks so they'll be run by travis. 
* Added missing directories to `API_TESTS`
* I randomly picked between `API_TESTS2` and `API_TESTS3` lists. Looking at a recent build, 1 seems to be the slowest and 2 is currently the fastest.
=> Add missing api_tests to inv task

website/views.py
Custom institution domain redirects aren't working.  ember-osf-web’s index.html is served instead of the institution detail page.  
Fixes bug introduced in https://github.com/CenterForOpenScience/osf.io/pull/8576
Line used to be this institution = Institution.objects.get(domains__contains=[request.host.lower()], is_deleted=False)
https://github.com/CenterForOpenScience/osf.io/pull/8576 made it institution = Institution.objects.filter(domains__icontains=[request.host], is_deleted=False)  (which will return an empty queryset)
should be something like:
institution = Institution.objects.get(domains__contains=request.host.lower(), is_deleted=False), removing array since using `icontains`
https://openscience.atlassian.net/browse/PLAT-1108
=> Hotfix/Custom Domains Redirect Fix [PLAT-1108]

website/files/utils.py
This will allow the most recent version of the cloned file to have the correct region, while the fileversion from the original file keeps its region
- Create a new fileversion instead of adding FKs to all the old fileversions
This should fix Lauren's most recent reported bug, and expected shouldnow happen!
Upload a file to region A
Give the file at least 2 versions
Copy it to region B
Upload a new version to region A
Try to render the file from region A
Expected
File would render.
none
none
https://openscience.atlassian.net/browse/PLAT-1100
=> [PLAT-1100] Create a new version from the most recent when copying

website/static/css/pages/project-page.css
View-only Links can be configured in two places: on contributors page and on settings page. There is used a template with class 'remove-or-reject' in both places - the same template. But on settings page, there is no definition of CSS styles for this class (another .css file is linked), so "x"-es removing table's rows are not so pretty like on contributors page.
I added the same style for the 'remove-or-reject' class as it is defined for contributors page.
Project settings page changed - configuration of View-only Links.
=> Lack of style for remove-or-reject class on the settings page.

website/templates/base.mako, website/templates/project/project_base.mako
GA custom dimension reporting for Embosf and osf.io is slightly different. This should make them identical.
- custom dimension #1 is now capitalized
- custom dimension #2 now uses the resource type so "projects" or "components" are now "nodes"
- custom dimension #3 is no longer a bool, but either "public", "private" or "n/a"
You should be able to set up a GA account and see the custom analytics been sent to it and see that they are seemly with the Ember analytics. Instructions on how to set up a GA account with custom dimensions are in the old PR for this [here](https://github.com/CenterForOpenScience/osf.io/pull/8140)
Basically a bug fix, no docs required.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-719
=> [PLAT-719] Bring Google analytics up to date with Ember

api/base/exceptions.py, api/base/serializers.py, api/nodes/serializers.py, api/nodes/views.py, api_tests/nodes/views/test_node_draft_registration_detail.py, api_tests/nodes/views/test_node_draft_registration_list.py
The going-forward ember method of connecting related resources is by manipulating the relationship instead of setting attributes, and this endpoint is just now being used by ember.
- Specify the `registration_schema` for a draft registration via relationships instead of an attribute.
```json
POST localhost:8000/v2/nodes/<node_id>/draft_registrations/
{
"data": {
"type": "draft_registrations",
"registration_supplement": "<schema_id"
}
}
}
```
```json
POST localhost:8000/v2/nodes/<node_id>/draft_registrations/
{
"data": {
"type": "draft_registrations",
"attributes": {},
"registration_schema": {
"data": {
"type": "registration_schemas",
"id": "<schema_id>"
}
}
}
}
}
```
- Errors in relationship field are serialized under source > pointer as error being …
=> Feature/Registration Schema Relationship [PLAT-1001]

.mergify.yml
See full notes for this PR [on the notion page](https://www.notion.so/cos/Mergify-19d768e2d65e4bf9bf6375acafca130f)
Keeping track of PRs to be merged can be an extra hassle for maintainers - let's try out Mergify to help manage that workflow. Mergify will automatically merge any PRs that meet a certain set of requirements.
The full docs [can be found here](https://doc.mergify.io/)
Out of those options, here's what this initial config does:
- Any PR with the label `enable-mergify` (added to the PR on github) will be eligible to be merged by mergify.
- By default, requires approving reviews from 1 contributor with **write access**
- Any review that comes before another commit has been made **will not count**
- Requires travis to pass
- Any PR that changes either `.travis.yml` or …
=> Integrate Mergify for auto-merging PRs after conditions have been met [PLAT-1048]

website/project/views/node.py, website/templates/project/settings.mako
Section "Affiliated Institutions" and "Available Institutions" in the "Project Settings" page should use the logo with rounded corners to prevent the circular image frame from cutting off its corners.
* Updated the `projects/settings.mako` to use `logo_path_rounded_corners` instead of `logo_path`.
* Updated `get_affiliated_institutions()` in `node.py` to return `logo_path_rounded_corners`.
It is impossible to test on staging without having a working institution. One thing QA can do is to either use the Admin App or ask Devs who can modify staging DB to manually affiliate users with a few institutions. I did the same thing locally. Make sure the logos looks good in section "Affiliated Institutions" and "Available Institutions" on the "Project Settings" page.
No
No …
=> [HotFix]  Fix the institution logo cut-off issue on the project settings page [SVCS-917]

addons/bitbucket/api.py
Bitbucket will connect properly, but when it attempts to retrieve your list of branches it returns a 400, because it's been updated to accept a page code instead of sequential page number.
- re-writes part of code that iterates over pages to account for new behavor
You should be able to view your bitbucket account connected and look at all your files/branches on the files page.
I decided not to include unit tests, because this a one-off that's largely dependent on bitbuckets outside behavior and so tests won't necessarily reflect working behavior and there are not pre-existing test for the bitbucket client.
https://openscience.atlassian.net/browse/PLAT-1067
=> [Hotfix][PLAT-1067] Bitbucket pagination fix 

addons/osfstorage/models.py
Prefetching `target` on children when checking `is_preprint_primary` was causing the child's `is_preprint_primary` property to not work properly. Removing this prevents folders from preprints from being moved. Thanks @felliott!  (aaah sorry other Fitz I accidentally tagged just now!)
- Remove prefetch related on children query for `is_preprint_primary` on `OsfStorageFolder`
You should no longer be able to move a folder containing a preprint to another component. 
This should happen (modified from the ticket):
1. Create a preprint
2. After preprint is created, go to the OSF project
3. Create a component under the project
4. On the OSF project (with preprint), create a folder 
5. Move the preprint file into this folder.
6. Try Move this folder into the component
7. This action should fail …
=> [hotfix] Don't let users move a folder with a preprint in it [PLAT-1116]

tests/test_views.py, website/project/views/node.py
Fix a regression where a non-admin contributor no longer has the option to remove themselves from a project and its components and add a test.
In order to give you the option to remove yourself from components as well, the UI needs to know that you're a contributor on children in the first place. https://github.com/CenterForOpenScience/osf.io/pull/7951 mistakenly removed this capability, only returning children if you were an admin.  This reverts some of that PR, returning children if you're a read contributor on the node, and then for each child, making sure you're a read contributor there as well.  This still leaves a lot of the optimizations that were done to speed things up.  A regression test added to ensure read contributors can still see children.
Same tests as …
=> Fix/Remove Self from Project and Components [PLAT-991]

osf/features.py, osf/models/queued_mail.py, osf_tests/test_queued_mail.py, website/mails/mails.py
Allows engagement emails to be temporarily disabled by a waffle switch ("disable_engagement_emails"). When the switch is active, users should not receive **any** of the emails listed below.  
Added osf/features.py to start keeping track of waffle flags/switches.
Confirm that when the switch is active, you **do not** receive the following emails. The google doc in the ticket description will be helpful in determining how some emails are triggered.
**Welcome**
* Sent immediately
* Subject: "Welcome to the Open Science Framework"
**Welcome OSF4I** 
* Sent immediately
* Subject: "Welcome to the Open Science Framework" (contains "Affiliate your projects with your institution" in the email body)
**No addons**
* Queued 
* Subject: "Link an add-on to your OSF project"
**No login**
* Queued
* …
=> [feature] Add waffle switch for engagement emails [PLAT-1076]

osf/models/node.py
Add the correct log ("custom citation added") when a custom citation is first created (instead of "custom citation edited"). 
Logic for adding the "custom citation added" log needed to be adjusted since custom citations are now nullable.
Confirm that when making a custom citation for the first time you receive the "custom citation added" log instead of "custom citation edited".
None expected 
https://openscience.atlassian.net/browse/PLAT-1124
=> [hotfix] Fix first custom citation log [PLAT-1124]

scripts/remove_after_use/fix_unclaimed_records_for_preprints.py
Some users were incorrectly added to nodes as contributors and not given unclaimed records. This PR searches the logs to give them those records.
- adds script to restore unclaimed records to users without them.
This should allow citations to appear for users who were having trouble with them before.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-1080
=> [PLAT-1080] Restore unclaimed records

addons/base/tests/models.py, addons/dropbox/tests/test_views.py, addons/github/tests/test_views.py, addons/gitlab/tests/test_views.py, addons/googledrive/tests/test_models.py, addons/onedrive/tests/test_models.py, api_tests/applications/views/test_application_reset.py, api_tests/providers/preprints/views/test_preprint_provider_moderator_list.py, osf_tests/test_node.py, requirements/dev.txt, tests/test_auth.py
In order to best prepare for the big changes coming with Python 3 we're going to implement some backward compatible changes first to defray the amount we have to CR in the final PR.
One thing we have to do is update mock. Currently mock 1.0.1 autospec function isn't compatible with Python 3 so it's best to upgrade to 2.0.0 now so there will be a seamless transition. 
- change dev.txt requirements
- change assert_called_once to assert_called_once_with/call_count
- remove mock for test_queueing_on_node_updated which was always throwing a false positive
No user-facing QA just run Unittests
No docs
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-1083
=> [PLAT-1083] Python 3: update mock to 2.0.0

website/routes.py, website/views.py
Custom domains are being routed to institution detail page. For example, https://osf.io/institutions/uwstout/, used to be hosted at https://open.uwstout.edu.  The correct code is loading, but the route should not change.
This is a fix of a fix, hopefully third time's a charm. https://github.com/CenterForOpenScience/osf.io/pull/8576 removed now obsolete code for the legacy dashboard and landing pages and simplified routing. We no longer needed some of the view and template logic for these pages, we could just reroute to the ember app.  A side effect was that custom domains also use the index route.  That ticket introduced a bug with custom domains not loading properly.  https://github.com/CenterForOpenScience/osf.io/pull/8694 attempted to fix, having a custom domain load the institution …
=> [Hotfix] Feature/Custom Domain Route [PLAT-1108]

website/project/metadata/utils.py, website/project/views/drafts.py, website/project/views/register.py, website/views.py
Fix issues preventing proper status messages to be passed to Embosfed project registrations page (and, in fact, all Embosfed node guid routes).
* For node guid routes, return `use_ember_app()` response instead of throwing it away
* Use guid routes throughout the registration process to avoid any redirection
* Set ids for registration-related status messages (translations keys for the Ember front-end)
This will affect all Embosfed guid routes (especially the registrations tab). It also changes the URLs during the registration process to all be `/<guid>/draft/...` instead of `/project/<guid>/draft/...`. This can be tested as part of the full regression for 18.0.0 and does not require API nor cross-browser testing.
N/A
Shouldn't be.
https://openscience.atlassian.net/browse/EMB-186
=> [EMB-186] status message fixes

scripts/remove_after_use/set_meetings_users_fullnames_to_guids.py, tests/test_conferences.py, website/conferences/message.py, website/conferences/utils.py, website/conferences/views.py
We don't want to show user emails as their fullname name when they submit a poster via email and don't provide a real fullname. This PR will give the users the guid instead of email for fullnane and migrates old users who have email for fullname.
- migration script for changing fullname to guid
- change to add_poster_by_email to prevent users from repeating this in the future
- add unittest
It's hard to test this in a local environment as it requires setting up mailgun I recommend just using the unittests.
Product wants to notify users that their fullname has been this is marked WIP while we wait on that language. Might want to split off the migration in the meantime and just merge the fix.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-1121
=> [WIP][PLAT-1121][Hotfix] User emails from meeting submissions no longer fullname

addons/wiki/views.py, api/actions/serializers.py, api/collections/serializers.py, api/collections/views.py, api/comments/views.py, api/nodes/serializers.py, api/nodes/views.py, api/preprints/serializers.py, api/preprints/views.py, api/providers/serializers.py, api/providers/views.py, api/registrations/serializers.py, osf/exceptions.py, osf_tests/test_user.py, website/profile/views.py, website/project/views/drafts.py, website/project/views/node.py, website/project/views/register.py, website/tokens/handlers.py
We want to make the transition to Python 3 as seamless as possible and that means we're going to have to do a lot of refactoring. To defray the amount we have to do I a single big change-over we're starting by preemptively changing code so it's valid in both Python 2 and Python 3.
Anyway part of that is the string-ifing exception messages. Which traditionally we do like `e.message` which is valid in Python 2, but not Python 3. However `str(e)` is valid in both, so we're changing as many of those exceptions as we can. 
Worth noting this only applies to built-in exceptions or those that inherit directly from those, so this isn't really exhaustive.
The following exceptions are now string-ified differently:
- PermissionsError
- ValueError
- NodeStateError
- InvalidTriggerError
- …
=> [PLAT-1084] Py3 stringify exceptions

framework/auth/oauth_scopes.py
OAuth scope descriptions are more visible on the embosf'd personal access tokens page. Inconsistent punctuation makes us look bad.
Add a period to the end of each scope description that doesn't already have one.
Check the scope descriptions at `/settings/tokens/create` (or on a token edit page) all end in a period.
n/a
n/a
https://openscience.atlassian.net/browse/EMB-341
=> [EMB-341] Consistent oauth scope description punctuation

website/views.py
Remove premature serving of ember front-end for node guid routes so that back-end handling of forbidden projects continues to work.
Remove code that checks for an active flag matching the current project page and returns a response serving the ember front end without processing through the Flask views.
Attempts to access embosfed project pages for private projects should match the behavior on prod, namely:
* logged out: redirect or log in page
* logged in, no access: present page telling you so and buttons for requesting access and switching accounts 
n/a
🤞
n/a
=> [EMB-377] Remove premature serving of ember front-end for node guid routes

api/registrations/serializers.py, api_tests/registrations/views/test_registration_detail.py
Add related meta count for total registration comments
⚠️ This count only accounts for `top_level`, `undeleted`, and node-type `page`.
- Add related count to comment relationship
- Add tests
NotQATeam
[REG-18](https://openscience.atlassian.net/browse/REG-18)
=> [REG-18][Registries] Add comment total count to registrations

api/nodes/serializers.py, api/registrations/serializers.py, api_tests/nodes/views/test_node_detail.py, api_tests/registrations/views/test_registration_detail.py
Add wiki page counts to registration
for registries ember app
- Add `wiki_page_count` to related counts node and registrations detail
- Add tests to registration, node detail
[[REG-16]](https://openscience.atlassian.net/browse/REG-16)
=> [REG-16][OSF] Add wiki page counts to registration

api/nodes/serializers.py
Fixes frontend
* don't `require` `provider` when creating a `DraftRegistration`, default to `OSFRegistries`
Should allow for continued testing
None expected
None
=> [No Ticket] Remove provider required, default to OSFRegistries

api/nodes/serializers.py, api/nodes/utils.py, api_tests/registrations/views/test_registration_detail.py
Make it easy to tell whether the current user is a contributor on a given registration, to correct a bug in the embosf'd project navbar.
Move `current_user_is_contributor` field from NodeDetailSerializer to the base NodeSerializer. This makes the field available on registrations, and on nodes fetched via list views.
- Open the analytics or forks page of one of your registrations
- Check the "Contributors" link appears
- Open the analytics or forks page of someone else's registration
- Check the "Contributors" link does not appear
n/a
n/a
https://openscience.atlassian.net/browse/EMB-362
=> [EMB-362] Expose "is contributor" on registrations

admin/collection_providers/forms.py
`Trim whitespace when setting provider choices`
`Trim whitespace when setting provider choices`
Should no longer be able to input leading/trailing `whitespace when setting provider choices`
None expected
None
=> [Hotfix] Trim whitespace when setting provider choices

scripts/analytics/node_summary.py, scripts/remove_after_use/create_spam_node_count_csv.py, scripts/tests/test_node_summary.py
This PR will start sending the number of nodes created daily excluding spam to keen and contains a script to generate a csv of that data for all dates through March 14 2018.
- Add excluding spam queries to node summary keen event
- update tests for node summary
- add script to generate csv for nodes created excluding spam
Fairly straightforward this can be tested by running the unit test and scripts and checking that the data is accurate.
None
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-1132
=> [Warmfix][PLAT-1132] Report non spam numbers

osf/external/chronos.py
Currently, the `FILE_DOWNLOAD_URL` is not constructed properly. This PRs fixes that by constructing the url using the `_id` of the file.
Change the `serialize_file()` method of `ChronosSerializer` so that it construct the download link correctly.
=> [Chronos] Change how FILE_DOWNLOAD_URL is constructed

api/schemas/serializers.py, api/schemas/urls.py, api/schemas/views.py, api_tests/schemas/views/test_registration_schemas_detail.py, framework/auth/oauth_scopes.py, osf/models/__init__.py, osf/models/metaschema.py
Add API v2 endpoints for Registration Schema form blocks.
Normalize formblock for Registries frontend needs normalized data structure for submission
- Add detail and list related views on RegistrationSchema `/v2/schemas/registrations/<schema_id>/form_blocks/<form_block_id>`
`/v2/schemas/registrations/<schema_id>/form_blocks/`
- Add tests
NotQATeam
- Coming soon
[REG-47](https://openscience.atlassian.net/browse/REG-47)
=> [REG-47][Registries] Add FormBlock API

addons/base/views.py, tests/test_addons.py
Currently going to https://osf.io/2ba8c/files/osfstorage/58a5bcb66c613b01f3ead217/  or any `/<nid>/files/osfstorage/<folder path>/` link will cause the browser to detect an infinite redirect loop and stop the page from loading. This fix prevents that.
- changed addon_view_or_download_file to properly handle folders
- add test
Links like this one https://osf.io/2ba8c/files/osfstorage/58a5bcb66c613b01f3ead217/ where the path points to a valid folder should resolve to a 400 Bad Request message instead of forcing the browser into a redirect loop.
🐞 fix no, docs.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-1139
=> [Hotfix][PLAT-1139] Fix infinite redirect loop for folder link

website/static/js/accountSettings.js, website/templates/profile/account.mako
Currently the Storage Internationalization user default dropdown has a bootstrap bug where it can't be clicked/touched on mobile screens. This PR fixes that.
- simple CSS fix
Very similar to an earlier touchscreen problem we had here:  https://github.com/CenterForOpenScience/osf.io/pull/8448
🐞  fix no docs.
https://openscience.atlassian.net/browse/PLAT-1136
=> [Hotfix][PLAT-1136] Fix unclickable storage i18n locations 

website/project/views/node.py, website/project/views/register.py
Add flagged redirects for views obviated by registries redesign
* Add redirects behind flag checks
Flag in `resolve_guid` to route to ember added in 21053215a424
None yet, until front-end redesign is complete
None expected
[REG-17](https://openscience.atlassian.net/browse/REG-17)
=> [REG-17] Redirect flags: obviated views -> base guid view

website/static/js/search.js
When we click the institutions link on the search page we want to open a tab to that page instead of filtering the search results for institutions. 
- JS change to make sure link opens when the institutions button is clicked
Go to search page, click the institutions button. if a tab with institutions landing page is opened, then this worked.
🐞 fix, no docs
https://openscience.atlassian.net/browse/PLAT-410
=> [PLAT-410] Add link on OSF Search to Institutions landing page

api/registrations/serializers.py, api/registrations/views.py, api_tests/registrations/views/test_registration_detail.py
Contributors with write permissions weren't being allowed to add tags to a registration because a registration's `permission_classes` included `AdminOrPublic`.
- Change `AdminOrPublic` to `ContributorOrPublic` 
- Move the check for updating privacy to the `update` method to ensure only admins have that power
Users with write permissions should now be able to add tags to a registration.
Are there other things that only admins could do on registrations other than changing private to public? If so, contributors with `write` permissions should now be able to do those things where they could not before. 
https://openscience.atlassian.net/browse/PLAT-1130
=> Allow write contributors to modify Registrations

osf/models/node.py, osf_tests/test_tag.py
When you add tags to a Node they get updated in ES, but not in SHARE. This PR updates SHARE when a tag is added or removed.
- adds `update_node_share(self)` to methods on the AbstractNode model where tags are added/removed.
It's hard to test this locally as you would have to set up and configure your own SHARE instance to test it fully. However, it's simple enough fix that I think we can assume it's updating properly.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-1129
=> [PLAT-1129] Update share when tags are added to Nodes

scripts/remove_after_use/node_preprint_share.py
Preprints that should be in SHARE post-divorce are not there.
Temporary script to run through all the preprints and call update_preprint_share.
Should the preprints query be restricted further? Any other oddities with preprints SHARE that I'm missing? There were some preprints created Friday that were wiped from the db and they were showing up.  @aaxelb removed those.
=> Feature/Add temporary script for updating SHARE. [No ticket yet]

scripts/populate_institutions.py
MQ discovered an issue at their end where attributes were not released as expected. A new metadata has been created with a new entity ID.
@binoculars 
```xml
<MetadataProvider type="XML"
uri="https://mq.okta.com/app/exk2dzwun7KebsDIV2p7/sso/saml/metadata"
backingFilePath="mq-metadata.xml"
reloadInterval="180000" />
```
```xml
<xsl:when test="$idp='http://www.okta.com/exk2dzwun7KebsDIV2p7'">
<id>mq</id>
<user>
<username><xsl:value-of select="//attribute[@name='eppn']/@value"/></username>
<familyName><xsl:value-of select="//attribute[@name='sn']/@value"/></familyName>
<givenName><xsl:value-of select="//attribute[@name='givenName']/@value"/></givenName>
<fullname><xsl:value-of select="//attribute[@name='displayName']/@value"/></fullname>
<middleNames/>
<suffix/>
</user>
</xsl:when>
``` …
=> [OSF Institutions] Update Metadata Entity ID for MQ [SVCS-912] 

requirements.txt
We maintain a few custom forks for decencies we don't have to, so lets see if we can remove them.
- change requirements.txt to remove custom forks
- mdx_del_ins: this had no additional commits, not sure why this was forked
- django-celery-beat: updated to 1.2.0
- django-extensions: updated to 2.1.3
Should be no user facing changes.
technical task, no docs.
https://openscience.atlassian.net/browse/PLAT-1022
=> [PLAT-1022] Remove custom forks where possible

api_tests/registrations/views/test_registration_list.py
Currently sometimes randomly generated factory registration titles coincidently match search terms in our filter tests and cause them to fail. This fixes that.
- change the factory registration names to something not random.
No really testable.
No ticket
=> [Travis Probablistic Failure] TestRegistrationFiltering tests

website/routes.py, website/templates/base.mako, website/views.py
This makes sure custom domains are redirected so they are preserved in the search bar when possible and login attempts redirect back to the correct page.
- @pattisdr's Orignal PR [here](https://github.com/CenterForOpenScience/osf.io/pull/8719) covers most of this, leaving the custom url intact when logged out and redirecting when logged in.
- change I added to login_url so login attempts redirect properly back to the Institutions landing page.
The expected behavior for this ticket changed and the up to date verison is now in the ticket description. 
To test this I had to mock a subdomain locally, so took a test institution, ASU and changed it's custom domain to `http://asu.lvh.me:5000/` this created more or less the same as what you'd see in production with a custom domain.
To clarify …
=> [PLAT-1108][Hotfix] Fix custom institution domain redirects

api/base/parsers.py
Make search behave as expected
* Switch `multi_match` to `query_string`
Should only affect collections search, as only `POST`s to `/v2/search/*` use `SearchParser`
None expected
None
=> [Hotfix] Use `query_string` for collections search

website/templates/nav.mako
To make the sign-up button redirect away from the institution's custom domain.
- small change to nav.mako
You should be able to go to a custom domain, click "Sign-up" and be redirected back to osf.io
https://openscience.atlassian.net/browse/PLAT-1108
=> [PLAT-1108][Hotfix] Custom domain instutions fix sign up button

api/users/serializers.py, api_tests/users/views/test_user_settings.py
POST to `/v2/users/user_id/settings/emails` with a blacklisted email needs to 400 instead of throwing an uncaught 500 error with a message that the email is blacklisted.
Catch BlacklistedEmailError and add a test.
None needed
No docs update needed.
https://openscience.atlassian.net/browse/PLAT-1148
=> Feature/Catch Blacklisted Email Error[PLAT-1148]

website/routes.py, website/templates/nav.mako
When a user is coming from a custom domain currently clicking signup will unhelpfully redirect them back to the dashboard and log them in. This fix logs them in and redirects them back to whatever page they were on.
- simple change to dashboard mako and template
When clicking signup when logged out from a custom domain you should always land back on the page you were on.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-1108
=> [PLAT-1108][Hotfix] Redirect back to institutions landing page after clicking on sign up

api/base/authentication/drf.py, api/base/requests.py, api/base/serializers.py, api/base/views.py, api/requests/views.py, api_tests/base/test_versioning.py, api_tests/nodes/views/test_node_contributors_list.py, api_tests/registrations/views/test_registration_detail.py, api_tests/users/views/test_user_settings_detail.py, requirements.txt
To be on the cutting edge of we got to stay up to late with the latest DRF releases. This PR does that.
Easy stuff:
- DRF has slightly different error messages when something is supposed to be a bool.
- `authenticate_credentials` now takes a request parameter, though we don't use it.
- the browsable API HTML is now formatted in a way that broke tests, but is easily fixed.
Difficult stuff:
- [This](https://github.com/CenterForOpenScience/osf.io/compare/develop...Johnetordoff:upgrade-django-rest?expand=1#diff-b07251433ac329b6b2c079ebe02bf8e0L67) and [this](https://github.com/CenterForOpenScience/osf.io/compare/develop...Johnetordoff:upgrade-django-rest?expand=1#diff-7d5c6cc5fa38ec2cb9834b36dbfab5a4L83) making EmbeddedRequests is now changed because DRF no longer allows you to wrap a DRF …
=> [PLAT-568] Upgrade Django Rest Framework

website/mails/mails.py
change email subjects from "Open Science Framework" to "OSF" to be consistent with our branding
Find and replace
None
https://openscience.atlassian.net/browse/PLAT-1155
=> [PLAT-1155] Update email subjects to OSF

api/nodes/serializers.py
* Fix `current_user_permissions` in the API for nodes where you are a read contributor.
* Visit /v2/users/me/nodes/ and find a project for which you are a read contributor. Note that the "current_user_permissions" attribute is null.
* Visit osf.io/prereg/, click "Preregister a project you have on the OSF" and note that the typeahead field doesn't list your project. Note the error in the console and the error sent to sentry in the networking tab.
https://openscience.atlassian.net/browse/PLAT-1189
=> [hotfix] Prevent current_user_permissions from returning None [PLAT-1189]

framework/auth/views.py, tests/test_views.py
If you try to confirm your ORCID account while logged in the OSF will redirect to the dashboard without confirming the account. This fix allows you to comfirm it without logging out.
- moves redirect clause to after confirmation clause so it's not missed.
- adds test
I tested this in the shell by creating a user with (paraphasing) :
```python 
user.email_verifications = {'token': {'email': user.email, 'external_identity': {'ORCID' {'fake_external_identity_id': 'fake status'}}}}
me.external_identity = {'ORCID': {'fake_external_identity_id': 'fake status'}}
```
and hitting endpoint `http://localhost:5000/confirm/external/<user guid>/token/?destination=dashboard` then checking account setting to see if the user had a confirmed fake ORCID.
🐞 fix, no docs …
=> [PLAT-1145][Hotfix] Confirming ORCID account doesn't work if you are logged in

api_tests/nodes/views/test_node_forks_list.py, osf/models/node.py
Currently the last logged date for forks is incorrect, because logs are are cloned before the "fork created" log is added. This PR fixes that.
- Move save statement to proper place
`node.logs.lastest().date` and ` fork.last_logged` should be the same date. Forked nodes should be listed properly.
https://openscience.atlassian.net/browse/PLAT-1122
=> [Hotfix][PLAT-1122] Fix newly created forks last_logged date 

api/collections/serializers.py, api/collections/views.py, api/nodes/serializers.py, api/nodes/views.py
When users with >1000 go to the My Projects page their collections query times out, so that their bookmarks don't show. This PR attempts to address that.
- adds minor optimizations to
- NodeLinkedRegistrationsList get_queryset
- related counts for linked nodes and registrations
- LinkedNodesList get_queryset
This issue can't be reproduced locally because a local node table is going to be too small to time out. If this is successful endpoints like `/v2/collections/<collection_guid>/relationships/linked_nodes/` for collections with >1000 nodes should load without timing out.
Just want to note that there's no guarantee this will work, I tried to optimize this but I have no way of telling  locally if this will time out. If there was a better way of benchmarking/reproducing …
=> [PLAT-1095] Some users' bookmarks don't load

requirements.txt
**Purpose**
Celery 4.2 contains a regression that causes
celery to disconnect from RabbitMQ
(celery/celery#4355).
**Changes**
* Forked celery
* Created new branch off of v4.1.1
* Backported celery/celery#4278, which
is needed in order to prevent stuck registrations
**QA Notes**
* Make sure that registrations of projects
with many components (>=7) is working as expected
**Ticket**
https://openscience.atlassian.net/browse/PLAT-1186
=> Downgrade to fork of celery 4.1.1

api/collections/serializers.py
Previously there was an issue where bookmark would timeout while loading, this was optimized to be faster, but unfortunately it was faster because the query was incorrect. This fix should fix the related counts query.
- query by the guid rather then the guid id
This will still take a very long time to load for users with >1000 nodes, but it should load without timing out.
🐞 fix no docs.
According to Django debug toolbar this query should take 7000ms
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-1095
=> [PLAT-1095] Fix related counts for collections bookmark issue

framework/auth/views.py, tests/test_views.py
Return `409 CONFLICT` when attempting to register a user with an email address of an existing user.
* raise `http.CONFLICT` when email already exists
* added a test for this
Will be tested in [EMB-347](https://openscience.atlassian.net/browse/EMB-347).
v1 endpoint
None.
https://openscience.atlassian.net/browse/EMB-34
=> [Hotfix] [EMB-347] 409 for existing emails

api/base/settings/defaults.py, osf/metrics.py, scripts/remove_after_use/backfill_elasticsearch_metrics.py
Backfill elasticsearch with PageCounter data for preprint downloads
* Temporarily turn off replication and set refresh_interval to '-1'
* Add script
I will QA this after I run it. Need to make sure that the counts in ES match the ones in Postgres.
```
python manage.py sync_metrics
python -m scripts.remove_after_use.backfill_elasticsearch_metrics
```
Then verify that the counts are consistent with the PageCounter data displayed on the preprint detail pages.
https://openscience.atlassian.net/browse/PLAT-1117
=> [PLAT-1117] Script to backfill elasticsearch metrics from PageCounter

api_tests/waffle/views/test_waffle_list.py, tasks/__init__.py
Waffle tests were failing and commented out, this brings them back into the fold.
- comment tests
- ensure tests account for Flags add through migrations
No user facing changes.
https://openscience.atlassian.net/browse/PLAT-1103
=> [PLAT-1103] Fix waffle tests

requirements.txt
**Purpose**
Currently, elasticsearch 5.4.0 gets installed, even though
pip thinks that 6.3.1 (the correct version) is installed.
```python
>>> import elasticsearch
>>> elasticsearch.VERSION
(5, 4, 0)
```
```
$ pip freeze | grep elasticsearch==
elasticsearch==6.3.1
```
**Changes**
Switch the order of elasticsearch2 and elasticsearch
in requirements.txt.
~~I have no idea why this fixes it...~~
Update: This was caused by an issue with the 2.5.0 distribution: https://github.com/elastic/elasticsearch-py/issues/824 . The 5.4.0 code was accidentally included in the wheel.
**Ticket**
No ticket
h/t @binoculars and @mfraezz
=> Fix installation of elasticsearch==6.3.1

api/base/filters.py, api/chronos/serializers.py, api/chronos/views.py, osf/external/chronos.py, osf/models/chronos.py
Only allow submission to Chronos if a preprint has never been submitted to a journal or the submission has been rejected.
A Chronos submission has four states: drafted, submitted, accepted, rejected. A preprint can be submitted iff there is no Chronos submission or all of the submissions are rejected.
https://openscience.atlassian.net/browse/EMB-409
=> [Chronos][EMB-409][OSF] Put some back-end restricts on what preprints can be submitted to Chronos

api/files/views.py
Using the `v2/files/<file_id>/` for any user that doesn't have permissions for that file will appear to throw a 502 instead of a 403 in the browsable API. This PR fixes that.
- catches PermissionDenied in `get_serializer_class` so the error is serialized properly.
For Devs [this stack overflow question](https://stackoverflow.com/questions/20868189/django-rest-framework-has-object-permission-raising-permissiondenied-exception) has essentially the exact same issue observed here.
❗️There are no additional unit tests for this because it only effects the browsable API.
https://openscience.atlassian.net/browse/PLAT-1188
=> [PLAT-1188] Catch permission denied error which was causing browsable API to break

addons/osfstorage/models.py, addons/osfstorage/tests/test_models.py, osf/models/node.py
When a node is deleted, it was still possible to both visit the landing page and download a deleted file if you had that link saved (or it had been indexed by a search engine).
When a node is deleted, mark those files as deleted as well to avoid this.
- When a node is deleted, delete all its osfstorage files
- Change the definition of `is_preprint_primary` to also check if the node has been deleted, and to not count if it has.
Files on deleted nodes should no longer be able to be viewed or downloaded.
Hotfix, none necessary.
Not sure if changing that definition of `is_preprint_primary` will have side effects, but should be ok, hopefully.
https://openscience.atlassian.net/browse/PLAT-1199
=> [hotfix] Mark all osfstorage files on a deleted node as deleted [PLAT-1199]

package.json, yarn.lock
Upgrade to osf-style 1.8.0. The pinned commit was the head of the develop branch, which has been released and published as 1.8.0.
`yarn upgrade @centerforopenscience/osf-style@1.8.0`
n/a
n/a
n/a
n/a
=> [no ticket] chore: upgrade to osf-style@1.8.0

website/static/js/requestAccess.js
Access request errors weren't making it to sentry because of an incorrect param being sent to Raven. Fix that!
Send update URL to raven message
Errors should now make it thru to Sentry! Hard to reproduce reliably I suppose!
Non needed
No ticket, but here's the Sentry error: https://sentry2.cos.io/cos/osf-front-end/issues/4250/
=> Send correct URL to raven for AccessRequest errors [no ticket]

scripts/populate_institutions.py
Update OSF, CAS and Shibboleth due to metadata change and attributes update.
cc @felliott 
**TEST SERVER ONLY**
@binoculars 
```xml
<xsl:when test="$idp='fsueeit.ferris.edu'">
<id>ferris</id>
<user>
<username><xsl:value-of select="//attribute[@name='mail']/@value"/></username>
<familyName><xsl:value-of select="//attribute[@name='sn']/@value"/></familyName>
<givenName><xsl:value-of select="//attribute[@name='givenName']/@value"/></givenName>
<fullname/>
<middleNames/>
<suffix/>
</user>
</xsl:when>
```
- Add the following to `attribute-map.xml`
```xml
<Attribute name="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" id="uid" />
<Attribute nameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" 
name="http://wso2.org/claims/emailaddress" id="mail" />
<Attribute …
```
=> [OSF Institutions] Update Entity ID for Ferris - Test Server First [SVCS-466]

addons/base/views.py, addons/osfstorage/listeners.py, addons/osfstorage/tests/test_models.py, api/nodes/views.py, osf/models/node.py, osf_tests/test_guid.py, website/project/decorators.py, website/templates/project/view_file.mako
Address things noted by Lauren in https://openscience.atlassian.net/browse/PLAT-1199 - file tree loads forever, deleted files on a private node unexpectedly taking the user to request access, bulk deletes.
- bulk deletes now delete files
- file tree now shows No files instead of infinite loader
- viewing a private file from an unauthorized account 410s, viewing it with perms to the former node shows the graveyard page
Hopefully things noted in the ticket are fixed now!
none
https://openscience.atlassian.net/browse/PLAT-1199
=> Viewing deleted files improvements [PLAT-1199]

tests/test_registrations/base.py, tests/test_registrations/test_embargoes.py, tests/test_registrations/test_views.py, website/project/views/drafts.py, website/static/js/registrationModal.js, website/static/js/registrationUtils.js, website/static/templates/registration-modal.html
paired with @Johnetordoff
**Purpose**
Embargoing a pre-reg currently doesn't work.
This is because the frontend is sending a v2-formatted
payload to a v1 endpoint.
**Changes**
* Modify the draft registration v1 endpoints to take
v2-formatted payloads.
* Disallow partial registrations on the frontend for
preregistrations. This is a hack to avoid adding too
much new code to the v1 endpoints to support partial
registrations.
**QA Notes**
I will test this out on staging1 before it goes to prod.
Need to make sure that embargoing a pre-reg works as
expected.
Some nasty special-casing that can hopefully
go away in the near future when the Prereg Challenge ends
**Ticket**
https://openscience.atlassian.net/browse/PLAT-1254
=> [PLAT-1254] Fix embargoing pre-registrations

website/project/views/node.py, website/templates/project/project.mako, website/templates/project/registrations.mako
Some basic UI changes ahead of groups coming to the OSF. The rest of this ticket was to do some analysis on what else probably should be changed legacy UI wise.
- If there are groups attached to the node, list their names under "Contributors" on the detail page
- If a user is just an admin through a group, do not show actions related to registrations or draft registrations on a node's registration page.
Part of a larger feature, no individual QA needed
Part of a larger feature, no individual docs needed
https://openscience.atlassian.net/browse/PLAT-1194
=> OSF Groups legacy UI [PLAT-1194]

addons/osfstorage/listeners.py, addons/osfstorage/tests/test_models.py
One of the (unwritten?) assumptions of celery tasks is that you shouldn't be performing `UPDATE` queries within tasks, unless they're transacted.
* Add transaction to async updates.
* Optimize query / workflow
* Enqueue task postcommit
None expected
None known
=> [Hotfix] Transact async file deletes

website/project/decorators.py
Revert unfix. Worked locally, but seemed to cause proxying to WB in test env
=> Revert "Merge branch 'hotfix/18.8.1'"

scripts/remove_after_use/update_datacite_dois.py
Script to send updates to Datacite for projects that were updated while the DISABLE_DATACITE_DOIS switch was active.
Start date: Dec 14, 2018 @ 10:09 PM EST = Dec 15, 2018 @ 03:09 UTC
End date: Dec 15, 2018 @ 12:34 PM EST = Dec 15, 2018 @ 17:34 UTC
https://openscience.atlassian.net/browse/PLAT-1273
=> Add script to send updated projects to Datacite [PLAT-1273]

api/base/views.py
To change front-end behavior based on a waffle switch (not a flag, e.g. `enable_inactive_schemas` for prereg winddown), switches need to be exposed in `active_flags` at the `/v2/` root endpoint. It only matters to the front end whether a given feature is on or off, not whether it's governed by a switch, sample, or flag.
Add switches and samples to the list of `active_flags`. This matches [what's included at `/v2/_waffle`](https://github.com/CenterForOpenScience/osf.io/blob/171b95755238dcd449867983029731e6d834ba89/api/waffle/views.py#L74), if that were filtered to only active waffles.
n/a
n/a
Very slightly slower `/v2/` round trip.
https://openscience.atlassian.net/browse/EMB-466
=> [hotfix][EMB-466] Include switches and samples in `active_flags` at /v2/

scripts/remove_after_use/top_100_preprints.py
[#PLAT-1288]
We'd like to know the top 100 downloaded preprints from 2018. Use the nifty new elasticsearch metrics to get those!
**Usage**:
`python -m scripts.remove_after_use.top_100_preprints > top_preprints.csv`
- script to output a CSV 
No QA needed!
Internal one time script, none needed
Nope!
https://openscience.atlassian.net/browse/PLAT-1288
=> Script to create CSV with top 100 preprints by download [PLAT-1288]

api/preprints/serializers.py, api_tests/preprints/views/test_preprint_detail.py
Fix NPD bug - cannot clear all your preprint tags. You can add a tag, remove a tag, but you can't send in an empty list with your preprint payload to clear all tags.
Now you can.
Rabia's notes in ticket should be fine. Thanks for finding this, Rabia!
https://openscience.atlassian.net/browse/PLAT-1283
=> Hotfix/Clear Preprint Tags [PLAT-1283]

admin/users/views.py
>Prevent 502s fetching admin claim links
* Prevent 502s fetching admin claim links
Can be tested by adding an unregistered user to a registration or preprint and trying to get their claim links via the admin module.
None expected
None known
=> [Hotfix] Prevent 502s fetching admin claim links

addons/dataverse/apps.py, addons/dataverse/settings/defaults.py, addons/googledrive/apps.py, addons/googledrive/settings/defaults.py, addons/owncloud/apps.py, addons/owncloud/settings/defaults.py, addons/s3/settings/defaults.py, website/static/js/fangorn.js
The providers mentioned in this ticket need a file size limit to prevent against users taking down OSF with large uploads. Also update the UI for this file size error to be more noticeable in a growler.
**note**: screen shot has a 1GB filesize limit for GD just for demo purposes only, there really is a 5GB limit!
- Add `MAX_UPLOAD_SIZE` for addons as specified in the ticket
- Change max upload size error to Growler rather than file widget error bar
- Remove failed file from UI on file size error
- The new growler should now be universal among all providers that currently already have upload limits.
These are the settings that are defaults for all providers with limits, though they could be different on the staging servers/production!
- box: 250 MB
- dataverse: 2 GB (new)
- dropbox: 150 MB …
=> Limit upload sizes for addons DV, GD, S3, and OC [PLAT-1232]

api/registrations/serializers.py, api_tests/registrations/views/test_withdrawn_registrations.py, osf/models/registrations.py
Currently the tombstone pages for retracted child registrations don't have the info for their parent's retractions. This PR serializes the children so they return the retraction info of the parent.
- makes `withdrawal_justification` and `date_withdrawn` serializer methods
- adds a test 
You should be able to create a multi-node registration, retract that, and then view the children's tombstone with complete info.
None needed.
https://openscience.atlassian.net/browse/PLAT-1200
=> [PLAT-1200] Include withdrawal date, justification for registered children

admin/preprint_providers/views.py, admin_tests/preprint_providers/test_views.py
SHARE's API apparently changed out from under the admin app (sorry), and `preprint_provider.share_source` is no longer set when you click "Setup Share Source".
This syncs expectations back up.
Set `share_source` based on the SHARE source's `longTitle`
Check that `share_source` and `access_token` are both set after clicking "Setup Share Source" for a preprint provider in the admin app.
n/a
=> [fix] Set preprint providers' share_source automatically

api/users/views.py
For the `UserEmailsList` view, `get_default_queryset` was using the email from `user.emails.all()` to determine `is_merged` for emails in `email_verifications`. Whoops!
- Properly iterate over the items stored in `email_verifications`
- Use the `email` key in the detail to determine `is_merge`
This is a bug fix for [a ticket already in QA](https://openscience.atlassian.net/browse/PLAT-1125), so see that one for the actual notes!
None (yet!)
https://openscience.atlassian.net/browse/PLAT-1125
=> Use verification token detail to determine is_merged [PLAT-1125]

api_tests/nodes/views/test_node_draft_registration_detail.py, api_tests/nodes/views/test_node_draft_registration_list.py, website/project/metadata/utils.py
Currently our jsonschema validator will occasionally throw errors, this PR fixes that.
- Makes it so optional singleselect fields work when left empty.
There should be no user-facing changes, but sentry errors should caused by registration's jsonschema validation should cease.
Not user-facing, no docs.
Note: many jsonschema validator errors that appear on Sentry were caused by the Prereg challenge registration and weren't addressed because that schema is no longer being used.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-1265
=> [Hotfix][PLAT-1265] Fix validation of registration schemas 

website/static/js/search.js
Searching OSF side, you can find results that are preprints from all providers. Clicking "Preprints"in the search sidebar to head to SHARE to narrow down the search limits the search to OSF preprints, thus eliminating some search results you saw on the previous page. Get rid of that to show all Preprints like on the search page, not just limiting to OSF preprints.
- Remove `provider=OSF` query param sent to SHARE search
Steps from the ticket are great!
- Select a preprint from a non-OSF provider (PsyArXiv, SocArXiv, EarthArXiv), copy its title
- Paste into legacy OSF elastic search
- Click 'Preprints' from the menu on the left
- The only parameter should now be be the text search query
None needed
https://openscience.atlassian.net/browse/PLAT-1278
=> No longer append provider=OSF to preprint searches on legacy search page [PLAT-1278]

website/templates/project/settings.mako
The institution link just points to the help page, this change points it specifically to the institution's help page.
- simple HTML change
You should be able to click the link pictured on the ticket and go to http://help.osf.io/m/institutions
Doc related.
https://openscience.atlassian.net/browse/PLAT-300
=> [PLAT-300] Fix Institutions settings 'FAQ' link

api/collections/serializers.py
In this [commit](https://github.com/CenterForOpenScience/osf.io/commit/9150172071970baec7e536ee845b0abb29dca4bd), `issue`, `volume` and `program_area` are added to the `CollectionSubmission` model. However in the corresponding serializer's `update` method was not changed to make those fields updatable. This PR fixes that.
=> [No Ticket][Collections][Hotfix] Add program_area, issue and volume to update method

admin/common_auth/forms.py, admin/preprint_providers/forms.py, admin/preprint_providers/urls.py, admin/preprint_providers/views.py, admin/templates/preprint_providers/detail.html, admin/templates/preprint_providers/register_moderator_admin.html
Make a separate view for adding moderators for each preprint providers.
A new view is added for each preprint provider so that OSFAdmin can register users as moderators or admins for the specific provider.
https://openscience.atlassian.net/browse/EMB-410
=> [EMB-410][OSF]simplify how we add moderators/admins to preprint providers

api/actions/serializers.py, api/base/generic_bulk_views.py, api/base/serializers.py, api/base/settings/defaults.py, api/base/views.py, api/collections/serializers.py, api/collections/views.py, api/nodes/views.py, api/preprints/views.py, api/users/views.py, api_tests/base/test_serializers.py, api_tests/collections/test_views.py, api_tests/nodes/views/test_node_linked_nodes.py, api_tests/nodes/views/test_node_linked_registrations.py, api_tests/preprints/views/test_preprint_node_relationship.py, api_tests/registrations/views/test_registration_linked_nodes.py, api_tests/registrations/views/test_registration_linked_registrations.py
Endpoints pointed to by relationship self urls should return Resource Identifier Objects consisting of the resource id and type. In several cases in the API, the resource types are set to the relationship name rather than the type of the related resource. This PR deprecates and versions out the incorrect resource type names.
* add a `get_meta_type()` helper method that will first look for `Meta.type_`, and, if not found, look for `Meta.get_type()` and pass it the current request
* `s/linked_nodes/nodes/` type for node.linked_nodes relationship self endpoint (including tests)
* `s/linked_registrations/registrations/` type for node.linked_registrations relationship self endpoint (including tests)
* add tests for new resource types for registrations relationships 
* …
=> Fix relationship types

addons/base/views.py
OSF was not always getting an int back as the version from WB for metrics tracking for osfstorage files
cast the version to an int before using it to update analytics!
Should just make things work as expected
None necessary
Staging sentry error: 
https://staging-sentry.cos.io/cos/osf-back-end-vu/issues/5054/
=> Make sure version coming back from WB is an int

api/base/settings/defaults.py, api/institutions/serializers.py, api_tests/institutions/views/test_institution_detail.py
Add `logo_rounded` url path for institutions to the api.
- Add `logo_rounded` asset path to institutions.
N/A
https://github.com/CenterForOpenScience/developer.osf.io/pull/40
https://openscience.atlassian.net/browse/EMB-401
=> [EMB-401] Add rounded institutions logo to api

api/files/views.py, api_tests/files/views/test_file_detail.py
The `get_file` endpoint checked for the `is_deleted` property before making sure it was a `BaseFileNode` object - just move that a little bit!
- Move check for `BaseFileNode` above check for `is_deleted`
Visiting a files detail endpoint like `/v2/files/<real_guid>/` with a guid that's not a file (like a user or a node's guid) returns a 404 not found!
Bug fix, no docs needed!
https://openscience.atlassian.net/browse/PLAT-1309
=> Move check for BaseFileNode in get_file, resolves #8888 [PLAT-1309]

api/users/serializers.py, api_tests/users/views/test_user_detail.py, api_tests/users/views/test_user_settings_detail.py
As it stands, it's not possible to complete two factor authentication using the API alone, as the secret you need to provide to a two factor authenticator isn't returned. Let's return it!
- Include the `totp_secret_b32` property in the user settings response whenever two factor is enabled but not confirmed
- Tests for this
- **Bonus:** include user settings relationship on the user serializer so the frontend can get to it!
- **Bonus tests for that too!**
Pretty sure this will be a "tested by the frontend as they make stuff" ticket and won't require anything else fancy!
https://github.com/CenterForOpenScience/developer.osf.io/pull/37
https://openscience.atlassian.net/browse/PLAT-1280
=> Return twofactor secret in API v2 [PLAT-1280]

api/registrations/serializers.py, api_tests/registrations/views/test_registration_detail.py
Registries would like the ability to initiate a withdrawal for a registration via API v2 - let's make that happen!
- Make the `withdrawn` and `withdrawal_justification` fields writable in the registration detail serializer
- Check `validated_data` for the withdrawal fields and update them accoordingly
- Tests to make sure the right things happen
- embargoes get un-embargoed
- withdrawal notification emails go to the right places
- the right errors happen
I imagine this will be one of those things that's QA-ed by the folks using the feature, so no special attention needed at the moment!
https://github.com/CenterForOpenScience/developer.osf.io/pull/36
https://openscience.atlassian.net/browse/PLAT-1275
=> Registration withdrawals with API V2 [#PLAT-1275]

api/registrations/serializers.py
Fixes failing test caused by https://github.com/CenterForOpenScience/osf.io/pull/8868 going in after https://github.com/CenterForOpenScience/osf.io/pull/8836.
Make sure you can still see withdrawal_justification on Registration children.
https://openscience.atlassian.net/browse/PLAT-1275
=> Feature/Follow-Up for Withdrawals via APIv2 [PLAT-1275]

api/identifiers/serializers.py, api/identifiers/views.py, api/nodes/permissions.py, api_tests/identifiers/views/test_identifier_list.py, framework/auth/oauth_scopes.py, website/identifiers/views.py
Allow POSTing to nodes' and registrations' identifiers relationship to request minting a DOI.
/v2/nodes/<guid>/identifiers/
/v2/registrations/<guid>/identifiers/
Right now, only valid to POST with category: 'doi'. Error if the node already has a DOI.
-Added route to v2 that does the same things v1 route did
API only, moves same code that allows us to create a DOI for a project/registration in v1 to v2.
https://github.com/CenterForOpenScience/developer.osf.io/pull/42
https://openscience.atlassian.net/browse/EMB-570
=> Feature/APIv2 Minting DOI's for Nodes and Registrations [EMB-570]

api/registrations/serializers.py, api_tests/registrations/views/test_registration_detail.py
Modify how we're initiating a withdrawal in v2.  Recent PR https://github.com/CenterForOpenScience/osf.io/pull/8868 sets `withdrawn` field to True to start the withdrawal process, but Registries has reported this causes issues Ember-side. We should patch the field that we have the ability to change instantly, "pending_withdrawal".
Update the `pending_withdrawal` field instead of `withdrawn`.  Set `withdrawn` back to read-only. 
None needed - this will be tested front-end with registries
Need to update Erin's documentation here https://github.com/CenterForOpenScience/developer.osf.io/pull/36
https://openscience.atlassian.net/browse/EMB-578
=> Feature/Updates to v2 Withdrawal Initiation [EMB-578][PLAT-1333]

scripts/populate_institutions.py
University of Cape Town (UCT) has migrated their IdP ADFS servers where the main metadata has changed, including the provider's entity ID which is used to build the login URL.
The institution reported that login had been successful on the test server. Similar to https://github.com/CenterForOpenScience/osf.io/pull/8935, this PR targets the production server to finalize the update.
@binoculars 
```xml
<MetadataProvider type="XML"
uri="https://adfs.uct.ac.za/FederationMetadata/2007-06/FederationMetadata.xml"
backingFilePath="uct-idp-metadata.xml"
reloadInterval="180000" />
```
```xml
<xsl:when test="$idp='http://adfs.uct.ac.za/adfs/services/trust'">
...
```
@mfraezz 
https://openscience.atlassian.net/browse/SVCS-960
=> [OSF Institutions] Update IdP's EntityID for UCT - Prod Server [SVCS-960]

api/base/views.py, api/nodes/serializers.py, api/nodes/urls.py, api/nodes/views.py, api/registrations/serializers.py, api/registrations/urls.py, api/registrations/views.py, api_tests/base/test_serializers.py, api_tests/nodes/views/test_node_bibliographic_contributors_list.py, api_tests/registrations/views/test_registration_bibliographic_contributors_list.py
- Add NodeBibliographicContributorsList and RegistrationBibliographicContributorsList.  Requesting bibliographic contributors only is a much more common use case so it's getting its own endpoint
- Two new endpoints: `nodes/<node_id>/bibliographic_contributors` and `registrations/<registration_id>/bibliographic_contributors`.  Only return contributors where visible=True
- Can filter these endpoints on same fields as NodeContributors
No QA needed API only - will be tested with Registries
incoming..
You can now filter RegistrationContributors on permission and bibliographic now that code is being shared a little differently. 
https://openscience.atlassian.net/browse/EMB-579
=> Feature/APIv2 BibliographicContributorsList Endpoints [EMB-579]

osf/models/sanctions.py, tests/test_registrations/test_embargoes.py, tests/test_registrations/test_retractions.py, website/project/views/node.py, website/routes.py
When Registries overview page moves to Ember, many registration links with token query params will no longer work because the registration will be loaded in the Ember app.  Create a new route in the flask app to process the token and then redirect to the registration.
- Affects URLs for approving/disapproving registrations, approving/disapproving embargo, approving/rejecting embargo termination, approving/rejecting retractions.
- These four registration cases should be checked.  Make sure email links work and you are directed to the appropriate location - approving registrations, embargoes, embargo terminations, and retractions. 
https://openscience.atlassian.net/browse/EMB-583
=> Feature/Add URL to Parse Token/Run Registration Handlers [EMB-583]

api/search/views.py, osf/models/node.py, website/search/elastic_search.py
Search by contributors on collections should work.
In `search_fields`, we change `contributor` to `contributor.fullname` because `fullname` is a nested attribute in the ES document.
Add `tags` to the ES document. Update the index upon addition/removal of tags.
https://openscience.atlassian.net/browse/EMB-498
=> [EMB-498][OSF][Collections] Enable search by contributor and by tags.

website/project/views/contributor.py
Generate a correct absolute url for confirmation email sent for claiming unregistered users.
Currently, we pass `_external=True` to `web_url_for`, which will in turn pass that parameter to `flask.url_for` to generate an absolute url. However, according to Flask's [docs for `url_for`](http://flask.pocoo.org/docs/1.0/api/?highlight=url_for#flask.url_for)
> _external – if set to True, an absolute URL is generated. Server address can be changed via SERVER_NAME configuration variable which defaults to localhost.
It seems that `SERVER_NAME` is not defined in our app. It might be defined as an env var on other stagings but certainly not on staging-3 (where current tests are conducted). This explains why `localhost` is used as the domain name in the confirmation email.
Changing `_external=True` …
=> [EMB-519] Change the way we get confirmation url for claim user emails.

osf/management/commands/rebrand_preprint_provider.py
Add management command to rebrand a preprint provider.
Note: some set-up must be done beforehand. See ticket / file docstring.
* Add script
This will be tested on `test-1` before being used on prod.
Verify:
1) old provider disappears
312) modified dates do not change
47) migrated preprints retain subjects, license, etc
9001) migrated preprints show up when searched for (i.e. SHARE reindex works)
6) the redirect from `preprints/<old_provider>/*` to the new provider works
Note: I verified 1-3 locally, but am unable to verify 4 without setting up SHARE or 5 without nginx.
None expected.
[[DEV-297]](https://openscience.atlassian.net/browse/DEV-297)
=> [Hotfix][DEV-297] Rebrand PreprintProvider script 

website/static/css/style.css, website/static/js/pages/base-page.js, website/templates/base.mako
To indicate we no longer support any version of Internet Explorer.
- Add dismiss-able new banner to base page
- generalizes GDPR "cookie banner" code to work for IE depreciation.
Setting up IE on a Mac is a real chore. Install virtualbox then go to https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ to download images to run Windows with IE (These files are huge and take a long time to download.) Also for some reason my IE application wouldn't recognize localhost unless it was written 10.0.2.2 and IE requires you always include the protocol so the full address should read `http://10.0.2.2:5000`.
Also there is a separate ticket for doing this in Ember, so don't go looking for the banner on Emberized pages.
Kinda is docs when you think about it. …
=> [PLAT-1286] IE Depreciation Banner

addons/osfstorage/tests/test_views.py, addons/osfstorage/views.py, api/base/settings/defaults.py, api/caching/settings.py, api/caching/tasks.py, osf/features.py, osf/migrations/0156_create_cache_table.py, osf/migrations/0157_add_storage_usage_flag.py, osf/models/node.py, website/ember_osf_web/decorators.py, website/project/utils.py, website/project/views/node.py, website/static/js/markdown.js, website/templates/project/project.mako
This will show the user how much storage space they are using for on a node.
- adds property `storage_usage` to node
- add caching configuration and migration for cache table
- adds a a signal event to update cache up file change with tests
- adds waffled front-end elements to display total
Bench marked new query here courtesy of Micheal:
```
SELECT SUM("versions__size__sum")
FROM
(SELECT SUM("osf_fileversion"."size") AS "versions__size__sum"
FROM "osf_basefilenode"
LEFT OUTER JOIN "osf_basefilenode_versions" ON ("osf_basefilenode"."id" = "osf_basefilenode_versions"."basefilenode_id")
LEFT OUTER JOIN "osf_fileversion" ON ("osf_basefilenode_versions"."fileversion_id" = "osf_fileversion"."id")
WHERE ("osf_basefilenode"."type" = 'osf.osfstoragefile'
AND "osf_basefilenode"."provider" = …
```
=> [PLAT-1182] Storage usage on project overview

api/providers/views.py, osf/models/mixins.py
Fix request state counts after node-preprint divorce.
Because preprints are no longer tied to a node, `target__node__isnull`, `target__node__is_deleted` and `target__node__is_public` no longer makes sense.
=> [Preprint Withdrawals][OSF][EMB-551] Fix requests state counts after NPD

scripts/populate_institutions.py
Florida State University (FSU) wants to migrate their IdP server from Shibboleth to CAS. Fortunately, institution login remains to use the SAML protocol. A small side-effect of this migration is that the main SAML metadata will be changed during this migration, including the IdP Entity ID which is used to build the login URL. This PR targets OSF test server only to test and verify the new changes while keeping our production server working with the old one.
@binoculars 
```xml
<MetadataProvider type="XML"
uri="https://casqna.fsu.edu/cas/idp/metadata"
backingFilePath="fsu-idp-metadata.xml"
reloadInterval="180000" />
```
```xml
<xsl:when test="$idp='https://idp.fsu.edu'">
<id>fsu</id>
<user>
<username><xsl:value-of select="//attribute[@name='mail']/@value"/></username> …
```
=> [OSF Institutions] Update SAML IdP Entity ID for FSU - Test Server [SVCS-961]

api/users/serializers.py, api_tests/users/views/test_user_settings.py
Ember naturally pluralizes models when sending requests to the API.  The backend should also be pluralized for consistency.
- Pluralize `user_password` to `user_passwords`
- Update test
`N/A`
`N/A`
Will only affect the user settings page when updating password
https://openscience.atlassian.net/browse/EMB-572
=> [EMB-572] Pluralize user_password

api/identifiers/views.py, api/nodes/permissions.py, api_tests/identifiers/views/test_identifier_list.py
Registries tombstone page (overview page for withdrawn registration) needs to show the registration
doi. Currently, `registrations/<guid>/identifiers/` returns unauthorized access error. 
Fix: Allow retrieving identifiers on withdrawn registrations
- Fix `RegistrationIdentifierListView`
If a registration has a DOI, please verify it shows on the tombstone page.
No ticket. minor fix.
=> [EMB-476] Allow retrieving identifiers on withdrawn registrations

osf/utils/machines.py, website/templates/emails/preprint_withdrawal_request_granted.html.mako
Fix email sent to preprint contributors when their withdrawal requests are approved. Currently, if an author submit a withdrawal request before the preprint is published, they will receive an email saying their preprint is removed but a tombstone page exists, which is not the case.
Therefore, we add a new email template for when `ever_public` on a preprint is `False`.
This PR also fixes a bug where in `notify_withdraw()` hook, we are actually not using correct parameters for lookup of `PreprintRequestAction` instances, resulting in incorrect emails to be sent.
Add new email templates.
Change lookup parameters.
https://openscience.atlassian.net/browse/EMB-548
=> [EMB-548][ENG-233][ENG-237][Preprint Withdrawals] Fix email template.

website/static/css/style.css, website/templates/base.mako
COS copyright banner was covering portions of the project.  Fix for https://github.com/CenterForOpenScience/osf.io/pull/8893.
- Make footBanners a class instead of its own tag
- Remove position:fixed.
=> Hotfix/Fix footBanners class [PLAT-1352]

docker-compose.yml
Support local MFR rendering of .docx and other files by updating `docker-compose.yml` to point to location of new LO version in the `unoconv` container.  See:
* https://github.com/CenterForOpenScience/docker-library/pull/49
* https://github.com/CenterForOpenScience/modular-file-renderer/pull/356
This will not be useful until the above are merged.
* The Dockerfiles for unoconv[1] and MFR[2] have both been updated to
pull in LibreOffice v6.1.5.  Support this by updating the path to
LO's python binary.
[1] https://github.com/CenterForOpenScience/docker-library/blob/master/unoconv/Dockerfile
[2] https://github.com/CenterForOpenScience/modular-file-renderer/blob/develop/Dockerfile
No QA needed, local dev only.
No documentation needs to be updated.
None expected, this PR should only affect …
=> [CR]bump libreoffice version in unoconv docker service

osf/models/request.py, osf/utils/machines.py, website/mails/mails.py, website/templates/emails/preprint_withdrawal_request_declined.html.mako
Per product's request, adding new email notification sent to requesters when withdrawal requests are denied.
https://openscience.atlassian.net/browse/ENG-234
=> [ENG-234][ENG-233][ENG-237] Add withdrawal request denied email

osf/models/user.py, osf_tests/test_user.py, scripts/remove_after_use/fix_unmerged_preprints.py, scripts/tests/test_fix_unmerged_preprints.py
Since the PND users who require merges aren't getting their preprints migrated to their primary account, this fix migrates those preprint to the primary account and ensures future merges include preprints.
- adds `_merge_users_preprints` method to user
- adds script for migration `fix_unmerged_preprints`
- adds tests for model and script
We are in touch with effected users and should check with them after this has delpoyed.
🐞 fix, no docs
https://openscience.atlassian.net/browse/ENG-100
=> [Hotfix][ENG-100] Fix merge_user for PND

api/nodes/views.py, api_tests/registrations/views/test_withdrawn_registrations.py
Make institutions endpoint read-only for withdrawn registrations
On a (withdrawn registration) tombstone page, check the console and make sure
no errors (related to institutions) show.
[ENG-176](https://openscience.atlassian.net/browse/ENG-176)
=> [ENG-176] Make institutions endpoint read-only for withdrawn registrations

tests/test_registrations/test_embargoes.py, website/project/views/node.py
Fix for https://github.com/CenterForOpenScience/osf.io/pull/8947
Registries overview is changing the registration approval (and embargo, withdrawal, etc. links).  The reason is the old-style links won't work with emberized pages.   But when we release registries overview, these old links still need to work. Old links expire after 48 hours. 
old style:
`/project/{guid}/?token=<acceptance_token>`
new style:
`/token_action/{guid}/?token=<acceptance_token>`
Restore process_token_or_pass decorator for old link handling.
- We should make registrations and save the approval links right before this goes on test.osf.io (so we have the old links).   On test.osf.io (with front end registries-over waffled off, verify that these old-style links work.  Also make new registrations, and verify that the …
=> Feature/Fix Old Approval Links for Registrations[ENG-419]

api/nodes/serializers.py, api/users/serializers.py, api/users/views.py, api_tests/users/views/test_user_detail.py
We need to be able to change a user's default storage region with the v2 api.
If you update your user with the default_region id, you can change the region your files are stored in by default.
PATCH /v2/users/<user_id>
```json
{
"data": {
"type": "users",
"id": "hcn6t",
"attributes": {},
"default_region": {
"data": {
"id": "ca-1",
"type": "regions"
}
}
}
}
}
```
```
{
"data": {
"default_region": {
"data": {
"type": "regions",
"id": "ca-1"
},
"links": {
"related": {
"href": "http://localhost:8000/v2/regions/ca-1/",
"meta": {}
}
}
}
},
"links": {
"self": "http://localhost:8000/v2/users/hcn6t/",
"html": "http://localhost:5000/hcn6t/"
},
"given_name": "Dawn"
},
"type": "users",
"id": "hcn6t"
},
"meta": {
"version": "2.14"
}
}
```
API-only …
=> Feature/Update User's Default Storage via APIv2 [PLAT-1321]

api/base/throttling.py, api_tests/users/views/test_user_settings.py
The Emberized account settings page needs to be able to get the user emails list without being throttled. The `SendEmailThrottle` throttling class was applied to the `UserEmailsList` view to throttle requests that result in an email being sent. `GET` requests to this endpoint, however, do not send an email and shouldn't be throttled. This PR bypassing throttling for `GET` requests to endpoints using the `SendEmailThrottle` throttling class. These include the `UserEmailsList` view as well as `UserAccountExport`, for which `GET` is not implemented. In addition, the `SendEmailDeactivationThrottle` throttling class inherits from `SendEmailThrottle`, which only sends an email when `PATCH`ing `deactivation_requested`.
* override `allow_request` method on `SendEmailThrottle` class to always …
=> [ENG-434] No throttle user email gets

website/project/views/node.py, website/project/views/register.py, website/views.py
Avoids critical bug while a Front-end fix is implemented
Ensure
1) Registrations reached via means that don't include a VOL route to ember views
2) Registrations reached with a `view_only` param route to old UI
=> [Hotfix] Route Registration A/VOLs to v1 UI

api/nodes/views.py, api/osf_groups/views.py, api/users/views.py, api_tests/nodes/views/test_node_groups.py, api_tests/osf_groups/views/test_osf_group_detail.py, api_tests/osf_groups/views/test_osf_group_members_detail.py, api_tests/osf_groups/views/test_osf_group_members_list.py, api_tests/osf_groups/views/test_osf_groups_list.py, api_tests/users/views/test_user_osf_groups_list.py, osf/features.py, osf/migrations/0167_auto_20190506_1556.py
It will probably be awhile before Groups Front End is out -  in the meantime, it is possible, though unlikely, that people start using Groups endpoints.  Because of a few side effects, like emails being sent, and a few places on emberized front end pages that need special handlings (admin group members shouldn't be able to create  draft registrations for example), waffle off the current groups API endpoints for now.
- Use custom `require_flag` decorator on all relevant methods on the OSFGroup API views to make sure all CRUD operations are blocked
- If hitting an endpoint that is waffled off, you get a 404 `This endpoint is disabled`.
- Add migration to add waffle flag turning off endpoints
- Override waffle flag in tests so API tests are preserved
- I've left the relationship links on …
=> Feature/Waffle off OSFGroups APIv2 Endpoints [ENG-145]

osf/external/chronos.py
Add fields to our payload sent to Chronos.
- Added a comma separated list of tags using the `KEYWORDS` field for the manuscript.
- Added provider information using the `EXTRAVALUES` field for the manuscript.
- Checks whether the OSFUser has both `given_name` and `family_name` defined. If not, serialize `fullname` under the `GIVEN_NAME` field and `null` under the `SURNAME` field.
https://openscience.atlassian.net/browse/ENG-344
https://openscience.atlassian.net/browse/ENG-428
https://openscience.atlassian.net/browse/ENG-483
=> [ENG-344][ENG-428][ENG-483] Add fields to payload sent to Chronos

api/providers/views.py, api_tests/providers/mixins.py, api_tests/providers/preprints/views/test_preprint_provider_licenses.py
Fix filtering on Provider Licenses - 
The provider "acceptable licenses" endpoints don't actually filter when they're supposed to. This already breaks the license picker in collections and will do the same for editable registrations.
Example: https://api.osf.io/v2/providers/registrations/osf/licenses/?filter[name]=aoeuaoeu
- Override `get_default_queryset` instead of `get_queryset`
- Return querysets instead of lists
- Rearrange logic to make it clearer
https://openscience.atlassian.net/browse/ENG-489
=> Feature/APIv2 Cannot filter provider licenses [ENG-489]

addons/bitbucket/api.py, addons/bitbucket/settings/defaults.py
(copied from PR #9019 by @cslzchen without modifications, except renaming branch and asking for merge to develop)
- BitBucket V1 Deprecation:
- https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/
- BitBucket V2 GDPR Update:
- https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/
- https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-workspaces/
- The only V1 usage in OSF is fetching the main/default branch. This dedicated endpoint is no longer available in V2 and does not have a V2 counterpart. Fortunately, we can still obtain it from the repo's own metadata.
- The GDPR update shouldn't affect the OSF side but we are not 100% sure due to BB's ambiguous GDPR docs and migration guide. Added a check and sentry log to the `repos` …
=> BitBucket V1 Deprecation and V2 GDPR Update [ENG-460]

api/banners/views.py, api/base/serializers.py, api_tests/base/test_serializers.py
Dashboard was displaying times incorrectly. The cause was that the `VersionedDateTimeField` was not properly treating versions 2.10 and higher as greater than 2.9, it was treating them as decimals, making them less than 2.2.
The VersionedDateTimeField is configured to display time info with timezone information for versions greater or equal than 2.2, meaning the most recent versions of the API were falling back to old time formatting behavior.
Use StrictVersion on the VersionedDateTimeField to handle more recent versions correctly.
h/t @jamescdavis for helping me troubleshoot and verifying that restoring the timezone designator in v2 will fix dashboard issues.
Verify that the `modified` dates on the dashboard match the `modified` date on the corresponding project page.  Additionally, …
=> Feature/Fix VersionedDateTimeField for Newer Versions [PLAT-1350]

osf/models/node.py, osf_tests/test_node.py
[#PLAT-159]
Forking a project or using a project as a template was not copying over the current users' affiliations. Fix it!
- Add method that copies affiliations from the node to the one it's forking or templating
- Tests to make sure forked and templated nodes have correct affilations
- Have a user with an institutional affiliation
- Be a contributor on a project with at least one affiliation that matches yours, and one that doesn't
- From the project overview page:
- fork the project
- use the project as a template
- Ensure both the fork and template have your affiliations, but not the ones your user doesn't have
This was expected behavior in the first place, so no changes needed
https://openscience.atlassian.net/browse/PLAT-159
=> Add user affiliations when forking or templating [PLAT-159]

api/collections/views.py, api_tests/collections/test_views.py
A request to the CollectedMetaDetail API v2 endpoint will fail `/v2/collections/<collection_id>/collected_metadata/<cgm_id>/` if the cgm belongs to multiple collections. 
Update the CollectionSubmission query on the view (CollectedMetaDetail.get_object()) to query the CollectionSubmission on both the collection and the guid so the query returns one result.
This fixes both descriptions noted in https://openscience.atlassian.net/browse/EMB-554
https://openscience.atlassian.net/browse/PLAT-1305.  Scenarios described there should be sufficient for testing.
https://openscience.atlassian.net/browse/EMB-554
https://openscience.atlassian.net/browse/PLAT-1305
=> Feature/Fix CollectionSubmission APIv2 Query  [PLAT-1305][EMB-554]

osf_tests/test_prereg.py, website/registries/views.py
Currently, the "Sign Up" button on the navbar for Registered Reports and Prereg landing pages does not have campaign query param in it. Users registered by clicking navbar sign up on those pages will not have system tags added to them. This PR fixes the problem.
Override `sign_up_url` for those views.
Make sure `?campaign=prereg` or `?campaign=osf-registered-reports` are included in the link of the navbar sign up button for Prereg and Registered Reports landing pages.
https://openscience.atlassian.net/browse/ENG-99
=> [ENG-99]Override `sign_up_url` for Registered Reports and Prereg landing pages.

api/users/views.py, api_tests/users/views/test_user_settings.py
When clicking the `Do not add` button on the modal after logging in through the confirmation link, the email is not actually removed. This PR fixes the problem.
After the user clicks the link, the `UserEmail` object returned by `get_object` is `confirmed` but not `verified`. So if we are removing the email, we should remove the corresponding key-value pair from `user.email_verification`, which is done by invoking the `remove_unconfirmed_email()` method.
https://openscience.atlassian.net/browse/ENG-450
=> [ENG-450] Check if the email is verified when deleting them.

website/static/js/accessRequestManager.js, website/static/js/requestAccess.js
If `enforce_csrf` waffle switch is turned on, request access to projects doesn't work, and approving a user's request for access doesn't work.  
Fix casing issue.  `osf.ajaxJSON` helper does not add CSRF token info by default, you need to override isCors=true.  We were passing in `is_cors` instead.
- Test that both requesting access and approving a request access works with `enforce_csrf` waffle switch on.
https://openscience.atlassian.net/browse/ENG-516
=> Feature/Fix Request Access requests with CSRF [ENG-516]

admin/templates/nodes/node.html, admin/templates/nodes/spam_status.html, admin/templates/users/user.html
Exposing spam status in user admin app will make it more clear exactly what the user's spam status is, rather than relying on "Is spammy", which accommodates multiple states.  This will also help verify that our schema/data migration from using user system tags to the User.spam_status field was successful.
Display spam status in the same way we display spam status for nodes. DRY up this code to share with node spam status display.
- Verify that spam user system tag pre-migration matches spam status display post-migration
- Do a quick skim over nodes' spam status on the node detail page as well as the user's nodes at the bottom of the user page.  Just make sure it's appearing/behaving as expected.
https://openscience.atlassian.net/browse/ENG-147
=> Feature/Expose User Spam Status in Admin App [ENG-147]

website/conferences/views.py, website/routes.py
Use `/meetings/<meeting_id>` instead of `/view/<meeting_id>` for meeting detail views.
For backwards compatibility, redirect to new one if users goes to the old route.
https://openscience.atlassian.net/browse/ENG-471
=> [ENG-471] Add route redirect

addons/bitbucket/api.py, addons/bitbucket/models.py, addons/bitbucket/tests/utils.py
https://github.com/CenterForOpenScience/osf.io/pull/9024 has expected [the GDPR update removing `username` issue](https://github.com/CenterForOpenScience/osf.io/pull/9024/commits/0332eea245ec7158cb277046a36670be0adaf365) where [repos](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D) and [team repos](https://developer.atlassian.com/bitbucket/api/2/reference/resource/teams/%7Busername%7D/repositories) endpoints may be broken. In short, these two endpoints no longer return the `values.owner.username` field, which is required to build the "username/repo" list when importing addon accounts. This PR fix the problem by using the `values.full_name` field directly instead.
* For both [repos](https://developer.atlassian.com/bitbucket/api/2/reference/res …
=> [ENG-460] Fix Broken Repos and Team Repos Endpoints Due to Bitbucket GDPR Update

osf/external/chronos.py, scripts/clear_chronos_user_id_and_submissions.py
Because we want to also send Chronos the link to supplemental node upon submission, we use the `UNDERLYING_DATASET_URL` field to send that information.
Also unrelated to this ticket, we add a new script to clear `chronos_user_id` field for all `OSFUser` instances, as well as delete all `ChronosSubmission` instances because we need to switch from using Chronos sandbox server to staging server.
Serialize `UNDERLYTING_DATASET_URL` as the preprint sup node's absolute url.
Add a new `clear_chronos_user_id_and_submissions` script.
https://openscience.atlassian.net/browse/ENG-536
=> [ENG-536 ]Add UNDERLYTING_DATASET_URL to payload.

api_tests/identifiers/views/test_identifier_list.py, tests/identifiers/fixtures/datacite_node_metadata.xml, tests/identifiers/fixtures/datacite_post_metadata_response.xml, tests/identifiers/test_datacite.py, website/identifiers/clients/datacite.py, website/settings/defaults.py
Update Datacite test prefix from 10.5072 to 10.70102.  
Datacite has changed the prefix used on Test and Staging Environments for Projects and Registrations to 10.70102. 
Assert that datacite works on staging and test environments again for minting doi's on projects and registrations.
This will probably need a config change from devops. 
https://openscience.atlassian.net/browse/ENG-371
=> Feature/Change Datacite Test Prefix [ENG-371]

api/base/utils.py, api/base/views.py, api/nodes/serializers.py, api/nodes/views.py, api/registrations/views.py, api_tests/nodes/views/test_node_children_list.py, api_tests/registrations/views/test_registrations_childrens_list.py
Now that we're using APIv2 VOL functionality, some gaps in VOL's are being uncovered.  Components do not take into account whether or not there is a view-only link (applies to both nodes and registrations).
- Refactor a BaseChildrenList class to be used in both NodeChildrenList and NodeRegistrationList 
- Modify so that view_only_links are considered when determining if a user can view a component
- (extra) Makes `implicit_contributors` anonymous if viewing a node with an anonymous VOL
- Test that registration components with and without vols behave as expected.
- If a registration has a VOL, but it's components are not included in the VOL, you should *not* see components.  Additionally, the component count should be 0.
- If a registration's components are included in the VOL, their …
=> Feature/APIv2 Components with VOL's [ENG-546]

addons.json, osf/models/external.py, tests/test_oauth.py, website/settings/defaults.py
Some time between 2019/05/31 and 2019/06/04, Bitbucket's OAuth2 API no longer expects non-empty `redirect_uri` **1)** as the query param in the `GET oauth2/authorize` request and **2)** as a field in the body of the `POST oauth2/access_token` request. In addition, it now relies on the "Callback URL" of the "OAuth Consumer" instead of the query param `redirect_uri` to redirect the auth flow after successful authorization.
Bitbucket's [OAuth2 integration guide, last updated on Oct. 2018](https://developer.atlassian.com/cloud/bitbucket/oauth-2/) doesn't mention `redirect_uri` at all. My guess is that they probably changed this a while ago and finally deprecated the old usage early this week. This sudden and unannounced change breaks the `requests_oauthlib` library, which we use to handle …
=> [ENG-580] Fix Bitbucket OAuth2 Issue on `redirect_uri`

api/registrations/serializers.py, api_tests/registrations/views/test_registration_detail.py, osf/models/registrations.py
Make registration category editable via the API
- Add `category` to whitelisted admin writeable fields.
- Add tests
- Please test this along with the frontend [ticket](https://openscience.atlassian.net/browse/ENG-364) that allows registration category to be editable only by the admin.
[ENG-363](https://openscience.atlassian.net/browse/ENG-363)
=> [ENG-363] Make registration category editable

admin/nodes/views.py, admin/templates/nodes/ham_spam_modal.html, admin/templates/nodes/node_list.html
Break out the "Confirm Ham"/"Confirm Spam" buttons and modal dialogs into a template. Add in capability for bulk Confirm Ham operations. 
- Modified admin/nodes.py NodeFlaggedSpamList to add functionality for bulk HAM operations.
- Created admin/templates/nodes/ham_spam_modal.html template for Ham/Spam button and modal.
- Modified admin/templates/nodes/node_list.html to utilize the ham_spam_modal.html template.
Test /nodes/flagged_spam to ensure Confirm Ham and Confirm Spam is working properly.
https://openscience.atlassian.net/browse/ENG-488
=> Feature/flagged nodes confirm ham [ENG-488]

api/base/parsers.py, api_tests/base/test_parsers.py
Modify `JSONAPIMultipleRelationshipsParserForRegularJSON` to have the same handling of list data as the `JSONAPIMultipleRelationshipsParser`.  It currently cannot handle multiple relationships (affiliated_institutions, for example).
- Both parsers should have the same behavior, they just handle different content types - application/json versus application/vnd.api+json.
JSONAPIMultipleRelationshipsParserForRegularJSON given same handling as JSONAPIMultipleRelationshipsParser.
For example, a request that looks like this wasn't working if the Content-Type is `application/json`.  We are trying to support both this and the json-api content-type, `application/vnd.api+json`.
```json
PATCH v2/registrations/xyb6e/
{
"data": {
"id": "xyb6e",
"type": "registrations", …
```
=> Feature/APIv2: Update Parser that handles multiple relationships [ENG-429]

addons/base/views.py
Quick fix for solving sentry error NoneType' object has no attribute 'kind' 
https://openscience.atlassian.net/browse/ENG-425
=> Fix/Sentry Error 'NoneType' object has no attribute 'kind' [ENG-425]

website/project/views/node.py
Project titles are displaying unescaped` &amp;` for &'s in the Make Private/Public modal box. 
Modified website/project/views/node.py to use sanitize.unescape_entities() to replace the `&amp; `with &.
Test the Make Private/Public modal to ensure `&amp;'s` are not displaying.
https://openscience.atlassian.net/browse/ENG-53
=> Fix ampersand displaying as "&amp;" in Public/Private dialog box [ENG-53]

addons/dataverse/requirements.txt
Fix issue in `dataverse-client-python` where dataverses within dataverses can cause a KeyError: 'protocol', because dataverses don't have the protocol key.
Points to latest osf fork of dataverse-client-python since this PR was merged https://github.com/CenterForOpenScience/dataverse-client-python/pull/4
Create a test dataverse on https://demo.dataverse.org/, and then add both a dataverse and a dataset to that top-level dataverse.  (Create the nested dataverse first).   
So I had dataverse Grapes Dataverse, with a Raisins Dataverse and a strawberries dataset.
On the OSF connect your Grapes Dataverse, select your strawberries dataset and hit save.  Before, you would get a key error when the _id property would loop through all the content in Grapes Dataverse (Raisins Dataverse and …
=> Feature/Fix Dataverse Error [PLAT-1328]

website/static/js/contribAdder.js, website/templates/project/modal_add_contributor.mako
We've been seeing DB deadlocks happening due to the v1 contributor endpoint.  While we're not sure of the root of issue, we can probably prevent mitigate it by preventing clickmashing on the add contrib modal.
- Disable the "Add" button after adding contributors in the add contributor modal
- Use the `canSubmit` KO variable
- Start on the "Contributors" page of a node
- Click the "+Add" button
- Search for some new contributors
- Choose a contributor to add
- Click the "Add" button 
Frontend, none needed
https://openscience.atlassian.net/browse/ENG-130
=> Disable Add button after clicking submitting changes [ENG-130]

.travis.yml, requirements/dev.txt, tasks/__init__.py
Tests take time, this speeds them up! 
Testmon speeds up tests by saving checksums of test code and skipping them via pytest if they are unchanged. Because any given PR is going to effect a very small proportion of total tests we can skip a large number (like ~90%) of them most of the time.
If you’re curious/skeptical if/how this is possible, it works with the coverage.py pytest plugin, which is stable and commonly used. It however has some limitations which are detailed [here](https://coverage.readthedocs.io/en/latest/trouble.html).
Our implementation of testmon runs during a travis build meaning each branch will get a seperate sqllite db that is cached by Travis between builds. This means you will have all the test info from the default branch from the first time you test and test info …
=> [ENG-123] Use testmon for travis

api/base/serializers.py, api/chronos/serializers.py, api_tests/chronos/views/test_chronos_submission_list.py
Only show `submission_url` if the user is the submitter.
Add `ShowIfChronosSubmitter` conditional field and make use of that field.
Add tests.
Nothing for this backend PR. See frontend counterpart for testing info.
https://openscience.atlassian.net/browse/ENG-586
=> [ENG-586] Add ShowIfChronosSubmitter conditional field

website/static/js/fangorn.js
Currently fangorn on staging can't handle creating dialogs for 202 it skips modals 
This:
Becomes this:
(dialog boxes aren't timed)
Testing this now should be the same, just expect modals as opposed to dialog boxes.
https://openscience.atlassian.net/browse/ENG-142
=> [ENG-142] Fix Fangorn rate throttling 202s

website/static/js/fangorn.js
Info boxes are supposed to be blue, not red!
Simple JS change
Just makes them blue!
https://openscience.atlassian.net/browse/ENG-142
=> [ENG-142] Make growlboxes blue for fangorn throttle issue

api/collections/serializers.py
Somehow, `collected-metadata` is not a relationship on the `collection` serializer. This PR adds that relationship.
https://openscience.atlassian.net/browse/ENG-261
=> [ENG-261] Add collected-metadata relationship to collection serializer.

api/chronos/serializers.py, api_tests/chronos/views/test_chronos_submission_detail.py
`ChronosSubmissionDetailSerializer` was meant to be used by `ChronosSubmissionDetail` view to provide an endpoint for getting the current Chronos submission status from Chronos API, instead of updating submission info, because an OSFUser does not (and should not) have any ways to update submission information through our API.
Therefore, instead of invoking `update_manuscript()` in `update()` hook of the serializer, we call `sync_manuscript()` instead.
No QA for the backend ticket. See front-end ticket for QA notes.
https://openscience.atlassian.net/browse/ENG-650
=> [ENG-650] Use sync_manuscript for ChronosSubmissionDetailSerializer

osf/management/commands/check_crossref_dois.py, osf_tests/management_commands/fixtures/crossref_works_response.json
Fix the problem where too many pending DOIs would create a really long URIs that would break things.
- limited requests to 20 preprints at a time.
No new QA notes
🐞  fix, no docs.
=> Make DOI tasks check crossref in batches

.travis.yml, api/base/urls.py, api/base/views.py, api/institutions/authentication.py, api/waffle/utils.py, api_tests/conftest.py, api_tests/institutions/views/test_institution_auth.py, api_tests/waffle/views/test_waffle_cookies.py, conftest.py, framework/auth/views.py, osf_tests/test_waffle.py, tests/test_auth.py, tests/test_ember_osf_web.py, website/ember_osf_web/decorators.py, website/ember_osf_web/views.py, website/profile/utils.py, website/profile/views.py, website/project/metadata/utils.py, website/project/views/node.py, website/project/views/register.py, website/routes.py, website/settings/local-travis.py, website/templates/base.mako, website/views.py
Currently our waffle flags don't really work as expected, because we are using some Flask elements django-waffle doesn't properly append a `set-cookie` head to the request object. This means we can't distinguish users on an individual level.
- Hack-y fix of `OsfWebRender` which imitates waffle middleware
- tests
When testing this issue you must be aware of 4 things!
- Check for superuser-hood!
- The flags are cached when check `is_active`! always check you have the correct flag with ` python manage.py waffle_flag <flag_name>`,  r
- Be very carefully with your flags because their attributes are inconsistent, for example `everyone` will override all other options whether it is False or True, or attributes like `authenticated` don't work this way.
- You can't set a cookie until you visually …
=> [ENG-643] Get Waffle Cookies working!

api/requests/views.py, api_tests/requests/mixins.py, api_tests/requests/views/test_request_action_list.py
Preprint admins need to be able to view preprint request actions to be able to see that a withdrawal request was rejected and view the rejection reason.
#8585 originally added this endpoint and restricted it to moderators (which satisfied the only use-case at the time).
Change required permission on `PreprintRequestActionList` view to `PreprintRequestPermission`, which includes moderators and preprint admins.
This should be tested as part of re-testing [ENG-559](https://openscience.atlassian.net/browse/ENG-559).
N/A (request actions are not documented)
None expected.
https://openscience.atlassian.net/browse/ENG-736
=> [ENG-736] expose preprint request actions to Preprint admins

osf/management/commands/data_storage_usage.py, website/settings/defaults.py
Make it so the right metrics scripts run properly during their celery beat.
1. Ensure the script has access to remote base folder regardless of where it's called from
2. Import the management commands to celery
3. Disable running keen snapshots by default (because they are slow)
No QA
Anything that might have relied on being able to pass in the folder rather than using website settings will no longer work.
N/A
=> Update metrics scripts

api/institutions/authentication.py, api/institutions/views.py
PR https://github.com/CenterForOpenScience/osf.io/pull/9084 and one of its commit https://github.com/CenterForOpenScience/osf.io/commit/6e65c870bd67b8f4d034706f0cea3d6243643f86 break institution login. Here is the sentry error: https://sentry2.cos.io/cos/osf-back-end/issues/20047/.
Only new accounts (first time institution login users that does not have an institution account) are affected since the broken piece is the confirmation / welcome email sending.
* Revert the change in `api/institutions/authentication.py`.
* Add comments that briefly explain what the endpoint does and a warning that encourages developers to check with code owners before making future changes.
* No test changes.
QA is not needed.
No
No
https://openscience.atlassian.net/browse/ENG-765
=> [HotFix] Fix Institution Auth API [ENG-765]

osf/models/analytics.py
Improvements to allow the new PageCounter columns to be populated over time.  Current PR has a line that assumes all columns have been populated, but this isn't going to be True on production immediately.  
https://github.com/CenterForOpenScience/osf.io/pull/8800 (Part 1 of Page Counter migration) adds four new columns to the PageCounter table - `file`, `record`, `version`, and `action`.  Because the `PageCounter` table is enormous, the intent of that work is to populate the table over time, no downtime required.  So for the time being, we need to write to five fields when this record is created, `file`, `record`, `version`, `action`, and the original `_id`.  After all fields have been populated, we can stop writing to `_id`.  Current page counter work is attempting to lookup PageCounter …
=> [Needs Migration Prep] Feature/PageCounter Part I Fix [ENG-122][ENG-751][ENG-752]

osf/management/commands/migrate_pagecounter_data.py, website/settings/defaults.py
Adding a beat job that's currently unscheduled to run page counter management command.  This management command is going to populate the new columns in the PageCounter table over time, rather than taking downtime to this. We'll run it manually a few times, and determine what the schedule should be based on resource usage, etc
https://openscience.atlassian.net/browse/ENG-122
=> Feature/Beat Job for Page Counters[ENG-122]

api/base/settings/defaults.py, api/taxonomies/serializers.py, api_tests/collections/test_views.py, api_tests/nodes/views/test_node_detail.py, api_tests/registrations/views/test_registration_detail.py, api_tests/subjects/mixins.py, api_tests/subjects/views/test_subject_detail.py
Followup for https://github.com/CenterForOpenScience/osf.io/pull/8948 
New API versions have been added since this PR was written. Bump API version to 2.16 that will start serializing subjects as relationships.  Earlier versions pre-2.16 should still serialize subjects as attributes.
- Reduce hardcoding 
Adding PR for dev docs for versions 2.15 and 2.16 -
https://openscience.atlassian.net/browse/ENG-161
=> Feature/Bump Version to Serialize Subjects as Relationships [ENG-161]

osf_tests/test_elastic_search.py, scripts/populate_institutions.py
Rewrite the institution population scripts so that we can update or create only the institution(s) we need instead of applying to all every time the script is run. In addition, this solves the sync issue between the script and the admin app mentioned in [OSF-PR#9118](https://github.com/CenterForOpenScience/osf.io/pull/9118). Finally, the script was poorly written only as a temporary script but ended up being used until now, which desperately needs a decent upgrade.
cc @mfraezz 
* Use `argparse` ([Python 2.7.16 Version](https://docs.python.org/2/howto/argparse.html)) for handling command line arguments. Here is the `--help` on `scripts.populate_institutions.py`.
```
docker-compose run --rm web python -m scripts.populate_institutions --help
usage: populate_institutions.py [-h] [-e ENV] [-i …
```
=> [OSF Institutions] Fully rewrite the institution populating script [ENG-771]

framework/auth/cas.py, framework/auth/views.py
When logging in from osf.io/forgotpassword, after successfully logging in, the user is redirected back to /forgotpassword, which logs the user out.
/framework/auth/cas.py has been changed to redirect back to dashboard instead of forgot password for the service url.
- Verify clicking on Sign In button from forgot password page navigates you to dashboard after typing in your credentials
- Verify same behavior on reset password page (this is the email link you get from the forgot password page) - osf.io/resetpassword/<user_id>/token/
https://openscience.atlassian.net/browse/ENG-49
=> Reset Password page breaks login page[ENG-49]

README-docker-compose.md
[OSF-PR-#9127](https://github.com/CenterForOpenScience/osf.io/pull/9127) / [ENG-771](https://openscience.atlassian.net/browse/ENG-771) rewrote the [institution populating script](https://github.com/cslzchen/osf.io/blob/master/scripts/populate_institutions.py) and changed how it is used. Thanks @corbinSanders for pointing it out that I need to update the `docker-compose` README.
cc @mfraezz I targeted this PR to `master` but feel free to change it to `develop` if you prefer.
Updated the command to run for populating institutions during OSF setup. It uses `test` environment and run for **all** institutions.
N / A
N / A
N / A
=> [No Ticket] Update docker-compose README on populating institutions

admin/preprints/views.py, admin/templates/preprints/preprint.html, admin_tests/preprints/test_views.py, osf/models/mixins.py, tests/test_preprints.py
Currently, when preprint providers are changed in the admin app, subjects stay the same, even though they might be a part of the custom taxonomy for the old provider. 
- admin/preprints/views.py modified to include a function to find and update the subjects for a preprint upon provider change. If a subject cannot be found in the new provider taxonomy, the old subject is retained, and a warning message is displayed.
- admin_tests/preprints.test_views.py modified to test the above feature.
- admin/templates/preprints/preprint.html modified to enable the displaying of warning messages when subjects cannot be mapped.
Test changing providers within the admin app for a preprint.
There should not be any side effects. Worse case if a subject with a mapping isn't found, then it simply retains the …
=> [ENG-664] Change subjects on provider change

addons/gitlab/api.py
Enable the GitLab addon to access all GitLab projects that the user is a member of. Previously, the addon was limited to GitLab projects that the user is the owner of.
Modifies the function that retrieves projects to use the general purpose project endpoint with a membership requirement as opposed to using the user/projects endpoint.
Testing the GitLab add on and ensuring that users are able to access GitLab projects they own as well as GitLab projects that they do not own but are members of would be beneficial. 
I tested this locally using two separate GitLab accounts. 
N/A
N/A
https://openscience.atlassian.net/browse/ENG-691
=> [ENG-691] Enables gitlab addon to access all gitlab projects with user membership

api/base/filters.py, api_tests/base/test_filters.py
Currently, all sorting must be done on the model name. This is not intuitive to a user as some fields such as date_created have a source of created.
api/base/filters.py - Modifying OSFOrderingFilter to support sorting on serializer fields.
api_tests/base/test_filters.py - Adding tests to ensure ordering is working correctly
Test ordering on models with ?sort=date_created. The order should match ?sort=created
There is currently no documentation on parameterized sorting in the documentation. Perhaps there should be?
Sorting by source name was not deprecated, so side effects should be minimal
https://openscience.atlassian.net/browse/ENG-61
=> [ENG-61] Fix sorting on serializer fields with source attributes

api/addons/serializers.py, api/base/renderers.py, api/base/serializers.py, api/base/settings/defaults.py, api/base/versioning.py, api/comments/serializers.py, api/files/serializers.py, api/nodes/serializers.py, api/schemas/serializers.py, api/users/serializers.py, api_tests/base/test_serializers.py
The JSON API v2 had inconsistent casing for types. Some were snake_case, and others were kebab-case. This pull request creates a new API (2.18) which makes all types kebab-cased. This API will accept both kebab, and snake, but will throw a deprecation warning when a snake cased type is submitted.
- addons/serializers.py, base/serializers.py comments/serializers.py, files/serializers.py, nodes/serializers.py, and users/serializers.py: Modified Meta class to check for version, and provide kebab-cased type.
- base/renderers.py: Modified JSONAPIRenderer.render to add the deprecation warning to the response.
- base/serializers.py: Modified class TypeField to accept both kebab and snake case for version for 2.18 and after
-schemas/serializers.py: Modified Meta classes to check for version and …
=> Using consistent kebab-cased type names [ENG-131]

docker-compose.yml
Allow running the `unoconv` container in local development once https://github.com/CenterForOpenScience/docker-library/pull/51 is merged.
The unoconv image MFR needs to convert Word docs to pdf has been updated to be based off of Debian buster and to install libreoffice via apt-get.  As a result, the invocation to start unoconv has changed.
* Update the path to the python binary.  Debian's libreoffice does not come with its own python.
* Set the `UNO_PATH` envvar so `unoconv` can find the libreoffice installation.
QA not needed.  This change only affects devs running unoconv locally.
No docs to update.
None expected!
https://openscience.atlassian.net/browse/ENG-379
=> [ENG-379] support buster-based unoconv image (dev-only change)

api/registrations/serializers.py, osf/utils/registrations.py, website/project/views/node.py
Follow-up to #9170 -- apply the same to APIv1
Strip out prereg challenge comments from registrations' `registered_meta`
=> [hotfix][no ticket] strip comments from registered meta (APIv1)

docker-compose.yml
`invoke assets -w` fails with a unicode error -- Unsure of the root cause (possibly webpack speaking the non-ascii rune `…` aloud?) but @felliott found a workaround.
Set `LANG=en_US.UTF-8` for `assets` and `admin_assets` containers in our docker-compose.yml. This avoids the problem in the common case, for now.
=> [no ticket] avoid encoding error in assets containers

.gitignore, scripts/EGAP/create_EGAP_json.py, scripts/EGAP/egap-registration.json, scripts/EGAP/egap_workflow.ipynb
Create an EGAP Jupyter Notebook capable of running the scripts for the EGAP migration
1. Un-DRY the first script to remove the need to have the entire OSF running just to run this migration.
2. Make the script work with Python 3 (which current versions of Jupyter require)
3. Add notebook
4. Copy EGAP Schema to EGAP scripts directory
5. Ignore iPython checkpoint files in git
_No, this is mostly an aid for testing_
_Low_
_No_
_Additive_
_By running the notebook_
- If verifying through API, what's the new version? Please include the …
=> [ENG-1177] EGAP Notebook

api/base/authentication/drf.py, api/institutions/authentication.py, api_tests/institutions/views/test_institution_auth.py
Improve institution SSO with inactive user accounts.
* ~~This PR only touches the institution auth api,~~ This PR's primary change touches the institution auth API, which only affects  and can only be tested on `test` and `prod`. Thus, this PR targets `master` as a `hotfix`.
* The secondary change that updated [`drf.check_user()`](https://github.com/CenterForOpenScience/osf.io/blob/develop/api/base/authentication/drf.py#L43) to check unconfirmed status for users created by ORCiD login. This is such a trivial change that shouldn't affects the PR's eligibility for being a `hotfix`.
* Fixed an issue where there is a chance that users are not saved after register
* Take care of inactive users during institution auth
* Unclaimed: clear records, set full name, set usable password and register
* …
=> [ENG-1134] [OSF Institutions] Institution SSO with Inactive Accounts

scripts/EGAP/EGAP_tests.py, scripts/EGAP/create_EGAP_json.py
Adding in required checking for EGAP registrations
Modifying create_EGAP_json.py  to do a final validation against the schema for required fields. If there is required fields missing, a file tree is not created, and the project ID is entered into errors.txt. 
Ensure that a file structure is not created for any errored out projects.
N/A
N/A
https://openscience.atlassian.net/browse/ENG-893
=> Adding in required field checking

scripts/populate_institutions.py
California Lutheran University decides to switch from CAS-based SSO to SAML-based SSO. The PR takes care of the `test` server.
As far as institution login is concerned, `test` and `prod` CAS / Jetty share same code (i.e. `master` branch) and some hard-coded configuration (i.e. sprint configuration, CAS attribute map, etc.). It is possible but inconvenient to switch only `test` without affecting `prod`. This is why this PR adds `callutheran2` as a new institution with a different auth but the same assets. Another benefit is that we can keep both SSO alive at the same time.
A new institution `callutheran2`.
N / A
N / A
N / A
No ticket but relates to: https://openscience.atlassian.net/browse/ENG-1110
=> [No Ticket] [OSF Institutions] California Lutheran University w/ SAML SSO

osf/management/commands/import_EGAP.py
make sure the ingest can deal with temporary directory 
- add code to `get_egap_assets` code
- No new details should work now.
Not user-facing
None
=> Fix ingestor

osf/management/commands/import_EGAP.py
There's a mutable argument which is holding up the EGAP migration.
Make mutable argument non-mutable.
Draft registrations for EGAP projects should have all their appropriate files.
None
=> [No Ticket] Remove mutable argument for EGAP

osf/management/commands/import_EGAP.py
Makes the registration creation process in EGAP non-atomic due to a race condition between the registration object being saved to the database and archiver beginning to archive the node. 
* Removes the use of an atomic transaction around the `register_silently`
Testing will be wrapped into general EGAP testing
=> EGAP Import: Ensure Registration object is created before archiver begins

osf/utils/migrations.py
the new EGAP registration has questions of format `'textarea'` and type `None`, and this is new. It breaks the schema block migration.
=> [fix] handle special question format/type for EGAP

website/project/metadata/osf-standard-2.json
To change the `title` and `description` text in `osf-standard-predata` to match new wording.
- Update the `osf-standard-predata` schema
Should be tested to make sure wording is accurate against the new changes.
`N/A`
`N/A`
`N/A`
=> [Feature] Update osf-standard-predata schema text

website/project/metadata/aspredicted.json
To change the `title` and `description` text in `aspredicted` to match new wording.
- Update the `aspredicted` schema
Should be tested to make sure wording is accurate against the new changes.
`N/A`
`N/A`
=> [Feature] Update aspredicted schema text

website/project/metadata/osf-open-ended-2.json, website/project/metadata/osf-open-ended-3.json
- Update the wording of the Open-ended Registration Schema.
- Make question required
- Removed redundant question header
- Update description text
- make question required
- Since the question was made to `required` there may be some issues with existing registrations. If it breaks some registrations, this (input required version) may need to be added as a new schema
N/A
- Potential weirdness with existing registrations that have no content
- Since the question heading is now removed, this may cause visual weirdness potentially?
N/A
=> Update wording for Open-ended schema

api_tests/nodes/views/test_node_draft_registration_detail.py, api_tests/nodes/views/test_node_draft_registration_list.py
To update the tests using the `osf-standard-predata` schema
- Update wording in `test_node_draft_registration_detail.py`
- Update wording in `test_node_draft_registration_list.py`
`N/A`
`N/A`
`N/A`
`N/A`
=> [Fix] osf-standard-predata tests

scripts/populate_institutions.py
Add University of British Columbia - Prod Server Only
cc @mfraezz 
- Auth is SAML2 / Shibboleth, IdP is not in InCommon and IdP has customized attributes.
```
<xsl:when test="$idp='https://authentication.ubc.ca'">
<id>ubc</id>
<user>
<username><xsl:value-of select="//attribute[@name='mail']/@value"/></username>
<fullname><xsl:value-of select="//attribute[@name='displayName']/@value"/></fullname>
<familyName/>
<givenName/>
<middleNames/>
<suffix/>
</user>
</xsl:when>
```
```
<MetadataProvider type="XML"
uri="https://authentication.ubc.ca/idp/shibboleth"
backingFilePath="ubc-idp-metadata.xml"
reloadInterval="86400" />
```
```
<Attribute name="urn:oid:1.3.6.1.4.1.60.1.7.1" name="ubcEduPersistentID" id="persistent-id"/>
```
</br>
FYI, here is the …
=> [ENG-888] [OSF Institutions] Add University of British Columbia - Prod

website/project/metadata/osf-open-ended-3.json
Change structure of V3 open-ended schema.
Put text input and file input directly under `questions` property of schema
There should be no duplicate text when viewing the open-ended schema. Please verify that this is the case :)
=> Place text area and file input directly under `questions` field

osf/management/commands/migrate_registration_responses.py, osf/migrations/0193_migrate_registered_meta.py
Avoid an error when migrating registration responses -- historical models in django don't have custom managers, so `Registration.objects.all()` will apparently return `Node`s of *any* type, not just `Registration`
In code used by migrations, use `AbstractNode` filtered by `type='osf.registration'` instead of `Registration`.
=> fix: avoid using typedmodels in migrations

website/project/metadata/registered-report-3.json, website/project/metadata/registered-report.json
Fix a typo.
Update descriptions text in both versions of the Registered Reports schema.
Low risk.
n/a
n/a
n/a
=> fix: registered-report schema typo

website/project/metadata/osf-preregistration.json
Fix issues found in osf-preregistration schema.
* revert changes to option text
* typo in Indices description
* typo in Transformations description
* typo in Randomization description
This should fix all issues with OSF Preregistration noted [here](https://www.notion.so/cos/Schema-Blocks-and-Text-Changes-Final-Sweep-of-Registries-Submission-Testing-af5ec50fda0c4b61ab75fd8ca369d649).
n/a
n/a
n/a
=> osf-preregistration schema fixes

requirements/constraints.txt
There is a problem with conflicting requirements that has creep up and is causing Travis to fail.
- pin coverage version to 4.0.3
No new QA activity needed.
None
=> [Hotfix] Pin coverage to prevent travis issue

osf/management/commands/import_EGAP.py
EGAP files are not functioning properly on registration pages. What was being returned by water butler did not have the required information for the archiver, causing KeyErrors.
Made changes to the import egap script to provider archiver with the necessary field data.
-This does not require a data migration. The data will be fixed by a re-import of EGAP
-Level of risk
-There is no risk. No permissions code is touched. This is an additive change.
-Ensure file links are working properly now on the EGAP schema. This only affects the EGAP registrations, not any other registrations. Fixes for other registration schemas are coming in another PR.
-Performance should be not affected upon testing.
N/A
Shouldn't be
https://openscience.atlassian.net/browse/ENG-1375
N/A
=> [ENG-1375] Adding in logic for metadata population

osf/migrations/0083_add_ember_waffle_flags.py
Fix a broken waffle flag when running migrations
Added a missing `,` in `EMBER_WAFFLE_PAGES`
Should fix the waffle flag that comes out as `ember_edit_draft_registrationfile_detail_page` (Big thanks to @adlius !)
`NA`
`NA`
`NA`
`NA`
=> fix typo in waffle flag pages

osf/models/provider.py
Preprint providers are being listed as thier abstract class name, not thier `__str__`.
- fix out dated python 3 dunder.
No migrations just check the list.
https://openscience.atlassian.net/browse/ENG-1418
=> [Hotfix][ENG-1418] fix python 2 error for preprint provider.

api/caching/tasks.py, api_tests/wb/views/test_wb_hooks.py
Replacing the naive query with a SQL query to optimize tasks.update_storage_usage_cache, as this is run frequently and is inefficient.
- api/caching/tasks.py - Modifying update_storage_usage_cache to use a more efficient query.
- I tested this by calling update_storage_usage_cache directly in the shell then making sure the set amount was correct.
-Ensure this is calculating file size correctly, specifically after moving/copying files.
N/A
Should not be any
https://openscience.atlassian.net/browse/ENG-1046
=> Optimizing query for tasks.update_storage_usage_cache [ENG-1046]

README-docker-compose.md
The readme for docker-compose is outdated due to Python 3. `python` is no longer available in the containers: `web`, `api` and `worker`. We must use `python3` when running scripts and migrations.
```
bash-4.4# which python
bash-4.4# which python3
/usr/bin/python3
bash-4.4# ls -la $(which python3)
lrwxrwxrwx    1 root     root             9 Jan 16 16:13 /usr/bin/python3 -> python3.6
bash-4.4# ls -la /usr/bin/ | grep python
lrwxrwxrwx    1 root     root             9 Jan 16 16:13 python3 -> python3.6
-rwxr-xr-x    2 root     root         14144 Oct 17 11:13 python3.6
-rwxr-xr-x    2 root     root         14144 Oct 17 11:13 python3.6m
```
Instead of modify the docker file to create a soft link for `python`, we decided to simply update the guide. 
* Updated all scripts and migration commands …
=> [No Ticket] Update docker-compose readme to use python3

website/conferences/utils.py
Currently meeting nodes are being created without their file attachements, this fixes that.
- decodes cookie so it's valid for WB
- add raise_for_status so this won't fail silently anymore
You should now be able to attach a file to an email and use that to create a meeting node with that attachment uploaded.
Since this will now throw errors when it fails, we may see new previously occuring, but unreported errors, random 500s etc. 
https://openscience.atlassian.net/browse/ENG-1432
=> [Hotfix] Fix meeting emails Python 2 problem

osf/management/commands/import_EGAP.py
Folders in EGAP projects were causing the import EGAP script to fail. These aren't necessary, for the metadata, so we'll just remove them. Some emails were also failing out, so I added some trimming for those. Also added a .sort() to the directories so they would process in order of directory name
Various fixes in import_EGAP.py
Nope
Shouldn't be any
No
Mostly additive. Adding functionality to remove any folders from the metadata, as well as additional email grooming.
Ensure links to files are still working in the metadata.
- If …
=> [ENG-1437] EGAP emails folders fix

api/metrics/views.py, api_tests/metrics/test_preprint_metrics.py
Fix the composite queries for Courtney's ES endpoint.
- removes seemingly extraneous `update_from_dict` from Elastic API view
No migrations, not user-facing, Courtney should now be able to make composite queries with Elasticsearch. 
Some code comments 
https://openscience.atlassian.net/browse/ENG-814
=> [ENG-814] Fix composite queries for ES and add tests.

api/base/serializers.py
With recent  ember-data upgrade, this inconsistency in resource types is not taken lightly and causes undesirable issues on the front-end.
- Update base serializer to return `user-settings` (instead of `users`) as type for user_settings relationship.
- This change should fix issues outlined in on the frontend.
[ENG-1462](https://openscience.atlassian.net/browse/ENG-1462)
[ENG-1482](https://openscience.atlassian.net/browse/ENG-1482)
=> [ENG-1462][ENG-1482] Return proper type for user::user-settings relationship

api_tests/registrations/views/test_registrations_childrens_list.py, osf/models/node.py, osf_tests/test_node.py
Fixing anonymous view only links results.
Editing osf/models/node.AbstractNodeQuerySet.can_view to fix issues with set union operator.
Does not require data migration
Might affect other view only links, but shouldn't
No
Additive and subtractive. Modifying logic.
Run API tests.
No new version. Endpoint /v2/registration/{reg_id}/children
--> …
=> [hotfix] Fixing set unions in can view

docker-compose.yml
* WB is now based off of python3.6. Update wb* services to reflect this.  To set up your new WB, run the following:
$ docker-compose pull wb_requirements
$ docker volume rm osfio_wb_requirements_vol
$ docker volume rm osfio_wb_requirements_local_bin_vol
$ docker-compose up wb_requirements
You may need to stop/remove the existing wb/wb_worker containers in order to remove the old volumes.
=> [CR] Update docker-compose to support wb-oathpit

scripts/populate_institutions.py
Boys Town has a special case that they want 1) users to start from their "MyApps" for login and 2) users being redirected back to "MyApps" after logout. We are enabling this feature on the test server for them to test.
- Login
- Logout
- Replaced `https://test.osf.io/goodbye` with `https://myapps.microsoft.com`
cc @mfraezz 
Add a dedicated logout URL for BT to test.
> This would be a log out of OSF then go to https://myapps.microsoft.com and stay logged into this.  We can test this and if it works that’s great.
Boys Town will test this feature.
N / A
N / A
N / A
=> [No Ticket] Logout URL for Boys Town

scripts/populate_institutions.py
Boys Town has a special case that they want 1) users to start from their "MyApps" for login and 2) users being redirected back to "MyApps" after logout. Test server works as expected so we move forward to production. See https://github.com/CenterForOpenScience/osf.io/pull/9301
- Login
- Logout
- Replaced `https://test.osf.io/goodbye` with `https://myapps.microsoft.com`
cc @mfraezz 
Add a dedicated logout URL for BT prod.
Boys Town will confirm this feature on prod.
N / A
N / A
https://openscience.atlassian.net/browse/ENG-1560
=> [ENG-1560] [OSF Institutions] Logout URL for Boys Town (Prod OSF)

api/base/settings/defaults.py, api/base/versioning.py, api/draft_registrations/views.py, api/nodes/views.py, api_tests/draft_registrations/views/test_draft_registration_list.py, api_tests/nodes/views/test_node_draft_registration_detail.py, api_tests/nodes/views/test_node_draft_registration_list.py
Creates a new API version that differentiates the use of DraftRegistration Legacy serializers and the updated DraftRegistration serializers when using either `/nodes/<node_id>/draft_registrations/` or `/nodes/<node_id>/draft_registrations/<draft_registration_id>/`
* Updated the views for NodeDraftRegistrationList and Detail to check for version specified in the request and set the serializer class accordingly
* Created a global versioning variable to represent the version that new DraftRegistration serializers are used
* Added `2.20` as an allowed version to the API because OSF is currently using `2.19`
This change could benefit from QA checking the functionality of the `/nodes/<node_id>/draft_registrations/` and `/nodes/<node_id>/draft_registrations/<draft_registration_id>/` endpoints …
=> Versions Draft Registration Serializers [ENG-1555]

api/nodes/views.py, api_tests/nodes/views/test_node_draft_registration_detail.py, osf/models/registrations.py
Changing Permissions behavior based on what the registration is branched from
Modified DraftMixin to check permissions against the branched from node when its not created from a draft node
No
Low
Yes
Additive
Create Node, create a draft registration, add a new contributor on the original node, use that contributor to try to access the draft registration
N/A
N/A
- How will this …
=> [ENG-1563] Fixing permissions for draft registrations. Adding a test

api/draft_registrations/serializers.py, api_tests/draft_registrations/views/test_draft_registration_detail.py, osf/models/mixins.py, osf/models/registrations.py, osf/models/validators.py, osf_tests/test_draft_registration.py, pytest.ini
Allow updating draft registration with blank titles via API.
- changes the serializer to allow blank titles 
- adds test
No migrations, dev test only
No user facing changes, no new docs.
https://openscience.atlassian.net/browse/ENG-1569
=> [ENG-1569] Allow updating draft registration with blank titles

osf/migrations/0204_ensure_schemas.py, osf_tests/test_prereg.py, website/project/metadata/osf-preregistration-3.json, website/project/metadata/registered-report-4.json, website/project/metadata/schemas.py, website/registries/utils.py
Remove duplicate fields from Registered Report and OSF Prereg schemas since now we have metadata fields.
- Added `osf-preregistration-3.json`
- Compared with the previous version, `title` and `description` questions are removed from the schema.
Added `registered-report-4.json`
- Compared with the previous version, the `title` question is removed from the schema.
- Added a new migration script to update the registrations schema and schema blocks.
- Fix failing tests because of the updated version schema.
Old draft registration created using the old schema should remain the same. New draft registration created after the migration is run should no longer have duplicate fields
[ENG-1480]
[ENG-1480]: https://openscience.atlassian.net/browse/ENG-1480
=> [ENG-1480] Aligning registered report and osf prereg schemas

api/metrics/views.py, api_tests/conftest.py, api_tests/metrics/test_composite_query.py, api_tests/metrics/test_preprint_metrics.py, api_tests/sloan/test_sloan_metrics.py, conftest.py, osf/management/commands/reindex_with_current_metrics_mappings.py, osf/metrics.py, osf_tests/conftest.py, osf_tests/management_commands/test_reindex_with_current_metrics_mappings.py
Re-index old data with newly synced template.
- adds method that re-indexes old data.
Devtest and Courtney test only
Not user facing, no new docs.
WIP
https://openscience.atlassian.net/browse/ENG-1650
=> [ENG-1650] Re-index re-mapped metric models

osf/features.py
Sloan flags of staging have different names, this makes them the same.
- changes setting file to make sloan flag names the same.
Should resolve sloan issues
Bug fix, no docs.
No ticket
=> Fix sloan flags for staging.

api/base/middleware.py, api/base/settings/defaults.py, api/base/views.py, api_tests/base/test_sloan_study.py
So this PR changes quite significantly how the Sloan cookie system is implemented, but doesn't change any of the underlying behavior (other then to fix bugs). Now instead of the cookie behavior being unceremoniously shoved in the `/v2/` root view, the cookie code is now all part of a class that Overrides waffle's middleware, special casing only the sloan cookies.
Change was made to address a bug where both Waffle and my own code were creating two sets of cookies, or sending all it's a flags as cookies on every request.
- All code overriding `/v2/` root behavior is moved to a `SloanOverrideWaffleMiddleware`
- `SloanIdmiddware` is deleted and added to to new `SloanOverrideWaffleMiddleware`
- Finally resolves problem where local cookies were silently rejected by the browser.
We'll be …
=> [ENG-1688] Sloan fixes - take 3

addons/base/views.py, api/base/middleware.py, api/base/settings/local-travis.py, api_tests/base/test_sloan_study.py
So this PR changes quite significantly how the Sloan cookie system is implemented, but doesn't change any of the underlying behavior (other then to fix bugs). Now instead of the cookie behavior being unceremoniously shoved in the `/v2/` root view, the cookie code is now all part of a class that Overrides waffle's middleware, special casing only the sloan cookies.
Change was made to address a bug where both Waffle and my own code were creating two sets of cookies, or sending all it's a flags as cookies on every request.
- All code overriding `/v2/` root behavior is moved to a `SloanOverrideWaffleMiddleware`
- `SloanIdmiddware` is deleted and added to to new `SloanOverrideWaffleMiddleware`
- Finally resolves problem where local cookies were silently rejected by the browser
- Resovle other …
=> [ENG-1688] Sloan fixes take 4

addons/base/views.py, api/base/middleware.py, api_tests/base/test_sloan_study.py, website/settings/local-dist.py, website/settings/local-travis.py
This ensures once and for all that the bool values for the sloan cookies are good and makes it so now cookies default to secure.
- changes so secure is always True for cookies
- fix custom domains to always attach to osf.io or staging.io
Dev test only, QA will able to see if this works on the front-end.
https://openscience.atlassian.net/browse/ENG-1688
=> [ENG-1688] Sloan take 5

addons/base/views.py, api/base/middleware.py, api_tests/base/test_sloan_study.py
Ok really, really for real the last Sloan fix.
- special cases staging2 and test servers
- makes sure we send ES data to fields mapped, not cookie names.
Dev test first then I'll contact QA.
🐞 fix, no docs
https://openscience.atlassian.net/browse/ENG-1688
=> [ENG-1688] Fix mapping issue and special case for staging2

api/base/middleware.py
With all this scramble to set sloan flag cookie to the correct domain, we ding dang forgot all about the `sloan_id` cookies, they fail on custom domains and staging and staging2 and staging3 and test.
- makes sloan_id and other sloan flag cookies use the same domain setting system.
Now all domains should be sending sloan_id to their correct domains.
🐞 fix, no new docs.
https://openscience.atlassian.net/browse/ENG-1688
=> [ENG-1688] Sloan take 8

api_tests/preprints/views/test_preprint_detail.py, osf/models/preprint.py
Currently, updating `why_no_data` on the preprint model fails when `has_data_links` is `'no'`. This PR fix the problem.
Change the conditional to check for whether `why_no_data` is `'no'` instead of `'available'`.
=> [No ticket] Fix `update_why_no_data`

api/base/middleware.py, api_tests/base/test_sloan_study.py
Currently staging2 would mysteriously always return flags, no matter if you were viewing a preprint or not, staging1 had no should error.
- filters out non-redirect preprint providers and changes test
Dev test, then Courtney test
https://openscience.atlassian.net/browse/ENG-1711
=> [ENG-1711] Filter out non-redirect preprint providers from sloan custom domains

addons/base/views.py, api/base/middleware.py, api_tests/base/test_sloan_study.py
Currently though the OSF creates cookies for the api `/v2/` endpoint on every preprint view they don't stick to the a custom domain if the refferer is a custom domain, this fixes that.
- Makes an extra set of cookies on custom domains so they send view/download info from that domain, not api.
- add some extra test cases
Dev then Courtney test.
🐞 fix, no new docs.
https://openscience.atlassian.net/browse/ENG-1710
=> [ENG-1710] Sloan fix custom domain problems

api/base/middleware.py, api_tests/base/test_sloan_study.py, api_tests/sloan/test_sloan_metrics.py
Fix some behavior where chrome was creating some cookies incorrect and using two wild card domains for custom branded domain registries.
- made all custom domains never use wildcard
- made "path only" custom domains resolve properly
dev-test first
🐞  fix, no new docs.
https://openscience.atlassian.net/browse/ENG-1720
=> [ENG-1720] Remove wildcard from custom domain cookies

addons/base/views.py, admin_tests/nodes/test_views.py, osf/models/provider.py, osf_tests/test_draft_registration.py, osf_tests/test_node.py, osf_tests/test_node_license.py, osf_tests/test_node_share.py, tests/test_registrations/test_retractions.py, website/project/tasks.py
This ticket should ensure the access token is passed from the node provider object to SHARE.
So I had to renovate some of this code, because there was multiple bugs in the tests and because the code itself was old and doesn't fit our current conventions. So I 
0) Moved `access_token` field to `AbstractProvider` instead of previous weird situation
1) Moved node license tests to `osf_tests/test_node_license.py`
2) Move node SHARE tests to `osf_tests/test_node_share.py`
3) Fixed and DRY-ed up most of the mocking for `test_node_share.py`
Dev test only.
tech task, no new docs.
Detours:
https://openscience.atlassian.net/browse/ENG-1630
=> [ENG-1630] Share add registration provider info

website/settings/defaults.py
Set up the scheduling of the `update_institutional_project_counts.py` script in the celery beats schedule
* Adds a dictionary for the script and schedule it should run at to the celery beats schedule dictionary in `website.settings.defaults.py`
This change can be verified on production by looking at the data of the institutional dashboards via the OSF UI. 
N/A
N/A
[JIRA Ticket](https://openscience.atlassian.net/browse/ENG-1723)
Configs need to be updated in order to actually schedule the script.
=> [ENG-1723] Sets Up Instititutional Metrics Script Scheduling

api/base/middleware.py, api/base/views.py, api_tests/base/test_sloan_study.py, website/settings/local-dist.py, website/settings/local-travis.py
Despite what I thought before it's actually the waffle middleware that's not working in Travis, not the cookies being secure. 
- ensures we don't need waffle data to set cookie.
- fix problems with `test_user_get_cookie_when_flag_is_everyone` failing
Just effects travis
🐞  fix, no docs.
https://openscience.atlassian.net/browse/ENG-1785
=> [ENG-1785] Fix so flags work with Travis

api/base/middleware.py, api/users/serializers.py, api_tests/base/test_sloan_study.py
Make it so Sloan cookies override when a user is logging and has no refferer, so the author assertion can appear in a single login request.
- logic changes with test.
- no migration, low risk.
🐞  fix, no docs.
https://openscience.atlassian.net/browse/ENG-1784
=> [ENG-1784] Sloan cookies overriding authenticated state in /v2/ request

api/institutions/serializers.py, api/institutions/views.py, api_tests/institutions/views/test_institution_user_metric_list.py
Currently, the username in the response of the InstitutionUserMetrics API endpoint is a combination of the user guid and fullname. Solely providing the user fullname will make things easier for the front end.
* Modifies the user_name string for the InstitutionUserMetrics endpoint to only include the user fullname
The modification to `user_name` can be verified by the API
N/A
N/A
[JIRA Ticket](https://openscience.atlassian.net/browse/ENG-1820)
=> [ENG-1820] Changes representation of username in InstitutionUserMetrics API Endpoint

api/base/serializers.py
The type on the summary metrics relationship in the institution detail endpoint needs to be `institution-summary-metrics`, not `institution`.
Added a case to the JSON API serializer for the summary metrics relation.
No
None
No
Additive
API (v2/institutions/<institution_id>/)
No new version
None
Shouldn't
-->
Institutional metrics won't be …
=> [ENG-1824] Fixing relationship field

api/draft_registrations/permissions.py, api/draft_registrations/views.py, api/nodes/permissions.py, api_tests/draft_registrations/views/test_draft_registration_contributor_list.py, api_tests/draft_registrations/views/test_draft_registration_detail.py, api_tests/draft_registrations/views/test_draft_registration_list.py, api_tests/users/views/test_user_draft_registration_list.py, osf/models/mixins.py, osf/models/node.py, osf/models/registrations.py, osf_tests/test_draft_registration.py, osf_tests/test_registrations.py
After much discussion, it has been decided that draft registration contributors will not be carried over when the draft registration is created. Rather, they will be copied over upon time of registration. Also, draft registration permissions need to be based on the branched from node. 
Changing when the contributors are carried over. Modifying api permission classes to check permissions against the branched from node. Modifying tests to work with this new scheme.
No.
Moderate. Just need to ensure permissions are right for all draft registration related things.
yes
Modification
- How can QA verify? …
=> [ENG-1782] Draft Registration permissions fix.

api/institutions/serializers.py, api_tests/institutions/views/test_institution_user_metric_list.py
…the tests slightly
Currently the user institutions metrics endpoint doesn't filter on department, it should do that!
- add to filter field set
- dry up and add new tests
You should know be able to in filter by department for example `?filter[department]=Psychology dept` on 
technical task, no new docs.
https://openscience.atlassian.net/browse/ENG-1822
=> [ENG-1822] Add more filterable fields to user institutions.

api/nodes/filters.py, api_tests/nodes/filters/test_filters.py, api_tests/registrations/filters/test_filters.py
When filtering using [parent][ne]=null on nodes, registrations, sparse or otherwise, the API gives a 502 error. This was caused because of a self.user, which is unnecessary since the endpoint should return all nodes where parent is not equal, not just the ones where the user is a contributor. 
api.nodes.filters.py - Removing `child__contributor = self.user`
Ensure the end point is functional, that all nodes with parent nodes are appearing.
I don't think there is any mention of this filtering on the documentation. Might be nice to add.
There shouldn't be. The query I changed was specifically used for `filter[parent][ne]`.
https://openscience.atlassian.net/browse/ENG-1162
=> [ENG-1162] Fix 502 on filtering on parent with [ne] operator

api/base/exceptions.py, api_tests/preprints/views/test_preprint_detail.py
Unfortunately it turns out our URLField were essentially broken by our custom exception handling, so that their actual message wasn't getting passed, just the int 0. This meant there was no good way of telling whether a typical 400 validation error was cause by a URLField or any other field. This PR should fix this.
- changes to custom exception handler and add tests
This is ultimately going to extended by a front-end dev who will write the exact error text message.
Bug fix, no docs.
https://openscience.atlassian.net/browse/ENG-1825
=> [ENG-1825] Fix url formatting and exception handling

osf/management/commands/update_institution_project_counts.py, website/settings/defaults.py
Update celery settings so the institutional dashboard metrics gathering script will run on schedule.
1. Rename task key
2. Add task decorator to management command update_institution_project_counts
3. Add command to low priority queue
4. While we're here, add import for check_crossref_doi command
- Does this change require a data migration? If so, what data will we migrate? *No*
- What is the level of risk? *Low*
- Any permissions code touched? *No*
- Is this an additive or subtractive change, other? *Other, mostly additive*
- How can QA verify? (Through UI, API, AdminApp or AdminAdminApp?) - *In the app, wait until 5AM the next day and the institutional dashboard values should update*
- If verifying through API, what's the new version? Please include the endpoints in PR notes or Dev …
=> Update celery settings and add task decorator

api/institutions/views.py, api_tests/institutions/views/test_institution_user_metric_list.py, osf/metrics.py
The total was not working properly on users when sorting, and the search would only return 10 records.
Adding a default ordering to the user metrics. Increased the user metrics search result size.
No.
Moderate. Need to ensure this didn't break anything in the institutional metrics.
No.
Modification
API
v2/institutions/<institution_id>/metrics/users/
v2/institutions/<institution_id>/metrics/departments/
Make sure all sorting works, …
=> Fix sorting error and user metrics issue [ENG-1876]

api/base/middleware.py, api_tests/base/test_sloan_study.py
The browsable api 502s! That's bad!
- improve check for browsable api 
The browsable api should now not 502.
Bug fix, no docs
https://openscience.atlassian.net/browse/ENG-1816
=> [ENG-1816] Better exclude browseable API for Sloan

api/base/serializers.py, api_tests/preprints/views/test_preprint_detail.py, osf/models/preprint.py
There are two issues with Sloan API changes. One is an issue with the data links error message showing as a list instead of just a string. The other is emptying out the data links field when the has_data_links is set to not be something other than 'available'
Added error handling to the base serializer for validation issues stemming from array fields.
No
Low
No
Additive
API
No new version. Run PATCH against …
=> [ENG-1915] Fix Sloan API Inconsistencies

api/preprints/serializers.py, api_tests/preprints/views/test_preprint_detail.py, osf/models/preprint.py, website/language.py
When `has_prereg_links` is set, the `prereg_links` field should be nulled out, as should `prereg_link_info`. Also doing some additional cleanup
Adding functionality to the preprint model. Adding a test. Cleaning up some language and variable names
No
Minimal
No
Additive
API
v2/preprints/<preprint_id>/
Sloan
Shouldn't
-->
N/A
N/A …
=> [ENG-1915] Sloan API cleanup part 2.

api/brands/views.py, osf/models/provider.py
To stop embedding null brands from 500ing, remove duplicate code I noticed.
- conditional that checks if NoneType embed is stringify with comment explaining context.
- random drive-by removal of duplicate code I noticed.
This is a temporary fix for a larger issue with the test app, though user behavior should return to expected immediately after this is merge and remain unchanged.
long comment in code.
This is a stopgap which specifically effects the test app giving it false positives, so no new tests. Any suggestions are welcome to add tests.
https://openscience.atlassian.net/browse/ENG-1843
=> [ENG-1843] Fix null brand embeds

api_tests/nodes/views/test_node_draft_registration_detail.py, api_tests/nodes/views/test_node_draft_registration_list.py, osf/migrations/0206_ensure_schemas.py, osf/migrations/0207_ensure_schemas.py, osf_tests/management_commands/test_migration_registration_responses.py, osf_tests/test_node.py, osf_tests/test_schemas.py, website/project/metadata/egap-registration.json, website/project/metadata/osf-preregistration-3.json, website/project/metadata/prereg-prize.json, website/project/metadata/registered-report-4.json
Registries now have metadata which is redundant with asking for 'authors' on specific registration forms.
* Removes the 'author' question json snippet from egap-registration, osf-preregistraton, prereg-challenge, and registered-report
* Adds an ensure_schema migration to update the database representation of the registration schemas
These changes can be validated through the UI by going through the process of creating registrations with these schemas and ensuring that registrations are created properly and that authors are not asked for. 
N/A
N/A
[JIRA Ticket](https://openscience.atlassian.net/browse/ENG-1651)
=> [ENG-1651] Removes 'Authors' from specified Registration Forms

api/registrations/serializers.py, api_tests/registrations/views/test_registration_list.py
Currently the new API version doesn't throw an error when the deprecated fields `lift_embargo` or `registration_choice` are specified, which is a problem because a user might utilize these fields to embargo their registration, but then its not registered because they are deprecated.
Adding error handling to the serializers. Adding tests to ensure these two fields have errors thrown on them
No
Low
No
Additive
API
2.19
- What …
=> Adding errors for new API Version [ENG-1490]

osf/migrations/0208_update_EGAP_schema.py, scripts/EGAP/create_EGAP_json.py, website/project/metadata/egap-registration-3.json
Date of start of study needed to be in the new version of the EGAP schema
Adding it back into the schema. Adding migration to update the schema. Updating the script to pull the date into the reg data
Yes. This will just change the existing schema for future EGAP registrations, not past.
Minimal
No
Additive
UI
N/A
EGAP registrations
Shouldn't …
=> [ENG-1975] Adding back in Date of start of study to EGAP form and migration

admin/preprints/views.py, admin/templates/preprints/ham_spam_modal.html, admin/templates/preprints/preprint_list.html, admin/templates/users/ham_spam_modal.html, admin/templates/users/user_list.html, admin/users/views.py
Admins need the ability to not only bulk spamify but also hamify preprints and users. 
Adding ham spam modals to preprints and users. Updating views.
No
Minimal
No
Additive
Admin app
N/A
N/A
N/A
-->
N/A
N/A
https://openscience.atlassian.net/browse/ENG-652
=> [ENG-652] Adding the ability to bulk hamify preprints and users

scripts/EGAP/create_EGAP_json.py, scripts/EGAP/egap-registration-3.json
The multiselect on the EGAP registration is not working correctly the way the create json script is currently written.
Updating the schema to use the newest json schema. Removing authors. Fixing the multiselect.
Yes. Updating egap schema
Minimal
No
Modification
UI. The EGAP registrations
EGAP
Shouldnt'
-->
N/A
N/A …
=> [ENG-1959] Adding functionality for the multiselect. Updating schema

api/preprints/serializers.py, api/preprints/urls.py, api/preprints/views.py, api_tests/preprints/views/test_preprint_bibliographic_contributors_list.py
Adds a bibliographic contributor relationship to Preprint's list/detail API views and creates a PreprintBibliographicContributor endpoint
* Creation of PreprintBibliographicContributors endpoint
* Adds a bibliographic contributor relationship to Preprint list/detail api views
* Adds tests for PreprintBibliographicContributors endpoint
This requires testing through the API of: 
* `/preprints/` - For bibliographic_contributors relationship links in the results
* `/preprints/<preprint_id>/` - For a bibliographic_contributors relationship link
* `/preprints/<preprint_id>/bibliographic_contributors/` - For a list of all bibliographic contributors for the preprint
External API documentation should be updated to reflect the addition of the PreprintBibliographicContributors and the relationship …
=> [ENG-1748] Adds Bibliographic Contributor Relationship to Preprints

framework/auth/views.py
There is a mysterious bug when users are logging into OSF using ORCiD's for the first time
framework.auth.views.external_login_confirm_email_get - Adding logging messages at points where exceptions are raised to provide more detail when users encounter errors.
Since this is just bug detection, just ensure ORCiD login works. There is no change in functionality.
None
Shouldn't be!
https://openscience.atlassian.net/browse/ENG-1029
=> [ENG-1029] Improved logging for ORCiD bug finding.

website/static/js/keen.js, website/static/js/osfHelpers.js
* Stop logging unused events to keen
* Log public pageview into partitioned collections for smaller/faster scans
* Stop logging `front-end-events` to Keen.  These should only be sent to GA.
* Start sending pageviews for public projects to collections partitioned by the first letter of the guid.  These collections will be created automatically by Keen.  We will switch over to them after collecting a month of data after which scans should be much faster.
* No data migration required.
* Fix will be manually dev-tested.
No documentation needs to be updated.
Unlikely.  Changes are highly restricted to keen tracking code.
https://openscience.atlassian.net/browse/ENG-1963
https://openscience.atlassian.net/browse/ENG-2010
=> [hotfix][ENG-1963][ENG-2010] Keen logging updates

api/providers/views.py, api_tests/providers/registrations/views/test_registration_provider_schemas.py
EGAP was not showing in the registration provider schama list. This fixes that.
- Pass `request` to `get_latest_versions()` so that EGAP would be returned if it's supposed to be
- Tests
- Does this change require a data migration? No
- What is the level of risk? Minimal
- Any permissions code touched? Not as such. It does take advantage of the `egap_admins` waffle flag, though.
- Is this an additive or subtractive change, other? Additive
- How can QA verify? (Through UI, API, AdminApp or AdminAdminApp?) Through API or integrated testing
- If verifying through API, what's the new version? Please include the endpoints in PR notes or Dev docs. Not versioned, but you can use `/v2/providers/registrations/egap/schemas/` if you have egap set up to use the EGAP Registration schema v3.
- What …
=> [ENG-2087] Add egap to registration provider schemas

admin/brands/views.py, admin/templates/base.html, admin/templates/brands/create.html, admin_tests/brands/test_views.py
1. Color picker doesn't validate for a11y noncompliant colors upon Create/save.  (But, does validate upon Edit/submit).
2. Boxes are shorter in Create/save mode (compared to Edit/submit). Make the boxes on the edit screen the same width as the create screen.
3. Make permissions fix
Fixing permissions, modifying create template, modifying view for admin brand create
- Does this change require a data migration? If so, what data will we migrate? No
- What is the level of risk? Minimal
- Any permissions code touched? Yes, an improvement
- Is this an additive or subtractive change, other? Modification
- How can QA verify? (Through UI, API, AdminApp or AdminAdminApp?) Admin app
- If verifying through API, what's the new version? Please include the endpoints in PR notes or Dev docs. N/A
- What …
=> Branded registries fixes [ENG-2096]

admin_tests/preprint_providers/test_views.py, admin_tests/registration_providers/test_views.py, osf/models/provider.py, website/settings/defaults.py
Adding a prefix to the share source name
Modifying setup_share_source. Adding tests
- Does this change require a data migration? If so, what data will we migrate? N/A
- What is the level of risk? Minimal, just for staging environments
- Any permissions code touched? no
- Is this an additive or subtractive change, other? additive
- How can QA verify? (Through UI, API, AdminApp or AdminAdminApp?) UI/Admin app
- If verifying through API, what's the new version? Please include the endpoints in PR notes or Dev docs. N/A
- What features or workflows might this change impact? Provider creation. And share
- How will this impact performance? Shouldn't
-->
N/A
Shouldn't be.
https://openscience.atlassian.net/browse/ENG-2115
=> Adding prefix to share source. [ENG-2115]

api/providers/serializers.py, api_tests/providers/registrations/views/test_registration_provider_detail.py
The front end needs the registration provider serialized in the API.
Adding the field to the serializer, adding test
- Does this change require a data migration? If so, what data will we migrate? No
- What is the level of risk? Minimal
- Any permissions code touched? No
- Is this an additive or subtractive change, other? Additive
- How can QA verify? (Through UI, API, AdminApp or AdminAdminApp?) API
- If verifying through API, what's the new version? Please include the endpoints in PR notes or Dev docs. v2/providers/registrations
- What features or workflows might this change impact? Branded registries
- How will this impact performance? Shouldn't
-->
I don't think this will be necessary to add to the docs.
Shouldn't be
https://openscience.atlassian.net/browse/ENG-2150
=> Adding branded_discovery_page field to registration provider serializer. [ENG-2150]

api_tests/providers/test_reindex_provider.py, osf/management/commands/reindex_provider.py
This should allow us to re-index `OSF Registries`.
- changes `reindex_preprint_provider.py` to handle all providers and adds tests.
- cleans up preprint factory
Yes, kind of, but only SHARE data.
Low
No
Additive
Devtest
Not
-->
tech task, no new docs.
https://openscience.atlassian.net/browse/ENG-2149
=> [ENG-2149] Modify preprint provider re-index command to handle all providers

api/share/utils.py
SHARE is sending 400s when recieiving registration data. 
~~ as you can see the payload is being retried 5 times with the `registration_format` portion being converted to json each time. (you can see this is probably the case by looking at the sequence of slashes which is the previous number of slashes*2 + 1). I believe this is some kind of mutable argument problem within celery.  ~~
So really all that was happening here was we were sending a bad payload which was somehow repeatably json-ifing itself, but as long as the payload is valid initially the problem doesn't express itself.
- remove `registration_type` from SHARE payload
No
Low
No
- Is this an …
=> [ENG-2142] Fix share sending bad payloads

osf/management/commands/move_egap_regs_to_provider.py, osf_tests/factories.py, osf_tests/management_commands/test_move_egap_regs_to_provider.py
The egap migration script only got version 3 of the EGAP schema, so the 1536 EGAP registrations with version 2 of the schema wouldn't be migrated. This fixes that. 
1. Loop over all of the versions of the schema
2. Assume the `_id` of the EGAP registry will be 'egap' (because it will be).
3. Rename `epag_provider` to `egap_provider`
This will be tested on Staging2 as part of branded registries submission. It shouldn't be any more problematic than it would have been otherwise.
N/A
None.
N/A
=> Ensure script runs on all versions of the egap schema

website/project/utils.py, website/static/js/keen.js
Stop sending pageview events to monolithic collection.  It's no longer needed.
* Stop sending pageview events to monolithic collection.  There is enough data in the partitioned collections to switch fully over to those.
* Update `website.project.utlils.get_keen_activity` to query partitioned collections.
* No data migration required.
* Fix will be manually dev-tested.
nope nope nope
None expected.
[ENG-2147](https://openscience.atlassian.net/browse/ENG-2147)
=> [hotfix][ENG-2147] stop logging to joint keen collection

addons/base/views.py
Personal access tokens with only a read only scope should not be able to upload files. Currently they can. Thats not good
Ensuring tokens are checked for all authentication operations, even if user.auth is present
- Make a personal access token with full read scope. Create a project, and use the command found in the ticket to ensure it gives you an error
N/A
N/A
Shouldn't be
https://openscience.atlassian.net/browse/ENG-2221
=> Prohibit file upload for read only token [ENG-2221]

website/templates/project/addons.mako
The old link to the Github access token page was broken, so updating that
- Updated target link for the aforementioned help page
- Please verify that the link in the project add-ons page (osf.io/<project_id>/addons ) goes to the appropriate help page
`NA`
`NA`
`NA`
=> [Hotfix] Fix link to reauthorize github access token help page

website/project/metadata/osf-open-ended-3.json
Have the Open-Ended Registration form expect files so that any attached files are associated with the registration rather than the node.
Add `config.hasFiles=true` to the registration form.
- Verify that making a registration with the open-ended registration form and a file attached will, when you click on that file's link in the registration, take you to the registration's file.
What are the areas of risk? Low risk. 
Any concerns/considerations/questions that development raised? No
Shouldn't be.
https://openscience.atlassian.net/browse/ENG-2272
=> [ENG-2272] Have open-ended form expect files

osf/management/commands/collect_user_nodes_exceeding_storage_limits.py, osf/management/commands/send_storage_exceeded_announcement.py, website/mails/mails.py, website/templates/emails/storage_cap_exceeded_announcement.html.mako
Add announcement email, script to warn users about exceeding storage capacities. Runs off the output from script ~~in~~ stolen from #9497
* Add email
* Add script
None -- dev QA. Tested locally with a mock input file:
None expected. Script should be sufficiently verbose and fault-tolerant to alert to errors and allow them to be investigated separately, without worrying about spamming users if multiple runs are necessary.
https://openscience.atlassian.net/browse/ENG-2296
https://openscience.atlassian.net/browse/ENG-2289
=> [Hotfix] Storage Exceeded Announcement Email and Script [ENG-2296][ENG-2289]

addons/bitbucket/api.py
Normalize BitBucket repo permissions for consistency.
- Perm level required to link personal repos lowered from "owner" to "contributor"
- Perm level required to link team repos raised from "member" to "contributor"
Affects what repositories may show up when selecting a repo to link to a node on `osf.io/<node_id>/addons`.
Expected that, for both "personal" and "team", repos where the authorizing user has either the "contributor", "admin", or "owner" permission level will display, whereas "member" will not.
If any exist, previously-connected "team" repos where the user was only a "member" and not "contributor" will no longer be displayed or connectable from the addon settings page, but will continue to render in the files widget unless disconnected. …
=> Require explicit "write" perms to link BB repo [ENG-2329]

admin/templates/nodes/storage_status.html
Storage limit statuses aren't showing up correctly on the admin app due to a missed case where a private node can be over the public limit. The admin app shows this as no storage concern
Adding two cases. One for a private node being over the public limit, and one for a non-calculated storage usage.
- Verify All cases of storage usage are working.
- Verify
N/A
Shouldn't be 
https://openscience.atlassian.net/browse/ENG-2322
=> Fixing template for storage usage status on admin app [ENG-2322]

addons/bitbucket/api.py, addons/bitbucket/models.py
Return all repositories authenticated user has permission for.
* Update API call from `BITBUCKET_V2_API_URL/repositories/{username}/` to `BITBUCKET_V2_API_URL/repositories/`
* Remove call to [deprecated `teams` endpoint](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/) 
API changes tested remotely. BB repos should still display and be connectable.
Leaves some seemingly-dead code related to `teams` endpoint. Follow-up ticket for [analysis and removal filed](https://openscience.atlassian.net/browse/ENG-2344).
None
=> [Hotfix] Update BitBucket API calls. [No Ticket]

osf/migrations/0221_add_schemas.py, osf/utils/migrations.py, website/project/metadata/asist-results-registration.json, website/project/metadata/qualitative-research.json, website/project/metadata/real-world-evidence.json
Updates the new registration forms
* Replaces 'help' keys with 'example' keys in the new registration schemas
* Updates migration utils function to ensure 'example' is retrieved and saved into schemas blocks from schemas
* Updates migration 0221 to ensure new registration forms are not visible but are active
- Verify example text in the registration form shows up as expected
- Verify new schemas are not visible but are active and can be added to a branded registry in the admin app
(Both have been verified locally)
N/A
N/A
[JIRA Ticket](https://openscience.atlassian.net/browse/ENG-2347)
=> [ENG-2347] Registration Form Fixes

api/actions/serializers.py, api/base/filters.py, api/nodes/permissions.py, api/nodes/serializers.py, api/providers/views.py, api/registrations/permissions.py, api/registrations/serializers.py, api/registrations/views.py, api/requests/serializers.py, api_tests/registries_moderation/test_submissions.py, framework/auth/oauth_scopes.py, osf/models/registrations.py
Adding POST/PATCH endpoints for registries moderation
Adding serializers. Modifying views.
- Verify you can perform actions against the endpoint. Verify it doesn't allow you to make actions out of order
- Verify you can make requests. Verify you can update the comment
I don't think moderation docs are public
N/A
https://openscience.atlassian.net/browse/ENG-2130
=> Adding post endpoints for registries moderation [ENG-2130]

api/providers/serializers.py
Add a `registrations` relationship to the RegistrationProviderSerializer
Adapted the `preprints` and `links` fields from the PreprintProviderSerializer to the RegistrationProviderSerializer.
Confirmed the presence of the field the local api.
https://openscience.atlassian.net/browse/ENG-2371
=> [ENG-2371] Add registrations and links fields to RegistrationProviderSerializer

osf/models/sanctions.py
As part of ENG-2182, the `is_pending_approval`, `is_pending_embargo`, and 'is_pending_retraction` properties were updated to return True until the underlying sanction had both admin and moderator approval. FE uses these properties to alert registration contributors when a sanction requires admin attention, so they should return False once all admin approvals are granted, even if the sanction is still pending moderation.
Update `Sanction.is_pending_approval` to only check whether the current `approval_stage` is `PENDING_ADMIN_APPROVAL`, this resolves all of the registration properties.
Note that `is_approved`, `is_embargoed`, and `is_retracted` will all continue to return False until moderator approval is also granted (if required).
https://openscience.atlassian.net/browse/ENG-2373
=> [ENG-2373] Fix Registration.is_pending_{approval/embargo/retraction} for FE

api/providers/views.py, api_tests/registries_moderation/test_submissions.py, tasks/__init__.py
related tests, add api_tests/registries_moderation/ to Travis
Our tests for Registries Moderation had some outdated assumptions and were failing on develop, these were not caught because the tests weren't included in the Travis configuration.
Update Travis configuration to run api_test/registries_moderation as part of API_TESTS1
Replace outdated references to `machine_state` with the correct `reviews_state`
Update the default_query_set for `RegistrationProviderRegistrationList` to no longer exclude registrations without an `APPROVED` `RegistrationApproval` -- a decision made before Sanctions were turned into the de-facto mode of handling moderated registrations. Remove the `autouse` pytest fixture `unapproved_registration` that was meant to verify that unapproved registrations weren't …
=> [ENG-2376] Fix registries_moderation tests and add to Travis

website/project/utils.py
On the registration files page, storage limits messaging is sometimes displayed. Storage caps does not apply to registrations and messaging related to storage caps should not be displayed on registration pages.
Currently, storage messaging on registration file pages can arise because of this boolean (https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/js/fangorn.js#L2225). The `storageLimitsStatus` checked in that boolean is based off of the `window.contextVars.node.storageLimitsStatus` which is determined by `website.project.utils.get_storage_limits_css`. Though storage caps don't apply to Registrations, `website.project.utils.get_storage_limits_css` can currently check storage for the Registration and return a dictionary value that should only be returned for …
=> [ENG-2348] Removes storage limits messaging on registration pages

admin/registration_providers/urls.py, admin/registration_providers/views.py, admin/templates/registration_providers/detail.html, admin/templates/registration_providers/edit_moderators.html, admin_tests/registration_providers/test_views.py
Adding the ability to add admin moderators cleanly to registration providers in the admin app.
Modifying templates. Adding code to the views. 
- Verify you can add and remove admins to registration providers
- Verify you can remove a moderator as an admin, but not as a moderator
N/A
Shouldn't be.
https://openscience.atlassian.net/browse/ENG-2372
=> Adding ability to add and remove moderators cleanly in the admin app. [ENG-2372]

api/base/utils.py, api/registrations/views.py
Currently when a registration is deleted it's moderation actions become inaccessible, this fixes that.
- add simple conditional overriding is_deleted check and overrides function.
- Verify actions are still accessible for deleted registrations
https://openscience.atlassian.net/browse/ENG-2386
=> [ENG-2386] Remove check for deleted registrations on registrations action list

api/caching/tasks.py
Sometimes a data provider gives us back a string size instead of an int size. We need the int.
Ensure the size metadata is an int
- Verify no errors are caused when moving files between google drive and osf storage. This is where the error occured
N/A
Shouldn't be.
https://openscience.atlassian.net/browse/ENG-2385
=> Ensuring target_file_size is an int to prevent a calculation error [hotfix] [ENG-2385]

osf/models/registrations.py, osf_tests/test_registrations.py
In order to help distinguish between normal withdrawals and forced withdrawals on the moderator app, we should prepend some sort of "Force withdrawn by moderator" message to the withdrawal justification on FORCE_WITHDRAW triggers
- prepend comment when writing RegistrationAction
- Verify Force withdrawals have prepended comment
tech task, no docs.
https://openscience.atlassian.net/browse/ENG-2366
=> [ENG-2366] Modify Retraction justification on FORCE_WITHDRAW

api/providers/serializers.py
We want to display a user's permissions with a provider via the API, for RegistrationProviders as well as PreprintProviders
- add serializer field to ProviderMixin
- Verify your permissions are accurately represented on the registration providers list and details.
https://openscience.atlassian.net/browse/ENG-2408
=> [ENG-2408] Add permissions to ProviderSerializer

website/templates/emails/new_pending_withdraw_requests.html.mako
When a withdrawal request was completed an email confirming that was supposed to be sent, but instead because there was no email template the whole transaction would fail, stranding the registration in the old moderation state.
- add placeholder template so transaction can complete and moderation state can change.
- Verify accepting admin withdrawal request causes the moderator to get a registration in the withdrawal request queue.
https://openscience.atlassian.net/browse/ENG-2405
=> [ENG-2405] add email template for withdrawal requests

admin/registration_providers/forms.py, admin/registration_providers/views.py
…d info page
Currently we show info and options for changing the `reviews_comments_anonymous` attribute on the provider model, but the registration type of provider doesn't have the option for non-anon comments, this is confusing, so we're removing the option from the admin app.
- simple config changes to the views.
- Verify `reviews_comments_anonymous` no longer appears anywhere on the registration provider admin app page.
- Verify
https://openscience.atlassian.net/browse/ENG-2400
=> [ENG-2400] Remove comments_anonymous from admin app Registries Moderation setup 

.travis.yml, tasks/__init__.py
Recently Travis has been having some sort of migration crisis and everyone's testmon cache has become invalid, this PR catches, deletes and refreshes invalid caches.
- catch the cachinig errors and remove or remake invalid db.
- Verify Travis cache remembers things and make tests go faster.
🐞 fix no docs.
None
=> [WIP] Fix testmon

api/subscriptions/views.py
Currently our filters for notifications return too many duplicates of the same thing.
- add distinct to query so notifications aren't repeated.
- Verify that Futa's notifications aren't repeated.
https://openscience.atlassian.net/browse/ENG-2424
=> [ENG-2424] Too many results from notification subscription queryset

api/registrations/views.py
API results from the RegistrationReviewAction endpoint should be in descending order by `created` timestamp
* Adds an explicit ordering to the RegistrationReviewAction view
- Verify that API results from `/v2/registrations/<registration_id>/actions` are ordered such that the most recent review actions are earlier in the results.
N/A
N/A
[JIRA Ticket](https://openscience.atlassian.net/browse/ENG-2422)
=> [ENG-2422] RegistrationReviewAction Descending Ordering in API

website/templates/emails/file_operation_failed.html.mako, website/templates/emails/file_operation_success.html.mako, website/templates/emails/notify_base.mako
In a few of our email templates, the copyright year is hardcoded as 2018 in the footer.
Make the emails use dynamic dates
- Verify the email is now 2020 in emails.
- Verify
N/A
N/A
https://openscience.atlassian.net/browse/ENG-2434
=> Fixing copyrights in the footers [ENG-2434]

osf/models/sanctions.py, website/templates/emails/pending_embargo_admin.html.mako, website/templates/emails/pending_embargo_non_admin.html.mako, website/templates/emails/pending_embargo_termination_admin.html.mako, website/templates/emails/pending_registration_admin.html.mako, website/templates/emails/pending_registration_non_admin.html.mako, website/templates/emails/pending_retraction_admin.html.mako, website/templates/emails/pending_retraction_non_admin.html.mako
This modifies email template language to accommodation registries moderation.
Changes text in:
- pending_embargo_admin.html.mako, 
- pending_embargo_non_admin.html.mako
- pending_embargo_termination_admin.html.mako
- pending_registration_admin.html.mako
- pending_registration_non_admin.html.mako
- pending_retraction_admin.html.mako
- pending_retraction_non_admin.html.mako 
and adds `is_moderated` to template context
- Verify all emails are sent with correct text differing for moderated and moderated registrations 
just new language, no docs.
https://openscience.atlassian.net/browse/ENG-2440
=> [ENG-2440] edit email templates for new language

osf/models/registrations.py, tests/test_registrations/test_review_flows.py
The API needs to return the withdrawal justification as the comment in the withdrawal action. Its not doing this right now
Ensure the registration model saves the withdrawal justification as the action comment.
- Verify the API returns the withdrawal justification made by the registration admin in the API
- Verify
N/A
N/A
https://openscience.atlassian.net/browse/ENG-2453
=> Ensure withdrawal justification is saved as comment for withdrawal action [ENG-2453]

osf/management/commands/correct_registration_moderation_states.py, website/settings/defaults.py
Allow correct_registries_moderation_states to be scheduled
- Update management command, args
- Update beat imports
To run, `beat_schedule` should be updated to include something like
```
'correct_registration_moderation_states': {
'task': 'management.commands.correct_registration_moderation_states',
'schedule': crontab(minute='*/30'), # Every 30 minutes
'kwargs': {'page_size': 500}
},
```
None
=> Allow correct_registries_moderation_states to be scheduled [No ticket]

osf_tests/management_commands/test_correct_registration_moderation_states.py, scripts/approve_embargo_terminations.py, scripts/tests/test_approve_embargo_terminations.py
valid. Fix tests for corret_registration_moderation_states
Make sure we don't leave dangling `embargo_termination_approval` objects when an embargo expires before the termination is approved.
These historically have just been ignored, but now they mess with `moderation_state`, which is no good.
Following the pattern for `EmbargoTerminationApproval._on_reject`, set registration.embargo_termination_approval to None when it is no longer valid.
- Verify
- Verify
=> Remove embargo_termination_approval objects when they are no longer

osf/models/node.py, osf_tests/test_files.py
We make far too many queries on `osfstorage_region` in certain API endpoints. We should make only one.
- Make `node.osfstorage_region` a `cached_property`
None expected, waiting for TCI
None
=> [Hotfix] Cache node.osfstorage_region

.travis.yml, api_tests/crossref/views/test_crossref_email_response.py, api_tests/users/views/test_user_actions.py, conftest.py, osf_tests/management_commands/test_migrate_deleted_date.py, osf_tests/test_management_commands.py, osf_tests/test_preprint_summary.py, osf_tests/test_registration_moderation_notifications.py, osf_tests/test_user.py, requirements/dev.txt, tasks/__init__.py, tests/identifiers/test_datacite.py, tests/test_registrations/test_review_flows.py
This is a booster shot of updated decencies for the OSF for pytest, these such keep us more up to date with the current test infrastructure and hopefully fix some probabilistic test fails.
You can read about the bug [here](https://github.com/pytest-dev/pytest/issues/3171) which indicates updating pytest will fix the issue. I picked pytest 5.0.0 because it is recent and only requires few changes. The biggest change is pytest no long allows passing of fixtures the same way. [Read about it here](https://github.com/pytest-dev/pytest/issues/3950). So that had to be changed to release this. 
- update pytest and related dependencies
- turn fixtures into functions to appease pytest update
- Verify that travis …
=> [ENG-2435] Upgrade pytest and others to fix broken tests

api_tests/identifiers/views/test_identifier_list.py, api_tests/registries_moderation/test_submissions.py, osf/models/node.py, osf/models/sanctions.py, tests/identifiers/test_datacite.py, website/identifiers/clients/datacite.py, website/settings/defaults.py, website/settings/local-dist.py, website/settings/local-travis.py
This is primarily a ticket for ensuring that DOIs mint of project draft registration, but at some time in the distant past the ability to mint DOIs locally and therefore test this feature was disabled, so I had to make some tweaks in order to restore that behavior.
- tweaks client (apparently just flat broken) to allow for minting DOIs and restructure tests to be mocked properly.
- removes old ServiceTemporarilyUnavailable exception
- removes old settings checks that were getting in the way of tests.  
- Verify at https://doi.test.datacite.org/repositories/demo.cos/dois that DOIs are being minted when a project or draft reg is registered. ⚠️ You will need appropriate credentials to do this. ⚠️ 
- Verify Registration process is timely and error free.
QA: is there any user facing docs about …
=> [ENG-2334] Make DOIs mint on project/draft registration 

osf/management/commands/sync_datacite_doi_metadata.py, osf/metadata/serializers.py, osf/metadata/utils.py, website/identifiers/clients/datacite.py
Currently we are only sending a small portion of our node's metadata to datacite, this fix will send all the available metadata.
- modifies formatting for metadata being sent to datacite
- add management command to sync pre-this-PR metadata
-  Verify at https://doi.test.datacite.org/repositories/demo.cos/dois that DOIs are being minted when a project or draft reg is registered. ⚠️ You will need appropriate credentials to do this. ⚠️
-  Verify Registration process is timely and error free.
https://openscience.atlassian.net/browse/ENG-2336
=> [ENG-2336] Send all additional DOI data over datacite

api/base/exceptions.py, api/nodes/views.py
Currently when a draft has been registered, it shows a 410 (Gone). Front end would like a 301 (Permanently moved).
Adding the redirect
- Verify After a draft is registered, the API properly redirects.
- Verify
N/A
Shouldn't be.
https://openscience.atlassian.net/browse/ENG-2471
=> Creating a redirect when a draft has been registered [ENG-2471]

api/registrations/serializers.py, api_tests/nodes/views/test_node_detail.py, website/project/licenses/__init__.py
Currently when a user with write permissions edits a DraftRegistration the permission scheme doesn't allow those edits, this fix gives the user the permission to do that.
- simple logic change to `set_license` 
- simple change to registration views
- Verify that license changes persist after a write user edits thier license.
🐞  fix, no docs.
https://openscience.atlassian.net/browse/ENG-1696
=> [ENG-1696] Make it so write users ‘license’ edits do persist

api/draft_registrations/serializers.py, api/registrations/serializers.py, api_tests/draft_registrations/views/test_draft_registration_detail.py, api_tests/registrations/views/test_registration_detail.py, osf/models/registrations.py
The front-end needs a way to determine if a registration has a project or not.
Adds a has_project field to the Registration and DraftRegistration serializers
- Verify that the has_project field is viewable via the api
new feature, no docs.
https://openscience.atlassian.net/browse/ENG-2552
=> [ENG-2552] Add has_project property to serializers

api/draft_registrations/serializers.py, api/draft_registrations/urls.py, api/draft_registrations/views.py, api_tests/draft_registrations/views/test_draft_registration_contributor_detail.py
To an bibliographic endpoint the draft registration endpoint.
- add bibliographic contributor relationship to view
- Verify view the bibliographic contributor endpoint from DraftRegistration
Remember to change API docs.
https://openscience.atlassian.net/browse/ENG-2566
=> [ENG-2566] Add bibliographic contributor relationship to draft registrations

osf/admin.py, osf/models/licenses.py
Allow admins to add Node Licenses to adminadmin app
- register admin app models and add help text
- Verify you can create license and add them to a provider
add help text, no addtional docs.
https://openscience.atlassian.net/browse/ENG-2464
=> [ENG-2464] Add admin app node license editor

osf/models/provider.py, osf_tests/test_elastic_search.py
Nodes currently aren't updated when collections they have submitted to modified
Performing a search update when _id is modified
- Verify nodes are displayed on collection discovery pages
Any concerns/considerations/questions that development raised? Why is the discover page using the search endpoint?
N/A
Shouldn't be
https://openscience.atlassian.net/browse/ENG-2544
=> Updating search upon _id change [ENG-2544]

api/draft_registrations/permissions.py, api/draft_registrations/serializers.py, api/draft_registrations/views.py, api/nodes/permissions.py, api_tests/draft_registrations/views/test_draft_registration_detail.py, api_tests/draft_registrations/views/test_draft_registration_list.py, api_tests/users/views/test_user_draft_registration_list.py, osf/models/mixins.py, osf/models/node.py, osf/models/registrations.py, osf_tests/test_draft_registration.py, osf_tests/test_node.py
The current user’s permissions on the draft registration retrieved through the API is not currently an attribute as it is for Nodes and Registrations. This is helpful because it removes the need for a follow-up API call to request the current user’s permissions on the draft registration. 
This PR builds off of https://github.com/CenterForOpenScience/osf.io/pull/9619 to avoid re-writing tests after contributor management is modified.
* Add the `current_user_permissions` field to the Draft Registration serializer
* Adds `test_current_permissions_field` to DraftRegistrationDetail tests
- Verify the presence and accuracy of the `current_user_permissions` field on the DraftRegistrationDetail endpoint
- Note that permissions should be based off of the user's contributorship on the draft …
=> [ENG-2597] Serializer Current User Permissions on Draft Registrations

README-docker-compose.md, docker-compose.yml
Clear out outdated container and update readme (ran the idea of removing the container from docker-compose by MattF)
* Remove registries container (and volumes) from `docker-compose.yml`
* Updates `README-docker-compose.md` to remove references to registries container
This does not require QA but should be verified by someone on Dev Ops
The README is appropriately updated
If any developers are still running the registries container and have an outdated `website/settings/local.py` file expects a registries container, they will encounter errors when trying to interact with the `/registries/` path. They should update the `EXTERNAL_EMBER_APPS` dict to match the `EXTERNAL_EMBER_APPS` in `website/settings/local-dist.py`
[JIRA Ticket](https://openscience.atlassian.net/browse/ENG-2518)
=> [ENG-2518] Removes registries container 

osf/management/commands/make_taxonomy_custom.py, osf/models/subject.py, osf/models/validators.py, osf_tests/management_commands/test_make_taxonomy_custom.py
To allow providers with the standard bepress taxonomy to highlight certain subjects, we need to copy that providers taxonomy into postgres. This adds a management command to copy over the standard taxonomy.
- adds management command that copies taxonomy with tests
- Verify that "OSF Subjects" in the admin app lists all the subjects for the provider and that highlighted status can be changed.
new management command, no docs.
https://openscience.atlassian.net/browse/ENG-2106
=> [ENG-2106] Add management command to copy custom taxonomies to allow hightlighting

.github/actions/build-es/action.yml, .github/workflows/test-build.yml
Fix GHA
- Pin to `ubuntu-20.04` to avoid varying between `18.04` and `20.04` with `latest` tag
- `sed` out the `UseParNewGC` ES2 Java opt, as it's unsupported.
None expected
=> [Hotfix] Fix GHA

osf/management/commands/update_mailchimp_email.py, osf/models/user.py, osf_tests/test_user.py, website/profile/views.py
Currently, when a user changes their primary email address, their email address in mailchimp isn't updated. 
Removing the mailchimp updating from website/profile/views.py and moving it to the user.save() method, anytime the username is updated, it will update mailchimp.
- Verify Mailchimp gets the new email address
- Verify the backfill updates all email addresses
N/A
Shouldn't be. This is a better solution than before.
https://openscience.atlassian.net/browse/ENG-2381
=> Changing primary email address should change email in mailchimp [ENG-2381]

website/static/js/logActionsList.json
Resolves `Unable to retrieve log details` message on newly created projects from no-project draft registrations.
* Adds a log message mapped to `project_created_from_draft_reg` to logActionsList.json
- Verify a newly created project based upon a no-project draft registration has an appropriate log message
N/A
N/A
N/A
N/A
[JIRA Ticket](https://openscience.atlassian.net/browse/ENG-2655)
=> [ENG-2655] Adds a log message for projects created from no-project draft registrations upon registration

osf/management/commands/project_to_draft_registration_contributor_sync.py, osf_tests/test_management_commands.py
We are modifying draft registrations to copy contributors from the branched project upon creation. This means that post-release all new draft registrations will have contributors from the branched project. Pre-release draft registrations will not have contributors from the branched project. This management command ensures that existing draft registrations contributor permissions are in line with what users expect after contributor management shifts to be on the draft registration. 
- Creates a management command to copy contributors from projects to active draft registrations
- Creates a test for the management command
This should be dev tested on a staging environment
N/A
N/A
[JIRA Ticket](https://openscience.atlassian.net/browse/ENG-2626)
=> [ENG-2626] Add management command to copy contributors from projects to draft registrations

api/base/serializers.py, api/files/serializers.py, api_tests/files/serializers/test_file_serializer.py
Ensures that the correct node type (node or draft-node) is communicated in the Files API 
* Added an `if` branch to `get_target_type` in the FileSerializer to check and return if the target is a draft-node
* Created a `RelatedLambdaRelationshipField`, an extension of RelationshipField which allows for the argument of a lambda view to be specified as an attribute of the serialized object (rather than needing to be the fieldname attribute)
* Modified `NodeFileHyperLinkField` to extend `RelatedLambdaRelationshipField` 
* Added a lambda function for the `files` relationship on the BaseFileSerializer and specified the lambda argument
* Created a test for the link returned by the `files` relationship to ensure points to the `/nodes/` and `/draft_nodes/` endpoints appropriately
Please make …
=> [ENG-2655] Fixes node:draft-node typing in Files API serialization

api_tests/draft_registrations/views/test_draft_registration_list.py, osf/migrations/0228_abstractnode_branched_from_node.py, osf/models/registrations.py, osf_tests/test_draft_registration.py, tests/test_views.py, website/project/views/contributor.py, website/templates/emails/contributor_added_draft_registration.html.mako
Make sure initiators of a "No-Project" Draft Registration receive an email with the link to the registration.
Draft Registrations that are not associated with a Project currently have no means of discovery beyond the email link sent to contributors. Historically, contributors
* Call the `contributor_added` signal in `DraftRegistration.create_from_node` when creating a DraftRegistration without a backing project.
* Update the `send_mail` call when notifying new contributors to pass all args as kwargs to improve hygiene
* Update the `URL_TEMPLATE` for DraftRegistrations to match the correct, updated format
* Minor fix to email text for new Draft Registration contributors
* Tests to confirm new behavior
New tests verify that email is sent to the initiator iff the draft node is created …
=> [ENG-2691] No-Project email fixes

api/base/settings/local-dist.py
- Add newly added files-related throttle rates to local-dist.py
- Added `files` and `files-burst` to `api/base/settings/local-dist.py`
- This is updating a settings file for running the OSF locally, and is geared towards developer experience. When running the OSF locally, developers may have overlooked these two throttling rates which can cause unexpected errors when doing file operations. This PR and its changes should have no impact on end-users.
None
- NA
- NA
=> Add new throttle rates for files in local-dist

admin_tests/nodes/test_views.py, api/share/utils.py, api_tests/share/test_share_node.py, osf/management/commands/recatalog_metadata.py, osf_tests/management_commands/test_recatalog_metadata.py, tests/test_preprints.py
SHARE will be changing soon, and will not be merging data from different
sources together -- let's stop relying on that behavior
- update the metadata record sent to share:
- include the full node lineage (parent, grandparent, etc. up to the
root) for registrations and projects, including metadata (title and
guid-url identifier) for each – building the lineage for search
results previously depended on merging multiple records together
- include full metadata for non-registration nodes – previously
only marked a project deleted, relying on merging with harvested
data to fill in the rest
- don’t include emails or "profile image url" as identifiers
- don't include non-bibliographic contributors
- add `suid` and `central_node_id` to the pushed payload – makes it
unambiguous what object the …
=> [ENG-2543][ENG-2642] clean up how metadata is pushed to SHARE

package.json, webpack.common.config.js, website/static/js/apiApplication.js, website/static/js/apiPersonalToken.js, website/static/js/filepage/index.js, website/static/js/registrationUtils.js, website/static/js/search.js
History JS is no longer supported. Worse, it has legacy dependency issues. 
Getting rid of History js. Modifying the search page (the only place Histroy js was being used) to utilize the HTML5 History API instead.
- Verify the search page works as intended without history js 
- Verify
We have single use dependencies everywhere.
N/A
Shouldn't be.
https://openscience.atlassian.net/browse/ENG-2749
=> Removing History js [ENG-2749]

website/static/js/conference.js
Currently any filtering on meetings causes a sentry error and does not filter properly, this fix stops that error behavior.
- Simply stops filtering on tags
- Verify projects are filterable on the meetings page
🐞 fix, no docs
Can no longer filter on tags.
https://openscience.atlassian.net/browse/ENG-2215
=> [ENG-2215] Fix meeting filtering

admin/institutions/views.py, osf/models/institution.py, osf_tests/test_institution.py, website/mails/mails.py, website/templates/emails/institution_deactivation.html.mako
Send emails to institution users upon deactivation
* Send the following email to all users affiliated with the deactivated institution.
* Django mangers aren't used when querying on related models. Thus, we can query affiliated users and send notification emails after the institution has been deactivated.
* Failure in sending emails will be logged and sent to sentry.
* Success # and attempts # are logged
```
[admin.institutions.views]  INFO: Institution deactivation notification email has been sent to [5/5] users for [cord]
```
* Attempts to deactivate an inactive institution and reactivate an active institution are rejected and logged.
```
admin_1             | [osf.models.institution]  WARNING: Action rejected - deactivating an inactive institution [cord].
admin_1             | …
```
=> [ENG-2927] Send emails to institution users upon deactivation

admin/templates/internet_archive/internet_archive.html, api/base/utils.py, conftest.py, osf/external/internet_archive/tasks.py, osf/models/registrations.py
Remove the logs link endpoint and improve withdraw behavior to add justifications, fix pigeon auth token.
- Dry-up code by moving `IA_ARCHIVE_ENABLED` conditional
- Fix but getting attributes from token
- Remove pigeon logs link 
- add withdrawal_justification to data
None that that I know of.
=> remove logs endpoint link and fix withdraw behavior

api/base/serializers.py, api/nodes/views.py, api/registrations/serializers.py, api_tests/base/test_serializers.py
Fix API Disabled Wiki Behavior for Registrations
- Prevent 502 when hitting relationship url
- Create and Apply `HideIfWithdrawalOrWikiDisabled` to relationship
None expected
None
=> [Hotfix] Fix API Disabled Wiki Behavior for Registrations

api/schema_responses/serializers.py, api/schema_responses/views.py, framework/auth/oauth_scopes.py, osf/models/schema_response.py
During initial integration testing I encountered three minor bugs. This PR fixes them.
- `registration_schema` serialization was wrong and just outside of test ranges, simple fix
- If you PATCHed without a `revisions_response` dict it would 500 instead of no-oping
- We didn't add `SCHEMA_RESPONSE_READ/WRITE` to the scope config properly, so token auth didn't work. 
- `get_object` for the schema detail endpoint 500ed instread of 404ing for bad ids.
- We forgot to allow PATCHing for `revision_justifications`!
- Verify SchemaResponses are creatable and updatable via the API.
- Verify you can use the Bearer auth properly.
None.
=> Integration Fixes For Schema Responses

api/base/utils.py, api/nodes/views.py, api/providers/views.py, api/registrations/annotations.py, api/registrations/serializers.py, api/registrations/views.py, api/schema_responses/annotations.py, api/schema_responses/views.py, api/users/views.py, api_tests/identifiers/views/test_identifier_list.py, osf/models/node.py
1) Requests to the RegistrationDetail endpoint were breaking when embedding `SchemaResponses`.
2) Filterable fields through the API must either exist on the model or be assigned via annotation, so the `SerializerMethodField` being used to set `revision_state` on the serialized Registration was insufficient.
Adding the revision_state directly to the Registration model leads to some not-fun abstraction violations, so needed to come up with a pattern for setting this value via annotation.
* Fixed the `view_category` for `RegistrationSchemaResponseList`
* Added the concept of `api/{model}/annotations.py` as a place to store all relevant code to produce annotations for filtering and/or populating serializer fields
* Added `REVISION_STATE` subquery to `api/registrations/annotations.py` 
* Moved …
=> Fix embedding of schema_responses and make revision_state filterable

website/registrations/utils.py
Fix parser issues found while testing
- Add a cache `STORE` for shared db lookups (optimizations innit?)
- Capitalize metadata headers
- Close stringIO object to free memory after reading rows
- Ensure 'N/A' is caught by license regex
- Remove extra space on contributor full names
- Return both invalid and missing headers in raised validation error
- Return db compatible category; account for `Uncategorized` and empty category
Tested with project release
N/A
N/A
=> [ENG-3104] Add parser fixes

api/providers/tasks.py, api/providers/views.py, api/share/utils.py, osf/exceptions.py, osf/models/registrations.py, website/registrations/utils.py, website/settings/defaults.py
* Fix the preparation task
* Create two tasks to monitor registration bulk upload jobs and to create draft registrations
* Delete bulk upload job if registration rows fail creation
* Create a cron job that monitors uploads and kicks off reg. creation
* Fully implemented draft registration creation task without sending emails of errors
* Reschedule the monitor task to run every 3 hours
* Fixed Share failure on DraftNode creation
* Fixed missing auth when updating draft registration data
* Applied fixes form https://github.com/CenterForOpenScience/osf.io/pull/9776
N / A
https://openscience.atlassian.net/browse/ENG-3100
=> [ENG-3100] Bulk Upload: Monitor Upload and Create Draft Registration

api/registrations/serializers.py, osf/models/node.py, osf/models/schema_response.py, osf_tests/test_schema_responses.py, website/mails/mails.py, website/reviews/listeners.py, website/templates/emails/updates_approved.html.mako, website/templates/emails/updates_initiated.html.mako, website/templates/emails/updates_pending_approval.html.mako, website/templates/emails/updates_rejected.html.mako
Add the logical plumbing for sending emails to contributors and moderators as part of the registration update flow (plus placeholder emails).
* Added Email templates for the major milestones in the update process
* Added logic to SchemaResponse to send emails with appropriate events
* Added new tests to confirm notifications render and are sent to all users
*  Refactored `schema_response` fixture to `initial_response` in order to free up the "schema_response" name for `mock`ing purposes
* Fixed an implementation that made `node.get_active_contributors_recursive` and `node.get_admin_contributors_recursive` take O(n^2) time instead of O(n) time when getting only unique contributors
- Verify
- Verify
What …
=> Support for notifications during registration update flow

api/providers/tasks.py, website/mails/mails.py, website/templates/emails/registration_bulk_upload_failure_all.html.mako, website/templates/emails/registration_bulk_upload_failure_duplicates.html.mako, website/templates/emails/registration_bulk_upload_product_owner.html.mako, website/templates/emails/registration_bulk_upload_success_all.html.mako, website/templates/emails/registration_bulk_upload_success_partial.html.mako, website/templates/emails/registration_bulk_upload_unexpected_failure.html.mako
Fix bugs and add improvements to bulk upload tasks
* Only send emails if not dry run
* Improve logging and error messages for unexpected exceptions during bulk upload registration row creation
* Reverse error list for bulk upload outcome emails so that uploader see the error rows in the same order as the CSV
* Check institution affiliation before draft creation
* Note: post-creation affiliation check is not removed, which is provided by the class util method
* Detect duplicate rows in CSV and database
* Duplicates will cause the upload preparation phase to fail. The task now preemptively check conflicts before the bulk create. This error is different from "some fail" and "all fail" since the errors are only on the duplicated rows while the entire upload will fail. A new email template is …
=> [No Ticket] Bulk Upload - Improvements and Bug Fixes for Tasks

api/providers/tasks.py, website/settings/defaults.py
Bulk Upload: Task Fixes
* This PR contains three bug fixes that address release blocking issues
* The first two are for [bugs](https://www.notion.so/cos/Bugs-1802b3efdc92481ebb0fc437663cfb8f)
* 1 Added registration responses validation
* 2 Only project admin can create registration from it, thus this [bug](https://openscience.atlassian.net/browse/ENG-2814) is not triggered.
* The 3rd completes the register and approval-require flow for non-auto-approval providers, which removes the [pre-release blocker](https://www.notion.so/cos/Release-Check-in-94a4adacd37d4d67a9ea11d5cb7b6872)
* 3 Moved `.register()` and `.require_approval()` out of the auto-approval flow and improved exception handling
There will be another PR for more minor improves
See …
=> [No Ticket] Bulk Upload: More Task Fixes

framework/auth/__init__.py, framework/auth/cas.py, framework/auth/tasks.py, osf/models/user.py, tests/test_cas_authentication.py, tests/test_views.py
Avoid deadlock edge cases during login.
- Apply auth-related user updates async
Dev test; run various logins and ensure fields are updated
None expected
[ENG-3347](https://openscience.atlassian.net/browse/ENG-3347)
=> [Hotfix][ENG-3347] Apply auth-related user updates async 

framework/auth/__init__.py, framework/auth/tasks.py, framework/sessions/__init__.py, osf_tests/users/test_last_login_date.py
Further prevent conditions that may lead to deadlock. Follow-up to #9816 
- Avoid costly OSFUser update on every request
None expected.
[ENG-3347](https://openscience.atlassian.net/browse/ENG-3347)
=> [Hotfix][ENG-3347] Generalize user login/activity update task

website/project/metadata/character-lab-long-form-registration.json
Character Lab's long-form registration schema is missing the `Q10` response key.
This results in upload fails with `invalid column ID`
- Update: Judgment
N/A
N/A
N/A
TBD
=> [Ticket TBD] Add missing response key Q10 to CL long-form schema

addons/wiki/models.py, addons/wiki/tests/test_wiki.py, addons/wiki/utils.py, addons/wiki/views.py
Fix Wiki rendering. In certain cases, backend rendering can hang. In all cases it is unnecessary; the front-end renders it.
- Replace calls to `WikiVersion.html()` with `WikiVersion.content`
- Verify wiki's render as expected in both widget and on wiki page
- Leaves dead code.
- Introduces potential miscalculation for displaying "Read more"  link in wiki widget -- now counts by raw text rather than rendered length. At worst, will display "Read more" unnecessarily, and link to the `/<pid>/wiki/home`
N/A
=> [Hotfix] Disable backend wiki rendering

osf/metrics.py
Allow filtering metrics by both before and after
- Add `before`
- Avoid `IndexNotFoundError`
Slightly slower searching to avoid `IndexNotFoundError`
None
=> [Hotfix] Allow filtering metrics by both before and after

osf/models/notable_email_domain.py
follow-up bug-fix for #9749 -- filtering and updating NotableEmailDomains in the admin breaks
even though `IntEnum` subclasses `int`, django seems to get
confused when validating or filtering on `IntEnum` values --
explicitly cast the choice value to `int` instead.
- Verify can filter admin list of notable email domains
- Verify can create, update, delete, and bulk-add notable email domains
[ENG-3110]
[ENG-3110]: https://openscience.atlassian.net/browse/ENG-3110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENG-3110][fix] handle django admin's handling of IntEnum choices

api/providers/tasks.py, osf/exceptions.py, osf/models/registration_bulk_upload_row.py
Refactor the `bulk_create_registrations` task
Update
* Refactored `handle_registration_row()` to use helper classes with improvements
* `check_node()`
* `prepare_subjects()`
* `prepare_institutions()`
* `prepare_contributors()`
* `prepare_license()`
* `bulk_upload_create_draft_registration()`
* `set_draft_contributors()`
* `set_affiliated_institutions()`
* `bulk_upload_register_draft()`
* Moved error aggregation and outcome email sending to `bulk_upload_finish_job` with improvements
* Created `RegistrationBulkCreationContributorError` and `RegistrationBulkUploadContributors` to support the refactor
TBD
TBD
TBD
https://openscience.atlassian.net/browse/ENG-3288
=> [ENG-3288] Part 1: refactor task `bulk_create_registrations`

api/providers/tasks.py
Fix non-bibliographic initiator during registration bulk creation.
For details, see the discussion in FD: https://www.flowdock.com/app/cos/bulk-upload/threads/44f0XKRGNPuFMXCL3qzuqFwTMsx
* Temporarily set the initiator contributor as visible before removing the others from the draft.
```python
Processing registration row [1: upload=100, row=233]
initiator contributor not visible
initiator contributor set to visible temporarily
contributor: DraftRegistrationContributor object; user: longze@cos.io
contributor: DraftRegistrationContributor object; user: roger@cos.io
removed or not: True
contributor: DraftRegistrationContributor object; user: doudou@cos.io
removed or not: True
contributor: DraftRegistrationContributor object; user: naxin@cos.io
removed or not: True
```
* Added an assertion to …
=> [ENG-3424] Fix non-bibliographic initiator during registration bulk creation

osf/models/schema_response.py, osf_tests/management_commands/test_fix_initial_schema_responses.py, osf_tests/test_schema_responses.py
avoid file-input weirdness
When checking to see if a `files-input` response has changed, compare the set of file_ids instead of the full dictionaries. This fixes two bugs in Registration Update:
One, the case where the `html` link create by Archiver for the file reference doesn't match the Files API's `html` link, leading to unanticipated updates to `file-input` respone blocks.
Two, the case where users remove and then re-add files as part of an update (or restore the files in an answer to match the previous version). Previously, this would also have looked like a change when it really wasn't.
* Add an `_is_updated_response` helper method to `schema_response.py` and use it when checking to see if a response has been updated or reverted
* `_is_updated_response` just checks the response …
=> File-specific response comparison

osf/management/commands/approve_pending_schema_responses.py, osf/models/schema_response.py, osf_tests/management_commands/test_approve_pending_schema_responses.py, website/settings/defaults.py, website/templates/emails/updates_pending_approval.html.mako
Registration Updates should auto-approve (at the admin level) just like the initial Registration.
* Script to identify and approve `UNAPPROVED` SchemaResponses with submission timestamp longer than the environment's auto-approval threshold.
* Tests
* 
- Verify
- Verify
=> Script to auto-approve registration updates

api/registrations/annotations.py, api/registrations/serializers.py, api_tests/registrations/views/test_registration_detail.py
Nested registrations don't have their own revisions, they inherit them from the root. That should include the `revision_state` attribute.
* When annotating `revision_state`, look for a SchemaResponse on the root
- Verify
- Verify
=> [Hotfix] Get revision_state from root

.github/workflows/test-build.yml, api/registrations/serializers.py, api/schema_responses/serializers.py
AVOLs are currently broken for registrations, as is our GHA workflow. Replacement for https://github.com/CenterForOpenScience/osf.io/pull/9843
* Surface SchemaResponse fields on anonymized Registration
*  Properly anonymize SchemaResponses
* Disable the NVM and Yarn Install workflow until the issue can be root-caused
- Verify
- Verify
=> [Hotfix] Fix Registration AVOLs for SchemaResponses, disable broken GHA workflow

.github/actions/start-build/action.yml, .github/workflows/test-build.yml
Fix and re-enable js tests to build and run on GHA.
* Stop using both npm & yarn to build js deps in GitHub Actions.
Replace usage of `npm install` with `yarn add --exact`.
The `invoke assets --dev` step of the `api1_and_js` test started
failing recently.  That command calls `yarn install
--frozen-lockfile`, which was crashing with the error 'An
unexpected error occurred: "Commit hash required".'
Real talk: I have no idea why this is happening, but commenting out
the `npm install` step in action.yml fixes it.  npm yells loudly
about mixing it with yarn, so let's take them at their word and
replace it.  Running `yarn install` in the "Start Build" action
could fix it, but I suspect it was split up to avoid installing the
full yarn deps for tests that don't need them.  Passing `yarn add`
the …
=> [CR] fix api1_and_js gha javascript tests

admin/management/views.py, admin/templates/management/commands.html, osf/management/commands/update_registration_schemas.py, osf/utils/migrations.py, osf_tests/default_test_schema.py, osf_tests/management_commands/test_update_registration_schemas.py
We previously re-built the SchemaBlocks for all schemas as part of our update process in case any schemas had in-place changes. By not allowing in-place changes to Schemas, we improve transparency by making sure registrations always look the way they did when they were filled out, and we remove possible failure points by not frivolously deleting RegistrationSchemaBlocks
* When invoking `map_schemas_to_schema_blocks` function, only create RegistrationSchemaBlocks for schemas/versions that don't currently have any
* Make `unmap_schemablocks` a noop, since it is explicitly called in some migrations
*  Restore access to `Update Registration Schemas` management command in the admin app
*  Add a dry_run mode to the `update_registration_schemas` management command and make it transactional
* …
=> [Hotfix] Only create SchemaBlocks for new schemas

package.json, yarn.lock
Uglify is having trouble with ES6 files on staging. Re-add babel-loader and force a newer version of uglifyjs-webpack-plugin to make it happier.
- Verify
- Verify
=> Fix Uglify breakages

framework/auth/cas.py, framework/auth/tasks.py, framework/auth/views.py
Create a celery task for the affiliation process and update the ORCiD SSO flow.
* Framed the affiliation task without making ORCiD API request and parsing the response
* Instrumented the ORCiD SSO flow with the task
* QA notes will be updated when the full feature is ready for test
N/A
* Without the implementation of [ENG-3621](https://openscience.atlassian.net/browse/) missing, the task remains a no-op action for now since `check_institution_affiliation()` always returns `None`.
* As documented in the code, current implementation only supports one affiliation (i.e. loop returns once eligible affiliation is found, which improves performance). In the future, if we have multiple institutions using this feature, we can easily update the loop and affiliation process. …
=> [ENG-3622] Framing the async affiliation task and update ORCiD SSO flow

framework/auth/tasks.py, website/settings/defaults.py
* Retrieve verified source of affiliations from ORCiD public records
* Created a helper class `orcid_public_api_make_request()` to handle the request and return an `lxml.etree._Element`
* Updated `get_orcid_employment_sources()` and `get_orcid_education_sources()` to parse out affiliation source list
* Updated `check_institution_affiliation()` to work with the combined source list
* Added logging, sentry and exception handling
* Affiliation Eligible
```
[2022-03-09 20:16:41,843: INFO/MainProcess] Received task: framework.auth.tasks.update_affiliation_for_orcid_sso_users[a186c0db-d44e-43d4-93b2-22682c9d52f6]
[2022-03-09 20:16:41,845: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7f920b578d90> (args:('framework.auth.tasks.update_affiliation_for_orcid_sso_users', …
```
=> [ENG-3621] Retrieve verified source of affiliations from ORCiD public records

website/archiver/utils.py
Archiver is loaded before the django app is started during deploy, so Guid cannot be imported at the top of `website/archiver/utils.py`. 
Move the import into the function where it is used :(
- Verify
- Verify
=> Move import of Guid in Archiver to after django app loads

osf/models/quickfiles.py, website/search/elastic_search.py
Fix Spam bans for QuickFilesNodes
- Optionally return a users' recast QFN in `QuickFilesNodeManager.get_for_user`
- Conditionally skip deleting formerly-quick files from index if no suitable `AbstractNode` is found
N/A
N/A
None expected
None known.
=> [Hotfix] Fix Spam bans for QuickFilesNodes

tests/test_notifications.py, website/notifications/utils.py
DraftRegistrations created without a project often take 6s or more to create. This is in part due to some unnecessary queries  against `osf_notificationsubscription`.
- Remove unnecessary queries
- Disable inapplicable test.
Some other things may also speed up
Unknown
=> [Hotfix] Optimize No-Project api.DraftRegistrationList.post

api/base/throttling.py, api_tests/base/test_throttling.py
Currently ember isn't denouncing it's requests, so it's frequently hitting the throttle so we'll disable the throttle for ember. Unfortunately our throttling tests were skipped a long time ago due to an issue with Travis so we will have to un-skip them and make minor fixes.
- add `NonCookieAuthThrottle` class to `BurstRateThrottle`
- unskip and fix tests
- Verify throttle is disabled. this is a script I used that can reliably hit it: https://gist.github.com/Johnetordoff/7502ac92e292be9874e952c35d2acb3c#file-gistfile1-txt
Now we disable throttling across the board if the user includes a valid cookie in the request. …
=> [ENG-3732] Make burst-rate-throttle allow cookies

addons/wiki/templates/wiki-bar-modal-help.mako, scripts/populate_institutions.py, tests/test_views.py, website/language.py, website/static/js/addProjectPlugin.js, website/static/js/components/publicNodes.js, website/static/js/myProjects.js, website/templates/base.mako, website/templates/emails/conference_submitted.html.mako, website/templates/emails/new_public_project.html.mako, website/templates/emails/no_login.html.mako, website/templates/emails/reviews_submission_confirmation.html.mako, website/templates/emails/reviews_submission_status.html.mako, website/templates/emails/welcome.html.mako, website/templates/emails/welcome_osf4i.html.mako, website/templates/emails/welcome_osf4m.html.mako, website/templates/project/settings.mako, website/templates/public/pages/meeting.mako, website/templates/public/pages/meeting_landing.mako, website/templates/util/render_nodes.mako, website/views.py
- Route users to the new helpguide
- Update openscience.zendesk.com links to new help guides
- This updates all the links that are currently taking users to the old helpguides (openscience.zendesk)
- NA
-NA
[ENG-3714]
[ENG-3714]: https://openscience.atlassian.net/browse/ENG-3714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENG-3714] Reroute users to new help guide

addons/base/views.py, addons/osfstorage/tests/test_views.py, website/views.py
Ensures the project file page and the project files page are routed to Ember on the correct waffle flag
- add flag conditionals to `guid_resolve`
- Verify `<project-guid>/files/<provider>` routes correctly on flag `EMBER_PROJECT_FILES`
- Verify `<file-project-guid>/` routes correctly on flag `EMBER_FILE_PROJECT_DETAIL`
- Verify `<file-project-guid>/?action=download` downloads the file
- Verify `files/<provider>/<id>/` routes correctly on flag `EMBER_FILE_PROJECT_DETAIL` to that files guid.
https://openscience.atlassian.net/browse/ENG-3760
=> [ENG-3760] add project files routes to guid routing

addons/base/views.py, addons/osfstorage/tests/test_views.py
Some addon file nodes seemlingly redirect before a history entry can be made, this breaks things.
- move touch function so it's before the redirect
- Verify
- Verify
https://staging-sentry.cos.io/cos/osf-back-end-77/issues/13316/
=> Fix issue creating ahistorical files

addons/osfstorage/tests/test_views.py, osf_tests/test_guid.py, website/views.py
To route unauthenticated users properly to CAS when they visit a node they don't have access to, even when going to the new emberized `files/` endpoint.
- Check users permissions and redirect them to CAS
- Verify that `<project-guid>/files/` redirect to CAS for an unauthenticated user.
- Verify
https://openscience.atlassian.net/browse/ENG-3832
=> [ENG-3832] Add redirect based for unauthed files page user

scripts/populate_institutions.py
As product requested, created a demo institution on the test server.
* Add a institution with name `OSF Demo Institution` and ID `osfidemo`
* Use placeholder assets and descriptions
* `email_domains` is left empty on purpose for product owner to modify later
- No CAS or Shibboleth
- Test server only and no need to deploy prod
* When a potential institution wants to test OSF, the product owner can modify the `email_domains` field in the Admin app.
* The institution project aggregate page will be https://test.osf.io/institutions/osfidemo/
N/A
See: https://docs.google.com/document/d/1t57_9ZBK75e8ggvcnSPWjq-4VAcoCKO7BvzaXS2xvJw/edit
N/A
N/A
=> [No Ticket] Add generic demo institution to the test server

api/base/serializers.py
Currently the `type` attribute in some node relationship is ignored and overridden by node's type, this PR ensures the proper type is passed.
- change serialize logic to pass canonical value. 
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3853
=> [ENG-3853] Fix node relationships' data type

addons/dataverse/models.py, api/base/views.py, api/files/serializers.py, api/nodes/views.py, api_tests/files/views/test_file_list.py
Currently Dataverse/WB send two versions of datverse files with the same path to osf.io, this is problematic because our FE/API can't distinguish which file to retrieve when asked to list files at that path. This PR adds a special case for dataverse so both files are listed at that path and passes the versioning infomation to the FE so they can style the files accordingly. 
This also removes an used branch of code by changing the logic of the `info` queryset retrieval code. Those are the changes in `api/nodes/views.py`.
- add special `MultipleObjectsReturned` case for dataverse only
- passes `extra` version info to FE
- add tests
- Verify
- Verify
Any …
=> [ENG-3872] Fix dataverse 502s and pass version info to FE

osf/apps.py, osf/migrations/0156_create_cache_table.py, osf/migrations/__init__.py
This is a small part of the larger Django Upgrade project which goal is to simplify the "migration stream" to include less archaic code. here we are moving the create cache migration into a post migration signal and using a managment command wrapper instead of raw SQL, to keep more in line in framework practices.
- removes migrations dependent and merging with the createcache migration stream. 
- adds post-migrate signal that builds cache 
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3820
=> [ENG-3820] Create Cache Table for NodeStorage as a post-migrate signal

osf/apps.py, osf/migrations/0038_ensure_schemas.py, osf/migrations/0077_ensure_schemas.py, osf/migrations/0078_ensure_schemas.py, osf/migrations/0080_ensure_schemas.py, osf/migrations/0096_ensure_schemas.py, osf/migrations/0112_ensure_schemas.py, osf/migrations/0136_preprint_node_divorce.py, osf/migrations/0137_transfer_preprint_service_permissions.py, osf/migrations/0142_change_registration_schemas.py, osf/migrations/0152_ensure_schemas.py, osf/migrations/0162_post_migrate.py, osf/migrations/0170_ensure_schemas.py, osf/migrations/0172_ensure_schemas.py, osf/migrations/0173_ensure_schemas.py, osf/migrations/0191_migrate_schemas_to_schemablocks.py, osf/migrations/0196_update_schemas.py, osf/migrations/0199_draft_node_permissions.py, osf/migrations/0204_ensure_schemas.py, osf/migrations/0207_ensure_schemas.py, osf/migrations/0207_update_schemas2.py, osf/migrations/0208_update_EGAP_schema.py, osf/migrations/0221_add_schemas.py, osf/migrations/0227_add_secondary_data.py, osf/migrations/__init__.py, osf/utils/migrations.py
Move schema ensuring and schema blocks update to post-migrate signals
Note: This is a shameless copy of @jwalz 's proof-of-concept PR: https://github.com/CenterForOpenScience/osf.io/pull/9938. There are only three minor updates:
* Included one extra `ensure_schema` migration: `0142_change_registration_schemas.py`
* Replace duplicate function with inline imports to fix circular imports.
* Reworked the commits
- ~~This PR is rebased upon the latest develop, which is slightly ahead of the django upgrade feature branch: https://github.com/CenterForOpenScience/osf.io/tree/feature/django_upgrade, should we bring the feature branch up-to-date before re-targeting this PR?~~ I happened to make a favorable mistake where this branch is not rebased upon the latest develop.
Migrations that adds or …
=> [ENG-3863] Move schema ensuring and schema blocks update to post-migrate signals

osf/apps.py, osf/migrations/0136_preprint_node_divorce.py, osf/migrations/0147_blacklistedemaildomain.py, osf/migrations/__init__.py, website/settings/defaults.py
This makes population of Blocked Email Domains a post-migration signal in preparation of the Django upgrade.
- removes license migration from the migration stream
- add new signal to populate migrations
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3868
=> [ENG-3868] Move blocked email domains to post-migrate signal

osf/migrations/0246_add_outcomes_and_artifacts.py, osf/models/outcome_artifacts.py
When we POST a new OutcomeArtifact (/Resource), we do it without a PID. As such, the `identifier` field must be Nullable to enable our workflow.
Doing this in the existing migration since it is only live on staging environments.
* Update model and existing migration to reflect nullability of the FK to `osf.identifier`
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3894
=> [ENG-3894] Rewrite history to make OutcomeArtifact.identifier nullable

requirements.txt
Add `PyYAML` to Requirements
Jenkins build failure reveals a missing package [`PyYAML`](https://pypi.org/project/PyYAML/) which is introduced in [`import yaml`](https://github.com/CenterForOpenScience/osf.io/pull/9950/files#diff-13b1f8258ce709fc64de14e9d995864e9497d9089b948357d24e7f3cfe78f552R3).
However, we all missed this one since builds consistently succeed in both local and GitHub action. This is because `PyYAML` is a dependency of `pre-commit` which is not available for server builds.
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-3836 follow-up fix
=> [ENG-3836] Follow-up: Add PyYAML to Requirements

osf/apps.py, osf/migrations/0138_ensure_subjects_and_providers.py, osf/migrations/__init__.py, osf/models/provider.py, osf_tests/test_registration_bulk_upload_parser.py
This is second PR to explore the different provider population options.
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3862
=> [ENG-3862][Take 2] Move post-migrate signal out of migration stream for default providers

website/project/decorators.py
The `check_contributor_auth` decorator was ~always redirecting to CAS in the case of a failed `check_can_access` check -- which would then redirect a logged-in user back to the url for the resource and back to CAS ad nauseam
Only redirect to CAS in the case where `user` is `None` (i.e., the user isn't already logged in). Otherwise, just return None and let the App decide what to do (403 or 404).
- Verify
- Verify
=> [HOTFIX] Fix `check_contributor_auth` infinite loop

api/resources/serializers.py, api_tests/resources/views/test_resource_detail.py, osf/exceptions.py, osf/models/identifiers.py, osf/models/outcome_artifacts.py, osf/utils/identifiers.py, osf_tests/test_identifiers.py, osf_tests/test_outcomes.py, website/settings/defaults.py
We want to alert users when they try to assign an invalid DOI to a resource. For DOIs, we do this by curling against `https://doi.or/ra/<doi_value>`. This will tell is where the DOI is registered if it is valid. Otherwise, it will tell us if the DOI is either malformed or simply hasn't been registered.  We skip this step for DOIs that we generated (i.e. DOIs that have an OSF `referent`), since we have a high level of confidence in their correctness.
Pinging the `/ra/` endpoint also empowers future work to store the registering agency to enable querying of PID metadata in the future.
* Add a `PIDValidator` Abstract class and `DOIValidator` subclass to handle validation for `Identifier` values
* Add `settings` values to control if validation happens and what endpoints to use
* Add …
=> [ENG-3945]Validate DOIs on PATCH

addons/bitbucket/api.py
Attempting to authenticate with `bytes` causes errors.
- `ensure_str` on `__init__`
None expected
=> [Hotfix] Ensure BitBucket token is string

api/base/exceptions.py
Be consistent with JSONAPI error spec
Add a `status` entry to the error dictionary, borrowing the `status_code` from the parsed exception
- Verify
- Verify
=> Add 'status' to JSONAPIError dictionary

api/base/exceptions.py, api/registrations/serializers.py, api/resources/annotations.py, api_tests/resources/annotations/test_open_practice_badge_annotations.py, osf/utils/outcomes.py
Add `has_papers` and `has_supplements` annotations to Registrations
*Add annotations for `has_papers` and `has_supplements` to `api/resources/annotations.make_open_practice_badge_annotations`
* Add `has_papers` and `has_supplements` fields to RegistrationSerializer and make them filterable
* Update tests to include the new fields
- Verify
- Verify
=> Add `has_papers` and `has_supplements` fields/annotations

api/base/exceptions.py, website/views.py
Redirect to Ember App when users navigate to `[environment.]osf.io/<registration_guid>/resources`
Update `website.views.resolve_guid` logic to be aware of the new route
- Verify
- Verify
=> Add route for new Registration resources subpage (take 2)

api/resources/serializers.py, api_tests/nodes/views/test_node_detail.py, osf/models/identifiers.py, osf/models/node.py, osf/models/outcome_artifacts.py, osf/models/outcomes.py, osf/models/registrations.py, osf_tests/test_outcomes.py, tests/identifiers/test_datacite.py, website/identifiers/clients/datacite.py, website/identifiers/listeners.py, website/identifiers/tasks.py
Update our Registration DOI metadata to contain links to artifacts
Also resolves https://www.notion.so/cos/Can-t-delete-unfinalized-resource-2b48a647c38f4418a37cf1e0b2180711
* Update the Datacite DOI client to include the Registration's artifacts as `relatedIdentifiers`
* Make `website.identifiers.tasks.update_doi_metadata_on_change` a `queued_task`
* Update other call sites to remove the `enqueue_task` call that this applies
* Make `IdentifierMixin.request_identifier_update` a noop in the case where no value has been set
* This is in support of our plan to give Embargoed Registrations an empty, placeholder identifier 
* Call `update_doi_metadata_on_change` in `Registration.related_resource_updated` in the case of an addition or deletion or a change to the DOI value 
* Clean up imports in …
=> [ENG-3903] Add artifacts to DOI metadata as `relatedIdentifiers`

osf/models/identifiers.py, osf/models/node.py, osf/models/sanctions.py, osf_tests/test_sanctions.py, website/identifiers/tasks.py
In order for a Registration to have related Resources, it needs to be the PRIMARY Artifact on an Outcome. In order to be an Artifact, it needs an Identifier.
To that end, create a placeholder Identifier for registrations when they have an approved Embargo while waiting to mint the DOI until after the Embargo is terminated
* Modify `IdentifirMixin.set_identifier_value` to support `None` values
* Call `set_identifier_value(category='doi', value=None)` on every Registration in the tree in the `_on_complete` functionality of the Embargo model
* Update `Node.set_privacy` to check `get_identifier_value` instead of `get_identifier` when determining whether to "udpate" or "create" the DOI
* This is so that we can have `IdentifierMixin.request_identifier_udpate` ignore identifiers with …
=> [ENG-3981] Add placeholder Identifier to Embargoed Registrations

api/resources/serializers.py, api_tests/resources/views/test_resource_detail.py, osf/models/outcome_artifacts.py, osf_tests/test_outcomes.py
We previously wouldn't let users `finalize` a resource that matched the PID and Resource Type of another `finalized` resource, but we had nothing in place to prevent them from updating an already `finalized` resource to match another `finalized` resource.
This PR fixes that broken expectation.
See: https://www.notion.so/cos/Integrity-not-enforced-for-already-finalized-resources-46e42f27b1f2431385acadb4d14d3567
* Check for other (`finalized`, non-`deleted`) `OutcomeArtifacts` matching the current one after updating if the `OutcomeArtifact` being updated is `finalized` and raise an IntegrityError if any exists.
* move the `@atomic` decorator to the `update` method instead of just the `_update_identifier helper method`
* Similarly to the check in the `finalize` function, this explicit check …
=> [ENG-3962] Enforce Integrity on update of `finalized` resources

admin/base/urls.py, admin/common_auth/urls.py, requirements.txt
Upgrades password reset for Django 3 [django-password-reset Changealog](https://django-password-reset.readthedocs.io/en/latest/)
⚠️ See if this is being used and where.
https://www.notion.so/cos/10-Django-Reset-Password-Update-View-e34bbfb074d244aba6d12e4a5941c1e2
⚠️ Based on Lozenge's comment I removed the views.
- updates requirements.txt and use different import path for urls.
- Verify
- Verify
=> [Django Upgrade] [ENG-3947] Remove `password_change` view and route in admin

admin/brands/views.py, admin/internet_archive/views.py, admin/management/views.py, admin/nodes/views.py, admin/preprints/views.py, admin/registration_schemas/views.py, api/base/pagination.py, api/base/serializers.py, api/base/versioning.py, api/files/annotations.py, api/files/serializers.py, tests/json_api_test_app.py
https://www.notion.so/cos/6188c43512ee482586da59bc5fdacf38?v=bb051c7d4d7346d69d9fcbbc979dd883
=> [Django Upgrade] [ENG-3947] Update import paths and fix module deprecation

api_tests/files/views/test_file_metadata_record_detail.py, api_tests/files/views/test_file_metadata_record_download.py, api_tests/schemas/views/test_file_metadata_schema_detail.py, osf/migrations/0136_add_datacite_file_metadata_schema.py, osf/migrations/0137_add_fm_record_to_osfstorage_files.py, osf/migrations/__init__.py, osf_tests/test_file_metadata.py
Pull the not fully implemented file metadata out of the migration stream. This is similar to the other PRs involving post-migration signals, but because this wasn't a fully implemented feature it's doesn't need a signal.
=> [Django Upgrade] [ENG-3947] Move file metadata population to unit test fixtures

api/base/serializers.py, api/resources/serializers.py, api_tests/registrations/views/test_registration_resource_list.py, api_tests/resources/views/test_resource_detail.py
Resources were not surfacing the `resource_type` in Anonymized contexts, and the `self` link for the Resources omitted the VOL, potentially leaking information for public registrations.
See:
https://www.notion.so/cos/Resource-self-link-does-not-inherit-VOL-key-723d274267cb4ad18768a2b6378cf6fe
https://www.notion.so/cos/resource-type-not-serialized-in-AVOLs-c09186bfee9e4b04b3ce2a02b22d51d8
* Add `resource_type` to the `nonanonymized_fields` for a Resource
* Update `LinkFields` to always append an vol key to `self` links
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-3962
=> [ENG-3962] Fix issues with Resource (A)VOLs

osf/models/node.py
<s>Change to cachedprotery in 2.2 broke this
https://docs.djangoproject.com/en/4.0/releases/2.2/#cached-property-aliases
</s>
This issue was actually created by not retrieving the exact value from a sub-queryset and instead using a subquery as a value.
=> [Django Upgrade] [ENG-3947] Storage region slice subquery issue

requirements.txt
Note: PR description added by reviewer.
Django 3.0 [Removed private Python 2 compatibility APIs](https://docs.djangoproject.com/en/4.0/releases/3.0/#removed-private-python-2-compatibility-apis) which includes the following change.
> `django.utils.six` - Remove usage of this vendored library or switch to `six`.
We have in-house library [django-elasticsearch-metrics](https://github.com/CenterForOpenScience/django-elasticsearch-metrics) that is affected. Here is the [PR](https://github.com/CenterForOpenScience/django-elasticsearch-metrics/pull/80) that updates the library.
Update requirements to ping to a PR commit. It will be updated post-release when the aforementioned PR is merged.
N/A
N/A
N/A
Part of https://openscience.atlassian.net/browse/ENG-3947
=> [Django Upgrade] [ENG-3947] Upgrade `django-elasticsearch-metrics`

admin/meetings/views.py, api_tests/preprints/views/test_preprint_detail.py
Note: PR description added by reviewer
This incompatibility comes from [Feature Removed in 2.0](https://docs.djangoproject.com/en/4.1/releases/2.0/#features-removed-in-2-0)
> Support for direct assignment to a reverse foreign key or many-to-many relation is removed.
This might have been missed by (or was added after) https://github.com/CenterForOpenScience/osf.io/pull/9300.
Replaced direct assignment with `.add()` and/or `.set()`.
Part of https://openscience.atlassian.net/browse/ENG-3947
=> [Django Upgrade] [ENG-3947] Direct assignment fix for Django 3

addons/wiki/models.py, requirements.txt, website/project/views/comment.py
Old versions of markdowns python library no longer work with Django so we have to upgrade Markdown to be compatible and update a few functions.Additionally Our forked markdown extension library https://github.com/CenterForOpenScience/mdx_del_ins/ is no longer compatible with markdown, so it had to have a minor fork. https://github.com/CenterForOpenScience/mdx_del_ins/pull/1
https://www.notion.so/cos/6188c43512ee482586da59bc5fdacf38?v=bb051c7d4d7346d69d9fcbbc979dd883&p=02a1b6368b0b47fbbab07a01d88135d9&pm=s
Error:
https://gist.github.com/Johnetordoff/84c900be9f2427db40ac57d18386cf6f
- updates markdown to use new format for passing arguments
- forks mdx_del_ins to work with new version of markdown.
- Verify …
=> [Django Upgrade] [ENG-3947] Update markdown extension

api_tests/resources/views/test_resource_detail.py, osf/exceptions.py, osf/models/outcome_artifacts.py, osf_tests/test_outcomes.py
Previously, you could add a Registration to its own list of Resources. Meanwhile the `RegistrationResourceList` was excluding entries  that referenced the Registration's DOI bu the but the `has_*` attributes on Registrations were not, leading to inconsistencies where the Registration was showing different badges than what was appearing on the Resources nav (in the case where the Registration was the only source of the badge).
It was [agreed](https://app.slack.com/client/T03LU72HEG4/C03SUSV5MS8/thread/C03SUSV5MS8-1660746232.846549) that we should prevent the Registration from being used as a resource (for now) but that we did not need to improve the filtering of the `has_*` attributes as the bad data is confined to Staging2.
See:
https://www.notion.so/cos/Difference-between-has-attributes-a …
=> [ENG-3962] Prevent using the PID of the Primary Artifact as another Artifact

api_tests/draft_registrations/views/test_draft_registration_list.py, api_tests/nodes/views/test_node_draft_registration_list.py, api_tests/schemas/views/test_registration_schemas_detail.py, osf/migrations/__init__.py
Move schema visibility/activeness update to pytest fixtures to fix the following errors, which was caused by a registration schema named "Election Research Preacceptance Competition" being visible/active while the tests expect it not to be. This fix is similar to what we did in https://github.com/CenterForOpenScience/osf.io/pull/9994. 
```
___ TestDraftRegistrationCreateWithNode.test_registration_supplement_errors ____
api_tests/nodes/views/test_node_draft_registration_list.py:453: in test_registration_supplement_errors
name='Election Research Preacceptance Competition', active=False)
/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/django/db/models/manager.py:85: in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs) …
```
=> [Django Upgrade] [ENG-3947] Move schema visibility/activeness update to `pytest` fixtures

api_tests/identifiers/managment_commands/test_sync_dois.py, osf/management/commands/sync_doi_metadata.py, tests/identifiers/test_datacite.py, website/identifiers/clients/datacite.py
DOI update was failing validation due to the inclusion of duplicates. It also wasn't excluding deleted Resources or non-final Resources, and there were some lingering issues with the existing Datacite update logic to be resolved.
* Only list each resource as a `relatedIdentifier` one time
* Exclude deleted and non-finalized Resources from the `relatedIdentifiers`
* Add tests for these cases
* Use known DOI values for the node when updating DOIs instead of always inferring
* Fix the logical flow within `DataciteClient.update_identifier`
* Fix tests for the sync_dois management command
- Verify
- Verify
=> Fix DOI Updating

osf/models/outcome_artifacts.py, osf/utils/identifiers.py, osf_tests/test_outcomes.py, tests/identifiers/test_datacite.py, website/identifiers/clients/datacite.py
Apparently, when urljoin receives a properly-formed URL (with protocol) as its second argument, it just returns that. So we were following random links if given as a PID value. No bueno. We've also wanted to not blow up on users when they pass the full DOI URI (doi.org/<10.xyz>). This PR resolves both of those problems.
* Add a `normalize_identifier` function to extract just the identifier value from a given pid uri
* Use `normalize_identifier` before attempting to update the PID
* Tests
* Fix unrelated probabilistic test fail
* order_by works weird followed by value list and ordering of `relatedIdentifiers` doesn't really mater, so remove it and make the test pass another way
- Verify
- Verify
What are …
=> Normalize PID input

.github/workflows/test-build.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

website/settings/local-dist.py
`SameSite=None` breaks local environment since it is blocked by the browser when OSF tries to set it via HTTP.
As is confirmed by [SameSite#none](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#none)
> Cookies will be sent in all contexts, i.e. in responses to both first-party and cross-site requests. If SameSite=None is set, the cookie Secure attribute must also be set (or the cookie will be blocked).
I am not sure what the settings are for our servers. This change only affects local env but may create a difference between local and server.
`SESSION_COOKIE_SAMESITE` is now set to `'Lax'` instead of `'None'` for local development
N/A
N/A
N/A
N/A
=> Set cookie samesite to 'Lax' for local env

framework/sessions/__init__.py, osf/models/user.py
This PR fixes an issue with the session object that arose with our `itsdangerous` library during the Django upgrade. I'm unsure exactly why this changed because our `itsdangerous` library is still pegged at the same version, but the fix seems simple enough.
Updated by CR:
This might be related with Django removed `bytestring` support in 2.0
https://docs.djangoproject.com/en/4.1/releases/2.0/#removed-support-for-bytestrings-in-some-places
The `ensure_str()` that we added for the `drf` cookies is from @Johnetordoff 's upgrade touch-up PR: https://github.com/CenterForOpenScience/osf.io/pull/9398 ⭐ .
The two cases here are outside DRF, one for old `flask` session/auth and the other for v1 `addon/files`.
Part of https://openscience.atlassian.net/browse/ENG-3948
=> [Django Upgrade] [ENG-3948] Fix session cookie decoding issue

api/draft_registrations/serializers.py
Replaces https://github.com/CenterForOpenScience/osf.io/pull/10034/
Reference PR: https://github.com/CenterForOpenScience/osf.io/pull/10057
For details of the DRF MRO change, refer to this [issue](https://github.com/encode/django-rest-framework/issues/5798) and [PR](https://github.com/encode/django-rest-framework/pull/6980) for DRF.
* `DraftRegistrationDetailSerializer` inherits from `DraftRegistrationSerializer` and `DraftRegistrationDetailLegacySerializer)`. Both of them define (or further inherits) `registration_schema = RegistrationSchemaRelationshipField(...)` with different params. The former inherits from `DraftRegistrationLegacySerializer` where `required=True` and `read_only=False`. The latter uses the default (both `False`). The DRF MRO upgrade led to …
=> [Django Upgrade] [ ENG-3498] Fix Draft Registration Serializer

framework/sentry/__init__.py, osf/metrics/counted_usage.py, osf/metrics/reporters/new_user_domain.py, tests/test_addons.py, tests/test_institutions/test_affiliation_via_orcid.py, website/identifiers/tasks.py
fix some problems which arose overnight
- explicitly stringify the `date` when sending `NewUserDomainReports` to keen
- replace naively recursive `_get_surrounding_guids` with iterative version, because turns out *some* nodes are >650 deep
- update unrelated sentry log to put the guid in `extra_data` so sentry knows how to aggregate it
- Verify
- Verify
=> [hotfix] keen replacement followup

admin_tests/institutions/test_views.py, admin_tests/nodes/test_views.py, admin_tests/preprints/test_views.py, admin_tests/users/test_views.py, api/draft_registrations/serializers.py, api_tests/draft_registrations/views/test_draft_registration_list.py, api_tests/nodes/views/test_node_detail.py, api_tests/nodes/views/test_node_draft_registration_detail.py, osf/models/base.py, osf/models/user.py, osf_tests/test_archiver.py, website/archiver/utils.py, website/static/urlValidatorTest.json
See: https://www.notion.so/cos/The-rest-of-the-fixes-ec6b2b2f96e74a2b902a1d57d2a8fe6a
* Ticket: https://openscience.atlassian.net/browse/ENG-4072
* Reference PR with initial attempts of fix: https://github.com/CenterForOpenScience/osf.io/pull/10048
* New Reference PR with following attempts + all tests passing: https://github.com/CenterForOpenScience/osf.io/pull/10074
* Part 1 of this PR: https://github.com/CenterForOpenScience/osf.io/pull/10070
* Fix linked_by_nodes in node related counts test
* Add alt fixtures to prevent both siblings & parent/child conflicts
* Improve to_internal_value() in NodeRelationshipField
* Revert "Fix an issue where get_node() is not availalbe from context view"
* Update URLs for URL Validation tests with Django 3
* Use a different schema to fix tests failure …
=> [Django Upgrade] [ENG-4072] The Rest - Part 2

api/institutions/views.py, osf/features.yaml
* Fix one flipped waffle in post-migration.
* This is a temporary fix that prevents one waffle being set to the wrong value which breaks OSF during post-migration.
* The long-term solution is to disable waffle update in post-migration for non-local environment.
* Reference: https://github.com/CenterForOpenScience/osf.io/pull/9950
* DRF change has led to MockQuerySet no longer have a model to use to validate "default" filterable fields.
* Before (3.8): [`get_default_valid_fields()`](https://github.com/encode/django-rest-framework/blob/3.8.2/rest_framework/filters.py#L180)
* After (3.13): [`get_default_valid_fields()`](https://github.com/encode/django-rest-framework/blob/3.13.1/rest_framework/filters.py#L208)
* The solution is to define them in `ordering_fields` for affected views which are …
=> [ENG-4136] Fix post-migration waffle and institution metrics

osf/external/spam/tasks.py, osf/migrations/__init__.py, osf/models/mixins.py, osf/models/notable_domain.py, osf/models/spam.py, osf_tests/test_notable_domains.py
To reclassify related resources when a `NotableDomain` is reclassified.
- Take some logic out of the `confirm_ham` hook of the `SpamOverrideMixin` into an `undelete` hook
- Modified the `confirm_spam` hook of the `SpamMixin` to include domains in `spam_data` if the resource is marked as spam because of a spammy domain.
- Add a `unspam` hook to `SpamMixin` and `SpamMixinOverride`
- Make use of the newly added `undelete` hook
- Modified the `save` hook of the `NotableDomain` class and only initiate the reclassification task when `note` has been changed.
- Modified the `reclassify_domain_references` task to spam and unspam related resources conditionally
- Add tests
- Verify
- Verify
What are the areas of …
=> [ENG-4087] Reclassification part 2

api_tests/collections/test_views.py, osf/models/collection.py, osf/models/node.py, osf_tests/test_collection.py
Prevent us from exposing details about a deleted or private project via the `CollectedMetaList` endpoint
* Move logic for what happens when removing a collected item to the CollectionSubmisison.delete()
* Update `AbstractNode.set_privacy()` and `AbstractNode.remove_node()` to delete all CollectionSubmissions when a node is made private or deleted
* Don't delete CollectionSubmissions for contributors' bookmark collections on make_private
* Add tests
* Remove brittle test that was checking an out-of-date error string
- Verify
- Verify
=> [ENG-3514] Delete CollectionSubmissions when collected project is deleted/marked private

api/nodes/filters.py
Optimize filtering nonnull parents
* Filter Nodes on `root_id!=id` rather than getting all `NodeRelations` where `child_id!=parent_id`
None Expected
None
=> [hotfix] Optimize filtering non-null parents

osf/external/spam/tasks.py, osf_tests/test_notable_domains.py
This is reverting the previous change to remove the constructed URL, but with the addition of `path` to the URL.
The reason we want to construct an URL is because `requests.head()` raises a `request.exceptions.MissingSchema` exception if the URL does not contain a `protocol` section. When that happens, it will be handled by the catch block on line 65 (line 70 after the change) and hit the `pass`. When that happens, the URL will be added as a NotableDomain regardless if it is really a valid URL. This PR fix the problem by constructed a URL with a protocol so that something that is not a URL would raise either `ConnectionError` or `InvalidURL`, and would not be added as a NotableDomain.
- Verify
- Verify …
=> [Hotfix] Construct a url for testing whether a matched string is a domain

api/providers/urls.py, api/subscriptions/views.py, api_tests/subscriptions/views/test_provider_subscription_detail.py, osf_tests/factories.py, website/templates/project/project.mako
Fixes duplicate `_id` issue for email subscriptions.
Adds API endpoints for  `preprints/<provider_id>/subscriptions/<subscription_id>/`, `registrations/<provider_id>/subscriptions/<subscription_id>/`, `collections/<provider_id>/subscriptions/<subscription_id>/`
- Verify
- Verify
=> Add provider moderator endpoints

osf/models/user.py
###
Remove user from institution metrics admin when affiliation is removed
For details, see: https://www.notion.so/cos/Remove-Institution-Admin-Access-if-a-User-Deletes-their-Institution-Affiliation-3d9d240cd90245338c91ce42bec3ddb8
=> [Institution Rework] Remove user from institution metrics admin when affiliation is removed

api/collection_submission_actions/serializers.py, api_tests/collection_submission_actions/views/test_collection_submissions_actions_list.py, osf/models/collection.py, osf/models/collection_submission.py, osf/models/node.py, osf/utils/workflows.py, osf_tests/test_collection_submission.py, website/mails/mails.py, website/search/elastic_search.py, website/static/js/pages/project-dashboard-page.js, website/templates/emails/collection_submission_cancel.html.mako, website/templates/project/project.mako
Pending collection submissions can't be withdrawn from consideration voluntarily by a project admin without some general bad UX, this adds a direct way for the user to cancel a pending collection submission without changing the privacy state of the project. 
- adds new trigger `cancel`  and new transition to the transitions list
- adds changes adding a cancel button to project overview page
- adds tests and serializer logic for canceling a collection submission
- Accessibility changes
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-4239
=> [ENG-4239] Add Cancel Behaviors for Collection Submissions

api/providers/serializers.py, api/providers/urls.py, api/subscriptions/serializers.py, api/subscriptions/views.py
Currently the subscription endpoint doesn't distingish a subscriptions provider type, that causes problems with duplicate `_id`s this fixes that.
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-4246
=> [ENG-4246] Add Specific Subscription Provider Endpoints for dupe ids

api/institutions/authentication.py, api_tests/institutions/views/test_institution_auth.py, framework/auth/__init__.py, osf/exceptions.py, osf/management/commands/migrate_user_institution_affiliation.py, osf/models/institution_affiliation.py, osf/models/user.py, website/mails/mails.py
https://openscience.atlassian.net/browse/ENG-4202
https://openscience.atlassian.net/browse/ENG-4204
Rework Institution SSO flow with identity and affiliation - API Part
CAS Part: https://github.com/CenterForOpenScience/osf-cas/pull/75
* Retrieve and parse the identity field from CAS
* Disambiguate the following attributes/properties
* SSO Identity (do not rely solely on `eppn` since institutions could use other attributes)
* SSO Email (an email provided by SSO, this may or may not be the same as user’s `username`)
* `username`
* User found by identity
* User found by SSO email
* Handle different cases of matching/mismatching identity and email (See code for details)
* CASE 1: new user: similar to the old flow's new user
* CASE 2: existing user by identity → add email and notify
* CASE 3: …
=> [Institution Rework] [ENG-4202] [ENG-4204] Rework Institution SSO flow with identity and affiliation - API Part

api/base/filters.py, api/base/views.py, api/collections/views.py, api/nodes/views.py, api/providers/views.py, api/registrations/views.py, api/subjects/views.py, api/taxonomies/utils.py, api/taxonomies/views.py, api_tests/registrations/views/test_registration_forks.py, osf/models/provider.py
Currently querysets that are ordered by a default ordering automatically override user provided sort parameters, this fix allows us to use both the view level default sorting and use the `sort` param to do a custom sort. Generally we wanted to stick to always sorting on DB fields or queryset annotations, even for default sorts even if just for consistency, 
- now querysets with `ordered==True`, are filterted on user params in `OSFOrderingFilter`
- logic that sorted subjects `is_other` ordering is now done using `_order` annotations.
- certain views whose default sorting was being ignored must get correct default odering parameters
- Verify
- Verify
Any …
=> fix ordering for collections moderation

api/institutions/authentication.py, api_tests/institutions/views/test_institution_auth.py, framework/auth/__init__.py, osf/management/commands/migrate_user_institution_affiliation.py, osf/models/institution_affiliation.py, osf/models/user.py
Add unit tests to cover reworked SSO flow with identity and affiliation
* Always use `None` (instead of `''`) when SSO identity is not provided
* When migrating existing SSO affiliations
* When removing identity from affiliations in the "duplicate account" case
* During institution authentication when identity is provided as empty or blank from CAS
* When calling `add_or_update` without the identity param
* Handle a corner case where SSO identity is not eligible
* Add unit tests to cover updated  SSO flow with identity and affiliation
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4229
=> [Institution Rework] [ENG-4229] Add unit tests to cover reworked SSO flow with identity and affiliation

osf/metadata/serializers/datacite_json.py, osf_tests/metadata/test_metadata_download.py
fix doi-minting for projects with non-YYYY license years
fix: in datacite serializer, check the format of dcterms:dateCopyrighted and fall back to date fields on the model if it does not match YYYY
- Verify projects with license year values that aren't just 4 digits can still get a doi
- Verify
[ENG-4392]
[ENG-4392]: https://openscience.atlassian.net/browse/ENG-4392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix][ENG-4392] datacite:publicationYear is stricter than dcterms:dateCopyrighted

framework/sessions/__init__.py
`get_session` should return empty session object when there is no cookie
Do not call `s.create()` in `get_session()` when there is no OSF cookie.
N/A
N/a
N/A
[ENG-4398](https://openscience.atlassian.net/browse/ENG-4398)
[ENG-4398]: https://openscience.atlassian.net/browse/ENG-4398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENG-4398] `get_session` should return empty session object when there is no cookie

website/templates/project/project.mako
Make all collection submission metadata fields appear on the project overview page.
- HTML template changes
Duplicating a lot of code here, but trying to keep it simple and declarative.
*currently only type (collected_type) and study_design appear here*
https://openscience.atlassian.net/browse/ENG-4395
=> [ENG-4395] Add Collection Submission Metadata

framework/status/__init__.py, osf/models/user.py
Since `session` is a `LocalProxy` of `get_session()`, everything we refer to `session` it is actually creating a new `SessionStore` object. Hence, doing `session['status'] = statuses` before `session.save()` is actually setting the `status` field of one `SessionStore` object and calling `save()` on another, therefore not updating the underlying session data in db/redis, even though the two `SessionStore` obects loads the same session data with the same `session_key`.
The fix is to directly call `get_session()` and store the `SessionStore` object in `current_session` and invoke `current_session.save()` after updating.
TBD
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4431
=> [Refactor Sessions] [ENG-4431] Fix status message

api/metrics/utils.py, api/metrics/views.py
Make MonthYear datetime work as expected for spam metrics filter.
- simple changes to date formatter, passes `is_monthly` format
There seemed to be some clashing with the `strict_date`/`strict_yearmonth` formatting with different environments, this preserves those fields without changing them and allows that YYYY-MM-DD format to be consistently used.
=> make month year datetime work correctly for spam metrics

osf/metrics/reporters/user_count.py
the "user count" nightly metrics report is failing on `develop`
update `OSFUser.objects.filter(affiliated_institutions__isnull...` to `OSFUser.objects.filter(institutionaffiliation__isnull...`
- Verify the `user_summary` metrics report (`osfapi:/_/metrics/reports/user_summary/recent/`) runs successfully each night
- Verify specifically the `new_users_with_institution_daily` field is correct-seeming (maybe add user with affiliation and check for increase the next day?)
[ENG-4412]
[ENG-4412]: https://openscience.atlassian.net/browse/ENG-4412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
=> [ENG-4412][fix] update user-count reporter to institution remodel

osf/management/commands/backfill_domain_references.py, osf/models/mixins.py, osf/models/user.py, osf_tests/management_commands/test_backfill_domain_references.py, osf_tests/test_notable_domains.py
We ran into a few issues with the `backfill_domain_references` management command on Prod.
* We were seeing duplicate results, driven by a naive query against `node__wikis__versions`
* The command was occasionally hanging while retrieving tags
* The supported parameter for checking users was incorrect (expected `User` but needed to be `OSFUser`)
* Replace the query against `node__wikis__versions` with an annotation that just notes the existence of any wiki version under the node that contains domain references
* Add a test for the case of multiple wiki versions with domains
* Add an option to `_get_spam_content` to omit `tags` when relevant
* `OSFUser` just adds an `**unused_kwargs` param, similarly to the `Comment` model to enable a consistent signature
* Fix the supported param for …
=> [HOTFIX] Fix Domain Backfill script

osf/external/spam/tasks.py, osf/management/commands/backfill_domain_references.py, osf/models/spam.py, osf_tests/test_notable_domains.py
Combining the `@run_postcommit` decorator with the `@task` decorator prevented us from actively running the `backfill_spam_domains` management command in non-local environments. Create separate functions for standard async execution and post-commit execution.
* Extract `check_resources_for_domains` functionality into a "protected", synchronous function.
* Create explicit `check_resources_for_domains_postcommit` and `check_resources_for_domains_async` functions and use them appropriately
* Fix tests that reference the old function to simply use the synchronous version
- Verify
- Verify
=> [Hotfix] Async Domain Extraction

website/static/js/logActionsList.json, website/static/js/logTextParser.js
https://staging-sentry.cos.io/cos/osf-front-end-r3/issues/16212/
Hack `logTextParser` to use a provided Title instead of just the guid when showing metadata updates.
- Verify
- Verify
=> Make GUID Metadata Logs actually display the name of the resource

api/logs/serializers.py
In a feat of surprisingly good separation of powers, the NodeLog widget on the Legacy FE actually pulls from the API. The NodeLog API, meanwhile, limits which NodeLog `params` are surfaced in order to ensure that some internal-only information remains internal-only. As such, the NodeLog widget had no access to the `title` param that was added to improve the readability of guid_metadata_updated NodeLogs. This PR surfaces that param.
Add `title` to the NodeLogParamsSerializer.
https://openscience.atlassian.net/browse/ENG-4411
=> [ENG-4411] Add title to NodeLogParams serializer

api/metrics/utils.py
Follow-up to #10355 
* Ensure default date values are parsed in YearMonth format for monthly metrics
* Increase default range (from `5` -> `150` days) for monthly metrics.
Manual endpoint verification
* 150 days is a cheap heuristic for months that will produce an inconsistent number of results on certain days, much like the previous default of 5 days.
[[ENG-4494]](https://openscience.atlassian.net/browse/ENG-4494)
[ENG-4494]: https://openscience.atlassian.net/browse/ENG-4494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Hotfix][ENG-4494] Fix Monthly Metric default dates

osf/models/analytics.py
* Reuse `auth_user_id`
* Save session before return if user is contributor.
See diff for details.
=> Fix a edge case where user session is not save in analytics

addons/osfstorage/tests/test_models.py, addons/osfstorage/tests/test_utils.py, api/base/settings/local-travis.py, framework/sessions/__init__.py
* Use DB backend when running unit tests on GitHub Actions.
* Fix add-on tests
* Properly create new session by calling `.create()` instead of or in addition to `.save()` to avoid key conflict
* Fix a discrepancy on Flask `g` between code and test.
N/A
N/A
Part of https://openscience.atlassian.net/browse/ENG-4393
=> [Refactor Sessions] [ENG-4393] Unit Tests - Part 1: Fix add-on tests

osf/models/user.py, osf_tests/test_user.py
Remove institution affiliations from merged user during merge
* Added a new helper method in `OSFUser` to remove all affiliated institutions
* Call this helper after affiliations have been copied when merging user
This is a hotfix that only needs post-release verification. However, this can’t be verified by QA via our website or the badmin app since the merged user is no longer active. What we need to do is to check that affiliations have been removed from a merged user via shell.
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4519
=> [ENG-4519] Remove institution affiliations from merged user during merge

framework/sessions/__init__.py, website/app.py
Fix an old bug for view-only link on legacy projects
* Remove the was-noop authentication check when processing view only link
* Remove deprecated order or handler notes
TBD
N/A
`prepare_private_key()` no longer have to be added before `before_request()`
N/A
=> Fix an old bug for view-only link on legacy projects

api/base/authentication/drf.py, osf_tests/test_session.py
Currently, we do `SessionStore().exists(session_key=session_key)` every time we want to get the session with a key. However, this is redundant, because if the `session_key` itself is not in redis/db, `SessionStore(session_key=session_key)` would not load the data at all, becasue the redis `GET` operation just returns nothing.
Therefore, simply removing the `SessionStore().exists(session_key=session_key)` in `drf_get_session_from_cookie` has the potential of reducing most of the `EXISTS` queries to Redis, potentially boosting performance because now the app does not have to do an extra query, and Redis has ~50% less queries to handle.
- Verify
- Verify
Any …
=> [Refactor Sessions] Redis performance improvement

osf/models/user.py, osf_tests/test_user.py
Cite unregistered contributors with the name provided when they were added
* Change `csl_name` logic to use `unclaimed_records` for unregistered contributors
* Update test
See Ticket
None expected
https://openscience.atlassian.net/browse/ENG-4557
=> [Hotfix][ENG-4557]Use provided name for unregistered contributors' csl_name

api/institutions/authentication.py, api_tests/institutions/views/test_institution_auth.py
Update selective SSO configuration for Yale Law School due to institution preferred ID change
`yalelaw` -> `yls`
N/A
N/A
Selective SSO for test server Yale Law School will be disabled until we update the institution ID. 
https://openscience.atlassian.net/browse/ENG-4435
=> [ENG-4435] Update selective SSO config due to institution preferred ID change

scripts/populate_institutions.py, website/ember_osf_web/views.py, website/templates/base.mako, website/templates/nav.mako
`osf.io/support` is being replaced by `help.osf.io`. Remove old links.
- Support links updated in the legacy top-nav and logged-in user drop-nav
- Updated in `populate_institutions.py`.
- Removed `/support` ember route.
- Also updated affected institution in the database.
https://openscience.atlassian.net/browse/ENG-4565
=> [Hotfix][ENG-4565] Remove deprecated support links

addons/s3/models.py, addons/s3/static/s3NodeConfig.js, addons/s3/tests/test_model.py, addons/s3/utils.py, addons/s3/views.py, api/addons/serializers.py, api/nodes/views.py, api_tests/nodes/views/test_node_addons.py
A system to allow a holder of S3 IAM credentials to link a CommonPrefix of their bucket to a project. This will allow project and their registrations to contain only a subset of the items inside a bucket.
- A bucket's root level path is now `/` instead of that buckets name.
- S3 special casing replaced in the NodeAddonFolderSerializer, S3 now passes a `bucket_name` query param to it's child buckets.
- Similar special casing for `bucket_name` in NodeAddonFolderList
https://docs.google.com/document/d/1glfVQLc5LNaqERcFE4vvsEoaVEveVjrtFERapq9TNxg/edit
Hypothetical behavior
- Verify
- Verify
Waterbutler-side fix …
=> [ENG-4566] S3 Subfolder Selection Feature

addons/s3/models.py, addons/s3/tests/test_model.py, addons/s3/utils.py, addons/s3/views.py, api/addons/serializers.py, api/nodes/views.py, api_tests/nodes/views/test_node_addons.py
We decided to move away from using parent directory names as bucket identifiers to delineating them with a colon. This is for two reasons:
- It looks better
- It allows the folder_id received to always be the same as the one sent.
- removes query param special casing and embraces the colon case.
- was discovered by QA test: https://github.com/CenterForOpenScience/osf-selenium-tests/blob/f9089d5b3db7673cf961e2874e955ddd93631936/api/osf_api.py#L406
- here's a script I ran to replicate that test locally:
```python
attributes = requests.get(
f'http://0.0.0.0:8000/v2/nodes/{node_id}/addons/s3/folders/',
headers={'Authorization': f'Bearer {token}'}
).json()['data'][0]['attributes']
raw_payload = {
'data': {
'type': 'node_addons',
'id': 's3',
'attributes': {
'folder_id': …
```
=> Use colon delineation for s3 buckets

addons/s3/utils.py
Because we are using an older version of boto we are subject to s3 region weirdness, this fixes that.
- remove old special casing that makes everything not work
- Verify
- Verify
relvent code from WB side:
```
async def _check_region(self):
"""Lookup the region via bucket name, then update the host to match.
Manually constructing the connection hostname allows us to use OrdinaryCallingFormat
instead of SubdomainCallingFormat, which can break on buckets with periods in their name.
The default region, US East (N. Virginia), is represented by the empty string and does not
require changing the host.  Ireland is …
```
=> Fix non-default regions for s3

osf_tests/test_archiver.py, website/archiver/utils.py
Improve special character handling 
- un-`bleach` `&amp;`'s
- For RegistrationSchemas that allow file uploads in response to questions, a file named `&.txt` should no longer break.
None expected
https://openscience.atlassian.net/browse/ENG-4192
=> [Hotfix][ENG-4192] Allow DraftRegistrations to register when attached files have '&' in the name

osf/metadata/osf_gathering.py, osf/metadata/rdfutils.py, osf/metadata/serializers/datacite/datacite_tree_walker.py, osf_tests/metadata/expected_metadata_files/file_full.turtle, osf_tests/metadata/expected_metadata_files/preprint_basic.turtle, osf_tests/metadata/expected_metadata_files/preprint_full.turtle, osf_tests/metadata/expected_metadata_files/project_basic.turtle, osf_tests/metadata/expected_metadata_files/project_full.turtle, osf_tests/metadata/expected_metadata_files/registration_full.turtle, osf_tests/metadata/test_osf_gathering.py
when building a metadata record, use an iri value for `dcterms:type` (aka `resourceNature`) to make it filterable in the new iri-centric search api
- introduce a namespace for terms defined in datacite 4.4: `https://schema.datacite.org/meta/kernel-4.4/#`
- datacite does not provide iris for each term, but that's ok -- for anyone curious how the term is defined, the iri leads to documentation
- use an iri in that namespace for each datacite resourceTypeGeneral value (in `dcterms:type`)
- before:
```
:my-item
dcterms:type "BookChapter" .
```
- after:
```
:my-item
dcterms:type <https://schema.datacite.org/meta/kernel-4.4/#BookChapter> .
<https://schema.datacite.org/meta/kernel-4.4/#BookChapter>
rdfs:label "BookChapter"@en .
```
Please make verification statements inspired by your code and …
=> [fix] filterable "resourceNature"

osf/metadata/osf_gathering.py, osf_tests/factories.py, osf_tests/metadata/test_osf_gathering.py
include withdrawal info in metadata gathered for indexing or download
- when gathering a metadata record, include withdrawal info for registrations and preprints
- `osf:dateWithdrawn` with the date the retraction/withdrawal completed
- `osf:withdrawal` with a separate object that has properties describing withdrawal/retraction itself
- has type `osf:Withdrawal`
- currently has no identifier of its own (blank node), but could in the future!
- for registrations this includes:
- `dcterms:created` with the date the retraction was initiated
- `dcterms:dateAccepted` with the date the retraction was completed (same as `osf:dateWithdrawn` on the registration)
- `dcterms:description` with the withdrawal justification
- `dcterms:creator` with a reference to the osf-user who initiated retraction
- …
=> get withdrawal metadata for registrations and preprints

addons/osfstorage/models.py, api/share/utils.py, osf/management/commands/recatalog_metadata.py, osf/models/files.py, osf_tests/management_commands/test_recatalog_metadata.py, website/search/elastic_search.py
Send file metadata to SHARE when files get updated, or the target it is contained within is updated
- Prefer `BaseFileNode.update_search` over older methods
- Extract, update `should_update_search` logic from `elastic_search.py` for reuse
- Ensure files `update_share` when appropriate
- Update `recatalog` command
None expected
https://openscience.atlassian.net/browse/ENG-4617
=> [ENG-4617] Send File Metadata to SHARE

osf/management/commands/recatalog_metadata.py, osf_tests/management_commands/test_recatalog_metadata.py
speedier `manage.py recatalog_metadata`
call `task__update_share.apply_async` instead of `update_share`
(because `framework.celery_tasks.handlers.enqueue_task` is a lie when called outside a request context (instead runs synchronously) -- is sometimes convenient, but not in this case)
- Verify
- Verify
=> [feature] recatalog metadata async

api/share/utils.py, api_tests/share/_utils.py, api_tests/share/test_share_node.py, osf/metadata/serializers/turtle.py, osf/metadata/tools.py, osf_tests/metadata/test_serialized_metadata.py
support non-ascii characters in metadata pushed to share/trove (oops)
- pass pre-encoded `bytes` to `requests.post` (instead of `str`)
- also add `charset=utf-8` to mimetype (more correct, tho it doesn't actually change anything)
- Verify non-ascii unicode characters get all the way thru to render in search results
- Verify
=> [fix] send utf8 to shtrove

api/institutions/serializers.py, api_tests/institutions/views/test_institution_detail.py
provide the institutions search frontend with all it needs
- add `iris` attribute to `InstitutionSerializer` with a list from the institution's `get_semantic_iris()` (to filter for an institution that may or may not have a ror id or non-osf iri)
- add `banner` to the `assets` attribute (to display the same banner image as the old institutions dashboard)
- Verify
- Verify
=> api: add `iris` and `assets.banner` to institutions

api_tests/draft_nodes/views/test_draft_node_detail.py, api_tests/draft_registrations/views/test_draft_registration_detail.py, api_tests/draft_registrations/views/test_draft_registration_list.py, api_tests/registrations/views/test_registration_list.py, osf/models/draft_node.py, osf/models/mixins.py, osf/models/node.py, osf/models/registrations.py, osf_tests/test_draft_node.py, osf_tests/test_draft_registration.py, website/settings/defaults.py
Some users are forgetting to update the title of their "no-project-registration", so this PR sets the no-project registration's title to an empty string so it must be updated to validate the form. This PR simply doesn't copy over the default DraftNode title if the DraftRegistration uses a DraftNode instead of a Node.
- Changes `copy_editable_fields` logic to exclude the default title of draftnodes 
- Changes to tests
- refactor `Untitled` to `DEFAULT_DRAFT_NODE_TITLE`
- **Removed unused param auth**
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-4560
=> [ENG-4560] Remove 'Untitled' as the default entry from the Title entry field for the draft registration

addons/boa/tasks.py, addons/boa/views.py, website/static/js/fangorn.js
Current upload URL in the Boa submission view only uploads file to the root folder.
The view needs to provide the parent folder’s upload URL to task.
* Update `fangorn` to submit parent data to Boa submission view in addition to file data
* Update submission view to obtain the upload URL
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4881
=> [ENG-4881] Provide parent folder info to use for the upload URL

addons/base/exceptions.py, addons/base/serializer.py, addons/base/tests/base.py, addons/base/tests/views.py, addons/boa/apps.py, addons/boa/models.py, addons/boa/routes.py, addons/boa/serializer.py, addons/boa/tests/async_mock.py, addons/boa/tests/factories.py, addons/boa/tests/test_models.py, addons/boa/tests/test_serializer.py, addons/boa/tests/test_tasks.py, addons/boa/tests/test_views.py, addons/boa/tests/utils.py, addons/boa/views.py, addons/owncloud/serializer.py, addons/owncloud/tests/test_models.py, addons/owncloud/tests/test_serializer.py, addons/owncloud/tests/test_views.py, addons/owncloud/tests/utils.py, tests/test_rubeus.py, website/util/rubeus.py
* Fix/update unit tests for Boa add-on
* Improve add-on code
Note: refer to diff in https://github.com/cslzchen/osf.io/pull/17 before https://github.com/CenterForOpenScience/osf.io/pull/10474 is merged
* Add-on base
* Added a new exception: `NotApplicableError`
* Fixed signature for `credentials_are_valid()` and its usage
* Boa
* Removed unused routes, views and methods
* Raise ``NonApplicableError()`` in stead of `return None` , `pass` or being commented out
* Added sentry logs
* Fixed a no-effect bug in `boa_submit_job()` where output URL was built with and extra parameter `&name=`
* Updated code style, comments and `docstr`
* Owncloud
* `credentials_are_valid()` returns False earlier if `external_account` is None
* Website
* Fixed an issue in `_collect_addons()` where `active_addons` …
=> [ENG-4897] Unit tests for Boa add-on + improve Boa add-on

addons/boa/tests/test_views.py, addons/boa/views.py
Fix a bug where only add-on owner can actually submit to boa. The expected behavior is any contributor with WRITE or higher permission should be able to.
* Replace view decorator `@must_have_addon(SHORT_NAME, 'user')` with `@must_have_permission(permissions.WRITE)`
* Added unit tests
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-4930
=> [ENG-4930] Fix permission for boa_submit_job view

addons/boa/README.md, addons/boa/apps.py, addons/boa/settings/defaults.py, addons/boa/settings/local-dist.py, addons/boa/static/boaUserConfig.js, framework/addons/data/addons.json, website/project/views/node.py, website/static/js/fangorn.js
Cleanups for Boa's legacy front-end (discovered during QA) + response to some of the CR items in https://github.com/CenterForOpenScience/osf.io/pull/10469
* Update Boa TOS to be Product-compliant
* Stably sort addon category names (and rename "Remote computing" to "remote-computing")
* make legacy submit-to-boa modal look and behave more like ember's. 
* make the README.md about Boa
* remove unused setting vars
N/A
N/A
N/A
N/A
=> [ENG-4642] Cleanups for Boa's legacy front-end

addons/base/models.py, api/addons/serializers.py, api/base/serializers.py, api/nodes/serializers.py, api/users/serializers.py, api/users/views.py, api_tests/users/views/test_user_addons.py
A catch all PR for minor tweaks to addon resources in API to accommodate new POSE based addons and FE/JSON-API best practices.
- remove figshare TODO: https://github.com/CenterForOpenScience/osf.io/blob/a3e0a0b9ddda5dd75fc8248d58f3bcdeece0323e/api/users/serializers.py#L289
- Add `user` relationship to UserAddons
- Add `accounts` relationship to UserAddons
- Add `node`  relationship to NodeAddons
- Fix top-level Addon type to addons from addon
- Add `self` link to top-level addons view
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-4946
=> [ENG-4946] Standardize Addon Serialization

osf/management/commands/fetch_cedar_metadata_templates.py
New template version is set to inactive when fetched
* If a template is fetched for the first time, set status to active
* If a template is fetched as a new version, set status to inactive
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-5038
=> [ENG-5038] New template version is set to inactive when fetched

osf_tests/test_generate_sitemap.py, scripts/generate_sitemap.py
Improve Google indexing of Preprints.
- Avoid redirects on web view paths
- Include file download links for preprint content indexing. The meta tags present on the page satisfy Google Scholar, but not Google Search.
- I've verified sitemap generation locally with this, but other behavior can only be tested as Google indexes production content. Likely dev-test.
N/A
None expected.
[ENG-4919]
[ENG-4919]: https://openscience.atlassian.net/browse/ENG-4919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Hotfix][ENG-4919] Update sitemap for preprint routes, downloads

osf/metadata/serializers/datacite/datacite_tree_walker.py, osf_tests/metadata/expected_metadata_files/file_full.turtle, osf_tests/metadata/expected_metadata_files/preprint_full.turtle, osf_tests/metadata/expected_metadata_files/project_full.datacite.json, osf_tests/metadata/expected_metadata_files/project_full.datacite.xml, osf_tests/metadata/expected_metadata_files/project_full.turtle, osf_tests/metadata/expected_metadata_files/registration_full.turtle, osf_tests/metadata/test_serialized_metadata.py
ensure valid xml for datacite when something has multiple funding references for the same funder
- update tests to cover multiple funding references from the same funder
- fix broken datacite serialization logic
- Verify a project can have multiple funding references with the same funder id
- Verify the datacite-xml metadata for that project (at `/<guid>/metadata?format=datacite-xml`)
1. downloads successfully
2. contains multiple `<fundingReference>` tags (matching what's shown in the ui), each with no more than one `<awardNumber>` and `<awardTitle>`
- Verify that project can have a DOI minted successfully (in environments set up for DOI minting)
Any …
=> [ENG-5044] fix: multiple funding awards from the same funder

api/base/serializers.py, api/cedar_metadata_records/serializers.py, api/cedar_metadata_records/utils.py, api/cedar_metadata_records/views.py, api/files/serializers.py, api/files/urls.py, api/files/views.py, api/nodes/serializers.py, api/nodes/urls.py, api/nodes/views.py, api/registrations/serializers.py, api/registrations/urls.py, api/registrations/views.py
* Finish missing features in https://github.com/CenterForOpenScience/osf.io/pull/10513
N/A
See [API contacts](https://docs.google.com/document/d/1pfcG0Je0ZntMRNnF0hcLzqNody2ZjBlThoRduPiVzQA/edit#heading=h.rh0pxer1zy44) for details
N/A
https://openscience.atlassian.net/browse/ENG-5203
=> [ENG-5203] Add metadata records relationships to nodes, registrations and files

api/cedar_metadata_templates/views.py
Template List Should Only Return Active Ones
See: https://www.notion.so/cos/CedarMetadataTemplateList-view-should-only-return-active-templates-a7cad22d080f47cf924e4d0b1bf3b15a
N/A
N/A
N/A
N/A
=> [Cedar] Bug Fix - Template List Should Only Return Active Ones

api/cedar_metadata_records/serializers.py, api/cedar_metadata_records/urls.py, api/cedar_metadata_records/views.py, osf/models/cedar_metadata.py
Support metadata download for a given record
* Add metadata download endpoint
* Add metadata download link to record serializer
* File name: `<guid>-<schema_name>-v<version_number>.json`
```json
"links": {
"self": "<domain>_/cedar_metadata_records/<record_id>/",
"metadata_download": "<domain>/_/cedar_metadata_records/<record_id>/metadata_download/",
}
```
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-5247
=> [ENG-5247] Support metadata download for a given record

api/files/serializers.py, api/files/urls.py, api/files/views.py
* `FileCedarMetadataRecordList` view now supports both `file_id` and `guid_id`;
* In addition, this PR fixed an unexpected side-effect from https://github.com/CenterForOpenScience/osf.io/pull/10531 where the file serializer fails if the file doesn't have a `guid` yet.
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-5258
=> [ENG-5258] Expand `FileCedarMetadataRecordList` view to support both `file_id` and `guid_id`

Dockerfile, requirements.txt
Update docker image to python 3.10
Updated docker image to alpine 3.17 which includes Python 3.10 and NodeJS 18
Bumped libraries which refused to complie on python 3.10 (because of changes in Python C API)
NodeJS 18 may break some things in the future, but for now everything works
Node JS 18 may break Node related stuff. LIbraries which are bumped may break things
https://openscience.atlassian.net/browse/ENG-5212
=> ENG-5211 updated base image to python 3.10

api/cedar_metadata_records/utils.py, api/cedar_metadata_records/views.py, api/files/views.py, api/nodes/views.py, api/registrations/views.py
* Remove unnecessary permission class for list views
* Apply similar permission check for related record views in nodes, registrations and files
* Node Record List `GET`
* Registration Record List `GET`
* File Record List `GET`
Cherry-picked from https://github.com/CenterForOpenScience/osf.io/pull/10534/commits/71edd4e53e576712bd57556c7208e8ab7920a2c4 in https://github.com/CenterForOpenScience/osf.io/pull/10534
This is a follow-up PR for https://github.com/CenterForOpenScience/osf.io/pull/10536
N/A
N/A
N/A
N/A
=> [Cedar] Bug-fix: More Permission Fix/Improvement

api/base/serializers.py
Fix another occurrence of the private view url reverse bug when it is a relationship of a public view
Related [bug](https://www.notion.so/cos/embedding-the-template-relationship-through-the-node-cedar-record-list-view-failed-with-NoReverseMat-66c46bb6577847cb80ff20b4c08931f4)
A similar [fix](https://github.com/CenterForOpenScience/osf.io/pull/10519/commits/34e6772b8b7c50ee2b4191f6ce58cbc03e68b35e) on a similar issue previously
N/A
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-5204
=> [ENG-5204] Fix another occurrence of the private view url reverse bug

osf/models/provider.py, osf/models/subject.py, osf/models/validators.py, tests/test_subjects.py
Remove the limit of 10 highlighted subjects.
- remove limits of ten elements from the views `highlighted_subjects`.
- remove validators that prevent addional highlighted subjects from being added.
- remove tests that ensure the limit is maintained.
- remove redundant methods that were enforcing the limit.
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5356
=> [ENG-5356] Unlimit the number of highlighted subjects are displayed

osf/metadata/serializers/google_dataset_json_ld.py, osf_tests/metadata/test_google_datasets.py
Add default "No description included" text in description to avoid not reaching number of characters necesarry for Dataset validation
- add default text with comments
- [wip] add tests
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-4658
=> [ENG-4658] Add default "No description included" text in node description

.github/actions/start-build/action.yml, .github/workflows/test-build.yml, osf_tests/test_session.py, osf_tests/test_user.py
Fix tests which pass locally but fail on CI
Closed session in teardown of TestSession TestCase
DRY improvements for CI 
- Verify
- Verify
[ENG-5521](https://openscience.atlassian.net/browse/ENG-5521)
[ENG-5521]: https://openscience.atlassian.net/browse/ENG-5521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENG-5521] Phase 3: Tests pass locally but fail on CI

admin_tests/preprint_providers/test_views.py
> Definition of problem: `<pre>` tag is being replaced to `\n` instead of being wiped. Location:
> `admin_tests/preprint_providers/test_views.py::TestPreprintProviderChangeForm::test_html_fields_are_stripped`
After discussion with @opaduchak, we discovered that "`<pre>` tag is being replaced to `\n`" is an expected behavior since `<pre>` is a block tag. See https://github.com/mozilla/bleach/issues/663.
Our next attempt is to not sanitize `<pre>`, however, this results in unexpected output too. This is caused by `<pre>` inside `<p>` being illegal. See https://github.com/mozilla/bleach/issues/588.
Thus, our solution is to provide a valid HTML for testing the sanitization, rather than tweak `bleach` or our code.
We also verified that the user for this form is our admin (product team or …
=> [ENG-5514] Fix bleach sanitization issues

.github/workflows/test-build.yml, addons/twofactor/models.py, api_tests/base/test_auth.py
Fix OTP test failures which popped up after python and libs upgrade and after migration from oath to pyotp
Fixed http requests raising unwanted excaptions in 
- `test_valid_credential_authenticates_but_user_lacks_object_permissions`
- `test_invalid_credential_fails`
- `test_valid_credential_but_twofactor_required`
- `test_valid_credential_twofactor_invalid_otp`
Fixed OTP drift in in otp validation logic, and added 1 second buffer after OTP expires
In addition, disable CI failure report for pull requests
There will be need to thoroughly test OTP logic, as library was changed to filter out any bugs and security concerns.
Yes, QA has the CAS server on staging servers to test OTP.
[ENG-5587](https://openscience.atlassian.net/browse/ENG-5587)
[ENG-5587]: …
=> [ENG-5587] Phase 3: Fix OTP test failures

addons/base/views.py
Fix some signals code that wasn't covered by tests.
- squish some ORM logic to avoid errors
- Verify
- Verify
=> [ENG-5140] #2 Update get_auth for GV and readability 

addons/base/views.py
`get_auth` was checking for `FileVersions` on all `osfstorage` entities -- including folders. This was breaking access to `osfstorage` on projects. Fix that.
* Rename `get_file_node_from_wb` and `get_file_version_from_wb` to `_get_osfstorage_file_node` and `_get_osfstorage_file_version` and only provide them the information they need from `waterbutler_data`.
* Grab the `OsfStorageFileNode` before grabbing the version
* Calls `load` using the file_id to [match behavior from original get_auth](https://github.com/CenterForOpenScience/osf.io/blob/b2916f756c792bb9eb8f3252e0b6fc56c5b0618c/addons/base/views.py#L315).
* Pass the OsfStorageFileNode to `get_osfstorage_file_version'. Short circuit when trying to retrieve a FileVersion for a non-"file" OsfStorageFileNode
Please make verification …
=> Fix get auth number two

tests/test_views.py
**Fix** test_old_password_invalid_attempts_reset_if_password_successfully_reset;
- **replace** json with data;
- **add** follow_redirects=True as it helped return status code `200` instead of `301`;
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5588
=> [ENG-5588] - Fix test_old_password_invalid_attempts_reset_if_password_successfully_reset

api/base/authentication/drf.py, api_tests/base/test_auth.py
Fix CSRF Middleware usage inside authentication
Added a crutch of `get_response` function to make CSRF checks not fail. This function isn't even being called during this check, so this is literally a crutch 
- Verify
- Verify
Any concerns/considerfc2256ations/questions that development raised?
https://openscience.atlassian.net/browse/ENG-5639
=> [ENG-5639] Phase 4: Fix CSRF Middleware

addons/base/views.py
=> add DraftRegistration file permission test

osf/external/gravy_valet/auth_helpers.py, osf/external/gravy_valet/gv_mocks.py, osf/external/gravy_valet/hmac.py, osf/external/gravy_valet/test_utils.py, osf_tests/test_gv_utils.py
Add
1) a configurable mock for running tests against expected GravyValet output
2) Utilities to generate HMAC signed headers to enable OSF to bypass auth callbacks to itself 
- `osf/external/gravyvalet/auth_helpers` is copied almost directly [from GravyValet](https://github.com/CenterForOpenScience/gravyvalet/blob/develop/addon_service/common/hmac.py) but adds support for sending `X-Requesting-User-URI`, `X-Requested-Resource-URI`, and `X-Requested-Resource-Permissions` headers (and including them in the HMAC signature).
- The only notable changes are using the [official spec for date header formats](https://www.rfc-editor.org/rfc/rfc9110.html#section-5.6.7) and parsing headers from requests in the `requests.Request` format instead of the `rest_framework.Request` format
- notably, no …
=> Configurable GV Mock + HMAC Auth

api/nodes/views.py
Make it so preprints api serialization has a root_folder
1. Modify the view to get the root_folder in the case of preprints
Should only affect preprints
https://openscience.atlassian.net/browse/ENG-5716
=> [ENG-5716] Get root_folder for preprints

osf/metadata/osf_gathering.py, osf_tests/metadata/test_osf_gathering.py, tests/identifiers/test_datacite.py
Ensure that all registrations have a default resource type of "Study Registration"
Updated DATACITE_RESOURCE_TYPE_BY_OSF_TYPE to set the default resource type for registrations to "StudyRegistration".
(https://openscience.atlassian.net/browse/ENG-5135)
=> Set Default Resource Type for Registrations to "Study Registration"

osf_tests/test_archiver.py
Fix archiver test not detecting call to `celery.group`
Instead of checking `celery.group` now checking `archive_addon.delay` in affected tests.
- Verify
- Verify
[ENG-5752](https://openscience.atlassian.net/browse/ENG-5752)
[ENG-5752]: https://openscience.atlassian.net/browse/ENG-5752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENG-5752] Phase 4: Fix archiver test not detecting call to `celery.group`

api/registrations/serializers.py, osf_tests/test_archiver.py, website/archiver/tasks.py, website/archiver/utils.py
Support Unicode in OSF Storage to prevent archiving failures due to special characters in filenames.
- Enhanced filename normalization to handle Unicode characters.
- Updated archiving workflow to ensure proper handling of special characters.
<https://openscience.atlassian.net/browse/ENG-5008>
=> [ENG - 5008] Support Unicode and special characters in file names during archiving

addons/s3/utils.py
S3 addon was broken after boto3 upgrade.
fixed s3 failures when setting up addon (not when browsing files)
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5780
=> [ENG-5780] fixed s3 failures when setting up addon (not when browsing files)

addons/base/views.py, tests/base.py
Restore expected functionality that unauthenticated users should be able to render/download public files.
NOTE:
This PR does not address the code smells of having additional auth checks that duplicate the work done by `@collect_auth`.  https://github.com/CenterForOpenScience/osf.io/pull/10642 proposes an alternative which keeps us from needing to re-confirm token scopes with CAS, but the team lacks time to address all of the test breakages it causes. This PR, meanwhile restores the status quo.
Remove explicit error case when auth.user does not exist.
- Verify
- Verify
=> [ENG-5178] Allow unauthenticated users to see public files

addons/base/views.py
Previous refactor stopped using the `make_auth` function, instead directly constructing the auth dictionary. This was adding another failure point for unauthenticated users.
Restore use of `make_auth` to gracefully handle the unauthenticated user case.
- Verify
- Verify
=> Use `make_auth` to avoid assumptions about `auth.user`

addons/base/views.py, osf/external/gravy_valet/auth_helpers.py, osf/external/gravy_valet/translations.py, osf/models/draft_node.py, osf/models/mixins.py, osf/models/node.py, osf/models/preprint.py, osf/models/user.py, tests/base.py, tests/test_addons.py, tests/test_preprints.py, tests/test_utils.py
Update `get_addon` and `get_addons` to return EphemeralSettings objects populated from GravyValet data when the GV waffle is active. Also, remove special casing for GravyValet from `get_auth` now that `get_addon` handles this transparently.
Also, further refactor `get_auth` to remove unnecessary checks, revert some deltas from the pre-refactored version, and improve consistency
**Changes to `get_addon(s)` and GV-facing libraries**
* update `AddonModelMixin.get_addon(s)` to conditionally check with GravyValet as the source of truth for configurations
* Maintain `osfstorage` `twofactor` `wiki` and `forward` as `OSF_HOSTED_ADDONS` that will follow legacy routes
* Add `_get_addon(s)_from_gv` to `AbstractNode` and `OSFUser` to handle retrieving the appropriate data and `EphemeralSettings`
* …
=> [ENG-5727][ENG-5728] Get Addon information from GravyValet

addons/base/views.py, api/files/permissions.py, api/files/serializers.py, api/files/views.py, api_tests/files/views/test_file_detail.py
Implement custom permissions to handle file access for withdrawn registrations.
- Added WithdrawnRegistrationPermission and updated FileDetailPermission to enforce access control for withdrawn registrations.
- Restrict API response
<(https://openscience.atlassian.net/browse/ENG-3685)>
=> [ENG-3685] Add permissions for withdrawn registration files

addons/base/views.py, api/files/serializers.py, api/files/views.py, api_tests/files/views/test_file_detail.py
Reverts CenterForOpenScience/osf.io#10650
Revert this for the time being to avoid having it go out with the upcoming python-upgrade release.
=> Revert "[ENG-3685] Add permissions for withdrawn registration files"

addons/base/views.py, api/institutions/authentication.py, api/waffle/utils.py, osf/external/messages/celery_publishers.py, osf/models/metaschema.py, osf/models/mixins.py, tests/test_ember_osf_web.py, website/ember_osf_web/decorators.py, website/oauth/views.py, website/project/views/file.py, website/views.py
correct checking of waffle-flags on flask requests
- use `api.waffle.utils.flag_is_active`, not `waffle.flag_is_active`
- update `api.waffle.utils.flag_is_active` to work for either flask or django request
- Verify
- Verify
=> fix: waffle flags in flask context

api/users/serializers.py, api/users/views.py, api_tests/institutions/views/test_institution_auth.py, api_tests/users/views/test_user_settings.py, framework/auth/views.py, tests/test_views.py, website/profile/views.py
Move email confirmation to a post-commit task.
- Moved send_confirm_email call to a post-commit task in UserEmailsSerializer.
- Defined send_confirm_email_async to handle email sending after database transactions are committed.
The send_confirm_email function has been refactored to send_confirm_email_async across various parts of the codebase. 
- API User Email Creation (api/users/serializers.py):
Scenario: Adding a new email address to a user profile.
- API User Email Resend Confirmation (api/users/views.py):
Scenario: Resending confirmation email.
- User Registration (framework/auth/views.py):
Scenario: New user registration.
- Resend Confirmation Email (framework/auth/views.py):
Scenario: Resending a confirmation email.
- External Login Email Handling (framework/auth/views.py): …
=> [ENG-4903] Fixes issue with email confirmation links failing due to database congestion

addons/base/views.py, api/files/serializers.py, api/files/views.py, api_tests/files/views/test_file_detail.py
This reverts commit 34d56414859066b98c0998fbc00cd130bf5de4fd.
Changes for ENG-3685 were reverted to avoid any complications with the Python Upgrade release. Re-add those changes to the b&i feature branch.
See #10650 
- Verify
- Verify
=> Re-add permissions changes for files on withdrawn registrations

osf/models/node.py
Fix the citation generation to use the registered_date instead of the last log date.
Updated the csl property to set the issued value to registered_date in the citation format.
<(https://openscience.atlassian.net/browse/ENG-4527)>
=> [ENG-4527] Fix citation to use registered date

admin/preprints/forms.py, admin/preprints/urls.py, admin/preprints/views.py, admin/templates/preprints/machine_state.html, admin/templates/preprints/preprint.html, admin/templates/preprints/provider.html, admin_tests/preprints/test_views.py
Allows admins to adjust preprint machine state
- Splits `PreprintView` into a GET only view and makes Form view `PreprintProviderChangeView`
- add `PreprintMachineStateView`
- adds tests
- remove ald machine_state label
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5848
=> [ENG-5848] Add button to admin to move preprint from initial to pending

poetry.lock, pyproject.toml
Fix broken dataverse code by updating our deps to point to the fixes we wrote. Glerp.
* There were a bunch of changes made to the dataverse python module to get it working with the upgraded OSF. Then we ignored them. Avenge this injustice!
* Rerunning `poetry lock` pulled in a new major version of indirect dep `django-datetime-field`. Pin the old version, b/c that seems like it could be break-y.
* Update OSF version declare in pyproject.toml
* Regenerate lockfile. Please setuptools, don't hurt 'em!
- Verify
- Verify
=> [CR] update dataverse dep revision to get changes

Dockerfile, addons/dataverse/requirements.txt, addons/mendeley/requirements.txt, api/ia/views.py, docker-compose-dist-arm64.override.yml, docker-compose-dist.override.yml, docker-compose.yml, osf/metrics/reports.py, poetry.lock, pyproject.toml, requirements.txt
Fix brokes and nits in:
* admin metrics reports
* IA archiving failures
* Dockerfile cleanups
* docker-compose cleanups
* pinning pyproject.toml github deps to commit shas rather than branches
* others to come?
* use the correct `elasticsearch_dsl` module in our metric reports
* stop using protected method for IA archiving
* update pyproject.toml deps to point to commit shas (add comment with name of branch for reference)
* fix a few nitpicks from recent Docker
* remove deprecated `version` stanza from Dockerfiles
* verify on admin app that metrics are correct
* verify that new registrations are being archived
nope, nope, nope
None expected.
* ✅ ENG-6019: https://openscience.atlassian.net/browse/ENG-6019
* ✅ ENG-6021: https://openscience.atlassian.net/browse/ENG-6021
* ~~🔲  ENG-6022: …
=> [CR][ENG-6019][ENG-6021][ENG-6023] hotfixes for recent python-upgrade release

docker-compose.yml
Fix devenv setup for people who use virtualenv inside project root in conjuction with docker-compose
Changed mount for `docker-compose` `requirements` service 
- Verify
- Verify
[ENG-6094](https://openscience.atlassian.net/browse/ENG-6094)
[ENG-6094]: https://openscience.atlassian.net/browse/ENG-6094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENG-6094] Poetry won't install deps properly in when venv is inside project root

osf_tests/metadata/test_osf_gathering.py
Confirm preprint affiliation data is sent to SHARE.
- modifies test of affiliation gathering.
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-5908
=> [ENG-5908] Add Test Confirming Preprint Affiliated Iinstitution Data is Sent to SHARE

api/institutions/authentication.py, api/providers/serializers.py, api_tests/institutions/views/test_institution_auth.py, framework/auth/__init__.py, osf/models/mixins.py, osf/models/osf_group.py, osf/models/user.py, osf_tests/test_user.py, website/project/views/contributor.py, website/util/metrics.py
Adds source tags to users created via email invitation or sso.
- adds line to SSO user creation method adding system tag
- adds line to unregistered_user method to add system tag
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-2562
=> [ENG-2562] Fix Source Tags for Users

osf/utils/notifications.py, osf_tests/test_reviewable.py, website/mails/mails.py, website/reviews/listeners.py, website/templates/emails/reviews_resubmission_confirmation.html.mako
Ensure emails are sent to users and moderators when preprints are resubmitted. 
- resubmission sents message to `reviews_email` to `reviews_email_submit` 
- add test to check for email template
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-5995
=> [ENG-5995] Make resubmission emails more like submissions emails

osf/metrics/reports.py, osf/metrics/utils.py, osf_tests/metrics/test_monthly_report.py
allow monthly reports for each institution or each institutional user account
replace `DailyReport.DAILY_UNIQUE_FIELDS` with `UNIQUE_TOGETHER_FIELDS` on both `DailyReport` and `MonthlyReport`
- Verify
- Verify
=> [ENG-6164] allow monthly metrics reports on multiple subjects

api/users/views.py, api_tests/users/views/test_user_draft_preprint.py
The preprint draft list includes deleted preprints, that's a litttle strange, lets fix that.
- uses view query for filter out preprints that have been deleted
- adds test cases
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6012
=> [ENG-6012] Filter out deleted preprints for preprint drafts lists

README-docker-compose.md, api/base/settings/defaults.py, conftest.py, docker-compose-dist-arm64.override.yml, docker-compose.yml, website/settings/defaults.py
Get MC's working es6 image to work with our test app.
- set up connection with es to use docker host number
- use ES6_URI envars correctly
- add ARM compatible Docker image
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6197
=> [ENG-6197] ES6 WILL run on an ARM processor 

osf/management/commands/monthly_reporters_go.py, osf/metrics/reporters/_base.py, osf/metrics/reporters/institutional_users.py, osf/metrics/reporters/spam_count.py, osf/metrics/reports.py
fix bugs found running monthly institutional-user report on actual data
- Verify
- Verify
=> [ENG-6165] bugfixing followup

api/base/elasticsearch_dsl_views.py, api/base/serializers.py, api/base/utils.py, api/institutions/serializers.py, api/institutions/urls.py, api/institutions/views.py, api_tests/base/test_views.py, api_tests/institutions/views/test_institution_department_list.py, api_tests/institutions/views/test_institution_summary_metrics.py, api_tests/institutions/views/test_institution_user_metric_list.py, api_tests/metrics/test_composite_query.py, api_tests/metrics/test_preprint_metrics.py, api_tests/metrics/test_raw_metrics.py, api_tests/metrics/test_registries_moderation_metrics.py, conftest.py, osf/features.yaml, osf/metrics/reports.py, osf/metrics/utils.py, osf_tests/management_commands/test_reindex_es6.py, osf_tests/test_management_commands.py
update api to serve institutional-user metrics based on the monthly report added in #10722 
reusable things added:
- `toggle_view_by_flag` util to ease feature-flagged views
- also allow non-class views to exist (minor updates to api tests and bases)
- base view `ElasticsearchListView`
- use `elasticsearch_dsl.Search` as queryset-analogue, for code reuse
- allows filtering (with 'eq' and 'ne' operators) following `filterable_fields` on the serializer (using `api.base.filters.FilterMixin`)
- allows sorting, following `default_ordering` and `ordering_fields` on the view
- allows pagination (with `page` and `page[size]` params), using default paginator
- `api.base.serializers.YearmonthField`
- `MonthlyReport.most_recent_yearmonth` classmethod
specific to this project:
- add feature flag …
=> [ENG-6119] api changes for institution-users updates

api/base/settings/defaults.py, osf/admin.py
allow editing a waffle flag in the admin interface (`admin.osf.example/admin/waffle/flag/<id>/change/`) -- currently, it tries to display a list of all django `Group`s, and (especially on production) there are tooo many
- set `WAFFLE_ENABLE_ADMIN_PAGES=False`
- register waffle admins explicitly
- customized `FlagAdmin` to work with many groups
- `SwitchAdmin` and `SampleAdmin` left as-is
- Verify
- Verify
=> fix: usable waffle-flag admin

api/institutions/serializers.py, api/institutions/urls.py, api/institutions/views.py, api_tests/institutions/views/test_institution_summary_metrics.py, osf/metrics/reports.py
This will hook up the ES back-end to our JSON API allowing fields to be sorted and filtered.
- adds `NewInstitutionSummaryMetricsSerializer`
- adds `_NewInstitutionSummaryMetricsList`
- adds `InstitutionMonthlySummaryReport`
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6125
=> [ENG-6125] Implement Required Changes to Institution-Metric Summary API

osf/metrics/reporters/__init__.py, osf/metrics/reporters/institution_summary_monthly.py, osf/metrics/reports.py, osf_tests/factories.py, osf_tests/metrics/reporters/test_institutional_summary_reporter.py
Adds monthly reporter for institution summary.
- add `InstitutionalSummaryMonthlyReporter` object with institutions KPIs
- adds `InstitutionMonthlySummaryReport` to reports file
- adds tests
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6124
=> [ENG-6124] Create Monthly Reporter for Institution Summary

osf/external/gravy_valet/translations.py
After recent changes to addons, making node private/public no longer works because on `EphemeralNodeSetting` there is not a `after_set_privacy` hook to call. Upon closer inspection, it seems that the `after_set_privacy` hooks for addons were all noops. Hence, this PR adds an `after_set_privacy` noop to `EphermeralNodeSetting`.
- Verify
- Verify
=> [ENG-6321] Add after_set_privacy noop

api/institutions/serializers.py, api/institutions/views.py, osf/metrics/reporters/institutional_users.py, osf/metrics/reports.py, osf_tests/metrics/reporters/test_institutional_users_reporter.py
Add Monthly Activity state for users report in institutional dashboard.
- add query to reporter for most recent user log
- add case to test
- add to filtering on view
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6366
=> [ENG-6366] Add Monthly Activity Stat to Dashboard Reporter

api/caching/tasks.py, osf/metadata/osf_gathering.py, osf/metadata/rdfutils.py, osf_tests/metadata/_utils.py, osf_tests/metadata/expected_metadata_files/file_basic.turtle, osf_tests/metadata/expected_metadata_files/file_full.turtle, osf_tests/metadata/expected_metadata_files/preprint_basic.turtle, osf_tests/metadata/expected_metadata_files/preprint_full.turtle, osf_tests/metadata/expected_metadata_files/preprint_supplement.turtle, osf_tests/metadata/expected_metadata_files/project_basic.turtle, osf_tests/metadata/expected_metadata_files/project_full.turtle, osf_tests/metadata/expected_metadata_files/project_supplement.turtle, osf_tests/metadata/expected_metadata_files/registration_basic.turtle, osf_tests/metadata/expected_metadata_files/registration_full.turtle, osf_tests/metadata/expected_metadata_files/registration_supplement.turtle, osf_tests/metadata/test_osf_gathering.py, osf_tests/metadata/test_serialized_metadata.py
add searchable metadata that will be used by the new™️ institutional dashboard
(recommend reading commit-by-commit)
- update metadata test helpers for more helpful feedback when adding metadata properties
- add `osf:hasOsfAddon` property (supplemental)
- identify addons with `urn:osf.example:addons:...`
- add `osf:storageRegion` property (supplemental)
- identify regions with `https://api.osf.example/v2/regions/.../`
- add `prov:qualifiedAttribution` (non-supplemental)
- qualifies contributorship with a role: `osf:admin-contributor`, `osf:write-contributor`, or `osf:readonly-contributor` (and could add more nuanced/helpful contributor roles in the future)
- add `osf:storageByteCount` property (supplemental)
- small refactor of `update_storage_usage_cache`:
- add …
=> [ENG-6185][ENG-6186][ENG-6187][ENG-6188] additional searchable metadata for institutional dashboard

osf/external/gravy_valet/translations.py
=> added s3 crutch to unblock qa for time being

osf/external/gravy_valet/translations.py, osf_tests/external/gravy_valet/gv_fakes.py, osf_tests/test_gv_utils.py
=> Implemented fetching settings from GV side

osf/external/gravy_valet/translations.py
Google drive had an underscore in the short name (`google_drive`) in the translations file, but in waterbutler it is just `googledrive`. So this fixes it to match waterbutler. Also adds onedrive.
1. Rename google_drive.
2. Add onedrive
=> Fix google drive short name in translations

osf/external/askismet/client.py, osf/external/oopspam/client.py, osf/metrics/reporters/__init__.py, osf/metrics/reporters/private_spam_metrics.py, osf/metrics/reporters/spam_count.py, osf/metrics/reports.py, osf_tests/external/akismet/test_akismet.py, osf_tests/external/oopspam/test_oopspam.py, osf_tests/metrics/test_spam_count_reporter.py
Add OOPSpam and Akismet metrics to track flagged and hammed content
- SpamCountReporter: Added OOPSpam and Akismet spam/ham metrics for nodes, registrations, preprints, and users.
- SpamSummaryReport: Added new fields for OOPSpam and Akismet flagged/hammed counts.
- OOPSpamClient & AkismetClient: Added methods to get flagged and hammed content counts.
(https://openscience.atlassian.net/browse/ENG-4438)
Deployment Note: Because the metric report has changed, it will be necessary to run sync_metrics to apply these changes to the updated spam metrics report.
=> [ENG-4438] Add OOPSpam and Akismet metrics to spam report

osf/management/commands/recatalog_metadata.py, osf_tests/management_commands/test_recatalog_metadata.py
speedier `manage.py recatalog_metadata` by skipping private/deleted
- update `recatalog_metadata` to skip private/deleted items by default
- add `--also-decatalog` to include private/deleted items
- update tests...
- remove `--datacite-custom-types` (comment describes it as a "temporary arg for datacite 4.5 migration" and updating tests for it became annoying)
- Verify
- Verify
=> [ENG-6571][hotfix] recatalog_metadata --also-decatalog

osf/metrics/reports.py, osf/metrics/utils.py, osf_tests/metrics/test_daily_report.py, osf_tests/metrics/test_monthly_report.py, osf_tests/metrics/test_yearmonth.txt
prevent duplicate reports when monthly/daily reports are run for past years
set `timestamp` based on `report_date`/`report_yearmonth`, so it's indexed by reporting period rather than when the reporter is run
- Verify
- Verify
=> [ENG-6435] fix: duplicate reports when run for past years

osf/models/preprint.py, website/identifiers/clients/crossref.py
Updated `build_posted_content` to include DOI version relationship
Updated method `build_posted_content` to include information about DOI version for preprint
Note: product needs to verify this on staging server with CrossRef
How posted content looks like with includint information about DOI version for preprint
* Only 1 version
```
| <posted_content xmlns="http://www.crossref.org/schema/5.3.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="preprint">
api-1  |   <group_title>Open Science Framework</group_title>
api-1  |   <contributors>
api-1  |     <person_name sequence="first" contributor_role="author">
api-1  |       <surname>Bohdan</surname>
api-1  |     </person_name>
api-1  |   </contributors>
api-1  |   <titles>
api-1  |     <title>test</title>
api-1  |   </titles> …
```
=> [ENG-6476] Updated `build_posted_content` to include DOI version relationship

osf/metrics/reporters/institutional_users.py, website/settings/defaults.py
Optimize InstitutionalUsersReporter. 
Currently, each individual task may take up to 5 minutes to complete, which clogs the queues. 
This is due to Postgres' query planner using a sequence scan when evaluating the query in `_public_osfstorage_file_queryset`, specifically the `OR` for `(_target_node_q | _target_preprint_q)`.
```
->  Parallel Seq Scan on osf_basefilenode  (cost=371.82..2546660.14 rows=2926198 width=0) (actual time=560.901..21218.302 rows=248 loops=3)
Filter: ((deleted IS NULL) AND (purged IS NULL) AND (created < '2024-12-01 00:00:00+00'::timestamp with time zone) AND ((type)::text = 'osf.osfstoragefile'::text) AND ((provider)::text = 'osfstorage'::text) AND (((target_content_type_id = %s) AND (hashed SubPlan 1)) OR ((target_content_type_id = %s) AND (hashed SubPlan 2)))) …
```
=> [Hotfix][No Ticket] Optimize InstitutionalUsersReporter

osf/management/commands/migrate_preprint_affiliation.py, osf/metrics/reporters/private_spam_metrics.py, osf_tests/management_commands/test_migrate_preprint_affiliations.py, osf_tests/metrics/test_spam_count_reporter.py
- Product has opted to only backfill affiliations on preprints created before the initial release of the Preprints Affiliation project.
- Fix an issue preventing the metric reports' execution
- Circuit-break the backfill for preprints created past a threshold
- Fix `.report` behavior
- Update tests
None expected 
None
=> [Hotfix] Fix Preprint Affiliation backfill, PrivateSpamMetricsReport

website/notifications/emails.py
Ensure deliverability of reviews notifications
- If no preferences are configured, assume `email_transactional` for `global_` notifications.
- This behavior is congruent with expectations detailed in [this comment](https://github.com/CenterForOpenScience/osf.io/blob/d68a07b26d3d79ced42113e8c4b16984f7a9a86c/website/notifications/constants.py#L6-L8)
- Review actions (accept/reject) should generate notification emails in the absence of configured `NotificationSubscriptions`
None expected
https://openscience.atlassian.net/browse/ENG-6675
=> [Hotfix][ENG-6675] Assume default  for `global_` notifications

website/views.py
Check and fix `website` tests
* Update check for redirect in `resolve_guid` view
* Combine overlapping code
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6700
=> [ENG-6700] Check and fix `website` tests

addons/base/tests/views.py, osf/external/gravy_valet/translations.py, website/oauth/views.py
=> [ENG-6731] Fix zotero connection

osf_tests/test_generate_sitemap.py
Updated sitemap generator unit tests
TBD
TBD
TBD
TBD
https://openscience.atlassian.net/browse/ENG-6648
=> [ENG-6648] Updated tests for sitemap generator

framework/email/tasks.py
🐛 
https://staging-sentry2.cos.io/organizations/cos/issues/1780/?query=is%3Aunresolved&referrer=issue-stream&stream_index=0
Unfortunately because of some of the loose mocking and not wanting to get a sendgrid API key our sendgrid code to allow BCC and reply emails did not work, this PR aims to fix it.
- uses up to date methods for Bcc and replyto for sendgrid
**I did finally get a sendgrid API key as a free trial so I validated the client worked, but no actual email could be sent with SMTP server. However it should work in production.**
=> [Bug} Fix sendgrid email for Institutional Access

api_tests/collections/test_views.py, api_tests/wb/views/test_wb_hooks.py, osf/management/commands/check_crossref_dois.py, osf_tests/factories.py, osf_tests/management_commands/fixtures/crossref_works_response.json, osf_tests/management_commands/test_check_crossref_dois.py, tests/identifiers/test_crossref.py
Check and fix `api3_and_osf` tests, excluding ElasticSearch and SHARE related failures
Check and fix `api3_and_osf` tests, excluding ElasticSearch and SHARE related failures
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6673
=> [ENG-6673] Check and fix `api3_and_osf` tests, excluding ElasticSearch and SHARE related failures

osf/external/gravy_valet/request_helpers.py, osf/external/gravy_valet/translations.py, osf_tests/external/gravy_valet/gv_fakes.py
=> [ENG-6539] Fixed archiving gv addons

addons/boa/views.py, osf/external/gravy_valet/translations.py, osf_tests/external/gravy_valet/gv_fakes.py
Update the boa addon to pull credentials and setting from gravyvalet if the GV waffle flag is set.
Also update `gv_fakes` for remote-computing support (though this is not yet tested)
I will be QAing this
None expected
None expected
https://openscience.atlassian.net/browse/ENG-6650
=> [ENG-6650] gravyboa: update boa addon to pull creds from gravyvalet if flag is set

osf/external/gravy_valet/request_helpers.py, osf/external/gravy_valet/translations.py, osf_tests/test_gv_utils.py
Enable submission of jobs to boa by correctly pulling creds from GV.
* Include computing addons in the addons list from gravyvalet.
* Support other addon types when fetching wb credentials.
Should enable remainder testing of gravyboa.
Nope.
None expected.
[ENG-6825](https://openscience.atlassian.net/browse/ENG-6825)
[ENG-6825]: https://openscience.atlassian.net/browse/ENG-6825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENG-6825] make gv helpers less storage-centric

osf/management/commands/email_all_users.py, osf_tests/management_commands/test_email_all_users.py, website/templates/emails/tou_notif.html.mako
Prepare to send users email about upcoming Policy changes
None expected.
https://openscience.atlassian.net/browse/ENG-6713
=> [ENG-6713][Hotfix] Policy Notification Updates

api_tests/actions/views/test_action_list.py, osf/models/base.py, osf_tests/factories.py, osf_tests/management_commands/test_check_crossref_dois.py, osf_tests/metadata/expected_metadata_files/preprint_basic.datacite.json, osf_tests/metadata/expected_metadata_files/preprint_basic.datacite.xml, osf_tests/metadata/expected_metadata_files/preprint_basic.turtle, osf_tests/metadata/expected_metadata_files/preprint_full.datacite.json, osf_tests/metadata/expected_metadata_files/preprint_full.datacite.xml, osf_tests/metadata/expected_metadata_files/preprint_full.turtle, osf_tests/metadata/expected_metadata_files/project_basic.datacite.json, osf_tests/metadata/expected_metadata_files/project_basic.datacite.xml, osf_tests/metadata/expected_metadata_files/project_basic.turtle, osf_tests/metadata/expected_metadata_files/project_full.datacite.json, osf_tests/metadata/expected_metadata_files/project_full.datacite.xml, osf_tests/metadata/expected_metadata_files/project_full.turtle, osf_tests/metadata/test_osf_gathering.py, osf_tests/metadata/test_serialized_metadata.py, osf_tests/metrics/reporters/test_public_item_usage_reporter.py, osf_tests/test_guid.py
Fix the rest of the failures in `api3_and_osf`. Most of them are caused by fixtures assigning fixed guid id.
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6721
=> [ENG-6721] Fixed `api3_and_osf` tests - Part 2

website/oauth/views.py, website/templates/project/project.mako, website/templates/util/oauth_complete.mako
=> [ENG-6849][ENG-6865] Update project overview files widget; auto close window upon oauth completion

api/preprints/views.py, osf/models/preprint.py
Update old version mix-in check to allow 'rejected'
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6850
=> [ENG-6850] Update old version mix-in check to allow 'rejected'

admin/nodes/urls.py, admin/nodes/views.py, admin/templates/nodes/node.html
Allow Product Support to call `update_moderation_state` manually when state transitions don't happen as they should.
- Add view, form to `update_moderation_state`
None expected. `update_moderation_state` is a no-op when the state is correct.
[ENG-6292](https://openscience.atlassian.net/browse/ENG-6292)
[ENG-6292]: https://openscience.atlassian.net/browse/ENG-6292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Hotfix] Add Admin button to update moderation state

osf/external/gravy_valet/request_helpers.py
added handling of all requests-related errors related to gv
- Verify
- Verify
=> [ENG-6896] Project overview not loading if GV is down

osf/management/commands/migrate_non_versioned_preprints.py
Fix and re-run version migration on staging2
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6856
=> [ENG-6856] Fix migration command to include last preprint

tests/identifiers/test_crossref.py, website/identifiers/clients/crossref.py
Fixed CrossRef metadata update failure when updating metadata about new preprint versions
Fixed CrossRef metadata update failure when updating metadata about new preprint versions
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6836
=> [ENG-6836] Fixed CrossRef metadata update failure

tests/identifiers/test_crossref.py, website/identifiers/clients/crossref.py
Get CrossRef metadata for preprints working
Removed `<doi>` and `<description>` from `<related_item>`
TBD
TBD
TBD
(https://openscience.atlassian.net/browse/ENG-6989)
=> [ENG-6989] Get CrossRef metadata for preprints working

api_tests/preprints/views/test_preprint_versions.py, osf_tests/factories.py
We have good coverage for `POST`; this PR adds new tests for `GET`
Add new tests in `TestPreprintVersionsListRetrieve`
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-6928
=> [ENG-6928] Add new tests in `TestPreprintVersionsListRetrieve`

osf/utils/machines.py, osf_tests/test_institutional_admin_contributors.py
This will make sure curator is added with listed permisssions. While permissions are currenlt displayed correct this PR will better pass them from the access request object to the node better, in a way that follows the business logic where `requested_permissions` defines the given permission when the request is accepted.
- change add_contributor logic
- add tests
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6995
=> [ICA][ENG-6995] Add Curator with Correct Permissions

api/requests/serializers.py, api_tests/requests/views/test_node_request_institutional_access.py
Allows a institutional access user to resubmit node requests. Before curator would get rejected accidently and be banned outside the node without way of making new request, This feature allows admin to update and re-new their request an infinite number of times.
- add resubmit behavior and testing
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6998
=> [IAC][ENG-6998] Infinite Resubmits For IAC

admin/preprints/urls.py, admin/preprints/views.py, admin/templates/preprints/preprint.html, admin/templates/preprints/resync_crossref.html
User should be able to run resync with CrossRef in admin app for preprints that have DOI
Added a separate endpoint and template to process this request
1. I have implemented this functionality using the approach Matthew mentioned in this ticket, however I'm worried about this requirement: This is not creating a new DOI version. From what I see calling request_identifier_update just uploads a new version of file for a specific preprint without DOI changes.
2. In order to test it I need CROSSREF_URL to set it in settings. Do we have a test account? But in general I used the existing functionality for update, so it should work correctly.
https://openscience.atlassian.net/jira/software/c/projects/ENG/boards/145?assignee=712020%3A7c7368dc-40cb-475f-bae8-b07a8bd2dd6c&selectedIssue=ENG-6417
=> [ENG-6417] Added resync crossref button on preprint page in admin app

tests/identifiers/test_crossref.py, website/identifiers/clients/crossref.py
CrossRef fails silently when a status of preprint is not public. In this case we should pass a specific string instead of an empty string
1. Matt's comment: "The XML file that we send has an empty <title>, which causes CrossRef to (silently) not accept it. If preprint spam_status is.SPAM, title should be REMOVED DUE TO POLICY VIOLATIONS, otherwise WITHDRAWN."
2. Import is not moved at the top of the file because of circular imports
https://openscience.atlassian.net/browse/ENG-6314
=> [ENG-6314] Set private title instead of an empty string when sync with CrossRef

website/archiver/tasks.py
During execution of the `stat_addon` task, which is the precursor of actually archiving addons, `get_addon` is called to get the correct addon. However because now `get_addon` makes requests to GV for addon info, we must pass GV authentication by putting `user` on the `DummyRequest` context.
- Verify
- Verify
=> Put `user` on the request context to fix `stat_addon` task errors

api/preprints/serializers.py
=> [ENG-6655] Peer-review DOI will not save on created or edited preprint

osf/models/node.py, website/archiver/tasks.py
It seems like the aggressive caching we do may have a negative side-effect for registration archiving tasks. My suspicion is that the app context and/or the `DummyRequest` context is not clear sufficiently, if at all, in between tasks, resulting in `node.get_addon` failures in the context of a celery task.
Hence, instead of running through the long pipeline of `node.get_addon()`, we fetch directly from GV the configured storage addon using pk in `<guid>:<addon_name>` format. Of course, [a PR to GV](https://github.com/CenterForOpenScience/gravyvalet/pull/237) is also opened to support this new form of querying for configured addons.
- Verify
- Verify
Any …
=> [ENG-7171] Fix registrations by fetching addons from GV directly

api/preprints/serializers.py, api_tests/preprints/views/test_preprint_detail.py
Remove preprint versions from links in serializer
Remove preprint versions from links in serializer
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-7262
=> [ENG-7262] Remove preprint versions from links in serializer

admin/nodes/urls.py, admin/nodes/views.py, admin/templates/nodes/node.html, admin/templates/nodes/resync_datacite.html
User should be able to run resync with DataCite in admin app for registrations that have DOI
Added a separate endpoint and template to process this request
https://openscience.atlassian.net/jira/software/c/projects/ENG/boards/145?search=resync&selectedIssue=ENG-6418
=> [ENG-6418] Added a resync with DataCite button on registration page 

api/nodes/views.py, api/preprints/views.py, tests/test_preprints.py
preventing the Creator of the preprint, while it’s a draft from changing their permissions or removing themselves as a contributor. 
updating back end patch and delete views with restriction conditions
Front end behaviour does not look the same in two different contributor update requests while creating a preprint. 
On the first one it was created a request to back end side and the answer to front end was returned (it is needed to investigate why it is not returned the error message that is on backend side). 
On second attempt a request for backend is not done (may see it on chrome dev tools on the video below).
it was tested on branch feature/b-and-i-25-01 (EMBER / OSF)
https://github.com/user-attachments/assets/022479a6-93fe-4b68-b895-8e488de9c79d …
=> ENG-5864 BE disable creator self removal and permission change before preprint is not submitted

api_tests/registries_moderation/test_submissions.py, osf/models/node.py
After creation of a registration of a spammed and hammed project and rejecting it as a moderator, we cannot ham project's creator
When we clone logs to a registration, spam logs have `was_public = True` in `params` that is inaccurate as registration is private until all approvals and embargo. When it's True we run Node.SpamOverrideMixin.confirm_ham.undelete.set_privacy sequence of methods when ham a user that causes an error after rejecting the registration in moderation.
https://openscience.atlassian.net/browse/ENG-5668
=> [ENG-5668] fixed ham functionality

admin/base/urls.py, admin/files/urls.py, admin/files/views.py, admin/templates/base.html, admin/templates/files/file.html, admin/templates/files/search.html
As with nodes, preprints, and users, a lookup is available for files.  The admin detail page includes all available metadata including contributors from the node, the node title and link, version information, and file name.
Adding in osf admin dashboard a page for searching files by guid and for showing the response
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6987
=> ENG-6987 enable file by guid searching via osf admin

admin/nodes/views.py, admin_tests/nodes/test_views.py, admin_tests/preprints/test_views.py, admin_tests/registrations/test_registrations.py, admin_tests/utilities.py, osf/models/mixins.py
When a user is is designated as Spam, and then confirmed as Ham, sometimes their preprints remain set to private.
It is needed to update to public true on ham just the objects that were public before were spammed.
It is needed to was_public parameter from the latest spammed log that was after public/private changings 
preprint
https://github.com/user-attachments/assets/2af3060b-ddbc-4fd6-aa58-c6462242673a
registration
https://github.com/user-attachments/assets/aae4f010-c782-48f0-84e2-f5bb25740c7e
node (branched embargoed registration from project)
https://github.com/user-attachments/assets/2cc51f71-7177-41a6-a27b-2997f5c5fe97
- Verify
- Verify
Any …
=> [ENG-4255] update to public true on ham just the objects that were public before were spammed

website/settings/defaults.py, website/static/js/components/tracker.js, website/static/js/pages/project-dashboard-page.js, website/templates/base.mako
Log views on projects with DOIs to datacite. This PR covers legacy pages only.
For the overview page, if the project has a DOI, log a view count metrics to Datacite.
* Tested on staging2
* Pages with DOIs should log a view metric payload to datacite
* Pages without DOIs should not log view metric.
Nope!
None expected!
https://openscience.atlassian.net/browse/ENG-5004
https://openscience.atlassian.net/browse/ENG-6969
=> [ENG-5004][ENG-6969] Add pageload logging for datacite (#10940)

admin/preprints/views.py, admin_tests/preprints/test_views.py
Enable to Withdraw Preprint Again After the preprint has been unwithdrawn
TBD
TBD
TBD
TBD
(https://openscience.atlassian.net/browse/ENG-7305)
=> [ENG-7305] Enable to Withdraw Preprint Again After the preprint has been unwithdrawn

.github/actions/start-build/action.yml, .github/workflows/test-build.yml, addons/base/tests/models.py, osf/models/user.py, tests/test_utils.py
The feature flipping passed the user holding the current request instead of the model user, to ensure the model user is used I removed the bug passing that user in the request context as the user requesting to GV.
- remove old code merging accounts
- upgrade ci to work with GHA
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7313
=> [ENG-7313] Fix Merging Accounts

api/base/views.py, api_tests/nodes/views/test_node_contributors_list.py
Update Contributor filter to filter on permissions
Added filter operator 'exact' for node contributor filtering
Added tests for exact permission filtering in contributor list
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-7291
=> [ENG-7291] Update Contributor filter to filter on permissions

api/nodes/serializers.py, api_tests/nodes/views/test_node_contributors_detail.py
Add is_curator attribute to v2/nodes/<node_id>/conributors/ to the GET endpoint
Added is_curator attribute to v2/nodes/<node_id>/conributors/ to the GET endpoint
Added unit test for is_curator attribute
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-7294
=> [ENG-7294] Add Curator indicator to V2

api/base/views.py, api/nodes/urls.py, api/nodes/views.py, api_tests/nodes/views/test_node_children_list.py, api_tests/nodes/views/test_node_reorder_components.py
Upgrade Node Component Reordering to V2.
Added API endpoint to reorder components
Updated node children endpoint for correct component ordering
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-7300
=> [ENG-7300] Upgrade Node Component Reordering to V2.

tests/test_preprints.py, website/routes.py
A preprint link with an unversioned GUID that is followed by “/” will construct an improper URL and fail to resolve.  For example, “https://osf.io/preprints/socarxiv/3rhyz/” resolves to “https://osf.io/preprints/socarxiv/3rhyz/3rhyz_v1” and is not an OSF page.
A link like “[https://osf.io/preprints/socarxiv/3rhyz/](https://osf.io/preprints/socarxiv/3rhyz/3rhyz_v1)” should resolve to the most recent version of that preprint GUID, the same way that “[https://osf.io/preprints/socarxiv/3rhyz](https://osf.io/preprints/socarxiv/3rhyz/3rhyz_v1)” would.
redirect to explicit url in order to not add 3rhyz_v1 to the end of url and replace 3rhyz with 3rhyz_v1
https://github.com/user-attachments/assets/27b76207-77ea-4cfd-a206-d95c5d551774
Please make verification statements inspired by your code and …
=> [ENG-7338] fix some older preprint links fail to resolve post-versioned GUIDs

admin/providers/views.py, admin_tests/registration_providers/test_views.py, osf/models/user.py
fix re-adding the same user to providers as moderator/admin
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7297
=> [ENG-7297] Re-adding the same user to registration providers as moderator/admin creates duplicate records

api/preprints/views.py, api_tests/preprints/views/test_preprint_detail.py, api_tests/preprints/views/test_preprint_versions.py
The current `get_preprint` method filters preprints by `is_published = True` that is incorrect in case `pre-moderation` is enabled as in this case preprints have `is_published = False` but still should be visible by users
Fixed queryset, added tests
https://openscience.atlassian.net/browse/ENG-7460
=> [ENG-7460] Unpublished preprints in pre-moderation return 404

api/users/serializers.py, api/users/urls.py, api/users/views.py, api_tests/base/test_views.py, api_tests/users/views/test_user_settings.py, osf/models/user.py, website/language.py, website/settings/defaults.py
Added API view for handling reset password requests
Added view for handling reset password requests (both institutional and non-institutional)
Added serializer for reset password requests
N/A
v2/users/reset_password/?email=(email)&institutional=(bool default=False)
TBD
N/A
https://openscience.atlassian.net/browse/ENG-7298
https://openscience.atlassian.net/browse/ENG-7336
=> [ENG-7298][ENG-7336] Password Reset API 

admin/files/views.py, admin/templates/base.html
Allow file admin search if 'view_basefilenode' for user is set and user is not superadmin
Updated view and html permissions
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-6987?focusedCommentId=83742
=> [ENG-6987] feature/ENG-6987-updates-v1 set 'view_basefilenode' permission for admin files search

admin/base/utils.py, admin_tests/base/test_utils.py, osf/models/sanctions.py
Fix issue when registrations are not public once embargo ends
TBD
TBD
TBD
TBD
(https://openscience.atlassian.net/browse/ENG-7280)
=> [ENG-7280] Fix registrations not public after embargo

website/templates/project/project.mako
Connected preprints should not be revealed on projects when user views it via anonymous link (here preprint name is vbvs)
Added if statement that checks if it's anonymous link. Result:
https://openscience.atlassian.net/jira/software/c/projects/ENG/boards/145?assignee=712020%3A7c7368dc-40cb-475f-bae8-b07a8bd2dd6c&selectedIssue=ENG-4032
=> [ENG-4032] hide preprints for anonymous node

api/base/utils.py, api_tests/registrations/views/test_registration_list.py
When user's registration is spammed, it's still shown on the UI that causes 410 and 404 errors on `/schema_responses/` endpoint because `/registrations/` endpoint returns deleted registrations
Issue is that these registrations were spammed in some way. When it happens, `Registration` model calls `confirm_spam` method of `SpamOverrideMixin`
https://github.com/CenterForOpenScience/osf.io/blob/a9022a2cbd504bd296b7f848615f5802cc5a119b/osf/models/mixins.py#L2099-L2107
where we set only `self.deleted = now`, but `is_deleted` is not updated to `True`, thus it's `False`
However to form queryset on `v2/registrations/` we call `default_node_list_permission_queryset` method
https://github.com/CenterForOpenScience/osf.io/blob/a9022a2cbd504bd296b7f848615f5802cc5a119b/api/registrations/views.py#L157-L16 …
=> [ENG-7678] Remove deleted registrations from queryset

website/static/js/wikiMenu.js
fix displaying escaped characters in component pages wiki section
https://openscience.atlassian.net/browse/ENG-2477
=> [ENG-2477] "&" Symbol Appears as "&amp;” on for Component Titles on Wiki Sidebar

api/custom_metadata/views.py, osf/metadata/gather/focus.py, osf/metadata/osf_gathering.py, tests/identifiers/test_datacite.py
For all registrations that on the OSF Data Archive only, should have their resourcetype defaulted to dataset.
Possible workaround for the following ticket
https://github.com/CenterForOpenScience/osf.io/pull/11030#issuecomment-2738051489
Check if registration provider is 'dataarchive' and there is no set 'resourcetype', if yes - return 'resource_type_general'= 'Dataset' to Front End without saving it in database (show it for OSF provider not Dataarchive registration because did not succeed to set dataarchive locally)
https://github.com/user-attachments/assets/d8ada0e4-a585-46cd-8924-3e70d924269f
- Verify
- Verify
=> [ENG-7295] feature/ENG-7295-v2 return default 'Dataset' value of 'dataarchive registration without setting/saving it in database

api_tests/preprints/views/test_preprint_versions.py, osf/models/preprint.py
New preprint version must inherit contributors ordering from the latest version
Don't set creator as contributor by default for new preprint versions, so that we can clone contributors ordering
Tests to be added
https://openscience.atlassian.net/jira/software/c/projects/ENG/boards/145?assignee=712020%3A7c7368dc-40cb-475f-bae8-b07a8bd2dd6c&assignee=712020%3Ad159705f-dbae-4ef6-b510-8820829c5042&selectedIssue=ENG-7473
=> [ENG-7473] Fixed contributors ordering for new preprint versions

framework/exceptions/__init__.py, osf/features.yaml, tests/test_conferences.py, website/conferences/views.py, website/mails/mails.py, website/templates/emails/conference_deprecation.html.mako
Depreciate Meetings waffle flag
- Introduced ServiceDiscontinuedError to handle discontinued services.
- Added DISABLE_MEETINGS feature flag to control meeting interactions.
- Updated meeting_hook to raise ServiceDiscontinuedError when meetings are disabled.
- Implemented email notification for users attempting to use the discontinued meeting service.
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-7333
=> [ENG-7333] Depreciate Meetings waffle flag

admin/preprints/views.py, admin_tests/preprints/test_views.py, osf/models/preprint.py
`set_published` method checks if this action is performed by admin contributor, however admins in admin app should be able to perform this action without the permission
Handle this case with an additional parameter in method because if we add check like "if is_admin or is_admin_contributor" there may be a case when admin user opens preprint and publishes it via API that he shouldn't be able to do
https://openscience.atlassian.net/jira/software/c/projects/ENG/boards/145/backlog?assignee=712020%3A7c7368dc-40cb-475f-bae8-b07a8bd2dd6c&selectedIssue=ENG-7749
=> [ENG-7749] admin user can publish preprint in admin app even if he isn't a contributor

api/registrations/serializers.py, api/registrations/views.py, api_tests/registrations/views/test_registration_contributor_detail.py
Contributors ordering in registration metadata is not updated
`index` field is read only if we inherit from `NodeContributorsSerializer`. The new one `NodeContributorDetailSerializer` overrides this field to be editable and inherits from `NodeContributorsSerializer`
Also contributors ordering is different on registration metadata and metadata editing pages, thus it was fixed by adding the ordering attribute
Also added tests
https://openscience.atlassian.net/browse/ENG-7751
=> [ENG-7751] Fixed contributors reordering on registration metadata page

osf/metadata/serializers/google_dataset_json_ld.py, website/profile/utils.py, website/templates/base.mako, website/templates/project/project_base.mako
In metadata we return authors' names as full names. We should use this format instead: "{family name}, {given name}"
Also added givenName and familyName in JSON-LD schema
Updated function that generates names, added `given_name` attribute when serialize contributors in mako templates
https://openscience.atlassian.net/browse/ENG-7799
=> [ENG-7799] Update authors' names format in metadata

admin_tests/users/test_views.py, osf/models/user.py
When user has a deleted node where he is the only admin, osf admin can't gdpr delete this user because of this error
Ignore this message for deleted nodes. Added a test
https://openscience.atlassian.net/jira/software/c/projects/ENG/boards/145/backlog?assignee=712020%3A7c7368dc-40cb-475f-bae8-b07a8bd2dd6c&selectedIssue=ENG-7557
=> [ENG-7557] Ignore deleted nodes when do gdpr deletion in admin

api/preprints/serializers.py, osf/management/commands/fix_unclaimed_records_for_preprint_versions.py, osf/models/preprint.py, osf/models/user.py
Fix bug with citations for a new preprint version.
The problem was in the process of creating a version of the preprint, so also added the manage command to fix already created versions
Fix bug with citations for a new preprint version
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7263?atlOrigin=eyJpIjoiZjA0YjY0ZjM1MjkxNGQ2NGE3ZWNhYjhmMTMwM2NhM2YiLCJwIjoiaiJ9
=> [ENG-7263] Fix/eng 7263

admin/preprints/urls.py, admin/preprints/views.py, admin/static/js/preprints/preprints.js, admin/templates/preprints/assign_new_version.html, admin/templates/preprints/preprint.html, admin_tests/preprints/test_views.py, api/base/utils.py, api/preprints/serializers.py, osf/models/mixins.py, osf/models/preprint.py, website/files/utils.py
Add "Create new version 1" button on admin UI
- Add button to admin UI
- Extend existing preprint versioning functionality
- Move permission validation logic from serializer to model level to keep everything in one place
- add required_permission decorator (with ignore_permission functionality) that checks if user has enough permission to call method
[Screencast from 2025-04-22 14-43-05.webm](https://github.com/user-attachments/assets/83081f85-61fb-41ac-865b-e853f9d0d4db)
Expected behavior:
1. Admin goes the preprint admin page
2. Clicks "Create new version 1", a modal asking to choose date will be displayed
3. If date is valid and file versions exists:
- a new version 1 will be created
- admin user will be redirected to v1
- optionally, admin user can make new preprint published by …
=> [ENG-7716] Allow for reinstatement of previous preprint versions (with date uploaded) via the admin app

api/preprints/serializers.py, osf/management/commands/fix_unclaimed_records_for_preprint_versions.py, osf/models/user.py
Fix the error in the manage command
Remove useless parameter
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7263?atlOrigin=eyJpIjoiMjlhYWY5YjdmNmM2NDQ1N2JjYzBjMmE1MTZkODM1NTciLCJwIjoiaiJ9
=> [ENG-7263] Part 2

osf/management/commands/fix_unclaimed_records_for_preprint_versions.py, osf/models/user.py
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7263?atlOrigin=eyJpIjoiNDZkOGRiNDdkZjg2NDI5NGEwZGJmMDY1YTQzYzRkZjUiLCJwIjoiaiJ9
=> [ENG-7263] Fix/eng 7263 part 3

docker-compose.yml
Migrate WaterButler to Poetry for dependency management
- Verify
- Verify
[ENG-7729](https://openscience.atlassian.net/browse/ENG-7729)
[ENG-7729]: https://openscience.atlassian.net/browse/ENG-7729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENG-7729] | migrated WaterButler to Poetry for dependency management

api/actions/views.py, api_tests/actions/views/test_action_list.py
Fix's a 502 that happened when the permission's class hit a NoneType target id
- improves tests
- adds validation for target ids
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7810
=> [ENG-7810] improve action requests creation

admin/users/views.py, osf/management/commands/deactivate_requested_accounts.py, osf/models/mixins.py, osf/models/user.py
fix broken users
- do not unregister users when deactivate spam
How I was able to recreate it:
In admin go to managment commands -> Ban spam users by regular expression and ban some users (Actually there may be other ways to recreate it using spam feature in different ways like management commands, scheduled spam checks and so on). They will become unregistered, disabled and confirmed. Then we can reactivate account in admin to make it enabled but not registered
https://openscience.atlassian.net/browse/ENG-7704
=> [ENG-7704] Accounts confirmed but not Registered

api/institutions/serializers.py, api_tests/institutions/views/test_institution_user_metric_list.py
Admins should be able to see number of messages that each admin sent to the same user
Added contact property, added a test and fixed existing ones
Contacts are ordered alphabetically
Additional scope: this property was added in export files as well
https://openscience.atlassian.net/jira/software/c/projects/ENG/boards/145
=> [ENG-7858] Return number of contacts messages of institutional admins

admin/management/views.py, admin/templates/management/commands.html, osf/management/commands/sync_doi_metadata.py
Admins should be able to resync preprints without minted doi with Crossref instead of all preprints.
1. Added check mark for syncing only preprints without minted DOI. Fixed text coloring that has red background and red text color
2. Improved retry functionality for sync_identifier_doi task
3. Created a new celery task to resync preprints missing DOI and after that exclude all preprints from identifiers queryset
https://openscience.atlassian.net/browse/ENG-7879?atlOrigin=eyJpIjoiZWRiM2Q0ZWI4YzZlNGRlOTg5NDMzMmRjZWQ5YjQ2NjkiLCJwIjoiaiJ9
=> [ENG-7879] Ability to resync preprints that have missing doi with Crossref

admin_tests/preprints/test_views.py, osf/models/preprint.py
Share update is not called when user withdrawals preprint and updates `date_withdrawn` and `withdrawal_justification` fields
Updated SEARCH_UPDATE_FIELDS, added a test
https://openscience.atlassian.net/jira/software/c/projects/ENG/boards/145?assignee=712020%3A7c7368dc-40cb-475f-bae8-b07a8bd2dd6c&assignee=557058%3A5fafb22b-df22-41bd-8ed5-d7701be68048&selectedIssue=ENG-5037
=> [ENG-5037] Call share update on preprint withdrawal

framework/auth/views.py
This isn't actual solution, just a way to handle error as it isn't reproducible locally, potentially because of smtp that is not used locally
Added exception handler, swapped sync call for async version
https://openscience.atlassian.net/browse/ENG-6206?atlOrigin=eyJpIjoiMjQ1MDJjNmEwMDlkNDFlM2E5MTBhOTA4MWViY2NkNTciLCJwIjoiaiJ9
=> [ENG-6206] Try to handle an unknown error for async email confirmation

admin/collection_providers/forms.py
Admins should be able to remove collections options without any restrictions
Removed validation
https://openscience.atlassian.net/browse/ENG-7871?atlOrigin=eyJpIjoiZWJmZDUxZDM1YTZlNGZiNGFiNTBmMjZhZDVmNDhhZGQiLCJwIjoiaiJ9
=> [ENG-7871] Removed restrictions that prohibit options deletion

osf/management/commands/force_archive.py, osf/models/mixins.py, osf/models/user.py, osf_tests/test_node.py
fix was_public state when flag spam
- correct check if node was public when flag_spam
- use earliest confirm/flag spam log to check if node was public instead of the latest one
---
- fix TypeError when check archiving status for stuck registrations (not related to ticket ENG-7873, but it's just one line `permissible_addons = set(permissible_addons)`, so no additional testing is required)
I couldn't reproduce this issue via UI, but combination `confirm_spam()` -> `flag_spam()` -> `...` breaks this feature. I'm not sure if it's exactly what's happening in our case, but since `flag_spam()` is used with automatic spam checks during node/preprint updates, it's quite possible.
https://openscience.atlassian.net/browse/ENG-7873
=> [ENG-7873] CLONE - SPAM - When Hamming a Spammed user, preprints and registrations remain private

osf/models/node.py, scripts/embargo_registrations.py
Embargo termination logging doesn't provide useful info regarding of what error was raised
Improved logging, removed if statement duplicate
https://openscience.atlassian.net/browse/ENG-7927?atlOrigin=eyJpIjoiZDJkYTQ3MjdmN2UxNDBjYmIzMDg1YzVhNmI4ZjMzMWQiLCJwIjoiaiJ9
=> [ENG-7927] Improved logging for embargo termination

admin/nodes/urls.py, admin/nodes/views.py, admin/templates/nodes/node.html, admin/templates/nodes/registration_provider.html, osf/models/registrations.py
allow admins change registration providers
- add a dropdown menu to provider section on admin UI
- add endpoint that allows to update registration provider
https://openscience.atlassian.net/browse/ENG-7977
=> [ENG-7977] Add ability for admin app to change registry that a registration belongs to

api/base/filters.py, api_tests/base/test_filters.py, api_tests/subscriptions/views/test_subscriptions_list.py
Query params filters were limited to handle multiple values starting from this commit https://github.com/CenterForOpenScience/osf.io/commit/6fd196821736c71566b50545f8bf1d83ecdb211e for these fields only: `_id`, `guid._id`, `journal_id`, `moderation_state`. Over time this list have been updated to these four values. Now all filter classes that inherit from `FilterMixin` support this feature.
In order to filter by multiple values, FE should use the following syntax:
`?filter[title]=text1,text2`
Filter uses OR operator for its values while filters use AND operator between themselves
1. Updated if statement to support multiple values for all fields
2. Also when one value was passed for any of the fields above, it was processed as a list. Now operator update was removed for `id` field in …
=> [ENG-8052] Fixed FilterMixin issue with multiple values of any filter

api/users/serializers.py, api/users/urls.py, api/users/views.py, api_tests/base/test_views.py, api_tests/users/views/sanction_response/test_user_sanction_response.py, api_tests/users/views/sanction_response/test_user_sanction_response_embargo.py, api_tests/users/views/sanction_response/test_user_sanction_response_embargo_termination.py, api_tests/users/views/sanction_response/test_user_sanction_response_registration_approval.py, api_tests/users/views/sanction_response/test_user_sanction_response_retraction.py, api_tests/users/views/test_user_confirm.py, framework/auth/oauth_scopes.py, osf/models/sanctions.py, osf/utils/tokens/__init__.py, osf/utils/tokens/handlers.py, tests/test_registrations/test_embargoes.py, tests/test_registrations/test_retractions.py, tests/test_tokens.py, website/language.py
Update the alternate email confirmation system to v2
- adds `/users/<user_id>/confirm/` route with views
- adds tests
- adds `/users/<user_id>/sanction_response/` route with views
- adds tests
- cleans-up and simplifies sanction_handler code to work better in different request contexts
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7965
=> [ENG-7965] Add v2 email token confirmation endpoints

api/users/views.py, api_tests/users/views/test_user_confirm.py
If user email already existed the error was uncaught.
- adds change to catch 400 error 
- adds test case.
- Verify
- Verify
=> Fix user confirm email already exists

api_tests/preprints/views/test_preprint_list.py, api_tests/registrations/views/test_registration_list.py
Add unittests for manual guid and doi asignment
- Verify
- Verify
=> [ENG-8185] Unit tests for Manual GUID and DOI

osf/management/commands/check_crossref_dois.py, osf/models/preprint.py, tests/identifiers/test_crossref.py, website/identifiers/clients/crossref.py, website/preprints/tasks.py
do not mint _v1 doi if legacy one exists
- make sure that CrossrefClient works well with legacy DOIs
- don't send request to crossref when check_crossref_dois if no DOIs were selected
- check only published preprints when mint_doi_on_crossref_fail
https://openscience.atlassian.net/browse/ENG-7870
=> [ENG-7870] Crossref DOIs not minting with _v1, OSF is displaying DOI versions with _v1

osf/models/node.py
`_get_addon_from_gv` iterates through None when service is not found in `_get_addons_from_gv_without_caching`
Replace None by an empty list
=> [ENG-8048_2] fixed None issue during iteration

api/preprints/views.py, api_tests/preprints/views/test_preprint_detail.py
User should be able to delete draft preprints, so that we don't save them in database
Added `delete` method.
User can delete a preprint only if it's in initial state, so it means this preprint is a draft
https://openscience.atlassian.net/browse/ENG-8247?atlOrigin=eyJpIjoiYzdkN2MwNDU5N2NkNDk5ZmI5Y2FmYWE0MDFkNTVjYTciLCJwIjoiaiJ9
=> [ENG-8247] Ability to delete draft preprints from database

admin/templates/users/user.html
add more information to user admin
Added fields:
- id
- Deactivation request
- Change password last attempt
- Change password invalid attempts
- Socials
- User is staff
- Groups
Added dates to:
- Disabled
- Registered
- Confirmed
https://openscience.atlassian.net/browse/ENG-8190
=> [ENG -8190] Update admin display of users to be more useful

website/archiver/tasks.py
User received an email of archive failure regardless of it was successful. It may happen because `archive_success` is run asynchronously
https://github.com/CenterForOpenScience/osf.io/blob/2328dd60f55e9c1281dcb29dcd45a78a7fd2cc5f/website/archiver/listeners.py#L33-L49
and may be finished before the main thread finishes archiving process. So at first `archive_success` is processed and no files found, thus email is sent, then the main thread finishes files processing and this archiving is successful actually.
Also it's possible that the celery queue had too many tasks to process and when the main thread finishes archiving, user sees his registration and when celery processes `archive_success` tasks that fails, user receives this email.
Added a one-time retry. …
=> [ENG-8175] Fixed potential race condition

admin/templates/nodes/contributors.html, admin/templates/nodes/node.html
fix content overflow on the node admin page
https://openscience.atlassian.net/browse/ENG-8063
=> [ENG-8063] Registrations in admin tables sometimes go out of the frame of the browser window

admin/nodes/views.py, admin/templates/nodes/node.html
Admin templates used nonexistent fields to display children and parent of a node (potentially new fields were added but the old fields weren't replaced by new ones). The templates used `parent` and `children` fields. However an endpoint that adds children and parent to a node uses fields `descendants` (or through `NodeRelation` using `get_nodes` method) and `parent_node` property through `_parents` field
Use correct fields
Deletion of children nodes that are displayed now is broken. Together with Mark decided to create a separate ticket for this issue
https://openscience.atlassian.net/browse/ENG-7969?atlOrigin=eyJpIjoiMGNhZWZhMWM4ZmM2NGNlM2E4ZDQ0OTg1ZjgyZmI1NGEiLCJwIjoiaiJ9
=> [END-7969] Fixed children/parent relationships in admin templates

api/users/serializers.py, api_tests/users/views/test_user_settings_detail.py, osf/management/commands/update_mailchimp_email.py, osf/models/user.py, scripts/fix_user_mailchimp.py, tests/test_configure_mailing_list_view.py, tests/test_mailchimp.py, tests/test_user_profile_view.py, website/mailchimp_utils.py, website/profile/views.py
Correct issues where PATCH responses wouldn't show preferences as updated due to async mailchimp task execution. Overrides instance model to return changed value, even though db value is unchanged until mailchimp confirms.
- adds special case for returning desired value synchronously 
- removes `update_osf_help_mails_subscription` because it's not used, but tested.
- adds test cases
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7962
=> [ENG-7962] Fix User Setting Response Payload async mailchimp perference change issues

api/base/serializers.py, website/views.py
Throughout registration creation user can view attached files. However `resolve_guid` doesn't handle this case and renders the legacy UI that shows error because `get_rdf_type` raises `NotImplementedError`. So this case has no be handled by ember. However when we switch to the new UI, we get `draftnode is not a supported target type`. Also there will be some work for FE because for now ember relies on `node` relationship that draft node/registration don't have. Taking into account Futa's words, it's an unusual flow for ember
Added redirect to ember, updated `view_map` that referenced to the non-existing view `draft_nodes:node-detail` to use `draft_nodes:draft-node-detail` view
1. I'm not confident that `draft-node` key is still used in `view_map`. From the `resolve` method of …
=> [ENG-5810] Switch to new UI when user views draft registration file

.github/workflows/test-build.yml, api_tests/mailhog/test_mailhog.py, conftest.py, docker-compose.yml, osf/features.yaml, pytest.ini, tasks/__init__.py, website/mails/mails.py, website/settings/defaults.py, website/settings/local-ci.py, website/settings/local-dist.py
TBD
TBD
TBD
TBD
TBD
https://openscience.atlassian.net/browse/ENG-8172
=> [ENG-8172] Improve email testing

osf/management/commands/sync_doi_metadata.py, website/identifiers/clients/crossref.py, website/identifiers/clients/exceptions.py, website/preprints/tasks.py, website/settings/defaults.py
CrossRef will be unavailable for 24 hours, so we handle it and do a few retries in 24 hours
Handle 500 error
So, in most cases we make a request to CrossRef via one of these methods:
`create_identifier`
`update_identifier`
`request_identifier_update`
`request_identifier`
Actually everything comes to `create_identifier` call
For now if crossref returns any status code besides `429` (rate limit), we don't show users any errors because crossref returns them via email.
Now we handle 500 error from crossref in celery tasks that already have retry in case of other errors. (all of them call `request_identifier_update`)
However what should we do with cases when `create_identifier` is called synchronously?
From one side we can make this method to call another celery task that will have retry.
On …
=> [ENG-8321] Handle 500 error from crossref

admin/maintenance/views.py, admin_tests/maintenance/test_views.py
Admins were not able to delete maintenance alerts because success_url was not set on backend. Also incorrect (`delete`) method was overridden as `BaseDeleteView` uses `post` method instead) so the deletion logic has never worked correctly
Added success_url for a correct redirection that caused 502
Fixed overridden method
https://openscience.atlassian.net/browse/ENG-8246
=> [ENG-8246] Fixed deletion of maintenance alerts in admin

admin/templates/nodes/children.html
Privacy of child nodes was not displayed.
Use correct attribute to display privacy of child nodes
https://openscience.atlassian.net/browse/ENG-8325?atlOrigin=eyJpIjoiNjBmODI2ZmRlYWNjNDJiNDgxYzk0MTZhMzQ4MjFmMDYiLCJwIjoiaiJ9
=> [ENG-8325] Fixed displaying of privacy of child nodes in admin

admin/nodes/views.py, admin/templates/nodes/registration_force_archive_form.html
Product team reported that they cannot force archive registration because of this error:
`["7t6qj: Original node zts5b has addons: ['osfstorage', 'wiki', 'github', 'zotero']`
It happens due to not all configured addons are displayed and selected in the template that is required to archive a registration
For example this registration has zotero and github addons that aren't displayed because we fetch addons from registration, not from it's parent node
Implicitly fetch addons so that admins shouldn't select them.
Fixed passed params issue
Hide addons from the template (agreed with Blaine)
Nothing was changed in force archive logic, but I encountered one bug related to function params that was fixed as well (as configurable addons have never been displayed, this flow couldn't be really …
=> [ENG-8224] Fixed force archive template with registration addons

api/providers/serializers.py, api_tests/providers/collections/views/test_collection_provider_detail.py
Add brand relations to collection provider like the registration and preprint provider. 
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-8320
=> [ENG-8320] Add Brand relationship to Collection Provider

api/base/filters.py, api/preprints/serializers.py
Angular team needs the ability to filter preprints by tags
Make `tags` field filterable
Use `ListFilterMixin` behavior to process this field
https://openscience.atlassian.net/browse/ENG-8396?atlOrigin=eyJpIjoiNTQxYjM2MTA1MmY3NDE1M2I5ZDMxOTNhMzg0OTcyY2UiLCJwIjoiaiJ9
=> [ENG-8396] Enable filtering preprints by tags

framework/email/tasks.py, tests/framework_tests/test_email.py
fix categories for sendgrid emails
- fix categories
- don't send sendgrid request if email was not parsed
https://openscience.atlassian.net/browse/ENG-7725
=> [ENG-7725] CLONE/Recurring - Preprint Emails Not Being Sent as Expected

api/base/views.py, api/nodes/serializers.py, api/registrations/views.py, api_tests/registrations/views/test_registrations_childrens_list.py, osf/models/node.py, osf/models/provider.py, osf/models/registrations.py, osf/utils/workflows.py
fix registration children visibility and count for non-contributor moderators
- extend get_node_count() sql to include pending registrations if user is moderator
- add custom_filters to AbstractNode.can_view() method to include not only public nodes
https://openscience.atlassian.net/browse/ENG-7979
=> [ENG-7979] Registrations pending moderation that have components also pending moderation do not display the children

admin/institutions/urls.py, admin/institutions/views.py, admin/management/views.py, admin/templates/institutions/detail.html, admin/templates/management/commands.html, admin_tests/institutions/test_views.py, api/institutions/views.py, osf/management/commands/monthly_reporters_go.py, osf/metrics/reports.py
create monthly reports when institution is created
- create institution when it's created
- add button to create report for institution in the admin
- fix most_recent_yearmonth when no reports are available
https://openscience.atlassian.net/browse/ENG-8462
=> [ENG-8462]  Institution setup fixes

api/users/views.py, api_tests/users/views/test_user_settings.py
remove csrf protection from reset password endpoint
https://openscience.atlassian.net/browse/ENG-8514
=> [ENG-8514] Remove CSRF protection from reset password api v2 POST

addons.json, addons/azureblobstorage/apps.py, addons/azureblobstorage/models.py, addons/base/views.py, api/base/settings/defaults.py
Implement BaseFileNode for azure blob storage so that the addon view can successfully resolve file class and redirect request
- Implement BaseFileNode for azure blob storage
- Get auth user from cookie if auth is not exist in kwargs 
- Verify
- Verify
NII Implementing Features in Legacy OSF Add-ons using BaseFileNode for hackason
[#49](https://github.com/CenterForOpenScience/community/issues/49)
=> Implement BaseFileNode for azure blob storage

api/preprints/serializers.py, api/preprints/views.py
- Verify
- Verify
https://openscience.atlassian.net/browse/ENG-7277?atlOrigin=eyJpIjoiMGYxMDIwNTBlYjFkNDMwZWEyMzY1YTRmMTAyMDUxNzgiLCJwIjoiaiJ9
=> [ENG-7173] Update doc to include version as relationship

api/users/serializers.py, api_tests/users/views/test_user_settings_detail.py
`subscribe_osf_general_email` setting is not updated
Added user record reload in the serializer.
This attribute is indeed updated within `mailchimp_utils.subscribe_mailchimp` call but when we return back to the serializer, this update is lost. I assume it happens because `mailchimp_utils.subscribe_mailchimp` fetches user instance with `OSFUser.load()` that updates user but the serializer works with the old version of this user.
Moving `user.reload()` to `mailchimp_utils.subscribe_mailchimp` doesn't fix the issue, while adding
`instance.mailchimp_mailing_lists[MAILCHIMP_GENERAL_LIST] = True` in the serializer fixes it that confirms my assumption above.
https://openscience.atlassian.net/browse/ENG-8743
=> [ENG-8743] subscribe_osf_general_email settings is not updated

api/institutions/views.py
=> [ENG-8519] remove deleted users from institutional dashboard

api/nodes/serializers.py, api_tests/nodes/views/test_node_view_only_links_list.py, api_tests/registrations/views/test_registration_view_only_links_list.py
Components are ignored when user creates a view-only link and includes components
https://openscience.atlassian.net/browse/ENG-8742?atlOrigin=eyJpIjoiYjg1ZGE2MzI3YjMyNGE2YWFiMDYyOGMyMjQyOTJhYmYiLCJwIjoiaiJ9
=> [ENG-8742] include ignored components when create a view-only link

admin/providers/views.py, admin_tests/registration_providers/test_views.py, api_tests/mailhog/provider/test_registration_provider_moderator.py
add PROVIDER_MODERATOR_ADDED email
See diff
N/A
N/A
N/A
https://openscience.atlassian.net/browse/ENG-8830
=> [ENG-8830] PROVIDER_MODERATOR_ADDED email

framework/auth/views.py, osf_tests/test_merging_users.py, website/templates/confirm_merge.html.mako
Make a send notification when a user's account is merged
Make a send notification when a user's account is merged
TBD
TBD
TBD
(https://openscience.atlassian.net/browse/ENG-8869)
=> [ENG-8869] Fix/make send email on account merge

api/users/serializers.py, api_tests/users/views/test_user_settings.py
Make send email when the primary email changes
Make send email when the primary email changes
TBD
TBD
TBD
(https://openscience.atlassian.net/browse/ENG-8872)
=> [ENG-8872] Fix/no notification send when primary email changed

framework/auth/views.py, osf/models/notification_subscription.py, osf/models/notification_type.py, osf_tests/test_merging_users.py
Stops issue with merged and confirmed users getting subscriptions which pointed to old users.
- Doesn't create a subscription for confirming accounts
- fix template typo
TBD
N/A
N/A
https://openscience.atlassian.net/browse/ENG-8978
=> [ENG-8978] Fix issue with user confirmation/merger creating subscription

api/base/serializers.py, api_tests/nodes/views/test_node_list.py
Requests from the legacy OSF can be processed by any backend regardless of a host of the backend
Added legacy host url for htmls of legacy OSF
https://openscience.atlassian.net/browse/ENG-9020?atlOrigin=eyJpIjoiYTMzN2QwOGNhYTFjNDQ0NmE0YjA5N2M1ZTBmZmM0ZjgiLCJwIjoiaiJ9
=> [ENG-9020] Custom html host for legacy OSF

api/preprints/serializers.py, osf/models/contributor.py
validate only changed permission
https://openscience.atlassian.net/browse/ENG-9021
=> [ENG-9021] If user is not a bibliographic contributor they do not have full admin permissions
